### ISSUE TITLE
Introduce support for class-scoped parameters

### ISSUE THREAD

**Issue by kcooney** [junit-team/junit5#1006]
## Overview

Provide a way to have values injected into a class that are created once before any test methods are created.

If your test class has constructor with a parameter annotated with `@PerClass`, then JUnit Jupiter will create it once per run of the test class, using the default constructor of the class (in Kotlin, the primary constructor). That class can have non-static methods annotated with `@BeforeAll`, `@AfterAll`, `@BeforeEach`, or `@AfterEach`.

Here's an example of a class that creates a local database:

```java
    @PerClass
    public class Database {
        @BeforeAll void createDatabase() {
        }
 
        @AfterAll void dropDatabase() {
        }

        @BeforeEach void clearDatabase() {
        }

        public void insert(long id, Account) }{
       }
    }

    class DatabaseTestCase {
      private final Database db;

      DatabaseTestCase(@PerClass Database db) {
        this.db = db;
      }

      @Test
      public void insertAccount() {
        Account account = ...
        db.insert(1, account);
        ...
      }
    }
```

You could think of this as a better version of JUnit4's `ExternalResource` rule.

This could also be used to support `@BeforeAll` in Kotlin tests

```kt
    class SimpleKotlinTestCase constructor(@PerClass db: Database) {
      class Database {
        @BeforeAll fun createDatabase() {
        }
 
        @AfterAll fun dropDatabase() {
        }

        @BeforeEach fun clearDatabase() {
        }

        fun insert(id: Int, account: Account) {
        }
      }

      @Test
      fun insertAccount() {
        val account = ...
        db.insert(1, account);
        ...
      }
    }
```

This could also be used to support integration tests.

## Deliverables

- [ ] ?

**Comment by sbrannen** [comment]
Updated title and description.

**Comment by sbrannen** [comment]
FYI: developers and third parties can already achieve comparable functionality via a custom extension that implements `BeforeAllCallback`, `AfterAllCallback`, `BeforeEachCallback`, `AfterEachCallback`, and `ParameterResolver`.

With that in mind, I'm not convinced that JUnit Jupiter should implement such a feature itself.
