### ISSUE TITLE
CsvSource with empty strings instead of null

### ISSUE THREAD

**Issue by michaelsiepmann** [junit-team/junit5#1014]
## Overview

When I add the following `CsvSource` to a test

```java
@CsvSource({",''", "'',''", "text1,text2"})
void teaserText(String source, String expected) {
}
```

I would expect, that 

- in the first step `source` is `null`, and `expected` is an empty string.
- in the second step both are empty strings.
- in the third step `source` is `text1`, and `expected` is `test2`.

but two single quotes without any content inside are parsed as `null`.

How can one create an empty string?

**Comment by sormuras** [comment]
The `emptyValue` attribute is not set in `CsvArgumentsProvider` -- it defaults to `null`.

We could configure the internal `CsvParserSettings` with `settings.setEmptyValue("");`.

@junit-team/junit-lambda Thoughts?

**Comment by sormuras** [comment]
Current implementation:
`parse("null , , empty , ''")` yields `"null", null, "empty", null` 

With `setEmptyValue("")`:
`parse("null , , empty , ''")` would result in `"null", null, "empty", ""`

**Comment by sbrannen** [comment]
My understanding was that one could specify an _empty string_ by supplying two adjacent single-quotes.

So, if that's not the case, then I am for changing the configuration to make it so.
