### ISSUE TITLE
Level of documentation in the JavaDoc

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1021]
## Overview

Copied comment from @smoyer64  in #1014:

> Looking at the section of the users guide for parameterized tests, there's a lot of great information which is exactly the sort of thing I'd like to see when my IDE pops up the javadocs for @CsvSource. Unfortunately, those javadocs simply link back to the users guide for the important stuff.

> I do think it's important to have a good users guide for those who are jumping into junit5 but I believe that those who are heavy users will appreciate the javadocs being complete and stand-alone. It's a lot more work to keep up-to-date if the information is in both places but I believe for things like this, it's important - kind of like date and regex format descriptions in the Java SE javadocs.

## Deliverables

- [ ] Enhance Javadoc with more details, examples and other "important stuff"

**Comment by sormuras** [comment]
Closing this issue as a duplicate of #1022

**Comment by smoyer64** [comment]
@sormuras - Sorry about that ... I should have refreshed my notifications before adding the last comment to #1014 and creating #1022.  I wouldn't have been insulted if you'd closed mine as the duplicate (it was after all five hours late).

**Comment by sormuras** [comment]
No problem at all! Your issue started with a real description ... mine was just a copy-n-paste draft as a reminder of the topic.
