### ISSUE TITLE
Document code or automatically configure Jacoco with Junit 5 Gradle Plugin

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-team/junit5#1024]
## Feature (or Documentation) Request
Should the Junit 5 plugin automatically configure the `junitPlatformTest` task to use Jacoco if it detects the plugin?

Currently configuring jacoco with Junit 5 requires a bit of digging into the DSL and figuring out its intricacies.

Perhaps configure the Junit5 plugin should be expanded to have a `enableJacoco` flag that will add a `jacocoJunit5TestReport` task if set to `true`? What are the teams thoughts?

### Current solutions

Anyone looking to configure jacoco with Junit 5 using the new [Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl) you currently need to use a bit of a workaround because of a kotlin compiler bug. This code is known to work with Gradle 4.1

```kotlin
// Don't use this sample, see below
afterEvaluate {
    val junitPlatformTest by tasks
    jacoco {
        applyToHelper(junitPlatformTest)
    }
    task<JacocoReport>("jacocoJunit5TestReport") {
        executionData(junitPlatformTest)
        sourceSets(java.sourceSets["main"])
        sourceDirectories = files(java.sourceSets["main"].allSource.srcDirs)
        classDirectories = files(java.sourceSets["main"].output)
    }
}

/**
 * Workaround fix for calling [org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyTo]
 *
 * [Issue details here](https://github.com/gradle/kotlin-dsl/issues/458)
 */
fun org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyToHelper(task : Task) {
    val method = this::class.java.getMethod("applyTo", Task::class.java)
    method.invoke(this, task)
}
```

**EDIT**

Better solution with less code:
```kotlin
afterEvaluate {
    val junitPlatformTest : JavaExec by tasks
    jacoco {
        applyTo(junitPlatformTest)
    }
    task<JacocoReport>("jacocoJunit5TestReport") {
        executionData(junitPlatformTest)
        sourceSets(java.sourceSets["main"])
        sourceDirectories = files(java.sourceSets["main"].allSource.srcDirs)
        classDirectories = files(java.sourceSets["main"].output)
    }
}
```

## Deliverables

- [ ] Documentation about how to configure Jacoco with Gradle or add code to the plugin to do it automatically

**Comment by marcphilipp** [comment]
IIRC Currently, the Jacoco plugin hooks into the test task. Could it be extended to support junitPlatformTest (at least until Gradle provides core support for the new JUnit platform)?

**Comment by alixwar** [comment]
@JLLeitschuh Do you know of a known workaround for Gradle Java?

My attempt, https://stackoverflow.com/questions/46233314/gradle-android-jacoco-and-junit5/46298696#46298696, unfortunately only results in code coverage data for JUnit4 tests

**Comment by JLLeitschuh** [comment]
Does the android plugin do something special for testing? I'm not totally certain because I've never done anything with it.

I guess my first question is can you get the junit 5 plugin to correctly execute your tests? Once you have that working the above should work.
If you need the same logic but for groovy I can provide an example of that if it would help.

**Comment by alixwar** [comment]
@JLLeitschuh I have  done the following for each submodule in the project:

```
project.afterEvaluate {
    apply plugin: "jacoco"
    jacoco {
        applyTo junitPlatformTestDebug
    }
}:
```

This is enough to generate code coverage for JUnit4 tests (inluding tests run by MockitoJUnitRunner) but not JUnit5 tests or Robolectric tests

**Comment by mannodermaus** [comment]
> Does the android plugin do something special for testing?

As opposed to the Gradle plugin for JUnit 5 provided by the junit5 team? It basically only extends its core functionality with the variant-awareness that Android projects have. Instead of adding just a single `junitPlatformTest` task, the android-junit5 plugin applies a task per variant, `junitPlatformTestDebug` & `junitPlatformTestRelease`, while also taking care of potential product flavors.

**Comment by alixwar** [comment]
@JLLeitschuh Any thoughts on the explanation from @mannodermaus ? Is there something that I or someone else can do to help clarify the issue?

**Comment by JLLeitschuh** [comment]
I don't work with any projects that use gradle for building android projects. I'm assuming that as long as you can get your android tests to run correctly using the `junitPlatformTest` task then the code snippet that I have provided should work.

If you have specific behaviour problems that you are experiencing then I may be able to help. At the moment I'm not totally certain I understand what the problem is.

**Comment by mannodermaus** [comment]
As discussed over at https://github.com/mannodermaus/android-junit5/issues/4, the latest SNAPSHOT release of the Android-based plugin for JUnit 5 implemented the first iteration of support for Jacoco out of the box, so there's nothing to be done from this side in that regard.

As for the Java-based JUnit 5 Gradle plugin, it could be a nice improvement to apply the code snippet for Jacoco integration directly through the plugin in a future release. [In the android-junit5 plugin](https://github.com/mannodermaus/android-junit5/blob/a16af5a2b8d080d600fabb9ec3bcd27c7f7fe383/android-junit5/src/main/groovy/de/mannodermaus/gradle/plugins/android_junit5/AndroidJUnitPlatformPlugin.groovy#L121), I'm conditionally extending each JUnit 5 task with a corresponding Jacoco reporting task only if the plugin is found to exist in a module.

**Comment by alixwar** [comment]
I'm happy to report that from my perspective the issue with JUnit5 is resolved on Android. It works fine with the latest snapshot release of the plugin.

**Comment by alixwar** [comment]
@JLLeitschuh I've created a sample project in the android plugin that illustrates the remaining issue (four different type of unit tests, three with working coverage): https://github.com/mannodermaus/android-junit5/pull/18

I realize that this is more of a problem for the Robolectric project (I've reported it here: https://github.com/robolectric/robolectric/issues/3397) but if any of you guys, who know much more about this than I, could take a quick peek and pin point what seems to be wrong it would be easier for someone else to make a pull request and fix the issue in the Robolectric project so that there is a workaround for all the Android projects out there to start using JUnit5.

**Comment by domhauton** [comment]
@JLLeitschuh 's solution worked but the idea groovy linter wasn't too happy. This was my final solution.

For Gradle 4.4.1
```
apply plugin: 'jacoco'

afterEvaluate {
    def junitPlatformTestTask = (JavaExec) project.tasks.getByName('junitPlatformTest')

    jacoco {
        applyTo(junitPlatformTestTask)
    }

    project.task(type: JacocoReport, "jacocoJunit5TestReport") {
        executionData(junitPlatformTestTask)
        sourceSets(sourceSets.main)
        sourceDirectories = files(sourceSets.main.allSource.srcDirs)
        classDirectories = files(sourceSets.main.output)

        reports {
            xml.enabled true
            xml.destination file("${buildDir}/jacoco/report.xml")
            html.enabled true
            html.destination file("${buildDir}/jacoco/html")
        }
    }

    check.dependsOn jacocoJunit5TestReport
}
```

**Comment by Thunderforge** [comment]
@domhauton Is there a better solution now that [Gradle 4.6 is out](https://docs.gradle.org/4.6/release-notes.html) with a new way of handling JUnit 5?

**Comment by sormuras** [comment]
@Thunderforge I guess, with Gradle 4.6 and `useJUnitPlatform()` you can use the [JaCoCo plugin](https://docs.gradle.org/current/userguide/jacoco_plugin.html) as-is.

**Comment by marcphilipp** [comment]
Since Gradle now provides [native support](https://docs.gradle.org/4.6/release-notes.html#junit-5-support) for running tests on the JUnit Platform, JaCoCo should work without any extra configuration. We've decided to deprecate our custom plugin (see #1317 for details) and not add any new features to it. Thus, I'm closing this issue.
