### ISSUE TITLE
Introduce @SuiteDisplayName in the platform suite API

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1036]
## Overview

Inspired by a discussion in [Gitter](https://gitter.im/junit-team/junit5?at=59a6e35f8f4427b462b5b48a), it would be useful to introduce a new `@SuiteDisplayName` annotation in the `org.junit.platform.suite.api` package.

Note that we cannot re-use `@DisplayName` since it is particular to the JUnit Jupiter API.

## Deliverables

- [x] Introduce `@SuiteDisplayName` annotation in the `org.junit.platform.suite.api` package.
- [x] Update the `JUnitPlatform` runner to use the user-supplied display name for the suite if `@SuiteDisplayName` is declared on the test class.
- [x] Update the User Guide.
- [x] Update the release notes.

**Comment by sormuras** [comment]
1. We're very(!) late in the GA process -- I know, it's only a name, what could possibly go wrong?! Target 5.1?
2. What about moving `@DisplayName` to the platform (commons)? (We're late in the GA process applies here too...) ;)

**Comment by sbrannen** [comment]
> 1. We're very(!) late in the GA process -- I know, it's only a name, what could possibly go wrong?! Target 5.1?

Well, TBH, I don't foresee that much (if anything) _could go wrong_. 😉 

But I of course understand the concern about introducing a new _feature_ immediately before the 5.0 GA release.

With that in mind, one option would be to introduce the `@SuiteDisplayName` annotation in 5.0 GA -- so that third parties could make use of it immediately if desired -- but move the implementation of the support for the annotation in the `JUnitPlatform` runner to 5.1.

> 2. What about moving `@DisplayName` to the platform (commons)?

I don't think that would be a good idea: although both annotations would currently only support a `value` attribute for setting the name, we cannot predict the future. Consequently, in order to allow for the possibility that the annotations need additional (perhaps competing) attributes in the future, my vote would be to keep them separate.

**Comment by sbrannen** [comment]
FYI: initial work for this issue has been pushed to the following branch:

https://github.com/junit-team/junit5/tree/issues/1036-suite-display-name

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
All necessary work has been pushed to `master`.
