### ISSUE TITLE
Cache downloaded dependencies with Travis CI

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-team/junit5#1037]
## Overview

The travis builds could be faster if they used the build cache. This would simply store the dependencies of the build so that they don't have to get re-downloaded for ever build.

https://docs.travis-ci.com/user/languages/java/#Caching

## Deliverables

- [ ] Add dependency caching to travis config

**Comment by sormuras** [comment]
We removed the caching with https://github.com/junit-team/junit5/commit/10a74b9d9f9e416e3cd27ff689d24415d6e19d72

Maybe now it is faster and the problems with updated versions vanished.

**Comment by sormuras** [comment]
See https://stackoverflow.com/questions/42992699/how-does-travis-ci-cache-gradle-dependencies for some more details.

**Comment by JLLeitschuh** [comment]
The only way that I'd be able to test this is by turning on travis on my own fork (which I totally can do).
I just noticed that there was a significant amount of time that gradle spent downloading dependencies when testing my build for JDK 9.

**Comment by sormuras** [comment]
Point is, that putting the files into the cache and restoring the files from the cache takes even longer than just download the files from the external sources. IIRC, if you have to install (unzip, precalculate, ...) some tools after downloading, then caching that installation results in a speed up.

I'll leave the issue open for future reference -- maybe you'll find out that my information is outdated.

**Comment by sormuras** [comment]
The three main time consumers are at the moment:

**54.189s** `:junit-platform-gradle-plugin:test` 	`org.gradle.api.tasks.testing.Test`
**16.442s** `:junit-jupiter-engine:junitPlatformTest` 	`org.gradle.api.tasks.JavaExec`	
**11.955s** `:junit-jupiter-engine:compileTestKotlin` 	`org.jetbrains.kotlin.gradle.tasks.KotlinCompile`

**Comment by sormuras** [comment]
Closing this non-issue.

If speed is ever a) a real concern here and b) can be optimized with caching on Travis CI, feel free to re-open it.

**Comment by JLLeitschuh** [comment]
Fair enough.
