### ISSUE TITLE
Change license to EPL v2.0

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1045]
## Overview

The Eclipse Foundation recently [announced EPL v2.0](https://www.eclipse.org/org/press-release/20170829eplv2.php).

After discussions with Eclipse Foundation's legal department, we have learned that the JUnit Team does not need to seek the permission of past contributors, unless the team wants to add in the GPL compatibility.

However, the Eclipse Foundation suggests to:

- inform downstream users of the change
- ensure there is rough consensus amongst the committers that this is the right time to switch

## Deliverables

- [x] Decide within the JUnit 5 Team if this is the right time to switch to EPL v2.0.
- [x] Consider contacting all [contributors](https://github.com/junit-team/junit5/graphs/contributors) to inform them of the decision to switch to the EPL v2.0.
- [x] Update all license headers in all source code (Java, Groovy, Kotlin, etc.).
- [x] Update license header used by Spotless.
  - `src/spotless/eclipse-public-license-1.0.java`
- [x] Update Spotless license header configuration in the Gradle build.
- [x] Update all `LICENSE.md` files in repository.
  - [x] which should include license files included in published artifacts, but this should be verified.

**Comment by jbduncan** [comment]
I've not read the full licensing terms for EPL v2.0, but just from reading the announcement above, the high-level changes from v1.0 to v2.0 look great to me! So, as a contributor to JUnit 5, I'd personally be very happy for the license to be switched from v1.0 to v2.0, and thus I hereby give my permission in advance.

I'd also be very happy to give permission to allow JUnit 5 to add in GPL compatibility, if the JUnit 5 team ultimately considers doing so, as I can only see allowing JUnit 5 to be usable in GPL-licensed projects as a good thing. :)

**Comment by sbrannen** [comment]
Thanks, @jbduncan

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
Fixed in master in 2220f7ee708a2e63ff1caac26f425487281556ca and 3c37e59640deaf1f8d9761c655c80193f8d9226a.
