### ISSUE TITLE
Implementation of AbstractExtensionContext#getRoot is wrong

### ISSUE THREAD

**Issue by VagrantBlackbird** [junit-team/junit5#1048]
## Overview

In RC3, AbstractExtensionContext implements ExtensionContext#getRoot. The documentation suggests that this method will return the top level ExtensionContext (in other words, the result of getRoot should be context independent), but the implementation is written such that it terminates after traversing one level of ExtensionContext at most.

Here's a unit test that fails both its tests:

```
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.ParameterContext;
import org.junit.jupiter.api.extension.ParameterResolutionException;
import org.junit.jupiter.api.extension.ParameterResolver;

import com.topdesk.stanchion.ExtensionContextGetRootTest.RootExtensionContextInjector;

@ExtendWith(RootExtensionContextInjector.class)
public class ExtensionContextGetRootTest {
	
	private final ExtensionContext rootExtensionContext;
	
	ExtensionContextGetRootTest(ExtensionContext rootExtensionContext) {
		this.rootExtensionContext = rootExtensionContext;
	}
	
	@Test
	void topLevelMethod(ExtensionContext shouldBeRootExtensionContext) {
		assertEquals(rootExtensionContext, shouldBeRootExtensionContext);
	}
	
	@Nested
	class NestedTest {
		
		@Test
		void nestedLevelMethod(ExtensionContext shouldBeRootExtensionContext) {
			assertEquals(rootExtensionContext, shouldBeRootExtensionContext);
		}
	}
	
	static class RootExtensionContextInjector implements ParameterResolver {
		
		@Override
		public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
			return parameterContext.getParameter().getType() == ExtensionContext.class;
		}
		
		@Override
		public ExtensionContext resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
			return extensionContext.getRoot();
		}
	}
}
```

From the failure messages, it becomes clear that all three injected extension contexts have a different root:

> org.opentest4j.AssertionFailedError: 
> Expected :org.junit.jupiter.engine.descriptor.JupiterEngineExtensionContext@184cf7cf
> Actual   :org.junit.jupiter.engine.descriptor.ClassExtensionContext@2fd6b6c7

And

> org.opentest4j.AssertionFailedError: 
> Expected :org.junit.jupiter.engine.descriptor.JupiterEngineExtensionContext@184cf7cf
> Actual   :org.junit.jupiter.engine.descriptor.ClassExtensionContext@63a65a25

## Deliverables
- [ ] Add tests to test this behavior
- [ ] Fix the bug

**Comment by marcphilipp** [comment]
Very good catch! I'm working on a fix.

**Comment by marcphilipp** [comment]
Fixed in c17571d.

@VagrantBlackbird Thanks for catching this just before the 5.0.0 release! 👍

**Comment by VagrantBlackbird** [comment]
@marcphilipp Thanks for fixing it so swiftly 😃 !

**Comment by sbrannen** [comment]
> @VagrantBlackbird Thanks for catching this just before the 5.0.0 release! 👍

I second that! 👍
