### ISSUE TITLE
AbstractTestDescriptor allows inconsistent parent/child relationships

### ISSUE THREAD

**Issue by kcooney** [junit-team/junit5#1056]
## Overview

The methods in `AbstractTestDescriptor`allows the parent/child relationship to be inconsistent.

## Deliverables

- [x] The `setParent()` method should throw an exception if the passed-in descriptor is not `null` and `this.parent` is not `null`
- [x] The `removeFromHierarchy()` method should call `setParent(null)` on all children.

**Comment by sormuras** [comment]
Good catches, @kcooney !

`setParent()`
The state/argument check is not violated within the code base, meaning all tests still run, when the check is applied.

`removeFromHierarchy()`
The proposed change make the behaviour more consistent with the implementation of `removeChild` -- that already calls `child.setParent(null)`

**Comment by sormuras** [comment]
Addressed the two issues in https://github.com/junit-team/junit5/commit/0da282dd71de748012f9be7c9fba549f924dc37c


Caveat: there is still a way to reset the parent of a `AbstractTestDescriptor`. First set it to `null`, then assign the new parent instance. See 
https://github.com/junit-team/junit5/blob/0da282dd71de748012f9be7c9fba549f924dc37c/platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/AbstractTestDescriptorTests.java#L87-L93

**Comment by marcphilipp** [comment]
What if an engine actually wants to change its parent-child relationships during discovery, e.g. to "compress" its tree or to group things? IMHO we should allow changing a child's parent. Therefore, I think we should not add any checks to `setParent()` but I'm fine with the proposed modification of `removeFromHierachy()`.

**Comment by sormuras** [comment]
As the new check does not prevent the parent change anyway (see two step test case above) I'm fine with reverting that _fix_.

**Comment by kcooney** [comment]
@marcphilipp good point. You could replace`removeFromHierarchy()` with `removeFromParent()` to allow re-parenting while keeping the tree consistent. I looked at the callers, and none of them need to remove the children from the node.

@sormuras you are right that the fact that `setParent()` exists makes it possible to make inconsistent hierarchies. The only way to avoid that would be to make `TestDescriptor` an abstract class instead of an interface, making `setParent()` package-scope, and making `addChild()` and  `removeChild() final. If it wasn't so late in the project, I would suggest doing that anyway, since everyone extends from `AbstratTestDescrptor` anyway.

**Comment by marcphilipp** [comment]
Please keep in mind that TestDescriptors are an API used by test engine authors, not test authors. So, while the flexibility of `TestDescriptor` being an interface introduces the potential of inconsistencies, I expect test engine authors to (a) know what they're doing and (b) thoroughly test their code.

**Comment by kcooney** [comment]
I still think it's good to protect against accidental misuse where possible. The reason why I suggested that `setParent()` should check that there isn't already a parent is because `addChild()` currently allows you to accidentally add a child to two parents, again leading to inconsistencies. Forcing the caller to call `setParenr(null)` to reparent a node at least means that the caller is making their intent clear.

If you want to allow people to compress the tree, replace `removeFromHierarchy()` with `removeFromParent()`. Either way, we should document that `setParent()` should be used with care, and have the JavaDoc reference the preferred methods.

**Comment by sbrannen** [comment]
@kcooney, we're right in the middle of the GA release...

Would you mind opening a new issue so that we can revisit this post 5.0 GA?

**Comment by kcooney** [comment]
@sbrannen all the context is in this issue so I will just reopen it and you can target it for another release.

**Comment by bechte** [comment]
The longer I think about this issue, the more I am convinced that ```removeFromHierarchy()``` should *only* set ```parent=null``` an leave the children _as-is_. ```removeFromHierarchy()``` removes the whole subtree starting at the given node from the tree, while it leaves the subtree consistent, which I think is valid and (at least I feel is) correct.

Another valid interpretation of the ```removeFromHierarchy()``` would be to remove the node and pull all children one level up, such that all children point to their "grandfather" or "grandmother".

A third option would be to call ```removeFromHierarchy()``` recursively.

Everything else leaves a lot of nodes in a "detached" state, which cannot be reached from anywhere anymore. This makes no sense at all.

Thoughts?

**Comment by marcphilipp** [comment]
For the use case it originally was introduced for, namely filtering, it doesn't make a difference. For reattaching this node elsewhere, leaving the children intact would make sense. Other use cases might have different requirements. Thus, I think we need to have a concrete problem to solve in order to think about a solution. In any case, we shouldn't change the meaning of `removeFromHierarchy()` now that it's released.

**Comment by kcooney** [comment]
I suggest adding `removeFromParent()` to the interface with a default implementation of essentially `getParent().removeChild(this)`

**Comment by bechte** [comment]
I would follow the suggestion from @kcooney (maybe call it ```detachFromParent()``` and in addition mark ```remoteFromHierarchy()``` with ```@Deprecated```. We could remove it later or, if we have a valid use case for it, change it to whatever is required.
