### ISSUE TITLE
**Bug report.** junit5-dynamic-test-example returns java.lang.ClassNotFoundException: org.junit.platform.commons.logging.LoggerFactory

### ISSUE THREAD

**Issue by Wojand** [junit-team/junit5#1058]
## Overview
Environment:

> Apache Maven 3.3.3 
> Java version: 1.8.0_92
> OS name: "windows 7

- ( ) **Bug report.**
Look into attached project created from original tutorial for junit 5.
This project is compiled correctly by Maven or Eclipse.
But when I run mvn clean test then I see:

> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> 
> Results :
> 
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 4.045 s
> [INFO] Finished at: 2017-09-12T15:44:42+02:00
> [INFO] Final Memory: 36M/3191M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
> 19:test (default-test) on project junit5-dynamic-test-example: Execution default
> -test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: T
> here was an error in the forked process
> [ERROR] java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngin
> e: Provider org.junit.vintage.engine.VintageTestEngine could not be instantiated
> 
> [ERROR] at java.util.ServiceLoader.fail(ServiceLoader.java:232)
> [ERROR] at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
> [ERROR] at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:3
> 84)
> [ERROR] at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
> [ERROR] at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
> [ERROR] at org.junit.platform.launcher.core.DefaultLauncher.validateUniqueIds(De
> faultLauncher.java:60)
> [ERROR] at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLaunch
> er.java:55)
> [ERROR] at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFacto
> ry.java:42)
> [ERROR] at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUn
> itPlatformProvider.java:59)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
> ssLoader(ForkedBooter.java:286)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
> edBooter.java:240)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
> 121)
> [ERROR] Caused by: java.lang.NoClassDefFoundError: org/junit/platform/commons/lo
> gging/LoggerFactory
> [ERROR] at org.junit.vintage.engine.VintageTestEngine.<clinit>(VintageTestEngine
> .java:40)
> [ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 
> [ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
> orAccessorImpl.java:62)
> [ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
> onstructorAccessorImpl.java:45)
> [ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [ERROR] at java.lang.Class.newInstance(Class.java:442)
> [ERROR] at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:3
> 80)
> [ERROR] ... 9 more
> [ERROR] Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.
> logging.LoggerFactory
> [ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> [ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [ERROR] ... 16 more
> [ERROR] -> [Help 1]

[junit5-dynamic-test-example.zip](https://github.com/junit-team/junit5/files/1296200/junit5-dynamic-test-example.zip)

**Comment by Wojand** [comment]
I modified junit5-dynamic-test-example because original project doesn't works (compile error appears)

**Comment by sormuras** [comment]
Closing this issue - likely real target project is https://howtoprogram.xyz

**Comment by Wojand** [comment]
You have right. 
https://github.com/howtoprogram/junit5-examples project should be described BIG flag **"DEPRECATED"**
I copied example from this project into https://github.com/junit-team/junit5-samples and it works (after update original example to newest API)
