### ISSUE TITLE
Decide on naming convention for source code elements pertaining to acronyms

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1059]
## Overview

The following comment was intended for #1052; however, the branch has been deleted in the interim making it impossible to post a comment.

## Comments in Reply to #1052 

Regarding the `UriSelector` vs `URISelector` discussion, IMHO `UriSelector` was the right choice.

Whenever you need to include acronyms as part of a type name or method name, it is best to keep the first letter of the acronym uppercase and use lowercase for the rest of the acronym. Otherwise, it becomes _impossible_ to perform camel-cased searches in IDEs, and it becomes potentially very difficult for mere humans to read and/or reason about the thing without reading documentation (if documentation even exists).

Consider for example a use case needing to support an HTTP URL. Calling the method `getHTTPURL()` is absolutely horrible in terms of usability; whereas, `getHttpUrl()` is great in terms of usability. The same applies for types `HTTPURLProvider` vs `HttpUrlProvider`.

I would therefore argue that `URIConverter` should be renamed `UriConverter` for consistency within the framework and in favor of usability.

Since it's an internal class, there is no harm in renaming it, even after 5.0 GA.

## Deliverables

- [x] Decide on naming convention for source code elements pertaining to acronyms
- [x] Document naming convention for source code elements pertaining to acronyms
- [x] Rename `URIConverter` to `UriConverter`.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda I'm opened this issue so that we can discuss the topic amongst the team. 

In the very least we need to have a clear consensus on how elements containing acronyms should be named within the framework going forward!

**Comment by jbduncan** [comment]
> The following comment was intended for #1052; however, the branch has been deleted in the interim making it impossible to post a comment.

Oh whoops, sorry @sbrannen! I didn't realise that deleting branches removed the ability to comment on them, so I'll keep that in mind for next time.

**Comment by marcphilipp** [comment]
Team Decision: Use the de facto naming convention and rename `URIConverter` to `UriConverter`.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Naming conventions for acronyms are now documented here:

https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#naming-conventions

**Comment by sbrannen** [comment]
All deliverables have been completed.

**Comment by jbduncan** [comment]
@sbrannen Looks great to me! Many thanks for fixing the name of `URIConverter` for me. :)
