### ISSUE TITLE
Create a builder for unique ID paths

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#106]
A unique ID should be built in parts, e.g.

`[engine: junit5]/[package:org]..../[class:MyClass]/[method:test1()]`

Implement in branch for team review. 

Prerequisite for #107

**Comment by bechte** [comment]
Requires a decision on #126

**Comment by jlink** [comment]
I don't think there's this strong coupling to #126. I'll give it a try if I find a quiet moment / hour.

**Comment by bechte** [comment]
It might become obsolete... I would like to talk about it on the team. but feel free to prepare something for the discussion.

**Comment by sbrannen** [comment]
@jlink, should this issue be closed now?

**Comment by jlink** [comment]
I created a follow up issue. So yes.

**Comment by jlink** [comment]
Follow up; #190

**Comment by sbrannen** [comment]
thanks!
