### ISSUE TITLE
Should ConditionEvaluationResult be a final class?

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#1062]
## Overview

I am in the process of prototyping a `@Retry` type annotation to run a test a certain number of times based on failures. I was looking at [`ConditionEvaluationResult`](https://github.com/junit-team/junit5/blob/0e0a3dbfb17568e3d9ce7e01552f304c78fb3354/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ConditionEvaluationResult.java) and noticed it was not a `final` class. This leaves it open for inheritance and possible breaking changes further down the line if other conditional test result types are supported (maybe Skipped?)

I wasn't sure if it was open by design or if the direction I could see it going doesn't align with what the team thinks.

## Deliverables

- [ ] Make `ConditionEvaluationResult` a `final` class

**Comment by marcphilipp** [comment]
It's "effectively" final because it only has a private constructor.

**Comment by mkobit** [comment]
Good point! I didn't notice that.
