### ISSUE TITLE
Document optional dependency on apiguardian-api in User Guide

### ISSUE THREAD

**Issue by tyuldashev** [junit-team/junit5#1064]
## Overview

Since there are no runtime dependencies on `apiguardian-api`, the focus of this issue has been changed to document that fact in the User Guide.

#1065 will _fix_ the dependency scope in the generated Maven POMs.

## Original Input from @tyuldashev 

Child of [#436 Relocate @API to a stand-alone module](https://github.com/junit-team/junit5/issues/436)

It seems that ["JUnit 5 User Guide" dependency diagram](http://junit.org/junit5/docs/current/user-guide/#dependency-diagram)  should be updated with dependency of `junit-platform-commons` on `apiguardian-api`.

## Deliverables

- [x] Document the `optional` dependency on `apiguardian-api` in the _Dependency Metadata_ section of the User Guide.
- [x] Add related _global_ note to the release notes in the User Guide.

**Comment by sbrannen** [comment]
Good catch!

Thanks for bringing this to our attention. 👍

**Comment by sbrannen** [comment]
...except that.... well, none of the modules in JUnit actually rely on the `@API Guardian` at runtime.

**Comment by sbrannen** [comment]
In fact, this _issue_ just made me realize that the dependency metadata (i.e., Maven POM) is actually incorrect for all artifacts that we just releases in JUnit 5.0 GA.

For example: https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.0.0/junit-jupiter-api-5.0.0.pom

`apiguardian-api` should **not** be listed as a `compile` dependency.

**Comment by mkobit** [comment]
If there is no runtime access, you could mark it as `compileOnly`.  The same approach could be taken for the nullabilluty annotations in https://github.com/junit-team/junit5/issues/358

**Comment by sbrannen** [comment]
@mkobit, yep exactly!

That's what I'm going to have us do for the next release. 😉

**Comment by sbrannen** [comment]
**Update**

Since there are no runtime dependencies on `apiguardian-api`, I am repurposing this issue to document that fact in the User Guide.

#1065 will _fix_ the dependency scope in the generated Maven POMs.

**Comment by sbrannen** [comment]
This issue is _blocked_ until #1065 is resolved.

**Comment by sbrannen** [comment]
Added _Deliverables_

**Comment by tyuldashev** [comment]
Thanks for quick response and explanation in YouTrack :).

**Comment by sbrannen** [comment]
You're welcome!

**Comment by sbrannen** [comment]
@mkobit 

> If there is no runtime access, you could mark it as `compileOnly`.  The same approach could be taken for the nullability annotations in #358.

The problem with `compileOnly` in Gradle is that the dependency is no longer listed at all in the generated Maven POMs; whereas, we actually want it to show up as an `optional` dependency. 😞 

Note, however, that I'm aware of a solution to that and will address that in #1065.

**Comment by jbduncan** [comment]
> The problem with `compileOnly` in Gradle is that the dependency is no longer listed at all in the generated Maven POMs; whereas, we actually want it to show up as an `optional` dependency. 😞

Do we want this because we want to be able to perform API-related analysis of code, for example to check that no third party code uses internal details?

**Comment by sbrannen** [comment]
> Do we want this because we want to be able to perform API-related analysis on both source code and compiled bytecode using these annotations, for example to check that no third party code uses internal details?

Yes.

That's one of the primary objectives of the @API Guardian project... even if the project home page currently has _zero_ documentation listing the objectives. 😉

**Comment by sbrannen** [comment]
FWIW, the (currently internal) [ApiReportGenerator](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/java/org/junit/api/tools/ApiReportGenerator.java) already performs analysis on byte code.

**Comment by jbduncan** [comment]
> FWIW, the (currently internal) ApiReportGenerator already performs analysis on byte code.

Oh, cool! For some reason, I thought ApiReportGenerator only worked on source code. :P

**Comment by sbrannen** [comment]
This issue is no longer _blocked_ by #1065.

**Comment by marcphilipp** [comment]
_in progress_
