### ISSUE TITLE
Remove compile dependency on apiguardian-api in Maven POMs

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1065]
## Overview

Commit 77c0f9a5002c52ca0f9d363a77a674137f5ae66e accidentally introduced a Maven `compile` scope dependency on the `apiguardian-api` artifact in all published JUnit artifacts; whereas, the dependency should **ideally** be listed as `optional` in the generated Maven POMs since there are in fact zero runtime dependencies on `@API` within published JUnit artifacts.

## Related Issues

- https://youtrack.jetbrains.com/issue/IDEA-178888
- #1064 

## Deliverables

- [x] Remove `compile` dependency on `apiguardian-api` in generated Maven POMs.
- [x] Consider including an `optional` dependency on `apiguardian-api` in generated Maven POMs.
  - AFAIK, it is not possible to generate an `optional` dependency with the standard Gradle infrastructure. For that we will likely have to use a third-party tool such as the [propdeps-plugin](https://github.com/spring-gradle-plugins/propdeps-plugin) from the Spring team.
- ❌ Consider backporting this change to `1.0.1`, `5.0.1`, and `4.12.0.1` releases.
  - Team decision: do not backport unless such branches are created due to other needs.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, I have added the `team discussion` label in order to address the following deliverable.

- Consider backporting this change to a `5.0.1` release.

**Comment by sbrannen** [comment]
For Vintage, we'll have to decide how to name/version point releases. 😕 

`4.12.1` vs `4.12.0.1` vs. ???

**Comment by sbrannen** [comment]
In retrospect, starting the Vintage version with `4.12.0` was perhaps not be the best idea. Oh well...

**Comment by sbrannen** [comment]
@junit-team/junit-lambda I also add the following deliverable which is up for discussion.

- Consider including an `optional` dependency on `apiguardian-api` in generated Maven POMs.
  - AFAIK, it is not possible to generate an `optional` dependency with the standard Gradle infrastructure. For that we will likely have to use a third-party tool such as the dependency management plugin from the Spring team.

**Comment by sbrannen** [comment]
Update: linked to propdeps-plugin in issue description

**Comment by sbrannen** [comment]
FYI: the `compile` dependency in Maven POMs has already been removed in `master` in a5f09e335f3bfb79ef39fc90a914063a0a18f35a.

**Comment by marcphilipp** [comment]
I think an optional dependency makes sense. I don't think we need to backport it to `*.0.1` releases unless we need those releases anyway.

**Comment by sbrannen** [comment]
ok. thanks for chiming in. I'll update the deliverables accordingly.

**Comment by sormuras** [comment]
Looking at the `pom.xml` version `5.1.0-SNAPSHOT` from `junit-jupiter-api` it still lists

- `opentest4j`
- `junit-platform-commons`

as **compile** scope dependencies. Shouldn't they only be in **runtime** scope?

**Comment by marcphilipp** [comment]
Why should they?

**Comment by sormuras** [comment]
If you want compile your project that refers to `junit-jupiter-api` as a `test-compile` dependency you don't need the other two at compile time, iirc. When starting the test run, the two must be on the class-path, though.

**Comment by sormuras** [comment]
Never mind - I always forget about `JUnitException` and `MultipleFailuresError`. Those and other are indeed needed in **compile** scope.

**Comment by sbrannen** [comment]
Introduced use of Spring's `propdeps-plugin` to configure the `@API Guardian` as an `optional` dependency in commit b3c286d71366ca9bcb8aeb120b387c5ea0d147cc.

**Comment by sbrannen** [comment]
For example, the generated Maven POM for `junit-jupiter-api` now contains the following dependency entry.

```xml
    <dependency>
      <groupId>org.apiguardian</groupId>
      <artifactId>apiguardian-api</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
```

**Comment by renatoathaydes** [comment]
Was this decision reverted later?

Currently, the dependency is [not optional in 5.8.2](https://central.sonatype.dev/artifact/org.junit.jupiter/junit-jupiter-api/5.8.2) all the way to [5.9.1](https://central.sonatype.dev/artifact/org.junit.jupiter/junit-jupiter-api/5.9.1) for example:

```xml
    <dependency>
      <groupId>org.apiguardian</groupId>
      <artifactId>apiguardian-api</artifactId>
      <version>1.1.2</version>
      <scope>compile</scope>
    </dependency>
```
