### ISSUE TITLE
Release notes should be ordered from newest to oldest

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#1066]
## Feature request

As the project has produced more releases, it's pretty obvious that you have to scroll a long way past the content of the user's guide to review the most recent release notes.

## Deliverables

- [x] Reverse the order of the published release notes.

**Comment by sbrannen** [comment]
Probably not a bad idea. 😉 

@junit-team/junit-lambda Any objections?

**Comment by marcphilipp** [comment]
No objections from me.

**Comment by sormuras** [comment]
I'd retain the order and "squash" the release notes by moving old ones to a second archive page. 

The advantage of the newest entry being first or last on a page is that you can fast-forward by pressing "ctrl+home" or "ctrl+end". Having the latest entry in the middle of the page kills these short-cuts.

**Comment by sormuras** [comment]
Or we move all release notes on a separate page and reverse the order to have the latest release on top.

**Comment by bechte** [comment]
I like the idea to invert the order and building an archive page for old releases, maybe one page per release.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
@junit-team/junit-lambda 

**Update**

I've initiated an archive for older release notes in the wiki...

https://github.com/junit-team/junit5/wiki/Release-Notes

It's a _work in progress_ since all links to sections of the User Guide are broken, but please let me know what you think about the approach!

Please note as well that my intention is to only include the _current_ release notes in the User Guide (i.e., 5.1 M1 at the moment).

**Comment by marcphilipp** [comment]
IMHO we need stable links to release notes. Thus, I would prefer an AsciiDoc-generated release notes page with the most recent one at the top.

**Comment by sbrannen** [comment]
> IMHO we need stable links to release notes. Thus, I would prefer an AsciiDoc-generated release notes page with the most recent one at the top.

I actually already came to the same conclusion myself and will therefore likely scrap all the work I just did in the wiki as an "experiment", but I'm leaving that "as is" for the time being.

**Comment by sbrannen** [comment]
Addressed in 5059698c58cac5335abdf4bb35de4830764ca308.

Further work will be performed in #1068.
