### ISSUE TITLE
Create release/5.0.x branch

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1076]
## Deliverables

- [x] Create releases/5.0.x branch starting from r5.0.0 tag
- [x] Cherry-pick commits of all issues assigned to the 5.0.1 milestone

**Comment by jbduncan** [comment]
I admit it's not clear to me why commits are being cherry-picked for 5.0.1, as opposed to releasing from a specific commit in master. Would you kindly clarify for me why it is being done this way, @marcphilipp?

**Comment by marcphilipp** [comment]
Because master already contains a few new features that we don't want to include in a minor bugfix release.
