### ISSUE TITLE
Introduce ClassFilter for use in reflection utilities

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1077]
## Overview

Many methods in classes and interfaces of package `org.junit.platform.commons.util` are using the two parameters `classNameFilter `and `classTester` in their signature their like:
```
T method(... Predicate<Class<?>> classTester, Predicate<String> classNameFilter, ...)
```
In most cases the actual values are just passed down the call-stack.

This issue proposes to introduce a wrapper named `ClassFilter` or `ClassTester` that could look like:

```java
@API(status = INTERNAL, since = "1.1")
public class ClassFilter {

	public static ClassFilter of(Predicate<Class<?>> classPredicate, Predicate<String> namePredicate) {
		Preconditions.notNull(classPredicate, "class predicate must not be null");
		Preconditions.notNull(namePredicate, "name predicate must not be null");

		return new ClassFilter(classPredicate, namePredicate);
	}

	private final Predicate<Class<?>> classPredicate;
	private final Predicate<String> namePredicate;

	private ClassFilter(Predicate<Class<?>> classPredicate, Predicate<String> namePredicate) {
		this.classPredicate = classPredicate;
		this.namePredicate = namePredicate;
	}

	public boolean test(Class<?> type) {
		return classPredicate.test(type);
	}

	public boolean test(String name) {
		return namePredicate.test(name);
	}
}
```

With such a type, the internal method signature will reduce to:
```
T method(... ClassTester classTester, ...)
```
and if we ever need to add another predicate, it can be done in the wrapper type w/o changing the signature of the internal methods.

## Deliverables

- [ ] Refactor internal methods to use the new class tester wrapper type

**Comment by sbrannen** [comment]
Seems like a good idea to me.

Go for it!
