### ISSUE TITLE
Add --scan-module-path support

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1080]
## Overview

Umbrella issue for adding `--scan-module-path` support to the JUnit Platform.

## Related Issues

- #1087 - [Multi-release JAR](http://openjdk.java.net/jeps/238) with `JigsawUtils` and module-path scanning support
- https://github.com/junit-team/junit5-samples/pull/36 - Sample running on the module-path

## Outdated Pull Requests

- Part I #1061 - SPI `ModuleClassFinder`
- Part II #1057  - Default (single) implementation

## Deliverables

- [x] Make `--scan-module-path` work
- [X] ~Add `--scan-module-path` and `--select-module` support to Gradle Plugin~ will be done in #1119
- [X] ~Add `--scan-module-path` and `--select-module` support to Maven Surefire Plugin~

**Comment by marcphilipp** [comment]
Closed in favor of #1119.
