### ISSUE TITLE
Display name for @ParameterizedTest should only include consumed arguments

### ISSUE THREAD

**Issue by karollewandowski** [junit-team/junit5#1081]
Default display name for test using parameters from `@CsvSource` could be improved. Currently the following test:
```java
class Test {
    @ParameterizedTest
    @CsvSource({"value1,value2"})
    void test(String string) {
        // 
    }
}
```
will produce test name:
```
[1] value1, value2
```

The reason is that generated test name contains all columns from record provided by `@CsvSource`. In above example the record `"value1,value2"` is converted to 2 columns: `"value1"` and `"value2"`. It would be better to include only actually used columns, so in this case: `"value1"`.

**Comment by karollewandowski** [comment]
I would be glad to contribute to project by implementing this feature. Please let me know whether I can create PR for that.

**Comment by sbrannen** [comment]
Hi @karollewandowski,

Yes, feel free to submit a PR for this.

But please keep in mind that the issue might not be limited to `@CsvSource`. Rather, it is perhaps an issue with `@ParameterizedTest` methods in general. Thus, we will need to see tests for all such cases.

Cheers!

**Comment by sbrannen** [comment]
Currently in the _5.1 Backlog_.

**Comment by sbrannen** [comment]
Thanks, @karollewandowski! 👍
