### ISSUE TITLE
Consider logging "Malformed class name" exceptions at DEBUG level

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1083]
## Overview

See discussion in #1082 for details.

## Deliverables

- [x] Log "Malformed class name" exceptions during classpath scanning at `DEBUG` level.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda,

This is a quick _fix_ on a single line in `ClasspathScanner.logMalformedClassName(Path, String, InternalError)`.

Please let me know if there any objections; otherwise, I'll go ahead and make the change for 5.1.

**Comment by marcphilipp** [comment]
No objections from me.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Resolved in `master` in commit f922f8e2cf1a5574325c7777d7532704d8ccb774.
