### ISSUE TITLE
Write micro-tests for classes in junit-commons

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#109]

**Comment by lutovich** [comment]
I would like to help with this but it seems most non-trivial classes from junit-commons already have pretty good test coverage. @marcphilipp could you please elaborate what should be done as part of this task?

**Comment by sbrannen** [comment]
@lutovich, basically just go through each utility in the `org.junit.gen5.commons.util` package in the `junit-commons` module, and for each non-private method, ensure that there is sufficient coverage in a corresponding test class in the `org.junit.gen5.commons.util` package in the `junit-tests` module.

Make sense?

**Comment by lutovich** [comment]
Yes, understood. I can do this.

**Comment by sbrannen** [comment]
Cool. thanks!

**Comment by lutovich** [comment]
@sbrannen I'm still working on this task, here is the branch https://github.com/lutovich/junit5/tree/issue109-tests-junit-commons. This will take couple more days.

**Comment by sbrannen** [comment]
I took a quick look and made some minor suggestions.

Keep up the good work, and thanks for helping us out!

**Comment by sbrannen** [comment]
PR #236 has been merged into `master` in commit 2dfd65461e7ecf2b8f1d7628c8b407bb67bd322a.
