### ISSUE TITLE
Promote API Status of parameterized tests

### ISSUE THREAD

**Issue by BlueIce** [junit-team/junit5#1093]
## Overview

According to the user guide the following types in the `junit-jupiter-params` module are currently annotated with API Status `EXPERIMENTAL`: 

`ParameterizedTest`, `ArgumentConversionException`, `ArgumentConverter`, `ConvertWith`, `JavaTimeConversionPattern`, `SimpleArgumentConverter`, `Arguments`, `ArgumentsProvider`, `ArgumentsSource`, `ArgumentsSources`, `CsvFileSource`, `CsvSource`, `EnumSource`, `MethodSource` and `ValueSource`.

Additionally the user guides gives a warning about using these types:

> Caution should be taken when relying on such APIs.

Because of this people might hesitate to start using parameterized tests in regular projects. As I feel that parameterized tests haven been tried and tested and are a valuable part of JUnit Jupiter I propose to promote the API Status to `MAINTAINED` or `STABLE`.

If you agree I can set up a pull request.

## Deliverables

- [ ] Promote API Status of types related to parameterized tests to `MAINTAINED` or `STABLE`

**Comment by sormuras** [comment]
We want to include `@ParameterizedContainer` (or similar) first: https://github.com/junit-team/junit5/issues/878#issuecomment-354544841

**Comment by rimal** [comment]
@sormuras by when will the status for `@ParameterizedTest` be promoted?

**Comment by marcphilipp** [comment]
@rimal Not in 5.5, but very likely in 5.6.

**Comment by BlueIce** [comment]
Superseded by #2362.

**Comment by marcphilipp** [comment]
@BlueIce Thanks!
