### ISSUE TITLE
ExternalResource should implement AutoCloseable

### ISSUE THREAD

**Issue by rbtcollins** [junit-team/junit5#1094]
## Overview

This is a feature request. We've some code that uses ExternalResources like TemporaryFolder within a test method, and that would be cleaner if ExternalResource implemented java.lang.AutoCloseable -  a trivial implementation like

```        @Override
        public void close() throws Exception {
            after();
        }
```

would be more than enough. Not suppling a patch per your request :)

## Deliverables

- [ ] ...

**Comment by kcooney** [comment]
Thanks for the contribution.

`ExternalResource` is defined in https://github.com/junit-team/junit4 (a different GitHub project) so please file feature requests for it there.

In any case, a test shouldn't call `ExternalResource.after()` because the framework calls it for you.
