### ISSUE TITLE
Fix Javadoc @value tag usages

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1098]
## Overview

`RepeatedTest.java` uses `{@value name}` tags that are not resolved by Javadoc 9 anymore:

	 * <li>{@value #DISPLAY_NAME_PLACEHOLDER}</li>
	 * <li>{@value #CURRENT_REPETITION_PLACEHOLDER}</li>
	 * <li>{@value #TOTAL_REPETITIONS_PLACEHOLDER}</li>

Warnings:
```
RepeatedTest.java:132: warning - {@value #DISPLAY_NAME_PLACEHOLDER} (referenced by @value tag) is an unknown reference.
RepeatedTest.java:132: warning - {@value #CURRENT_REPETITION_PLACEHOLDER} (referenced by @value tag) is an unknown reference.
RepeatedTest.java:132: warning - {@value #TOTAL_REPETITIONS_PLACEHOLDER} (referenced by @value tag) is an unknown reference.
```

## Deliverables

- ❌  Find syntax that works or replace by hard-coded values

**Comment by VikasSherawat** [comment]
@sormuras @marcphilipp May i work on this one?

**Comment by marcphilipp** [comment]
Sure!

**Comment by sbrannen** [comment]
Resolved in commit f1ac69ad2b271df246b98b7cc4b7386c951c0afd.

**Comment by VikasSherawat** [comment]
Hi @sbrannen , I report this bug to Oracle. They have responded back saying if we have a specific test cases for that.

Bug URL : http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8191030

**Comment by sbrannen** [comment]
Thanks for raising the bug, @VikasSherawat.

> They have responded back saying if we have a specific test case to reproduce the issue.

Just put together the simplest example you can based on the JavaDoc used in `RepeatedTest` before the change I made.

**Comment by sbrannen** [comment]
And... I wouldn't state "This bug can be reproduced occasionally." in the bug report.

Rather, I would state that it can always be reproduced.
