### ISSUE TITLE
Surefire plugin ignores test classes which doesn't follow certain name pattern

### ISSUE THREAD

**Issue by rumpfc** [junit-team/junit5#1102]
During some JUnit 5 training sessions I discovered that test classes are ignored by Surefire plugin if they don't follow a certain name pattern:

**class names where tests will run**

- MyJUnitTest
- TestFirstDynamicTestExample
- TestLoginLogout

**class names where tests are ignored**

- FirstDynamicTestExample
- LoginLogout
- MyJUnitExample

I don't know if that's on purpose or an accidental bug. Same happens with JUnit 4 surefire plugin

**Comment by sbrannen** [comment]
Hi @rumpfc,

Out of personal curiosity regarding the "JUnit 5 training sessions" you mentioned, are you the trainer or the trainee?

And... can people check out the syllabus for these trainings?

**Comment by sbrannen** [comment]
> I don't know if that's on purpose or an accidental bug. Same happens with JUnit 4 surefire plugin

This is how the Maven Surefire plugin works.

It supports a predefined set of test class name patterns by default, and these are documented here:

http://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html

I am therefore closing this issue as _invalid_.

**Comment by rumpfc** [comment]
With training session I mean self training after going through some tutorials and trying out different test cases to get familiar with JUnit 5 (I'm a software tester after all). I use both eclipse and maven to run tests and discovered that surefire only uses test classes with a certain pattern. I wasn't sure if this was a default setting and I wasn't aware of an existing documentation on maven website.

Thanks for clarification

**Comment by sbrannen** [comment]
> With training session I mean self training 

Ah. OK.

> Thanks for clarification

You're welcome.
