### ISSUE TITLE
Unable to resolve org.junit.jupiter:junit-jupiter-api:5.0.1

### ISSUE THREAD

**Issue by hanct** [junit-team/junit5#1108]
Hi,

I am using gradle to download junit.

My gradle file is very simple. It just contains only the below few lines, but I got unable to resolve org.junit.jupiter:junit-jupiter-api:5.0.1.  Any idea why is that so?  

*My group id, artifact id and version number seems to be correct. And I am using kotlin-dsl for gradle.

plugins {
    java
}

dependencies{
    testCompile("org.junit.jupiter:junit-jupiter-api:5.0.1") 
}

**Comment by sormuras** [comment]
Seems like your build is missing a `repositories` section:

`repositories {	mavenCentral() }`

See https://github.com/junit-team/junit5-samples/blob/master/junit5-vanilla-gradle/build.gradle for a example Gradle build script.

**Comment by hanct** [comment]
Yes. My fault. You are right. Thanks! Adding this solve the problem!

**Comment by xahon** [comment]
@sormuras I have `mavenCentral()` but this issue occurs too  

```
// Apply the java plugin to add support for Java
apply plugin: 'java'

// In this section you declare where to find the dependencies of your project
repositories {
    jcenter()
    mavenCentral()
}

// In this section you declare the dependencies for your production and test code
dependencies {
    // The production code uses the SLF4J logging API at compile time
    compile 'org.slf4j:slf4j-api:1.7.13'

    compile 'org.projectlombok:lombok:1.16.20'

    // Declare the dependency for your favourite test framework you want to use in your tests.
    // TestNG is also supported by the Gradle Test task. Just change the
    // testCompile dependency to testCompile 'org.testng:testng:6.8.1' and add
    // 'test.useTestNG()' to your build script.
    testCompile 'junit:junit:3.8.2'
    compile 'org.junit.jupiter:junit-jupiter-api'
}
```

**Comment by sormuras** [comment]
> `compile 'org.junit.jupiter:junit-jupiter-api'`

...is missing a version.

Should read something like: `testCompile 'org.junit.jupiter:junit-jupiter-api:5.2.0'`

For a more detailed answer I need more input. And please open a new issue if it is looks similar to an existing one.

**Comment by hanipro91** [comment]
remove this lib, you don't need it

**Comment by gayathri-nagidi** [comment]
@sormuras i am new to this technology and i am also facing same issue could you please help me regarding the same. Thanks in Advance

plugins {
    id 'java'
}

group 'org.hmtmcsc'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}


-------------------------------------------------------------------------

Could not resolve org.junit.jupiter:junit-jupiter-api:5.6.0.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Rohitesh-Kumar-Jain** [comment]
Can anyone help me resolve the same on maven pls?

**Comment by marcphilipp** [comment]
The artifact is available on Maven Central:
https://search.maven.org/artifact/org.junit.jupiter/junit-jupiter-api/5.6.0/jar

**Comment by Anne-aaa** [comment]
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation 'org.junit.jupiter:junit-jupiter:5.8.1'
    implementation 'org.testng:testng:7.1.0'
}

application {
    // Define the main class for the application.
    mainClass = 'com.thoughtworks.tools.App'
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


:app:test: Could not resolve org.junit.jupiter:junit-jupiter:5.8.1.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

anyone could help me to solve it?
