### ISSUE TITLE
Surefire provider should not build test plan per class

### ISSUE THREAD

**Issue by hwellmann** [junit-team/junit5#1113]
## Overview

I'm using a custom `TestExecutionListener` registered via `META-INF/services` which implements `testPlanExecutionStarted()` and `testPlanExecutionFinished()` to execute some custom setup and teardown which needs to be executed just once per suite/plan, and not once per class.

JUnit version: 5.0.1

### Expected Behaviour

When running `mvn test` on a project, my listener gets invoked once before all test class executions and once after all executions.

### Actual Behaviour

My listener gets invoked for every class, which defeats its purpose.

**Comment by marcphilipp** [comment]
I'm afraid there's no easy fix. Surefire's whole execution and reporting is tightly coupled to having test classes. You have to call `testSetStarting` for each. The way it works now is really stupid, but I'm not sure how we can call `testSetStarting` from the `RunListener`.

**Comment by marcphilipp** [comment]
_in progress_
