### ISSUE TITLE
Error combining TestSuite with ParameterizedTest

### ISSUE THREAD

**Issue by lgiorcelli** [junit-team/junit5#1122]
## Overview
Hi, I'm trying to combine a ParameterizedTest with a TestSuite, but it does not work. The only message that I get is "test not started", if there is other tests in the same file, none of them start. 
After some combinations, I found the minimal expression that fails.

This is happening to me in IntelliJ Idea 2017.2.5
Jupiter api, engine and params version: 5.0.1
junit-platform-runner version: 1.0.1

Here is my suite:

```
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectPackages;
import org.junit.runner.RunWith;

@RunWith(JUnitPlatform.class)
@SelectPackages("suite.example.junit5")
public class TestSuite {
}
```

And here is the test:

```
public class BasicTest {

	@ParameterizedTest
	@ValueSource(ints = {2, 4})
	void parameterized(final int argument) {
		assertEquals(0,argument % 2);
	}

}
```

pd: Sorry for my bad english

**Comment by marcphilipp** [comment]
The test suite uses the `JUnitPlatform` runner which is an interim solution to run JUnit 5 tests in IDEs and build tools that do not support JUnit 5, yet. It uses JUnit 4 internally which does not support tests "appearing" at runtime. Thus, it does not report invocations of parameterized tests. Unfortunately, the JUnit Platform does at this time not support declarative test suites (see #744). For now, the Gradle plugin, the ConsoleLauncher and IDEA or Eclipse can be used to execute all tests in a package reliably.
