### ISSUE TITLE
Improve documentation of supported utilities in the User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1132]
## Overview

The current content of the [Supported Utilities in Extensions](http://junit.org/junit5/docs/current/user-guide/#extensions-supported-utilities) section of the User Guide is very lacking.

## Deliverables

- [ ] Improve documentation of supported utilities in the User Guide.
  - Mention `AssertionSupport` and `ReflectionSupport` specifically, pointing out the basic feature set above and beyond what the core JDK libraries have to offer.

**Comment by hglasgow** [comment]
I have created pull request #1171 to add two sections about the annotation and reflection support classes. Hope this is what you were wanting.

**Comment by sbrannen** [comment]
The initial work on this issue by @hglasgow has been merged into `master`; however, I am leaving this issue open in order to perform some additional polishing.

**Comment by sbrannen** [comment]
Additional polishing was added in 59ce73eb888b71cb002af9ed6f1ed542ee4e43e7.

I am therefore closing this issue.

**Comment by sbrannen** [comment]
@hglasgow FYI: the fruit of our combined labor: http://junit.org/junit5/docs/snapshot/user-guide/#extensions-supported-utilities
