### ISSUE TITLE
Support for extension (@ExtendWith) parameters

### ISSUE THREAD

**Issue by maxenglander** [junit-team/junit5#1135]
It would be great if it were possible to parameterize JUnit 5 extensions. For instance, something like this:

```java
@ExtendWith(LiquibaseExtension.class, properties={
    @ExtensionProperty(key="url", value="jdbc:h2:..."),
    @ExtensionProperty(key="changeLogFile", value="path/to/changelog")
})
class MyTest {
}
```

This would enable re-using extension across different codebases and organizations.

Thanks for the terrific tool!

**Comment by marcphilipp** [comment]
> Thanks for the terrific tool!

Thanks! 😊

> It would be great if it were possible to parameterize JUnit 5 extensions.

Neat idea! Right now, you could create your own set of annotations and use `AnnotationSupport` to scan for them. There's #497 which aims at something similar. Which approach would you prefer?

**Comment by maxenglander** [comment]
`AnnotationSupport` will actually work just fine, and #497 looks like a fine solution as well. Thanks for the reply!
