### ISSUE TITLE
Make it possible to return arbitrary Objects from @ValueSource

### ISSUE THREAD

**Issue by britter** [junit-team/junit5#1140]
## Overview

**Feature request.** Make it possible to return arbitrary Objects from a `@ValueSource`.

`@ValueSource` is a nice way to write parameterized tests, but it only lets me define ints, doubles, longs or strings. However what I want to do for example is test some `LocalDate` values:

```java
@ParameterizedTest
@ValueSource(objects = {
    LocalDate.of(2017, 1, 1),
    LocalDate.of(2017, 6, 6),
    LocalDate.of(2017, 12, 31),
})
void testSomethingWithLocalDates(LocalDate param){
    // ...
}
```

This is currently not possible and I have to fall back to dynamic tests, which are quite complex compared to `@ValueSource`

## Deliverables

- [ ] `objects` field in `@ValueSource` to allow definition of object parameters for parameterized tests.

## Note

I'm happy to provide a PR for this, but wanted to check first with the maintainers whether there are reasons this has not already been added (because from looking at the code of `ValueArgumentsProvider` it looks quite trivial to add this).

**Comment by britter** [comment]
This does not work since annotation values can't be abitrary objects. So the best solution is probably to use a method source instead.

**Comment by rumpfc** [comment]
I fear that's impossible in Java generally. 

[Annotation Type Elements](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.1)

**Comment by marcphilipp** [comment]
@britter If only `LocalDate.of(...)`, `List.of(...)` were literals... 😔

However, there's a built-in way of writing this using an implicit conversion:

```java
@ParameterizedTest
@ValueSource(strings = {
    "2017-01-01",
    "2017-06-06",
    "2017-12-31"
})
void testSomethingWithLocalDates(LocalDate param) {
	// ...
}
```
