### ISSUE TITLE
Add ClassUtils.nullSafeToString to support package

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1144]
## Overview

Most third-party test engines that allow test methods with parameters will probably 
need `ClassUtils.nullSafeToString(classes)` or something similar to create their unique IDs. 
That's why I suggest that you create `ClassSupport.nullSafeToString(Class<?>... classes)` and delegate to ClassUtils.

**Comment by marcphilipp** [comment]
Fine by me! Do you have time to submit a pull request?

**Comment by jlink** [comment]
https://github.com/junit-team/junit5/pull/1147

**Comment by sbrannen** [comment]
Addressed in commit f8e5a9491c4e904e69bf047afda87c6c5e0962fb in `master.`
