### ISSUE TITLE
Create 5.0.2 Release Notes

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1146]
- [x] Create Release Notes for 5.0.2

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
I created the release notes in 20db6f8d8cab8583dba7f6aeb3ed34ac52823382.

@marcphilipp, it would be great if you could review them so that we have any extra pair of eyes look at them. TIA!

**Comment by sbrannen** [comment]
Leaving this issue _open_ due to the requested review.

**Comment by marcphilipp** [comment]
LGTM, thanks! 👍
