### ISSUE TITLE
junit5 not support spring Autowired annotation

### ISSUE THREAD

**Issue by htzhang2** [junit-team/junit5#1152]
We have a junit4 test class with Autowired field. After converting to junit5, Autowired stops working and throws NullPointerException.

@RunWith(JUnitPlatform.class)
public class GetAvailableRewardsComponentTests extends ServiceComponentTestsBase
{
    @Autowired
    private RequestValidator m_requestValidator;

    @BeforeEach
    public void setup()
    {
        m_requestValidator.setEnabled(false);
    }
...

**Comment by marcphilipp** [comment]
You need to register the `SpringExtension` in order to make it work. Please refer to https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#integration-testing-annotations-junit-jupiter.

**Comment by htzhang2** [comment]
Which jar file is SpringExtension is located?

I tried:  junit-jupiter-api
            junit-jupiter-engine
            junit-jupiter-params
            junit-jupiter-migrationsupport

None of them work.

**Comment by jbduncan** [comment]
@htzhang2 It's in Spring Framework 5.0, apparently. (https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/context/junit/jupiter/SpringExtension.html)

**Comment by jbduncan** [comment]
Hope this helps. :)
