### ISSUE TITLE
Reduce log level in Jupiter discovery

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1153]
## Overview

When running tests using several test engines, all those test engines will receive discovery request for certain classes or methods or packages (e.g. if you click the run tests button in IntelliJ). It's a normal thing that not all engines can resolve a certain element.

Using logging level `WARNING`, e.g.
`logger.warn(() -> format("Class '%s' could not be resolved.", testClass.getName()));` in `JavaElementsResolver` creates noise in the test runner's output.

Reducing the logging level to `DEBUG` would be preferable from a 3rd-party-testengine POV.

**Comment by sbrannen** [comment]
_in progress_

**Comment by marcphilipp** [comment]
Makes sense! Thanks for bringing this to our attention, @jlink! 👍
