### ISSUE TITLE
Provide better names for the test plan specification

### ISSUE THREAD

**Issue by bechte** [junit-team/junit5#116]
## Status Quo

The names `TestPlanSpecification`, `EngineFilter` and `DescriptionFilter` do not communicate their intent very well and should be changed.

## Deliverables
Renaming:
- [x] Rename class `TestPlanSpecification` to `DiscoveryRequest`
- [x] Rename class `TestPlanSpecificationElement` to `DiscoverySelector`
- [x] Rename class `TestPlanSpecificationElementVisitor` to `DiscoverySelectorVisitor`
- [x] Rename filter classes

Changes:
- [x] create class `FilterResult` based on `ConditionEvaluationResult`
- [x] extract generic interface `GenericFIlter<T>` providing a method `FilterResult filter(T object);`
- [x] let `EngineIdFilter`, `DiscoveryFilter`, and `PostDiscoveryFilter` extend it.
- [x] let the `Launcher` execute the `EngineIdFilter`

Optional:
- [x] Remove the specification DSL if possible from the codebase (saving it to a feature branch)
- [x] move `EngineIdFilter` & `PostDiscoveryFilter` to `junit-launcher-api`
- [x] make `DiscoveryRequest` immutable and implement `Serializable`

**Comment by bechte** [comment]
Changed names within master at e453ca8a.

**Comment by marcphilipp** [comment]
We should also rename occurrences of "elements" in variables and methods of `DiscoveryRequest` (and throughout the codebase) to "selectors".

@bechte Do you have this on your radar? I can do it myself but don't want to interfere with you working on this task.

**Comment by bechte** [comment]
@marcphilipp: Thanks for asking. Yes I do have this on my radar. I was already searching for variables that needs to be replaced, but I am sure that I will miss a few of them, as the names of the variables do not always follow a strict rule.

For the moment, I would be happy if you simple post your findings in this ticket (as you did). I will rename them in my branch along the other changes.

After I have done my work, I will close this ticket and then it would be great if you simple "boy-scout" what I have been missing. :+1:

**Comment by bechte** [comment]
Changes have been pushed to feature branch 'feature-116-providenewnames'.

I will need to rebase it onto master, but don't have time right now. Still, I wanted to provide it to you guys for review purposes. Therefore, I've already created a pull request: #119

**Comment by marcphilipp** [comment]
Since I'm actively working on junit4-engine, I would like to do those changes on my own to prevent conflicts.

Can you please first do an interactive rebase on e453ca8a44da846e17f2be33ea673d5ad9639880, and edit your commits to undo changes to classes in junit4-engine? Then the rebase on master should not lead to conflicts (in junit4-engine).

**Comment by marcphilipp** [comment]
Looking through your changes again, I just realized that my "plan" will not work. :disappointed: 

I will stop working in master for now. We should get the renames merged as soon as possible. Additional work on the DSL can IMHO continue in a branch afterwards.

**Comment by bechte** [comment]
I changed the semantic of `FilterResult` to reflect `isAccepted` in the general case. Nevertheless, there are cases (especially in lambdas / method references) in which it is more natural to say `isFiltered`. Therefore, I changed the default to `isAccepted` but also kept the `isFiltered` variant. I hope this is fine with you.

As an example see the following code (taken from the launcher):

```java
if (specification.getEngineIdFilters().stream()
        .map(engineIdFilter -> engineIdFilter.filter(testEngine.getId()))
        .anyMatch(FilterResult::isFiltered)) {

    // Log ... (statement removed for better readability)

    continue;
}
```

I couldn't find a well readable alternative solution based on `FilterResult::isAccepted` that expresses the same statement, as one, unfortunately, cannot compose `anyMatch(! Predicate<?>)` with its variants `noneMatch(Predicate<?>)` or `allMatch(Predicate<?>)`, since the default case (having no filters at all) is not reflected correctly.

If we find a better solution for that, I would feel free with removing `isFiltered` from the codebase anytime.

**Comment by marcphilipp** [comment]
How about adding `isNotAccepted()` or `isDeclined()` in addition to `isAccepted()`?

**Comment by marcphilipp** [comment]
Thanks to a compiler warning I noticed that you removed setting the engine filter in the `JUnit5` runner and restored it in af1a83f0cd1588a3fae09b9d875c791e4d115668. Was that by accident or on purpose?

**Comment by bechte** [comment]
@marcphilipp : Yes I did this on purpose. The new `EngineIdFilter` will be executed by the `Launcher`, before the engine itself is executed. Therefore, we do not need a `PostDiscoveryFilter` that runs after the test run, anymore.

Did I miss something with the configuration of the `EngineIdFilter` for the JUnit4 runner `JUnit5`, i.e. reading and passing the configuration from the annotation?

**Comment by marcphilipp** [comment]
Yes, the value of the annotation wasn't used anymore. Hence the compiler warning.

**Comment by marcphilipp** [comment]
@bechte Have you seen my [previous comment](https://github.com/junit-team/junit5/issues/116#issuecomment-172316605)?

**Comment by bechte** [comment]
I like the names: I'm in favor of `isDeclined()`. I will have a look at both issues and revalidate them.

**Comment by sbrannen** [comment]
Filters are typically used to _include_ or _exclude_ elements from a set.

With this in mind, I propose the following API and implementation for `FilterResult`.

```java
public class FilterResult {

	public static FilterResult included(String reason) {
		return new FilterResult(true, reason);
	}

	public static FilterResult includedIf(boolean included) {
		return includedIf(included, null);
	}

	public static FilterResult includedIf(boolean included, String reason) {
		return (included ? included(reason) : excluded(reason));
	}

	public static FilterResult excluded(String reason) {
		return new FilterResult(false, reason);
	}

	// -------------------------------------------------------------------

	private final boolean included;

	private final Optional<String> reason;

	private FilterResult(boolean included, String reason) {
		this.included = included;
		this.reason = Optional.ofNullable(reason);
	}

	/**
	 * @return {@code true} if the filtered object should be included in
	 * the test plan
	 */
	public boolean isIncluded() {
		return included;
	}

	/**
	 * @return {@code true} if the filtered object should be excluded from
	 * the test plan
	 */
	public boolean isExcluded() {
		return !isIncluded();
	}

	public Optional<String> getReason() {
		return reason;
	}

	@Override
	public String toString() {
		// @formatter:off
        return new ToStringBuilder(this)
                .append("included", this.included)
                .append("reason", this.reason)
                .toString();
        // @formatter:on
	}

}
```

**Comment by sbrannen** [comment]
Alternatively, the `isIncluded()` and `isExcluded` methods could even be simplified as follows:

```java
public class FilterResult {
	// ...

	/**
	 * @return {@code true} if the filtered object should be included in
	 * the test plan
	 */
	public boolean include() {
		return included;
	}

	/**
	 * @return {@code true} if the filtered object should be excluded from
	 * the test plan
	 */
	public boolean exclude() {
		return !include();
	}

	// ...
}
```

**Comment by bechte** [comment]
I am happy with this change :+1:

In the end it sounds more natural. Glad you mentioned it. Thanks. I will change it tomorrow.

**Comment by sbrannen** [comment]
cool / agreed / you're welcome / looking forward to it :wink:

**Comment by bechte** [comment]
We did not make `DiscoveryRequest` immutable and serializable, but we introduced an interface `EngineDiscoveryRequest` that provides read-only access to the request configuration. This ensures, that the request object is not manipulated by one `TestEngine` during the discovery phase.

**Comment by bechte** [comment]
All topics have been resolved. Therefore, I close this issue.
