### ISSUE TITLE
Typed tags

### ISSUE THREAD

**Issue by tobiasdiez** [junit-team/junit5#1160]
## Overview
- (x) **Feature request.** 

As far as I can see, currently a tag only allows for a string as the argument. It would be nice if we could add tags in a more "typed" way. For example, create an enum `MyTags` and then annotate tests with for example `@Tag(MyTags.Fast)`. In this way, the magical strings disappear and you get IDE support (e.g, auto-completion and advanced renaming facilities). 
I know I can already use `@Tag(MyTags.Fast.name())` but that feels more like a work-around then a real solution.

**Comment by mkobit** [comment]
I am pretty confident you can create your own tag annotation.

```java
// Retention and Target and others
@Tag("myFast")
public @interface MyFast {}
```

**Comment by sormuras** [comment]
Please use the [meta-annotations](http://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotations) support, as mentioned by Mike. Here is an example for collecting all your tags in a common place:

```java
interface MyTags {
    
    @Tag("fast")
    @interface Fast {}

    @Tag("ui")
    @interface Ui {}

    @Fast
    @Ui
    @interface FastUx {}
    
}
```

Each `@interface` declaration needs an "opener" like:

```java
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
```

Usage example:


```java
@Test
@MyTags.FastUx
void testLogin() {...}
```

**Comment by tobiasdiez** [comment]
Thank you very much for the help. Your suggestion works perfectly with the Jupiter engine.

On the other hand, the filters specified in gradle `filters > tags` seem to be completely ignored by the vintage engine. Is this by design or a known bug? Should I open a new issue?

**Comment by sormuras** [comment]
> On the other hand, the filters specified in gradle filters > tags seem to be completely ignored by the vintage engine. Is this by design or a known bug? Should I open a new issue?

Mh, I'm not aware of a "tag to category" converter. Please, open an issue. Thanks in advance.

**Comment by marcphilipp** [comment]
> On the other hand, the filters specified in gradle `filters > tags` seem to be completely ignored by the vintage engine. Is this by design or a known bug? Should I open a new issue?

@tobiasdiez In fact, they are not ignored. A JUnit 4 test annotated with `@Category(Foo.class)` has the fully qualified name of Foo, e.g. `org.example.Foo`, as a tag. When you specify `org.example.Foo` in Gradle you can include or exclude all tests with that tag.

**Comment by tobiasdiez** [comment]
@marcphilipp Thanks a lot for the tip! It is working wonderfully. You should consider adding it in the documentation, as it makes migration way easier.
