### ISSUE TITLE
Gradle plugin should not show stdout by default

### ISSUE THREAD

**Issue by shollander** [junit-team/junit5#1166]
With the built-in gradle junit 4 support, stdout from tests is not output to the screen by default. Stdout is only output to screen when info logging is enable for gradle (`-i` or `--info`). 

With the `junit-platform-gradle-plugin`, all stdout from executing tests is output to the screen by default. I don't think this is the correct behavior. `junit-platform-gradle-plugin` should follow the standard gradle convention.

**Comment by marcphilipp** [comment]
I think that's the standard behavior of the `JavaExec` task which we use internally, isn't it? Please keep in mind, that our Gradle plugin is only meant as an interim solution until Gradle introduces first-class support out of the box.

**Comment by shollander** [comment]
I didn't realize that the `junit-platform-gradle-plugin` was only meant to be an interim solution. The [Junit 5 User Guide](http://junit.org/junit5/docs/current/user-guide/#running-tests-build) makes no mention of this.
In that case it's probably not worth fixing since hopefully Gradle will soon natively support Jupiter.

**Comment by marcphilipp** [comment]
Well, it’s quite usable for regular Gradle projects. And it should be fairly simple to migrate to the core Gradle solution once it’s available. So I didn’t mean to discourage you from using it. We‘re meeting with the Gradle team later today to discuss how to move things forward.

**Comment by shollander** [comment]
It turns out that I can't use `junit-platform-gradle-plugin` anyway since I have integration tests in a separate srcSet which does not seem to be supported.

**Comment by marcphilipp** [comment]
You're right, the `junit-platform-gradle-plugin` does not support it directly. But there are workarounds to achieve this using Gradle, for example https://stackoverflow.com/a/45363280.

**Comment by geowarin** [comment]
Hey guys! 

Is there a way to hide the application output in gradle while we wait for gradle official support ([v4.6 earliest](https://github.com/gradle/gradle/issues/828#issuecomment-351431932)) ?

I tried messing up with the `logManager` attribute to no avail.

**Comment by marcphilipp** [comment]
@geowarin You can redirect the standard output of the junitPlatformTest task like this:

```groovy
junitPlatformTest.standardOutput = new ByteArrayOutputStream()
```

If you really want to make sure nothing gets stored in memory, you can configure it using an anonymous "/dev/null" implementation:

```groovy
junitPlatformTest.standardOutput = new OutputStream() {
    @Override public void write(int byte) throws IOException {}
}
```

**Comment by geowarin** [comment]
Thanks @marcphilipp 👍 

My little hack just for you:

```java
junitPlatform {
  details 'tree'
}

junitPlatformTest.standardOutput = new OutputStream() {
  Queue<Byte> lastBytes = com.google.common.collect.EvictingQueue.create(20)
  def out = new ByteArrayOutputStream()
  def capture = false

  void write(int b) {
    if (lastBytesToString().contains("JUnit Jupiter")) {
      capture = true
    }
    if (capture) {
      out.write(b)
    } else {
      lastBytes.add(b)
    }
  }

  String lastBytesToString() {
    byte[] bytes = new byte[lastBytes.size()]
    lastBytes.eachWithIndex { v, i -> bytes[i] = v }
    return new String(bytes)
  }

  void display() { println out.toString() }
}

task('junitReport') {
  doLast {
    junitPlatformTest.standardOutput.display()
  }
}

junitPlatformTest.finalizedBy(junitReport)
```

**Comment by childnode** [comment]
ℹ️  as I see today, output has been suppressed since `id 'org.junit.platform.gradle.plugin' version '1.0.3'`

**Comment by marcphilipp** [comment]
Gradle now provides [native support](https://docs.gradle.org/4.6/release-notes.html#junit-5-support) for running tests on the JUnit Platform using the standard `test` task which does not show stdout by default. We've decided to deprecate our custom plugin (see #1317 for details) and not add any new features to it. Thus, I'm closing this issue.
