### ISSUE TITLE
Kotlin compiler chokes on jdk-10+ea-31

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1169]
## Overview

It worked with build 29 and 30 of jdk-10+ea: http://jdk.java.net/10/

Blocked by https://youtrack.jetbrains.com/issue/KT-21303

## Deliverables

- [ ] Upgrade to Kotlin version that supports jdk-10+ea-31 or higher

**Comment by JLLeitschuh** [comment]
Fun times on the bleeding edge

**Comment by sormuras** [comment]
Sometimes it's no `fun`: 
```
:junit-jupiter-api:compileKotline: java.rmi.NoSuchObjectException: no such object in table
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:209)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:161)
	at com.sun.proxy.$Proxy93.clearJarCache(Unknown Source)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemon(GradleKotlinCompilerRunner.kt:215)
```

**Comment by sormuras** [comment]
Disabled the Kotlin Compiler Daemon ... now running into an ignorable(?) warning

`"w: The '-d' option with a directory destination is ignored because '-Xbuild-file' is specified"`

See https://travis-ci.org/junit-team/junit5/jobs/304295302#L751

**Comment by juergenzimmermann** [comment]
I'm getting this warning from time to time after the Kotlin daemon crashed.

**Comment by sormuras** [comment]
_"We use ASM 6.0_ALPHA in the Kotlin compiler. This problem is going to be fixed by using ASM 6.0 instead."_

https://youtrack.jetbrains.com/issue/KT-21303#comment=27-2566164

**Comment by robstoll** [comment]
Unfortunately this happens to me quite regularly lately and also for jdk-8

**Comment by sormuras** [comment]
About to disable Kotlin support on Java 10 for the time being. Seeing 99% of our build run on Java 10 is more important than waiting for Kotlin to update their shadowed ASM dependency. I guess by March 2018, when Java 10 is released, the following commit may be reverted for good.

**Comment by sormuras** [comment]
Java 10 support is expected to arrive with Kotlin **1.2.30**.

**Comment by sormuras** [comment]
Kotlin 1.2.30-EAP was just released: https://discuss.kotlinlang.org/t/kotlin-1-2-30-eap/6479

It will fix this issue. See PR #1278 "Upgrade to Kotlin 1.2.30"

**Comment by sormuras** [comment]
Resolved in master via https://github.com/junit-team/junit5/commit/00aa2c4e63fa6e783477b27f55a74a736d180294

**Comment by sormuras** [comment]
Thanks for the heads-up.

The underlying reason here was an out-dated ASM version used by the Kotlin compiler.
