### ISSUE TITLE
Ensure that method names containing special characters can be selected by "fully qualified method name"

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-team/junit5#1170]
## Overview

Discussion started on this PR #1164

Other JVM languages allow special characters in method names (e.g., Kotlin, Groovy, etc.) which are forbidden in Java source code. EG: 🦆 

In the above noted PR I introduced a test that makes sure that the engine can call methods that aren't valid methods in Java. The test that I wrote a method that looked like this:

```kotlin
@Test
fun `🦆 ~|~test with a really, (really) terrible name & that needs to be changed!~|~`() { }
```

There was a comment that this doesn't quite go far enough:

> FYI: this verifies that a test method can have such a name and that it can be executed; however, it does not verify that such a method can be selected by it's "fully qualified method name" as was brought up on Gitter. So we'll still need to address that.
> \- @sbrannen 

There should be additional tests added to ensure that tests can be selected using their fully qualified names.

## Deliverables

- [x] Test ensuring that methods with strange characters can be selected using their "fully qualified method name"
- [x] Remove duplication in `DiscoverySelectors` and `ReflectionUtils` regexes for matching fully qualified method names
- [x] Document in Release Notes.

**Comment by marcphilipp** [comment]
Thanks for creating the issue, @JLLeitschuh!

**Comment by sbrannen** [comment]
👍

**Comment by mmerdes** [comment]
When running `org.junit.jupiter.engine.kotlin.ArbitraryNamingKotlinTestCase` in the latest version of Idea
it can be executed, but not selected and re-executed from the tree GUI:
`org.junit.platform.commons.util.PreconditionViolationException: org.junit.jupiter.engine.kotlin.ArbitraryNamingKotlinTestCase#🦆 ~|~test with a really, (really) terrible name & that needs to be changed!~|~ is not a valid fully qualified method name`
Not quite sure yet whether this is due to the problem at hand or to Idea's special way of integration.

**Comment by JLLeitschuh** [comment]
What version of IntelliJ are you using, for reference?

**Comment by mmerdes** [comment]
in progress

**Comment by mmerdes** [comment]
@JLLeitschuh 
Intellij Idea version: 2017.2.6 (released November 13)

**Comment by sbrannen** [comment]
FWIW, rerunning that test method in Eclipse Oxygen 4.7.1a also works.

**Comment by sbrannen** [comment]
But... that's likely because both IDEs rerun test methods by selecting them by `UniqueID` which does **not** involve a regular expression to parse out the method name.

**Comment by sbrannen** [comment]
As I [mentioned on Gitter](https://gitter.im/junit-team/junit5?at=5a08c4bedf09362e67fdbd69), ...

> it's most likely just a limitation of the RegEx I wrote.

... for parsing a "fully qualified method name". 😉

**Comment by mmerdes** [comment]
yes, the regex seems involved

**Comment by mmerdes** [comment]
@sbrannen 
rerunning does *not* work in idea but rather gives the "...is not a valid fully qualified method name"-exception

**Comment by sbrannen** [comment]
> @sbrannen
rerunning does not work in idea but rather gives the "...is not a valid fully qualified method name"-exception

Ahhh... then I'd consider that a bug in IDEA: IDEA should rerun based on the Unique ID like Eclipse does. 😇

**Comment by sbrannen** [comment]
> Ahhh... then I'd consider that a bug in IDEA: IDEA should rerun based on the Unique ID like Eclipse does. 😇

@akozlova, thoughts?

**Comment by akozlova** [comment]
It isn't possible to run tests by unique id from the editor as there is no unique id available. Idea uses the same configurations for running tests from the editor as well as for rerunning. Why rerunning from view should create another configuration? 
Btw uniqueIds don't solve rerunning dynamic tests problems. Probably they can work well for custom engines, this is worth checking.

 But normal tests should be discovered by vm names, everything else looks like a workaround

**Comment by sbrannen** [comment]
> But normal tests should be discovered by vm names, everything else looks like a workaround

Fair enough. 😉 

I was just thinking that the particular use case of rerunning a test with a name that would not be valid in Java would work when using the unique IDs.... which is in fact the case in Eclipse. However, you're correct: it's just a workaround for the underlying problem (i.e., the fact that my regular expression does not allow parentheses _within_ the method name).

**Comment by sbrannen** [comment]
@mmerdes, what's the current status of this issue? Are you still actively working on the fix?

**Comment by mmerdes** [comment]
Yes, planning to  resume after Christmas time :)

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Resolved in `master` in commits 54241c67dc9969134c9108408556611f6d9d1980 and e053eea82ced73e010a85f4f6a1be2a2d17d13e3.

**Comment by JLLeitschuh** [comment]
@sbrannen Can you give a high level explanation of what the solution was?

**Comment by sbrannen** [comment]
Sure...... get rid of the regular expressions and use basic index-based text parsing instead.

Or did you want more details than that? 😉

**Comment by sbrannen** [comment]
Basically, the code is in this commit: e053eea82ced73e010a85f4f6a1be2a2d17d13e3

**Comment by sbrannen** [comment]
Specifically the changes to `DiscoverySelectors.selectMethod(String)` here:

https://github.com/junit-team/junit5/commit/e053eea82ced73e010a85f4f6a1be2a2d17d13e3#diff-edf29eb7e361599ea92ff18c258be7b9
