### ISSUE TITLE
ClassNameFilter should not be used on @Nested test classes

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#118]
Currently a class name filter also filters out nested test classes. Since those are merely a means to structure the tests of a given test class, a test class filter should not be used on them.

This should probably hold for all filters derived from `ClassFilter`. Maybe `ClassFilter` should be renamed to `TopLevelClassFilter` or alike to reflect the narrower purpose.

**Comment by bechte** [comment]
I agree, that the filtering should be more precise on what it is filtering and how filters get applied.

For this concrete example, I think we need to define what a `ClassNameFilter` should do. E.g. if it filters based on the simple class name, then this is a bug, of course. If it filters based on the full qualified class name then it is not a bug, but does not have a precise name.

For the moment, I suggest we rename `ClassNameFilter` into `FullQualifiedClassNameFilter`.

I am not happy with the idea of having a `TopLevelClassFilter`. I think we should not tie together the types of filters available and the hierarchy of Java elements at which we currently search for tests.

I would like to wait before we extend the filter capabilities of the current state until we have a more flexible discovery approach. For me the filters have an influence on the test discovery and, therefore, our discovery mechanism should declare how filters are defined and applied. As this is in change, we should wait until this is somehow stable.

**Comment by jlink** [comment]
I like the name `FullyQualifiedClassNameFilter`. What it would mean,
though, is that the regular expression has to allow the test class itself
plus any additional nested classes. That does not feel intuitive.


`TopLevelClassFilter` could keep the current regular expressions with, I
think, the intuitive behaviour that all tests and children tests are being
executed when a class is accepted as test class. Maybe
`ContainerClassFilter` would better reflect that a container that is
accepted by the filter will be executed with everything.



2016-01-16 18:17 GMT+01:00 Stefan Bechtold <notifications@github.com>:

**Comment by jlink** [comment]
Team decision:
- Class filters will not be applied on class annotated with `@Nested`. Nested classes will be included if their parent is included.
- `ClassFilter` and `ClassNameFilter` will NOT be renamed.

**Comment by sbrannen** [comment]
Is this still considered a _bug_?

**Comment by jlink** [comment]
Until it is fixed.

**Comment by jlink** [comment]
Fixed in https://github.com/junit-team/junit5/commit/262c0f09d7d891c27c478c86f290c63aabdfd980
