### ISSUE TITLE
 class extending TestDataPublisher not being detected by jenkins for new plugin 

### ISSUE THREAD

**Issue by vishnu1295** [junit-team/junit5#1181]
I am working on a custom plugin for modifying test reports. I have :
`public class CheckTestDataPublisher extends TestDataPublisher`
which overrides `contributeTestData()` and `getTestAction()`.
Yet, both are not called once the test results are collected.

**Comment by marcphilipp** [comment]
What's a `TestDataPublisher`? It's not from junit5 anyway...

**Comment by marcphilipp** [comment]
Closing due to lack of feedback. Feel free to comment or re-open if the issue persists.
