### ISSUE TITLE
Add support to assert the content of two iterables, ignoring the element order

### ISSUE THREAD

**Issue by u6f6o** [junit-team/junit5#1189]
## Feature Request

I'd like to introduce an assertion that checks the content of two iterables, ignoring the elements order. For example, having two iterables, all currently available assertions take the order into account: 

```java    
   @Test
    void testIterablesEquality() {
        final List<String> expected = new ArrayList<>();
        expected.add("FOO");
        expected.add("BAR");

        final List<String> actual = new ArrayList<>();
        actual.add("BAR");
        actual.add("FOO");

        assertThrows(AssertionFailedError.class, () -> assertEquals(expected, actual));
        assertThrows(AssertionFailedError.class, () -> assertIterableEquals(expected, actual));
    }
```
A first draft of such an assertion could look like the following: 

```java  
   public static void assertIterableContentIgnoreOrder(Iterable<?> expected, Iterable<?> actual) {
        Map<Object, Integer> tmpMap = new HashMap<>();

        for (Object obj : expected) {
            tmpMap.putIfAbsent(obj, 0);
            tmpMap.compute(obj, (o, cnt) -> cnt + 1);
        }
        for (Object obj : actual) {
            Integer count = tmpMap.get(obj);
            if (count == null) {
                fail("Occurrences of " + obj + " greater in actual iterable.");
            }
            if (count > 1) {
                tmpMap.compute(obj, (o, cnt) -> cnt - 1);
            } else {
                tmpMap.remove(obj);
            }
        }
        if (!tmpMap.isEmpty()) {
            fail("Iterables content differs.");
        }
    }
```

**Comment by sbrannen** [comment]
I cannot speak for the rest of the team, but my gut feeling is that we don't want to increase the complexity of the simple `Assertions` provided by JUnit Jupiter.

For more advanced uses cases (like the one you describe), we generally recommend the use of a dedicated third-party assertion library such as AssertJ, Hamcrest, Truth, etc.

For example, using AssertJ your test could be rewritten as follows.

```java
import static org.assertj.core.api.Assertions.assertThat;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Test;

class IterableTests {

	@Test
	void lists() {
		List<String> expected = Arrays.asList("FOO", "BAR");
		List<String> actual = Arrays.asList("BAR", "FOO");

		assertThat(actual).containsAll(expected);
		// or...
		assertThat(actual).containsExactlyInAnyOrder("FOO", "BAR");
	}

}
```

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, I have assigned this to 5.1 M2 in order to discuss amongst the team.

**Comment by u6f6o** [comment]
Thanks for mentioning AssertJ and Truth, I did not know about them. After all, I think I would also try to keep the complexity low and go with one of the mentioned libraries otherwise.

**Comment by sormuras** [comment]
> [...] we don't want to increase the complexity of the simple Assertions provided by JUnit Jupiter.

+1

**Comment by sbrannen** [comment]
> Thanks for mentioning AssertJ and Truth, I did not know about them.

You mean... you haven't read the [JUnit 5 User Guide](http://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions-third-party)? 😜

**Comment by sbrannen** [comment]
**Team Decision**

- Decline feature request in favor of recommendation to use third-party assertion libraries.
