### ISSUE TITLE
Document best practices for implementing ParameterResolvers

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1190]
## Overview

Based on discussions in #1184 and https://github.com/weld/weld-junit/issues/3, it is apparent that we need to document _best practices_ for implementing `ParameterResolver`, particularly with regard to "playing nicely" with other registered `ParameterResolver` implementations.

## Proposed Categories

After having put a bit more thought into the subject, I am tossing around the idea of categorizing `ParameterResolver` implementations by behavior as follows.

- **explicit**: support requires an annotation for disambiguation.
- **implicit**: support is automatic for types _owned_ by the resolver.
- **speculative**: a resolver claims it _can_ support a given parameter even if it potentially _should not_ (a.k.a., _greedy_ or _eager_).

## Deliverables

- [ ] Document best practices for `ParameterResolver` implementations in JavaDoc.
  - more succinct than the documentation in the User Guide
- [ ] Document best practices for `ParameterResolver` implementations in the User Guide.
  - including examples and explanations of how to avoid conflicts

**Comment by sbrannen** [comment]
Update: added _Proposed Categories_ section to issue.

**Comment by rumpfc** [comment]
Can you also provide examples for error/exception handling within `ParameterResolver` which are actually not `ParameterResolutionExceptions` (i.e. `resolveParameter()` reads a File where an `IOException` is thrown).

**Comment by slinkydeveloper** [comment]
Hey @marcphilipp @sbrannen, can you please re-open this issue? I think it's still relevant, as right now it's not clear how to develop a `ParameterResolver` that doesn't conflict with other parameter resolvers, and in particular to create one that doesn't conflict with `ParameterizedTest`. I'm also willing to help with the review of the doc.

My use case is that I want to create a test matrix combining several `TestTemplateInvocationContextProvider`, in particular my own `ParameterResolver` (injected through an implementation of `TestTemplateInvocationContextProvider`) and `@ParameterizedTest`.

**Comment by sbrannen** [comment]
> can you please re-open this issue? I think it's still relevant, as right now it's not clear how to develop a `ParameterResolver` that doesn't conflict with other parameter resolvers, 

Sure. I'll reopen this issue.

> and in particular to create one that doesn't conflict with `ParameterizedTest`. 

That aspect is already covered in the [current documentation](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-consuming-arguments).

**Comment by jabhatfield** [comment]
PR for this issue had some formatting violations, now fixed.
