### ISSUE TITLE
Support @ParameterizedTest in conjunction with @TestFactory

### ISSUE THREAD

**Issue by reitzmichnicht** [junit-team/junit5#1192]
## Overview

I started to write some dynamic tests, and now it would be handy to reuse some `@ParameterizedTest` functionality I already implemented.

Take a look at this example:

```java
  @ParameterizedTest(name = "{0}")
  @ArgumentsSource(ClassArgumentsProvider.class)
  @TestFactory
  Stream<DynamicTest> apiGuards(Class<?> c) {
    return ApiGuardHelper.checkGuards(() -> EnhancedRandom.random(c));
  }
```

This should generate some dynamic tests for each class found in the package, but sadly the `@ParameterizedTest` annotation is not supported with a `@TestFactory` method.

Kind regards,
Michael

## Related Issues

- #871
- #878

**Comment by sbrannen** [comment]
Why don't you just extract the logic from your `ClassArgumentsProvider` that generates the stream of classes and use that stream directly within your `@TestFactory` method to generated the `Stream<DynamicTest>` (instead of the `Stream<Arguments>` created in your provider)?

You could put that in a common utility and use the utility (e.g., static factory method) both from your provider as well as in test factories.

**Comment by sbrannen** [comment]
FWIW, it is not feasible for JUnit Jupiter to treat a single method as two containers simultaneously: it just doesn't make sense.

Note that a `@ParameterizedTest` and a `@TestFactory` are both technically _containers_ as opposed to _tests_ (in terms of `org.junit.platform.engine.TestDescriptor.Type`).

**Comment by sbrannen** [comment]
Relates to #871 and #878.

**Comment by sbrannen** [comment]
Assigned to 5.1 backlog for team discussion.

**Comment by sbrannen** [comment]
> `ApiGuardHelper`

Is this related to the API Guardian project created by the JUnit 5 team?

**Comment by reitzmichnicht** [comment]
This is my junit5 implementation of guard assertions as described here:
https://madstt.dk/verify-your-guards-with-autofixture/

It takes all public methods of a class and checks if null arguments are safely handled. So it generates for each parameter of each method a dynamic test. Now I want combine this to get these tests generated for each class in the package. So I want nested Testcontainers like nested classes:
GuardTest
-- Class A
-- -- Method B Param1
-- Class C
...

Combining a TestFactory with ParametrizedTest was the most obvious for me.

**Comment by sbrannen** [comment]
> I want nested Testcontainers like nested classes

We actually already have support for nested dynamic containers! 😉 

In the [Dynamic Test Examples](http://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests-examples) section of the User Guide you'll find a test method named `dynamicTestsWithContainers()` which demonstrates this feature.

I think that will cover your needs, but please reply here to let us know in any case.

Cheers!

Sam

**Comment by sormuras** [comment]
Here is another [usage](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/java/org/junit/platform/console/ConsoleDetailsTests.java) of dynamic containers which produces a tree like:

![consoledetailsteststree](https://user-images.githubusercontent.com/2319838/33430547-2f2c88ea-d5d1-11e7-9d5a-04a05b9dab74.PNG)

**Comment by reitzmichnicht** [comment]
When it is supported by code to have nested dynamic containers it should also be possible by annotation.
It's always better to have tests maintainable and understandable which is more given by annotations instead of creating dynamic containers in code.

**Comment by marcphilipp** [comment]
I'm closing this issue as "declined".

**Comment by prdoyle** [comment]
Re @sbrannen "Why don't you just extract the logic from your `ClassArgumentsProvider`" - because I'm already using it with other `@Test` methods, and I want to use the same set of arguments in a `@TestFactory`.
