### ISSUE TITLE
Surefire does not execute single test method when selected via system property

### ISSUE THREAD

**Issue by AlejandroJadzinsky** [junit-team/junit5#1193]
I'm trying to do this `mvn test -Dtest=SingleMethodTest#firstMethod`, but Maven Surefire executes all the test methods.

- here you can check the [test](https://github.com/AlejandroJadzinsky/junit5-test)

-   used versions
<surefire.version>2.19.1</surefire.version>
<junit-jupiter.version>5.0.1</junit-jupiter.version>
<junit-platform.version>1.0.1</junit-platform.version>

- expected result 
only 'firstMethod' is tested.

**Comment by sbrannen** [comment]
Assigned to 5.1 backlog for further investigation.

**Comment by marcphilipp** [comment]
Our Surefire provider does currently not support the `test` parameter. The provider would need to process the included/excluded patterns in `providerParameters.getTestRequest().getTestListResolver()` and add one or multiple `PostDiscoveryFilters`.

I'm putting this issue "up-for-grabs".

**Comment by lutovich** [comment]
Hi @marcphilipp, can I work on this issue?

**Comment by marcphilipp** [comment]
@lutovich Absolutely!

**Comment by sbrannen** [comment]
@nishant-shah-spider, this repository is for **JUnit 5**.

If you are having issues with **TestNG** and Maven Surefire, please raise an issue against Maven Surefire.
