### ISSUE TITLE
Correct class names for surefire test reports generated tests

### ISSUE THREAD

**Issue by reitzmichnicht** [junit-team/junit5#1205]
Using Junit 5.0.2

The surefire Plugin does not output correct information for classnames in the TEST-*.xml reports for tests using `@ParametrizedTest` or `@TestFactory`
```
<testcase name="mapsToSelectionDto" classname="com.foo.bar.MapperTest" time="0.138"/>
<testcase name="mapsToLocationDto" classname="com.foo.bar.MapperTest" time="0.115"/>
<testcase name="asLocationDtoWithNullinBedPlace" classname="apiGuards()" time="0"/>
<testcase name="asLocationDtoWithNullinBedPlace" classname="apiGuards()" time="0.001"/>
```

The last two entries are generated with TestFactory and the classname is missing. The missing classname has sideeffects for Jenkins Test Results and also the SonarQube runner does not recognize them.

**Comment by reitzmichnicht** [comment]
#990

**Comment by sbrannen** [comment]
Closing this issue since it duplicates #1182.
