### ISSUE TITLE
Link to screencast in Wiki

### ISSUE THREAD

**Issue by marcobehler** [junit-team/junit5#1206]
Hi guys
(I already asked on Twitter and Sam Brannen told me to open up a Github issue, so here we are:)

Although this might come off as blatant self promotion, I was wondering if you guys were willing to link to 
[this screencast on "What's new in Junit 5?"](https://www.marcobehler.com/episodes/93-what-s-new-in-junit-5) from the Wiki?

Cheers,
Marco

**Comment by sormuras** [comment]
Here you go: https://github.com/junit-team/junit5/wiki/Videos

**Comment by marcobehler** [comment]
Thank you a lot, @sormuras !
