### ISSUE TITLE
Can't filter inner classes correctly

### ISSUE THREAD

**Issue by ebrowne72** [junit-team/junit5#1207]
## Overview

- Jupiter version: 5.0.2
- Vintage version: 4.12.2

I have JUnit 4 tests inside static inner classes. Vintage finds these classes if the inner class name ends with "Test". For example:

```java
public class OuterTest {
    public static class InnerTest {
        // some tests which are found
    }
}
```

But if the inner class name does not end with "Test" then it is not found.

```java
public class OuterTest {
    public static class Inner {
        // some tests which are *not* found
    }
}
```

The default filter for test classes is `^.*Tests?$`, which is why `OuterTest$InnerTest` is found and `OuterTest$Inner` is not. But I tried setting `junitPlatform.filters.includeClassNamePatterns` to `'^.*Tests?$', '^.*Tests?\$.*$'` and it didn't find `OuterTest$Inner`. It seems like the filter isn't applied against the fully qualified class name, or the '$' is confusing it somehow.

**Comment by marcphilipp** [comment]
Thanks for raising this issue! I've added it to the 5.1 M2 milestone for team discussion.

**Comment by sbrannen** [comment]
FYI: the following works fine with JUnit Jupiter as the test engine.

```java
package org.junit.foo;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.IncludeClassNamePatterns;
import org.junit.platform.suite.api.SelectPackages;
import org.junit.runner.RunWith;

@RunWith(JUnitPlatform.class)
@SelectPackages("org.junit.foo")
@IncludeClassNamePatterns({ "^.*Tests?$", "^.*Tests?\\$.*$" })
class OuterTest {

	static class Inner {

		@Test
		void innerTest(TestInfo testInfo) {
			System.err.println(testInfo);
		}

	}

}
```

**Comment by sbrannen** [comment]
Note, however, that I have not yet tried an analogous scenario for JUnit 4 / Vintage.

**Comment by sbrannen** [comment]
FYI: the following works for JUnit 4 / Vintage...

```java

package org.junit.foo;

import org.junit.Test;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.IncludeClassNamePatterns;
import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectPackages;
import org.junit.runner.RunWith;

@RunWith(JUnitPlatform.class)
@SelectPackages("org.junit.foo")
@IncludeClassNamePatterns({ "^.*Tests?$", "^.*Tests?\\$.*$" })
@IncludeEngines("junit-vintage")
public class OuterTest {

	public static class Inner {

		@Test
		public void innerTest() {
			System.err.println("innerTest()");
		}
	}
}
```

**Comment by sbrannen** [comment]
@ebrowne72, you're using the JUnit Platform Gradle plugin to run these tests -- right?

**Comment by sbrannen** [comment]
Your regular expression is simply missing a backslash which is required to escape the `$` in a Java RegEx.

The following configuration in the Gradle build works fine for the example in my previous comment.

```groovy
junitPlatform {
	selectors {
		packages 'org.junit.foo'
	}
	filters {
		includeClassNamePatterns '^.*Tests?$', '^.*Tests?\\$.*$'
	}
}
```

I am therefore closing this issue as "works as designed".
