### ISSUE TITLE
Enhancement request : Introduce a way to distinguish between test failures and errored out tests

### ISSUE THREAD

**Issue by jaikiran** [junit-team/junit5#1208]
Consider the following test case:

```
public class SomeTest {

    @Test
    public void testOne() {
       Assert.assertEquals(1, 2);
    }

   @Test
   public void testTwo() {
       Integer i = null;
       i.toString(); // leads to NPE
   }
}
```

Both these test methods are expected to fail. Right now, the JUnit *platform* doesn't distinguish between these two different types of failures. I consider the `testOne` to be a "failure" where as the `testTwo` as an error. 

It would be good to have this distinction available at the platform level, through platform APIs, so that test engines can (optionally) mark certain types of exceptions as "failures" and that information then gets propagated all the way back to the `TestExecutionListener`(s) so that the `TestExecutionResult` has a way to distinguish between such failures.

Right now, the only way to do that in a framework that integrates with JUnit 5 platform is something like this in a TestExecutionListener:

```
public void executionFinished(final TestIdentifier testIdentifier, final TestExecutionResult testExecutionResult) {
    switch (testExecutionResult.getStatus()) {
        case SUCCESSFUL: {
            // succeeded
            break;
        }
        case FAILED: {
            if (testExecutionResult.getThrowable() instanceof <some.testengine.specific.exception.class>) {
                // consider this a failure
            } else {
                // consider this an error
            }
            break;
        }
        case ABORTED: {
            // aborted
        }
    }
}
```
As you can see the `if` is testing against a specific test engine specific exception class which isn't a good thing and most of the times not feasible (since it adds a compile time dependency on the test engine specific libraries in the framework).

**Comment by rumpfc** [comment]
JUnit throws an `java.lang.AssertionError` exception within each `Assertions.assertXXX(...)` method. This exception is derived from `java.lang.Error`

Eclipse defines a test as
* FAILURE whenever an exception derived from `java.lang.Error` is thrown
* ERROR whenever a `Throwable` which is not derived from `java.lang.Error` is thrown

**Comment by jaikiran** [comment]
>> JUnit throws an java.lang.AssertionError exception within each Assertions.assertXXX(...) method. 

You are right, the JUnit test engine does do that and I can probably rely on that knowing that it does. But I was wondering if there can be a contract between the JUnit platform and various test engines, so that the test listeners won't have to bother about whether or not each of the test engines out there follow this convention.

**Comment by rumpfc** [comment]
I'm not sure, but these two should return the same value for the same test:
http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/extension/ExtensionContext.html#getUniqueId--
http://junit.org/junit5/docs/current/api/org/junit/platform/launcher/TestIdentifier.html#getUniqueId--

Maybe you can connect this with a singleton class or something

**Comment by marcphilipp** [comment]
The distinction between failures and errors was given up in JUnit 4. We will not add it back. If you want to distinguish between failed assertions and other exceptions, please simply check for `instanceof AssertionError`.
