### ISSUE TITLE
Introduce implicit argument conversion for URI and Currency

### ISSUE THREAD

**Issue by juergenzimmermann** [junit-team/junit5#1218]
Tests for business apps will be easier when `@ParameterizedTest` tests also have implicit argument conversions for `java.net.URI` and `java.util.Currency` -- just as today for e.g. `LocalDate`.

**Comment by marcphilipp** [comment]
I think that makes sense! Feel free to submit a pull request for it. 😉

**Comment by sormuras** [comment]
This [Currency](https://docs.oracle.com/javase/9/docs/api/java/util/Currency.html) (which is present since Java 1.4)?

**Comment by juergenzimmermann** [comment]
Yes, I mean `java.net.URI` and `java.util.Currency`.

**Comment by sbrannen** [comment]
While we're at it, I think we should go ahead and support implicit conversions for `java.util.Locale` as well (using the `java.util.Locale.Locale(String)` constructor).

@juergenzimmermann, care to implement and test that support as well?

**Comment by hisener** [comment]
@sbrannen I can add it to the PR (#1221)?

**Comment by sbrannen** [comment]
> @sbrannen I can add it to the PR (#1221)?

Yep, that's what I had in mind.

**Comment by sbrannen** [comment]
_in progress_ in #1221

**Comment by sbrannen** [comment]
Resolved in 1dc5c06669a225067d6cd674d297209e9f96204c
