### ISSUE TITLE
ClasspathScanner loads all classes causing class visibility side effects

### ISSUE THREAD

**Issue by almondtools** [junit-team/junit5#1220]
Migrating my Tests from JUnit 4 got stuck because my productive code (not test code) contains a class that MUST be loaded with the system/bootstrap class loader (the code is quite complex).

JUnit Jupiter seems to scan all classes and loads them with the current classloader. The latter is a problem for me, because an already loaded class shadows the one which is loaded later on (in the test) by the system classloader (meaning that the test operates on a different class than the rest of the program).

Maybe it would be better to do classpath scanning in a separate classloader (and reload only those classes that were qualified by the scanner).

If you are interested in an example I will prepare a branch in my github project to contain only the classes that provoke this error.

**Comment by marcphilipp** [comment]
How do you execute your tests? Can you set a class/package name filter? IIRC the scanner only loads classes that pass the name filters.

**Comment by almondtools** [comment]
The test is executed with eclipse. The error does not occur if I start the test class isolated, i.e. if the there is no classpath scanning at all.

You are right, the classname filter is applied before class loading. Can you give me a hint how to configure this in eclipse?

**Comment by marcphilipp** [comment]
> So a workaround for my problem does exist - and the eclipse launcher could be optimized to restrict the ClasspathScanner to the classes from the testdirectory (which is probably not your issue).

Glad you found a workaround! Could you please open an issue with Eclipse for this?

> I am yet not settled about the deeper problem with the ClasspathScanner. What do you think about separating class scanning and class loading. I think the majority of projects will not require it, but it leads to very strange and hard to debug behaviours.

We rely on reflection to determine whether a class is a potential test class, e.g. to look at annotations. Thus, we need to load the class after it passed the name filter. Am I missing something?

**Comment by almondtools** [comment]
I would open an eclipse issue if I knew how to fix it. Unfortunately Eclipse does not distinguish code and test directories, so there could not be a generic way to restrict Junit to the test directory.

I agree that class loading is necessary if one depends on reflection. There may be solutions without selection (e.g. reading the bytecode and filtering on a byte code abstraction), yet my suggestion was the following:

* use two class loaders: the common class loader (given in the current code) and the IsolatedClassLoader (this one loads classes but does not automatically propagate classes to the common class loader)
* the ClasspathScanner uses the IsolatedClassloader, such that all side effects caused by reflective class loading are restricted to classes that are never used in the later tests
* all filterings on classes are applied on the classes of IsolatedClassloader
* after all filterings are applied the resulting set of classes is reloaded with the common class loader

This way allows to load all classes, but the side effects do only apply if the loaded class is qualified as test.

Maybe the scenario is too specific to deserve a resolution, in the other case I could spend some effort on finding a reproducable failing test case (and assist in writing a patch of ClassPathScanner).

**Comment by sormuras** [comment]
> [...] Unfortunately Eclipse does not distinguish code and test directories, so there could not be a generic way to restrict Junit to the test directory.

Almost there: https://bugs.eclipse.org/bugs/show_bug.cgi?id=224708

**Comment by marcphilipp** [comment]
Do we have an idea how much loading every class that passes the filter twice would impact the performance of the classpath scanner? Since most people won't run into this problem, we could implement it as an opt-in feature.
