### ISSUE TITLE
Dependency Diagram missing in User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1222]
## Overview

There is a bug in the Gradle plugin for Asciidoctor (https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/222) which prevents the diagram from being generated if the Gradle daemon is running.

## Workaround

The following (which disables the Gradle daemon) generates the diagram on my local machine:

`gradle --no-daemon :documentation:clean ascii`

## Original Assumption

Due to recent changes to the build, the _Dependency Diagram_ created with Plant UML is no longer included in the snapshot build for the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/#dependency-diagram), and we now see the following warning during the build.

`asciidoctor: WARNING: overview.adoc: line 146: invalid style for listing block: plantuml`

## Deliverables

- [ ] Ensure that the _Dependency Diagram_ is included in the User Guide -- for example, by disabling the Gradle daemon when generating the User Guide on the CI server.

**Comment by sbrannen** [comment]
This is potentially due to changes in commit 6b945ebf9a7d2f75b1fd843e0e9ffa2125412066.

**Comment by sbrannen** [comment]
@marcphilipp, I've tentatively assigned this issue to you since you made the latest changes to the documentation build.

**Comment by sbrannen** [comment]
Actually, commit 4a1757d7aec18edfe21ce40e769833cbd7093015 seems to be the culprit.

**Comment by sbrannen** [comment]
After further analysis it appears to be a bug in the Gradle plugin for Asciidoctor: https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/222

The following (which disables the Gradle daemon) generates the diagram on my local machine:

`gradle --no-daemon :documentation:clean ascii`

**Comment by marcphilipp** [comment]
I may be missing something, but Jenkins already uses `--no-daemon` and generates the diagram just fine. 🤔

**Comment by sbrannen** [comment]
> I may be missing something, but Jenkins already uses `--no-daemon` and generates the diagram just fine. 🤔

Hmmmm.... maybe _I'm_ missing something!

I thought I observed that it was missing on the published Web site, but perhaps I'm mistaken.

In any case, it definitely doesn't work locally with the daemon running.

Let's leave this issue open for a little longer to see if things continue to work well for the published snapshot docs.

**Comment by sbrannen** [comment]
Seems like things are A-Okay for the snapshots.

So I'm closing this issue.
