### ISSUE TITLE
CDATA end marker in exception message of failed test must not break XML output

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1225]
## Overview

Exception messages that contain the XML CDATA end marker `]]>` currently cause the XML output to be invalid, e.g. the message `<foo><![CDATA[bar]]></foo>` results in the following document:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Engine" tests="1" skipped="0" failures="1" errors="0" time="0" timestamp="2018-01-04T13:33:43">
<testcase name="test" classname="Engine" time="1,515,069,223.854">
<failure message="&lt;testsuite&gt;&lt;![CDATA[foo]]&gt;&lt;/testsuite&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: <foo><![CDATA[bar]]></foo>
	at  ...
]]></failure>
</testcase>
</testsuite>

```

## Deliverables

- [ ] Ensure exception messages that contain the CDATA end marker `]]>` result in valid XML

**Comment by sbrannen** [comment]
Thanks for the super quick turn-around on that one! 👍
