### ISSUE TITLE
TestTemplateInvocationContextProvider should have type bounded return to allow implementations to more easily return TestTemplateInvocationContext implementations

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#1226]
## Overview

The signature of `Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContexts(ExtensionContext context);` requires casting under certain implementation conditions. For example, one usage where I am forced to cast the implementation type to the interface type is here: https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/blob/b1d0b2f207cf2d28d96fa8e16692fda657abfb75/src/test/kotlin/testsupport/MultiVersionGradleProjectTestTemplate.kt#L35-L43

Contrived example:

Java:

```java
class NoExtends implements TestTemplateInvocationContextProvider {

    @Override public boolean supportsTestTemplate(final ExtensionContext context) { return false; }

    @Override
    public Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContexts(ExtensionContext context) {
      // Dumb example, but would be something more complex context.getTestInstance().map(i -> Stream.of(DummyContext))
      // or context.getConfigurationParameter().map()
      Stream<DummyContext> s = Stream.of(new DummyContext());
      return s;
    }
    private static class DummyContext implements TestTemplateInvocationContext {}
  }
```

Fails to compile to do incompatible type of `Stream<DummyContext>` and `Stream<ExtensionContext>`.

_Proposal_: change `Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContexts(ExtensionContext context);` to `Stream<? extends TestTemplateInvocationContext> provideTestTemplateInvocationContexts(ExtensionContext context)`, but it looks to be backwards compatibility breaking change based on the discussion on the Gitter and my understanding of https://wiki.eclipse.org/Evolving_Java-based_APIs_2#Evolving_API_interfaces_-_API_methods

> Add, delete, or change type bounds of type parameter | - | **Breaks compatibility** -- | -- | --

I do believe that implementations of the `TestTemplateInvocationContextProvider` would still be able to compile with no changes but I don't know the runtime implications.

## Deliverables

- [ ] ...

**Comment by marcphilipp** [comment]
Hmm, in hindsight `Stream<? extends TTIC>` might have been better. I'm hesistant to change it now because it's a breaking change and very easy to work around.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment]
Slated for 5.1 M2 in for _team discussion_ prior to the 5.1 GA release.

**Comment by marcphilipp** [comment]
Team Decision: Although it is a minor inconvenience, we have decided not to go for this breaking change. It will, at the very least, break tests of implementors of `TestTemplateInvocationContext` that assign the result of `provideTestTemplateInvocationContexts(...)` to a local variable etc.
