### ISSUE TITLE
Introduce DiscoverySelectors for files and folders

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#123]
## Status Quo

`DiscoverySelectors` can currently select package names, class names, and method names.

Other names (files, specs, etc.) which might be needed by other engines are not yet supported.

## Related Issues

- #301
- #453

## Deliverables

- [x] Support selection of files in the file system.
- [x] Support selection of folders in the file system.

**Comment by jlink** [comment]
This probably requires to introduce a new Selector which will be resolved by engines. This is too big a change for Milestone 1. Moving issue to backlog.

**Comment by sbrannen** [comment]
Updated issue title and description.

**Comment by sbrannen** [comment]
Addressed in commit 4fa01d554e14069ee0655e7fad23a9b9ea6bc8b9.

**Comment by sbrannen** [comment]
Reopening this issue in order to switch to storing the "raw path" instead of a `java.io.File` reference for selected files and directories.

**Comment by sbrannen** [comment]
Closing this issue since the latest changes have been pushed in decaeffc5566049ca2eee3bf09d8dd911907adcd.
