### ISSUE TITLE
"junitPlatformTest" Gradle task does not handle dependencies defined by the Java Library plugin

### ISSUE THREAD

**Issue by cmakshin** [junit-team/junit5#1233]
Using `JavaExec` as the base for "junitPlatformTest" task breaks Gradle builds which:
* use Java Library plugin for better/proper separation of interface and implementation dependencies;
* have a dependency with direction opposite to the lexicographical order of projects' names.

An example can be found at https://github.com/cmakshin/junit5-bugs:
Java 9
Gradle 4.4.1
JUnit Platform 1.1.+ (tested with 1.1.0-M1)
JUnit Jupiter 5.1.+ (tested with 5.1.0-M1)

Project "atestproject" depends on "projectB" which depends on "projectA" (all dependencies are specified as "implementation").

Running `gradlew -m -PnoDummyTest=y build` will produce this output (I removed some irrelevant lines):
```
:projectA:compileJava SKIPPED
:projectB:compileJava SKIPPED
:atestproject:compileJava SKIPPED
...
:atestproject:junitPlatformTest SKIPPED
...
:projectB:jar SKIPPED
:atestproject:test SKIPPED
```
An actual build would fail at ":atestproject:junitPlatformTest" because its runtime classpath includes the output of ":projectB:jar".

Adding a dummy Test task and making it a dependency of "junitPlatformTest"
```
task dummyTest(type: Test) {
   enabled = false
}

junitPlatformTest {
    dependsOn.add(dummyTest)
}
```
fixes the problem (`gradlew -m build`):
```
:projectA:compileJava SKIPPED
:projectB:compileJava SKIPPED
:atestproject:compileJava SKIPPED
...
:projectB:jar SKIPPED
:atestproject:dummyTest SKIPPED
:atestproject:junitPlatformTest SKIPPED
:atestproject:test SKIPPED
```

This workaround implies that task ordering has nothing to do with the implementation of the standard "test" task.

**Comment by marcphilipp** [comment]
This seems to be related to all the module path specific config you've added. [When I remove it](https://github.com/marcphilipp/junit5-bugs/commit/15d404bd8ee457fb531fd5a680a69deecfe70796), it works as expected:

```
:projectA:compileJava SKIPPED
:projectB:compileJava SKIPPED
:atestproject:compileJava SKIPPED
...
:atestproject:testClasses SKIPPED
...
:projectB:jar SKIPPED
:atestproject:junitPlatformTest SKIPPED
:atestproject:test SKIPPED
:atestproject:check SKIPPED
:atestproject:build SKIPPED
```

Any ideas which part of your configuration might cause this?

**Comment by cmakshin** [comment]
Commenting/removing the "enableModulePath = true" line in "atestproject/build.gradle" without changing anything else fixes the task order. I've done some semi-random experiments, trying to find a connection between these two seemingly unrelated things, but failed to find anything.

**Comment by sormuras** [comment]
Mh, I encountered a similar bogus behaviour when testing #1234 here: https://github.com/junit-team/junit5/blob/master/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy#L214

Still trying to find out why that boolean switch causes troubles...

**Comment by cmakshin** [comment]
My most plausible guess is that `JavaExec` uses its `classpath` parameter
to find tasks which create the needed JARs and marks these tasks as
dependencies during the task graph generation phase. "Module-path mode"
clears this parameter so `dependsOn` becomes the only source of
dependencies and the task gets executed ASAP.

Unfortunately, I won't be to check this assumption until tomorrow.

**Comment by cmakshin** [comment]
It looks like that guess about the `JavaExec` task was right (https://github.com/cmakshin/junit5-bugs/commit/b4270b29bec23e32f70c45328ba409d36cac6f60).

I added another project, "projectC", and a dummy `JavaExec` task to "atestproject":
```
task dummyJavaExec(type: JavaExec) {
    enabled = false
    classpath = project(':projectC').sourceSets.main.runtimeClasspath;
}

build {
    dependsOn.add(dummyJavaExec)
}
```

"atestproject" has no explicit (`dependencies` project block, `dependsOn` task property, etc.) dependencies on "projectC" but the new task is scheduled at the right place:
```
:projectA:compileJava SKIPPED
:projectB:compileJava SKIPPED
:atestproject:compileJava SKIPPED
...
:atestproject:junitPlatformTest SKIPPED
...
:projectB:jar SKIPPED
:atestproject:test SKIPPED
:atestproject:check SKIPPED
:projectC:compileJava SKIPPED
:projectC:processResources SKIPPED
:projectC:classes SKIPPED
:atestproject:dummyJavaExec SKIPPED
:atestproject:build SKIPPED
```

So adding test runtime classpath to the dependencies of the "junitPlatformTest" task would solve the problem (https://github.com/cmakshin/junit5-bugs/commit/94129a617f515160308673845e3b509ca032fc72).

**Comment by marcphilipp** [comment]
That would indeed explain it, thanks for looking into it!

**Comment by sormuras** [comment]
https://github.com/junit-team/junit5/blob/master/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy#L149

```java
	private void configureTaskDependencies(project, junitTask, junitExtension) {
		def testClassesTask = project.tasks.getByName('testClasses')
		junitTask.dependsOn testClassesTask
		junitTask.dependsOn project.sourceSets.test.runtimeClasspath
//[...]
```

Locally I added `junitTask.dependsOn project.sourceSets.test.runtimeClasspath`. Would that work?

**Comment by marcphilipp** [comment]
I think the dependency on the `testClasses` task is redundant, isn't it?

What about `project.configurations.junitPlatform`? Do we need to depend on that, too? What happens when the local Gradle cache is empty and `enableModulePath` is turned on?

**Comment by sormuras** [comment]
> I think the dependency on the `testClasses` task is redundant, isn't it?

All existing tests are still green after I removed that line.

> What about `project.configurations.junitPlatform`? Do we need to depend on that, too?

It doesn't hurt and with it, it mimics the default `classpath` configuration. I.e. when `enableModulePath` is `false`.

> What happens when the local Gradle cache is empty and `enableModulePath` is turned on?

Good question. I hope "Gradle will handle it". :)

**Comment by sormuras** [comment]
@cmakshin now the needed dependencies are always set via `dependsOn`. Can you please re-run your test project?

Wondering whether we should also add something similar to our default VM setup:

https://github.com/cmakshin/junit5-bugs/blob/94129a617f515160308673845e3b509ca032fc72/build.gradle#L75-L90

**Comment by cmakshin** [comment]
@sormuras the code from https://github.com/junit-team/junit5/commit/c597ca3ef67077b73bdfa8967ed51eb9d17e19ee works correctly.

> Wondering whether we should also add something similar to our default VM setup

All these options except "-ea" and "-esa" are specific to HotSpot JVM so I'm not sure it would be a good idea to use them by default. On the other hand, that stuff is kind of mandatory for testing classes in Jigsaw modules:
1) `'--patch-module', "$moduleName=" + files(sourceSets.test.java.outputDir).asPath`
is needed because Jigsaw forbids split packages;
2) `'--add-reads', "$moduleName=org.junit.jupiter.api"`
is needed because otherwise everything would fail due to unsatisfied JUnit dependencies in test classes;
3) `'--add-opens', "$moduleName/$packageName=org.junit.platform.commons"`
is needed because otherwise JUnit wouldn't be able to run tests for classes in non-exported packages and declaring the whole module as `open module ...` cripples the whole idea of strong encapsulation.

So probably not unconditionally but with either JVM detection or some boolean parameter...

**Comment by sormuras** [comment]
> "-ea" and "-esa"

Yes. We always should add those two. In class-path and module-path mode. @junit-team/junit-lambda ?

> 1.

We will support both ways: a) patching test sources into the main modules and b) patching main sources into test modules. The latter way achives the same goal as 2. and 3. do -- without leaving the modular world when designing and implementing tests.

> 2. and 3.

Needed for way a) ... not needed for way b)

Back on topic:

https://github.com/junit-team/junit5/compare/fix-modulepath-in-gradleplugin here is my current spike fixing the `module-path` issue. Our Gradle-Plugin will defer the resolution of needed artifacts to `JavaExec` execution time (similar to class-path handling of `JavaExec`) -- but now the `'--add-modules', 'ALL-MODULE-PATH'` is to broad. Some artifacts don't meet the *automatic module name extraction* needs and the whole build fails:

```
Error occurred during initialization of boot layer
  java.lang.module.FindException: Unable to derive module descriptor for [...]/groovy-all-2.4.12.jar
    Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class moduleName=groovy-all not in module
```

Potential solution: don't add all modules via `JUnitPlatformJavaExec#args.addAll('--add-modules', 'ALL-MODULE-PATH'`, only user-supplied paths and compatible/need jars by the Platform, including engines.

**Comment by sbrannen** [comment]
> > "-ea" and "-esa"
> 
> Yes. We always should add those two. In class-path and module-path mode. @junit-team/junit-lambda ?
> 

IMHO: We should support them but not configure them by default. Gradle has never done that by default, so I don't think we should either.

In any case, a user can already set those for the JUnit Platform Gradle plugin.

**Comment by sormuras** [comment]
@cmakshin I refactord the module-path support offered by our Gradle plugin from a simple `boolean` switch to a `FileCollection` taking all entries that should land on the module path at execution time.

See commit comment https://github.com/junit-team/junit5/commit/d9310999fe15b70da7ced5be4f470d4e1dc75ada

Closing this issue for good, as it was resolved. If the new support has bug or prevents your project to work correctly, feel free to open a new issue. Thanks!
