### ISSUE TITLE
Setting launcher main class name to an empty string breaks test execution on Linux

### ISSUE THREAD

**Issue by cmakshin** [junit-team/junit5#1234]
Using Java 9 module path instead of classpath by specifying
```
junitPlatform {
   enableModulePath = true
}
```
makes Gradle plugin clear the main class name string:
https://github.com/junit-team/junit5/blob/a94ef93a68edd481673a81db86b2f4d844a3e063/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy#L133

The problem is that Gradle's `JavaExec` task unconditionally adds the main class name to the list of command line parameters:
https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java#L219
```
public List<String> getAllArguments() {
    List<String> arguments = new ArrayList<String>();
    arguments.addAll(getAllJvmArgs());
    arguments.add(mainClass);
    arguments.addAll(getArgs());
    return arguments;
}
```
This breaks test execution on systems which natively support passing command line parameters as an array of strings (at least on Linux but other Unix-like systems are likely to be affected too) because JVM launcher treats this empty string as the main class name (_By default, the first argument that isn’t an option of the `java` command is the fully qualified name of the class to be called_) and fails with the following error:
```
Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 
java.lang.ClassNotFoundException: 
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:654)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:551)
```

Gradle's bug tracker already contains a somewhat related report (https://github.com/gradle/gradle/issues/1346) about the "-jar" option for executable JARs. `main = '-jar'` is suggested as a workaround there so moving the "--module" option from `args` to `main` may be used in this case.

Temporary solution for end-users:
```
junitPlatformTest {
    doFirst {
        args = args.subList(1, args.size())
        main = '--module'
    }
}
```

Gradle 4.4.1
Oracle JDK 9.0.1 on Debian GNU/Linux
JUnit Platform 1.1.0-M1
JUnit Jupiter 5.1.0-M1
Test project: https://github.com/cmakshin/junit5-bugs (does not include the temporary solution shown above)

**Comment by marcphilipp** [comment]
Thanks for the bug report, @cmakshin! Tentatively slated for 5.1 M2 for investigation.

**Comment by sormuras** [comment]
Presumably solved via https://github.com/junit-team/junit5/commit/2584afa91ac53224019cb341a61a760f2110a5b0 -- @cmakshin can you please confirm?

Awaiting your feedback and need some help to get https://github.com/junit-team/junit5/commit/2584afa91ac53224019cb341a61a760f2110a5b0#diff-a497bf488b1e717fd412900d07052bc3R214 running... before closing this issue.

**Comment by cmakshin** [comment]
@sormuras yes, that works. Thank you for quick response.
