### ISSUE TITLE
Document the extension ordering

### ISSUE THREAD

**Issue by rmannibucau** [junit-team/junit5#1238]
Hi

Can you please ensure the documentation contains how to sort extensions. Since Java sorts the annotations and keeps it into the bytecode, it is just a matter of writing the extension definition order is the one used - including nested levels of repeatable annotations. So using @SetEnv @StartServer will let the server use the env setup whereas @StartServer @SetEnv wouldnt.

Compared to Junit4 RuleChain this is way nicer but without it being explicit it can be seen as a hack since you need to check the code to ensure Junit 5 uses only array and lists and not sets for extensions.

Thanks,
Romain

**Comment by sbrannen** [comment]
> it is just a matter of writing the extension definition order is the one used - including nested levels of repeatable annotations.

This is in fact already documented in the [User Guide](http://junit.org/junit5/docs/current/user-guide/#extensions):

> The execution of tests in both `MyTestsV1` and `MyTestsV2` will be extended by the `FooExtension` and `BarExtension`, **in exactly that order**.

Does the above documentation not meet your needs?

**Comment by rmannibucau** [comment]
@sbrannen good catch. yes, it meets my need. Thanks!
