### ISSUE TITLE
Prune Release Notes

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1241]
## Deliverables

- [x] Add 5.0.3 release notes to `master`
- [x] Update "Date of Release" in 5.0.3 release notes on `master`
- [x] Prune all release notes sections prior to 5.0 GA

**Comment by sbrannen** [comment]
Haven't checked... but we might need to update additional `@since` tags in JavaDoc like I just did in commit 4c8c469332e962600ca5dab6165035ee6e9e1677.

**Comment by sbrannen** [comment]
FYI: I already took care of the `@since` tags.

**Comment by marcphilipp** [comment]
Regarding the last deliverable: Actually, I think we need to keep the duplicates in M2 because people are likely going to update from M1.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment]
I guess it would't hurt to leave the duplicates in the milestone release notes since the branches are actually parallel (i.e., `master` and `5.0.x`).

Another thing we could consider is merging all milestone and RC release note sections into a single release notes section for GA releases like 5.1. 

I'm thinking the latter would make it easier for people migrating from 5.0.x to 5.1.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment]
Also, we might want to prune all release notes sections prior to 5.0 GA for the 5.1 GA release: I'm not sure that people are interested in the release notes leading up to GA any more. 😉

**Comment by marcphilipp** [comment]
> Another thing we could consider is merging all milestone and RC release note sections into a single release notes section for GA releases like 5.1.

I was also wondering whether we should do that. I think that would definitely make it easier. 👍 

> Also, we might want to prune all release notes sections prior to 5.0 GA for the 5.1 GA release: I'm not sure that people are interested in the release notes leading up to GA any more.

The 5.0 GA release notes describe the delta to RC3 at the moment. How would we change those?

**Comment by sbrannen** [comment]
> The 5.0 GA release notes describe the delta to RC3 at the moment. How would we change those?

Well, that information already got published in the release notes section of the user guide for 5.0 GA. So, the 5.0 section in the release notes for 5.1 could simply provide a link to the 5.0 GA release online.

**Comment by sbrannen** [comment]
last deliverable: _in progress_

**Comment by sbrannen** [comment]
Closing this issue since the last task was completed in commit 179dd54547f205b3f5b72d3be4adc25db648c6de.
