### ISSUE TITLE
Document Maven test filtering support in User Guide

### ISSUE THREAD

**Issue by dmitry-timofeev** [junit-team/junit5#1245]
## Overview

Currently it might appear to a reader that only filtering by tags is supported.

Could you consider expanding the JUnit 5 User Guide with a reference to a page in Maven Surefire documentation about filtering of tests by file name or class name?

## Proposal

I think it may be as simple as

```markdown
### Filtering by Tags
…
### Filtering by Test File Name
Please refer to
[Maven Surefire documentation](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html)
to enable filtering of tests by file name or class name.
```

## Related Issues

- #1237 

## Deliverables

- [ ]  Document Maven test filtering support in the User Guide.
  - [ ] `-Dtest` system property support
  - [ ] standard Maven Surefire include and exclude support in `pom.xml`

**Comment by sbrannen** [comment]
Sure. I think it would be easy enough to add such a sentence/link.

Slated for inclusion in 5.1 M2.

**Comment by sbrannen** [comment]
Actually, now that I think about it...

It would be beneficial to document this and the `-Dtest` support added in conjunction with #1237.

So, I'll expand the scope of this issue and slate it for possible (last minute) inclusion in 5.0.3.

**Comment by sbrannen** [comment]
_in progress_
