### ISSUE TITLE
Provide a way to specify my own test method runner

### ISSUE THREAD

**Issue by MatousJobanek** [junit-team/junit5#1248]
## Overview
I'm part of Arquillian team and I've been trying to implement either Arquillian Engine or Arquilian Extension for JUnit 5. Unfortunately, nothing is feasible for now. The Engine is a bigger issue. In case of extension, there is missing only one functionality. 

## Specific problem
One of Arquillian modes is running in-container tests - executing test methods/classes inside of a container (as part of a deployment). Unfortunately, currently there is no way to tell JUnit 5 where the test should be executed or to provide my own runner that would execute the test method either on a client or in a container. I can only skip the test methods or let them run locally.

### Custom ExecutableInvoker
The easiest solution would be having an SPI (eg. using service loader) that would load inside of the [TestMethodTestDescriptor](https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java#L60) a custom implementation of the `ExecutableInvoker` class (if none is provided, then the default would be used) and execute the method using the provided invoker.

### Custom runner for test descriptors
The previous solution is easy to do, but has one side effect - the method callbacks would be executed on both sides - on a client and inside of the container (as I would need to simulate everything inside of the container again). An advanced solution would be having a possibility to provide an invoker for every `TestDescriptor` separately.

For more information about my research see this issue: https://github.com/arquillian/arquillian-core/issues/137

## Related Issues

- #157

**Comment by marcphilipp** [comment]
We're going to provide a way to execute a test (for #20 and #60) using a custom "ExecutorService"-like interface. The "Executable" we're planning to hand to this "ExecutorService" would, when executed, fire events to `EngineExecutionListeners`. I'm not sure if that would suit your needs or whether you need something more fine-grained.

Is this request different from #1145?

**Comment by marcphilipp** [comment]
I don't think providing an `ExecutableInvoker`would be sufficient. All extension code should also be executed inside the Arquillian container, shouldn't it? In addition, the class-level `@BeforeAll`/`@AfterAll` methods would have to be executed there, too, right?

**Comment by MatousJobanek** [comment]
Hi, 
thanks for your reply and for the links - yeah it is mainly related to the #20 and #1145 - to intercept/replace the execution of the particular phases - whole class or method blocks. 

`ExecutableInvoker` is the simplest solution and would be partially sufficient (there are some corner cases) - the execution of the tests inside of the container is invoked by rest calls and then the execution itself is done using JUnit 5 API with a new request:
```java
LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
    .selectors(DiscoverySelectors.selectMethod(testClass.getCanonicalName(), methodName))
    .build();
launcher.execute(request);
```
so, then I have the whole test lifecycle executed inside of the container again.

But, having the way of providing my own executor for the test method block (including the callbacks) would be the best.

**Comment by marcphilipp** [comment]
How would this work in detail?

Let's assume we introduced a new `ExecutableInvoker` interface. I imagine it would look similar to this:

```java
interface ExecutableInvoker extends Extension {
  void invoke(Executable executable, ExtensionContext extensionContext) throws Throwable;
}
```

What would the Arquillian implementation do in the non-embedded container case? Would it completely ignore the `Executable` and pass on the unique ID or test class and method from the `ExtensionContext` to the other JVM? The latter would cause class-level lifecycle callbacks to be executed again, wouldn't it?

**Comment by jonpeterson** [comment]
I'd like to see something like this so I could write an invoker and stop having to wrap all my tests that call Kotlin Coroutines `suspend` functions in `runBlocking { ... }`.

**Comment by sbrannen** [comment]
This issue is related to #157.

**Comment by arjantijms** [comment]
> This issue is related to #157.

With #157 resolved, is there any progress on this issue now?

**Comment by sbrannen** [comment]
@MatousJobanek and @arjantijms, does the support introduced in #157 and #2083 meet your needs?
