### ISSUE TITLE
The 5.0.3 Revisions Having Issues In Repo

### ISSUE THREAD

**Issue by ssanbeg** [junit-team/junit5#1249]
Result of running: mvn help:effective-pom (ran several times after rm-rf ~/.m2/repository and repopulated):

[INFO] Scanning for projects...
[WARNING] Failed to retrieve plugin descriptor for org.junit.jupiter:junit-jupiter-api:5.0.3: Failed to parse plugin descriptor for org.junit.jupiter:junit-jupiter-api:5.0.3 (/Users/ssanbeg/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.0.3/junit-jupiter-api-5.0.3.jar): No plugin descriptor found at META-INF/maven/plugin.xml

[WARNING] Failed to retrieve plugin descriptor for org.junit.jupiter:junit-jupiter-engine:5.0.3: Failed to parse plugin descriptor for org.junit.jupiter:junit-jupiter-engine:5.0.3 (/Users/ssanbeg/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.3/junit-jupiter-engine-5.0.3.jar): No plugin descriptor found at META-INF/maven/plugin.xml

[WARNING] Failed to retrieve plugin descriptor for org.junit.platform:junit-platform-launcher:1.0.3: Failed to parse plugin descriptor for org.junit.platform:junit-platform-launcher:1.0.3 (/Users/ssanbeg/.m2/repository/org/junit/platform/junit-platform-launcher/1.0.3/junit-platform-launcher-1.0.3.jar): No plugin descriptor found at META-INF/maven/plugin.xml

[WARNING] Failed to retrieve plugin descriptor for org.junit.platform:junit-platform-runner:1.0.3: Failed to parse plugin descriptor for org.junit.platform:junit-platform-runner:1.0.3 (/Users/ssanbeg/.m2/repository/org/junit/platform/junit-platform-runner/1.0.3/junit-platform-runner-1.0.3.jar): No plugin descriptor found at META-INF/maven/plugin.xml

[WARNING] Failed to retrieve plugin descriptor for org.junit.vintage:junit-vintage-engine:4.12.3: Failed to parse plugin descriptor for org.junit.vintage:junit-vintage-engine:4.12.3 (/Users/ssanbeg/.m2/repository/org/junit/vintage/junit-vintage-engine/4.12.3/junit-vintage-engine-4.12.3.jar): No plugin descriptor found at META-INF/maven/plugin.xml

**Comment by ssanbeg** [comment]
The context in which these occurs in when the pom file contains:

**Comment by ssanbeg** [comment]
...        <plugin>
          <groupId>org.junit.platform</groupId>
          <artifactId>junit-platform-runner</artifactId>
          <version>1.0.3</version>
        </plugin>
        <plugin>
          <groupId>org.junit.vintage</groupId>
          <artifactId>junit-vintage-engine</artifactId>
          <version>4.12.3</version>
        </plugin>
      </plugins>
    </pluginManagement>

**Comment by ssanbeg** [comment]
The context of this occurs when the POM contains:

`        ...
         <plugin>
          <groupId>org.junit.platform</groupId>
          <artifactId>junit-platform-runner</artifactId>
          <version>1.0.3</version>
        </plugin>
        <plugin>
          <groupId>org.junit.vintage</groupId>
          <artifactId>junit-vintage-engine</artifactId>
          <version>4.12.3</version>
        </plugin>
      </plugins>
    </pluginManagement>`

**Comment by ssanbeg** [comment]
The context in which this occurs is when running a POM containing:

>          ...
>         <plugin>
>           <groupId>org.junit.platform</groupId>
>           <artifactId>junit-platform-runner</artifactId>
>           <version>1.0.3</version>
>         </plugin>
>         <plugin>
>           <groupId>org.junit.vintage</groupId>
>           <artifactId>junit-vintage-engine</artifactId>
>           <version>4.12.3</version>
>         </plugin>
>       </plugins>
>     </pluginManagement>
>

**Comment by ssanbeg** [comment]
The context in which this occurs is when running a POM containing:

>          ...
>         <plugin>
>           <groupId>org.junit.jupiter</groupId>
>           <artifactId>junit-jupiter-api</artifactId>
>           <version>5.0.3</version>
>         </plugin>
>         <plugin>
>           <groupId>org.junit.jupiter</groupId>
>           <artifactId>junit-jupiter-engine</artifactId>
>           <version>5.0.3</version>
>         </plugin>
>         <plugin>
>           <groupId>org.junit.platform</groupId>
>           <artifactId>junit-platform-launcher</artifactId>
>           <version>1.0.3</version>
>         </plugin>
>         <plugin>
>           <groupId>org.junit.platform</groupId>
>           <artifactId>junit-platform-runner</artifactId>
>           <version>1.0.3</version>
>         </plugin>
>         <plugin>
>           <groupId>org.junit.vintage</groupId>
>           <artifactId>junit-vintage-engine</artifactId>
>           <version>4.12.3</version>
>         </plugin>
>       </plugins>
>     </pluginManagement>
>     <plugins>
>

**Comment by marcphilipp** [comment]
These artifacts are not plugins and belong into the `dependencyManagement` or `dependencies` section rather than the `pluginManagement` section.
