### ISSUE TITLE
Compile error in junit-tests: JUnit4TestEngineDiscoveryTests

### ISSUE THREAD

**Issue by schauder** [junit-team/junit5#125]
I pulled a fresh version of the project and ran
    
    gradlew clean test

this results in the following build failure:

    :junit-tests:compileTestJavaD:\workspaces\junit-lambda\junit-tests\src\test\java\org\junit\gen5\engine\junit4\JUnit4TestEngineDiscoveryTests.java:529: error: incompatible types: Predicate<CAP#1> cannot be converted to Predicate<? super CAP#1>
                                .filter(where(TestDescriptor::getDisplayName, isEqual(displayName)))
                                             ^
      where CAP#1 is a fresh type-variable:
        CAP#1 extends TestDescriptor from capture of ? extends TestDescriptor
    Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
    1 error
     FAILED

    FAILURE: Build failed with an exception.

IntelliJ fails to compile with basically the same message, but the on the fly compiler does not find a problem with the code, nor do I.

The problematic code is:

	private TestDescriptor findChildByDisplayName(TestDescriptor runnerDescriptor, String displayName) {
		// @formatter:off
		Set<? extends TestDescriptor> children = runnerDescriptor.getChildren();
		return children
				.stream()
				.filter(where(TestDescriptor::getDisplayName, isEqual(displayName)))
				.findAny()
				.orElseThrow(() ->
					new AssertionError(format("No child with display name \"{0}\" in {1}", displayName, children)));
		// @formatter:on
	}

I was able to beat it into conformance by some hard casting:

	Set<TestDescriptor> children = (Set<TestDescriptor>) runnerDescriptor.getChildren();

Since the CI build doesn't fail, I assume it is something on my machine, maybe the java version?

    $ java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by jlink** [comment]
Is that the latest Java version on your platform?

2016-01-19 10:02 GMT+01:00 Jens Schauder <notifications@github.com>:

**Comment by schauder** [comment]
No, I'm currently installing the latest, (u66)

**Comment by schauder** [comment]
With the latest version u66 it now works. So I guess this was a bug in the JDK.

**Comment by marcphilipp** [comment]
I had the same issue with 1.8.0_31.
