### ISSUE TITLE
JavaElementsResolver should not warn about abstract classes with test methods

### ISSUE THREAD

**Issue by uhafner** [junit-team/junit5#1250]
## Overview

I have an [abstract base class](https://github.com/jenkinsci/analysis-model/blob/master/src/test/java/edu/hm/hafner/analysis/AbstractParserTest.java) that contains a test case. When I run the tests using maven then the class `org.junit.jupiter.engine.discovery.JavaElementsResolver` logs the warning: 

```
WARNUNG: Class 'edu.hm.hafner.analysis.AbstractParserTest' could not be resolved."
```
Expected behavior: there should be no warning.

Versions:
Java 8
Maven 3.5.2
pom.xml (relevant part):

```xml
    <junit.surefire.provider>1.0.2</junit.surefire.provider>
    <junit.version>5.0.2</junit.version>
    <surefire.maven.plugin>2.19.1</surefire.maven.plugin>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${surefire.maven.plugin}</version>
          <dependencies>
            <dependency>
              <groupId>org.junit.platform</groupId>
              <artifactId>junit-platform-surefire-provider</artifactId>
              <version>${junit.surefire.provider}</version>
            </dependency>
            <dependency>
              <groupId>org.junit.jupiter</groupId>
              <artifactId>junit-jupiter-engine</artifactId>
              <version>${junit.version}</version>
            </dependency>
          </dependencies>
        </plugin>
 
```

## Deliverables

- [Example project](https://github.com/jenkinsci/analysis-model/)
- [Example maven log](https://ci.jenkins.io/job/Plugins/job/analysis-model/job/master/94/consoleText)

**Comment by sbrannen** [comment]
_investigating_

**Comment by sbrannen** [comment]
With JUnit Jupiter **5.0.3**, the warning is no longer displayed:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

I am therefore closing this issue as _invalid_ since the issue has been addressed in the latest official release.

**Comment by sbrannen** [comment]
**FYI**: #1153 changed the log level from `WARN` to `DEBUG`.

Thus, the log statement is still generated; however, it's simply not displayed on the console by default.

**Comment by sbrannen** [comment]
On second thought (and since I apparently never actually clicked the "Close" button), I am leaving this open and slated for 5.1 M2 since I think I can improve the code for such situations.

**Comment by sbrannen** [comment]
**Results**:

I decided not to change the current behavior, since the log message is only emitted at `DEBUG` level now. Plus, it's good to have this log message available if necessary for diagnostic purposes.

FYI: it is not JUnit that is attempting to run that class. Rather, it is Surefire that picks it up via classpath scanning (based solely on the class name and ignoring the fact that it's `abstract`) and then asks the JUnit Platform to "select it" for execution. Consequently, JUnit Jupiter is merely stating that the abstract class is not supported as a test class for the JUnit Jupiter programming model.
