### ISSUE TITLE
`junit-platform-gradle-plugin` requires 'Test' suffix for tests to be discovered

### ISSUE THREAD

**Issue by Whathecode** [junit-team/junit5#1263]
Currently I am switching from the built-in build system of IntelliJ (Community 2017.3.3) to using Gradle for my project.

I struggled for a long time trying to figure out why when I ran my tests using the 'Platform Test Runner' of IntelliJ, more tests were discovered than when using the `junit-platform-gradle-plugin` (org.junit.platform:junit-platform-gradle-plugin:1.1.0-M1).

After an extensive investigation I seem to have discovered that `gradle test` only runs tests defined in classes which are suffixed with 'Test'. (p.s. I am using Kotlin, in case that matters)

```kotlin
class Bleh {

    @Test
    fun Test() { }
}
```

This test is not discovered by `gradle test`, but it is when the class is renamed to `BlehTest` or `BlehTests`. Not even `TestBleh` works. I'm new to Gradle and JUnit 5, but this does not seem like expected/intended behavior to me.

**Comment by sormuras** [comment]
See `includeClassNamePattern[s]` here: http://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-filters

**Comment by sbrannen** [comment]
As @sormuras pointed out, this is documented in the User Guide.

I am therefore closing this issue as "works as designed".
