### ISSUE TITLE
Conditional evaluation of Assert.assertEquals message

### ISSUE THREAD

**Issue by krichter722** [junit-team/junit5#1268]
## Overview

In some situations it's convenient to evaluate the `message` argument of `Assert.assertEquals` only if the assertion fails, e.g.

```java
    HttpURLConnection uc = (HttpURLConnection) new URL("http://example.org/some/rest/path").openConnection();
    uc.setRequestProperty("Accept", MediaType.TEXT_PLAIN);
    Assert.assertEquals(String.format("unexpected response code was %d and response text '%s'",
                uc.getResponseCode(),
                IOUtils.toString(uc.getErrorStream(),
                        Charsets.UTF_8)),
            200,
            uc.getResponseCode());
```

doesn't work, because `uc.getErrorStream` returns `null` if the request was successful, but it's evaluated for constructing the `message` string and thus fails due to a `NullPointerException`. If there was a possibility to construct `message` in a callback which is only invoked if the assertion failed, the above could be used.

There might be workarounds to achieve the above, maybe even more elegant and splitting the statement with `if` is trivial, but it's intended to be an example and in other situations no such workaround might exist.

This applies to other `Assert.assert...` methods as well.

This report can be seen both as question whether such a feature exists and as feature request in case it does not.

**Comment by sbrannen** [comment]
As @jbduncan pointed out, JUnit Jupiter (a.k.a., JUnit 5) has always supported lazy evaluation of assertion failure messages  via a `Supplier<String>` (typically implemented as a lambda expression) for `assert*()` methods in [Assertions](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html). This is demonstrated in the `standardAssertions()` test method in the [User Guide](http://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions).

If you wish to have similar functionality in JUnit 4's `Assert` class, you would need to make a request in the [JUnit 4 GitHub Project](https://github.com/junit-team/junit4).

I am therefore closing this issue as "invalid".
