### ISSUE TITLE
Can't get a report out of the gradle plugin

### ISSUE THREAD

**Issue by schauder** [junit-team/junit5#127]
I'm trying to get a report for my tests out of the gradle plugin.

I created a new module in my fork (https://github.com/schauder/junit-lambda)
and use a build.gradle file based the junit-tests module.

The tests get executed fine (with lots of intentional failures), but no report get's generated for my module (https://github.com/schauder/junit-lambda/tree/master/schauderhaft-examples)
commit: 2d2b172f999d96

Any pointers what I'm doing wrong?

**Comment by jlink** [comment]
there is no real report created currently. See #86

2016-01-19 15:41 GMT+01:00 Jens Schauder <notifications@github.com>:

**Comment by schauder** [comment]
Now, that explains it :-)

**Comment by sbrannen** [comment]
I am closing this issue since it will be addressed in conjunction with #86.
