### ISSUE TITLE
Documentation: Chart of performance between JUnit 4 vs 5

### ISSUE THREAD

**Issue by manueljordan** [junit-team/junit5#1273]
Would be possible add a chart about the comparison about performance between JUnit 4 vs 5?

**Comment by dmitry-timofeev** [comment]
That would be interesting, though the results might be misleading. For example, when you use a mocking framework, it might take almost a second to initialize it, whilst tests take milli- or microseconds. That is, the performance of real-world tests might be dominated by how much it takes to kick-start your mocking framework than by the test framework overhead. On top of that, I'd personally pay a little in terms of performance for unique features of JUnit 5 that make tests more readable, easier and faster to write, than abstain from them for _x%_ faster tests.

**Comment by manueljordan** [comment]
Hello, I understand your point... 

but I thought about to test some _use case_ in both `JUnit`, **4** and **5**, it with and without `Mock` .... i.e: `Integration Testing` through `Spring Framework` ...

Even if results are not favorable to `JUnit` 5, its API and new features (work for package level classes and methods) are valuables.

**Comment by LifeIsStrange** [comment]
Friendly ping.
Would be nice to compare to other frameworks too such as testNG!
