### ISSUE TITLE
Improve documentation about logManager for Gradle plugin

### ISSUE THREAD

**Issue by manueljordan** [junit-team/junit5#1274]
Currently in the reference documentation in the [Configuring the JUnit Gradle Plugin](http://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-junit-configure) section exists this example:

`logManager 'org.apache.logging.log4j.jul.LogManager'`

Is not clear:

* If that `org.apache.logging.log4j.jul.LogManager` is mandatory or not
* If we are able to change to `logback`, if yes, what is the value?

I am working with `Jenkins`, when I execute the test for a module, my `@Test` pass but I get

```
:junit-01-infrastructure:junitPlatformTestCould not load Logmanager "org.apache.logging.log4j.jul.LogManager"
java.lang.ClassNotFoundException: org.apache.logging.log4j.jul.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
```

I have in my classpath `SLF4J` and `Logback`, I did a research for the latter and there is no nothing similar than `LogManager` but the former has [org.apache.log4j.LogManager](https://www.slf4j.org/apidocs/org/apache/log4j/LogManager.html) (different package), thus if I use now:

```
//logManager 'org.apache.logging.log4j.jul.LogManager'
logManager 'org.apache.log4j.LogManager'
```

Then again the `@Test` pass but I get now:

```
:junit-01-infrastructure:junitPlatformTestCould not load Logmanager "org.apache.log4j.LogManager"
java.lang.ClassNotFoundException: org.apache.log4j.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```
Thus I am not able to see the `Gradle Report` (the `reports` directory within the `build` directory), but I know that all the `@Test` pass due the `JUnit` plugin in `Jenkins`

If I comment both lines

```
//logManager 'org.apache.logging.log4j.jul.LogManager'
//logManager 'org.apache.log4j.LogManager'
```

the `reports` directory within the `build` directory does not appear

Not sure how handle correctly this situation.

## Related Issues

- #1295

**Comment by marcphilipp** [comment]
Thanks for letting us know that the documentation is unclear! The `logManager` property is optional. When no `logManager` is set, the default behavior of JUL will kick in. Logback uses a different approach to capture JUL logs: https://stackoverflow.com/a/41592332/6327046

**Comment by manueljordan** [comment]
Thanks by the reply, please see my updated post. I will try your suggestion.

**Comment by manueljordan** [comment]
I have now:

```
//logManager 'org.apache.logging.log4j.jul.LogManager'
//logManager 'org.apache.log4j.LogManager'
```
Thus working through the _default_ `logManager` and in the dependencies now I have

```
//Logging
compile	"ch.qos.logback:logback-classic:$logbackVersion"
['jcl-over-slf4j',
 'jul-to-slf4j', // <---- just added according with your SO link suggestion.
 'slf4j-api'
 ].each { 
  compile "org.slf4j:$it:$slf4jVersion" 
 }
```
The `@Test` method pass, no error shown about the `logManager` **but** the `reports` directory (about `Gradle`) within the `build` directory does not appear

**Comment by marcphilipp** [comment]
Unfortunately, the `junitPlatformTest` task does not write any reports at the moment. It merely writes XML files to `build/test-results`. We're working with Gradle at the moment to add support for JUnit 5 to the core `test` task. In the meantime, you could try https://github.com/kncept/junit-reporter.

**Comment by manueljordan** [comment]
Oh I see, thanks by the explanation, correct about `build/test-results`. 

So I was wrong, I thought the missing `reports` directory was due the `logManager` configuration. Interesting, could you consider add this situation to the reference documentation? I think is valuable for the community.

Thanks by the two links, I will wait in peace the Gradle support.

Thanks by the advice...

**Comment by sbrannen** [comment]
Related to #1295.
