### ISSUE TITLE
Improve documentation for @ParameterizedTest

### ISSUE THREAD

**Issue by manueljordan** [junit-team/junit5#1275]
I am migrating a Spring App from JUnit 4 to 5. The purpose is only have the API for JUnit 5.

Currently the following works fine with JUnit **4**

**Alpha**
```
@Transactional
@RunWith(Parameterized.class)
@ActiveProfiles(resolver=TestJdbcActiveProfilesResolver.class)
@ContextConfiguration(classes={RootApplicationContext.class})
@TestExecutionListeners(listeners={LoggingTestExecutionListener.class}, mergeMode=MergeMode.MERGE_WITH_DEFAULTS)
public class PersonaJdbcRepositoryTest {

    private static final Logger logger = LoggerFactory.getLogger(PersonaJdbcRepositoryTest.class.getSimpleName());

    @ClassRule
    public static final SpringClassRule SPRING_CLASS_RULE = new SpringClassRule();

    @Rule
    public final SpringMethodRule springMethodRule = new SpringMethodRule();

    ...

    @Parameters
    public static Collection<Persona[]> data() {
	return Arrays.asList(new Persona[][] {
	       //something to do
	 });
    }

    public PersonaJdbcRepositoryTest(Persona persona){
	this.persona = persona;
    }

    @Test
    public void aTest(){
      ...
    }

    @Test
    public void bTest(){
      ...
    }

    ...

}
```

After to read the following documentation:

* [3.13. Parameterized Tests](http://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests)
* [JUnit 5 – Parameterized Tests](https://blog.codefx.org/libraries/junit-5-parameterized-tests/)

I have tried the following in JUnit **5** and works fine.

**Beta**
```
@Transactional
@SpringJUnitConfig(classes={RootApplicationContext.class})
@ActiveProfiles(resolver=TestJdbcActiveProfilesResolver.class)
@TestExecutionListeners(listeners={LoggingTestExecutionListener.class}, mergeMode=MergeMode.MERGE_WITH_DEFAULTS)
class PersonaJdbcRepositoryTest {

	private static final Logger logger = LoggerFactory.getLogger(PersonaJdbcRepositoryTest.class.getSimpleName());

//	@ClassRule
//	public static final SpringClassRule SPRING_CLASS_RULE = new SpringClassRule();
//
//	@Rule
//	public final SpringMethodRule springMethodRule = new SpringMethodRule();

	static Collection<Persona[]> data() {
		return Arrays.asList(new Persona[][] {
	        {PersonaFactory.crearPersona01()},
	        {PersonaFactory.crearPersona02()},
	        {PersonaFactory.crearPersona03()},
	        {PersonaFactory.crearPersona04()},
	        {PersonaFactory.crearPersonaMix()}
	    });
	}

	static Stream<Persona> dataa(){
		return Stream.of(
				PersonaFactory.crearPersona01(),
		                PersonaFactory.crearPersona02(),
		                PersonaFactory.crearPersona03(),
		                PersonaFactory.crearPersona04(),
		                PersonaFactory.crearPersonaMix());
	}

//	public PersonaJdbcRepositoryTest(Persona persona){
//		this.persona = persona;
//	}

	//@Test
	@ParameterizedTest
	@MethodSource("data")
	@Sql(scripts={"classpath:/com/manuel/jordan/db/delete.sql"})
	void saveOneTest(Persona persona){
		...
	}

        ...

}
```

From above I have the following points (please consider in explain each point adding each answer to the Reference Documentation for the community, I think would be valuable).

1. I am concerned that `@ParameterizedTest` be experimental, it means that it would be disappear. Am I correct? If yes, how would be replaced? It would be complicated for many Test classes, consider the long refactor.
2. `@MethodSource` can works with either `data` or `dataa` methods, thus the documentation should explain if is mandatory use a method returning a `Stream` or not.
3. For `@MethodSource` is mandatory use it together with `@ParameterizedTest` and not with `@Test`, if the latter is used, I get:

```
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [com.manuel.jordan.domain.Persona arg0] in executable [void com.manuel.jordan.repository.jdbc.PersonaJdbcRepositoryTest.saveOneTest(com.manuel.jordan.domain.Persona)].
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:191)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:174)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:135)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:116)
	at 
```
Consider add a new feature about use `@Test` working with and without `@MethodSource`. It because consider the complications about do a migration of `@Test` to `@ParameterizedTest` from many Test classes according JUnit 4 to 5 working in a Parameterized scenario

4. Even when is possible reduce some code (see the commented lines in **Beta**), seems is mandatory add a parameter for each test method, when `@MethodSource` and `@ParameterizedTest` are used. In some way would be verbose, but I am OK with this new approach until some point. Just curious if `@MethodSource` (or a new annotation variation) would be added to work with a constructor and in this way avoid add a new parameter for each test method. Something like:

```
        @MethodSource("data")
	public PersonaJdbcRepositoryTest(Persona persona){
		this.persona = persona;	
        }

	@Test
	@Sql(scripts={"classpath:/com/manuel/jordan/db/delete.sql"})
	void saveOneTest(){
		...
	}
```

Practically the same approach that `@Parameters` in JUnit 4. I hope you see my point

Thanks in advance by your support.

**Comment by marcphilipp** [comment]
First of all, thank you for providing feedback – highly appreciated!

> I am concerned that `@ParameterizedTest` be experimental, it means that it would be disappear. Am I correct? If yes, how would be replaced? It would be complicated for many Test classes, consider the long refactor.

So far we've received very positive feedback for `@ParameterizedTest`. So I don't foresee it disappearing. In contrast, I can imagine changing it to `Stable` soon.

> `@MethodSource` can works with either `data` or `dataa` methods, thus the documentation should explain if is mandatory use a method returning a `Stream` or not.

Very good point, it's documented in the [User Guide](http://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-MethodSource), but not in the Javadoc. I'll add it there, too.

> For `@MethodSource` is mandatory use it together with `@ParameterizedTest` and not with `@Test`, if the latter is used, I get:
> 
> Consider add a new feature about use `@Test` working with and without `@MethodSource`. It because consider the complications about do a migration of `@Test` to `@ParameterizedTest` from many Test classes according JUnit 4 to 5 working in a Parameterized scenario

Conceptually, a `@Test` and a `@ParameterizedTest` method are different: Both can have parameters, but only a `@ParameterizedTest` method will be executed multiple times. Thus, we're not going to change that. However...

> Even when is possible reduce some code (see the commented lines in **Beta**), seems is mandatory add a parameter for each test method, when `@MethodSource` and `@ParameterizedTest` are used. In some way would be verbose, but I am OK with this new approach until some point. Just curious if `@MethodSource` (or a new annotation variation) would be added to work with a constructor and in this way avoid add a new parameter for each test method. 

... we are considering adding support for parameterized test classes via a `ContainerTemplate` extension point. The corresponding issue #871 is currently in the 5.2 Backlog. With `@ParameterizedContainer` on a test class, you'll be able to use `@Test` on your methods. You might even be able to combine `@ParameterizedContainer` on a class and `@ParameterizedTest` on a method within that class.

**Comment by manueljordan** [comment]
Hello Marc

> First of all, thank you for providing feedback – highly appreciated!

Thanks. I think any feedback for this software must be shared 

> So far we've received very positive feedback for @ParameterizedTest. So I don't foresee it disappearing. In contrast, I can imagine changing it to Stable soon.

Sounds great!

> Conceptually, a @Test and a @ParameterizedTest method are different: Both can have parameters, but only a @ParameterizedTest method will be executed multiple times. Thus, we're not going to change that. However...

I understand. Thanks by the explanation.

> ... we are considering adding support for parameterized test classes via a ContainerTemplate extension point. The corresponding issue #871 is currently in the 5.2 Backlog. With @ParameterizedContainer on a test class, you'll be able to use @Test on your methods. You might even be able to combine @ParameterizedContainer on a class and @ParameterizedTest on a method within that class.

Interesting, I understand the idea just a 50%, a snippet code or example code about what would be available in the future would nice to complement the idea.

**Omicron**

I did realize the following in `JUnit` **5**, if in one Test class I have the following together, for example:

``` 
	@ParameterizedTest
	@MethodSource("data")
	@Sql(scripts={"classpath:/com/manuel/jordan/db/delete.sql"})
	void saveOneTest(Persona persona){
		...
	}

        @Test
	void findAllTest(){
		...
	}
```

I can confirm that `saveOneTest` executes N times according the size of `data` *and* `findAllTest` is executed just one. It practically is the solution that I was looking for in:

[How specify the behaviour of SpringClassRule/SpringMethodRule for a specific @Test?](https://stackoverflow.com/questions/39234490/how-specify-the-behaviour-of-springclassrule-springmethodrule-for-a-specific-te)

The situation above only happens in `JUnit` **4**

**Zulu**

Just curious if the following scenario would be possible in the future (read the comments):

```
@Transactional
@SpringJUnitConfig(classes={RootApplicationContext.class})
@ActiveProfiles(resolver=TestJdbcActiveProfilesResolver.class)
@TestExecutionListeners(listeners={LoggingTestExecutionListener.class}, mergeMode=MergeMode.MERGE_WITH_DEFAULTS)
class PersonaJdbcRepositoryTest {

	private static final Logger logger = LoggerFactory.getLogger(PersonaJdbcRepositoryTest.class.getSimpleName());

	static Stream<Persona> data(){
		return Stream.of(
				PersonaFactory.crearPersona01(),
		                PersonaFactory.crearPersona02(),
		                PersonaFactory.crearPersona03(),
		                PersonaFactory.crearPersona04(),
		                PersonaFactory.crearPersonaMix());
	}

        @MethodSource("data") // Just declared once in the constructor.
	public PersonaJdbcRepositoryTest(Persona persona){
		this.persona = persona;
	}

	@ParameterizedTest
	//@MethodSource("data") moved to the constructor
	@Sql(scripts={"classpath:/com/manuel/jordan/db/delete.sql"})
	void saveOneTest(){ // Persona persona removed
		...
	}

	@ParameterizedTest
	//@MethodSource("data") moved to the constructor
	void updateOneTest(){ // Persona persona removed
		...
	}
        ...

        @Test // should be executed just one.
	void findAllTest(){
		...
	}

}
```

From above see that _each_ `@MethodSource` now is moved to the constructor *and* `Persona persona` has been removed of each test method marked with `@ParameterizedTest`. I think it is a valuable approach **only** if we have more `@ParameterizedTest` than `@Test`, such as 10/2 or 50/20 .. I hope you see my point.

The current approach has sense if we have mixed many `@ParameterizedTest` and `@Test` together, almost equally about of declarations/use of each one, such as the _Omicron_ scenario, 1/1.

Just sharing ideas and thoughts, I respect a lot the efforts and work of `JUnit` team.

**Comment by marcphilipp** [comment]
> Just curious if the following scenario would be possible in the future (read the comments)

Yes, we've plans to add something like this, see https://github.com/junit-team/junit5/issues/878#issuecomment-354544841.

**Comment by manueljordan** [comment]
Thanks for that link ...

**Comment by rimal** [comment]
@marcphilipp By when can we expect the `@ParameterizedTest` to be assigned a `STABLE` status?
I am wanting to use it in my application and have been waiting for the status change.

**Comment by sbrannen** [comment]
@rimal, we are considering doing that in the next release (i.e., 5.3). See #1093 for details.
