### ISSUE TITLE
Fix or remove PDF version of User Guide

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1281]
Fix the PDF version of the user guide OR remove the link to it from the top of the User Guide.

**Comment by sormuras** [comment]
Tried to fix it last week. Did not work out: https://github.com/jruby/jruby/issues/4805#issuecomment-361215636

**Comment by sormuras** [comment]
See #1099 for details -- i think, we have to remove the link to the PDF or upload it manually.

Try this branch https://github.com/junit-team/junit5/compare/issues/1099-pdf-user-guide to "fix" the PDF generation.

**Comment by marcphilipp** [comment]
Starting from the feature branch, I fixed embedded images and links to Javadoc and enabled the `pdf` backend on Mac and Windows (it does currently not work on Linux). Thus, we're good to go wrt. the release. Fixing it for good will be addresses in #1099.

**Comment by sbrannen** [comment]
I agree that it's "good enough" for now.

Thanks for fixing it guys!

And... I'll add some todos in #1099 for the broken links.
