### ISSUE TITLE
Document module path requirements for running junit-jupiter-engine

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1282]
Document that junit-jupiter-engine does not ship with a module descriptor but requires java.scripting and can be run using `--add-modules ALL-MODULE-PATH,ALL-DEFAULT`.

**Comment by sormuras** [comment]
This is the stacktrace produced on OpenJDK 10-ea+42:
```
JUnit Jupiter
    => java.lang.NoClassDefFoundError: javax/script/ScriptException
       org.junit.jupiter.engine@5.1.0-M2/org.junit.jupiter.engine.extension.ExtensionRegistry.<clinit>(ExtensionRegistry.java:54)
       org.junit.jupiter.engine@5.1.0-M2/org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.prepare(JupiterEngineDescriptor.java:37)
       org.junit.jupiter.engine@5.1.0-M2/org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.prepare(JupiterEngineDescriptor.java:28)
       org.junit.platform.engine@1.1.0-M2/org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.prepare(HierarchicalTestExecutor.java:89)
       org.junit.platform.engine@1.1.0-M2/org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:74)
       org.junit.platform.engine@1.1.0-M2/org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
       org.junit.platform.engine@1.1.0-M2/org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
       org.junit.platform.launcher@1.1.0-M2/org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
       org.junit.platform.launcher@1.1.0-M2/org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
       org.junit.platform.launcher@1.1.0-M2/org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
```

**Comment by sormuras** [comment]
We should catch that exception while creating the `ExtensionRegistry` and remember the "missing" class for when/if scripting is used the for first time. Then we should emit an error message and mark the annotated tests as "broken" by raising a `ScriptEvaluationException`.

Reasoning:  using script-based `@DisabledIf` or `@EnabledIf` annotation will not be common, most conditional test execution will and should be controlled by other implementations in package `org.junit.jupiter.api.condition` which do not need module `java.scripting` to be present at the module resolution phase nor at runtime.

**Comment by marcphilipp** [comment]
I think we should try to go that route for now. However, I think we should fail all tests that use `@EnabledIf`/`@DisabledIf` with clear instructions how to solve the problem. Maybe we can check for `javax.script.ScriptException` in `ExtensionRegistry` and only if it's available register the extension by default. Otherwise, we should register an `Extension` that throws an exception when `@EnabledIf` or `@DisabledIf` is present.

**Comment by sormuras** [comment]
At the moment there's no dedicated "Java 9+" section in the user-guide. Only the main README has a small section regard module names: https://github.com/junit-team/junit5#java-9-module-names

The documentation to be delivered by this issue would make more sense if it was embedded in a dedicated **JUnit Platform on JPMS** section.
