### ISSUE TITLE
@ParameterizedTest times out unless @MethodSource factory has a side effect

### ISSUE THREAD

**Issue by Pr0methean** [junit-team/junit5#1283]
## Bug Report

Using: JUnit 5.0.3

In https://github.com/GlowstoneMC/Glowstone/pull/842/files#diff-05705156f52e5f6dbc6cadca3fb637d1R31 the test suite begins reporting "Killed" on CircleCI if I remove the `System.err.println` call.

Maybe an "optimization" of side-effect-free `@MethodSource` methods is backfiring?

**Comment by sbrannen** [comment]
I cloned your fork, modified the `@MethodSource` factory method as below, and the `ParticleTest` class executes without any problems.

```java
static Stream<Effect> getCases() {
	return Stream.of(Effect.values())//
			.filter(effect -> effect.getType() == Effect.Type.PARTICLE);
}
```

Running on:

```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Java version: 1.8.0_161, vendor: Oracle Corporation
Default locale: en_CH, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"
```

Are you perhaps using older versions of the JDK or Maven?

**Comment by sbrannen** [comment]
@Pr0methean 

> Are you perhaps using older versions of the JDK or Maven?

Ping!

**Comment by Pr0methean** [comment]
Looking into it.

**Comment by Pr0methean** [comment]
I'm using Maven 3.5.2 and Java 1.8.0_151
```
#!/bin/bash -eo pipefail
mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T07:58:13Z)
Maven home: /opt/apache-maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-111-generic", arch: "amd64", family: "unix"

#!/bin/bash -eo pipefail
java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by Pr0methean** [comment]
I haven't been able to get the versions on previous runs, but the test now works with `sbrannen`'s refactor.

**Comment by sbrannen** [comment]
Thanks for the feedback!

I will now close this issue.
