### ISSUE TITLE
Add hooks to DynamicContainer which execute beforeall/afterall tests

### ISSUE THREAD

**Issue by mvysny** [junit-team/junit5#1292]
### Feature request

I'm building a very simple test framework https://github.com/mvysny/dynatest . I would like to add a simple functionality akin to `@BeforeAll`/`@AfterAll`; a code in DynamicContainer that would be run by JUnit5 before/after all nested tests are run.

Implementation proposal: the `DynamicContainer` could have two more fields, `public Runnable beforeAll = null` and `public Runnable afterAll = null`; these runnables would then be called by JUnit5 test runner as appropriate.

JUnit currently 5.0.3 lacks this capability.

Thank you very much :)

**Comment by sormuras** [comment]
@junit-team/junit-lambda  I'm reluctant to add this feature to dynamic test generation and execution. It mimics the lifecycle of what Jupiter already provides.

Maybe you can implement `dynatest` using [Test Templates](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-templates) instead?

**Comment by mvysny** [comment]
The Test Templates seems to be very complex; also they allow reuse on the granularity of methods only, and not classes.

Please allow me to digress here from the original feature request. My use-case was to have a test battery for, say, an interface, which I could run on any concrete implementation of that interface. Typically with JUnit you create an abstract test class, then extend it for every interface implementation. That may not always be possible, especially if another test inheritance strategy is mandated by the project. To achieve this with Test Templates I would have to have every method annotated with `@TestTemplate @ExtendWith(MyTestTemplateInvocationContextProvider.class)` and implement the context provider; adding a test for another implementation requires lots of code in the provider which is error-prone.

**Comment by sbrannen** [comment]
Have you considered using _testing traits_ instead?

See [Test Interfaces and Default Methods](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-interfaces-and-default-methods) for details.

**Comment by marcphilipp** [comment]
It is a well documented decision not to support any lifecycle callbacks for dynamic tests. Thus, I'm closing this issue.
