### ISSUE TITLE
JUnit5 Platform Launcher API - Cannot create Launcher without at least one TestEngine

### ISSUE THREAD

**Issue by LucasBullen** [junit-team/junit5#1294]
> Copying from StackOverflow due to inactivity: https://stackoverflow.com/questions/48672051/junit5-platform-launcher-api-cannot-create-launcher-without-at-least-one-teste

I am attempting to upgrade the testing abilities of our automated testing suite to accept JUnit5 tests and when following The [JUnit Platform Launcher API instructions][1] I get the error **"Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath"**. The cause is that the following is unable to find any instances of `TestEngine`:

```java
Iterable<TestEngine> testEngines = ServiceLoader.load(TestEngine.class,ClassLoaderUtils.getDefaultClassLoader());
```

Do you have any suggestions on how to ensure that the `ServiceLoader` is able to find an instance of `TestEngine`?

I have included `org.junit.jupiter.engine`, which contains `JupiterTestEngine` which implements `TestEngine`, as a required plugin. I have tried adding a direct path to the `jupiter.engine` JAR in the project's `.classpath`. I have tried creating an instance of `JupiterTestEngine` within the same file and it is created successfully, but still no ```TestEngine```s found by the service loader.

This is for Eclipse and you can see the code base here:
http://git.eclipse.org/c/platform/eclipse.platform.releng.git/tree/bundles/org.eclipse.test

I added the following to the manifest:

```
    org.junit.platform.launcher,
    org.junit.jupiter.api;bundle-version="5.0.0",
    org.junit.platform.engine;bundle-version="1.0.0",
    org.junit.platform.commons;bundle-version="1.0.0",
    org.junit.jupiter.engine;bundle-version="5.0.0",
    org.junit.vintage.engine;bundle-version="4.12.0"
```

Added this to the `.classplath`:
`<classpathentry exported="true" kind="lib" path="/home/lbullen/Documents/eclipse/plugins/org.junit.jupiter.engine_5.0.0.v20170910-2246.jar"/>`

Added the `org.junit.jupiter.engine` JAR to the lib folder then added it to be included in the binary build. (I'm stretching for a solution)

And I'm trying to get the Tutorial code to work in an edited version of http://git.eclipse.org/c/platform/eclipse.platform.releng.git/tree/bundles/org.eclipse.test/src/org/eclipse/test/EclipseTestRunner.java with all the old JUnit code removed and `LauncherFactory.create();` added to the `EclipseTestRunner` constructor.

  [1]: https://junit.org/junit5/docs/current/user-guide/#launcher-api

**Comment by sbrannen** [comment]
Have you considered asking your question within the Eclipse issue tracker?

I imagine someone there could help you much better than we can. 😉 

@noopur2507, thoughts?

**Comment by LucasBullen** [comment]
Overarching issue being tracked here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=531057

**Comment by sbrannen** [comment]
> Overarching issue being tracked here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=531057

Thanks

**Comment by noopur2507** [comment]
It can be tracked further in the Eclipse bug.

**Comment by sbrannen** [comment]
> It can be tracked further in the Eclipse bug.

Thanks! 🙇 

I'll close this issue now.
