### ISSUE TITLE
How to use slf4 in gradle as logger

### ISSUE THREAD

**Issue by childnode** [junit-team/junit5#1295]
https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-junit-configure
only shows up to use jul to log4j ... but gradle typically logs via slf4

related to / tried to workaround https://github.com/junit-team/junit5/issues/1166

```
plugins {
    id "java-gradle-plugin"
    // see https://github.com/junit-team/junit5/issues/768
    id("org.junit.platform.gradle.plugin") version '1.0.3'
}

buildscript {
  dependencies {
    // classpath 'org.apache.logging.log4j:log4j-core:2.10.0'
    classpath 'org.apache.logging.log4j:log4j-jul:2.10.0'
    classpath 'org.slf4j:log4j-over-slf4j:1.7.25'
  }
}

junitPlatform {
    logManager 'org.apache.logging.log4j.jul.LogManager'
}
```

still ends up in 
`ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`

when adding `logback-classic` we get an additional
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/marcel/.gradle/caches/4.5/generated-gradle-jars/gradle-api-4.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/marcel/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext]

```

I admit: this logging stuff is a way brainfucked ... or I am :D

**Comment by sbrannen** [comment]
The JUnit Platform uses JUL (java.util.logging). Thus if you want to use sl4fj, you'll need to configure the JUL support for sl4fj.

In any case, I am closing this issue as a _duplicate_ of #1274.

So please feel free to follow that issue and add comments there.

**Comment by childnode** [comment]
thx @sbrannen for pointing out #1274
