### ISSUE TITLE
Enhance catching expected exceptions in tests

### ISSUE THREAD

**Issue by ottlinger** [junit-team/junit5#130]
At the moment one can catch expected exceptions in 
```
@Test(expected = IllegalArgumentException.class
```
Usually a more specific test wants to make assertions about the exceptions message or a cause.

What do you think about enhancing the Test-Annotation to be able to use the following assertions:
```
@Test(expected = IllegalArgumentException.class, messageStartsWith = "Error: argument invalid")
@Test(expected = IllegalArgumentException.class, message = "Null not allowed here") 
```
One could exactly match an exception message.

What do you think?

**Comment by schauder** [comment]
I personally don't like it. It basically would mean starting to write an assertion facility based on annotations.  And it will become ugly fast and will keep having huge holes. What if you want to check that a certain String is contained? Or multiple? or a date in a certain format. 

All these are handled by something that takes a closure that returns the exception thrown by the closure. [And such a thing is already exists](https://junit.ci.cloudbees.com/job/JUnit5/javadoc/org/junit/gen5/api/Assertions.html#expectThrows-java.lang.Class-org.junit.gen5.api.Executable-)

**Comment by sbrannen** [comment]
Hi @ottlinger,

Please note that this is the issue tracker for JUnit 5, not JUnit 4.

The `@Test` annotation in JUnit 5 no longer has an `expected` attribute. Instead, the recommend practice with JUnit 5 is to use a utility that catches any exception thrown from a lambda expression or method reference.

Here is a concrete example taken from our own `DefaultLauncherTests`:

```java
JUnitException exception = expectThrows(JUnitException.class,
	() -> launcher.discover(request().select(forUniqueId("foo")).build()));

org.junit.gen5.api.Assertions.assertTrue(exception.getMessage().contains("multiple engines with the same ID"));

org.assertj.core.api.Assertions.assertThat(exception).hasMessageContaining("multiple engines with the same ID");
```
In the above example, I have used the `expectThrows()` method from `org.junit.gen5.api.Assertions`. This catches the exception for me and allows me to save a reference to it in the `exception` variable.

I can then assert anything about the exception that I want. Here I have shown two possibilities:

1. Using JUnit 5's `Assertions.assertTrue` method to verify the contents of the exception message.
1. Using AssertJ's `Assertions.assertThat` infrastructure to verify the contents of the exception message.

With these kinds of options already in place in JUnit 5, I will go ahead close this issue.

However, if you would like to provide further input on the feature set that JUnit 5 supports (i.e., `assertThrows` and `expectThrows` in `org.junit.gen5.api.Assertions`), feel free.

Cheers,

Sam

**Comment by ottlinger** [comment]
Thanks for your input and the brief discussion - I do see your point and am looking forward to a more generic solution with junit5.
