### ISSUE TITLE
Export `findAllClassesInModule`

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1300]
## Overview

The platform-internal method `findAllClassesInModule` in class `org.junit.platform.commons.util.ModuleUtils` is not exported for external usage. 

The Jupiter engine uses it here:

https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java#L62-L63

3rd-party test engines, as [JQwik](https://github.com/jlink/jqwik/blob/master/src/main/java/net/jqwik/discovery/JqwikDiscoverer.java), can't find test classes in modules, yet.

## Deliverables

- [x] Add `findAllClassesInModule` to `org.junit.platform.commons.support.ReflectionSupport`

**Comment by jlink** [comment]
Would be useful and provide an easy means to support module discovery in jqwik.

**Comment by sormuras** [comment]
In the meantime, you could resort to temporarily use the "unsupported" `findAllClassesInModule` in [ModuleUtils](https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ModuleUtils.java#L96) method, though.

**Comment by jlink** [comment]
Just noticed that - unlike the Methods in ReflectionSupport - `ModuleUtils.findAllClassesInModule` does not have a classNamefilter predicate as parameter. Any reason for this asymmetry?

**Comment by sormuras** [comment]
The two filters `classNameFilter` and `classFilter` are combined into the internal `org.junit.platform.commons.util.ClassFilter` class since version 1.1 of the JUnit Platform. This is class is used by `ReflectionUtils` and `ModuleUtils`.

I'd implement the facading method in `ReflectionSupport ` like:

```
	public static List<Class<?>> findAllClassesInModule(
			String moduleName,
			Predicate<Class<?>> classFilter,
			Predicate<String> classNameFilter) {
		return ModuleUtils.findAllClassesInModule(moduleName, ClassFilter.of(classNameFilter, classFilter));
	}
```

Now, only non-internal types are part of the API and the signature is similar to the other two `findAllClassesIn...` methods.

**Comment by sormuras** [comment]
Added the current snapshot version of **net.jqwik** to the `junit5-vanilla-modules` sample via https://github.com/junit-team/junit5-samples/commit/8398dd5136c3c7630ccac93b9982b831e87958c4

See the test plan run tree at https://travis-ci.org/junit-team/junit5-samples/jobs/347992083#L647

**Comment by sormuras** [comment]
@junit-team/junit-lambda a candidate for 5.1.1 as well?

**Comment by marcphilipp** [comment]
Sounds good to me!

**Comment by sbrannen** [comment]
... and documented in Release Notes in commit cf09937f1dc01554574f991f0fc9b2b512477dc6.
