### ISSUE TITLE
Use callable or String supplier to build assertion messages

### ISSUE THREAD

**Issue by buraksarac** [junit-team/junit5#1302]
## Overview

 Future request on assertion implementation. Assertion messages should build after failure not immediately

- ( ) **Feature request.** i.e. below code block:

```
Optional<Void> nullable = Optional.ofNullable(null);

assertFalse("Here no nullable expected!" + nullable.get(), nullable.isPresent());
```
  will throw:

>  java.util.NoSuchElementException

instead of assertion failure.

**Comment by sormuras** [comment]
The parameter positions indicate that you're using JUnit 4. The message, a plain `String` comes first. Jupiter Assertions API expected the message as last parameter.

Be sure to import [`Assertions`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertFalse-boolean-java.util.function.Supplier-) from package `org.junit.jupiter.api` and provide a `Supplier<String>` as the last parameter:

```
import static org.junit.jupiter.api.Assertions.assertFalse;
[...]
Optional<Void> nullable = Optional.ofNullable(null);
assertFalse(nullable.isPresent(), () -> "Here no nullable expected!" + nullable.get());
```
