### ISSUE TITLE
Change attribute from name to value

### ISSUE THREAD

**Issue by michaelsiepmann** [junit-team/junit5#1303]
When using `@ParameterizedTest`, one have to add the name-attribute to create a speaking text. For example:

```
@ParameterizedTest(name = "Wenn enableComments auf {0} steht, sollte isCommentable {1} zurück geben.")
```

When you change this attribute to "value", one can simplier write:

```
@ParameterizedTest("Wenn enableComments auf {0} steht, sollte isCommentable {1} zurück geben.")
```

This is similar to `@DisplayName`.

**Comment by sormuras** [comment]
`name` was chosen on purpose here. `value` could be misleading as of _"The value for the parameterized test."_

If only we had an [`@AliasFor`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/annotation/AliasFor.html) annotation... ;)
