### ISSUE TITLE
Feature request: Allow multiple constructors in test class

### ISSUE THREAD

**Issue by jorn86** [junit-team/junit5#1304]
Consider the following test code:

```
class ReproTest extends BaseTest {
    private final int expectedValue;

    ReproTest() {
        this(1);
    }

    private ReproTest(int value) {
        super(new ClassUnderTest(value));
        this.expectedValue = value;
    }

    @Test
    void test() {
        assertEquals(expectedValue, subject.value);
    }
}
abstract class BaseTest {
    final ClassUnderTest subject;

    BaseTest(ClassUnderTest subject) {
        this.subject = subject;
    }
}
class ClassUnderTest {
    final int value;

    ClassUnderTest(int value) {
        this.value = value;
    }
}
```

Can  we find a way to allow a second constructor in a test class to support this case? Perhaps by ignoring the private constructor or by annotating the constructor JUnit is supposed to use? There is no way to achieve the same functionality without either duplicating values (it's not a constant in my real-world case) or having a second constructor.

**Comment by sormuras** [comment]
Did you try the built-in "DI" support?

See details at https://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection

**Comment by jorn86** [comment]
I did earlier, but I'll have another look on Monday. Thanks for pointing me in that direction!

**Comment by jorn86** [comment]
It's a bit heavy to have to make an extension for this, but it works perfectly. Thanks!
