### ISSUE TITLE
Allow to reference test parameters that aren't among the method arguments

### ISSUE THREAD

**Issue by dmitry-timofeev** [junit-team/junit5#1306]
### Feature Request
Would you please consider allowing referencing a test parameter in a formatting string when it does not appear in a formal method parameter list?

Consider the following code:
```java
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

class SampleTest {

  @ParameterizedTest(name = "{1}: {0}")
  @MethodSource("testParameters")
  void test(String s,
            // IDE highlights 'testDescription' variable below as unused,
            // although it is used in the formatting string (as {1}).
            String testDescription) {
    assertThrows(NumberFormatException.class,
        () -> Integer.parseInt(s)
    );
  }

  static Stream<Arguments> testParameters() {
    return Stream.of(
        Arguments.of("1a", "illegal character"),
        Arguments.of("10000000000000", "out of bounds")
    );
  }
}
```

The IDE highlights `testDescription` variable below as unused, although it is used in the formatting string (as `{1}`). Even if this issue is [fixed](https://youtrack.jetbrains.com/issue/IDEA-184660) in Intellij IDEA, I believe many static analysis tools out there might not be updated.

A possible workaround is to mark the parameter with `@SuppressWarnings("unused")`, but it's tedious to write each time.

If `testDescription` is removed, JUnit will not replace `{1}`, resulting in the following output (as of 5.1.0):
```
{1}: 1a
{1}: 10000000000000
```

There are some things to consider:
  - (+) A user can omit an extra parameter when it's meaning is clear from the context.
  - (+) A user can omit any number of parameters (a "tail" of parameters), that are not related to the current parameterized test, but still reference any of them in the description. That might be useful, when some arguments are not necessary in all parameterized tests sharing the same arguments source.
  - (-) This feature will improve readability only if a test method and its arguments source are _adjacent_. When an index to a parameter that is not among method parameters is included in the formatting string *and* the arguments source is far from the parameterized test, it will confuse the readers. In that case it would be cleaner to add a method parameter and give it a proper name.
  - (-) Can't say how much, but I think support for this feature might make the JUnit internals more complex.

### Alternatives
As suggested by @sormuras , add a `description` method to the `Arguments` interface + a transforming method that sets a description, e.g.:
```java
Arguments {
  Arguments description(String newDescription);
  Arguments description();
}
```

**Comment by sormuras** [comment]
I don't like mis-using a parameter here.

But thinking aloud ... I'd prefer an extra field in the `Argument` class which optionally describes the argument. It could be referred in the display via `{argument.description}`.

**Comment by dmitry-timofeev** [comment]
@sormuras , Sounds interesting! Do you imagine something like that:
```java
Arguments.of("1a").description("illegal character");
Arguments.of("any", "number", "of", "arguments")
    .description("Users need a transforming method to separate arguments from their description");
```

**Comment by dmitry-timofeev** [comment]
@sormuras , I really like your words about mis-using, because that is clearly not a test _parameter_, rather some meta-data about all parameters. I think this feature would be universally useful (personally I had to add descriptions in JUnit 4 ParameterizedTests & JUnit 5 tests), and  your proposal deserves its own issue: #1309

**Comment by marcphilipp** [comment]
We should not allow to reference extra test parameters because, as you wrote in the issue description, it looks confusing.
