### ISSUE TITLE
Improve the ease of Arguments transformation

### ISSUE THREAD

**Issue by dmitry-timofeev** [junit-team/junit5#1307]
### Feature Request
Please consider improving the ease of `Arguments` transformation. Currently a user can only get an underlying array of `Object`s, and cast each of them to the desired type manually.

### Uses cases
Consider the following code:
```java
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.exonum.serialization.runtime.StringReader;
import com.exonum.serialization.runtime.testutils.ByteBuffers;
import java.nio.ByteBuffer;
import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

class ExampleTest {

  @ParameterizedTest(name = "[{index}] {1}")
  @MethodSource("invalidUtf8Strings")
  void testInvalidStrings(ByteBuffer buffer,
                          @SuppressWarnings("unused") String description) {
     // Check that the SuT rejects invalid UTF-8 strings in binary form.
  }

  private static Stream<Arguments> invalidUtf8Strings() {
    return Stream.of(
        // …
        // Missing continuation bytes
        Arguments.of("DF", "2nd byte expected"),
        Arguments.of("EF BF",  "3rd byte expected")
        // …
    )
        .map(args -> {
          String strHex = (String) args.get()[0];
          ByteBuffer strBuffer = ByteBuffers.fromHex(strHex.toLowerCase());
          String testDescription = (String) args.get()[1];
          String fullDescription = String.format("%s: %s", testDescription, strHex);
          return Arguments.of(strBuffer, fullDescription);
        });
  }
```
`invalidUtf8Strings` uses a hex-string representation of binary data, because it's easier to write and read than an array of bytes (`bytes(0xEF, 0xBF)`). That hex-string representation must be converted into a ByteBuffer to be used by the test. On top of that, the transformation function creates a friendly test description.

When `Arguments` expose only an array of `Object`s, that requires the callers to perform type casts.

### Possible solution
The following APIs may be added to simplify a transformation of an `Arguments`:
- Generic specializations of an `Arguments` interface for _2…N_ number of arguments, e.g., `Arguments3<A1, A2, A3>`, where _N_ is the number of specializations it makes sense to support. Such interfaces must extend `Arguments`.
- Overloads of factory method `Arguments.of`, for _0…N+1_.
- `<R> R ArgumentsN#map(Function<A1, A2, …, AN, R> transformingFunction)`, where _X_ in _2…N_, allowing to easily transform the arguments.

### Results
The code of the source method above may evolve into either of:
```java
  private static Stream<Arguments> invalidUtf8Strings_1() {
    return Stream.of(
        // Same as above ^, but here Arguments.of 
        // may produce an instance of Arguments2<String, String>:
        Arguments.of("DF", "2nd byte expected")
    )
        .map(args -> {
          String strHex = args.first();  // or A1 get0(), TBD
          ByteBuffer strBuffer = ByteBuffers.fromHex(strHex.toLowerCase());
          String testDescription = args.second(); // or A2 get1()
          String fullDescription = String.format("%s: %s", testDescription, strHex);
          return Arguments.of(strBuffer, fullDescription);
        });
  }
  
  private static Stream<Arguments> invalidUtf8Strings_2() {
    return Stream.of(
        // same as above ^
    )
        .map(args -> args.map((strHex, testDescription) -> {
          ByteBuffer strBuffer = ByteBuffers.fromHex(strHex.toLowerCase());
          String fullDescription = String.format("%s: %s", testDescription, strHex);
          return Arguments.of(strBuffer, fullDescription);
        }));
  }
}
```

### Questions
1. Is it a common use case to transform the arguments?
2. Is it worth the effort and maintenance cost?
3. How many specializations shall we provide (what is the value of _N_)?
4. Shall we implement `ArgumentsX#map` for _X > 2_? It will require implementing the corresponding functional interfaces (if there isn't a library with them).

**Comment by sormuras** [comment]
Did you try the [Argument Conversion](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion) that Jupiter provides? Especially the [`ArgumentConverter`](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion-explicit) could help here, I guess.

**Comment by dmitry-timofeev** [comment]
Thank you for the references! I didn't consider this option. I think I will write a snippet of how the code above looks like with ArgumentConverters. I'll submit it here a little bit later.

**Comment by marcphilipp** [comment]
It's outside the scope of JUnit to provide typed Tuple types. Please use a different library, e.g. [Commons Lang](http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/tuple/package-summary.html) and transform those into `Arguments` in case you need intermediate mapping steps. Adding an optional description to `Arguments` instances is being discussed in #1309.
