### ISSUE TITLE
Failures in lifecycle methods should take precedence over TestAbortedException

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1313]
## Overview

In the following example, `abortedTest` will be reported as _aborted_, while `successfulTest` will be reported as _failed_ due to the exception in `afterEach()`.

Expected behavior: `abortedTest` should be reported as _failed_ with a suppressed `TestAbortedException`.

```java
class TestCase {

	@Test
	void abortedTest() {
		assumeFalse(true, "abortedTest");
	}

	@Test
	void successfulTest() {
	}

	@AfterEach
	void afterEach() {
		throw new RuntimeException("afterEach");
	}
}
```

## Deliverables

- [ ] Let other exceptions take precedence over `TestAbortedException`.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by sbrannen** [comment]
@marcphilipp, are you planning on documenting this _fix_ in the 5.3 Release Notes?

**Comment by marcphilipp** [comment]
Thanks for the reminder! Done in d39730591e.
