### ISSUE TITLE
DisplayName not working

### ISSUE THREAD

**Issue by dnccfu** [junit-team/junit5#1314]
I am currently using junit5 jupiter for all my tests, and would like to report that the displayname has no effect either in the netbeans test results window or launching maven test phase from the terminal. The default java name is used in both cases.

**Comment by sormuras** [comment]
Can only guess here -- it looks like you're using JUnit 4 in your setup.

Please provide detailed information about your Maven configuration.

AFAIK, Netbeans does not support "JUnit 5" out-of-the-box.

**Comment by dnccfu** [comment]
I am only using the default dependencies suggested by the user guide for jupiter tests and simply using the jupiter api "Test" and "DisplayName" annotations. Thats pretty much it.

Forgive my lack of deep technical knowledge but reading your user guide i expect the test names that appear either in Netbeans or the console via mvn test to be the values in DisplayName annotation. Perhaps i got it wrong?

```
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>
    <version>1.1.0</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>5.1.0</version>
    <scope>test</scope>
</dependency>
</dependencies>
<build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>1.0.3</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```

**Comment by sormuras** [comment]
There's version mismatch in your `pom.xml` snippets: `1.1.0` vs `1.0.3`

The very basic [Maven Surefire provider](https://github.com/junit-team/junit5/tree/master/junit-platform-surefire-provider) does not pass along the name set via the `@DisplayName` annotation. If I remember correctly, that is due to a limitation of Surefire that expectes tests to be composed of a valid class and method name.

Things will improve when Surefire implements native JUnit Platform support. Soon. :)

**Comment by dnccfu** [comment]
I see. Its weird though that it works in IntelliJ with the same setup (just tried), even with the version mismatch, it shows the display names in the test window. I thought both just use surefire for all maven project tests. Ill look into it.

Anyway thanks for your time

**Comment by marcphilipp** [comment]
Yes, this is definitely an issue with the current Surefire Provider SPI and the limitations of the XML reporting format. Closing this issue for now as duplicate (see #990).
