### ISSUE TITLE
Move Cross-Engine Annotations to Platform API Package

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1323]
## Overview

There are a few annotations (`@DisplayName`, `@Tag`, `@Tags`, `@Disabled`) that will eventually
be implemented by all annotation-based test engines. For example, jqwik just introduced a `@Label` annotation to allow for customized test names.

For test writers it can be confusing why they have to choose different annotations for different types of tests to basically do the same thing.

### Suggested Solution

Duplicate `@DisplayName`, `@Tag`, `@Tags`, `@Disabled` in org.junit.platform.commons.annotation (which already contains `@Testable`) and mark the original ones as deprecated. 

Alternatively one could introduce a new package, e.g. org.junit.platform.api for these annotations.

**Comment by sormuras** [comment]
Mh, first thought: good candidate for https://github.com/ota4j-team/opentest4j

Second thought: test writers will usually(?) use a single test engine API. That API should provide all types it supports. What if another engine does not support tagging per-se and the test writer uses the `@Tag` which is ignored?

**Comment by jlink** [comment]
@sormuras 

I briefly thought about opentest4j but discarded it since the annotation conflict only shows up when running on the junit platform. Running two different test frameworks outside junit platform would be an error-prone setup. 

As for "test writers will usually(?) use a single test engine": not necessarily. For projects that require Spring support I  nowadays often choose Jupiter as base but add jqwik for property testing. Additionally jqwik will report if a property is annotated with jupiter annotations and skip it.

Not supporting a platform feature is a problem that can happen with other stuff as well, eg not supporting all discovery selectors.

**Comment by sbrannen** [comment]
> For test writers it can be confusing why they have to choose different annotations for different types of tests to basically do the same thing.

I certainly cannot deny that.

However, I am not a fan of moving core annotations outside of the Jupiter API.

Once we move annotations outside of our control, we then lose the ability to modify them at a later date to support new features within Jupiter.

For example, if we ever determine that we need to meta-annotate one of those annotations or introduce additional attributes in them, it would be impossible to do that if Jupiter no longer _owns_ the annotations.

So I tend to agree with @sormuras: a testing framework _API should provide all types it supports_.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment]
Assigned to 5.2 M1 for _team discussion_

**Comment by marcphilipp** [comment]
We've discussed this issue in the team. We believe it's more confusing for new users to have these annotations in a different package or even artifact. Test authors that use multiple engines should be experienced enough to pick the correct import. In addition, from a maintainability perspective, using the same annotation in multiple APIs to write tests would introduce an unnecessary coupling between them. We want to stay flexible enough to add an attribute to an annotation etc. Thus, I'm closing this issue.
