### ISSUE TITLE
Delete junit-platform-gradle-plugin subproject

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1331]
The `junit-platform-gradle-plugin` will be deprecated in JUnit Platform 1.2 and is scheduled to be discontinued in JUnit Platform 1.3.

## Deliverables

- [ ] Remove the `junit-platform-gradle-plugin` subproject from Gradle config and Git repo using the **JUnit Team** account for the commits

**Comment by sbrannen** [comment]
👍
