### ISSUE TITLE
Feature Request: Structures in Dynamic Tests

### ISSUE THREAD

**Issue by mibutec** [junit-team/junit5#1335]
I'm really looking forward using JUnit 5, especially Dynamic Tests. In our company we are using a lot of JBehave. In short JBehave allows to describe scenarios written in special DSL files and execute them by an own JBehave Runner.

In JUnit 4 we had a lot of problems getting test reporting done for that tests being executed by JBehave Runner, so each successful and each failed scenario is reported and counted correctly in JUnit. Now in JUnit 5 each scenario is a Dynamic Test and things work fine.

The only drawback: Test description in JBehave is quite hierarchical: One JUnit-Test may execute several story files, one story file consists of several scenarios, one scenario may consist of multiple examples.

For now I'm just able to flatten all that hierarchy to the lowest level, hiding a lot of information from developers. It would be great, if it was possible to structure those tests in a hierarchic view having some logical containers on some levels.

**Comment by sormuras** [comment]
https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests

Like the last example?

**Comment by mibutec** [comment]
Thanks for the link. I cancel my request
