### ISSUE TITLE
Update User Guide regarding official Mockito extension

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1344]
## Overview

Since the Mockito team has released official support for JUnit Jupiter, we should update the User Guide accordingly.

## Related Issues

- https://github.com/junit-team/junit5-samples/issues/62

## Deliverables

- [x] Replace references to the `MockitoExtension` from the `junit5-samples` repository with references to the official `MockitoExtension` supplied by the Mockito team and revise content to align with the feature set of the official `MockitoExtension`.

**Comment by marcphilipp** [comment]
@smoyer64 Good point! I think we might need to find a different example for parameter resolution.

**Comment by sbrannen** [comment]
I expounded on the deliverable. 😉

**Comment by marcphilipp** [comment]
_in progress_
