### ISSUE TITLE
Introduce assertDoesNotThrow()

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1348]
## Overview

This proposal is a result of a [discussion on Twitter](https://twitter.com/KevlinHenney/status/978565873991548929).

It has been noted that AssertJ provides similar support via the following construct.

```java
assertThatCode(() -> {}).doesNotThrowAnyException();
```

## Deliverables

- [ ] Introduce `assertDoesNotThrow(Executable)` in JUnit Jupiter's `Assertions` along with variants accepting a `String` or `Supplier<String>` for failure messages.

**Comment by sbrannen** [comment]
Tentatively slated for 5.2 M1 for _team discussion_

**Comment by sbrannen** [comment]
FWIW, I am now in favor of this proposal.

While reviewing [this test class](https://github.com/spring-projects/spring-framework/blob/e5096be66022f892b762965540aa261bfb718d53/spring-test/src/test/java/org/springframework/test/web/servlet/DefaultMvcResultTests.java) in Spring (with the `assertDoesNotThrow` proposal in the back of my mind)... I really thought... "Wow, it sure would be nice if that last line in the `getAsyncResultSuccess()` test method were rewritten as `assertDoesNotThrow(() -> this.mvcResult.getAsyncResult());`." 😉

**Comment by sbrannen** [comment]
FYI: I just pushed my proposed implementation to a feature branch here:

https://github.com/junit-team/junit5/commit/4d6abf08ff1ad3e4deee092e99b8af11ddff0214

**Comment by sbrannen** [comment]
_in progress_

**Comment by marcphilipp** [comment]
**Team Decision:** Go for it!

**Comment by sbrannen** [comment]
This support has been pushed to `master` in commit a1989a2c8f6294a49c8f0e0b88aca4f6846744cb.
