### ISSUE TITLE
Briefly document Ant build support in User Guide

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1352]
Ant support has been released (cf. https://github.com/junit-team/junit5/issues/512#issuecomment-376820461).

## Deliverables

- [x] Add Ant subsection with a minimal example and links to the official Ant documentation

**Comment by jaikiran** [comment]
@marcphilipp, I just submitted a PR for review https://github.com/junit-team/junit5/pull/1361. Let me know if you think any changes/additions are required in there.

**Comment by sbrannen** [comment]
Ant build support is now documented in `master` via commits 7ebaa8142ced045bb13c893b88a31252e168c6ed and 069df8d31d8147a07c6d741e253d13fea2168edd.
