### ISSUE TITLE
JUnit Jupiter instantiates test class for a disabled test method

### ISSUE THREAD

**Issue by christophsturm** [junit-team/junit5#1358]
I have this class:

```java
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

public class JunitTest {
    {
        System.out.println("yo");
    }
    @Disabled
    @Test
    public void disabledTest() {

    }
    @Test
    public void enabledTest() {

    }
}
```

and I would expect that it outputs "yo" once, but it outputs it twice. I'm pretty sure that JUnit 4 did not do that. 

In that example it may seem far fetched, but the my real test suite is in Kotlin and to keep everything immutable I initialize my dependencies in the class instead of in `@BeforeEach`:

```java
class Tests {
  val webServer=TestUtils.startWebserver()

  @AfterEach
  fun stopIt() {
    webServer.stop()
  }
}
```

so if i add a disabled test method to this class, my webserver is started, but not stopped.

**Comment by sormuras** [comment]
> I'm pretty sure that junit 4 did not do that.

Try it... ;)

**Comment by christophsturm** [comment]
how is that related to the issue? I want one test instance per test which is the default, and also what junit 4 did. but i want one instance per actually enabled test and no instance per disabled test.

**Comment by sormuras** [comment]
> but i want one instance per actually enabled test and no instance per disabled test.

Pardon me, that desire was not clear to me.

I guess that JUnit 4's `@Ignore` prevented the entire lifecycle around the `@Test`-annotated method to be skipped. `@Disabled` is realized as a common extension in Jupiter which works apparantly different to your expectation.

**Comment by christophsturm** [comment]
another case that makes it very unintuitive is junit4 rule support. Rules are initialized for disabled tests but their lifecycle does not run.

**Comment by sbrannen** [comment]
`@Ignore` is analyzed statically in JUnit 4; whereas, `@Disabled` is actually a _condition_ in JUnit Jupiter that is evaluated dynamically.

If you want something _static_ in Jupiter, you can use _tags_ (e.g., `@Tag("my-tag-name")`) instead of conditions.

Another option would be to use a condition at the class level instead of at the method level -- for example, `@Disabled`, `@DisabledIf(...)`, or a custom `ExecutionCondition`.

@christophsturm, does that answer your questions?

**Comment by sbrannen** [comment]
> so if i add a disabled test method to this class, my webserver is started, but not stopped.

It's not a good idea to perform custom setup in an instance initialization block since there is no corresponding _tear down_ block.

Whereas, if you create a `@BeforeEach`/`@AfterEach` method pair, then JUnit Jupiter guarantees that the "afters" are invoked in the "befores" were invoked.

**Comment by sbrannen** [comment]
FWIW, it's also not a good idea to set up things in a static initialization block if those things must be guaranteed to be _torn down_ afterwards.

**Comment by christophsturm** [comment]
ok so basically that means when a test method is disabled in junit5 the test class is instantiated, but no lifecycle methods are called at all. If it's going to stay that way it really should be documented somewhere. 

And I agree that in a perfect world this should not be a problem. but for example, a junit4 rule that does work in its constructor instead of its startup callback (which it should not), will leak in that case (when running with junit4 compatibility)

**Comment by sbrannen** [comment]
> ok so basically that means when a test method is disabled in junit5 the test class is instantiated, but no lifecycle methods are called at all.

Correct.

> If it's going to stay that way it really should be documented somewhere.

Hmmm... I thought it was already documented, but perhaps it's documented more from the perspective of an extension author rather than from the point of view of a test developer.

I'll investigate.

**Comment by sbrannen** [comment]
> And I agree that in a perfect world this should not be a problem. but for example, a junit4 rule that does work in its constructor instead of its startup callback (which it should not), will leak in that case (when running with junit4 compatibility)

True.

But... I don't see how we can prohibit that. 

Like you said, a rule could do that in JUnit 4, but "it should not".

**Comment by sbrannen** [comment]
OK. I looked into the existing documentation, and it appears that this behavior is not actually documented per se.

So we'll improve that.

**Comment by sbrannen** [comment]
_in progress_

**Comment by christophsturm** [comment]
maybe add "This means that it's not safe to initialize test dependencies in their declaration instead of `@BeforeEach`". and maybe also add a note in the docs for the per method lifecycle. 

is changing the behavior totally off the table?

**Comment by sbrannen** [comment]
Documented in commit d8acdb3d6ab66179b0e9c66583dc507be3287032.

**Comment by sbrannen** [comment]
> is changing the behavior totally off the table?

Yes.

**Comment by sbrannen** [comment]
> and maybe also add a note in the docs for the per method lifecycle.

What are you suggesting here?

**Comment by christophsturm** [comment]
https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle

"JUnit creates a new instance of each test class before executing each test method (see note below for what qualifies as a test method). This "per-method" test instance lifecycle is the default behavior in JUnit Jupiter and is analogous to all previous versions of JUnit."

maybe add "Please note that in this config the class is instantiated even when the test is disabled"

**Comment by sbrannen** [comment]
Ahhh.... OK. You meant in the User Guide.

Thanks

**Comment by sbrannen** [comment]
Update: I pushed the following _Note_ to the User Guide: 4d0629a5940b9ef0ade772eba3bbde851351298d

**Comment by sbrannen** [comment]
> maybe add "This means that it's not safe to initialize test dependencies in their declaration instead of `@BeforeEach`". 

I agree that that is useful information; however, it's a very general tip that should be applied across the board when implementing any kind of tests. Plus, it applies not only to user code but also to how extensions are implemented.

So I'm not sure where we would include such a tip.

**Comment by christophsturm** [comment]
one more idea: you could measure the time that it takes to instantiate the test class, and if it takes longer than 1ms output a warning that you should not do any work at instantiation time. 
Not sure if its practical, and will probably create false positives.

**Comment by sbrannen** [comment]
Yeah, that would likely lead to false positives.

I think we'd better not try to do anything like that.
