### ISSUE TITLE
junit4-runner: When skipping a container all leaves must be reported as ignored

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#136]
## Status Quo

Right now the container is reported as ignored and no events are emitted for its descendants. JUnit 4 circumvents this problem by not even generating children for test classes annotated with `@Ignore`.

## Tasks

- [ ] When a container is skipped: collect all leaves and report each of them as ignored.
- [ ] Clarify Javadoc of `TestExecutionListener#executionSkipped` and `EngineExecutionListener#executionSkipped`: When a container is skipped no events are generated for any of its descendants.

**Comment by jlink** [comment]
Alternatively this could be done by HierarchicalTestExecutor. Or the HierarchicalTestExecutor could prune all children away.

**Comment by marcphilipp** [comment]
Well, if a container is skipped, I don't think we should send start/end events. Therefore we have to stick to sending a skipped event for the container. If we do, when would we send skipped events for its descendants? I think the current behavior makes sense in the presence of container events. It's different from JUnit 4's because JUnit 4 does not consistently supports container events.
