### ISSUE TITLE
Surefire provider during integration tests gives SLF4J issues using Logback and REST Assured

### ISSUE THREAD

**Issue by amohabir** [junit-team/junit5#1360]
## Bug Report

Using:

- JUnit platform 1.1.0
- Jupiter engine 5.1.0
- surefire-provider 1.1.0
- failsafe-plugin 2.19.1
- JDK 8 Update 161

## Issue

So a very specific combination of the failsafe plugin with the surefire provider and having a test using REST assured in combination with logback for logging purposes is not working. This same setup but with the surefire plugin is working, as seen in the example project below. When switching logback for SLF4J-simple, it seems to work again. It also works when just switching back to Junit 4.

For some reason SLF4J is also loading a `jdk14` library coming from the Maven plugins.

Error message:

```
Running io.github.bonigarcia.PublicRestServicesIT
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/amohabir/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/amohabir/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.122 sec <<< FAILURE! - in io.github.bonigarcia.PublicRestServicesIT
testCountryService  Time elapsed: 1.107 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
	at io.github.bonigarcia.PublicRestServicesIT.testCountryService(PublicRestServicesIT.java:37)

testEchoService  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
	at io.github.bonigarcia.PublicRestServicesIT.testEchoService(PublicRestServicesIT.java:30)

```

Code is based on: https://github.com/bonigarcia/mastering-junit5/tree/master/junit5-rest-assured

## Example Project

[junit5-rest-assured-example.zip](https://github.com/junit-team/junit5/files/1884057/junit5-rest-assured-example.zip)

**Comment by sbrannen** [comment]
> For some reason SLF4J is also loading a jdk14 library coming from the Maven plugins.

Well, if that's the case, then I don't know what the JUnit team could do to help.

We don't have any control over the Failsafe plugin.

What happens if you _exclude_ the "jdk14 library coming from the Maven plugins"?

**Comment by amohabir** [comment]
Excluding either or both the SLF4J jdk14 and API libraries doesn't help solve the issue. Perhaps it makes sense to also link this one to the Maven team?

**Comment by sbrannen** [comment]
Yes, I recommend you take it up with the Maven team since I don't think we can do anything to help.

With that in mind, I am closing this issue.

However, if the Maven team determines there is actually a bug in JUnit, please report that back here.

Thanks!

**Comment by sbrannen** [comment]
Thanks for the reference to #1318.

I've changed the label to "duplicate".

**Comment by amohabir** [comment]
Ah cool. Thanks, guys! Any estimates on the 5.2 release? Will there be a separate failsafe-provider at some point btw?

**Comment by marcphilipp** [comment]
We've donated our provider to the Maven Surefire Apache project. Now we're waiting for them to update and publish it. Once they do, Surefire will autodetect which provider to use. AFAIK there's no separate Provider API for the surefire and failsafe plugins, they just use different conventions and different Maven lifecycles but leverage the same implementation.

**Comment by sormuras** [comment]
> Any estimates on the 5.2 release?

5.2 M1 Due by May 4, 2018 -- https://github.com/junit-team/junit5/milestone/22

**Comment by amohabir** [comment]
Testing it with 5.2 M1 seems to have solved the issue.
