### ISSUE TITLE
Fix Javadoc stylesheet for JDK 10

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1362]
Jenkins is already using JDK 10 to generate Javadoc. I've noticed that [the overview](https://junit.org/junit5/docs/snapshot/api/overview-summary.html) now uses tabs for the groups "Jupiter", "Vintage", and "Platform". Before using JDK 10 or higher to compile a release we need to improve our stylesheet. We should probably diff the JDK 9 and 10 default stylesheets/html output to see what changed.

**Comment by sbrannen** [comment]
When you say "Fix...", do you mean something is broken on JDK 10?

Or are you just saying we should investigate to make sure that nothing is potentially broken?

**Comment by sbrannen** [comment]
Answering for Marc...

One noticeable difference is that the tabs (All Packages, Jupiter, Vintage, Platform) do not have a visible spacer between them: it's just one big red bar.

Contrast that to the default style sheet used here: https://docs.oracle.com/javase/10/docs/api/overview-summary.html

**Comment by sbrannen** [comment]
@sormuras, if you're going to tackle this one, it'd probably be good to remove the "up for grabs" label, but I'll leave that up to you.

**Comment by marcphilipp** [comment]
Fixed by 80066a9d903044d753b9f452fb4747b3e43f71e3.
