### ISSUE TITLE
Description error in JavaDoc for TestExecutionListener interface

### ISSUE THREAD

**Issue by roussi** [junit-team/junit5#1368]
## Overview

_ I think that there is a little error in the description of TestExecutionListner interface ( https://junit.org/junit5/docs/current/api/org/junit/platform/launcher/TestExecutionListener.html ) 

> Register an instance of **this class** with a Launcher to be notified of events that occur during test execution. 

should be 

> this interface

 instead of 

> this class

**Comment by sbrannen** [comment]
Good catch.

I'll fix that ASAP.

**Comment by sbrannen** [comment]
Done!
