### ISSUE TITLE
Improve test coverage for argument aggregator support

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1370]
## Overview

This issue picks up where #1191 left off.

## Deliverables

- [x] Verify that we have _decent_ code coverage for features introduced to support argument aggregation.
- [x] Introduce unit tests for `ArgumentsAccessor`.
  - Introduced in 5.2 M1.
- [x] Introduce tests for exception handling and error cases when parameterized tests with aggregators are executed.
  - In other words, `AggregatorIntegrationTests` currently only tests _happy paths_, but we need to test for known error cases as well.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
no longer _in progress_

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I fixed a bug in 50a3d6db2f2399cfcc71ac363a046c220ca70751 and added tests for exception handling in dad11e9605d7dbb28eacb12725ee65b56a7647a6. As far as 5.2 is concerned, that should address the concerns raised by this issue.

In addition, I created #1397 to improve performance when `@ConvertWith` or `@AggregateWith` are used.
