### ISSUE TITLE
Code Styling via Intellij

### ISSUE THREAD

**Issue by dotCipher** [junit-team/junit5#1374]
I am an intellij user, and it seems like the default Intellij project files set the import order to be different than what you guys specified in the [CONTRIBUTING.md > Formatting](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#formatting) section, thus the arrangement of import ordering conflicts directly between the two styles.  This manifest itself as when a developer applies the `Cmd + Alt + L` (format code) command to intellij, the order will change once (via the intellij formatting style) then immediately a second time (via the enabled eclipse formatter).

This can be confusing since the order of formatters seems to be non-deterministic, thus leaving the developer in an unknown state of proper formatting.  I realize that applying `./gradlew spotlessApply` can fix this on an ad-hoc basis, but it might be better to have tooling that directly alters the default Intellij project code style files, instead of bypassing it through a third-party plugin.

**Comment by sbrannen** [comment]
@marcphilipp, @mmerdes, & @sormuras: how do you deal with that situation?

**Comment by jbduncan** [comment]
I can't speak for anyone else, but as someone who contributed to JUnit 5 in the past with IntelliJ IDEA, I just clicked on the `check` and `spotlessApply` tasks in the Gradle view whenever I needed to test changes and fix formatting respectively...

Allowing, for example, `spotlessApply` to be invoked with a keyboard shortcut like `(Ctrl|Cmd) + Alt + L` would be good, though. Perhaps there's a way of doing this in IntelliJ that I'm unaware of?

**Comment by sormuras** [comment]
Same for me. Executing a saved run configuration calling "gradlew spotlessApply build" or sometimes even "gradlew clean spotlessApply build".

**Comment by pauldingemans** [comment]
See section "Rearrange code" on page https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html how to set the order of the imports in IntelliJ. If this suffices, please close the issue.

**Comment by marcphilipp** [comment]
@dotCipher Have you tried using https://github.com/krasa/EclipseCodeFormatter?

**Comment by dotCipher** [comment]
This answer suffices, thank you for the clarification
