### ISSUE TITLE
Make XML report generator available to the public

### ISSUE THREAD

**Issue by cburgmer** [junit-team/junit5#1375]
## Overview

We have written our own test runner and would like to use the JUnit Platform's `XmlReportsWritingListener` to generate test result output. However the implementation is currently not in the public API.

Background:

We have created our own test runner, it seems for the following reasons.

- Setup of external dependencies
- Provide own `TestExecutionListener`

With this we replace which I assume would otherwise be provided by the `ConsoleTestExecutor`, which is the only point in JUnit which accesses the `XmlReportsWritingListener`.

## Deliverables

- [x]  Make XML report generation publicly available.

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 for _team discussion_

**Comment by marcphilipp** [comment]
**Team Decision:** Polish (e.g. rename) and publish it as part of junit-platform-launcher.

**Comment by marcphilipp** [comment]
@cburgmer Is this issue still relevant to you?

**Comment by cburgmer** [comment]
As in "will be implemented and released eventually"? If so, feel free to close now. We are running our own version right now, but in the long run it might be nice to replace with upstream.

**Comment by sbrannen** [comment]
> If so, feel free to close now.

Well, if we close this issue now, that means the task will no longer be in any backlog (which means it will not be done). 😉 

On the other hand, if nobody in the community needs it urgently, the issue may potentially remain open but assigned to a later _milestone_.

**Comment by cburgmer** [comment]
Let's say, we can work with the solution we have now. I'll get out of your hair, so you can decide best what the priorities are for the next weeks :)

**Comment by r0e** [comment]
I would also like to make use of the XML Report generator

**Comment by sbrannen** [comment]
@r0e, can you tell us what your concrete use case is?

**Comment by sormuras** [comment]
Using this XML report genertor is common use case when integrating the JUnit Platform in "build tools". By now, I could use them in both projects listed below:

* https://github.com/forax/pro
* https://github.com/sormuras/junit-platform-maven-plugin

Same goes for the `TreePrintingListener`, to a lesser extend.

**Comment by sormuras** [comment]
> Team Decision: Polish (e.g. rename) and publish it as part of `junit-platform-launcher`.

Perhaps a dedicated `junit-platform-reporter` project is better place to collect commonly used report generating listeners? Would keep the `junit-platform-launcher` clear from those implementations.

**Comment by sbrannen** [comment]
> Perhaps a dedicated `junit-platform-reporter` project is better place to collect commonly used report generating listeners?

Maybe, but we'd probably want to name it something like `junit-platform-reporting` or `junit-platform-reports`.

**Comment by marcphilipp** [comment]
+1 for `junit-platform-reporting`

**Comment by sormuras** [comment]
_in progress..._

**Comment by sormuras** [comment]
@cburgmer the `junit-platform-reporting` module is (soon) avaiable in the `1.4.0-SNAPSHOT` builds. It'd be great, if you find the now public `XmlReportsWritingListener` useful. Feedback is very appreciated.

**Comment by sbrannen** [comment]
Closing this issue now that the "legacy" renaming and polishing have been pushed to `master`.
