### ISSUE TITLE
Document how to execute static nested test classes with Maven Surefire

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1378]
## Overview

In light of #1377, we should inform users that static nested test classes are supported by JUnit Jupiter but are excluded from Maven builds by default.

## Deliverables

- [ ] Document that JUnit Jupiter supports `static` nested test classes.
- [ ] Document how to execute `static` nested test classes in a Maven build.
  - See solution [here](https://github.com/junit-team/junit5/issues/1377#issuecomment-381964988).

**Comment by marcphilipp** [comment]
_in progress_
