### ISSUE TITLE
Don't use human format for serialising time in XML report

### ISSUE THREAD

**Issue by cburgmer** [junit-team/junit5#1381]
## Overview

- (x) **Bug report.**

For a test running longer than roughly 17 minutes, the time in seconds will reach 4 digits and XmlReportWriter (https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/tasks/XmlReportWriter.java#L239) will use a comma as a thousand separator. This is contrary to how for example XMLSerializer (https://w3c.github.io/DOM-Parsing/#the-xmlserializer-interface) would do that. No thousand separator or any other cultural formatting should be applied. The serialisation should rather be optimised for machine consumption.

Compare:

```xml
<testcase name="my_test" classname="com.example.something" time="14,029.255">
</testcase>
```

to XMLSerializer

```js
> p = document.createElement('p')
> p.setAttribute('data-x', 1/9 * 10000)
> new XMLSerializer().serializeToString(p)
"<p xmlns=\"http://www.w3.org/1999/xhtml\" data-x=\"1111.111111111111\"></p>"
```

## Deliverables

- [ ] Use standard float serialisation

**Comment by marcphilipp** [comment]
Thanks for reporting this issue! The XSD we use do validate our output in our tests does not really help here: it defines `time` as a string.

Thus, I did a bit of research to find out what other producers write and consumer expect when reading. [Gradle](https://github.com/gradle/gradle/blob/4f2f2b6822bd90774830729452e3f8536ff1b0ff/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/JUnitXmlResultWriter.java#L95-L98) uses `String.valueOf(Double)`, [Maven Surefire](https://github.com/apache/maven-surefire/blob/17c18e5209cf1544f7ace31e99573e65a135bb60/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/ReporterUtils.java#L40-L44) also uses `NumberFormat` with an English locale. On the consumer's side, [Jenkins](https://github.com/jenkinsci/junit-plugin/blob/1bdadf2d6d79bb2e2eb15f260180ef3c8bbe8286/src/main/java/hudson/tasks/junit/TimeToFloat.java#L42-L56) seems to be able to handle both.

@cburgmer Which tool broke when the `,` separator was present in the XML document?

**Comment by cburgmer** [comment]
> Which tool broke when the , separator was present in the XML document?

I am parsing the document via Clojure's `Float/parseFloat`:
```clj
user=> (Float/parseFloat "1,111.111")

NumberFormatException For input string: "1,111.111"  sun.misc.FloatingDecimal.readJavaFormatString (FloatingDecimal.java:2043)
```

**Comment by marcphilipp** [comment]
When I originally wrote the XML writer, I checked how Maven Surefire outputs the time. Thus, it now includes the `,`. We've discussed this issue in the team and came to the conlusion _not_ to change it. 

Please use a workaround similar to the one used by Jenkins (linked above):

```java
    public float parse() {
        if (time != null) {
            time = time.replace(",", "");
            try {
                return Float.parseFloat(time);
            } catch (NumberFormatException e) {
                try {
                    return new DecimalFormat().parse(time).floatValue();
                } catch (ParseException x) {
                    // hmm, don't know what this format is.
                }
            }
        }
        return 0.0f;
    }
```

**Comment by agilob** [comment]
Number with `,` in as a separator is US number formatting, other cases use `.` space or nothing. It breaks paring in non-US number parsers. It would be useful to allow us setting it with a locale flag or following system wide locale.
