### ISSUE TITLE
Provide Kotlin extension function for ArgumentsAccessor

### ISSUE THREAD

**Issue by juergenzimmermann** [junit-team/junit5#1382]
When using JUnit 5.2.0-RC1 with Kotlin, you have to write e.g.:
```
val date = args.get(2, LocalDate::class.java)
```
It would be smoother when one could write (as e.g. in https://github.com/junit-team/junit5/blob/r5.2.0-RC1/junit-jupiter-api/src/main/kotlin/org/junit/jupiter/api/Assertions.kt#L96):
```
val date = args.get<LocalDate>(2)
```

**Comment by hutaidavid** [comment]
Hello!
I would like to work on this issue if it is not a problem and be part of the contribution.

**Comment by WilderPereira** [comment]
Hello, I'm also interested in working on this issue! How can we proceed?

**Comment by marcphilipp** [comment]
Let's decide if/how to implement it before getting started. Having said that, I'm all for it.

Can this be implemented as a extension function?

**Comment by marcphilipp** [comment]
@hutaidavid @WilderPereira Are you still interested in working on this issue?

**Comment by marcphilipp** [comment]
Well then, go for it! 🙂

**Comment by marcphilipp** [comment]
_in progress_ by @WilderPereira
