### ISSUE TITLE
Only instantiate ArgumentConverters and ArgumentsAggregators once per parameterized test method

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1397]
Currently, any `ArgumentConverter` or `ArgumentsAggregator` registered via `@ConvertWith` or `@AggregateWith`, respectively, is instantiated once per invocation of the `@ParameterizedTest` method.

For example, the following class

```java
class NoisyTestCase {

    static class MyConverter implements ArgumentConverter {
        public MyConverter() {
            System.out.println("created instance of " + MyConverter.class);
        }

        @Override
        public Object convert(Object source, ParameterContext context) throws ArgumentConversionException {
            return source;
        }
    }

    static class MyAggregator implements ArgumentsAggregator {
        public MyAggregator() {
            System.out.println("created instance of " + MyAggregator.class);
        }

        @Override
        public Object aggregateArguments(ArgumentsAccessor accessor, ParameterContext context) throws ArgumentsAggregationException {
            return null;
        }
    }

    @ParameterizedTest
    @ValueSource(ints = {1, 2, 3})
    void test(@ConvertWith(MyConverter.class) int i, @AggregateWith(MyAggregator.class) Object o) {
        System.out.println("test(" + i + ", " + o + ")");
    }
}

```

prints

```
created instance of class NoisyTestCase$MyConverter
created instance of class NoisyTestCase$MyAggregator
test(1, null)
created instance of class NoisyTestCase$MyConverter
created instance of class NoisyTestCase$MyAggregator
test(2, null)
created instance of class NoisyTestCase$MyConverter
created instance of class NoisyTestCase$MyAggregator
test(3, null)
```

## Deliverables

- [ ] Instantiate `ArgumentConverter` or `ArgumentsAggregator` registered via `@ConvertWith` or `@AggregateWith`, respectively, only once per parameterized test method (e.g. instantiate eagerly or reuse for subsequent invocations)

**Comment by sbrannen** [comment]
If we go that route, we should immediately (i.e., before the 5.2 GA release) update the JavaDoc for `ArgumentConverter` and `ArgumentsAggregator` to require that implementations must be thread-safe and stateless.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda,

FYI: Slated for 5.2 GA in order to address the previous documentation task.

This issue can be reassigned to 5.3 M1 once the documentation is updated.

**Comment by marcphilipp** [comment]
Documentation was updated in 8a41632695f12f8d61a1a4824f50a712964ec0f2. Reassigning to 5.3 M1 now.

**Comment by sbrannen** [comment]
Thanks, @gaganis and @marcphilipp! 👍
