### ISSUE TITLE
Request For Enhancement: simple mechanism to tell the framework which test methods to run without @Test annotation

### ISSUE THREAD

**Issue by henrik-io** [junit-team/junit5#1402]
I wanted to be able to be able to run unit tests without them being picked up automatically. I.e. I only want to run them from inside a `main()` method. Sormuras came up with a solution to my question [here](https://stackoverflow.com/questions/50110819/launching-junit-jupiter-tests-from-inside-a-main-method), and suggested that I submit a feature request. I propose that specifying a class or method in a `selector` supplied to the `LauncherDiscoveryRequestBuilder` should make the engine pick that class/methods up and run them even if they're not annotated with `@Test`. I.e. it would be an alternative method of telling the engine what to run.

**Comment by sbrannen** [comment]
The problem is that there is not a single "engine".

There can be multiple competing engines running at the same time.

So, how would each engine know it's supposed to run the test or method?

**Comment by henrik-io** [comment]
I'm not familiar with the implementation, so I can't comment on that, but from a 10,000 foot view, why would it be different to declare a method as a candidate for a test using an annotation vs very specifically telling the framework "please consider this method a test method"?  The use case is essentially to be very specific about when to run the particular test method. I.e. I never want it to run as part of the standard "run all tests" scenario, only when I specifically choose to run it. Sormuras came up with two viable solutions, although I think that there should be an easier and more specific way of doing it. The `@EnabledIf` solution is definitely useful, but it gets tedious if you have many test methods. Maybe I'm misunderstanding the semantics of the `selectors()` method, but it seems reasonable to me that if I explicitly point out a class, or one or more methods to run, the engine(s) should pick those up. I was surprised that explicitly selecting a class and/or methods to run via the `selectors()` mechanism didn't work the way I expected.

**Comment by henrik-io** [comment]
The `@EnabledIfSystemProperty` annotation looks like it could be useful here. I did something like this:
```
private static final String prop = "onlySetInThisClass";
private static final String match = "cantGuessThis";

public static void main(String[] args) {
    System.setProperty(prop, match);
    ...
} 

@Test
@EnabledIfSystemProperty(named = prop, matches = match)
void myTestMethod() {
    ...
}
```

A little more work than what I'd like it to be, but it certainly works.

**Comment by sormuras** [comment]
> So, how would each engine know it's supposed to run the test or method?

By using its unique ID: `"[engine:junit-jupiter]/[class:com.example.S3ManualTest]/[method:happyPath()]"`

At the moment, because there's no `@Test` attached to `happyPath()` it reports:

```
org.junit.jupiter.engine.discovery.JavaElementsResolver handleResolvedDescriptorsForUniqueId
WARN: Unique ID '[engine:junit-jupiter]/[class:com.example.S3ManualTest]/[method:happyPath()]' could only be partially resolved. All resolved segments will be executed; however, the following segments could not be resolved: [Segment [type = 'method', value = 'happyPath()']]
```
