### ISSUE TITLE
@Disabled annotation not honored using Maven

### ISSUE THREAD

**Issue by giacgbj** [junit-team/junit5#1403]
Environment:

- JDK 8
- Maven 3.5.3
- JUnit 5.2.0
- maven-surefire-plugin 2.21.0
- Eclipse Oxygen.3a (4.7.3a)

When I run the [attached sample project](https://github.com/junit-team/junit5/files/1968805/foo.zip) in Maven both the tests are executed, while running them in Eclipse the annotation works.

Project highlights:

**pom.xml**
```
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.junit</groupId>
			<artifactId>junit-bom</artifactId>
			<version>5.2.0</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
<dependencies>
	<dependency>
		<groupId>org.junit.jupiter</groupId>
		<artifactId>junit-jupiter-api</artifactId>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.junit.platform</groupId>
		<artifactId>junit-platform-launcher</artifactId>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.junit.jupiter</groupId>
		<artifactId>junit-jupiter-engine</artifactId>
		<scope>test</scope>
	</dependency>
</dependencies>
<build>
	<plugins>
		<plugin>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.21.0</version>
		</plugin>
	</plugins>
</build>
```

**TestFoo.java**:
```
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

public class TestFoo {

    @Test
    public void testEnabled() {
        System.out.println("ENABLED");
    }

    @Disabled
    @Test
    public void testDisabled() {
        System.out.println("DISABLED");
    }

}
```

**Comment by sormuras** [comment]
Please add the `junit-platform-surefire-provider` to the `maven-surefire-plugin` configuration:



		<plugin>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.21.0</version>
			<dependencies>
				<dependency>
					<groupId>org.junit.platform</groupId>
					<artifactId>junit-platform-surefire-provider</artifactId>
				</dependency>
			</dependencies>
		</plugin>

**Comment by giacgbj** [comment]
Adding it:
```
[ERROR]   The project it.jhack.foo:foo:0.0.1-SNAPSHOT (/Users/jhack/workspace/foo/pom.xml) has 1 error
[ERROR]     'build.plugins.plugin[org.apache.maven.plugins:maven-surefire-plugin].dependencies.dependency.version' for org.junit.platform:junit-platform-surefire-provider:jar is missing. @ line 57, column 18
```

It seems Maven can't handle dependency management for plugin dependencies, so I had to specify a version too.

It works like that, but **junit-bom** seems to be useless in this case. Is there a way to avoid specifying the version?

**Comment by sormuras** [comment]
Mh, the BOM-POM contains the provider:

```xml
<dependency>
  <groupId>org.junit.platform</groupId>
  <artifactId>junit-platform-surefire-provider</artifactId>
  <version>1.2.0</version>
</dependency>
```

http://central.maven.org/maven2/org/junit/junit-bom/5.2.0/junit-bom-5.2.0.pom

IFAICT it should work.

**Comment by sormuras** [comment]
No. It does not work. See https://issues.apache.org/jira/browse/MNG-5588 for details.

Closing this issue as the initial `@Disabled`-related question is resolved.

**Comment by DineshNO** [comment]
I am using below for compatablity with jdk 12 Junit 5 test cases.
`
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M3</version>
                    <configuration>
                        <argLine>-Djava.net.preferIPv4Stack=true</argLine>
                    </configuration>
                </plugin>
`
@Disabled doesnot skip the tests.
Any additional configuration required

**Comment by marcphilipp** [comment]
@DineshNO Are tests being executed at all?

**Comment by DineshNO** [comment]
> @DineshNO Are tests being executed at all?

Hi @marcphilipp 
my mistake.i was running integration tests and it fails in startup with another error 

[https://stackoverflow.com/questions/57936671/junit-5-integration-test-failed-in-maven-3-5-2-build](url)

So tried @Disable to ignore and mistook loading of the context as test execution.

Thanks.

**Comment by 3rdstage** [comment]
Maven Surefire Plugin added **native support** for JUnit Platform (JUnit 5) from **version 2.22.0**.  Apache JIRA issue [SUREFIRE-1330](https://issues.apache.org/jira/browse/SUREFIRE-1330) is for this.

So, the below plug-in declaration is enough to support `@Disabled` tags and other stuffs of JUnit 5.

```xml
        <plugin>
          <!-- For more, refer https://maven.apache.org/surefire/maven-surefire-plugin/ -->
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.2</version>
        </plugin>
```
