### ISSUE TITLE
Dependency Diagram not rendered in User Guide

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1404]
The Dependency Diagram is not rendered in the **current** version of the User Guide. Instead, the source code was emitted:

```
skinparam {
    defaultFontName Open Sans
}

package org.junit.jupiter {
    [junit-jupiter-api] as jupiter_api
    [junit-jupiter-engine] as jupiter_engine
    [junit-jupiter-params] as jupiter_params
    [junit-jupiter-migrationsupport] as jupiter_migration_support
}

package org.junit.vintage {
    [junit-vintage-engine] as vintage_engine
...
```

https://junit.org/junit5/docs/current/user-guide/#dependency-diagram

Both, the HTML and PDF versions are affected.

The **snapshot** version shows the expected image: 

![component-diagram](https://junit.org/junit5/docs/snapshot/user-guide/images/component-diagram.svg)

https://junit.org/junit5/docs/snapshot/user-guide/#dependency-diagram

**Comment by sbrannen** [comment]
Ooooooooops! 😱

**Comment by sbrannen** [comment]
Good catch.

Perhaps that part of the build ran in a _daemon_ Gradle process? 🤷🏻‍♂️

**Comment by marcphilipp** [comment]
Clear case of ”does _not_ work on my machine“… 😂

I‘ll check what went wrong later and fix it.

**Comment by marcphilipp** [comment]
It's not like it didn't happen before (cf. #1222). I generated and uploaded the documentation again and added `--no-daemon` to the [Releasing](https://github.com/junit-team/junit5/wiki/Releasing) instructions for now. We can remove it from there again when https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/222 is fixed.

**Comment by sbrannen** [comment]
👍
