### ISSUE TITLE
Introduce a @NotThreadSafe annotation

### ISSUE THREAD

**Issue by arcuri82** [junit-team/junit5#141]
Feature request:

To speed up testing, one would like to run unit tests in parallel on the same JVM.
This is already possible for example in the Maven Surefire plugin. 
However, in some cases you cannot run some of the unit tests in parallel. 
An example is when more than one test does manipulate the same static state, eg a cache.
It would be good to be able to have a tag to specify that a specific test (or test class) should never be run in parallel on the same JVM. 
It would be then the responsibility of the runner (eg Surefire/Failsafe plugins) to honor such constraint. 

A further annotation (or an option in the above one) could be used to tag a test to never run in parallel, not even if in a different spawn JVM. This might be for example useful if a set of tests are manipulating a same external resource (eg writing/reading a file). I personally never encountered such case, but I guess it could happen.

**Comment by Tibor17** [comment]
Use JCIP annotations as we do in Surefire few years.
As @arcuri82 mentioned, we use it in Surefire and here is our documentation
https://maven.apache.org/surefire/maven-failsafe-plugin/examples/fork-options-and-parallel-execution.html#Parallel_Test_Execution_and_Single_Thread_Execution

**Comment by djangofan** [comment]
WHEN forking test by class, my utopian dream is that each fork isolates the test in a way such that exceptions wont fail the test suite, but only fail the individual test-thread.   Thats a problem I have with TestNG running via Surefire.  This could be where JUnit might be able to exceed TestNG.

**Comment by marcphilipp** [comment]
Related issue: #60.

**Comment by marcphilipp** [comment]
This can be done since 5.3 using `@Execution(SAME_THREAD)`.
