### ISSUE TITLE
Add ability to use datasource in class with @Nested Tests

### ISSUE THREAD

**Issue by kiryl-naurotski** [junit-team/junit5#1411]
## Overview

Right now tests located in a `@Nested` class run only after tests in enclosing classes have finished their execution. Such behavior doesn't allow one to run test classes with different values.

If we run the following test class:

```java
public class StackTest {
    static int number;

    @ParameterizedTest
    @ValueSource(ints = {1, 2, 3, 4})
    @DisplayName("is instantiated with new Stack()")
    void isInstantiatedWithNew(int numbers) {
        number = numbers;
    }

    @Nested
    @DisplayName("when new")
    class WhenNew {

        @Test
        @DisplayName("is empty")
        void isEmpty() {
            System.out.println("Is empty: " + number);
            assertTrue(true);
        }

        @Nested
        @DisplayName("after pushing an element")
        class AfterPushing {

            @Test
            @DisplayName("it is no longer empty")
            void isNotEmpty() {
                System.out.println("is not empty: " + number);
                assertTrue(true);
            }
        }
    }
}
```

... we will see that all nested tests received only the last number (4).

Is there any way to send all provided numbers to nested tests?

## Related Issues

- #878

**Comment by sbrannen** [comment]
> Is there any way to send all provided numbers to nested tests?

There is no built-in mechanism for achieving that.

If you just want the list of numbers, you could of course store them in a field of type `List<Integer>` instead of only storing the last one in a field of type `int`.

**Comment by sbrannen** [comment]
The ability to run test classes with different values (i.e., to _parameterize_ test classes) will be introduced in conjunction with #878.

I am therefore closing this issue as a _duplicate_.

Feel free to provide further input in #878.

Thanks!

**Comment by sbrannen** [comment]
> Also for some reason class with nested tests runs faster, than class with single test with the same number of checks and actions

I cannot imagine how that could be the case since the execution of a class along with its nested classes technically requires more work.

So, if you can provide a small project that proves that, we'd be interested in seeing that (in a separate GitHub issue).

Cheers

**Comment by kiryl-naurotski** [comment]
> Do the proposals in #871 and #878 address your needs?
It seems that yes

**Comment by sbrannen** [comment]
> It seems that yes

Great. Thanks for the feedback!
