### ISSUE TITLE
Add possibility to disable tests on AIX by using @DisabledOnOs(AIX)

### ISSUE THREAD

**Issue by epeee** [junit-team/junit5#1412]
## Overview

It would be great if we could ignore certain tests only on AIX by using `@DisabledOnOs(AIX)`.
Due to `OS.OTHER` this change might be a breaking one.

## Deliverables

- [ ] Add AIX to OS enum and add AIX detection

**Comment by sbrannen** [comment]
What?

People run JUnit Jupiter tests on AIX? 😱

**Comment by sbrannen** [comment]
All kidding aside, I think it would be fine to introduce explicit support for `AIX`.

The `OS.OTHER` enum constant is essentially meant to be used when none of the other constants apply, and the intent was to be able to add additional enum constants over time.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Support for AIX has been pushed to `master` and will be available in 5.3 M1.

Feel free to try it out in the upcoming snapshot artifacts.
