### ISSUE TITLE
Introduce java.time formatting support for @ParameterizedTest display names

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#1418]
## Feature request

The display name of the following is not very readable. Of course the real problem is that Java didn't make `DateTimeFormatter` implement `Format`; otherwise, I believe this would work out of the box.

It would be nice to provide java.time formatting for the display name. Might also be nice to allow custom formatters. 

```java
    @ParameterizedTest( name = "[{index}] {1}  is {2} from now {0}")
    @ArgumentsSource( Instants.class )
    void testIsLockedOn( Instant now, Instant time, Duration duration ) {
        assertThat( lockedRange.isLockedOn( time ) ).isEqualTo( SEC.equals( duration ) );
    }
```

**Comment by sbrannen** [comment]
To simplify analysis, the following example can be used stand alone.

```java
@ParameterizedTest(name = "[{index}] {1} is {2} from now {0}")
@MethodSource
void testIsLockedOn(Instant now, Instant time, Duration duration) {
}

static Stream<Arguments> testIsLockedOn() {
	return Stream.of(
		Arguments.of(Instant.now(), Instant.now().plusSeconds(100), Duration.ofMillis(1000)),
		Arguments.of(Instant.now(), Instant.now().plusSeconds(200), Duration.ofMillis(2000))
	);
}
```

**Comment by sbrannen** [comment]
Execution of the above stand-alone example with the `ConsoleLauncher` results in the following.

```
│  │  ├─ testIsLockedOn(Instant, Instant, Duration) ✔
│  │  │  ├─ [1] 2018-05-12T14:39:24.395442Z is PT1S from now 2018-05-12T14:37:44.395437Z ✔
│  │  │  └─ [2] 2018-05-12T14:39:24.395461Z is PT2S from now 2018-05-12T14:37:44.395460Z ✔
```

**Comment by sbrannen** [comment]
Related OpenJDK bug issue: https://bugs.openjdk.java.net/browse/JDK-8016743

**Comment by sbrannen** [comment]
Related thread on OpenJDK mailing list: http://mail.openjdk.java.net/pipermail/core-libs-dev/2013-December/023665.html
