### ISSUE TITLE
Add Microtests for MethodInvoker

### ISSUE THREAD

**Issue by mmerdes** [junit-team/junit5#142]

**Comment by mmerdes** [comment]
@signed: are you still working on this?

**Comment by signed** [comment]
I intend to, just waiting for feedback on #223 to see if I can keep using [`ExtensionRegistry`](https://github.com/junit-team/junit5/blob/master/junit5-engine/src/main/java/org/junit/gen5/engine/junit5/extension/ExtensionRegistry.java) for the tests (preferred) or if I better move to a test double.
[Here](https://github.com/signed/junit5/blob/sandbox/junit-tests/src/test/java/org/junit/gen5/engine/junit5/execution/MethodInvokerTests.java) is what I have so far. I'll squash the commits before the pull request.

**Comment by marcphilipp** [comment]
#223 has been merged.

**Comment by sbrannen** [comment]
Merged PR #248 into `master` in 3ebaf5fc328931679943bb55a4007a64d5cf7b85.
