### ISSUE TITLE
Add support for testing private methods and fields

### ISSUE THREAD

**Issue by tutoref** [junit-team/junit5#1420]
## Overview

Everytime you want to test a private method or access a private field you should add code that uses java reflexion.
Can JUnit offer a reusable mean to access (read/write) private class members ?

**Comment by jbduncan** [comment]
Hi @tutoref. Potentially good news: this can be achieved without reflection by making the necessary private methods package-private.

Would this work for you? :)

**Comment by tutoref** [comment]
@jbduncan not really, I should keep using private methods. However it's a good technique when it is allowed to have package-private methods.

**Comment by marcphilipp** [comment]
Providing a API to read/write fields is outside of the scope of JUnit. Apache Commons Lang has [`FieldUtils`](https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/reflect/FieldUtils.html) that might help. In addition, JUnit's [`ReflectionSupport`](https://junit.org/junit5/docs/current/api/org/junit/platform/commons/support/ReflectionSupport.html#invokeMethod(java.lang.reflect.Method,java.lang.Object,java.lang.Object...)) provides a convenience method to invoke a potentially private method using reflection.
