### ISSUE TITLE
howto ? : Adding metainfo that is in CSV, HTML, XML and JUnit XML reports : enhancement?

### ISSUE THREAD

**Issue by hanasaki** [junit-team/junit5#1421]
How can arbitrary information be added to the JUnit run (per class and per method)?  Prefer in an annotation.  If not possible now, please consider this a feature/enhancement request.
examples: requirements number, reference number, some external info

Want the data to show up in:
- results data; xml, csv
- reports : html

Ideally to work in JUnit4 AND JUnit5

**Comment by gaganis** [comment]
Would a custom display name annotation serve your purposes? You can read about the feature here : https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-names

You could incorporate the information you need via a naming scheme / convention.

**Comment by hanasaki** [comment]
Wrote a short test in JUnit5 (non vintage) prior to the first posting.  The text of the @displayname is not in the XML result file nor CSV (should it be in the XML and CSV?  What could I have done wrong)  Also, there is ALOT in the CDATA section which is somewhat inconvenient to parse out vs an XML doc with more structure.

The idea is to post-process the JUnit XML report from JUnit4 and 5 without any need for special coding such as the TestInfo class as a parameter.

**Comment by marcphilipp** [comment]
@hanasaki How do you run your tests? Maven?

Jupiter provides an API to attach additional key-value pairs to a test:
https://github.com/junit-team/junit5/blob/master/documentation/src/test/java/example/TestReporterDemo.java#L20-L36

A similar API can also used by extensions:
https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TestReporterParameterResolver.java#L32

Thus, you can write an extension that looks for your annotation, e.g. `@Requirement("foo")`, using `AnnotationSupport` and call `ExtensionContext.publishReportEntry()`.

So, the APIs are in place. However, the current "standard" reporting format (XML) is not extensible. The plan is to define a new, extensible reporting format which will include reporting entries, display names etc. in https://github.com/ota4j-team/opentest4j/issues/9. Once that is defined, our `ConsoleLauncher` will output it and tools like Gradle and Maven will, hopefully, follow suit. Thus, I'm closing this issue for now. Feel free to follow the issue linked above to get notified on our progress.

**Comment by hanasaki** [comment]
- marcphilipp : I guess I missed the TestReporter auto-discover implied in your response. So sorry about that.  I will give it a try and see how the xml,cvs and html generated reports come out.  Was trying to use the built-in functionality if at all possible instead of writing and maintaining a plugin.
- Using gradle 4.x right now.  Will probably be using Maven as well / also in the future.
