### ISSUE TITLE
Add @Solo annotation

### ISSUE THREAD

**Issue by StaNov** [junit-team/junit5#1423]
## Overview

Situation: I have a test class with 20 @ Test methods. I want to run only 5 of them.

Current options:
* Add @ Ignore to the 15 tests and run all the class.
* Run only selected tests with special command line options enumerating them.
* Make the desired tests fail and rerun only failed in IDE.

Proposal:

Create a @ Solo annotation for test methods. It will serve the same purpose as the "solo" option in multitrack audio editing software.

* If you create an audio project and hit no solo/mute, all tracks play.
  * If you create a test class with no ignores, all run.
* If you hit mute on one or more tracks, all other tracks play except the muted ones.
  * If you ignore one or more tests, all other run except the ignored ones.
* If you hit solo on one track, only the one selected track plays.
  * If you use @ Solo on myTest, only myTest gets run.
* If you hit solo on two tracks and mute on three tracks, only the two solo'ed tracks are played.
  * If you put @ Solo on myTest1 and myTest2 and ignore three other tests, only myTest1 and myTest2 run.

If at least one test is annotated as @ Solo, others are marked as ignored in IDEs and reports etc.

Example:

    public class MyTestClass {
        @Test
        @Solo
        public void thisTestWillRunBecauseAnnotatedAsSolo() {
            ...
        }

        @Test
        public void thisTestWillNotRun() {
            ...
        }

        @Test
        @Solo
        public void thisTestWillAlsoRunBecauseAnnotatedAsSolo() {
            ...
        }

        @Test
        public void thisTestWillNotRunToo() {
            ...
        }
    }

## Deliverables

- [ ] The @ Solo annotation described above.

**Comment by marcphilipp** [comment]
Thanks for creating the issue! However, you're not the first one. Please join the discussion in #346.

Duplicates #346.
