### ISSUE TITLE
Migrate from Maven Plugin to Maven Publish Plugin

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1426]
## Overview

The Gradle team has recently stated that the [Maven Publish Plugin](https://docs.gradle.org/4.8-rc-1/userguide/publishing_maven.html) is now stable and should be used in favor of the "old" [Maven Plugin](https://docs.gradle.org/4.8-rc-1/userguide/maven_plugin.html). Since we currently use the latter, we should look into migrating to the _Maven Publish Plugin_.

## Deliverables

- [ ] Migrate to the _Maven Publish Plugin_ in the Gradle build.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by sbrannen** [comment]
wow.... you jumped on this one like a 🦇 outta #3!!. 😉

**Comment by marcphilipp** [comment]
Well, I was already contemplating to do it. 😂
