### ISSUE TITLE
TestInfo should contain the list of tags of a test

### ISSUE THREAD

**Issue by schauder** [junit-team/junit5#143]
At least I would expect such information there.

**Comment by jlink** [comment]
Todos:
- [ ] Introduce `TestInfo.getTags()`
- [ ] Document `TestInfo.getTags()`

**Comment by schauder** [comment]
I tried just now to obtain the tags inside a MethodParameterResolver, and couldn't find them?

Did I look in the wrong spot? Should it be part of this issue? Or should it be a new one?

**Comment by jlink** [comment]
Since TestInfo is provided by MethodParameterResolver I'd say it's the same thing. 

Von meinem iPad gesendet

**Comment by sbrannen** [comment]
@schauder,

That's actually a separate issue. Tests should be able to retrieve the tags from `TestInfo`; whereas, an extension should be able to retrieve the tags from the `ExtensionContext`.

Can you please open a separate issue to address the latter?

Thanks!

Sam

**Comment by jlink** [comment]
Solved in master.
