### ISSUE TITLE
Investigate warning printed when compiling Kotlin code

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1432]
```
w: junit5/junit-jupiter-params/src/main/kotlin/org/junit/jupiter/params/aggregator/ArgumentsAccessor.kt:
(23, 47): Extension is shadowed by a member: 
  public abstract operator fun get(index: Int): Any!
```

## Deliverables

- [x] Figure out if this is a problem, i.e. if both methods can still be called from Kotlin code
- [ ] Fix or suppress warning for this specific case

**Comment by mmerdes** [comment]
@bit-jkraushaar 
Do you have an opinion here?

**Comment by sbrannen** [comment]
@sdeleuze, any tips for us here?

**Comment by sdeleuze** [comment]
I guess there is a potential conflict between an existing method and the extension so in practice it could not be reachable but that's can be a false warning. The best way to ensure it is ok is to have a test using it and using `@Suppress("EXTENSION_SHADOWED_BY_MEMBER")` to avoid this warning.

**Comment by sbrannen** [comment]
Thanks for advice and tip, @sdeleuze! 👍 

We'll add some tests and suppress the warning if appropriate.

**Comment by marcphilipp** [comment]
_in progress_
