### ISSUE TITLE
(Suggestion : feature / improvement) Do not rerun tests where nothing had changed

### ISSUE THREAD

**Issue by belun** [junit-team/junit5#1434]
## Overview

To start with a  disclaimer : this feature would not be generic. It would not apply for fast running tests, but more for slow tests / integration tests. 

A. If one thinks about an engine whose purpose is to skip tests, the first idea to spawn in mind is "That defeats the whole purpose of the concept of testing. I want to change stuff, and I want the tests to tell me what I broke". 

However, there can be some tests that take a lot of time (integration tests are the most basic example), so why run them for no particular reason? Notice how above, one part of the remark is "I want to change stuff and...". So, how about when nothing changed?

B. Another remark would be : "isn't this engine dangerous?" and the answer : "hell, yeah"

**Feature request.** 
Do not rerun tests where nothing has changed.

For a certain type of tests (marked with a specific annotation ; in order to keep the global approach "run all tests"), try to optimize the reruns. 

Build a dependency matrix (things that impact each test), monitor the dependencies and rerun only where changes had ocured.

## Deliverables
Concepts:
1. test resources = anything that, when changed, could affect the test results ; the test class itself and the class under test are implicit test resources ; other things could be : files that are used as inputs for tests (changing should a file would definitely require a test rerun)
2. tests and resource dependency matrix

Real deliverables
a. the reports show what was run and why (what changed from the dependency list that triggered the runner to rerun a test) 
b. annotations to configure what goes under the jurisdiction of this new engine
c. OR dsl for the Runner to configure this new engine
d. annotations to "guide" the engine : basically markers or configuration that says what is a "test resource" and to which test it applies; in fact, this engine does not have to be smart at all (there will be no magic inside of it that detects what is a "test resource"), it will just read the configuration, monitor resources between runs, and rerun tests according to the dependency matrix

**Comment by sormuras** [comment]
Build tools are better suited here, methinks.

A build tool, that knows much more about "main" and "test" dependences, assets, external resources, and what-not, could take care running only test affected by some change. Encoding all this into an implemenation of a `TestEngine` (like Jupiter) is not trivial and needs to re-use or duplicate a lot configuration work already done for your build process anyway.

On the other hand, if you come up with an implementation spike of a `TestEngine` that achieves that feature I'll be interested in using it.

**Comment by sbrannen** [comment]
I agree with @sormuras: the proposed feature is better suited for an IDE or a build tool.

In addition, there is already a product on the market for this: [Infinitest](https://infinitest.github.io/).

In light of that I am inclined to close this issue.

**Comment by sbrannen** [comment]
In light of the above comments I am closing this issue.
