### ISSUE TITLE
Clarify and document names and display names of JUnit 4 and 5 TestDescriptors

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#145]
- [ ] Display Name of @Nested Test Class should probably be the simple name of the class.
- [ ] Should the display name for a method really include the class it's running in?

----
### Related To
- #153
- #162

**Comment by jlink** [comment]
The current default for `displayName` contains the fully qualified name of classes and methods. I think the simple name would be enough. I'd rather provide the source as an additional property if there's really a need for that.

**Comment by jlink** [comment]
Furher discussion on #153
