### ISSUE TITLE
Introduce extension APIs to handle exceptions from lifecycle callback methods

### ISSUE THREAD

**Issue by beluha** [junit-team/junit5#1454]
## Overview

I need to handle exceptions thrown during the execution of each `@BeforeAll`, `@AfterAll`, `@BeforeEach`, and `@AfterEach` method.

There are [test lifecycle callbacks](https://junit.org/junit5/docs/current/user-guide/#extensions-lifecycle-callbacks). Just for error tracking needs these callbacks are useful, but if I need to capture AUT (application under test) state (for example to take an application screenshot, log current condition) at exception time, then these callbacks are not enough, because application state is changed before execution reaches the callback.

Let's say an exception occurs in a `@BeforeEach` method. I need to take an application screenshot at this exception. The nearest callback to handle the exception is `AfterEachCallback`. So application state is changed in `@AfterEach` method, and we lose original screen of application in `AfterEachCallback`. I reference to the [diagram here](https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order).

## Proposal

Introduce the following additional _callback_ extension APIs which will be invoked after each `@BeforeAll`, `@AfterAll`, `@BeforeEach` and `@AfterEach` method. This make it possible to handle exceptions and take application screenshots at the correct point in time.

- `AfterBeforeAllCallack`
- `AfterAfterAllCallback`
- `AfterBeforeEachCallback`
- `AfterAfterEachCallback`

**Comment by sbrannen** [comment]
Tentatively slated for the 5.3 backlog for _team discussion_

**Comment by marcphilipp** [comment]
Alternatively, we could add these callback methods to `TestExecutionExceptionHandler`, e.g. `handleExceptionInBeforeEachMethod(ExtensionContext context, Throwable throwable)`.

**Comment by sbrannen** [comment]
Yep, that's also an option.

**Comment by beluha** [comment]
I'm also concerned about handling exceptions in time in constructors.
Introduction of additional callback methods or exception handlers for constructors could be a good option as well taking into account `@TestInstance` values `Lifecycle.PER_METHOD` and `Lifecycle.PER_CLASS`.

**Comment by phoenix384** [comment]
I made PR 1509. It handles exceptions for BeforeEach and AfterEach methods. BeforeAll and AfterAll is still missing - it's just to get the idea.
@marcphilipp Is this what you had in mind?

**Comment by marcphilipp** [comment]
@phoenix384 Yeah, that looks promising! Would you mind adding the same for `@BeforeAll` and `@AfterAll`?

**Comment by phoenix384** [comment]
@marcphilipp done

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 RC1 due to work being performed in #1509.

**Comment by JockX** [comment]
As the work done on #1509 got stalled, I prepared another pull request #1868, that fixes the most outstanding issues, i.e. fulfills the DoD and has no conflicts with master. Appreciate the review.

**Comment by sbrannen** [comment]
Resolved in 2844ee40948b9ae14bc7426ad73c3400dbfff3a5

**Comment by beluha** [comment]
Hi team,

Did you have a chance to introduce Constructor exception handler mentioned by me in this comment https://github.com/junit-team/junit5/issues/1454#issuecomment-395669713 ?
Since 2018 many things have been included into JUnit 5. I didn't find in `org.junit.jupiter.api.extension` package required exception handler. Can you please help me to identify, how to handle exceptions thrown in Constructor in time like it has been done in this enhancement?

If that option is still not present, I would like to create feature request similar to current one.

**Comment by sbrannen** [comment]
Hi @beluha,

_This_ issue has been closed for over 2 years.

Please create a new issue to discuss a mechanism for handling exceptions thrown from a test class constructor.

With regard to handling exceptions thrown from a static block, I don't imagine that we would ever be able to support that reliably since a test class can be initialized outside the control of JUnit Jupiter mechanisms. Furthermore, I don't think we should attempt to do that.
