### ISSUE TITLE
Deprecate @ParameterizedTest and add required annotation to @ArgumentSource

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#1457]
In order to avoid [PEBCAK](https://www.webopedia.com/TERM/P/PEBCAK.html) errors and refactoring mistakes, I think it would be better to be able to simply write:

```java
@Test
@ArgumentSource(MySource.class)
```

... such that the "parameterized" portion becomes inferred.

This could also simplify conventions for #871, since you could simply put `@ArgumentSource` on the class as well... however this probably means more complicated code in JUnit Jupiter.

This is just an idea as client refactoring seems slightly tedious and error prone.

**Comment by sbrannen** [comment]
`@Test` signifies that the method is a standard test method.

`@ParameterizedTest` signifies that the method is parameterized and is actually a specialization of `@TestTemplate` which is discovered and executed completely separate from `@Test` methods.

We can therefore not reasonably treat a `@Test` as a `@TestTemplate` for technical reasons.

**Comment by sbrannen** [comment]
In any case, I do not see why the JUnit team would ever deprecate `@ParameterizedTest`.

**Comment by sbrannen** [comment]
In light of the above, I am closing this issue as _declined_.
