### ISSUE TITLE
@ParameterizedTest annotation does not appear to be valid in Groovy file

### ISSUE THREAD

**Issue by dlanaghen** [junit-team/junit5#1462]
I get a compile error using the `@ParamterizedTest` annotation in a Groovy file.  `@Test` works fine.

Using JUnit 5 parallel-exectution branch, but just testing a simple JUnit 5 test in a groovy file.

File:  ParamerizedTests.groovy

```groovy
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

class ParameterizedTests {
    @ParameterizedTest
    @ValueSource(strings = {"Dave", "Bill"})
    public void T(String s) {
        println( "Hello ${s}")
    }
}
```

I get a compile error.

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:generateTestStubs (default) on project fitpay-automation: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: startup failed:
[ERROR] /Users/davidlanaghen/work/automation3/automation/src/test/groovy/fitpay/automation/api/tests/users/ParameterizedTests.groovy: 8: unexpected token: @ @ line 8, column 5.
[ERROR]        @ParameterizedTest
[ERROR]        ^
[ERROR] 
[ERROR] 1 error
```

This is a springboot application and the following dependency has been added to allow for Groovy compilation:

```xml
       <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy</artifactId>
        </dependency>
```

**Comment by sormuras** [comment]
Any chance that the `org.junit.jupiter:junit-jupiter-params:5.2.0` is missing?

**Comment by sbrannen** [comment]
As @sormuras pointed out, you'll need to add the following to your POM:

```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-params</artifactId><version>${junit-jupiter.version}</version></dependency>
```

Please try that out and let us know if it solves your problem.

**Comment by marcphilipp** [comment]
Compilation fails because you have to use `[` and `]` instead of `{` and `}` in Groovy:

```groovy
class ParameterizedTests {
    @ParameterizedTest
    @ValueSource(strings = ["Dave", "Bill"])
    public void T(String s) {
        println( "Hello ${s}")
    }
}
```

**Comment by marcphilipp** [comment]
FWIW I added a Groovy-based starter projects to our samples:
https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle-groovy

**Comment by sbrannen** [comment]
> Compilation fails because you have to use `[` and `]` instead of `{` and `}` in Groovy:

Good catch!
