### ISSUE TITLE
JUnit Platform Surefire Provider silently ignores tests when run using Java 7

### ISSUE THREAD

**Issue by k1w1m8** [junit-team/junit5#1464]
I tried to use JUnit 5.2 surefire/failsafe provider in maven to run my tests.

I accidentally had the JDK set to 1.7. In that case I got this

```
[INFO] --- maven-failsafe-plugin:2.21.0:integration-test (default) @ CBASOL-JETQARUN-ALL-CI ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```
Eventually I figured out the JVM was wrong so I changed it to JDK 1.8.

Then I got

```
[INFO] --- maven-failsafe-plugin:2.21.0:integration-test (default) @ CBASOL-JETQARUN-ALL-CI ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.clear2pay.jetqarun.junit5.JUnit5TestFactory
...
```

So it seems that if you specify the wrong JDK, the provider silently ignores the tests. An obvious mistake on my part, but the error handling made it very difficult to diagnose the issue.

Note that all the tests i was running were DynamicTests. Not sure if that makes a difference, but it may do, 

Something as simple as an exception which says "JUnit5 surefire provider requires Java 8" would have made diagnosing a lot easier.

**Comment by sormuras** [comment]
@k1w1m8 As Surefire 2.22.0 is released can you please re-run your setup and verify if the issue still persists using the latest-and-greatest version with native JUnit Platform support?

Thanks in advance.
