### ISSUE TITLE
Should static @BeforeAll/@AfterAll methods in class annotated with @TestInstance(PER_CLASS) be executed if constructor throws exception?

### ISSUE THREAD

**Issue by gaganis** [junit-team/junit5#1465]
## Overview

Given a test class annotated with `@TestInstance(PER_CLASS)` with `static` `@BeforAll` and `@AfterAll` methods, if the constructor for the test class throws an exception, these callback methods are currently not executed.

Technically there is no restriction why these would not run (since an instance of the test class is not required to execute `static` methods in that class), so it is a matter of design what the expected behavior here would be. 

 - On the one hand, having a `PER_CLASS` class failing on the constructor suggests a major problem that warrants aborting everything. Also why run `@BeforeAll` of `@AfterAll` when we have run no tests? 
 - On the other hand, this seems inconsistent with what JUnit Jupiter does for classes that are instantiated _per method_ where a failing constructor does not affect the execution of methods annotated with `@BeforeAll` or `@AfterAll`.  So I personally consider this as unexpected behavior.

This was discussed in #1460 and refers to point _b)_ in comment https://github.com/junit-team/junit5/issues/1460#issuecomment-395965906

## Deliverables

- [ ] Clarify what the expected behavior in this case is.
- [ ] Document the expected behavior in the User Guide
- [ ] Review if automated tests currently cover the expected behavior.

**Comment by sbrannen** [comment]
Tentatively slated for the 5.3 backlog for _team discussion_

**Comment by sbrannen** [comment]
@gaganis, thanks for starting the discussion.
