### ISSUE TITLE
Document exception handling regarding user code and extension interactions in User Guide

### ISSUE THREAD

**Issue by gaganis** [junit-team/junit5#1466]
## Overview

In the User Guide we have [section 5.11](https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order) where the _happy path_ relative execution order is described. 

During our work on #1465 and #1460 I was trying to find in the user guide what would be the expected behavior when something fails. Specifically in that case I wanted to know what is expected to run when there is an exception in the constructor of the test class.

I would have expected this information to be described in the User Guide, yet it is not or I was unable to find it.

## Deliverables

- [ ] Document the expected execution paths and order in case of failures.
- [ ] Add link to this information in `Relative Execution Order Section` of the User Guide so it easy to find.

**Comment by smoyer64** [comment]
Related to #1022 (this may be a case where javadocs don't make sense but I prefer javadocs as they show up in my IDE).

**Comment by sbrannen** [comment]
@smoyer64, since the information required to document this would have to span multiple annotations and extension APIs, I don't think it would be feasible to cover it in the JavaDoc.

We could, however, consider linking to the User Guide from the JavaDoc for various annotations extension APIs.

**Comment by smoyer64** [comment]
package-info.java?

**Comment by sbrannen** [comment]
`package-info`: the question then is which package?

- `org.junit.jupiter.api`?
- `org.junit.jupiter.api.extension`?
- both?

**Comment by smoyer64** [comment]
Yeah ... I don't think it's optimal.  I've admitted I like javadocs due to their IDE integration but that makes the contents of package-info pretty invisible (or I don't know how to show them?)
