### ISSUE TITLE
Why doesn't Junit include a stub or mock feature?

### ISSUE THREAD

**Issue by BeyondW** [junit-team/junit5#1468]
## Overview
**Feature request.** 
Usually, I use Junit to do unit testing and integration testing. However, I need another framework like easymock to generate stub. Wouldn't it be better to integrate the feature within Junit?

**Comment by marcphilipp** [comment]
We see mocking out of scope for JUnit because there are already excellent mocking frameworks available, e.g. Mockito, EasyMock, and JMock. We believe users should be able to use their mocking framework of choice instead of another baked-in solution.
