### ISSUE TITLE
Introduce assertDefaultValue method

### ISSUE THREAD

**Issue by Andrei94** [junit-team/junit5#1471]
### **Feature request**
Provide convenient assertion methods for commonly used assertions, for example empty strings, assertIsZero etc, as well as a way to define a default value for your own objects.

### **Deliverables**

- [ ] convenience methods(`assertEmptyString`, `assertIsZero`...)
- [ ] way to define default value for objects

### **Possible solutions for defining default values** 
- use the default constructor of the objects
- match the passed arguments to the method call with an existing constructor

**Comment by jbduncan** [comment]
@Andrei94 Nice suggestion, regarding the convenience methods! However, in my personal opinion, existing _fluent_ assertion libraries like [Truth](https://google.github.io/truth/) and [AssertJ](https://joel-costigliola.github.io/assertj/) are the perfect solution for this problem, as they are more well-equipped to deal with _all_ the possible combinations of convenience assertions that one could want.

Do either of these libraries work for you? If not, how could JUnit 5 help improve things? :)

I admit that I don't understand what you mean by "define a default value for your own objects". Can you clarify further?

**Comment by sormuras** [comment]
I'm with @jbduncan here. Here's an excerpt from the User-Guide:
_**3.4.1. Third-party Assertion Libraries**_
_Even though the assertion facilities provided by JUnit Jupiter are sufficient for many testing scenarios, there are times when more power and additional functionality such as matchers are desired or required. In such cases, the **JUnit team recommends** the use of third-party assertion libraries such as **AssertJ**, **Hamcrest**, **Truth**, etc. Developers are therefore free to use the assertion library of their choice._
https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions-third-party

**Comment by marcphilipp** [comment]
+1 to what @sormuras wrote above.

@Andrei94 Feel free to reopen the issue if you think we've misunderstood your use case.

**Comment by sbrannen** [comment]
+1 to what @sormuras wrote above.

**Comment by sbrannen** [comment]
Yes, things like `assertEmptyString`, `assertEmptyCollection`, etc. are better suited for a dedicated assertion library.
