### ISSUE TITLE
Ignore JEnv specific files from version control

### ISSUE THREAD

**Issue by dotCipher** [junit-team/junit5#1473]
## Overview

- **Feature request:** `.gitignore` [jenv](https://github.com/gcuisinier/jenv) specific local files

If you are a developer who works with multiple versions of the JDK for multiple projects and want to easily specify Java 9+/10 for JUnit5, running `jenv local 10` will create a local dotfile specifying the `JAVA_HOME` etc shims to use for the local project (dotfile is called `.java-version`).

In an effort to reduce mistakes for developers who use jenv for managing their environments, I would request that we add `.java-version` as an ignored value for JUnit5 in it's `.gitignore`.

## Deliverables

- [ ] Ignore `.java-version` in `.gitignore`

**Comment by dotCipher** [comment]
See PR with proposed change: #1474

**Comment by marcphilipp** [comment]
Why don’t you just add that to your global Ignore list?

**Comment by dotCipher** [comment]
I honestly didn't even know that was possible!  Thanks for the pointer.  I would be fine closing this out if that is the suggested path of action here.

**Comment by marcphilipp** [comment]
Personally, I use [jabba](https://github.com/shyiko/jabba) which uses a `.jabbarc` file and have added it to my global ignore list. Other people might be using yet another such tool so I'd rather not add it to our `.gitignore` file. Thanks for the issue and PR, though! 👍
