### ISSUE TITLE
Fix broken tests in DefaultParallelExecutionConfigurationStrategyTests

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1478]
## Overview

Various tests in `DefaultParallelExecutionConfigurationStrategyTests` are broken (presumably) due
to issues with Mockito on Java 10. Specifically, the mocked method invocations appear not to work at all.

## Deliverables

- [x] Fix broken, `@Disabled` tests in `DefaultParallelExecutionConfigurationStrategyTests`.

**Comment by marcphilipp** [comment]
Fixed in 2ffddb5632880440ed61618a49792ff36dd7f54c.
