### ISSUE TITLE
Nashorn is deprecated in Java 11

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1481]
## Overview

With _"Deprecate the Nashorn JavaScript Engine"_ http://openjdk.java.net/jeps/335 integrated in JDK 11 we need to find another default value for `DisabledIf::engine() default "Nashorn";`:

- https://github.com/junit-team/junit5/blob/master/junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIf.java#L176

and also `EnabledIf::engine() default "Nashorn";`:

- https://github.com/junit-team/junit5/blob/master/junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIf.java#L176

Another Nashorn lives here:

- https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/script/Script.java#L35

## Marked for removal

_"A separate JEP will be filed for the actual removal of the types and modules in a future JDK feature release."_ 

Which feature version will be the first without Nashorn? 12?

## Alternatives

As explicitly stated in JEP 335: _"This deprecation does not affect, in any way, the `javax.script` API."_ finding another "general purpose language" via using the support exposed by the [java.scripting](https://download.java.net/java/early_access/jdk11/docs/api/java.scripting/module-summary.html) module should be possible.

- Provide JSR 223 compatible wrapper around [jdk.jshell](https://download.java.net/java/early_access/jdk11/docs/api/jdk.jshell/module-summary.html) -- it is based on `jdk.compiler` and should stay accessible for the next decade... methinks. Example: https://github.com/dmac100/JShellScriptEngine

- Find and integrate (shade) another light-wight solution: http://java-source.net/open-source/scripting-languages

- ...or mark `DisabledIf` and `EnabledIf` as deprecated (for removal) as well?

**Comment by jbduncan** [comment]
Kotlin may also work as a default, apparently: https://discuss.kotlinlang.org/t/embedding-kotlin-as-scripting-language-in-java-apps/2211/10

**Comment by mkobit** [comment]
May be worth thinking about https://github.com/graalvm/graaljs (or something like it)

**Comment by sormuras** [comment]
Graal VM offers a compatibility mode with _ScriptEngine_ support: https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f

**Comment by Frontrider** [comment]
Groovy would be a prime candidate because it's similar to Java, and Gradle already uses it.

**Comment by sormuras** [comment]
Groovy are Kotlin are both too heavy for the purpose of evaluating a simple (but generic) boolean expression. Groovy is already supported via its JSR 223 adapter. See this test: https://github.com/junit-team/junit5/blob/1925886aa7d0b5d570ab818768be941d65fcd758/platform-tests/src/test/java/org/junit/jupiter/extensions/EnabledIfTests.java#L128

Just found out that BeanShell is still alive: https://github.com/beanshell/beanshell/tree/merge-fork-beanshell2 -- maybe we may shade it into the Jupiter Engine artifact. Or have it in `provided` scope.

**Comment by Frontrider** [comment]
This?
https://github.com/JetBrains/jdk8u_nashorn

**Comment by sormuras** [comment]
Pulling in an entire JRE in order to evaluate a simple expression still feels heavy to me. Or is it distributed as minimal "standalone" jar?

Btw. now, using JDK 11 to build JUnit 5, this warning is emitted:
```
> Task :documentation:consoleLauncherTest
Warning: Nashorn engine is planned to be removed from a future JDK release
```

**Comment by Frontrider** [comment]
The only reason I threw that in, is because that contains a version that might be maintained if there is a use case.

I should probably just extract the script engine from it, then turn it into a library, but I don't have time for that. :/

**Comment by leonard84** [comment]
Maybe spring-expression SpEL?

**Comment by sormuras** [comment]
Is it available as self-contained distro with a JSR 223 implementation?

**Comment by leonard84** [comment]
It seems to need some glue-code https://github.com/melin/starflow/blob/master/src/main/java/com/googlecode/starflow/core/script/spel/SpelScriptEngine.java

There is an open issue for that https://jira.spring.io/browse/SPR-7651

```
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-expression</artifactId>
    <version>4.3.19.RELEASE</version>
</dependency>
```

See https://stackoverflow.com/questions/40074932/maven-entry-for-spel-as-a-scriptengine

It has a dependency on spring-core but I don't know if that is a crucial dependency or only some edge case.

**Comment by sormuras** [comment]
I tend to favor an in-memory `javac`-based `ScriptEngine` solution as the default engine.
It embeds a user script as a snippet into a pre-defined class template, compiles it to bytecode and evaluates it on demand.

- no external library is needed
- foundation tool `javac` will remain in the JDK
- the syntax (Java) is well-known

See #1599 for an implemetation spike.

**Comment by Frontrider** [comment]
So your solution is to use Java itself from scripting. That should work for all future java versions.

**Comment by sormuras** [comment]
> So your solution is to use Java itself from scripting. 

Aye.

> That should work for all future Java versions.

Don't be too sure, here. Thought that Nashorn (or some other Javascript interpreter) was here to stay "for ever". :-)

> Can you put a space between Java and ScriptEngine? I can't help to read that it uses javascript.

Names are not final, yet. The "Java[S|s]cript" pun was intended.

**Comment by sormuras** [comment]
> Can you sandbox it (or is it gonna be sandboxed by default)?

Mh, like with a SecurityManager? Don't know how feasible this is. The purpose of the scripted conditional execution extension is to provide a tool that users may use to test non-default stuff in a quick manner. The current solution using Nashorn is not guarded as well.

**Comment by leonard84** [comment]
Haven't looked in deeply but, can we use (parts of) `jshell` https://docs.oracle.com/javase/9/docs/api/jdk.jshell-summary.html for Java9+

**Comment by sormuras** [comment]
See first alternative in the initial issue description. `jshell` would be it, if it only was introduced in Java 8... trying hard to get JUnit 5 on 9+, but will fail for years, methinks.

**Comment by sormuras** [comment]
https://github.com/janino-compiler/janino

**Comment by leonard84** [comment]
We could support Nashorn up to Java 10 and offer fallback/forward to `jshell`, this should be doable via feature detection. `EnabledIf::engine() default "Nashorn";` could be changed to `default "Autodetect"` as long as the expressions the engines support are similar.

**Comment by leonard84** [comment]
We should at least allow to define a `default` engine for a project, instead of having to repeat it on every annotation if you want to choose `groovy` for example.

**Comment by sormuras** [comment]
Before we invest too much time into this "quick and one-shot-helper" and still experimental feature, I'd rather scrap it from the API. It was and is intended to used _very_ seldom, a custom `ExecutionCondition` is just class away and the pre-defined ones cover already a lot of use-cases:

> Mind the 3 notes at the start of https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-scripts

Having said this, my current plan is to do the following:

1. remove the default value from the annotation, forcing the user to specify an engine
2. show how to include an external scripting language via the JSR223 API
3. provide a `javac`-based script engine via https://github.com/sormuras/java-compiler-script-engine

Added the "team discussion" tag.

**Comment by leonard84** [comment]
One possibility would be to change `@EnabledIf`/`@DisabledIf` to have `Class<? extends ExecutionCondition>` or just `Class<? extends Predicate<ExtensionContext>>` as value which would be instantiated and then invoked to determine the result.

**Comment by Frontrider** [comment]
> 
> 
> One possibility would be to change `@EnabledIf`/`@DisabledIf` to have `Class<? extends ExecutionCondition>` or just `Class<? extends Predicate<ExtensionContext>>` as value which would be instantiated and then invoked to determine the result.
> 
> This would reduce some boilerplate for one-off conditions.
> 
> ```java
> @EnabledIf(MyCustomCondition.class)
> ```

I like the idea of that. Basically the same as implementing a java scripting engine, with actual ide support.

**Comment by marcphilipp** [comment]
Is that really so much different from `@ExtendWith(MyCustomCondition.class)`?

**Comment by sormuras** [comment]
Again, the USP of the current `@EnabledIf` and `@DisabledIf` programming model is that it uses a simple user-provided string, treats it as a script, and evaluates it with the _in-house_ JavaScript engine. Not a single external library is needed. Every extra work we require the user to perform must be compared to the work of creating a custom `ExecutionCondition` -- which is already not that much.

I see only three real options:
- Scrap the API for good: `@ExtendWith(MyCustomCondition.class)` is easy enough and offers "ide support" out of the box.
- Resort to `javac` as the _in-house_ tool evaluating the user-provided predicate.
- Bundle (shadow) a 3rd party script engine into `Jupiter`: tiny footprint, well-known syntax, ideally works via JSR-223

**Comment by marcphilipp** [comment]
The downside of a `Condition` or `Predicate` over `ExecutionCondition` is that it lacks the ability to return a reason.

**Comment by sormuras** [comment]
See PR #1599 which is now very small and concise. Only thing left open: remove default value `Nashorn` from the annotation declarations.

**Comment by sormuras** [comment]
The upside of the `java` as script engine approach:

```java
@Test
@EnabledIf(engine = "java", value = "return org.junit.jupiter.api.extension.ConditionEvaluationResult.enabled(\"Go!\");")
void javaWithCustomMessage() {
}
```

Still works.

**Comment by sormuras** [comment]
Accessing script bindings via attributes also works:

```java
@Test
@EnabledIf(engine = "java", value = "return \"\\\\o/\".equals(context.getAttribute(\"junitDisplayName\"));")
@DisplayName("\\o/")
void javaAccessingBindings() {
}
```
_Where art thou, Raw String Literals?_

**Comment by sormuras** [comment]
Just found this https://github.com/graalvm/graaljs/blob/master/docs/user/ScriptEngine.md and https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f ... and at first glance it seemed that OpenJDK 11 ships `graal.js` by default. But it doesn't. Does it?

**Comment by sbrannen** [comment]
> at first glance it seemed that OpenJDK 11 ships `graal.js` by default. But it doesn't. Does it?

It doesn't appear so, but the truth is in the [build](https://github.com/graalvm/graal-js-jdk11-maven-demo/blob/master/pom.xml).

**Comment by sormuras** [comment]
You linked "graal-js" -- we would that to be included into OpenJDK, though: https://github.com/openjdk/jdk/search?q=Graal&type=Commits

**Comment by sormuras** [comment]
Removed `@EnabledIf` and `@DisabledIf` via #1902 -- thus closing this issue.

**Comment by sormuras** [comment]
FYI: **Remove the Nashorn JavaScript Engine** via https://openjdk.java.net/jeps/372
