### ISSUE TITLE
@ParameterizedTest performance deteriorates with number of parameters

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1483]
## Overview

A user recently approached @sormuras with a `@ParameterizedTest` with 200 parameters that uses `@CsvFileSource` with 25,000 rows. Each invocation took about 700 ms. When using an `ArgumentsAggregator` each invocation took less than a millisecond.

While this scenario is certainly on the extreme end, I profiled it and found parameter annotation lookup to be the culprit: 99% of the time is spent in `Parameter.getDeclaredAnnotations()`. Since the annotations don't change between invocations, we only need to look them up once and pass the lookup result to each invocation context.

## Deliverables

- [ ] Cache annotation lookup for `@ParameterizedTest` parameters.

**Comment by sbrannen** [comment]
Good catch!
