### ISSUE TITLE
Package test from Android Studio runs all the tests in a project

### ISSUE THREAD

**Issue by mayowa-egbewunmi** [junit-team/junit5#1486]
## Overview

**Bug report.** When you run tests for android project package from Android Studio it will run all the tests in the project.

**Comment by marcphilipp** [comment]
While Android Studio passes a `PackageSelector` with the empty string as the `packageName` (which will cause all tests from all packages to be discovered), IntelliJ IDEA passes the package name correctly.

### Android Studio ()

<img width="505" alt="screen shot 2018-07-04 at 19 58 08" src="https://user-images.githubusercontent.com/214207/42290291-a2db473e-7fc4-11e8-8354-71fac3768046.png">

### IntelliJ IDEA ()

<img width="662" alt="screen shot 2018-07-04 at 19 59 08" src="https://user-images.githubusercontent.com/214207/42290309-c814569e-7fc4-11e8-9ec2-70122db1c797.png">

---

@mayowa-egbewunmi Could you please open an issue for Android Studio for this one?

@akozlova Do you have any idea why this happens?

**Comment by akozlova** [comment]
There are some customizations in AS. Moreover 3.1.2 is build over IJ 2017.3, so probably there was a bug in IJ as well (though I don't remember to see something similar). Sorry, but it's better to contact AS developers as I am not sure when they use which customization.

**Comment by mayowa-egbewunmi** [comment]
@marcphilipp thanks for the feedback, I will open a bug report with AS.
