### ISSUE TITLE
Memory issues with concurrent ParameterizedTest

### ISSUE THREAD

**Issue by jarnbjo** [junit-team/junit5#1491]
**Bug report**

I am trying to make use of the new concurrency features in 5.3.0-M1 to speed up some long running parameterized tests. With JUnit 5.2 or with 5.3.0-M1 using `SAME_THREAD` execution mode, everything works as expected. With 5.3.0-M1 and `CONCURRENT` execution mode, the test runs only for a short while, after which the VM starts getting very busy with garbage collection and the execution of the actual test code clogs up and comes almost to a complete halt.

Simplified code, with which the behavior can be reproduced:

```java
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@Execution(CONCURRENT)
public class OOMTest {

    @ParameterizedTest
    @MethodSource
    public void test(int a, int b, int c, int d) {

    }

    public Stream<? extends Arguments> test() {
        return IntStream.range(0, 1000).boxed()
                .flatMap(a -> IntStream.range(0, 1000).boxed()
                        .flatMap(b -> IntStream.range(0, 1000).boxed()
                                .flatMap(c -> IntStream.range(0, 1000).boxed()
                                        .map(d -> Arguments.of(a, b, c, d)))));
    }

}

```

In reality, we have a method source, which reads real production data from a database on an 'on demand' basis. The test arguments are not read from the DB until they are actually pulled from the stream. The simplified test code emulates this behavior by generating the Cartesian product of four sets of integers in the range [0, 999] to form the four test arguments.

When this test is run in concurrent execution mode, it seems as if the argument stream is very eagerly consumed, long before any test runner is free to actually execute the test code. With a 4GB default heap limit, the pasted test code slows down on my machine already after a few 10.000 test cases as it is filling up the available heap. A heap dump shows that about 1.500.000 instances of `org.junit.platform.launcher.TestIdentifier` and `org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor` have already been created. Each instance of `TestTemplateInvocationTestDescriptor` contains an invocation context with an `Object` array with arguments, which have already been pulled from the argument stream.

I haven't looked into the implementation, but it looks to me as if something is reading the arguments from the stream, creating some kind of executable test task and puts these tasks into an executor queue at a much higher rate than they can be consumed. Limiting the size of the queue will probably solve the problem.

**Comment by marcphilipp** [comment]
Thanks for reporting this issue! Your suspicion is indeed correct. Every invocation is wrapped and submitted to the `ForkJoinPool` which does not limit the queue size or block in any way. I‘ll take a closer look in the next few days.

**Comment by marcphilipp** [comment]
I pushed 4831d24 to master that solved the issue for me locally.

@jarnbjo Before closing this issue, could you please test with the latest 5.3.0-SNAPSHOT from [Sonatype's snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/) in your project?

**Comment by jarnbjo** [comment]
@marcphilipp I appreciate the very quick fix! I hope that I have time tomorrow to take a look at it, but then I'm away for two weeks and won't be able to verify the fix until I'm back.

**Comment by jarnbjo** [comment]
I have tried the snapshot version from the repository you linked to, your commit is included there, but it does not quite work as expected.

The memory issue is solved, but now, something seems to block the creation of new test cases, even if there are worker threads available to run the actual test. I have a configuration with 16 worker threads and when I start my real test case, I seem to observe the following behaviour:

1. A number of test cases, less than 16, usual values are in the range 6-10, are pulled from the argument source.
2. These test are started concurrently.
3. Something now waits until all running tests are finished.
4. Repeat from 1.

I have added some logging to the original test case to try to show the behaviour:

```
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@Execution(CONCURRENT)
public class OOMTest {

    private static final AtomicInteger activeThreadCount = new AtomicInteger();
    private static final Random random = new Random();

    @ParameterizedTest
    @MethodSource
    public void test(int a, int b, int c, int d) {
        System.out.println("> number of tests currently running: " + activeThreadCount.incrementAndGet());
        try {
            Thread.sleep(2000 + random.nextInt(2000));
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("< number of tests currently running: " + activeThreadCount.decrementAndGet());
    }

    public Stream<? extends Arguments> test() {
        return IntStream.range(0, 1000).boxed()
                .flatMap(a -> IntStream.range(0, 1000).boxed()
                        .flatMap(b -> IntStream.range(0, 1000).boxed()
                                .flatMap(c -> IntStream.range(0, 1000).boxed()
                                        .map(d -> {
                                            System.out.println("creating test for " + a + " " + b + " " + c + " " + d);
                                            return Arguments.of(a, b, c, d);
                                        }))));
    }

}

```

This test case has more or less the same runtime behaviour as our real test:

- Determining the test data in the argument source is relatively fast and cheap.
- The actual test case runs a random time between 2 and 4 seconds.

I have attached the log output from a run of this test case here:

[junit-concurrency.log](https://github.com/junit-team/junit5/files/2187820/junit-concurrency.log)

My initial observations were not quite correct, but at least at the start, you can see the following behaviour:

- Even with 16 threads configured, only 7 test cases are pulled from the argument source.
- These 7 tests are started, and the test runner now blocks, until all 7 test cases are finished.
- Not until now, further test cases are pulled from the argument source and started.
- The following runtime behaviour is a little bit chaotic, but as you can see from the log output, all 16 test runners are never used simultaneously. At most, 12 tests are running concurrently.

**Comment by marcphilipp** [comment]
Thanks for testing and providing an updated sample. I'll dig deeper in the next few days.

**Comment by marcphilipp** [comment]
I finally got around to looking into this issue again and increased the queue size limit in 95fbba8.

@jarnbjo Could you please give it another try?

**Comment by marcphilipp** [comment]
> Just a question out of curiosity: Currently, the implementation seems to use forEach on the argument source stream, create some kind of test context around it and from there, a ForkJoinTask which is submitted to a ForkJoinPool. Wouldn't it be much easier to use a ThreadPoolExecutor, which is fed by a work queue directly backed by the argument stream?

For this simple use case that would work. However, generally speaking, a `TestDescriptor` could spawn additional dynamic children which would have to be executed before finishing the enclosing test descriptor and so on.

> Sure, it seems to work much better now.

Thanks for verifying the fix!
