### ISSUE TITLE
Document the default value for --filter-classname (if any)

### ISSUE THREAD

**Issue by rherrmann** [junit-team/junit5#150]
I was playing around with JUnit 5 and in the absence of IDE support used the _Console Runner_ to execute tests.

While tryiing to find out why no tests were executed I thought it would be useful if the documentation of the [Console Runner options](https://junit-team.github.io/junit5/#console-runner) would state if there is a default value and what it is.

Though most people will probably assume `*Test` to be the default, an explicit hint would give confidence and possibly eliminate one try-and-error step.

**Comment by jlink** [comment]
The default is that all class names are accepted. Will document.

**Comment by jlink** [comment]
Documented in master.
