### ISSUE TITLE
Document how to use @RegisterExtension for static extensions from Kotlin

### ISSUE THREAD

**Issue by stefano-m** [junit-team/junit5#1500]
## Overview

- JUnit 5 version: **`5.2.0`**
- Kotlin version: **`1.2.30`**

Hello, I am trying to use the [Programmatic Extension Registration via Static Fields](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic-static-fields) to register an extension in tests written in the Kotlin programming language.  However, I cannot get the `beforeAll` method to be called.  Note that using the `@BeforeAll` annotation works fine.

Note that to have "static" methods in Kotlin, one must use the `@JvmStatic` annotation inside an `object`.

### Example 1: Working `@BeforeAll` annotation:

```kotlin
class TestBeforeAllAnnotation {
    companion object {

        var setMeBeforeAllTests :String? = null

        @JvmStatic
        @BeforeAll
        fun annotatedBeforeAll() {
            setMeBeforeAllTests = "before"
        }
    }

    @Test
    fun testAnnotatedBeforeAll() {
        assertEquals("before", setMeBeforeAllTests) // OK
    }
}
```

### Example 2: Non-working `BeforeAllCallback` extension registration

```kotlin
class BeforeAllCallBackExtension : BeforeAllCallback {

    val atConstructionTime = "done"

    var fromBeforAllCall: String? = null

    override fun beforeAll(context: ExtensionContext?) {
        println("BEFORE ALL CALLED")
        fromBeforAllCall = "before"
    }

}

class TestProgrammaticExtension {
    companion object {
        @JvmStatic
        @RegisterExtension
        val extension = BeforeAllCallBackExtension()
    }

    @Test
    fun filedAtConstructionTimeWorks() {
        assertEquals("done", extension.atConstructionTime) // OK
    }

    @Test
    fun fieldSetInCallBackFails() {
        assertEquals("before", extension.fromBeforAllCall) // FAILS
    }
}
```

**Comment by sbrannen** [comment]
Thanks for raising the issue.

We'll do our best to look into this in time for 5.3.

**Comment by marcphilipp** [comment]
Using `@JvmField` instead of `@JvmStatic` works, otherwise Kotlin generates a private field which we filter out.

@stefano-m Would you be interested in documenting this in the User Guide?

**Comment by marcphilipp** [comment]
I changed the issue title to improve documentation.

**Comment by stefano-m** [comment]
> Using @JvmField instead of @JvmStatic works, otherwise Kotlin generates a private field which we filter out.

Awesome! I'm going to try that out ASAP.

> Would you be interested in documenting this in the User Guide?

@marcphilipp I can surely do that, but I'd need a pointer or to to get started.

Thanks!

**Comment by marcphilipp** [comment]
> I can surely do that, but I'd need a pointer or two to get started.

Basically, I think we should add a short paragraph and a sample here:
https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic-static-fields

The source code for that lives in the documentation subproject:
https://github.com/junit-team/junit5/blob/master/documentation/src/docs/asciidoc/user-guide/extensions.adoc#static-fields

See https://github.com/junit-team/junit5/blob/aae5f5df3053dc45de1eb32fae864973dccc51d3/documentation/README.md for details.

@stefano-m Does that help?

**Comment by stefano-m** [comment]
Cool! I can give it a shot.

Hopefully I'll submit a PR in the next few days.

Thanks.

---
P.S.

FWIW I can confirm that using `@JvmField` fixes the issue (see below example).

```kotlin
class BeforeAllCallBackExtension : BeforeAllCallback {

    val atConstructionTime = "done"

    var fromBeforAllCall: String? = null

    override fun beforeAll(context: ExtensionContext?) {
        println("BEFORE ALL CALLED")
        fromBeforAllCall = "before"
    }

}

class TestProgrammaticExtension {
    companion object {
        @JvmField
        @RegisterExtension
        val extension = BeforeAllCallBackExtension()
    }

    @Test
    fun filedAtConstructionTimeWorks() {
        assertEquals("done", extension.atConstructionTime) // OK
    }

    @Test
    fun fieldSetInCallBackFails() {
        assertEquals("before", extension.fromBeforAllCall) // OK
    }
}
```

**Comment by stefano-m** [comment]
Hi, the issue went off my radar due to other commitments, but hopefully I'll have some free time to do it in the next couple of days.

**Comment by sbrannen** [comment]
@stefano-m, thanks for getting back to us.

If you can tackle this soon, we might be able to squeeze it into 5.3. Otherwise, it'll go into 5.4.

**Comment by sbrannen** [comment]
Re-added the `up-for-grabs` label, since we like to be able to refer to such community contributions after they have been resolved. 😉

**Comment by sbrannen** [comment]
For example...

https://github.com/junit-team/junit5/issues?q=label%3Aup-for-grabs+is%3Aclosed

**Comment by Sam-Kruglov** [comment]
Hi, just tried using

**Comment by sbrannen** [comment]
> Not reproducible in Java. This JUnitJupiterSoftAssertions instance only remains alive in Kotlin

Hi @Sam-Kruglov,

This issue is closed.

Would you mind opening a new issue and including a more inclusive example -- for example, including whether or not you are using `@TestInstance(PER_CLASS)` lifecycle semantics for your Kotlin-based tests?

**Comment by sbrannen** [comment]
@Sam-Kruglov, I just opened the following issue against AssertJ.

https://github.com/joel-costigliola/assertj-core/issues/1418

Please follow that issue instead of creating a new issue against JUnit.

Thanks

**Comment by Sam-Kruglov** [comment]
> @Sam-Kruglov, I just opened the following issue against AssertJ.
> 
> [joel-costigliola/assertj-core#1418](https://github.com/joel-costigliola/assertj-core/issues/1418)
> 
> Please follow that issue instead of creating a new issue against JUnit.
> 
> Thanks

Hey, I started opening it here and found that it actually reproduces in Java and is directly connected with `@Nested` behavior. see the issue here https://github.com/junit-team/junit5/issues/1756
