### ISSUE TITLE
Feature: Introduce Steps

### ISSUE THREAD

**Issue by RomanIovlev** [junit-team/junit5#1503]
Add Steps support for JUnit Jupiter.

The idea is to allow the user to mark some methods with a `@Step` annotation and have the ability to do something with these _steps_ -- for example, logging, monitoring, timing, etc.

In addition it will be good to have access on JUnit asserts in same extension.

So for test

```java
Calculator calc = new Calculator();

@Test
public void simpleTest() {
  int multiplication = calc.multiply(3,5);
  assertEquals(multiplication, 15);
  int sum = calc.sum(2,8);
  assertEquals(sum, 10);
  int division = calc.divide(12,3);
  assertEquals(division, 4);
}
```

I can see log:

```
TEST: simpleTest() 
Step: multiply(3, 5)
AssertEquals: 15
Step: sum(2, 8)
AssertEquals: 10
Step: divide(12, 3)
AssertEquals: 4
Method [simpleTest] took 11 ms.
```

See project example on [GitHub](https://github.com/RomanIovlev/simple-junit-test)

Suggested code marked as // ADD

**Comment by sbrannen** [comment]
The proposal is not feasible from the perspective of a framework like JUnit Jupiter.

1. JUnit annotations are "test" annotations and should never be present in "application" code.
2. JUnit does not inspect or manipulate byte code, which would be required to analyze what "steps" were being executed.
3. Assertions are `static` utility methods that do not track state or interact with the JUnit Jupiter extension model.

In light of the above, I am closing this issue as "declined".

**Comment by sbrannen** [comment]
For what it's worth, if you are interested in the general notion of "steps", you may be interested in participating in the discussion of "scenario tests" (#48).

**Comment by sbrannen** [comment]
Using something like AspectJ is beyond the scope of the JUnit framework.

Generally speaking we have a "zero external dependencies" rule with very few exceptions.

**Comment by sbrannen** [comment]
>  P.S. Thanks I will participate Steps discussion

You're welcome!

And thanks for raising all of the issues today: it shows you're interested in the framework! 😉
