### ISSUE TITLE
Suggestion: Move @ DisplayName in @ Test

### ISSUE THREAD

**Issue by RomanIovlev** [junit-team/junit5#1504]
so I can write
@ Test("Awesome tests")
instead of 
@ Test
@ DisplayName("Awesome tests")

**Comment by sbrannen** [comment]
Custom display name support is not limited to conventional `@Test` methods. Test classes, parameterized tests, repeated tests, dynamic test factory methods, etc. can all have custom display names.

Thus, it would not make sense to make the proposed change.

In addition, the team is not in favor of adding any attributes at all to the `@Test` annotation.

I am therefore closing this issue as "declined".

**Comment by sbrannen** [comment]
`@DisplayName` will be used for the container. The `name` attribute of `@ParameterizedTest` is used for invocations of the parameterized test underneath that container.

**Comment by sbrannen** [comment]
related to #1440
