### ISSUE TITLE
Suggestion: rename 'name' variable to 'value' in ParametrizedTest

### ISSUE THREAD

**Issue by RomanIovlev** [junit-team/junit5#1505]
So you can write
@ ParametrizedTest("Calculate {0} ")
instead of 
@ ParametrizedTest(name = "Calculate {0} ")

**Comment by sbrannen** [comment]
Thanks for the suggestion.

We naturally considered that option when the annotation was created but decided against.

Since changing it now would be a breaking change, I am closing this issue as "won't fix".
