### ISSUE TITLE
DiscoverySelector implementations are missing custom equals() and hashCode()

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1510]
## Overview

Due to an oversight of the team, implementations of `DiscoverySelector` do not currently have custom implementations of `equals()` and `hashCode()`. This is in contrast to implementations of `TestSource`, `TestDescriptor`, etc.

## Deliverables

- [ ] Implement `equals()` and `hashCode()` in all `DiscoverySelector` implementations.

**Comment by clevertension** [comment]
@sbrannen are you working on this issue?

**Comment by sbrannen** [comment]
@clevertension, I am not actively working on this very second, but I plan to address this in the coming days.

However, if you think you can put together a PR within the next day or two, feel free to do so. Just make sure you add a comment here stating that you are actively working on it. Otherwise, I'll do it.

Please keep in mind that we will not accept a PR without complete test coverage for newly introduced `equals()` and `hashCode()` implementations. See `org.junit.platform.engine.support.descriptor.AbstractTestSourceTests.assertEqualsAndHashCode(T, T, T)` for inspiration.

Regards,

Sam

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
FYI: this issue has been resolved in `master`.
