### ISSUE TITLE
Parallel execution and @TestInstance(PER_CLASS) result in concurrency issues for instance fields mutated in test and lifecycle methods

### ISSUE THREAD

**Issue by dlanaghen** [junit-team/junit5#1511]
`@TestInstance` annotation seems to cause threading problems with tests in Spring Boot.

```xml
<junit5.jupiter.version>5.3.0-M1</junit5.jupiter.version>
<junit5.platform.version>1.2.0</junit5.platform.version>
```

I was able to replicate this problem by creating a small Spring Boot application using the Spring Initializer (https://start.spring.io/).

The application:

```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}
```

A dummy class for testing:

```java
package com.example.demo;

public class Klass {
    public Klass(String field) {
        this.field = field;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }

    String field;
}
```

My test class:

```java
package com.example.demo;

import org.junit.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.context.junit4.SpringRunner;

// @TestInstance(TestInstance.Lifecycle.PER_CLASS) // Needed for BeforeAll annotation but causes threading issues. 
@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = {DemoApplication.class})
public class DemoApplicationTests {

	@Test
	public void contextLoads() {
	}

	Klass klass = null;

	@BeforeEach
	public void beforeEach() {
		klass = new Klass(Thread.currentThread().getName());
	}

	@RepeatedTest(8)
	public void parallel() {
		klass.setField("Modified: " + klass.getField());
	}

	@AfterEach
	public void afterEach() {
		System.out.println(String.format("%s - %s", Thread.currentThread().getName(), klass.field ));
	}
}
```

Output when not using `@TestInstance`:

```
ForkJoinPool-1-worker-3 - Modified: ForkJoinPool-1-worker-3
ForkJoinPool-1-worker-0 - Modified: ForkJoinPool-1-worker-0
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-2
ForkJoinPool-1-worker-3 - Modified: ForkJoinPool-1-worker-3
ForkJoinPool-1-worker-4 - Modified: ForkJoinPool-1-worker-4
ForkJoinPool-1-worker-4 - Modified: ForkJoinPool-1-worker-4
ForkJoinPool-1-worker-6 - Modified: ForkJoinPool-1-worker-6
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-2
```

Output when using `@TestInstance`:

```
ForkJoinPool-1-worker-0 - Modified: ForkJoinPool-1-worker-4 <<< oops
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-4 <<<
ForkJoinPool-1-worker-3 - Modified: ForkJoinPool-1-worker-3
ForkJoinPool-1-worker-0 - Modified: ForkJoinPool-1-worker-0
ForkJoinPool-1-worker-4 - Modified: ForkJoinPool-1-worker-0 <<<
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-2
ForkJoinPool-1-worker-3 - Modified: ForkJoinPool-1-worker-3
```

**Comment by sbrannen** [comment]
Thanks for raising the issue.

We'll look into it.

**Comment by marcphilipp** [comment]
This behavior does not surprise me: You're using the same instance of `DemoApplicationTests` and call `beforeEach()`, `parallel()`, and `afterEach()` from different threads. When one of the threads prints in `afterEach()`, another thread is very likely to have already called `beforeEach()` or `parallel()` which modifies the test instance.

Since issues like this one are inevitable when using `@TestInstance(PER_CLASS)`, I think we should change the default execution mode to `SAME_THREAD` in this case.

@junit-team/junit-lambda Thoughts?

**Comment by marcphilipp** [comment]
@dlanaghen `@TestInstance(PER_CLASS)` is not "Needed for BeforeAll", only if you want your `@BeforeAll` methods to be not `static`.

**Comment by dlanaghen** [comment]
I realize that, but I had put that notation in a base test class because some of my other classes might need that and I saw no reason not to just include it in my base class.  
This is not going to be problem currently for us, but I thought I would report my finding.
- Dave 

    On Saturday, July 28, 2018, 7:57:55 AM MDT, Marc Philipp <notifications@github.com> wrote:  
 
 
@dlanaghen @TestInstance(PER_CLASS) is not "Needed for BeforeAll", only if you want your @BeforeAll methods to be not static.

**Comment by sbrannen** [comment]
This is actually not related to Spring Boot.

I have therefore renamed this issue accordingly.

**Comment by sbrannen** [comment]
The following simplified example demonstrates the same behavior without Spring Boot in the picture.

```java
@TestInstance(PER_CLASS)
class DemoApplicationTests {

	Klass klass;

	@BeforeEach
	void beforeEach() {
		klass = new Klass(Thread.currentThread().getName());
	}

	@RepeatedTest(8)
	void parallel() {
		klass.setField("Modified: " + klass.getField());
	}

	@AfterEach
	void afterEach() {
		System.out.println(String.format("%s - %s", Thread.currentThread().getName(), klass.getField()));
	}

}
```

**Comment by sbrannen** [comment]
Without a change in JUnit itself, you have two options for avoiding the undesired behavior.

### Disable Parallel Execution

```java
@TestInstance(PER_CLASS)
@Execution(SAME_THREAD)
class DemoApplicationTests {

	Klass klass;

	@BeforeEach
	void beforeEach() {
		klass = new Klass(Thread.currentThread().getName());
	}

	@RepeatedTest(8)
	void parallel() {
		klass.setField("Modified: " + klass.getField());
	}

	@AfterEach
	void afterEach() {
		System.out.println(String.format("%s - %s", Thread.currentThread().getName(), klass.getField()));
	}

}
```

### Store test instance state in a `ThreadLocal`

```java
@TestInstance(PER_CLASS)
class DemoApplicationTests {

	ThreadLocal<Klass> klass = new ThreadLocal<>();

	@BeforeEach
	void beforeEach() {
		klass.set(new Klass(Thread.currentThread().getName()));
	}

	@RepeatedTest(8)
	void parallel() {
		Klass klass2 = klass.get();
		klass2.setField("Modified: " + klass2.getField());
	}

	@AfterEach
	void afterEach() {
		System.out.println(String.format("%s - %s", Thread.currentThread().getName(), klass.get().getField()));
	}

}
```

The first option completely disables parallel execution, thereby avoiding the undesired behavior completely but obviously executing each test sequentially.

```
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1 - Modified: ForkJoinPool-1-worker-1
```

The second option allows the tests to continue to execute in parallel but introduces more work for the author of the test.

```
ForkJoinPool-1-worker-3 - Modified: ForkJoinPool-1-worker-3
ForkJoinPool-1-worker-4 - Modified: ForkJoinPool-1-worker-4
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-2
ForkJoinPool-1-worker-4 - Modified: ForkJoinPool-1-worker-4
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-2
ForkJoinPool-1-worker-3 - Modified: ForkJoinPool-1-worker-3
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-2
ForkJoinPool-1-worker-2 - Modified: ForkJoinPool-1-worker-2
```

**Comment by sbrannen** [comment]
> Since issues like this one are inevitable when using `@TestInstance(PER_CLASS)`, I think we should change the default execution mode to `SAME_THREAD` in this case.
> 
> @junit-team/junit-lambda Thoughts?

Yes, I'm _thinking_. 😉 

And I'm leaning toward saying "yes".

The use of a `ThreadLocal` as I demonstrated above certainly works, but I imagine that most developers would either not want to hassle with a `TheadLocal` or might not even know what a `ThreadLocal` is.

So, switching the default parallel execution mode for `@TestInstance(PER_CLASS)` to `SAME_THREAD` would follow the "principle of least surprise" in most cases, and developers who truly want multi-threading for `@TestInstance(PER_CLASS)` could still opt in for per test class hierarchy. We'd just need to make sure the different defaults are well documented.

**Comment by dlanaghen** [comment]
Thanks for the reply Sam.  This is not a show stopper for us and since our application is a Spring application, most of the BeforeAll kinds of things are already out there for us.
BTW, I did experiment with a ThreadLocal in my application last week and it actually did not work for me.  I still had similar behavior.  I have not tried it in the stripped down test I included with the report.
- Dave 

    On Saturday, July 28, 2018, 9:30:46 AM MDT, Sam Brannen <notifications@github.com> wrote:  
 
 

Since issues like this one are inevitable when using @TestInstance(PER_CLASS), I think we should change the default execution mode to SAME_THREAD in this case.

@junit-team/junit-lambda Thoughts?


Yes, I'm thinking. 😉
 
And I'm leaning toward saying "yes".

The use of a ThreadLocal as I demonstrated above certainly works, but I imagine that most developers would either not want to hassle with a TheadLocal or might not even know what a ThreadLocal is.

So, switching the default parallel execution mode for @TestInstance(PER_CLASS) to SAME_THREAD would follow the "principle of least surprise" in most cases, and developers who truly want multi-threading for @TestInstance(PER_CLASS) could still opt in for per test class hierarchy. We'd just need to make sure the different defaults are well documented.

**Comment by marcphilipp** [comment]
@dlanaghen Would you agree that changing the default execution mode to `SAME_THREAD` for test classes that use `@TestInstance(PER_CLASS)` is a sensible thing to do?

**Comment by dlanaghen** [comment]
I would agree that the default should probably be SAME_THREAD.  
Running things in parallel though, is extremely useful and most will want to run their tests that way.  The JUnit5 documentation is pretty good, so I assume that these kinds of issues and potential work arounds could be included.
BTW, like I said, I experimented with ThreadLocal expecting it to solve my problem in my real test application, and I swear I still saw funny behavior.  I thought that somehow Spring might be the underlying complicating factor.   If I get time next week, I may go back one more time and see if I was just confused.
Thanks for you work!
- Dave 

    On Saturday, July 28, 2018, 1:04:33 PM MDT, Marc Philipp <notifications@github.com> wrote:  
 
 
@dlanaghen Would you agree that changing the default execution mode to SAME_THREAD for test classes that use @TestInstance(PER_CLASS) is a sensible thing to do?

**Comment by marcphilipp** [comment]
If we decide to go that route, I think we should default to `ExecutionMode.SAME_THREAD` for nested classes that don't use `Lifecycle.PER_METHOD` if one of their enclosing classes uses `Lifecycle.PER_CLASS`, too.

```java
@TestInstance(PER_CLASS) // => ExecutionMode.SAME_THREAD
class Outer {
    @Nested
    // Lifecycle.PER_METHOD
    // => ExecutionMode.SAME_THREAD ?
    class Inner {
        // ...
    }
}
```

**Comment by sbrannen** [comment]
> Running things in parallel though, is extremely useful and most will want to run their tests that way. 

I'm actually not 100% convinced of that.

I know a lot of people like to run their tests in parallel, but not everybody. Lots of use cases don't actually work with parallel execution (e.g., transactions committing to a shared database), and some use cases simply don't need it (e.g., fast _unit_ tests).

I'm actually wondering if we shouldn't make parallel execution an opt-in feature on a per-class level without the need for _Configuration Parameters_ (but maintaining the existing _global_ opt in via Configuration Parameters).

@marcphilipp, what do you think about that?

**Comment by sbrannen** [comment]
> BTW, like I said, I experimented with ThreadLocal expecting it to solve my problem in my real test application, and I swear I still saw funny behavior.  I thought that somehow Spring might be the underlying complicating factor.   If I get time next week, I may go back one more time and see if I was just confused.

Sure. If you find something, please do report back!

**Comment by sbrannen** [comment]
> If we decide to go that route, I think we should default to `ExecutionMode.SAME_THREAD` for nested classes that don't use `Lifecycle.PER_METHOD` if one of their enclosing classes uses `Lifecycle.PER_CLASS`, too.

Mmmmm.... interesting. I suppose that would make sense as well.

**Comment by dlanaghen** [comment]
Sam, I think you are right that many won't need parallel execution.  But I believe that if what people are doing is truly 'unit' testing, especially with mocking, parallel should always work.  
In our case, we are actually doing functional/integration testing which is where things like shared resources come into play and parallel execution requires much more thought and caution.  But in our case, performance is critical.  Our tests are slow.  There are lots of REST calls and lots of time is spent waiting.  I am seeing great improvement in performance with parallel execution.
I like the idea of the base opt-in configuration which sets the default configuration which should probably default to single treaded and then provide the ability to override that configuration with a per class annotation.  As I recall, that is what I saw in an earlier version.
And it makes sense to me that if someone has things set to run parallel but sets PER_CLASS in a test, that tests are forced to run in the same thread.  Good documentation here would be required because behavior would not match what was expected, but at least the tests would run as expected.
- Dave 

    On Sunday, July 29, 2018, 7:00:44 AM MDT, Sam Brannen <notifications@github.com> wrote:  
 
 

If we decide to go that route, I think we should default to ExecutionMode.SAME_THREAD for nested classes that don't use Lifecycle.PER_METHOD if one of their enclosing classes uses Lifecycle.PER_CLASS, too.


Mmmmm.... interesting. I suppose that would make sense as well.

**Comment by sbrannen** [comment]
> I think the use case we're talking about is gradually enabling parallelism for an existing codebase on a test class by test class basis, right?

Yep.

**Comment by sbrannen** [comment]
> A possible alternative to make that possible would be to introduce another new configuration parameter to configure the default execution mode (similar to what we have for the test instance lifecycle). 

I was indeed thinking about something like we have in place for the test instance lifecycle mode.

> This way you could enable parallel execution but set the default to `SAME_THREAD`. Then you could add `@Execution(CONCURRENT)` selectively to those test classes where it works.

I think that's a good trade-off and improvement over the status quo.

**Comment by sbrannen** [comment]
> One downside of this approach is that enabling parallelism in general (but not using by default) would impose a significant overhead because we spin up a `ForkJoinPool` with a number of threads, check for locks etc. That's why we currently have `SameThreadHierarchicalTestExecutorService` and `ForkJoinPoolHierarchicalTestExecutorService`. Thus, I think we need some kind of global activation.

Hmmm... I'm obviously not as familiar with the new "parallel execution" code as you are.

I was actually hoping it would be possible for the `JupiterTestEngine` to select the execution style (i.e., `SameThreadHierarchicalTestExecutorService` vs. `ForkJoinPoolHierarchicalTestExecutorService`) _dynamically_ based on annotations and/or configuration parameters, analogous to how it currently dynamically decides whether it should cache test instances.

Would that be an option?

**Comment by marcphilipp** [comment]
_in progress_

**Comment by hashhar** [comment]
@marcphilipp Sorry to bump such an old issue but after this change how can I configure my tests such that I don't need to add `@Execution` annotations to ALL test classes if none of my tests are thread-unsafe and I've set `PER_CLASS` as the global default (because all my test classes are safe because the objects on the test class instance are "immutable")?

One option is to remove `PER_CLASS` and use `@BeforeAll` to instantiate the "costly" objects on the class once per test class? Would this even work?

Are there other options?

**Comment by marcphilipp** [comment]
As long as the costly objects are thread-safe that should work.
