### ISSUE TITLE
Use `@BeforeEach` method return value as an implicit `ParameterResolver`

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#1513]
**Feature request.**

Been reading https://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection and thinking I often write things like:

```java
    private Project project;

    @BeforeEach
    void setup() throws Exception {
        project = ProjectBuilder.builder().build();
        Git git = new InitCommand().setDirectory( project.getProjectDir() ).call();
        RevCommit one = git.commit().setMessage( "one" ).setAllowEmpty( true ).call();
    }


    @ParameterizedTest
    @ArgumentsSource( PluginProvider.class )
    void codeQuality( Collection<Class<Plugin<Project>>> pluginClass ) {
        pluginClass.forEach( project.getPluginManager()::apply );
``` 

where I create a new instance of something simply to ensure the state is known prior to running the test, however it would be nice to be able to achieve this same thing by writing:

```java
    @BeforeEach
    Project setup() throws Exception {
        Project project = ProjectBuilder.builder().build();
        Git git = new InitCommand().setDirectory( project.getProjectDir() ).call();
        RevCommit one = git.commit().setMessage( "one" ).setAllowEmpty( true ).call();
        return project;
    }


    @ParameterizedTest
    @ArgumentsSource( PluginProvider.class )
    void codeQuality( Project project, Collection<Class<Plugin<Project>>> pluginClass ) {
        pluginClass.forEach( project.getPluginManager()::apply );

```

this seems more functional and certainly requires less state mutation. I know I could write a `ParameterResolver`, but it honestly doesn't seem as natural.

## Related Issues

- #1657

**Comment by sbrannen** [comment]
As a general rule, we do not allow lifecycle callback methods to have a return value, and to be honest, I don't foresee us diverging from that rule.

In any case, if you want to have a _simple_ way to create an object that will later be injected into test methods _by type_, you can do something like the following

```java
public abstract class TypeBasedParameterResolver implements ParameterResolver {

	private final Class<?> type;

	public TypeBasedParameterResolver(Class<?> type) {
		this.type = type;
	}

	@Override
	public final boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
		return parameterContext.getParameter().getType().equals(this.type);
	}
}
```

```java
class ParameterResolverTests {

	@RegisterExtension
	ParameterResolver parameterResolver = new TypeBasedParameterResolver(CustomType.class) {
		@Override
		public CustomType resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
			return new CustomType();
		}
	};

	@Test
	void parameterInjectionByType(CustomType customType) {
		assertNotNull(customType);
	}

}
```

What do you think about that?

**Comment by xenoterracide** [comment]
I think that's comparatively complicated, and verbose, compared to what I propose. similar things that you might have to do in other frameworks that support injection, like CDI or Spring (though they often have similar things under the hood). Usually those same frameworks allow you to register a "bean" with a lifecycle, hence why I suggested `@BeforeEach` though you could use a different annotation if that was going to overload `@BeforeEach` too much. Just thinking that you want an easy way to say recreate for every test, vs create once for all tests  in class.

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 RC1, though primarily for the sake of _team discussion_ in the near future.

**Comment by marcphilipp** [comment]
*Team decision:* While it's an interesting idea, it would result in added complexity and is beyond the scope of JUnit Jupiter. All of the building blocks are in place so this feature could easily be implemented as an extension should you so desire.
