### ISSUE TITLE
Clarify how TestReporter's keys and values are to be used

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#1515]
About `TestReporter`, the documentation says:

> In JUnit Jupiter you should use `TestReporter` where you used to print information to `stdout` or `stderr` in JUnit 4.

This does not clarify the intend behind key value pairs, though, and since leaving them empty is an error, it would help to explain how to use them. Otherwise users might be under the impression that the reporter is only useful to output test data (like in `reportSeveralValues` in [the user guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection)), but not status messages.

Or maybe add an overload that accepts a single string as a message.

**Comment by marcphilipp** [comment]
I think key-value pairs should be fine for now.

@nicolaiparlog Do you have time to improve the documentation and send a PR?

**Comment by nicolaiparlog** [comment]
I have the time, but not the answer, meaning I don't really know either what you guys had in mind regarding simple status messages. My intuition was to use an empty key and the message as value, but since that doesn't work, I don't really know what to do. :)

**Comment by marcphilipp** [comment]
Well, as you empirically discovered, one has to supply both key and value. 😉

Could you please provide an example for the use case? I think that might help in talking about it.

**Comment by nicolaiparlog** [comment]
I will - the next time I want to use the reporter. ;)

**Comment by nicolaiparlog** [comment]
Found one. As a demo for the extension model, I wrote [a benchmark extension](https://github.com/CodeFX-org/demo-junit-5/blob/master/src/main/java/org/codefx/demo/junit5/BenchmarkExtension.java) and it publishes entries like this:

```
String message = /*...*/;
context.publishReportEntry("Benchmark", message);
```

Result in IntelliJ:

> timestamp = 2018-08-04T09:41:46.305890, Benchmark = Test 'benchmarked()' took 100 ms.

"Benchmark" is a lousy key, but what else could I use? I only really care about the message.

**Comment by sormuras** [comment]
What about adding the following convenience method to `ExtensionContext`?

```java
	default void publishReportMessage(String message) {
		this.publishReportEntry("message", message);
	}
```

It'd yield:

`timestamp = 2018-08-04T09:41:46.305890, message = Test 'benchmarked()' took 100 ms.`

**Comment by sbrannen** [comment]
I think the default `message` key is a good idea.

**Comment by nicolaiparlog** [comment]
Great, I'll create a PR later this weekend. :smiley:

**Comment by sbrannen** [comment]
Whoa, horsey.... _Immer langsam mit den jungen Pferden_. 😋 

(That's German for "Hold your horses")

**Comment by sbrannen** [comment]
j/k... go ahead with the PR. The testing and documentation will take you 20 times longer than implementing (copying-n-pasting) the method. 😇

**Comment by nicolaiparlog** [comment]
Wow, 20x? It I spent about an hour to prepare the console launcher test input files. That's a quagmire! Otherwise, I think I'm done with one little question - see #1523.

**Comment by sormuras** [comment]
> That's a quagmire! 

Back fire of the generated/dynamic test feature. :P

**Comment by sbrannen** [comment]
> Wow, 20x?

Did I say 20x? I meant "at least 2000x". 😝

**Comment by sbrannen** [comment]
Revised in 1cbda447f499cff7e457790ec67f34c7d5198b8f
