### ISSUE TITLE
Identify expected value in parameterized test arguments

### ISSUE THREAD

**Issue by nipafx** [junit-team/junit5#1517]
## Overview

Add `expected` attribute to `@ParameterizedTest` and if present change default output to `[{index}] {input} ~> {expected}` (or similar).

## Status Quo

When writing parameterized tests it is common to pass in input data together with the expected output, e.g.:

```java
@ParameterizedTest
@CsvSource({ "I, 1", "II, 2", "V, 5" })
void testWithDisplayName(String roman, int arabic) { /*...*/ }
```

```
# display names
[1] I,1
[2] II, 2
[3] V, 5
```

This is nice, but can be improved by pointing out what is input and what is expected:

``` java
@DisplayName("Roman numeral")
@ParameterizedTest(name = "\"{0}\" should be {1}")
```

```
# display names
"I" should be 1
"II" should be 2
"V" should be 5
```

But... [can't somebody else do that](https://www.youtube.com/watch?v=YihiSqO4jnA&t=25s)?

## Proposal

Add an attribute `expected` to `@ParameterizedTest` that names the parameter holding the test's expected result:

```java
@ParameterizedTest(expected = "arabic")
@CsvSource({ "I, 1", "II, 2", "V, 5" })
void testWithDisplayName(String roman, int arabic) { /*...*/ }
```

If `expected` is present, Jupiter makes the new placeholders `{input}` and `{expected}` (a partition of `{arguments}`) available for naming tests and switches the default from name from `[{index}] {arguments}` to `[{index}] {input} ~> {expected}`. (All names and formats are up for bike-sheds!)

## Related Issues

- #1309

**Comment by marcphilipp** [comment]
For this to work, test classes would have to be compiled with `-parameters`, right?

**Comment by sbrannen** [comment]
Yes, that's correct, Marc.

Otherwise that `arabic` parameter would be known as `arg1`. 😉

**Comment by sbrannen** [comment]
Related to #1309.
