### ISSUE TITLE
[bug] Spek tests not executed with junit-jupiter-engine:5.3.0-M1

### ISSUE THREAD

**Issue by stefan-hornea** [junit-team/junit5#1518]
## Overview
Trying to create Kotlin project with maven build.
The Spek tests are not executed with jupiter 5.3.0-M1, although they are executed correctly with jupiter 5.2.0.
I have attached complete Maven + Kotlin project 
[test_prj.zip](https://github.com/junit-team/junit5/files/2249959/test_prj.zip)

to reproduce the behavior.
To switch between jupiter versions please change the  Maven _jupiter.version_ property, in the attached _pom.xml_

#### Junit artefacts versions (can be seen also in the attached pom.xml):
- junit-jupiter-api: 5.3.0-M1
- junit-jupiter-engine: 5.3.0-M1

#### Java version:
 _java version "1.8.0_151"
 Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
 Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)_

#### Maven version:
_Apache Maven 3.3.9_

#### Expected behavior (works with jupiter 5.2.0): 4 unit tests are executed, 2 of them fail
 - Maven surefire report:
   _Tests run: 4, Failures: 2, Errors: 0, Skipped: 0_
#### Current behavior (with jupiter 5.3.0-M1): no unit tests are executed, alghough the _*Spec_ file to be executed is detected.
- Maven surefire report (incorrect):
_Tests run: 0, Failures: 0, Errors: 0, Skipped:_

**Comment by marcphilipp** [comment]
@stefan-hornea Thanks for reporting!

Spek seems to completely ignore the passed `DynamicTestExecutor` [1] and instead add the test descriptor and call the execution listener directly [2] which is not how `HierarchicalTestEngine` is supposed to be used. 🤔 

[1] https://github.com/spekframework/spek/blob/v1.1.5/spek-junit-platform-engine/src/main/kotlin/org/jetbrains/spek/engine/Scope.kt#L44-L53

[2] https://github.com/spekframework/spek/blob/v1.1.5/spek-junit-platform-engine/src/main/kotlin/org/jetbrains/spek/engine/SpekTestEngine.kt#L214-L215

**Comment by marcphilipp** [comment]
Fixed by https://github.com/spekframework/spek/pull/463.

**Comment by raniejade** [comment]
FYI, Spek `1.2.1` is out with the fix to this issue.

**Comment by marcphilipp** [comment]
Thanks, @raniejade!

I updated our sample project in https://github.com/junit-team/junit5-samples/commit/ae96ee5d9a0625e3a95bf51c554f4977c280fa94.
