### ISSUE TITLE
add support for parameterized tests in JUnit XML reports

### ISSUE THREAD

**Issue by bitcoder** [junit-team/junit5#1519]
## Overview

 **Feature request.** 
We're a Test Management vendor for Jira and our addon (Xray) (https://marketplace.atlassian.com/apps/1211769/xray-test-management-for-jira?hosting=server&tab=overview) provides already handling of JUnit XML reports. However, our users have the need of have visibility of the results from parameterized tests so they can properly analyze them.
The problem that we're facing with JUnit is that the current XML report does not provide visibility of this, so our users cannot take advantage of this information in our reports because we simply are unable to process them.
With TestNG this works fine though, so some users are using it instead. Of course we want to promote also JUnit and I think if we were able to get a way of at least deal with parameterized tests in some way 
Some preliminary investigation with JUnit4 allowed us to see that different runners are able to overcome this, although in slight different ways.

It seems that the output generated with JUnit4 generates a "standard" JUnit xml where the "name" attribute contains the parameters as seen below (using two different runners).

```xml
  <testcase name="testCompute[0: fib(0)=0]" classname="com.xpand.java.Fibonacci3Test" time="0.002"/>
 <testcase name="personIsAdultInline(17, false) [0]" classname="com.xpand.java.PersonTest" time="0.042"/>
```

 The first example was generated with the "Parameterized" class runner,

```java
package com.xpand.java;

import static org.junit.Assert.assertEquals;

import java.util.Arrays;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class Fibonacci3Test {

    @Parameters(name = "{index}: fib({0})={1}")
    public static Iterable<Object[]> data() {
        return Arrays.asList(new Object[][] { 
                 { 0, 0 }, { 1, 1 }, { 2, 1 }, { 3, 2 }, { 4, 3 }, { 5, 5 }, { 6, 8 }
           });
    }

    private int input;
    private int expected;

    public Fibonacci3Test(int input, int expected) {
        this.input = input;
        this.expected = expected;
    }

    @Test
    public void testCompute() {
        assertEquals(expected, Fibonacci.compute(input));
    }
}
```

```xml
  <testcase name="testCompute[0: fib(0)=0]" classname="com.xpand.java.Fibonacci3Test" time="0.002"/>
  <testcase name="testCompute[1: fib(1)=1]" classname="com.xpand.java.Fibonacci3Test" time="0"/>
  <testcase name="testCompute[2: fib(2)=1]" classname="com.xpand.java.Fibonacci3Test" time="0"/>
  <testcase name="testCompute[3: fib(3)=2]" classname="com.xpand.java.Fibonacci3Test" time="0"/>
  <testcase name="testCompute[4: fib(4)=3]" classname="com.xpand.java.Fibonacci3Test" time="0"/>
  <testcase name="testCompute[5: fib(5)=5]" classname="com.xpand.java.Fibonacci3Test" time="0"/>
  <testcase name="testCompute[6: fib(6)=8]" classname="com.xpand.java.Fibonacci3Test" time="0"/>
```
The second example code,  using JUnitParamsRunner class,  is:

```java
package com.xpand.java;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;
import org.junit.runner.RunWith;

import junitparams.JUnitParamsRunner;
import junitparams.Parameters;


@RunWith(JUnitParamsRunner.class)
public class PersonTest {

	@Test
	@Parameters({ 
	        "17, false", 
	        "22, true" })
	public void personIsAdultInline(int age, boolean valid) throws Exception {
	    assertThat((new Person(age)).isAdult()).isEqualTo(valid);
	}
	
	@Test
	@Parameters(method = "adultValues")
	public void personIsAdultMethod(int age, boolean valid) throws Exception {
	    //assertEquals(valid, new Person(age).isAdult());
	    assertThat(new Person(age).isAdult()).isEqualTo(valid);
	}

	private Object[] adultValues() {
	    return new Object[]{
	                 new Object[]{13, false},
	                 new Object[]{17, false},
	                 new Object[]{18, true},
	                 new Object[]{22, true}
	            };
	}
}
```

```xml
  <testcase name="personIsAdultInline(17, false) [0]" classname="com.xpand.java.PersonTest" time="0.042"/>
  <testcase name="personIsAdultInline(22, true) [1]" classname="com.xpand.java.PersonTest" time="0"/>
```
Thanks for your help.

It would be great to uniformize this somehow.
Some possible suggestions, taken the last example as an input: 

- use the "name" attribute and put there the name of the method plus the arguments; e.g. "personIsAdultInline(22, true)"
- a better option would be to have the name of the arguments also; e.g. "personIsAdultInline(age: 22, valid: true)"

Some care needs to be taken though, since arguments can be potentially lengthy and have strings..

note: please see previous discussion on https://github.com/junit-team/junit5/issues/1182#issuecomment-409680219

**Comment by marcphilipp** [comment]
We plan to address this as part of #373.
