### ISSUE TITLE
@TestFactory should be able to return a single DynamicNode

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#1521]
I [experimented](https://github.com/CodeFX-org/demo-junit-5/blob/0dbfbfdade3995cbf35541449fe60ebde95d9aa3/src/test/java/org/codefx/demo/junit5/dynamic/ArithmeticTreeTest.java) with using dynamic tests to generate a hierarchical structure that mirrors the test data's structure (went well), and I came up with one minor possible improvement:

Allow test factory methods to return a single `DynamicNode`.

I ended up there because my input data was a tree, which has just a single top-level node, so I created a test plan with a single top-level `DynamicContainer`. Wrapping that in a `Stream` is not complicated, but unnecessary.

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 for _team discussion_

**Comment by sbrannen** [comment]
I think that's a valid feature request.

So, let's see what the rest of the @junit-team/junit-lambda says.

**Comment by marcphilipp** [comment]
Does a single top-level container really make sense? Why not just use the `@TestFactory` method to group things instead?

**Comment by nicolaiparlog** [comment]
Two reasons:

* A recursive approach to generating dynamic tests for a recursive data structure will typically yield the root node as top-level element, not a list of its children. Special-casing that or unpacking the children is meaningless boilerplate.
* The top-level container is associated with a concrete node in the graph and might be named accordingly whereas the test method itself could have a more general name:

    ![junit-5-hierarchical-test-output](https://user-images.githubusercontent.com/6537432/43714773-7e31bdd6-997e-11e8-89da-9b5986431d9f.png)

**Comment by marcphilipp** [comment]
Thanks for the example! No objections from my side.

**Comment by dmcg** [comment]
I came here looking for this feature. Without it [minutest](https://github.com/dmcg/minutest) ends up generating a vestigial root node, which is a shame. Happy to contribute if someone will point me in the right direction.

**Comment by sormuras** [comment]
Implementing a spike right now:

### Given
```java
@TestFactory
DynamicNode dynamicNodeRoot() {
	return dynamicTest("0th dynamic test", () -> assertFalse(false));
}
```

### Then A
![image](https://user-images.githubusercontent.com/2319838/45907294-b0779980-bdf7-11e8-8adb-ec0320800e63.png)

### Then B
```
> 0th dynamic test
> dynamicTestsFromArray()
```
_without the method node_


Which one do you want?

**Comment by nicolaiparlog** [comment]
Generally speaking, **A** (see second bullet [here](https://github.com/junit-team/junit5/issues/1521#issuecomment-410680679)), but for the special special case where the single returned node is a test (not a container), **B** may be ok...

**Comment by sormuras** [comment]
Okay. Version `A` is ready for review in a few minutes...

**Comment by sormuras** [comment]
...as **B** is almost impossible to implement. The display name for a dynamic test is determined at runtime and can't override the properties of the `@TestFactory`-annotated method node.

Updated the source snippet and image above showing now a sample for `DynamicTest` and  `DynamicContainer`.
