### ISSUE TITLE
Use field injection for TestReporter et al

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#1522]
Do not require Jupiter users to create a constructor to use fields of type `TestReporter` (and other types Jupiter injects by default). Instead, inject instances into such fields after construction.

**PS**: This is a straw man, I don't actually want this feature, but I'd like to have a place to direct people to for explanation on why it doesn't exist. Why I don't think that's a good idea:

* field injection is "magic", i.e. a decent amount of developers will be unsure where the instances come from
* fields can be declared all over the place, which makes it easy to miss one
* injected fields can not be referenced in the constructor because they are still `null`

All you get for that is saving less than the dozen keystrokes it takes to have you IDE generate or update the constructor.

If this feature is not implemented, this issue could serve as documentation for why not. Beyond that a short note in the user guide could mention that this is not an oversight.

**Comment by marcphilipp** [comment]
The `ParameterResolver` extension point is designed to support parameter injection. Technically, it relies on a `java.lang.reflect.Parameter` being present which would not work for fields. Fields are different, e.g. there's no defined order. Extensions that wish to support field injection can do so by implementing the `TestInstancePostProcessor` interface. Moreover, I don't really see the use case for having a `TestReporter` field. Why not inject it into the test methods that need it directly?

**Comment by nicolaiparlog** [comment]
> Moreover, I don't really see the use case for having a TestReporter field. Why not inject it into the test methods that need it directly?

In this hypothetical, many tests use the reporter; enough that it was decided that a field and constructor would be a better choice than repeating the same parameter everywhere. Even more ~~laziness~~ desire for succinctness lead to the wish to get rid of the constructor.

**Comment by sbrannen** [comment]
Whenever something like a `TestReporter` is needed in multiple test methods, I also condone the use of `private final` fields (i.e., immutable and set via _constructor injection_).

Of course, that's assuming one has not opted for the per-class test instance lifecycle. 😉 

In general, I think it would be out of scope for JUnit Jupiter to provide direct support for _field injection_. Moreover, as @marcphilipp pointed out, the existing `ParameterResolver` API and infrastructure simply would not work for fields.
