### ISSUE TITLE
Improve TestKit API

### ISSUE THREAD

**Issue by dotCipher** [junit-team/junit5#1532]
## Overview

**Refacting and polishing of the `testkit` API**:  
As referenced in #1392 , the API for `testkit` has a lot of duplicate methods, non-symmetrical calls, etc.  It would be my intention to refactor the existing calls into a more concise API for accessing different parts of the underlying test's `Execution` or `ExecutionEvent`s.

To elaborate, the concepts provided from the API should follow the hierarchy (basic draft) of:
- Event
  - TestEvent
  - ContainerEvent
- Test

Every API method should maintain symmetry in terms of pluralization of the concept provided (ie `getEvents()` and `getTestEvents()` etc).

## Deliverables

- [ ] Refactor `testkit` API for a more consistent and concise API
- [ ] Documentation for all associated methods

**Comment by jlink** [comment]
What I'd need to transfer most of my integration tests for jqwik to testkit:
- events.assertEventsMatch() : Event matching where order of events does not matter and where some events can be left out

**Comment by jlink** [comment]
Moreover, I'd like an entry to testkit where I can give a TestEngine instance. Something like:
`EngineTestKit.engine(new MyTestEngine(...))`
This would simplify specific configuration testing that have different behaviour.

**Comment by jlink** [comment]
Just noticed that `EngineTestKit.engine(new MyTestEngine(...))` does exists but its behaviour is different from `EngineTestKit.engine("engine-id")` since there are more events being generated.

**Comment by sbrannen** [comment]
Oops...... this GitHub issue somehow slipped under the radar.

It has since been superseded by #1662 which went in JUnit Jupiter 5.4.

I am therefore closing this issue.

@dotCipher, have you had a chance to look at the version of the Test Kit that was released this week in 5.4?

**Comment by sbrannen** [comment]
> What I'd need to transfer most of my integration tests for jqwik to testkit:
> 
>     * events.assertEventsMatch() : Event matching where order of events does not matter and where some events can be left out

@jlink, are you aware of the `org.junit.platform.testkit.engine.Events.assertThatEvents()` method.

With `assertThatEvents()` you are not required to declare all events, unlike with `assertEventsMatchExactly(Condition<? super Event>... conditions)`.

There are examples in the User Guide: https://junit.org/junit5/docs/current/user-guide/#testkit-engine-events

If that does not meet your needs, please open a new GitHub issue.

Thanks!

**Comment by jlink** [comment]
see https://github.com/junit-team/junit5/issues/1771
