### ISSUE TITLE
Respect `--disable-ansi-colors` option when showing usage help 

### ISSUE THREAD

**Issue by remkop** [junit-team/junit5#1537]
Following up on #1530:

> @marcphilipp: Should we take into account the `--disable-ansi-colors` option when printing the usage message?
> 
> @remkop: I would like to but the API of the `CommandLineOptionsParser` interface in its current form does not lend itself to this: the `printHelp` method has no parameter to indicate whether ANSI colors should be used.
> @remkop: Shall we discuss improving the internal `CommandLineOptionsParser` API to cater for switching off ANSI output in a separate ticket?
> @marcphilipp: Yeah, let's do that. 

Salient points:
* this is an internal API and can be modified at will
* it may not always be possible to respect the `--disable-ansi-colors` option, e.g., when the input is invalid

**Comment by sbrannen** [comment]
PR #2349 has been submitted to address this.
