### ISSUE TITLE
Autocompletion script for ConsoleLauncher

### ISSUE THREAD

**Issue by remkop** [junit-team/junit5#1538]
Would there be interest in a bash/zsh completion script that would allow users to TAB-complete options and option parameters when invoking the `ConsoleLauncher`?

Currently the launcher is started with 

```
java -jar junit-platform-console-standalone-1.2.0.jar <Options>
```

By using the Gradle `application` plugin, it is straightforward to generate a distribution that includes a script for running the application. 

This script would become the main way to invoke the console launcher. For example:

```
consolelauncher.sh <Options>
```

Once we have a starter script, picocli can easily generate a [completion script](https://picocli.info/autocomplete.html) that suggests possible completion candidates for anything following `consolelauncher.sh` on the command line.

Let me know if there’s interest in doing this.

**Comment by remkop** [comment]
@sbrannen, sure, like every feature, it needs to be a good trade-off. 

For what it's worth, the cost side of this trade-off is very low since the completion script is not hand-crafted code but is generated automatically from the `AvailableOptions` command definition. It could even be automatically generated as part of the build.

**Comment by sbrannen** [comment]
> For what it's worth, the cost side of this trade-off is very low since the completion script is not hand-crafted code but is generated automatically from the AvailableOptions command definition. It could even be automatically generated as part of the build.

OK. That's good to know.
