### ISSUE TITLE
Introduce "Deprecated APIs" section in User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1540]
## Overview

Analogous to the existing [Experimental APIs](https://junit.org/junit5/docs/snapshot/user-guide/#api-evolution-experimental-apis) section in the User Guide, we should introduce a "Deprecated APIs" section as well.

## Related Issues

- #1317 
- #1536 

## Deliverables

- [ ] Introduce "Deprecated APIs" section in User Guide

**Comment by sormuras** [comment]
_in progress..._

**Comment by sbrannen** [comment]
Thanks for the super quick turnaround... less than 24 hours after the 5.3 RC1 release. 😉
