### ISSUE TITLE
Update JUnit Jupiter Sample Projects section of User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1542]
## Overview

The [JUnit Jupiter Sample Projects](https://junit.org/junit5/docs/snapshot/user-guide/#dependency-metadata-junit-jupiter-samples) section of the User Guide currently only references the `junit5-jupiter-starter-gradle` and `junit5-jupiter-starter-maven` projects; whereas, the sample repository now contains considerably more projects.

## Deliverables

- [x] Update _JUnit Jupiter Sample Projects_ section of User Guide to reference all sample projects (or at least a selected set of highlighted projects)

**Comment by rbfriedman** [comment]
I can take this

**Comment by sbrannen** [comment]
@rbfriedman, OK. I've labeled it as "up for grabs" for the time being.

Feel free to submit a PR.

Cheers

**Comment by sricheta92** [comment]
Hello,
I am new to open source contribution. I have fixed it and raised a pull request. Please review and let me know if any changes need to be done.
Thanks.

**Comment by PaulSh84** [comment]
oh no, I was about to raise a pull request too :(

**Comment by sbrannen** [comment]
This has been addressed by @sricheta92 in e6d1db38be4a027432b824fe37f4b4fd4f0cacd5 and polished in edf0d45967dad707e4f17c35d5d22b2aceffce7e.
