### ISSUE TITLE
Merge @Test and @DisplayName annotations

### ISSUE THREAD

**Issue by ViToni** [junit-team/junit5#1543]
After reviewing some tests written with JUnit 5 I noticed that parameterized tests can be expressed in a more compact form than "regular" tests because the @ParameterizedTest annotation supports the name parameter whereas the regular tests need a @Test and @DisplayName annotation.

If the @Test annotation would accept a String value the same could be achieved by using just one annotation.

What do you think?

**Comment by smoyer64** [comment]
Duplicate of #614 and #1504

**Comment by sbrannen** [comment]
related to #1440
