### ISSUE TITLE
Kotlin extension function ArgumentsAccessor.getAs cannot be imported

### ISSUE THREAD

**Issue by juergenzimmermann** [junit-team/junit5#1546]
Looks like https://github.com/junit-team/junit5/issues/1490 still doesn't work:

```
import org.junit.jupiter.params.aggregator.getAs
```
results in:
```
e: C:\testcase\src\test\kotlin\de\test\MyTest.kt: (7, 44): Unresolved reference: getAs
```

A testcase is attached.
[testcase.zip](https://github.com/junit-team/junit5/files/2287420/testcase.zip)

**Comment by marcphilipp** [comment]
Thanks for reporting! I was sure I verified it worked after we made the change but now I'm running into the same issue again. I think it's time for a real integration test for Kotlin extension functions.

@juergenzimmermann Any idea why it doesn't work?

**Comment by marcphilipp** [comment]
Eureka! I think I found the root cause: https://discuss.kotlinlang.org/t/solved-extension-functions-not-available-when-exported-to-jar/4939

The JAR file does not include the `META-INF/junit-jupiter-params.kotlin_module`. Looks like it's lost during shadowing. Without it extension function don't work.

**Comment by juergenzimmermann** [comment]
Sounds good:
* e.g. `io.projectreactor:reactor-core3.2.0.M3` contains `META-INF/reactor-core.kotlin_module`
* junit-jupiter-params-5.3.0-RC1.jar doesn't have such a metadata file. See also https://blog.jetbrains.com/kotlin/2015/06/improving-java-interop-top-level-functions-and-properties.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
Oops, wrong button. 🙈

**Comment by sbrannen** [comment]
> The JAR file does not include the `META-INF/junit-jupiter-params.kotlin_module`. Looks like it's lost during shadowing. Without it, extension functions don't work.

_Eureka!_ 

Nice detective work, @marcphilipp! 👏
