### ISSUE TITLE
Ship picocli license with junit-platform-console

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1547]
The junit-platform-console JAR currently ships with `META-INF/LICENSE-jopt-simple.md`. Instead, it should include picocli's license.

### Deliverables

- [ ] Replace `LICENSE-jopt-simple.md` with `LICENSE-picocli.md`

**Comment by marcphilipp** [comment]
_in progress_

**Comment by sbrannen** [comment]
good catch

**Comment by sbrannen** [comment]
Though I'm not sure I'd classify this as a 🐛 . 😉
