### ISSUE TITLE
JUnit XML Spec

### ISSUE THREAD

**Issue by palmerj3** [junit-team/junit5#1550]
## Overview

**Feature request.** 

The JUnit XML spec allows for properties on a [testsuite](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_14.1.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html) but not on individual tests.

I would like to expand this spec to support properties for each test.

For large systems, like Spotify (where I work), we are limited to what we can do with properties in the current XML spec. We can currently provide aggregate information in the test suite but if we have per-test ownership, per test performance data, etc we have to use other systems to log this. I would much rather us continue to use junit xml spec.

## Deliverables

- JUnit XML spec offers per-test properties

**Comment by sormuras** [comment]
Related to the up-stream project: https://github.com/ota4j-team/opentest4j/issues/9

**Comment by sbrannen** [comment]
Closing this issue since the JUnit Team does not actually _own_ the "JUnit XML" schema you are referring to.

Please contribute proposals and comments to the aforementioned issue with the OTA.
