### ISSUE TITLE
Unrecognized module

### ISSUE THREAD

**Issue by 1459177541** [junit-team/junit5#1552]
In testing JDK9 module system, module related information is not available. Can only get module information of JDK.
I wrote the same module code in the main function and the test method, but the results were different.The main function can get the relevant information normally, but the test method is not.

**Comment by sormuras** [comment]
Please share more details about how you setup your project and how you start the test run. Even better, provide a minimal compiling example.

More information on "Testing in the Modular World" are gathered here: https://github.com/junit-team/junit5-samples/tree/master/junit5-modular-world

**Comment by 1459177541** [comment]
Thank you. I think maybe I am not familiar with how to configure it.

**Comment by 1459177541** [comment]
Code like this:
`public class ModuleTest {
    @Test
    public void moduleTest(){
        System.out.println(ModuleTest.class.getModule());
    }

    public static void main(String[] args) {
        System.out.println(ModuleTest.class.getModule());
    }
}`
Run moduleTest() print: unnamed module @363ee3a2
Run main() print: module moduleTest
In my project, ModuleTest in moduleTest module.

English is not my mother tongue. It may not be clear.

**Comment by sormuras** [comment]
Got your point.

See [moduleName()](https://github.com/junit-team/junit5-samples/blob/master/junit5-modular-world/src/test/black.box/black/box/BlackBoxTests.java#L30) test: it is exactly checking what you are trying to. For these kind of tests to succeed, you have go the way of [test-patch-compile.jsh](https://github.com/junit-team/junit5-samples/blob/master/junit5-modular-world/test-patch-compile.jsh). That is launching the Java module system with the test environment as your launch pad.

I am about to write a very detailed blog post about this topic ... soon. In the meanwhile, you may consult my "notes" for it here: https://gitpitch.com/sormuras/testing-in-the-modular-world/master#/6

**Comment by sormuras** [comment]
Did you get your modular test green, @1459177541?

**Comment by 1459177541** [comment]
Sorry, I think I need to continue to study it.

**Comment by 1459177541** [comment]
Thank you very much. I'll do my research again.

**Comment by sormuras** [comment]
Alright, closed the question for now. Will paste the link to the blog here, when it's done.

Happy researching!
