### ISSUE TITLE
Check TestEngine ID for "junit-" prefix on registration

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1557]
## Overview

The `junit-` prefix is owned by the JUnit Team. It's akin to using `org.junit` as a base package. No other entity in the world should do that.

Only two engines should use the prefix at the moment:

* `junit-jupiter`
* `junit-vintage`

Source of the discussion: https://github.com/junit-team/junit5/commit/5a44da8c6145611057923a8ae46df540c566fc04#r30200049

## Deliverables

- [x] Document in the User Guide that the JUnit Team _owns_ the `junit-` prefix for `TestEngine` IDs.
- [x] Emit a warning when a `TestEngine` ID starts with `junit-`, except those published by the JUnit Team from the JUnit 5 repository for public consumption.
- [x] Create follow-up ticket for ignoring all such _foreign_ engines in a future release of the Platform: #1572

**Comment by sormuras** [comment]
_in progress..._

**Comment by sbrannen** [comment]
Reopening to address unfinished TODOs.

**Comment by sbrannen** [comment]
@sormuras, did you already take care of this one?

>  Create follow-up ticket for ignoring all such foreign engines in a future release of the Platform.

**Comment by sormuras** [comment]
Just creating it.

**Comment by sbrannen** [comment]
These changes are now documented in the User Guide.

See a23cffd8d0693a47b6f0454ac23b175dbb34e4e0.
