### ISSUE TITLE
Add list of contributors to release notes

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#156]
Since we do not use author tags.
Also add it to release notes for Alpha.

Can we easily automate the creation of  this list?

**Comment by jlink** [comment]
One question before tackling it: How should contributors be sorted?
- Alphabetically?
- By number of committed/deleted lines?
- By number of commits?
- In order of appearance?
- any other criteria?

**Comment by marcphilipp** [comment]
One thought before you start:Isn't https://github.com/junit-team/junit5/graphs/contributors enough?

**Comment by jlink** [comment]
Do you mean you wouln't like them to be in the release notes at all?

2016-03-01 9:07 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by marcphilipp** [comment]
Well, if it's easy to do, I think we should add them to the release notes. But if it's a lot of hassle I would rather focus on something else. :wink:

**Comment by jlink** [comment]
I'm fine with that if everyone else is. So I'll only add a link to the
project's contributors page.

2016-03-01 9:12 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by jlink** [comment]
Done in master.
