### ISSUE TITLE
Introduce implicit conversion from fully qualified class name to Class instance in parameterized tests

### ISSUE THREAD

**Issue by Jitsusama** [junit-team/junit5#1562]
## Overview

I would like to be able to pass a class name in to a parameterized test along with a set of other data points and use these parameterized values to drive/validate a test. I typically use this in a circumstance where I want to drive a test wherein a number of possible exceptions could be thrown that should result in a similar result, with that result having a number of other parameterized input parameters.

## Related Pull Requests

- #1564 

## Deliverables

- [ ] Provide a solution such that code similar to the following example could work:

```java
@ParameterizedTest
@CsvSource({"OneException.class,someName,someNumber", "TwoException.class,anotherName,anotherNumber"})
void anExampleTest(Class<Throwable> clazz, String name, String number) {
  when(collaborator.doTheOtherThing(name, number)).thenThrow(class);

  try {
    unitUnderTest.doTheThing(name, number);
  }
  catch (Exception ignored) {
  }

  assertThat(standardOutput).contains(name + " " + number);
}
```

**Comment by Jitsusama** [comment]
As a note; my current work-around is to use a `@MethodSource` with a method that returns a data structure containing all of the items I need. This makes for one-off methods lying around as test fixtures, often to support a single test, with a nasty interface inside the test requiring that I perform a `#get` on a list or some such.

**Comment by nicolaiparlog** [comment]
@Jitsusama Take a look [at argument converters](https://blog.codefx.org/libraries/junit-5-parameterized-tests/#Argument-Converters) - with them you can easily map such strings to a `Class` instance.

**Comment by nicolaiparlog** [comment]
Mmh, I just checked why `String` ~> `Class` does not work by object factories. Turns out, `Class` not only has `static Class<?> forName(String)` (good!), but also `static native Class<?> getPrimitiveClass(String)` (bad).

**Comment by sormuras** [comment]
We could add `static Class<?> forName(String)` to the list of well-known and supported factories.

**Comment by nicolaiparlog** [comment]
On it.

**Comment by Jitsusama** [comment]
Thanks so much @nicolaiparlog and @sormuras for not only answering, but working on an even nicer solution so quickly!

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 GA for _team discussion_

**Comment by Jitsusama** [comment]
@sbrannen; I noticed you changed the title to indicate that a fully qualified class name is required. Is this accurate? Can I not refer to just the class name without the package hierarchy specified when the class is imported into the test module?

**Comment by sbrannen** [comment]
Since JUnit does not analyze the byte code of your compiled class, JUnit does not know what types you imported when you class was compiled. Consequently, the fully qualified class name is in fact necessary.

**Comment by Jitsusama** [comment]
Thanks for the clarification @sbrannen.
