### ISSUE TITLE
Using JUnit 4 APIs with JUnit 5 is punitive

### ISSUE THREAD

**Issue by swankjesse** [junit-team/junit5#1582]
If you import a JUnit 4 API by mistake, JUnit 5 doesn’t honor it. For example, if you use `assumeTrue()` from the legacy package your test will fail with an `org.junit.AssumptionViolatedException`.

```
import static org.junit.Assume.assumeTrue;
```
The same is true for `org.junit.Ignore` vs `org.junit.jupiter.api.Disabled`. The `@Ignore` annotation is not honored and there’s not even guidance that the annotation has changed.

I work with both versions and so I’m frequently suffering papercuts because the APIs are needlessly incompatible.

**Comment by sormuras** [comment]
Feel your pain too, sometimes. Maybe Jupiter could provide a "strict" opt-in mode, where it warns about vintage annotations when it sees 'em.

Or a one could define a Checkstyle rule that warns (or bails out) for when it sees a mix of both API used in one compilation unit. Usually, you have either JUnit 4 or Jupiter API -- not both of them. Would that help?

**Comment by leonard84** [comment]
This could also be addressed via a global extension, that inspects the test class/method for any legacy annotations.

**Comment by swankjesse** [comment]
Could you just honor the old behavior? Why make me choose?

**Comment by sbrannen** [comment]
> The `@Ignore` annotation is not honored and there’s not even guidance that the annotation has changed.

That's not true.

This is clearly documented in the [User Guide](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-tips) as well as in countless blogs, tutorials, and conference talks online.

**Comment by sbrannen** [comment]
FWIW, it would actually be easy to:

1. Implement an `ExecutionCondition` that supports JUnit 4's `@Ignore`.
2. Implement a `TestExecutionExceptionHandler` that wraps an `org.junit.AssumptionViolatedException` in an `org.opentest4j.TestAbortedException`.

And those could be part of `junit-jupiter-migrationsupport`.

Of course, a `TestExecutionExceptionHandler` could not handle an `org.junit.AssumptionViolatedException` thrown from a lifecycle callback method or extension.

So an alternative to that would be the introduction of reflective support to determine if an exception of type `org.junit.AssumptionViolatedException` was thrown and then treat that as an `org.opentest4j.TestAbortedException` within the `JupiterTestEngine` internals.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment]
Currently assigned to the 5.4 M1 backlog for the purpose of team discussion.

**Comment by sbrannen** [comment]
> I work with both versions and so I’m frequently suffering papercuts because the APIs are needlessly incompatible.

Well, AFAIK, JUnit 4 will never change `AssumptionViolatedException` to extend `TestAbortedException`. So there won't be any remedy for you there when using JUnit 4.

The best we can offer is either better diagnostics in JUnit Jupiter or outright "translation" support as I mentioned in my previous comments.

**Comment by sbrannen** [comment]
> Well, AFAIK, JUnit 4 will never change `AssumptionViolatedException` to extend `TestAbortedException`. So there won't be any remedy for you there when using JUnit 4.

However, we could potentially meta-annotate `@Disabled` with `@Ignore` (and only have the JUnit 4 artifact as an _optional_ dependency).

That would work, except that you'd lose the custom message supplied to `@Disabled`, and no other types of `ExecutionCondition` would be "supported" in JUnit 4.

**Comment by swankjesse** [comment]
The JUnit 5 User Guide is a 98 page PDF. Is it called Jupiter because it’s massive and takes a lifetime to get to?

**Comment by smoyer64** [comment]
@swankjesse You don't have to read the whole thing at once - it's organized topically.  You will need to grok the intent behind JUnit Jupiter.  I suppose we could write a little routine that pipes the User Guide to Twitter 140 characters at a time for people who are averse to reading.

**Comment by swankjesse** [comment]
I’m grumpy not because JUnit 5 has a lot of documentation, but because JUnit 5 needs a lot of documentation. It’s a big library that has many features and solves many problems and is awkwardly different from and incompatible with its predecessor.

**Comment by sormuras** [comment]
@swankjesse It took me some hours, but I compiled an overview. Just for you. :-)

https://sormuras.github.io/blog/2018-09-13-junit-4-core-vs-jupiter-api

**Comment by smoyer64** [comment]
@swankjesse If you're really only talking about JUnit4 tests written using the junit library, @boyarsky wrote a nice converter that will bulk change your imports, tests and assertions (https://github.com/boyarsky/convert-junit4-to-junit5).  If you're using additional Rules or Runners, you've already added more features/complexity.  Hopefully we'll be moving that project to [Pioneer](https://github.com/junit-pioneer/junit-pioneer) and upgrading it to handle more types of conversions automatically.

**Comment by swankjesse** [comment]
@smoyer64 I maintain a [test library](https://github.com/square/okhttp/blob/master/mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java#L101) that uses `org.junit.rules.ExternalResource` so to migrate myself I need to migrate a lot of downstream users first! I’ve learned the lesson not to depend on JUnit APIs.

**Comment by marcphilipp** [comment]
**Team Decision:**

- Add support for `AssumptionViolatedException` to junit-jupiter-engine (#1585)
- Add support for `@Ignore` to junit-jupiter-migrationsupport (#1586)
