### ISSUE TITLE
Include Javadoc and Sources in Platform ConsoleLauncher standalone artifacts

### ISSUE THREAD

**Issue by krizleebear** [junit-team/junit5#1583]
Actual:
The sources/javadoc JARs on maven only contain the manifest information, but are missing the real information.

Expected:
I would expect the files to contain the sources and javadocs of all the classes delivered in junit-platform-console-standalone-1.3.0.jar

Rationale:
The standalone JAR offers an easy way to migrate an old JUnit 3/4 code base to JUnit Jupiter.
But without Javadoc and/or Java sources a lot of important information how to perform the migration (e.g. deprecation notes) is harder to access.

The can easily be seen if you have a look at the artefact list:
http://central.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.3.0/

**Comment by sbrannen** [comment]
Thanks for raising the issue.

I've assigned this to the 5.4 Backlog and put it "up for grabs".

**Comment by krizleebear** [comment]
Thanks for the quick reply!

**Comment by sormuras** [comment]
Tried it once but failed to maintain the integrity of the standalone artifact - as it includes the binaries from various modules, license files, _hand-crafted_ MANIFEST file, etc. Can't you just load the source and javadoc jar from the other modules and use them?

**Comment by krizleebear** [comment]
I can try but it seems non-trivial, as I might end up with the same problem you were facing. Eclipse only allows a 1:1 relationship between Lib and attached source. 
Note: We're not using Maven or Gradle. That's why the standalone package is so beneficial for us. And I guess that's also the reason it exists (?)

**Comment by krizleebear** [comment]
My light weight solutions is an Ant task that builds a combined JAR of attached-sources from "JUnit 4.12" and "Jupiter API". I'm aware that this is not the real solution to the reported problem, but might help others with the same problem.

```xml
<project default="combine-sources">

	<property name="JUNIT_PLATFORM_VERSION" value="1.3.0" />
	<property name="JUNIT_JUPITER_VERSION" value="5.3.0" />

	<target name="combine-sources">
		<property name="attached-sources-dir" value="attached-sources" />
		<property name="MAVEN_REPO_URL" value="https://repo1.maven.org/maven2" />

		<delete dir="${attached-sources-dir}" />
		<mkdir dir="${attached-sources-dir}" />

		<get src="${MAVEN_REPO_URL}/junit/junit/4.12/junit-4.12-sources.jar" dest="${attached-sources-dir}" />
		<get src="${MAVEN_REPO_URL}/org/junit/jupiter/junit-jupiter-api/${JUNIT_JUPITER_VERSION}/junit-jupiter-api-${JUNIT_JUPITER_VERSION}-sources.jar" dest="${attached-sources-dir}" />

		<jar destfile="junit-platform-console-standalone-${JUNIT_PLATFORM_VERSION}-sources.jar">
			<archives>
				<zips>
					<fileset dir="${attached-sources-dir}" includes="**/*.jar" />
				</zips>
			</archives>
		</jar>

		<delete dir="${attached-sources-dir}" />
	</target>
	
</project>
```

**Comment by joergsesterhenn** [comment]
Creating an uber jar for sources is discussed here: https://github.com/johnrengelman/shadow/issues/41

They also mention a workaround, that could be implemented here.

@sormuras: As for integrity... Would there be value in having all sources in the jar (e.g. for debugging), even if the manifest, license files, etc. were missing/invalid?
Another idea would be to provide just the aggregated javadoc and leave the sources alone. This could improve debugging/migration. Would you think this might be easier than dealing with the sources?

**Comment by sormuras** [comment]
> As for integrity... Would there be value in having all sources in the jar (e.g. for debugging), even if the manifest, license files, etc. were missing/invalid?

Missing out some assets would be okay, including invalid ones not.

And yes, I think having Java sources included in the standalone JAR has its merits. Wonder, how much the size of the JAR file increases and whether it makes sense to provide a dedicated `"-standalone-with-sources.jar"`.

**Comment by krizleebear** [comment]
> Another idea would be to provide just the aggregated javadoc and leave the sources alone. This could improve debugging/migration. Would you think this might be easier than dealing with the sources?

Javadoc alone wouldn't be enough from my POV. We're very keen in taking a look into the inner workings.

**Comment by marcphilipp** [comment]
I think we should publish regular sources and javadoc jars like we do for all other subprojects.
