### ISSUE TITLE
ResourceLocks via Extensions

### ISSUE THREAD

**Issue by ashley-taylor** [junit-team/junit5#1584]
We are wanting to experiment with parallel test threads to speed up execution.
We are using a custom Extension in our e2e test suite.

These e2e tests are mostly read only tests with a few that modify db state.

The annotation takes the name of the client we are testing against.
The Extension is then responsible for making sure everything related to the client is prepared and in the base state.

It then uses the ParameterResolver feature to passes testing objects into each test method that automatically talk to the client based on the annotation.

Within the Extension we know if the helpers request modify state or are read only.

We would like to be able to extend our existing extension to be able to dynamic add ResourceLocks on a per test bases.

**Comment by marcphilipp** [comment]
In order to avoid deadlocks, all resource locks have to be known before starting execution. Currently, we don't discover or instantiate extensions prior to a test's execution.
