### ISSUE TITLE
Add support for JUnit 4's AssumptionViolatedException in JUnit Jupiter

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1585]
## Overview

In order to provide a smoother migration path from JUnit 4 to JUnit Jupiter, the `JupiterTestEngine` module should provide support for JUnit 4's `org.junit.AssumptionViolatedException` for failed assumptions analogous to Jupiter's support for the `org.opentest4j.TestAbortedException` from the Open Test Alliance.

## Implementation Notes

In order to avoid a compile-time dependency on JUnit 4 within the `junit-jupiter-engine` module, we should use reflection to load the `org.junit.AssumptionViolatedException` based on a hard-coded copy of its fully qualified class name.

## Related Issues

- #1586 

## Deliverables

- [x] Add support for JUnit 4's `org.junit.AssumptionViolatedException` in JUnit Jupiter
- [x] Update User Guide
- [x] Update Release Notes

**Comment by sbrannen** [comment]
FYI: I wrote the _description_ for this issue.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
For anyone interested, the work for this issue can be viewed in the following feature branch.

https://github.com/junit-team/junit5/commits/issues/1585-AssumptionViolatedException

**Comment by sbrannen** [comment]
This has been addressed in `master` in c4533c378ffa2200067850f371e3626b08258b34.
