### ISSUE TITLE
Add support for JUnit 4's @Ignore to junit-jupiter-migrationsupport

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1586]
## Overview

In order to provide a smoother migration path from JUnit 4 to JUnit Jupiter, the `junit-jupiter-migrationsupport` module should provide support for JUnit 4's `@Ignore` annotation analogous to Jupiter's `@Disabled` annotation.

## Related Issues

- #1585

## Deliverables

- [x] Add support for JUnit 4's `@Ignore` annotation to `junit-jupiter-migrationsupport` -- for example, via a new `IgnoreCondition`
- [x] Introduce a new `@EnableJUnit4MigrationSupport` _composed annotation_ that registers all rule migration support in addition to the new `IgnoreCondition`
- [x] Introduce proper integration tests for `IgnoreCondition`
- [x] Introduce empirical integration tests for `@EnableJUnit4MigrationSupport`
- [x] Update User Guide
- [x] Update Release Notes 
- ✖️ Allow the `IgnoreCondition` to be automatically registered via the `ServiceLoader` mechanism

**Comment by sbrannen** [comment]
FYI: I wrote the _description_ for this issue.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Work on this issue can be viewed in the following feature branch:

https://github.com/junit-team/junit5/commits/issues/1586-junit4-ignore-annotation

**Comment by sbrannen** [comment]
The 3 code "deliverables" have already been pushed to the feature branch.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, I've add the "team discussion" label in order to discuss the scope of this issue (i.e., which of the 3 code deliverables we want to keep).

**Comment by sbrannen** [comment]
**Team Decision**:

Do _not_ allow the `IgnoreCondition` to be automatically registered via the `ServiceLoader` mechanism.

**Comment by sbrannen** [comment]
I have force pushed the removal of the auto-registration support and updated the _Deliverables_.

**Comment by sbrannen** [comment]
I have force pushed additional tests and updated the Deliverables.

**Comment by sbrannen** [comment]
This work has now been merged into `master` in commit 7f04a28b136e8545206b66bf4b200271805beced.
