### ISSUE TITLE
How do non-Maven users download JUnit?

### ISSUE THREAD

**Issue by andrewducker** [junit-team/junit5#1587]
## Overview

There doesn't seem to be a way for developers who aren't using Maven to download JUnit 5 and reference it from their projects.  Am I missing something, or is this something that JUnit doesn't support as yet?

## Deliverables

A method of downloading JUnit and getting it running in a Java build system which doesn't use Maven.

**Comment by sbrannen** [comment]
Well, anyone can download straight from Maven Central. It only requires a web client (e.g., a web browser).

Also, Gradle has built-in support for downloading from Maven Central, and Ant can be used in conjunction with Ivy.

Did you have something specific in mind?

**Comment by sbrannen** [comment]
For example, if you want the JUnit Jupiter 5.3.1 API, you'd simply go here:

https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.3.1/

**Comment by sbrannen** [comment]
And if you want to know how I found that, I simply went search.maven.org:

https://search.maven.org/artifact/org.junit.jupiter/junit-jupiter-api/5.3.1/jar

**Comment by andrewducker** [comment]
It's not clear, from the documentation, which files I want to download.

From the JUnit 4 instructions it's quite clear - I download these two and put them in my classpath:

    [junit.jar]http://www.java2s.com/Code/Jar/j/Downloadjunit410jar.htm
    [hamcrest-core.jar]

From JUnit 5 - there are 15 Jars listed.  Do I need to download them all and include them all in my classpath?  I thought maybe the "Migrating from JUnit 4" section would be clear about what I needed to take, but it also didn't have anything on that.

A section on "If you're doing X, then you need Jars A, B, and C.  If you're doing Y then you need Jars A, C, and D" would be a great help.

**Comment by sormuras** [comment]
I suggest using the _console launcher standalone jar_ in case of lacking a dependency managing tool: https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

**Comment by andrewducker** [comment]
Thank you, that's great!

**Comment by britter** [comment]
> I suggest using the console launcher standalone jar in case of lacking a dependency managing tool: https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

Maybe the Installation section should be improved. It really doesn't go into detail on how to _install_ junit in your project. It describes the artifacts only. I think it could easily improved by a should section about build tool support, ide support and launching junit using the console launcher.

**Comment by marcphilipp** [comment]
@darkelf44 Your comment is disrespectful and clearly violates our [code of conduct](https://github.com/junit-team/junit5/blob/master/CODE_OF_CONDUCT.md). Please adjust your language and behavior. Otherwise, you cannot be a part of this community.

**Comment by ifrh** [comment]
Well, I want to use JUnit5. My linux package manager (Ubuntu 18 LTS) does know a package for Junit3 a package for Junit4 - but no Package for Junit5. I want to integrate Junit5-support to https://github.com/ifrh/Praktomat but realy I don't find information I need.
What Java-Packages should I copy to be able to call JUnit5 like Junit3 or Junit4 ( https://github.com/ifrh/Praktomat/blob/master/src/checker/checker/JUnitChecker.py#L50 ) ?

**Comment by marcphilipp** [comment]
@ifrh Sounds like you might want to use the [console launcher standalone jar](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher).

**Comment by ifrh** [comment]
@marcphilipp Yes, you are right. Thanks for pointing me to the `junit-platform-console-standalone-1.4.0.jar`. I'll try if that contains everything I need - but reading other information it may be that this _"standalone.jar"_ have multiple depenecies to other `jars`

**Comment by sormuras** [comment]
> ... but reading other information it may be ...

Which information source are those? Anyway, the _standalone_ stands on its own feet. It contains all you need to launch Jupiter and Vintage based tests.

**Comment by ifrh** [comment]
So I misinterpreted https://junit.org/junit5/docs/current/user-guide/#dependency-diagram .
I 'll try to connect [Praktomat ](https://github.com/ifrh/Praktomat/blob/master/src/checker/checker/JUnitChecker.py#L50) with the _standalone_ downloadable from https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.4.0/junit-platform-console-standalone-1.4.0.jar
