### ISSUE TITLE
Easily apply the same assertion(s) on a collection of items

### ISSUE THREAD

**Issue by quiram** [junit-team/junit5#1590]
## Overview

There are occasions in which you have a collection or stream of items, and you want to run the same assertion(s) on all of them. Moreover, you don't want to stop at the first failure, but rather you want to run the assertion in all items and get a full report. This can be done with the current set of assertions, but it could be useful to have some syntactic sugar to do this in a more compact manner.

For instance, if I have a list of invalid documents (that I'm defining somewhere else), and I want to test that my validator appropriately reports all of them as invalid, I would like a construct like this:

```java
List<Document> invalidDocuments = getInvalidDocuments();
assertForAll(invalidDocuments, doc -> () -> assertFalse(validator.isValid(doc)));
```

I know this looks similar to the following, but this stops at the first failure, which isn't what I would like to achieve:

```java
List<Document> invalidDocuments = getInvalidDocuments();
invalidDocuments.forEach(doc -> assertFalse(validator.isValid(doc)));
```

I guess I could also use `assertThat` on the collection and then specify a matcher to be applied to all items, but then I would have to write matchers instead of straight assertions, which would be more code. I would like the simplicity of one single, static assertion to check all items abide by one or more assertions.

## Deliverables

Something like the following can work; further versions can easily be made to cover `Stream` and the like.

```java
public static <T> void assertForAll(Collection<T> items, Function<T, Executable> executableProvider) throws MultipleFailuresError {
	final List<Executable> assertions = items.stream()
			.map(executableProvider)
			.collect(toList());

	assertAll(assertions);
}
```

**Comment by quiram** [comment]
Yes, good point, I forgot to mention that... I actually thought about it but couldn't apply that pattern to my particular case. I have an abstract `TestBase` class where I define some tests to apply to several cases, and the collection of items is provided by the extending child classes. Something like this (typing straight to avoid copy-pasting, apologies if there are some typos):

```
abstract class TestBase {
    abstract List<Document> getInvalidDocuments();
    abstract Validator getValidator();

    Validator validator;

    @BeforeEach
    void setup() {
        validator = getValidator();
    }

    @Test
    void testInvalidDocuments() {
        List<Document> invalidDocuments = getInvalidDocuments();
        assertForAll(invalidDocuments, doc -> () -> assertFalse(validator.isValid(doc)));    }
    }
}
```

Then, for each different `Validator`, the corresponding `ValidatorTest` extends `TestBase` and implements `getValidator()` and `getInvalidDocument()`. In my case there are several other tests defined in the `TestBase`, which justifies (I think) the template pattern.

In this case I cannot use `@ParameterizedTest` with `@MethodSource` because the target method needs to be `static`, which prevents me from overriding it in child classes.

**Comment by marcphilipp** [comment]
How about this?

```java
invalidDocuments.forEach(doc -> assertFalse(validator.isValid(doc)));
```

**Comment by marcphilipp** [comment]
Nevermind, that would obviously stop after the first failure.

**Comment by sormuras** [comment]
Testlets! Aka dynamic tests could help.

**Comment by quiram** [comment]
Mm, I don’t know about teslets, do you have a link that I can check? Maybe that can fix my scenario 🙂

**Comment by sormuras** [comment]
Here you go: https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests

**Comment by quiram** [comment]
Thanks @sormuras, this is interesting and I think I could write my tests this way. There is one thing that concerns me though: if I understand correctly, the `@BeforeEach` is run before the entire suite of tests provided by `@TestFactory`, instead of before each individual test, is that right? If so, would there be a way so the setup is done before each test? I'd prefer each test(let) to be fully independent from the others.

**Comment by sormuras** [comment]
> ... the @BeforeEach is run before the entire suite of tests provided by @TestFactory, instead of before each individual test, is that right?

Correct. That's why I call them "testlets" or _assertAll-on-steroids_...

...so the solution is here to care about the setup before each lambda yourselves. Like instead of

`() -> assertTrue(validator.isValid(doc))`

do 

`() -> assertTrue(getValidator().isValid(doc))`.

If you need to tear down the created validator, introduce a dedicated assertion method. Like:

```
private void assertIsValid(Doc doc) {
  var validator = getValidator();
  try {
    assertTrue(validator.isValid(doc));
  } finally {
    validator.close();
  }
}
```
and use it via `() -> assertIsValid(doc)` as an `Executable` with the dynamic test.

**Comment by quiram** [comment]
I see... but then, if I have multiple testlets (as I would have if I was to rewrite my current case using `@TestFactory`), I would have to repeat the setup in each of them, which would probably make for a messier test class.

Don't get me wrong, I like the idea of testlets and I thank you for introducing me to it, but I don't think it quite fits in this case. I guess they are just more powerful than what I need, and with a cost.

**Comment by quiram** [comment]
Maybe... to be fair, and for my particular case, simply removing the constraint that the target method in `@MethodSource` has to be static wold work for me, but I don't know whether that's possible.

**Comment by leonard84** [comment]
@quiram you could try [AssertJ's Soft Assertions](https://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#soft-assertions)

**Comment by sbrannen** [comment]
@quiram, does `@TestInstance(PER_CLASS)` work for you?

**Comment by quiram** [comment]
Documentation? What's that? :trollface: 

In all seriousness, first of all apologies for late reply, I have been backed up the last couple of days. And second apologies for not noticing that in the user guide, I guess assumed so strongly that the method had to be static that I didn't even consider checking if there was a way to avoid that restriction. Using`@TestInstance(PER_CLASS)` does help, and now I can have parameterised tests making the supplier method abstract and non-static, thanks!

@leonard84 AssertJ's soft assertions would have worked too, I didn't know about those, thanks! However I'll stick to the simpler parameterised tests like @sbrannen suggested.
