### ISSUE TITLE
Introduce support for a custom test scheduler

### ISSUE THREAD

**Issue by ThomasKrieger** [junit-team/junit5#16]
Hello,
my use case is to execute the same testcase concurrently in different threads on the same test object to find race conditions. If I understand the api correctly this should be possible by using the annotation @TestInstance PER_CLASS and the yet to be implemented but planned "Introduce support for registering parameterized tests  #14". What is missing is an annotation for a custom scheduler which gets preferably the root EngineTestExecutionNode and is responsible for actually running the tests. Is something like this planned already?
Thank you very much
Thomas

**Comment by sbrannen** [comment]
Hi @ThomasKrieger,

We are in fact considering to provide an extension point for the actual _execution_ of a test; however, we have not yet gotten to the point where we can make that a reality in the current prototype.

As soon as make progress in this area, we will post back here.

Cheers,

Sam

**Comment by marcphilipp** [comment]
This will be addressed by #871 and #20.
