### ISSUE TITLE
@DisabledOnOs does not work on Solaris

### ISSUE THREAD

**Issue by epeee** [junit-team/junit5#1603]
## Overview

I tired to disable a junit jupiter test on Solaris (5.10 and 5.11) using 

```
@DisabledOnOs(OS.SOLARIS)
```

but the test was still executed afterwards.

I had a quick look at the implementation and it looks like the solaris detection for Solaris seems to be the problem (org.junit.jupiter.api.condition.OS#determineCurrentOs).

'os.name' seems to return `SunOS`.

I can come up with a pr for this one later on today.

**Comment by sormuras** [comment]
Thanks for the report and the PR in advance.
