### ISSUE TITLE
assertEquals(expected, actual, delta) should allow a delta of zero

### ISSUE THREAD

**Issue by lessthanoptimal** [junit-team/junit5#1606]
## Overview

`assertEquals(expected, actual, delta)` currently throws an exception if a delta of zero is passed in. 

This is a change in behavior from JUnit 4 and an unnecessary restriction. I propose that the desired behavior should be to treat delta of zero as a test for equality.

In my projects a delta of zero occurs when the test tolerance is dynamically computed. The current work around is to add EPS to the dynamic tolerance. This bloats the code and the desired test is for equality, not _nearly_ equal.

## Proposal

Two simple modifications (once for float and double) are required.  Change the line `delta <= 0.0` to `delta < 0.0`.

```java
	static void assertValidDelta(float delta) {
		if (Float.isNaN(delta) || delta < 0.0) {
			failIllegalDelta(String.valueOf(delta));
		}
	}
```

That's it.

**Comment by marcphilipp** [comment]
I'd be fine with changing it.

@junit-team/junit-lambda WDYT?

**Comment by sormuras** [comment]
+1

**Comment by mateuszjarzyna** [comment]
I've tried to fix this issue

**Comment by sbrannen** [comment]
_in progress_ in #1613
