### ISSUE TITLE
Introduce support for assertNotEquals for primitive data types

### ISSUE THREAD

**Issue by lessthanoptimal** [junit-team/junit5#1607]
## Overview

There is currently support for `assertEquals( expected, actual )` and `assertEquals( expected, actual , delta )` for primitive types, e.g. `int`, `float`, `double`, but there is no support for `assertNotEquals( unexpected, actual , delta )`. The current `assertNotEquals()` function only works on `Object`. 

This is a change from JUnit 4 which had support for functions such as this. Auto-boxing technically adds support for `assertNotEquals( unexpected, actual )` to primitive types, but that could cause performance issues if testing a very large number of points.

## Deliverables

- [x] Introduce `assertNotEquals( expected, actual , delta )`  for floats and doubles
- [x] Introduce `assertNotEquals( unexpected, actual )` for <strike>`boolean`</strike>, `byte`, `char`, `short`, `int`, `float`, `double`

## Related Issues

- #269

**Comment by shirishp** [comment]
@marcphilipp Are you looking for PRs for this? I would like to work on this if that's okay.

**Comment by marcphilipp** [comment]
I want to discuss it with the rest of the team first. We'll meet later this week. I'll update this issue then. But I think it's very likely that we'll want to do it and will be looking for PRs.

**Comment by marcphilipp** [comment]
**Team Decision:** We'd like to add `assertNotEquals` for primitive data types.

@shirishp Do you have time to submit a PR?

**Comment by shirishp** [comment]
@marcphilipp Yes. I will work on this over weekend and submit a PR.

**Comment by marcphilipp** [comment]
Yes, that sounds good!

**Comment by shirishp** [comment]
@lessthanoptimal @marcphilipp There is no `assertEquals(boolean, boolean)`. Do we still want to implement `assertNotEquals(boolean, boolean)` for boolean?

IMHO, if we want to do it, it should be for both, equals and notEquals.

**Comment by lessthanoptimal** [comment]
@shirishp At first I was thinking that the boolean case isn't useful. However, right now if you wanted to see if two boolean variables are equals you do `assertTrue(a==b)` which doesn't read as well as `assertEquals(a,b)`. My vote would be to add `assertEquals(boolean, boolean)` and `assertNotEquals(boolean, boolean)`.

**Comment by shirishp** [comment]
@lessthanoptimal I am adding the `assertNotEquals(boolean, boolean)` in PR for this issue. I feel we should create a separate issue for adding `assertEquals(boolean, boolean)`. I can take that and submit PR.
@marcphilipp What do you think?

**Comment by shirishp** [comment]
@marcphilipp @lessthanoptimal Please review the PR here - https://github.com/junit-team/junit5/pull/1623

**Comment by sbrannen** [comment]
> @lessthanoptimal @marcphilipp There is no `assertEquals(boolean, boolean)`. Do we still want to implement `assertNotEquals(boolean, boolean)` for boolean?
> 
> IMHO, if we want to do it, it should be for both, equals and notEquals.

Please see my comments in PR #1623.

**Comment by sbrannen** [comment]
_in progress_ by @shirishp in #1623.

**Comment by sbrannen** [comment]
The PR for this issue has been merged into `master` in 0f62c6b261044009542620b6fc645217fe793ccb.
