### ISSUE TITLE
Can't exclude tags with Maven Surefire via command line options

### ISSUE THREAD

**Issue by hmartinh** [junit-team/junit5#1612]
I'm trying to exclude a tag from test execution with Java system props that are passed via the command line, but it's not working.

```java
public class A {

    @Test
    @Tag("NotThreadSafe")
    public void test(){
        System.out.println("NotThreadSafe");
    }

    @Test
    public void test2(){
        System.out.println("It's ok");
    }
}
```

`$: mvn clean test -Dtest="**/selftest/**" -DexcludeTags="NotThreadSafe"`

Output:

```
NotThreadSafe
It's ok
```

But `-Dgroups` propery works fine:

`$: mvn clean test -Dtest="**/cdp/autotests/selftest/**" -Dgroups="NotThreadSafe"`

Output:

```
NotThreadSafe
```

**Comment by sormuras** [comment]
Assuming you're using Surefire 2.22.0, you may exclude tags via `excludedGroups`.

For details see https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html

**Comment by hmartinh** [comment]
> Assuming you're using Surefire 2.22.0, you may exclude tags via `excludedGroups`.
> 
> For details see https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html

Yeah, but in this case i have to make two profiles with different exclude/include Tags :(

**Comment by sormuras** [comment]
That's how Maven/Surefire works. Perhaps StackOverflow is a better place to ask Surefire configuration/setup related questions. Their might be a solution to your task. :)

**Comment by sbrannen** [comment]
> Yeah, but in this case i have to make two profiles with different exclude/include Tags :(

Have you tried using a [tag expression](https://junit.org/junit5/docs/current/user-guide/#running-tests-tag-expressions) instead of just simple tags?

**Comment by sbrannen** [comment]
Closing this issue since the JUnit team no longer maintains the Maven Surefire provider.

**Comment by hmartinh** [comment]
> > Yeah, but in this case i have to make two profiles with different exclude/include Tags :(
> 
> Have you tried using a [tag expression](https://junit.org/junit5/docs/current/user-guide/#running-tests-tag-expressions) instead of just simple tags?
Yep, it's solution, thnx
mvn clean test -Dtest="**/cdp/autotests/selftest/**" -Dgroups=\!NotThreadSafe

**Comment by sbrannen** [comment]
You're welcome.

Glad that works for you!

And thanks for letting us know.

**Comment by Ghilteras** [comment]
I have the same issue and just specifying `-Dgroups` should work, according to the documentation, but it does not, not sure why you need to specify `-Dtest` here

**Comment by GuptaMegha** [comment]
I am having the same issue. I am using maven-surefire-plugin<3.0.0-M4>
 -Dgroups!=category
-DexcludeGroups=category
-DexcludeTags=category
none of the above is excluding tag category. Is there any solution?

**Comment by GuptaMegha** [comment]
Putting in single quotes works for me:
mvn clean test '-Dgroups=!category'
