### ISSUE TITLE
API for accessing outer test instances

### ISSUE THREAD

**Issue by britter** [junit-team/junit5#1618]
## Overview

- (x) **Feature request.** Provide an API to access outer test instance

Extensions that manage test instance fields often need access to the fields declared in outer test instances. Examples for this are the [MockitoExtension](https://github.com/mockito/mockito/blob/release/2.x/subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java) and the [Testcontainers extension](https://github.com/testcontainers/testcontainers-java/pull/887). The `ExtensionContext` currently does not provide access to the outer test instance:

```java
        Optional<ExtensionContext> current = context.getParent();

        while(current.isPresent()) {
            ExtensionContext ctx = current.get();
            Optional<Object> testInstance = ctx.getTestInstance()
            if (testInstance.isPresent()) { // will never be true
                // do something with testInstance
            }
            current = ctx.getParent();
        }
```

So currently extension authors have to fall back to putting test instances into the extension store and retrieve it from there. This should be more straight forward.

## Deliverables

- [ ] API for accessing outer test instances

**Comment by britter** [comment]
This API could also be hosted by the `TestObject` wrapper I described in #1611

**Comment by marcphilipp** [comment]
Here's a draft PR, please take a look and comment: #1650.
