### ISSUE TITLE
Document order of callback methods and extensions that run after test/container execution

### ISSUE THREAD

**Issue by apodkutin** [junit-team/junit5#1620]
Based on [JUnit5 user-guide](https://junit.org/junit5/docs/current/user-guide/#extensions) extensions execution order should correlate with extensions declaration order:

> Extensions registered declaratively via @ExtendWith will be executed in the order in which they are declared in the source code. For example, the execution of tests in both MyFirstTests and MySecondTests will be extended by the FooExtension and BarExtension, in exactly that order.

But it does not. 

Example: https://github.com/apodkutin/junit5-extensions-order-test/blob/master/src/test/java/junit5/extensions/order/JUnit5ExtensionsOrderTest.java

`@ExtendWith({FirstExtension.class, SecondExtension.class})`

### Expected output
_FirstExtension afterEach method call_
_SecondExtension afterEach method call_

### Actual output
_SecondExtension afterEach method call_
_FirstExtension afterEach method call_

Jupiter-api version is 5.3.1

```
<groupId>org.junit.jupiter</groupId>
<artifactId>junit-jupiter-api</artifactId>
<version>5.3.1</version>
```

## Deliverables

- Document the **lack** of explicit ordering for all user-supplied callback methods (i.e., `@BeforeEach`, `@AfterEach`, `@BeforeAll`, `@AfterAll`) declared within a single test class/interface.
   - [x] in Javadoc
   - [x] in User Guide

- Document the **lack** of _wrapping_ behavior for all user-supplied callback methods (e.g., `@AfterAll`, `@AfterEach`) declared within a single test class/interface.
   - [x] in Javadoc
   - [x] in User Guide

- Document _wrapping_ behavior for all user-supplied callback methods (i.e., `@BeforeEach`, `@AfterEach`, `@BeforeAll`, `@AfterAll`) within test class/interface hierarchies.
   - [x] in Javadoc
   - [x] in User Guide

- Document _wrapping_ behavior for all applicable extension APIs (e.g., `TestExecutionExceptionHandler`, `AfterTestExecutionCallback`, `AfterEachCallback`, `AfterAllCallback`, etc.).
   - [ ] in Javadoc
   - [x] in User Guide

**Comment by apodkutin** [comment]
Thank for your comment @smoyer64, but I can't agree with you, because you're showing the diagram which is related to user-provided test and lifecycle methods and it looks like expected behavior for me as well. 

But when I'm extending some test class with extension, and I'm declaring them in a specific order, I'm expecting that they will be invoked in the same order, I mean `beforeEach` from the first extension and after that `beforeEach` from the second extension. And I'm expecting that the same behavior should be for `afterEach` method based only on this statement from the guide "will be executed in the order in which they are declared in the source code."

I understand that for more than one extension order, execution order logic will be the same as for user-provided test and lifecycle methods execution order logic. But, do you think, that this statement is correct "will be executed in the order in which they are declared in the source code."? Maybe it should be changed to avoid misleading or maybe I've understood it wrong.

**Comment by marcphilipp** [comment]
@apodkutin Thanks for reporting this issue! @smoyer64 described our intention correctly: Extensions that run after a test are run in reverse order. However, as you noticed that's missing from the documentation and we should add it there.

**Comment by sbrannen** [comment]
Please note that the _wrapping_ behavior for "after" extensions applies to callback methods as well (e.g., `@AfterEach`, `@AfterAll`).

I've updated the title of this issue accordingly.

**Comment by sbrannen** [comment]
I've added a _Deliverables_ section as well.

**Comment by apodkutin** [comment]
@smoyer64 , @marcphilipp @sbrannen, thank you guys for the quick answers!
I'm really appreciate that you will add this information to the JavaDoc and to the user-guide as well.

But I still have only one question, do you think that this behavior and I'm talking only about callback methods from extensions **should be like this**? I have one example when I've faced it and why I actually raised this ticket.

Example:

We have `EnvVariablesExtension` which is changing environment variables in the `beforeEach` callback method and restoring them to original ones in the `afterEach` callback method.
I've tried to test `EnvVariablesExtension` with the second extension. Let's name it `AcceptanceExtension`  and, of course, this extension is saving original environment variables in the `beforeEach` callback and asserting that environment variables which was fetched in `afterEach` callback method equals original environment variables. 

Order of the extensions is 

1. `AcceptanceExtension` 
2. `EnvVariablesExtension`

As you already understood, `beforeEach` part works fine, but the second one `afterEach` part does not work, because `AcceptanceExtension` is called first and assertion failed. 

My question is, why you've chosen this approach for execution order of callback extension's methods?
Why not just calling every callback extension's methods in that order which you've provided in the `@ExtendWith({AcceptanceExtension.class, EnvVariablesExtension.class})` annotation?
```
AcceptanceExtension.beforeEach -> 
EnvVariablesExtension.beforeEach -> 
Test's body -> 
AcceptanceExtension.beforeEach -> 
EnvVariablesExtension.beforeEach
```
Thank you in advance.

**Comment by smoyer64** [comment]
I've never had a situation where I _didn't_ want to invert the test setup when performing the tear-down.  In my mind, the phrase

> Let's name it AcceptanceExtension and, of course, this extension is saving original environment     variables in the beforeEach callback and asserting that environment variables which was fetched in afterEach callback method equals original environment variables.

immediately raised red-flags.  In my opinion, you really shouldn't be making assertions outside of test methods.  In the case where I've written tests for an extension that implements both a ``beforeXxx()`` and ``afterXxx()`` extension point, I've individually tested that the ``beforeXxx()`` method functions as expected and that the ``afterXxx()`` method works as expected and then trusted that JUnit 5 will execute them at the appropriate times in the test lifecycle.

**Comment by sormuras** [comment]
Output generated...
```text
ExtensionAlpha.beforeEach()
ExtensionOmega.beforeEach()
  @BeforeEach TestClass.setUpA()
  @BeforeEach TestClass.setUpB()
--> TestClass.test()
  @AfterEach TestClass.tearDownA()
  @AfterEach TestClass.tearDownB()
ExtensionOmega.afterEach()
ExtensionAlpha.afterEach()
```

Generated by executing:
```java
class WrappingCallbacksAndExtensionsDemo {

	@Nested
	@ExtendWith({ ExtensionAlpha.class, ExtensionOmega.class})
	class TestClass {

		@BeforeEach
		void setUpA() {
			System.out.println("  @BeforeEach " + getClass().getSimpleName() + ".setUpA()");
		}

		@AfterEach
		void tearDownA() {
			System.out.println("  @AfterEach " + getClass().getSimpleName() + ".tearDownA()");
		}

		@BeforeEach
		void setUpB() {
			System.out.println("  @BeforeEach " + getClass().getSimpleName() + ".setUpB()");
		}

		@AfterEach
		void tearDownB() {
			System.out.println("  @AfterEach " + getClass().getSimpleName() + ".tearDownB()");
		}

		@Test
		void test() {
			System.out.println("--> " + getClass().getSimpleName() + ".test()");
		}
	}

	static class ExtensionAlpha implements BeforeEachCallback, AfterEachCallback {

		public void beforeEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".beforeEach()");
		}

		public void afterEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".afterEach()");
		}
	}

	static class ExtensionOmega implements BeforeEachCallback, AfterEachCallback {

		public void beforeEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".beforeEach()");
		}

		public void afterEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".afterEach()");
		}
	}

}
```
Before I start creating a diagram, is this what we want to document? Anything missing?

**Comment by sbrannen** [comment]
> I think we should add a super class with lifecycle callbacks.

I agree.

**Comment by sbrannen** [comment]
> ```
> ExtensionAlpha.beforeEach()
> ExtensionOmega.beforeEach()
>   @BeforeEach TestClass.setUpA()
>   @BeforeEach TestClass.setUpB()
> --> TestClass.test()
>   @AfterEach TestClass.tearDownA()
>   @AfterEach TestClass.tearDownB()
> ExtensionOmega.afterEach()
> ExtensionAlpha.afterEach()
> ```

If that's the actual output, then that demonstrates that we have a 🐛  in the support for user-supplied lifecycle callbacks.

`TestClass.tearDownB()` **must** be called before `TestClass.tearDownA()`.

**Comment by sbrannen** [comment]
We do actually have proper wrapping support for user-supplied lifecycle callbacks within class hierarchies.

For example, the following...

```java
	@ExtendWith({ ExtensionAlpha.class, ExtensionOmega.class })
	static class TestClassA {

		@BeforeEach
		void setUpA() {
			System.out.println("  @BeforeEach " + getClass().getSimpleName() + ".setUpA()");
		}

		@AfterEach
		void tearDownA() {
			System.out.println("  @AfterEach " + getClass().getSimpleName() + ".tearDownA()");
		}
	}

	static class TestClassB extends TestClassA {

		@BeforeEach
		void setUpB() {
			System.out.println("  @BeforeEach " + getClass().getSimpleName() + ".setUpB()");
		}

		@AfterEach
		void tearDownB() {
			System.out.println("  @AfterEach " + getClass().getSimpleName() + ".tearDownB()");
		}

		@Test
		void testB() {
			System.out.println("--> " + getClass().getSimpleName() + ".testB()");
		}
	}
```

... results in the following output:

```
ExtensionAlpha.beforeEach()
ExtensionOmega.beforeEach()
  @BeforeEach TestClassB.setUpA()
  @BeforeEach TestClassB.setUpB()
--> TestClassB.testB()
  @AfterEach TestClassB.tearDownB()
  @AfterEach TestClassB.tearDownA()
ExtensionOmega.afterEach()
ExtensionAlpha.afterEach()
```

**Comment by sbrannen** [comment]
Or maybe it's better to just omit the simple class name. 🤔

**Comment by sbrannen** [comment]
Or.... we could _fix_ this.

For example, given the following...

```java
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;

class WrappingCallbacksAndExtensionsDemo {

	@ExtendWith({ Extension1.class, Extension2.class })
	static class TestClassA {

		private final String className = TestClassA.class.getSimpleName();

		@BeforeEach
		void setUpA1(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpA1()");
		}

		@AfterEach
		void tearDownA1() {
			System.out.println("  @AfterEach " + className + ".tearDownA1()");
		}

		@BeforeEach
		void setUpA2(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpA2()");
		}

		@AfterEach
		void tearDownA2() {
			System.out.println("  @AfterEach " + className + ".tearDownA2()");
		}

	}

	static class TestClassB extends TestClassA {

		private final String className = TestClassB.class.getSimpleName();

		@BeforeEach
		void setUpB1(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpB1()");
		}

		@AfterEach
		void tearDownB1() {
			System.out.println("  @AfterEach " + className + ".tearDownB1()");
		}

		@BeforeEach
		void setUpB2(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpB2()");
		}

		@AfterEach
		void tearDownB2() {
			System.out.println("  @AfterEach " + className + ".tearDownB2()");
		}

		@BeforeEach
		void setUpB3(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpB3()");
		}

		@AfterEach
		void tearDownB3() {
			System.out.println("  @AfterEach " + className + ".tearDownB3()");
		}

		@Test
		void testB() {
			System.out.println("--> " + className + ".testB()");
		}

	}

	static class TestClassC extends TestClassB {

		private final String className = TestClassC.class.getSimpleName();

		@BeforeEach
		void setUpC1(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpC1()");
		}

		@AfterEach
		void tearDownC1() {
			System.out.println("  @AfterEach " + className + ".tearDownC1()");
		}

		@BeforeEach
		void setUpC2(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpC2()");
		}

		@AfterEach
		void tearDownC2() {
			System.out.println("  @AfterEach " + className + ".tearDownC2()");
		}

		@BeforeEach
		void setUpC3(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpC3()");
		}

		@AfterEach
		void tearDownC3() {
			System.out.println("  @AfterEach " + className + ".tearDownC3()");
		}

	}

	static class Extension1 implements BeforeEachCallback, AfterEachCallback {

		@Override
		public void beforeEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".beforeEach()");
		}

		@Override
		public void afterEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".afterEach()");
		}
	}

	static class Extension2 implements BeforeEachCallback, AfterEachCallback {

		@Override
		public void beforeEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".beforeEach()");
		}

		@Override
		public void afterEach(ExtensionContext context) {
			System.out.println(getClass().getSimpleName() + ".afterEach()");
		}
	}

}
```

... with a minor change I've made to `org.junit.jupiter.engine.descriptor.ClassTestDescriptor.registerAfterEachMethodAdapters(ExtensionRegistry)` locally on my machine, I now get the following output when executing the above `TestClassC` test class:

```
Extension1.beforeEach()
Extension2.beforeEach()
  @BeforeEach TestClassA.setUpA1()
  @BeforeEach TestClassA.setUpA2()
  @BeforeEach TestClassB.setUpB1()
  @BeforeEach TestClassB.setUpB2()
  @BeforeEach TestClassB.setUpB3()
  @BeforeEach TestClassC.setUpC1()
  @BeforeEach TestClassC.setUpC2()
  @BeforeEach TestClassC.setUpC3()
--> TestClassB.testB()
  @AfterEach TestClassC.tearDownC3()
  @AfterEach TestClassC.tearDownC2()
  @AfterEach TestClassC.tearDownC1()
  @AfterEach TestClassB.tearDownB3()
  @AfterEach TestClassB.tearDownB2()
  @AfterEach TestClassB.tearDownB1()
  @AfterEach TestClassA.tearDownA2()
  @AfterEach TestClassA.tearDownA1()
Extension2.afterEach()
Extension1.afterEach()
```

@junit-team/junit-lambda, Thoughts?

**Comment by sbrannen** [comment]
My local fix works with interface default methods as well.

Declaring:

```java
class TestClassC extends TestClassB implements TestInterfaceX {
    // ...
}
```

... with the following test interface

```java
interface TestInterfaceX {

	String className = TestInterfaceX.class.getSimpleName();

	@BeforeEach
	default void setUpX1(TestInfo testInfo) {
		System.out.println("  @BeforeEach " + className + ".setUpX1()");
	}

	@AfterEach
	default void tearDownX1() {
		System.out.println("  @AfterEach " + className + ".tearDownX1()");
	}

	@BeforeEach
	default void setUpX2(TestInfo testInfo) {
		System.out.println("  @BeforeEach " + className + ".setUpX2()");
	}

	@AfterEach
	default void tearDownX2() {
		System.out.println("  @AfterEach " + className + ".tearDownC2()");
	}

}
```

... yields the following output:

```
Extension1.beforeEach()
Extension2.beforeEach()
  @BeforeEach TestClassA.setUpA1()
  @BeforeEach TestClassA.setUpA2()
  @BeforeEach TestClassB.setUpB1()
  @BeforeEach TestClassB.setUpB2()
  @BeforeEach TestClassB.setUpB3()
  @BeforeEach TestInterfaceX.setUpX1()
  @BeforeEach TestInterfaceX.setUpX2()
  @BeforeEach TestClassC.setUpC1()
  @BeforeEach TestClassC.setUpC2()
  @BeforeEach TestClassC.setUpC3()
--> TestClassB.testB()
  @AfterEach TestClassC.tearDownC3()
  @AfterEach TestClassC.tearDownC2()
  @AfterEach TestClassC.tearDownC1()
  @AfterEach TestInterfaceX.tearDownC2()
  @AfterEach TestInterfaceX.tearDownX1()
  @AfterEach TestClassB.tearDownB3()
  @AfterEach TestClassB.tearDownB2()
  @AfterEach TestClassB.tearDownB1()
  @AfterEach TestClassA.tearDownA2()
  @AfterEach TestClassA.tearDownA1()
Extension2.afterEach()
Extension1.afterEach()
```

**Comment by sbrannen** [comment]
Of course, truth be told: there is no real, physical correlation between methods such as `setUpA1()` and `tearDownA1()`.

Specifically, they are only related by a naming convention, and the order in which lifecycle methods are invoked is not controlled explicitly by the author of the test class.

So, one could argue that the status quo is fine: JUnit Jupiter does not guarantee any order or wrapping semantics for user-supplied lifecycle methods within a single test class/interface.

On the other hand, some users might expect that wrapping occurs for methods named like those in the examples here.

One final point: it may be best to hold off on wrapping behavior for user-supplied lifecycle methods within a single test class/interface until JUnit Jupiter supports explicit ordering of such methods (e.g., via `@Order`) -- if such support is ever introduced.

**Comment by sbrannen** [comment]
Example in favor of my "final point" above:

```java
	@ExtendWith({ Extension1.class, Extension2.class })
	static class TestClassZ {

		private final String className = TestClassB.class.getSimpleName();

		@BeforeEach
		void startDatabase(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".startDatabase()");
		}

		@AfterEach
		void closeDatabase() {
			System.out.println("  @AfterEach " + className + ".closeDatabase()");
		}

		@BeforeEach
		void setUpZ2(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpZ2()");
		}

		@AfterEach
		void tearDownZ2() {
			System.out.println("  @AfterEach " + className + ".tearDownZ2()");
		}

		@BeforeEach
		void setUpZ3(TestInfo testInfo) {
			System.out.println("  @BeforeEach " + className + ".setUpZ3()");
		}

		@AfterEach
		void tearDownZ3() {
			System.out.println("  @AfterEach " + className + ".tearDownZ3()");
		}

		@Test
		void testZ() {
			System.out.println("--> " + className + ".testZ()");
		}

	}
```

Executing `TestClassZ` with the "wrapping fix results in:

```
Extension1.beforeEach()
Extension2.beforeEach()
  @BeforeEach TestClassB.startDatabase()
  @BeforeEach TestClassB.setUpZ2()
  @BeforeEach TestClassB.setUpZ3()
--> TestClassB.testZ()
  @AfterEach TestClassB.closeDatabase()
  @AfterEach TestClassB.tearDownZ3()
  @AfterEach TestClassB.tearDownZ2()
Extension2.afterEach()
Extension1.afterEach()
```

And that demonstrates that there is in fact zero correlation between methods like `startDatabase()` and `closeDatabase()`.

Long story, short: let's just document the status quo for execution order for user-supplied lifecycle methods. 😉

**Comment by sbrannen** [comment]
I'm pasting the "fix" I experimented with locally here for future reference in case it proves useful.

Change in `ClassTestDescriptor`:

```java
/**
 * {@link Comparator} that reverses the order of methods declared within the
 * same class.
 */
Comparator<Method> lifecycleMethodComparator = (Method m1, Method m2) -> {
	Class<?> class1 = m1.getDeclaringClass();
	Class<?> class2 = m2.getDeclaringClass();

	if (class1.equals(class2)) {
		return -1;
	}

	return 0;
};

private void registerAfterEachMethodAdapters(ExtensionRegistry registry) {
	// Make a local copy since findAfterEachMethods() returns an immutable list.
	List<Method> afterEachMethods = new ArrayList<>(findAfterEachMethods(this.testClass));

	// Since the bottom-up ordering of afterEachMethods will later be reversed when the
	// synthesized AfterEachMethodAdapters are executed within TestMethodTestDescriptor,
	// we have to reverse the afterEachMethods list to put them in top-down order before
	// we register them as synthesized extensions.
	Collections.reverse(afterEachMethods);

	// Reverse the order of @AfterEach methods declared within the same class/interface.
	afterEachMethods.sort(lifecycleMethodComparator);

	registerMethodsAsExtensions(afterEachMethods, registry, this::synthesizeAfterEachMethodAdapter);
}
```

**Comment by sbrannen** [comment]
**Update**: _Deliverables_ have been overhauled to reflect the current scope.

**Comment by sbrannen** [comment]
Examples introduced in 591e5c00ee4512d60c7a99ba07ad7b1d7918faff demonstrate proper and improper lifecycle method configuration.

Note, however, that that commit only contains the code: it doesn't update the User Guide or Javadoc.

**Comment by sbrannen** [comment]
Executing `BrokenLifecycleMethodConfigDemo` results in:

```
Extension1.beforeEach()
Extension2.beforeEach()
  @BeforeEach BrokenLifecycleMethodConfigDemo.insertTestDataIntoDatabase()
  @BeforeEach BrokenLifecycleMethodConfigDemo.connectToDatabase()
    @Test BrokenLifecycleMethodConfigDemo.testDatabaseFunctionality()
  @AfterEach BrokenLifecycleMethodConfigDemo.disconnectFromDatabase()
  @AfterEach BrokenLifecycleMethodConfigDemo.deleteTestDataInDatabase()
Extension2.afterEach()
Extension1.afterEach()
```

**Comment by sbrannen** [comment]
Executing `DatabaseTestsDemo` results in:

```
Extension1.beforeEach()
Extension2.beforeEach()
  @BeforeEach AbstractDatabaseTests.connectToDatabase()
  @BeforeEach DatabaseTestsDemo.insertTestDataIntoDatabase()
    @Test DatabaseTestsDemo.testDatabaseFunctionality()
  @AfterEach DatabaseTestsDemo.deleteTestDataInDatabase()
  @AfterEach AbstractDatabaseTests.disconnectFromDatabase()
Extension2.afterEach()
Extension1.afterEach()
```

**Comment by sbrannen** [comment]
@sormuras and @marcphilipp, with regard to the undesirable behavior in `BrokenLifecycleMethodConfigDemo`, I suggest we state in the document something along the lines of the following.

> Due to the aforementioned behavior, the JUnit Team recommends that developers declare at most one of each type of lifecycle method (i.e., `@BeforeAll`, `@AfterAll`, `@BeforeEach`, `@AfterEach`) per test class or test interface.
