### ISSUE TITLE
Document Test Kit API

### ISSUE THREAD

**Issue by dotCipher** [junit-team/junit5#1621]
## Overview

Based on the significant change in formalizing and exposing the new `junit-platform-testkit` module, the User Guide should include documentation for the first version of its usage.

## Related Issues

- #1356 
- #1392
- #1662 
- #1663 

## Deliverables

- [x] Write Javadoc for methods in `EventConditions` and `TestExecutionResultConditions`.
- [x] Document `junit-platform-testkit` in the Release Notes.
- [x] Document `junit-platform-testkit` in the User Guide.
  - [x] Include in [Dependency Metadata](https://junit.org/junit5/docs/current/user-guide/#dependency-metadata).
  - [x] Include in [Dependency Diagram](https://junit.org/junit5/docs/current/user-guide/#dependency-diagram).
  - [x] Introduce new _JUnit Platform Test Kit_ chapter including high level overview and usage with common use cases as examples.

**Comment by dotCipher** [comment]
Fair, let me know when I should pull the trigger on it then.  Thanks!

**Comment by sbrannen** [comment]
This issue is currently **blocked** until #1662 is completed.

**Comment by sbrannen** [comment]
> This issue is currently **blocked** until #1662 is completed.

#1662 is now complete.

**Comment by sbrannen** [comment]
Please note that I've already taken care of the Javadoc except for methods in `ExecutionEventConditions` and `TestExecutionResultConditions`.

**Comment by sbrannen** [comment]
> Please hold off on starting with the documentation. I want to take a closer look and possibly rename a few things here and there first.

@marcphilipp, are you still planning on that in light of the work I did in #1662?

**Comment by marcphilipp** [comment]
Nope, I think we‘re good now thanks to your work. 👍

**Comment by sbrannen** [comment]
> Nope, I think we‘re good now thanks to your work. 👍

OK... but now this issue is **blocked** until #1663 is complete. 😉

**Comment by sbrannen** [comment]
This issue is no longer **blocked** since #1663 has been resolved.

**Comment by dotCipher** [comment]
Sorry I was traveling and just saw this.  Can I still take point on it now?

**Comment by sbrannen** [comment]
> I do plan to make some improvements to the `EngineTestKit` API (i.e., I plan to make building of the request _fluent_ as well), but that won't affect the overall work you'll be documenting. Rather, it will only incur minor changes to a few examples likely.

FYI: that work has been pushed to `master` in 252c9da377e8f5f5c10a610e09cb3f08cfe8e24a.

**Comment by sormuras** [comment]
Updated deliverables: included Test Kit in Dependency Metadata and Diagram

**Comment by sbrannen** [comment]
**Update**: ✅ Document `junit-platform-testkit` in the Release Notes.

**Comment by dotCipher** [comment]
Apologies on letting this slide, I appreciate your help with it.  Thank you!

**Comment by sbrannen** [comment]
> Apologies on letting this slide, I appreciate your help with it. 

No worries.

> Thank you!

👍

**Comment by sbrannen** [comment]
In case anyone is interested in seeing the status quo in the User Guide, have a look here:

https://junit.org/junit5/docs/snapshot/user-guide/#testkit

**Comment by sbrannen** [comment]
**Update**: documentation in the User Guide is complete for 5.4 M1.

**Comment by sormuras** [comment]
:+1: 👍
