### ISSUE TITLE
@CsvSource - allow collections as parameters

### ISSUE THREAD

**Issue by llowrey** [junit-team/junit5#1622]
Feature Request for `@CsvSource`:

I often need to verify that the output of a method is a list or set of values.  Right now I end up passing the list as a single string with a different delimiter and then splitting it in the test method. It would be more convenient to be able to do something like:

```java
@ParameterizedTest
@CsvSource({
"foo, bar, [ABC, DEF]",
"one, two, []",
})
public void testMethod(String param1, String param2, Set<SomeEnum> expectedResult) {
    Set<SomeEnum> actualResult = someMethod(param1, param2);
    assertThat(actualResult, is(expectedResult));
}
```

**Comment by sbrannen** [comment]
Hi @llowrey,

I see a few problems with the proposal.

1. Brackets are valid syntax in CSV.
2. CSV has no notion of collections or sets within an input line.
3. I imagine that this is a bit of a corner case that most users will not face.

**Comment by sbrannen** [comment]
Also, have you considered making use of the `Arguments` or `ArgumentsAggregator` APIs?

They might simplify your implementation.

**Comment by llowrey** [comment]
Thank you for the feedback.  I can see that my suggestion is not compatible with CsvSource. I ended up creating an annotation for this so my problem is solved. This ticket can be closed.

**Comment by sbrannen** [comment]
> Thank you for the feedback. I can see that my suggestion is not compatible with CsvSource. I ended up creating an annotation for this so my problem is solved. This ticket can be closed.

OK. I just closed this issue.

Thanks for letting us know.

But... out of curiosity, would you mind sharing with us what kind of annotation you created for your solution?

**Comment by llowrey** [comment]
I created a version of CsvSource that implements the feature I had requested. Since the syntax is similar but different it made sense for it to be a different annotation. Taking the ArgumentsSource route seemed to be the lowest friction option.

**Comment by sbrannen** [comment]
> I created a version of CsvSource that implements the feature I had requested. Since the syntax is similar but different it made sense for it to be a different annotation. Taking the ArgumentsSource route seemed to be the lowest friction option.

Thanks for the feedback.
