### ISSUE TITLE
Support hexadecimal values in arguments converters

### ISSUE THREAD

**Issue by dmitry-timofeev** [junit-team/junit5#1624]
## Overview

It’s a feature request: support converting argument strings containing integral literals in hexadecimal to the corresponding types on top of decimal.

### Description
Currently one cannot use hexadecimal integral values when specifying arguments, e.g., this won't work:
```java
@CsvSource({
    "1",
    "0x1", // Won't be converted
}) // CSV source for illustrative purposes: ValueSource would suite here better
@ParameterizedTest
void test(int v) {
```

The cases when one needs to use hex include copying values in hex from some specification; when binary representation (i.e., which bit in the value is set) matters.

### Workaround 
Use String as argument type and convert yourself with, e.g., Integer::decode.

## Deliverables

- [ ] ...

**Comment by dmitry-timofeev** [comment]
BTW, [`Float.valueOf`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Float.html#valueOf\(java.lang.String\)), in contrast to Integer.valueOf, supports hex literals.

**Comment by sbrannen** [comment]
_in progress_ in #1625

**Comment by sbrannen** [comment]
Tentatively slated for inclusion in 5.4

**Comment by dmitry-timofeev** [comment]
Do you think JUnit shall also support converting unsigned _bytes_, e.g.,
`"0xFF"` → `(byte) 0xFF`? I'd consider it useful to be able to specify any byte value as unsigned hex — as it clearly expresses the values of individual bits.

**Comment by marcphilipp** [comment]
@dmitry-timofeev I think we should stick with the `Byte.decode()` semantics. You could implement your own converter and register it via `@ConvertWith`.

**Comment by dmitry-timofeev** [comment]
Thanks, that makes sense, such special case, although useful for some users, might be confusing to others!
