### ISSUE TITLE
How I can run code After all tests in Parallel? 

### ISSUE THREAD

**Issue by romsper** [junit-team/junit5#1627]
## Overview

I try to run my tests in parallel via Maven **forkCount-${threadCount}** and **reuseForks-false** but unsuccessfully.

- ( ) **Bug report.** Currently, when I use **TestExecutionListener** his method **testPlanExecutionStarted** exeute after each class. I found a little information about this problem, but I can't find the solve. 

- ( ) **Feature request.** I tried to use **Runtime.getRuntime().addShutdownHook** but it works like **testPlanExecutionStarted** - after each test class. 

`object ShutDownHook {
    @JvmStatic
    fun main(args: Array<String>) {
        Runtime.getRuntime().addShutdownHook(object : Thread() {
            override fun run() {
                println("Shutdown Hook is running !")
            }
        })
        println("Application Terminating ...")
    }
}`

Also I tried to use **Launcher**  and it was successfully! 
But it is really uncomfortable method! I can't see tests result and always run my tests via this construction is bad idea

`object Main {
    @JvmStatic
    fun main(args: Array<String>) {
        val launcherConfig = LauncherConfig.builder()
                .enableTestExecutionListenerAutoRegistration(false)
                .addTestExecutionListeners(TestListener())
                .build()
        val launcher = LauncherFactory.create(launcherConfig)
        val request = LauncherDiscoveryRequestBuilder.request()
                .selectors(selectPackage("test.users"))
                .configurationParameter("junit.jupiter.execution.parallel.enabled", "true")
                .filters(TagFilter.includeTags("regress"))
                .build()
        launcher.execute(request)
    }
}`

- ( ) **Question.** Please tell me, how I can run my code after all tests which run in parallel. Maybe JUnit has a some annotation like **@AfterAllTests**... I don't understand, why **TestNG** can do it but JUnit can't...

**Comment by marcphilipp** [comment]
This is really a Maven Surefire issue, so please open an issue on their issue tracker. In the meantime, you're welcome to try [JUnit's mechanisms to run tests in parallel](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution).

**Comment by romsper** [comment]
The solution:
**JUnit** - **TestExecutionListener** with **testPlanExecutionStarted**
and **Maven** 

> <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire.version}</version>
                <configuration>
                    <threadCount>${THREAD_COUNT}</threadCount>
                    <trimStackTrace>true</trimStackTrace>
                    <properties>
                        <includeTags>${includeTags}</includeTags>
                        <excludeTags>${excludeTags}</excludeTags>
                    </properties>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                    <systemProperties>
                        <property>
                            <name>junit.jupiter.extensions.autodetection.enabled</name>
                            <value>true</value>
                        </property>
                        <property>
                            <name>junit.jupiter.execution.parallel.enabled</name>
                            <value>true</value>
                        </property>
                        <property>
                            <name>allure.results.directory</name>
                            <value>${project.build.directory}/allure-results</value>
                        </property>
                    </systemProperties>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>${junit.platform.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.junit.jupiter</groupId>
                        <artifactId>junit-jupiter-engine</artifactId>
                        <version>${junit.jupiter.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
