### ISSUE TITLE
How to use internal custom TestEngine implementations in Maven-Surefire-Plugin?

### ISSUE THREAD

**Issue by performrumpf** [junit-team/junit5#1632]
For developing custom TestEngine classes there already is a lot of documentation on how to use them:

- ServiceLoader and plugin system
- LauncherConfig

Well, I tried to use a custom TestEngine with ServiceLoader (intern), it works fine in IntelliJ or using a Launcher, but I didn't get anything while running **mvn test**.

In Maven Surefire documentation it's mentioned that you only need to add JUnit-Jupiter-Engine in dependencies without the help of an provider. But these engines are external. What about internal engines?

**Comment by sormuras** [comment]
> But these engines are external. What about internal engines?

What are _external_ and _internal_ engines?

Do you have a `pom.xml` snippet to share?

**Comment by sormuras** [comment]
Here is an integration test showing how to include three engines in a `pom.xml`:

https://github.com/apache/maven-surefire/blob/19006aa70f36705f399b8c105a16f636904f00f3/surefire-its/src/test/resources/junit-platform-multiple-engines/pom.xml#L36-L71

**Comment by performrumpf** [comment]
```
    <properties>
        <java.version>1.8</java.version>
        <junit.platform.version>1.3.1</junit.platform.version>
    </properties>

    <build>
        <directory>target</directory>
        <outputDirectory>target/classes</outputDirectory>
        <testOutputDirectory>target/test-classes</testOutputDirectory>
        <sourceDirectory>src/main/java</sourceDirectory>
        <testSourceDirectory>src/test/java</testSourceDirectory>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
            </testResource>
        </testResources>

        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>${junit.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>${junit.platform.version}</version>
        </dependency>
    </dependencies>
```

Project structure
- src
  - main
     - java
     - resources
  - test
     - java
       - com.experiment.engine
         - MyTestEngine.java
         - MyTestDescription.java
     - resources
       - META-INF
         - services
           - org.junit.platform.engine.TestEngine

**Comment by performrumpf** [comment]
I overwrote discover and execute methods in a way that engineExecutionListener fires "start" and "finish" for the root and one child

**Comment by sormuras** [comment]
> I overwrote discover and execute methods in a way that engineExecutionListener fires "start" and "finish" for the root and one child

Are you extending `JupiterTestEngine`? Or extending some class in `junit-platform-launcher`?

**Comment by performrumpf** [comment]
I don't extend from JupiterTestEngine as that test engine will build tests from other resources (i.e. XML files). I use launcher only to see if LauncherConfig works or (for the future) if DiscoverySelectors work properly.

```
public class MyTestEngine implements TestEngine {
   // implemented methods
}
```

**Comment by sormuras** [comment]
Can you please move your `com.experiment.engine` with its `org.junit.platform.engine.TestEngine` into the `main` source set and see if Surefire now sees your engine?

**Comment by sormuras** [comment]
What is listed in Surefire's `class-path`s when you invoke your build with `mvn --debug ...`?

**Comment by performrumpf** [comment]
unfortunately moving it to main didn't help. Also I couldn't find any useful information in debug mode about class path. The only line i could find with class path was `<classpathDependencyExcludes>${maven.test.dependency.excludes}</classpathDependencyExcludes>
`
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.experimental:junit5-sandbox >-------------------
[INFO] Building junit5-sandbox 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ junit5-sandbox ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ junit5-sandbox ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ junit5-sandbox ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 34 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ junit5-sandbox ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\Users\c.rumpf\Documents\perform\junit5sandbox\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ junit5-sandbox ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.773 s
[INFO] Finished at: 2018-10-12T11:10:58+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by sbrannen** [comment]
What happens if you move `META-INF/services/org.junit.platform.engine.TestEngine` to `src/main/resources` as well?

**Comment by sormuras** [comment]
Below those configurations there should be line like `[DEBUG] -- end configuration --` and then the interesting lines start. Look for lines starting with `[DEBUG] test(compact) classpath:` and `[DEBUG] provider(compact) classpath:`.

**Comment by performrumpf** [comment]
At "maven-compiler-plugin":
```
[DEBUG] Classpath:
[DEBUG]  C:\Users\c.rumpf\Documents\perform\junit5sandbox\target\test-classes
[DEBUG]  C:\Users\c.rumpf\Documents\perform\junit5sandbox\target\classes
[DEBUG]  C:\Users\c.rumpf\.m2\repository\org\junit\platform\junit-platform-engine\1.3.1\junit-platform-engine-1.3.1.jar
[DEBUG]  C:\Users\c.rumpf\.m2\repository\org\apiguardian\apiguardian-api\1.0.0\apiguardian-api-1.0.0.jar
[DEBUG]  C:\Users\c.rumpf\.m2\repository\org\junit\platform\junit-platform-commons\1.3.1\junit-platform-commons-1.3.1.jar
[DEBUG]  C:\Users\c.rumpf\.m2\repository\org\opentest4j\opentest4j\1.1.1\opentest4j-1.1.1.jar
[DEBUG]  C:\Users\c.rumpf\.m2\repository\org\junit\platform\junit-platform-launcher\1.3.1\junit-platform-launcher-1.3.1.jar
```
Surefire didn't display any classpath informations

**Comment by sormuras** [comment]
Does `C:\Users\c.rumpf\Documents\perform\junit5sandbox\target\test-classes` contain the `MyEngine.class` AND the `META-INF/services/org.junit.platform.engine.TestEngine` file?

> Surefire didn't display any classpath informations

Strange...

**Comment by performrumpf** [comment]
> Does C:\Users\c.rumpf\Documents\perform\junit5sandbox\target\test-classes contain the MyEngine.class AND the META-INF/services/org.junit.platform.engine.TestEngine file?

When they are under `src/test/...`, then yes. Otherwise they are in `target\classes`

**Comment by sormuras** [comment]
Some more suggestions:

- Add `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>` to your `<properties>`
- Update the `maven-compiler-plugin` to `3.8.0`
- Help Surefire to select its `surefire-junit-platform` provider

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit-platform</artifactId>
                        <version>2.22.1</version>
                    </dependency>
                </dependencies>
            </plugin>
```

For details see https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html

Got it working with the [`ice.cream`](https://github.com/junit-team/junit5-samples/tree/master/junit5-modular-world/src/main/ice.cream/ice/cream) engine -- without any `src/main` directory.

![image](https://user-images.githubusercontent.com/2319838/46884607-ba6c4580-ce55-11e8-94a7-d57b1f70d521.png)

**Comment by performrumpf** [comment]
I made the suggested changes, but I don't get this last part of yours. Maybe Surefire is handling test discovery from a TestEngine differently then DefaultLauncher.
```
C:\Users\c.rumpf\Documents\perform\junit5sandbox>mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.experimental:junit5-sandbox >-------------------
[INFO] Building junit5-sandbox 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ junit5-sandbox ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ junit5-sandbox ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ junit5-sandbox ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 35 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ junit5-sandbox ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to C:\Users\c.rumpf\Documents\perform\junit5sandbox\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ junit5-sandbox ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.708 s
[INFO] Finished at: 2018-10-16T08:55:47+02:00
[INFO] ------------------------------------------------------------------------

```

Here is MyTestEngine.java
```
public class MyTestEngine implements TestEngine {

    @Override
    public String getId() {
        return "my-test-engine";
    }

    @Override
    public TestDescriptor discover(EngineDiscoveryRequest engineDiscoveryRequest, UniqueId uniqueId) {
        System.out.println("Discovery of tests here");
        UniqueId rootId = uniqueId.append("container", "root#1");
        TestDescriptor root = new MyEngineDescriptor(uniqueId,"Root Description");
        TestDescriptor rootContainer = new MyTestDescriptor(rootId, "Container no. 1", TestDescriptor.Type.CONTAINER);

        rootContainer.addChild(new MyTestDescriptor(rootId.append("test", "child#1"), "Child no. 1", TestDescriptor.Type.TEST));
        rootContainer.addChild(new MyTestDescriptor(rootId.append("test", "child#2"), "Child no. 2", TestDescriptor.Type.TEST));
        root.addChild(rootContainer);
        return root;
    }

    @Override
    public void execute(ExecutionRequest executionRequest) {
        System.out.println("Execution of test here");

        EngineExecutionListener listener = executionRequest.getEngineExecutionListener();
        TestDescriptor root = executionRequest.getRootTestDescriptor();

        listener.executionStarted(root);
        System.out.println("Time to execute");

        for(TestDescriptor child : root.getDescendants()) {
            listener.executionStarted(child);
            System.out.printf("--- %s ---\n", child.toString());
            //listener.executionFinished(child, TestExecutionResult.failed(new RuntimeException(String.format("\"%s\" failed on purpose", child.getUniqueId().toString()))));
            listener.executionFinished(child, TestExecutionResult.successful());
        }
        listener.executionFinished(root, TestExecutionResult.successful());
    }

    @Override
    public Optional<String> getGroupId() {
        return Optional.of("com.experimental");
    }

    @Override
    public Optional<String> getArtifactId() {
        return Optional.of("my-test-engine");
    }

    @Override
    public Optional<String> getVersion() {
        return Optional.of("1.0.0");
    }
}
```

**Comment by performrumpf** [comment]
I guess this is a maven issue and not an JUnit platform issue. I did following steps which resulted in executing my test:

- Added JUnit-Jupiter 5.3.1 to dependencies
- Wrote a Java JUnit test with a dummy test method (no assertions or output)

Maybe Surefire only consideres other TestEngine implementations if it finds a valid one.

**Comment by performrumpf** [comment]
I'd like to close this ticket as this is definitely a feature of Surefire. Following reasons:

- Surefire looks for files having a certain pattern (see [documentation](http://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html))
- The filter can be overwritten with a simple order: `mvn test -Dtest=*`
- The filter can be overwritten by adding `<test>*</test>` in plugin configuration
- **Not recommended**: Using a Java class which follows default filter criteria without having any test methods (i.e. foo/DummyTest.java)

Maybe this should be mentioned in JUnit 5 User Guide Chapter [Configuring Test Engines](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-engines-configure).

**Comment by sbrannen** [comment]
> Maybe this should be mentioned in JUnit 5 User Guide Chapter Configuring Test Engines.

Maven's default patterns and filtering are mentioned in the User Guide: https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-filter-test-class-names

That section also links to: https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html

Are you saying the User Guide should do more than it already does in this regard?

**Comment by sbrannen** [comment]
> I'd like to close this ticket as this is definitely a feature of Surefire.

OK. I'm closing it for you now.

**Comment by sormuras** [comment]
Surefire should select the correct Framework Provider automatically: having `org.junit.platform:junit-platform-engine` in your test runtime dependencies should trigger the selection of its `surefire-junit-platform`. As that didn't work out in my example, I added the `surefire-junit-platform` provider to the plugin dependencies, which forces this provider to be selected and executed.

**Comment by adamretter** [comment]
I have a similar problem whereby I have written a custom TestEngine implementation (`XSuiteTestEngine` with id: `elemental-xsuite`), it should discover tests from files available on the classpath written in my own DSL.

The pertinent parts of my Maven `pom.xml` file are:

```xml
<testResources>
    <testResource>
        <directory>src/test/resources</directory>
        <filtering>false</filtering>
    </testResource>
    <testResource>
        <directory>src/test/resources-filtered</directory>
        <filtering>true</filtering>
    </testResource>
    <testResource>
        <directory>src/test/xsuite</directory>
        <filtering>false</filtering>
        <targetPath>xsuite</targetPath>
    </testResource>
</testResources>
```

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <systemPropertyVariables>
            <junit.platform.logging.level>DEBUG</junit.platform.logging.level>
        </systemPropertyVariables>
    </configuration>
    <executions>

        <execution>
            <id>xsuite-tests</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
            </goals>
            <configuration>
                <includeJUnit5Engines>
                    <includeJUnit5Engine>elemental-xsuite</includeJUnit5Engine>
                </includeJUnit5Engines>
                <excludeJUnit5Engines>
                    <excludeJUnit5Engine>junit-vintage</excludeJUnit5Engine>
                    <excludeJUnit5Engine>junit-jupiter</excludeJUnit5Engine>
                </excludeJUnit5Engines>

                <includes>
                    <include>xsuite/**.xml</include>
                </includes>
                <failIfNoTests>true</failIfNoTests>

            </configuration>
        </execution>

        <execution>
            <id>java-tests</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
            </goals>
            <configuration>
                <excludeJUnit5Engines>
                    <excludeJUnit5Engine>elemental-xsuite</excludeJUnit5Engine>
                </excludeJUnit5Engines>
            </configuration>
        </execution>

    </executions>
</plugin>
```

When I run `mvn surefire:test@xsuite-tests` I get the error:

```
[DEBUG] Resolved included and excluded patterns: xsuite/**.xml, !**/*$*
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.228 s
[INFO] Finished at: 2026-01-07T18:04:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.2:test (xsuite-tests) on project exist-core: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]
```

----

If I remove:

```xml
<includes>
    <include>xsuite/**.xml</include>
</includes>
<failIfNoTests>true</failIfNoTests>
```

Then the `discover` method of my `XSuiteTestEngine` is incorrectly called once for each of my Java Test Classes on the classpath - however my engine can't execute Java tests, it is meant to execute its own DSL tests, and I want it to be called once for a Directory, File, or Classpath Root.

---

Looking at the JUnit [Discovery Selectors documentation](https://docs.junit.org/6.0.2/running-tests/discovery-selectors.html) I have then tried using the following instead of `<includes>`:

```xml
<test>directory:${project.build.testOutputDirectory}/xsuite</test>
```

But I now get a different error:

```
[DEBUG] Resolved included and excluded patterns: directory:/Users/aretter/tmp/elemental-7.x.x/exist-core/target/test-classes/xsuite
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.357 s
[INFO] Finished at: 2026-01-07T18:10:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.2:test (xsuite-tests) on project exist-core: No tests matching pattern "directory:/Users/aretter/tmp/elemental-7.x.x/exist-core/target/test-classes/xsuite" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.)
```

----

So is it at all possible to use a custom JUnit Platform Engine from a Java Maven project where the tests that the engine should execute are not written in Java?

**UPDATE** - it looks like this has sadly been a problem in maven-surefire-plugin for 6 years now - https://github.com/apache/maven-surefire/issues/2065

**Comment by mpkorstanje** [comment]
@adamretter I've had to solve a similar problem for Cucumber. Contributing a solution to Surefire at the time was a bit much as internally it assumes tests are class-method pairs. With JUnit 5+ they're decidedly not, but that assumption is hard to get rid of in other frameworks.

Anyway, you can use the [JUnit Platform Suite Engine](https://docs.junit.org/6.0.2/advanced-topics/junit-platform-suite-engine.html) to declaratively execute the JUnit Platform. Surefire will execute the class, which can then execute your test engine. E.g:

```java
@Suite
@IncludeEngines("cucumber")
@SelectPackages("io.cucumber.skeleton")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "html:target/report.html")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "io.cucumber.skeleton")
public class RunCucumberTest {
}
```

Full example for Cucumber here: https://github.com/cucumber/cucumber-jvm-starter-maven-java

**Comment by adamretter** [comment]
@mpkorstanje Thanks for the quick reply, it's reassuring to see you found a workaround. I have been experimenting with a slightly different work around which looks like this:

```xml
    <executions>

        <execution>
            <id>xsuite-tests</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
            </goals>
            <configuration>
                <includeJUnit5Engines>
                    <includeJUnit5Engine>elemental-xsuite</includeJUnit5Engine>
                </includeJUnit5Engines>
                <excludeJUnit5Engines>
                    <excludeJUnit5Engine>junit-vintage</excludeJUnit5Engine>
                    <excludeJUnit5Engine>junit-jupiter</excludeJUnit5Engine>
                </excludeJUnit5Engines>

                <includes>
                    <!-- NOTE(AR) workaround for https://github.com/apache/maven-surefire/issues/2065 -->
                    <include>xyz.elemental.test.xsuite.XSuiteTestEngineSurefireBootstrap</include>
                </includes>
                <failIfNoTests>true</failIfNoTests>

            </configuration>
        </execution>

        <execution>
            <id>java-tests</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
            </goals>
            <configuration>
                <excludeJUnit5Engines>
                    <excludeJUnit5Engine>elemental-xsuite</excludeJUnit5Engine>
                </excludeJUnit5Engines>
                
                <excludes>
                    <!-- NOTE(AR) workaround for https://github.com/apache/maven-surefire/issues/2065 -->
                    <exclude>xyz.elemental.test.xsuite.XSuiteTestEngineSurefireBootstrap</exclude>
                </excludes>

            </configuration>
        </execution>

    </executions>
</plugin>
```

My `XSuiteTestEngineSurefireBootstrap` class then is just empty, i.e.:

```java
package xyz.elemental.test.xsuite;

/**
 * Workaround for https://github.com/apache/maven-surefire/issues/2065
 */
public class XSuiteTestEngineSurefireBootstrap {
}
```

That seems to be enough to get my XSuiteTestEngine's discover method to be called just once and presented a single ClassSelector for `XSuiteTestEngineSurefireBootstrap`.

From here I now need to discover my DSL tests, but... to do that I need to know where they are! Therefore I would like to pass a property from Maven to my TestEngine that holds that path information.

I have tried all of the following in the `<configuration>` block of the `<execution> for the surefire plugin:

```xml
<argLine>-Dxyz.elemental.test.xsuite.selector.directory=${project.build.testOutputDirectory}/xsuite</argLine>
                            
<systemPropertyVariables>
    <configurationParameters>
        xyz.elemental.test.xsuite.selector.directory=${project.build.testOutputDirectory}/xsuite
    </configurationParameters>
    <xyz.elemental.test.xsuite.selector.directory>${project.build.testOutputDirectory}/xsuite</xyz.elemental.test.xsuite.selector.directory>
    <junit.platform.configurationParameters>
        xyz.elemental.test.xsuite.selector.directory=${project.build.testOutputDirectory}/xsuite
    </junit.platform.configurationParameters>
</systemPropertyVariables>
<properties>
    <configurationParameters>
        xyz.elemental.test.xsuite.selector.directory=${project.build.testOutputDirectory}/xsuite
    </configurationParameters>
    <xyz.elemental.test.xsuite.selector.directory>${project.build.testOutputDirectory}/xsuite</xyz.elemental.test.xsuite.selector.directory>
    <junit.platform.configurationParameters>
        xyz.elemental.test.xsuite.selector.directory=${project.build.testOutputDirectory}/xsuite
    </junit.platform.configurationParameters>
</properties>
```

Strangely in my XSuiteTestEngine's `discover` method I can't seem to access that property though:
1. `engineDiscoveryRequest.getConfigurationParameters().get("xyz.elemental.test.xsuite.selector.directory")` always returns `Optional.empty`
2. `System.getProperty("xyz.elemental.test.xsuite.selector.directory")` always returns `null`

Any ideas on how I can get a property value from Maven over to my TestEngine?

**Comment by mpkorstanje** [comment]
> From here I now need to discover my DSL tests, but... to do that I need to know where they are! Therefore I would like to pass a property from Maven to my TestEngine that holds that path information.

No. You should _not_ pass a property from Maven to your Test Engine to discover tests. That is the wrong solution for test discovery. The JUnit API works with discovery selectors, so your test engine should _only_ discover tests in response to the discovery selectors in the discovery request and respond only to those selectors it supports. 

So instead work with the default Maven Surefire settings and use the  [JUnit Platform Suite Engine](https://docs.junit.org/6.0.2/advanced-topics/junit-platform-suite-engine.html) to create a `RunElementalXSuiteTest`.

Now I don't know the details of your engine, but the suite declaration could look something like this:

```java
@Suite
@IncludeEngines("elemental-xsuite")
@SelectDirectories("src/test/xsuite")
public class RunElementalXSuiteTest {
}
```

This then works as follows:

The `RunElementalXSuiteTest` is has the `*Test` suffix, so Surefire will launch the JUnit Platform with a discovery selector for that class. 

At this point there are presumably two test engines on the classpath. The Elemental XSuite engine and the JUnit Platform Suite Engine. Both will receive a discovery request containing the class selector for the `RunElementalXSuiteTest`. Because the Elemental XSuite Engine does not support classes, it should not discovery any tests.

The Suite Engine does support classes and recognizes the `@Suite` annotation, marking this class as a test suite. It then reads the `@SelectDirectories("src/test/xsuite")` and translates that into to discovery selector for the  `src/test/xsuite`  directory. It then  (recursively) requests discovery for the `elemental-xsuite` engine from the JUnit Platform with the selector it just created.

Because of `@IncludeEngines("elemental-xsuite")` only the Elemental XSuite Engine now receives a request for discovery of tests in the `src/test/xsuite` directory and because it supports files, it can now discover and respond with the discovered tests.

The JUnit Platform Suite Engine then receives these discovered tests and if the Element XSuite Engine is well behaved, the JUnit Platform Suite Engine will act as an almost transparent proxy.

Note: 
 * If your tests are on the classpath in the `xsuite` package you can use `@SelectPackages("xsuite")` instead.
 * If you are developing use the [JUnit Platform Test Kit](https://docs.junit.org/6.0.2/advanced-topics/testkit.html) and for manual testing use the [JUnit Platform Launcher API](https://docs.junit.org/6.0.2/advanced-topics/launcher-api.html). This will help ensure that the Element XSuite Engine works with complete spectrum the JUnit API rather than Maven Surefires specific use of the API.
