### ISSUE TITLE
Correct @API annotation link in pull request template

### ISSUE THREAD

**Issue by shirishp** [junit-team/junit5#1636]
## Overview

Link to `@API` annotation in current [Pull Request Template](https://github.com/junit-team/junit5/blob/master/.github/PULL_REQUEST_TEMPLATE.md) in definition of done section is expired / dead.

Current link points to http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html which does not exist.

I am not sure what should be correct link, because this annotation comes from `org.apiguardian.api.API` which I believe is from `apiguardian` project.

## Deliverables

- [ ] Correct link to `@API` in Pull Request Template

**If somebody can provide a correct link, I would like to send a PR for this.**

**Comment by marcphilipp** [comment]
Thanks for raising this issue! I've fixed the link.
