### ISSUE TITLE
Error occurs when trying to execute Tag-based Gradle task using & separator between tags 

### ISSUE THREAD

**Issue by AlienBykova** [junit-team/junit5#1641]
Good Afternoon. Could you please assist me with problem that I'm facing?

I use JUnit 5, Gradle, Java 8, and Spring.

I've tried to create new gradle task

```groovy
task pipelineTest(type: Test) { Test task ->
    task.useJUnitPlatform { org.gradle.api.tasks.testing.junitplatform.JUnitPlatformOptions options ->
        options.includeTags 'Authorization-QA & Authorization-DEV'
    }
}
```

As a result the build fails.

In your official documentation mentioned that it is possible.

Stack trace and debug results in the attachment: [stackTrace.txt](https://github.com/junit-team/junit5/files/2496338/stackTrace.txt)

**Comment by marcphilipp** [comment]
Which versions of JUnit artifacts are you using?

**Comment by sbrannen** [comment]
Based on the presence of `at org.junit.platform.launcher.TagFilter.toTestTags(TagFilter.java:125)` in the stack trace, we can see that you are using a version of the JUnit Platform that was released before support for tag expressions was introduced in JUnit 5.1 (see #454).

To fix your problem, make sure that you use are using at least JUnit Platform 1.1, preferably JUnit Platform 5.3.1.

I am therefore closing this issue.
