### ISSUE TITLE
Improve class-level Javadoc for support classes

### ISSUE THREAD

**Issue by britter** [junit-team/junit5#1645]
## Overview

As discussed in https://github.com/junit-team/junit5/pull/1644#discussion_r227276117, the class-level Javadoc for the support classes in `org.junit.platform.commons.support` should be improved.

## Deliverables

- [ ] Improve class-level Javadoc for classes in `org.junit.platform.commons.support`.

**Comment by sbrannen** [comment]
Thanks for raising the issue.

I'll tackle this one quickly...

**Comment by sbrannen** [comment]
_in progress_
