### ISSUE TITLE
Including tags useJunitPlatform closure does not exclude untagged tests

### ISSUE THREAD

**Issue by tduehr** [junit-team/junit5#1649]
## Overview

In JUnit 5.3.1 run via Gradle, when I use `includeTags` to specify the tests to run in the `useJUnitPlatform` callback, tests with the included tags are run along with any tests without tags. The behavior is not defined in the documentation for Gradle support, and documentation for the deprecated Gradle plugin implies untagged tests should not run.

## Deliverables

- Document the intended behavior for untagged tests
- Add a method to exclude untagged tests

**Comment by sormuras** [comment]
Which version of Gradle and JUnit are you using?
What does your build script look like?
Are your tests annotated with `@Tag`?

Running https://github.com/junit-team/junit5-samples/tree/master/junit5-migration-gradle yields following results:

#### Plain

Just `useJUnitPlatform()`, i.e. no `includeTags` nor `excludeTags` specified.

1. com.example.project.FirstTest > myFirstTest(TestInfo) PASSED
2. com.example.project.OtherTests > testThisThing() PASSED
3. com.example.project.OtherTests > testThisOtherThing() PASSED
4. com.example.project.SecondTest > aSlowTest() PASSED
5. com.example.project.SecondTest > mySecondTest() SKIPPED
6. com.example.project.JUnit4Test > test PASSED

#### Exclude `"slow"` tests

Via `useJUnitPlatform { excludeTags 'slow' }`

1. com.example.project.FirstTest > myFirstTest(TestInfo) PASSED
2. com.example.project.OtherTests > testThisThing() PASSED
3. com.example.project.OtherTests > testThisOtherThing() PASSED
4. com.example.project.SecondTest > mySecondTest() SKIPPED
5. com.example.project.JUnit4Test > test PASSED

#### Include `"fast"` tests

Via `useJUnitPlatform { includeTags 'slow' }`

1. com.example.project.FirstTest > myFirstTest(TestInfo) PASSED

**Comment by tduehr** [comment]
Test portion of build script:
https://github.com/apereo/cas/blob/junit_migration/gradle/tests.gradle

Main:
https://github.com/apereo/cas/blob/junit_migration/build.gradle

Gradle version 4.10, JUnit version 5.3.1, JUnit Platform 1.3.1

JUnit dependencies specified:
https://github.com/apereo/cas/blob/junit_migration/gradle/dependencies.gradle#L1364

Should you need to test against our stuff yourself, there's a untagged test that will fail if run without creds:
https://github.com/apereo/cas/blob/junit_migration/core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/adaptive/intel/BlackDotIPAddressIntelligenceServiceTests.java

Running the `testRestful` task should not run the above test, but does currently.

We had similar issues in JUnit4 using categories.

**Comment by tduehr** [comment]
Got some more troubleshooting in... I was unable to reproduce the issue with `junit-samples` until I added the `useJUnitPlatform` part of the `tasks.withType(Test)` closure to it. Looks like calling that twice, rather than modifying the existing options object, adds a second.

**Comment by sormuras** [comment]
Sounds like a configuration to me, am I right @marcphilipp?

https://github.com/tduehr/junit5-samples/blob/master/junit5-migration-gradle/build.gradle#L48-L80

**Comment by marcphilipp** [comment]
Yeah, it turns out the last call of `useJUnitPlatform()` overrides all previous ones:
https://github.com/gradle/gradle/blob/1ee5ff831577fbccc4d8ef047eaff239fd72de26/subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java#L904

Thus, that leads to the one in `tasks.withType(Test)` overriding the previous ones.

If you consider that confusing (and I wouldn't object), please open an issue for Gradle. In the meantime, you can use the following if you're sure `useJUnitPlatform()` was called previously:

```gradle
testFramework.options.includeEngines('junit-jupiter', 'junit-vintage')
```

Otherwise, there's this beauty:

```gradle
task testSlow(type: Test) {
	configureJUnitPlatform(delegate) {
		includeTags 'slow'
	}
}

tasks.withType(Test) {
	configureJUnitPlatform(delegate) {
		includeEngines('junit-jupiter', 'junit-vintage')
	}
}

def configureJUnitPlatform(Test task, Closure configureAction) {
	if (task.testFramework.class.simpleName == "JUnitPlatformTestFramework") {
		configureAction.setDelegate(task.testFramework.options)
		configureAction.call()
	} else {
		task.useJUnitPlatform(configureAction)
	}
}
```

**Comment by tduehr** [comment]
I was starting to think the same thing. Thanks for the help.
