### ISSUE TITLE
Use realistic examples in User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1651]
## Overview

Although the examples in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) are technically correct, many of them are not "good examples" for people new to JUnit 5 and JUnit Jupiter in particular.

For example, I hear complaints about examples such as `assertEquals(2, 2)`, examples that use `foo` and `bar`, or the fact that the `assertThrows(...)` example [throws an exception directly instead of invoking user code that throws an exception](https://stackoverflow.com/questions/52825082/understanding-exception-tests-in-junit-5).

## Guidelines

1. Avoid the use of meaningless assertions such as `assertEquals(2, 2)` or `assertTrue(true)`.
   - Replace such assertions with something more meaningful such as `assertEquals(3, calculator.add(1, 2)` and `assertTrue(isPalindrome("racecar"))`, respectively.
1. Focus on a realistic domain model throughout the examples. 
   - For example, we already have `example.ParameterizedTestDemo.isPalindrome(String)` (which could be relocated to something like a `StringUtils` class) and a [`Person` class](https://github.com/junit-team/junit5/blob/master/documentation/src/test/java/example/Person.java).
   - The aforementioned `Calculator` is from my examples in [junit5-demo](https://github.com/sbrannen/junit5-demo/tree/master/src/main/java/demo); a `StringUtils` class exists there with the aforementioned `isPalindrome(String)` method.
1. I propose for starters that we focus on reusing `isPalindrome()`, `Person`, and `Calculator` for most examples.
   - As mentioned by [@foobarjet on Twitter](https://twitter.com/foobarjet/status/1055902451902091264), _if necessary_ we can embellish tests using standard JDK libraries (e.g., `List<Person>`, etc.).
   - If we need something more along the lines of "integration testing" examples, we can consider reusing (and enhancing, if necessary) the existing [`WebClient` demo code](https://github.com/junit-team/junit5/blob/master/documentation/src/main/java/example/registration/WebClient.java).
1. We should **not** actually implement anything complex to use as an example.
   - For example, the aforementioned `WebClient` does not do anything at all, **but**... it _appears_ to do something realistic in the [examples that use it in the User Guide](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic-static-fields), and that's our primary goal: _for the examples to appear realistic_.
   - Granted, the `isPalindrome(String)` method does actually do something realistic, _but_ it was not difficult to implement. 😇 

## Deliverables

- [x] Revise examples in the User Guide (i.e., in the `documentation` project) so that the examples appear to be "real world" examples.
   - [x] Replace assertions such as `assertEquals(2, 2)` with something more meaningful such as `assertEquals(3, calculator.add(1, 2)`.
   - [x] Replace assertions such as  `assertTrue(true)` with something more meaningful such as `assertTrue(isPalindrome("racecar"))`.
   - [x] Replace _dummy_ variable names and values (e.g., `foo`, `bar`, `baz`, etc.) with something more meaningful. For example, switching to names of fruits might work out nicely, as was done for an example with `@CsvSource` (search for "apple").
   - [x] Revise examples for `assertThrows(...)` so that it appears that user code is being tested instead of an inline lambda expression that throws an exception.

**Comment by sbrannen** [comment]
Please note that this issue is "up for grabs" for community contribution.

However, please share your ideas here first and gather feedback from the JUnit 5 team before beginning work on this issue.

**Comment by psychsane** [comment]
Would love to work on this @sbrannen

**Comment by durgaswaroop** [comment]
Great idea. Every other software should also do this.  For a lot of projects, documentation and examples tend to show a disconnect between users and library developers.

**Comment by JLLeitschuh** [comment]
Because of the complex nature of some of the objects I'm working with, I end up with double or triple nested `assertAll` calls.
```kotlin
val anObject = aVeryBigComputation()

assertAll(
    anObject.someElement.flatMap {
           listOf(
              { assertEquals("some good name", it.name) },
              { validateNested(it.someNestedElement) }
           )
    }
)

fun validateNested(aCollection: Collection<Something>) {
    assertAll(aCollection.map { ....
    ....
```

This might provide some insights into how `assertAll` actually gets used.

**Comment by sbrannen** [comment]
> Would love to work on this @sbrannen

Glad to hear it!

I'll add some guidelines to this issue's description.

**Comment by sbrannen** [comment]
@JLLeitschuh, I think the `dependentAssertions()` [example in the User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions) adequately covers nested use of `assertAll()`.

With regard to nesting `assertAll()` invocations with streams of `Executable`, flat mappings, etc., I personally consider that a more advanced use case that is out of scope for the User Guide.

Of course... that's just my opinion. 😇 

If there is high demand for such an example, the team will consider including something along those lines.

**Comment by sbrannen** [comment]
OK... I added a new **Guidelines** section to this issue.

@junit-team/junit-lambda, please give a 👍 or 👎 to let me know if you're OK with the proposed guidelines, and then @psychsane can start on the work.

**Comment by psychsane** [comment]
> @psychsane,
> 
> > Would love to work on this @sbrannen
> 
> Glad to hear it!
> 
> I'll add some guidelines to this issue's description.

Super 🆒 I am thrilled to be part of this 🕺

**Comment by sbrannen** [comment]
OK... 3 * 👍 from team members.

So... @psychsane, go for it!

I've added the `in progress` label to denote that you are working on it.

If you decide not to work on it, please let us know.

**Comment by sbrannen** [comment]
@psychsane, to make the reviews manageable, please rework the examples one _class_ at a time.

In other words, one commit per modified example/demo class.

I think the easiest way is to start at the beginning of the User Guide and work your way down, tackling each example/demo class in the order in which they appear in the User Guide.

If you have any questions, just ask.

Cheers!

**Comment by sbrannen** [comment]
@psychsane, feel free to copy the `Calculator` class and tests for that class from my `junit5-demo` project. I give you permission. 😉 

Also, feel free to move all "domain" classes to the `src/main/java` directory structure in the `documentation` project.

**Comment by psychsane** [comment]
Thanks for your guidance @sbrannen I am on it!

**Comment by psychsane** [comment]
@sbrannen I have created PR #1664 
Should we keep the same PR open until the task is done or one PR/commit?

**Comment by psychsane** [comment]
Sorry @sbrannen I haven't yet managed to replace the foo-bars. I will try to get it finished by 1st week of Dec. Thanks!

**Comment by sbrannen** [comment]
> Sorry @sbrannen I haven't yet managed to replace the foo-bars. I will try to get it finished by 1st week of Dec. Thanks!

No worries.

We just like to keep an eye on who's working on what, so that we know the status of issues as we approach release dates.

**Comment by sbrannen** [comment]
**Update**: I have revised the _Deliverables_.

**Comment by sbrannen** [comment]
Closing this issue since all current _deliverables_ have been completed.
