### ISSUE TITLE
Release JUnit 5.3.2

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1652]
## Overview

List of fixed bugs since release 5.3.1 so far: https://github.com/junit-team/junit5/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22type%3A+bug%22+milestone%3A%225.4+M1%22+

## Deliverables

- [x] Create 5.3.2 Milestone on GitHub.
- [x] Move bug fix issues to 5.3.2 Milestone.
- [x] Backport bug fixes to `5.3.x` branch.
   - [x] #1591
   - [x] #1600
   - [x] #1603
   - [x] #1640
   - [x] #1643
   - [x] #1646
   - [x] #1665
   - [x] #1666
- [x] Create `release-notes-5.3.2.adoc` based on entries in `release-notes-5.4.0-M1.adoc`.
- [x] Copy release note _polishing_ from `release-notes-5.4.0-M1.adoc` on `master` into `release-notes-5.3.2.adoc`.
- [x] Ensure that #1600 is documented in `release-notes-5.3.2.adoc`.
- [x] Copy `release-notes-5.3.2.adoc` to `master`.
- [x] Delete `release-notes-5.4.0-M1.adoc` from the `5.3.x` branch.
- [x] Update `@since` and `@API` entries for backported bug fixes in `5.3.x` branch.
- [x] Cherry pick updated `@since` and `@API` entries for backported bug fixes to `master` branch.
- [x] Update Release Notes on `master`.
- [x] Have at least one more set of eyes review the backported commits.
- [x] Ensure the Travis CI builds pass.
- [ ] Release Jupiter and Vintage 5.3.2 as well as Platform 1.3.2 according to the [Releasing Checklist](https://github.com/junit-team/junit5/wiki/Releasing).

**Comment by sbrannen** [comment]
updated _Deliverables_

**Comment by sbrannen** [comment]
Update:

- revised Deliverables
- moved all resolved PRs to the 5.3.2 milestone as well

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
I'm currently _attempting_ to backport fixes.

So please don't do anything on the `5.3.x` branch in the interim. 😇

**Comment by sormuras** [comment]
Done: _"Ensure the Travis CI builds pass."_

**Comment by sormuras** [comment]
Done: _#1600 is documented._

**Comment by marcphilipp** [comment]
Done in 0414ccae1f9ef890b821f8df343a93a4112c7ca5.
