### ISSUE TITLE
Introduce LOCALE and TIME_ZONE constants in Resources

### ISSUE THREAD

**Issue by sdavids** [junit-team/junit5#1658]
` java.util.Locale.setDefault()`
`java.util.TimeZone.setDefault()`

https://junit-pioneer.org/docs/default-locale-timezone/

**Comment by sdavids** [comment]
Relates to https://github.com/junit-pioneer/junit-pioneer/issues/131

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 M1 for _team discussion_.

**Comment by marcphilipp** [comment]
**Team Decision:** Let's add them.
