### ISSUE TITLE
Proposal to enable @BeforeAll/@AfterAll in nested classes

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#166]
As far as I can tell the reason to have nested test classes be static is that you usually want to build on the outer class(es)' structure and state. Unfortunately this bars the use of `@BeforeAll`/`@AfterAll` in nested classes. If it is considered beneficial to enable their use, the following could be a way to go:

* Alternatively allow static nested classes.
* Create a parameter injector that injects instances of the outer classes.

This might look as follows:

```java
class Outer {

	AwesomeClass unitUnderTest	;

	@Nested
	static class InnerTest {
		
		@BeforeAll
		// 'Outer' instances can not be injected
		// because it makes no sense to operate on them 
		static void initAll() {
			// ...
		}
	
		@BeforeEach
		// an 'Outer' instances is created;
		// all '@BeforeEach' methods are run on/with;
		// it is injected here
		static void init(Outer outer) {
			outer.unitUnderTest.prepareYourThing();
		}
	
		@Test
		// same as with 'init'
		static void testThatThing(Outer outer) {
			outer.unitUnderTest.doYourThing();
		}
	
	}

}
```

Because this makes nested tests more verbose, it should be an alternative for the scenarios where it is direly needed. The default way to go would be non-static nested classes because the need for `@BeforeAll`/`@AfterAll` is comparatively rare (in my experience).

**Comment by jlink** [comment]
I'd vote against nested static classes. If you really really need before/afterAll behaviour in nested tests just use an extension.

Von meinem iPad gesendet

**Comment by bechte** [comment]
The idea behind nested test classes is more or less an grouping aspect. I can understand that it might be useful to have before/after all behavior in some corner cases, but I would also vote for not supporting this due to the enormous complexity that goes along with this feature.

If you really need a completely different before/after all behavior, like starting a service or spring context, I would also suggest to create a new test class per "environment" and use nested tests only to separate different aspects in the same "environment", like inheritance.

Could you give us a better understanding of your use-case by telling about the situation in which you wanted to use nested static classes?

all the best

Stefan

**Comment by nicolaiparlog** [comment]
> Could you give us a better understanding of your use-case by telling about the situation in which you wanted to use nested static classes?

I don't have one. :wink:

@jlink's talk and `@BeforeAll`'s Javadoc made it seem as if the reason why `@...All` were not supported in nested classes was purely technical. This is a proposal for a solution to that technical problem, not a feature request.

**Comment by bechte** [comment]
It might be a technical limit of the current implementation, but for me this is not the reason why we implemented it the way it is. I currently see no use-case that would require such a feature. If there was, I would suggest another way to implement Before/AfterAll that covers both cases, TopLevel and Nested Classes. 

We might want to keep your solution in mind and pick it up as soon as we need it. :smiley:

**Comment by marcphilipp** [comment]
When you have multiple levels of nesting, e.g. a static inner class inside another static class and so on, this would become challenging to use and implement. You would need multiple parameters in your `@BeforeAll` methods.

Anyway, I'm with @jlink and @bechte on this one: I don't see a compelling use case and therefore I'm closing this issue for now.

**Comment by ahrytsiuk** [comment]
I totally agree that we should avoid `@BeforeAll` and `@AfterAll` callbacks in the `@Nested` test classes.

But anyway you can implement [them](https://gist.github.com/ahrytsiuk/c5289a63c1ea83557fcb1064ec51712d)

**Comment by sbrannen** [comment]
@ahrytsiuk, that's quite an interesting _hack_ you've used there, having an `@Nested` inner class extend a static nested class just to be able to declare static `@BeforeAll` and `@AfterAll` methods. 😱

**Comment by hjohn** [comment]
Thanks @ahrytsiuk -- just what I needed.

**Comment by gileli121** [comment]
I am not sure that it is written here but this will work:

```java
public class MyTestClass {

    @Nested
    @TestInstance(TestInstance.Lifecycle.PER_CLASS) // You must add this!
    public class TestsType1 {

        @BeforeAll
        public void beforeAll() {
            System.out.println("before all");
        }
        
        @Test
        public void test1_a() {
            System.out.println("test1_a");
        }
        @Test
        public void test2_a() {
            System.out.println("test2_a");
        }
    }

```

This will work because of `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`
