### ISSUE TITLE
Convert Test Kit to fluent API

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1662]
## Overview

#1356 introduced the _Test Kit_ as a published artifact.

However, the existing API is rather static in nature.

This issue aims to improve the user experience by converting the Test Kit to a _fluent API_.

## Scope

The existing APIs in `ExecutionEventConditions` and `TestExecutionResultConditions` are out of scope for this issue.

## Related Issues

- #1356 
- #1621 

## Considerations

1. ✅ Decide on naming for dynamically registered containers and tests, since "test" doesn't make sense if you've filtered by containers.
   - Ideas: `dynamicRegistration()`, `dynamicNodeRegistered()`
   - Team Decision: **`dynamicallyRegistered()`**
1. ❌ Introduce category-aware `Events` specializations (e.g., `SkippedEvents`, `FinishedEvents`, etc.) in order to prevent broken use cases such as `events.skipped().aborted()` -- for example, `SkippedEvents` would not provide `aborted()` as part of its API since that would not make sense.
   - Team Decision: stick with the existing API.
1. ✅ Convert `Statistics` assertion API to a fluent API and thus remove the need for static imports.
   - Team Decision: implement a spike to verify feasibility.
1. ❌ Split `Statistics` into `GlobalStatistics` and `FilteredStatistics`, so that statistics for tests *and* containers can be asserted together via `ExecutionResults.events()` instead of separately via `ExecutionResults.containers()` and `ExecutionResults.tests()`.
   - Team Decision: hold off for now.
1. ❌ Introduce fluent API for AssertJ-based assertions for **events**, replacing the existing static factory methods with discoverable method chaining analogous to AssertJ's APIs.
   - Team Decision: stick with the existing static factory methods.
1. ❌ Introduce  built-in AssertJ-based assertions for **executions** analogous to those for events.
   - Team Decision: wait for community feedback.
1. ❌ Introduce  support for asserting statistics for **executions** analogous to those for events.
   - Team Decision: wait for community feedback.

## Deliverables

- [x] Introduce fluent API for filtering and accessing **events**.
- [x] Introduce fluent API for filtering and accessing **executions**.
- [x] Introduce fluent API for asserting statistics for **events**.
- [x] Introduce support for debugging **events**.
- [x] Introduce support for debugging **executions**.
- [x] Introduce Javadoc for new fluent APIs.
- [x] Write (and potentially rewrite) Javadoc for all public APIs in the Test Kit, excluding `ExecutionEventConditions` and `TestExecutionResultConditions` which are out of scope.
- Will be documented in the Release Notes in conjunction with #1621.

**Comment by sbrannen** [comment]
_in progress_ in the following branch:

https://github.com/junit-team/junit5/tree/experiments/test-kit-fluent-api

**Comment by jbduncan** [comment]
I've not played around with either the static or fluent API yet, but one thing I've noticed reading the source code is that it's apparently difficult/impossible to test events coming from the JUnit Jupiter test engine without depending on `JupiterTestEngine`, which IIRC is `@API(Internal)`.

If I could use the Test Kit against the Jupiter test engine, then I imagine it would allow me to shorten my existing tests for [jupiter-collection-testers](https://github.com/jbduncan/jupiter-collection-testers). But I'm not sure about this yet as, as I said earlier, I've yet to actually play around with the Test Kit.

**Comment by sbrannen** [comment]
> I've not played around with either the static or fluent API yet, but one thing I've noticed reading the source code is that it's apparently difficult/impossible to test events coming from the JUnit Jupiter test engine without depending on `JupiterTestEngine`, which IIRC is `@API(Internal)`.

Good point!

I've also had some qualms about having to instantiate the `TestEngine`.

I'd rather like to see a process more like the `Launcher` does for discovering engines and filter out all other engines than the one currently being tested.

But... that is out of scope for this issue which focuses on a fluent API.

@jbduncan, would you mind opening a new issue to address?

**Comment by jbduncan** [comment]
Certainly! I've just raised it over here: https://github.com/junit-team/junit5/issues/1663. :)

**Comment by sbrannen** [comment]
The Test Kit has been converted to a fluent API in `master` in 8013c6a6a2f07463c4f78f295f5652c04554b065.

**Comment by sbrannen** [comment]
Update: the `EngineTestKit` now has a fluent API for building the discovery request. See 252c9da377e8f5f5c10a610e09cb3f08cfe8e24a for details.
