### ISSUE TITLE
Use ServiceLoader mechanism to load TestEngines in the Test Kit

### ISSUE THREAD

**Issue by jbduncan** [junit-team/junit5#1663]
## Overview

I'm raising this issue at @sbrannen's request from https://github.com/junit-team/junit5/issues/1662#issuecomment-435420852.

We should consider changing the API of the Test Kit so that it can easily test...uh, tests, from the JUnit Jupiter Engine. Currently, if one wants to do so, they need to depend on `JupiterTestEngine` which is `@API(Internal)`.

This issue originated from [this comment of mine](https://github.com/junit-team/junit5/issues/1662#issuecomment-435381451).

## Proposal

Introduce support similar to that in the `Launcher` for discovering engines via Java's `ServiceLoader` mechanism and filter out all engines other than the one currently being tested (which is selected by engine ID).

## Deliverables

- [x] Allow `TestEngine` implementations to be tested with the Test Kit without the need to instantiate the `TestEngine` directly.

**Comment by sbrannen** [comment]
Thanks for creating this issue.

I've added a **Proposal** to this issue's description and will now update the title accordingly.

**Comment by jbduncan** [comment]
> Thanks for creating this issue.
>
> I've added a Proposal to this issue's description and will now update the title accordingly.

You're very welcome, and cheers! :+1:

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
And... Voilà!

Pushed to `master` in commit https://github.com/junit-team/junit5/commit/dfce0a78c61d93742f1907210aaf5009569678b6

**Comment by jbduncan** [comment]
Brilliant! Thank you very much Sam. :)

**Comment by sbrannen** [comment]
> Brilliant! 

😊 

> Thank you very much Sam. :)

You (and the community) are very welcome! 🙇
