### ISSUE TITLE
Assumptions.assume(not)Throws

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#1667]
I have this test

```java
    @Test
    void equalsAndHashcodeForFields() {
            EqualsVerifier.forClass( Emr.class )
                    .withRedefinedSuperclass()
                    .withIgnoredFields( AbstractEntityBase.ID )
                    .verify();
    }
```

currently it's failing for reasons not relevant here, verify returns void and throws an exception. I was hoping I could wrap it in an assumption of some kind.  Instead I guess I'll mark it disabled.

**Comment by marcphilipp** [comment]
TBH I'm not sure how generally useful such an assumption would be. I've added this issue to the general backlog for the time being to see if other people come up with similar use cases.

**Comment by juliette-derancourt** [comment]
Superseded by #2482.
