### ISSUE TITLE
Supply invocation index for @ParameterizedTest to test author

### ISSUE THREAD

**Issue by Gabology** [junit-team/junit5#1668]
## Overview

The invocation index of a parameterized test is accessible for templating when setting the display name of the test.

When it comes to accessing the invocation index using `TestInfo` it is not possible as it looks like the `TestInfo` implementation for `@ParameterizedTest` is of the default type. I would expect to get an `RepetitionInfo` instance so that I can access the invocation index programmatically. 

## Related Issues

- #944
- #1139
- #1884

**Comment by sbrannen** [comment]
FYI: this is closely related to #944.

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 M1 for _team discussion_

**Comment by mschechter-bellese** [comment]
It would also be helpful to have the index available in the `ExtensionContext`, so that it can be used via the `@EnabledIf` / `@DisabledIf` handler method.

**Comment by marcphilipp** [comment]
A non-intrusive way of adding this would be to add the invocation index to `ArgumentsAccessor`.

@Gabology @mschechter-bellese Would that work in your use case?

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by mschechter-bellese** [comment]
> A non-intrusive way of adding this would be to add the invocation index to `ArgumentsAccessor`.
> 
> @Gabology @mschechter-bellese Would that work in your use case?

Would that make it available to the methods implemented for `@EnabledIf` / `@DisabledIf`, so that I can skip specific indexes when running a parameterized test? If so, I think the `ArgumentsAccessor` would work.

**Comment by marcphilipp** [comment]
> Would that make it available to the methods implemented for `@EnabledIf` / `@DisabledIf`, so that I can skip specific indexes when running a parameterized test?

No, `ExecutionConditions` are currently only evaluated at the method level, not the invocation level so I think that would be a separate issue.

**Comment by mschechter-bellese** [comment]
> > Would that make it available to the methods implemented for `@EnabledIf` / `@DisabledIf`, so that I can skip specific indexes when running a parameterized test?
> 
> No, `ExecutionConditions` are currently only evaluated at the method level, not the invocation level so I think that would be a separate issue.

Yes, that makes sense. I think I would need a different solution, then. Could you please let me know if there's an existing issue that covers this?

**Comment by marcphilipp** [comment]
I think #1139 is closely related.

**Comment by mschechter-bellese** [comment]
> I think #1139 is closely related.

Thanks!

**Comment by marcphilipp** [comment]
**Team decision:** Add `ArgumentsAccessor.getInvocationIndex()`.

**Comment by marcphilipp** [comment]
@Gabology @mschechter-bellese Would one of you be interested in submitting a PR for this?

**Comment by mschechter-bellese** [comment]
@marcphilipp,

I am currently more focused on making the invocation index available to `@DisabledIf` / `@EnabledIf` consumers via #1139.

Quick question: if the invocation index is to be accessible from the `ArgumentsAccessor`, how is the invocation index value provided during instantiation? It appears that the invocation index is only available as an `AtomicInteger` in `ParameterizedTestExtension.provideTestTemplateInvocationContexts`, so I'm probably missing something.

**Comment by marcphilipp** [comment]
> Quick question: if the invocation index is to be accessible from the `ArgumentsAccessor`, how is the invocation index value provided during instantiation? It appears that the invocation index is only available as an `AtomicInteger` in `ParameterizedTestExtension.provideTestTemplateInvocationContexts`, so I'm probably missing something.

From there it needs to be passed to `ParameterizedTestInvocationContext`, `ParameterizedTestParameterResolver`, and finally `ParameterizedTestMethodContext.resolve`.

**Comment by hglasgow** [comment]
I have the `ArgumentsAccessor.getInvocationIndex()` idea working on my fork. Ill raise a PR for it.
