### ISSUE TITLE
Introduce runtime dependency from Jupiter API to its Engine

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1669]
## Engine Implementation Artifact Hint

A test engine API should be able to hint/point to its default implementation artifact. Build tools could use that hint to dynamically resolve an engine implementation artifact and its transitive dependencies at runtime.

For example, in Gradle, it should be enough to state
```
testCompile('org.junit.jupiter:junit-jupiter-api:5.3.1')
```
From this fact, the "missing" `testRuntime('org.junit.jupiter:junit-jupiter-engine:5.3.1')` could be deduced.

**Comment by sbrannen** [comment]
How do you propose to provide such a _hint_?

**Comment by sormuras** [comment]
Mh, good question. Those solutions are in my mind:

1. Define a JAR MANIFEST key that may contain the hint.
2. Introduce an interface `DefaultEngineImplementationArtifactHint` in `junit-platform-commons` and the `ServiceLoader` facility.
3. Scan all optional dependency entries of the engine API artifact's `pom.xml`... and pick the right one?!

**Comment by sormuras** [comment]
@sbrannen and my favorite is: **Define a JAR MANIFEST key that may contain the hint.**

**Comment by jlink** [comment]
Why would that be better than specifying an additional testRuntime dependency? Is it just the one line? 

As soon as we get to Java 9+, the module system will make the separation into two jars redundant or does it?

**Comment by sormuras** [comment]
> Why would that be better than specifying an additional testRuntime dependency? Is it just the one line?

True. For Gradle. In Maven 3 there is no such scope as `test runtime`, iirc.

> As soon as we get to Java 9+, the module system will make the separation into two jars redundant or does it?

Why? From a user's point of view, you write `module test { requires org.junit.jupiter.api; }`. Then, at test runtime, a build tool needs to enhance the enhance the module graph with `org.junit.jupiter.engine` -- imho, the `ServiceLoader` mechanism should kick in resolve the coupling between both modules. Due to `engine reads api` and `provides TestEngine with JupiterTestEngine`. That's a blind guess, need to test it.

**Comment by sormuras** [comment]
Proposal:
`JUnit-TestEngine-Implementation-Maven-Artifact-ID: junit-jupiter-engine`

Optional group ID: 
`JUnit-TestEngine-Implementation-Maven-Group-ID: org.junit.jupiter`
If missing, assume same group ID as the current (_api_) artifact belongs to.

Optional version: 
`JUnit-TestEngine-Implementation-Maven-Version: 5.3.1`
If missing, assume same version as the current (_api_) artifact reports.

**Comment by sormuras** [comment]
### Proposal 2

`JUnit-TestEngine-Implementation-Maven-Coordinates: [org.junit.jupiter:]junit-jupiter-engine[:5.3.1]`

Both, the group ID and version, are optional. The build tool needs to extrapolate "missing" values from the current (_api_) artifact.

**Comment by sormuras** [comment]
@rfscholte said in the ASF slack #maven channel:

>  Is there only 1 engine for the API? If so, how about if the api gets the dependency for the engine with scope runtime? Yes, this looks like a circular dependency, but the scope should do the proper magic.

Thus, `junit-jupiter-api:N` would declare a runtime dependency on `junit-jupiter-eninge:X`. And `junit-jupiter-engine` (and its transitive dependencies) **won't** appear on the test compile path in Maven.

What about Gradle, @marcphilipp? Does it behave similar?

**Comment by marcphilipp** [comment]
It will with 5.0: https://docs.gradle.org/5.0-rc-5/userguide/upgrading_version_4.html#rel5.0:pom_compile_runtime_separation

**Comment by sormuras** [comment]
So, if we introduced a **runtime** dependency from `junit-jupiter-api:5.4.0-SNAPSHOT` on to `junit-jupiter-engine:5.4.0-SNAPSHOT` we have the following picture regarding Maven and Gradle.

### Maven (since when?)

```xml
<dependency>
  <groupId>org.junit.jupiter</groupId>
  <artifactId>junit-jupiter-api</artifactId>
  <version>5.4.0-SNAPSHOT</version>
  <scope>test</scope>
</dependency>
```

test**Compile** `junit-jupiter-api.jar:...`
test*Runtime* `junit-jupiter-api.jar:junit-jupiter-engine.jar:...`

### Gradle 4.10.2 and earlier

```groovy
testCompile("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
```

test.**compile** `junit-jupiter-api.jar:junit-jupiter-engine.jar:...`
test.*runtime* `junit-jupiter-api.jar:junit-jupiter-engine.jar:...`


### Gradle 5 and later

```groovy
testCompile("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
```

test.**compile** `junit-jupiter-api.jar:...`
test.*runtime* `junit-jupiter-api.jar:junit-jupiter-engine.jar:...`

**Comment by sormuras** [comment]
I assume that this `1:1` relation ship is almost 99% the desired one. For rare cases, for when an API should be handled by different engines, they can be added to the test runtime paths as always. For the even rarer cases when the default engine should be excluded, users may `excluded` the default runtime dependency.

**Comment by sbrannen** [comment]
> @rfscholte said in the ASF slack #maven channel:
> 
> > Is there only 1 engine for the API? If so, how about if the api gets the dependency for the engine with scope runtime? Yes, this looks like a circular dependency, but the scope should do the proper magic.

Interesting! 👍

**Comment by sormuras** [comment]
With https://github.com/junit-team/junit5/commit/436342980610f009077bd5d01221f88b75e767c6 the current `5.4.0-SNAPSHOT` (_build in progress_) of the `junit-jupiter-api` includes a runtime dependency to its `junit-jupiter-engine` artifact.

_"Is it secret? It it save?"_ -- Does it break your build?

Feedback is very welcome.

**Comment by sbrannen** [comment]
> > @rfscholte said in the ASF slack #maven channel:
> > > Is there only 1 engine for the API? If so, how about if the api gets the dependency for the engine with scope runtime? Yes, this looks like a circular dependency, but the scope should do the proper magic.
> 
> Interesting! 👍

Like I said....... "interesting". So interesting in fact that it broke Eclipse. 😉 

But I just _fixed_ that.... 2da87e7923b2048fc8adc9af7976714f3216c8ed

**Comment by sbrannen** [comment]
*Update*: moved to 5.4 M1 since it will be available in M1.

If we need to _undo_ any of these changes, we should open new issues in a subsequent milestone or RC.

**Comment by sbrannen** [comment]
@sormuras, can this issue now be closed for 5.4 M1?

**Comment by sormuras** [comment]
Sure. Closed.

**Comment by sormuras** [comment]
_Reopened for team discussion._

Let's revert the _cyclic but okay-ish_ runtime dependency and introduce a dedicated **`junit-jupiter`** module that only hosts the following dependencies:

```groovy
testCompile("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}")
```

Same for a new **`junit-vintage`** module:

```groovy
testCompile("junit:junit:4.12")
testRuntimeOnly("org.junit.vintage:junit-vintage-engine:${junitVintageVersion}")
```

Find a working sample of this pattern in the `mainrunner` module https://github.com/sormuras/mainrunner -- it just contains:

```xml
<dependencies>
    <dependency>
        <groupId>de.sormuras</groupId>
        <artifactId>mainrunner-api</artifactId>
        <version>${project.version}</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>de.sormuras</groupId>
        <artifactId>mainrunner-engine</artifactId>
        <version>${project.version}</version>
        <scope>runtime</scope>
    </dependency>
</dependencies>
```

It is used in the junit5-samples here: https://github.com/junit-team/junit5-samples/commit/4dd699098612a20139e26234db9c2ad75e7a8867
