### ISSUE TITLE
SNAPSHOT javadocs are missing "framed" version

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#1671]
Please provide us the version of JUnit 5 you are using and, if possible, a failing unit test with your bug report. Don't forget to describe the rationale for this issue (e.g. expected vs. actual behavior).

## Steps to reproduce

1.  Browse to https://junit.org/junit5/docs/current/api/index.html?overview-summary.html and you'll
    have the option to select "Frames" or "No Frames".  Note that this site comes up in the "Frames"
    mode by default.
2.  Browse to https://junit.org/junit5/docs/snapshot/api/index.html?overview-summary.html and the
    sub-menu bar is completely missing.  Note that this site comes up in the "No Frames mode by
    default.

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.3.x versus 5.4.x-SNAPSHOT
 - Build Tool/IDE: N/A

## Deliverables

- [ ] Make the SNAPSHOT javadocs format the same as the production/stable version.

**Comment by marcphilipp** [comment]
I'm afraid that's because we're building the Javadocs using Java 11 and it seems to no longer support frames (cf. [JDK 11 Javadocs](https://docs.oracle.com/en/java/javase/11/docs/api/index.html)).

Unless I'm missing sth., I think we should close this issue.

**Comment by sormuras** [comment]
https://stackoverflow.com/questions/51992347/missing-iframe-view-for-javadocs-jdk-11

> [...] A warning should be generated if "--frames" option is specified to generate frames. The support for frames will be removed from a future release.

**Comment by marcphilipp** [comment]
Thanks for the link, @sormuras! I've tried adding the `--frames` option and it works but generates the following warning:

```
> Task :aggregateJavadocs
javadoc: warning - You have specified to generate frames, by using the --frames option.
The default is currently to not generate frames and the support for
frames will be removed in a future release.
To suppress this warning, remove the --frames option and avoid the use of frames.
1 warning
```

I think we should use it anyway for now, at least for the aggregated docs.

@junit-team/junit-lambda WDYT?

**Comment by marcphilipp** [comment]
**Team Decision:**

Since Java will remove the option in the future, we'll discontinue shipping Javadocs with frames with 5.4.
