### ISSUE TITLE
Navigating to search results broken in snapshots Javadocs

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1673]
When using the search box in the current [snapshot Javadocs](https://junit.org/junit5/docs/snapshot/api/), clicking on one of the results takes one to an invalid URL.

For example, when typing `TestDescriptor` and clicking on the first link, on ends up at https://junit.org/junit5/docs/snapshot/api/undefined/org/junit/platform/engine/TestDescriptor.html.

Note the `undefined` in the URL. Root cause is probably that we've started using JDK 11 to build the Javadocs and have customized it considerably.

**Comment by marcphilipp** [comment]
Comparing it with this URL, it looks the `undefined` part is supposed to be the module name: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ArrayList.html

**Comment by marcphilipp** [comment]
Looks like there' a `var useModuleDirectories = true;` JavaScript definition in each generated HTML file. If we can get that to generate to set `false`, we should be good.

**Comment by sbrannen** [comment]
Great detective work! 👍
