### ISSUE TITLE
Abstract slides, flyer, sticker?

### ISSUE THREAD

**Issue by onemanagency** [junit-team/junit5#1678]
Hi.
I´d like to promote JUnit 5 inside my company, do you provide any kind of abstract or open slides that i can use? By chance, do you have kind of abstract or sth. like a onepager/flyer, that i can drop at the right table?

**Comment by sormuras** [comment]
As far as I know, none of those "hardware" assets exist.

Could have used such material as handouts last time I presented JUnit 5, though. At least some stickers with the logo should be easy to "generate" using this image:

https://junit.org/junit5/assets/img/junit5-logo.png
