### ISSUE TITLE
Catch up on JUnit 4 Runner support for custom test instances

### ISSUE THREAD

**Issue by rmannibucau** [junit-team/junit5#1680]
Runners in JUnit 4 were a great way to control the test environment and instance from user land (without writing an engine).

It would be great if JUnit Jupiter would allow one to do the same.

The main challenge is controlling the test instance redefining a custom `@Test`.

**Comment by sormuras** [comment]
Does the [`TestInstanceFactory`](https://junit.org/junit5/docs/current/user-guide/#extensions-test-instance-factories) extension point already help your use-case?

**Comment by sormuras** [comment]
What about the [`TestInstancePostProcessor`](https://junit.org/junit5/docs/current/user-guide/#extensions-test-instance-post-processing) extension?

**Comment by rmannibucau** [comment]
the processor is way too late (the instance exists so it does not help at all), test instance factory works (but requires the last release, i was on the 5.3.0) but can likely be enhanced to be supported per test and not only globally (the API is not called when defined on a test method)

thanks for the heads up anyway, wouldnt have noticed the bad version otherwise

**Comment by sbrannen** [comment]
@rmannibucau, based on your latest feedback, I am closing this as a _duplicate_ of #201.

Feel free to participate in the discussion in #201.

**Comment by rmannibucau** [comment]
Oki, i will just note that willing to handle all particular cases instead of providing a generic API as junit4 was is going to be a lot more complex and less powerful even if the api is a bit more fun so probably time to rationalize junit5 instead of fixing cases one by one.
