### ISSUE TITLE
Add parallel execution mode that runs only test classes in parallel

### ISSUE THREAD

**Issue by theigl** [junit-team/junit5#1682]
I'm in the process of upgrading our parallel test setup to JUnit5. My JUnit4 surefire configuration looks like this:

```
<configuration>
    <parallel>classes</parallel>
    <threadCount>1</threadCount>
    <perCoreThreadCount>true</perCoreThreadCount>
</configuration>
```

With this configuration, test classes run in parallel but individual test methods within a class run within the same thread (see [Surefire Docs](
https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html)).

I tried to emulate this behavior with `@Execution(ExecutionMode.SAME_THREAD)` on my test classes. But as discussed on Gitter, this actually causes the test and all its method to run in the same thread as the test classes parent node which is the test engine.

@marcphilipp suggested two possible workarounds:
- you could put the annotation on each test method but that's probably overkill
- you could put all your test methods into `@Nested` classes and use `@Execution(ExecutionMode.SAME_THREAD)` on the nested class

Both workarounds are quite invasive and not very intuitive for authors of new tests.

It would be great if we had an additional execution mode that runs only test classes in parallel or if `@Execution(ExecutionMode.SAME_THREAD)` on test classes could be adapted to do that.

**Comment by marcphilipp** [comment]
I'm pondering adding a second parameter to `@Execution()` for setting the default execution mode of children, e.g. `@Execution(children = SAME_THREAD)`.

@junit-team/junit-lambda WDYT?

**Comment by sbrannen** [comment]
Yes, I think that would be a good idea.... to have separate configuration for children, and to have the _default_ configuration apply to "current level and below" (without configuring _parents_) as @Sam-Kruglov mentioned.

**Comment by kelunik** [comment]
With the default execution mode and the following configuration, tests are run in parallel for me, but individual methods within a test are run in sequential order. I don't have any annotations on the test classes or methods. Could you clarify what doesn't match your wish with this configuration?

```xml
<properties>
  <configurationParameters>
    junit.jupiter.execution.parallel.enabled = true
    junit.jupiter.execution.parallel.config.strategy = fixed
    junit.jupiter.execution.parallel.config.fixed.parallelism = 6
  </configurationParameters>
</properties>
```

**Comment by drabe8** [comment]
We have this need as well. Currently we're using gradle to parallelize our test execution, but it has its own limitations (it's not very smart about how to divide the test classes among multiple threads). Once we have the ability to run multiple test classes in parallel (with all methods in each test class running serially), we can let JUnit parallelize the workload for us!

**Comment by marcphilipp** [comment]
@kelunik Which version are you using?

**Comment by marcphilipp** [comment]
The opposite use case (running test method within a class in parallel but top-level classes sequentially) [just came up on StackOverflow](https://stackoverflow.com/q/56215257/6327046).

We've introduced `junit.jupiter.execution.parallel.mode.default` in 5.4 which can be used to set the default execution mode. If we introduced a new `junit.jupiter.execution.parallel.mode.classes.default` (or similar) I think we could make both use cases work.

The following config would cause everything except top-level classes to be executed sequentially:

```
junit.jupiter.execution.parallel.mode.default=same_thread
junit.jupiter.execution.parallel.mode.classes.default=concurrent
```

While the opposite configuration would cause everything except for top-level classes to run concurrently:

```
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.mode.classes.default=same_thread
```

The new property would only be applied to top-level classes, not their children.

@junit-team/junit-lambda WDYT?

**Comment by kelunik** [comment]
@marcphilipp I'm using the following versions:

```xml
<junit.jupiter.version>5.3.2</junit.jupiter.version>
<junit.platform.version>1.3.2</junit.platform.version>
```

**Comment by marcphilipp** [comment]
@kelunik Thanks, that explains why you didn't have to set `junit.jupiter.execution.parallel.mode.default=concurrent` which was introduced in 5.4. :wink:

**Comment by sbrannen** [comment]
> The new property would only be applied to top-level classes, not their children.
> 
> @junit-team/junit-lambda WDYT?

I think it's a good idea to introduce this level of configurability.

**Comment by marcphilipp** [comment]
**Team Decision:** Add `junit.jupiter.execution.parallel.mode.classes.default`

**Comment by vab2048** [comment]
@marcphilipp I realise this issue has been closed for a while now but I wasn't sure where else to ask.

Is there any intention to extend JUnit 5's parallel feature to allow for forking separate JVM(s) and running tests on those?

I'm envisioning something where an annotation is placed on a class (or otherwise) which results in JUnit forking a JVM and running those tests in that class separately in that JVM.

**Comment by marcphilipp** [comment]
@vab2048 No, there are currently no plans to do so. It should be fairly straightforward to configure a separate test task or execution in Gradle or Maven, respectively.

**Comment by spc16670** [comment]
https://stackoverflow.com/questions/67164642/execute-junit5-test-in-parallel-in-separate-jvms-with-gradle

**Comment by mridang1611** [comment]
We are using JUNIT5
I have the following in junit-platform.properties
```
junit.jupiter.execution.parallel.enabled = true
# methods in a class
junit.jupiter.execution.parallel.mode.default = concurrent
# classes
junit.jupiter.execution.parallel.mode.classes.default = concurrent
```
However in logs in only see 
INFO: Using parallel execution mode 'CONCURRENT' set via the 'junit.jupiter.execution.parallel.mode.default' configuration parameter.
Nothing for the classes can someone please help

**Comment by marcphilipp** [comment]
@mridang1611 Which version are you using? Please see https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution for details.
