### ISSUE TITLE
Document default execution mode for test classes that use Lifecycle.PER_CLASS and for @Nested test classes

### ISSUE THREAD

**Issue by sidamos** [junit-team/junit5#1683]
JUnit 5.3.1
I have set junit.jupiter.execution.parallel.enabled=true in junit-platform.properties.

According to the docs, all tests should now run in parallel.

In fact, only tests with @Execution(ExecutionMode.CONCURRENT) run in parallel.

Attaching 2 test classes.

[examples.zip](https://github.com/junit-team/junit5/files/2600122/examples.zip)

**Comment by sidamos** [comment]
If you intend to fix that, please also have a look at issue #1684. Because the current behavior is actually good for us. ;-)

**Comment by sormuras** [comment]
Content `example.zip` w/o import statements:

```java
@Execution(ExecutionMode.CONCURRENT)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class JUnit5Test1 {
    @Test
    public void method1() {
        System.out.println(Thread.currentThread().getName());
    }

    @Test
    public void method2() {
        System.out.println(Thread.currentThread().getName());
    }
}

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class JUnit5Test2 {
    @Test
    public void method1() {
        System.out.println(Thread.currentThread().getName());
    }

    @Test
    public void method2() {
        System.out.println(Thread.currentThread().getName());
    }
}
```

**Comment by sormuras** [comment]
What does the output look like? On which machine (cpu, cores, threads...) are you running the tests?

**Comment by sidamos** [comment]
Test1:
INFORMATION: Loading JUnit Platform configuration parameters from classpath resource [file:/C:/Workspace/connexity/smartpricing-automation/target/test-classes/junit-platform.properties].
ForkJoinPool-1-worker-3
ForkJoinPool-1-worker-2

Test2:
INFORMATION: Loading JUnit Platform configuration parameters from classpath resource [file:/C:/Workspace/connexity/smartpricing-automation/target/test-classes/junit-platform.properties].
ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1

Running within IntelliJ 2018.2. CPU is Core i7-4790. 4 Cores (8 virtual).

**Comment by marcphilipp** [comment]
That's because we execute test classes that use `TestInstance.Lifecycle.PER_CLASS` in the same thread by default because test authors would need to ensure thread safety when using instance variables etc. That's missing from the documentation, though.

**Comment by sbrannen** [comment]
> That's because we execute test classes that use `TestInstance.Lifecycle.PER_CLASS` in the same thread by default because test authors would otherwise have to ensure thread safety when using instance variables etc. That's missing from the documentation, though.

I recall discussing that in great detail when we made those changes.

Did we really forget to document it? Oops! 🙈

**Comment by sbrannen** [comment]
Update: I changed the title to reflect the fact that we need to document the default execution mode for `@Nested` test classes as well.
