### ISSUE TITLE
Support having only a few parallel test classes

### ISSUE THREAD

**Issue by sidamos** [junit-team/junit5#1684]
JUnit 5.3.1

According to the docs, when I set `junit.jupiter.execution.parallel.enabled=true` in `junit-platform.properties`, then all tests run in parallel, unless they have annotation `@Execution(ExecutionMode.SAME_THREAD)`.

This is not true (see issue #1683), but once this is true, then this will be pretty annoying. From our preliminary testing of JUnit 5, I can say that making tests thread-safe can be a greater task than one would anticipate.

Therefore, we'd need the ability to easily only have some classes run in parallel and not the other way around (only some classes not parallel), like this seems to be planned according to the docs.

Thanks!

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 M1 for _team discussion_.

**Comment by snicoll** [comment]
Wishful thinking on my end most probably but if that was truly opt-in (i.e. you have to flag the tests that need this feature), this would ease the configuration as the only requirement would be to flag the tests that should  run in parallel. If we keep the current situation with a different default for the execution mode, we have more to configure for the most used case (which, IMO, is to flag the tests you want to run in parallel).

**Comment by marcphilipp** [comment]
It‘s still experimental so we could change the default to be sequential and have a single property to configure it.

**Comment by marcphilipp** [comment]
**Team Decision:**

- Leave the `junit.jupiter.execution.parallel.enabled` property in place with `false` as default value
- Introduce a new `junit.jupiter.execution.parallel.mode.default` property with default `same_thread`

**Comment by marcphilipp** [comment]
_in progress_
