### ISSUE TITLE
Tags are not being picked up correctly

### ISSUE THREAD

**Issue by scharfstein-dev** [junit-team/junit5#1685]
I am using JUnit 5.3.1 with Gradle 4.10.2 in the context of a medium sized application with a fair bit of legacy infrastructure, both for tests and for the build. I am trying to run a subset of my tests based on how they are tagged. However, running the following Gradle tasks picks up no tests at all:
```
task testIntegrationTests(type: Test) {
	useJUnitPlatform {
		includeTags 'IntegrationTest'
	}
}
```
This is counter to the fact that such tests exist:
```
import org.myapp.IntegrationTest;
import org.junit.experimental.categories.Category;
import org.junit.jupiter.api.Tag;

@Tag("IntegrationTest")
@Category(IntegrationTest.class)
public class MyAppIntegrationTest {
    ...
}
```
As you can see, the test also is annotated with a JUnit 4 `@Category` annotation. This is where it gets weird, because substituting the following Gradle task for the previously mentioned one works and, in fact, selects the correct subset of tests:
```
task testIntegrationTests(type: Test) {
	useJUnitPlatform {
		includeTags 'org.myapp.IntegrationTest'
	}
}
```
In other words, regular JUnit Platform Tags are not picked up by my Gradle Test Runner, while the autogenerated Category Tags are processed correctly.

I have tried removing the Category annotations altogether, to no discernible effect.

My hypothesis at this point is that I am seeing some weird corner case possibly created by the interplay of some dependencies, so I am going to provide the full set here:
```
'org.junit.jupiter:junit-jupiter-api:5.3.1',
'org.junit.jupiter:junit-jupiter-engine:5.3.1',
'org.junit.jupiter:junit-jupiter-params:5.3.1',
'org.junit.vintage:junit-vintage-engine:5.3.1',
'org.junit.platform:junit-platform-launcher:1.3.1',
'org.junit.platform:junit-platform-suite-api:1.3.1',
'junit:junit:4.12',
'org.assertj:assertj-core:3.11.1',
'org.mockito:mockito-core:2.19.0',
'nl.jqno.equalsverifier:equalsverifier:2.4.7'
```
My question: How can I proceed debugging this to produce a minimal test case? I have found next to no information about tracing test discovery and selection through Gradle and JUnit Platform, so I am posting here in hope of some advice. What information can I provide that will make debugging this possible?
(Note that my reason for not providing full build scripts here is that they are a horrible mess spread over twenty files that will take some considerable effort to comprehend, but if necessary I can post relevant extracts)

**Comment by marcphilipp** [comment]
Thanks for raising the issue! If categories are processed, that means the Vintage engine considers `MyAppIntegrationTest` to be a JUnit 3/4 test. 

@scharfstein-dev Which `@Test` annotations are you using?

**Comment by scharfstein-dev** [comment]
Interesting! Indeed I am using both JUnit 4 and JUnit Jupiter `@Test` annotations along different test type hierarchies. I have just verified that along a hierarchy using Jupiter annotations, the Tags work as expected for me. The original behavior occurs only for hierarchies that don't have any Jupiter tests.

Along the way, I also found out that using something like this is a strict no-no:
```
	useJUnitPlatform {
		includeTags 'UiTest'
	}
	include '**/com/myapp/test/landing/**'
```
When I wrote it I kind of thought of the two includes as complementary to each other, but I guess `includeTags` only filter the regular `include`, correct?

Anyway, is the above expected behaviour, i.e. is annotating a vintage test with a Jupiter Tag a bad idea? This would be a bit awkward compatibility-wise, because I have three distinct use cases:
1) Execute a subset of all tests that are exclusively using Jupiter features and have a `@Tag` annotation
2) Execute a subset of all tests that are exclusively using Vintage features and have a `@Category` annotation
3) Execute the subset of all tests that have neither `@Tag` nor `@Category` annotations and which are a mix of Jupiter and Vintage JUnit

Especially point 3 seems to suggest that I would need to annotate the tests from point 1 with `@Category` as well as `@Tag`, which I would rather avoid if possible. Are my assumptions off here, do I need to annotate my new tests with vintage annotations, or what do you think?

**Comment by scharfstein-dev** [comment]
Thanks, this is very helpful - I think I'll end up using `@Tag("org.myapp.IntegrationTest")` for the transition period. Sorry about the confusion, but I think I understand the concepts better now :)

**Comment by marcphilipp** [comment]
No worries, thanks for asking! 🙂
