### ISSUE TITLE
Discovery selector & filter model does not work with dynamically registered tests

### ISSUE THREAD

**Issue by npryce** [junit-team/junit5#1687]
I'm writing a TestEngine against JUnit 5.3.1.

The test engine I am writing registers tests dynamically, during the execution phase rather than discovery.

In the current engine API, discovery selectors and filters are passed to the `discover` method of the engine in the `EngineDiscoveryTest`, but not to the `execute` method in the `ExecuteRequest`. This means that selectors and filters are not available to be applied to dynamically registered tests.

For example, this means that there is no way to run an specific dynamically registered test identified by a UniqueIdSelector.

Suggested solution: pass the selectors and filters to the execute phase in the `ExecuteRequest`.

**Comment by sormuras** [comment]
Work-around: store the selectors and filters passed to your engine instance and re-use them when executing tests.

**Comment by marcphilipp** [comment]
That's what we do for dynamic tests and test template invocations:

https://github.com/junit-team/junit5/blob/dff15fb145efd34629582e469f657ad64490e22b/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java#L146-L151

Thus, I'm inclined to close this issue. Any objections?

**Comment by npryce-springer** [comment]
Aha, @marcphilipp!  You store the selectors and filters in the engine descriptor that's a much better solution than storing them in mutable state in the engine itself.  Thanks.  I'll do that.

**Comment by sormuras** [comment]
True. Much better. Updated my comment above.

> Thus, I'm inclined to close this issue. Any objections?

No.
