### ISSUE TITLE
Interrupted test cases cause random failures with thread reuse

### ISSUE THREAD

**Issue by bacer-esteco** [junit-team/junit5#1688]
## Status Quo

Whenever a test case is interrupted (`Thread.interrupt()`), the test runner thread seems to stay in interrupted state. This causes random failures later when the thread is reused for other test cases.

## Expected Behavior

When the thread is reused, the interrupted flag for the thread is cleaned before starting a new test case. This can be done by calling `Thread.interrupted()`, which returns the interrupted state and clears the interrupted flag.

## Steps to Reproduce

The following code reproduces the problem (when run against JUnit Jupiter 5.4 snapshots), given that `test1()` is run before `test2()`.

```java
package example;

import org.junit.jupiter.api.MethodOrderer.Alphanumeric;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@TestMethodOrder(Alphanumeric.class)
class ThreadTests {

  @Test
  void test1() {
    Thread.currentThread().interrupt();
  }

  @Test
  void test2() throws InterruptedException {
    Thread.sleep(1000);
  }

}
```

## Analysis

This problem is reproducible using both Jupiter and Vintage (tried on version 5.3.1), launching the test both from Gradle 4.10.2 and IntelliJ IDEA 2018.3 (and previous).

I guess it is the same exact bug reported in JUnit 4 (https://github.com/junit-team/junit4/issues/1365)

## Deliverables

- [x] Reset the interrupted flag before/after executing a `Node`.
- [x] Document in Release Notes.

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 M1 for _team discussion_.

**Comment by sbrannen** [comment]
I added `@TestMethodOrder(Alphanumeric.class)` to the example and verified that `test2()` always fails on `master`.

**Comment by sbrannen** [comment]
Inserting `Thread.interrupted();` as the first line in `org.junit.platform.engine.support.hierarchical.NodeTestTask.execute()` allows the example test class to execute correctly.

@junit-team/junit-lambda, As for whether or not that is the correct location to invoke `Thread.interrupted();` is open for discussion.

**Comment by sbrannen** [comment]
I have removed the `Vintage` label since the invocation of JUnit 4 tests is handled by the corresponding JUnit 4 `Runner` which is not under the control of the `VintageTestEngine`.

**Comment by marcphilipp** [comment]
**Team Decision:** Reset the flag before/after executing a `Node`.
