### ISSUE TITLE
Add Launcher execute() method that accepts the TestPlan returned by discover()

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1695]
## Overview

IDEs and build tools use the `org.junit.platform.launcher.Launcher` interface to discover and run tests. However, the interface does not provide a means to run rests with a previous discovered test plan. This results, at least for IntelliJ, in that test engines will be asked twice to come up with the same test plan. See: https://youtrack.jetbrains.com/issue/IDEA-203173 for details.

Since discovery often involves classpath scanning this can be a real performance hit in large projects.

## Proposal

Add interface method `void execute(TestPlan)` to the interface to allow reuse of already discovered test plan.

### Alternative

If the suggestion above is difficult to realize. Cache a discovered test plan that results from an identical `LaunchDiscoveryRequest` object.

## Deliverables

- [ ] Introduce a new `void execute(TestPlan)` method in the `Launcher` API.
  - [ ] Implement appropriate tests.
- [ ] Add checks to `TestPlan` that throw an exception if the _user_ attempts to modify the state of the `TestPlan` after discovery has completed.
  - [ ] For the above, we will need some form of _state_ within the `TestPlan` to track if discovery has completed.
  - [ ] Implement appropriate tests.
- [ ] Document in User Guide.
- [ ] Document in Release Notes.

**Comment by marcphilipp** [comment]
Thanks for reporting the issue! I was not aware that IDEA first called `discover` and then `execute`. I think they should be able to use `TestExecutionListener.testPlanExecutionStarted(TestPlan)` instead of calling `discover` since the intend is to execute tests, not just display them. I responded on the linked IDEA issue.

IIRC I removed the `execute(TestPlan)` method because `TestEngines` cannot be expected to be able to work with potentially modified `TestPlans`. For instance, `TestPlan` exposes an `add()` method. In hindsight it should probably have been an interface.

I'll wait for @akozlova to reply before closing this issue.

**Comment by marcphilipp** [comment]
[Reply](https://youtrack.jetbrains.com/issue/IDEA-203173#focus=streamItem-27-3199177-0-0) from @akozlova:

> looks like it's possible, thanks

I've clarified when `Launcher.discover()` should be used and how to get access to the `TestPlan` without calling it in d0616e59d0.

**Comment by noopur2507** [comment]
Eclipse has the same issue reported in [bug 542742](https://bugs.eclipse.org/bugs/show_bug.cgi?id=542742).

**Comment by marcphilipp** [comment]
@noopur2507 Thanks for the link! Please let us know whether the proposed solution works for you as well.

**Comment by noopur2507** [comment]
The proposed solution to avoid calling `Launcher.discover()` first is not straight-forward for Eclipse. The existing implementation in Eclipse is generic for all versions of JUnit based on a sequence of notifications in the IDE. With the suggested solution to invoke `Launcher.execute()` directly, the notifications order in the IDE will be impacted e.g. the test execution may start via `Launcher.execute()` before the tree is ready. It may be possible to make it work differently for JUnit 5 with considerable effort by adding some waits/notifications etc. but it will not be a clean solution and I am not inclined towards making such changes.

It will be good to have a way in JUnit 5 also to pass a test plan to execute. A `Launcher.execute(TestPlan)` or `TestPlan.execute()` method can be added with a disclaimer to the clients to not modify the `TestPlan` before calling it.

**Comment by sbrannen** [comment]
Reopened in light of the feedback from @noopur2507 for _team _discussion_.

**Comment by sbrannen** [comment]
**Team Decision**:

- Introduce a new `execute(TestPlan)` method in the `Launcher` API.
- Add checks to `TestPlan` that throw an exception if the _user_ attempts to modify the state of the `TestPlan` after discovery has completed.
- For the above, we will need some form of _state_ within the `TestPlan` to track if discovery has completed.

I will add a new _Deliverables_ section to this issue covering the above.

This new feature is currently slated 5.4 M2.

**Comment by sbrannen** [comment]
> I will add a new _Deliverables_ section to this issue covering the above.

✅

**Comment by noopur2507** [comment]
Thank you for considering this.
