### ISSUE TITLE
Make ParameterizedTestExtension public.

### ISSUE THREAD

**Issue by grunenwflorian** [junit-team/junit5#1696]
Hi,

Using Using: JUnit: 5.3.2

## Problem
Let's assume that I am testing on different browsers that a title, on a single website, is equals to "Junit5". I do that using the convenient test template (TestTemplateInvocationContextProvider) feature. A TestTemplateInvocationContext by browser. That scenario works really well.

As of today a new use case came up. I need to do the same on two different sites and one of them will always have "Junit4" for title.

## What I want to do :
I would like to mix my custom Extension with the ParameterizedTestExtension extension.

### What I guessed after a quick look at the Jupiter Engine
Annotating the tests methods with both annotations (SeleniumExtension and ParametrizedExtension) does not work. This is expected as the jupiter engine only picks and uses only the first TestTemplateInvocationContextProvider he finds.
That behavior makes perfect sense as it is impossible to easily guess how the two lists of TestTemplateInvocationContext should be merged.

## How I would do it
My idea is to create a TestTemplateInvocationContextProvider wrapper containing both Extensions that way I could choose how to merge them.

Unfortunately, ParametrizedExtension is not public and I'd rather avoid using introspection to get the object.

## Deliverables
Would you consider making ParametrizedExtension public ? Or do you have a better idea ?

Thanks for your help.

**Comment by marcphilipp** [comment]
Thanks for raising the issue! We plan to address this use case by allowing test classes to be parameterized. Then, you could use `SeleniumExtension` to provide an invocation context for your test class and `ParametrizedExtension`, i.e. `@Parameterized`, for the method (see #871).
