### ISSUE TITLE
Introduce support for type information in TestExecutionContext

### ISSUE THREAD

**Issue by ttddyy** [junit-team/junit5#17]
`TestExecutionContext` is hierarchical, and currently there are _"engine"_, _"class"_, and _"method"_ context types. 
However, once context is created, there is no simple indication of which type it is.

I think it would be better that `TestExecutionContext` would have some API that can easily distinguish context type.

Implementation may be:
- keep `TestDescriptor` which is passed at constructor of `DescriptorBasedTestExecutionContext`, then user can do  `context.getDescriptor() instanceof ClassTestDescriptor`.
- or, can have `getContextType()` method that returns simple enum such like:
```java
public enum TestExecutionContextType {
  ENGINE, CLASS, METHOD
}
```

**Comment by sbrannen** [comment]
Hi @ttddyy,

Can you please tell us what use cases you to hope to be able to support with such additional _contextual_ information?

In other words, how does the lack of this information in the current prototype hinder you from achieving your goal?

Thanks,

Sam

**Comment by ttddyy** [comment]
One of the usage I was thinking is for asserting `TestExecutionContext`.
While writing a method which handles `TestExecutionContext`, I would like to prevent wrong context to be passed or used.

```java
@Override
public void postAfterEach(TestExecutionContext testExecutionContext, Object testInstance) throws Exception {
    updateContext(testExecutionContext);  // should pass parent context
}

@Override
public void postAfterAll(TestExecutionContext testExecutionContext) throws Exception {
    updateContext(testExecutionContext);
}

private void updateContext(testExecutionContext) {
    assert context.getType() == ContextType.CLASS;
    ....
}
```

It can be prevented if user knows which hierarchy of context should be passed. However, without context type, documentation will be the only way to prevent wrong usage of API.

May be this is too much thinking for defensive programming, but it may protect from developers wondering about unintended behavior.


On the other hand, defining context types makes less flexible of introducing other types. 
It may be good to have `CUSTOM` type for user defined context type(if needed) when there will be `ENGINE`, `CLASS`, `METHOD` types defined as enum. 
Or, `getType()` can be `String` that returns `"engine"`, `"class"`, `"method"`, or user defined String for custom context.

**Comment by sbrannen** [comment]
@ttddyy, since the `TestExecutionContext` from the prototype has been split up into `ContainerExtensionContext` and `TestExtensionContext`, do you still foresee the need for additional _type information_?

**Comment by ttddyy** [comment]
Thanks for the update.

If we introduce engine/global callbacks, they may need additional marker interfaces.
But I think `ContainerExtensionContext` and `MethodInvocationContext` are enough for now, along with the fact that *ExtensionContext.Store* can transparently resolve values from parent Store.

So, probably you can close this issue. 

Thanks,

**Comment by sbrannen** [comment]
Thanks for the feedback. I'll go ahead and close this issue.
