### ISSUE TITLE
JUnit data sets - Not failing when looking for NULL, if value is present.

### ISSUE THREAD

**Issue by stacksamus** [junit-team/junit5#1700]
Hello. Used both JUnit 4.12 and 4.13-beta-1. Also dbUnit 3.4.2 and 3.4.6 and also xmlunit both 1.3 and 1.6.

Firstly apologies if this is in the wrong place. I am also unsure if this issue is JUnit or dbUnit. 

We are creating JUnits and using xml datasets as an expected result following running tests, to ensure data is as expected on our Oracle database.

We are now finding an issue, where if we look for null values in our dataset ([null]), it does not fail if the column we are checking does actually contain a value.

If we specify a value in the data set, which is different to the actual value in the colum, it will fail and tell us the difference.

So the issue is that the data set does not detect if a column has a value it in, when our data set is looking for a NULL value.

In the code snippet below, if there is a value on the table 'TABLE_NAME' in the column 'COLUMN_THREE', it will not throw an error.

```
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:exap="schema_instance" >

  <exap:TABLE_NAME COLUMN_ONE="1" COLUMN_TWO="STACKSAMUS" COLUMN_THREE="[null]" />  
  
 </dataset>
```

Thank you very much for any information or help that can be provided and to all those who have put the work into this framework.

Stacks

**Comment by marcphilipp** [comment]
Sounds like an issue with dbUnit. Have you tried asking on StackOverflow? I'm closing this issue because this repo is for JUnit 5. If it turns out to be a JUnit issue after all, please open an issue in https://github.com/junit-team/junit4/.

**Comment by stacksamus** [comment]
> Sounds like an issue with dbUnit. Have you tried asking on StackOverflow? I'm closing this issue because this repo is for JUnit 5. If it turns out to be a JUnit issue after all, please open an issue in https://github.com/junit-team/junit4/.

Thank you :)
