### ISSUE TITLE
Overloaded assertions should work from Groovy

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1710]
The overloaded assertions introduced as part of #1638 broke Groovy's dynamic method dispatch. For example the following code yields the following exception:

```groovy
assertEquals(2, new Integer(2), "some message")
```

```
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method org.junit.jupiter.api.Assertions#assertEquals.
Cannot resolve which method to invoke for [class java.lang.Integer, class java.lang.Integer, class java.lang.String] due to overlapping prototypes between:
	[int, class java.lang.Integer, class java.lang.String]
	[class java.lang.Integer, int, class java.lang.String]
```

Adding an overload that matches `[class java.lang.Integer, class java.lang.Integer, class java.lang.String]` exactly might solve the issue.

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.4 M1

## Deliverables

- [ ] Make Groovy's dynamic dispatch work with the new overloaded methods

**Comment by sbrannen** [comment]
Let's see if "compile static" _solves_ the problem for Groovy. 😉

**Comment by sbrannen** [comment]
**Team Decision**:

- Initial investigations for @marcphilipp show that `@CompileStatic` _improves_ the situation. We should therefore document that option in the User Guide.
- Introduce new overloaded `assertEquals(<wrapper type>, <wrapper type>, ...)` variants to further improve Groovy's ability to select the appropriate overloaded method.

**Comment by marcphilipp** [comment]
Additional overloads also need to be added for `assertNotEquals(<wrapper type>, <wrapper type>, ...)`.

@mmerdes I've pushed my experimentation branch to [issues/1710-groovy-assertions-fixes](https://github.com/junit-team/junit5/tree/issues/1710-groovy-assertions-fixes).

**Comment by sormuras** [comment]
@kreinhard found a similar issue using Kotlin here: https://github.com/micromata/projectforge/blob/PROJECTFORGE-3614-ReactJS/projectforge-jax-rs/src/test/kotlin/org/projectforge/rest/json/JsonValidatorTest.kt#L27

It compiles but produces the following at runtime:
```
java.lang.NoSuchMethodError: org.junit.jupiter.api.Assertions.assertEquals(ILjava/lang/Integer;)V
	at org.projectforge.rest.json.JsonValidatorTest.parseJson(JsonValidatorTest.kt:27)
```

**Comment by marcphilipp** [comment]
Sounds like a Kotlin bug...

**Comment by marcphilipp** [comment]
@sormuras Please create a new issue. 🙂

**Comment by kreinhard** [comment]
Thanx, yesterday I’ve migrated all 179 Testclasses from TestNG to JUnit 5 and all problems disappeared. I guess, that Intellij got into trouble due to multiple test engines: TestNG, JUnit 4 and JUnit 5. There rest half a dozen of JUnit 4 test classes, but they work fine with maven as well as with Intellij now.

BTW: Excellent job, guys! I appreciate JUnit 5.
