### ISSUE TITLE
JUnit BOM should not include scope declarations for managed dependencies

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1712]
## Overview

In https://github.com/junit-team/junit5/issues/1629#issuecomment-450031271, @eggilbert brought it to our attention that the `junit-bom` released in 5.4 M1 now contains `<scope>compile</scope>` entries that cause problems. This is in contrast to previous releases of the `junit-bom` and violates "best practices" for dependency management in Maven BOMs.

## Related Issues

- #1629 

## Deliverables

- [ ] Ensure that dependencies in the `junit-bom` do not include `<scope>...</scope>` declarations.

**Comment by marcphilipp** [comment]
_in progress_
