### ISSUE TITLE
New line characters in (dynamic) display names

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1713]
New line characters may disrupt layout of the tree-based test plan rendering:

```
[INFO] Launching JUnit Platform 1.4.0-M1...
[INFO] .
[INFO] '-- JUnit Jupiter [OK]
[INFO]   +-- LayoutTests [OK]
[INFO]   | +-- readModuleName() [OK]
[INFO]   | | +-- module a { [OK]
[INFO]   | | +-- open module a{ [OK]
[INFO]   | | '-- what ever 
[INFO]  prefix module    a   
[INFO] { [OK]
[INFO]   | '-- checkMavenProjects() [OK]
...
```

Other [ASCII control characters](https://en.wikipedia.org/wiki/Control_character) may even produce side-effects or more severe issues.

Should the tree renderer replace those control characters before emitting them?

What about other display name emitters, like reporting?

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 M2 for _team discussion_.

**Comment by sbrannen** [comment]
**Team Decision**:

- _Sanitize_ display names before they are output via the `ConsoleLauncher`.
  - Consider introducing a sanitizing convenience method somewhere in `junit-platform-commons`.
- Do not do anything to display names otherwise. In other words, due to backward compatibility constraints (e.g., `TestDescriptor#getDisplayName()`), we cannot enforce any rules other than "not null and not blank". Build tools and IDEs are responsible for _consuming_ display names and deciding how to display them.

**Comment by sbrannen** [comment]
Here's a new example in our own test suite.....

https://travis-ci.org/junit-team/junit5/jobs/475989143#L819

😉

**Comment by sbrannen** [comment]
FYI: that comes from the new examples for `@NullSource` and `@EmptySource` introduced in #1637.

**Comment by sbrannen** [comment]
It actually occurs twice: once in the above link, and [here](https://travis-ci.org/junit-team/junit5/jobs/475989143#L828) as well.

**Comment by sbrannen** [comment]
FWIW, I noticed that Eclipse IDE simply displays all of those display names containing only whitespace, newlines, etc. as an _empty_ string in the GUI.

**Comment by sormuras** [comment]
_in progress..._

**Comment by sormuras** [comment]
> Here's a new example in our own test suite.....
> https://travis-ci.org/junit-team/junit5/jobs/475989143#L819

```
│  │  ├─ NullAndEmptySource_2 ✔
│  │  │  └─ nullEmptyAndBlankStrings(String) ✔
│  │  │     ├─ [1] null ✔
│  │  │     ├─ [2]  ✔
│  │  │     ├─ [3]   ✔
│  │  │     ├─ [4]     ✔
│  │  │     ├─ [5] 	 ✔
│  │  │     └─ [6] 
 ✔
│  │  └─ NullAndEmptySource_1 ✔
│  │     └─ nullEmptyAndBlankStrings(String) ✔
│  │        ├─ [1] null ✔
│  │        ├─ [2]  ✔
│  │        ├─ [3]   ✔
│  │        ├─ [4]     ✔
│  │        ├─ [5] 	 ✔
│  │        └─ [6] 
 ✔
```
...is now emitted (Windows) as:
```
| | +-- NullAndEmptySource_2 [OK]
| | | '-- nullEmptyAndBlankStrings(String) [OK]
| | |   +-- [1] null [OK]
| | |   +-- [2]  [OK]
| | |   +-- [3]   [OK]
| | |   +-- [4]     [OK]
| | |   +-- [5] . [OK]
| | |   '-- [6] . [OK]
| | '-- NullAndEmptySource_1 [OK]
| |   '-- nullEmptyAndBlankStrings(String) [OK]
| |     +-- [1] null [OK]
| |     +-- [2]  [OK]
| |     +-- [3]   [OK]
| |     +-- [4]     [OK]
| |     +-- [5] . [OK]
| |     '-- [6] . [OK]
```
