### ISSUE TITLE
@ParameterizedTest name only supports String formatters (no numbers, etc) 

### ISSUE THREAD

**Issue by t-8ch** [junit-team/junit5#1714]
## Steps to reproduce

```java
@ParameterizedTest(name="{0,number}")
@ValueSource(ints = {1, 2, 3})
void someTest(int testInt) {
    assertTrue(testInt > 0);
}
```

results in the following error during test discovery:

```
org.junit.platform.commons.JUnitException: The display name pattern defined for the parameterized test is invalid. See nested exception for further details.
	at org.junit.jupiter.params.ParameterizedTestNameFormatter.formatSafely(ParameterizedTestNameFormatter.java:76)
...
Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.text.DecimalFormat.format(DecimalFormat.java:507)
	at java.text.Format.format(Format.java:157)
	at java.text.MessageFormat.subformat(MessageFormat.java:1322)
	at java.text.MessageFormat.format(MessageFormat.java:865)
```

This happens because `ParameterizedTestNameFormatter.format()` transforms all arguments into strings before invoking the `MessageFormat.format()` method. The `DecimalFormatter` however only works with numbers.

Being able to use the full range of `MessageFormat` would be useful to pad the parameter names. Also the javadoc for `ParameterizedTest.name` sounds to me, as if this functionality is supposed to be supported.

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.3.2
 - Build Tool/IDE: N/A

**Comment by t-8ch** [comment]
```java
// junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java

@Test
void formatSupportsSubformatters() {
    ParameterizedTestNameFormatter formatter = new ParameterizedTestNameFormatter("{0,number}", "enigma");
    assertEquals("15", formatter.format(1, 15));
}
```

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 M2 for _team discussion_.

**Comment by sbrannen** [comment]
**Team Decision**: revert to previous logic that supported formats other than strings; if that fails (within a try-catch block), use the newer "format safely" mechanism.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I'll take a slightly different approach:
1. Convert all arguments to Strings (like before) that don't use a explicit format
2. Call `MessageFormat.format()`

**Comment by t-8ch** [comment]
Thanks!

**Comment by sbrannen** [comment]
> I'll take a slightly different approach:
> 
>     1. Convert all arguments to Strings (like before) that don't use a explicit format
> 
>     2. Call `MessageFormat.format()`

Interesting idea. I'll have a look. 😉
