### ISSUE TITLE
Introduce platform mechanism to switch off conditions

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1717]
https://github.com/junit-team/junit5/issues/78 solved the problem for just Jupiter and (probably) Vintage. If other engines introduce the same all IDEs will have to adapt to each engine's naming of params and values.

I suggest to either:
- Choose config param name that is agnostic to engine. Currently it is `junit.jupiter.conditions.deactivate`.  This will also require to standardize the possible values which currently refer to class names in Jupiter/Vintage.
- Add dedicated property  in `ConfigurationParameters` e.g. `ConfigurationParameters.getDeactivatedConditions() : List<ConditionType>`.

Any other ideas?

**Comment by marcphilipp** [comment]
The problem has not yet been solved for Vintage either, cf. #605.
