### ISSUE TITLE
TestIdentifier.isDisplayNameSet()

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#172]
Would be cool to have testIdentifier.isDisplayNameSet(). The background:

user may setup display name and default names are provided by the TestDescription by method/class names. Say we want to run all tests in the package, we don't want to repeat fully qualified class names when package already contains this name. In junit 4, IDE could just check startsWith on strings but now that could lead to strange results.

**Comment by akozlova** [comment]
Relates to #153 I suppose

**Comment by marcphilipp** [comment]
Can you use `TestIdentifier#getSource` and check whether present and instance of `JavaSource`? That's the preferrable way to determine the source location of a `TestIdentifier`.

**Comment by akozlova** [comment]
Yes, I can determine if annotation was present, no problem but looks like you already have the information and it would be a common place? I don't insist anyway

**Comment by marcphilipp** [comment]
If I understand you correctly you want to check whether the display name is set in order to decide what to display in the test tree UI, right? If display name is set you will just display it? If not you want to to some special post-processing to remove the package name, right?

My answer was targeting the post-processing step. Our API to get the Java class of a `TestIdentifier` is `TestIdentifier#getSource`:

```java
TestIdentifier testIdentifier = ... // some value
Optional<TestSource> source = testIdentifier.getSource();
if (source.isPresent() && source.get() instanceof JavaSource) {
    JavaSource javaSource = source.get();
    if (javaSource.getJavaClass().isPresent()) {
        Class<?> javaClass = javaSource.getJavaClass().get();
    }
}
```

Regarding the first problem (determining whether display name is set) I think that's a good point and should be addressed in #153. I'm wondering whether it would be best to change the return type of `getDisplayName()` to `Optional<String>` instead of adding an additional method. However, that would force users to write `testIdentifier.getDisplayName().orElseGet(() -> testIdentifier.getName())`.

@junit-team/junit-lambda What do you guys think?

**Comment by jlink** [comment]
Not sure I understand the use case you describe, but I'll clarify what @marcphilipp was aiming at. I think what you want is calling `getSource().getJavaClass()` (returns `Class<?>`) on a test identifier representing a test class.  If it's a method then you'll have to get the parent - `testPlan.getParent(testIdentifier)` - first. With that information you can collect all classes in the same package into one group / node.

We have also been thinking about having packages as nodes in the tree of test identifiers. Would that make your life easier?

**Comment by jlink** [comment]
@marcphilipp As for #153: If `getName()` is the default value of `getDisplayName()` as suggested, one could always compare the two to see if display name has been overridden.

**Comment by akozlova** [comment]
Guys, I understand how I can check if the display name was set explicitly, I just thought that this would be a common place so probably you could provide API. If not, feel free to close.

Thanks

**Comment by bechte** [comment]
@akozlova : @jlink raised a question that we had a discussion about some weeks ago, that we couldn't answer ourselves as we are not the consumer of the test plan. I would really like to get your feedback about this topic:

> We have also been thinking about having packages as nodes in the tree of test identifiers. Would that make your life easier?

This definitely does not support the idea in this ticket, but could you answer this question in general?

Would it be nice to have the package structure be reflected in the test tree? It would also support to have features like group tests by module/package in the UI. What do you think?

**Comment by akozlova** [comment]
this sounds cool but then you get problems with suites: how to pass it into the hierarchy when the suite contains tests from different packages.

The problem what I have in mind is flattening: I get tree like 
package/
  Junit5/
      MyTestClass/
      ...
the JUnit5 node is overwhelming when there is no another engines worked. Even when one method is run, the structure is very complex and I am sure that people would complain. I am not sure if you should address this issue as for build tools that should not be a problem but looks like IDEs should simplify the plan.

**Comment by jlink** [comment]
Yes, IDEs can - IMO should - flatten the tree for display, e.g. start with
the first level that contains more than one node.

2016-03-11 8:10 GMT+01:00 Anna Kozlova <notifications@github.com>:

**Comment by sbrannen** [comment]
This issue has been superseded by #153.
