### ISSUE TITLE
Intelligent scheduling of parallel tests with @ResourceLock

### ISSUE THREAD

**Issue by kelunik** [junit-team/junit5#1721]
I'm running a test suite in parallel which uses `@ResourceLock` on a few tests. Most tests don't use any resource locks. There are two tests which lock resource `X`. If the first test runs rather late, the second will have to wait for the first to finish, often being the last test being executed, while the other threads already finished and have nothing left to do.

It would be helpful if all tests with locking would be scheduled before any tests without locking. The workers can pick a lock-less test if there's nothing else. This should on average result in a shorter total execution time, as the blocking of lock-awaiting tests will happen while there are still other tests to be executed by other workers, instead of having a sequential test execution order at the end.

**Comment by zeinabmohamed** [comment]
@kelunik  Hi, did you get sol for you issue as I suffer from  same one .

**Comment by kelunik** [comment]
@zeinabmohamed No, sorry.

**Comment by mheinzerling** [comment]
There seems to be still no solution to this issue, isn't it?
