### ISSUE TITLE
Support File parameters in TempDirectory extension

### ISSUE THREAD

**Issue by rmannibucau** [junit-team/junit5#1725]
## Overview

The `TempDirectory` extension is great but only supports `Path`. I think it does not cost much to support `File`, and it enables to get a more fluent code base for several cases where the `Path` API is not yet the first citizen.

## Deliverables

- [x] Support `File` in addition to `Path` in the `TempDirectory`
- [x] Update Javadoc for `TempDirectory`
- [x] Update "The TempDirectory Extension" section of the User Guide
- [x] Document change in the Release Notes

**Comment by sormuras** [comment]
Thanks for raising this issue. I've tentatively slated this for 5.4 M2 for the purpose of team discussion.

**Comment by jbduncan** [comment]
I personally disagree because I see `File` as effectively deprecated and I find `file.toPath()` very easy for write and read, but I understand that this is a subjective area. :)

**Comment by sormuras** [comment]
I tend to agree with @jbduncan -- using `path.toFile()` in this case. ;-) -- but supporting `File` type here for more convenient usages of _legacy_ libraries would be fine with me.

**Comment by rmannibucau** [comment]
Well File is not deprecated at all and the only way to integrate with several libraries so I guess we are in the case where I agree with your point but think it is worth to do better here, in particular cause the cost is very low as you point out and cause the loose coupling of the API rocks for these things ;).

**Comment by sbrannen** [comment]
FYI: I've add a _Deliverables_ section to this issue.

**Comment by sbrannen** [comment]
**Team Decision**: merge #1726 once all _Deliverables_ have been addressed.

**Comment by rmannibucau** [comment]
@sbrannen i checked the boxes but not sure it was intended to be done by me thinking about it, if not please untoggle them

**Comment by sbrannen** [comment]
> @sbrannen i checked the boxes 

Thanks

> but not sure it was intended to be done by me thinking about it, if not please untoggle them

That's OK. It's our job to review the checked-off things as well. 😉
