### ISSUE TITLE
Test fix for legacy reporting names for Vintage tests

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1728]
## Overview

#1719 provided a fix for the regression in  legacy reporting names for the `VintageTestEngine` but did not introduce integration tests to verify the actual output from Maven Surefire and Gradle.

## Deliverables

- [ ] Introduce integration tests that verify the expected output (e.g., content and names of files) from **Maven Surefire** for Vintage test classes.
- [ ] Introduce integration tests that verify the expected output (e.g., content and names of files) from **Gradle** for Vintage test classes.

**Comment by sormuras** [comment]
Added Gradle to the list of deliverables.
