### ISSUE TITLE
Introduce mechanism to stop test run with first failing test

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1729]
Subject says it all. Would be especially useful for TCR (test && commit || reset) workflow.
Feature could be globally configured or switched of from IDE / build tool.

https://github.com/junit-team/junit5/issues/431 is related and https://github.com/pitest/pitest-junit5-plugin/pull/15 might also profit.

**Comment by marcphilipp** [comment]
I wonder if/how this could be implemented on the platform level. I guess we could provide a platform feature to enable it and add a `isStopped()` method to `ExecutionRequest` which engines should check before starting a execution of a new test. Thoughts?

**Comment by jlink** [comment]
You're right, a new channel from platform to engine is needed to signal the stop. I wonder if such a channel could be used for other useful stuff as well...

The simplest solution I can think of, however, is `System.exit`. I'm not sure, though, what kind of adverse effects that might bring.

**Comment by marcphilipp** [comment]
Since build tools/IDEs run in the same JVM I don't think that would be a viable solution. Moreover, even if a test run's being cancelled, we should stick to the contracts in `TestExecutionListener`.
