### ISSUE TITLE
Parameterized tests: JavaSource doesn't contain method

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#173]
I try to run org.junit.gen5.engine.junit4.samples.junit4.ParameterizedTestCase. I see that org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor#toJavaMethodSource is called and because the method name is test[foo] no methods exactly match this name, so the method returns new JavaSource(testClass).

I need initial string to get navigation, rerun, etc.

In order to determine method name I tried method copied from the junit:
```
private static String getMethodName(TestIdentifier testIdentifier) {
   return testIdentifier.getSource().filter(JavaSource.class::isInstance).map(JavaSource.class::cast).map(source -> source.getJavaMethodName().orElse(null)).orElse(null);
  }
```

**Comment by marcphilipp** [comment]
I think we should definitely try to improve that. Thanks for raising the issue!

**Comment by sbrannen** [comment]
:+1:
