### ISSUE TITLE
Address open issues with TestWatcher API and NodeTestTask.prepare()

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1730]
## Overview

Based on feedback on the `TestWatcher` extension API by @marcphilipp in https://github.com/junit-team/junit5/pull/1393#discussion_r205951408, there are still a few issues that need to be addressed:

> I checked and `context` is indeed `null` when `prepare()` throws an exception which happens when an exception occurs creating the test instance.
> 
> If we want to report such failed tests to extensions as well and I think we should, we need to change `prepare` to add the exception to `ThrowableCollector` instead and add `context.getThrowableCollector().assertEmpty()` to `JupiterTestDescriptor.shouldBeSkipped()` (otherwise a test with a failing constructor could be reported as skipped).
> 
> One more thing I noticed: When something fails on the test class level, e.g. an exception a `@BeforeAll` method, `TestMethodTestDescriptor` never gets called. I think we should clearly document this limitation in the Javadoc of `TestWatcher`.

## Related Issues

- #542 
- #1393 

## Deliverables

- [ ] Investigate and address the aforementioned issues.

**Comment by marcphilipp** [comment]
_in progress_
