### ISSUE TITLE
Add a download link to the JUnit 5 home page

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#1737]
As noted in #1587, the JUnit 5 home page doesn't provide a link to the compiled JARs like JUnit 4's page did.  For the rare user that's not using a dependency management tool with defined repositories, this will give them a place to start their dependency hell.

## Deliverables

- [ ] Add a "Download JARs" link to the "Resources" section of https://junit.org/junit5/ that points to the latest release JARs.
- [ ] Add "Download JAR" links to the `README` in this repository.

**Comment by sbrannen** [comment]
Thanks for raising the issue.

I'll add a deliverable for the README in this repository as well.

**Comment by ifrh** [comment]
I am one of those users whose development environment doesn't use a dependency management tool.
The package manager of my linux distribution  cannot install Junit5, too - because I cannot find any **deb**-Package - unlike for junit3 or junit4.

**Comment by smoyer64** [comment]
I never even realized there was a ``.deb`` package for JUnit ... but when I search for it, it does indeed show up!

```shell
p   jmeter-junit                                        - Load testing and performance measurement application (junit mo
p   junit                                               - Automated testing framework for Java                          
p   junit-doc                                           - Document for JUnit                                            
i A junit4                                              - JUnit regression test framework for Java                      
p   junit4-doc                                          - JUnit regression test framework for Java - documentation      
p   libjunitperf-java                                   - JUnit extensions for performance and scalability testing      
p   libjunitperf-java-doc                               - Documentation for libjunitperf-java                           
p   libtap-formatter-junit-perl                         - Perl module for converting TAP output to JUnit XML output     
p   python-junit.xml                                    - creates JUnit XML test result docs readable by tools such as J
p   python-junitxml                                     - PyUnit extension for reporting in JUnit compatible XML        
p   python3-junit.xml                                   - creates JUnit XML test result docs readable by tools such as J
p   python3-junitxml                                    - PyUnit extension for reporting in JUnit compatible XML   
```

**Comment by smoyer64** [comment]
@ifrh This link provides a very old example of how to run junit from the CLI - https://github.com/selesy/junit5/blob/b427e1177716bebfd80147c92a400c70bb4c95a0/documentation/run-example-tests-via-console.sh.  Please note that the package names and hierarchy have changed but the console package continues to provide an executable JAR.  The trick will be to get everything necessary on the classpath - this was easier before JUnit since there was only one JAR.

I personally don't expect to ever write another ``.deb`` package - will your system install snap packages?

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M2 for _team discussion_

**Comment by ifrh** [comment]
@smoyer64 Sure, I'll describe my development environment. It is a django based webapplication called Praktomat. I want to add JUnit5 support to Praktomat, like there exists support for junit3 and junit4:
https://github.com/ifrh/Praktomat/blob/master/src/checker/checker/JUnitChecker.py#L50

**Comment by marcphilipp** [comment]
@ifrh @smoyer64 Would this be sufficient?

<img width="1233" alt="Screenshot 2019-03-09 at 13 32 13" src="https://user-images.githubusercontent.com/214207/54071659-ed353100-426f-11e9-9c98-bbdf6b0dc1da.png">

**Comment by ifrh** [comment]
I would like to have an direct link usable without JavaScript and a link to a ` junit5-console-standalone.jar` . And a notice is needed what jars should be downloaded if you want to start JUnit5 directly from console.

**Comment by marcphilipp** [comment]
I don't think we should include such a notice on the homepage. There are too many different use cases. Please keep in mind that your use case is not as typical as you might think. Most users use a build tool and rely on its dependency management functionality.

How to use the `ConsoleLauncher` is part of the user guide: https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

Maybe the can think of a way to make that more discoverable?

**Comment by sormuras** [comment]
https://javadoc.jitpack.io/com/github/sormuras/bach/master-99cefd9f29-1/javadoc/Bach.Action.html
![image](https://user-images.githubusercontent.com/2319838/54821184-b87a9e00-4ca1-11e9-92fe-7349b048a96a.png)

Note: the links point to `5.5-M1` at the moment, but they should point to latest GA version, which is `5.4.1`.

**Comment by ifrh** [comment]
@ifrh wrote on Mar 7, 2019:
> [...]
>  I cannot find any deb-Package [for junit5] - unlike for junit3 or junit4 [...] 

@smoyer64 wrote on Mar 8, 2019:
> [...]
> I personally don't expect to ever write another `.deb` package [...]

in mean time someone has written deb packages for junit5 
- https://packages.debian.org/search?keywords=Junit5
- https://packages.ubuntu.com/search?keywords=Junit5

And I think someone will write deb packages for Junit6 as well.
