### ISSUE TITLE
Provide reusable base implementation of test discovery

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1739]
All class-based test engines should handle the following selectors during test discovery:

- `ClasspathResourceSelector`
- `ClasspathRootSelector`
- `ModuleSelector`
- `PackageSelector`
- `UniqueIdSelector`
- `ClassSelector`
- `MethodSelector`

The code required to handle the first four of these is straightforward but repetitive and [easy to forget](https://stackoverflow.com/questions/52780940/kotlintestengine-discover-doesnt-return-any-tests). Moreover, resolving `UniqueIdSelectors` is non-trivial but the implementations of the Jupiter and Vintage engine provide examples of how to handle them correctly. Both use a similar yet slightly different approach. If we implemented the base algorithm once in an extensible way, it could be reused by other test engines. Doing so would reduce the burden on test engine authors and increase consistency across test engine implementations.

## Deliverables

- [ ] Extract an extendable base algorithm for resolving selectors from existing implementations
- [ ] Provide extensible configuration mechanism
- [ ] Provide sensible defaults for class-based test engines
- [ ] Use base algorithm in Jupiter and Vintage
- [ ] Reach out to authors of third-party test engines to get feedback and help them adopt the new base algorithm

**Comment by gopinath-langote** [comment]
@marcphilipp anyone working on this?

**Comment by sbrannen** [comment]
Yes, as you can see above to the left, it's assigned to @marcphilipp and labeled as "in progress".

**Comment by gopinath-langote** [comment]
@sbrannen 👍
