### ISSUE TITLE
 Using the JUnit 5 Standalone Console launcher when classpath points to a different drive in Windows 10, the tests are not detected

### ISSUE THREAD

**Issue by npworkcode** [junit-team/junit5#1744]
I am using the following from a command line:
java -jar junit-platform-console-standalone-1.4.0-M1.jar @junit5learn-args.txt
 
The contents of the junit5learn-args.txt file are:
--include-engine=junit-jupiter
--exclude-engine=junit-vintage
--disable-ansi-colors
--details=verbose
--details-theme=ascii
--fail-if-no-tests
--reports-dir=L:/junit5/reports
--class-path=JavaProjects/Eclipse/junit5learn/target/test-classes
--scan-classpath
 
This works, and the tests are seen and run perfectly.
 
However if my test classes are on a different drive the following errors occur when I try to change –class-path variable:
 
--class-path=L:/JavaProjects/Eclipse/junit5learn/target/test-classes 
Results in: Test plan execution started. Number of static tests: 0
 
--class-path=”L:/JavaProjects/Eclipse/junit5learn/target/test-classes” or 
--class-path=’L:/JavaProjects/Eclipse/junit5learn/target/test-classes’
Results in:
Error parsing command-line arguments: Unmatched argument: L:JavaProjectsEclipsejunit5learn      arget   est-classes
 
In addition, is there a way to add comments to the Junit 5 Arguments file?
[junit5learn-args.txt](https://github.com/junit-team/junit5/files/2791183/junit5learn-args.txt)

**Comment by sormuras** [comment]
Can you please try: `--class-path=L:\\JavaProjects\\Eclipse\\junit5learn\\target\\test-classes`?

**Comment by sormuras** [comment]
> In addition, is there a way to add comments to the Junit 5 Arguments file?

Use `#` as the first character of a line.

For more details see: https://picocli.info/#AtFiles

**Comment by npworkcode** [comment]
If I use the quotes or use the double backslashes I get the following error:
Error parsing command-line arguments: Unmatched argument: L:\JavaProjects\Eclipse\unit5learn\target\test-classes
Usage: ConsoleLauncher [-h] [--disable-ansi-colors] [--fail-if-no-tests] [--scan-modules]
However if you look at my attached argument file, you will see that the following line works fine:
--reports-dir=L:/junit5/reports

Don't understand when I specify the location of the testfiles, it fails.

When I try to use the # tag as the first character of a line, as the picocli parser encourages, I get:
Error parsing command-line arguments: Unmatched arguments: #--disable-ansi-colors

**Comment by sormuras** [comment]
> When I try to use the # tag as the first character of a line, as the picocli parser encourages, I get:
Error parsing command-line arguments: Unmatched arguments: #--disable-ansi-colors

My fault, talked to early and without checking our configuration. We disable comments by:

https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java#L278

**Comment by sormuras** [comment]
Can you please try the "simplified at files" mode of Picocli? Seems to work on my box.

`java -Dpicocli.useSimplifiedAtFiles=true -jar junit-platform-console-standalone-<version>.jar @junit5learn-args.txt`

With this layout (one line is one argument) of your `@file`:
```
--include-engine
junit-jupiter
--exclude-engine
junit-vintage
--disable-ansi-colors
--details
verbose
--details-theme
ascii
--fail-if-no-tests
--reports-dir
L:\junit5\reports
--class-path
L:\JavaProjects\Eclipse\junit5learn\target\test-classes
--scan-classpath
```

**Comment by npworkcode** [comment]
Thanks for the help but I keep the console launcher is not finding the test classes.
I have included the output I get via a jpg snapshot. The comment character still leads to a parsing error.

--include-engine
junit-jupiter
--exclude-engine
junit-vintage
--disable-ansi-colors
--details
verbose
--details-theme
ascii
--fail-if-no-tests
--reports-dir
L:/junit5/reports
--class-path
L:/JavaProjects/Eclipse/unit5learn/target/test-classes
--scan-classpath
![junit5consoleerror](https://user-images.githubusercontent.com/38742048/51674696-64a05100-1f9f-11e9-8c67-7c1430d00cde.jpg)

**Comment by sormuras** [comment]
> The comment character still leads to a parsing error.

That is expected. Using the "simplified at files" switch does not override the hard-coded configuration within the console launcher parser.

Does `L:\JavaProjects\Eclipse\junit5learn\target\test-classes` really contain compiled test classes? Just in case... and please use single backslashes `\` in the `junit5learn-args.txt` file.

One more try for today: let's `java` care for building up the class-path.
Change the command to: `java -Dpicocli.useSimplifiedAtFiles=true -cp C:\java\jars\junit\unit-platform-console-standalone-1.4.0-M1.jar;L:/JavaProjects/Eclipse/unit5learn/target/test-classes org.junit.platform.console.ConsoleLauncher @file`

With `@file` contents:
```
--include-engine
junit-jupiter
--exclude-engine
junit-vintage
--disable-ansi-colors
--details
verbose
--details-theme
ascii
--fail-if-no-tests
--reports-dir
L:/junit5/reports
--scan-classpath
```

**Comment by npworkcode** [comment]
Thanks a lot Sormuras, that worked perfectly.
(Sorry for the late response, had to drop the little ones to school).
Thank you again for your time and expertise.
Have a great day and weekend!

**Comment by npworkcode** [comment]
Ok. So I intend to keep experimenting.
I used the following command line, reverted the argument file to key=value pairs and removed the picole simplefile option and got the test classes to run successfully.
java  -cp c:\java\jars\junit\junit-platform-console-standalone-1.4.0-M1.jar;L:/JavaProjects/Eclipse/junit5learn/target/test-classes org.junit.platform.console.ConsoleLauncher @junit5learn-args.txt
![junit5consolesuccess](https://user-images.githubusercontent.com/38742048/51687479-95dd4900-1fc0-11e9-87b8-d024eef121ab.jpg)
