### ISSUE TITLE
Remove apiguardian dependency from published POM of org.junit.jupiter:junit-jupiter

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1745]
While being pulled in transitively anyway, the POM unnecessarily references apiguardian as a direct dependency because of our build setup. 

## Deliverables

- [ ] Remove apiguardian from org.junit.jupiter:junit-jupiter aggregator project

**Comment by sormuras** [comment]
Tried it via 'configurations.all ... exclude()' and via excluding it for each dependency declaration to no avail.

**Comment by sormuras** [comment]
transitive false doesn't work either. Guess we have to remove that module from the list of dependencies just before the generatePomFileForMavenPublication

**Comment by sormuras** [comment]
_in progress..._

```
publishing {
	publications {
		create<MavenPublication>("mavenJava") {
			from(components["java"])
			afterEvaluate {
				configurations.all {
					dependencies.removeIf{
						it.group == "org.apiguardian"
					}
				}
			}
		}
	}
}
```
...seems to work. Writing an integration test that verifies that only `junit-jupiter-api`, `junit-jupiter-params` and `junit-jupiter-engine` are listed in the `<dependencies>` element.
