### ISSUE TITLE
Delete junit-platform-surefire-provider from documentation

### ISSUE THREAD

**Issue by Tibor17** [junit-team/junit5#1751]
Delete `junit-platform-surefire-provider` from documentation https://junit.org/junit5/docs/current/user-guide

The users still refer to it and report fake bugs in Surefire JIRA.

Rather put this link to your documentation
https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html

**Comment by sormuras** [comment]
The new user-guide already points to the Maven Surefire documentation and says:

> **The JUnit Platform Maven Surefire Provider has been discontinued**
> The junit-platform-surefire-provider, which was originally developed by the JUnit team, was deprecated in JUnit Platform 1.3 and discontinued in 1.4. Please use Maven Surefire’s native support instead.

https://junit.org/junit5/docs/snapshot/user-guide/#running-tests-build-maven

It will be the default user-guide when 5.4 GA is shipped ... in a few days.

**Comment by sormuras** [comment]
Closing this issue as all work is done on `master`. Please feel free to open it if you think the new section lacks information or is not clear enough.
