### ISSUE TITLE
Reduce scope and surface area of TempDirectory extension

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1752]
Since there are currently multiple issues (e.g. #864 and #1672) that might change how extensions that provide resources are written and registered, we should hide the implementation of `@TempDir` so we can easily change it in a future release.

## Deliverables

- [x] Remove support for custom file systems, i.e. remove `ParentDirProvider` and `TempDirContext`.
- [x] Make `@TempDir` a top-level type.
- [x] Move appropriate Javadoc from `TempDirectory` to `@TempDir`.
- [x] Move `TempDirectory` to `junit-jupiter-engine` and make it package-private.
- [x] Register `TempDirectory` as a default extension.
- [x] Update existing documentation in User Guide.
- [x] Document breaking changes in Release Notes.

**Comment by sbrannen** [comment]
Let's consider relocating `@TempDir` to the `org.junit.jupiter.api` package as well..

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Update: 1st deliverable completed

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
> Let's consider relocating `@TempDir` to the `org.junit.jupiter.api` package as well.

For the time being, I have moved the `@TempDir` annotation to a top-level type in a new `org.junit.jupiter.api.io` package.

**Comment by sbrannen** [comment]
Closing this issue since all deliverables have been completed in `master`.

**Comment by snicoll** [comment]
>  Register TempDirectory as a default extension.

That is very nice!
