### ISSUE TITLE
Support @TempDir on constructor parameters

### ISSUE THREAD

**Issue by snicoll** [junit-team/junit5#1754]
## Overview

See https://github.com/junit-team/junit5/issues/1748#issuecomment-457612952

I've started to use this feature and I miss constructor injection quite a lot. Being able to inject the directory and then creating my tester as a final field was quite what I was looking for. 

I've moved that code to `@BeforeEach` but that's yet another annotation I have to add for no good reason. I actually don't need to create the tester for every test but I don't want to flag the tester static.

## Related Issues

- #1748 
- #1752

**Comment by sbrannen** [comment]
Thanks for creating this issue.

In case you missed it, we completely overhauled the scope of the `@TempDir` support in #1752.

It's easier to use now, but constructor parameters are still not supported.

I have therefore slated this for 5.5 M1 for _team discussion_.

**Comment by sbrannen** [comment]
> I've started to use this feature and I miss constructor injection quite a lot. Being able to inject the directory and then creating my tester as a final field was quite what I was looking for.

@snicoll, out of curiosity, were you using the `@TestInstance(PER_CLASS)` lifecycle mode?

And if not, did the fact that the temp directory was shared across all test methods adversely affect your tests?

**Comment by snicoll** [comment]
Thanks for the quick reply. I didn't know and those looks quite sane change to me.

> @snicoll, out of curiosity, were you using the @TestInstance(PER_CLASS) lifecycle mode?

No I did not.

> And if not, did the fact that the temp directory was shared across all test methods adversely affect your tests?

It did at first and then I added something to create a sub-dir per invocation in my custom tester. I think it's counter intuitive that the same temp `Path` is injected every time the constructor is invoked (i.e. for every test).

Is that some sore of limitation in the parameter resolution model or is there a reason why this can't be supported?

**Comment by sbrannen** [comment]
It's a known limitation of the `ExtensionContext` design/implementation.

I attempted to outline the issues here:

- https://github.com/junit-team/junit5/issues/1748#issuecomment-457634710
- https://github.com/junit-team/junit5/issues/1748#issuecomment-457638042

**Comment by snicoll** [comment]
Thanks, I missed the full context on the second comment.

**Comment by bjmi** [comment]
I also miss constructor injection of a `@TempDir` variable. The following example would then work in Kotlin.
```
class FileSystemStoreTest(@TempDir documents: Path) {

    private val store = FileSystemStore(documents)

    @Test
    fun read() {
        // Setup
        val content = """<owner><name>Peter</name><name>Marc</name></owner>"""
        store.write("owners.xml", content)
        // Exercise
        val result = store.read("owners.xml")
        // Verify
        assertEquals(content, result)
    }
}
```
Or if #2208 is implemented then it would work in a similar way
```
class FileSystemStoreTest {
    private val documents = TempDir.create()
    private val store = FileSystemStore(documents)
    ...
```
