### ISSUE TITLE
@RegisterExtension instance field is not disposed in @Nested classes

### ISSUE THREAD

**Issue by Sam-Kruglov** [junit-team/junit5#1756]
Hi, just tried using [this AssertJ feature](http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.11.0-junit5-soft-assertions)

The following test class fails both tests but should only faild test `one`.

```java
import org.assertj.core.api.JUnitJupiterSoftAssertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.extension.RegisterExtension;

@TestInstance(TestInstance.Lifecycle.PER_METHOD)
public class Bla {

    @RegisterExtension
    public final JUnitJupiterSoftAssertions softly = new JUnitJupiterSoftAssertions();

    @BeforeEach
    void setUp() {
       //in IDEA place a breakpoint to NOT suspend and log and evaluate softly.hashcode()
        System.out.println("before");
    }

    @Nested
    class A {
            
        @Test
        void one() {
            softly.assertThat(1).isEqualTo(2);
        }

        @Test
        void two() {
            softly.assertThat(1).isEqualTo(1);
        }
    }
}
```

Also, go into JUnitJupiterSoftAssertions#afterEach and also place a breakpoint to log `this.hashcode()` when `errors` is not empty.

The problem is actually fixed by removing the nested class and just putting both tests into the root. Or by placing the field and setUp into the nested class. So, the `@Nested` breaks everything here. 

Versions:
assertJ 3.11.1
Junit 5.3.2
open jdk 11.0.1
kotlin 1.3.11
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
macOS 10.13.6

**Comment by sbrannen** [comment]
It's not just `@Nested`.

I also reproduced it with test instance per-class lifecycle semantics.

```java
import static org.junit.jupiter.api.TestInstance.Lifecycle.PER_CLASS;

import org.assertj.core.api.JUnitJupiterSoftAssertions;
import org.junit.jupiter.api.MethodOrderer.Alphanumeric;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.RegisterExtension;

@TestMethodOrder(Alphanumeric.class)
@TestInstance(PER_CLASS)
class AssertJSoftAssertionsExtensionTests {

	@RegisterExtension
	public final JUnitJupiterSoftAssertions softly = new JUnitJupiterSoftAssertions();

	@Test
	void test1() {
		// should fail
		softly.assertThat(1).isLessThan(0);
	}

	@Test
	void test2() {
		// should pass
		softly.assertThat(0).isLessThan(1);
	}

}
```

**Comment by sbrannen** [comment]
Thanks for opening the issue!

In any case, this is not an issue with JUnit Jupiter.

The problem lies in the implementation in AssertJ.

I am therefore closing this issue in favor of https://github.com/joel-costigliola/assertj-core/issues/1418.

Cheers,

Sam
