### ISSUE TITLE
JAR manifests contain invalid Specification-Version

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1766]
It reads `Specification-Version: MatchGroup(value=5.4.0, range=0..4)` for Jupiter and Vintage JARs, but should be `Specification-Version: 5.4.0`.
Same goes for Platform JARs, which contain `Specification-Version: MatchGroup(value=1.4.0, range=0..4)`, but should have`Specification-Version: 1.4.0`.

## Deliverables

- [ ] Use correct value for `Specification-Version` in all manifest files
- [ ] Write an integration test that checks expected manifest values

**Comment by sormuras** [comment]
_in progress..._

**Comment by marcphilipp** [comment]
I've cherry-picked f23b287543fcabbc60aaec0b8d441a16de7089d4 and c2ae582582120dbe45021e2f8cb075047c086f18 to the `releases/5.4.x` branch.
