### ISSUE TITLE
Access method name in beforeAll extension point

### ISSUE THREAD

**Issue by MykolaGolubyev** [junit-team/junit5#1769]
Hello,
I am writing a JUnit 5 extension. 
```
public void beforeAll(ExtensionContext extensionContext) { .. }
```
My custom code is being called, which is awesome. 
But I can't seem to find a way to have a callback for methods marked with `@BeforeAll`.

**Comment by sbrannen** [comment]
> But I can't seem to find a way to have a callback for methods marked with `@BeforeAll`.

There are not any extension APIs that receive callbacks for the invocation of user-supplied lifecycle methods such as `@BeforeAll`,  `@BeforeEach`, etc.

Generally speaking, an extension should not be concerned with whether or not a user implements custom lifecycle methods. Their presence or absence should in no way influence the behavior of an extension.

So why do you feel that you need a callback for such scenarios?

**Comment by sbrannen** [comment]
Also, the current title of this issue ("Access method name in beforeAll extension point") does not align with the question you asked in this issue's description.

Did you mean to ask two questions?

What "method name" do you wish to access?

**Comment by marcphilipp** [comment]
FWIW we might add such a callback in #157.

**Comment by MykolaGolubyev** [comment]
My goal is to generate test reporting using ReactJS and data collected from test runs. I use a framework that tracks executed Test Steps. I associate test steps with each test and let users explore what happened during each test.
I want "init" part to be present in the generated report as well. 
Right now I put a hack and simply display "init". Ideally I want to display "user function name one" and "another init function two" instead of a single catch all "init".

**Comment by sbrannen** [comment]
OK. So it's just for reporting purposes.

In that case, it might make sense to add "events" to the `TestWatcher` API for user-supplied lifecycle methods.

@junit-team/junit-lambda, Thoughts?

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M1 for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team Decision:** Implement #157 first and see if that can reasonably be used to implement the use case described in this issue.

**Comment by MykolaGolubyev** [comment]
Hello @marcphilipp, was there any decision made?
Anything I can help with?

**Comment by marcphilipp** [comment]
@MykolaGolubyev The new `InvocationInterceptor` extension point should allow you to do what you need:

```java
public class MyExtension implements InvocationInterceptor {
    @Override
    public void interceptBeforeAllMethod(Invocation<Void> invocation, ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext) throws Throwable {
        String methodName = invocationContext.getExecutable().getName();
        // remember methodName somewhere for tracking here
        try {
            invocation.proceed();
        }
        finally {
            // forget methodName again here
        }
    }
}
```

**Comment by MykolaGolubyev** [comment]
@marcphilipp this is a very nice new addition to the API! Thank you for pointing it out. 
Currently when I wrap regular `@Test` methods via `beforeEach(ExtensionContext extensionContext)` I am able to get the provided display name using `ExtensionContext::getDisplayName`. Is there a way to get provided display name of `@BeforeAll`?

**Comment by marcphilipp** [comment]
`@BeforeAll` methods don't have display names so I'm not following. Could you clarify what you need, maybe with an example?

**Comment by MykolaGolubyev** [comment]
I was trying to use `@DisplayName` on top of `@BeforeAll`
```
@BeforeAll
@DisplayName(“create customers”)
public static void create() { ... }
```

**Comment by marcphilipp** [comment]
That's not read by Jupiter, but you could read it from the method in the `InvocationInterceptor`:

```java
var method = invocationContext.getExecutable();
var name = AnnotationSupport.findAnnotation(method, DisplayName.class)
	.map(DisplayName::value)
	.orElseGet(method::getName)
```

**Comment by MykolaGolubyev** [comment]
@marcphilipp oh of course! Thanks again. Didn't realize that `@BeforeAll` and `@DisplayName` combo is not part of the framework standard combo. 
Closing this ticket.
