### ISSUE TITLE
Make ExecutionRecorder in Test Kit public

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1772]
`org.junit.platform.testkit.engine.ExecutionRecorder` could be used to test internals of 3rd party TestEngine implementations if the class was public with a public constructor or a public factory method.

**Comment by sbrannen** [comment]
How would making `ExecutionRecorder` public change the status quo?

In other words, what is missing in the current API that would be made possible only by making `ExecutionRecorder` public?

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M1 for discussion.

**Comment by sbrannen** [comment]
> `org.junit.platform.testkit.engine.ExecutionRecorder` could be used to test internals of 3rd party TestEngine implementations...

The reason I asked the above questions is that your quoted statement above is exactly the goal of the Test Kit.

There is nothing (intentional) about the Test Kit that is specific to test engines implemented by the JUnit team.

So, if something is missing, let's try to address those shortcomings without opening up implementation details like `ExecutionRecorder` if possible.

**Comment by jlink** [comment]
I'd like to inject an ExecutionRecorder instance in other places than the engine in order to check events at a place closer to where they are being created.

**Comment by marcphilipp** [comment]
@jlink Is this issue still relevant for you? If I understand you correctly, you'd like to use `ExecutionRecorder` as a `EngineExecutionListener` for finer grained tests that don't need to go through the engine. Is that right?

**Comment by jlink** [comment]
@marcphilipp correct. It's still relevant but not critical since I touch the relevant tests rather rarely.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Let's make it public.

**Comment by marcphilipp** [comment]
_in progress_
