### ISSUE TITLE
Log Spam on STANDARD_ERROR?

### ISSUE THREAD

**Issue by sdavids** [junit-team/junit5#1774]
Using JUnit 5.4.0.

junit-platform.properties
```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
```

build.gradle
```
tasks.withType(Test).configureEach {
  useJUnitPlatform()

  forkEvery = 1

  testLogging {
    showStandardStreams = true
  }
}
```

Will lead to:

```
Gradle Test Executor 93 STANDARD_ERROR
    Feb 14, 2019 2:57:50 PM org.junit.platform.launcher.core.LauncherConfigurationParameters fromClasspathResource
    INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/Users/dev/tmp/build/resources/test/junit-platform.properties].

Gradle Test Executor 94 STANDARD_ERROR
    Feb 14, 2019 2:57:50 PM org.junit.platform.launcher.core.LauncherConfigurationParameters fromClasspathResource
    INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/Users/dev/tmp/build/resources/test/junit-platform.properties].

Gradle Test Executor 95 STANDARD_ERROR
    Feb 14, 2019 2:57:50 PM org.junit.platform.launcher.core.LauncherConfigurationParameters fromClasspathResource
    INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/Users/dev/tmp/build/resources/test/junit-platform.properties].

Gradle Test Executor 96 STANDARD_ERROR
    Feb 14, 2019 2:57:50 PM org.junit.platform.launcher.core.LauncherConfigurationParameters fromClasspathResource
    INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/Users/dev/tmp/build/resources/test/junit-platform.properties].

... several more of the above ...

com.test.MyTest STANDARD_ERROR
    Feb 14, 2019 2:57:51 PM org.junit.jupiter.engine.config.EnumConfigurationParameterConverter get
    INFO: Using parallel execution mode 'CONCURRENT' set via the 'junit.jupiter.execution.parallel.mode.default' configuration parameter.
```

Is this "spam" desired?

*showStandardStreams* is enabled because we need it for another use case.

**Comment by sdavids** [comment]
Workaround to get rid of the "spam":

build.gradle
```
tasks.withType(Test).configureEach {
  useJUnitPlatform()

  systemProperty 'java.util.logging.config.file', "${project.buildDir}/resources/test/logging-test.properties"

  forkEvery = 1

  testLogging {
    showStandardStreams = true
  }
}
```

logging-test.properties
```
handlers=java.util.logging.ConsoleHandler
.level=INFO

org.junit.platform.launcher.core.LauncherConfigurationParameters.level=WARNING
org.junit.jupiter.engine.config.EnumConfigurationParameterConverter.level=WARNING
```

**Comment by marcphilipp** [comment]
Glad you figured out for yourself! We apologize for the verbosity, but unfortunately we cannot change the default behavior of java.util.logging. Thus, I'm closing this issue as "works-as-designed".

**Comment by marcphilipp** [comment]
@davidburstromspotify Good point! It would be better to use a `CommandLineArgumentProvider` or pass a relative path.

**Comment by alexandrubodnar1996** [comment]
> handlers=java.util.logging.ConsoleHandler
> .level=INFO



> Workaround to get rid of the "spam":
> 
> build.gradle
> 
> ```
> tasks.withType(Test).configureEach {
>   useJUnitPlatform()
> 
>   systemProperty 'java.util.logging.config.file', "${project.buildDir}/resources/test/logging-test.properties"
> 
>   forkEvery = 1
> 
>   testLogging {
>     showStandardStreams = true
>   }
> }
> ```
> 
> logging-test.properties
> 
> ```
> handlers=java.util.logging.ConsoleHandler
> .level=INFO
> 
> org.junit.platform.launcher.core.LauncherConfigurationParameters.level=WARNING
> org.junit.jupiter.engine.config.EnumConfigurationParameterConverter.level=WARNING
> ```

Hi there, I really would appreciate if there is a configuration for maven project maybe. 

this is what I tried but didn't work at all, maybe I'm missing something:
`            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.config.file>${project.basedir}/src/test/resources/test-logging.properties</java.util.logging.config.file>
                    </systemPropertyVariables>
                </configuration>
            </plugin>`
