### ISSUE TITLE
Exception thrown from TestExecutionListener fails the test plan

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1777]
## Overview

Currently, if a `TestExecutionListener` throws an exception, that exception will propagate and cause the entire test plan to fail.

## Deliverables

- [ ] Ensure that exceptions thrown from methods in a `TestExecutionListener` are swallowed and logged at `ERROR` level.
- [ ] Update Javadoc for `TestExecutionListener` to describe the expectation that such listeners never throw exceptions and what happens if a listener throws an exception.

**Comment by gopinath-langote** [comment]
I can pick this up. If no one is picking

**Comment by sbrannen** [comment]
@gopinath-langote, feel free to submit a PR!

The desired behavior is analogous to the support for `TestWatcher` callback invocations.

If you have problems finding where/how to test the changes, just let us know.

**Comment by sbrannen** [comment]
> I can pick this up. If no one is picking

If you decide to start working on it, please just say so here so that we can mark it as "in progress".

**Comment by gopinath-langote** [comment]
@sbrannen 
I can work on this.


I need more information on this though.  Could you please redirect me to exact class (with full package ).

Is this for all the methods in the class or all?
How to test the behavior?


Regards,
Gopinath

**Comment by sbrannen** [comment]
The easiest way to find where something like this is used is to search for uses within the code base.

For example, I just searched for where `org.junit.platform.launcher.TestExecutionListener.executionFinished(TestIdentifier, TestExecutionResult)` is invoked, and the results show me:

- `org.junit.platform.launcher.core.ExecutionListenerAdapter`
- `org.junit.platform.launcher.core.TestExecutionListenerRegistry`

So you'll need to analyze invocations of all methods in `TestExecutionListener` and determine the best place to add try-catch blocks.

**Comment by sbrannen** [comment]
>     2. Is this for all the methods in the class or all?

It's for the entire API, so all methods in the `TestExecutionListener` interface.

**Comment by sbrannen** [comment]
Regarding where to test it, you'll need to find an appropriate place within the `platform-tests` module.

And you'll need to create an "exception throwing" `TestExecutionListener` (stub or mock), register it, execute a simple test plan, and verify that the exceptions were all swallowed and logged. See uses of `org.junit.jupiter.engine.TrackLogRecords` for achieving the latter.

**Comment by gopinath-langote** [comment]
Hello @sbrannen ,
Thanks for the information. I will start working on this.

**Comment by sbrannen** [comment]
_in progress_: @gopinath-langote is working on it.
