### ISSUE TITLE
JUnit 5 Test Suites don't run with surefire 3.0.0-M3 under pure Maven

### ISSUE THREAD

**Issue by 1vanan** [junit-team/junit5#1778]
## Overview

I'm trying to launch test suite with surefire plugin under Maven version 3.0.0-M3. But if I do it with ```@RunWith(JUnitPlatform.class)``` annotation in pure Maven, situation ```No tests were executed!``` occurs. I figured out that this problem appears with 2.22.x version surefire, on the earlier versions all is fine. Therefore, dynamic tests with ```@TestFactory``` work fine with newer versions and do not work on 2.21.x and earlier.

## Problem reproduction

I faced this problem during migration to JUnit 5 a part of open-source project Apache Ignite [1].  Also, for clarity, I tried to reproduce it on a small project [2]. I tried to run tests in two ways: with ```@SelectClasses``` annotation and dynamically, with  ```@TestFactory``` annotation (commented) [3]. The first approach works fine with 2.21.x version surefire and earlier and the second one is vice versa. For me, it is necessary to run the test suite ```MainSuiteTest``` under pure maven with the newest version that supports Java 11. I use command ```mvn -Dtest=MainSuiteTest test``` and get the next result:

<details><summary>LOG</summary>
<p>

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.472 s
[INFO] Finished at: 2019-02-15T18:04:51+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project quickstart: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)
```

</p>
</details>

From IDE both approaches work fine and it does not depend on the surefire version.

## Context

 - Surefire plugin: 3.0.0-M3
 - JUpiter: 5.3.2
 - Vintage: 5.3.2
 - Platform launcher: 1.3.2
 - Platform runner: 1.3.2
 - IDE: Intellij IDEA 2018.1.7 (Ultimate)
 - Maven: 3.6.0
 - Java: 1.8.0_152

## Links
[1] https://github.com/apache/ignite/pull/5888/files#diff-04dc5d029560773ac79faaf3da0fbb22R134
[2] https://github.com/1vanan/quickstart/tree/Junit5
[3]https://github.com/1vanan/quickstart/blob/Junit5/src/test/java/com/quickstart/application/testSuites/MainSuiteTest.java

**Comment by marcphilipp** [comment]
I know it's a little confusing, but the suite class annotated with `@RunWith(JUnitPlatform.class)` is actually a JUnit 4 test class and as such needs to be executed with Surefire's JUnit 4 provider. Surefire 2.22.x is the first version with autodetection of the JUnit platform, i.e. as soon as `junit-platform-engine` is on the classpath it will attempt to execute all test classes using the JUnit Platform. However, the JUnit Platform cannot execute suites annotated with `@RunWith(JUnitPlatform.class)`. There will eventually be support for suites in the Platform (cf. #744). In the meantime, you can [force Surefire](https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html) to use its JUnit 4 provider. In your example, however, I would recommend to not use any suite at all and just let Maven and your IDE discover test classes automatically.

**Comment by 1vanan** [comment]
@marcphilipp Thank you for the answer!  
Now with dependency
```java
      <dependency>
        <groupId>org.apache.maven.surefire</groupId>
        <artifactId>surefire-junit47</artifactId>
        <version>3.0.0-M3</version>
      </dependency>
```
it works.

**Comment by 1vanan** [comment]
I chose this way as it is necessary to use suites in Ignite because on TeamCity all tests are aggregated to suits and run under them [1].

[1] https://ci.ignite.apache.org/project.html?projectId=IgniteTests24Java8&branch_IgniteTests24Java8=pull%2F5888%2Fhead

**Comment by marcphilipp** [comment]
@1vanan I'm glad you found a solution. Thanks for letting us know!

**Comment by minherz** [comment]
It does not work for me. Tested on 3.0.0-M3 -- 3.0.0-M5 with 
JUpiter: 5.8.2
Java: 1.8.0_292
Maven: 3.8.1

I get
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project servlet-app: There are test failures.
[ERROR] 
[ERROR] Please refer to /workspaces/java/java-servlet-app/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] org/junit/runner/notification/RunListener
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org/junit/runner/notification/RunListener
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by marcphilipp** [comment]
> Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

Anything in there?

**Comment by minherz** [comment]
Something like
```
Created at 2021-12-03T14:58:06.471
java.lang.NoClassDefFoundError: org/junit/runner/notification/RunListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
```

**Comment by marcphilipp** [comment]
Looks like Surefire is not using its `surefire-junit-platform` provider implementation. Youu can try forcing it as described here: https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html. If that doesn't help, please raise a new issue with a reproducer project.
