### ISSUE TITLE
EngineTestKit: How to prevent selected class run from outside engine

### ISSUE THREAD

**Issue by mmichaelis** [junit-team/junit5#1779]
First of all thanks for the `EngineTestKit` &mdash; it just came in time, as I need to test exception handling in my extension.

Unfortunately the test detection mechanism in Idea as well as when run from Gradle also finds the referenced class to run (which should fail) instead of ignoring it.

My workaround: I annotated my "test under test" with `@EnabledIfSystemProperty(named = "engine.test.kit", matches = "enabled")` and in the test class with `EngineTestKit` I defined `BeforeAll` and `AfterAll`:

```java
  @BeforeAll
  static void setUpAll() {
    System.setProperty("engine.test.kit", "enabled");
  }

  @AfterAll
  static void tearDownAll() {
    System.setProperty("engine.test.kit", "");
  }
```

This works... but I think there should be a simpler way of doing so. Any ideas?

If there is no solution up to now, I suggest to have an `ExecutionCondition` like `@OnlyRunViaEngineTestKit` or something similar.

Possibly related to #1372.

**Comment by sbrannen** [comment]
TBH, in JUnit's own test suite (and other test suites where I "test the tests"), we use naming conventions to differentiate between _real_ test classes and _demo_ test classes.

For example, in JUnit 5 every real test class is named `*Tests`, and every demo test class is named `*TestCase`. Then in the build we simply make sure that the class name include filter matches against `*Tests` but not against `*TestCase`.

Something I've done in other test suites is introduce a _tag_ that represents that a particular category of test classes is expected to fail, and I exclude that tag from the build.

Of course, in both cases, the default scanning semantics of the IDE may pick up those "tests under test" anyway. So the challenge is finding a solution that works well in the build and in the IDE.

**Comment by sbrannen** [comment]
> If there is no solution up to now, I suggest to have an `ExecutionCondition` like `@OnlyRunViaEngineTestKit` or something similar.

That's tricky.

The Test Kit has zero dependencies on JUnit Jupiter, and we would like to keep it that way. Though, adding an _optional_ runtime dependency on `junit-jupiter-api` may be an option (no pun intended).

But that would only help people testing a test engine via tests written using JUnit Jupiter. Thus, a developer not using JUnit Jupiter would have zero benefit from a Jupiter-specific `ExecutionCondition`.

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M1 for _team discussion_

**Comment by JojOatXGME** [comment]
I had a similar issue. Especially that IntelliJ dosn't know that I excluded certain tests within Gradle. I created feature request #2330, which might provide an alternative solution for some scenarios.

For now, I am using [configuration parameters] instead of [system properties]. That avoids potential threading issues and maybe other problems with static variables. I also created a special test annotation called `@MockTest`.

```java
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Test
@Tag("mock")
@ExtendWith(EnableInTestKit.class)
public @interface MockTest {}

public static @NotNull EngineExecutionResults runTest(@NotNull Class<?> clazz, @NotNull String methodName) {
  return EngineTestKit
      .engine("junit-jupiter")
      .configurationParameter(CONFIGURATION_TO_ENABLE_TESTS, "true")
      .selectors(selectMethod(clazz, methodName))
      .execute();
}

static final class EnableInTestKit implements ExecutionCondition {
  @Override
  public ConditionEvaluationResult evaluateExecutionCondition(ExtensionContext context) {
    return context.getConfigurationParameter(CONFIGURATION_TO_ENABLE_TESTS).isPresent()
           ? ConditionEvaluationResult.enabled("Enabled because JUnitTestKitUtil is used.")
           : ConditionEvaluationResult.disabled("Tests annotated with @MockTest run only as part of other tests.");
  }
}
```

I still exclude the tests in Gradle by using the tag on `@MockTest`. So Gradle doesn't count them as *skipped* in the statistics.

[system properties]:
<https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.html#getProperty(java.lang.String)>
"System.getProperty(String)"
[configuration parameters]:
<https://junit.org/junit5/docs/current/api/org.junit.platform.testkit/org/junit/platform/testkit/engine/EngineTestKit.Builder.html#configurationParameter(java.lang.String,java.lang.String)>
""

**Comment by dmfs** [comment]
FWIW, here is another solution to the problem:

Put the "test case" classes into their own source-set that's not executed by default:

```Groovy
sourceSets {
    intTest {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
    test {
        compileClasspath += sourceSets.intTest.output
        runtimeClasspath += sourceSets.intTest.output
    }
}

configurations {
    intTestImplementation.extendsFrom implementation
    intTestRuntimeOnly.extendsFrom runtimeOnly
}
```

In this case put all the "test case" classes into `src/intTest/java/…`. The Test Engine integration test itself is still in the `test` source-set, just like all the other tests.

See [this example](https://github.com/saynotobugsorg/confidence/blob/0.13.0/confidence-incubator/build.gradle#L11-L25)
