### ISSUE TITLE
JMockit teardown no longer works as before

### ISSUE THREAD

**Issue by AndreasVolkmann** [junit-team/junit5#1792]
When upgrading from `5.3.2` to `5.4.0`, the JMockit mock leaks into other tests. 

Previously, when mocking something in one test, the next test would be completely reset and be influenced by previous mocks. 

After upgrading, my tests fail because mocks from other tests are still active. 

## Steps to reproduce

In my example I use JMockit to mock `System.getEnv`.

```kotlin
import mockit.Mock
import mockit.MockUp
import org.junit.jupiter.api.Test

class JMockitTest {

    @Test fun willCreate() {
        MockSystem("key" to "1")
        val result = System.getenv("key")
        assert(result == "1")
    }

    @Test fun shouldTearDown() {
        val result = System.getenv("key")
        assert(result == null)
    }

}

class MockSystem(private val envs: Map<String, String>) : MockUp<System>() {

    constructor(vararg envs: Pair<String, String>) : this(mapOf(*envs))

    @Mock fun getenv(name: String) = envs[name]
}
```

And here is my build.gradle:
```groovy
plugins { id 'org.jetbrains.kotlin.jvm' version '1.3.21' }
group 'me.avo'
version '1.0-SNAPSHOT'
repositories { jcenter() }
ext { junit_version = '5.4.0' }

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    testCompile "org.jmockit:jmockit:1.45"
    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: junit_version
    testRuntime "org.junit.jupiter:junit-jupiter-engine:$junit_version"
}

test {
    useJUnitPlatform {
        includeEngines 'junit-jupiter'
    }

    doFirst {
        def jMockit = configurations.testCompile.find {
            it.name.startsWith("jmockit-")
        }
        jvmArgs "-javaagent:${jMockit}"
    }
}
```

## Context

 - Used versions (Jupiter/Vintage/Platform): `5.3.2` and `5.4.0`
 - Build Tool/IDE: `IntelliJ Ultimate`

**Comment by sbrannen** [comment]
Thanks for raising the issue.

I have confirmed that the test passes on Jupiter 5.3.2 and fails on Jupiter 5.4.0 using the following Java project.

```groovy
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
	jcenter()
}

ext {
	// junit_version = '5.3.2'
	junit_version = '5.4.0'
}

dependencies {
    testCompile "org.jmockit:jmockit:1.45"
    testCompile "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testRuntime "org.junit.jupiter:junit-jupiter-engine:$junit_version"
}

test {
    useJUnitPlatform {
        includeEngines 'junit-jupiter'
    }

    doFirst {
        def jMockit = configurations.testCompile.find {
            it.name.startsWith("jmockit-")
        }
        jvmArgs "-javaagent:${jMockit}"
    }
}
```

```java
package example;

import java.util.Collections;
import java.util.Map;

import org.junit.jupiter.api.Test;

import mockit.Mock;
import mockit.MockUp;

public class JMockitTest {

	@Test
	void willCreate() {
		new MockSystem(Collections.singletonMap("key", "1"));
		String result = System.getenv("key");
		assert (result == "1");
	}

	@Test
	void shouldTearDown() {
		String result = System.getenv("key");
		assert (result == null);
	}

	static class MockSystem extends MockUp<System> {

		private final Map<String, String> envs;

		public MockSystem(Map<String, String> envs) {
			this.envs = envs;
		}

		@Mock
		String getenv(String name) {
			return this.envs.get(name);
		}
	}

}
```

**Comment by sbrannen** [comment]
It also fails with Jupiter `5.4.0-M1`.

**Comment by sormuras** [comment]
Perhaps (also) related to how Gradle uses the JUnit Platform to launch test runs? Does it fail using our standalone console launcher?

**Comment by sbrannen** [comment]
It's not specific to Gradle.

We see the same behavior in Eclipse as well if we add something similar to the following VM arguments to the Run Configuration.

`-ea -javaagent:/Users/<some-user-name>/.gradle/caches/modules-2/files-2.1/org.jmockit/jmockit/1.45/<some-hash-tag>/jmockit-1.45.jar`

**Comment by sbrannen** [comment]
It appears that `mockit.internal.startup.JMockitInitialization.applyInternalStartupFakesAsNeeded()` does not register JMockit's `mockit.integration.junit5.FakeExtensionRegistry.FakeExtensionRegistry()`.

The net result is that the `mockit.integration.junit5.JMockitExtension` does not get registered.

So JMockit's support for JUnit Jupiter simply is not being used with Jupiter 5.4.

Note, however, that I was able to verify that the `JMockitExtension` extension does actually work with Jupiter 5.4. I achieved this by copying the source code of `JMockitExtension` into a local `public` class which I then registered automatically (as described [here](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic)).

After I did that, the previously failing test class began to pass with Jupiter 5.4.

**Comment by sbrannen** [comment]
In the interim I have determined that there are several issues that have been opened against JMockit along the same lines.

- https://github.com/jmockit/jmockit1/issues/585
- https://github.com/jmockit/jmockit1/issues/589

I am therefore closing this issue.
