### ISSUE TITLE
Test-drive JUnit 5 build on Azure Pipelines

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1795]
## Overview

Test-drive our build on Azure Pipelines [1].

[1] https://azure.microsoft.com/en-us/services/devops/pipelines/

## Deliverables

- [x] Add `azure-pipelines.yml` with minimal configuration.
- [x] Does it work on Linux?
- [x] Does it work on Mac?
- [x] Does it work on Windows?
- [x] How to configure which JDK is used?
- [x] Is OpenJDK-EA supported?
- [x] On failing builds, are logs easy to access and scan?
- [x] Are Gradle Build Scans still published?
- [x] What about speed?
- [x] SNAPSHOT deployments: documentation (user-guide, javadoc) and artifacts

**Comment by brunoborges** [comment]
Confirming a minimal setup for Linux works as expected.

`azure-pipeline.yml`

 - https://github.com/brunoborges/junit5/commit/4ee8d238a8647314d2925f78deaa56f6fdec6a4b

Here's a build test:

 - https://dev.azure.com/brunoborges-github/junit5/_build/results?buildId=25&view=logs

And here's the Gradle scan:

 - https://scans.gradle.com/s/6723pxshyiv2y

**Comment by sormuras** [comment]
Awesome, @brunoborges -- thanks for spiking an example setup. PR? ;)

**Comment by sormuras** [comment]
Superseded by #1810
