### ISSUE TITLE
Support global configuration to override the default DisplayNameGenerator

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#1797]
For our case, nearly all of our test cases are written in Kotlin. With the default name generation, that can result in a bit more cumbersome/ugly test names that are output by IDEs or in reporting.

For example, in a Gradle project we have.

```kotlin
internal class MkobitExample {
    @Test
    internal fun `this is an example test that should demonstrate something!`() {
    }

    @Test
    internal fun `this test uses the @TempDir extension`(@TempDir path: Path) {
    }
}
```

Which results in test names like

* `this is an example test that should demonstrate something!$my_service()`
* `this test uses the @TempDir extension$my_service(Path)`

Where `my_service` is the name of the module (Gradle's `project.group`).

What we have been doing is using our own simple `DisplayNameGenerator.Standard` implementation:

```kotlin
private class KotlinFriendlyDisplayNameGenerator : DisplayNameGenerator.Standard() {
    override fun generateDisplayNameForNestedClass(nestedClass: Class<*>): String {
        return nestedClass.kotlin.simpleName ?: super.generateDisplayNameForNestedClass(nestedClass)
    }

    override fun generateDisplayNameForMethod(testClass: Class<*>, testMethod: Method): String {
        return testMethod.kotlinFunction?.name ?: super.generateDisplayNameForMethod(testClass, testMethod)
    }

    override fun generateDisplayNameForClass(testClass: Class<*>): String {
        return testClass.kotlin.simpleName ?: super.generateDisplayNameForClass(testClass)
    }
}

@DisplayNameGeneration(KotlinFriendlyDisplayNameGenerator::class)
internal annotation class KotlinFriendlyDisplayNames
```

Then, Gradle reports the test as:

* *Test* - `this is an example test that should demonstrate something!` - *Method name* `this is an example test that should demonstrate something!$frame_service()`
* *Test* - `this test uses the @TempDir extension` - *Method name* `this test uses the @TempDir extension$frame_service(Path)`

It would be useful to allow a user supplied override parameter to select the default `DisplayNameGenerator` implementation.

## Deliverables

- [ ] Configuration parameter support for Jupiter engine to override default `DisplayNameGenerator`

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M1 for _team discussion_

**Comment by marcphilipp** [comment]
**Team Decision:** let's do it.

**Comment by gopinath-langote** [comment]
Hello @marcphilipp @sbrannen

If this is up for grab, I can do this.

**Comment by marcphilipp** [comment]
Let's use `junit.jupiter.displayname.generator.default` for the new config parameter.

@gopinath-langote Go for it! 🙂

**Comment by gopinath-langote** [comment]
@marcphilipp 
Couple of clarification I want to do before starting PR

1. Configuration `junit.jupiter.displayname.generator.default` will be take `full class path` ex.
   `junit.jupiter.displayname.generator.default=org.junit.jupiter.api.DisplayNameGenerator.Standard`

2. Configuration ill go in `org.junit.jupiter.engine.config.JupiterConfiguration`

3. Both `CachingJupiterConfiguration` & `DefaultJupiterConfiguration` will implement this method of getting `DisplayNameGenerator`.

4. method signature will be something like
```
Class<?> getTestGeneratorClass();
```

5. `DisplayNameUtils` class will have logic for checking if a configuration exists for this.  



Please clarify my above assumption & then I will go straight for PR :) 


Regards,
Gopi

**Comment by marcphilipp** [comment]
> 1. Configuration `junit.jupiter.displayname.generator.default` will be take `full class path` ex.
>   > `junit.jupiter.displayname.generator.default=org.junit.jupiter.api.DisplayNameGenerator.Standard`

Yes, the fully qualified class name. I'm wondering whether we should add a fallback so users can say `Standard` and we would first attempt to lookup that class and, in case that fails try `org.junit.jupiter.api.DisplayNameGenerator.$className`. WDYT?

> 2. Configuration will go in `org.junit.jupiter.engine.config.JupiterConfiguration`

👍 

> 3. Both `CachingJupiterConfiguration` & `DefaultJupiterConfiguration` will implement this method of getting `DisplayNameGenerator`.

👍 

> 4. method signature will be something like
> ```
> Class<?> getTestGeneratorClass();
> ```

Let's use `getDefaultDisplayNameGeneratorClass()`.

> 5. `DisplayNameUtils` class will have logic for checking if a configuration exists for this.  

SGTM

**Comment by gopinath-langote** [comment]
@marcphilipp

1. If user don't provide configuration we are anyways going to use Standard.
I am not seeing someone who will pu only Standard in configuration.
In case we are providing that, user might get confused with fully classname vs just name as Standard

-
Our documentation will be clear that if no configuration provided we will use Standard one.


that's what I think. 
Open for other opinion :)

**Comment by sbrannen** [comment]
>     1. If user don't provide configuration we are anyways going to use Standard.
>        I am not seeing someone who will put only Standard in configuration.
>        In case we are providing that, user might get confused with fully classname vs just name as Standard

I think @marcphilipp was only using `Standard` as an example. We would of course not condone that one override the default with the default since that does not make sense.

But... a team may wish to set `ReplaceUnderscores` as the default generator. So following Marc's proposal, we could support `junit.jupiter.displayname.generator.default=org.junit.jupiter.api.DisplayNameGenerator.ReplaceUnderscores`
 or `junit.jupiter.displayname.generator.default=ReplaceUnderscores` as a convenience.

Though, to be honest, I'm not convinced that we need to support that since it may be more confusing than it's worth (especially for the status quo where there is only one implementation other than the default, `Standard`). Furthermore, I would like to leave open the possibility that Jupiter may later decide to implement generators that are not defined within the `DisplayNameGenerator` interface.

> Our documentation will be clear that if no configuration provided we will use Standard one.

Correct.

**Comment by marcphilipp** [comment]
Fair enough. Let's omit the additional convenience I suggested above and always treat `junit.jupiter.displayname.generator.default` as a fully-qualified class name.
