### ISSUE TITLE
Support composability for `ParameterResolver`s

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#1802]
I would like to leverage existing `ParameterResolver` implementations and use/adapt the type they would resolve in my own `ParameterResolver`.
If possible, I would like to use them in a declarative fashion.

### Using a `ParameterResolver` result in another `ParameterResolver`

The first use case I have is leveraging the built-in [`@TempDir`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/io/TempDir.html) while testing against multiple Gradle versions and different configurations.
We have an extension that works as a `TestTemplate` to run tests against multiple Gradle versions.
Right now, both parameters are injected separately and are setup at the start of the test (`@ParameterizedTest`) or set up (`@BeforeEach`):

```kotlin
@TestTemplate
@ForGradleVersions(["5.1", "5.2"])
internal fun `do thing with GradleRunner`(@TempDir directory: Path, gradleRunner: GradleRunner) {
  // assume GradleRunner sort-of-configured here
  gradleRunner.withProjectDir(directory.toFile())
  // run build with Gradle Runner
}
```

I would like to be able to compose the `ParameterResolver` class that is performing the resolution for `GradleRunner` with the `ParameterResolver` for `@TempDir`'s path.

For example, something like this:

```kotlin
@TestTemplate
@ForGradleVersions(["5.1", "5.2"])
internal fun `do thing with GradleRunner`(gradleRunner: GradleRunner) {
  // gradleRunner.withProjectDir(directory.toFile()) unneeded because @ForGradleVersions extension leverages another tool/extension to bootstrap a project directory
  // now, run build with Gradle Runner
}
```

In this example, the extension would leverage the JUnit Jupiter built-in `@TempDir` `ParameterResolver` to set the `withProjectDir(...)` before the parameter is actually injected.
The other extension lifecycle methods would also be invoked appropriately.

------

Another similar example we have is another `ParameterResolver`-like extension that gets some local Gradle project files and provides the location of it to the test as a `Path`.
Then, in the test setup, the `GradleRunner` is set up wit those files before building.

An example might look like this:

```kotlin
@TestTemplate
@ForGradleVersions(["5.1", "5.2"])
internal fun `do thing with GradleRunner and files`(@TempDir directory: Path, gradleRunner: GradleRunner, @GradleProject(["projects", "only-plugins-block"]) directoryWithProject: Path) {
  // assume GradleRunner sort-of-configured here with version and withPluginClassPath()
  recursivelyCopyDirectory(from = directoryWithProject, to = directory)
  gradleRunner.withProjectDir(directory.toFile())
  // run build with Gradle Runner
}
```

In here, I have multiple `ParameterResolver`s that all get combined in the test (`@ParmaterizedTest`) implementation.
I want to mutate the `GradleRunner` that was passed in with another "modifier" like extension.

Since the `GradleRunner` has a `null` `.getProjectDir()`, then the customization of the directory from the `@GradleProject` resolver can't really do much.

An example of what it might look like with this feature might be:

```kotlin
@TestTemplate
@ForGradleVersions(["5.1", "5.2"])
internal fun `do thing with GradleRunner`(@GradleProject(["projects", "only-plugins-block"]) gradleRunner: GradleRunner) {
  // GradleRunner has full project configured and setup
  // run build with Gradle Runner
}
```

In this example, the `GradleRunner` has the `withProjectDir(...)` configured by the `ParameterResolver` for `@TempDir` and it's `getProjectDir()` mutated by the `ParameterResolver` (or some other extension) that makes use of `@GradleProject`.

### Adapting/converting an existing `ParameterResolver`  result

We have an internal JUnit Jupiter `ParameterResolver` that provisions Docker containers.
We like that is is mostly generic and can be used to create arbitrary Docker containers, networks, and other launch configurations that we can execute against.

For some containers that get used, a user would like to "adapt" the `Container` parameter that gets injected  to a client for whatever service they are starting.

For example, here is an example that provisions a Cassandra Docker container on `localhost` and runs against it:

```kotlin
@ExtendWith(DockerContainerExtension::class)
@Test
internal fun `my test that uses cassandra container`(@DockerContainer(CassandraContainerLaunchConfigurationProducer::class) container: Container) {
  Cluster.builder()
    .withPort(container.bindings.first { it.fromPort == 9042 }.toPort)
    .addContactPoint("localhost")
    .withoutJMXReporting()
    .withoutMetrics()
    .build().use { cluster ->
      cluster.connect().use { session ->
        // create keyspace, tables, etc.
        // run test
      }
    }
}
```

The `Cluster` and `Session` are opened and used to setup some additional resources like tables, keyspace, etc. before being used in test code.
In this example, we are not (at least not yet) composing `ParameterResolver` and performing the set up in the test (`@Test`) or set up (`@BeforeEach`) methods.

Below is an example of what I would like it to (possibly) look like.

```kotlin
@ExtendWith(DockerContainerExtension::class)
@Test
internal fun `my test that uses cassandra container`(@DockerCassandraSession session: Session, @DockerCassandraKeyspace keyspace: String) {
  // do test with cassandra
  // expect cassandra stuff shut down by extension
}
```

In this example, the underlying connection is to a `Container` is abstracted away.
I'm also hoping to resolve multiple parameters here for a single `Container`.
This example does not have multiple `Container`s, but that is most likely a valid use case, too.

## Using Existing Tools

From what I can tell, there is no way to do this with existing tooling. The `ExtensionContext.Store` isn't helpful here because each extension has dependencies which would require ordering.
There is a desire to reduce the amount of parameters that a test needs as input while also not introducing any inheritance.

The way we have been mostly doing it is to put the injection and configuration in a `@BeforeEach` method and then perform the setup in the test.
We would like to, instead, build upon JUnit Jupiter's tools and extension model.

## Related Issues

- #1604 

## Deliverables

Unsure on exact deliverables.

- [ ] ...

**Comment by sbrannen** [comment]
Possible duplicate of #1604
