### ISSUE TITLE
Improve ReflectionSupport.newInstance to support creating instances that have polymorphic-accepting constructors

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#1809]
## Steps to reproduce

* Java 8, Kotlin 1.3.21, JUnit `5.4.0`

```kotlin
import org.junit.platform.commons.support.ReflectionSupport

internal class ConstructorWithString(s: String)

internal class ConstructorWithCharSequence(n: Number)

fun main() {
    val s: String = "hey"
    ReflectionSupport.newInstance(ConstructorWithString::class.java, s)
    ReflectionSupport.newInstance(ConstructorWithCharSequence::class.java, s)
}

```

Fails with

```
Exception in thread "main" java.lang.NoSuchMethodException: ConstructorWithCharSequence.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:428)
	at org.junit.platform.commons.support.ReflectionSupport.newInstance(ReflectionSupport.java:180)
	at MkDemoReflectionSupportKt.main(mkDemoReflectionSupport.kt:10)
	at MkDemoReflectionSupportKt.main(mkDemoReflectionSupport.kt)

```

## Context

 - Used versions (Jupiter/Vintage/Platform): `5.4.0`/-/`1.4.0`
 - Build Tool/IDE:

Attempting to build an extension that uses a `ReflectionSupport.newInstance(MyType::class.java, extensionContext)` where the constructor looks like `MyType(private val extensionContext: ExtensionContext)`

but, the object fails to construct due to

```
java.lang.NoSuchMethodException: MyType.<init>(org.junit.jupiter.engine.descriptor.MethodExtensionContext)
```

Because a constructor is being looked up for the concrete type that is passed in rather than the interface.

My expectation was that the constructor using the interface was going to be used to instantiate the object instead of the concrete type.

## Deliverables

If support is desired:

- [ ] Improve `ReflectionSupport.newInstance` to support instantiating types where the type doesn't match the concrete implementation type passed in as the `args` to `newInstance`

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M2 for _team discussion_

**Comment by sbrannen** [comment]
Although I've slated this for _team discussion_, I do not foresee us changing the semantics of `newInstance()`. 

Doing so would open up a whole new can of worms that I do not think should be supported by JUnit.

Such "worms" include: implementing and maintaining an algorithm that picks the "most specific constructor" based on type hierarchies (possibly with generics and parameterized types) for multiple combinations of overloaded constructors with potentially similar parameter lists.

**Comment by sbrannen** [comment]
As @marcphilipp pointed out elsewhere, for your particular use case, you can just look up the `Constructor` on your own via `java.lang.Class.getDeclaredConstructor(Class<?>...)` and then invoke  it via `constructor.newInstance()`.

**Comment by marcphilipp** [comment]
**Team Decision:** For the reasons mentioned by @sbrannen above, we have decided not to add support for this feature.
