### ISSUE TITLE
Add optional order parameter to @ExtendWith

### ISSUE THREAD

**Issue by ugrepel** [junit-team/junit5#1811]
Extensions can be added to a test class on class level (using `@ExtendWith` on the class) and with `@RegisterExtension` on fields of the test class.

While ordering the `@RegisterExtension` extensions can be achieved with the `@Order` annotation there is no way to do that with the `@ExtendWith` extensions - at least not in a way that the `@RegisterExtension` extensions actually are wrapped by the `@ExtendWith` extensions.

This could be achieved by adding an optional order parameter to the `@ExtendWith` annotation with basically the same semantics as the `@Order` annotation for `@RegisterExtension`.

Note that using multiple separate `@ExtendWith` annotations should use their own order parameters.

The effect should be that `@RegisterExtension` with a given order number wrap `@ExtendWith` with the same order number, which then wrap `@RegisterExtension` extensions with a higher order number or without an order number, with `@ExtendWith` without order parameter being the innermost extensions in this wrapping hierarchy.

A scenario where this would be useful is with Mockito and its `@ExtendWith(MockitoExtension.class)` extension, which initializes fields annotated with `@Mock`. These fields currently cannot be used by `@RegisterExtension` extensions, since they aren't initialized yet when `@RegisterExtension` extensions execute their `beforeEach()` methods.

Workarounds include using `Mockito.mock(MyClass.class)` instead of `@Mock`, or using `BeforeTestExecutionCallback` instead of `BeforeEachCallback`, but that might not help or be possible in all szenarios (with or without Mockito).

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M2 for _team discussion_

**Comment by sbrannen** [comment]
Although I've slated this for _team discussion_, I do not foresee us ever mixing extensions registered via `@ExtendWith` and `@RegisterExtension`. Those mechanisms serve two separate purposes.

As it stands now, extensions registered at the class level via `@ExtendWith` are **always** registered before extensions registered at the class level (e.g., via `static` fields) via `@RegisterExtension`.

Furthermore, extensions registered via `@ExtendWith` are already implicitly ordered based on the order of annotation declarations in the source code.

**Comment by ugrepel** [comment]
Two separate purposes which would be able to work together if they could be mixed in a controlled way.

See my example: the Mockito team provided an extension that is designed to work with `@ExtendWith`. That extension basically initializes the class fields marked with `@Mock.` (as well as constructor parameters marked as such). This is just fine.

Now `@ExtendWith` cannot be used in all scenarios. First, there can be only one instance of such an extension. Then, you might want to programmatically configure your extension - for example with a mocked field initialized by `@ExtendWith(MockitoExtension.class)`.

I just cross-checked registering order - you are right with that `@ExtendWith` registers (and thus executes) before `@RegisterExtension`.

I now see my error - my scenario wasn't complete and could not be working regardless of the order of extensions. I used the first field (the one with `@Mock`) directly while initializing the second field (with my own `@RegisterExtension`, and expected it to be filled by Mockito. Cannot be.

I could use the mocked field in a lambda (e.g. a Supplier) passed to my own extension object, which could then be used in its `beforeEach()` method.

I guess I should retract my enhancement request...

**Comment by joshiste** [comment]
I just stumbled across this issue. And I think I'm currently also in the need of ordering the extensions:

I have a custom extension setting a ThreadLocal which can be used on it's own, but when combined with the SpringExtension it has to run before the SpringExtension (especially before the TransactionalExecutionListener).
This only works if we order the annotations on our test classes in the correct order... So it would be nice if the extension implementor could somehow influence the order of extensions...

**Comment by sbrannen** [comment]
@joshiste, please see #506 which covers the use case you are describing.
