### ISSUE TITLE
Introduce cleanup mode in @TempDir

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1814]
## Overview

As discussed in https://github.com/spring-io/initializr/issues/862, the `TempDirectory` may fail to clean up the temporary directory due to various reasons, but sometimes the user would prefer that the extension not cause the test to fail if certain files or folders within the temporary directory cannot be deleted.

Introducing a configurable clean up mode would help to support such use cases.

## Proposal

Proposal by @marcphilipp:

> I think it should be strict by default in order to catch subtle bugs in the code under test, e.g. an unclosed stream. But changing to a lenient mode via the annotation (sth. like `@TempDir(cleanupMode = LENIENT)`) or a configuration parameter is certainly sth. we can consider for 5.4.1.

## Deliverables

- [ ] Introduce a means to opt out of test failure when the temporary directory cannot be cleaned up automatically.
- [ ] Document in Javadoc.
- [ ] Document in User Guide.
- [ ] Document in Release Notes.

**Comment by OrangeDog** [comment]
When you have a limited bandwidth that's exactly when you don't want a stalebot, because valuable stuff will die simply because you haven't got to uit yet, rather than because it's obsolete.

**Comment by marcphilipp** [comment]
@OrangeDog Valuable stuff will come up again even if Stalebot closes it.

**Comment by marcphilipp** [comment]
Superseded by #2159.
