### ISSUE TITLE
Consider repeatable @EnabledIfEnvironmentVariableExist

### ISSUE THREAD

**Issue by onacit** [junit-team/junit5#1825]
Apologies, `@IfNotApplicable`.

I faced a problem with my integration test that needs multiple environment variables to run.

```java
class MyIT {

    void test() {
        // needs multiple environment variables to run.
    }
}
```

Do we have any chances to get `@EnableIfEnvironmentExist`?

```java
@EnableIfEnvironmentVariables({
    @EnableIfEnvronmentVariable(exist = true, andOptionallyMatches="..."),
    @EnableIfEnvronmentVariable(exist = true, andOptionallyMatches="..."),
    @EnableIfEnvronmentVariable(exist = true, andOptionallyDoesNotMatch="..."),
})
void test() {
}
```
or
```java
@EnableIfEnvironmentVariableExists({
    @EnableIfEnvronmentVariableExist(andOptionallyMatches="..."),
    @EnableIfEnvronmentVariableExist(andOptionallyMatches="..."),
    @EnableIfEnvronmentVariableExist(andOptionallyDoesNotMatch="..."),
})
void test() {
}
```

**Comment by sbrannen** [comment]
> Do we have any chances to get `@EnableIfEnvironmentExist`?

You can already achieve "exists" behavior by simply matching against anything, like this:

```@EnabledIfEnvironmentVariable(named = "MY_KEY", matches = ".+")```

To enable a test if something does not match, you can use inverse boolean logic with `@DisabledIfEnvironmentVariable(named = "MY_KEY", matches = "does match")`.

As for repeatable annotation support for built-in conditions, that will be addressed in #1793.

I am therefore closing this issue.
