### ISSUE TITLE
Let Assert.fail have an arbitrary return type

### ISSUE THREAD

**Issue by aioobe** [junit-team/junit5#1827]
How about letting `Assert.fail(...)` pretend that it returns something of a generic type `T`?

    public static <T> T fail() { ... }

this would be backward compatible in all regards, but also allow for expressions like

    String result = x == 1 ? "one"
                  : y == 2 ? "two"
                  : z == 3 ? "three"
                  : fail();

Refer to this blog post: https://aioo.be/2016/06/28/returning-assert-method.html

**Comment by marcphilipp** [comment]
The `Assertions` class in JUnit Jupiter already does that. I'm assuming you're referring to the `Assert` class from JUnit 4. Therefore, I'm closing this issue. Feel free to open an issue in the junit4 repo instead. However, to be honest, it's unlikely that we're going to change it there. In case I misunderstood your request, please let me know.

**Comment by aioobe** [comment]
Look at that. I was looking at JUnit 4 and didn't realize it had been addressed in JUnit 5.
Thanks!
