### ISSUE TITLE
Upgrade to Spotless version based on Eclipse 4.5.1+

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#183]
## Background

For details, see:

- https://github.com/junit-team/junit5/pull/179
- https://github.com/diffplug/spotless/issues/15

## Deliverables

- [x] Once a version of Spotless that is based on Eclipse 4.5.1+ has been released, upgrade the JUnit 5 build to use it.

**Comment by sbrannen** [comment]
Performed in `master` using the team account: https://github.com/junit-team/junit5/commit/28637e6b6eeae797291c8f31902b09aa0fca594a

**Comment by marcphilipp** [comment]
Thanks! :+1:
