### ISSUE TITLE
Update API status in User Guide 

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1832]
## Overview

@fanngrim wrote on Mar 24 20:24 at https://gitter.im/junit-team/junit5

> Hi,
> I just noticed something in the documentation.
> The user guide states that Dynamic Tests are still an experimental feature but when checking the Experimental APIs table they are not listed there.
> Also, the TestFactory annotation is marked as MAINTAINED. Is the the documentation outdated?

## Deliverables

- [x] Remove outdated warning from Dynamic Tests section: https://github.com/junit-team/junit5/commit/1d9541999b3a38c6aa6c6f45e524753276fdc469
- [x] Verify other sections of the User Guide are in-sync with their annotations
  - [x] Capturing std out/err
  - [x] Parameterized Tests
  - [x] JUnit 4 `Rule` support
  - [x] JUnit 4 `@Ignore` support
  - [x] `@TempDir`
  - [x] Parallel test execution
  - [x] Test Kit

**Comment by sormuras** [comment]
Should we cherry-pick https://github.com/junit-team/junit5/commit/1d9541999b3a38c6aa6c6f45e524753276fdc469 on the 5.4.x branch and update the "current" user guide as well?

**Comment by sbrannen** [comment]
> Should we cherry-pick [1d95419](https://github.com/junit-team/junit5/commit/1d9541999b3a38c6aa6c6f45e524753276fdc469) onto the 5.4.x branch and update the "current" user guide as well?

Yes, I think that's a good idea.

**Comment by sormuras** [comment]
User Guide is in-sync with annotations.
