### ISSUE TITLE
Annotate user facing API with @API

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#1833]
The ``TempDirectory`` extension as well as others in https://github.com/junit-team/junit5/tree/835160321973c08ba03cd5792d6e42b2866aa98f/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension are effectively user APIs and should be annotated with their life-cycle status.

This is an interesting case because these classes are not in the API module, are specific to the Jupiter engine (they won't run in other test engines) but are explicitly advertised for use by test authors.  If we want to keep a strict separation between the API used by test authors and the engine, I suppose we could create a "jupiter extensions" module but in either case it's my opinion that these methods should be annotated and that tools for checking API guardian annotations should consider this package.

As an aside, do the API guardian tools consider unannotated targets as ``INTERNAL``?

Related to #1832 - ``@TempDir`` is listed in that issue which is a ``junit-jupiter-api`` use of the extension provided by ``junit-jupiter-engine``.

**Comment by marcphilipp** [comment]
`TempDirectory` is package-private and thus not visible. We don't annotate package-private classes with `@API`. Is there a reason why we should?

**Comment by sbrannen** [comment]
In line with the intended and documented usage of `@API`, I don't think we should start documenting non-public APIs.

The team is at liberty to change those as necessary or desired, and the public-facing documentation for the support provided by such implementations should be sufficient.

**Comment by smoyer64** [comment]
Sorry ... I didn't notice those class were packaged scoped.  I guess I assumed that the extensions underlying the ``@TempDir`` annotation were public to allow they're use in custom versions of the extensions.

**Comment by sbrannen** [comment]
> Sorry ... I didn't notice those class were packaged scoped. 

No worries.

> I guess I assumed that the extensions underlying the `@TempDir` annotation were public to allow they're use in custom versions of the extensions.

Ahhhh, well... that's another topic: #1786 😉
