### ISSUE TITLE
PR Codecov report not getting published

### ISSUE THREAD

**Issue by gopinath-langote** [junit-team/junit5#1841]
For recent PRs codecov reports are not available.
https://codecov.io/gh/junit-team/junit5/pulls

In the CI pipeline, Codecov `Coverage ` step (Codecov returning 400 for URL.)

```
    ‌query:‌ branch=merge&amp;commit=853385448e466fc4c64505a0d69a6065dba387b8&amp;build=20190401.4&amp;build_url=https%3A%2F%2Fdev.azure.com%2Fjunit-team%2Fjunit5%2F_build%2Fresults%3FbuildId%3D111&amp;name=&amp;tag=&amp;slug=junit-team%2Fjunit5&amp;service=azure_pipelines&amp;flags=&amp;pr=&amp;job=111‌
    ‌-&gt;‌ Pinging Codecov‌
https://codecov.io/upload/v4?package=bash-8a28df4&token=$(codecovToken)&branch=merge&commit=853385448e466fc4c64505a0d69a6065dba387b8&build=20190401.4&build_url=https%3A%2F%2Fdev.azure.com%2Fjunit-team%2Fjunit5%2F_build%2Fresults%3FbuildId%3D111&name=&tag=&slug=junit-team%2Fjunit5&service=azure_pipelines&flags=&pr=&job=111
HTTP 400‌
Provided token is not a UUID.‌
##[section]Finishing: Coverage
```

Ex Build: https://dev.azure.com/junit-team/junit5/_build/results?buildId=111

**Comment by marcphilipp** [comment]
The root cause is that `$(codecovToken)` is not expanded because its value is not being passed to PR builds for security reasons.

@brunoborges Is there a way to integrate Azure Pipelines with Codecov.io? IIRC Travis and Codecov.io were integrated directly without us having to pass a Codecov token.

**Comment by brunoborges** [comment]
I don't see an extension from them in the Marketplace, so I will assume there is no out of the box integration.

https://marketplace.visualstudio.com/search?term=codecov&target=AzureDevOps&category=Azure%20Pipelines&sortBy=Relevance

Hey @ethomson, do you know of anything?

**Comment by ethomson** [comment]
I'm not super familiar with codecov.io, but it _looks_ like it can derive the necessary information from some CI systems for public projects, without needing a token.  Let me see if I can find out how we can give them the necessary information or how they can get it from us...

**Comment by ethomson** [comment]
(In the meantime, I think that we'll need to keep providing the token.)

**Comment by marcphilipp** [comment]
@brunoborges @ethomson Thanks for looking into this! 👍
