### ISSUE TITLE
Provide a way to NOT inherit extensions in nested containers or methods

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#1842]
Sometimes an extension should not be applied to nested containers, e.g. if the extension wants to open and close a resource just once per annotated container. It seems to me that currently any registered extension will also be applied to its children and I couldn't find a way to switch that off.

The workarounds I can think of require strange things like storing the first context object in order to compare the current context object with it. I might be missing something, though.

## Related Issues

- #506

**Comment by sormuras** [comment]
Test authors should be in full-charge to decide what resource is to be used where. Extension authors should provide means to configure/setup that requirement using the existing model. If the extension model lacks such configuration, we need to improve it.

Said that, I favor a generic and built-in `ResourceSupplier` SPI as layed out here: https://github.com/sormuras/brahms#resource-manager-extension

**Comment by jlink** [comment]
I guess `ResourceSupplier` would solve my problem at hand. I am not sure, though, that the more general problem of deciding where exactly to apply an extension can be solved with it.

**Comment by sormuras** [comment]
With extensions comes complexity...

With `ResourceSupplier` you get explicit, type-safe and easy to see resources that you (as a test author) control. No need for an own extension. 3rd-party extensions may use the `ResourceSupplier` SPI to manage resources as well, but should (optionally) pass the control of creating/closing (read managing) to the test author.

**Comment by sormuras** [comment]
@testcontainers and other long-living resources are a perfect use-case: https://twitter.com/philipp_hauer/status/1112757852685430785

**Comment by sbrannen** [comment]
This is a duplicate of or subtask of #506.
