### ISSUE TITLE
Support MethodSource as custom test source in dynamic tests

### ISSUE THREAD

**Issue by magictractor** [junit-team/junit5#1850]
## Background

#1467 and #1178 added support for dynamic containers and tests specifying a custom test source via `DynamicNode.getTestSourceUri()`.

These `URI`s can be used to link dynamic tests and containers with a `FileSource`, `DirectorySource` or `ClasspathResourceSource`.

These sources may optionally have an associated line and column number, which is indicated by using a query string in the `URI`, such as `line=23&column=12`.

## Proposal

If a `URI` has a `classpath` scheme and a `method=myMethodName` query string then `TestFactoryTestDescriptor.fromUri(URI uri)` should create and return a `MethodSource`.

## Use cases

I initially encountered this when using `@TestFactory` to run a test suite without switching engines. That's working (bar linking back to methods in test cases from the test tree in Eclipse), but it is not a compelling use case since suites are being addressed by #744.

However, I can envisage other cases where this would be useful, such as verifying consistent use of Hibernate annotations across Java beans. Previously I've written cumbersome custom PMD rules for this. Dynamic tests could link back to getters in the application source rather than unit tests.

## Related issues

* #1467
* #1178

## Deliverables

- ❌  Add support for creating a `MethodSource` for a dynamic test if the custom test source `URI` uses the `classpath` scheme and a `method=myMethodName` query string.
- [ ] Introduce support for converting from a URI of the form `method:<FQMN>` to a `MethodSource`, where FQMN is the fully qualified method name. See the Javadoc for [`DiscoverySelectors.selectMethod(String)`](https://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectMethod(java.lang.String)) for the supported formats for a FQMN.
- [ ] Modify JavaDoc to explain supported `URI` schemas and query strings.
- [ ] Document in User Guide.
- [ ] Document in Release Notes.

**Comment by marcphilipp** [comment]
Thanks for raising the issue. I think that would make sense.

@junit-team/junit-lambda WDYT?

**Comment by marcphilipp** [comment]
Tentatively assigned to 5.5 M2 for _team discussion_.

**Comment by sbrannen** [comment]
**Team Decision**:

Although we do not foresee that many developers would use such a `MethodSource` to _link_ to non-test methods (as in the originally listed use cases), we can imagine that such a feature could be useful for linking to methods used as a method reference and similar use cases. We have therefore decided to go ahead with this proposal modified as follows.

Introduce support for converting from a URI of the form `method:<FQMN>` to a `MethodSource`, where FQMN is the fully qualified method name. See the Javadoc for [`DiscoverySelectors.selectMethod(String)`](https://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectMethod(java.lang.String)) for the supported formats for a FQMN.

Note that we will not reuse the `classpath:` scheme since that scheme is solely for "classpath resources" which a method is not.

**Comment by sbrannen** [comment]
This issue is currently "up for grabs".

**Comment by sbrannen** [comment]
FYI: the implementation of this feature should internally delegate to `org.junit.platform.commons.util.ReflectionUtils.parseFullyQualifiedMethodName(String)` for parsing the FQMN.

**Comment by gopinath-langote** [comment]
@sbrannen If no one is picked up this. I would like to pick this issue & submit PR.
Let me know!

**Comment by sbrannen** [comment]
@gopinath-langote, you're the first to volunteer. So feel free to submit a PR.

**Comment by ielatif** [comment]
@gopinath-langote did you get a chance to work on this? If not, I can pick it up if you don't mind?

**Comment by marcphilipp** [comment]
@ielatif Feel free to pick it up, if you're still interested.

**Comment by ielatif** [comment]
@marcphilipp Yes I still do.

@sbrannen 

> Ideally, the new method: scheme should be internal to JUnit Jupiter and not leaked into the JUnit Platform.

We can add a new class ex MethodFinder/MethodExtractor in org.junit.jupiter.engine.descriptor to implement the logic of extracting a method from URI `Optional<Method> findMethod(URI uri)` 

Or may be reuse org.junit.jupiter.engine.discovery.MethodFinder and add a new method `Optional<Method> findMethod(URI uri)` to it then change it's access level to be accesssed from `TestFactoryTestDescriptor`

**Comment by gopinath-langote** [comment]
@marcphilipp @sbrannen sorry for the late reply.

I did not get time to work on this. Someone else can pick this issue. 

I will look for the other one.


Thanks,
Gopinath

**Comment by ielatif** [comment]
@gopinath-langote I am on it. Thanks

**Comment by marcphilipp** [comment]
@gopinath-langote No worries, thanks for letting us know!

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 RC1 since PR #1895 has been submitted.

**Comment by ielatif** [comment]
@sbrannen @marcphilipp We should update issue Deliverables to reflect the changes.

**Comment by sbrannen** [comment]
> @sbrannen @marcphilipp we have to update issue Deliverables to reflect the changes.

Done 👍
