### ISSUE TITLE
Add support for an optional message with assertLinesMatch

### ISSUE THREAD

**Issue by tcfurrer** [junit-team/junit5#1855]
I love assertLinesMatch, but it seems odd that this is the only assertion that doesn't support an associated message.  Please add a version of assertLinesMatch that accepts a third argument for a String message, to be consistent with all other assertion types.  Thanks!

**Comment by sormuras** [comment]
Thanks for the feedback and I entatively assigned your request to 5.5 M2 for _team discussion_.

**Comment by marcphilipp** [comment]
**Team Decision:** Let's add overloads that take a `String` or `Supplier<String>`.

@tcfurrer Would you be interested in submitting a PR for this?

**Comment by marcphilipp** [comment]
@sormuras Or would you like to do this one?

**Comment by sormuras** [comment]
Yes, I do. Unless @tcfurrer has already a PR at hand.

**Comment by sormuras** [comment]
Where should the custom message appear? Prepend `(1)` or append `(2)` it to the existing one?

```java
String message = "XXX";
List<String> expected = Arrays.asList("a", "b", "c");
List<String> actual = Arrays.asList("a", "d", "c");

Error error = assertThrows(AssertionFailedError.class, () -> assertLinesMatch(expected, actual, XXX));
	List<String> expectedErrorMessageLines = Arrays.asList( //
		message + " ==> " + "expected line #2:`b` doesn't match ==> expected: <a", // (1)
		"b", //
		"c> but was: <a", //
		"d", //
		"c>" + "  ==> "+ message); (2)
assertLinesMatch(expectedErrorMessageLines, Arrays.asList(error.getMessage().split("\\R")));
```

**Comment by marcphilipp** [comment]
I think it should behave like all other assertions and prepend the message (1), possibly calling `AssertionUtils.buildPrefix`.

**Comment by sbrannen** [comment]
> I think it should behave like all other assertions and prepend the message (1), possibly calling `AssertionUtils.buildPrefix`.

Yes, please be consistent with the rest of the assertion messages.

So, +1 for both of Marc's comments.

**Comment by sormuras** [comment]
Alright. Will file a PR later today.

Will also improve the layout of the "difference message". From

```text
[custom message ==> ]more actual lines than expected: 1 ==> expected: <first line
second line
third line> but was: <first line
second line
third line
last line>
```

to

```text
[custom message ==> ]more actual lines than expected: 1 ==> expected: <
first line
second line
third line
> but was: <
first line
second line
third line
last line
>
```

**Comment by sbrannen** [comment]
LGTM
