### ISSUE TITLE
Convert methods in TestWatcher API to default methods

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1862]
## Overview

Methods in the `TestWatcher` API are currently abstract thereby forcing developers to implement all methods even if all events are not needed by the extension implementing the API.

## Deliverables

- [x] Convert methods in the `TestWatcher` API to default methods.
- [ ] Document in the Release Notes.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sormuras** [comment]
Covert or convert? ;-)

**Comment by sbrannen** [comment]
Ummm.... I'll convert covertly. 😛
