### ISSUE TITLE
Move PreconditionViolationException to commons base package

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1863]
## Overview

Follow-up from #1857 

## Deliverables

- [x] Deprecate `PreconditionViolationException` in package `org.junit.platform.commons.util` in favor a new sibling of `JUnitException` in the exported package `org.junit.platform.commons`.

**Comment by sormuras** [comment]
```text
> Task :junit-platform-commons:compileJava
\junit5\junit-platform-commons\src\main\java\org\junit\platform\commons\PreconditionViolationException.java:23: warning: [deprecation] PreconditionViolationException in org.junit.platform.commons.util has been deprecated
public class PreconditionViolationException extends org.junit.platform.commons.util.PreconditionViolationException {
                                                                                   ^
error: warnings found and -Werror specified
```

Hm...

**Comment by sormuras** [comment]
...after deleting the deprecated `PreconditionViolationException` from `org.junit.platform.commons.util`, everything's fine. Breaking (INTERNAL) change incoming?

**Comment by sormuras** [comment]
...using `-Xlint:-deprecation` a warning like this is shown:

```
> Task :junit-platform-commons:compileJava
Note: \junit5\junit-platform-commons\src\main\java\org\junit\platform\commons\PreconditionViolationException.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Not nice either. Which road do we take, @junit-team/junit-lambda?

**Comment by sbrannen** [comment]
> Which road do we take, @junit-team/junit-lambda?

Did you annotate the new `PreconditionViolationException` class with `@SuppressWarnings("deprecation")`?

**Comment by sormuras** [comment]
Yes. That helps within the IDE, but `javac` still emits a warning of category `exports`. Adding `exports` to the list of suppressed warning seems to work:

```
package org.junit.platform.commons;
// ...
@API(status = STABLE, since = "1.5")
@SuppressWarnings({ "deprecation", "exports" })
public class PreconditionViolationException
  extends org.junit.platform.commons.util.PreconditionViolationException
  {...}
```
