### ISSUE TITLE
Introduce TestInstancePreDestroyCallback as counterpart to TestInstancePostProcessor

### ISSUE THREAD

**Issue by joerg1985** [junit-team/junit5#1864]
## Overview

We use the `TestInstancePostProcessor` to inject handles to external resources. These resources need to be released after the tests is completed. 

Depending on the concrete test this might happen after each test method or after the class is completed.

We use the `TestInstance` `Lifecycle` to control the injection of new handles (for each method or for each class) and register to `afterEach` and `afterAll` to do the cleanup depending on the instance lifecycle. To make this work we have to do read the `Lifecycle`, check whether to release or collect instances, and so on.

## Proposal

With a `TestInstanceFinalizer` extension, executed after JUnit Jupiter is finished running tests in this particular test instances (depending on the Lifecycle), cleanup could be implemented more easily.

This would be the counterpart of the existing `TestInstancePostProcessor`; all other Extensions have a counterpart.

**Comment by sormuras** [comment]
Would it be possible to implement the https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/extension/ExtensionContext.Store.CloseableResource.html interface, pass your resource (or a wrapper object that holds it) to the context store and let store care about calling your close method?

**Comment by joerg1985** [comment]
@sormuras i had a look into it and the following issues are blocking us from using this approach:
- failures in the cleanup / release of a resource are not related to the original test. The original test is in status "passed", but the cleanup failed.
- all resources are releases at the end of the class, also for Lifecycle.PER_METHOD. Our resources are bound to a limited set of physical devices, shared between different people. This would end in tests not completed because the lack of free resources.

Is it possible to change the lifecycle of the Store to get it more bound to the TestInstance?

Thanks in advance and best regards
Jörg

**Comment by joerg1985** [comment]
Would a pull request with this TestInstanceFinalizer feature in principle be accept? 
I didn't try to implement it so far, but i would like to give it a chance.

Best regards
Jörg

**Comment by sbrannen** [comment]
> Would a pull request with this TestInstanceFinalizer feature in principle be accept?

Since the team has not yet decided to support such an extension API, a PR would not be appropriate at the moment.

However, I'm going to slate this for _team discussion_ for 5.6 since we have received similar requests for a `Store` bound to the current test instance for other use cases.

**Comment by marcphilipp** [comment]
Naming proposals from our team call:

- `TestInstanceFinalizer`
- `TestInstanceCleaner`
- `TestInstanceDestructor`
- `TestInstanceCloser`
- `TestInstancePreDestroyCallback`
- `TestInstanceEraser`
- `TestInstanceCleanupCallback`
- `JustBeforeAfterTestInstanceCallback`

Now we just need to decide on one of those or sth. better...

@joerg1985 Alternative proposals welcome!

**Comment by joerg1985** [comment]
@marcphilipp I my mind the TestInstancePostProcessor and the new class should be named as a common pair of words (like get/set, add/remove, start/stop, ...), because of their logical relation.
But this seems to be not possible due to the naming of the TestInstancePostProcessor or is it possible to rename the existing class? If this would be possible i would prefere to rename TestInstancePostProcessor too.
Apart from this i don't have any alternative proposals.

**Comment by sbrannen** [comment]
> or is it possible to rename the existing class?

No, it is not possible to rename `TestInstancePostProcessor`.

**Comment by marcphilipp** [comment]
**Team Decision:** Let's go with `TestInstancePreDestroyCallback`.

**Comment by stehrn** [comment]
I'd like to work on this please

**Comment by marcphilipp** [comment]
@stehrn Go ahead! 👍

**Comment by stehrn** [comment]
Summary of approach:

New:
TestInstancePreDestroyCallback - pass in testInstance object
TestInstancePreDestroyCallbackTests - be sure to assert if cleanup fails test should fail
Update:
ClassBasedTestDescriptor.after() - invoke TestInstancePreDestroyCallback's - derive testInstance from ExtensionContext
TestMethodTestDescriptor.execute() - invoke TestInstancePreDestroyCallback's after call to invokeAfterEachCallbacks, looks like can leverage invokeAllAfterMethodsOrCallbacks with TestInstancePreDestroyCallback.class
TestInstancePostProcessorTests

Implementation in progress, initial testing looks correct although more test cases required and documentation needs finishing - a few days effort remaining.

**Comment by marcphilipp** [comment]
> `TestInstancePreDestroyCallback` - pass in testInstance object

Yes, and the `ExtensionContext`.

> `TestMethodTestDescriptor.execute()` - invoke `TestInstancePreDestroyCallback's` after call to `invokeAfterEachCallbacks`, looks like can leverage `invokeAllAfterMethodsOrCallbacks` with  `TestInstancePreDestroyCallback.class`

Generally, it depends on the `TestInstance.Lifecycle` when `TestInstancePreDestroyCallback` needs to be called. You might be able to check whether the `TestInstances` in the `ExtensionContext` differ from the parent and, if so, only call it then.

**Comment by stehrn** [comment]
A few other commitments have pushed me back on this, if ok then should be in shape to provide PR for this weekend?

**Comment by marcphilipp** [comment]
Sure, go ahead!
