### ISSUE TITLE
Add Kotlin contracts to exposed Kotlin API

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-team/junit5#1866]
## Foreward
First off, I want to thank the Junit 5 team from being so willing to officially support Kotlin as a first-class citizen in the Junit 5 library. It has been absolutely wonderful being able to use my own contributions in all of my Kotlin projects.

## Feature Request

I believe that this API can be further enhanced with the new Kotlin 1.3 feature, [Contracts](https://kotlinlang.org/docs/reference/whatsnew13.html#contracts).

Contracts are making guarantees to the compiler that various methods have certain characteristics.

Here's an example from the Kotlin Std-Lib:

```kotlin
/**
 * Throws an [IllegalStateException] if the [value] is null. Otherwise
 * returns the not null value.
 *
 * @sample samples.misc.Preconditions.failCheckWithLazyMessage
 */
@kotlin.internal.InlineOnly
public inline fun <T : Any> checkNotNull(value: T?): T {
    contract {
        returns() implies (value != null)
    }
    return checkNotNull(value) { "Required value was null." }
}
```

Before Kotlin Contracts, the following code wouldn't have compiled:
```kotlin
fun validateString(aString: String?): String {
    checkNotNull(aString)
    return aString
}
```

I believe that JUnit 5 has a few places where these contracts would be valuable.

#### `assertNotNull`

```kotlin
@ExperimentalContracts
fun <T: Any> assertNonNull(actual: T?, message: String): T {
    contract {
        returns() implies (actual != null)
    }
    Assertions.assertNotNull(actual, message)
    return actual!!
}
```

The above would allow something like this:

```kotlin
val exception = assertThrows<IllegalStateException { /** whatever **/}
val message = exception.message
assertNotNull(message)
assertTrue(message.contains("some expected substring")) 
```

Alternatively, it would also allow for this sort of use case:
```kotlin
val message = assertNotNull(exception.message)
```

#### `assertThrows` / `assertDoesNotThrow`
Since the `callable` passed to `assertThrows` is only ever called once, we can expose that in the contract.
```kotlin
@ExperimentalContracts
inline fun <reified T : Throwable> assertThrows(noinline message: () -> String, noinline executable: () -> Unit): T {
    contract {
        callsInPlace(executable, InvocationKind.EXACTLY_ONCE)
    }
    return Assertions.assertThrows(T::class.java, Executable(executable), Supplier(message))
}
```

Similar 

This would for something like this:
```kotlin
val something: Int
val somethingElse: String
assertDoesNotThrow {
    something = somethingThatDoesntThrow()
    somethingElse = gettingSomethingElse()
}
```

## Caveats

Kotlin Contracts are only supported in Kotlin 1.3 and higher.
This would require a discussion regarding what version of Kotlin the Junit 5 team want's to officially support.

## Deliverables

- [ ] Add Kotlin method `assertNotNull`
- [ ] Add Contracts to Kotlin method `assertNotNull`
- [ ] Add Contracts to Kotlin method `assertThrows`
- [ ] Add Contracts to Kotlin method `assertDoesNotThrow`

**Comment by jbduncan** [comment]
This sounds like a useful usability feature!

**Comment by ephemient** [comment]
Please do this.

**Comment by TWiStErRob** [comment]
@junit-team What is missing to move this forward?

@JLLeitschuh I think these might also be deliverables for full coverage:
 * `assertNull` to get Kotlin compilation protection for `val actual = ...; assertNull(actual); actual.foo()` (`.foo()` would be a 100% NPE with current solution and it wouldn't compile with contracts)
 * `assertInstanceOf` (similar to non-null, but with `implies (actualValue is T)`)

**Comment by awelless** [comment]
Is anyone working on this issue?

**Comment by awelless** [comment]
Okay.
I could start working on it. However, it might take some time

**Comment by TWiStErRob** [comment]
@JLLeitschuh how can this be tested with automation? Because contracts should induce Kotlin compilation failures. I guess the positive cases of smart casts as results of contract can be tested:
```
val foo: String? = ...
assertNotNull(foo)
assertEquals(1, foo.size)
```
(if the contracts stop working, the above test will not compile)

**Comment by JLLeitschuh** [comment]
As you suggested, I would use the compiler as your validation

**Comment by awelless** [comment]
> I think these might also be deliverables for full coverage:
> ...
>     * `assertInstanceOf` (similar to non-null, but with `implies (actualValue is T)`)

Contracts with reified generics are [supported only since kotlin 1.4](https://youtrack.jetbrains.com/issue/KT-28298). Therefore, `assertInstanceOf` can't be implemented for now

**Comment by awelless** [comment]
Since kotlin version [has been bumped to 1.6](https://github.com/junit-team/junit5/blob/main/platform-tooling-support-tests/projects/gradle-kotlin-extensions/build.gradle.kts#L23), it should be possible to implement `assertInstanceOf` with a contract specified
