### ISSUE TITLE
Consider removing runtime scope on `junit:junit` from the Vintage engine

### ISSUE THREAD

**Issue by snicoll** [junit-team/junit5#1872]
The vintage engine currently has a `runtime` scope on JUnit 4. Strictly speaking, I can't argue this is wrong but it has several unpleasant side effects:

* With Maven, adding the vintage engine in `test`scope means that everything that it brings share that scope (`test`) so `junit` is on the test classpath and all is well.
* Gradle, on the other hand, looks at the scope in transitive dependencies and honours them. Adding the vintage engine in `testCompile` does not bring JUnit 4 to the test compile classpath.

Looking at your samples, this looks like [an intentional decision](https://github.com/junit-team/junit5-samples/blob/6b61ee73aa4e9f860ec7e2e34c025d58a3525a9c/junit5-migration-gradle/build.gradle#L27). 

Would it be possible to remove that scope from the vintage engine so that the story is more consistent between those two build systems? The same way we've asked you to add `junit-jupiter` to have one library that brings the necessary bits, I'd argue that adding the vintage engine should bring me the necessary bits to compile/run tests using JUnit 4.

We didn't notice this problem immediately when we migrated Spring Boot to JUnit 5. We've taken the decision [to add junit 4 explicitly in our starter](https://github.com/spring-projects/spring-boot/issues/16807) to make sure gradle-based projects are not broken on upgrade. Doing so makes it harder to switch purely to JUnit 5 as [two dependencies have to be excluded now](https://github.com/spring-projects/spring-boot/commit/81af0f2fa672d962d4c8569b6b7ee802008717c2#diff-3034c859fdf54b18876462585532bd82R6822).

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M2 for _team discussion_

**Comment by sormuras** [comment]
Didn't made up my mind, yet -- but we need to take into account, that JUnit 4 `junit:junit` is the mandated API for the Vintage engine. Additional background regarding `runtime` scope usages in Maven and Gradle by the Jupiter engine: https://sormuras.github.io/blog/2018-12-26-junit-jupiter-aggregator.html#usage-with-gradle-5

**Comment by sormuras** [comment]
### Jupiter `pom.xml`  w/o versions
```xml
  <dependencies>
    <dependency>
      <groupId>org.apiguardian</groupId>
      <artifactId>apiguardian-api</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-engine</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

### Vintage `pom.xml` w/o versions
```xml
  <dependencies>
    <dependency>
      <groupId>org.apiguardian</groupId>
      <artifactId>apiguardian-api</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-engine</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>runtime</scope> <!-- *** this should be compile *** -->
    </dependency>
  </dependencies>
```

I made up my mind. Let's do it as requested by @snicoll.

**Comment by ielatif** [comment]
@sormuras @sbrannen  I would like to pick-up this if it's up-for-graps?

**Comment by sormuras** [comment]
It's still scheduled for team discussion, which will happen on Friday.

**Comment by ielatif** [comment]
Thanks @sormuras I will watch it :)

**Comment by marcphilipp** [comment]
@snicoll Thanks for raising this issue! I think the original intention was to signal that users should choose a version of `junit:junit` >= 4.12. While the 4.13 release will come of soonish, we won't upgrade the dependency version in junit-vintage-engine but users can choose a to use the newer version.

Regarding Gradle, you shouldn't add junit-vintage-engine as a `testCompile` dependency, it should really be `testRuntimeOnly`. Thus, you'll have to add `junit:junit` yourself anyway.

That being said I think it would be more consistent and also more correct conceptually to use `compile` scope for `junit:junit` in `junit-vintage-engine`. I'll change that.
