### ISSUE TITLE
Improve String-based comparison in assertLinesMatch

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1876]
Extra new line characters were introduced in https://github.com/junit-team/junit5/pull/1861/files#diff-1d1ebfdfa50596f4e0ecb4039d842b03R167 to improve textual layout of the comparison of non-matching lists of lines on the console. See the changes made to the unit test within the linked commit.

tl;dr
Match two single-line lists, like:
```java
assertLinesMatch(List.of("single line"), List.of("another line"));
```
...yields on the console:
```
...
  => org.opentest4j.AssertionFailedError: expected line #1:`single line` doesn't match ==> expected: <
single line
> but was: <
another line
>
```
...but in IDE(a)s the extra new lines disturb the diff view:
![image](https://user-images.githubusercontent.com/2319838/57603562-4ec09700-7562-11e9-8245-a1cd0316e41f.png)

Users may be confused by where lines 1 and 3 originate from...

@junit-team Remove the extra new lines or keep them?

**Comment by sbrannen** [comment]
This is what it looks in Eclipse running against `master`.

![Screenshot 2019-05-13 at 13 08 39](https://user-images.githubusercontent.com/104798/57617157-660e7d00-7580-11e9-9168-c221fa7bc786.png)

> ...but in IDE(a)s the extra new lines disturb the diff view:

I don't know that it is really disturbing as long as you focus on the differences, but I admit it may make people wonder why there are magically now extra lines.

In summary, I have no problem with reverting the change, but let's see what other say.

p.s. It's better to use @junit-team/junit-lambda instead of `@junit-team` when addressing the JUnit 5/Lambda team. 😉

**Comment by sormuras** [comment]
@marcphilipp suggested to [only enrich the created failure message](https://github.com/junit-team/junit5/compare/issues/1876-only-add-extra-lines-in-message) with wrapping new line characters and leave the original lists (expected and actual) untouched. That works fine IDEA, and should also in Eclipse and other IDE's that inspect the values of the failure object.

**Comment by sbrannen** [comment]
> That works fine IDEA, and should also in Eclipse and other IDE's that inspect the values of the failure object.

I'm not sure how Eclipse produces the comparison dialog for OTA exceptions.

Though... in the past (i.e., for JUnit 4 assertion failures), I think Eclipse parsed the text of the exception message.

So we'll have to experiment in Eclipse.

@noopur2507, can you provide any insight here?

**Comment by sormuras** [comment]
Implemented the suggestion and a bug fix via https://github.com/junit-team/junit5/commit/4fe8b6356178b11c21ee6b3c0dce6268377ced1d -- need to double-check what it looks like in Eclipse. Therefore, I leave the issue open.

**Comment by sbrannen** [comment]
I just checked it in Eclipse for `assertLinesMatchFailsWithDescriptiveErrorMessage()` (throwing the error), and here's what it looks like

![Screenshot 2019-05-23 at 18 00 59](https://user-images.githubusercontent.com/104798/58267979-e2753d00-7d84-11e9-8c72-da08a04d0758.png)

So.... all good for Eclipse. 👍

**Comment by sormuras** [comment]
Thanks, Sam!
