### ISSUE TITLE
Missing opens directives in module descriptors

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1877]
### Description

Having declared

```java
@Test
@EnabledOnJre(JRE.JAVA_11) void test() {}
```

or other usages of Jupiter API that internally needs to access _package private_ types yields:

```
Unable to make org.junit.jupiter.api.condition.EnabledOnJreCondition() accessible:
module org.junit.jupiter.api does not "opens org.junit.jupiter.api.condition"
                                   to module org.junit.platform.commons
```

Module `org.junit.jupiter.api` is declared like follows:
```java
module org.junit.jupiter.api {
	requires transitive org.apiguardian.api;
	requires transitive org.junit.platform.commons;
	requires transitive org.opentest4j;

	exports org.junit.jupiter.api;
	exports org.junit.jupiter.api.condition;
	exports org.junit.jupiter.api.extension;
	exports org.junit.jupiter.api.function;
	exports org.junit.jupiter.api.io;
	exports org.junit.jupiter.api.parallel;
}
```

Exporting _public_ types from all 6 packages doesn't allow deep reflective access to non-public types. Thus, directives like `opens org.junit.jupiter.api.condition to org.junit.platform.commons;` need to added to this module descriptor. This goes also for all other modules that make use of the reflection support provided by module `org.junit.platform.commons`.

#### Reflecting code uses
* Usages of `@ExtendWith` in JUnit "Project Production Java Files"
![image](https://user-images.githubusercontent.com/2319838/57631781-76ceeb00-75a0-11e9-90ad-0ac736af099f.png)

### Deliverables
- [ ] Write integration test that shows the issue.
- [ ] Fix by adding appropriate `opens to org.junit.platform.commons` directives.
- [ ] Find other places where reflection support from `org.junit.platform.commons` is used.

**Comment by sormuras** [comment]
Updated initial issue description.

**Comment by sormuras** [comment]
### JUnit 5 - `documentation` as modular test
```
java
--show-version
--show-module-resolution
--module-path {...}
--add-modules documentation
--module org.junit.platform.console
--scan-modules
--include-classname .*Tests
--include-classname .*Demo
--exclude-tag exclude
```
- test run module resolution https://gist.github.com/sormuras/9cb94d59805b1435f6e80de2776cf128
- test run tree https://gist.github.com/sormuras/9ce9155988cf2166b0ac28299aa18d48

```
28 containers failed
20 tests failed
```

**Comment by Mamadou59** [comment]
Hello, 
I have a question about personnal JUnit extension.
I created a JUnit extension in a maven plugin project and i want to use this plugin and also the JUnit extension in another  project but i have no idea haw can i manage an export and import dependencies of the maven plugin and also his JUnit extension!
Thank you for help!

**Comment by marcphilipp** [comment]
@Mamadou59 This issue tracker is usually not the best place to get answers to such questions. I think if you post this question on StackOverflow you're far more likely to get a helpful answer. Having said that, assuming your custom extension is in the test source folder, you should be able to [build a test-jar](https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html) and consume it in the other project.
