### ISSUE TITLE
Replace `Path` with `File` in docs for TempDir

### ISSUE THREAD

**Issue by StefMa** [junit-team/junit5#1878]
I'm not sure why you use `Path` instead of `File` in your documentation for the `TempDir` feature.
But I think that should be changed to `File` because this is way more common to use instead of `Path`.

**Comment by sormuras** [comment]
I'm totally fine with using and documenting `Path` here.

> [...] to `File` because this is way more common to use instead of `Path`.

Out of curiosity, do you have any numbers? How much is "way more"? Based on which sample set?

**Comment by marcphilipp** [comment]
I agree with @sormuras on this one. Maybe we should switch one of the examples to use `File`?

**Comment by sbrannen** [comment]
I see no reason to replace all examples of `Path` with `File`, since `Path` is the more modern API and generally recommended over `File`. Plus, the documentation explicitly states that one can use `Path` or `File`.

The only thing I could imagine us changing is including a separate example using `File` instead of `Path`, but I don't personally see how that would add much value.

**Comment by sbrannen** [comment]
> Maybe we should switch one of the examples to use `File`?

Hmmm.... two posts crossed paths in the ether......

**Comment by StefMa** [comment]
> Out of curiosity, do you have any numbers? How much is "way more"? Based on which sample set?

No, I haven't any numbers 🙃 .
But it based on my experience especially with Junit4. Where we use `newFile()`.
Also - from what I know as an Android Developer - `File` is literally used everywhere when doing something with the file system.

> since Path is the more modern API and generally recommended over File.

I didn't know that `Path` is more modern than `File`.
But after googling a little bit around it true that `Path` is way younger than `File` 🙃 

Maybe I was too optimistic by creating this issue without inform myself about the `Path` object.
Seems Junit5 is more in the future than the Android eco system 😉
Sry for the deflection. You can now go back to work 😄 

deflection |  
-- | --




deflection |  
-- | --

**Comment by sbrannen** [comment]
> Sry for the deflection. You can now go back to work 😄

No worries. Glad to hear you learned something in the process! 👍
