### ISSUE TITLE
Website: Replace "JUnit Lambda" references

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#188]
Fix the current website so that it has areas for JUnit 4 and 5 and Lambda is replaced by JUnit 5.

**Comment by jlink** [comment]
Just pushed an updated version of the old website: https://github.com/junit-team/junit/commit/5345833c6b382646ced3060a8dbc85763e7bc817

**Comment by jlink** [comment]
Created follow up issue #205.

**Comment by sbrannen** [comment]
Thanks!
