### ISSUE TITLE
Add ability to access the current repetition of a RepeatedTest from afterEach in a custom Extension

### ISSUE THREAD

**Issue by vmassol** [junit-team/junit5#1884]
My use case:

* At the end of each test, save a video of the test in a file.
* It has to support the `@RepeatedTest` annotation and thus the computed file name must include the repetition index.

It seems the info is in RepeatedTestInvocationContext but there are 2 issues:

1. I don't know how to get access to that object in my afterEach, i.e. from an ExtensionContext. I guess I could use instanceof on the parent but it seems it's a TestTemplateExtensionContext so it wouldn't even work (and it feels hacky ;))
2. Even if I were able to get access to RepeatedTestInvocationContext it doesn't contain any API to get the current repetition. The only thing it offers is a custom displayName but having to parse that to get the repetition index doesn't feel right.

## Related Issues

- #944
- #1139
- #1668

**Comment by marcphilipp** [comment]
I agree that this would be useful. 👍

**Comment by dlapunas** [comment]
This would be very useful for us, since we use a custom extension with log4j to separate test logs into different files.
Current workaround:
```
private static final Pattern REPEATED_TEST_PATTERN = Pattern.compile("^repetition (\\d+) of (\\d+)$");

private static String parseRepetition(ExtensionContext context) {
        String displayName = context.getDisplayName();
        Matcher matcher = REPEATED_TEST_PATTERN.matcher(displayName);
        if (matcher.matches()) {
            int charCount = matcher.group(2).length();
            int repetition = Integer.parseInt(matcher.group(1));
            String format = "%0" + charCount + "d";
            return String.format(format, repetition);
        } else {
            return null;
        }
    }
```
