### ISSUE TITLE
[Kotlin] Compiler picks assertTimeout(Duration, Executable) over assertTimeout(Duration, ThrowingSupplier<T>)

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-team/junit5#1887]
## Steps to reproduce

The following does not compile with the Kotlin compiler.

```kotlin
private fun timeoutTest(): Int {
    return assertTimeout(Duration.ofSeconds(1)) {
        42
    }
}
```

<img width="413" alt="Screen Shot 2019-05-20 at 12 06 55 PM" src="https://user-images.githubusercontent.com/1323708/58036132-62d33e00-7af8-11e9-989c-079c862aa3d1.png">

## Cause

The Kotlin compiler incorrectly picks the `void assertTimeout(Duration timeout, Executable executable)` over the `<T> T assertTimeout(Duration timeout, ThrowingSupplier<T> supplier)` implementation of the method.

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.4.0
 - Build Tool/IDE:
```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

## Deliverables

- [ ] Add explicit Kotlin implementation of `assertTimeout`.

**Comment by JLLeitschuh** [comment]
I believe that these are the required methods to resolve this issue:

```
fun <R> assertTimeout(timeout: Duration, executable: () -> R): R =
    Assertions.assertTimeout(timeout, executable)

fun <R> assertTimeout(timeout: Duration, message: String, executable: () -> R): R =
    Assertions.assertTimeout(timeout, executable, message)

fun <R> assertTimeout(timeout: Duration, message: () -> String, executable: () -> R): R =
    Assertions.assertTimeout(timeout, executable, message)

fun <R> assertTimeoutPreemptively(timeout: Duration, executable: () -> R): R =
    Assertions.assertTimeoutPreemptively(timeout, executable)

fun <R> assertTimeoutPreemptively(timeout: Duration, message: String, executable: () -> R): R =
    Assertions.assertTimeoutPreemptively(timeout, executable, message)

fun <R> assertTimeoutPreemptively(timeout: Duration, message: () -> String, executable: () -> R): R =
    Assertions.assertTimeoutPreemptively(timeout, executable, message)
```

**Comment by marcphilipp** [comment]
@JLLeitschuh Looks good to me! Would you be interested in submitting a PR?

**Comment by JLLeitschuh** [comment]
Yea, I'm working on it currently.

**Comment by JLLeitschuh** [comment]
@marcphilipp Any good suggestions for testing these beyond just copy and pasting the existing tests from Java and having them in Kotlin as well?
