### ISSUE TITLE
Remove or update translation links in User Guide

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1890]
From https://github.com/junit-team/junit5/pull/1198#issuecomment-494631822:

> http://sjyuan.cc/junit5/user-guide-cn now is 404 - There isn't a GitHub Pages site here.

## Deliverables

- [ ] Fix link or remove it

**Comment by marcphilipp** [comment]
@sjyuan-cc Please help! 🙂

**Comment by marcphilipp** [comment]
The Japanese translation is still available but outdated (based on 5.2.0).

@tsukakei Do you have plans to update that?

**Comment by tsukakei** [comment]
Hi @marcphilipp 
Thank you for asking!
We're sorry to say that we don't have plans to update that...

**Comment by sbrannen** [comment]
@tsukakei, thanks for letting us know.

Since we have not heard back from @sjyuan-cc either, we will remove both links for the time being.
