### ISSUE TITLE
Introduce support to add additional info for TestIdentifiers

### ISSUE THREAD

**Issue by performrumpf** [junit-team/junit5#1892]
TestExecutionListener is very useful to write custom reports, trace tests or view test plans. Informations like displayname, test source and legacy report name are already very useful for most situations.

But what if those infos from TestIdentifier are not enough? What if for creating reports etc. more informations are needed (i.e. like "usecase_ID", "authors" or "description") even before execution phase (ReportEntry only works during execution phase)? These infos could be stored in a Map<String,String> or Map<String,Object> for that purpose.

Therefore it would be useful to introduce mechanics to add additional informations. This would require extensions in a few areas:

Examples:
`Map<String,String> TestIdentifier.getAdditionalInfos()`
`Optional<String> TestIdentifier.getAdditionalInfo(String key)`

I can imagine following way to add these infos to TestIdentifier (in Jupiter)

- `@Info(key = "key", value = "value")` can be used to add additional infos to Class- or MethodTestDescriptors (repeatable annotation)
- TestDescriptor needs to be extended to return a Map<String,Object>
- `TestIdentifier.from(TestDescriptor descriptor)` needs to be extended to get this info map from TestDescriptor

That way TestIdentifier is more flexible for report creating frameworks (i.e. [Extent Report](http://extentreports.com/)) using not just Jupiter Engine but also custom TestEngine implementations.

**Comment by sormuras** [comment]
Related to https://github.com/ota4j-team/opentest4j/issues/9

**Comment by performrumpf** [comment]
Just a simple thought: with `ClassSource#getJavaClass()` you can get a `Class<?>` instance of a TestIdentifier container. That way you have access to all its annotations and "infos" you might need for a report.

On the other hand, `MethodSource` doesn't have a `MethodSource#getJavaMethod()` method to do the same thing. Honestly I can imagine why this method is absent, but is there a way to include a method to return all annotations of the test method?

**Comment by sbrannen** [comment]
> On the other hand, `MethodSource` doesn't have a `MethodSource#getJavaMethod()` method to do the same thing. Honestly I can imagine why this method is absent, 

The reason is that `java.lang.reflect.Method` is not `Serializable`.

However, it should be possible to add methods for loading the Java Class and Java Method lazily via reflection.

Feel free to open a new issue to request that.

**Comment by marcphilipp** [comment]
Related to #1900.
