### ISSUE TITLE
Provide a public API for creating a MethodSource with a class name, method name, and a Class[] of parameters

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#1893]
Spock uses AST-Transformations to turn its expressive method names (e.g., "a nice descriptive test name") into "safe" method names in the bytecode `$spock_feature_1_0`.

Due to the issue with Intellij [IDEA-214779](https://youtrack.jetbrains.com/issue/IDEA-214779) we can't use `MethodSource.from(java.lang.reflect.Method)` but have to use the `org.junit.platform.engine.support.descriptor.MethodSource#from(java.lang.String, java.lang.String, java.lang.String)` variant. Unfortunately, `org.junit.platform.commons.util.ClassUtils#nullSafeToString(java.lang.Class<?>...)` is internal, so we would have to duplicate the implementation.

## Deliverables

- ❌ Make `org.junit.platform.commons.util.ClassUtils#nullSafeToString(java.lang.Class<?>...)` public and/or
- [ ] Add `org.junit.platform.engine.support.descriptor.MethodSource#from(java.lang.String, java.lang.String, java.lang.Class<?>...)` with the varargs being the parameter types..

**Comment by sbrannen** [comment]
Thanks for raising the issue.

>     * [ ]  Add `org.junit.platform.engine.support.descriptor.MethodSource#from(java.lang.String, java.lang.String, java.lang.Class<?>...)` with the varargs being the parameter types..

I'm more in favor of this option.

@junit-team/junit-lambda, thoughts?

**Comment by sormuras** [comment]
> I'm more in favor of this option.

👍

**Comment by marcphilipp** [comment]
+1

**Comment by sbrannen** [comment]
OK. It seems we are in agreement.

@leonard84, are you interested in submitting a PR for this?
