### ISSUE TITLE
ConsoleLauncher's class-path scanning sometimes does not work

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1898]
## Steps to reproduce

_Working on a minimal non-working example..._

## Context

Starting the `ConsoleLauncher` via reflection and in-process in a layered class loader setup works as expected. Adding multiple drives (on Windows) into the equation results in the class-path scanning no longer finding tests. It is **similar**(!) to the following snippet:
```
C:\>java 
  --class-path junit-platform-console-standalone.jar
  ...
  ConsoleLauncher 
  ...
  --class-path 
     Z:\project\main-classes;Z:\project\test-classes
  --scan-class-path
```

## Deliverables

- [ ] Investigate underlying issue

**Comment by sbrannen** [comment]
Tentatively labeled as a _bug_

**Comment by marcphilipp** [comment]
Closing due to lack of reproducer and activity.
