### ISSUE TITLE
Document URI TestSource support of dynamic tests in User Guide

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1903]
When URI `TestSource` support for dynamic tests was extended in #1895, we noticed that we don't have any documentation for this feature in the User Guide.

## Deliverables

- [ ] Add a subsection that documents the different supported URI formats with examples

**Comment by ielatif** [comment]
@marcphilipp as discussed in #1895 I will add the documentation for 5.5 GA

**Comment by marcphilipp** [comment]
Great! Feel free to start working on it. If we can get it into 5.5 RC1 that would be even better. 🙂
