### ISSUE TITLE
Prefer public methods when creating Vintage MethodSource

### ISSUE THREAD

**Issue by obelix74** [junit-team/junit5#1904]
I am working on porting a legacy application to JUnit5.  The test framework implements a `TestExecutionListener` which is listening for `executionStarted` and `executionFinished` methods and from the `TestIdentifier`, extract the `TestSource` and find out if it is a `ClassSource` or a `MethodSource` and do some operations based on that (the tests are cached and a TESTSUITES.xml file built at the end).

What I notice is with a legacy JUnit4 test, if there is a test, say

```java
@Test 
public void foo() {

}
```

and the test also has a private overriden method with the same name:

```java
private void foo(final boolean arg) {
}
```

then in the `executionStarted` and `executionFinished` callbacks, the `TestSource` contained in the `TestIdentifier` are for a `ClassSource` and not a `MethodSource`.  I lose all information on that _specific_ method being tested.

Attached a reproducible unit test and the build.gradle file.

```java
import java.io.PrintWriter;
import java.util.HashSet;
import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.platform.engine.TestExecutionResult;
import org.junit.platform.engine.TestSource;
import org.junit.platform.engine.discovery.DiscoverySelectors;
import org.junit.platform.engine.support.descriptor.MethodSource;
import org.junit.platform.launcher.Launcher;
import org.junit.platform.launcher.LauncherDiscoveryRequest;
import org.junit.platform.launcher.TestExecutionListener;
import org.junit.platform.launcher.TestIdentifier;
import org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder;
import org.junit.platform.launcher.core.LauncherFactory;
import org.junit.platform.launcher.listeners.SummaryGeneratingListener;
import org.junit.platform.launcher.listeners.TestExecutionSummary;

public class TestLauncher {

    @Test
    public void testLauncher() {

        final Launcher launcher = LauncherFactory.create();
        final LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
                .selectors(DiscoverySelectors.selectClass(SimpleLegacyTest.class)).build();
        final SummaryGeneratingListener listener = new SummaryGeneratingListener();
        final SimpleListener simpleListener = new SimpleListener();
        launcher.registerTestExecutionListeners(listener, simpleListener);
        launcher.execute(request);
        final TestExecutionSummary summary = listener.getSummary();
        summary.printTo(new PrintWriter(System.out));
        Assertions.assertEquals(summary.getTestsFoundCount(), simpleListener.methods.size());
    }

    private static class SimpleListener
            implements TestExecutionListener {

        private final Set<String> methods = new HashSet<>();

        @Override
        public void executionFinished(final TestIdentifier testIdentifier,
                                      final TestExecutionResult testExecutionResult) {
            final String message = String.format("Execution Finished: %s - %s - %s",
                    testIdentifier.getDisplayName(), testIdentifier.getUniqueId(), testExecutionResult);
            System.out.println(message);
            if (testIdentifier.getSource().isPresent()) {
                final TestSource testSource = testIdentifier.getSource().get();
                if (testSource instanceof MethodSource) {
                    this.methods.add(((MethodSource) testSource).getMethodName());
                }
            }
        }
    }

    public static class SimpleLegacyTest {
        @org.junit.Test
        public void testFoo() {

        }

        @org.junit.Test
        public void testBar() {

        }

        @org.junit.Test
        public void foobar() {

        }

        private void testFoo(final boolean flag) {

        }

        private void testBar(final boolean flag) {

        }
    }
}
```

```groovy
plugins {
    id 'java'
}

group 'test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.4.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.4.2'
    compile("org.junit.platform:junit-platform-launcher:1.4.2")
    testCompile("org.junit.vintage:junit-vintage-engine:5.4.2")
}

test {
    useJUnitPlatform {
        excludeTags 'slow'
        includeEngines 'junit-jupiter', 'junit-vintage'
    }
}
```

Notice that the `SummaryGeneratingListener` contains the correct number of tests executed (3), but the methods tested only has one (the only method without a non conflicting name).

Also note that, if there are no legacy tests, then this does not fail.

**Comment by sbrannen** [comment]
> then in the `executionStarted` and `executionFinished` callbacks, the `TestSource` contained in the `TestIdentifier` are for a `ClassSource` and not a `MethodSource`.

Thanks for raising the issue and supplying the test case!

I can confirm that this is a bug.

**Comment by marcphilipp** [comment]
Ironically, I originally implemented it this way to avoid passing the wrong `TestSource` to the `TestDescriptor` for cases like the following (from our test suite):

https://github.com/junit-team/junit5/blob/5e41ebe612fd67e905f96f1dd3184a071b65be17/junit-vintage-engine/src/test/java/org/junit/vintage/engine/samples/junit4/JUnit4TestCaseWithOverloadedMethod.java#L29-L37

The problem is that the `Description` object that we get from JUnit 4 is basically the String `theory(org.junit.vintage.engine.samples.junit4.JUnit4TestCaseWithOverloadedMethod)` which we cannot use to differentiate between the two methods. So, instead of choosing one at random, I decided to bail out and just use the `ClassSource`. The intention of the `TestSource` API was and still is mainly to allow for navigation to the source code in IDEs.

I guess we could apply a few heuristics to the method lookup. For instance, only take into account `public` methods if we find multiple.

@junit-team/junit-lambda WDYT?

**Comment by obelix74** [comment]
Thank you.  I understand the limitations of Description. I ran into this quite a bit with the way the test framework is designed as well. 

I guess the surest fix is to simply port the tests over to JUnit5, but we are talking tens of thousands of tests written over a 15 year period by hundreds of developers :(.

**Comment by sbrannen** [comment]
> I guess we could apply a few heuristics to the method lookup. For instance, only take into account `public` methods if we find multiple.

If there is no way to disambiguate otherwise, then yes, I am in favor of applying some sort of "best guess" heuristics.

**Comment by marcphilipp** [comment]
I think as a first step preferring public methods would make sense and add support for this use case so I'll add that.
