### ISSUE TITLE
Upgrade to JDK 13

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1906]
## JDK 13

"JDK 13, the reference implementation of Java 13, is now Generally Available." as of `2019-09-17`.

https://jdk.java.net/13/

-   350: Dynamic CDS Archives
-   351: ZGC: Uncommit Unused Memory
-   353: Reimplement the Legacy Socket API
-   354: Switch Expressions (Preview)
-   355: Text Blocks (Preview)

## Deliverables

- [ ] Upgrade to JDK 13 as the minimum to build "JUnit 5"
- [ ] ~~Make use of Java [Text Blocks](https://openjdk.java.net/jeps/355) syntax in our test code~~
- [ ] Remove JDK 12 from the build matrix, it reached EOL

**Comment by sormuras** [comment]
Updated initial issue description.

**Comment by sormuras** [comment]
Blocked by Gradle not running on Java 13: https://github.com/gradle/gradle/issues/10785#issuecomment-533011768

**Comment by marcphilipp** [comment]
I don't think we're blocked by that since we don't have any Groovy buildscripts.

**Comment by sormuras** [comment]
Blocked we are: `settings.gradle.kts` can't resolve `isJava13Compatible`

![image](https://user-images.githubusercontent.com/2319838/65305876-71079880-db84-11e9-90ab-22a3b2cbe443.png)
