### ISSUE TITLE
Relax RegisterExtension field type restriction

### ISSUE THREAD

**Issue by philwebb** [junit-team/junit5#1908]
Due to the checks in [ExtensionUtils.IsNonStaticExtensionField](https://github.com/junit-team/junit5/blob/463a838002b1603853e8e5cb528d4a9ade9a22d7/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ExtensionUtils.java#L140) and [ExtensionUtils.IsStaticExtensionField](https://github.com/junit-team/junit5/blob/463a838002b1603853e8e5cb528d4a9ade9a22d7/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ExtensionUtils.java#L158) it is not currently possible to use `@RegisterExtension` on fields that do not implement `Extension`. Furthermore, no warning or error is produced telling the developer that the extension is not active.

I wonder if this restriction could be relaxed, and the `@RegisterExtension` annotation alone be used as the trigger. If the actual field instance does not implement `Extension` then an error could be raised.

The specific driver for this issue is to allow a `@RegisterExtension` class that does not present JUnit specific APIs to the user. i.e.:

```java
public class UserFacingApi {
  // .. API methods the user will want
}

public class ExtensionClass extends UserFacingApi implement Extension... {
  // .. JUnit methods that the user should not call
}
```

```java
@RegisterExtension
private UserFacingApi userFacing = new ExtensionClass();
```

(see https://github.com/spring-projects/spring-boot/issues/17029 for a real use-case)

**Comment by sbrannen** [comment]
Sounds legit to me.

I'll see what I can do.

**Comment by sbrannen** [comment]
_in progress_: investigating options

**Comment by sbrannen** [comment]
Thanks for raising the issue, @philwebb, and for helping to improve JUnit Jupiter!

This has also inspired improved diagnostics for `private` `@RegisterExtension` fields (see #1912).
