### ISSUE TITLE
Introduce assertions for java.util.Optional

### ISSUE THREAD

**Issue by stolle** [junit-team/junit5#1920]
It would be convenient to have some type safe shortcuts to test the content of an Optional for its presence and value. This has been discussed a few times like: https://stackoverflow.com/questions/38954742/assert-that-optional-has-certain-value

The following Assertions methods shall explain, what I have in mind:

```java
    public static void assertEmpty(Optional optional) {
        assertNotNull(optional);
        assertTrue(optional.isEmpty());
    }

    public static void assertPresent(Optional optional) {
        assertNotNull(optional);
        assertTrue(optional.isPresent());
    }

    public static <T> void assertContains(T expected, Optional<T> actual) {
        assertNotNull(expected);
        assertPresent(actual);
        // maybe even more strict: assertEquals(optional.get().getClass(), value.getClass());
        assertEquals(actual.get(), expected);
    }
```

**Comment by sormuras** [comment]
Interesting idea.

`assertPresent()` could also return the object contained in the optional instance...

**Comment by stolle** [comment]
Yep, definitely. This would look like:

    public static <T> T assertPresent(final Optional<T> optional) {
        assertNotNull(optional);
        assertTrue(optional.isPresent());
        return optional.get();
    }

**Comment by stolle** [comment]
And there should be methods for OptionalLong, OptionalInt and OptionalDouble as well.

**Comment by sbrannen** [comment]
To be perfectly honest, I'm not convinced that we should be adding additional categories of assertions to JUnit Jupiter.

Third-party frameworks like AssertJ already provide excellent support for `java.util.Optional`.

@junit-team/junit-lambda, thoughts?

**Comment by marcphilipp** [comment]
I agree.

**Comment by sormuras** [comment]
Convinced.

**Comment by sbrannen** [comment]
**Team Decision**: we will not introduce dedicated assertions for `Optional`, and we encourage developers to use third-party assertion frameworks when greater power and/or expressiveness is desired.

Quoting from the [User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions-third-party):

> Even though the assertion facilities provided by JUnit Jupiter are sufficient for many testing scenarios, there are times when more power and additional functionality such as matchers are desired or required. In such cases, the JUnit team recommends the use of third-party assertion libraries such as AssertJ, Hamcrest, Truth, etc. Developers are therefore free to use the assertion library of their choice.
