### ISSUE TITLE
Support first/last order for extensions registered via @RegisterExtension

### ISSUE THREAD

**Issue by ihorppp** [junit-team/junit5#1924]
## Question

Would it be possible to have `@Order` annotation take priority over reverse execution order of `AfterEachCallback` extensions?

## Overview

Assume I want extension annotated with `@Order(1)` executed first:

```java
class Tests {

    @Order(1)
    @RegisterExtension
    AfterEachCallback first = (context -> System.out.println("first"));

    @RegisterExtension
    AfterEachCallback second = (context -> System.out.println("second"));

    @RegisterExtension
    AfterEachCallback third = (context -> System.out.println("third"));

    @RegisterExtension
    AfterEachCallback fourth = (context -> System.out.println("fourth"));

    @Test
    public void test1(){
        System.out.println("test");
    }
}
```

However per extension execution order the result is currently:

```
test
third
second
fourth
first
```

To have first extension executed first I have to annotate each and every extension (including superclasses):

```java
class Tests {

    @Order(4)
    @RegisterExtension
    AfterEachCallback first = (context -> System.out.println("first"));

    @Order(3)
    @RegisterExtension
    AfterEachCallback second = (context -> System.out.println("second"));

    @Order(2)
    @RegisterExtension
    AfterEachCallback third = (context -> System.out.println("third"));

    @Order(1)
    @RegisterExtension
    AfterEachCallback fourth = (context -> System.out.println("fourth"));

    @Test
    public void test1(){
        System.out.println("test");
    }
}
```

Then I get the result I want:

```
test
first
second
third
fourth
```

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M1 for _team discussion_

**Comment by sbrannen** [comment]
Brainstorming:

- Something like JUnit 4's `RuleChain` (discussed with @sormuras) -- though that requires potentially copying a lot of the internal logic of the `JupiterTestEngine`.
- Something like `@javax.annotation.Priority` combined with `@Order`.

**Comment by sormuras** [comment]
Um, doesn't Jupiter already support this feature?

https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic

**Comment by ihorppp** [comment]
Yes, it works with extensions whose execution order is not reversed. However to make AfterEachCallback extension executed first all others should also be annotated with `@Order`.

**Comment by sormuras** [comment]
> Any `@RegisterExtension` field not annotated with `@Order` will appear at the end of the sorted list.

Meaning, all not annotated one are executed last in the "before" phase and also last in the "after" phase?

**Comment by ihorppp** [comment]
In the "after" phase all **not** annotated extensions are executed **before** the annotated ones. Setting extension `@Order(1)`  in the "after" phase makes extension execute **last** instead of being **first**. So there is no way to make an "after" phase extension be executed first, without annotating all others "after" extension with `@Order`.

**Comment by sbrannen** [comment]
Brainstorming # 2:

- Use `Integer.MAX_VALUE - 1` as the default order. Then `Integer.MAX_VALUE` could be declared by users to signal the very last order, which would be the first order when reversed.
- Otherwise, I think using `@Priority` would be a viable alternative.

**Comment by ihorppp** [comment]
Thank you. The first option works, event though it's not very convenient to annotate all extensions with `@Order`.
However, to my shame, I haven't figured out how to use `@Priority` with `@Order`. Would you mind giving the example?

**Comment by sbrannen** [comment]
> Thank you. The first option works, event though it's not very convenient to annotate all extensions with `@Order`.

My point was that, if we made that change, users would no longer have to declare `@Order` on all extension fields.

> However, to my shame, I haven't figured out how to use `@Priority` with `@Order`. Would you mind giving the example?

We do not yet support `@Priority`. The "brainstorming" is about things that we could decide to do.

**Comment by marcphilipp** [comment]
New brainstorming idea: Change the default to `Integer.MAX_VALUE / 2` and introduce a `DEFAULT` constant so that the above use case can be written as `@Order(DEFAULT + 1)`.

**Comment by marcphilipp** [comment]
**Team Decision:** Let's go with the latest proposal above.

**Comment by sbrannen** [comment]
_in progress_
