### ISSUE TITLE
RegisterExtension + Nested tests cause ParameterResolutionException

### ISSUE THREAD

**Issue by dmitry-timofeev** [junit-team/junit5#1925]
## Overview

If an extension, implementing ParameterResolver, is registered with `RegisterExtension` in a class with `Nested` test classes, parallel execution of tests from this class results in `ParameterResolutionException`s.

## Steps to reproduce

The minimal example with instructions to reproduce is in a separate repo: https://github.com/dmitry-timofeev/junit-paramresolver-bug 

Quick links to:
 - [The extension](https://github.com/dmitry-timofeev/junit-paramresolver-bug/blob/master/src/main/java/dt/TestExtension.java)
 - [The test](https://github.com/dmitry-timofeev/junit-paramresolver-bug/blob/master/src/test/java/dt/TestExtensionTest.java)

### Actual behaviour

```

[ERROR] Tests run: 13, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 0.135 s <<< FAILURE! - in dt.TestExtensionTest
[ERROR] t1{String}[2]  Time elapsed: 0.018 s  <<< ERROR!
java.util.ConcurrentModificationException

[ERROR] t2{String}  Time elapsed: 0.034 s  <<< ERROR!
org.junit.jupiter.api.extension.ParameterResolutionException: 
  Discovered multiple competing ParameterResolvers for parameter [java.lang.String arg0] 
  in method [void dt.TestExtensionTest.t2(java.lang.String)]: 
  dt.TestExtension@430095d6, 
  dt.TestExtension@5f2eaa85
[…]
```

### Expected

No exceptions, whether the `@Nested` classes use the extension (= get parameters injected) or not (as in the example).

## Context

 - Used versions: 5.5.0-RC1
 - Build Tool/IDE: any (reproducible when run via Maven and IntelliJ)
 - Originally discovered in https://github.com/exonum/exonum-java-binding/pull/954 with [this test failing](https://github.com/exonum/exonum-java-binding/blob/b9b619b0a5d6ef385085dda867cd1d926498c19c/exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java)

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M1 for _team discussion_

**Comment by sbrannen** [comment]
What happens if you annotate the top-level test class with `@TestInstance(PER_CLASS)`?

**Comment by dmitry-timofeev** [comment]
It will suppress the parallel execution, and all tests will be run in the same thread and pass. If I also add `@Execution(ExecutionMode.CONCURRENT)`, they also pass.

**Comment by dmitry-timofeev** [comment]
The extension instance in both cases will be, predictably, the same: 

```
[INFO] Running dt.TestExtensionTest
repetition 1 of 10 in tid = 20, extension = dt.TestExtension@267728db
t2(String) in tid = 17, extension = dt.TestExtension@267728db
repetition 3 of 10 in tid = 22, extension = dt.TestExtension@267728db
repetition 5 of 10 in tid = 23, extension = dt.TestExtension@267728db
repetition 4 of 10 in tid = 21, extension = dt.TestExtension@267728db
nestedT1() in tid = 15, extension = dt.TestExtension@267728db
t3(String) in tid = 19, extension = dt.TestExtension@267728db
repetition 2 of 10 in tid = 18, extension = dt.TestExtension@267728db
repetition 6 of 10 in tid = 18, extension = dt.TestExtension@267728db
repetition 7 of 10 in tid = 22, extension = dt.TestExtension@267728db
repetition 9 of 10 in tid = 20, extension = dt.TestExtension@267728db
repetition 8 of 10 in tid = 17, extension = dt.TestExtension@267728db
repetition 10 of 10 in tid = 15, extension = dt.TestExtension@267728db
```

**Comment by marcphilipp** [comment]
@dmitry-timofeev Thanks for reporting this bug! Looks like this bug was around since we introduced `@RegisterExtension`.

**Comment by dmitry-timofeev** [comment]
@marcphilipp Thank you very much for the fix!
