### ISSUE TITLE
Code coverage percentage dropped drastically with junit-platform 1.4.0

### ISSUE THREAD

**Issue by steinarb** [junit-team/junit5#1927]
When I switched to junit-runner 1.4.0 code coverage dropped from around 92% to 6%
 https://github.com/steinarb/authservice/#status-of-the-project

The drop in coverage happened on both coveralls and sonar.

I've used git bisect and found that the change happens with this commit (switching from version 1.1.0 to 1.4.0 of junit-runner):
https://github.com/steinarb/authservice/commit/664ac362e2919382407194c4b2f398debdcab846

I'm currently using 1.4.2 of junit-runner so upgrading didn't help.

## Steps to reproduce

1. Download and install sonar locally https://docs.sonarqube.org/latest/setup/get-started-2-minutes/
2. Clone the repo
```
git clone https://github.com/steinarb/authservice.git
```
3. Build the project with sonar analysis
```
cd authservice
mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent -B install sonar:sonar -Dsonar.host.url=http://localhost:9000
```
4. Open http://localhost:9000/dashboard?id=no.priv.bang.authservice%3Aauthservice and observe that the coverage is 6.3% where it should have been 92%

## Context

 - Used versions (Jupiter/Vintage/Platform):
junit 5.4.2
junit-platform 1.4.2
openjdk-8 1.8.0_212 
- Build Tool/IDE:
maven 3.6.0 on debian 9.9 "stretch" (current stable) on amd64

## Deliverables

- [ ] ...

**Comment by jbduncan** [comment]
Hi @steinarb, welcome to JUnit 5. :)

I can't speak for the JUnit 5 team, but it's not clear to me what "junit-runner" is, and I can't seem to find it in your project using GitHub's search function. Would you kindly clarify on this?

**Comment by sormuras** [comment]
> junit 5.4.2
> junit-platform 1.4.2

The latter should read: `1.5.2`

**Comment by steinarb** [comment]
@jbduncan Sorry! Mental short circuit on my side, when reading the maven dependencies.

I meant junit-platform, i.e. junit-platform-launcher and junit-platform-runner (that's probably where the "runner" bit came from):
 https://github.com/steinarb/authservice/blob/master/pom.xml#L85

**Comment by sormuras** [comment]
https://github.com/steinarb/authservice/blob/master/pom.xml#L91-L96

Looks suspicious. Surefire (2.22.2 or try 3.0.0-M3) works without `junit-platform-runner`. It's purpose is getting "JUnit 5" started where it isn't supported natively, yet.

**Comment by steinarb** [comment]
> https://github.com/steinarb/authservice/blob/master/pom.xml#L91-L96
> 
> Looks suspicious. Surefire (2.22.2 or try 3.0.0-M3) works without `junit-platform-runner`. It's purpose is getting "JUnit 5" started where it isn't supported natively, yet.

I've removed that dependency, 
 https://github.com/steinarb/authservice/commit/001ce0982b6cb8471784f2de5c4f5831946f544f
but coverage is still low, unfortunately
 https://github.com/steinarb/authservice#status-of-the-project
both on sonar (6.3%)
 https://sonarcloud.io/dashboard?id=no.priv.bang.authservice%3Aauthservice
and on coveralls (5%)
 https://coveralls.io/github/steinarb/authservice

**Comment by marcphilipp** [comment]
You're using Surefire 2.20:
https://scans.gradle.com/s/ba73pce34mrz6/plugins?expanded=WzE4OF0#sg7w5bi4g3tjg

You need at least 2.22.

This PR should fix the issue: https://github.com/steinarb/authservice/pull/3
