### ISSUE TITLE
Implicit conversion of complete set of java.time types

### ISSUE THREAD

**Issue by jodastephen** [junit-team/junit5#1929]
[Implicit conversion](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion-implicit) is supported for most `java.time.*` types. However, there are some missing ones:

* `Period`
* `Duration`
* `MonthDay`
* `ZoneId`
* `ZoneOffset`

Please can the set of implicit conversion types be extended to support these additional types.

**Comment by sbrannen** [comment]
Yes, I think that sounds feasible.

Would you like to submit a PR?

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 GA due to PR #1931.
