### ISSUE TITLE
Extend fallback argument conversion

### ISSUE THREAD

**Issue by jodastephen** [junit-team/junit5#1930]
The [fallback approach to argument conversion](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion-implicit-fallback) is a good one, however I'd like to see it extended in two ways:

Firstly, it only considers methods that accept `String`, whereas there are cases where the factory method accepts `CharSequence`. Notably, this includes `java.time.*` and the related ThreeTen projects.

Secondly, the fallback approach can't complete if it finds multiple matching factory methods. This is an issue that [Joda-Convert](https://www.joda.org/joda-convert/) tackles with annotations:

```java
    import org.joda.convert.FromString;
    public class Point {
      @FromString
      public static Point of(String str) {...}
      public static Point ofInverted(String str) {...}
    }
```

(the one annotated with `@FromString` is the one to use for parsing formalized strings in the way JUnit requires).

What I am proposing is that if the fallback mechanism reaches a point where it finds multiple matching factory methods/constructors, it then searches for an annotation with the name `FromString` (not the type `org.joda.convert.FromString` to avoid the dependency) and chooses that one. This would occur at the end of the current lookup process, thus be backwards compatible.

Supporting this approach would instantly make Joda-Time, Joda-Money and ThreeTen-Extra types compatible with JUnit 5, as they all use Joda-Convert.

For completeness, I note that the `ArgumentConverter` interface already allows Joda-Convert to be integrated if desired. Where the approach above enhances this is that it provides a way to integrate the concept of Joda-Convert directly into JUnit 5 *without the need to add the dependency*.

**Comment by sbrannen** [comment]
Supporting `CharSequence` sounds feasible on its own.

Would you like to submit a PR for that?

**Comment by sbrannen** [comment]
Regarding support for any annotation named `@FromString`, I think that should be discussed amongst the team.

**Comment by sormuras** [comment]
What `@StringConsumingDeserializer`? :wink: https://cr.openjdk.java.net/~briangoetz/amber/serialization.html

**Comment by jodastephen** [comment]
The `@Deserializer` concept is different though - it converts the *constituent parts* of the object into the whole object. `@FromString` takes the whole object as a *formalized string* and converts that to an object. As per [VALJOs](https://blog.joda.org/2014/03/valjos-value-java-objects.html), this is suitable for those types where each state of the class can be represented as a unique string, and methods are provided to convert object -> string and string -> object. JUnit 5 only needs the string -> object part, so it just needs `@FromString`.

**Comment by sormuras** [comment]
Aye. Understood.

The initial name used in my comment was `@StringConsumingDeserializer`. Shouldn't have changed it.

**Comment by marcphilipp** [comment]
**Team Decision:** Put on hold until we've gotten more feedback about the importance of this use case.
