### ISSUE TITLE
Increase log level for when Random prints out default seed value 

### ISSUE THREAD

**Issue by wkorando** [junit-team/junit5#1937]
As a part of #1805 when no seed value is configured a default one is generated and printed to the console. However that message is currently set to config level which isn't printed by default. It seems this could frequently lead to issues where a generated seed causes a test to fail, but the seed isn't printed to console, because Java util log wasn't configured to print out config messages.

Should this logging message be changed to print a higher level, possibly INFO, which is printed out by default?

## Deliverables

- [ ] Update `MethodOrderer` to print default seed to `INFO`

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 GA for _team discussion_

**Comment by sbrannen** [comment]
**Team Decision**: print the default seed using the `INFO` log level.

**Comment by sbrannen** [comment]
_in progress_

**Comment by slovdahl** [comment]
For anyone else finding this issue and wondering why it isn't logged on `INFO`: the change was reverted in https://github.com/junit-team/junit5/commit/c8f45dedee4bfa8499807e4b08823cd6915a7b84 and https://github.com/junit-team/junit5/commit/d25b650ec2c3e781762a2573243a90f137c38201

**Comment by perlun** [comment]
> the change was reverted in [c8f45de](https://github.com/junit-team/junit5/commit/c8f45dedee4bfa8499807e4b08823cd6915a7b84) and [d25b650](https://github.com/junit-team/junit5/commit/d25b650ec2c3e781762a2573243a90f137c38201)

Yep. See #2690 for the PR which changed this back to `config` level.
