### ISSUE TITLE
Regression in 5.5.0-RC2? ParameterResolutionException

### ISSUE THREAD

**Issue by AlvaHenrik** [junit-team/junit5#1938]
I'm using JUnit 5 together with jmockit-1.46.

When I use JUnit 5.5.0-M1 then my unit tests work properly, but when I use 5.5.0-RC2 then I get a `ParameterResolutionException` for parameters injected into tests with `@Mocked`. 

Please guide me how to provide more useful information if needed.

**Comment by sormuras** [comment]
@AlvaHenrik thanks for rising this issue.

Any stacktrace, any minimal project to reproduce that issue would help us to find the cause faster.

**Comment by AlvaHenrik** [comment]
```
public class Foo {

    public void a() {
        System.out.println(b());
        System.out.println("A");
    }

    public String b() {
        return "B";
    }

    public Foo() {}
}
..........................
import mockit.Expectations;
import mockit.Mocked;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class FooTest {

    @Test
    public void testMock(@Mocked final Foo mockedFoo) {
        new Expectations(Foo.class) {{
            new Foo(); result = mockedFoo;
            mockedFoo.b(); result = new Exception("test");
        }};
        Foo test = new Foo();
        assertThrows(Exception.class, () -> test.a());
    }
}
```
And this is my pom.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>junit-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <junit.jupiter.version>5.5.0-RC2</junit.jupiter.version>
        <jmockit.version>1.46</jmockit.version>
        <jacoco.version>0.8.4</jacoco.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jmockit</groupId>
            <artifactId>jmockit</artifactId>
            <version>${jmockit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>org.jacoco.agent</artifactId>
            <classifier>runtime</classifier>
            <version>${jacoco.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M3</version>
                <configuration>
                    <argLine>
                        -javaagent:${settings.localRepository}/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar
                    </argLine>
                    <systemPropertyVariables>
                        <jacoco-agent.destfile>target/jacoco.exec</jacoco-agent.destfile>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>instrument</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>instrument</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>restore</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>restore-instrumented-classes</goal>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>`
I hope this helps. Just switching from M1 to RC2 will show the problem.

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 GA for _team discussion_ and investigation

**Comment by sbrannen** [comment]
@AlvaHenrik, thanks for providing the example.

We'll look into it.

**Comment by sbrannen** [comment]
There were in fact changes to the internals of the Jupiter `TestEngine` from 5.5 RC1 to RC2, but the JUnit 5 team is at liberty to make such changes.

The regression therefore lies with JMockit, and I have raised https://github.com/jmockit/jmockit1/issues/619 so that the JMockit team can address it.
