### ISSUE TITLE
Run `jdeps --check` on all modules

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1939]
## Description

Running `jdeps [...] --check org.junit.platform.commons` yields:

```
org.junit.platform.commons (file:///Z:/junit10570588147507757156/lib/junit-platform-commons-1.5.0-SNAPSHOT.jar)
  [Module descriptor]
    requires mandated java.base;
    requires java.compiler;
    requires java.logging;
    requires transitive org.apiguardian.api (@1.1.0);
  [Suggested module descriptor for org.junit.platform.commons]
    requires mandated java.base;
    requires java.compiler;
    requires java.logging;
    requires transitive org.apiguardian.api;
  [Transitive reduced graph for org.junit.platform.commons]
    requires mandated java.base;
    requires java.compiler;
    requires java.logging;
    requires transitive org.apiguardian.api;
  [Unused qualified exports in org.junit.platform.commons]
    exports org.junit.platform.commons.logging to org.junit.jupiter.migrationsupport,org.junit.jupiter.params,org.junit.platform.console,org.junit.platform.reporting,org.junit.platform.runner,org.junit.platform.suite.api
    exports org.junit.platform.commons.util to org.junit.platform.suite.api
```

### Analysis

- Directives actually compiled into the the module descriptor (`[Module descriptor]`) do match those listed below `[Suggested module descriptor for <module>]`.
- Directives listed below `[Transitive reduced graph for <module>]` ignored here, as we should favor the explicite declaration of all required modules.
- Directives listed below `[Unused qualified exports in <module>]` may be pruned from the module descriptor. Or they may stay for potential future-use.

## Deliverables

- [ ] Add integration test checking all modules
- [ ] Consult output and apply suggested directives when applicable

**Comment by djchapm** [comment]
+1, maven enforcer build plugin errors multiple versions of apiguardian-api are referenced - 1.1.0 and 1.0.0.
Dependency convergence error for org.apiguardian:apiguardian-api:1.1.0 paths to dependency are:
  +-org.junit.jupiter:junit-jupiter-engine:5.5.2
    +-org.apiguardian:apiguardian-api:1.1.0
and
  +-org.junit.jupiter:junit-jupiter-engine:5.5.2
    +-org.junit.platform:junit-platform-engine:1.3.2
      +-org.apiguardian:apiguardian-api:1.0.0
and
  +-org.junit.jupiter:junit-jupiter-engine:5.5.2
    +-org.junit.platform:junit-platform-engine:1.3.2
      +-org.junit.platform:junit-platform-commons:1.3.2
        +-org.apiguardian:apiguardian-api:1.0.0
and
  +-org.junit.jupiter:junit-jupiter-engine:5.5.2
    +-org.junit.jupiter:junit-jupiter-api:5.3.2
      +-org.apiguardian:apiguardian-api:1.0.0

**Comment by marcphilipp** [comment]
@djchapm Where's the 1.0.0 dependency coming from? Our artifacts all reference 1.1.0.

**Comment by djchapm** [comment]
That print out above was mvn enforcer... telling me that junit-jupiter-qpi 5.3.2 had a dependency on apiguardian 1.0.0... however now - I'm not able to reproduce!  I've been changing a lot, but this was part of an upgrade stumble I ran into and I think it resolved on changing surefire plugin maybe?

**Comment by sormuras** [comment]
> [...]  I think it resolved on changing surefire plugin maybe?

99% sure. ;-)

**Comment by sormuras** [comment]
Further investigation and automation of this is blocked by https://bugs.openjdk.java.net/browse/JDK-8225773 -- here's a MVE project: https://github.com/sormuras/JDK-8225773
