### ISSUE TITLE
Default MethodOrderer.Random seed is printed even when a custom seed is provided

### ISSUE THREAD

**Issue by wkorando** [junit-team/junit5#1942]
Version: JUnit 5.5.0

When MethodOrderer.Random is used a message is printed displaying the default seed that was generated. This is useful when attempting to recreate a build if an issue was discovered, however if a seed has been provided this message should not be printed as it could be confusing as to which seed was used when executing tests in random order.

## Deliverables

- [ ] Default seed should only be printed when no seed is supplied

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M1 for _team discussion_

**Comment by sbrannen** [comment]
**Team Brainstorming Results**: the team discussed this issue and decided that the proposal is reasonable; however, the team did not come up with an immediate solution.

It turns out that this proposal is much more difficult to implement than one might initially assume. For example, a `MethodOrderer` does not have access to a shared data store such as the `ExtensionContext.Store`, which makes it a challenge to track whether something has already been logged. The team decided that it would likely not be a good idea to store such state in a `static` field since that would not be reset across test plan executions within the same JVM.

**Comment by sbrannen** [comment]
If it were possible to save a new configuration parameter at runtime, we could refactor the implementation similar to the following.

```java
private static final String TRACKED_SEED_PROPERTY_NAME = Random.class.getName() + ".SEED";

private Long getSeed(MethodOrdererContext context) {
	String trackedSeed = System.getProperty(TRACKED_SEED_PROPERTY_NAME);
	if (StringUtils.isNotBlank(trackedSeed)) {
		try {
			return Long.valueOf(trackedSeed);
		}
		catch (NumberFormatException ex) {
			logger.warn(ex, () -> String.format("Failed to convert tracked seed [%s] to a long.", trackedSeed));
		}
	}

	Long seed = context.getConfigurationParameter(RANDOM_SEED_PROPERTY_NAME).map(configurationParameter -> {
		Long customSeed = null;
		try {
			customSeed = Long.valueOf(configurationParameter);
			logger.config(
				() -> String.format("Using custom seed for configuration parameter [%s] with value [%s].",
					RANDOM_SEED_PROPERTY_NAME, configurationParameter));
		}
		catch (NumberFormatException ex) {
			logger.warn(ex,
				() -> String.format(
					"Failed to convert configuration parameter [%s] with value [%s] to a long. "
							+ "Using default seed [%s] as fallback.",
					RANDOM_SEED_PROPERTY_NAME, configurationParameter, DEFAULT_SEED));
		}
		return customSeed;
	}).orElseGet(() -> {
		logger.info(() -> "MethodOrderer.Random default seed: " + DEFAULT_SEED);
		return DEFAULT_SEED;
	});

	System.setProperty(TRACKED_SEED_PROPERTY_NAME, String.valueOf(seed));
	return seed;
}
```

The above code stores the "tracked seed" as a JVM system property merely for demonstration purposes. If we could save a configuration parameter for the current test plan execution, we could replace the above use of `System.getProperty` and `System.setProperty` with the revised configuration parameter support.

**Comment by marcphilipp** [comment]
Alternatively, we could use a special logger that only logs the same message once per call of `discoverTests()`.

**Comment by marcphilipp** [comment]
**Team Decision:** Implement a spike with a "log once" feature in our internal logging façade.
