### ISSUE TITLE
@ParameterizedTest Thread count

### ISSUE THREAD

**Issue by jflefebvre06** [junit-team/junit5#1946]
could you please add a way to configure the number  of threads running @ParameterizedTest like testng dataproviderthreadcount

**Comment by marcphilipp** [comment]
@jflefebvre06 What's your use case for such a setting?

**Comment by jflefebvre06** [comment]
There are mutiple uses case , exemple :
 - low value for test consuming a lot of memory
 - hight value for slow tests

**Comment by jflefebvre06** [comment]
Hello 
Any update about this issue ?

**Comment by marcphilipp** [comment]
@jflefebvre06 This would be very involved to implement so we're putting it into the general backlog for now and will wait for additional interest from the community.

**Comment by MarQs1990** [comment]
This would be a great thing. In a business project we switched from JUnit to TestNG, because TestNG has the ability to set a custom limit of threads.
We used it for parallel mobile testing in an real device mobile cloud, and there we need to set the parallel threads to a small number
