### ISSUE TITLE
Make MAX_STACKTRACE_LINES in MutableTestExecutionSummary configurable

### ISSUE THREAD

**Issue by arcuri82** [junit-team/junit5#1947]
Hi,

running tests programmatically with a 

```java
Launcher launcher = LauncherFactory.create();
```

where I register a `SummaryGeneratingListener`. Unfortunately, the failure messages are of limited use, as `MutableTestExecutionSummary.MAX_STACKTRACE_LINES` is a constant set to the low value of 10. It would be good if such value could be configurable in `SummaryGeneratingListener`, or at least provide a higher default (e.g., 30 or 50).

This issue seems somehow related to #1693.

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M1 for _team discussion_

**Comment by marcphilipp** [comment]
**Team Decision:** Add an overload for `TestExecutionSummary .printFailuresTo(PrintWriter writer, int maxStackTraceLines)`.

@arcuri82 Would you be interested in submitting a PR?

**Comment by arcuri82** [comment]
yes, a PR should be relative easy to do

**Comment by sbrannen** [comment]
> yes, a PR should be relative easy to do

Great! Looking forward to it. 👍

**Comment by sbrannen** [comment]
Resolved in c132aed1903176be4c393c23a6f2ecc92ef7010b and refined in 11c95c60fd1ceb9bed6a6d8588113f752b1cc77a.
