### ISSUE TITLE
Provide JARs with OSGi metadata

### ISSUE THREAD

**Issue by rherrmann** [junit-team/junit5#195]
The JARs that are produced during a build should contain OSGi metadata. This would allow to consume them as OSGi bundles right away.

**Comment by hwellmann** [comment]
See also #216.

**Comment by marcphilipp** [comment]
@rherrmann Is this issue still relevant?

**Comment by rherrmann** [comment]
Yes, I believe this is still relevant. As far as I understand, the packaged JARs don't provide OSGi metadata (i.e. don't contain a `MANIFEST.MF` with the relevant information). Thus they cannot be consumed by OSGi build systems or the OSGi runtime without re-packaging them with included metadata.

**Comment by marcphilipp** [comment]
`Bundle-SymbolicName` and `Bundle-Version` would be easy enough to add. But maintaining `Export-Package` and `Import-Package` in addition to the regular dependencies would be a burden. Is there a tool/Gradle plugin that can generate those automatically?

**Comment by sbrannen** [comment]
AFAIK, people typically use `bnd` for that, and there is a [bnd Gradle Plugin](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md).

**Comment by jbduncan** [comment]
[Goomph](https://github.com/diffplug/goomph), another Gradle plugin, apparently has the capability to generate OSGi metadata using bnd as well.
