### ISSUE TITLE
Improve method names for event filtering in the EngineTestKit API

### ISSUE THREAD

**Issue by joel-costigliola** [junit-team/junit5#1950]
## Overview

The `EngineTestKit` API could be more readable by renaming `EngineExecutionResults` methods to show they are dealing with events. This was discussed in this [comment](https://github.com/joel-costigliola/assertj-core/issues/1418#issuecomment-509002192). 

The methods rename suggested are:

- EngineExecutionResults.all() to `allEvents`
- EngineExecutionResults.tests() to `testEvents`
- EngineExecutionResults.container() to `containerEvents`

## Deliverables

- [ ] Rename methods but keep and deprecate the older version for backward compatibility
- [ ] Update documentation for all renamed methods

**Comment by sbrannen** [comment]
Thanks for raising the issue.

We'll look into this for 5.6.

**Comment by sbrannen** [comment]
This has been addressed in 8ce46d91b63857c097b01c4ee83f047046aef93a.
