### ISSUE TITLE
Add support for String delimiters in @CsvSource and @CsvFileSource

### ISSUE THREAD

**Issue by nrundle** [junit-team/junit5#1958]
Configuring the delimiter in `@CsvSource` when using Groovy is extremely limited due to the lack of support of character literals.

The only way to configure the delimiter in the annotation that I could find is to cast it to char which requires the class the use of `@CompileStatic`.

The [univocity parser](https://github.com/uniVocity/univocity-parsers/blob/v2.8.2/src/main/java/com/univocity/parsers/csv/CsvFormat.java) that is used can take either a `char` or `String` delimiter.

In order to offer better support for writing tests in Groovy, please update this annotation so that a string delimiter may be used.

## Deliverables

- [ ] Add support for String delimiters in `@CsvSource` and `@CsvFileSource`

**Comment by marcphilipp** [comment]
You mean like this?

```groovy
@CompileStatic
class GroovyParamsTests {

    private static final char COMMA = (char) ','

    @CsvSource(value = ["1, 2", "3, 4"], delimiter = COMMA)
    @ParameterizedTest
    void test(int i, int j) {

    }
}
```

**Comment by marcphilipp** [comment]
Changing it from `char` to `String` would be a breaking change. On the other hand,  `@CsvSource` is still experimental although widely used.

Tentatively slated for 5.6 M1 for _team discussion_.

**Comment by nrundle** [comment]
Yes, I experimented with using `@CompileStatic`, but unfortunately then I lose access to other Groovy features that I was using.

So far, I like being able to use the @CsvSource and see the inputs and expected outputs right above the test.

**Comment by sormuras** [comment]
Perhaps something Groovy 3.x will support w/o resorting to `String`?

Because only to support `","` -- a single character sequence -- I'd hesitate to change the API of `@CsvSource`.

**Comment by nrundle** [comment]
Perhaps rather than changing the API, a new one could be created.  Since the univocity parser allows string delimiters with more than one character, I thought it might be a nice enhancement which not only supports groovy's lack of a character literal, but also allows for a wider set of delimiters to be used.

**Comment by sbrannen** [comment]
> Perhaps rather than changing the API, a new one could be created. Since the univocity parser allows string delimiters with more than one character, I thought it might be a nice enhancement which not only supports groovy's lack of a character literal, but also allows for a wider set of delimiters to be used.

I suppose we could introduce something like `delimiterString`. It's not the most elegant and would require a more complicated lookup algorithm (that rejects configuration of both attributes), but it's possible.

**Comment by marcphilipp** [comment]
**Team Decision:** Let's add `delimiterString`, check that the user does not declare both delimiter attributes, and set the default values in the annotation to `'\0'` and `""`, respectively.

**Comment by sormuras** [comment]
...and default to ',' (comma character) when no delimiter is set?

**Comment by sbrannen** [comment]
> ...and default to ',' (comma character) when no delimiter is set?

Yes, exactly. That was discussed during the call but didn't make it into the "Team Decision".

**Comment by marcphilipp** [comment]
I've updated my comment above.

**Comment by juliette-derancourt** [comment]
I'd like to take a look at that if it's ok with you :)

**Comment by sbrannen** [comment]
> I'd like to take a look at that if it's ok with you :)

Well, it was assigned to me, but I'm totally happy that you've submitted a PR to address this. 😉 

Cheers,

Sam

**Comment by juliette-derancourt** [comment]
> Well, it was assigned to me, but I'm totally happy that you've submitted a PR to address this. 😉

Yes I saw that afterwards, sorry! 😅
