### ISSUE TITLE
@Timeout should support debugging

### ISSUE THREAD

**Issue by jportner-hw** [junit-team/junit5#1959]
We tried to use the new `@Timeout` annotation introduced in https://github.com/junit-team/junit5/pull/1885 to enforce a global timeout. I put it on the base class that all our JUnit Jupiter integration tests extend from. 

It works, but unfortunately without any kind of "DisableOnDebug" feature we cannot realistically use it. When debugging a test and stepping through with a debugger it will fail early with the timeout.

If adding a global "DisableOnDebug" is not being considered, I think it would be a small fix to `org.junit.jupiter.engine.extension.TimeoutExtension` itself.

Just need to add something like this (copied from JUnit 4's `DisableOnDebug`) to `TimeoutExtension` and not apply the timeout if `isDebugging()` is `true`.

```java
private static boolean isDebugging() {
    List<String> inputArguments = ManagementFactory.getRuntimeMXBean().getInputArguments();
    Iterator<String> iterator = inputArguments.iterator();
    String argument;
    do {
        if (!iterator.hasNext()) {
            return false;
        }

        argument = iterator.next();
        if ("-Xdebug".equals(argument)) {
            return true;
        }
    } while (!argument.startsWith("-agentlib:jdwp"));

    return true;
}
```

**Comment by sormuras** [comment]
We could implement something similar to the system property we support for execution conditions described here: https://junit.org/junit5/docs/current/user-guide/#extensions-conditions-deactivation

**Comment by marcphilipp** [comment]
@jportner-hw Would that work for you, e.g. by setting a system property?

**Comment by jportner-hw** [comment]
Hi @marcphilipp . 
Would that system property name be configurable by us? If so we could use `intellij.debug.agent` which is set to true during debugging in IntelliJ to disable the Timeout.

If the system property name was defined by JUnit we could edit our "Run/Debug configuration" in IntelliJ to include it. I think the user configurable system property would be preferred so it could just be defined in our usage of Timeout and not force developers to make the change in IntelliJ.

**Comment by sbrannen** [comment]
> Would that system property name be configurable by us?

How would that make things easier?

Wouldn't we then need a system property (or JUnit Platform "configuration parameter") to set the name of the other system property, thereby forcing you to set two things?

**Comment by marcphilipp** [comment]
I'm wondering whether we should simply deactivate timeouts if we can autodetect that a debugger is connected. Is there really a use case for debugging with active timeouts? 🤔

**Comment by sbrannen** [comment]
> I'm wondering whether we should simply deactivate timeouts if we can autodetect that a debugger is connected. 

I agree. As the OP pointed out, JUnit 4's `org.junit.rules.DisableOnDebug.isDebugging(List<String>)` seems like a pretty good way to achieve that.

> Is there really a use case for debugging with active timeouts? 🤔

I doubt it.

I wonder if we should consider doing anything for `assertTimeout*()` as well -- perhaps not, but worth considering nonetheless.

**Comment by jportner-hw** [comment]
Yup. I'm happy if you implement the easy solution of just disabling `@Timeout` when a debugger is connected. "-Xdebug" jvm argument.
I can't think of a reason why someone would want to timeout while debugging.

**Comment by jportner-hw** [comment]
> > Would that system property name be configurable by us?
> 
> How would that make things easier?
> 
> Wouldn't we then need a system property (or JUnit Platform "configuration parameter") to set the name of the other system property, thereby forcing you to set two things?

I was thinking something like `@Timeout(disabledWithSystemProperty="intellij.debug.agent")`
But like other people have replied maybe it's better to just take the simple approach of disabling timeout by default if debugging.

**Comment by marcphilipp** [comment]
**Team Decision:** Introduce a new `junit.jupiter.execution.timeout.mode` configuration parameter to configure when timeouts are applied. There are three modes: `enabled`, `disabled`, `disabled_on_debug`. By default it would be `enabled`.

@jportner-hw This way, you could add that to `junit-platform.properties` and comment it out or uncomment it as needed. Would that work for you?

**Comment by jportner-hw** [comment]
thanks @marcphilipp . sounds good.

**Comment by georgy** [comment]
CAn grab this one? do I need to assign it to myself or do something else to "own" it?

**Comment by sbrannen** [comment]
> Can I grab this one? do I need to assign it to myself or do something else to "own" it?

Yes, sure. Go for it!

I'll label this as "in progress".

However, if you don't find time to work on it in the coming weeks, please post back here so that somebody else can _grab_ it.

Thanks

**Comment by marcphilipp** [comment]
@georgy Did you start work on this one or shall we try to find someone else?

**Comment by georgy** [comment]
@marcphilipp yep, give me till Wednesday to wrap it up please

**Comment by marcphilipp** [comment]
@georgy Any updates? 🙂

**Comment by georgy** [comment]
@marcphilipp Sorry for the delayed reply, unfortunately I will not be able to finish the task this/next week due to change in schedule. Please feel free to pass it to someone else. Apologies for the inconvenience.

**Comment by marcphilipp** [comment]
@georgy No worries, thanks for letting us know! Have you already started work and would like to share your work-in-progress?

**Comment by stehrn** [comment]
I'd like to give this one a go if ok? @georgy pls let me know if any work in progress, fine if not; will aim for PR early next week

**Comment by chrischild** [comment]
Hello - I've actually think I have this completed. Sorry I didn't PR this as I have not contributed to any Open Source projects before and wanted to poke around on my own without being assigned to the issue just in case I couldn't figure it out. I'm just going through the DoD.

**Comment by stehrn** [comment]
Nice, I’ll leave it to you then

**Comment by chrischild** [comment]
I think I've got everything in order. I just need permission to push my branch.

**Comment by marcphilipp** [comment]
@chrischild Please fork the repo, push the branch to your fork, and open a PR from there.

**Comment by chrischild** [comment]
Thanks @marcphilipp! I literally just read that somewhere online and figured that was what I was supposed to do.

**Comment by sormuras** [comment]
[ ] Change is documented in the User Guide and Release Notes
