### ISSUE TITLE
Support focusing in addition to skipping

### ISSUE THREAD

**Issue by arturdryomov** [junit-team/junit5#1960]
Using traditional JUnit structure there are no problems executing a single isolated test.

```kotlin
class Suite {
    @Test a() = Unit
    @Test b() = Unit
 }
```
In the snippet above re-running `b` in isolation usually is not an issue in such IDEs as IJ. There is a green arrow nearby which executes a single method. This is great.

However, using non-traditional DSLs, similar to RSpec does not provide such a luxury.

```kotlin
@Testable
class Suite : Spec({
    context("A") {
        it("works") {
        }
    }
    context("B") {
        it("works") {
        }
    }
})
```
Since both `context` and `it` are not method declarations but invocations there are no IDE hints to execute a single `B`. 

In RSpec this is achieved using skipping (`xit`, `xcontext`) and focusing (`fit`, `fcontext`).

Lucky for us there is the `org.junit.platform.engine.support.hierarchical.Node.SkipResult` API which can be used to provide skipping. Unfortunately there is nothing for focusing. Of course it is possible to implement focusing manually going over the `TestDescriptor` tree, finding if there are focused nodes, then go over the whole tree again and mark all non-focused nodes as skipped. However, I thought maybe there is a chance to provide a mirror API for `Node.SkipResult` like `Node.FocusResult`. 

WDYT? Is there some other way to achieve focusing using JUnit Platform? Or maybe hint the IDE that it is possible to execute a single node?

**Comment by sbrannen** [comment]
> Is there some other way to achieve focusing using JUnit Platform?

To be perfectly honest, I didn't fully understand what you meant by "focusing".

Is that functionality you need within a custom `TestEngine` implementation? Or is that some kind of feature that build tools and IDEs could use?

> Or maybe hint the IDE that it is possible to execute a single node?

IDEs perform static analysis to determine what can be executed as a "test" or "container" on the JUnit Platform. To simplify the implementation for IDEs, the JUnit team introduced the `@Testable` annotation so that test engines can _flag_ tests and containers.

Traditionally, tests and containers in JVM languages have been methods and classes, respectively, hence the following declaration of `@Testable`.

```java
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Inherited
public @interface Testable {
}
```

Would expanding the `@Target` list help you with your use case?

If not, what other kind of "hint" do you propose?

**Comment by ming13** [comment]
> To be perfectly honest, I didn't fully understand what you meant by "focusing".

Focusing is basically filtering out everything except focused nodes.

* `xit` (skipping) — everything is executed except skipped nodes.
* `fit` (focusing) — nothing is executed except focused nodes.

I imagine a possible API as a part of the Platform `org.junit.platform.engine.support.hierarchical.Node` abstraction, nothing from the tooling side. Something like this in `Node`: 

```java
default FocusResult shouldBeFocused(C context) throws Exception {
    return FocusResult.doNotFocus();
}
```

The focusing can be achieved using existing `SkipResult` API but it requires a bit of friction:

* in `HierarchicalTestEngine.discover` assemble a nodes tree;
* go over all nodes and find if there are focused nodes;
    * focused nodes available — go over all nodes again and mark non-focused nodes as skipped;
    * focused nodes not available — leave the tree as-is.

I hope this clarifies things a bit.

> Would expanding the @Target list help you with your use case?

While this might work it requires the support from IDE which is not a good thing. For example, `FilePosition` was introduced into the `ClassSource` [three years ago](https://github.com/junit-team/junit5/issues/406) but [still is not supported by IJ](https://youtrack.jetbrains.com/issue/IDEA-218420) (at least).

Also I doubt that it will be possible for IDE to provide the support in the first place. Execution a single method invocation from the IDE side will probably lead to `UniqueIdSelector` but those IDs are not available till the discovery phase and IDEs do not do the discovery until the execution is triggered (right?).
