### ISSUE TITLE
Vintage engine to warn/error on mixed JUnit 3/4 tests

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#1964]
If the Vintage engine encounters a class that extends `TestCase` *and* has `@Test` annotations in it, then it will silently ignore all of the JUnit 4 tests. It would be good if it were not so silent about it, as it could lull people into a false sense of security that all their tests are passing, when some are simply not running at all.

I just encountered the case where a test class had no tests found, and Vintage helpfully noted the fact as a test under the relevant class named "warning", with appropriate diagnostics in the error message/stack trace. A similar technique could be used to report the error when `TestCase` and `@Test` are mixed.

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M1 for _team discussion_

**Comment by kriegfrj** [comment]
As an alternative (superior) solution to this problem, possibly Vintage could be changed to support mixed JUnit 3 & 4 tests in a single test class.

**Comment by marcphilipp** [comment]
The Vintage engine is really only a compatibility layer around JUnit 4. JUnit 4 does not detect this problem and I cannot remember it ever coming up as an issue there. It's not that easy to change either. For example, if you have a `@RunWith` annotated class, `TestCase` will be ignored. But, who knows, what the runner does? It could very well ignore `@Test` methods, too. Thus, I think we should close this issue.

@junit-team/junit-lambda WDYT?

**Comment by kriegfrj** [comment]
Yes, understand that this is really a JUnit 4 issue more so than a Vintage engine issue. Neverthless, it would be possible (though admittedly not the cleanest) for the Vintage wrapper to detect and report this issue even if the underlying JUnit 4 implementation does not. Given that development on JUnit 4 has ceased it seems adding this check in the Vintage wrapper is the only live option.

I have encountered a few issues of Bnd developers (including myself) getting caught out by this - that probably has something to do with the fact that the Bnd tester (until the current development snapshot) only supported JUnit 3 & 4, and consequently there were (are) a lot of legacy JUnit 3/4 tests hanging around. If it can't go into the Vintage engine, my second choice would be to add a check for this in our `BundleEngine`.

**Comment by marcphilipp** [comment]
I'd be ok with adding such a warning to _Jupiter_ test classes, i.e. if you mix Jupiter `@Test` annotations with JUnit 4 ones or extend `TestCase`. But then again, I'm not sure how often that actually happens. Would that be helpful for you?

**Comment by kriegfrj** [comment]
Actually, Jupiter doesn't need such a warning, because it can happily coexist side-by-side with either JUnit 4 or JUnit 3 in the same test class. Jupiter runs the Jupiter tests, Vintage runs the JUnit 3 or 4 tests (but not both!) and everyone's happy.

So it's really the mixed 3/4 case that I'm trying to cover.

**Comment by marcphilipp** [comment]
**Team Decision:** We don't intend to add new functionality to the Vintage engine that enhances JUnit 4 or works around its limitations. Therefore, we're closing this issue.

**Comment by marcphilipp** [comment]
@juliette-derancourt Thanks for actually closing the issue. 😅
