### ISSUE TITLE
Test discovery is very slow with scalatest

### ISSUE THREAD

**Issue by sherfert** [junit-team/junit5#1965]
Our tests are written in scalatest and run by adding the annotation `@RunWith(classOf[JUnitRunner])` and using the maven surefire plugin. In one test class we have 14.000 tests. These tests take roughly 4 seconds to execute but 11 minutes to discover.

The issue seems to be connected with `VintageTestDescriptor`. It tries to find the method of a test using `VintageTestDescriptor.findMethod` which in turn enumerates all methods to find the one of the test.

I see two possible solutions:

* Do not call into `ReflectionUtils.findMethods` _for every test_. This means enumerating ~14.000 methods of that class (plus suplerclass methods) 14.000 times. If we could reuse the computed `List<Method>` of a class instead of recomputing it, that would solve the problem.

* Do not enumerate all methods to find one. This would mean changing `List<Method> findMethods(Class<?> clazz, Predicate<Method> predicate, HierarchyTraversalMode traversalMode)` and `List<Method> findAllMethodsInHierarchy(Class<?> clazz, HierarchyTraversalMode traversalMode)` to work all the way with `Stream`s instead of `Lists`s so that we do not need to continue enumerating methods once we have found the method, by leveraging the `Stream.findFirst` method. This would help in our particular case. Most of the time is actually spent in `ReflectionUtils.isMethodShadowedByLocalMethods`, which is only called for superclass methods. All of our tests are defined in the concrete class, so we would never need to enumerate that far.

I will attach a profile of `mvn test` during the test discovery phase for a better analysis.

**Comment by sherfert** [comment]
Profile:  [maven2.zip](https://github.com/junit-team/junit5/files/3425621/maven2.zip)

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M1 for _team discussion_

**Comment by marcphilipp** [comment]
@sherfert Could you please provide a sample project so we can reproduce the issue when working on improving the performance?

**Comment by sherfert** [comment]
You can find a small sample project for reproduction [here](https://github.com/sherfert/JUnitSlowTestDiscovery).

**Comment by marcphilipp** [comment]
@sherfert Thanks! 👍

**Comment by marcphilipp** [comment]
I finally found some time to look into the sample project. Here's a quick flamegraph that shows that roughly 53% of the execution are spent in `VintageTestDescriptor.findMethod`:

<img width="799" alt="Screenshot 2019-09-14 at 20 53 07" src="https://user-images.githubusercontent.com/214207/64912589-d9dcb400-d731-11e9-9231-7a154cfe3ecb.png">

It doesn't help that Surefire calls `discover` twice: once when scanning for test classes and once when executing them.
