### ISSUE TITLE
@SelectPackages not working with Maven CLI

### ISSUE THREAD

**Issue by steppinrazor** [junit-team/junit5#1968]
Didn't get a response on SO so reposting here to see if I have any better luck

https://stackoverflow.com/questions/57136247/selectpackages-not-working-with-maven-cli

**Comment by marcphilipp** [comment]
The [answer on StackOverflow](https://stackoverflow.com/a/57157951/6327046) is correct. There's an open issue to support suites on the Platform: #744.
