### ISSUE TITLE
Smarter @EnumSource implementation

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#1973]
I've just started using `@EnumSource` in a parameterized test. Very handy.

However, after having used it with a few methods, it occurred to me that it could be a little handier and a little DRYer.

Consider:

```java
@ParameterizedTest
@EnumSource(MyEnum.class)
public void myTestMethod(MyEnum param) {
}
```
We have to specify the enum type twice. This seems to be needless repetition and a possible source of errors.

My proposal is in two parts:

1. The "value" parameter of the `@EnumSource` annotation should be inferred by the engine based on the type of the parameter.
2. As a further enhancement, if there is no other configuration needed for the `@EnumSource` annotation, then it would be nice if it were possible to omit it altogether.

### Proposal part 1

Ability to write tests as follows:

```java
@ParameterizedTest
// Equivalent to @EnumSource(MyEnum.class)
@EnumSource 
public void myTestMethod(MyEnum param) {
}
```

```java
@ParameterizedTest
// Equivalent to @EnumSource(value = MyEnum.class, names = {"VAL1", "VAL2"}))
@EnumSource(names = { "VAL1", "VAL2" }) 
public void myTestMethod(MyEnum param) {
}
```

### Propsal part 2

Ability to write tests as follows:

```java
@ParameterizedTest
// Equivalent to @EnumSource(MyEnum.class)
public void myTestMethod(MyEnum param) {
}
```

**Comment by marcphilipp** [comment]
I think the first proposal makes sense. 👍

**Comment by sbrannen** [comment]
> I think the first proposal makes sense. 👍

That could work, but we need to be cautious about additional enum types in the formal parameter list that may be supplied by a `ParameterResolver`.

In other words, if there's only a single enum type in the formal parameter list, it's straightforward, but we might want to throw an exception if there is more than one enum type.

**Comment by marcphilipp** [comment]
I'd only look at the first parameter to match what `@EnumSource` does today.

**Comment by marcphilipp** [comment]
@kriegfrj I've submitted #1993 to address this.
