### ISSUE TITLE
Jupiter engine calls static initializer on each invocation

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#1974]
## Steps to reproduce

```java
public class MyTest {

   static int count = 0;
    {
        System.err.println("Hi there!: " + System.identityHashCode(MyTest.class) + ", count: " + count++);
    }

    @Test
    public void myFirstTest() {}

    @Test
    public void mySecondTest() {}
}
```
Sample output when run using the Jupiter engine

```
Hi there!: 1929600551, count: 0
Hi there!: 1929600551, count: 1
```
Run this test using Jupiter and watch the console. "Hi there!" will appear twice, and both lines will have the same identity hash code and the count is remember between tests, indicating that they are the same class.

Once I understood what was happening, it was easy to work around this by using a static method with a `@BeforeAll` annotation instead of a static initializer. However, this behaviour was very surprising.

## Context

The above was tested using Jupiter 5.4.0.

## Deliverables

I'm not sure if this behaviour is by design. But on the surface of it, I'd have thought that the static initializer should only be invoked once, when the class is loaded (per the Java spec).

**Comment by marcphilipp** [comment]
That's not a static initializer but an instance initializer which is invoked whenever an instance of the test class is created. By default, Jupiter creates a new instance for every test method. Please [refer to the docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle) should you want to change that behavior.

**Comment by kriegfrj** [comment]
C'mon, so sorry for the false alarm. Yes, I was missing the static keyword.

**Comment by marcphilipp** [comment]
No worries!
