### ISSUE TITLE
Incorrect test count displayed with Maven Surefire

### ISSUE THREAD

**Issue by priyankshah217** [junit-team/junit5#1975]
## Steps to reproduce

- Run code from https://github.com/priyankshah217/junit5sample
- It has running strategy concurrent (method and class level)

``` 
junit.jupiter.execution.parallel.mode.default = concurrent
junit.jupiter.execution.parallel.mode.classes.default = concurrent
```

- Run test using `mvn clean test`

**Actual Output**

```
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.026 s - in SampleTest2
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.04 s - in SampleTest
```

https://gist.github.com/priyankshah217/c8860393e82eb18172e6bd2afda5957e#file-junit5executionlog

**Expected Output**
```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.026 s - in SampleTest2
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.04 s - in SampleTest
```

## Context

 - Used versions (Jupiter/Vintage/Platform): junit-jupiter-engine:5.5.1,junit-platform-runner:1.5.1
 - Build Tool/IDE: mvn:3.6.1

Note: Before creating this issue I referred to #148, but it seems different than I am facing.

**Comment by sbrannen** [comment]
This looks like a bug in Maven Surefire, but the JUnit team does not maintain the `maven-surefire-plugin`.

So, please open an issue against [Maven Surefire](https://issues.apache.org/jira/projects/SUREFIRE/issues/SUREFIRE-1408?filter=allopenissues).

**Comment by Bananeweizen** [comment]
Just for future readers: The same issue (wrong count of "Tests run" when enabling junit 5 concurrent flags) appears in Tycho Surefire (which inherits from Maven Surefire). I've tested with Tycho Surefire 1.7.0.
