### ISSUE TITLE
Issue with @-file when classpath includes spaces in folder name

### ISSUE THREAD

**Issue by cdl-locp** [junit-team/junit5#1976]
Hi 

I'm using Junit 5 version 5.3.2 on Spring Tools Suite (STS) version 4.2.0 on Windows 10. I have my STS installed on a folder on my c drive called 'spring tools'. 

When running a Junit test within a project with a short enough classpath that an @-file is not generated, my tests run fine. I believe this is because the classpath is enclosed in double quotes.

But on a project that has a long enough classpath that an @-file is generated when running a JUnit test, I get a 'No tests found with test runner 'JUnit 5' and a message in the console saying

"Error: Could not find or load main class tools\sts-4.2.0.RELEASE\configuration\org.eclipse.osgi\233\0\.cp;C:\spring
Caused by: java.lang.ClassNotFoundException: tools\sts-4/2/0/RELEASE\configuration\org/eclipse/osgi\233\0\/cp;C:\spring"

The issue is that when I look into the @-file that is generated, the file does not generate with the classpath enclosed in double quotes so when the Picocli parser reads the classpath it falls over when encountering the white space in 'spring tools'.

I've attached an example @-file.
[temp-CsvToJsonConverterTest-classpath-arg-1565169103897.txt](https://github.com/junit-team/junit5/files/3476560/temp-CsvToJsonConverterTest-classpath-arg-1565169103897.txt)

**Comment by marcphilipp** [comment]
@cdl-locp Who writes that @-file, STS/Eclipse?

**Comment by cdl-locp** [comment]
That I do not know, any idea how I'd find out?

**Comment by marcphilipp** [comment]
@sbrannen As our Eclipse/STS user, any ideas?

**Comment by sbrannen** [comment]
I wasn't aware that Eclipse created an @-file.

@noopur2507, can you shed any light on this?

**Comment by noopur2507** [comment]
I am not aware of any @-file created by Eclipse JDT. Where do you find it? Probably something specific to STS?

**Comment by cdl-locp** [comment]
In the Run Configuration for Junits there is a 'Show Command Line' button, clicking this button generates the command line to run the test and the @-file (located in the root of the project). Running a JUnit test doesn't produce the @-file so I'm guessing either the @-file is getting removed as part of the running of the test or it is being produced in a different directory. 
![show command line](https://user-images.githubusercontent.com/43061990/62704227-c592f200-b9e2-11e9-9305-618be616f241.JPG)

**Comment by noopur2507** [comment]
The issue seems to be the whitespace in the classpath. The @-file doesn't matter. Please open a bug report in Eclipse: [https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT&component=UI](url) for this.

**Comment by marcphilipp** [comment]
Thanks for investigating, @noopur2507!

**Comment by sbrannen** [comment]
> Thanks for investigating, @noopur2507!

+1
