### ISSUE TITLE
Move LegacyReportingUtils to junit-platform-reporting

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#1978]
For historical reasons, `org.junit.platform.launcher.listeners.LegacyReportingUtils` is really in the wrong package and in the wrong module. Its purpose is reporting related, not launching related.

Proposal:

1. Copy it to `org.junit.platform.reporting.legacy` package in `junit-platform-reporting` module.
2. Deprecate the version in `junit-platform-launcher` with appropriate commentary, for future removal.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 Backlog for _team discussion_.

**Comment by marcphilipp** [comment]
**Team Decision:** We're ok with moving it to `junit-platform-reporting`.
