### ISSUE TITLE
LegacyXmlReportGeneratingListener to have configurable roots

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#1980]
`LegacyXmlReportGeneratingListener` generates one xml report file per root `TestIdentifier` instance in the in the `TestPlan` being executed. The file name is of the form `Test-nnnn.xml` where `nnn` is the name of the root node.

I recently encountered a situation where I would have liked to be able to change both the number of files generated, and the algorithm used to derive their filenames. Unfortunately, `LegacyXmlReportGeneratingListener` has been written in such a way to make this impossible without extensive use of reflection, as the necessary methods that need to be overridden are all private:

https://github.com/junit-team/junit5/blob/7dc2df5cede39eafe17f0cc026f7dfdcc96215ee/junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/LegacyXmlReportGeneratingListener.java#L102-L127

`executionFinished()` (and `executionSkipped()`) both call `writeXmlReportInCaseOfRoot()` to do the (optional) writing of an xml file. It would be ideal to simply tap into it here somewhere, but being private makes it impossible without reflection.

## Proposal

1. Combine the functionality of `isRoot()` and the code that extracts the root name in `writeXmlReportInCaseOfRoot()`. This could be done by having a single method which returns an `Optional<String>` - empty indicates a non-root (no file to be written), a string indicates the name to use in the test file. Say we call it `getRootFileName(TestIdentifier)`.
2. Make it possible to override `getRootFileName(TestIdentifier)`, either by:
   1. making it `protected` method and thereby allowing a subclass to override it, or else
   2. by making it a field of type `Function<Optional<String>, TestIdentifier>` and initializing it to the current implementation in the constructor by default.

**Comment by adityas71094** [comment]
@kriegfrj, Even I have a use case where I need to generate a test report for every test class. I later combine all these files into one report file. But right now I am not able to combine as all files have the same name.


It will be great if we are able to call a setFileName(String fileName) or a setFile(File reportFile) on LegacyXmlReportGeneratingListener.

**Comment by mseele** [comment]
@adityas71094 please see https://github.com/junit-team/junit5/issues/1989

**Comment by kriegfrj** [comment]
@adityas71094 , thanks for your comment.

Please see PR #1981. You should be able to use it to accomplish what you want by passing in an implementation for the `rootFileName` parameter that returns the name of the file that you want for each class. Eg, something like this:

```java
new LegacyXmlReportGeneratingListener(reportsDir, outWriter, x -> {
	List<Segment> segments = UniqueId.parse(x.getUniqueId())
		.getSegments();
	Segment last = segments.get(segments.size() - 1);
	if (last.getType()
		.equals("class")) {
		return Optional.of(last.getValue());
	}
	return Optional.empty();
});
```

You might need to play with the value to go in the `equals()` statement, but apart from this it should do what you want.

**Comment by kriegfrj** [comment]
Btw, I forgot to say if you have any feedback about how I've implemented this in #1981, I'm more than happy to hear it!

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 Backlog for _team discussion_.

**Comment by marcphilipp** [comment]
**Team Decision:** Since we intend to publish a completely new reporting format that supports all platform features in #373, we don't want to make further investments in the legacy XML reporting.

**Comment by kriegfrj** [comment]
I must admit I'm a bit baffled by this decision. I would understand if I was asking for a feature request/addition and asking the JUnit team to implement it; however in this case the investment had already been made as I had already submitted a PR with a complete implementation (including unit tests)?

**Comment by marcphilipp** [comment]
It's not just the initial work of implementing it and reviewing the changes. We feel this feature might be brittle and would likely cause us maintenance effort that we would rather spend on other features.
