### ISSUE TITLE
Ability to register extensions for framework provider

### ISSUE THREAD

**Issue by TheGoesen** [junit-team/junit5#1990]
This is a follow up to  
https://github.com/junit-team/junit5/issues/1938
Jmockit used to call into internal API to register it's extension. Now JMockit changed their code to set the Systemproperty 
`junit.jupiter.extensions.autodetection.enabled=true`
which is kind of official API but also is a lot worse.

- It' my decision as a user whether i want autodetection or not ,an external framework shouldn't invalidate my choice
- autodetection will pick up anything thats on the classpath, especially things i am not aware of and don't need or want. 

But the root cause seems to me that junit5 doesn't seem to provide a straighforward API for jmockit (and other frameworks) to globally register their (and only their) extension. So you can't really blame jmockit to much on there choice.

## Deliverables
Sort of: Being able to to insert a single extension in a controlled way into the extension registry.

**Comment by sbrannen** [comment]
This is very closely related to #1986.

**Comment by sbrannen** [comment]
Tentatively slated for the 5.6 backlog for _team discussion_

**Comment by marcphilipp** [comment]
TBH, I think JMockit should not activate global extension registration but let users decide if they want that (as you said). Unless I'm missing something, I don't see how any framework should make that choice and thus don't see why we should add an extension point to support it.

**Comment by TheGoesen** [comment]
Here's the Jmockit Workflow:
The user activate it by adding jmockit to the jvm as a javaagent. You need to do that, otherwise it doesn't work. Jmockit gets a callback from the jvm into plain javacode and will try to register itself with testing frameworks.
From there on it will run implicitly on all Testscases.
As a user i already decided to activate jmockit by setting the javaagent.
I think I shouldn't have to repeat myself by having to activate it a second time and installing it manually into junit. Jmockit should be able to perform the steps that I would need to manually install it into junit itself. If there was ever a usecase where I need jmockit as a javaagent, but don't want it in my unit tests, this could be solved by a configuration or property in jmockit. But currently i don't see that usecase...
