### ISSUE TITLE
Drop java.compiler dependence in org.junit.platform.commons

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1995]
In order to reduce the surface of required modules, let's follow @lukaseder advice:

https://twitter.com/lukaseder/status/1167087138246184960
> The implementation is relatively simple, I usually use Character.isJavaIdentifierStart() and Character.isJavaIdentifierPart() directly, instead.

https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/module/org.junit.platform.commons/module-info.java#L12

## Deliverables

- [x] Implement own `isJavaName(String s)` method and drop `java.compiler`

**Comment by juliette-derancourt** [comment]
I could do that! ✋ 

However, I noticed that the method used in `PackageUtils` is `SourceVersion.isName` and not `SourceVersion.isIdentifier`. This method is based on `isIdentifier` — replaceable by the methods from the tweet — but also `isKeyword`, which is checking that the name isn't a language keyword. Now this would be a bit longer to replace.

But, is it really intended to check if the name isn't a keyword? If not, we could just rewrite the `isIdentifier` call and drop the `isKeyword` call. If it is, then rewriting the whole thing would not be relevant IMO.

**Comment by sormuras** [comment]
Hi again, @juliette-derancourt -- I assigned this issue to you. Thanks for grabbing it!

You're correct. The call in question is `SourceVersion.isName`:
https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/PackageUtils.java#L76

This call should be replaced by a similar one declared within `PackageUtils` to maintain the current behaviour: fail if any part of the given package name is invalid.

You may of course refer to `SourceVersion.isName` within test scope to verify that the new implementation yields similar results.

**Comment by juliette-derancourt** [comment]
> Hi again, @juliette-derancourt -- I assigned this issue to you. Thanks for grabbing it!

My pleasure! :)

> This call should be replaced by a similar one declared within PackageUtils to maintain the current behaviour: fail if any part of the given package name is invalid.

Yes, but my point was that [isKeyword](https://github.com/openjdk/jdk/blob/2399a8d764e63145c27af17c3c3023ebdb939347/src/java.compiler/share/classes/javax/lang/model/SourceVersion.java#L378) seems to be more complex to rewrite locally, because of the version it takes as a parameter. Now that I took a closer look at it, I guess we can just check equality for all keywords since the specific cases only apply for older versions. So it’s all good ;)

> You may of course refer to SourceVersion.isName within test scope to verify that the new implementation yields similar results.

Wouldn’t it be better to get rid of the dependency altogether?

**Comment by sormuras** [comment]
> Wouldn’t it be better to get rid of the dependency altogether?

No. At test time, we're all in. Use language feature of Java 12 and use foundation modules as you need them, and introduce external test helpers if that makes life easier.

https://github.com/junit-team/junit5/blob/336945b56c79283c0efd2d5ee6c23c9fdc2ea148/buildSrc/src/main/kotlin/Versions.kt#L17-L25

**Comment by juliette-derancourt** [comment]
> No. At test time, we're all in. Use language features of Java 12, require foundation modules as you need them, and introduce external test helpers if that makes life easier.

Alright! Thanks for the answers ;)

**Comment by sbrannen** [comment]
This has been resolved in `master` via #1999.
