### ISSUE TITLE
Introduce @YamlFileSource similar to @CsvFileSource

### ISSUE THREAD

**Issue by RunningSanil** [junit-team/junit5#1996]
`@CsvFileSource` is useful, but structured data structures are not supported.

I suggest to add a `@YamlFileSource` for explicit YAML support like `@CsvFileSource` to support structured data structures.

I have created a little demo locally, but it may not be complete. I want to know what everyone thinks.

**Comment by sbrannen** [comment]
This is related to #1571.

**Comment by sbrannen** [comment]
I'm inclined to label this as a duplicate of #1794.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment]
**Team Decision**: closing as a duplicate of #1794.
