### ISSUE TITLE
Add a possibility to add custom PostDiscoveryFilter via SPI or configuration property

### ISSUE THREAD

**Issue by baev** [junit-team/junit5#1997]
Currently we are working on solution that will allow users to select tests to run from web UI. Every test is already marked by custom `@TestId` annotation, so we only missing possibility to register a custom `PostDiscoveryFilter` via SPI or some kind of configuration property. 

Currently the only way to add `PostDiscoveryFilter` is to manually create `LauncherDiscoveryRequest` but that's seems to be hard for users (imagine, they will need to switch from maven/gradle integrations to custom plugin)

I know there is possibility to run tests via className/method name or uniqueId but this values may be changed during test refactoring but they will still related to same entity in test management system. Thats why we are using custom annotation `@TestId` to store this relation.

The solution I have in mind is to implement custom `PostDiscoveryFilter`, register it via SPI, and then enable/configure it via environment variable (system property).

**Comment by sbrannen** [comment]
Have you considered relying on the built-in support for _tags_ instead?

**Comment by baev** [comment]
yes, we are using tags in some cases, for example for cucumber tests.

What for JUnit, as far as I know there is no extension that allows to provide additional tags, and currently the only way to add tags is by using `@Tag` annotation (correct me if I'm wrong). Having an extension that allows us to add custom tags from annotations may help.

The reason I'm asking for such extension instead of just having `@Tag` annotation on tests is that our users are still using tags in common way (to mark smoke tests etc). And we need to filter such tags as `system` and not display this tags to users. That adds additional complexity: in order to find this tags we are using a special notation `@allure.id=SOMEID`. And users instead of just adding additional annotation with copy-paste value should create a tag that should match our format. Plus, we have an IDE plugin that rely on same id annotation for all the test frameworks that we support.

After all that I still like to go with `PostDiscoveryFilter` as this solution may give our users a fluent experience: they only add an dependency to their project (that they already did if they want to use allure) and install our CI plugin (that they forced to do in order to use our product). When they trigger a job from our system, our CI integration generates `testplan.json` file somewhere in workspace and sets some environment variable (for example, `ALLURE_TEST_PLAN_FILE`) with the location to test plan file. 

All we need is check in `PostDiscoveryFilter` that such environment variable is exists, read the file, and filter only tests we need. 

The second advantage over tags is that we can implement more complex logic in our `PostDiscoveryFilter`, for example fallback to unique id in case of test with required id not found, or run whole class (it is always better to run extra tests instead of miss some of results)

**Comment by baev** [comment]
BTW currently as workaround we are using `ExecutionCondition`. The problem is that all the tests get into test plan, as the result we have all the tests in the report

**Comment by sbrannen** [comment]
> What for JUnit, as far as I know there is no extension that allows to provide additional tags, and currently the only way to add tags is by using `@Tag` annotation (correct me if I'm wrong). 

That's correct for JUnit Jupiter.

> Having an extension that allows us to add custom tags from annotations may help.

`PostDiscoveryFilter` is essentially already such an "extension" (so to speak) for the JUnit Platform, and I understand your desire to be able to register one globally.

Having such an extension for JUnit Jupiter, however, would not make sense. Jupiter extensions are evaluated during the "execution phase" which is too late. Tags can only be properly honored during the "discovery phase".

**Comment by sbrannen** [comment]
> BTW currently as workaround we are using `ExecutionCondition`. 

Yes, that is the best viable option for the status quo.

> The problem is that all the tests get into test plan, as the result we have all the tests in the report

And indeed... that is the only negative side effect of using an `ExecutionCondition` for this purpose.

**Comment by sbrannen** [comment]
Tentatively slated for the 5.6 backlog for _team discussion_

**Comment by choojoykin** [comment]
Hello. its seems to be good decision to give it all in junit api. In our projects we need to override ExecutionCondition and parse custom test ids from CI to run, parse our classpath for filter all junit tests. Run by Tags its common way, but if we need to run tests on some feature if we know only IDs from tms - we need, as i wrote above,  override ExecutionCondition

**Comment by baev** [comment]
is there any way to have this issue processed any time soon? Our team are very interested in this feature and we can provide some help to you if you need

**Comment by marcphilipp** [comment]
@baev Sorry for the delay! I‘ll bring it up in the next team call.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Let's add such a `ServiceLoader`-based hook, make it enabled by default, and add a boolean property to the `LauncherConfig.Builder` to disable it.

**Comment by marcphilipp** [comment]
@baev Would you be interested in submitting a PR for this?

**Comment by baev** [comment]
Sure, but it would be nice to get additional implementation notes just before I start working on it as I'm not very familiar with codebase.

So far it looks like the entry point is `LauncherDiscoveryRequestBuilder` -- JUnit Platform integrations use it directly to create `LauncherDiscoveryRequest` that holds filters and selectors (for example, in [maven-surefire](https://github.com/apache/maven-surefire/blob/master/surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java#L183-L188)). But at that point we have no access to `LauncherConfig`.

The other option would be apply registered filters in `EngineDiscoveryOrchestrator`

**Comment by marcphilipp** [comment]
I think it should be done in `EngineDiscoveryOrchestrator`.

**Comment by baev** [comment]
@marcphilipp I created pull request #2283 , could you please take a look, there are some design considerations required in order to continue the work

**Comment by sdoeringNew** [comment]
I think this sounds like something we need.

But how does it work? I did not see any changed documentation on the pull request.

**Comment by marcphilipp** [comment]
The docs are here: https://junit.org/junit5/docs/current/user-guide/#launcher-api-post-discovery-filters-custom
