### ISSUE TITLE
Allow tests to be executed in a user-defined thread

### ISSUE THREAD

**Issue by debruyckere** [junit-team/junit5#20]
## Overview

In JUnit 4, we use a specific test runner that runs the test code on a dedicated UI thread, such as the AWT/Swing thread (or the JavaFX thread). This avoids cluttering your code with `EventQueue.invokeAndWait` all over the place. As far as I understood, the current extensions proposal does not allow to do such thing.

The below runner simply wraps all calls to _before_, _after_, and _test_ methods in an `EventQueue.invokeAndWait` call. Tests simply have to declare `@RunWith(AWTThreadRunner.class)` to get this behavior.

``` java
    public class AWTThreadRunner extends BlockJUnit4ClassRunner {
      public AWTThreadRunner(Class<?> klass) throws InitializationError {
        super(klass);
      }

      @Override
      protected Statement classBlock(RunNotifier notifier) {
        return onAWTThreadStatement(super.classBlock(notifier));
      }

      @Override
      protected Statement methodBlock(FrameworkMethod method) {
        return onAWTThreadStatement(super.methodBlock(method));
      }

      private static Statement onAWTThreadStatement(final Statement aStatement) {
        return new Statement() {
          @Override
          public void evaluate() throws Throwable {
            EventQueue.invokeAndWait(new Runnable() {
              public void run() {
                aStatement.evaluate();
                // left out exception handling code improve readability
              }
            });
          }
        };
      }
    }
```

Note: the actual implementation is a bit more complex in that it does proper exception handling and refuses JUnit's time-outs as that doesn't work together with running on a dedicated thread.

## Related Issues

- #157

**Comment by sbrannen** [comment]
Hi @debruyckere,

Thanks for raising this issue.

We are already considering providing a mechanism for test extensions to influence the way tests are physically executed.

Once we begin work on this front, we'll post back here.

Regards,

Sam

**Comment by akozlova** [comment]
Looks like relates to #157, I tried to have a custom engine for this issue.

This engine delegates to jupiter like:
```
public class EDTAwareEngine implements TestEngine {
  private JupiterTestEngine myEngine = new JupiterTestEngine();

  @Override
  public String getId() {
    return "junit-jupiter-edt";
  }

  @Override
  public TestDescriptor discover(EngineDiscoveryRequest request, UniqueId id) {
    return myEngine.discover(request, id);
  }

  @Override
  public void execute(ExecutionRequest request) {
    try {
      SwingUtilities.invokeAndWait(() -> myEngine.execute(request));
    }
    catch (Throwable e) {
      e.printStackTrace();
    }
  }
}
```
works well by itself but as discovery mechanism is the same, all tests are discovered twice. This problem could be solved with EngineFilters but unfortunately engine filters are not provided as extensions: one can register them on launcher request or for JUnitPlatform runner. Even if IDE would allow to take this parameter from some configuration, it won't work good (cause this configuration can't be retrieved from the code).  Frankly saying I don't want to invent my own annotations with all discovery and execution staff. Any ideas how to deal with this or should we just wait for this issue to be resolved?

**Comment by sbrannen** [comment]
> Any ideas how to deal with this or should we just wait for this issue to be resolved?

I think it's best to wait for this issue to be resolved.

**Comment by sbrannen** [comment]
Closing this issue as _superseded_ by #157.

Please continue the discussion on this topic there.
