### ISSUE TITLE
Access to the Include-/Exclude-ClassnameFilters

### ISSUE THREAD

**Issue by svenruppert** [junit-team/junit5#2001]
If you are writing a custom TestEngine, the discovery method will be the entrance for the selection of the TestClasses. If you want to select a package and you are using an IDE ( IntelliJ in my case) the IDE will give you a ClasspathRooSelector in combination with an Include- and / ExcludeClassnameFilter.

`request.getFiltersByType(ClassNameFilter.class);` is not enough, because the implementing classes are not public.

## Deliverables
- [ ] access to the pieces of information to build a proper TestDescriptor

**Comment by marcphilipp** [comment]
Why do you need access to the implementing classes?
Are you using `EngineDiscoveryRequestResolver` which was introduced in 1.5?

**Comment by svenruppert** [comment]
hhmm I am implementing the method `public TestDescriptor discover(EngineDiscoveryRequest request, UniqueId engineID)` .  At the point `request.getSelectorsByType(ClasspathRootSelector.class)` I want to extract this filters given by IntelliJ to create the TestDescriptors. IntelliJ is not using the PackageSelector.

**Comment by sormuras** [comment]
I wonder if the issue vanishes when using the [AbstractClassBasedTestEngine](https://github.com/sormuras/mainrunner/blob/master/src/de.sormuras.mainrunner.engine/main/java-8/de/sormuras/mainrunner/engine/AbstractClassBasedTestEngine.java) as the base class of your engine.

You "just" specify what a test method/class is, and it cares about the discovery process.

**Comment by marcphilipp** [comment]
@svenruppert Please have a look at `EngineDiscoveryRequestResolver`. It does all that for you if you call `addClassContainerSelectorResolver`. It will convert `ClasspathRootSelectors`, `ModuleSelectors`, and `PackageSelectors` into `ClassSelectors` which you can then resolve.

Here's a full example from the Jupiter engine:
https://github.com/junit-team/junit5/blob/9ffd427e4b94a1d433bddb188c489d5b35b9d22d/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java#L32-L48

`ClassNameFilters` should also be applied when resolving `ClassSelectors`. You can get the filter as a `Predicate<String>` by calling `context.getClassNameFilter()`.

**Comment by svenruppert** [comment]
@marcphilipp ok, will try it. Thx

**Comment by svenruppert** [comment]
@marcphilipp hhmm , the only thing here. I have to add the Jupiter Engine to the dependencies of my Custom TestEngine. So I have to extract this.

**Comment by svenruppert** [comment]
@marcphilipp OK, it is working. The discovery process itself is something generic and I really would love to see a solution that would abstract this away from the Developer of a Test-Engine. Just the definition of a TestClass and a TestMethod would be needed.

**Comment by marcphilipp** [comment]
@sormuras Do we yet have an issue to track that?

**Comment by sormuras** [comment]
Not, yet. But soon.

I already have a candidate that works like @svenruppert describes: [AbstractClassBasedTestEngine](https://github.com/sormuras/mainrunner/blob/master/src/de.sormuras.mainrunner.engine/main/java-8/de/sormuras/mainrunner/engine/AbstractClassBasedTestEngine.java) -- you just tell this abstract base class what a test class/method is and it cares about the rest.

**Comment by sormuras** [comment]
Created #2011 - thus closing this issue.
