### ISSUE TITLE
Improve @TestInstance documentation regarding @Nested test classes

### ISSUE THREAD

**Issue by michael-simons** [junit-team/junit5#2002]
Having `@TestInstance` on a toplevel test class changes the lifecycle of this class. 

My simple assumption would be, that the lifecycle of all nested `@Nested` test classes are changed accordingly. 
This is not the case, they also need to be configured.

While I find this behaviour irritating and would expect all classes down the hierarchy to share the lifecycle of the container class, I also can life with configuring it.

It would be important to document this however. 

Sometimes one notices, sometimes don't. 

Documentation can be in form of docs (apparently), but a warning log maybe helpful, too.

On a side note, current docs state:

> Used to configure the test instance lifecycle for the annotated test class. Such annotations are inherited.

Now, "inherited" of course refers to annotation inheritance with `@Inherited` which only applies to  real inheritance, but to a causal reader it could seem that an outer class actually inherits its lifecycle.

**Comment by sormuras** [comment]
Attached a bunch of labels -- tagged for next team discussion.

**Comment by sbrannen** [comment]
Thanks for raising the issue.

Tentatively slated for the 5.5 backlog for _team discussion_

**Comment by sbrannen** [comment]
FWIW, the Javadoc is a bit more explicit:

> Note, however, that an explicit lifecycle mode is inherited within a test class hierarchy.

**Comment by marcphilipp** [comment]
**Team brainstorming:** While we cannot change the default in order to stay backwards compatible, we could introduce a new config param to opt-in to applying the lifecycle from the `@TestInstance` annotation to nested classes.

**Comment by khmarbaise** [comment]
stumbled over the same problem. The given suggestion by @marcphilipp sounds like a very good idea.
@sbrannen Doesn't that mean the inheritance via `extends` ?

**Comment by sbrannen** [comment]
> @sbrannen Doesn't that mean the inheritance via `extends` ?

Yes. In this context (test class hierarchy), I am referring to inheritance hierarchies (via `extends`).

The other form of hierarchy is a "nested class hierarchy" in which there is no actual form of inheritance in the object oriented sense of the term.

**Comment by jbduncan** [comment]
This still sounds like a useful feature, although I admit I've never been a big user of nested classes in JUnit. :)
