### ISSUE TITLE
junit-platform-commons-1.5.1-sources.jar from Maven Central has module-info.class instead of module-info.java

### ISSUE THREAD

**Issue by rgoldberg** [junit-team/junit5#2003]
`junit-platform-commons-1.5.1-sources.jar` downloaded from Maven Central has `module-info.class` instead of `module-info.java`.

This same problem might occur in other files & other versions.

**Comment by sormuras** [comment]
`junit-jupiter-5.5.1-sources.jar` has it too... others as well. Like `junit-jupiter-5.6.0-20190906.085229-49-sources.jar`.

Thanks for raising this issue.

**Comment by sormuras** [comment]
Underlying reason is this block that's applied to all `Jar` tasks:

https://github.com/junit-team/junit5/blob/ada66c4f698e48ed01d3bd787af2bfd96f5f661b/buildSrc/src/main/kotlin/java-library-conventions.gradle.kts#L96-L98
