### ISSUE TITLE
Provide class-based TestEngine support

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2011]
The [AbstractClassBasedTestEngine](https://github.com/sormuras/mainrunner/blob/master/src/de.sormuras.mainrunner.engine/main/java-8/de/sormuras/mainrunner/engine/AbstractClassBasedTestEngine.java) already implements the base logic needed to support a (Java) class-based `TestEngine`. Derived classes only have to specify what a test class and what a test method is, and all "communication" with the JUnit Platform is handled under the hood.

## Deliverables

- [ ] Decide if JUnit Platform should provide such abstract `TestEngine` support class
- [ ] Another abstract support class `AbstractAnnotationBasedTestEngine<MyTest>` that handles a custom method annotation.

**Comment by svenruppert** [comment]
any news here?

**Comment by sormuras** [comment]
None, yet. Waiting for further interest in this feature.
