### ISSUE TITLE
JUnit Platform Release Notes

### ISSUE THREAD

**Issue by arturdryomov** [junit-team/junit5#2013]
Right now [release notes are combined](https://junit.org/junit5/docs/current/release-notes/index.html#release-notes). There is a number of issues with this approach:

* when using a custom `TestEngine` users don’t really care about JUnit changes, but care very much about platform changes;
* there is no per-version changes for platform components — for example, `junit-platform-launcher` was updated to `1.5.2` recently but there is no way to find out what was changed from `1.5.1`;
* relates to the previous point but it is a bit weird to see `5.x` and `1.x.x` together which is confusing for new people (it fades away once you start thinking about the platform and Jupiter / Vintage as different-level things).

Also, it might be useful to actually split all the documentation into two blocks — one is for the platform, another one for Jupiter / Vintage. I think a lot of people don’t really care about the platform since their user interactions are based around engines built on it.

**Comment by marcphilipp** [comment]
> there is no way to find out what was changed from `1.5.1`

Isn't there? It says "No changes" here: https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.5.2-junit-platform

**Comment by sbrannen** [comment]
> > there is no way to find out what was changed from `1.5.1`
> 
> Isn't there? It says "No changes" here: [junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.5.2-junit-platform](https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.5.2-junit-platform)

I was also going to point that out.

Though I can understand that it is confusing for people unfamiliar with JUnit 5.

Perhaps we should put the version numbers next to the subproject names in the headers.

Otherwise, one can misinterpret that to mean JUnit Platform 5.5.2 instead of 1.5.2.

**Comment by ming13** [comment]
For me it looks like there were changes to JUnit artifacts, not JUnit platform ones. At least in my head JUnit artifacts are completely independent from JUnit platform ones. They have different versions after all and different responsibilities.

**Comment by ming13** [comment]
This situation actually reminds me Android Support (AndroidX) libraries situation when they had all libraries tied to a single version. So even if a single artifact was changed all artifacts were updated. Nowadays they’ve switched to the independent scheme.

**Comment by pauldingemans** [comment]
Usage of release notes may vary per reader. On the other hand the release notes are not generated but manually written by different contributors. So it is important to keep it simple and therefore less error prune.

I think it is possible to use sub documents to construct different views of the release notes. One such view could be identical to the current documentation (per release split by sub project) while another view split the sub project by release.

For this we need to create a separate asciidoc per sub project. Those documents are the ones that need to changed whenever an issue is closed which needs to be addressed specifically in the release notes.

For each view on the release note there exists a separate asciidoc which only contains the scaffolding and include statements for the sub project release notes.

I will be happy to give it a try if the idea is supported.

**Comment by marcphilipp** [comment]
@pauldingemans With "subproject" you mean platform, jupiter, and vintage, right?

**Comment by pauldingemans** [comment]
> @pauldingemans With "subproject" you mean platform, jupiter, and vintage, right?

Yes I do.
