### ISSUE TITLE
Allow tests to be enabled or disabled on a range of JREs

### ISSUE THREAD

**Issue by wilkinsona** [junit-team/junit5#2016]
I'd like to test some code that behaves in different ways depending on the version of the JRE on which it's running. In my particular case, the code behaves in one way on Java 12 and earlier and in another on Java 13 and later. We have CI jobs that test on Java 8, 11, 12, and 13 (we'll probably drop 12 soon due to it being superseded by 13).

As CI jobs on new JREs are added and removed, I'd prefer for it not to be necessary to change the code to make sure that the right tests are enabled. As far as I can tell, even if `@EnabledOnJre` and `@DisabledOnJre` were repeatable, this goal would not be met. Instead, what I'd really like to be able to do is specify a (possibly open-ended) range of JREs on which a test should be enabled or disabled. In my particular case being able to enable a test on JRE 12 and earlier and another on JRE 13 and later would be sufficient, but I'm sure there are other use cases that would benefit from support for closed ranges.

## Deliverables

- [ ] Support for enabling or disabling a test on a range of JREs

**Comment by marcphilipp** [comment]
**Team Decision:** Introduce a new `@EnabledForJreRange` annotation that has optional `min`/`max` attributes to define closed, potentially half open ranges, e.g. `@EnabledForJreRange(min = JAVA_8)`, `@EnabledForJreRange(max = JAVA_11)`, `@EnabledForJreRange(min = JAVA_8, max = JAVA_11)`.

**Comment by marcphilipp** [comment]
@wilkinsona Would you be interested in submitting a PR?

**Comment by wilkinsona** [comment]
Yeah, I would, although it'll probably be mid-October before I have time to tackle it.

**Comment by marcphilipp** [comment]
Alright, I've put it up-for-grabs in case someone else wants to pick it up in the meantime.

**Comment by aepfli** [comment]
i actually would love to try to implement this :D - i will try my best next week, and i will let you know if i think i am able to do this. - but looks pretty straight forward

**Comment by sormuras** [comment]
Give it a shot, @aepfli 👍

**Comment by aepfli** [comment]
my Assumption:
- the ordinality of JRE is reliable for version comparison
- JRE.JAVA_8 will always be the lowest version, so i can use it as default for min value
- JRE.OTHER will always be the highest version, so i can use it as default for max value

Question:
- is there also a usecase for `@DisabledOnJreRange`? should i take that into account?

**Comment by marcphilipp** [comment]
Sounds good and I think there's a use case for `@DisabledOnJreRange`, too! 👍

**Comment by juliette-derancourt** [comment]
Maybe they should be mutually exclusive though, to avoid weird cases?
What should happen if a test combines ´@EnabledForJreRange(min = JAVA_8, max = JAVA_11)´ and ´@DisabledForJreRange(min = JAVA_10, max = JAVA_12)´ for instance? 😮

**Comment by aepfli** [comment]
I can agree that there might be weird cases, but I think right now there is no exclusivity over `@Disabled*` and `@Enabled*` of the same type. So I can do this theoretically already with just `@EnabledOnJre` and `@DisabledOnJre` already. Hence that I would stick to the existing behavior of this functionality.

Furthermore I think it will be difficult to handle, what if a method has `@DisabledOnJre` and the class has a @EnabledOnJre`. This will get really tricky in my opinion.

**Comment by sormuras** [comment]
> Each of the conditional annotations listed in the following sections can only be declared once on a given test interface, test class, or test method. If a conditional annotation is directly present, indirectly present, or meta-present multiple times on a given element, only the first such annotation discovered by JUnit will be used; any additional declarations will be silently ignored. Note, however, that each conditional annotation may be used in conjunction with other conditional annotations in the `org.junit.jupiter.api.condition` package.

Copied from https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution

That and the lazy evaluation -- the first condition that yields "disabled" wins -- ensures a deterministic behavior. Users may always implement a custom `ExecutionCondition` to apply a logic of their choice.

**Comment by marcphilipp** [comment]
> What should happen if a test combines `@EnabledForJreRange(min = JAVA_8, max = JAVA_11)` and `@DisabledForJreRange(min = JAVA_10, max = JAVA_12)` for instance? 

I guess it should run on Java 8 and 9... certainly a good way to confuse one's coworkers. 😉
