### ISSUE TITLE
assumptions that fail on success

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#2022]
So I think this might actually be a number of features. Note that assumptions might be the wrong thing, this may be a new thing entirely.

My use case is that I am developing against a spec (FHIR), I know what *should* pass, but currently some things cannot pass, I'd like to write tests for them anyways, should they someday pass I'd like to be alerted that they are passing so I can mark them as not an assumption. Currently I'm just disabling the tests. The only way I can think to do this is fail on passing assumptions (globally) so that we can know if the test is now passing.

**Comment by sbrannen** [comment]
> I know what _should_ pass, but currently some things cannot pass, I'd like to write tests for them anyways, should they someday pass I'd like to be alerted that they are passing so I can mark them as not an assumption.

The proper way to implement this is with tags.

1. Define a tag name -- for example _WIP_ (work in progress).
2. Annotate test classes or test methods with `@Tag("WIP")` (or create a custom composed `@WIP` annotation that's meta-annotated with `@Tag("WIP")`).
3. Exclude the "WIP" tag from the build.
4. Occasionally include the "WIP" tag in the build to see which WIP-tests now pass.
5. Remove the `@Tag("WIP")` declaration on tests that now pass.
6. Go to step # 3 and repeat.

**Comment by marcphilipp** [comment]
How is this different from #2023?

**Comment by xenoterracide** [comment]
this is about changing how to deal with assume behavior globally (and/or some other facility)), whereas #2023 is specifically to allow assumptions by an annotation. @sbrannen's example might work for that, though I would prefer that it was something provided by Junit and thus less custom, more standard.

For this, I don't like step 4, as it requires manual intervention (though I understand the counter argument, reproducible builds)

**Comment by marcphilipp** [comment]
Did you see my comment about `@ExpectToFail` I posted in the other issue? https://github.com/junit-team/junit5/issues/2023#issuecomment-534502331

FWIW Spock has a similar annotation called `@PendingFeature`:
http://spockframework.org/spock/docs/1.3/all_in_one.html#_pendingfeature

If there's sufficient interest, we could make a polished version of our extension public.

Would that work for your use case?

**Comment by xenoterracide** [comment]
I think so, I was thinking a more global way of setting the behavior here, but that's perhaps a bad idea in the first place.

**Comment by marcphilipp** [comment]
I think a global switch that says "expect all tests to fail unless I said otherwise" would be strange. I'm inclined to close this one and continue the discussion for an annotation-based approach in #2023.

@xenoterracide Any objections?

**Comment by xenoterracide** [comment]
well it wasn't really "expect all tests to fail" but yes, I think we can do that
