### ISSUE TITLE
Vintage Parameterized Tests are more than two orders of magnitude slower

### ISSUE THREAD

**Issue by marschall** [junit-team/junit5#2030]
JUnit 5.5.2

## Steps to reproduce

Run the following empty test. With JUnit 4 it takes about 2 seconds to run, with the JUnit 5 vintage engine it takes about 250 seconds to run.

https://github.com/marschall/junit5-Segment-hashCode/blob/master/src/test/java/com/github/marschall/junit5/segmenthashcode/ReproducerTest.java

## Context

We have a JUnit 4 Parameterized test with about 70'000 total tests. 3 Tests with about 20'000 parameters. The test runs massively slower with the JUnit 5 vintage engine compared to the the JUnit 4 engine.

Profiling highlights the following hot spots:

- `TestRun#getInProgressTestDescriptorsWithSyntheticStartEvents` has a bad complexity (probably O(N²)) because every time it iterates over all started descriptors, it gets slower the more tests you have
- `UniqueId#hashCode` is not memoized 
- `UniqueId#toString` is not memoized

See the following flight recording

<img width="883" alt="TestResult" src="https://user-images.githubusercontent.com/471021/65680904-36a46c80-e058-11e9-81df-41084a245562.png">

**Comment by marcphilipp** [comment]
Thanks for reporting this issue! 👍 

I had also seen that being slow in a recent profile I did in https://github.com/junit-team/junit5/pull/2012#issue-317622439.

I will improve it for 5.6.

**Comment by marcphilipp** [comment]
@marschall I see you have already started, have you?

**Comment by marschall** [comment]
Yes, the changes take the runtime of the posted empty test from ~250 seconds to ~4 seconds.
