### ISSUE TITLE
Support timeouts for extensions

### ISSUE THREAD

**Issue by dartyuhov** [junit-team/junit5#2037]
Hi, I tried to set up timeouts for extension methods (`BeforeAllCallback` or `AfterEachCallback`) by using the `@Timeout` annotation with it, but it didn't work.

Also I've tried to set global timeouts such us `junit.jupiter.execution.timeout.aftereach.method.default`, and this also hasn't worked. 

It would be great to see this feature in JUnit 5 next releases.

**Comment by marcphilipp** [comment]
@dartyuhov Can you use `Assertions.assertTimeoutPreemptively(Duration, ThrowingSupplier<T>)` in your extension instead?

**Comment by dartyuhov** [comment]
@marcphilipp thank you for quick reply!
Yes, as temporal solution I decided to use 'assertTimeoutPreemptively' method. But it still seems strange for me that extensions don't obey to whole project timeout rules. From my point of view extensions methods are same part of test lifecycle as common @beforeeach or @afterall(and so on) methods. Please correct me if I'm thinking wrong.

**Comment by marcphilipp** [comment]
You're not wrong. We initially decided against supporting `@Timeout` on extensions since we weren't sure how useful that will be. So you'd want to add `@Timeout` to your method definitions in your `Extension` implementation, right?

**Comment by dartyuhov** [comment]
yes, it would be useful from my point of view

**Comment by SgtSilvio** [comment]
randomly stumbled upon this. While one can workaround with `assertTimeoutPreemptively`, it would be great if extensions follow the same timeout principles of being able to configure global default timeouts and overwriting them on specific methods if necessary.
Currently it is not possible to avoid stuck CI builds entirely by defining global timeout properties and all extensions need to carefully implement timeouts themselves (which is desired, but would global timeouts for safety would be great).
