### ISSUE TITLE
New junit.org Website

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#205]
Create new website:
- More modern site generation, e.g. Jekyll
- More modern, responsive layout
- Split website in areas for JUnit4 and JUnit5

**Comment by marcphilipp** [comment]
I've started to work on this in my fork:
https://github.com/marcphilipp/junit5/tree/gh-pages

**Comment by marcphilipp** [comment]
TODOs:
- [ ] better icon for Javadoc
- [ ] id for events heading
- [ ] iCal feed?

**Comment by marcphilipp** [comment]
Even though we will probably continue to work on the website, I'm closing this issue for now as we have an initial version.
