### ISSUE TITLE
Improve error reporting for exceptions thrown by SelectorResolvers in EngineDiscoveryRequestResolution

### ISSUE THREAD

**Issue by lbernwald** [junit-team/junit5#2052]
Exceptions thrown by custom `SelectorResolvers` for test discovery are not propagated back to the `TestEngine` when using the `EngineDiscoveryRequestResolver`, therefore also not the `Launcher` and consequently also not the user. Currently if discovery in a `SelectorResolver` fails, JUnit only reports that no tests were found.

I am building a custom `TestEngine`, because I have some domain-specific needs, that Jupiter does not fulfill. To reduce the workload for coding the discovery phase of the engine I started using the `EngineDiscoveryRequestResolver` suggested in #1739 and introduced with #1798.
If Tests are malformed, i. e. my `SelectorResolver` checks whether the Tests have been specified correctly, discovery in my engine should outright fail by throwing an exception. Suggested in #1909 and introduced with #2006 exceptions thrown by the `TestEngine` are reported to the `TestExecutionListeners` and potentially provide the user with feedback why the discovery has failed. Unfortunately that is not the case for the `EngineDiscoveryRequestResolver` respectively the `EngineDiscoveryRequestResolution`. As far as I can tell the class just [catches all `Throwables`](https://github.com/junit-team/junit5/blob/d6c023e10349109d7e57d642b4191e2ba5e156fd/junit-platform-engine/src/main/java/org/junit/platform/engine/support/discovery/EngineDiscoveryRequestResolution.java#L95) and simply logs them internally. The user never gets to see the reason why the Test Discovery failed or rather why no tests could be found.

Might it be possible to let the `Exceptions` caught in the `EngineDiscoveryRequestResolver` respectively the `EngineDiscoveryRequestResolution` to not be caught in that class, but to let them travel up the hierarchy to the `TestEngine` to be then caught by the `Launcher` and as a result to be propagated back to the user?
Or is there any other way to communicate the reason for failed test discovery back to the user?

## Deliverables

- [ ] Propagate exceptions thrown by `SelectorResolvers` to the `TestEngine`

**Comment by marcphilipp** [comment]
I ran into a similar problem yesterday when using the `Launcher` and trying to debug why there weren't any tests. Thus, I've spiked a potential solution in #2060.

@lbernwald I'd appreciate your feedback on the PR!

**Comment by lbernwald** [comment]
The proposed solution definitely works. I've tried it out with my engine and it correctly propagates the error caused by the discovery back to the user by logging it. It thus solves the issue, I had.

I have provided further feedback on the PR.
