### ISSUE TITLE
how to use assert to confirm two jsonString equals

### ISSUE THREAD

**Issue by danishlyy** [junit-team/junit5#2055]
junit 4 :
code:
`   @Test
    public void testToJSONString(){
        String text = "{\n" +
                "    \"userName\":\"张三\",\n" +
                "    \"gender\":1,\n" +
                "    \"email\":\"920331569@qq.com\",\n" +
                "    \"age\":20,\n" +
                "}";
        PersonDTO personDTO = new PersonDTO();
        personDTO.setUserName("张三");
        personDTO.setGender(1);
        personDTO.setEmail("920331569@qq.com");
        personDTO.setAge(20);
        String json = JSON.toJSONString(personDTO);
        System.out.println(json);
        System.out.println(text);
        System.out.println(text.equals(json));
        
    }`
result json String:
`{"age":20,"email":"920331569@qq.com","gender":1,"userName":"张三"}
{
    "userName":"张三",
    "gender":1,
    "email":"920331569@qq.com",
    "age":20,
}`
the two json key and value are all the same,but the location has some different.I mean that the two json is equal,but I use assertEqual(json,text) return false

**Comment by danishlyy** [comment]
> junit 4 :
> code:
> ` @test
> public void testToJSONString(){
> String text = "{\n" +
> " "userName":"张三",\n" +
> " "gender":1,\n" +
> " "email":"[920331569@qq.com](mailto:920331569@qq.com)",\n" +
> " "age":20,\n" +
> "}";
> PersonDTO personDTO = new PersonDTO();
> personDTO.setUserName("张三");
> personDTO.setGender(1);
> personDTO.setEmail("[920331569@qq.com](mailto:920331569@qq.com)");
> personDTO.setAge(20);
> String json = JSON.toJSONString(personDTO);
> System.out.println(json);
> System.out.println(text);
> System.out.println(text.equals(json));
> 
> ```
> }`
> ```
> 
> result json String:
> `{"age":20,"email":"920331569@qq.com","gender":1,"userName":"张三"} { "userName":"张三", "gender":1, "email":"920331569@qq.com", "age":20, }`
> the two json key and value are all the same,but the location has some different.I mean that the two json is equal,but I use assertEqual(json,text) return false

**Comment by smoyer64** [comment]
The Go Testify library does this by unmarshaling to Map<String, byte[]> (effectively) and comparing the maps ... a similar strategy should work in Java.
