### ISSUE TITLE
@BeforeParameter/@AfterParameter  to do prameter level initialization 

### ISSUE THREAD

**Issue by adityas71094** [junit-team/junit5#2062]
We are in a process of migrating our JUnit4 testcases to JUnit5.
In JUnit4 all the tests in a class associated with one parameter in parameterized tests ran in one class. So It was possible to to use the constructor to do some initialization at each parameter level. But in JUnit5 each test case in a test class seems to be run on its own instance of the class. So we are no longer able to use the constructor to do parameter level initialization. Is there any plans of introducing any new feature/annotation to accomplish the same.
Eg. code to demonstrate the required behavior in JUnit4

    public ParameterizedCaseTest4(String a , String b)
    {
        System.out.println("constructor");
        System.out.println(System.currentTimeMillis());
    }

    @Parameters
    public static List<Object[]> testCases()
    {
        return Arrays.asList(new Object[][]
                {
                        {"a" , "a"},//ID=1
                        {"b" , "b"},//ID=1
                        {"c" , "c"},//ID=2
                });
    }

    @BeforeClass
    public static void init() throws Exception
    {
        System.out.println("before all");
        System.out.println(System.currentTimeMillis());
    }

    @Test
    public void test1() throws Exception
    {
        System.out.println("test1 " + expected2 + " " + expected);
        System.out.println(System.currentTimeMillis());
    }

    @Test
    public void test2() throws Exception
    {
        System.out.println("test2" + expected2 + " " + expected);
        System.out.println(System.currentTimeMillis());
    }

    @AfterClass
    public static void destroy() throws Exception
    {
        System.out.println("after all");
        System.out.println(System.currentTimeMillis());
    }

**Comment by marcphilipp** [comment]
Thanks for reporting this issue! We plan to add support for parameterization on the class level in #878. Please add your vote there.
