### ISSUE TITLE
A lot of warnings in IntelliJ IDE

### ISSUE THREAD

**Issue by IgorGanapolsky** [junit-team/junit5#2064]
## Steps to reproduce
Clone repo and open it in IntelliJ

See screenshot.  There are plenty of warnings and build errors in the Gradle script:
<img width="1375" alt="Screen Shot 2019-10-15 at 12 14 50 PM" src="https://user-images.githubusercontent.com/201209/66849848-a4e89a80-ef45-11e9-8b0c-a989cda486bd.png">

## Context

 - Used versions (Jupiter/Vintage/Platform): latest MASTER BRANCH
 - Build Tool/IDE: IntelliJ EAP IU-193.4386.10 (IU-193.4386.10)

**Comment by juliette-derancourt** [comment]
Maybe try to reimport the gradle project or enable auto-import?
I am also using IntelliJ and don't have any warnings...

**Comment by IgorGanapolsky** [comment]
@juliette-derancourt Now there is an error:
> The JUnit 5 build requires Java 12 or higher. Currently executing with Java 11.

**Comment by juliette-derancourt** [comment]
That's because you need to install at least the JDK 12 to be able to build the project 😉

**Comment by IgorGanapolsky** [comment]
When I run `java --version` it shows 
> java 12.0.2 2019-07-16

However, IntelliJ doesn't like it and advises to use bundled Java....

**Comment by juliette-derancourt** [comment]
You can choose which JDK will be used in the Gradle panel of the settings (`Build, Execution, Deployment > Build Tools > Gradle`)

**Comment by IgorGanapolsky** [comment]
Please see screenshot.  No `JDK
<img width="1015" alt="Screen Shot 2019-10-15 at 2 58 15 PM" src="https://user-images.githubusercontent.com/201209/66861034-3c58e800-ef5c-11e9-9177-3d25237ea589.png">
` option there:

**Comment by sormuras** [comment]
Trolling? You're showing the `Preferences for New Projects` dialog.

Try `File` -> `Settings...`

![image](https://user-images.githubusercontent.com/2319838/66861741-d5552680-ef8f-11e9-9278-43c9a5a12864.png)

**Comment by sormuras** [comment]
Or hit the 🔧 in the 🐘 Gradle Tool Window

**Comment by IgorGanapolsky** [comment]
None of this fixes the original issue in the OP....

**Comment by sormuras** [comment]
> I am also using IntelliJ and don't have any warnings...

IntelliJ IDEA 2019.3 EAP (Community Edition)
Build #IC-193.4386.10, built on October 9, 2019
Runtime version: 11.0.4+10-b517.1 amd64

.
.
.

`OutOfIdeasError` 😞

Perhaps there's help on StackOverflow or at [JetBrains](https://youtrack.jetbrains.com)?

**Comment by marcphilipp** [comment]
After setting the JDK you need to reimport the Gradle project.

**Comment by IgorGanapolsky** [comment]
@marcphilipp Still the same problem.  I've opened the issue with JetBrains (https://youtrack.jetbrains.com/issue/IDEA-224895)

**Comment by marcphilipp** [comment]
Thanks for letting us know! I'm closing this issue for now. Please let us know if the problem persists.
