### ISSUE TITLE
Make (Dis|En)ableIfEnvironmentVariableCondition public

### ISSUE THREAD

**Issue by Brunomachadob** [junit-team/junit5#2066]
Is there a reason why `DisabledIfEnvironmentVariableCondition.java` and `EnabledIfEnvironmentVariableCondition.java` are not public?

I would like to extend these classes and override `getEnvironmentVariable` to be able to get the variable from [java-dotenv](https://github.com/cdimascio/java-dotenv) instead of `System.getenv`

I could open a PF for that is that's OK.

## Deliverables

- [ ] `DisabledIfEnvironmentVariableCondition` is public
- [ ] `EnabledIfEnvironmentVariableCondition` is public

**Comment by sormuras** [comment]
> Is there a reason why `DisabledIfEnvironmentVariableCondition.java` [...] are not public?

They are an implementation detail of their corresponding annotations. I don't see a way how you could re-register your implementation in such a way that the default `@DisabledIfEnvironmentVariable` annotation delegates to it.

I guess, you have to implementation your own annotation and extension.

**Comment by Brunomachadob** [comment]
I currently created both the annotation and the condition class.

Examples in Kotlin:

```kotlin
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
@ExtendWith(DisabledIfDotEnvCondition::class)
annotation class DisabledIfDotEnv(val named: String, val matches: String)
```

```kotlin
private class DisabledIfDotEnvCondition(): ExecutionCondition {
//...
}
```

But the thing is that I could create my Condition class extending the JUnit one and just override `getEnvironmentVariable `.

Now, `DisabledIfDotEnvCondition` is a complete duplication of the JUnit condition class changing only the `getEnvironmentVariable`

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 M2 for _team discussion_.

**Comment by marcphilipp** [comment]
It would not be sufficient to override `getEnvironmentVariable()` since you'll have to use your own annotation which the abstract base class would not know about.

**Team decision:** Since Java does not support inheritance in annotations we recommend that you implement your own extension.

**Comment by Brunomachadob** [comment]
The thing is that `I will use my own annotation` and `@ExtendWith` my own `ExecutionCondition`, but it would be easier if I could extend JUnit's condition to avoid this much duplication.

This is my current setup:

```java
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
@ExtendWith(DisabledIfDotEnvCondition::class)
annotation class DisabledIfDotEnv(val named: String, val matches: String)

/**
 * Used to determine if a test should be skipped using our dotenv environments
 * Based on: org.junit.jupiter.api.condition.DisabledIfEnvironmentVariableCondition
 * */
private class DisabledIfDotEnvCondition(): ExecutionCondition {
    override fun evaluateExecutionCondition(context: ExtensionContext): ConditionEvaluationResult {
        val optional = AnnotationUtils.findAnnotation(context.element, DisabledIfDotEnv::class.java)

        if (!optional.isPresent) {
            return ConditionEvaluationResult.enabled("@DisabledIfDotEnv is not present")
        }

        val annotation = optional.get()
        val name = annotation.named.trim { it <= ' ' }
        val regex = annotation.matches

        Preconditions.notBlank(name) { "The 'named' attribute must not be blank in $annotation" }
        Preconditions.notBlank(regex) { "The 'matches' attribute must not be blank in $annotation" }

         // The only real change I made, the rest is copy/past from your definition. I your class were public.
        // I could just override the getEnvironmentVariable
        val actual = getEnv(name)

        return when {
            actual.matches(regex.toRegex()) -> ConditionEvaluationResult.disabled(String.format("Environment variable [%s] with value [%s] matches regular expression [%s]", name, actual, regex))
            else -> ConditionEvaluationResult.enabled(String.format("Environment variable [%s] with value [%s] does not match regular expression [%s]", name, actual, regex))
        }
    }
}
```

**Comment by marcphilipp** [comment]
This block is specific to your annotation:

```kotlin
val annotation = optional.get()
val name = annotation.named.trim { it <= ' ' }
val regex = annotation.matches
```

To make it reusable, the abstract base class would have to support different annotation types. Thus, we'd either have to add methods like `getNamed()`, `getMatches()` (and additional ones if we add more attributes in the future) or have you supply us with the annotation `Class<T>` and a `Function<T, String>` for each attribute. Neither seems worth the complication. If you think differently, please show us how you'd refactor `EnabledIfEnvironmentVariableCondition` to make that possible.

**Comment by Brunomachadob** [comment]
No, it's not. I just converted to `Kotlin` as I said above.
Believe me, I did not change anything but the `getEnv` part, the rest is "the same", but in Kotlin.

Have a look here, you can see we are doing the same thing:

https://github.com/junit-team/junit5/blob/10d5cec27fbec2a5df7a5f19932978ce59b55933/junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfEnvironmentVariableCondition.java#L45
```java
...
EnabledIfEnvironmentVariable annotation = (EnabledIfEnvironmentVariable)optional.get();
String name = annotation.named().trim();
String regex = annotation.matches();
...        
```

The only change I would make to `(En|Dis)abledIfEnvironmentVariableCondition` is to make them public, so I can extend it and override `getEnvironmentVariable`

**Comment by sbrannen** [comment]
Hi @Brunomachadob,

You misunderstood what @marcphilipp was saying.

The attributes/methods `named()` and `matches()` are specific to your annotation.

You may think they are the same simply because they have the same names and identical return types; however, they are not the same.

The two annotations are of different types in Java.

And since Java does not support inheritance for annotations, it is not possible for the compiler to see them as the "same type".

Thus, your proposal simply would not compile.

**Comment by Brunomachadob** [comment]
Yes, indeed. You're right.

The implementation would require an additional change here:
```java
Optional<EnabledIfEnvironmentVariable> optional = AnnotationUtils.findAnnotation(context.getElement(), EnabledIfEnvironmentVariable.class);
```

To point out the `annotation that is being extended by this class`, instead of the hardcoded `EnabledIfEnvironmentVariable.class`
