### ISSUE TITLE
Test Data Container for DynamicTest

### ISSUE THREAD

**Issue by RuslanSafa** [junit-team/junit5#2067]
It would be convenient if there was a class for test data to use it as a container for dynamic tests. In the dynamic test, there are incoming parameters and the expected result, and for convenience, you could still include the name of the test case.
For example
```java
public class TestData<I, O> {
    private final String nameTest;
    private final I inData;
    private final O outData;
}
```

**Comment by sormuras** [comment]
What would a usage example look like?

**Comment by RuslanSafa** [comment]
`java
@TestFactory
Stream<DynamicTest> test_dynamic_is_validated() {
    return Stream.of(TestData.of("is_validated_true", createRowValidated(), Boolean.TRUE),
                     TestData.of("is_validated_false", createRowReject(), Boolean.FALSE))
            .map(testData -> DynamicTest.dynamicTest(testData.getNameTest(), () -> assertThat(validatorUtils.isValidated(testData.getInData())).isEqualTo(testData.getOutData())));
}
`

**Comment by marcphilipp** [comment]
**Team decision:** We feel that this use case is better addressed by parameterized tests (see the following for an example).

This looks a lot like a `@ParameterizedTest`:

```java
@ParameterizedTest
@MethodSource("my_params")
void test_dynamic_is_validated(Object row, boolean expected) {
	assertThat(validatorUtils.isValidated(row)).isEqualTo(expected);
}

Stream<Arguments> my_params() {
	return Stream.of(
		Arguments.of(createRowValidated(), true),
		Arguments.of(createRowReject(), false)
	);
}
```

**Comment by RuslanSafa** [comment]
th's
