### ISSUE TITLE
Hide JupiterTestEngine and VintageTestEngine from standard Java code

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2073]
## Overview

The _trick_ described in https://github.com/netty/netty/pull/9687#pullrequestreview-304243904 provides a way to hide the `JupiterTestEngine` and `VintageTestEngine` from standard Java code.

Since we only made those two classes `public` to make them usable by the `ServiceLoader` mechanism, we should consider implementing this _trick_ to better encapsulate the internals of Jupiter and Vintage.

FYI: I tried it out locally for the `JupiterTestEngine`, and it works. Note, however, that we might have to use reflection in a few places in our test suite as a result of the change.

## Deliverables

- [ ] Decided if we want to hide `JupiterTestEngine` and `VintageTestEngine` from standard Java code.

**Comment by sormuras** [comment]
That's a core feature of the Java module system. Let's not re-invent it with some "reflection in a few places". Yes, the module system is optional, which leaves every user to option to use it.

Declare you test module like...
```java
open /*test*/ module it {
  requires org.junit.jupiter;
}
```
...and you'll only see ... not a single test engine class as an end-user. Nor are you presented hidden packages from `org,junit.platform.commons` modules.

**Comment by marcphilipp** [comment]
**Team Decision:** Since all `public` methods of both classes are part of the `TestEngine` interface, hiding it in this way does not buy us much. Since we're instantiating these classes from our tests, we would mainly make life harder for ourselves.
