### ISSUE TITLE
Improve documentation for writing tests and contional test execution

### ISSUE THREAD

**Issue by aepfli** [junit-team/junit5#2076]
During the implementation of #2016 we could see that crucial information regarding conditional test execution was missing within the documentation.

Although the information is present in the [Extensions](https://github.com/junit-team/junit5/blob/master/documentation/src/docs/asciidoc/user-guide/extensions.adoc#L243-L247) section of the User Guide ...

> When multiple `ExecutionCondition` extensions are registered, a container or test is
disabled as soon as one of the conditions returns _disabled_. Thus, there is no guarantee
that a condition is evaluated because another extension might have already caused a
container or test to be disabled. In other words, the evaluation works like the
short-circuiting boolean OR operator. 

... this kind of information is missing within the [Writing Tests](https://github.com/junit-team/junit5/blob/master/documentation/src/docs/asciidoc/user-guide/writing-tests.adoc#L334) section, which can lead to confusion when people start using multiple `ExecutionCondition`s.

## Deliverables

- [ ] Update User Guide to present or link crucial information

**Comment by aepfli** [comment]
there is already a link in place, which might be overseen, when just looking at the docs. i think that maybe adding just the first sentence to the "writing-docs" documentation, might be useful for developers. As a link might be easily over looked.

**Comment by marcphilipp** [comment]
I agree that adding the first sentence to the end of the first paragraph makes sense. 👍

**Comment by aepfli** [comment]
Perfect than I will open the pr tomorrow ;)

**Comment by sormuras** [comment]
Thanks, @aepfli!
