### ISSUE TITLE
Add typed accessor to Arguments

### ISSUE THREAD

**Issue by onacit** [junit-team/junit5#2081]
Recently I needed to fetch values from an `Arguments` object sourced from another method.

```java
static Stream<Arguments> sourceSome() {
    return OtherClass.sourceOther().map(a -> {
        return Arguments.of(new Some((Casted) a.get()[0]),
                            new Other((Casted) a.get()[1]));
    });
}
```

It will be much better if we have `Arguments#get(int index, Class<T> type)`.

## Deliverables

- [ ] Add typed accessor to `Arguments`.

**Comment by sbrannen** [comment]
As stated in the class-level Javadoc for `Arguments`:

**API Note:**

This interface is specifically designed as a simple holder of arguments of a parameterized test. Therefore, if you end up transforming or filtering the arguments, you should consider using one of the following in intermediate steps:

- The standard collections
- Tuples from third-party libraries, e.g., Commons Lang, or javatuples
- Your own data class

> Recently I needed to fetch values from an `Arguments` object sourced from another method.

Can you please describe your use case in a little more detail and explain why the aforementioned alternatives do not meet your needs?

**Comment by onacit** [comment]
The original source method sources two object references of different types.

```java
static Stream<Arguments> sourceLevel1() {
    return Stream.of(Arguments.of(A, B));
}
```
And the second source method sources two object references of, again, different types.

```java
static Stream<Arguments> sourceLevel2() {
    return sourceLevel1().map(a -> {
        A a = (A)a.get()[0];
        B b = (B)b.get()[1];
        return Arguments.of(new C(a), new D(b));
    });
}
```

**Comment by marcphilipp** [comment]
There's already `ArgumentsAccessor` which provides an API like the one you're requesting. While `DefaultArgumentsAccessor` is `@API(Internal)`, you could instantiate it as an interim solution. If that's worthwhile, we could think about adding an `ArgumentsAccessor.from(Arguments)` static factory method.

**Comment by onacit** [comment]
Oh. I should've known [`ArgumentAccessor`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/params/aggregator/ArgumentsAccessor.html).
Now, my codes look like this.
```java
return sourceByteIoArray().map(a -> {
    final ArgumentsAccessor accessor = new DefaultArgumentsAccessor(a.get());
    return Arguments.of(new DefaultBitOutput(accessor.get(0, ByteOutput.class)),
                        new DefaultBitInput(accessor.get(1, ByteInput.class)));
});
```
And I suddenly became eager to
```java
Arguments#apply(Function<? super ArgumentAccessor, ? extends Arguments>)
```
or
```java
Arguments#accept(Consumer<? super ArgumentAccessor>)
```
Thanks.

**Comment by sormuras** [comment]
Here's another example: https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-aggregation including: _apart from direct access to a @ParameterizedTest method’s arguments using an ArgumentsAccessor, JUnit Jupiter also supports the usage of custom, reusable aggregators._

**Comment by onacit** [comment]
It seems `ArgumentConverter` works for me.
```java
@MethodSource("...#sourceLevel1") // provides A and B
@ParameterizedTest
void test(@ConvertWith(A_to_C_Converter.class) final C c,
          @ConvertWith(B_to_D_Converter.class) final D d) {
}
```
