### ISSUE TITLE
Links in the docs to CI are referencing to 404

### ISSUE THREAD

**Issue by khmarbaise** [junit-team/junit5#2089]
Currently the links within the README.md file on Github to the continuous integration are both showing 404 error pages.

```
## Continuous Integration Builds

[![CI Status](https://github.com/junit-team/junit5/workflows/CI/badge.svg)](https://github.com/junit-team/junit5/actions) [![Cross-Version Status](https://github.com/junit-team/junit5/workflows/Cross-Version/badge.svg)](https://github.com/junit-team/junit5/actions)
```

https://github.com/junit-team/junit5/#continuous-integration-builds
are currently showing pages with 404 error messages.

**Comment by sormuras** [comment]
Seeing the 404 errors, too.

Strangely, the `Actions` tab is not showing up on this repo. On my personal repos, they do work.

Possibly related: https://github.community/t5/GitHub-Actions/Actions-tab-missing/td-p/36233

**Comment by sormuras** [comment]
Created https://github.community/t5/GitHub-Actions/Actions-tab-missing-actions-URL-404-runs-work/m-p/36462/highlight/true#M2580 ... let's what happens.

**Comment by sormuras** [comment]
It's working again.

Thanks @ethomson ;-)

**Comment by khmarbaise** [comment]
Thanks working.
