### ISSUE TITLE
Gradle task type for executing tests

### ISSUE THREAD

**Issue by MartinAhrer** [junit-team/junit5#209]
I'm excited to start playing with a new JUnit. I'm a Gradle user and I was wondering if there are plans to add a task type such that I can declare my own task (or even multiple tasks) with a configuration different from the configuration provided by the extension.

```
task commitTest (type: Junit5Test) {
   requireTag 'commit'
}

```

This would allow for example executing different sets of tests within a project. E.g. fast tests, slow tests, commit tests (in terms of delivery pipeline commit test), etc.

**Comment by marcphilipp** [comment]
Thanks for your feedback! We're in touch with the Gradle team already and hope that they will start to work on "official" support in Gradle similar to the current support for JUnit 4 and TestNG as soon as we've shipped Milestone 1. This will then hopefully enable you to use a custom task type.
