### ISSUE TITLE
Support @Tag as meta-annotation.

### ISSUE THREAD

**Issue by christophstrobl** [junit-team/junit5#2097]
It would be nice if `@Tag` could be used as meta annotation so that one can create a custom annotation without having to repeat a certain string/tag value, while being able to read the value via `ExtensionContext#getTags()` when evaluating an `ExecutionCondition`.

```java
@Tag("condition");
public @interface RequiresMyConditionToBeMatched {

}
```

**Comment by sormuras** [comment]
This already works: https://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotations

**Comment by christophstrobl** [comment]
sorry for the noise - I had the Retention set. It was my IDE that would not want to compile it.

**Comment by marcphilipp** [comment]
@christophstrobl No worries, thanks for letting us know!
