### ISSUE TITLE
Introduce TestExecutionListener for configuring Java Logging for test suites

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2099]
## Overview

Various logging frameworks have mechanisms for test configuration. For example, log4j2 supports a `log4j2-test.xml` file in the root of the classpath, which people typically store under `src/test/resources`.

Java Util Logging (JUL) on the other hand has no mechanism for automatic discovery of test configuration. One can of course set the `java.util.logging.config.file` JVM system property, but that can be cumbersome since one would have to set it for every single run configuration within an IDE.

For the Spring Framework, I introduced a JUnit Platform `TestExecutionListener` that automatically looks for a file named `jul-test.properties` in the root of the classpath and used it to configure JUL. See this commit for details: https://github.com/spring-projects/spring-framework/commit/89b3a9cef218c0d6ff3121d3f0c386b0c2f06dbc

## Deliverables

- [ ] Decide if it would be useful to introduce such a `TestExecutionListener` as an opt-in feature of the JUnit Platform.

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M2 for _team discussion_

**Comment by marcphilipp** [comment]
**Team Decision:** Wait for interest from the community.
