### ISSUE TITLE
OSGi capability namespace for TestEngines

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2100]
Pending the resolution of #2095:

I would also like to see us leverage the OSGi capability mechanism in some way to define dependency relationships between test bundles and test engine bundles. That way, the resolver can help with making sure that the correct engines are included in the set of run bundles. For example, the test engine bundle could declare something like this:

```
Provide-Capability: org.junit.platform.engine;
    org.junit.platform.engine.id='junit-jupiter;version="[5.5.1]"' # By convention, make this == TestEngine.getId()
    version=5.5.1
```
...then the test bundle can declare its dependency on a particular versions of particular engines by (eg) the following:

```
Require-Capability: org.junit.platform.engine;
   org.junit.platform.engine.id='junit-jupiter;version="[5.5,6)",junit-vintage;version=4.12,org.myorg.my-test-engine;version=1.0'
```

Now the resolver will be able to ensure that the test bundles are paired with the correct versions of the correct test engines. The syntax might need a bit of tweaking (I'm not an expert in this area), but hopefully the idea makes sense.

## Deliverables

- A specification for the capability namespace for test engine implementations.
- Add the appropriate `Provide-Capability` metadata to the `junit-jupiter-engine` and `junit-vintage-engine` OSGi manifests.

**Comment by marcphilipp** [comment]
**Team decision:** We're okay with adding the metadata.
