### ISSUE TITLE
Consider support for PostDiscoveryFilters in EngineTestKit

### ISSUE THREAD

**Issue by mmerdes** [junit-team/junit5#2109]
The `EngineTestKit` is able to execute an `EngineDiscoveryRequest`.

This implies that a `PostDiscoveryFilter` is not respected since such filters are not applied by the `EngineTestKit`. Such filters are only applied by the `Launcher` when executing multiple test engines.

For example, `TagFilter.includeTags(...)` and `TagFilter.excludeTags(...)` are not supported by the `EngineTestKit`, and if they are registered via a `LauncherDiscoveryRequest` that is passed to the `EngineTestKit`, they are silently ignored.

This issue serves as a place to discuss the options for supporting `PostDiscoveryFilter` in EngineTestKit-based integration tests.

**Comment by marcphilipp** [comment]
Another use case is testing that a `TestDescriptor` doesn't get pruned (because that also happens in the `Launcher`).
