### ISSUE TITLE
junit-lambda URL not correct

### ISSUE THREAD

**Issue by mariusneo** [junit-team/junit5#211]
While browsing through the project I've see in the junit5/build.gradle file the following snippet : 

```
				pom.project {
					name "${project.group}:${project.name}"
					packaging 'jar'
					description "Module \"${project.name}\" of JUnit 5."
					url 'http://junit.org/junit-lambda.html'
```

, but the URL  http://junit.org/junit-lambda.html does not exist on junit.org website (404 HTTP error code).

On the other hand, this page exists : 
http://junit.org/junit4/junit-lambda.html

I guess that the issue to be fixed is actually on the junit.org site, which adds junit4 to every page.
e.g. : http://junit.org/junit4/junit5.html

**Comment by marcphilipp** [comment]
That's a bug I introduced last night... thanks for reporting it! :-)

**Comment by marcphilipp** [comment]
Temporarily fixed the link by using a Javascript redirect. We will be working on a new website for JUnit 5 in the next few weeks.
