### ISSUE TITLE
ThrowableCollector.toTestExecutionResult() is package private

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2113]
We're in the process of trying to update the baseline version of Eclipse used in our `BundleEngine`. This has in turn updated the baseline version of JUnit 5 from an ancient version (5.0.0 of Jupiter and 1.0.1 of junit-platform) to something more recent.

Our `BundleEngine` used to make use of `SingleTestExecutor`, which is now deprecated. The deprecation note in `SingleTestExecutor` advises to use `ThrowableCollector.execute()` and `ThrowableCollector.toTestExecutionResult()` instead:

https://github.com/junit-team/junit5/blob/01e00d21016554dcdabd5a993a88a2f20cab6df9/junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/SingleTestExecutor.java#L29-L30

However, `toTestExecutionResult()` is package private.

The code is simple enough that I can (and will) roll our own in `BundleEngine`. However, this is an annoyance and means it's not a 100% replacement for `SingleTestExecutor` (where this functionality was public).

## Deliverables

Either:
1. make `toTestExecutionResult()` public, or
2. document a publicly-available alternative in the `SingleTestExecutor` deprecation note.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 M1 for _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Let's make it public.

**Comment by marcphilipp** [comment]
@kriegfrj Would you be interested in submitting a PR for this?

**Comment by kriegfrj** [comment]
> @kriegfrj Would you be interested in submitting a PR for this?

Done!
