### ISSUE TITLE
JUnit Vintage distributes tests very unevenly between forks, causing poor parallelism

### ISSUE THREAD

**Issue by Dretch** [junit-team/junit5#2114]
Junit 5.6.0-M1

## Steps to reproduce

Run the following test case with `mvn clean verify`:
[junit-5-vintage-bug.zip](https://github.com/junit-team/junit5/files/3891165/junit-5-vintage-bug.zip)

Observe output like the following:
```[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running My7Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.017 s - in My7Test
[INFO] Running My9Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.983 s - in My9Test
[INFO] Running My4Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.998 s - in My4Test
[INFO] Running My8Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.999 s - in My8Test
[INFO] Running My6Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.001 s - in My6Test
[INFO] Running My1Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1 s - in My1Test
[INFO] Running My5Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.999 s - in My5Test
[INFO] Running My3Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.997 s - in My3Test
[INFO] Running My2Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1 s - in My2Test
[INFO] Running My0Test
Test in process 32569
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.999 s - in My0Test
```

Notice how all the tests are being run on the same process. This is wrong because there should be 5 forks - and the tests should be evenly distributed between them.

If Junit4 is used instead of Junit5+vintage (see the commented dependency in `pom.xml`) then this issue does not occur.

Thanks for any help :cake:

**Comment by sormuras** [comment]
["Forking"](https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html) is feature that Maven Surefire provides, we can't control/fix from our side. Thus, closing this issue. An issue created at https://issues.apache.org/jira/browse/SUREFIRE might help.

#### Why does it work with JUnit 4?
Because Surefire selects another Surefire Provider, namely: https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit.html

**Comment by Dretch** [comment]
Thanks @sormuras , I have logged an issue with surefire: https://issues.apache.org/jira/browse/SUREFIRE-1725
