### ISSUE TITLE
Introduce TestTemplateInvocationContextBuilder

### ISSUE THREAD

**Issue by AOreshin** [junit-team/junit5#2117]
Hello, everyone! I'm just starting to contribute, so if I'm making any mistakes, please tell me how to do it right :)

## Overview
I'm enjoying using TestTemplateInvocationContextProvider in conjuction with @ExtendsWith and @TestTemplate - it's a powerful tool that helps to bring all test invocation configuration in one place, do some fine tuning without using TestBase classes. And it helps to avoid tons of annotations above test methods. All of which greatly increases readability and maintainability of the tests.

## Proposal
Introduce TestTemplateInvocationContextBuilder, which contains following methods:

- withDisplayName(String displayName)

self explanatory

- withDisplayNamePrefix(String displayNamePrefix)
- withDisplayNamePostfix(String displayNamePostfix)

this allows grouping of display names which makes them more readable 

- addExtension(Extension extension)

adds extension at the end of the extension list, which makes it first or last among others, depending on type 
[Docs reference](https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order-wrapping-behavior)

- addExtension(int index, Extension extension)

adds extension at certain place in list of extensions to force certain order of execution

- addParameterResolver(Class<T> parameterType, T value)

syntactic sugar for adding ParameterResolver if test method parameters contains only one parameter with T type

- addParameterResolver(Class<T> parameterType, T value, String parameterName)

syntactic sugar for adding ParameterResolver if test method parameters contains one or more parameters with T type and they need to be distinguished.

- build()

returns TestTemplateInvocationContext with displayName and extensions

## Deliverables
Speeding up of test creation, ease of maintenance, increase in readability

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 M1 for _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Waiting for additional interest from the community.
