### ISSUE TITLE
JUnit 5 reporting in gradle

### ISSUE THREAD

**Issue by mariusneo** [junit-team/junit5#212]
I'm not sure if this is not a duplicate request, and if it is, please simply close it.

While browsing the documentation of the project : 
http://junit.org/junit5/#running-tests

I thought to have a look how the test output is done via gradle command : 

```
./gradlew :documentation:test
```

This command outputs in documentation/build/test-results/junit5 directory two files : 
- TEST-junit4.xml
- TEST-junit5.xml

My initial intention was to see what `example.DisplayNameDemo` will output in the test results (btw this is a feature that I like very much in Spock groovy framework : http://spockframework.github.io/spock/docs/1.0/spock_primer.html), but in the output (TEST-junit5.xml) I don't see any mention about the tests which successfully run.

Can you point me out how can I see the test reports for the tests from the documentation project via gradle?
If you find this relevant for more users, maybe it makes sense to update the adocs of the project.

**Comment by marcphilipp** [comment]
At the moment we generate one XML file per TestEngine. Thus, the tests from `example.DisplayNameDemo` are in `TEST-junit5.xml`:

```xml
<testcase name="Custom test name containing spaces" classname="example.DisplayNameDemo" time="0"><!--Unique ID: [engine:junit5]/[class:example.DisplayNameDemo]/[method:testWithDisplayNameContainingSpaces()]--></testcase>
<testcase name="╯°□°）╯" classname="example.DisplayNameDemo" time="0"><!--Unique ID: [engine:junit5]/[class:example.DisplayNameDemo]/[method:testWithDisplayNameContainingSpecialCharacters()]--></testcase>
<testcase name="😱" classname="example.DisplayNameDemo" time="0"><!--Unique ID: [engine:junit5]/[class:example.DisplayNameDemo]/[method:testWithDisplayNameContainingEmoji()]--></testcase>
```

**Comment by marcphilipp** [comment]
Jenkins can display them this way:
https://junit.ci.cloudbees.com/job/JUnit5/lastCompletedBuild/testReport/example/DisplayNameDemo/

**Comment by mariusneo** [comment]
Sorry, I didn't look with more attention. The file `TEST-junit5.xml` does indeed contain data about all the executed test cases. Thanks for pointing this out.
