### ISSUE TITLE
'mvn test' doesn't run tests with maven-surefire-plugin version 3.0.0-M4 when having cucumber 4.8.0 version

### ISSUE THREAD

**Issue by rsm8988** [junit-team/junit5#2120]
When my project pom contains below build configuration and parent pom has cucumber-4.8.0 version:
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M4</version>
      </plugin>
    </plugins>
  </build>

When I execute mvn test command it is not able to read runner.java class and it is also not able to read .features.

Always it returns:
Running TestRunner Tests run: 0

![image](https://user-images.githubusercontent.com/58452807/70018132-21454480-15ab-11ea-95b6-e1bd49e01239.png)

**Comment by juliette-derancourt** [comment]
Could you share your pom please?

> and it is also not able to read .features.

How are you launching your Cucumber tests? Do you have a Java class with the Cucumber runner? You have to import `junit-vintage` as well, since Cucumber has not yet provided JUnit 5 support (although they seem to be pretty close as https://github.com/cucumber/cucumber-jvm/issues/1149 was closed some days ago).

**Comment by rsm8988** [comment]
By using below command i was trying to execute my tests:

mvn -f D:\NisumAutomationPlatform\%Project_PATH%\pom.xml test -DargLine="-Ddc.platformName=Windows -Ddc.browserName=chrome -DtestType=PC -DElementWaitTimeoutInSeconds=30 -Dcucumber.options='--tags @regression'"

And below are my pom dependencies: 

<dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>4.4.0</version>
        </dependency>
<dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-jvm</artifactId>
            <version>4.4.0</version>
            <type>pom</type>
        </dependency>
<dependency>
            <groupId>net.javacrumbs.json-unit</groupId>
            <artifactId>json-unit-assertj</artifactId>
            <version>2.7.0</version>
        </dependency>

**Comment by rsm8988** [comment]
My TestRunner.Java

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import cucumber.api.testng.AbstractTestNGCucumberTests;
import cucumber.api.testng.CucumberFeatureWrapper;
import cucumber.api.testng.TestNGCucumberRunner;
import org.junit.runner.RunWith;
import org.testng.annotations.*;

//@RunWith(Cucumber.class)
@CucumberOptions(
        features = "features",
        glue = {"stepdefinitions"},
        tags = {"@project_omni_sta"},
        plugin = {"pretty",
                "html:target/cucumber_target.html", "json:target/cucumber.json"})
public class TestRunner extends AbstractTestNGCucumberTests {

}

**Comment by rsm8988** [comment]
issue is resolved after adding <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>4.4.0</version>
        </dependency>

**Comment by rsm8988** [comment]
Once I'll update the cucumber version to 4.8.0 and provide a final update

**Comment by juliette-derancourt** [comment]
> issue is resolved

👍

Btw, just be aware that this repository (and therefore this issue tracker) is only dedicated to JUnit 5, I see that you are using JUnit 4 😉

**Comment by rsm8988** [comment]
Thank you all.. The issue is fixed after adding cucumber-testng in project pom.

**Comment by UrbanNomadIT** [comment]
@juliette-derancourt  I had exactly this issue and solved exactly as @ramareddy88. In case any of you you could explain what's wrong I would be glad. Why I need testing to run unit/cucumber tests via maven?

**Comment by juliette-derancourt** [comment]
I honnestly have no clue.

@junit-team/junit-lambda Any ideas?

**Comment by marcphilipp** [comment]
@UrbanNomadIT I'm not sure what you're asking. It sounds like @ramareddy88 wasn't using JUnit but TestNG to run the Cucumber tests, or am I missing sth.?

**Comment by mpkorstanje** [comment]
There are several inconsistencies in the information that has been provided that make the problem untraceable.

I'd recommend that anybody facing the same problem first decides if they want to use Cucumber with TestNG, JUnit 4 or JUnit 5. If you are unsure which one to choose, pick the one you use for the other tests in your project. If you do not have other test, default to JUnit 4.

After this, make sure the non-chosen integrations are not present. This means that a project should have either `cucumber-testng`, `cucumber-junit` or `cucumber-junit-platform-engine`. So if `cucumber-junit` was chosen then `cucumber-testng` and  `cucumber-junit-platform-engine` should not be used as a dependency.

- https://github.com/cucumber/cucumber-jvm/tree/master/testng
- https://github.com/cucumber/cucumber-jvm/tree/master/junit
- https://github.com/cucumber/cucumber-jvm/tree/master/junit-platform-engine

**Comment by marcphilipp** [comment]
@mpkorstanje Thanks for the detailed explanation! 👍

**Comment by sourisengupta** [comment]
I also resolved the same issue by removing testng from the pom.xml file. But if I have to use testNG to make the test parallel then how can we use that?

**Comment by Nikasan** [comment]
> I also resolved the same issue by removing testng from the pom.xml file. But if I have to use testNG to make the test parallel then how can we use that?

the same
