### ISSUE TITLE
Consider removing bin/ build/ out/ and */out/* patterns from .gitignore

### ISSUE THREAD

**Issue by vlsi** [junit-team/junit5#2125]
Note: `.gitignore` patterns are not tied to the location of `.gitignore` file by default.

In other words, `build/` ignores `build` folders in all the possible subfolders.
In other words, if one day someone creates `org.junit.build.tools` Kotlin/Java package, then it would be excluded as well.

It might result in sad stories up to the point when the code might be lost (e.g. developer thinks the code is kept in Git, but in fact it is not there).

In the same way, `*/out/*` duplicates `out/` pattern.

Git enables to specify paths "relative to .gitignore location" by prefixing the patterns with `/`

So I suggest to use the following:

```
/build/
/*/build/

/out/
/*/out/

/bin/
/*/bin
```

See also https://twitter.com/phillip_webb/status/1202820013905727488

**Comment by marcphilipp** [comment]
Good catch, thanks! 👍
