### ISSUE TITLE
Add support for fixed and random test delays during concurrent testing

### ISSUE THREAD

**Issue by dsbecker** [junit-team/junit5#2126]
When using JUnit 5 concurrent test functionality as a form of integration testing, I would like the ability to configure a random (with min/max bounds) or fixed delay between tests to simulate a more natural load. Currently I'm handling this with a `@BeforeEach` that calls a `Thread.sleep(...)` but would like to see configuration parameters to handle this natively.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 M2 solely for the purpose of _team discussion_.

**Comment by dsbecker** [comment]
Awesome! Thank you.

**Comment by marcphilipp** [comment]
**Team Decision:** We don't think this use case is general enough to warrant a specific feature in the Jupiter API. You can implement it using an extension that implements `BeforeEachCallback` that you [register globally](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic).

**Comment by dsbecker** [comment]
Thank you for considering it.
