### ISSUE TITLE
Add expectedMessage to assertThrows

### ISSUE THREAD

**Issue by jimshowalter** [junit-team/junit5#2128]
Currently the way to check for an expected message is `assertEquals("the exception message", assertThrows(SomeException.class, () -> some.operationThatThrows()).getMessage());`

That's repeated boilerplate, and after a while it gets kind of annoying. You could add:

`assertThrows(SomeException.class, () -> some.operationThatThrows(), "the exception message");`

Except you can't, because that signature is already taken to provide a way to specify a failure message. So you'd either need a new method name, like `assertThrowsWithExpectedMessage`, or some ugly thing like a new provider similar to the Supplier for failure messages. I'd lean towards a new method name.

Related: https://github.com/junit-team/junit5/issues/2129

**Comment by marcphilipp** [comment]
If we implemented this, some people will argue that you should only check the message with contains. Maybe you want to check the root cause etc. Thus, instead of adding a new overload of assertThrows for each of these use cases, we explicitly decided against adding APIs to check properties of exceptions. This way, users can choose which assertion library to use.

```java
var e = assertThrows(SomeException.class, () -> some.operationThatThrows())
assertEquals("the exception message", e.getMessage());
```

I'd argue while the above might be a little verbose, it's very readable and consistent with the other assertions provided by the Jupiter API. If you want more powerful assertions, you might be better of using an assertion library such as AssertJ:

```java
assertThatExceptionOfType(SomeException.class)
    .isThrownBy(() -> some.operationThatThrows())
    .withMessage("the exception message");
```

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 M2 solely for the purpose of _team discussion_.

**Comment by jimshowalter** [comment]
We could use AssertJ, but then instead of just JUnit and Mockito (which are sufficiently different to justify managing two dependencies), we have to add another testing jar, for just a trivial amount of additional functionality, similar to adding more matchers when the bulk of what's needed is already available in JUnit.

Each dependency increases work, and we have to ensure they're compatible every time we upgrade a dependency version. We'd rather offload it to you!

**Comment by sbrannen** [comment]
If were to decide to add support for an expected message, another option would be to declare the expected message as the second argument as follows.

```java
public static <T extends Throwable> T assertThrows(
    Class<T> expectedType,
    String expectedMessage,
    Executable executable,
    Supplier<String> messageSupplier) {

      // ...
}
```

**Comment by marcphilipp** [comment]
**Team Decision:** We think the current basic assertion APIs in Jupiter support this use case well enough. Adding an overload of `assertThrows` with additional parameters will make it shorter but not easier to read. Users who need such an assertion frequently should consider using an assertion library like AssertJ or extract their own specialized assertion method.
