### ISSUE TITLE
Provide way to specify that the root cause should be checked in assertThrows

### ISSUE THREAD

**Issue by jimshowalter** [junit-team/junit5#2129]
Currently `assertThrows(SomeRootCause.class, () -> some.operationThatUsesReflectionToInvokeSomethingThatThrows);` fails, because it tries to match `SomeRootCause.class` to the outermost exception, which in this case is `InvocationTargetException.class`.

The workaround is to not use `assertThrows` and instead write a try/catch block that calls `some.operationThatUsesReflectionToInvokeSomethingThatThrows`, catch `InvocationTargetException`, and get the inner exception oneself, all without framework support.

It would be nicer if the framework provided something like `assertThrowsInnermost(SomeRootCause.class, some.operationThatUsesReflectionToInvokeSomethingThatThrows);`, or `assertThrows(SomeRootCause.class, some.operationThatUsesReflectionToInvokeSomethingThatThrows, true);`, where the new `boolean` overload tells the framework to get the innermost exception instead of the outermost exception.

Related: https://github.com/junit-team/junit5/issues/2128

**Comment by marcphilipp** [comment]
Why not do it like this (assuming the cause is the root cause)?

```java
var e = assertThrows(InvocationTargetException.class, () -> some.operationThatUsesReflectionToInvokeSomethingThatThrows);
assertEquals(SomeRootCause.class, e.getCause().getClass());
```

or with AssertJ

```java
assertThatExceptionOfType(InvocationTargetException.class)
    .isThrownBy(() -> some.operationThatUsesReflectionToInvokeSomethingThatThrows)
    .withRootCauseInstanceOf(SomeRootCause.class);
```

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 M2 solely for the purpose of _team discussion_.

**Comment by jimshowalter** [comment]
There's no guarantee that the cause is just one level deep, so we wind up having to write:

`Throwable t = assertThrows(etc);
while (t.getCause() != null) {
    t = t.getCause();
}`

After doing that several times and converting it to a utility method, it begs the question why we're writing it instead of it being provided.

As for using AssertJ, yes, we could do that, but then instead of just JUnit and Mockito (which are sufficiently different to justify managing two dependencies), we have to add another testing jar, for just a trivial amount of additional functionality, similar to adding more matchers when the bulk of what's needed is already available in JUnit.

Each dependency increases work, and we have to ensure they're compatible every time we upgrade a dependency version. We'd rather offload it to you!

**Comment by marcphilipp** [comment]
**Team Decision:** We think the current basic assertion APIs in Jupiter support this use case well enough. Adding an overload of `assertThrows` with additional parameters will make it shorter but not easier to read. Users who need such an assertion frequently should consider using an assertion library like AssertJ or extract their own specialized assertion method.
