### ISSUE TITLE
Ability to add @tags during runtime

### ISSUE THREAD

**Issue by BChitrakannan** [junit-team/junit5#2134]
With reference to this thread, https://github.com/junit-team/junit5-samples/issues/118#event-2883368068 

It would be nice to have the ability to add tags during runtime (especially for Data-Driven Testing). 

Use Case: 
1. We are using different test data for a test case. We want to group all the positive test data as a smoke suite and add negative test data to the Regression suite. 

Model Test Data:

` {
    "testName": "Sample 1",
    "tag":"smoke",
    "testData":"TD"

  },

{
    "testName": "Sample 2",
    "tag":"Regression",
    "testData":"TD12"

  }`

Let me know if this is feasible!

**Comment by marcphilipp** [comment]
Tags cannot be added dynamically at the moment because they have to be known during test discovery so they can be used for filtering. Your use case sounds like you'd want some kind of extension mechanism that adds tags programatically during test discovery, right?

**Comment by marcphilipp** [comment]
Related issue: #1997

**Comment by BChitrakannan** [comment]
Yes. It would be really easy to group the test cases externally. I can run the same test case with different data. Only few data qualify to be in smoke/regression suite. 

As is, If i mark a test case as Smoke test case, it will be executed with all the data which is not necessary!

**Comment by marcphilipp** [comment]
@BChitrakannan You could implement a custom `ExecutionCondition` to disable test cases you're not interested in. The only downside would be that the ones that are filtered out are counted as skipped. Would that suit your needs?

**Comment by marcphilipp** [comment]
@BChitrakannan Have you tried the above workaround?

**Comment by BChitrakannan** [comment]
Hi @marcphilipp , the proposed solution, as you said, had skipped the test cases. So we are not implementing the @tag as it might make us overlook the test cases which is skipped for other important reasons. We are really hoping to have this feature in the near future :)

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
@BChitrakannan How do you create test cases from the above JSON? Do you use parameterized test or have a custom test engine?

**Comment by Chitrakannan14** [comment]
I have a custom test engine. But this case would be applicable even when I use @MethodSource annotation

**Comment by marcphilipp** [comment]
Why would you need to add tags at runtime if you have a custom engine?

**Comment by maxim5** [comment]
A potential use case: add a tag from the an extension.
