### ISSUE TITLE
Create module API overview page

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2136]
Like can be seen at the [API of JDK 11](https://docs.oracle.com/en/java/javase/11/docs/api):

> ![image](https://user-images.githubusercontent.com/2319838/71244332-8b334d00-2312-11ea-965c-e421b70d0601.png)

`javadoc` supports creating a modular overview page. At the moment, we prevent that page from being created via `--no-module-directories`.

JUnit's overview page could look like:

```
| All Modules | Jupiter | Platform | Vintage |
+-------------+---------+----------+---------+---
| Module                  Description
+------------------------------------------------
| org.junit.jupiter       The aggregator module of the JUnit Jupiter API.
| org.junit.jupiter.api   JUnit Jupiter API for writing tests.
| ...
+------------------------------------------------
```

Might supersed #2056

## Deliverables

- [x] Drop `--no-module-directories` and get the overview page generated and uploaded.

**Comment by sormuras** [comment]
Sneak peek view

![image](https://user-images.githubusercontent.com/2319838/71289833-6ec4fe00-236e-11ea-865b-5f262cfe2336.png)

**Comment by marcphilipp** [comment]
Current (not working, yet) WIP is available on:
https://github.com/junit-team/junit5/tree/issues/2136-modular-javadoc

**Comment by marcphilipp** [comment]
I'm currently stuck with the following error:
```
import picocli.CommandLine;
       ^
  (package picocli is declared in module info.picocli, but module org.junit.platform.console does not read it)
```
(see https://scans.gradle.com/s/gll5xdtyptwi6/console-log?task=:documentation:aggregateJavadocs#L239-L242)

That happens even though I've added `--add-reads org.junit.platform.console=info.picocli` to the Javadoc options.

You can reproduce that locally by running `./gradlew aggregateJavadocs`. If you want to inspect the generated options file, see `documentation/build/tmp/aggregateJavadocs/javadoc.options`. You can even invoke Javadoc directly with it: `javadoc @documentation/build/tmp/aggregateJavadocs/javadoc.options`.

**Comment by sormuras** [comment]
🤔 ... the "shell-only" javadoc call doesn't throw that error.

Another note: https://github.com/junit-team/junit5/blob/98508171340cbe489184da38002cdd6f5d5003d1/junit-jupiter/src/module/org.junit.jupiter/module-info.java#L14 is not honored or ignored or ... what is good for anyway? Copied that annotation "blindly" from here

https://github.com/openjdk/jdk/blob/8a1b5ad914e5bb737ab8e2a2a919fac8bc1f023a/src/java.base/share/classes/module-info.java#L74

**Comment by sormuras** [comment]
Also adding `--add-modules info.picocli` helps.

Next error: 

```
...junit5\junit-platform-console\src\module\org.junit.platform.console\module-info.java:24: error: cannot find symbol
        provides java.util.spi.ToolProvider with org.junit.platform.console.ConsoleLauncherToolProvider;
                                                                           ^
  symbol:   class ConsoleLauncherToolProvider
  location: package org.junit.platform.console
```

MR-JAR fun. Needs some `--patch-module` love.

**Comment by sormuras** [comment]
Modular Javadoc is being generated in branch https://github.com/junit-team/junit5/compare/issues/2136-modular-javadoc

![image](https://user-images.githubusercontent.com/2319838/72431944-3c07fd00-3796-11ea-8423-96305f69a2d1.png)

Two modules are missing a description...

**Comment by sormuras** [comment]
Regarding the `@moduleGraph` I found the following links:
- https://bugs.openjdk.java.net/browse/JDK-8173303
- https://bugs.openjdk.java.net/browse/JDK-8176785
- https://bugs.openjdk.java.net/browse/JDK-8178132
- and https://stackoverflow.com/questions/59743180/module-info-javadoc-modulegraph

But I still don't see way how to generate those images _automagically_.

**Comment by sormuras** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8212233

**Comment by sormuras** [comment]
We should perhaps streamline the module descriptions similar to what the JDK uses: `Defines ... API.`

https://docs.oracle.com/en/java/javase/11/docs/api

**Comment by marcphilipp** [comment]
> Provides the implementation of the ... provider

Hmm.... 🤔

**Comment by sormuras** [comment]
PR #2155 is ready for a final review and polishing pass.
