### ISSUE TITLE
Append module name to default display name of classes

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2137]
When selecting multiple modules (e.g. via `--select-module a,b,c` within a console launcher run) users can't quickly infer from which module a test class (read: container) originates. By appending that information to the default display name its origin is presented in plain sight.

### Example

Without module names: 
![image](https://user-images.githubusercontent.com/2319838/71246243-925c5a00-2316-11ea-8cd3-0322c45df64a.png)

With module name prepended:
![image](https://user-images.githubusercontent.com/2319838/71246299-abfda180-2316-11ea-97e5-570aa5ac644d.png)

Implementation:
https://github.com/sormuras/junit5-looming/blob/master/src/test.base/test/java/test/base/PrependModuleName.java

## Questions

- [ ] What about package names?
- [ ] Is it better to generate logical nodes for container modules and packages -- like we do for classes and engines?

**Comment by marcphilipp** [comment]
**Team decision:** We consider the class name to be unique enough.
