### ISSUE TITLE
Introduce support for repeated tests

### ISSUE THREAD

**Issue by ttddyy** [junit-team/junit5#214]
## Overview

It would be great to have simple way of running same tests repeatedly **without changing test code**.

Currently, I'm working on async library and writing correct tests is very important.
All Tests passes most of the time but some fails time to time (which we have to fix).
We verify tests by running our test suites very often; our CI test job runs every 5min.

While writing/debugging test, it is very handy to have infrastructure that can repeatedly run same test over and over. For example, I would like to run single test method/class/suite 1000 times in local machine before checking in. In my case, I want result(summary) to be accumulated, but it may different by cases; aggregate all, repeat each result, or both.

If such feature is available, I foresee the integration with IDE, surefire, etc. Ideally, I can right click my IDE and specify N number to repeat, then run.

## Deliverables

- [x] Introduce support for repeated tests based on the test template infrastructure.
  - [x] Introduce a new `@RepeatedTest` annotation and related extension implementation.
  - [x] Introduce support for injecting information about the current repetition into a `@RepeatedTest`,
`@BeforeEach`, or `@AfterEach` method.
- [x] Document `@RepeatedTest` in the annotations section of the User Guide.
- [x] Introduce a new `Repeated Tests` section in the User Guide.
- [x] Introduce examples in the `documentation` module and include them in the User Guide.
- [x] Update the release notes accordingly.

**Comment by brsanthu** [comment]
Other feature related to this would be,

Ability to re-run the test (if they fail or continuously till user aborts it), automatically based on some annotation. For ex., we are in IDE trying to run all tests. If any tests fail, we want junit or a custom extension to provide a prompt asking to re-run. This is really helpful when we are working with dynamic class reloading tools like Spring reloading.

I think these are candidates for extensions so good support to build such extensions would be nice.

**Comment by sormuras** [comment]
Like https://www.jetbrains.com/help/idea/2016.3/rerunning-tests.html#rerun_failed_test ?

**Comment by brsanthu** [comment]
@sormuras that is re-running the test failed starting from scratch. If that is a integration test (think of spring boot with webenvironment set to random or fixed port), it will take a while to run those tests.

What I was hoping for something like, `@ExtendWith(LoopIfFailed.class)` and if so, if that test fails, it will prompt the user to fix the code and press a key, on which the just that test case (with its associated before test methods) are executed.

**Comment by nicolaiparlog** [comment]
Covered as #642.

**Comment by sbrannen** [comment]
@marcphilipp, if this feature request is fully covered by #642, could you please close this one and label it as superseded? 

Or shall we leave this issue open (or create a new one) to make sure there are examples of "repeated tests" in the User Guide?

**Comment by sbrannen** [comment]
FYI: I just pushed support for `@RepeatedTest` to a new branch: https://github.com/junit-team/junit5/commits/issues/214-repeated-test

Feedback is welcome! 😉

**Comment by sbrannen** [comment]
_in progress_ due to work on the aforementioned branch.

**Comment by sbrannen** [comment]
FYI: I have added a new _Deliverables_ section to this issue's description.

**Comment by sbrannen** [comment]
FYI: if you're interested in experimenting before M4 is released, I have already merged the support for `@RepeatedTest` into `master` in commit 2199096a62eb549bfb12c0be010324a2735f72e9. So you should be able to try it out in recent SNAPSHOT builds.

**Comment by sbrannen** [comment]
This issue has been addressed in the last several commits pushed to `master`.

In addition, the new functionality has been documented in the User Guide:

- http://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-repeated-tests
- http://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-repeated-tests-examples
