### ISSUE TITLE
More Concise Error Message In Tests

### ISSUE THREAD

**Issue by stevewhitmore** [junit-team/junit5#2141]
It would be really useful to be able to add an additional argument to the `@Test` annotation to assert an error was thrown with a certain message instead of instantiating a new class and then calling a method on it.

ExpectedException is an okay workaround but it would be much more concise as 

```java
@Test (expected = RuntimeException.class, message = "Employee ID is null")
public void shouldThrowRuntimeExceptionWhenEmployeeIDisNull() { ... }
```

as discussed here: https://stackoverflow.com/questions/2469911/how-do-i-assert-my-exception-message-with-junit-test-annotation

**Comment by sbrannen** [comment]
This issue tracker is for JUnit 5. The `@Test` annotation in JUnit Jupiter (part of JUnit 5) does not have any attributes.

If you would like to make a proposal for JUnit 4's `@Test` annotation, please open an issue in the [JUnit 4 issue tracker](https://github.com/junit-team/junit4/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
