### ISSUE TITLE
Difference between "Jupiter 5.5.2" and "Vintage 5.5.2"  ??

### ISSUE THREAD

**Issue by martijintro** [junit-team/junit5#2148]
Found here, what's the difference?
-> https://junit.org/junit5/

Thx for feedback.

Regards, Jan

**Comment by sormuras** [comment]
Consult the first section of the User Guide https://junit.org/junit5/docs/current/user-guide/#overview-what-is-junit-5

> JUnit **Jupiter** is the combination of the new programming model and extension model for writing tests and extensions in JUnit 5. The Jupiter sub-project provides a TestEngine for running Jupiter based tests on the platform.
> JUnit **Vintage** provides a TestEngine for running JUnit 3 and JUnit 4 based tests on the platform.

**Comment by sormuras** [comment]
This video explains your question in more detail: https://www.youtube.com/watch?v=oGaatK5ShUs

**Comment by martijintro** [comment]
ok thx
