### ISSUE TITLE
Bad version range in Import-Package

### ISSUE THREAD

**Issue by bjhargrave** [junit-team/junit5#2149]
## Steps to reproduce

The change https://github.com/junit-team/junit5/commit/aba6adbe591b7a5dd33e346f9b91a872e62d3322 lead to invalid version ranges in Import-Package statements. For example in `junit-platform-runner` we see `@4.12` instead of the desired `[4.12,5)`:

```
Import-Package
  org.junit.platform.commons.logging     {version=[1.6,2), status=INTERNAL}
  org.junit.platform.commons.util        {version=[1.6,2)}
  org.junit.platform.engine              {version=[1.6,2)}
  org.junit.platform.engine.discovery    {version=[1.6,2)}
  org.junit.platform.engine.reporting    {version=[1.6,2)}
  org.junit.platform.engine.support.descriptor {version=[1.6,2)}
  org.junit.platform.launcher            {version=[1.6,2)}
  org.junit.platform.launcher.core       {version=[1.6,2)}
  org.junit.platform.suite.api           {version=[1.6,2)}
  org.junit.runner                       {version=@4.12}
  org.junit.runner.manipulation          {version=@4.12}
  org.junit.runner.notification          {version=@4.12}

```

## Context

This occurs in the current master branch.

## Deliverables

The solution will be change change the versions in the build scripts from `version="@${Versions.junit4Min}"` to `version="[${Versions.junit4Min},5)"`.

**Comment by marcphilipp** [comment]
I took that syntax from https://bnd.bndtools.org/chapters/170-versioning.html. Is that not officially supported by OSGi?

**Comment by bjhargrave** [comment]
That syntax is a Bnd idiom (which is not working here which I will investigate for a fix to the next Bnd release) which Bnd should map to a proper version range. OSGi does not directly support those Bnd idioms.

So you can either directly code the upper limit to `5` since JUnit 4 should, by definition, not use the major version 5 since that belongs to JUnit 5. 

`version="[${Versions.junit4Min},5)"`

Or you can use the Bnd `range` macro to compute the upper limit 5:

`version="${'$'}{range;[==,+);${Versions.junit4Min}}"`

This uses `${'$'}` to stop Kotlin string interpolation from interpreting `${range` so that Bnd can process it as the `range` macro. https://bnd.bndtools.org/macros/range.html

There is also the question of why the resolve check did not catch this issue. @rotty3000 said he will investigate that.

**Comment by marcphilipp** [comment]
The first fix looks much more readable. Would you mind submitting that as a PR?

**Comment by rotty3000** [comment]
I'll work on the PR.

**Comment by marcphilipp** [comment]
@bjhargrave @rotty3000 Thanks again for reporting and fixing! Could you please test with a snapshot version once CI has published?

**Comment by marcphilipp** [comment]
Since the new test you added is green, I feel confident enough to release 5.6 GA without another feedback from your side. 🤞

**Comment by bjhargrave** [comment]
Sorry, I had taken a look at a snapshot jar in the sonatype snapshot repo and it looked good. I forgot to reply here...

**Comment by marcphilipp** [comment]
No worries, thanks for the feedback!
