### ISSUE TITLE
[junit-console] OS X terminal: ensure to restore default font color after running tests

### ISSUE THREAD

**Issue by bmalinowsky** [junit-team/junit5#215]
When executing `junit-console`, it sometimes happens (e.g., when the process is killed) that the standard font color is not restored after `junit-console` terminated.

A way to reproduce this behavior: if the current console output is painted a different color by `ColoredPrintingTestListener`, e.g., green, hitting `ctrl+c` will paint all subsequent lines also green.

**Comment by marcphilipp** [comment]
I'm not sure there is a reasonable way to ensure the default font color gets restored. We could try to add a shutdown hook but there is no guarantee that it gets executed.

If this is a recurring problem for you you can pass `-C` or `--disable-ansi-colors` to `ConsoleRunner`.

**Comment by marcphilipp** [comment]
@bmalinowsky Is this problem still relevant?

**Comment by bmalinowsky** [comment]
I tried it with `junit-platform-console-standalone-1.3.2.jar`, and it seems to always restore the color. So the problem is not really relevant anymore.

**Comment by sormuras** [comment]
Thanks for the heads up.
