### ISSUE TITLE
Support disabling cleanup for @TempDir

### ISSUE THREAD

**Issue by solter** [junit-team/junit5#2159]
When initially developing tests against legacy code that utilizes the filesystem extensively, I often find myself creating using `@TempDir`, which is fantastic. But oftentimes when debugging and/or initially writing the test I need to capture the outputs to get a "golden file" that I can regression test against on future runs. As such, currently I just use a non-TempDir folder to capture them, then need to update my test using TempDir later.

It would be super helpful if instead the TempDir annotation provided an option so that I could disable cleanup for a couple of runs then re-enable cleanup later in the development lifecycle. I'm envisioning something like the following

```java
@TempDir(cleanup=false)
private Path outputFolder;
```

**Comment by juliette-derancourt** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_

**Comment by leonard84** [comment]
I think a system property might be useful as well.

**Comment by marcphilipp** [comment]
**Team decision:** Let's add a "strategy-like" config parameter (similar to display name generator or method orderer) to configure in which cases temp dirs should be cleaned up with initial implementations of "always", "on_failure", and "never". This needs to be spec'ed out a bit more before work can actually be started.

**Comment by marcphilipp** [comment]
In addition, we could add a new class-level `@TempDirCleanupStrategy` or `@TempDirCleanupMode` annotation to configure it per class.

**Comment by marcphilipp** [comment]
@hglasgow Thanks for the PR! I think we should first discuss the new APIs here to avoid back and forth on the PR.

I think we should do the following:
* Introduce a new enum called `CleanupMode` in the `org.junit.jupiter.api.io` package with `ALWAYS`, `ON_SUCCESS`, and `NEVER` constants.
* Add a `cleanup` attribute to the `@TempDir` annotation with `ALWAYS` as its default.
* Add a `junit.jupiter.tempdir.cleanup.mode.default` configuration parameter

I'm not convinced we need a `@TempDirCleanupStrategy` or `@TempDirCleanupMode` annotation that I proposed above.

**Comment by hglasgow** [comment]
That sounds good. Then you could have a tag like @TempDir(cleanup = CleanupMode.ON_SUCCESS). That way you can specify the cleanup mode per directory.

**Comment by marcphilipp** [comment]
Yep, I think that would be the most discoverable API. Do you have time change your PR accordingly?

**Comment by hglasgow** [comment]
Yep, I'll work on it this week.

**Comment by delanym** [comment]
Do I need to modify all my @TempDir annotations or is there a global property I can set via surefire-plugin to set the default cleanup mode?

**Comment by delanym** [comment]
@sbrannen if a tempdir is created and left on disk, it would be nice to have its path in the build log.

I set my test to fail and added surefire config

```diff
+            <properties>
+              <configurationParameters>junit.jupiter.tempdir.cleanup.mode.default=NEVER</configurationParameters>
+            </properties>
```

The directories remain after the tests. But if I set it to **ON_SUCCESS** or **on_success** the directory is always removed.

**Comment by sbrannen** [comment]
> I set my test to fail and added surefire config
> 
> ```diff
> +            <properties>
> +              <configurationParameters>junit.jupiter.tempdir.cleanup.mode.default=NEVER</configurationParameters>
> +            </properties>
> ```
> 
> The directories remain after the tests. But if I set it to **ON_SUCCESS** or **on_success** the directory is always removed.

That sounds like the expected behavior (for successful tests).

Or are you stating something else?

> @sbrannen if a tempdir is created and left on disk, it would be nice to have its path in the build log.

That should already be the case:

https://github.com/junit-team/junit5/blob/8685a6a7dc7104cac43553a83da81b93e65b33b4/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L240-L244

Have you set the appropriate log category to `INFO`?

**Comment by sbrannen** [comment]
Thanks for the feedback, @delanym.

> Conclusion: on_success is not working. I tried setting all the tests to fail. It makes no difference.

Since _this_ issue is closed, please [open a new issue to report that bug](https://github.com/junit-team/junit5/issues/new?assignees=&labels=&template=bug_report.md).

> ```
>             <properties>
>               <configurationParameters>junit.jupiter.tempdir.cleanup.mode.default=on_success
>                 org.apache.logging.log4j.simplelog.StatusLogger.level=info</configurationParameters>
>             </properties>
> ```
> 
> Whether its always/never/on_success, I don't see any mention of the output directory in Maven's log, or in the <project.build.directory>/surefire-reports/* files.

With regard to the logging, you'll need to find out how to set the `org.junit.jupiter.engine.extension` (or `org.junit.jupiter.engine.extension.TempDirectory.CloseablePath`) category to `INFO`. Please refer to the documentation for your logging framework for details.
