### ISSUE TITLE
Module imports and exports

### ISSUE THREAD

**Issue by hwellmann** [junit-team/junit5#216]
Now that JUnit 5 has a modular structure, at least in the sense that it is delivered as a set of artifacts or libraries, it is time to think of package visibility between modules. This is a basic requirement of all potentially relevant module systems like JDK 9, OSGi or JBoss Modules.
- Is a given package supposed to be used by other modules?
- Should a package be regarded as internal to the given module?
- Does a module depend on packages from other modules?
- Should a package be split when it contains a mixture of exported and internal classes?

It might be useful to follow a naming convention, e.g. any package named  `*.internal.*` is internal.

**Comment by jlink** [comment]
Some of your concerns have been addressed by API annotations: http://junit.org/junit5/#api-annotations

We've explicitly decided against a package convention like "internal" since it requires to move classes if you promote or demote their API usage.

**Comment by marcphilipp** [comment]
Closing because covered by #1353 and #1091.
