### ISSUE TITLE
platform console standalone from cmd issue scan and noclassdeffounderror

### ISSUE THREAD

**Issue by finndesolace** [junit-team/junit5#2161]
Hi,
I'm trying to run my tests from command prompt with the platform console standalone 1.5.2.
I'm facing two issues:

1. scanning the project folder for the junit tests
2. noclassdeffounderror for library which is fetched through maven

-1
starting out from the project root directory, where the junit-platform-console-standalone-1.5.2.jar is located,  i tried:
java -jar junit-platform-console-standalone-1.5.2.jar -cp . --scan-classpath
which doesn't detect the junit jupiter 5.5.1 test called TestDummy
Only when using -cp C:\Users\<userID>\eclipse-workspace\Winium_test\target\test-classes -classpath , it runs my test.

-2
After reading @sormuras comment in https://stackoverflow.com/questions/54409727/junit5-consolelauncher-noclassdeffounderror

I tried 
-cp C:\Users\<userID>\eclipse-workspace\Winium_test\lib\jPowershell-3.3.1.jar:out -cp C:\Users\<userID>\eclipse-workspace\Winium_test\target\test-classes --scan-classpath

and 
-cp C:\Users\<userID>\eclipse-workspace\Winium_test\lib\jPowershell-3.3.1.jar:C:\Users\<userID>\eclipse-workspace\Winium_test\target\test-classes:out --scan-classpath

however, the first command still gives me the noclassdeffound error and the second one doesn't detect the junit test....  

I also added the library in a lib folder and the build path, instead of fetching it from maven.

Thanks for helping me out.

Directory output:
.
├── .classpath
├── .project
├── .settings
│   ├── org.eclipse.core.resources.prefs
│   ├── org.eclipse.jdt.core.prefs
│   └── org.eclipse.m2e.core.prefs
├── junit-platform-console-standalone-1.5.2.jar
├── lib
│   ├── jPowerShell-3.1.1-sources.jar
│   └── jPowerShell-3.1.1.jar
├── pom.xml
├── src
│   ├── main
│   │   ├── java
│   │   │   └── test
│   │   │       ├── Anyconnect.java
│   │   │       ├── TreeNode.java
│   │   │       ├── TreeNodeIter.java
│   │   │       └── winium_test.java
│   │   └── resources
│   └── test
│       ├── java
│       │   └── testcase
│       │       └── TestDummy.java
│       └── resources
└── target
    ├── classes
    │   ├── META-INF
    │   │   ├── MANIFEST.MF
    │   │   └── maven
    │   │       └── com.Winium_test
    │   │           └── Winium_test
    │   │               ├── pom.properties
    │   │               └── pom.xml
    │   └── test
    │       ├── Anyconnect.class
    │       ├── TreeNode.class
    │       ├── TreeNodeIter$ProcessStages.class
    │       ├── TreeNodeIter.class
    │       └── winium_test.class
    └── test-classes
        └── testcase
            └── TestDummy.class

**Comment by sormuras** [comment]
- Does `mvn test` work as expected from the command line?
- Is your source uploaded to public repository?

**Comment by finndesolace** [comment]
[TestProject_Anton_16022020.zip](https://github.com/junit-team/junit5/files/4107659/TestProject_Anton_16022020.zip)

@sormuras   
Thanks for your feedback!
Hi,
thanks about your remark for the path seperator.  However changing it did not do the trick.
I have attached the project archive file so you'd be able to take a look if so desired.
This is just a tryout project not following the academic rules.

As for mvn:
So i had to add the jdk in order to run the mvn test inside eclipse.

Although, i added the jpowershell dependency as library, but nog in the pom, it seems mvn is only aware of the dependencies in the pom.  So i had to put it there in order for mvn to find it and run my test.  

I think the mvn test alternative is maybe better suited than the junit platform standalone console.
Thanks for that.
I'll have to install maven outside eclipe in order to run from command line.

**Comment by marcphilipp** [comment]
@finndesolace You also need to add the main classes in `target/classes` to the classpath.
