### ISSUE TITLE
JUnit Jupiter 5.6.0 @Nested tests do not run when running tests in Maven Surefire and IntelliJ IDEA

### ISSUE THREAD

**Issue by koretzki** [junit-team/junit5#2162]
## Steps to reproduce

Pom.xml with Junit 5.6.0 and run with maven surefire plugin
example code (Kotlin)

```
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class NestedClassTest {
  @Nested
  inner class InnerClassTest1 {
    @Test
    fun innerClassTest1Case1() {
      println("InnerClass1 Test1 Case1")
    }
    @Test
    fun innerClassTest1Case2() {
      println("InnerClass1 Test1 Case2")
    }
    @Test
    fun innerClassTest1Case3() {
      println("InnerClass1 Test1 Case3")
    }
    @Test
    fun innerClassTest1Case4() {
      println("InnerClass1 Test1 Case4")
    }
  }
}
```
In maven, they are not in the report, where non-nested classes run ok. 
In IntelliJ IDEA when running the test class, it alerts to "No tests were found" 
In Jupiter 5.5.2 (and recent previous versions) the issue is not present: tests are running in both.
This may be related to https://github.com/junit-team/junit5/issues/1343

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.6.0, Platform: 1.60
 - Build Tool/IDE: Maven surefire plugin / IntelliJ IDEA

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
Do you experience the same behavior when using Java instead of Kotlin?

**Comment by sbrannen** [comment]
Also, please include the versions of Maven Surefire and IntelliJ IDEA that you are using.

**Comment by marcphilipp** [comment]
Works for me with our `junit5-jupiter-starter-maven-kotlin` project in IDEA 2020.1 EAP and Maven Surefire 2.22.2 and 3.0.0-M4.

**Comment by koretzki** [comment]
thank @marcphilipp,
I reset all the JUnit dependencies and used the one from junit5-jupiter-starter-maven-kotlin and this solved it. Look like I had a configuration issue in pom.xml file the worked until 5.5.2. I am closing the issue.

**Comment by sormuras** [comment]
Thanks for the feed-back, Ran.
