### ISSUE TITLE
Using the JUnit logo

### ISSUE THREAD

**Issue by Gyanesha** [junit-team/junit5#2165]
Hi,

I'm working on adding support for JUnit to a [Jenkins plugin](https://github.com/jenkinsci/warnings-ng-plugin) that allows you to inspect your code using different tools.
This Jenkins plugin has support to display an icon for the tool that's being used and I was wondering if we could use the JUnit logo from Github ([https://camo.githubusercontent.com/049cbfc3f4c820fe5aa0b376a703a975ab75181a/68747470733a2f2f6a756e69742e6f72672f6a756e6974352f6173736574732f696d672f6a756e6974352d6c6f676f2e706e67](https://camo.githubusercontent.com/049cbfc3f4c820fe5aa0b376a703a975ab75181a/68747470733a2f2f6a756e69742e6f72672f6a756e6974352f6173736574732f696d672f6a756e6974352d6c6f676f2e706e67)) for this purpose.

I'm asking this since I couldn't find any information regarding the license of the logo.
If it's not allowed to use the logo that's okay as I can simply leave it empty.

**Comment by sbrannen** [comment]
**Team Decision**: First and foremost, thank you for asking for permission.

The JUnit 5 team grants you permission to use the aforementioned logo for the Jenkins plugin.

**Comment by Gyanesha** [comment]
Ok, thanks for the permission!
