### ISSUE TITLE
Helpful error message when TestTemplateInvocationContextProvider provides an empty stream

### ISSUE THREAD

**Issue by t1** [junit-team/junit5#2166]
The javadoc of `TestTemplateInvocationContextProvider# provideTestTemplateInvocationContexts` says: "This method is only called by the framework if `#supportsTestTemplate` previously returned `true` for the same `ExtensionContext`. Thus, this method must not return an empty `Stream`."

But if an implementation fails to do so and actually returns a non-empty stream, the exception thrown is not very helpful: "org.junit.platform.commons.PreconditionViolationException: No supporting TestTemplateInvocationContextProvider provided an invocation context"

## Deliverables

One of these:
- `TestTemplateTestDescriptor#execute` checks the stream of all providers (instead of filtering on `isPresent`) and throws an error message like "<xxx> provided an empty stream" where `<xxx>` is the name of the provider (if we want to stick to the requirement that empty streams are forbidden).
- Change the javadoc of `TestTemplateInvocationContextProvider` to allow for empty streams; and `TestTemplateTestDescriptor#validateWasAtLeastInvokedOnce` throws with a message "None of the providers [...] has provided a non-empty stream" where `[...]` is the list of valid providers (if we want to stick to the current behavior of actually allowing empty streams).

I could work on a PR, if the decision about which way to go was made.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Let's go with option 2.

@t1 Would you still be interested in submitting a PR?

**Comment by t1** [comment]
@marcphilipp : I'll create a PR

**Comment by t1** [comment]
created https://github.com/junit-team/junit5/pull/2174
