### ISSUE TITLE
Allow @Testable on fields

### ISSUE THREAD

**Issue by rweisleder** [junit-team/junit5#2168]
## Background

Currently, it's only possible to annotate classes and methods with `@Testable` to indicate that those are testable.

In ArchUnit we have a custom engine to execute defined architecture rules as tests. The user has to annotate the elements with `@ArchTest`. The engine executes all rules that are annotated `@ArchTest`, no matter if they are methods or fields.

Example project: [archunit-example/example-junit5](https://github.com/TNG/ArchUnit/tree/v0.13.0/archunit-example/example-junit5)
Example test class: [CodingRulesTest](https://github.com/TNG/ArchUnit/blob/v0.13.0/archunit-example/example-junit5/src/test/java/com/tngtech/archunit/exampletest/junit5/CodingRulesTest.java)

When I open the mentioned test class in my IDE, the IDE only recognizes the class itself and the one method as testable. The fields are not recognized as testable.

## Suggestion

It should be possible to (meta)-annotate fields with `@Testable`. With this enhancement, IDEs have the chance to identify testable fields.

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
> It should be possible to (meta)-annotate fields with `@Testable`. With this enhancement, IDEs have the chance to identify testable fields.

It is already possible to meta-annotate fields with `@Testable`.

So, if an IDE doesn't find `@Testable` as a meta-annotation on fields, you would need to bring that up with the maintainers of the IDE.

As for allowing `@Testable` to be declared directly on a field, I don't see any problem with allowing that.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M1 for _team discussion_

**Comment by marcphilipp** [comment]
**Team decision:** Allow `@Testable` to be used on fields directly.

**Comment by marcphilipp** [comment]
LGTM! 👍
