### ISSUE TITLE
Expose JRE.CURRENT_VERSION for public access

### ISSUE THREAD

**Issue by filiphr** [junit-team/junit5#2176]
I've recently been fiddling with Junit Jupiter in order to migrate some of our custom Junit 4 runners into appropriate Jupiter extensions.

Due to different reasons we need to write custom `ExecutionCondition` which would enable or disable running of certain tests under different JREs. We can't use the `@DisabledOnJre` feature since we are using a `@TestTemplate` which based on the passed information would later on decide if it can execute the test on the current JRE.

In our case we are running some compiler tests with Eclipse JDT and Javac. When running under Java 11 we need to disable the Eclipse JDT tests. We are using a template since the same test is executed twice, once with Eclipse and once with Javac.

Current workaround is to do

```java
 static final JRE CURRENT_VERSION;

    static {
        JRE currentVersion = JRE.OTHER;
        for ( JRE jre : JRE.values() ) {
            if ( jre.isCurrentVersion() ) {
                currentVersion = jre;
                break;
            }
        }

        CURRENT_VERSION = currentVersion;
    }
```

However, it would be better if this can be provided by the `JRE` class itself. for example `JRE.currentVersion()`.

If the JUnit team is OK with such addition to the `JRE` API I can provide a PR for adding it

## Deliverables

- [ ] ...

**Comment by aepfli** [comment]
is checking a JRE version if it is the current one not enough? you are using already jre.isCurrentVersion  and it can be also used for this usecase. or am i missing something.

**Comment by filiphr** [comment]
My condition is similar to `EnabledForJreRange` and `DisabledForJreRange`. However, I can't use those since the template can be enabled for Java 11 for Javac, but disabled for Eclipse.

An example can be found here:

https://github.com/mapstruct/mapstruct/blob/a6b3cc364a7824a4584fdd690c82c6695447dd79/integrationtest/src/test/java/org/mapstruct/itest/testutil/extension/ProcessorEnabledOnJreCondition.java#L32-L36

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Let's add a `public JRE.currentVersion()` method.

**Comment by marcphilipp** [comment]
@filiphr Feel free to submit a PR for this issue. 🙂

**Comment by filiphr** [comment]
Thanks for agreeing to this. PR #2184 has been submitted 😄
