### ISSUE TITLE
Introduce mechanism to deactivate TestExecutionListeners

### ISSUE THREAD

**Issue by nishantvas** [junit-team/junit5#2181]
Currently, if any of the dependencies or transitive dependencies wishes to add a `TestExecutionListener`, it can do so by adding `org.junit.platform.launcher.TestExecutionListener` in `META-INF/services`.

However, sometimes, we need a dependency for the features it provides, but we do not want its `TestExecutionListener` to get registered.

Is it possible to have a similar construct like that of `junit.jupiter.conditions.deactivate` to be able to provide a pattern to disable or I suppose in this context de-register the listeners?

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_

**Comment by marcphilipp** [comment]
**Team decision:** Let's add a `junit.platform.execution.listeners.deactivate` config parameter that can be set to a comma-separated list of fully-qualified class names of `TestExecutionListener` implementations that should be deactivated. The names may be supplied as patterns where `*` is supported as a wildcard. The deactivation only applies to listeners registered via `ServiceLoader`, but not to listeners passed to the `Launcher` explicitly. Similarly, we should change `junit.jupiter.conditions.deactivate` to support multiple, comma-separated patterns.

**Comment by marcphilipp** [comment]
@nishantvas Would you be interested in submitting a PR for this?

**Comment by nishantvas** [comment]
@marcphilipp, sure. However, could you direct me towards what would be a good starting point ?
I've checked the `DefaultLauncher` in hope of doing this without having to change the service, but I wasn't able to identify where the Listeners are being registered via `ServiceLoader`

I can check further, but a pointer would help greatly.

`junit.jupiter.conditions.deactivate` I am aware of and can update it as per the decided approach.

**Comment by nishantvas** [comment]
I've submitted a pull request, I'm contributing to the project for the first time, so kindly let me know if there are more pre-requisites I need to cover

I'm unsure where I need to update the documentations as well unfortunately, so would need your support
