### ISSUE TITLE
Provide DynamicTestExecutor.executeSilently 

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#2188]
Spock 2.x provides data driven tests and decided to unroll (report every child) per default. However, users have requested to be able to get the old behavior, i.e., that a data-driven tests is only reported as a single one, since they'd get thousands of test entries.

For this we would need a new method on the `DynamicTestExecutor`, @marcphilipp suggested the name `executeSilently`. This method would take care of correctly executing the task, but I wouldn't report the individual executions to the platform listener (maybe `NoOpListener`).  Failures would need to be reported to the container/parent test in some way, so that they could be properly marked as failed.

Furthermore, since the test is marked as failed if any one child failed it would be nice to kill any pending executions.

## Deliverables

- [ ] `DynamicTestExecutor.executeSilently`
- [ ] cancel all pending child executions for a failed test
- [ ] communicate result to parent

**Comment by marcphilipp** [comment]
We could add an overload for `execute` that returns a `Future` (so you can cancel asynchronous executions) and takes an `EngineExecutionListener` as an additional argument.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Continue exploring this idea.
