### ISSUE TITLE
Clearly document that `name` attribute of `@ParameterizedTest` is a `MessageFormat` pattern

### ISSUE THREAD

**Issue by kec2** [junit-team/junit5#2192]
junit 5.5.2

## Steps to reproduce

@ValueSource(ints = { -1, 1 })
@ParameterizedTest(name = "don't message {0}")
void myTest(int value) {}

The pling in the name string courses the test name to be formatted wrong.
The result is "dont message {0}"

Removing the pling results in:
"dont message -1" and "dont message 1"

## Context

 - Used versions (Jupiter/Vintage/Platform):
 - Build Tool/IDE:

## Deliverables

- [ ] ...

**Comment by marcphilipp** [comment]
We should document this better: `name` is a `MessageFormat` pattern, i.e. you need to write `don''t message {0}`.

**Comment by sbrannen** [comment]
Note that we do actually have an example including single quotes in the `name` in the [User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-display-names), but it's not specifically documented.

**Comment by juliette-derancourt** [comment]
Done in c9e00df612857d55be043d4ae02026ddf5adc5b8.
