### ISSUE TITLE
Add support for printing test execution summary every X seconds

### ISSUE THREAD

**Issue by swaranga** [junit-team/junit5#2196]
When using JUnit for integration test that can have hundreds of test with long runtimes, it will be helpful if we can configure the current execution summary (number of tests pending, executed, failed, succeeded) so far. Ideally it should be the similar nice looking summary that is printed by the ConsoleTestExecutor

That can help developers get to the failing unit tests earlier rather than having to wait for the final summary or dive through the logs to figure out what tests failed.

The frequency at which the summary so far is printed should be configurable via a property.

**Comment by marcphilipp** [comment]
Build tools and IDEs typically already show the pending test cases, don't they? Thus, I'm not convinced such a listener would be generally useful. Please note that you could implement a custom `TestExecutionListener` and register it via the `ServiceLoader` mechanism.

**Comment by swaranga** [comment]
For unit tests which are typically run inside and IDE this is redundant. However I am talking about is when we run integration tests that may run for hours and in a remote machine then having a periodic summary printed in the console/logs would be very helpful.

I am aware that I can register my own listener but was wondering if you would consider this use case as a necessary part of the SummaryExecution listener provided by default mainly because it already collects all the information and keep it in a tree and has the logic of displaying it nicely formatted to the console.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by mmerdes** [comment]
Team decision: 
We do not feel that this feature should be included in the platform itself.
It should rather be implemented with a custom listener.

See https://github.com/junit-team/junit5/issues/2196#issuecomment-590838360
