### ISSUE TITLE
JUnit4VersionCheck fails on a version string "4.12.0.redhat-003"

### ISSUE THREAD

**Issue by rsynek** [junit-team/junit5#2198]
junit-vintage-engine does not recognize junit4 built under a version "4.12.0.redhat-003" and fails fast in JUnit4VersionCheck [1].

## Steps to reproduce
1. In a maven project, include junit of version "4.12.0.redhat-003" on classpath together with junit-vintage-engine as test dependencies. 
2. mvn test -> as a result, no tests are run

Additional information: based on maven-surefire-plugin version, either no hint is given at all (surefire version 2.22.1) or a stacktrace (2.22.2 and above) is provided, clearly leading to [1].

## Context

 - Used versions (Jupiter/Vintage/Platform):
5.5.2
 - Build Tool/IDE:
maven

## Deliverables

Expected: parse the aforementioned version string, discover the junit4 engine on classpath and run tests.

[1] https://github.com/junit-team/junit5/blob/master/junit-vintage-engine/src/main/java/org/junit/vintage/engine/JUnit4VersionCheck.java#L54

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M1 for _team discussion_

**Comment by sbrannen** [comment]
**Team Decision**: Make the version parsing in `JUnit4VersionCheck` more lenient.
