### ISSUE TITLE
Update link to AssertJ API documentation

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2200]
This link https://joel-costigliola.github.io/assertj/core-8/api points to the wrong (out of date) version:

https://github.com/junit-team/junit5/blob/9db860622517e077f2dbc21c34d585e170b19159/documentation/documentation.gradle.kts#L84

Correct target: https://javadoc.io/doc/org.assertj/assertj-core/3.14.0

The version in the link must match the one defined in `Versions.kt`:

https://github.com/junit-team/junit5/blob/9db860622517e077f2dbc21c34d585e170b19159/buildSrc/src/main/kotlin/Versions.kt#L17

**Comment by marcphilipp** [comment]
So it should be `https://www.javadoc.io/doc/org.assertj/assertj-core/${Versions.assertJ}/index.html`, right?

**Comment by sormuras** [comment]
With #2236 being merged, it'll read: `https://javadoc.io/doc/org.assertj/assertj-core/$versions.assertj`

**Comment by sormuras** [comment]
Linking didn't work out: https://junit.org/junit5/docs/snapshot/api/org.junit.platform.testkit/org/junit/platform/testkit/engine/EventConditions.html

![image](https://user-images.githubusercontent.com/2319838/78459554-1cf47980-76ba-11ea-96b5-b81893842286.png)

**Comment by sormuras** [comment]
When adding the missing `/` at the end of new URL, our `--link-offline` work-around fails with:

```
Execution failed for task ':documentation:downloadJavadocElementLists'.
> Could not get resource 'https://javadoc.io/doc/org.assertj/assertj-core/3.14.0/package-list'.
   > Could not GET 'https://javadoc.io/doc/org.assertj/assertj-core/3.14.0/package-list'. Received status code 403 from server: Forbidden
```

**Comment by sormuras** [comment]
https://javadoc.io/doc/org.assertj/assertj-core/3.14.0/element-list works though:

```
org.assertj.core.annotations
org.assertj.core.api
org.assertj.core.api.exception
org.assertj.core.api.filter
org.assertj.core.api.iterable
org.assertj.core.api.junit.jupiter
org.assertj.core.api.recursive.comparison
org.assertj.core.condition
org.assertj.core.configuration
org.assertj.core.data
org.assertj.core.description
org.assertj.core.error
org.assertj.core.error.future
org.assertj.core.error.uri
org.assertj.core.extractor
org.assertj.core.groups
org.assertj.core.internal
org.assertj.core.matcher
org.assertj.core.presentation
org.assertj.core.util
org.assertj.core.util.diff
org.assertj.core.util.diff.myers
org.assertj.core.util.introspection
org.assertj.core.util.xml
```

@marcphilipp what are doing wrong here?

https://github.com/junit-team/junit5/blob/407a29f642b2ef8d2f5bf2ba028ce5d6dfd5d14a/documentation/documentation.gradle.kts#L201-L217

**Comment by sormuras** [comment]
A fix for Java 15 is in progress: https://bugs.openjdk.java.net/browse/JDK-8240169

**Comment by sormuras** [comment]
FYI: https://hg.openjdk.java.net/jdk/jdk/rev/3b557aef43c4 -- should land in next 15-ea build.
