### ISSUE TITLE
Upgrade to bnd 5.0.0

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#2203]
@rotty3000 I'm a bit confused: there seems to have been a 5.0.0 release of bndtools (congrats BTW!), but the Gradle plugin portal still lists a 4.3.x version. Can we already upgrade or is there still an issue with publishing to the Gradle plugin portal?

## Deliverables

- [ ] Remove custom `APIGuardianAnnotations` bnd plugin and switch to official one

**Comment by rotty3000** [comment]
There is a 5.0.0 bnd gradle, plugin. But since gradle didn't support us with a fix for an issue on gradle plugin portal we released it only to maven central (and jcenter). I can do the change for you monday as I promised when adding this support :)

**Comment by marcphilipp** [comment]
Sounds good! In the meantime, I've taken a stab at fixing the Plugin Portal issue at https://github.com/bndtools/bnd/pull/3811.

**Comment by bjhargrave** [comment]
The 5.0.0 version of the Bnd Gradle plugin is now available from the Gradle Plugin Portal thanks to the fix from @marcphilipp.
