### ISSUE TITLE
Provide a definition of "container" in the User Guide

### ISSUE THREAD

**Issue by vinogradoff** [junit-team/junit5#2205]
The word `container` is used more than 50 times in the current Guide https://junit.org/junit5/docs/current/user-guide/

This term wasn't used in JUnit4 and is new to many JUnit users. In the development industry we have just too many different containers to leave this to "common sense" understanding.

Please just add the definition of JUnit5 "container" in the User Guide.

**Comment by sormuras** [comment]
Agreed, we should define the word in the User Guide.

Related question on SO (by @vinogradoff, I guess): https://stackoverflow.com/questions/60507366/what-is-a-container-in-junit-5

**Comment by jbduncan** [comment]
This sounds like this would be useful to document still.

**Comment by Sowtch** [comment]
Hello, I am interested in contributing to this issue. 
His it still avaible ? :)

**Comment by sbrannen** [comment]
@Sowtch, yes this issue is still open.

**Comment by Sowtch** [comment]
Ok thank you for your answer, I'll take care of it then.

**Comment by CorentinDelrue** [comment]
I hope this little doc update done with @Sowtch will be satisfying :)
