### ISSUE TITLE
Provide a utility class which allows to create TempDir programmatically in code.

### ISSUE THREAD

**Issue by mielecmichal** [junit-team/junit5#2208]
Please provide a utility class which allows me to create TempDir programmatically. 

I am working on a file system watching library. All my tests operates on a directory created by ```@TempDir``` extension. I mostly create some scenarios in which I create/modify some files. My scenarios started to complicate when I tried to cover symlink to different temp directory. 

For now I decided to use JDK API directly:
```Path secondDirectory = Files.createTempDirectory(name);```

Utility method like bellow would be very useful in situations like mine:
```Path secondDirectory = TempDir.create();```

## Deliverables

- TempDir utility class which creates a directory consistently with ```@TempDir``` annotation. Perfectly being aware about test context and clean the directory at the end of the test if possible.

**Comment by sormuras** [comment]
Why is (Files.createTempDirectory)[https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempDirectory-java.nio.file.Path-java.lang.String-java.nio.file.attribute.FileAttribute...-] not suitable?

**Comment by sormuras** [comment]
Or, create two (or more) directories in the one provided by `@TempDir`.

**Comment by mielecmichal** [comment]
Regarding ```Files::createTempDirectory```:
 - I need to care about the cleanup
 - When there will be some improvement in future TempDir it wont work for me.

Regarding 2 directories, that's an option I can do like that. You are right, but sometimes it may require to significantly change the tests structure.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** We think the current `@TempDir` support is sufficient. Please follow the advice stated in https://github.com/junit-team/junit5/issues/2208#issuecomment-596089294.
