### ISSUE TITLE
Allow @TempDir to specify sub-directories

### ISSUE THREAD

**Issue by kalgon** [junit-team/junit5#2218]
When using `@TempDir`, I often need to partition my temp directory into multiple sub-directories like "input", "output", "errors", ".camel", etc.

So, would it be possible to add an attribute on `@TempDir` to specify sub-directories.

This would allow me to do something like:

```java
@Test
public void test(@TempDir("input") Path input, @TempDir("output") Path output) {
	// test
}
```

instead of:

```java
@Test
public void test(@TempDir Path root) {
	Path input = Files.createDirectories(root.resolve("input"));
	Path output = Files.createDirectories(root.resolve("output"));
	// test
}
```

WDYT?

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_

**Comment by sbrannen** [comment]
If we were to introduce support for automatic creation of named subdirectories, I think we would need to pick an explicit name for the attribute instead of `value`, since we may at some point introduced support for _named_ temporary directories.

Speaking of which, isn't this request effectively a duplicate of #1967?

**Comment by sormuras** [comment]
> Speaking of which, isn't this request effectively a duplicate of #1967?

Yes.

**Comment by sormuras** [comment]
And I'm still fine with only providing a single temporary directory. If you need multiple ones, create sub folders. If you need a special cleanup strategy, create and delete sub folders...

**Comment by kalgon** [comment]
You are right, I may have misspelled "TmpDir" (instead of "TempDir") when I searched for issues and didn't find it. Sorry about that.

**Comment by sbrannen** [comment]
> You are right, I may have misspelled "TmpDir" (instead of "TempDir") when I searched for issues and didn't find it. 

Yes, I assume so, since you also spelled it "TmpDir" in the title and description of this issue (which I edited for you). 😉 

> Sorry about that.

No worries.
