### ISSUE TITLE
Broken Link in User Guide, Example Projects

### ISSUE THREAD

**Issue by broeser** [junit-team/junit5#2222]
This affects the current User Guide linked from the website (junit.org/junit5)

## Steps to reproduce

- Click on any of the links in the section 1.4.3 (Example Projects)
- A 404 error will be the result

**Comment by sormuras** [comment]
Thanks for reporting the issue.

- The `snapshot` version of the User Guide is not affected. See https://junit.org/junit5/docs/snapshot/user-guide/#overview-getting-started-example-projects
- The `current` version contains `r5.0.0` path elements: https://github.com/junit-team/junit5-samples/tree/r5.0.0/junit5-jupiter-starter-ant
- Those version elements should read `r5.6.1`.

**Comment by sbrannen** [comment]
I assume that happened because the example command in the [Releasing](https://github.com/junit-team/junit5/wiki/Releasing) page was used verbatim.

> * Generate and upload docs
>    * For GA releases: `./gradlew --no-build-cache -PreleaseBranch=r5.0.0 -PreplaceCurrentDocs clean gitPublishPush`

**Comment by sbrannen** [comment]
Based on the above analysis, it becomes clear that the following links to actual code are pointing to the wrong versions as well.

```
:DisabledCondition:                          {current-branch}/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/DisabledCondition.java[DisabledCondition]
:RepetitionInfoParameterResolver:            {current-branch}/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/RepetitionInfoParameterResolver.java[RepetitionInfoParameterResolver]
:TempDirectory:                              {current-branch}/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java[TempDirectory]
:TestInfoParameterResolver:                  {current-branch}/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TestInfoParameterResolver.java[TestInfoParameterResolver]
:TestReporterParameterResolver:              {current-branch}/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TestReporterParameterResolver.java[TestReporterParameterResolver]
:TypeBasedParameterResolver:                 {current-branch}/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/support/TypeBasedParameterResolver.java[TypeBasedParameterResolver]
// Jupiter Examples
:CustomAnnotationParameterResolver:          {current-branch}/junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/injection/sample/CustomAnnotationParameterResolver.java[CustomAnnotationParameterResolver]
:CustomTypeParameterResolver:                {current-branch}/junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/injection/sample/CustomTypeParameterResolver.java[CustomTypeParameterResolver]
:MapOfListsTypeBasedParameterResolver:       {current-branch}/junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/injection/sample/MapOfListsTypeBasedParameterResolver.java[MapOfListsTypeBasedParameterResolver]
```

**Comment by sbrannen** [comment]
@marcphilipp has already made the necessary changes and pushed the documentation.

Bot the `current` and `5.6.1` versions of the user guide are now correct.
