### ISSUE TITLE
Ability to capture any exception raised during test execution

### ISSUE THREAD

**Issue by vmassol** [junit-team/junit5#2224]
Hi,

I'd like to implement a JUnit5 extension that would capture any exception raised during test execution,  including exceptions raised in other Extensions. My goal is to help in debugging integration and functional tests when they fail by displaying environmental information in the CI. For example to execute:

```
        if (System.getenv("JENKINS_HOME") != null || Boolean.parseBoolean(System.getProperty("inCI"))) {
            LOGGER.info("Environment information to help debug the failing test:");
            LOGGER.info(RuntimeUtils.run("top -b -n 1"));
            LOGGER.info(RuntimeUtils.run("lsof -i -P -n "));
            LOGGER.info(RuntimeUtils.run("docker ps -a"));
            LOGGER.info(RuntimeUtils.run("docker events --since '15m' --until '0m'"));
        }
```

I first tried writing an extension implementing `TestExecutionExceptionHandler` to find that it'll only trigger inside a `@Test`(see https://github.com/junit-team/junit5/blob/86277defc09e76e37de7c053461346b1881adf4b/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java#L217).

I then checked the code and found that https://github.com/junit-team/junit5/blob/29aedcd74487f083cf97b0d37206c0d78fc77f6e/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java#L131 shows that it's currently not possible to have an extension catching any raised exception since https://github.com/junit-team/junit5/blob/29aedcd74487f083cf97b0d37206c0d78fc77f6e/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java#L149 will raise any collected exception.

It would be nice to be able to write an extension implementing some interface and have `throwableCollector.assertEmpty()` call these extensions before it raises the exception. That would allow me to implement my use case above.

WDYT?

Thanks!

**Comment by vmassol** [comment]
hmm I think I'm wrong. Reading the code more closely I see that this is caught at a higher level, in https://github.com/junit-team/junit5/blob/3f7fed61f2edcee2a5551dbde75382b1dbe21267/junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTestTask.java#L154 and I see that I could have a `EngineExecutionListener`. Will try this and report here and close the issue if it works.

**Comment by vmassol** [comment]
The only potential issue is that I didn't do this initially since I couldn't see how to register an `EngineExecutionListener` automatically in Maven Surefire/FailSafe.

**Comment by sbrannen** [comment]
It's not possible to register an `EngineExecutionListener` of your own.

That's an internal implementation detail of `org.junit.platform.launcher.core.DefaultLauncher.execute(InternalTestPlan, TestExecutionListener[])`.

**Comment by vmassol** [comment]
@sbrannen thanks. It's working with a `TestExecutionListener` (which can be registered automatically using the service loader mechanism). Closing the issue!
