### ISSUE TITLE
Upgrade versions of 3rd-party libraries

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2226]
## Status

https://github.com/junit-team/junit5/blob/2f6f5d8607177ca889ffc9d6c6528a81667ecf79/buildSrc/src/main/kotlin/Versions.kt#L7-L13

https://github.com/junit-team/junit5/blob/2f6f5d8607177ca889ffc9d6c6528a81667ecf79/buildSrc/src/main/kotlin/Versions.kt#L15-L25

https://github.com/junit-team/junit5/blob/2f6f5d8607177ca889ffc9d6c6528a81667ecf79/buildSrc/src/main/kotlin/Versions.kt#L27-L33

## Deliverables

- [x] [Picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0)
- [x] AssertJ 3.16.0 + move to "Dependencies" section -- **not** 3.15.0 doesn't play nice on the module path. #2170 
- [x] [ArchUnit 0.13.1](https://github.com/TNG/ArchUnit/releases/tag/v0.13.1)
- [x] [ClassGraph 4.8.65](https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.65)
- [x] [Groovy 3.0.2](https://github.com/apache/groovy/releases/tag/GROOVY_3_0_2)
- [x] [Log4j 2.13.1](https://logging.apache.org/log4j/2.x/changes-report.html#a2.13.1)
- ❌ [Mockito 3.3.6](https://github.com/mockito/mockito/releases/tag/v3.3.6) -- only 3.3.3 is on Maven Central
- [x] [Checkstyle 8.31](https://checkstyle.org/releasenotes.html#Release_8.30)
- [x] [JMH 1.23](https://github.com/openjdk/jmh/releases/tag/1.23)

**Comment by sbrannen** [comment]
Deliverables achieved.

**Comment by juliette-derancourt** [comment]
Mockito pushed a new version to maven central, upgraded via #2356
