### ISSUE TITLE
Tests count is 1 if there is  failure in @BeforeAll setup method

### ISSUE THREAD

**Issue by ksiddu** [junit-team/junit5#2231]
Junit 5.6.0
maven-surefire-plugin --> 2.22.0

## Steps to reproduce

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class MultipleTests {

	@BeforeAll
	public static void beforeAll() {

		System.out.println("beforeAllFirstTest() executed!");

		assertTrue(false);

	}

	@Test
	public void testMethod1() {
		System.out.println("testMethod1() executed!");
	}

	@Test
	public void testMethod2() {
		System.out.println("testMethod2() executed!");
	}

	@AfterEach
	public void tearDown(TestInfo testInfo) throws Exception {
		System.out.println("tearDown executed!");
		System.out.println("<-- tearDown executed!" +" --> " +testInfo.getDisplayName());
		
		
	}

	@AfterAll
	public static void afterAll() {

		System.out.println("afterAllFirstTest() executed!");
		

	}

Actual Result:
 -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.siddu.cases.group.MultipleTests
beforeAllFirstTest() executed!
afterAllFirstTest() executed!
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.031 s <<< FAILURE! - in org.siddu.cases.group.MultipleTests
[ERROR] org.siddu.cases.group.MultipleTests  Time elapsed: 0.03 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
 	at org.siddu.cases.group.MultipleTests.beforeAll(MultipleTests.java:21)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MultipleTests.beforeAll:21 expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.

With this test count issue, in Jenkins we are getting variations in the total count on each run.
We can mark the tests inside the class container as failed or skipped.
Expected Result: 
1. [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0
OR
2. [SKIPPED] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2

**Comment by sormuras** [comment]
The result line `Tests run: R, Failures: F, Errors: E, Skipped: S` is generated by Surefire.

Please find a similar issue or open a new issue at https://issues.apache.org/jira/projects/SUREFIRE
