### ISSUE TITLE
Usage of junit5 testsuite

### ISSUE THREAD

**Issue by objectBoolean** [junit-team/junit5#2232]
Does junit5 not have the functionality of testsuite in junit4?
Include testsuite within testsuite
Running parameterized test cases with @runwith (junit platform.class) results in errors in intellij idea reports. I want the functionality of testsuite in junit4

**Comment by sormuras** [comment]
> Does junit5 not have the functionality of testsuite in junit4?

Yes. Is does not. See #330 and linked issues for details.
