### ISSUE TITLE
Consider moving dependency versions to gradle.properties (and remove Versions from buildSrc)

### ISSUE THREAD

**Issue by vlsi** [junit-team/junit5#2234]
I see you've moved the versions to dependency constraints (which I think is nice), however, it looks like there's no point in having `Versions` in `buildSrc`.

The problems with `Versions` object are:
1) Every time `Versions` is updated the whole thing is rebuilt
2) The only option to try a new version is to edit the build scripts.

What do you think if the versions are moved to `gradle.properties` instead?
For instance:

gradle.properties:
```properties
apiguardian-api.version=1.1.0
picocli.version=4.2.0
...
```

Then dependency constraints can be created as follows:

```kotlin
val String.v: String get() = rootProject.extra["$this.version"] as String

fun DependencyConstraintHandlerScope.apiv(
    notation: String,
    versionProp: String = notation.substringAfterLast(':')
) =
    "api"(notation + ":" + versionProp.v)

dependencies {
    (constraints) {
        apiv("org.apiguardian:apiguardian-api")
        apiv("info.picocli:picocli")
        ...
    }
}
...
```

It would
1) Consolidate the versions in `gradle.properties`
2) Enable testing with newer versions via `-Ppicocli.version=5.0.0`
3) Avoid recompilation when `Versions` is updated

**Comment by marcphilipp** [comment]
One of the main benefits of `Versions` is that it allows to pick from a set of defined versions in build scripts and you can search for references to find out where a given version is used. However, I think we change it so that it is backed by project properties, e.g. by adding a Kotlin extension function with lazily initialized properties that read from the project properties.

@vlsi Would you be interested in giving that a try?

**Comment by vlsi** [comment]
> One of the main benefits of Versions is that it allows to pick from a set of defined versions in build scripts and you can search for references to find out where a given version is used

In practice, build script needs group id and artifact id as well, so having just version brings very little value from my point of view.

Then, using regular "group:artifact" helps to understand what is the dependency (== the format is the same as on the official guides).

I think I can prepare a PR that removes `Version`.
