### ISSUE TITLE
Kotlin style: official or not?

### ISSUE THREAD

**Issue by vlsi** [junit-team/junit5#2237]
I see you often use `tabs` for Kotlin code which looks weird in GitHub diffs.

Is it accidental or a deliberate choice?

Kotlin official style guide suggests using 4 spaces for indentation: https://kotlinlang.org/docs/reference/coding-conventions.html#formatting

**Comment by sormuras** [comment]
Is there a non-configurable Kotlin formatter that emits officially styled code? Something similar to https://github.com/google/google-java-format

**Comment by vlsi** [comment]
https://github.com/pinterest/ktlint is OK.
There's a glitch with import order formatting, however, in general, it formats great.

Note: `tabs` vs `spaces` should probably be configured via `.editorconfig`.

**Comment by sormuras** [comment]
> https://github.com/pinterest/ktlint is OK.

Do you mind perparing a PR with ktlint applied for further discussion?

> Note: tabs vs spaces should probably be configured via .editorconfig.

#2057

**Comment by vlsi** [comment]
I've seen #2057, however, it says nothing regarding `indent_style` for `kt` and `kts` files.

So the key question here is what are you expectations regarding the style.

**Comment by marcphilipp** [comment]
IIRC we already use ktlint via Spotless.

**Comment by marcphilipp** [comment]
The reason for using tabs is consistency with the rest of the (Java) codebase.

**Comment by vlsi** [comment]
> The reason for using tabs is consistency with the rest of the (Java) codebase.

Just an example: `*.md`  has a special notion for `trailing whitespace`, so `*.md` should not use `trim trailing whitespace` rule.

So I guess it might be OK to have spaces for Kotlin code.

**Comment by marcphilipp** [comment]
> Just an example: `*.md` has a special notion for `trailing whitespace`, so `*.md` should not use `trim trailing whitespace` rule.

Well, GitHub-flavored Markdown does not... 😉 

> So I guess it might be OK to have spaces for Kotlin code.

We'll discuss it in the next team call.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** We'd rather have our own codebase consistent than follow the official Kotlin style. Kase klosed.
