### ISSUE TITLE
assertTimeoutPreemptively should provide reference to future or executor service parameter

### ISSUE THREAD

**Issue by doctorpangloss** [junit-team/junit5#2239]
## Overview

The stack trace of the `future` used for `assertTimeoutPreemptively` provides valuable information for where a test thread gets "stuck" and is itself valuable for assertions.

## Proposal

Provide a reference to the `future` used to execute the code under test. This way, users can see, in their errors, where the code hung. Or, users can assert that, e.g., a blocking method correctly blocked.

A robust way to do this, supporting whatever functionality users may want, would be to add a `assertTimeoutPreemptively` overload that accepts an `ExecutorService`. There, users can provide a `ThreadedPoolExecutor` with a `newTaskFor` overload.

Alternatively, the `ExecutorService` can be provided by a `@Rule` (?) But I'm not too familiar with the big picture configuration for JUnit5.

JUnit5 doesn't seem to use custom exceptions, not does it pass information about the assertion failure to callbacks. This seems to be the most flexible way to provide a look into the timeout that future library authors can use without changing conventions.

## Deliverables

 - [ ] A new signature for `assertTimeoutPreemptively`:

```java
public static <T> T assertTimeoutPreemptively(Duration timeout, ThrowingSupplier<T> supplier, Object messageOrSupplier, ExecutorService executorService)
```

## Workaround

Copy and paste the implementation out of JUnit and modify it to print the failed thread's stack trace:

```java
static <T> T assertTimeoutPreemptively(Duration timeout, ThrowingSupplier<T> supplier,
	                                              Object messageOrSupplier) {

		var thread = new AtomicReference<Thread>();
		var factory = new ThreadFactory() {
			@Override
			public Thread newThread(@NotNull Runnable r) {
				thread.set(new Thread(r));
				return thread.get();
			}
		};

		ExecutorService executorService = Executors.newSingleThreadExecutor(factory);

		try {
			Future<T> future = executorService.submit(() -> {
				try {
					return supplier.get();
				} catch (Throwable throwable) {
					throw ExceptionUtils.throwAsUncheckedException(throwable);
				}
			});

			long timeoutInMillis = timeout.toMillis();
			try {
				return future.get(timeoutInMillis, TimeUnit.MILLISECONDS);
			} catch (TimeoutException ex) {
				ex.setStackTrace(thread.get().getStackTrace());
				throw new AssertionFailedError(buildPrefix(nullSafeGet(messageOrSupplier))
						+ "execution timed out after " + timeoutInMillis + " ms\ntask stacktrace:\n" + Throwables.getStackTraceAsString(ex));
			} catch (ExecutionException ex) {
				throw ExceptionUtils.throwAsUncheckedException(ex.getCause());
			} catch (Throwable ex) {
				throw ExceptionUtils.throwAsUncheckedException(ex);
			}
		} finally {
			executorService.shutdownNow();
		}
	}
```

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M1 sole for the purpose of _team discussion_

**Comment by marcphilipp** [comment]
**Team decision:** Investigate a solution similar to the workaround posted above that would report the stacktrace as part of the assertion error in some way (e.g. using a special exception with the stacktrace of the stuck thread as its cause).

**Comment by hisener** [comment]
I want to give it a try.
