### ISSUE TITLE
TestExecutionListener,  Test that failed while parameterizing the test, gets the result “SUCCESSFUL” 

### ISSUE THREAD

**Issue by houseshi** [junit-team/junit5#2247]
## java test code

```java

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;


public class test {
    @ParameterizedTest
    @MethodSource("userGenerator")
    void testFail1(String name,String pw) {
        Assertions.assertEquals(name,pw);
    }
    public static Stream<Arguments> userGenerator(){
        return Stream.of(Arguments.of("15138493452", "hlf2016"));
    }
}
```

```java
public class TestListener implements TestExecutionListener {
  /*
    *   ... ...
    */

public void executionFinished(TestIdentifier testIdentifier, TestExecutionResult testExecutionResult) {


}
   if ("SUCCESSFUL".equals(testExecutionResult.getStatus().name())) {

         /* testExecutionResult.getStatus().name() = "SUCCESSFUL"
           *
           * Expected : FAILURES
           */  
}

}
```

## bug screenshots

![image](https://user-images.githubusercontent.com/2319838/78626999-a6f63b00-7890-11ea-89b4-10c6cda1a65a.png)

**Comment by sormuras** [comment]
I fixed the inlined screenshot in the initial description.

Please translate the title into English. And what is your question?

**Comment by houseshi** [comment]
> I fixed the inlined screenshot in the initial description.
> 
> Please translate the title into English. And what is your question?

TestExecutionListener, Test that failed while parameterizing the test, gets the result “SUCCESSFUL”，Expected : FAILURES

**Comment by sormuras** [comment]
Are you expecting that the parent container of a failing test should be marked as `FAILED`?

**Comment by sbrannen** [comment]
Given the following simplified version of your example...

```java
package example;

import java.util.stream.Stream;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

public class Tests {

	@ParameterizedTest
	@MethodSource("userGenerator")
	void testFail1(String name, String pw) {
		Assertions.assertEquals(name, pw);
	}

	static Stream<Arguments> userGenerator() {
		return Stream.of(Arguments.of("15138493452", "hlf2016"));
	}
}
```

```java
package example;

import static org.junit.platform.engine.discovery.DiscoverySelectors.selectClass;

import java.io.PrintWriter;

import org.junit.platform.engine.TestExecutionResult;
import org.junit.platform.engine.TestExecutionResult.Status;
import org.junit.platform.launcher.Launcher;
import org.junit.platform.launcher.LauncherDiscoveryRequest;
import org.junit.platform.launcher.TestExecutionListener;
import org.junit.platform.launcher.TestIdentifier;
import org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder;
import org.junit.platform.launcher.core.LauncherFactory;
import org.junit.platform.launcher.listeners.SummaryGeneratingListener;
import org.junit.platform.launcher.listeners.TestExecutionSummary;

public class Tester {

	public static void main(String[] args) {
		LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request().selectors(
			selectClass(Tests.class)).build();

		Launcher launcher = LauncherFactory.create();

		SummaryGeneratingListener listener = new SummaryGeneratingListener();
		launcher.registerTestExecutionListeners(listener, new TestListener());

		launcher.execute(request);

		TestExecutionSummary summary = listener.getSummary();
		summary.printTo(new PrintWriter(System.err));
	}

	static class TestListener implements TestExecutionListener {

		@Override
		public void executionFinished(TestIdentifier testIdentifier, TestExecutionResult testExecutionResult) {
			if (testExecutionResult.getStatus() == Status.FAILED) {
				System.err.println(">>>> " + testIdentifier);
			}
		}
	}

}
```

Executing that yields:

```
>>>> TestIdentifier [uniqueId = '[engine:junit-jupiter]/[class:example.Tests]/[test-template:testFail1(java.lang.String, java.lang.String)]/[test-template-invocation:#1]', parentId = '[engine:junit-jupiter]/[class:example.Tests]/[test-template:testFail1(java.lang.String, java.lang.String)]', displayName = '[1] name=15138493452, pw=hlf2016', legacyReportingName = 'testFail1(String, String)[1]', source = MethodSource [className = 'example.Tests', methodName = 'testFail1', methodParameterTypes = 'java.lang.String, java.lang.String'], tags = [], type = TEST]

Test run finished after 108 ms
[         4 containers found      ]
[         0 containers skipped    ]
[         4 containers started    ]
[         0 containers aborted    ]
[         4 containers successful ]
[         0 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         1 tests failed          ]
```

The failure for the parameterized test invocation is properly reported to the listener.

**Comment by marcphilipp** [comment]
JUnit Platform reports a finished event for each node in the test tree. In Sam's example there are:

```
+- JUnit Jupiter (Engine)
|  +- Test Class
|     +- Parameterized Method
|        +- Parameterized Invocation
+- JUnit Vintage
```

4 of these are containers, 1 is a test. If you're only interested in events for tests, please check `TestIdentifier.isTest()` in your listener implementation. Please not that you might miss failures from class-level lifecycle callbacks, e.g. an exception thrown from a `@BeforeAll` method this way.

**Comment by houseshi** [comment]
@ParameterizedTes & @MethodSource  combined use of annotations,judgment is not a test, right?

**Comment by houseshi** [comment]
> JUnit Platform reports a finished event for each node in the test tree. In Sam's example there are:
> 
> ```
> +- JUnit Jupiter (Engine)
> |  +- Test Class
> |     +- Parameterized Method
> |        +- Parameterized Invocation
> +- JUnit Vintage
> ```
> 
> 4 of these are containers, 1 is a test. If you're only interested in events for tests, please check `TestIdentifier.isTest()` in your listener implementation. Please not that you might miss failures from class-level lifecycle callbacks, e.g. an exception thrown from a `@BeforeAll` method this way.



@ParameterizedTes & @MethodSource combined use of annotations,judgment is not a test, right?

**Comment by sbrannen** [comment]
> @ParameterizedTes & @MethodSource combined use of annotations,judgment is not a test, right?

That's correct. A `@ParameterizedTest` method is technically a "container" in JUnit 5.

**Comment by houseshi** [comment]
If you use @test together， The use case is executed multiple times 。parameterizedtest ，Don't think it is "tests" ,  Is that a problem? or, How does it become a "tests"

**Comment by houseshi** [comment]
> > @ParameterizedTes & @MethodSource combined use of annotations,judgment is not a test, right?
> 
> That's correct. A `@ParameterizedTest` method is technically a "container" in JUnit 5, but the individual parameterized test method invocations _below_ that container are "tests".


If you use @test together， The use case is executed multiple times 。parameterizedtest ，Don't think it is "tests" , Is that a problem? or, How does it become a "tests"

**Comment by houseshi** [comment]
> > > @ParameterizedTes & @MethodSource combined use of annotations,judgment is not a test, right?
> > 
> > 
> > That's correct. A `@ParameterizedTest` method is technically a "container" in JUnit 5, but the individual parameterized test method invocations _below_ that container are "tests".
> 
> If you use @test together， The use case is executed multiple times 。parameterizedtest ，Don't think it is "tests" , Is that a problem? or, How does it become a "tests"

I understand ，Thank you
