### ISSUE TITLE
Detecting cycles in inner class hierarchies throws exceptions even for classes not marked as @Nested

### ISSUE THREAD

**Issue by chavan77me** [junit-team/junit5#2249]
Upgrading to JUnit 5.6 is breaking a unit test I have.

```java
private class MySillyClosure(...) extends Closure<RetryStrategy>(...) { 
    @override
    RetryStrategy call(...) { return MyStrategy() } 
}
```

This class is defined in my test suite and the recursive check fails even though I have not marked any of these classes as `@Nested`.

I think this is the suspect code:

https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestClassWithTests.java#L46

https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java#L1007-L1008

Notice that the code looks for all nested classes (and asserts on finding a cycle) before attempting to filter out using the predicate for `@Nested`. Therefore any class that has this inner inheritance (in my case Groovy `Closure` and `WriteableClosure`) is causing an error even if they are not marked as `@Nested`.

For reference, here is the closure code and its inner class:

https://github.com/groovy/groovy-core/blob/master/src/main/groovy/lang/Closure.java#L847

Is there a way for me to disable this recursion check?

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
> Is there a way for me to disable this recursion check?

No. There is unfortunately no way to disable the cycle detection, but we'll look into fixing the issue.

Thanks for bringing this to our attention!
