### ISSUE TITLE
Mark Preconditions class as MAINTAINED or STABLE

### ISSUE THREAD

**Issue by khmarbaise** [junit-team/junit5#2254]
Currently I stumbled another time about the thing that the class `Preconditions` is marked as part of the `INTERNAL` API, but it would be helpful for authors of extensions to make it `MAINTAINED` or `STABLE` so it can be used very easily otherwise it could happen that you change the `Preconditions` class and my own extensions do not work anymore (This is of course the idea of an INTERNAL API). Maybe others have observed the same thing.

The `Precondition` class and its methods are very helpful in cases where you write a `ExecutionCondition` like `Disabled.*` or `Enabled.*` etc. and it is not limited to this.

**Comment by juliette-derancourt** [comment]
Tentatively slated for 5.7 M1 for _team discussion_

**Comment by marcphilipp** [comment]
**Team decision:** We'd rather keep it internal so we can change it if need be. Please use a general purpose library for that, e.g. Guava or Apache Commons Lang, or resort to a good old `if` statement.
