### ISSUE TITLE
DisabledOnOs annotation does not disable on the OS environment

### ISSUE THREAD

**Issue by parkavi11** [junit-team/junit5#2257]
I have disabled a particular test which will fail on Windows with the annotation `@DisabledOnOs(OS.WINDOWS)`

However, that particular test case runs in Windows and it fails (as the test case written for other OS except for Windows). 
Looking forward to your early response on this.

I tried JUnit 5.6.2

Please find the below code that I ran:

### build.gradle

```groovy
dependencies {
    testCompile 'org.testng:testng'
    testImplementation('org.junit.jupiter:junit-jupiter:5.6.2')
}
```

### Test.java

```java
    @Test(description = "some description")
    @DisabledOnOs(WINDOWS)
    public void testDisabledOnWindows() throws IOException {
        // my code

    }
```

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
The `@DisabledOnOs` annotation is from JUnit Jupiter and cannot be used with the `@Test` annotation from TestNG.

If you want to use `@DisabledOnOs`, you must make sure that you are writing tests using the JUnit Jupiter programming model (i.e., `@org.junit.jupiter.api.Test`, etc).

In light of that, I am closing this issue as "works as designed".
