### ISSUE TITLE
Repeatable annotations are not found on interfaces

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#226]
## Status Quo

JUnit 5's annotation search algorithm currently does not find repeatable annotations declared on interfaces. Annotations currently affected include `@Tag`, `@ExtendWith`, and their containers.

For example, this behavior makes it impossible to register an extension via `@ExtendWith` on an interface that is used to supply _default methods_ to concrete test classes that implement the interface.

The current work-around is to declare such annotations on all concrete subclasses, but this is obviously something we don't want to force users to have to do.

## Deliverables

- [ ] Refine the search algorithm for repeatable annotations so that such annotations are also discovered on interfaces implemented by a test class.

**Comment by marcphilipp** [comment]
I agree that we should fix this.

**Comment by mmerdes** [comment]
Fine with me als well

Marc Philipp <notifications@github.com> schrieb am So., 17. Apr. 2016 um
17:44:

**Comment by sbrannen** [comment]
"in progress"

**Comment by sbrannen** [comment]
Pushed to `master` 6ffc6aa0ea1ae082eb0e3c2b7e0669935c773aa2.
