### ISSUE TITLE
@ParamerizedTests {displayName}/{arguments} cannot show correctly in Maven's report

### ISSUE THREAD

**Issue by sima-zhu** [junit-team/junit5#2260]
## Steps to reproduce
Add the parameterized to tests.
```
@ParameterizedTest(name = "{displayName} with [{arguments}]")
@ValueSource(strings = { "val0", "val1" })
public void testDisplay(String someValue)
```

**Expected to see:**
```
  <testcase name="testDisplay(String) with val0" classname="com.example.MyTest" time="0.029"/>
  <testcase name="testDisplay(String) with val1" classname="com.example.MyTest" time="0.002"/>
```
**Actual reports**
```
  <testcase name="testDisplay{String}[1]" classname="com.example.MyTest" time="0.029"/>
  <testcase name="testDisplay{String}[2]" classname="com.example.MyTest" time="0.002"/>
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Win10 + jdk 11 + jupiter
 - Maven SureFire Plugin: 3.0.0-M4
 - Build Tool/IDE: Terminal

**Comment by marcphilipp** [comment]
You can configure Surefire to output the display names. Please refer to https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName.

**Comment by homberghp** [comment]
Same would and should apply for csvfilesource
