### ISSUE TITLE
Add requires to module "org.hamcrest"

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2263]
https://github.com/junit-team/junit5/blob/040037dfb08a0e61b7cb9e485196b0ba3758e756/junit-vintage-engine/src/module/org.junit.vintage.engine/module-info.java#L19

JUnit 4 mandates Hamcrest to be available at runtime and Hamcrest 2.2 (or earlier) claimed `org.hamcrest` as its stable module name.

https://github.com/hamcrest/JavaHamcrest/blob/5dd6a622c73daf716c6e8f33efa712be8dbb42ed/hamcrest/hamcrest.gradle#L16

**Comment by marcphilipp** [comment]
Should we do this even though it‘s just a transitive dependency? Are there general recommendations how to deal with this situation in the presence of automatic modules?

**Comment by sormuras** [comment]
In general, one shouldn't. Or even: mustn't.

But -- as we are the maintainers of both modules, i.e. `org.junit.vintage.engine` and `junit`, we could. Or better: should.

If module `junit` was a Java module with a compiled module descriptor, it would declare `requires org.hamcrest;` on its own. Let's release `junit@4.13.1` with a `module-info.class` and let `org.junit.vintage.engine@5.7.0-SNAPSHOT` depend on it.

**Comment by sormuras** [comment]
⬆️ Correct, @nicolaiparlog?
