### ISSUE TITLE
Invalid XML report created

### ISSUE THREAD

**Issue by AugustH** [junit-team/junit5#2269]
tested with:
1.5.1, 1.6.2, 1.7.0-M1

## Steps to reproduce

TestAscii.java
```java
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class TestAscii {
    @Test
    void testAsciiZero() {
        assertEquals("A", "B\0");
    }
}
```

```sh
VER=1.7.0-M1

javac -encoding UTF-8 -d . -cp .:junit-platform-console-standalone-${VER}.jar TestAscii.java
java -jar junit-platform-console-standalone-${VER}.jar -cp=. --details=summary  --reports-dir=. --scan-class-path
```

The '\0' ist copied to the failure message in the xml report 

try any xml tool, e.g.
```
xmllint TEST-junit-jupiter.xml

TEST-junit-jupiter.xml:57: parser error : Char 0x0 out of allowed range
<failure message="expected: &lt;A&gt; but was: &lt;B
```

**Comment by sbrannen** [comment]
Some quick research reveals that the `NUL` character is simply [not supported in XML 1.0 and 1.1](https://en.wikipedia.org/wiki/Valid_characters_in_XML#Characters_allowed_but_discouraged).

> Note that the code point U+0000, assigned to the null control character, is the only character encoded in Unicode and ISO/IEC 10646 that is always invalid in any XML 1.0 and 1.1 document.

**Comment by sbrannen** [comment]
How about simply using `assertTrue(...)` for such use cases in order to avoid inclusion of the `NUL` character in the generated XML report?

For example...

```java
assertTrue("A".equals("B\0"), "A == B\\0");
```

That results in error message like this:

```
org.opentest4j.AssertionFailedError: "A".equals("B\0") ==> expected: <true> but was: <false>
```

**Comment by AugustH** [comment]
the above is a very simplified example: actually the data was read from a file and the `\0` was missed in the cleaning, and the created XML-File was not readable, which gave a cryptic message in the system that runs the tests. So nobody expected the `\0`... and one breaking test gave an invalid file which was interpreted as a lot of failed tests. 
And the system is a grading software (https://inginious.readthedocs.io/en/v0.6/teacher_doc/what_is_inginious.html) an the "0 pts" resulted in a very unhappy student ;-)

**Comment by sbrannen** [comment]
> the "0 pts" resulted in a very unhappy student ;-)

Yes, I can imagine. 

Thanks for providing further details.

We'll see if we can improve the situation.

**Comment by marcphilipp** [comment]
FWIW Surefire writes `&amp;#0;` for `\0`.

**Comment by AugustH** [comment]
thanks a lot for the quick fix

**Comment by marcphilipp** [comment]
@AugustH Are you okay with using a snapshot for the time being? We don't intend to publish a bugfix release for this issue since it's really an edge case.

**Comment by AugustH** [comment]
no problem, my students are instructed to avoid the problem. But it is fixed for the class. Thanks again
