### ISSUE TITLE
TELs 'reportingEntryPublished' not triggered from extension context

### ISSUE THREAD

**Issue by Bukama** [junit-team/junit5#2277]
After chatting with @sormuras  on Gitter he asked me to open an issue:

Background: My goal is to create an annotation and create a report where the name of a test, it's result and the value of the annotation is published. @marcphillip suggested to use a `TestExecutionListener` for creating the report.

So whats done so far is:

1. Created an annotation (okay I used an existing from our project) which publishes the values into the extension context (`context.publishReportEntry(...)`). 

This is a simple extension, which publishes the annotations values into the extensions context:

```
	@Override
	public void beforeEach(ExtensionContext context) throws Exception {
		PioneerAnnotationUtils
				.findAllEnclosingRepeatableAnnotations(context, ReportEntry.class)
				.peek(ReportEntryExtension::verifyKeyValueAreNotBlank) // Not shown, but you get it by the name
				.forEach(entry -> context.publishReportEntry(entry.key(), entry.value()));
	}
```  

This is a test method of the extension:

```
  @Test
  void explicitKey_keyAndValueAreReported() {
    List<Map<String, String>> reportEntries = executeTestMethod(ReportEntriesTest.class, "explicitKey")
        .publishedTestReportEntries();

    assertThat(reportEntries).hasSize(1); // Line 31
    Map<String, String> reportEntry = reportEntries.get(0);
    assertThat(reportEntry).hasSize(1);
    assertThat(reportEntry).containsExactly(TestUtils.entryOf("Crow2", "While I pondered weak and weary"));
  }
  
```
with executes the following test

```  
static class ReportEntriesTest {

  @Test
  @ReportEntry(key = "Crow2", value = "While I pondered weak and weary")
  void explicitKey() {
  }
} 
``` 

This works fine. The test checks the published entries inside if they are correctly published and they are.

2. I than created a `TestExecutionListener` (TEL), registered it in META-INF and implemented the `executionStarted`, `reportingEntryPublished` and `executionFinished` with simple `System.out.printlin()` to check if they are called the way the docs say

```
public class PioneerReportListener implements TestExecutionListener {

  @Override
  public void executionStarted(TestIdentifier testIdentifier) {

    if(null != testIdentifier) {
      String msg = "Starte: " + testIdentifier.getDisplayName();
      System.out.println(msg);
    }
  }
  
  @Override
  public void reportingEntryPublished(TestIdentifier testIdentifier, ReportEntry entry) {
    String msg = String.format("Entry %s for test %s was published", entry.toString(), testIdentifier.getLegacyReportingName());

    System.out.println(msg);

  }
  
  @Override
  public void executionFinished(TestIdentifier testIdentifier, TestExecutionResult testExecutionResult) {

    if(testIdentifier.isTest()) {
      String result = String.format("test %s result is %s", testIdentifier.getLegacyReportingName(), testExecutionResult.getStatus().toString());

      System.out.println(result);
    }

  }
}
```

The `executionStarted` and `executionFinished` are work fine, but the `reportingEntryPublished` does not. When an report entry is published via an extension context the callback method is **NOT** called. It's only called when the test method uses a `TestReporter` parameter (@sormuras asked me to test the same using a `TestReporter`) and publishes an entry via `testreporter.publishEntry()`.

When taken the test method above the console output is:

> Starte: explicitKey_keyAndValueAreReported()
> 
> test explicitKey_keyAndValueAreReported() result is SUCCESSFUL
> 
> Starte: JUnit Jupiter
> Starte: ReportEntryExtensionTest

As seen the `reportingEntryPublished` is not called.

If I change the indirectly called test method to:

```
		@Test
		@ReportEntry(key = "Crow2", value = "While I pondered weak and weary")
		void explicitKey(TestReporter reporter) {
			reporter.publishEntry("Hello Junit!");
		}
```

the output is:

> Starte: explicitKey_keyAndValueAreReported()
> 
> test explicitKey_keyAndValueAreReported() result is FAILED
> 
> 
> java.lang.AssertionError: 
> Expected size:<1> but was:<0> in:
> <[]>
> 
> 	at org.junitpioneer.jupiter.ReportEntryExtensionTest.explicitKey_keyAndValueAreReported(ReportEntryExtensionTest.java:31)
> 
> Starte: JUnit Jupiter
> Starte: ReportEntryExtensionTest

Again the `reportingEntryPublished` is not called and the `assertThat(reportEntries).hasSize(1);` failes. This seems odd, as I would have expected two published report entries but not zero.

When the `TestReporter` is used on the test method which is actually executed (instead on using it on the indirectly test method:

```
	@Test
	void explicitKey_keyAndValueAreReported(TestReporter reporter) {
		reporter.publishEntry("Hello Junit!");
    
		List<Map<String, String>> reportEntries = executeTestMethod(ReportEntriesTest.class, "explicitKey")
				.publishedTestReportEntries();

		assertThat(reportEntries).hasSize(1);
		Map<String, String> reportEntry = reportEntries.get(0);
		assertThat(reportEntry).hasSize(1);
		assertThat(reportEntry).containsExactly(TestUtils.entryOf("Crow2", "While I pondered weak and weary"));
	}
  

		@Test
		@ReportEntry(key = "Crow2", value = "While I pondered weak and weary")
		void explicitKey() {
		}
```

the output is the following:

> Starte: explicitKey_keyAndValueAreReported(TestReporter)
> 
> Entry ReportEntry [timestamp = 2020-04-27T14:08:16.277396800, value = 'Hello Junit!'] for test explicitKey_keyAndValueAreReported(TestReporter) was published
> timestamp = 2020-04-27T14:08:16.277396800, value = Hello Junit!test explicitKey_keyAndValueAreReported(TestReporter) result is SUCCESSFUL

> Starte: JUnit Jupiter
> Starte: ReportEntryExtensionTest

As seen the callback is called but only for the published entry of the `TestReporter` not for the entry of the extension.

**Comment by sbrannen** [comment]
It looks like the entry should be published from an extension via `org.junit.jupiter.engine.descriptor.AbstractExtensionContext.publishReportEntry(Map<String, String>)`.

And the `TestReporter` support is implemented in `org.junit.jupiter.engine.extension.TestReporterParameterResolver.resolveParameter(ParameterContext, ExtensionContext)` by delegating to `extensionContext::publishReportEntry`.

So, we'll have to investigate what's going on.

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M2 for _team discussion_ and investigation

**Comment by marcphilipp** [comment]
@Bukama Thanks for the detailed description. It would really help us to have a minimal reproducer. Could you please put one together?

**Comment by Bukama** [comment]
> @Bukama Thanks for the detailed description. It would really help us to have a minimal reproducer. Could you please put one together?

I've createad the [listener4junit branch ](https://github.com/Bukama/junit-pioneer/tree/listener4Junit) for you.

Inside there you find the:

* [PioneerReportListener](https://github.com/Bukama/junit-pioneer/blob/listener4Junit/src/main/java/org/junitpioneer/jupiter/report/PioneerReportListener.java)
* [TEL registration](https://github.com/Bukama/junit-pioneer/blob/listener4Junit/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener)
* [Modified ReportEntryExtensionTests](https://github.com/Bukama/junit-pioneer/blob/listener4Junit/src/test/java/org/junitpioneer/jupiter/ReportEntryExtensionTests.java)

I modified the `ReportEntryExtensionTests` to two test: One with the original publishing via the [ReportEntryExtension](https://github.com/Bukama/junit-pioneer/blob/listener4Junit/src/main/java/org/junitpioneer/jupiter/ReportEntryExtension.java), the second one using the `TestReporter`. When you run this tests you will see the described output on `System.out`.

Hope this helps

**Comment by marcphilipp** [comment]
Thanks for the example!

This is what happens:

1. You run `ReportEntryExtensionTests` using IDEA or Gradle
1. The JUnit Platform registers `PioneerReportListener` as a `TestExecutionListener`
1. `ReportEntryExtensionTests.testReporter` is executed and publishes a report entry using `TestReporter` which is picked up by `PioneerReportListener` andd printed to `System.out`.
1. `ReportEntryExtensionTests.explicitKey_keyAndValueAreReported` is executed
1. It uses `EngineTestKit` to execute `ReportEntriesTest`
1. It reports a report entry using `ExtensionContext`. However, since this execution is completely separate from the one you triggered via IDEA or Gradle it is not reported to `PioneerReportListener` (neither are any other events for `ReportEntriesTest`).

If you add a `@ReportEntry` annotation to `ReportEntryExtensionTests.explicitKey_keyAndValueAreReported`, you will see that it is reported as expected.

**Comment by Bukama** [comment]
Thanks for explanation. This `EngineTestKit` blows my mind 🤯

**Comment by marcphilipp** [comment]
I guess that's just the nature of testing the testing framework with the testing framework. 😉
