### ISSUE TITLE
#1289 the package-list error in the JavaDocs is still an issue

### ISSUE THREAD

**Issue by jmccay-work** [junit-team/junit5#2278]
I downloaded and added to NetBeans 11.0 with Java 8:
JUnit 5.6.2 Jupiter
JUnit 5.6.2 Vintage
JUnit 1.6.2 Platform

## Steps to reproduce
Adding the documentation jars to the library still produces the following error:

 **_Invalid Javadoc root {path to doc jar file} 
The Javadoc root does not contain the package-list file._**

## Context
 - Used versions (Jupiter/Vintage/Platform):
Jupiter 5.6.2
Vintage 5.6.2
Platform 1.6.2

 - Build Tool/IDE:
Apache NetBeans 11.0

   Is there any chance this will be fixed in the next version?

**Comment by sormuras** [comment]
We work around https://bugs.openjdk.java.net/browse/JDK-8240169 to link to external API documentation sites. It is possible, that we "forget" to include non-module based assets in the process.  Although it looks like, we do take measures to include it:

https://github.com/junit-team/junit5/blob/19785134f95ba100346eb2d8b0c24f707535ebe4/documentation/documentation.gradle.kts#L300-L303

🤔

**Comment by sbrannen** [comment]
This artifact (https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.6.2/junit-jupiter-api-5.6.2-javadoc.jar) contains `element-list` but does not contain `package-list`.

**Comment by sbrannen** [comment]
Note, however, that `package-list` does exist in the published JavaDoc: https://github.com/junit-team/junit5/blob/gh-pages/docs/5.6.2/api/package-list

**Comment by marcphilipp** [comment]
_in progress_

**Comment by jmccay-work** [comment]
Thank you for the work you people have done.

**Comment by sormuras** [comment]
Methinks, we might remove our workaround, soon.

![image](https://user-images.githubusercontent.com/2319838/87319622-28153c00-c52a-11ea-9ca2-09e2d262d128.png)

**Comment by marcphilipp** [comment]
I'm not so sure.

@jmccay-work Did this error message come from Netbeans directly?

> **_Invalid Javadoc root {path to doc jar file}
> The Javadoc root does not contain the package-list file._**
