### ISSUE TITLE
Support file system resources in @CsvFileSource

### ISSUE THREAD

**Issue by homberghp** [junit-team/junit5#2281]
## Problem description

Test resources are strange beasts. The compiler does not know about them nor cares, so getting the resources into the class path in typical builds needs help from the build system (ant, maven, gradle). This leads to several problems

- running a single test file (e.g. a first after project clean or fresh project) will not work, unless a more or less complete build step is executed.
- copying the test file from one location to another without any transformation is a waste of time (and ssd wear).
- Modifying the test data and rerun the test requires a rebuild (remember the deployment of the test data to the (test) class path, so modifying just the test data and re-run the test is not enough.
- Test data should be considered input to the program, not a resource. A resource is a glorified constant, test data should be able to vary independent of program code, test or otherwise.

## Original Proposal
- Modify the InputStream creating method (see my remarks in #1970) to try file system first, then class path would be a sufficient change. This will create this feature very cheaply without changing current class path semantics.
- Update @CsvFileSource documentation to reflect this change since the change proposal in #1970 adapts a private method in the CsvFileArgumentsProvider class.

**Comment by sbrannen** [comment]
As I stated in https://github.com/junit-team/junit5/issues/1970#issuecomment-621727776, we likely will **not** want to change default semantics since that would be a potentially breaking change.

Instead, adding support for looking in the file system would be "in addition" to the current classpath support. It should not "supersede" that support.

That's why I suggested a robust and backward compatible solution based on schemes (a.k.a., _prefixes_) such as `classpath:` and `file:`, where `classpath:` is the inferred default.

As a side note, I understand your preference for placing resources directly in the file system. There may be valid use cases for that. That's why I asked you to open this issue; however, I don't agree with the following.

> so getting the resources into the class path in typical builds needs help from the build system

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M2 for _team discussion_

**Comment by sbrannen** [comment]
As @sormuras mentioned in https://github.com/junit-team/junit5/issues/1970#issuecomment-621728986, supporting `modulepath:` as a scheme would also be an option.

**Comment by homberghp** [comment]
Ultimately a URI or URL would be most flexible, but will introduce quite some effort to get it working.
Fetched test data from server might be useful in integration tests.

**Comment by homberghp** [comment]
By the way, I want to compliment you on the quick response. Absolutely phenomenal.

**Comment by homberghp** [comment]
I have just created a pull request with an implementation (including test and javadoc updates) on how I would envision it.
I like simple when simple does it.

**Comment by homberghp** [comment]
## Studying the scheme like proposal

- Considering to implement a URI like schema. Studying the URL and URI doc, I found that 
using proper url like https://junit5.org will work and produce a reasonable resource specifying string.
However, using the `file://` only allows full path names like '  file:/home/hom/NetBeansProjects/uriresolution/target/classes/u/u.csv' which of course would be a **no go**, because that would bind the project to a specific file system organization. The class loader resolution which is still intact will deal with the class path, presumably the module path and the jar path too. 

- The order of evaluation might need some consideration because in case of having two resources on in the project with the same name will give the first one evaluated precedence. On the business side of a project, I could imagine that this leads to unsafe situations because a local file could overwrite a constant in a jar. On the other hand, having an almost automatic overwrite mechanism in the testing part of a project might be beneficial. In that case, giving file system resolution precedence over class-loader resolution might be acceptable.



> As I stated in [#1970 (comment)](https://github.com/junit-team/junit5/issues/1970#issuecomment-621727776), we likely will **not** want to change the default semantics since that would be a potentially breaking change.

I am NOT proposing to change the default semantics. Default is what will happen if a file is not resolvable via the Path.get() method, and that default is then the class loader resolving. The added tests in the pull request may help to convince that there will be little breakage if any.

> 
> Instead, adding support for looking in the file system would be "in addition" to the current classpath support. It should not "supersede" that support.
> 
> That's why I suggested a robust and backward compatible solution based on schemes (a.k.a., _prefixes_) such as `classpath:` and `file:`, where `classpath:` is the inferred default.
> 

The file: prefix may lead to quite some confusion because that will not support a relative path, which is what you typically want.

> As a side note, I understand your preference for placing resources directly in the file system. There may be valid use cases for that. That's why I asked you to open this issue (And thanks for doing so!); however, I don't agree with the following.
> 
> > so getting the resources into the class path in typical builds needs help from the build system
> 
> Most projects I have seen over the past decade use Maven or Gradle (or some other build tool) that supports the de facto standard for classpath resources (i.e., the `src/main/resources` and `src/test/resources` folders). IDEs also fully support the notion of test classpath resources. Furthermore, there are times when classpath resources are the only option -- for example, when test support is published as a JAR file in which both the compiled classes and classpath resources must be present.

Loading the resource via the class loader will still be supported. This proposal does not want to supplant but only enhance the current implementation. The last use case you describe is still supported and even improved, because with a test-jar you could simply add test cases to the csv file, by making a copy of the csv file in the jar, and adding your test cases. This will only make the case for this enhancement stronger. In that scenario, one must of course take care of proper file naming and potential sub directories a.k.a. namespaces for the test resource files.

**Comment by sbrannen** [comment]
**Team Decision**:

- Introduce a new `String[] files() default {};` attribute in `@CsvFileSource` that is used to configure file system paths to CSV files, supporting both relative and absolute paths.
  - Throw an exception if a specified file system resource does not exist.
- Throw an exception if both `resources` and `files` are empty arrays, but do not preclude the option to configure both classpath and file system resources.
- Make the `resources` attribute have a default of `{}`.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by homberghp** [comment]
Excellent decision
