### ISSUE TITLE
Provide a less generic argument converter

### ISSUE THREAD

**Issue by juliette-derancourt** [junit-team/junit5#2284]
When implementing an explicit converter via `SimpleArgumentConverter`, the signature of the `convert` method is the following: `Object convert(Object source, Class<?> targetType)`. Some boilerplate code is then needed to check if the types of the source/target are supported.

I personally often use one converter per use case, i.e. to convert type X to type Y.
Maybe we could implement a new argument converter that would take two types (one for the source and one for the target) and would do the checks for the user. The method to implement would then have a simpler signature.

## Deliverables

- [ ] An abstract converter like `TypedArgumentConverter<S, T>` that would ensure that source is of type S and target of type T (Simple's already taken so... `SimplerArgumentConverter`? :P)

**Comment by sbrannen** [comment]
**Team Decision**: introduce an abstract `TypedArgumentConverter<S, T>` class in `org.junit.jupiter.params.converter` package.
