### ISSUE TITLE
TestEngineKit by default picks up settings for parallel execution

### ISSUE THREAD

**Issue by Bukama** [junit-team/junit5#2285]
I was working on [JUnit-pioneer #131](https://github.com/junit-pioneer/junit-pioneer/issues/131), which is about making some extensions thread safe, e.g. due using the `@ResourceLock` annotation.
 
For testing purposes I set the execution to the most parallel execution possible (Test classes and methods inside each class are executed in parallel):

```properties
#  Enable parallel execution of JUnit tests
junit.jupiter.execution.parallel.enabled=true
# Run all tests methods inside a class in parallel as default
junit.jupiter.execution.parallel.mode.default=concurrent
# Run all tests classes in parallel as default
junit.jupiter.execution.parallel.mode.classes.default=concurrent
# Explicit set the execution strategy to dynamic (default strategy)
junit.jupiter.execution.parallel.config.strategy=dynamic
# Explicit set the factor of dynamic strategy to its default value 
junit.jupiter.execution.parallel.config.dynamic.factor=1
```

It seems that by current default the `TestEngineKit` also picks up those settings for parallel execution(_, which results in a large amount of flaky tests, when you verify your tests using the engine kit_).
@marcphilipp thinks this is unexpected, when using EngineTestKit and JUnit should not do this be default. So he [asked](https://github.com/junit-pioneer/junit-pioneer/issues/131#issuecomment-622953047) me to open an issue for further investigation and decision.

Note: He also mentioned that a workaround for the current behavior is so disable the parallel execution at the `TestEngineKit` using `.configurationParameter("junit.jupiter.execution.parallel.enabled", "false")`.

**Comment by marcphilipp** [comment]
I indeed think `EngineTestKit` should not read system properties or `junit-platform.properties` by default. Instead, we should make that an opt-in behavior.

@junit-team/junit-lambda WDYT?

**Comment by sbrannen** [comment]
**Team Decision**: do not read system properties or `junit-platform.properties` by default. Instead, we make that opt-in behavior.

**Comment by marcphilipp** [comment]
_in progress_
