### ISSUE TITLE
Incorrect Javadoc in BeforeTestExecutionCallback

### ISSUE THREAD

**Issue by BlueIce** [junit-team/junit5#2288]
The Javadoc for `BeforeTestExecutionCallback` states:
https://github.com/junit-team/junit5/blob/c4e0a26deb6194c0221410d9fa8261cf3ffd3719/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/BeforeTestExecutionCallback.java#L18-L23

I think that should read "user-defined _setup_ methods" instead of "user-defined teardown methods".

## Deliverables

- [x] Correct Javadoc

**Comment by marcphilipp** [comment]
Good catch! 👍

**Comment by BlueIce** [comment]
Just spotted another location:

https://github.com/junit-team/junit5/blob/06aca78f1e5a4b3691d927f48e18ae5711b5cfef/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/BeforeTestExecutionCallback.java#L67-L69

**Comment by marcphilipp** [comment]
Thanks, not sure how I missed that. 🤦‍♂️
