### ISSUE TITLE
Introduce getJavaClass() and getJavaMethod() in MethodSource

### ISSUE THREAD

**Issue by kicasta** [junit-team/junit5#2294]
# Problem Description
We added a new Annotation to the Test Cases, i.e. DisplayDescription, which allows giving a longer description of a test case than that of DisplayName(). Afterward, we need to check for the presence of / access this annotation. We do this via the TestIdentifier. 

`Optional<TestSource> source = identifier.getSource();`

In case of a class source it is straightforward: 

```
if (source.filter((e) -> e instanceof ClassSource).isPresent()) {
     ClassSource cs = (ClassSource) source.get();
     annotation = cs.getJavaClass().getAnnotation(DisplayDescription.class);
}
```

However, there isn´t, to our knowledge, a function that does the same for methods, leaving us to use Reflection in order to get the Java Method Source:

```
else if (source.filter((e) -> e instanceof MethodSource).isPresent()) {
     MethodSource ms = (MethodSource) source.get();
     try {
         annotation = Arrays.stream(Class.forName(ms.getClassName()).getMethods())
                  .filter(m -> m.getName().equals(ms.getMethodName()))
                  .findAny().map(m -> m.getAnnotation(DisplayDescription.class))
                 .orElse(null);
     } catch (ClassNotFoundException e) {
         annotation = null;
    }
}
```

# Request
Support for something in the art of: `((MethodSource) source.get()).getJavaMethod()` that works analog to getJavaClass

**Comment by marcphilipp** [comment]
I think this is a good idea! In the meantime, there's `ReflectionSupport.findMethod` which takes into account parameters as well.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_.

**Comment by sbrannen** [comment]
`MethodSource` could also benefit from a `getJavaClass()` method as well.

**Comment by marcphilipp** [comment]
**Team decision:** Add `getJavaClass()` and `getJavaMethod()` to `MethodSource`.

**Comment by marcphilipp** [comment]
@kicasta Would you be interested in submitting a PR?

**Comment by kicasta** [comment]
> @kicasta Would you be interested in submitting a PR?
@marcphilipp Yes, I can get on with it on Sunday

**Comment by marcphilipp** [comment]
@kicasta Any updates? 🙂

**Comment by sbrannen** [comment]
@kicasta, please note that @cberes has already submitted PR #2320.
