### ISSUE TITLE
stdout/stderr loss despite config options in JUnit Vintage test execution

### ISSUE THREAD

**Issue by Vazzilena** [junit-team/junit5#2298]
We were using ant Junit4 task to run our tests and we migrated to Junit platform console launcher, but we are experiencing some stdout/stderr loss.

I added the proper configuration settings as advised in the documentation:

```
<sysproperty key="junit.platform.output.capture.stdout" value="true"/>
<sysproperty key="junit.platform.output.capture.stderr" value="true"/>
```

But there is still some stdout/stderr loss compared to our reports before the change. My initial assumption is that I do not have a proper test listener in place but isn’t the launcher having some default listener that receives the stdout/stderr? (we cannot use the ant junitlauncher as it does not support jacoco configuration)

What am I missing? Can I still use the launcher and get the generous stdout/stderr as in Junit4 ant task

Old ANT task:

  ```
<macrodef name="test.executor">
    <attribute name="suite"/>
    <attribute name="test.jvm.classpath"/>
    <attribute name="server.jvm.classpath" default=""/>
    <attribute name="license.file" default="${server.license.file}"/>
    <attribute name="license.directory" default="${server.license.directory}"/>
    <attribute name="extra.server.classpath" default=""/>
    <attribute name="category" default="nocategory"/>
    <attribute name="exclude.category" default=""/>
    <attribute name="run.jacoco.reporter" default="true"/>
    <attribute name="junit.print.summary.option" default="${junit.task.print.summary.option}"/>
    <attribute name="maxmemory" default="${junit.maxmemory}"/>
    <sequential>

      <split-by-dot-and-get-the-last-item input.string="@{category}"
        result.project.property="trimmed.category"/>
      <mkdir dir="${basedir}/${trimmed.category}/@{suite}"/>

      <local name="generate.event.uid"/>
      <condition property="generate.event.uid" value="true" else="false">
        <contains string="@{suite}"
          substring="TraceLoggerClientGenerateUUIDTest"/>
      </condition>

      <jacoco:coverage destfile="${basedir}/${trimmed.category}/@{suite}/jacoco.exec" append="true">
        <junit showoutput="true" printsummary="@{junit.print.summary.option}" fork="yes"
          maxmemory="@{maxmemory}"
          dir="${basedir}/${trimmed.category}/@{suite}" haltonfailure="${haltonfailure}"
          logfailedtests="true">
          <sysproperty key="java.io.tmpdir" value="${custom.java.tmp.dir}"/>
          <sysproperty key="DOCKER_TEST_SERVER" value="${docker.test.server}"/>
          <sysproperty key="DOCKER_IMAGE_VERSION" value="${docker.image.version}"/>
          <sysproperty key="DOCKER_HOST" value="${docker.host}"/>
          <sysproperty key="DOCKER_ADAPTER" value="${docker.adapter}"/>
          <sysproperty key="DOCKER_IMAGE_REPOSITORY_URL" value="${docker.image.repository.url}"/>
          <formatter type="xml"/>
          <jvmarg line="${jvm.args}"/>
          <jvmarg value="-XX:+HeapDumpOnOutOfMemoryError"/>
          <jvmarg value="-XX:HeapDumpPath=${basedir}"/>
          <jvmarg value="-Dnirvana.test.requiredCategories=@{category}"/>
          <jvmarg value="-Dnirvana.test.excludeCategories=@{exclude.category}"/>
          <jvmarg value="-Djava.io.tmpdir=${custom.java.tmp.dir}"/>
          <jvmarg value="-DLOGLEVEL=${log.level}"/>
          <jvmarg value="-DTESTLOGLEVEL=${test.log.level}"/>
          <jvmarg value="-DTESTLOGFILELEVEL=${test.log.file.level}"/>
          <jvmarg value="-DEnableDebug=${debug.flag}"/>
          <jvmarg value="-DLICENCE_DIR=@{license.directory}"/>
          <jvmarg value="-DLICENCE_FILE=@{license.file}"/>
          <jvmarg value="-DPROJECT_ROOT_FOLDER=${project.root}"/>
          <jvmarg value="-DTEST_WORKING_DIR=${basedir}/${trimmed.category}/@{suite}"/>
          <jvmarg value="-DJUnitBasePort=${junit.base.port}"/>
          <jvmarg value="-DFAILON_SESSION_LEAKS=${check.session.leaks}"/>
          <jvmarg
            value="-Dnirvana.test.server.classpath_extra=@{server.jvm.classpath}${path.separator}@{extra.server.classpath}"/>
          <jvmarg value="-Dnirvana.test.server.classpath_nostd=yes"/>
          <jvmarg value="-DGETCOVERAGE=${server.code.coverage.option}"/>
          <jvmarg value="-DJACOCO_PATH=${jacocoagent.location}"/>
          <jvmarg value="-Dcom.softwareag.um.client.GenerateEventUID=${generate.event.uid}"/>
          <classpath>
            <pathelement path="@{test.jvm.classpath}"/>
            <pathelement path="@{server.jvm.classpath}"/>
          </classpath>
          <test name="@{suite}" todir="${basedir}/${trimmed.category}/@{suite}"
            outfile="TEST-@{suite}-${current.os}">
            <formatter type="xml"/>
          </test>
        </junit>
      </jacoco:coverage>
      <jacoco.reporter
        reporting.dir="${basedir}/${trimmed.category}/@{suite}"
        suite="@{suite}"
        category="${trimmed.category}"
        run.reporter="@{run.jacoco.reporter}"/>
    </sequential>
  </macrodef>
```

New ANT task (using junit-platform-console-standalone-1.5.2.jar):

```
<macrodef name="console.runner">
    <attribute name="console.arguments" default=""/>
    <attribute name="max.memory" default=""/>
    <attribute name="jvm.args" default=""/>
    <attribute name="test.jvm.classpath" default="${test.jvm.classpath}"/>
    <attribute name="server.jvm.classpath" default="${server.jvm.classpath}"/>
    <attribute name="license.file" default="${server.license.file}"/>
    <attribute name="license.directory" default="${server.license.directory}"/>
    <attribute name="extra.server.classpath" default=""/>
    <attribute name="fail.if.no.tests" default="true"/>
    <attribute name="fail.on.error" default="false"/>
    <attribute name="maxmemory" default="${junit.maxmemory}"/>
    <attribute name="reporting.dir" default="${basedir}"/>
    <attribute name="identifier" default=""/>
    <attribute name="jupiter.engine.timeout.milliseconds" default="600000"/>
    <sequential>

      <path id="discovery.path">
        <fileset dir="${project.root}/jars">
          <include name="*.jar"/>
        </fileset>
      </path>
      <local name="test.discovery.classpath"/>
      <pathconvert property="test.discovery.classpath" refid="discovery.path"/>

      <mkdir dir="@{reporting.dir}"/>
      <jacoco:coverage destfile="@{reporting.dir}/@{identifier}.exec"
        append="true">

        <java fork="true"
          failonerror="@{fail.on.error}"
          append="true"
          maxmemory="@{max.memory}"
          classname="org.junit.platform.console.ConsoleLauncher"
          dir="@{reporting.dir}">

          <sysproperty key="junit.platform.output.capture.stdout" value="true"/>
          <sysproperty key="junit.platform.output.capture.stderr" value="true"/>

          <sysproperty key="DOCKER_TEST_SERVER" value="${docker.test.server}"/>
          <sysproperty key="DOCKER_IMAGE_VERSION" value="${docker.image.version}"/>
          <sysproperty key="DOCKER_HOST" value="${docker.host}"/>
          <sysproperty key="DOCKER_ADAPTER" value="${docker.adapter}"/>
          <sysproperty key="DOCKER_IMAGE_REPOSITORY_URL" value="${docker.image.repository.url}"/>
          <sysproperty key="junit.jupiter.execution.timeout.default"
            value="@{jupiter.engine.timeout.milliseconds}"/>

          <arg
            line=" --disable-ansi-colors --details-theme=ascii --details=tree --fail-if-no-tests=@{fail.if.no.tests} --reports-dir=@{reporting.dir} --classpath=${test.discovery.classpath}@{console.arguments}"/>

          <jvmarg line="${jvm.args}"/>
          <jvmarg line="@{jvm.args}"/>
          <jvmarg value="-XX:+HeapDumpOnOutOfMemoryError"/>
          <jvmarg value="-XX:HeapDumpPath=${basedir}"/>
          <jvmarg value="-Djava.io.tmpdir=${custom.java.tmp.dir}"/>
          <jvmarg value="-DLOGLEVEL=${log.level}"/>
          <jvmarg value="-DTESTLOGLEVEL=${test.log.level}"/>
          <jvmarg value="-DTESTLOGFILELEVEL=${test.log.file.level}"/>
          <jvmarg value="-DEnableDebug=${debug.flag}"/>
          <jvmarg value="-DLICENCE_DIR=@{license.directory}"/>
          <jvmarg value="-DLICENCE_FILE=@{license.file}"/>
          <jvmarg value="-DPROJECT_ROOT_FOLDER=${project.root}"/>
          <jvmarg value="-DJUnitBasePort=${junit.base.port}"/>
          <jvmarg value="-DFAILON_SESSION_LEAKS=${check.session.leaks}"/>
          <jvmarg
            value="-Dnirvana.test.server.classpath_extra=@{server.jvm.classpath}${path.separator}@{extra.server.classpath}"/>
          <jvmarg value="-Dnirvana.test.server.classpath_nostd=yes"/>
          <jvmarg value="-DGETCOVERAGE=${server.code.coverage.option}"/>
          <jvmarg value="-DJACOCO_PATH=${jacocoagent.location}"/>

          <classpath>
            <pathelement location="${console.runner.location}"/>
            <pathelement path="@{test.jvm.classpath}"/>
            <pathelement path="@{server.jvm.classpath}"/>
          </classpath>

        </java>
      </jacoco:coverage>
    </sequential>
  </macrodef>
```

Sample output files:

Using the JunitPlatform with the proper config options in place (49,6 KB): 
[TEST-JmsMessageIdFailoverTest-windows_JunitPlatform_stdout_stderr_options_added.txt](https://github.com/junit-team/junit5/files/4627014/TEST-JmsMessageIdFailoverTest-windows_JunitPlatform_stdout_stderr_options_added.txt)

Using the JunitPlatform without the proper config options (48,6 KB): 
[TEST-JmsMessageIdFailoverTest-windows_JunitPlatform_no_sterr_stdout_options.txt](https://github.com/junit-team/junit5/files/4627016/TEST-JmsMessageIdFailoverTest-windows_JunitPlatform_no_sterr_stdout_options.txt)

Using old school junit4 ant task (378 KB): 
[TEST-com.pcbsys.nirvana.nAdminAPI.cluster.failover.JmsMessageIdFailoverTest-windows_junit4_ant_task.txt](https://github.com/junit-team/junit5/files/4627015/TEST-com.pcbsys.nirvana.nAdminAPI.cluster.failover.JmsMessageIdFailoverTest-windows_junit4_ant_task.txt)

**Comment by Vazzilena** [comment]
Maybe this is somehow related to https://github.com/junit-team/junit5/issues/780. 

I see the console laucher is using org.junit.platform.launcher.listeners.TestExecutionSummary, and I probably need to configure another test listener that takes care of the stdout/stderr.... :?

**Comment by Vazzilena** [comment]
I figured when using the junit platfom System.out.println() entries from the test itself, are send to the xml file, but the whole console output of the execution is not. 

In comparison, when using the old school junit4 ant task, there is an attribute [outputtoformatters], which is true by default, and sends any output generated by tests to the test formatters: https://ant.apache.org/manual/Tasks/junit.html 

Therefore, the result xml file contains complete console output, while junit platform does not have a configuration option for this.

Is it possible to configure the console with this option somehow? 

We cannot use the junit launcher task as it is limited compared to directly using the console launcher jar (ant java task)?

**Comment by Vazzilena** [comment]
[std-err-out.zip](https://github.com/junit-team/junit5/files/4656475/std-err-out.zip)

Attaching a very simple repro zip. Once extracted, execute `ant 5` command in the basedir to see what I mean. To showcase how this looks with old junit4 task execute `ant 4 `in the basedir.  

The resulting xml would be different - one would contain full stdout, the other would contain only system out entries from the test.

**Comment by Vazzilena** [comment]
Perhaps the answer is here: 

https://junit.org/junit5/docs/current/user-guide/#running-tests-capturing-output

> Please note that the captured output will only contain output emitted by the thread that was used to execute a container or test. Any output by other threads will be omitted because particularly when executing tests in parallel it would be impossible to attribute it to a specific test or container.

Is there a plan to support this for the non-parallel cases? It is a disadvantage compared to what the old school execution offers…

**Comment by juliette-derancourt** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_

**Comment by marcphilipp** [comment]
@Vazzilena I think what you're seeing is caused by `XmlReportWriter` only emitting system-out/-err elements for `<testcase>` elements, but not for the `<testsuite>` level.

We could add the output for the engine-level as well. However, that might be confusing since it will not contain the test-level output and there's no way to tell where in the output a test was started. Alternatively, we could capture the whole output of all tests in the engine and add that but that would be less useful in many cases since there's no way to attribute lines so specific test classes/methods. Thoughts? 🤔

**Comment by Vazzilena** [comment]
@marcphilipp,

Considering how things work on our end perhaps I would opt for the second option as our internal tasks are doing some extra pre-processing and, in the end, we end up with a single test that we execute using the console launcher.
We do this because we have huge test database and we want to know that in a single report folder we always have data only for one single test. 
We also have BeforeEach/AfterEach and BeforeAll/AfterAll implemented in a base test super class where we explicitly print the test who is starting/ending as well as any time related info, so we have a solution for this as well…

Perhaps these two modes can be managed by a configuration option? The default would be whatever you think is best for the framework?
