### ISSUE TITLE
ConsoleLauncher's output in verbose mode interleaves with actual test output

### ISSUE THREAD

**Issue by swaranga** [junit-team/junit5#2302]
Team, when running JUnit tests using the console launcher in standalone mode with `--detail verbose`, the output of the  `VerboseTreePrintingListener` gets interleaved with the test output which makes it harder to read the output.

Here is a minimal test that reproduces the problem:

```
import org.junit.jupiter.api.Test;

import org.junit.jupiter.api.BeforeAll;

class AppTest {
    @BeforeAll
    public static void setupClass() {
        for (int i = 0; i < 10; i++) {
            System.out.println("class setup");
        }
    }

    @Test
    void testApp() {
        for (int i = 0; i < 10; i++) {
            System.out.println("test output");
        }
    }
}
```

I ran this with command `java -jar junit-platform-console-standalone-1.6.2.jar -cp target/classes -cp target/test-classes --scan-classpath --details verbose` and got the following output:

```
Thanks for using JUnit! Support its development at https://junit.org/sponsoring

Test plan execution started. Number of static tests: 1
╷
├─ JUnit Jupiter
│  ├─ AppTest
class setup
class setup
class setup
class setup
class setup
class setup
class setup
class setup
class setup
class setup
│  │  ├─ testApp()
│  │  │       tags: []
│  │  │   uniqueId: [engine:junit-jupiter]/[class:com.swaranga.junit5.demo.AppTest]/[method:testApp()]
│  │  │     parent: [engine:junit-jupiter]/[class:com.swaranga.junit5.demo.AppTest]
│  │  │     source: MethodSource [className = 'com.swaranga.junit5.demo.AppTest', methodName = 'testApp', methodParameterTypes = '']
test output
test output
test output
test output
test output
test output
test output
test output
test output
test output
│  │  │   duration: 15 ms
│  │  │     status: ✔ SUCCESSFUL
│  └─ AppTest finished after 36 ms.
└─ JUnit Jupiter finished after 65 ms.
├─ JUnit Vintage
└─ JUnit Vintage finished after 2 ms.
Test plan execution finished. Number of all tests: 1

Test run finished after 91 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         0 tests failed          ]
```

This is a toy example but if my tests have some problem that prints some exceptions at startup those gets interleaved with all the test case tree details from the listener.

I think this problem occurs because the `VerboseTreePrintingListener` effectively calls `System.out.println` via a `PrintWriter` to print each line of the tree summary separately. If the actual tests are also printing things to the console, they get all mixed up.

If instead we could collect the entire summary in a `StringBuilder` and finally send it to the output stream then this problem may not occur. Another solution could be to print this summary before any test execution is started. Let me know what you think.

On a related note, the reason I am using `verbose` mode for my tests is because if a test throws any exception, JUnit 5 prints the entire stacktrace only in the verbose mode. Would it be reasonable to require other modes too to print to the console? If so, I can submit an another issue for that.

**Comment by juliette-derancourt** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_

**Comment by marcphilipp** [comment]
@swaranga Have you tried using the `flat` mode? That also prints the full stacktrace but not the tree. However, test "events" would still be interleaved with test output.

**Comment by swaranga** [comment]
The tree mode is the most readable format that I have found and our team members really love it. Especially if the tests contain repeated test it. We tried out the flat mode and to us it does not really seemed helpful for a few reasons - it does not print "SUCCESSFUL" when the test finishes and instead relies on Ansi colors to convey that information. For our test infrastructure, where we are viewing the output in a browser that makes it harder to understand. The `details` model is really the best, only if it would print the full stack trace.

If I summarize the way we would like to review test execution is:
* [Optional, nice to have] At the start, before any tests start execution (before any test logs start to appear), print in tree mode what tests will be executed.
* [Required] During test execution, if some test throws exception, print the full trace to the console. It would be even better if that was done via `java.util.Logger` so we can redirect it using our own logging framework. But `System.out.println` also works.
* [Required]: At the end of all test execution, print a tree view of all tests runs and show the execution status (SUCCESS, FAILED, time taken etc). In this, it is okay to include a 1 liner of the exception if any for that test.

Let me know what you think.

**Comment by marcphilipp** [comment]
> At the start, before any tests start execution (before any test logs start to appear), print in tree mode what tests will be executed.

This would only be a partial tree since dynamic items such as parameterized test invocations won't be present before executing the tests.

> During test execution, if some test throws exception, print the full trace to the console. It would be even better if that was done via `java.util.Logger` so we can redirect it using our own logging framework. But `System.out.println` also works.

Did you know that you can [register your own](https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom) `TestExectionListener` via `ServiceLoader`? There's even a sample implementation for logging: `org.junit.platform.launcher.listeners.LoggingListener`.

> At the end of all test execution, print a tree view of all tests runs and show the execution status (SUCCESS, FAILED, time taken etc). In this, it is okay to include a 1 liner of the exception if any for that test.

Does the current `tree` mode meet your needs for this?

**Comment by swaranga** [comment]
>This would only be a partial tree since dynamic items such as parameterized test invocations won't be present before executing the tests.

I suspected that, so marked it as nice to have. This is not a big requirement.

>Did you know that you can register your own TestExectionListener via ServiceLoader?

Yeah, that is one option, if the current one does not meet my needs then I will have to implement one. They seems to be simple enough though. Thank you.

>Does the current tree mode meet your needs for this?

It does, only problem was that it would not print any test execution stack trace. I can implement the listener and this combined with the tree mode solves the problem.
