### ISSUE TITLE
TestFactory simply succeed when the method throws

### ISSUE THREAD

**Issue by kezhenxu94** [junit-team/junit5#2303]
## Steps to reproduce

Here is a reproducible test:

```java
    @TestFactory
    List<DynamicNode> tests() {
        int a = 1 / 0;  // intentionally throws
        return Arrays.asList(
            DynamicContainer.dynamicContainer(
                "dynamic container 1",
                Stream.of(
                    DynamicTest.dynamicTest("dynamic test 1", () -> fail("")),
                    DynamicTest.dynamicTest("dynamic test 2", () -> fail(""))
                )
            ),
            DynamicContainer.dynamicContainer(
                "dynamic container 2",
                Stream.of(
                    DynamicTest.dynamicTest("dynamic test 3", () -> fail("")),
                    DynamicTest.dynamicTest("dynamic test 4", () -> fail(""))
                )
            )
        );
    }
```

the test above succeeded if `int a = 1 / 0;` is present, and failed as expected if I remove it, showing 4 tests executed and all of them failed.

## Context

 - Used versions (Jupiter/Vintage/Platform):

```xml
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>5.6.0</version>
            </dependency>
```

 - Build Tool/IDE:

maven-failsafe-plugin, with all necessary dependencies configured

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.0.0-M4</version>
                <dependencies>
                    <!-- not important, thus omitted -->
                </dependencies>
            </plugin>
```

## Deliverables

I'm expecting the tests to be failed if the `TestFactory` method throws

**Comment by sbrannen** [comment]
When I execute the example, I get a failure for the `@TestFactory` method.

> java.lang.ArithmeticException: / by zero

Thus, there must be an issue with Maven Surefire/Failsafe.

**Comment by kezhenxu94** [comment]
> When I execute the example, I get a failure for the `@TestFactory` method.
> 
> 
> 
> > java.lang.ArithmeticException: / by zero
> 
> 
> 
> Thus, there must be an issue with Maven Surefire/Failsafe.

Did you run in the IDE? It succeeds in my IDE too, so it is an issue of maven Surefire plugin right?

**Comment by sbrannen** [comment]
> > When I execute the example, I get a failure for the `@TestFactory` method.
> > > java.lang.ArithmeticException: / by zero
> > 
> > 
> > Thus, there must be an issue with Maven Surefire/Failsafe.
> 
> Did you run in the IDE?

Yes.

> It succeeds in my IDE too, so it is an issue of maven Surefire plugin right?

That's correct. In light of that, I am closing this issue.

Please open an issue in the [Maven Surefire issue tracker](https://issues.apache.org/jira/projects/SUREFIRE/issues/SUREFIRE-1751?filter=allopenissues) to have it fixed there.

**Comment by kezhenxu94** [comment]
Thanks anyway
