### ISSUE TITLE
JUnit jupiter should support @Test methods that return Void

### ISSUE THREAD

**Issue by PashaTurok** [junit-team/junit5#2304]
Currently JUnit Jupiter ignores the following test:

```java
   @Test
    public Void myTest() {
       ...
        return null;
    }
```

I am sure, that such test must be supported as this is totally to java language specs. Or I misunderstand something?

**Comment by sbrannen** [comment]
JUnit Jupiter does not support `@Test` methods that return anything.

Having a return type of `void` meets that requirement.

Having a return type of `Void` does not meet that requirement.

Since JUnit Jupiter does not support a return value, there should be no need to use `return null;` in a `@Test` method. 

If you wish to return from the test method prematurely, you may simply invoke `return;` instead of `return null;`.

**Comment by PashaTurok** [comment]
@sbrannen Thank you for quick answer. However, I can't agree with you. I have Void type and return null not because I like it, but because I want to use interfaces with generics as it gives me very flexible features. About `return null` please see https://stackoverflow.com/questions/676663/what-do-i-return-if-the-return-type-of-a-method-is-void-not-void

**Comment by sbrannen** [comment]
**Team Decision**: Closing this issue in light of https://github.com/junit-team/junit5/issues/2304#issuecomment-631363978.

**Comment by PashaTurok** [comment]
@sbrannen That's wrong in light of  https://github.com/junit-team/junit5/issues/2304#issuecomment-631366812

**Comment by sbrannen** [comment]
> @sbrannen Thank you for quick answer. 

You're welcome.

> I have Void type and return null not because I like it, but because I want to use interfaces with generics as it gives me very flexible features.

The return type of a `@Test` method should not be influenced by any interfaces with generics that you may be using. If you find the opposite to be true, you should rethink the design of your test interfaces.

**Comment by PashaTurok** [comment]
@sbrannen Please, read the link I provided. `Use return null. Void can't be instantiated and is merely a placeholder for the Class<T> type of void.`. What I do with interfaces is what I think I should do with them. The question is not about my test design. The question is about void vs Void and as Junit supports it (I mean how it doesn't support it).  

So, again, it is wrong to close this issue.

**Comment by sbrannen** [comment]
The JUnit 5 team is aware of the differences between `void` and `Void`, and as previously stated, JUnit Jupiter does not support `@Test` methods with anything other than a `void` return type.

Consequently, the aforementioned "team decision" stands, and I think we'll just have to agree to disagree on this subject.
