### ISSUE TITLE
DynamicContainer to support an optional Executable

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2305]
I've just had my first attempt to use `TestFactory` "in anger". The idea is to take the output from EngineTestKit, rebuild the `TestDescriptor` hierarchy generated by the testkit run, and transform that hierarchy into a series of dynamic tests and containers. In this way, individual failures inside the testkit run will be directly reported in the top-level testing framework rather than swallowed up in the low-level test run and only reported "in aggregate" at the top-level.

Anyway, while implementing this I discovered that while `TestDescriptor`s in a JUnit Platform test hierarchy can be _both_ a container and a test, in the dynamic testing interface these are mutually exclusive - a DynamicNode can be ~both~ either  a `DynamicTest` or a `DynamicContainer`, but not both. It seems to me to be a bit of a capability gap in the dynamic testing interface that it can't generate dynamic test nodes that cover the full gamut of functionality available in `TestDescriptor`s. 

For a real-world example of a test hierarchy with a TestDescriptor that is both a container and a test, consider the case in Jupiter (or JUnit 4) where a test class has several test methods that all pass, but then it has an `@AfterAll/@AfterClass`-annotated method that throws an exception (this is the exact real-world situation I encountered in my experiment above and led to this feature request). 

In my case, I have a workaround - to add a `DynamicTest` child to the `DynamicContainer` that represents my `TestDescriptor` container, which carries the execution state of the `TestDescriptor` container. However, IMO it is visually not quite as nice as how (eg) a failed `@AfterAll` method is represented in the regular hierarchy, and (again IMO) it would be nice if testing developers had the option.

## Deliverables

A few of options:
* Add an optional `Executable` property to `DynamicContainer`.
* Add optional children property to `DynamicTest`.
* Come up with a third class `DynamicContainerTest` that requires both properties. If `DynamicTest` and `DynamicContainer` had been interfaces this could have simply been through multiple inheritance (which would probably have been the best option) but I think that ship has sailed...

_Edit: fixed potentially confusing typo_

**Comment by marcphilipp** [comment]
When would the `Executable` be called? Before or after the children? Wouldn't two executables (one for before, one for after) make more sense?

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_.

**Comment by Mincol** [comment]
I would like to see 4 executables emulating `@BeforeAll, @BeforeEach , @AfterEach and @AfterAll`
