### ISSUE TITLE
Is there a way to use the unicode theme via the Gradle plugin?

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#2307]
https://stackoverflow.com/q/62054470/206466 (I also asked on the gradle slack)

is there any way to use the unicode theme (are there others?) via the gradle plugin? if not is there an API I can tell them about as a request to enable it?

**Comment by sbrannen** [comment]
I don't think the Gradle `test` task uses the `ConsoleLauncher` at all.

But @marcphilipp can provide further details.

**Comment by JasonHK** [comment]
I have a similar question. I world like the result to display tree-like structure in Gradle. I've searched through the documentation nor the internet, but found nothing.

**Comment by marcphilipp** [comment]
> I don't think the Gradle `test` task uses the `ConsoleLauncher` at all.

That's right.

> I world like the result to display tree-like structure in Gradle. I've searched through the documentation nor the internet, but found nothing.

Please raise an issue with Gradle to add that functionality.
