### ISSUE TITLE
@DisplayName not working when used with @ParameterizedTest

### ISSUE THREAD

**Issue by JasonHK** [junit-team/junit5#2308]
## Steps to reproduce

```java
@DisplayName("RandomTest")
public class RandomTest
{
    @Test
    @DisplayName("Test")
    void test() {}

    @DisplayName("Parameterized Test")
    @ParameterizedTest()
    @ValueSource(bytes = { 0, 1, 2 })
    void parameterizedTest() {}
}
```

I expect it to print the following result:

```
RandomTest > Test PASSED

RandomTest > Parameterized Test > [1]  PASSED

RandomTest > Parameterized Test > [2]  PASSED

RandomTest > Parameterized Test > [3]  PASSED
```

But it actually printed this:

```
RandomTest > Test PASSED

RandomTest > [1]  PASSED

RandomTest > [2]  PASSED

RandomTest > [3]  PASSED
```

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.6.2
 - Build Tool/IDE: Gradle

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
When you say "it" in "it actually printed", what do you mean by "it"?

**Comment by JasonHK** [comment]
> When you say "it" in "it actually printed", what do you mean by "it"?

@sbrannen I mean JUnit.

**Comment by marcphilipp** [comment]
That's a limitation of Gradle which only prints the enclosing class (`RandomTest`) and the leaf test. Please raise an issue with Gradle to have this improved.
