### ISSUE TITLE
preDestroyTestInstance not able to get test instance from context if postProcessTestInstance failed

### ISSUE THREAD

**Issue by joerg1985** [junit-team/junit5#2312]
## Overview

JUnit is treating an exception inside the `postProcessTestInstance` method like an `Exception` in the constructor, but the instance has been created and should (in my mind) be accessible for proper termination.

Even if the behavior is desired and the context should not contain the not proper initialized instance, the call to `preDestroyTestInstance` is somewhat useless without the corresponding instance. 

Perhaps the `preDestroyTestInstance` signature could be extended with the `testInstance` (like the `postProcessTestInstance`)?

Thanks in advance

## Steps to reproduce

```java
        @Override
        public void postProcessTestInstance(Object testInstance, ExtensionContext context) throws Exception {
            throw new IllegalStateException();
        }

        @Override
        public void preDestroyTestInstance(ExtensionContext context) throws Exception {
            context.getRequiredTestInstance().disconnect(); 
       }
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.6.1

**Comment by sormuras** [comment]
The API documentation doesn't describe this case for when `postProcessTestInstance` doesn't terminate normally: https://junit.org/junit5/docs/snapshot/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/TestInstancePostProcessor.html -- at least, that should be clarified.

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by marcphilipp** [comment]
_in progress_
