### ISSUE TITLE
Remove ExtensionPoint, ExtensionRegistrar, Position etc. and simplify implementation of JUnit 5 TestEngine

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#232]

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
The _work in progress_ can be viewed here: https://github.com/sbrannen/junit5/commits/issue232-simplified-extension-model

And an official PR is forthcoming.

**Comment by sbrannen** [comment]
See PR #237

**Comment by sbrannen** [comment]
Merged into `master` in 434a3609f4b0a80fdeeac4a35f7c4b03bd2138d5.
