### ISSUE TITLE
Move Assertions.fail example to Assertions.fail(String)

### ISSUE THREAD

**Issue by Marcono1234** [junit-team/junit5#2321]
Currently the explanation for the return value of `Assertions.fail` and an example for it exists for `Assertions.fail(String, Throwable)`:
https://github.com/junit-team/junit5/blob/be2aa2497a75dedceb37bc3297276e230fb4f293/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java#L117-L128

However, the example does not fit because it does not use the `fail(String, Throwable)` overload. Would it therefore make sense to move the return value explanation and the example to `fail(String)` and link to that from the other `fail` overloads instead?

**Comment by marcphilipp** [comment]
> Would it therefore make sense to move the return value explanation and the example to `fail(String)` and link to that from the other `fail` overloads instead?

Good catch, I think that would indeed be better!

@Marcono1234 Would you be interested in submitting a small PR for this? Please note, that the Javadoc of `fail(Supplier)` also has to be changed.
