### ISSUE TITLE
no argument constructor causes super classes @BeforeAll to no be invoked

### ISSUE THREAD

**Issue by donahchoo** [junit-team/junit5#2325]
I'm using JUnit 5.6.2.  If my test class has a no argument constructor the parent classes @BeforeAll method is not invoke.

## Steps to reproduce

Create a test class that has a no argument constructor.

```
public class MyTest extends IntegrationTestParent {
    public String aVar = null;
    public void MyTest() {
         aVar = "hi";
    }
}

public class IntegrationTestParent {
    @BeforeAll
    public static void beforeIntegrationTests() {
        System.out.println("super class");
   }     
}
```

It does not appear I can workaround this by calling the super class's `@BeforeAll` method manual.  It appears that the presence of the constructor in the test class causes `@BeforeAll` to not be invoked at all.  IE, this will not work around the problem.

```
@BeforeAll 
    public static void setupMyTest() {
        IntegrationTestParent.beforeIntegrationTests();
    }
```

I'll default to `@BeforeEach`, it's wasteful but it's a workaround.
## Context

 - JUnit 5.6.2
 - IntelliJ and Gradle 5.6.

**Comment by sbrannen** [comment]
`public void MyTest()` is not a constructor. Rather, it is a void-returning method named `MyTest()`.

Given the following...

```java
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class MyTest extends IntegrationTestParent {

	String aVar = null;

	public MyTest() {
		this.aVar = "hi";
	}

	@Test
	void test() {
		System.out.println("test(): " + this.aVar);
	}
}

class IntegrationTestParent {

	@BeforeAll
	static void beforeIntegrationTests() {
		System.out.println("super class");
	}
}
```

The output is:

```
super class
test(): hi
```

In light of the above, I am closing this issue.

If you find that you continue to have problems, feel free to post back here with additional information.

**Comment by donahchoo** [comment]
Sorry that was a copy paste error.  The constructor should not have had `void` in it.  I edited the original.  you are right, though I thought I could reproduce this in a simple case but I can't.  If you have any thoughts as to what might cause this in a more complicated setup (that I can't share) I would welcome the info.

**Comment by sbrannen** [comment]
Glad you figured it out!

Did you perhaps switch the test instance lifecycle at some point?
