### ISSUE TITLE
Allow tests in local classes when using Test Kit

### ISSUE THREAD

**Issue by JojOatXGME** [junit-team/junit5#2330]
When I write tests using test kit, I usually have to create two tests. The actual tests and the test that is executed by the actual test. I build a few utils for myself to accommodate this pattern.

```java
@Test
void actual_test() {
  EngineExecutionResults results = JUnitTestKitUtil.runTest(getClass(), "mock_test");
  results.testEvents().assertThatEvents().haveExactly(1, EventConditions.finishedWithFailure(
      TestExecutionResultConditions.instanceOf(AssertionFailedError.class),
      TestExecutionResultConditions.message("EXPECTED")));
}

@MockTest
void mock_test() {
  Assertions.fail("EXPECTED");
}
```

`JUnitTestKitUtil.runTest(…)` runs the given test using *Test Kit*. `@MockTest` adds a tag and ensures that the test is disabled if it is not executed using `JUnitTestKitUtil.runTest(…)`.

However, I think splitting the scenario (`mock_test`) and the assertions into two separate methods makes it more difficult to follow. Therefore, I would appreciate it if I could refactor the tests to use local classes.

```java
@Test
void actual_test() {
  final class Scenario {
    @MockTest // Maybe I wouldn't even need to have this separate annotation anymore.
    void mock_test() {
      Assertions.fail("EXPECTED");
    }
  }

  EngineExecutionResults results = JUnitTestKitUtil.runTest(Scenario.class);
  results.testEvents().assertThatEvents().haveExactly(1, EventConditions.finishedWithFailure(
      TestExecutionResultConditions.instanceOf(AssertionFailedError.class),
      TestExecutionResultConditions.message("EXPECTED")));
}
```

Unfortunately, `TestContainerResolver.resolveElement(AnnotatedElement,TestDescriptor)` filters any local classes by calling `isPotentialCandidate(clazz)`.  I would like to have an option to include such class in certain situations. I could imagine two way to enable the usage of such classes.

1. Add an option to allow the usage of local classes (and maybe other classes).
2. Accept such classes even when they don't qualify if thy where explicitly selected by a `ClassSelector` or `MethodSelector`.

**Comment by marcphilipp** [comment]
FWIW we explicitly exclude local classes here:
https://github.com/junit-team/junit5/blob/3f7fed61f2edcee2a5551dbde75382b1dbe21267/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsPotentialTestContainer.java#L40-L42

I agree that it would be useful to be able to write tests in this way. We could think about differentiating whether a class was explicitly selected via a `ClassSelector` and allow local classes in that case. Alternatively, we could introduce a config parameter to allow local classes that `EngineTestKit` could set. It would be a little weird for `EngineTestKit` to set a Jupiter-specific config parameter by default, though.

@junit-team/junit-lambda Thoughts?

**Comment by marcphilipp** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Since local classes are non-static we cannot instantiate the local class without an instance of the enclosing test class. Since `EngineTestKit` does not have access to the enclosing instance, there's no straightforward way of implementing this. Thus, we decided to close this issue for now.

**Comment by JojOatXGME** [comment]
That is right. I didn't thought about that the class may not be static. Anyway, I just had another idea that I wanted to discuss. Since this ticket is closed and the feature request looks somewhat different, I created the separate ticket #2331.
