### ISSUE TITLE
How to add testcase description in junit xml.

### ISSUE THREAD

**Issue by rgaikwad008** [junit-team/junit5#2332]
![image](https://user-images.githubusercontent.com/58168151/85106095-3fae1d00-b229-11ea-9d48-05d0f3b3ef75.png)

We need to add multi-line description with scenario so that we get it in junit xml but it seems junit is not supporting description in junit xml currently.

**Comment by rgaikwad008** [comment]
If description is not in the standard syntax, can name attribute be multi-line in test-case tag?

**Comment by marcphilipp** [comment]
As I said, we're not maintaining any XML schemas in this project.
