### ISSUE TITLE
Rename Alphanumeric Orderer to MethodName

### ISSUE THREAD

**Issue by gaganis** [junit-team/junit5#2334]
With the introduction of `DisplayName` orderer in https://github.com/junit-team/junit5/commit/6fee44dc95b1cf49d85166d93a861ce0a9483d68, the name of the `Alphanumeric` orderer becomes ambiguous ie "Alphanumeric of what?". I believe then that `MethodName` would be a better name for that orderer. It is unambiguous, it clearly states what it is using for ordering the tests and it is consistent with the new orderer `DisplayName`. 

## Deliverables
I guess since this has been published we would need to deprecate it add the renamed one as a delegator?

If it sounds good and the exact process of changing is clear or decided(deprecation? straight rename?) I would be happy to submit a PR for this.

**Comment by juliette-derancourt** [comment]
I agree that it can be a bit confusing 👍

**Comment by juliette-derancourt** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_

**Comment by gaganis** [comment]
Went ahead and created #2336 at least as an opportunity to brush-up my junit5 commiting skills and dev environment ;) 

:crossed_fingers: you agree and it proves valuable

Stay frosty!
Giorgos

**Comment by gaganis** [comment]
> ...  brush-up my junit5 commiting skills ...

Which skills have become quite dusty if I look at my spectacular failure in CI... :flushed:

**Comment by marcphilipp** [comment]
**Team decision:** Let's deprecate `Alphanumeric` and introduce `MethodName`.
