### ISSUE TITLE
Parametrized CSV tests do not accept integer literals with underscore "_"

### ISSUE THREAD

**Issue by SvitlanaMo** [junit-team/junit5#2335]
Relates to JUnit 5.6.2

JUnit 5 does not allow using integer literals with underscore in the CSV parameters of parameterized tests. 

Such literals are valid as described in https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html (Using Underscore Characters in Numeric Literals.)

## Steps to reproduce

 ```java
    @ParameterizedTest(name = "Testing Divisors.gcd ({0}, {1} -> {2})")
    @CsvSource({
        "-2_147_483_648, 400, 16",
    })
    void testDivisors_gcd(int input1, int input2, int output) {
        assertEquals(output, Divisors.gcd(input1, input2));
    }
```
It triggers the following error:
```
Error converting parameter at index 0: Failed to convert String "-2_147_483_648" to type java.lang.Integer
```
## Context

 - Used versions (Jupiter/Vintage/Platform): NA
 - Build Tool/IDE: Sublime

## Deliverables

- [ ] NA

Thank you!

**Comment by sbrannen** [comment]
Note that JUnit Jupiter uses `Integer::decode`, etc. in `org.junit.jupiter.params.converter.DefaultArgumentConverter.StringToPrimitiveConverter`.

JUnit Jupiter does not support the parsing of underscores in numeric literals, because the JDK itself does not support that.

- https://bugs.openjdk.java.net/browse/JDK-8179313
- https://bugs.openjdk.java.net/browse/JDK-6863378

**Comment by marcphilipp** [comment]
**Team decision:** We'd prefer to stay with Java's "defaults" here. You could write your own `ArgumentConverter` and register it on each method parameter with `@ConvertWith` or a composed annotation.

**Comment by marcphilipp** [comment]
**Revised team decision:** As a Christmas present, we've changed our my mind based on the simplicity of the implementation in #2425.

**Comment by SvitlanaMo** [comment]
Thank you very much for excellent news! Happy Holidays to you!

Svitlana
