### ISSUE TITLE
InvocationInterceptor does not intercept @ParameterizedTest methods

### ISSUE THREAD

**Issue by andreoss** [junit-team/junit5#2338]
`InvocationInterceptor` does not intercept methods annotated with `@ParameterizedTest`, but works fine on `@Test` methods with parameters and a custom `ParameterResolver`.

Is there a way to intercept `@ParameterizedTest` method?

## Steps to reproduce

```java
class EveryTestFails implements Extension, InvocationInterceptor {
    @Override
    public void interceptTestMethod(
        Invocation<Void> invocation,
        ReflectiveInvocationContext<Method> invocationContext,
        ExtensionContext extensionContext
    ) throws Throwable {
        Assertions.fail();
    }
}

@ExtendWith(EveryTestFails.class)
public class StreamTest {

    @Test
    void failsAsExpected() {
         // THIS FAILS
    }

    @ValueSource(ints = {1,2,3})
    @ParameterizedTest
    void failsAsExpected(final int x) {
        // THIS DOES NOT FAIL
    }
}
```

## Context

 - Used versions (Jupiter/Vintage/Platform):  5.7.0-M1

**Comment by juliette-derancourt** [comment]
I believe `InvocationInterceptor.interceptTestTemplateMethod()` might satisfy your need? It works in your example at least :)

**Comment by marcphilipp** [comment]
Juliette's right, `interceptTestTemplateMethod()` is what you're looking for.

**Comment by andreoss** [comment]
@marcphilipp Thanks, it would be nice to have `@ParameterizedTest` mentioned in the javadoc of `InvocationInterceptor`.

**Comment by marcphilipp** [comment]
Point taken. Added in 6525e176bc53ddc9d6f8471376b5faf1569e3192.
