### ISSUE TITLE
Fully document Launcher and Engine APIs

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#234]
### Rationale

We want IDE and build tool vendors to start consuming these APIs starting with M1.

### Deliverables

- [x] Document all `public` APIs in the `junit-launcher` module.
- [x] Document all `public` APIs in the `junit-engine-api` module.
  - [x] Document `AbstractTestDescriptor`, including its intended usage
  - [x] Document `HierarchicalTestEngine.execute()`
  - [x] Improve documentation of `Node.execute()` by explaining that containers typically do not implement `execute()` since the `HierarchicalTestEngine` handles execution of children.

**Comment by bechte** [comment]
I will take care of adding documentation.

**Comment by marcphilipp** [comment]
Unassigning from @bechte for now.

**Comment by sbrannen** [comment]
This issue is _blocked_ until #44 has been completed.

**Comment by sbrannen** [comment]
This issue is no longer _blocked_.

In addition, the _Deliverables_ have been updated.

**Comment by marcphilipp** [comment]
I'm starting to work on this issue.

**Comment by sbrannen** [comment]
What's left to document:

- [ ] NameBasedSelector
- [ ] ReportEntry.appendDescription()
- [ ] AbstractTestDescriptor
- [ ] EngineDescriptor
- [ ] HierarchicalTestEngine.execute()

**Comment by sbrannen** [comment]
Closing this issue since all sub-tasks have been completed in `master`.

In addition, the fate of `ReportEntry.appendDescription()` will be now addressed in #293
