### ISSUE TITLE
Generate dynamic test nodes from Test Kit results

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2343]
We have been using `EngineTestKit` to test our Jupiter extensions. I (along with others) have expressed our concerns about the clumsiness of using `Conditions` and `assertThatEvents()`, so we came up with a couple of alternative approaches. 

For reference, please see https://github.com/osgi/osgi-test/blob/ce0638e30460f3a45af4ace1bf8132dc28ee6eb7/org.osgi.test.junit5/src/test/java/org/osgi/test/junit5/context/DynamicNodeGenerator.java and its calling context https://github.com/osgi/osgi-test/blob/ce0638e30460f3a45af4ace1bf8132dc28ee6eb7/org.osgi.test.junit5/src/test/java/org/osgi/test/junit5/context/BundleContextExtensionTest.java#L90-L159

In this strategy, we had a test class which we were using to drive the testkit, and all of the tests in the test kit were expected to pass (note that this strategy is not useful where you're testing some scenarios in which the tests are expected to fail). So we wrote some code to:

1. capture all of the test events from the testkit's execution run;
2. find the root TestDescriptor among the captured events;
3. traverse the captured test hierarchy and transform each `TestDescriptor` into a `DynamicContainer`/`DynamicTest` node as appropriate; *(this step provides some context to the request in #2305; see below)*
4. return the root dynamic node from a `@TestFactory` method.

I feel that this approach worked really well. It had a number of advantages:

1. The test output is more informative - you can see all the tests that testkit ran.
2. The output is more readable than asserting on events using conditions (assuming that you've used sensible names for the test classes and methods that you passed in to testkit).
3. If one of the tests fails, it will have an associated stack trace which is reported through the normal mechanisms. In most IDEs, this means that you can click on the stack trace in the test results window and be taken directly to the point in your code where the exception/assertion was generated, and start debugging straight away.

One disadvantage is that there is no direct mapping to `DynamicNode`s for `TestDescriptor`s that are both containers (ie, have their own children) and tests (ie, have their own execution result). This was the motivation for #2305. We got around this by creating `DynamicContainer` nodes and adding an extra `DynamicTest` to them to represent the execution resolve of the container itself:
https://github.com/osgi/osgi-test/blob/ce0638e30460f3a45af4ace1bf8132dc28ee6eb7/org.osgi.test.junit5/src/test/java/org/osgi/test/junit5/context/DynamicNodeGenerator.java#L40

This technique will not be useful in all circumstances - for example, if you want to assert that certain tests have failed, or if you need to verify the correctness of the actual structure of the test hierarchy and not just the test results. However, there might be enough scenarios in which it could be useful that the JUnit team may wish to consider adapting it and transplanting it into the testkit implementation itself for others to use.

**Comment by marcphilipp** [comment]
**Team decision:** We believe this use case is too specialized to be of general use.
