### ISSUE TITLE
Provide more direct access to actual results in EngineExecutionResults

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2344]
As a follow-up to #2343:

In our `DynamicNodeGenerator` implementation, we had to jump through some hoops to re-create the test hierarchy, as the information is not directly provided by the testkit's `EngineExecutionResults`. I think it would be useful if `EngineExecutionResults` provided access to the following:

1. Access to the root `TestDescriptor` generated by the execution run;
2. A mapping function which, when supplied with a `TestDescriptor` instance, will return the corresponding `TestExecutionResult` instance generated for that test.

For example:

```java
public class EngineExecutionResults {
  public TestDescriptor getRootDescriptor() {...}

  public TestExecutionResult getResultFor(TestDescriptor test) {...}

  // Although we didn't have a need for it, the following two would be useful in other cases too:
  public ReportEntry getReportEntryFor(TestDescriptor test) {...}

  public String getSkippedReasonFor(TestDescriptor test) {...}
}
```

In this way, rather than the meta-test needing to be concerned about verifying the order and correctness of low-level test events (something that I believe that `ExecutionRecorder` should handle directly), they can be more concerned about examining and asserting on the the actual test results (which are more likely to be of interest to a higher-level test). Assertion frameworks like AssertJ and Truth can then also come up with their own custom assertions that operate directly on the test results.

**Comment by marcphilipp** [comment]
> Access to the root `TestDescriptor` generated by the execution run;

With the current API this is already possible, although a bit inconvenient: you'd have to find the first execution started event in the result.

> A mapping function which, when supplied with a `TestDescriptor` instance, will return the corresponding `TestExecutionResult` instance generated for that test.

How would you find the right `TestDescriptor` for looking that up? Wouldn't it be more useful to specify that as a condition/predicate, e.g. using its display name?

**Comment by kriegfrj** [comment]
> > Access to the root `TestDescriptor` generated by the execution run;
> 
> With the current API this is already possible, although a bit inconvenient: you'd have to find the first execution started event in the result.
> 

Correct. I have code that does this - it finds all of the "started" and "finished" events so that it can 1. find the TestDescriptor with no parent (ie, the root) and 2 store a map of `TestDescriptor` to `TestExecutionResult`. If this is a common use case for TestKit then it might be worth TestKit providing more direct support for it.

> > A mapping function which, when supplied with a `TestDescriptor` instance, will return the corresponding `TestExecutionResult` instance generated for that test.
> 
> How would you find the right `TestDescriptor` for looking that up?

Once you have the root `TestDescriptor`, you can traverse the hierarchy to find the node that you're looking for. Given that you ran the test, you should know what kind of output you're looking for.

> Wouldn't it be more useful to specify that as a condition/predicate, e.g. using its display name?

That might be useful in some circumstances too. But suppose you've already got a reference to a `TestDescriptor` object (eg, by traversing the hierarchy) - it would be nice to have a more direct way to get the result corresponding to that specific descriptor rather than have to take a more indirect route (not to mention possibly less accurate route - what if you use a condition that happens to match multiple TestDescriptors other than the one that you were specifically interested in, and you didn't realise?). 

I suppose if we provide a single `getResult()` method that takes a condition or a predicate to match on a `TestDescriptor`, and then you can call `getResult(testDescriptor::equals)` to get the result for your particular test descriptor. That would maximise your flexibility.

Actually, we could provide a series of methods for convenience:

`TestExecutionResult getRequiredResult(Predicate<? super TestDescriptor> criterion)` // this should throw an assertion error if it doesn't find exactly one result
`Optional<TestExecutionResult> getResult(Predicate<? super TestDescriptor> criterion)` // this should perhaps throw an assertion error if it finds more than one result
`List<TestExecutionResult> getResults(Predicate<? super TestDescriptor> criterion)` // use this one when you're expecting possibly more than one match; returns them in the order they were encountered.

I do find the condition/predicate approach useful as a way of trying to "select" the test that you are trying to check; however the diagnostic messages are horrible. Custom assertions are much better. I know that the current implementation uses AssertJ assertions for the condition asserts under-the-hood, but even the current maintainer of AssertJ says he's not a fan of conditions and they're mainly in there for backward compatibility reasons (he inherited them from the now-defunct FEST project that AssertJ is a fork of). He prefers custom assertion classes in most circumstances. With something like the above methods, we can get the best of both worlds - the flexibility using complicated predicates/conditions to select the result(s), and then using a custom assertion (could be Truth or AssertJ or something else) to assert on the result to give you more intelligible diagnostics.
