### ISSUE TITLE
Remove validation of proceed call count for InvocationInterceptor

### ISSUE THREAD

**Issue by rmannibucau** [junit-team/junit5#2345]
Hi,

org.junit.jupiter.engine.execution.InvocationInterceptorChain.ValidatingInvocation#markInvokedOrSkipped prevents to implement some retry like interceptors and I'm not sure what this validation intends so my request is to drop that validation or at least enable interceptors to disable it to avoid to have to use getExecutable().invoke() which bypasses interceptor chain.

Romain

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M2 solely for the purpose of _team discussion_

**Comment by marcphilipp** [comment]
> prevents to implement some retry like interceptors

That's actually on purpose because for a retry it's rarely enough to just invoke e.g. the test method again without the setup due to state in instance variables etc.

> at least enable interceptors to disable it to avoid to have to use getExecutable().invoke() which bypasses interceptor chain

You can already call `invocation.skip()` to disable the validation in case you have some other means of invoking the method. How would you pass method parameters to `getExecutable().invoke()`, though?

**Comment by rmannibucau** [comment]
@marcphilipp current impl looks like (simplified version):

        final Object[] args = invocationContext.getArguments().toArray(new Object[0]);
        final Object targetInstance = invocationContext.getTarget().orElse(null);
        for (int i = 0; i < config.maxRetries(); i++) {
            try {
                // invocation.proceed(); // junit5 prevents to call it > once today
                executable.invoke(targetInstance, args);
                invocation.skip(); // avoid to fail cause proceed() was not called
                return;
            } catch (final InvocationTargetException ae) {
                if (i == config.maxRetries() - 1) {
                    throw ae.getTargetException();
                }
                log.info("Retrying {} ({})", executable, ae.getTargetException().getMessage());
                sleep(config.pauseUnit().toMillis(config.pause()));
            }
        }

However, desired impl would be:

        for (int i = 0; i < config.maxRetries(); i++) {
            try {
                invocation.proceed();
                return;
            } catch (final InvocationTargetException ae) {
                if (i == config.maxRetries() - 1) {
                    throw ae.getTargetException();
                }
                log.info("Retrying {} ({})", executable, ae.getTargetException().getMessage());
                sleep(config.pauseUnit().toMillis(config.pause()));
            }
        }

A nice to have would be to extend ReflectiveInvocationContext, as EE one, to enable to do setParameters() for cases parameters are slightly modified but not required for this particular ticket.
