### ISSUE TITLE
@ParameterizedTest does not fire any events in TestWatcher

### ISSUE THREAD

**Issue by HardNorth** [junit-team/junit5#2355]
JUnit version: 5.6.0

## Steps to reproduce
Our team develops a reporting tool (ReportPortal) and for sake of reporting we need to know when JUnit 5 skips tests. For regular `@Test` methods we can use `org.junit.jupiter.api.extension.TestWatcher.testDisabled` to catch disabled tests, but `@ParameterizedTest` does not trigger any methods in TestWatcher.

A test example:
```java
package junit5.features.parameters;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

public class EnumParametersTest {

	public enum TestParams {
		ONE,
		TWO
	}

	@Disabled("my disable reason")
	@ParameterizedTest
	@EnumSource(TestParams.class)
	public void testParameters(TestParams param) {
		System.out.println("Test: " + param.name());
	}
}

```

## Context

 - Used versions:
   - org.junit.jupiter:junit-jupiter-api:5.6.0
   - org.junit.jupiter:junit-jupiter-params:5.6.0
   - org.junit.jupiter:junit-jupiter-engine:5.6.0
   - org.junit.platform:junit-platform-launcher:1.6.0
   - org.junit.platform:junit-platform-runner:1.6.0
 - Build Tool/IDE:
   - IntelliJ IDEA

**Comment by marcphilipp** [comment]
@HardNorth Have you considered registering a `TestExcecutionListener` instead?

**Comment by HardNorth** [comment]
@marcphilipp Do you mean `EngineExecutionListener`? We implemented our reporter on top of extension API. And I believe listeners do not have enough features for us. We also report before/after methods, test and test suite structure, test parameters with an ability to specify parameter names, code references and many more. So we can't rely on just listeners. And for me it doesn't look right to make users register several listeners/extensions.

BTW thanks for the fix!
