### ISSUE TITLE
Using JUnit 5 parallelism support and Maven Surefire retry mechanism produces test log files containing tests that should not belong inside

### ISSUE THREAD

**Issue by aaronq** [junit-team/junit5#2361]
I have configured my tests to run in parallel with the following config:
```
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = same_thread
junit.jupiter.execution.parallel.mode.classes.default = concurrent
junit.jupiter.execution.parallel.config.strategy = fixed
junit.jupiter.execution.parallel.config.fixed.parallelism = 6
```
My junit-jupiter-version is 5.6.2 and junit-platform-version is 1.6.2

I'm running these tests with the maven surefire plugin (3.0.0-M4) and specifying the flag `surefire.rerunFailingTestsCount` to rerun failed tests.

I've run into a test results bug when I get a test failure, and the test gets rerun and passes on the retry.

When I look into the `TEST*.xml` files for each test class, I see some tests that belong to another test class, but show up in another test class's xml file. In the scenario above, I would see the result of `TestClassA#testA` in 2 different `TEST*.xml` files. In one test xml file, it would show up as failure, and in another it would show up as success (the rerun).

This messes up the reporting that happens when you look at the test reports in Jenkins when these XML files are archived by the junit plugin. It double counts the test in this case, and marks the build as unstable.

Is this a byproduct of running things in parallel and retrying test cases in surefire?

**Comment by marcphilipp** [comment]
Since Surefire writes these XML reports, I'm afraid you'll have to raise the issue with them.
