### ISSUE TITLE
Combining Multiple Extensions into One

### ISSUE THREAD

**Issue by ghunteranderson** [junit-team/junit5#2372]
When developing a test library I am torn on the composition of extension. Users of the library should only need to list one extension but often that extension has multiple responsibilities that would otherwise be broken down into multiple classes.

For example, a library might perform different tasks as different stages in the life cycle as well support parameter injection for different types. It would be helpful if the library developer could implement multiple extensions, one per task/responsibility, and use a Junit natively supported way of combining those into a single extension for the user. This makes the extensions less complex, more testable, and eases maintenance because of the separation of responsibilities.

One solution could be to add a CompositeExtension class to Junit that handles multiple extensions in the same way that Junit would when multiple extensions are listed using `@ExtendWith`. Developers could extend CompositeExtension and implement some method `protected List<Object> getExtensions()` with all extensions that should be included. This gives test library developers the flexibility of small single purpose extension without expecting users to explicitly list them all.

``` java
public abstract class CompositeExtension implements <all-junit-extension-interfaces> {
  
  protected abstract List<Object> getExtensions();
  
  @Override
  public void afterEach(ExtensionContext context) throws Exception {
    getExtensions().forEach(e -> e.afterEach(context));
  }

  // ... implement remaining methods in similar fashion
}
```

**Comment by marcphilipp** [comment]
You can achieve this by definining your own composed annotation and listing all extensions in one or multiple `@ExtendWith` annotations on that annotation definition. Would that work in your use case?

**Comment by ghunteranderson** [comment]
This works beautifully. I was able to use the snippet below and annotate test classes with `@MyCompositeExtension`. It would be nice if users could still use the `@ExtendWith` semantic but this works well too.
``` java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
@ExtendWith({
  ExtensionA.class,
  ExtensionB.class,
  ExtensionC.class,
  ExtensionD.class
})
public @interface MyCompositeExtension{}
```

I wasn't able to find this feature in the user guide or javadoc. If the Junit team is interested, I would not mind documenting it. Otherwise, I suppose this issue servers as a form of documentation.

Thanks for your help @marcphilipp

**Comment by sbrannen** [comment]
> This works beautifully.

Glad to hear that meets your needs!

> I wasn't able to find this feature in the user guide or javadoc.

[Support for meta-annotations](https://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotations) is documented in the User Guide; however, we don't explicitly state that a custom composed annotation is a good technique for composing extension registration.

In addition, the Javadoc for some annotations states that JUnit Jupiter annotations may be used as meta-annotations; however, the [Javadoc for `@ExtendWith`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtendWith.html) does not.

So, we could certainly add some documentation for this technique.

**Comment by marcphilipp** [comment]
> So, we could certainly add some documentation for this technique.

I agree.

**Comment by marcphilipp** [comment]
I've submitted #2373 to address this. @ghunteranderson Do you think you would have found this and it would have helped?

**Comment by ghunteranderson** [comment]
@marcphilipp Nice! That's the section I opened first when I was looking for a solution. Definitely helpful :)
Thanks for helping with this so quickly.
