### ISSUE TITLE
Add overload of DynamicTest.stream(…) that accepts a Stream

### ISSUE THREAD

**Issue by odrotbohm** [junit-team/junit5#2374]
It feels weird having to hand an `Iterator` to `DynamicTest.stream(…)`. Creating `Iterator`s usually requires an additional step from usual sources (collections, streams) that are usually easily createable via an `of(…)` factory method. So it would be cool if one could just write this:

```java
var source = Stream.of(…); // or List.of(…)

return DynamicTest.stream(source, …);
```

instead of 

```java
var source = Stream.of(…); // or List.of(…)

return DynamicTest.stream(source.iterator(), …);
```

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M2 for _team discussion_
