### ISSUE TITLE
Support named sources for DynamicTest.stream(…)

### ISSUE THREAD

**Issue by odrotbohm** [junit-team/junit5#2375]
I am trying to create a `Stream<DynamicTest>` from a set of different sources (read: different types) and the way that generics work makes this quite cumbersome. Here's an example from Spring HATEOAS:

```java
Links links = Links.NONE;
Link link = Link.of("/foo");
		
List<NamedLinks> sources = Arrays.asList(
		NamedLinks.of("via varargs", links.and(link)),
		NamedLinks.of("via Iterable", links.and(Arrays.asList(link))),
		NamedLinks.of("via Stream", links.and(Stream.of(link))));

return DynamicTest.stream(sources.iterator(), NamedLinks::getName,
		it -> assertThat(it.links.getRequiredLink(IanaLinkRelations.SELF)).isNotNull());
```

The test is supposed to verify that *different parameter types* (here: some object, an `Iterable` of objects, and a stream) handed to the `Links.and(…)` method lead to a certain result. Ideally, I would like to treat those as sources but that would just hand in the common supertype to the `ThrowingConsumer`, so that I cannot call `links.and(…)` anymore as those expect the concrete types. To work around this limitation I call the method beforehand and end up with `Links` consistently but am then unable to produce test names in the second parameter as I cannot distinguish the individual `Links` instances anymore.

I created `NamedLinks` myself to be able to already eagerly bind a name to use in the setup of `Dynamic.stream(…)` but I wonder if that could be made available by JUnit OOTB providing a simple value type `NamedSource<T>` that exposes a name and source `T`and an overload of `DynamicTest.stream(Stream<NamedSource<T>> sources, ThrowingCallable<T> callback)`.

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M2 for _team discussion_

**Comment by sbrannen** [comment]
Note that this is very similar to the `Named<T>` proposal in https://github.com/junit-team/junit5/issues/2301#issuecomment-640487091.

Thus, we should consider introducing a single such "named payload" type that can be used in multiple scenarios.

**Comment by sbrannen** [comment]
**Team Decision**: Moved to 5.8 backlog in light of pending 5.7 release.

**Comment by marcphilipp** [comment]
**Team decision:** Add these two static methods to `DynamicTest` after `Named<T>` has been added in #2301:

```java
public static <T> Stream<DynamicTest> stream(Iterator<? extends Named<T>> inputGenerator, ThrowingConsumer<? super T> testExecutor)
public static <T> Stream<DynamicTest> stream(Stream<? extends Named<T>> sources, ThrowingConsumer<? super T> testExecutor)
```

**Comment by odrotbohm** [comment]
Lovely, looking forward!
