### ISSUE TITLE
ExtendWith is allowed on TYPE and METHOD level only

### ISSUE THREAD

**Issue by khmarbaise** [junit-team/junit5#2376]
I'm working a longer time on an extension and thought about the `@ExtendWith` annotation. For my own extension it would make sense to define it on a package level but that does not work, cause `@ExtendWith` is limited to TYPE and METHOD level only. 

If `@ExtendWith` would support defining on a package level it could make usage simpler in some situations. This means it could be defined for a number of classes within a package or within the subpackages.

Is there a good reason not to do that? Or did I miss a thing ?

WDYT?

**Comment by sormuras** [comment]
...don't forget about the module level! :D

Closing as a duplicate of #1986

**Comment by sormuras** [comment]
#1990 might also provide a solution for your use-case.
