### ISSUE TITLE
Add project metadata to JAR manifest

### ISSUE THREAD

**Issue by aalmiray** [junit-team/junit5#238]
It would be great if JAR manifests contained additional information related to the project such as

    Manifest-Version: 1.0
    Built-By: ${user.name}
    Created-By: 1.8.0_92 (Oracle Corporation 25.92-b14)
    Build-Date: 2016-05-05
    Build-Time: 18:44:48.377+0200
    Build-Revision: 0ca4beaa67bd484f98fd46e776e31c89adfea234
    Specification-Title: ${project.name}
    Specification-Version: 5.0.0-ALPHA
    Specification-Vendor: junit.org

**Comment by sbrannen** [comment]
Merged PR into `master` in febd4b10d63358a1a1b9bec8cfede02c0abc4653.
