### ISSUE TITLE
Provide a concise test feed details mode for the ConsoleLauncher

### ISSUE THREAD

**Issue by rmannibucau** [junit-team/junit5#2381]
The ability to have a good report (tree) does not prevent to have some real time hints about executed tests.
Currently, these requirements are not fulfilled OOTB by the console launcher.
Would be great to have a listener logging each test being executed (a bit like surefire does "Running X") + the global report at the end.

**Comment by sormuras** [comment]
You may activate "some real time hints" by passing `--details=flat` to the Console Launcher program.

There's also the `--details=verbose` mode, which combines `flat` and `tree` modes.

If those (and other) OOTB listeners/printers don't fulfill your needs, consider to provide your own: [Plugging in your own Test Execution Listener](https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom)

**Comment by rmannibucau** [comment]
@sormuras verbose logs all internal details of junit (uniqueId and so on) which is useless most of the time, however all builds need to know what is currently running or in which order test were ran (using the log to track flacky tests) and have a summary for a quick review of the execution (in particular in case of failure). So I really think junit5 built-in listeners are not enough until you can use `--details=tree,flat` or something like that.
Last note being a custom listener is not an option in "application projects" in general so this would end up in a reusable module released outside junit5 whereas it benefits all junit5 users IMHO so I think it should be available OOTB.

**Comment by sbrannen** [comment]
Tentatively slated for 5.8 Backlog for _team discussion_

**Comment by rmannibucau** [comment]
Some more precise feedback:

I turned on flat instead of tree on my setup. Here are the conclusions:
- tree/summary enables to know which test failed easily
- flat enables to know which test hangs or is getting executed (don't assume a test is <1s ;))

=> both features are required at the same time

With flat, when there is a failure it is hard to know which test until you go in the xml report which is not that readable or even browsable - at least in CLI without xml tools.
With tree I have to jstack the console launcher process to know what happens - if possible, in some cases it does not help.

Therefore I really think that combining listeners is required to make the experience at least not worse than alternate existing runners.

**Comment by marcphilipp** [comment]
**Team decision:** Add a new `testfeed` details mode and make `--details` take a comma-separated list of modes.

The output would look similar to this (fewer/more blank lines up for debate):
```
JUnit Jupiter > Some container display name > Some nested container display name > Some test display name STARTED
JUnit Jupiter > Some container display name > Some nested container display name > Some test display name SUCCEEDED

JUnit Jupiter > Some container display name > Some nested container display name > Some other test display name SKIPPED
    Reason: ...

JUnit Jupiter > Some container display name > Some nested container display name > Some failing test display name STARTED

JUnit Jupiter > Some container display name > Some nested container display name > Some failing test display name FAILED/ABORTED
   java.lang.AssertionError: some message
       at SomeClass.java:42

JUnit Jupiter > Some container display name > Some nested container display name > Yet another test display name STARTED
JUnit Jupiter > Some container display name > Some nested container display name > Yet another test display name SUCCEEDED
```

**Comment by marcphilipp** [comment]
@rmannibucau Would that suit your needs?

**Comment by rmannibucau** [comment]
@marcphilipp perfectly, thanks a lot!

**Comment by leonard84** [comment]
My only question would be, whether the test names are escaped? E.g. how would a test like this be logged `@DisplayName("test a > b")`, same with `\n` and oder special chars.

@rmannibucau what is the intended audience, a human or a maschine?

**Comment by rmannibucau** [comment]
@leonard84 clearly a human, machine audience only uses file reports (legacy xml until there is a new standard).

**Comment by marcphilipp** [comment]
> My only question would be, whether the test names are escaped?

Since this intended for human consumption, I don't think we need to escape `>`.

**Comment by rmannibucau** [comment]
up, any hope to get it in a coming release?
