### ISSUE TITLE
Ask IntelliJ to support `@EnabledIf`/`@DisabledIf`

### ISSUE THREAD

**Issue by juliette-derancourt** [junit-team/junit5#2385]
We should file an issue on [IntelliJ issue tracker](https://youtrack.jetbrains.com) to ask them to support the new `@EnabledIf`/`@DisabledIf` feature.
I was testing those, and the condition methods used in the annotations are (rightfully) marked as unused, which is not ideal.

## Deliverables

- [x] File the issue when JUnit Jupiter 5.7 is released

**Comment by sormuras** [comment]
@akozlova -- would it be possible to offer a similar user experience like IDEA does for `@MethodSource` in the realm of parameterized tests?

**Comment by juliette-derancourt** [comment]
Issue submitted [here](https://youtrack.jetbrains.com/issue/IDEA-251100).

**Comment by marcphilipp** [comment]
Thanks, @juliette-derancourt! 👍
