### ISSUE TITLE
Junit5 & Wiremock & Multiples tests cause failure

### ISSUE THREAD

**Issue by CyrilGermain** [junit-team/junit5#2389]
Dear all,

I obtain a test failure with the **java.io.IOException: Failed to bind to /0.0.0.0:8081** exception.

Please find the project structure below : 

ProjectBase
+ src
  + main
   | + java
   |  |+ com.mypackage
   |  |   + MockApplication.java
   | + Resources
   |    + application.properties
  + Test
     + java
        + com.mypackage
           + AbtractTestClass
           + Unit1Test.class
           + Unit2Test.class

The whole project is built and tested with maven and JUnit. The Junit-jupiter-engine version is 5.6.2.

The AbstractTestClass.java : 
`
public abstract class AbstractTestClass{
  protected static int PORT = 8081;
  protected static MockApplication mockApi;
  
  @BeforeAll @SneakyThrows
  public static void init(){
    mockApi = new MockApplication(PORT);
    mockapi.init().start();
  }
}
`

The two other classes are very semblable : 

`
@DisplayName("Unit1Test")
@DirtiesContext
public class Unit1Test extends AbstractTestClass{
   @Test 
   public void test1(){
      HttpGet get = new HttpGet(MOCK_API_URL);
      HttpResponse response = httpClient.execute(get);
      assertEquals(HttpStatus.OK.value(), response.getStatusLine().getStatusCode());
   }
}
`
If I ran tests separately, everything is fine. but if I try to run it by maven or intelliJ, the first-class runs perfectly, but the second fails with the **java.io.IOException: Failed to bind to /0.0.0.0:8081** .

Any advice?

Thanks,

Cyril GERMAIN

**Comment by marcphilipp** [comment]
The `@BeforeAll` method is inherited to your concrete test classes and executed once before all tests in `Unit1Test` and once before `Unit2Test`. Since you never seem to stop your `MockApplication`, the second call to `start()` fails. You should probably add a `@AfterAll` method to `AbstractTestClass` that calls `stop()`.
