### ISSUE TITLE
Allow extensions to leverage registered ParameterResolvers for method and constructor invocations

### ISSUE THREAD

**Issue by sebersole** [junit-team/junit5#2393]
I am working on an extension for tests to be able to react to failed tests or tests that end in exception by including a method annotated with `@OnFailure`.  

My specific high-level "requirement" is to be able to rebuild a Hibernate `SessionFactory` in these cases.  That method needs access to the `SessionFactory` to be rebuilt.  Actually it is a `SessionFactoryScope` class that manages a `SessionFactory` and exposes it via a `ParameterResolver`.  E.g.

```java
@SessionFactory
public class MyTest {
    @Test
    public void theTest(SessionFactoryScope scope) {
        // ...
    }
}
```

If this test fails, I'd like to be able to access the `SessionFactoryScope` to trigger it to release its `SessionFactory` and build a new one.  To do that it needs access to the `SessionFactoryScope`.  I.e.:

```java
    @OnFailure
    public void rebuild(SessionFactoryScope scope) {
        // ...
    }
```

Currently, JUnit Jupiter does not allow access to registered ParameterResolvers nor any way to invoke such "extension methods" with resolved parameter arguments.

Seems like a generally useful feature.

**Comment by sormuras** [comment]
Tentatively slated for 5.8 for _team discussion_

**Comment by sbrannen** [comment]
I thought we already had an open issue for that, but I can't seem to find it now.

In any case, this is related to:

- #944 
- #1139
- #2191

**Comment by sebersole** [comment]
Any word on this?  

I looked at the "related issues", though to my noob eyes I was not really seeing the relationship aside from them also asking about ParameterResolvers 

- the first 2 specifically related to parameterized tests
- the 3rd may relate, but I really did not understand fully what was being asked there

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
One option would be to introduce a method directly on `ExtensionContext`: `Object invokeWithParameterResolution(Object target, Executable executable)`.

An intermediate interface, e.g `ParameterResolution`, that could be accessed via `ExtensionContext` would allow us to later support additional use cases.

**Comment by marcphilipp** [comment]
**Team decision:** Introduce `ExtensionContext.getParameterResolution()` and `ParameterResolution.invoke(Object target, Executable executable)` methods. Investigate how other use cases (see https://github.com/junit-team/junit5/issues/2393#issuecomment-683420815) would be addressed in this new API.

**Comment by sormuras** [comment]
Yes.

Those two methods are targeted to be included in milestone [5.8 RC1](https://github.com/junit-team/junit5/milestone/54) - which follows after not-yet released milestone [5.8 M2](https://github.com/junit-team/junit5/milestone/55) - which in turn was predated by [5.8 M1](https://github.com/junit-team/junit5/milestone/51) in February 2021.

**Comment by sebersole** [comment]
So any idea when 5.9 will be released now?

**Comment by marcphilipp** [comment]
@sebersole This change has not yet been made. Would you be interested and have time to work on it?

**Comment by sbrannen** [comment]
@juliette-derancourt is currently working on a prototype for this feature.

**Comment by sebersole** [comment]
Sorry @marcphilipp I was on vacation when you sent that and it got lost in the weeds.

I'd be willing to help if I can.  @juliette-derancourt - let me know if there is something I can do

**Comment by juliette-derancourt** [comment]
@sebersole Thanks for the offer!
I just opened a draft PR, you're welcome to review it if you want to 🙂 (The documentation is missing for now)
Please tell me if this is what you had in mind when opening this issue!

**Comment by juliette-derancourt** [comment]
> So in my extension, I'd invoke the method I mentioned using `context.getExecutableInvoker().invoke( onFailureMethod )`?

@sebersole Yes, that would work like this 👍

**Comment by sebersole** [comment]
Looks beautiful to me :)

**Comment by ledoyen** [comment]
If I may, can we imagine this as a building block for the classloader extension discussed in #201 ?

The next move can be to build (and run with it) this kind of class loader when JUnit starts: boot -> platform -> junit-related urlCL -> what's left urlCL

This later would allow an extension point to let users decide how to build their custom classloader as long as the *junit-related urlCL* is in the parent chain.

WDYT ?

**Comment by sbrannen** [comment]
@ledoyen, I don't see how _this_ new Jupiter feature is related to the Platform-level `ClassLoader` issue.

This particular new feature doesn't have anything to do with class loading.

**Comment by ledoyen** [comment]
@sbrannen, sorry I rushed into this a little fast, I was thinking of my [current implementation](https://github.com/fridujo/classpath-junit-extension/blob/fea10bd9eb0d465c5e3bd47d1d7c20f97a54213e/src/main/java/com/github/fridujo/classpath/junit/extension/jupiter/AbstractClasspathExtension.java) which lacks compatibility with other extensions and will benefit from this new feature.

However, from the JUnit framework perspective, this is no different than the actual test method invocation which already exists and indeed brings nothing to the classloader topic.

Sorry for that 😞

**Comment by sbrannen** [comment]
No worries, @ledoyen 👍
