### ISSUE TITLE
Is there a assertStringsEqualIgnoreEOL or something?

### ISSUE THREAD

**Issue by XenoAmess** [junit-team/junit5#2394]
Hi.
I want to assert two Strings be equals ignore EOL, as CR, LF, CRLF.
If there exist such a feature?

And if not, I can implement it, I have experience in doing that.
Is it acceptable?

**Comment by sormuras** [comment]
**Team decision:** In line with other team decisions (see https://github.com/junit-team/junit5/issues/1920#issuecomment-499841520), we will not include the proposed assertions in JUnit Jupiter.

Perhaps, Jupiter's [`Assertions.assertLinesMatch`](https://junit.org/junit5/docs/snapshot/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html#assertLinesMatch(java.util.List,java.util.List)) in combination with [`String.lines`](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/String.html#lines()) is a solution for your use-case?

**Comment by XenoAmess** [comment]
@sormuras Got it. Thanks anyway.
