### ISSUE TITLE
Provide information about the current ExecutionMode in ExtensionContext

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2396]
I am contributing to a bunch of JUnit 5 extensions that rely on a form of field injection to achieve their goals.

Field injection, if done in a `@BeforeEach` callback, works well for both parallel and sequential testing. It also works well for both `PER_CLASS` and `PER_METHOD` lifecycle semantics. However, it does not work very well if you're combining parallel execution with `PER_CLASS` lifecycle semantics, as the parallel execution threads for each test method will each inject their own instances into the single test class instance and clobber each other, interfering with the tests running in other threads. In such situations, it is necessary to inject into a `ThreadLocal` container instead.

Accordingly, I would like my extensions to be able to give fail-fast-and-loud behaviour in these circumstances - throwing an `ExtensionConfigurationException` if it finds it is being asked to run in an environment where it is being asked to run `CONCURRENT` and `PER_CLASS` at the same time, and informing the user that they should use a `ThreadLocal` in such a case.

The problem: the `ExtensionContext` that is passed to the extension's lifecycle methods has a method for telling you which class instance lifecycle mode is in force. However, it doesn't seem to give you a way to easily determine the execution mode. This can be inferred by manually examining the annotations and the global execution mode, but I feel that this breaks encapsulation a little bit - I don't have to do the same for the lifecycle.

## Deliverables

Method `ExecutionMode getExecutionMode()` in `ExtensionContext`.

Possibly a pair of methods - one that returns the value annotated on the class, and one that returns the *actual* execution mode in force (taking into account any global setting). The latter would be more directly useful to my use case.

**Comment by sbrannen** [comment]
Without having looked into the details, I think it sounds reasonable to introduce something like `getExecutionMode()`.

Tentatively slated for 5.8 M1 for _team discussion_

**Comment by kriegfrj** [comment]
Thanks! In the meantime, is there a standard or recommended way for an extension to tell if it's being run in parallel, in the absence of an explicit method in `ExtensionContext`? Do I simply have to inspect the value of the `@ExtensionMode` annotation and the global parameter?

**Comment by marcphilipp** [comment]
Since there are also config params to change the default execution mode, I don't think that would work reliably.

**Comment by kriegfrj** [comment]
The same has true of the lifecycle - there are config params that change the default. Empirically, it seems that the ExtensionContext always returns the lifecycle mode that is in force. Something similar would be useful for the concurrency mode. 

For reference,  have a look at joel-costigliola/assert-core#1984. I needed to change the behavior based on the concurrency mode to use a ThreadLocal if it is concurrent & per class, but wanted to avoid this overhead otherwise. For the Per Class mode it's straightforward as it won't run concurrent unless explicitly annotated, so i can just check for the presence of the annotation. But a general solution would be appropriate i think.

**Comment by marcphilipp** [comment]
**Team decision:** Add `ExecutionMode getExecutionMode()` to `ExtensionContext`.

@kriegfrj Would you be interested in submitting a PR for this?

**Comment by kriegfrj** [comment]
Thanks for asking - I'll see if I can find some time but I'll be busy for the next couple of weeks at least.
