### ISSUE TITLE
InvocationInterceptor.interceptDynamicTest does not provide access to the invocation context

### ISSUE THREAD

**Issue by loicmathieu** [junit-team/junit5#2399]
I'm using JUnit 5.6.2.

I work on an extension that needs to have access on  the invoked test method.

For standard tests, the `InvocationInterceptor.interceptTestMethod` gives access to a `ReflectiveInvocationContext<Method>` that gives access to the test method.

For dynamic tests, the `InvocationInterceptor.interceptDynamicTest` don't include any `ReflectiveInvocationContext<Method>` so we cannot access the test method.

Note that a `ReflectiveInvocationContext` is provided in almost all intercept methods except the dynamic test one.

An alternative would be to give access to the `DynamicTest` object itself.

**Comment by marcphilipp** [comment]
You can intercept the `@TestFactory` method by overriding `interceptTestFactoryMethod(...)`. The `ExtensionContext` provided to `interceptDynamicTest(...)` contains the information about the `DynamicTest`, e.g. its name. You could use the `ExtensionContext` as well for traversing up the hierarchy to find the `ExtensionContext` of the `@TestFactory` method.

@loicmathieu Does that help? What's your exact use case?

**Comment by loicmathieu** [comment]
@marcphilipp `interceptDynamicTest` contains the name of the dynamic test but not the `Executable`.

I'm working on QuickPerf and in certain circumstances we need to execute the test in a different VM so we skip the invocation and directly execute the test method. This works for standard tests invocation as we have the invocation context to access the test method but for Dynamic test we don't have access to the invocation context nor the dynamic test `Executable`.

Sure, we can use the ExtensionContext to retrieve the test factory method, execute it and get the right dynamic test, but this is a lot to do so having an invocation context or the `Executable` would be an easier to use solution.

**Comment by marcphilipp** [comment]
How do you transfer the `Executable` to a different VM? Couldn't you do the same with the `Invocation`?

**Comment by marcphilipp** [comment]
Could you transfer the `Invocation` instead?

**Comment by loicmathieu** [comment]
It's not very convenient for us as we want to directly invoke the test method because our test framewok make some low level stuff. For example we have the ability to measure the allocation of a test method, to lower the interraction between the test method and the test framework we fork the JVM and directly invoke the test method inside the forked VM.

This is how it works for JUnit4, TestNG and JUnit5 test methods.
This is how we want to make it work for Dynamic tests.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by loicmathieu** [comment]
Hi, is this considered for inclusion ?

I create an example implementation by passing the `Executable` to the interceptor: https://github.com/junit-team/junit5/compare/main...loicmathieu:feat/access-dynamic-test-executable

Of course this is only a proposal implementation to show how it can work. As it would break the existing interceptors maybe it needs to keep the old method for backward compability.

**Comment by marcphilipp** [comment]
**Team decision:** Add an overload of `interceptDynamicTest` that takes an `Invocation<Void>`, a `DynamicTestInvocationContext`, and an `ExtensionContext` that delegates to the old `interceptDynamicTest` method (so that existing extensions still work), and deprecate the old method. `DynamicTestInvocationContext` will just have a single method (for now): `Executable getExecutable()`.

@loicmathieu Thanks for the initial spike! Would you like to work on a PR?

**Comment by loicmathieu** [comment]
@marcphilipp great! I'll be happy to work on a PR for it.
