### ISSUE TITLE
Aggregate coverage reports with JaCoCo

### ISSUE THREAD

**Issue by aalmiray** [junit-team/junit5#240]
It would be great to compute aggregate coverage reports with JaCoCo and perhaps post the results to coveralls.io and/or codecov.

**Comment by marcphilipp** [comment]
We switched from JaCoCo to Clover because JaCoCo had/has issues with exceptions that lead to our Assertions class having a very poor coverage.

I've added support for Clover to our Travis build in fbf595d51f21c8813ee335c6b94fa9ba688dbdb9. That worked for a while, even though Codecov has some issues parsing Clover reports.

However, because the encrypted clover license (`clover.license.enc`) couldn't be decrypted when building branches in forks, it broke pull requests. I tried to address this in 8a22b0e3db76c04bba9a6eb6d5a43f957eec8482 but failed and removed Clover and Codecov support from our Travis build in b36aa262a1e038c0f8e61d680c616ba007576212.

So we currently only have our coverage on Jenkins: https://junit.ci.cloudbees.com/job/JUnit5/lastSuccessfulBuild/clover-report/pkg-summary.html

**Comment by aalmiray** [comment]
I also encountered additional issues after adding an initial JaCoCo configuration. At least half of the projects do not produce any tests, so they must be excluded form aggregate reports (otherwise `jacocoTestReport` task fails). JaCoCo instrumentation doe snot run out of the box with the `junit5-gradle` plugin because the new test task is not related to gradle's `Test` task, thus explicit configuration must be put in place.

I think there are a couple of action items that can be explored:
- collect issues faced with JaCoCo, let the JaCoCo team be aware of them.
- explore the possibility of the junit5 test task extending gradle's `Test` task.

**Comment by marcphilipp** [comment]
Here's the JaCoCo configuration that worked for us:
https://github.com/junit-team/junit5/blob/69b0a0138e4c3158504f7b382cdf05cc1e05b92e/junit-tests/build.gradle#L47-L65

We've asked the JaCoCo team for help in jacoco/jacoco#370 before switching to Clover.

For the latter point: I absolutely agree that this would be desirable. 5.0.0-M1 will focus on stabilizing our Launcher and Engine APIs. Once it is shipped, it work on bringing JUnit 5 support to [core Gradle](https://github.com/gradle/gradle/tree/master/subprojects/testing-jvm) can start. Do you think it makes sense to do it in our plugin instead? It was merely meant as an intermediate solution to execute tests from Gradle.

**Comment by aalmiray** [comment]
I see now. Could issue 1 be solved by rewriting the method such as

    throw fail(nullSafeGet(messageSupplier));

I remember seeing this idiom in the `fest` library.

https://github.com/alexruiz/fest-assert-2.x/blob/bff5925af00fc732ba3a0e85f6774acba77ec7c8/src/main/java/org/fest/assertions/internal/Failures.java
https://github.com/alexruiz/fest-assert-2.x/blob/bff5925af00fc732ba3a0e85f6774acba77ec7c8/src/main/java/org/fest/assertions/internal/Arrays.java#L74

I think it's worthwhile exploring option 2 as there's no guarantee Gradle Inc. will pick up JUnit5 as early as you may want them to. This work can be done in an experimental branch

**Comment by marcphilipp** [comment]
We've been in contact with Etienne from Gradle since the JUnit Lambda kickoff. That should improve our chances, I hope. But you're right that there's no guarantee, of course. It sounds like you're eager to work on it? If so, please open a new issue for it – we'd be happy to see progress there. :-)

Regarding the JaCoCo issue: Thanks for the suggestion. We can try that. However, I want a coverage tool I can trust and not write my code to workaround its limitations. You don't seem to like Clover very much, do you?

**Comment by aalmiray** [comment]
Great! Etienne is a fellow colleague of mine :smile: 

I do like Clover but as I recalled its development hasn't been so important to its owning company in the latest years (I may be totally wrong too, <3 Atlassian). Setting up the license in a public CIo server is also a problem as you don't a "smart guy" to "borrow" it. JaCoCo and Cobertura are the other options we have at hand; JaCoCo is more accurate than Cobertura.

will have a look at the gradle plugin next week during Zurich Hackergarten.

**Comment by marcphilipp** [comment]
The last time I checked, Cobertura didn't have full support for Java 8. 

Clover is already set up on Cloudbees: https://junit.ci.cloudbees.com/job/JUnit5/

Good to hear that you'll meet with @sbrannen at Zurich Hackergarten!

**Comment by jbduncan** [comment]
By my understanding, Clover has been open sourced now as [OpenClover](http://openclover.org/) and no longer needs an encrypted license.

If Travis and either Codecov or coveralls.io properly support Clover reports now, it would be worth looking into enabling code coverage again.

**Comment by marcphilipp** [comment]
IIRC only Codecov has Clover support.

@jbduncan Do you have time to give it a try using your fork?

**Comment by jbduncan** [comment]
@marcphilipp Sorry, could you clarify for me what you'd like me to try out? :)

**Comment by jbduncan** [comment]
Do you mean trying out OpenClover on my fork using Codecov?

**Comment by marcphilipp** [comment]
We're already using OpenClover. Could you try to integrate Codecov with our Travis build?

**Comment by jbduncan** [comment]
I can't guarantee anything, but I'm certainly happy to give it a go! I will get cracking tonight or within the next few days. :)

**Comment by jbduncan** [comment]
@marcphilipp, I think I might actually be out of depth with this one.

So far, on my local machine, I've only found one workaround for the problem you experienced yourself with branch [`codecov`](https://github.com/junit-team/junit5/tree/codecov), where Travis fails with a `java.lang.NoClassDefFoundError: com_atlassian_clover/TestNameSniffer`. The workaround I found is to run the following commands one after another, but it takes quite a long time for both commands to run on my machine, and I imagine it would do the same on Travis.

1. `./gradlew build`
2. `./gradlew -PenableClover cloverHtmlReport cloverXmlReport`

I did find this [StackOverflow question](https://stackoverflow.com/questions/41703853/caused-by-java-lang-noclassdeffounderror-com-atlassian-clover-testnamesniffer) which I thought would help, but I personally wasn't able to derive any useful information from it.

I'm also busy with IRL things like doing job interviews, so I doubt that I'll have the time and energy to pursue this further, at least in the foreseeable future.

I hope that my efforts help in some way!

**Comment by marcphilipp** [comment]
No worries, thanks for letting me know! Good luck with your job interviews!

**Comment by hisener** [comment]
@marcphilipp Anything to do with this issue?

**Comment by marcphilipp** [comment]
Nope, thanks for the pointer!
