### ISSUE TITLE
Support custom file system for `@TempDir`

### ISSUE THREAD

**Issue by nipafx** [junit-team/junit5#2400]
Jupiter's `@TempDir` does not allow the configuration of custom file systems. It would be nice if it would.

A key motivation for me to open this issue is that custom file systems are the only thing that Pioneer's `@TempDir` can do that Jupiter's can't. Since Jupiter's is quite a bit more powerful than ours now, we'd like to remove our extension (this also prevents confusion for users), but we don't feel comfortable doing that as long as there's a feature we offer that you don't.

If Jupiter isn't fundamentally opposed to such a feature, we could implement it and open a PR.

**Comment by marcphilipp** [comment]
**Team decision:** Since the `Extension` backing Jupiter's `@TempDir` is currently registered globally, implementing this is not straightforward. In addition, at this time, we have not yet received great interest in such a feature within Jupiter itself. In light of that, we'd like to focus our resources on some of the more popular outstanding issues in Jupiter. If it later turns out that there's significant community interest to include it in Jupiter we may revisit this issue at that time.

**Comment by nicolaiparlog** [comment]
Me:

> If Jupiter isn't fundamentally opposed to such a feature, we could implement it and open a PR.

You:

> we'd like to focus our resources on some of the more popular outstanding issues in Jupiter

Not sure how they relate. :smiley: Should we (Pioneer) consider working on this to create a PR or would you prefer if we didn't?

**Comment by marcphilipp** [comment]
Well, even if you put in the work to submit a PR we'd have to review it. Moreover, we would discuss how the API and implementation should roughly look like before that. So, for now, we'd prefer that you didn't. I hope you understand. 🙂

**Comment by nicolaiparlog** [comment]
> I hope you understand.

Of course, no worries. Just wanted to make sure.

**Comment by jbduncan** [comment]
I think this issue is valuable.

**Comment by marcphilipp** [comment]
Now that `@TempDir` is created per declaration by default, that might make an approach that configures it locally feasible.

**Comment by scordio** [comment]
Although the custom file system could/will be specified per declaration, it'd still be useful to have a way to set it globally, for example with a configuration property (rationale at https://github.com/junit-team/junit5/issues/2889#issue-1200641741).

**Comment by scordio** [comment]
@marcphilipp @sbrannen is this up for grabs? I would like to work on it if that's fine with you.
