### ISSUE TITLE
Javadoc Generation for Kotlin Methods

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-team/junit5#2401]
Support for generating JavaDocs for Kotlin methods is now supported in Dokka.

I don't really have the cycles to add this myself, but I wanted to make the JUnit team aware as this question came up when the Kotlin methods were introduced.

https://github.com/Kotlin/dokka/issues/211

If this is a low/no priority issue, feel free to close this. I just wanted to make the JUnit team aware.

**Comment by marcphilipp** [comment]
@JLLeitschuh Does Dokka integrate with the regular Javadoc task so that we can ship a single Javadoc artifact that includes both Java and Kotlin code? Do you know which Java versions Dokka runs on?

**Comment by JLLeitschuh** [comment]
Sorry, I can't answer any of these questions without more digging. I honestly don't know unfortunately.
