### ISSUE TITLE
Limit publishing settings on build file

### ISSUE THREAD

**Issue by aalmiray** [junit-team/junit5#241]
It looks like publishing settings are applied to all subprojects but only a handful of them are actually meant for publication. This leads to repeated task deactivation on the projects that should publish their artifacts. The build can be simplified in many ways, one of them would be to apply the following pattern to the build

    def mavenizedProjects() {
        [
            project(':project1'),
            project(':project2')
        ]
    }

    configure(mavenizedProjects()) {
       ...
    }

**Comment by sbrannen** [comment]
Thanks for the suggestion. We'll look into it.

**Comment by aalmiray** [comment]
@sbrannen: any chance you'll be at Zurich Hackergarten next week? Perhaps we can have a look at the gradle build together :smiley:

**Comment by sbrannen** [comment]
@aalmiray, sounds like a good idea. I just [signed up](http://www.meetup.com/Hackergarten-Zurich/events/230563975/). 😉

**Comment by sbrannen** [comment]
Resolved in conjunction with #256 and merged into `master` in ea636bfb8d47f5fec872836b6415bbaa6b3b9f73.
