### ISSUE TITLE
Introduce configuration to disable all outbound network connections

### ISSUE THREAD

**Issue by sudo-chill** [junit-team/junit5#2419]
Unit tests should not make outbound network requests, but it can be difficult to remember all of the ways code might be depending on external systems when someone is writing tests for it. Especially if there is per-developer setup that makes the tests work with the author, but not other consumers.

A straightforward configuration to disable network connections would ensure that unit tests enforce a 'no access to external dependencies' policy which would help make the tests more reliable and portable.

I recognize that this may not be the right place for such configuration, but I feel a standardized JUnit setting would be the most accessible and intuitive place to put it for most developers who are otherwise not super familiar with the nuances of network configuration.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
AFAIK the only way to do so is to replace the `SecurityManager` and that has to be done as a VM parameter so that would mean it's out-of-scope for JUnit. Am I missing sth.?

**Comment by marcphilipp** [comment]
@sudo-chill Friendly ping.

**Comment by sudo-chill** [comment]
Ah sorry, I should have responded sooner.

In general I wasn't sure if JUnit was the right place for this. But it represents the most visible possible 'injection point' for such a behavior within testing that I thought it was a good place to start asking if there are options.

After doing a bit of reading about the SecurityManager, it sounds like you are correct; a JVM argument is required to specify an alternate security manager implementation. At best, JUnit could vend such an implementation that simply returns false for all check* methods associated with network access and print warnings if JUnit detects it's running unit tests without using that security manager. But ultimately enforcement at this layer is probably not possible.

That said, I'm glad I asked anyway. I didn't know about SecurityManager before, and it's giving me ideas for achieving my goal. So thanks!

**Comment by judepereira** [comment]
For those stumbling upon this, we had a similar requirement, and created a custom policy which restricts tests from accessing the internet: https://tech.clevertap.com/using-javas-security-policy-to-block-internet-access-for-junit-tests/

**Comment by marcphilipp** [comment]
@judepereira Nice, thanks for sharing! 👍
