### ISSUE TITLE
Provide mechanism to control whether or not to trim whitespace in @CsvSource and @CsvFileSource

### ISSUE THREAD

**Issue by dmsergeevN26** [junit-team/junit5#2420]
`CsvArgumentProvider` does not support configuration of the underlying `CsvParser` by univocity.

## Steps to reproduce

```java
    @ParameterizedTest
    @CsvSource(
        "        SW34NT,SW34NT   "
    )
    fun test(one: String, two: String) {
        assertThat(one).isEqualTo(two)
    }

```

This should **NOT** work, or at least the behavior should be configurable:

CsvParserSettings.ignoreTrailing/LeadingWhitespace = false

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.7.0
 - Build Tool/IDE: IntelliJ

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
Tentatively slated for 5.8 M1 for _team discussion_

**Comment by dmsergeevN26** [comment]
@sbrannen thanks! The title is not correct, which is my fault as my original title was not phrased right.
It should be `Provide mechanism to control whether or not to trim whitespace`

**Comment by sbrannen** [comment]
Ahhh.... OK. 

So, you want to make it possible for the following test to pass; whereas, it currently fails because leading and trailing whitespace are trimmed by default.

```java
@ParameterizedTest
@CsvSource("        SW34NT,SW34NT   ")
void test(String one, String two) {
	assertNotEquals(one, two);
}
```

**Comment by dmsergeevN26** [comment]
Exactly! Sorry I was not clear.

**Comment by marcphilipp** [comment]
**Team decision:** Introduce `ignoreTrailingAndLeadingWhitespace` attribute to `@CsvSource` and `@CsvFileSource` with default value of `true`.

**Comment by marcphilipp** [comment]
@dmsergeevN26 Would you be interested in submitting a PR for this?

**Comment by dmsergeevN26** [comment]
@marcphilipp i will give it a try

**Comment by marcphilipp** [comment]
@somayaj is working on this issue in #2491.
