### ISSUE TITLE
BeforeAllCallback called twice when using @Nested test classes

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [junit-team/junit5#2421]
Junit 5.7.0

## Steps to reproduce

```kotlin
class Ext : BeforeAllCallback, AfterAllCallback {
    override fun beforeAll(context: ExtensionContext) = println("beforeAll")
    override fun afterAll(context: ExtensionContext) = println("afterAll")
}

@ExtendWith(Ext::class)
internal class MainActivityTest {
    @org.junit.jupiter.api.Nested
    inner class Nested {

        @Test
        fun beforeAllCalledTwice() {
            /** Out put is:
            beforeAll
            beforeAll
            
            
            afterAll
            afterAll
             */
        }
    }
}
```

## Context

    def junitVersion = "5.7.0"
    testImplementation("org.junit.jupiter:junit-jupiter:$junitVersion")
    testCompileOnly('junit:junit:4.13') // To allow running JUnit 4 Tests
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:$junitVersion")

AS 4.0.1 Build tools 30.0.2

## Deliverables

I assume this shouldn't happen and it should only be called once?

**Comment by marcphilipp** [comment]
> I assume this shouldn't happen and it should only be called once?

Actually, this works as-designed: the `BeforeAllCallback` is called before every container. Thus, in your case, before all methods in `MainActivityTest` _and_ before all methods in `MainActivityTest$Nested`. You can use the `ExtensionContext.Store` to store something in the first invocation and check for that value in subsequent invocations.
