### ISSUE TITLE
Allow parallel execution of child nodes if only read locks are acquired

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#2423]
Currently, child nodes are forced to `SAME_THREAD` execution if the parent has any locks. 

If the parent only has `READ` locks, then it would be valid for the child nodes to execute concurrently. This would also alleviate the issues of #2038 and we partly have this logic already for the isolated execution of #2142 

## Deliverables

- [ ] Don't force child nodes to `SAME_THREAD` execution if only `READ` locks are acquired

**Comment by marcphilipp** [comment]
SGTM. Would you like to send a PR?

**Comment by XN137** [comment]
is this still actively being worked on?
if no, i might be willing to take a stab at this

**Comment by leonard84** [comment]
@XN137 go ahead, I still have some stuff to finish over at https://github.com/spockframework/spock before I get to this
