### ISSUE TITLE
Which jars are required for a minimal and backward compatible (-> "vintage") junit 5 environment?

### ISSUE THREAD

**Issue by jayjupdhig** [junit-team/junit5#2432]
hi there

there are A LOT of jars on junit page - which ones are required for a MINIMAL backward compatible (-> "vintage") junit 5 environment?

Thank you for your feedbacks.

With best regards,
Jan

**Comment by sormuras** [comment]
Your description of "a minimal and backward compatible junit 5 environment" lacks a lot of information.

Perhaps, our single (all-in, happy, uber) JAR helps here?

https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

**Comment by jayjupdhig** [comment]
thank you. 

Eclipse does not show "Run As -> JUnit Test" when i add some JUnit 5 jar files. But the "Test" class for annotation will be found in the 2 jars i added. (That jar that contains the "Test" class for annotation and the vintage jar - both most current versions)

Maybe the problem is that i added not all required jars?

-> https://bugs.eclipse.org/bugs/show_bug.cgi?id=566021

Regards, Jan

**Comment by jayjupdhig** [comment]
OK... so i've downloaded the file `junit-platform-console-standalone-1.7.0-all.jar` and added it to my project's `lib` directory.

Now my question is: What's the name of the class that contains the main()-method?

So what do i need to define here?

![Usdnbenannt](https://user-images.githubusercontent.com/42765391/94899430-961b3080-0493-11eb-9de2-2d19169bc882.jpg)

My idea is to run that launcher as a normal java programm...

![sdfdsfs](https://user-images.githubusercontent.com/42765391/94899579-df6b8000-0493-11eb-93fd-b0b305ebcbaf.jpg)

But i don't kown which class (like org.junit.JUnitLauncher) i need to define for the running configuration.

When that works, i think i can add the class to test (With @Test annotations) as an argument to the JUnit luncher config. Am i right with this?

Thank you for your feedback.

**Comment by jayjupdhig** [comment]
Currently, these 3 files are in the project's `lib` directory. 2 of them are in the classpath on project config: `junit-jupiter-api-5.7.0.jar` and `junit-vintage-engine-5.7.0.jar` ->first one for `@Test` annotations and the 2nd one to retain backward compatibility to older versions.

The `junit-platform-console-standalone-1.7.0-all.jar` i didn't added to the projects classpath. With that file i just want to add a new run configuration ("normal" java application, no specific JUnit test) to run my test classes with `@Test`-annotated test methods.

I think i'm on the right way, but i don't know which class contains the main function... when i open the `junit-platform-console-standalone-1.7.0-all.jar` e.g. with 7zip, there is no manifest file which defines the location (class) with a `main()` method.

So it seems, today a `manifest.mf` file is not required anymore to define the class that contains the `main()` methods. (to be truthful: i started with Java again after almost 10 years - is seems my knowledge is not really "up to date" anymore)


With best regards,
Jan

**Comment by jayjupdhig** [comment]
Oh... when i want to go that way, i also need to add the `junit-platform-console-standalone-1.7.0-all.jar` to classpath! ;-)

I also decompiled the class `module-info.class` in `junit-platform-console-standalone-1.7.0-all.jar`... because of the missing `manifest.mf`...

Then i saw that:

![sfwergf](https://user-images.githubusercontent.com/42765391/94901401-df20b400-0496-11eb-94ca-dba2792f9d58.JPG)

So...

- `org.junit.platform.engine.TestEngine`

OR

- `org.junit.jupiter.engine.JupiterTestEngine`

...must contain the `main()` method. (???)

But: 

![1](https://user-images.githubusercontent.com/42765391/94901807-81409c00-0497-11eb-8ec5-4c8771116724.jpg)

Leads to that output:

`Fehler: Hauptmethode in Klasse org.junit.platform.engine.TestEngine nicht gefunden. Definieren Sie die Hauptmethode als:
   public static void main(String[] args):
oder eine JavaFX-Anwendung muss javafx.application.Application erweitern`


AND 

![2](https://user-images.githubusercontent.com/42765391/94901820-84d42300-0497-11eb-91b6-96d6a11c9e6f.jpg)

Leads to that output:

`Fehler: Hauptmethode in Klasse org.junit.jupiter.engine.JupiterTestEngine nicht gefunden. Definieren Sie die Hauptmethode als:
   public static void main(String[] args):
oder eine JavaFX-Anwendung muss javafx.application.Application erweitern`


So (currently) the only way seems to be to write an ANT script that executes:

`java -jar junit-platform-console-standalone-1.7.0-all.jar PARAM1 PARAM2 PARAM3`

???

I'm since 3 days on that task any my chief soonly get insane!!!!!!

**Comment by jayjupdhig** [comment]
AND: I don't want to use the eclipse built-in JUnit versions (available on the project config classpath tab) - that was NOT the question!! ;-)

**Comment by jayjupdhig** [comment]
On a configuration with eclise-built-in JUNit 5 jars, i also can't see what the main class of junit framework is:

![wedvcwdv](https://user-images.githubusercontent.com/42765391/94902669-dc26c300-0498-11eb-997b-ea31e926dbbd.JPG)

...so my question is still pendent.

**Comment by jayjupdhig** [comment]
I also opened a bug case on eclipse bug tracker. When a method is annotated with `@Test`, then Eclipse should show "Run As - JUnit Test" automatically. With self-added 4.13 version, that works. with self-added 5.7 version, it works NOT!!
-> https://bugs.eclipse.org/bugs/show_bug.cgi?id=566021

**Comment by jayjupdhig** [comment]
If you need more informations, so please don't heistate to ask me ffor them. Thanks.

Kind regards,
Jan

**Comment by jayjupdhig** [comment]
Oh, now i've found the manifest.mf file in META-INF directory. The class with main method is: `org.junit.platform.console.ConsoleLauncher`

;-)
