### ISSUE TITLE
@DisplayNameGenerator - not working with Surefire

### ISSUE THREAD

**Issue by sricharankrishnan** [junit-team/junit5#2433]
I've searched everywhere for a step by step explanation for this but to no avail. The requirement is simple and clear

I have a demo test class in AppTest.java and I am using Junit 5 for this
I am using the @DisplayNameGenerator with a custom Generator static class
But no changes are showing in the termnial
I am not sure what it is I need to do further. Can someone help me please? Here is the code so far I have got:

## Steps to reproduce
```package learnjunit;

/* assertions and junit 5 core annotation imports */
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.lang.reflect.Method;


@DisplayNameGeneration(AppTest.ReplaceCamelCase.class)
public class AppTest {
  @BeforeAll
  public static void test_beforeAll() {
    System.out.println("@BeforeAll - Executing");
  }

  @BeforeEach
  public void test_beforeEach() {
    System.out.println("@Before - Executing");
  }

  @Test  
  public void test_testOne() {
    System.out.println("@Test - Executing for test_testOne()");
  }

  @Test
  public void test_testTwo() {
    System.out.println("@Test - Executing for test_testTwo()");
  }

  @AfterEach  
  public void test_afterEach() {
    System.out.println("@AfterEach - Executing");
  }

  @AfterAll
  public static void test_afterAll() {
    System.out.println("@AfterAll - Executing");
  }
  
  static class ReplaceCamelCase extends DisplayNameGenerator.Standard {
      @Override
      public String generateDisplayNameForClass(Class<?> testClass) {
          /* -> this I can see in the terminal */ System.out.println(super.generateDisplayNameForClass(testClass));
          /* -> this has no effect */ return super.generateDisplayNameForClass(testClass) + "__YES";
      }

      @Override
      public String generateDisplayNameForNestedClass(Class<?> nestedClass) {
          return replaceCamelCase(super.generateDisplayNameForNestedClass(nestedClass));
      }

      @Override
      public String generateDisplayNameForMethod(Class<?> testClass, Method testMethod) {
          return this.replaceCamelCase(testMethod.getName()) + 
            DisplayNameGenerator.parameterTypesAsString(testMethod);
      }

      String replaceCamelCase(String camelCase) {
          StringBuilder result = new StringBuilder();
          result.append(camelCase.charAt(0));
          for (int i=1; i<camelCase.length(); i++) {
              if (Character.isUpperCase(camelCase.charAt(i))) {
                  result.append(' ');
                  result.append(Character.toLowerCase(camelCase.charAt(i)));
              } else {
                  result.append(camelCase.charAt(i));
              }
          }
          return result.toString();
      }
  }
}```

I've really honestly searched everywhere I could and have posted on Stackoverflow. I would really be grateful if someone told me what to do!

**Comment by sbrannen** [comment]
>  But no changes are showing in the termnial

What exactly do you mean by the "terminal"?

How are you executing the tests (IDE, build tool, ConsoleLauncher, ...)?

**Comment by sricharankrishnan** [comment]
I run the test on the terminal using the command mvn test. I am not using and GUI Editors
![Screenshot from 2020-10-02 17-59-22](https://user-images.githubusercontent.com/19187230/94923173-0e581500-04d9-11eb-92bd-1cc21dea1d6a.png)

**Comment by sricharankrishnan** [comment]
Ok BTW, this is built using maven. Does that make a difference by chance to answer this?

**Comment by sormuras** [comment]
Do you configure Surefire to emit display names as documented here? https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName

**Comment by sricharankrishnan** [comment]
@Sormuras - I've copied and pasted the details from the location you sent but still no difference. Here are the screen shots:

![Screenshot from 2020-10-02 20-26-27](https://user-images.githubusercontent.com/19187230/94937778-ab24ad80-04ed-11eb-90d3-ce62cb7991b3.png)
Screen shot from my POM.xml (this is a multi module project)

![Screenshot from 2020-10-02 20-27-57](https://user-images.githubusercontent.com/19187230/94937853-c55e8b80-04ed-11eb-8a33-142da87ece9f.png)
Guess there is still no change in the out put in the terminal after running mvn test

**Comment by sricharankrishnan** [comment]
/* -> this has no effect */ return super.generateDisplayNameForClass(testClass) + "__YES";
The trailing __YES still cannot be seen

**Comment by sricharankrishnan** [comment]
I'm actually hitting local time here in India for snooz, ill be back in sometime. I;ve uploaded a demo project of this issue @ https://github.com/sricharankrishnan/demo-num3

So the condition is that once the maven project is downloaded, all commands need to be run on the terminal with mvn test etc..

I'm no pro in Java but Id be grateful if someone could take a look and me know. Currently pursuing a course and I could use some help here! =)

Do let me know what changes should be made. you could go ahead and make the changes in the file too if you would like and I'll take a look on how its done

**Comment by sormuras** [comment]
I filed a PR that updates Surefire from 3.0.0-M3 to -M5 and checked in GitHub Codespaces that the `__YES` suffix is emitted.

**Comment by sricharankrishnan** [comment]
Hello @sormuras - good morning!
yes changing to m5 worked and its great!

![Screenshot from 2020-10-03 05-05-32](https://user-images.githubusercontent.com/19187230/94977411-3de93a80-0536-11eb-8b39-4a7bb1bacde8.png)
Screenshot from my terminal. So the @DisplayNameGenerator Annotation seems to be fine with the class name. Will do more work and let you know if something comes up

I'd also like to clarify, how to do the same for individual methods? For annotation @DisplayName, there are sufficient examples but it too does not work in the terminal. So do I use @DisplayName or @DisplayNameGenerator? Made a push at https://github.com/sricharankrishnan/demo-num3 again pointing to the name generator method in the static class

Here is the screen shot of only what works but need help with the actual method name (which does not seem to work)
![Screenshot from 2020-10-03 05-23-58](https://user-images.githubusercontent.com/19187230/94977935-b81abe80-0538-11eb-9db0-4ae5099fdd30.png)
Grateful once again, please help!

**Comment by sricharankrishnan** [comment]
Good day to you all. Just wanted to check on my request status. 
Looking forward to hearing from your side please

**Comment by sormuras** [comment]
As @sbrannen wrote in this [comment](https://github.com/junit-team/junit5/issues/2435#issuecomment-703096979) we "prefer to use the issue tracker only for bugs and enhancements." Thus, I'll close this issue.

From your last question and screenshots, I can tell, everything's working as expected:

> ... do the same for individual methods?

Exactly how you did it.

> So do I use `@DisplayName` or `@DisplayNameGenerator`?

What-ever you want/need. In Jupiter, both end up as a custom display name string.

> ... does not work in the terminal.

Most of the output you see is generated by Maven Surefire. It doesn't emit a string for each test method. When you print a string (to `System.out`, for example) you're in charge of what is printed. Have a look at this example how you may retrieve a display name at runtime: https://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection
