### ISSUE TITLE
junit-platform-commons 1.7.0 does not contain MANIFEST.MF as first JAR entry

### ISSUE THREAD

**Issue by jsedding** [junit-team/junit5#2438]
While the JAR file specification doesn't mention this, the `java.util.jar.JarInputStream` implementation assumes that `META-INF/MANIFEST.MF` is the first or second entry in a jar file.

From the `JarInputStream` sources:
> // This implementation assumes the META-INF/MANIFEST.MF entry
> // should be either the first or the second entry (when preceded
> // by the dir META-INF/). It skips the META-INF/ and then
> // "consumes" the MANIFEST.MF to initialize the Manifest object.

Also the [Java Archive Tool Documentation](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/jar.html) mentions:

> The jar tool automatically generates a manifest file entry named META-INF/MANIFEST.MF. It is always the first entry in the jar file. 

Commit 5631ebc (#2217) introduced reproducible builds. Part of this is `java-repackage-jars` plugin, which sorts jar entries alphabetically. For junit-platform-commons, this results in the following first entries:

> META-INF/
> META-INF/LICENSE-notice.md
> META-INF/LICENSE.md
> META-INF/MANIFEST.MF

Evidently, this causes issues with any tools implemented using `JarInputStream`.

## Steps to reproduce

- download [junit-platform-commons-1.7.0.jar](https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-commons/1.7.0/junit-platform-commons-1.7.0.jar)
- `unzip -l junit-platform-commons-1.7.0.jar` (or list the file contents in another way)

Note: my real scenario involved [code in an Apache Sling module](https://github.com/apache/sling-org-apache-sling-installer-core/blob/master/src/main/java/org/apache/sling/installer/core/impl/Util.java#L74)

## Desired outcome

It would be nice if `MANIFEST.MF` could be sorted to the top of the list for reproducible builds.

**Comment by marcphilipp** [comment]
Thanks for the comprehensive bug report! I wasn't aware of that assumption. Would you be interested in submitting a PR with a fix?

**Comment by jsedding** [comment]
Thanks for your prompt feedback. I am not familiar with kotlin, but I gave it a shot anyway. It works for me with the proposed change.
