### ISSUE TITLE
Document TimingExtension example in the User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#244]
Document (in `/documentation/src/docs/asciidoc/extensions.adoc`) how to implement `BeforeTestMethodCallback` and `AfterTestMethodCallback` extensions by demonstrating the implementation of the `TimingExtension` and its usage in `TimingExtensionTests`.

**Comment by sbrannen** [comment]
This issue is currently slated for 5.0.0-M2; however, if it is completed in time it may be included in 5.0.0-M1.

**Comment by hglasgow** [comment]
I have created pull request #306 with the required documentation changes. I have not used asciidoc before so hope it is okay.

**Comment by sbrannen** [comment]
Assigned to M1 due to pending PR #306.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
PR #306 has been merged into `master` in cbf84cd2d348535f1d6fc4ab9104d4c0b3288808.
