### ISSUE TITLE
Wrong encoding of standard output

### ISSUE THREAD

**Issue by Romanzek** [junit-team/junit5#2440]
We are using log4j 1.2 for loging purpose in out project. All output is produced in UTF-8. But when we executing our tests on Windows in junit 5 we have broken encoding in standard output and the junit 5 html report. It's seems junit converts stdout according to system encoding - when we change the file.encoding property (jvmArgs '-Dfile.encoding=UTF-8') all become ok.
We need  some settings in junit to specify standard output encoding.

**Comment by marcphilipp** [comment]
JUnit doesn't write an HTML report. How are you running your tests?

**Comment by Romanzek** [comment]
I mean JUnit platform. We just started tests in our gradle build.

**Comment by Romanzek** [comment]
The same problem with redirecting standard output with gradle option "testLogging.showStandardStreams = true".

**Comment by marcphilipp** [comment]
In that case Gradle writes these reports and setting `file.encoding` actually sounds like what you need.
