### ISSUE TITLE
TempDir can't delete subfolders when assertAll is used

### ISSUE THREAD

**Issue by MichaelWarnecke** [junit-team/junit5#2444]
## Steps to reproduce

Executing the following test results in an exception:
```
java.io.IOException: Failed to delete temp directory C:\tmp\junit3857951443644498861. The following paths could not be deleted (see suppressed exceptions for details): 
[...]
	Suppressed: java.nio.file.DirectoryNotEmptyException: C:\tmp\junit3857951443644498861
```
	

```
public class DirTest {

	@TempDir
	Path temp;

	@Test
	public void foo() throws MultipleFailuresError, IOException {
		Path dir = temp.resolve("dir");
		Files.createDirectories(dir);
		Files.createFile(dir.resolve("file"));
		assertAll(Files.list(dir).map(f -> () -> {}));
	}

}
```

Debugging shows that `file` can be deleted while `dir` remains existent even after a successful call to `Files#delete` ([TempDirectory](https://github.com/junit-team/junit5/blob/cfdf09aad5ed70fae210fe14fad6d6356f749242/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L206))

I suspect there is something within `assertAll` interfering with deleting the directory. Can anyone confirm this behaviour or propose a solution?

## Context

 - JUnit-Version: org.junit.jupiter:junit-jupiter:5.6.2
 - Build Tool/IDE: Eclipse 2020-03

**Comment by sbrannen** [comment]
This is potentially a duplicate of #2171.

Can you please try your example against JUnit Jupiter 5.7.0?

**Comment by sormuras** [comment]
Or, like in most case, some other file handle holds a lock on the file/directory on Windows.

**Comment by MichaelWarnecke** [comment]
Using org.junit.jupiter:junit-jupiter:5.7.0, the thrown exception is exactly the same. 

@sormuras was actually right. Apparently there was an open file handle due to the stream returned from `Files.list`. Using a try-with-resource around the stream, the code throws no more exceptions:

```
	@Test
	public void foo() throws MultipleFailuresError, IOException {
		Path dir = temp.resolve("dir");
		Files.createDirectories(dir);
		Files.createFile(dir.resolve("file"));
		try(Stream<Path> stream = Files.list(dir)) {
			assertAll(stream.map(f -> () -> {}));
		}
	}
```
