### ISSUE TITLE
Build against opentest4j 1.0.0-M1

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#245]
We are currently building against opentest4j snapshots, but before JUnit 5.0 M1 is released we will need to build against opentest4j 1.0.0-M1.

**Comment by marcphilipp** [comment]
I'm starting to work on this issue.

**Comment by marcphilipp** [comment]
Actually, I've misread the issue... I thought it was to change the dependency from 1.0.0-ALPHA to 1.0.0-SNAPSHOT. But that has already been done in 7626b32.

**Comment by marcphilipp** [comment]
This issue is *blocked* until #138 is completed.

**Comment by marcphilipp** [comment]
This issue is no longer _blocked_ because #138 has been _resolved_.

**Comment by marcphilipp** [comment]
I'm starting to work on this issue.

**Comment by sbrannen** [comment]
Thanks, @marcphilipp!
