### ISSUE TITLE
Improve user guide for Nested Tests (section 2.11.)

### ISSUE THREAD

**Issue by Chealer** [junit-team/junit5#2451]
## Deliverables

- A clear documentation of nested tests. Currently, section _Nested Tests_ contains:

> Nesting can be arbitrarily deep, and those inner classes are considered to be full members of the test class family with one exception: @BeforeAll and @AfterAll methods do not work by default.

It is unclear what the _test class family_ is.
It is also unclear how the _Nested test suite for testing a stack_ behaves.

**Comment by marcphilipp** [comment]
**Team decision:** Improve the nested tests section in the User Guide: (1) remove confusing "family" term, (2) add behavior description and IDE screenshot for "testing a stack" example.

**Comment by mmerdes** [comment]
in progress
