### ISSUE TITLE
ExtensionContext.Store#getOrComputeIfAbsent invokes the defaultCreator twice if the defaultCreator throws an exception

### ISSUE THREAD

**Issue by filiphr** [junit-team/junit5#2455]
## Steps to reproduce

```java
public class ConvertCmmnModelResolver implements ParameterResolver {

    @Override
    public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
        return CmmnModel.class.equals(parameterContext.getParameter().getType());
    }

    @Override
    public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {

        extensionContext.getRoot().getStore(ExtensionContext.Namespace.GLOBAL)
                .getOrComputeIfAbsent(extensionContext.getUniqueId(), key -> {
                    throw new RuntimeException("Test exception");
                });
        return null;
    }

}
```

I think that the fact that this is a parameter resolver doesn't matter. When this code is run the exception will be thrown twice.

The reason for that is the fact that the `MemoizingSupplier` does not handle the fact that the passed supplier might throw an exception in:

https://github.com/junit-team/junit5/blob/a37f726bc3f5241cdffd7491e16b0266002e0eb9/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionValuesStore.java#L201-L213

This means that when the exception is thrown the first time the value in the `MemoizingSupplier` is still `NO_VALUE_SET`. The supplier is than invoked again when the store is closed as part of:

https://github.com/junit-team/junit5/blob/a37f726bc3f5241cdffd7491e16b0266002e0eb9/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionValuesStore.java#L62-L70

## Context

 - Used versions (Jupiter): 5.7.0
 - Build Tool/IDE: Not relevant

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
Tentatively slated for 5.7.1 for investigation based on the assumption that this is in fact a bug, which it appears to be.
