### ISSUE TITLE
Junit 5 - BeforeEach, BeforeAll, AfterAll, AfterEach are completly ignored

### ISSUE THREAD

**Issue by martijnhiemstra** [junit-team/junit5#2459]
I have a maven project that I have loaded in Eclipse. I have setup a test class with a test method that gets executed when I right click the project and say Run as Junit test. So the tests work.

I now want to add a ```@BeforeAll ``` to my tests so that I can initailize stuff. I create a new class in the src/test/java directory and that class is called TestSuiteTest. I add the follwoing lines:

```
@BeforeAll
	static void setup() {
		System.out.println("@BeforeAll executed");
	}

	@BeforeEach
	void setupThis() {
		System.out.println("@BeforeEach executed");
	}

        // Without this test beforeall and such aren't even found
        @Test
	public void test_intest() {
		System.out.println("In Test executed");
	}

	@AfterEach
	void tearThis() {
		System.out.println("@AfterEach executed");
	}

	@AfterAll
	static void tear() {
		System.out.println("@AfterAll executed");
	}
```
Without the test_intest method the other methods are never called! It only works if I have 1 method in the class that has a ``` @Test ``` annotation and even then the behaviour is really really wierd. 

I see this is in the output:

```
testing test_myFirstTest // This is my test in another class which is executed before the BeforeAll. How is that possible???
@BeforeAll executed
@BeforeEach executed
In Test executed
@AfterEach executed
@AfterAll executed
```

This is in my maven dependencies:

```
               <dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>5.5.2</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.5.2</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-runner</artifactId>
			<version>1.5.2</version>
			<scope>test</scope>
		</dependency>
```

Even the order of the tests is complety wrong. How is this possible?

**Comment by marcphilipp** [comment]
`@BeforeAll` only applies to _all_ tests in that test class, not globally for all test classes.
