### ISSUE TITLE
Need alternative to TestInfo.getTestClass for inherited @Nested tests

### ISSUE THREAD

**Issue by sewe** [junit-team/junit5#2471]
I have a shared base class with a couple of `@Test` methods (like [this one](https://github.com/sewe/junit5-samples/blob/reproducer/junit5-jupiter-starter-gradle/src/test/java/com/example/BaseClass.java)).

Now suppose the `TestInfo` object injected into the test methods should be used to derive unique, test-specific directory names.

Unfortunately, no combination of `TestInfo.getTestClass()` and `TestInfo.getTestMethod()` does the trick, at least not for `@Nested` tests, as their `TestInfo.getTestClass()` is the base class, not the concrete subclass.

Consider [this reproducer](https://github.com/sewe/junit5-samples/commit/e4d905db390c371aedd3c56495c9c5cc3a84bc8c#diff-a349a9b76e6a99bbcce3b1d8711f2dbabe8c4fe238845e286629a7ea3344e2df) based on [junit5-samples](https://github.com/junit-team/junit5-samples):

```java
abstract class BaseClass {

    @Test
    void test(TestInfo testInfo) {
        String actualName = testInfo.getTestClass().get().getName();
        Assertions.assertTrue(actualName.matches("com.example.Example[123]Test"), actualName);
    }

    @Nested
    class NestedClass {

        @Test
        void nestedTest(TestInfo testInfo) {
            String actualName = testInfo.getTestClass().get().getName();
            Assertions.assertTrue(actualName.matches("com.example.Example[123]Test\\$NestedClass"), actualName);
        }
    }
}
```

```java
class Example1Test extends BaseClass { }
```

```java
class Example2Test extends BaseClass { }
```

While the test class for the two invocations of `BaseClass.test` is `Example1Test` and `Example2Test`, respectively, for the two invocations of `BaseClass.NestedClass.nestedTest` it is in both cases `BaseClass.NestedClass` (making `nestedTest` fail as written). This means that `TestInfo.getTestClass()` is unusable for deriving the name of a test-specific directory.

```
[INFO] Running com.example.Example1Test
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.example.Example1Test
[ERROR] nestedTest{TestInfo}  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: com.example.BaseClass$NestedClass ==> expected: <true> but was: <false>
	at com.example.BaseClass$NestedClass.nestedTest(BaseClass.java:22)

[INFO] Running com.example.Example2Test
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.025 s <<< FAILURE! - in com.example.Example2Test
[ERROR] nestedTest{TestInfo}  Time elapsed: 0.006 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: com.example.BaseClass$NestedClass ==> expected: <true> but was: <false>
	at com.example.BaseClass$NestedClass.nestedTest(BaseClass.java:22)
```

## Deliverables

I would hence like to see some alternative to `TestInfo.getTestClass()` (`getInvokedClass()` perhaps?), that changes based on the class that is "invoked" (for lack of a better name) by the test runner, not the class where the test method ultimately executed resides.

Alternatively, since for non-`@Nested` tests, `getTestClass()` already behaves as expected by me, it's behavior might be (incompatibly) changed for `@Nested` tests.

## Considered Alternatives

`@TempDir` is unfortunately not an alternative, for two reasons:
- The test-specific directories MUST to be created below a specific directory
- The directory names SHOULD be human-readable and easily correlatable to the tests; what `@TempDir` produces is too cryptic.

**Comment by marcphilipp** [comment]
You could do something like this:

```java
@ExtendWith(TestInstancesParameterResolver.class)
abstract class BaseClass {

    @Test
    void test(TestInstances testInstances) {
        String actualName = getActualName(testInstances);
        assertTrue(actualName.matches("com.example.Example[123]Test"), actualName);
    }

    @Nested
    class NestedClass {

        @Test
        void nestedTest(TestInstances testInstances) {
            String actualName = getActualName(testInstances);
            assertTrue(actualName.matches("com.example.Example[123]Test\\$NestedClass"), actualName);
        }
    }

    private static String getActualName(TestInstances testInstances) {
        return testInstances.getAllInstances().stream()
                .map(Object::getClass)
                .map(testClass -> {
                    if (testClass.getEnclosingClass() == null) {
                        return testClass.getName();
                    }
                    return testClass.getSimpleName();
                })
                .collect(joining("$"));
    }
}

class TestInstancesParameterResolver implements ParameterResolver {

    @Override
    public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
        return parameterContext.getParameter().getType().equals(TestInstances.class) && extensionContext.getTestInstances().isPresent();
    }

    @Override
    public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
        return extensionContext.getRequiredTestInstances();
    }
}
```

**Comment by sewe** [comment]
Interesting. The exact string is immaterial for me, as long as it is human-readable and unique per executed test. But kudos for all the class name mangling in `getActualName`.

I am just wondering whether something akin to `TestInstances` might make a nice additon to `TestInfo`, which seems ATM unaware of `@Nested` tests. (Or maybe `TestInfo.getParentInfo()`?)

`TestInfo.getDisplayName` also gives you just the display name of the deepest nested test, so you can’t piece together some breadcrumbs like `Outer test > Nested test"` from `TestInfo` either, which would fit my use case as well: human-readable, unique (if display names don’t clash) IDs for tests.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.
