### ISSUE TITLE
It should be possible to select inherited methods as tests

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#2476]
This issue is caused by https://github.com/spockframework/spock/issues/1235

It used to be possible to select an inherited tests in a child class.

`./gradlew test --tests *ChildSpec.parent`

My guess is that it is probably that line here
`return matcher.matchesTest(methodSource.getClassName(), methodSource.getMethodName());`

https://github.com/gradle/gradle/blob/46d60a4c6d72ce8880882e76a73d8db25d8aed9a/subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java#L179

Comment by @marcphilipp 
> The `MethodSource` is supposed to contain the declaring class, hence "source", and was introduced to allow IDE navigation. The filtering code could check for the parent descriptor's `ClassSource` in this case instead of using the `MethodSource`'s class name.

## Deliverables

- [ ] Enhance the filter code to allow to select inherited methods

**Comment by marcphilipp** [comment]
The filtering code that probably needs to be changed is in Gradle, not JUnit Platform. Would you mind opening a Gradle issue instead?
