### ISSUE TITLE
Passing TestExecutionListener to engine launched by EngineTestKit

### ISSUE THREAD

**Issue by nipafx** [junit-team/junit5#2480]
In junit-pioneer/junit-pioneer#375, we failed to write an integration test for an extension because it includes a `TestExectionListener` and the test run we launch with `EngineTestKit` didn't pick it up (at least it didn't call methods like `reportingEntryPublished` and `executionFinished` for the tests executed by that engine). Is that behavior intentional?

If so and it can't be changed (it would be somewhat weird to have an execution listener that listens to both the actual Jupiter run, but then also to the engine launched during one of those tests), it would be nice if we'd be able to register a listener explicitly. The `EngineExecutionListener` comes close, but I didn't find a way to register our own implementation.

**Comment by marcphilipp** [comment]
**Team decision:** The `EngineTestKit` is meant for testing engines. We had originally envisioned potentially adding a `LauncherTestKit` or sth. similar later. If you need to integration test with a `TestExecutionListener`, please use the `Launcher` API directly for the time being.
