### ISSUE TITLE
[IJ IDE] JUnit Jupiter Assumptions do not work in @BeforeAll methods 

### ISSUE THREAD

**Issue by Diego11914** [junit-team/junit5#2483]
I am still seen this issue on intelliJ

org.junit.jupiter
junit-jupiter-api
5.7.0
test
IntelliJ IDEA 2020.2.4 (Community Edition)
Build #IC-202.8194.7, built on November 24, 2020
Runtime version: 11.0.9+11-b944.49 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8

![image](https://user-images.githubusercontent.com/49316187/100390917-8b929880-2ff7-11eb-8140-11858f9c5c81.png)

**Comment by marcphilipp** [comment]
`@BeforeAll` methods have to be `static` unless you change the default test instance lifecycle to `PER_CLASS`.
