### ISSUE TITLE
Documentation Request - Improvement to Extension Order Documentation

### ISSUE THREAD

**Issue by JKomoroski** [junit-team/junit5#2486]
I was looking for a complete list of all extension interfaces and the order in which they are executed, but I the closest thing I was able to find was the [User code and extension code](https://github.com/junit-team/junit5/blob/main/documentation/src/docs/asciidoc/user-guide/extensions.adoc#extensions-execution-order-diagram) which is missing several extension user implementable extension interfaces. For example, as far as I can tell, `TestInstancePostProcessor` happens after `@BeforeEach` but before `@Test`. If these details exist in a java doc and I simply missed the documentation please point me to the right place in a comment and close.

## Deliverables

- [ ] Update [Extensions Doc](https://github.com/junit-team/junit5/blob/main/documentation/src/docs/asciidoc/user-guide/extensions.adoc) to include all stable and user facing extension interfaces.
- [ ] Consider documenting Experimental Interfaces such as `TestInstancePreDestroyCallback`
- [ ] Update acceptance requirements to include new extension interfaces in the execution order documentation when merged or migrated to `status = STABLE`

**Comment by marcphilipp** [comment]
The Javadoc lists all extension interfaces: https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/Extension.html

`TestInstancePreDestroyCallback` is documented (albeit not very detailed) here: https://junit.org/junit5/docs/current/user-guide/#extensions-test-instance-pre-destroy-callback

The execution order documentation is currently focused on the lifecycle extensions. We considered adding all extension interfaces there but had the impression it would get too complicated.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.
