### ISSUE TITLE
Filter DisabledIfEnvironmentVariable by OS.

### ISSUE THREAD

**Issue by jameshilliard** [junit-team/junit5#2487]
I'm looking for a way to scope `DisabledIfEnvironmentVariable` to a particular OS in order to disable certain unreliable tests when run in CI. I see there is a `DisabledOnOs` annotation available but it doesn't seem it can be used in combination with `DisabledIfEnvironmentVariable` for this purpose.

**Comment by marcphilipp** [comment]
Are those env vars you'd like to check present locally?

**Comment by jameshilliard** [comment]
No, it's only present on the CI system.

I'm basically trying to make this only apply to certain operating systems:
```java
@DisabledIfEnvironmentVariable(named = "GITHUB_ACTIONS", matches = "true")
```

**Comment by juliette-derancourt** [comment]
If you don’t have a `GITHUB_ACTIONS` variable locally, the test is going to be executed anyway :)
So I guess your solution already works?

**Comment by jameshilliard** [comment]
> If you don’t have a `GITHUB_ACTION` variable locally, the test is going to be executed anyway :)

Which is intended, I don't want any of these tests getting disabled at all when run locally as the failures only seem to happen on CI.

> So I guess your solution already works?

No, because I don't want to disable the tests on CI for operating systems that the tests are not broken on. I need to disable the tests only when I match both a specific CI ENV variable and specific OS.

For example a test may be broken on CI with Windows but it may work fine on CI with Linux or local Windows.

**Comment by marcphilipp** [comment]
As a workaround, you could write your own `ExecutionCondition` or maybe use sth. like `@DisabledIfEnvironmentVariable(named = "GITHUB_WORKSPACE", matches = "[A-Z]:.*")` to detect Windows-like paths.

**Comment by jameshilliard** [comment]
> detect Windows-like paths

Well that wouldn't work for disabling flaky OSX tests AFAIK.

Maybe adding an os filtering param would make sense?

Something like this:
```java
@DisabledIfEnvironmentVariable(named = "GITHUB_ACTIONS", matches = "true", os = {OS.WINDOWS, OS.MAC})
```

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by sbrannen** [comment]
> As a workaround, you could write your own `ExecutionCondition` or maybe use sth. like `@DisabledIfEnvironmentVariable(named = "GITHUB_WORKSPACE", matches = "[A-Z]:.*")` to detect Windows-like paths.

I'm not sure if we need a workaround or dedicated annotation for the combined use case. I guess it depends on how often people need such a combination for a custom execution condition.

In light of that, I consider the following a viable solution for the stated requirements.

```java
package example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledIf;
import org.junit.jupiter.api.condition.OS;

class DisabledIfTests {

	@Test
	void enabled() {
		System.out.println("enabled");
	}

	@Test
	@DisabledIf("example.DisabledIfTests#githubActionsOnMacOs")
	void disabled() {
		System.out.println("disabled");
	}

	static boolean githubActionsOnMacOs() {
		return OS.MAC.isCurrentOs() && "true".equals(System.getenv().get("GITHUB_ACTIONS"));
	}

}
```

Now that the `githubActionsOnMacOs()` method could reside in a separate class. I've used the fully qualified method name syntax in order to demonstrate that.

**Comment by sbrannen** [comment]
And if you want to encapsulate that in a custom annotation, the following works.

```java
package example;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import org.junit.jupiter.api.condition.DisabledIf;
import org.junit.jupiter.api.condition.OS;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Retention(RUNTIME)
@Target({ TYPE, METHOD })
@Documented
@DisabledIf("example.DisabledOnMacOsWithGitHubActions$Utils#githubActionsOnMacOs")
public @interface DisabledOnMacOsWithGitHubActions {

	static class Utils {

		static boolean githubActionsOnMacOs() {
			return OS.MAC.isCurrentOs()
					&& "true".equals(System.getenv().get("GITHUB_ACTIONS"));
		}
	}
}
```

You can then rewrite your test method as follows.

```java
@Test
@DisabledOnMacOsWithGitHubActions
void disabled() {
	System.out.println("disabled");
}
```

**Comment by jameshilliard** [comment]
> I'm not sure if we need a workaround or dedicated annotation for the combined use case.

In terms of syntax I think being able to pass multiple operating systems at the same time is desirable as it seems fairly common for a test to have issues on multiple operating systems. Most of the tests I was wanting to use this with would fail on CI for both mac and windows seemingly due to timing sensitive tests getting broken by unusually slow `sync()` calls on github CI.

**Comment by marcphilipp** [comment]
**Team decision:** In light of the above [solution](https://github.com/junit-team/junit5/issues/2487#issuecomment-751710288), we don't feel it's justified to introduce a new specialized annotation for such custom use cases.

**Comment by jameshilliard** [comment]
> In light of the above solution

That's pretty messy IMO, especially when this is an issue I've been running into frequently across different projects when adding additional OS CI runners(was doing that a lot recently due to travis-ci no longer offering free CI to open source projects).

> we don't feel it's justified to introduce a new specialized annotation for such custom use cases

Yeah, I agree that a specialized annotation for each combination of annotations is probably not a great solution, something more generalized probably makes more sense, maybe what would work best is having a filter parameter usable by all annotations that conditionally disables the annotation based on arbitrary filter objects.

Something like this maybe:
```java
@DisabledIfEnvironmentVariable(named = "GITHUB_ACTIONS", matches = "true", filters = {OsFilter.enabledIf( os = {OS.WINDOWS, OS.MAC} )})
```
which could also do negative matching:
```java
@DisabledIfEnvironmentVariable(named = "GITHUB_ACTIONS", matches = "true", filters = {OsFilter.disabledIf( os = {OS.LINUX} )})
```

The idea here would be that you would evaluate all the filters and only enable the annotation if all filters return true.

**Comment by marcphilipp** [comment]
Unfortunately, Java doesn't allow such expressions in annotations.
