### ISSUE TITLE
Rename extension APIs

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#249]
## Status Quo

JUnit 5 currently provides the following `Extension` APIs, which can be logically assigned to three categories.

*Conditional Text Execution*

- `ContainerExecutionCondition`
- `TestExecutionCondition`

*General Purpose*

- `InstancePostProcessor`
- `ExceptionHandler`
- `MethodParameterResolver`

*Test Lifecycle Callbacks*

- `BeforeAllCallback`
- `AfterAllCallback`
- `BeforeEachCallback`
- `AfterEachCallback`
- `BeforeTestMethodCallback`
- `AfterTestMethodCallback`

The semantics of the first and third categories should be self explanatory; however, the second category needs perhaps some clarification. Based on the current names, it would _appear_ to the casual observer that these extensions are general purpose, but that is not entirely the case. 

- `InstancePostProcessor` and `ExceptionHandler` are explicitly tied to the _test execution_, at the instance level and method level respectively, but their names imply that they can be used to post-process any instance (e.g., perhaps an extension instance if JUnit ever decides to support that) or handle any exception (e.g., perhaps thrown from a lifecycle callback).
- Similarly, although `MethodParameterResolver` is in fact dedicated to the resolution of parameters for methods, it could just as easily be applicable for the resolution of a parameter to any `java.lang.reflect.Executable` (i.e., a `Constructor` or a `Method`). Furthermore, if JUnit 5 were to introduce a parameter resolver API for constructors, the current names of methods in `MethodParameterResolver` would then be potentially misleading if not conflicting (disregarding method signatures).

## Proposal

In light of the aforementioned drawbacks to the current extension API names, I recommend that we aim for consistency in naming based on _where_ such extensions can be applied.

The names of the `ContainerExecutionCondition` and `TestExecutionCondition` APIs serve as good examples of the direction in which we should precede, leading logically to the following renaming.

- `InstancePostProcessor` --> `TestInstancePostProcessor`
  - `postProcessTestInstance()` --> _unchanged_
- `ExceptionHandler` --> `TestExecutionExceptionHandler`
  - `handleException()` --> `handleTestExecutionException()`
- `MethodParameterResolver`: to be addressed in #267
- `BeforeTestMethodCallback` --> `BeforeTestExecutionCallback`
  - `beforeTestMethod()` --> `beforeTestExecution()`
- `AfterTestMethodCallback` --> `AfterTestExecutionCallback`
  - `afterTestMethod()` --> `afterTestExecution()`

## Related Issues

- #267
- #268 

## Deliverables

- [x] Rename extension APIs as described in the aforementioned proposal.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, this issue is now open for discussion. 😉

**Comment by mmerdes** [comment]
@sbrannen 
such names are a means of categorizing something. Did you consider using different marker interfaces (instead or in addition to)? These would be a little bit like UML stereotypes.

**Comment by mmerdes** [comment]
In general I think the proposal constitutes an improvement - whether realized by mere renamings, or marker interfaces, or both.

**Comment by mmerdes** [comment]
I would personally  prefer to have the structural changes beyond the renaming in a separate issue.

**Comment by sbrannen** [comment]
@mmerdes, thanks for the feedback.

If you have suggestions for marker interfaces for categorization purposes, please tell us. In any case, I think we should add those in a different issue if we deem it appropriate.

We agreed in our last team call that we will address structural changes (e.g., generalization of the `MethodParameterResolver` API) in a separate issue.

cheers,

Sam

**Comment by sbrannen** [comment]
This issue is _blocked_ until #58 has been completed and merged into `master`.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, generalization of the `MethodParameterResolver` API will be addressed separately in issue #267.

I have slated #267 for M2 for the time being; however, I would prefer to get this additional breaking change into M1 along with #249 (i.e., the earlier the better). 

Thoughts?

**Comment by marcphilipp** [comment]
Ok by me if we get it in on time.


Am 16. Mai 2016, 17:32 +0200 schrieb Sam Brannen<notifications@github.com>:

**Comment by sbrannen** [comment]
This issue is no longer _blocked_ since #58 has been completed.

**Comment by sbrannen** [comment]
Closing this issue since it has been addressed in the following commits:

- ebfdc4d7fcb4a71c7ae88521ae197d951bbbdcda
- c7c0d24a3b6b46868d732e6358834c2ddf81ad48
- 6b9f227921f86893f4a759b578f4d197437cbae9
- f68eba6bd690e5686b9b6492db3ea36f758b7b4c
