### ISSUE TITLE
Add an `assertInstanceOf` to Jupiter assertions

### ISSUE THREAD

**Issue by jbee** [junit-team/junit5#2492]
In cases where `assertThrows` cannot be used as the test setup is more intricate than a single operation there is still the need to assert that expected exceptions are of a certain `instanceof` type. 

The naive way to test this would be for example:
```java
assertTrue(e instanceof IllegalStateException);
```
as I had used it here
https://github.com/jbee/purejin/pull/137/files#diff-567a735adbd51f614bf6f2beb67d86ff5ec9d3c7933d59cd0a49b89a6742e39eR68-R71

The downside of this is clearly that the message of this assertion isn't useful.
A custom message could be assembled to improve that but I basically would want to rebuild what `assertThrows` already does https://github.com/junit-team/junit5/blob/7f5e22536b26a99b310f565de7df9d8a0518b079/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java#L63-L65

So I think this could be extracted to a method in the API either especially for exceptions or more generally to assert that a value is an instance of some specific type.

For completeness the API I imagine would be:
```java
void assertInstanceOf(Class<?> expected, Object actual);
// and/or
void assertExceptionOfType(Class<? extends Throwable> expected, Throwable actual);
```

**Comment by sormuras** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by sormuras** [comment]
An `assertInstanceOf` assertion sounds good, simple, and useful.

@jbee, would you like to provide a PR?

**Comment by jbee** [comment]
@sormuras I'll give it a try

**Comment by bjmi** [comment]
After discovering that assertion I find it really expressive and useful.
Could you please also add a Kotlin variant of `assertInstanceOf` to _Assertions.kt_? E.g.

Usage:
```
Now:            assertInstanceOf(String::class.java, actual)
Kotlin version: assertInstanceOf<String>(actual)
```

Definition:
```
inline fun <reified T : Any> assertInstanceOf(actualValue: Any?): T =
    Assertions.assertInstanceOf(T::class.java, actualValue)
...
```

**Comment by marcphilipp** [comment]
@bjmi Sounds like that would be a good addition. Could you please raise a new issue for that or send a PR?

**Comment by bjmi** [comment]
Promote new `assertInstanceOf` in IntelliJ [IDEA-322244](https://youtrack.jetbrains.com/issue/IDEA-322244).
