### ISSUE TITLE
Publish to MavenCentral

### ISSUE THREAD

**Issue by jaredsburrows** [junit-team/junit5#250]
Just like `compile 'junit:junit:4.12'` can be used in Gradle and downloaded from MavenCentral, when can we upload Junit 5 to MavenCentral?

**Comment by smoyer64** [comment]
Maven central is generally for releases ... you can get the 5.0.0-ALPHA and 5.0.0-SNAPSHOT from the Sonatype SNAPSHOT repository:

https://oss.sonatype.org/content/repositories/snapshots/org/junit/

You can either add this to your project's repositories definition *OR* if you're using Nexus or Artifactory (or others) to mirror external repositories and/or host your own, you can add the Sonatype SNAPSHOT repository there.

**Comment by sbrannen** [comment]
JUnit `5.0.0-ALPHA` artifacts are already available in [Maven Central](http://search.maven.org/#search|ga|1|org.junit).

As discussed in the [JUnit 5 User Guide](http://junit.org/junit5/docs/current/user-guide/#dependency-metadata), `5.0.0-SNAPSHOT` artifacts can be consumed from Sonatype’s [snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/org/junit/).

You can see a concrete example for the latter in the [junit5-maven-consumer](https://github.com/junit-team/junit5-samples/tree/master/junit5-maven-consumer) project.

I am therefore closing this issue as _invalid_.
