### ISSUE TITLE
Pointing failed assertions in external resource and not Java test

### ISSUE THREAD

**Issue by splatch** [junit-team/junit5#2504]
I come across an interesting question which seems to be unanswered both in documentation and source code.

I have a set of dynamic tests which are really about going over XML document and comparing binary input with expected XML output created out of hex stream. Thanks to `testSourceUri` parameter I am able to hint IDE where to look for tests (`?line=&column=`), now I seek for second step - assertion errors.

When any of my test fails I would like to point at least to location where it started to fail. Currently stack traces are closely related to Java and test itself. Reason why I would like to ease is due to fact that suite XML can be pretty long and involve multiple steps. Navigating over it to can be sometimes trouble. It really boils down to "how to throw" an error so it gets different location than one in Java stack trace.

Here is example element used to create assertion: https://github.com/apache/plc4x/blob/develop/protocols/ads/src/test/resources/protocols/ads/AdsDiscoverySerializerTest.xml#L77L108

 I managed to achieve partial result by manipulating exception stack trace, yet IDE doesn't feel lucky when I point xml file instead of java one. It still opens exception class file instead of stack trace file location (set to XML). I know this is super ugly hack, but couldn't hold myself from checking it.

**Comment by marcphilipp** [comment]
You mean something similar to Gradle's `LocationAwareException`, I assume? https://github.com/gradle/gradle/blob/60bfa1f23acf482a270540cfef8e31e76551ec30/subprojects/core/src/main/java/org/gradle/internal/exceptions/LocationAwareException.java

If so, we'd have to check if IDEs already support some kind of syntax to link to a file location, e.g. by parsing the exception message.

**Comment by splatch** [comment]
Yes, it seems to match the need - an exception (or assertion error) pointing file and optionally line and column number. Just like `FileSource` does.

**Comment by marcphilipp** [comment]
Could you use report entries for that?

**Comment by splatch** [comment]
Not sure what you mean by  "report entries". Can you elaborate a bit more?

**Comment by marcphilipp** [comment]
I was wondering whether it would help you to write an extension that would [publish report entries](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtensionContext.html#publishReportEntry(java.util.Map)) (e.g. for file, line and column number) and a custom `TestExecutionListener` that would [receive them](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/TestExecutionListener.html#reportingEntryPublished(org.junit.platform.launcher.TestIdentifier,org.junit.platform.engine.reporting.ReportEntry)) and write them to some kind of report. While extension support for dynamic tests is very limited, you could write an invocation interceptor that would catch a custom exception and publish the necessary info via a report entry.

**Comment by Michael1993** [comment]
Can you throw a custom `AssertionFailedError(String message, Object expected, Object actual, Throwable cause)` from your dynamic tests?

IntelliJ supports that, you can click on a nice "click to show difference" button and it highlights the difference for you.
![image](https://user-images.githubusercontent.com/4085611/103658827-068e8d80-4f6c-11eb-8877-eff2308c346a.png)

Sorry if I misunderstood something.

**Comment by splatch** [comment]
I do have assertion error which is thrown from test framework extension itself. There is a diff and information what is wrong (diff from xmlunit), last thing to make it functional is navigation to failed element.

**Comment by marcphilipp** [comment]
I think this could be solved by adding an optional URI (cf. `UriSource.from(URI)`) to `AssertionFailedError` that IDEs could resolve.

@splatch Since that needs to be done in OpenTest4J, please open an issue over there in case this is still relevant for you.
