### ISSUE TITLE
assertThrows doesn't fail if the thrown exception is of child type

### ISSUE THREAD

**Issue by govi20** [junit-team/junit5#2505]
## Steps to reproduce

`assertThrows(FileNotFoundException.class, () -> service.readFile("sampleFile.txt")); `

this assertion will pass even if the thrown exception is IOException or Exception.

I believe this is happening because we are using `Class#isInstance` it will return true for parent types also.

https://github.com/junit-team/junit5/blob/637a78393194737e77d6f9681ad93e9ddac1f399/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java#L58

Shouldn't this be replaced with `if (expectedType == actualException.getClass())` ?

**Comment by sormuras** [comment]
Works for me:

```java
  @Test
  void testAssertThrows() {
    assertThrows(FileNotFoundException.class, this::throwFileNotFoundException);
    assertThrows(IOException.class, this::throwFileNotFoundException);
    assertThrows(Exception.class, this::throwFileNotFoundException);
    assertThrows(Throwable.class, this::throwFileNotFoundException);

    // assertThrows(FileNotFoundException.class, this::throwIOException); // fails
    assertThrows(IOException.class, this::throwIOException);
    assertThrows(Exception.class, this::throwIOException);
    assertThrows(Throwable.class, this::throwIOException);
  }

  private void throwFileNotFoundException() throws FileNotFoundException {
    throw new FileNotFoundException();
  }

  private void throwIOException() throws IOException {
    throw new IOException();
  }
```

With `assertThrows(FileNotFoundException.class, this::throwIOException)` it yields:

```
Unexpected exception type thrown ==> expected: <java.io.FileNotFoundException> but was: <java.io.IOException>
```

**Comment by govi20** [comment]
@sormuras Seems, it's reverse, if the assertion expects Parent type and if the test code throws child type Exception it always passes. 

```
    @Test
    void testAssertThrows() {
        assertThrows(IOException.class, this::throwCustomException);
     }

    private void throwCustomException() throws FileNotFoundException {
        throw new FileNotFoundException();
    }
```

As a workaround, I am checking the Class type explicitly

```
	Throwable throwable =  assertThrows(Throwable.class, () -> {
		service.readFile("sampleFile.txt");
	});
	assertEquals(FileNotFoundException.class, throwable.getClass());
```

**Comment by sormuras** [comment]
The current behaviour is intended. The [API documentation](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html#assertThrows(java.lang.Class,org.junit.jupiter.api.function.Executable)) of `assertThrows` could need a refinment pass, though.

Be as specific as possible, when using `assertThrows`.

**Comment by govi20** [comment]
@sormuras thanks for the feedback, 
Even if I assert on the specific type, but if the specific type is RuntimeException and somebody changes the behavior and changes it to child type. shouldn't the test fail? 

for e.g. below code:

```
    @Test
    void testHttpErrorCodeException() {
        assertThrows(HttpResponseException.class, () -> reThrowSpecifiException(500));
        assertThrows(RuntimeException.class, () -> reThrowSpecifiException(404));
     }

    private void reThrowSpecifiException(int httpsStatusCode) {
        if(httpsStatusCode == 500) {
            throw new HttpResponseException();
        } else {
            throw new RuntimeException();
        }
    }
```

Now if someone modifies the code as below, I feel the second assertion should fail.

```
    @Test
    void testHttpErrorCodeException() {
        assertThrows(HttpResponseException.class, () -> reThrowSpecifiException(500));
        assertThrows(RuntimeException.class, () -> reThrowSpecifiException(404));
    }

    private void reThrowSpecifiException(int httpsStatusCode) {
        throw new HttpResponseException();
    }
```

**Comment by marcphilipp** [comment]
The current behavior is designed to work like in a try-catch block. We could introduce another assertion, e.g. `assertThrowsExactly`.

**Comment by sormuras** [comment]
Yeah.

Perhaps a better name would have been: `assertCatches(? extends Throwable, try-block)`

**Comment by sormuras** [comment]
Also related to #2492, where an `assertInstanceOf(...)` is being introduced.

**Comment by marcphilipp** [comment]
@govi20 Could you please create a new issue, describe your use case and propose adding an `assertThrowsExactly` assertion method?

**Comment by govi20** [comment]
@marcphilipp hi, created an enhancement issue https://github.com/junit-team/junit5/issues/2509

if you guys are okay with the new API, I am happy to work on the patch.
