### ISSUE TITLE
Document constant value for ExclusiveResource.GLOBAL_KEY

### ISSUE THREAD

**Issue by mpkorstanje** [junit-team/junit5#2508]
Cucumber integrates with the JUnit Platform by implementing a test engine. This engine extends the `HierarchicalTestEngine` and inherits its support to lock resources. Because Cucumber uses plain text files we can not references constants from a class e.g:

```
@ResourceLock(ExclusiveResource.GLOBAL_KEY)
```
but instead have to [reference the plain text value in a configuration file](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#running-tests-in-isolation):

```
cucumber.execution.exclusive-resources.isolated.read-write=org.junit.platform.engine.support.hierarchical.ExclusiveResource.GLOBAL_KEY
```

Currently the value of `ExclusiveResource.GLOBAL_KEY` is not documented in the Javadoc and not part of the API. As such Cucumber and other non-java based engines can't depend on this value to run tests in isolation.

Note: The same is also true for all constants in `Resources`. And I somewhat would expect `GLOBAL_KEY` to be documented here rather then in `ExclusiveResource`.

## Deliverables

- [ ] Document the value of `ExclusiveResource.GLOBAL_KEY` in the JavaDoc using `{@value}` in `Resources`.
- [ ] Optionally document the values of `Resources.*` in the JavaDoc using `{@value}`.

**Comment by marcphilipp** [comment]
Sounds like a good plan! We should then also reference the new `Resources.GLOBAL` constant from `@Isolated`. Do you have time to submit a PR for this?

**Comment by mpkorstanje** [comment]
> Do you have time to submit a PR for this?

Done.
