### ISSUE TITLE
Make TreePrintingListener available for custom engines

### ISSUE THREAD

**Issue by mythsunwind** [junit-team/junit5#2517]
The class and the constructor of TreePrintingListener are not public and cannot be used by custom test engines. Code of listener:
https://github.com/junit-team/junit5/blob/main/junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrintingListener.java

I'm working on my own HierarchicalTestEngine and would like to reuse this listener instead of re-implementing it. Would it be possible to allowing access to it so that a custom engine can use it?

## Deliverables

- [ ] Make class public
- [ ] Make constructor public

**Comment by marcphilipp** [comment]
Duplicate of #1963

**Comment by marcphilipp** [comment]
Duplicate of #1963

**Comment by marcphilipp** [comment]
@mythsunwind Thanks for raising the issue. Please voice your interest and describe your use case in #1963.
