### ISSUE TITLE
Add capability to get all configuration parameters

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#2520]
As a test engine provider I'd like to check if users trying to provide the engine with parameters use the correct parameter keys and warn about unknown keys or potential spelling errors. In order to check that, I need some way to get at all configuration parameters - or at least those specified in file `junit-platform.properties` - with my engine's prefix, e.g. "jqwik.". 

The signiature could look like:

`Set<String> ConfigurationParameters.allWithPrefix(String prefix)`

Maybe class `org.junit.platform.engine.support.config.PrefixedConfigurationParameters` is the better place for such a method?

**Comment by marcphilipp** [comment]
Would a `Set<String> keySet()` that you could filter for the engine's prefix also work for you? Returning all keys would include all system properties, though, and hence would be inconsistent with `size()` which currently only takes into account explicit configuration parameters passed as part of the discovery request. Technically, we could change the semantics of `size()` but I'm not sure who relies on the current behavior. Thoughts?

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by jlink** [comment]
`keySet()` would work for me.

As for `size()`, I never understood its intention in the first place. What are typical intended use cases?

**Comment by marcphilipp** [comment]
That's a good question. It looks like it was added for testing in https://github.com/junit-team/junit5/commit/6d3cbe6240ef9bcc2aec860f0400a6edd0bdd6bf.

Thus, I think changing it's semantics or even deprecating it would be fine.

**Comment by marcphilipp** [comment]
**Team decision:** Let's introduce `keySet()` and deprecate `size()`.

@jlink Do you have time to submit a PR for this?

**Comment by jlink** [comment]
@marcphilipp I can try.
