### ISSUE TITLE
add SHORT_DISPLAY_NAME and LONG_DISPLAY_NAME to ParameterizedTest

### ISSUE THREAD

**Issue by chia7712** [junit-team/junit5#2525]
## Status Quo

By default, the display name of ```ParameterizedTest``` is similar to ```RepeatedTest#SHORT_DISPLAY_NAME```. If we want to make display name include "method name", we have to write string formate like ``` "{displayName} - {arguments}"``` for all test cases. It seems to me ```RepeatedTest#LONG_DISPLAY_NAME``` is a good example and it would be better to introduce ```LONG_DISPLAY_NAME``` to ```ParameterizedTest```. The benefit is that junit 5 users can replace aforementioned string format by "standard" long display name.

```java
@ParameterizedTest(name = ParameterizedTest.LONG_DISPLAY_NAME)
```

## Considerations

```java
	String SHORT_DISPLAY_NAME = "[" + INDEX_PLACEHOLDER + "] " + ARGUMENTS_WITH_NAMES_PLACEHOLDER;
	String LONG_DISPLAY_NAME = DISPLAY_NAME_PLACEHOLDER + " :: " + SHORT_DISPLAY_NAME;
        String DEFAULT_DISPLAY_NAME = SHORT_DISPLAY_NAME
```

## Deliverables

N/A

**Comment by sbrannen** [comment]
Superseded by  #2526.

If you are going to immediately submit a PR, there is no need to create an issue first.
