### ISSUE TITLE
@CsvSource fails when values start with the number sign (#)

### ISSUE THREAD

**Issue by ZeroOne3010** [junit-team/junit5#2527]
Greetings,

I'm using **junit-jupiter-api** and **junit-jupiter-params** version **5.7.0**. I was developing a method to parse hexadecimal color strings, such as #BFFF00, into their red/green/blue components. I figured the `@CsvSource` would be a great way to do this:

```java
  @ParameterizedTest
  @CsvSource({
      "#ff0000,1,0,0",
      "#00ff00,0,1,0",
      "#0000ff,0,0,1"
  })
  void hexToColor(final String input, final float expectedRed, final float expectedGreen, final float expectedBlue) {
    // assert stuff
  }
```

As it stands, however, even the stub test above just crashes before it is ever executed, printing out the error message **org.junit.platform.commons.PreconditionViolationException: Line at index 0 contains invalid CSV: "#ff0000,1,0,0"**. I dug into the matter and found out that the # sign is considered a comment character by default by the underlying `com.univocity.parsers.csv.CsvParser` CSV parser. 

Now, in this case when I'm just supplying a static set of strings **I would expect that all of my lines were parsed**. It is a different business with the `@CsvFileParser` annotation, but that is out of scope for the issue at hand. The comment character used by the underlying library could be changed, but there is no use for that feature with the `@CsvSource` annotation and the `CsvArgumentsProvider`, as it just throws an error in case it encounters a commented-out line anyway.

I have prepared a change that would enable the usage of the number sign in the context of the `@CsvSource` annotation, while preserving the existing functionality of ignoring commented-out lines in the context of a `@CsvFileSource`. This is not even a breaking change but just a bug fix, as nobody could have possibly used the number sign with the `@CsvSource` before.

**Comment by sbrannen** [comment]
Superseded by  #2528.

If you are going to immediately submit a PR, there is no need to create an issue first.
