### ISSUE TITLE
Junit 4.13.1 version can't be parsed by JUnit4VersionCheck

### ISSUE THREAD

**Issue by david-m-s** [junit-team/junit5#2529]
Using cucumber 6.9.1 which brings junit 4.13.1 and  junit-vintage-engine 5.7.0 at some point there is a check for junit version and the JUnit4VersionCheck class can't handle x.y.z format, just x.y

I'm having this exception:

> Caused by: org.junit.platform.commons.JUnitException: Failed to parse version of junit:junit: 4.13.1
> 	at org.junit.vintage.engine.JUnit4VersionCheck.parseVersion(JUnit4VersionCheck.java:54)
> 	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:37)
> 	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:32)
> 	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:62)
> 	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)

**Comment by marcphilipp** [comment]
That was fixed in #2198 for 5.6.3 and 5.7.0. Are you sure you're using junit-vintage-engine 5.7.0?

**Comment by david-m-s** [comment]
True, sorry I see it's actually 5.6.2. Closing.

**Comment by marcphilipp** [comment]
No worries, thanks for reporting back! 👍
