### ISSUE TITLE
Document concurrency considerations for TestExecutionListener implementations

### ISSUE THREAD

**Issue by jaikiran** [junit-team/junit5#2539]
I've been looking at some documentations to see if there is any thread safety semantics to consider when implementing a `org.junit.platform.launcher.TestExecutionListener`. I haven't found any, so asking here.

More specifically, is there ever a case where the same instance of `TestExecutionListener` could get invoked by multiple threads (simultaneously), such that these implementations need to handle any thread safety issues? If so, is it only for certain methods or do all methods on that interface's implementation need to take into account this aspect? For example, in theory, I wouldn't expect more than one thread invoking the `testPlanExecutionFinished` method.

**Comment by marcphilipp** [comment]
Good point, we should document that. `testPlanExecutionStarted` and `testPlanExecutionFinished` are always called from the same thread and it's safe to assume there's at most one `TestPlan` at a time (in theory, someone could call the `Launcher` concurrently but AFAIK no tool does that). All other method could be called from different threads concurrently in case one or multiple test engines execute tests in parallel.

**Comment by jaikiran** [comment]
@marcphilipp, thank you. That answer helps me decide how to go about one of the implementations in Apache Ant.

**Comment by jbduncan** [comment]
The proposed documentation change sounds useful to me, so I wonder if this issue should be re-opened?

**Comment by edysli** [comment]
I'd like to give this one a try. :)
Is updating the Javadoc on `org.junit.platform.launcher.TestExecutionListener` enough, or is there another guide to update as well?
