### ISSUE TITLE
Logs get dumped to console all at once when the execution is over, instead of being printed in real time

### ISSUE THREAD

**Issue by PataviniMa** [junit-team/junit5#2541]
Hello,

I'm working on a test automation project using Maven (with Surefire plugin) and JUnit 5. Since I have very long-running UI scripts (up to 20 minutes), I make intensive use of logging to the console. This is crucial to me, at least in the developing phase of each script. However, logs gets dumped all at once at the end of the execution, instead of being printed in real-time. I realize this makes perfect sense in case of parallel execution (to avoid overlapping issues), but I would like a way to disable this when executing in a serial fashion. I've searched both Surefire and JUnit documentations, but I can't seem to find a way. Any help would be appreciated. This is a very simple dummy project to reproduce the issue:

`projectRoot/pom.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.example</groupId>
    <artifactId>project</artifactId>
    <version>1.0</version>
    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M5</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

`projectRoot/src/test/java/DummyTest.java`:

```java
import org.junit.jupiter.api.Test;

public class DummyTest {
    @Test
    public void ConsoleLoggingTest() {
        System.out.println("STARTING TEST...");
        try { Thread.sleep(30000); } catch (Exception ignored) { } //SIMULATE LONG-RUNNING TASK
        System.out.println("TEST IS FINISHED!");
    }
}
```

I use to execute tests with the `mvn test` command in my IDE (IntelliJ IDEA). Please note that I used `System.out.println()` for the sake of simplicity, but I get the same behavior using any logging library, like log4j.

**Comment by sbrannen** [comment]
When executing tests via Maven Surefire, aggregation of console output is under the control of Surefire and therefore cannot be influenced by the JUnit Platform itself -- right @marcphilipp and @sormuras ?

**Comment by PataviniMa** [comment]
@sbrannen thanks for the answer. Indeed, running the test through the integrated JUnit plugin in my IDE results in real-time logging as expected. However, I can remember having a similar setup a couple of years ago (Surefire 2.x + JUnit 4) and I've never experienced this issue. So, do I have to assume that the culprit is the latest version of Maven Surefire? Is there any JUnit configuration parameter to control this behavior?

**Comment by sbrannen** [comment]
If I'm not mistaken, the only way to control the aggregation of console output when using Surefire would be via a mechanism (configuration option) in Surefire itself.

Perhaps @sormuras can shed more light on the subject.

**Comment by marcphilipp** [comment]
AFAIK Surefire prints output directly to the build log unless it's configured to write it to a file. In any case, JUnit is not doing anything special in the above setup so you'll probably be better off asking the Surefire team for help.

**Comment by PataviniMa** [comment]
If there's no configuration I can try on JUnit side, then I'll try to ask the Surefire team.
It feels so strange, however, that such a fundamental piece of information is missing from the docs. Hope I'm not missing something obvious.

**Comment by sbrannen** [comment]
Closing in favor of following up with the Maven Surefire team.
