### ISSUE TITLE
API Guardian should be optionally imported in OSGi metadata

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2547]
From: https://github.com/junit-team/junit5/pull/2095#pullrequestreview-314557992:

> 2\. API guardian must not be imported (as previously discussed in #1353).

From #1353:

> > As https://github.com/apiguardian-team/apiguardian is also a compile-time dependency, does it also be OSGi-fied?
> 
> No, that should not be necessary since it's not a runtime dependency.

My question: if API guardian is not intended to be a runtime dependency, then why is it defined with `RUNTIME` retention? I feel that if it has runtime retention, users would be entitled to expect it to be available at runtime.

Therefore, I feel that for consistency reasons, we should do one of the following:
* either API Guardian should be osgi-ified and it should be imported by bundles that use it (can be an optional import as the bundle will run without it), or
* we should consider changing the retention of `@API` to `CLASS`.

Thoughts?

**Comment by sbrannen** [comment]
>     * either API Guardian should be osgi-ified and it should be imported by bundles that use it (can be an optional import as the bundle will run without it),

That sounds reasonable.

>     * we should consider changing the retention of `@API` to `CLASS`.

The `@API` annotation is supported for runtime access via the Java reflection APIs. Thus changing the retention from `RUNTIME` to `CLASS` is not an option in my opinion.

**Comment by kriegfrj** [comment]
> The `@API` annotation is supported for runtime access via the Java reflection APIs. Thus changing the retention from `RUNTIME` to `CLASS` is not an option in my opinion.

If that is an anticipated use case, then we should definitely OSGi-ify the API Guardian jar and change the JUnit 5 bundles to optionally import the packages, otherwise the annotations won't be available for reflection for code running inside an OSGi framework.

**Comment by kriegfrj** [comment]
Raised https://github.com/apiguardian-team/apiguardian/issues/22 to deal with the API-guardian side of this. Can't progress this issue until there is a version of API Guardian publically available with OSGi metadata.

**Comment by kriegfrj** [comment]
> Raised apiguardian-team/apiguardian#22 to deal with the API-guardian side of this.

A PR has now been raised for this: apiguardian-team/apiguardian#23

> Can't progress this issue until there is a version of API Guardian publically available with OSGi metadata.

Actually, I realised that this is not true - we could modify the current JUnit 5 bundles so that they *optionally* import API Guardian and it won't matter that there is no publicly available bundle yet. That would close off this issue without needing to wait for the next API Guardian release. (And in fact, I realised that there is a public OSGi version of API Guardian available in the Eclipse repositories that form part of the Eclipse distribution - I used a different BSN to make sure that we don't clash.)

**Comment by marcphilipp** [comment]
> I used a different BSN to make sure that we don't clash

What's a BSN?

**Comment by sbrannen** [comment]
> What's a BSN?

Bundle Symbolic Name

See... I still remember something from my OSGi days. 😉

**Comment by kriegfrj** [comment]
Yes, a BSN is an identifier that (together with the bundle version) uniquely identifies a bundle. If you have two different bundles with the same BSN, it can cause issues. The Eclipse bundle's BSN is `org.apiguardian` whereas this PR's is `org.apiguardian.api` (which is the same as the bundle's module name).

**Comment by marcphilipp** [comment]
> My question: if API guardian is not intended to be a runtime dependency, then why is it defined with `RUNTIME` retention?

We used to have it as a `compileOnly` dependency but that led to downstream projects, i.e. projects containing tests that used Jupiter annotations, to get compiler warnings because the `API.Status` enum was missing. We could switch that to `compileApiOnly` so at least Gradle projects wouldn't have it on their test runtime classpath.

**Comment by marcphilipp** [comment]
**Team decision:** Let's add OSGi metadata to API Guardian and optionally import it in JUnit, as you've proposed.

**Comment by marcphilipp** [comment]
@kriegfrj Now that https://github.com/apiguardian-team/apiguardian/pull/23 is merged can we update to 1.1.2-SNAPSHOT and simplify our setup?

**Comment by kriegfrj** [comment]
Yes! If I had thought of it I would have held off and done that from the start, rather than waste time and effort figuring out how to add the right version imports for the non-OSGi jar! At least I learned something about Gradle! 😄

**Comment by marcphilipp** [comment]
I should have thought of it as well. Thanks for taking care if this so quickly! 👍

**Comment by kriegfrj** [comment]
> I should have thought of it as well. Thanks for taking care if this so quickly! 👍

It wasn't a complete loss - the hoops I jumped through to get the version on there made it easier to fix it this time as I only had to do it in one place.
