### ISSUE TITLE
Inconsistent @TempDir behaviour

### ISSUE THREAD

**Issue by gebezs** [junit-team/junit5#2550]
The `@TempDir` behaves differently if a non-test level resource is annotated than a test-level.

If I annotate an attribute or static field in my test than the annotated parameter will be same as the field.
This is true for `@BeforeAll` and `@BeforeEach` method as well.
```java
public class SameTempDirTest {
  @TempDir
  public Path attribute;

  @Test
  public void test1(@TempDir Path parameter) {
    assertEquals(attribute, parameter);
  }

  @Test
  public void test2(@TempDir Path parameter) {
    assertEquals(attribute, parameter);
  }
}
```

However if I only annotate the test method parameters than they will be different.
```java
public class DifferentTempDirTest {
  private Path otherParameter;

  @Test
  public void test1(@TempDir Path parameter) {
    if (otherParameter == null) {
      otherParameter = parameter;
    } else {
      assertNotEquals(otherParameter, parameter);
    }
  }

  @Test
  public void test2(@TempDir Path parameter) {
    if (otherParameter == null) {
      otherParameter = parameter;
    } else {
      assertNotEquals(otherParameter, parameter);
    }
  }
} 
```

This is an inconsistent behavior which could cause issues.
One potential problem when I already have multiple test methods annotated with `@TempDir` and for some reason I want to use `@BeforeAll` with a `@TempDir` which will result all of the previously different temp dirs to be the same.

## Steps to reproduce
The [inconsistent-tempdir.zip](https://github.com/junit-team/junit5/files/5964361/inconsistent-tempdir.zip) file contains a maven project with the two test classes.

## Context

 - Used versions Jupiter 5.7.0
 - Build Tool/IDE: Maven, Intellij IDEA (same result in both)

## Deliverables
- [ ] Option 1: Consistent way of working for normal tests and tests created by `TestFactory` like `ParameterizedTest`.
- [ ] Option 2: Show an error if test and higher level `@TempDir` annotations present.
- [ ] Option 3: A more detailed configuration like in #1967
- [ ] The #2219 is similar issue but for multiple annotations on same level.

**Comment by marcphilipp** [comment]
This actually works as designed: if you create the temp dir on the class level (e.g. by using `@TempDir` on a `@BeforeAll` method parameter), it will be created for the test class. #1967 will add an option to create different temporary directories and hence supersedes this issue.
