### ISSUE TITLE
Support declarative extension registration on lifecycle methods

### ISSUE THREAD

**Issue by dakusui** [junit-team/junit5#2555]
```@ExtendWith``` annotation attached to a custom "before all" annotation is not respected.
When it is attached to an annotation interface with a "@TestTemplate", it lets JUnit use an extension specified by it.
However, when it is attached to an interface with ```@BeforeAll``` annotation, JUnit doesn't use the extension and keep performing the default behaviour, apparently.

*Expectation:*
If the extension specified by the "@ExtendWith" is implementing "before all callback extension" , the ```beforeAll(ExtensionContext)``` method should be called back.

That is, with the code example I placed in "Steps to reproduce", it should print following.

```
beforeAll(ExtensionContext) is called
beforeAll is called
customBeforeAll is called
test is called
```

*Actual:*
The ```beforeAll(ExtensionCotext)``` of the provided extension is not called back.
That is, we see a following output when we run the test in the "Steps to reproduce" section.

```
beforeAll is called
customBeforeAll is called
test is called
```

## Steps to reproduce
Run following class from your IDE. (in my case IntelliJ).

```java
package com.github.dakusui.jcunitx.engine.junit5;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;

import java.lang.annotation.Retention;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

public class Example {
  @BeforeAll
  @Retention(RUNTIME)
  @ExtendWith(CustomBeforeAllExtension.class)
  public @interface CustomBeforeAll {
  }

  public static class CustomBeforeAllExtension implements BeforeAllCallback {
    @Override
    public void beforeAll(ExtensionContext context) {
      System.out.println("beforeAll(ExtensionContext) is called");
    }
  }

  @BeforeAll
  public static void beforeAll() {
    System.out.println("beforeAll is called");
  }

  @CustomBeforeAll
  public static void customBeforeAll() {
    System.out.println("customBeforeAll is called");
  }

  @Test
  public void test() {
    System.out.println("test is called");
  }
}
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.7.1
 - Build Tool/IDE: IntelliJ

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
Tentatively slated for 5.8 M2 solely for the purpose of _team discussion_

**Comment by sbrannen** [comment]
## Related Issues

- #864
- #1986

**Comment by marcphilipp** [comment]
**Team decision:** We don't want to add another way to register extensions, in particular since `BeforeAllCallbacks` should be registered on the class-level.
