### ISSUE TITLE
Document fully qualified method name syntax for custom conditions

### ISSUE THREAD

**Issue by DaeAkin** [junit-team/junit5#2556]
Hi,

I am studying JUnit5 by looking at the official documentation.

While studying, I have a question for custom condition method.

The documents says "Condition methods located in external classes must also be static.", but it does not work .

What did i do wrong?

```java
public class CustomConditionalTest {

    //this code don't work
    @Test
    @EnabledIf("eCustomCondition")
    void enabled() {


    }

    @Test
    @DisabledIf("customCondition")
    void disabled() {

    }

    boolean customCondition() {
        return true;
    }



}
class ExternalClass {

     static boolean eCustomCondition() {
        return true;
    }
}
```

In my opinion, it can't seem to find the condition method.

```
Failed to evaluate condition [org.junit.jupiter.api.condition.EnabledIfCondition]: Could not find method [eCustomCondition] in class [dev.donghyeon.junitstudy.conditional.CustomConditionalTest]
```

[code](https://github.com/DaeAkin/JUnit5-Study/blob/junit5-q/src/test/java/dev/donghyeon/junitstudy/conditional/CustomConditionalTest.java)

**Comment by sbrannen** [comment]
The documentation in the User Guide also states the following.

> The method is provided to the annotation via its name, or its fully qualified name if located outside the test class.

Thus, you have to use the "fully qualified method name" to reference a static method in another class.

For example, if `ExternalClass` resides in the `example` package, you would reference it as follows.

```java
@EnabledIf("example.ExternalClass#eCustomCondition")
```

We do actually have an example for a fully qualified method name in the [`@MethodSource`](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-MethodSource), section, but we are missing an example and explanation of the "fully qualified method name" syntax in the [Custom Conditions](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-custom).

In light of that, I am going to repurpose this issue to improve the documentation.
