### ISSUE TITLE
Test results for @Disabled @ParameterizedTest are not displayed correctly in IntelliJ

### ISSUE THREAD

**Issue by renyiwei-xinyi** [junit-team/junit5#2560]
When combined with parameterized test annotations, the results are not displayed correctly. The expected `test_skip` is `@Disabled`, but is actually not reported.

```java
public class TestDisabled {

	@Disabled
	@ParameterizedTest
	@ValueSource(strings = {"test"})
	void test_skip(Object test) {
		System.out.println(test);
	}

	@Disabled
	@Test
	void test_skip_test() {
		System.out.println("test");
	}

}
```

**Comment by renyiwei-xinyi** [comment]
![image](https://user-images.githubusercontent.com/55709533/109450943-3008f880-7a87-11eb-8851-8143ac9b99ba.png)

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
This looks like a presentation issue in IntelliJ IDEA.

@marcphilipp and @sormuras, can one of you confirm this?

**Comment by sbrannen** [comment]
For example, Eclipse IDE displays the disabled parameterized test method as an "empty container".

![image](https://user-images.githubusercontent.com/104798/109471767-84a17900-7a71-11eb-94e3-39f0f05cfd98.png)

If the parameterized test method is not disabled, Eclipse displays a green check mark for the parameterized test container.

![image](https://user-images.githubusercontent.com/104798/109471888-b61a4480-7a71-11eb-8d59-eea220c47e0e.png)

**Comment by marcphilipp** [comment]
We've verified that JUnit reports the `test_skip(Object)` container as skipped but IntelliJ IDEA shows it as having passed. Please open an issue for IntelliJ to get that fixed.
