### ISSUE TITLE
Filtering by tags prevents Spock specs from being executed.

### ISSUE THREAD

**Issue by jakub-bochenski** [junit-team/junit5#2563]
Neither Spock 1.x nor Spock 2.x support tags, so they should not be affected by a tag filter. Yet it seems they are

## Steps to reproduce

Update: I was able to spot this in the debugger (somehow the debug output is not printed even when I run gradle with `-d`)
![Screenshot_20210305_175214](https://user-images.githubusercontent.com/2794994/110147304-cfa5ee00-7ddb-11eb-8f6e-927b5f500b6f.png)

I think this clearly shows there is a bug. Tags should not affect other engines than Jupiter.

--

Add some Spock 1.x Specs and have a gradle test task configured as follows:

```
    test {
            useJUnitPlatform {
                includeTags("SomeTag")
                includeEngines("junit-vintage")
            }
    }
```
Observe specs are not being executed. 
If you comment out the line with "includeTags" the specs are executed.

I've checked in the debugger that a `RunnerTestDescriptor` with a `Sputnik` runner is being discovered (the Specs are not being skipped/ignored by Spock). 
![Screenshot_20210305_165810](https://user-images.githubusercontent.com/2794994/110143226-4c829900-7dd7-11eb-80a0-baa66fbda3ac.png)

The same happens with Spock 2.x 
```
    test {
            useJUnitPlatform {
                includeTags("SomeTag")
                excludeEngines("junit-vintage")
            }
    }
```
![Screenshot_20210305_174750](https://user-images.githubusercontent.com/2794994/110146620-12b39180-7ddb-11eb-9c3a-1ca70674d7cd.png)

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.6.3 / 1.6.3
 - Build Tool/IDE: gradle 6.8.3
 - Spock 1.3-groovy-2.5, 2.0-M2-groovy-2.5

**Comment by marcphilipp** [comment]
As explained in https://github.com/spockframework/spock/issues/1288#issuecomment-791901698, this works as designed.
