### ISSUE TITLE
Improve documentation on tags in User Guide

### ISSUE THREAD

**Issue by jakub-bochenski** [junit-team/junit5#2564]
Opening issue as requested here: https://github.com/spockframework/spock/issues/1288#issuecomment-792803341

I mean this part: 

![Screenshot_20210310_171335](https://user-images.githubusercontent.com/2794994/110660582-fbeab180-81c3-11eb-8998-8e7d24dcb532.png)

The way it is written suggests tags are a Jupiter feature, not a platform one. 

I think something like: 

> Jupiter test classes and methods can be tagged via the `@Tag` annotation. Other engines can support different ways like for example category annotation or configuration file or naming convention or cyclomatic complexity of a method or data about previous runs and so on. The engine translates whatever means it sees fit to a platform tag on which you then can filter.

(source https://github.com/spockframework/spock/issues/1288#issuecomment-792136881)

would make it much more clear. (Style probably needs to be improved though)

**Comment by sbrannen** [comment]
Tentatively slated for 5.8 M2 for _team discussion_

**Comment by marcphilipp** [comment]
**Team decisions:**

- Relocate "Syntax Rules for Tags" section to the Platform section about tags and link to it from Jupiter tags section
- Rename Platform "Tag Expressions" section into "Tags"
- Create "Tag Syntax Rules" and "Tag Expressions" subsections
- Create intro paragraph for "Tags" section similar to the above proposal
