### ISSUE TITLE
Candidate JEP 400: UTF-8 by Default

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2565]
https://openjdk.java.net/jeps/400 's summary reads:
> Use UTF-8 as the JDK's default charset, so that APIs that depend on the default charset behave consistently across all platforms and independently of the user’s locale and configuration.

If this JEP is integrated (into Java 17), it may impact at least the following code line:

https://github.com/junit-team/junit5/blob/0d6d21f0d8bcc3d06e1524b87b7dcdd3f308941a/junit-platform-console/src/main/java/org/junit/platform/console/options/CommandLineOptions.java#L38

Where else does JUnit Platform, Jupiter, and Vintage refer to and rely on the default charset?

**Comment by sormuras** [comment]
Might have been addressed/superseded by https://github.com/junit-team/junit5/pull/2882

**Comment by sbrannen** [comment]
> Might have been addressed/superseded by #2882

seems plausible

**Comment by marcphilipp** [comment]
Superseded by #2882
