### ISSUE TITLE
Remove PackageUtils package name validation

### ISSUE THREAD

**Issue by paplorinc** [junit-team/junit5#2570]
Currently the primitive type names aren't considered keywords, even though they can't be package names:
```groovy
org.junit.platform.commons.util.PackageUtils.JavaNameUtils.isJavaName('int')
Result: true
```

based on https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-Identifier, `int` shouldn't be allowed in package names:
![image](https://user-images.githubusercontent.com/1841944/111344251-7f047f80-867c-11eb-8967-c39b4c4e3bda.png)

**Comment by sormuras** [comment]
Good catch, @paplorinc

How did you find it? Entered an invalid package name and JUnit Platform Commons didn't fail?

I wonder, if we, instead of fixing and maintaining this code, should add a `requires java.compiler;` directive to the `org.junit.platform.commons` module descriptor and use the [SourceVersion::isKeyword](https://docs.oracle.com/en/java/javase/16/docs/api/java.compiler/javax/lang/model/SourceVersion.html#isKeyword(java.lang.CharSequence)) method directly.

**Comment by paplorinc** [comment]
We've been generating packages randomly and using JUnit to validate them.

I've added https://github.com/junit-team/junit5/pull/2571, lemme' know if you think we should require compiler instead.

**Comment by sormuras** [comment]
> We've been generating packages randomly and using JUnit to validate them.

Using hidden (as in not exported) `PackageUtils` directly?

> I've added #2571, lemme' know if you think we should require compiler instead.

Slated for 5.8 M2 for team discussion - we'll get back to you soon.

**Comment by paplorinc** [comment]
> Any usage by external parties is not supported

I wasn't complaining :)

**Comment by marcphilipp** [comment]
> I wonder, if we, instead of fixing and maintaining this code, should add a `requires java.compiler;` directive to the `org.junit.platform.commons` module descriptor and use the [SourceVersion::isKeyword](https://docs.oracle.com/en/java/javase/16/docs/api/java.compiler/javax/lang/model/SourceVersion.html#isKeyword(java.lang.CharSequence)) method directly.

Actually, we did this to get rid of that dependency in https://github.com/junit-team/junit5/issues/1995. However, we could add a test-only dependency write a test that checks both behave the same.

**Comment by sormuras** [comment]
Yes - yet in 2021, we might want to reconsider this decision.

Or, as this is the only place that method used in out production code...

https://github.com/junit-team/junit5/blob/9558af1961a8f539288f4c7ac59d4666417c9990/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java#L73

...we could also drop the check entirely.

**Comment by paplorinc** [comment]
Lemme' know, and I'll update my PR

**Comment by marcphilipp** [comment]
**Team decision:** Remove `PackageUtils` class and usage in `ClasspathScanner` and adjust tests accordingly.
