### ISSUE TITLE
Assert Reflection Equals

### ISSUE THREAD

**Issue by frascu** [junit-team/junit5#2573]
It would be useful if it was a method to compare two objects by reflection.

I suppose to have this class:
```java
public class Person {
    private long id;
    private String name;
    private String surname;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
       
    public long getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }
}
```

In ordet two check if two objects are equals I can create the test in this way:
```java
@Test
void myTest() {
    Person person1 = new Person();
    person1.setId(1L);
    person1.setName("name1");
    person1.setName("surname1");

    Person person2 = new Person();
    person2.setId(2L);
    person2.setName("name1");
    person2.setName("surname1");

    Assertions.assertEquals(person1, person2);
}
```

This test would work just if I implement the equals method in the class `Person`.
I think that a new method can be added to `Assertions`:
```java
public static void assertReflectionEquals(Object expected, Object actual, String... excludeFields) {
    // check by reflection 
}
```
This new method executes the equals method for each field having the same name between two objects.
If at least one field is not equal, the assertion fails and the different fields are printed.

This would work also for objects having different types.

**Comment by sbrannen** [comment]
**Team Decision**: Thanks for the proposal. We appreciate your desire to extend JUnit Jupiter's assertion support; however, we have decided not implement the proposal in line with previous decisions involving such proposals. See https://github.com/junit-team/junit5/issues/1920#issuecomment-499841520 for details.
