### ISSUE TITLE
JDK 16 Records for Tests not working

### ISSUE THREAD

**Issue by khmarbaise** [junit-team/junit5#2575]
# Actual behaviour
Using JDK 16 records within a test:

## First Test Case
If you define a test class (record) like this:
```java
record RecordTest() {

  @Nested
  record F2() {

    @Test
    @DisplayName("Record F2:test1")
    void test_1() {
      assertThat(true).isTrue();
    }

  }

  @Nested
  record F1() {

    @Test
    @DisplayName("Record F1:test1")
    void test_1() {
      assertThat(true).isTrue();
    }

    @Test
    @DisplayName("Record F1:test2")
    void test_2() {
      assertThat(true).isTrue();
    }
  }

}
```
## Second Test Case

```java
package com.soebes.kata.fraction;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

class ClassTest {

  @Nested
  record F2() {

    @Test
    @DisplayName("Record F2:test1")
    void test_1() {
      assertThat(true).isTrue();
    }

  }

  @Nested
  record F1() {

    @Test
    @DisplayName("Record F1:test1")
    void test_1() {
      assertThat(true).isTrue();
    }

    @Test
    @DisplayName("Record F1:test2")
    void test_2() {
      assertThat(true).isTrue();
    }
  }

}
```

In both cases neither within the IDE (IntelliJ) nor with the build tool (Maven / maven-surefire-plugin) identifies the test cases and execute them.

The IDE shows the so called "gutter icon" that you can execute the tests within the class but the result is simply:
`No tests were found`.

## Expected Behaviour

My opinion is that both cases `ClassTest` as well as `RecordTest` should execute all Test cases (methods).

## Steps to reproduce

I have created a minimal project with the different class/record setup's for reproducing it ...

https://github.com/khmarbaise/junit-jupiter-record-issue

Using the `RecordWithoutNestedTest` you can execute the tests from `F2` via IDE and for the class `UsualWithoutNestedTest` you can not even execute the tests from within the IDE. But those case are correct because both record/class do not contain `@Nested` annotation to make junit jupiter aware of tests within the local classes/records.

The class `UsualTest` will execute the tests as expected. That will work from IDE as well as from Maven (cli).

Apart from above there can be observed a very interesting behaviour:
If you start the tests based on the package `com.soebes.junit.jupiter.record` via IDE Ctrl-Shift-R(MAC) / Ctrl-Shift-F10(Windows) you will get the following output:

![Screenshot 2021-03-18 at 22 37 29](https://user-images.githubusercontent.com/42484/111701309-eff19600-883a-11eb-9a99-2d51cfaf5fb3.png)

which shows a completely different behaviour.

## Context

- Using JUnit Jupiter 5.7.1 / 5.8.0-M1
- Using Maven 3.6.3 as well as IntelliJ IDE (2020.3.2)

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/khmarbaise/tools/maven
Java version: 16, vendor: Oracle Corporation, runtime: /Users/khmarbaise/.sdkman/candidates/java/16-open
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

**Comment by marcphilipp** [comment]
Thanks for the issue report!

> If a record class is itself nested, then it is implicitly static

Source: https://openjdk.java.net/jeps/395

![image](https://user-images.githubusercontent.com/214207/111753283-f9a8e700-8896-11eb-99cd-d7fe3ad336c8.png)

Hence, JUnit sees nested records as standalone classes and executes them accordingly.
