### ISSUE TITLE
Intoduce API to add ParameterResolvers through Launcher

### ISSUE THREAD

**Issue by alexstaeding** [junit-team/junit5#2577]
I am developing a framework that aims to automate grading by running student submissions together with JUnit tests to assign points and produce a graded rubric. Each submission (sources) jar is compiled at runtime together with the JUnit tests for that submission. These tests are all run in parallel on separate ClassLoaders.

I would like to provide a custom instance of my interface `TestCycle` (which represents a combination of submission classes + test classes). An example usage can be found [here](https://github.com/JagrKt/JagrKt/pull/1). I looked for a way of providing a `ParameterResolver` through the platform launcher but could not find one.

This is the class that runs the JUnit tests for a given submission: [JavaRuntimeTester](https://github.com/JagrKt/JagrKt/blob/feature/code-context/jagrkt-common/src/main/kotlin/org/jagrkt/common/testing/JavaRuntimeTester.kt). Note that `createTestCycle` runs in parallel for all submissions.

### What I tried

According to https://junit.org/junit5/docs/current/user-guide/#extensions-registration, there are currently three ways of registering ParameterResolvers. Both `@ExtendsWith` and the java ServerLoader are out of the question because they would require some way of accessing the current `TestCycle` from a global context, which is not compatible with parallelization.

The only way I came up with providing my `TestCycle` instance (with the current JUnit API) was during the classloading of the JUnit tests. As each JUnit test class instance is unique to that `TestCycle`, it would potentially be possible to inject a reference to the current `TestCycle` in a static field in the test class and use this reference in the test methods. However, I find this solution relatively ugly and unnecessary considering the `ParameterResolver` system in JUnit.

### My suggestion

In my opinion, it should be possible to register `ParameterResolver`s programmatically through the `Launcher` somehow. 

I launch JUnit like this in my [JavaRuntimeTester](https://github.com/JagrKt/JagrKt/blob/feature/code-context/jagrkt-common/src/main/kotlin/org/jagrkt/common/testing/JavaRuntimeTester.kt):

```kotlin
  private fun List<DiscoverySelector>.runJUnit(testCycle: JavaTestCycle): JUnitResultImpl? {
    return try {
      val launcher = LauncherFactory.create()
      val testPlan = launcher.discover(LauncherDiscoveryRequestBuilder.request().selectors(this).build())
      val summaryListener = SummaryGeneratingListener()
      val statusListener = TestStatusListenerImpl(logger)
      launcher.execute(testPlan, summaryListener, statusListener) // <-- inject testCycle here?
      JUnitResultImpl(testPlan, summaryListener, statusListener)
    } catch (e: Throwable) {
      logger.error("Failed to run JUnit tests for ${testCycle.submission.info}", e)
      null
    }
  }
```

To use in tests like this:

```java
@Test
@DisplayName("Fib Iterative Correct")
public void fibIterative(TestCycle testCycle) {
  JavaMethodContext ctx = ContextResolver.ofJavaMethod(() -> Fibonacci.class.getMethod("fibIterative", int.class))
    .resolve(testCycle);
  assertTrue(ctx.modified()); // ctx.getModifiedSource() != ctx.getOriginalSource()
  assertTrue(ctx.getModifiedSource().contains("for"));
  ...additional tests...
}
```

To me this seems like the most intuitive way of doing this: I have my `TestCycle` in `runJUnit` and would like to pass it to the methods I am running (indirectly through the launcher).

While I have used JUnit in the past, this is my first time programmatically running tests using the platform launcher. So I am therefore not entirely sure of the best way to approach adding this to the API and am open to discussing alternatives.

(for more info on what the context stuff is, click [here](https://github.com/JagrKt/JagrKt/pull/1))

**Comment by marcphilipp** [comment]
I think this can be solved by using a globally registered extension that reads the `TestCycle` from an `InheritableThreadLocal`. Would that work for you?

**Comment by alexstaeding** [comment]
Thank you. This seems to be a good solution.
