### ISSUE TITLE
Add attributes of expected & actual in AssertionFailedError

### ISSUE THREAD

**Issue by lapplislazuli** [junit-team/junit5#2580]
Hi, 

I am currently working on a small project where I would like to display the differences from a foreign set of run JUnit Tests. 
So, someone has Tool A and runs it on Project B with Unit tests, and Tool A gives you nice info. 

I would like to give a test-overview similar to what is existing, but also include information how far some of the tests where off if that is possible (depending on the datatype, such as double). 

At the moment, I will need to get such information out of the ErrorMessage, 
which is not ... super complex, but I was wondering that the AssertionFailedExceptionhas 0 attributes except the ErrorMessage. 

## Deliverables

- [ ] Add fields `Optional<> expected` and `Optional<> actual` to AssertionFailedException
- [ ] Default them to `Optional.empty`
- [ ] Add them when possible/applicable to the assertion methods
- [ ] (Maybe) Add an Enum Value which assertion generated the Exception (EQUALS; NOTNULL; etc.)
- [ ] (Maybe) Type of the originating test (Test, ParameterizedTest,RepeatedTest, etc. )

I can see that adding the actual values especially for objects might cause side-effects or higher memory consumption, 
but I think that adding a few fields can help many people who programmatically work with JUnit Output. 

I would also like to get your general thoughts about this. 
Was it not done for a purpose? 
Would this break something somewhere I don't know?

**Comment by marcphilipp** [comment]
`org.opentest4j.AssertionFailedError` already has fields for expected and actual. Have you seen those?

**Comment by Twonki** [comment]
@marcphilipp Thanks for the quick response! 

I indeed did not find that, maybe I was working against an older version of opentest4j. Thank you very much for pointing it out to me! 

What do you think about the two points marked as *Maybe*?

**Comment by marcphilipp** [comment]
I think both would be specific to JUnit Jupiter while OpenTest4J is more general. For the former, you could derive the information from the stacktrace.
