### ISSUE TITLE
JUnit Jupiter Engine has a dependency to kotlin-stdbli-jdk8

### ISSUE THREAD

**Issue by khmarbaise** [junit-team/junit5#2583]
Currently the 5.8.0-M1 version of `junit-jupiter-engine` has an explicit dependency to `kotlin-stdblib-jdk8`.

```xml
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.4.20</version>
      <scope>compile</scope>
    </dependency>
```
Is this really necessary?

## Context

 - 5.8.0-M1
 - Build Tool/IDE:
 -  Maven / IDEA IntelliJ

**Comment by sormuras** [comment]
Duplicate of #2551
