### ISSUE TITLE
Add concrete steps to "Migrating from JUnit 4" docs section.

### ISSUE THREAD

**Issue by mleonhard** [junit-team/junit5#2584]
I have some code that uses jUnit 4.  I want to update it to use jUnit 5.  The first thing I did was try to find out which dependency to add:
1. Go to https://junit.org/junit5/
1. Click "User Guide"
1. Read through the overview.
1. Reach section [1.4.1. Downloading JUnit Artifacts](http://junit.org/junit5/docs/current/user-guide/#overview-getting-started-junit-artifacts)
1. Click [Dependency Metadata](http://junit.org/junit5/docs/current/user-guide/#dependency-metadata)
1. Stare in confusion at the 19 different JAR files available.
1. Go back and continue through the document.  The first example uses an `org.junit.jupiter` import.  I guess jUnit is now called Jupiter.  Why would they change the name?
1. Skip down to ["3. Migrating from JUnit 4"](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4).  I'm hoping to find concrete info.  Instead, I find:
   - Annotations are in `org.junit.jupiter.api`.  What about the other bits of jUnit?  Matchers?  Do I still need to use hamcrest which hasn't been updated in 2 years?
   -  The ["3.3 Limited JUnit 4 Rule Support"](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-rule-support) section says that jUnit 5 doesn't support jUnit 4 rules, then it says that it does.  This is so confusing.
   - Finally, the ["3.4. JUnit 4 @Ignore Support"](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-ignore-annotation-support) tells me something actionable: depend on `junit-jupiter-migrationsupport` and annotate the class with `@EnableJUnit4MigrationSupport`.  And there's an example!  I wish they were all written this way.

## Deliverables

- Update [3. Migrating from JUnit 4](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4) to have concrete imperative steps:
  - Depend on these JARs: ... (include JAR with matchers)
  - Change these things in your tests to get them to run under jUnit 5: ...
  - Change these things so you can start using the new features: ...
  - You can use the new API to replace crufty code like ... with shiny code like ... .
  - Link to javadocs for various packages.
  - Full working example showing off various features.
- Update the [Dependency Metadata](http://junit.org/junit5/docs/current/user-guide/#dependency-metadata) section to state which dependencies most people need.  Say "Most people only need dependency X and Y" or "If you're unsure then just depend on X."
- Make the prose more concise.  Use active voice.
   - Example:
      - Change this sentence: "The following are topics that you should be aware of when migrating existing JUnit 4 tests to JUnit Jupiter."
      - Into this: "When migrating jUnit 4 tests to jUnit Jupiter, be aware of:"
   - Example:
      - Change this: "While the JUnit team encourages reusable extensions to be packaged and maintained in separate libraries, the JUnit Jupiter API artifact includes a few user-facing extension implementations that are considered so generally useful that users shouldn’t have to add another dependency."
      - Into this: "`junit-jupiter-api` artifact includes these extensions.  Other extensions are in `<link>`."

**Comment by jbduncan** [comment]
@mleonhard Regarding a working example, I've personally used the Gradle sample by the JUnit 5 team below. I assume the Maven sample works just as well.

- https://github.com/junit-team/junit5-samples/tree/main/junit5-migration-gradle
- https://github.com/junit-team/junit5-samples/tree/main/junit5-migration-maven

I hope this helps.

**Comment by jbduncan** [comment]
Regarding migrating JUnit 4 tests to "JUnit Jupiter" tests (not just running old JUnit 4 tests on JUnit 5's "JUnit Platform"), I'm aware of a couple of tools that automate some parts of it. I've never used them though, so YMMV.

- https://github.com/junit-pioneer/convert-junit4-to-junit5
- https://github.com/openrewrite/rewrite-testing-frameworks

**Comment by marcphilipp** [comment]
@mleonhard Thanks for the suggestions! Would you be interested in submitting a PR with some of these improvements?

**Comment by p1729** [comment]
@marcphilipp can I try adding these improvements ?

**Comment by marcphilipp** [comment]
@p1729 Sure!

**Comment by marcphilipp** [comment]
@signed Good point! There's also a couple of rewrite recipes at https://docs.openrewrite.org/reference/recipes/java/testing/junit5/
