### ISSUE TITLE
Please delete this issue.

### ISSUE THREAD

**Issue by mleonhard** [junit-team/junit5#2585]
DELETED

**Comment by mleonhard** [comment]
Hi JUnit Team,
I apologize for the tone of the original content.  I wrote it in a moment of exhausted frustration.  Hamcrest is working OK.  I hope it remains so going forward.

Please delete this issue.

Best Wishes,
Michael

**Comment by marcphilipp** [comment]
Thanks for coming back and changing the original description. If you have any suggestion how to improve [section 2.4.2](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions-third-party), please let us know.
