### ISSUE TITLE
Consider default value for @EnabledIfEnvironmentVariable.matches

### ISSUE THREAD

**Issue by sewe** [junit-team/junit5#2586]
Sometimes, you want to run a test only if a particular environment variable is present, regardless of its value.

This can be achieved using 

```java
@EnabledIfEnvironmentVariable(named = "VARIABLE", matches = ".*")
```

which is a bit verbose.

In the past, this requirement has led to feature requests like https://github.com/junit-team/junit5/issues/1825, asking for a dedicated `@EnabledIfEnvironmentVariableExist` counterpart.

But IMHO, the same could be achieved by adding a default value of `".*"` or `".+"` for the `matches` property. Then the following would be legal:

```java
@EnabledIfEnvironmentVariable(named = "VARIABLE")
```

AFAICT, this change would not break compatibility; all annotations with the explicit `matches` property would work as before.

## Deliverables

- [ ] A new version of `@EnabledIfEnvironmentVariable` with a default value for the `matches` property.

**Comment by marcphilipp** [comment]
**Team decision:** Although being a bit verbose, we think the current API is clearer. If you have this use case just for a few environment variables, you could define your own composed annotations like this:
```java
@EnabledIfEnvironmentVariable(named = "CI", matches = ".*")
public @interface EnabledOnCI {}
```

**Comment by sewe** [comment]
Fair enough.
