### ISSUE TITLE
Add static method `named` to the `Named` interface

### ISSUE THREAD

**Issue by helpermethod** [junit-team/junit5#2587]
Hi!

First of all, great work! JUnit 5 is my favorite testing library of all time!

I've just discovered that JUnit 5.8 will provide a `Named<T>` interface, which is a great addition!
But the thing I don't quite like about is that I have to use `Named.of(...)` to construct such an instance.
I'd rather use a more descriptive method which I could statically import, like `Named.named(...)`, so I could write something like

```java
    arguments(named("me", new User()))
```

Wdyt?

## Deliverables

- Add a static method `named` to the `Named<T>` interface.

P.S. I'd love to provide a PR for this!

**Comment by sbrannen** [comment]
I actually intended to introduce the proposed `named()` static factory method but haven't yet gotten around to it, so I'm all for it.

Tentatively slated for 5.8 M2 for _team discussion_.

**Comment by marcphilipp** [comment]
I'm also all for it and it would be consistent with `Arguments.arguments`.

**Comment by mmerdes** [comment]
As a general proponent of static imports for such use cases I am all for it as well.

**Comment by marcphilipp** [comment]
**Team decision:** Add `Named.named`.

@helpermethod Feel free to introduce the helper method (pun intended).

**Comment by helpermethod** [comment]
@marcphilipp The interface methods are currently not documented, and there are no tests. Is this intended? Should I add those, or just add the static method?

**Comment by sbrannen** [comment]
Feel free to document the interface methods as well, since that is missing.

**Comment by sbrannen** [comment]
As for the tests, a test was introduced in https://github.com/junit-team/junit5/commit/9c4da0934db8e33600a4a8622ec2fc03ffe374be#diff-b433f96680abe9d8f1ade35f0c0412bd65e567b828e5e5f165cb912825ea6752.

So you could modify that to use `Named.of` and `Named.named`, and that should cover it.

**Comment by sbrannen** [comment]
Superseded by #2591
