### ISSUE TITLE
Discover tests in suites packaged into jars, e.g. TCKs

### ISSUE THREAD

**Issue by t1** [junit-team/junit5#2594]
As discussed [in the discussions](https://github.com/junit-team/junit5/discussions/2589), we need a way to package a test suite into a jar and run it for several implementations. This is a common requirement when building Technology Compatibility Kits. There are generally three artifacts:

1. `api` contains some interfaces and a `ServiceLoader` (or similar IoC mechanism) to load an implementation of the api interfaces.
2. `impl1` containing one implementation (sometimes called a reference implementation `ri`) of the `api`; includes the `services` files for the `ServiceLoader`.
3. `tck` the test suite to check that an implementation of the api is compliant.

You can run the tests in the `tck` by adding a `runtime` dependency on `impl1`. But the tck should be usable by any other implementation as well: I want the `impl1` to load the `tck`-jar and run it, not the other way around. The `tck` should be a library of tests that the implementations can include as a `test` dependency. The dependency should be `impl1→tck` not `tck→impl1`.

I assume that scanning all jars for tests would result in unacceptable performance, so we probably need some way to specify the jars to scan, or even better to mark a jar to be a test-suite.

I currently need this for an open source project: https://github.com/t1/smallrye-graphql It's about the TCK in the client. But I've also built a minimal, reproducible example that may be easier to play around with: https://github.com/t1/junit-tck-mre.

## Deliverables

- [ ] A mechanism to specify the jars to scan for tests
- [ ] Update to the User Manual

**Comment by mpkorstanje** [comment]
> I assume that scanning all jars for tests would result in unacceptable performance, so we probably need some way to specify the jars to scan, or even better to mark a jar to be a test-suite.

I would expect that running the `ConsoleLauncher` with either  `--select-module`, `--select-package` or `--scan-classpath` should suffice or alternatively a declarative test suite from https://github.com/junit-team/junit5/pull/2416 with the equivalent selectors.

**Comment by t1** [comment]
Is there a plan as to when this will be released?

**Comment by mpkorstanje** [comment]
#2415 has been released in the latest preview and will presumably be generally available once the 5.8.0 backlog is cleared out.

**Comment by t1** [comment]
I got it working with 5.8.0-M1. Thanks a lot!

**Comment by jbduncan** [comment]
@t1 Ooh, nice! Am I right to think that you got it working over at https://github.com/smallrye/smallrye-graphql/issues/796?

I like how the suite-based TCK runs a bunch of other tests, which in turn grab the implementation-under-test from the classpath using `ServiceLoader`. 

I can see now why, for a project of this size, the [Test Interface pattern](https://junit.org/junit5/docs/5.7.0/user-guide/#writing-tests-test-interfaces-and-default-methods) wouldn't work: the TCK already has lots of test classes, so merging them into one to create a Test Interface would be infeasible.

Great work! 👍

**Comment by jbduncan** [comment]
I think this issue could be re-opened though, as I believe this suite-based TCK pattern is worth documenting in the User Guide.

What do you think, JUnit 5 team?

**Comment by mpkorstanje** [comment]
I think it is worth documenting this pattern as one particular use case of declarative test suites.

But I'm not part of the JUnit team. I think you have to tag them with @junit-team.

**Comment by marcphilipp** [comment]
@t1 Could you please outline your approach here?

**Comment by t1** [comment]
> @t1 Could you please outline your approach here?

Sure. In the `tck` artifact, I define a suite like:

```java
package org.example;

import org.junit.platform.suite.api.SelectPackages;
import org.junit.platform.suite.api.Suite;

@Suite
@SelectPackages("org.example")
public abstract class TechnologyCompatibilityKit {
}
```

The class doesn't have to be abstract, but it make the intended usage more explicit. I'm not sure if `@SelectPackages` is the best option, as it includes a repetition of the package name. Maybe `@SelectModule` would be better, but IIUC I'd have to introduce Java Modules for that.

In the implementation, I define a subclass that's discoverable by the test runner:

```java
package test;

import org.example.TechnologyCompatibilityKit;

class TckTests extends TechnologyCompatibilityKit {
}
```

Combined with the general setup outlined in the issue description (esp. the `ServiceLoader`), this makes for a very powerful toolset.

Additionally, in the real project I use a fixture class to decouple the implementation-specific test setup from the TCK. This includes some mocking and test data generation. It would be great to be able to react to the test suite lifecycle to set this up, but I just use another `ServiceLoader` in `src/test/resources/META-INF/services/`, which is okay for the first release of the test suites.

BTW: I really love JUnit 5. Great work!
