### ISSUE TITLE
Support AutoCloseable for arguments provided to a @ParameterizedTest

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2597]
## Overview

Sometimes the arguments provided to a `@ParameterizedTest` are resources that need to be cleaned up after each invocation of the parameterized test -- for example, when testing against various implementations of an API. However, it is currently not possible to clean up such resources without duplicated logic in each `@ParameterizedTest` method that makes use of the arguments source.

One _could_ store the argument injected into the `@ParameterizedTest` method in a field and then access that field within an `@AfterEach` method, but that is more work than simply invoking the cleanup method directly from within each `@ParameterizedTest` method. The following simplified example demonstrates the latter approach.

```java
class ServerTests {

	@ServerTest
	void json(Server server) {
		server.handleRequest("JSON");
		server.shutdown();
	}

	@ServerTest
	void xml(Server server) {
		server.handleRequest("XML");
		server.shutdown();
	}


	private interface Server {

		default void handleRequest(String data) {
			System.out.println("Request: " + data + " for " + getClass().getSimpleName());
		}

		default void shutdown() {
			System.out.println("Shutting down " + getClass().getSimpleName());
		}
	}

	private static class MockServer implements Server {
	}

	private static class RealServer implements Server {
	}


	@Retention(RetentionPolicy.RUNTIME)
	@ParameterizedTest
	@MethodSource("servers")
	@interface ServerTest {
	}

	static Stream<Server> servers() {
		return Stream.of(new MockServer(), new RealServer());
	}

}
```

The following are the results of executing the above test class.

```
Request: XML for MockServer
Shutting down MockServer
Request: XML for RealServer
Shutting down RealServer
Request: JSON for MockServer
Shutting down MockServer
Request: JSON for RealServer
Shutting down RealServer
```

If we want to automate the shutdown of each server, we can implement a custom `ArgumentsProvider` that stores the arguments in the `ExtensionContext.Store` and modify the `Server` interface so that it extends `CloseableResource`. The following example demonstrates this approach.

```java
class ServerTests {

	@ServerTest
	void json(Server server) {
		server.handleRequest("JSON");
	}

	@ServerTest
	void xml(Server server) {
		server.handleRequest("XML");
	}


	private interface Server extends CloseableResource {

		default void handleRequest(String data) {
			System.out.println("Request: " + data + " for " + getClass().getSimpleName());
		}

		default void shutdown() {
			System.out.println("Shutting down " + getClass().getSimpleName());
		}

		@Override
		default void close() {
			shutdown();
		}
	}

	private static class MockServer implements Server {
	}

	private static class RealServer implements Server {
	}

	@Target(ElementType.METHOD)
	@Retention(RetentionPolicy.RUNTIME)
	@ParameterizedTest
	@ArgumentsSource(ServerArgumentsProvider.class)
	@interface ServerTest {
	}

	static class ServerArgumentsProvider implements ArgumentsProvider {

		private static final Namespace namespace = Namespace.create(ServerArgumentsProvider.class);

		@Override
		public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
			MockServer mockServer = new MockServer();
			RealServer realServer = new RealServer();
			context.getStore(namespace).put("mockServer", mockServer);
			context.getStore(namespace).put("realServer", realServer);
			return Stream.of(arguments(mockServer), arguments(realServer));
		}
	}
}
```

The following are the results of executing the above test class.

```
Request: XML for MockServer
Request: XML for RealServer
Shutting down RealServer
Shutting down MockServer
Request: JSON for MockServer
Request: JSON for RealServer
Shutting down RealServer
Shutting down MockServer
```

Here we see that the `Server` instances are in fact automatically shut down; however, there are two undesired side effects of this approach:

1. Each `Server` instance is held onto until after _all_ invocations of a given `@ParameterizedTest` have completed.
2. The `Server` instances are closed/shut down in reverse order.

The latter is due to a feature of the `ExtensionContext.Store` that supports "wrapping" of closable resources, so that behavior is to be expected in this scenario, but it may not be acceptable depending on the actual use case.

Aside from the above runtime side effects, the implementation requires a lot of boilerplate code to get working.

## Proposal

To simplify such use cases, we should invoke the `close()` method on any `CloseableResource` (or `java.lang.AutoCloseable`) that is provided as an argument to a `@ParameterizedTest`, and that should occur after each invocation of the `@ParameterizedTest` method. Doing so would allow the original `ServerTest` example to be implemented using `@MethodSource` and having the `Server` extend `CloseableResource` without the need for a custom `ArgumentsProvider` and avoiding direct interaction with the `ExtensionContext.Store`.

## Deliverables

- [ ] Support `java.lang.AutoCloseable` for `@ParameterizedTest` arguments, enabled by default but configurable via a new `autoCloseArguments` attribute in the `@ParameterizedTest` annotation.

**Comment by marcphilipp** [comment]
**Team decision:** Introduce a new `autoCloseArguments` attribute on `@ParameterizedTest` which defaults to `true`. If `true`, all arguments provided by `ArgumentsProviders` that implement `AutoCloseable` would be closed after `@AfterEach` methods and `AfterEachCallbacks` have been called (details to be worked out).
