### ISSUE TITLE
User guide states JUnit 5 can run JUnit 3 tests but it fails to detect them

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#2599]
> JUnit Vintage provides a TestEngine for running JUnit 3 and JUnit 4 based tests on the platform.

but if I have dependency on junit 3.8.1 then I got the following exception
```
Caused by: org.junit.platform.commons.JUnitException: Unsupported version of junit:junit: 3.8.1. Please upgrade to version 4.12 or later.
	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:49)
```
Looks like the guide should be updated or vintage engine should support junit 3.8 dependencies

Checked with junit-vintage-engine:5.7.0

**Comment by sbrannen** [comment]
The `VintageTestEngine` requires JUnit 4.12 or higher, and JUnit 4 includes JUnit 3.8.2 within the same artifact.

Thus, if I recall correctly, only JUnit 3.8.2 bundled with JUnit 4.12+ is supported.

@marcphilipp, do you have any further input on the topic?

**Comment by marcphilipp** [comment]
@sbrannen is correct.

@akozlova Can you use the JUnit 4 jar instead?

**Comment by akozlova** [comment]
It's IntelliJ IDEA users who struggle. 

As far as I understand them, junit 3 is bundled with some android dependencies or similar. Most probably people don't need junit 3 but that jar appears on their classpath and IJ adds vintage engine for them (cause the documentation says that it supports junit 3). So my fix would be to omit vintage-engine if there is no junit 4.12+ on the classpath. 

If you would write in the guide that junit 4.11 and below is not supported, it would be more fair to my taste. Thanks

**Comment by marcphilipp** [comment]
Thanks for the suggestion! I've done so in ec2afa1.
