### ISSUE TITLE
Include license in published archives

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#260]
## Status Quo

In contrast to the `junit-4.12.jar` which contains a `LICENSE-junit.txt` file, published artifacts such as `junit5-api-5.0.0-SNAPSHOT.jar` currently do not contain the EPL license file.

## Deliverables

- [ ] Update the Gradle build so that the `LICENSE.md` file (from the root folder) is included in every published archive under `/META-INF/LICENSE.md`.

**Comment by marcphilipp** [comment]
I think using the Markdown file is fine.

**Comment by RAnders00** [comment]
Should the license file be included in the javadoc and source jars as well?

**Comment by sbrannen** [comment]
I think that including the license in the javadoc and source JARs is perfectly reasonable.

**Comment by sbrannen** [comment]
FYI: I have updated this issue's deliverables accordingly.

**Comment by sbrannen** [comment]
The work merged into `master` in f37c963715cf60874bbd9fe893f3e7898c277b00 in fact only copies the license file to *binary* JARs.

Thus, javadoc and source JARs do not currently include the license file.

@junit-team/junit-lambda, if anyone thinks we need to ensure that the EPL license file is included in javadoc and source JARs, please reopen this issue or a new one.
