### ISSUE TITLE
org.junit.platform.testkit is not compatible with latest version of AssertJ

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#2603]
Junit Platform 1.7.1, AssertJ 3.19.0 ->

```
java.lang.NoSuchMethodError: org.assertj.core.api.SoftAssertions.fail(Ljava/lang/String;)V

	at org.junit.platform.testkit.engine.Events.checkCondition(Events.java:455)
	at org.junit.platform.testkit.engine.Events.assertEventsMatchLoosely(Events.java:420)
	at org.junit.platform.testkit.engine.Events.assertEventsMatchLoosely(Events.java:301)
```

**Comment by marcphilipp** [comment]
Thanks for reporting! We currently compile against 3.19.0 and I don't remember us having to make any source code changes so it sounds like AssertJ broke binary compatibility. Have you already reported an issue for them?

**Comment by jlink** [comment]
> Thanks for reporting! We currently compile against 3.19.0 and I don't remember us having to make any source code changes so it sounds like AssertJ broke binary compatibility. 

Yes, I think they do b/c they removed an overloaded method with vararg parameter.

> Have you already reported an issue for them?

Nope.

**Comment by jlink** [comment]
So it should be fixed with the next release.

**Comment by marcphilipp** [comment]
@jlink Do you mean in the next release of JUnit Platform or AssertJ?

**Comment by marcphilipp** [comment]
I'll report an issue for AssertJ.

**Comment by jlink** [comment]
> @jlink Do you mean in the next release of JUnit Platform or AssertJ?

Of JUnit platform. Since you compile it freshly.

**Comment by marcphilipp** [comment]
Understood. I opened an issue for AssertJ: https://github.com/assertj/assertj-core/issues/2190

**Comment by marcphilipp** [comment]
**Team decisison:** Document incompatibility in user guide when releasing 5.7.2

**Comment by marcphilipp** [comment]
Resolved in 2555cd03901b9d940fbe9a4030e512c29bb349cd.

![image](https://user-images.githubusercontent.com/214207/118131410-ca2ddb00-b3fe-11eb-9e36-9af841462ce3.png)

**Comment by sbrannen** [comment]
Shouldn't the note explicitly state what versions of AssertJ _are_ compatible first?

And then mention AssertJ 3.19.0 and higher is incompatible?

**Comment by marcphilipp** [comment]
Better?

![image](https://user-images.githubusercontent.com/214207/118132985-92c02e00-b400-11eb-9ab7-d31e82c3e94d.png)

**Comment by sbrannen** [comment]
Yes, much better.

Thanks

**Comment by marcphilipp** [comment]
Thanks for the quick review! 👍
