### ISSUE TITLE
Make `assertTimeout()` more valuable

### ISSUE THREAD

**Issue by Michaeli71** [junit-team/junit5#2610]
Currently there is nearly not functional distinction between `assertTimeout()` and `assertTimeoutPreemptively()`.

`assertTimeout()` is waiting to complete the execution. Therefore it seems to be natural that you can access the result to check it even if timeout exceeded.

Would be great to see that it produces the correct result and is in time or has a timeout.

Perhaps a new type of "error" has to be invented. 

In this way you can fine tune performance and have a look at correctness.

Please contact me for more information: michael_inden@hotmail.com

<img width="1139" alt="Timeout" src="https://user-images.githubusercontent.com/3299776/117497528-e520cb00-af78-11eb-9736-06bea7d60ed0.png">

**Comment by marcphilipp** [comment]
@Michaeli71 I'm not sure I fully understand what you're asking for. In both cases the thrown `AssertionFailedError` will clearly indicate that the timeout was exceeded. Introducing a new error type would have too many implications but we could talk about a custom exception type that extends `AssertionError`. IDEs could then decide whether they want to show a different icon as they already do by checking for `AssertionError` vs. any other kind of `Throwable`.

@noopur2507 @akozlova Would that be sth. you'd consider?

**Comment by akozlova** [comment]
sorry, missed the initial comment. No, I don't think that in IJ we would like to separate this kind of test failures with a separate icon.

**Comment by sbrannen** [comment]
Thanks for the feedback, @akozlova.

In light of that and lack of community interest in such a feature, I am closing this issue.
