### ISSUE TITLE
Repeated Tests should report amount of failures and succesful runs to make it more valuable

### ISSUE THREAD

**Issue by Michaeli71** [junit-team/junit5#2611]
Right now it is possible to repeat tests for several iterations.
It is even possible to get a lot of conect information from
RepetionInfo. 

In a lot of trainings and according to my own experience 
 something really relevant seams to be missing: Please
add a possibility to get a summary or information on
how many invocations are succesful and how many failed.
This would be extremly useful for integration testing
unreliable external systems, to get and idea of how
many calls failed. Perhaps it would be nice to be able
to specifiy the needed success rate, like 7 of 10
have to be successful to be considered as test pass.
<img width="1121" alt="Repeated" src="https://user-images.githubusercontent.com/3299776/117498371-00d8a100-af7a-11eb-8a13-ec78b2378674.png">

Please contact me for more information: michael_inden@hotmail.com

## Deliverables

- [ ] ...

**Comment by Michael1993** [comment]
Hi @Michaeli71 ! 👋 

Consider checking out [`rerunner-jupiter`](https://github.com/artsok/rerunner-jupiter), it does exactly what you describe here!

Example:
```java
/**
 * Repeated 100 times with minimum success four times, then disabled all remaining repeats.
 * See image below how it works. Default exception is Exception.class
 */
@DisplayName("Test Case Name")
@RepeatedIfExceptionsTest(repeats = 100, minSuccess = 4)
void reRunTest4() {
    if(random.nextInt() % 2 == 0) {
        throw new RuntimeException("Error in Test");
    }
}
```

**Comment by marcphilipp** [comment]
Closing since there's a community project to achieve the desired behavior. Thanks for pointing that out, @Michael1993! 👍
