### ISSUE TITLE
ClasspathScanner#determineSubpackageName sometimes resolves to wrong subpackageName starting with '...'

### ISSUE THREAD

**Issue by hosuaby** [junit-team/junit5#2612]
This bug was introduced in JUnit `5.7.1`. `5.7.0` have no such a problem.

Example: 

```java
Path baseDir = "/com/fasterxml/jackson/core/base/";
Path classFile = "/com/fasterxml/jackson/core/base/ParserMinimalBase.class";
String subpackageName = determineSubpackageName(baseDir, classFile);
// subpackageName now equals "...base"
```

The bug is probaby due to commit https://github.com/junit-team/junit5/pull/2531 (Fix package path computation in ClasspathScanner )

I got this bug because I use `ReflectionSupport#findAllClassesInPackage` inside my JUnit Jupiter plugin.

## Steps to reproduce

To reproduce the bug is quite a trick. So project https://github.com/jlrosa/testwithresources was created. Here the steps to do
1) Clone the project, execute `mvn clean install`, and open the project in IDE.
2) Setup a breakpoint in `ClasspathScanner#processClassFileSafely` line 131.
3) Run the test `InjectResourcesTest` in debug mode.
4) Java debugger will stop. Check the value of the variable `fullyQualifiedClassName`. It will be something like: "com.adelean.inject.resources.junit.jupiter....jupiter.WithJacksonMapper"

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit 5.7.1
 - Build Tool/IDE: Intellij

## Deliverables

- [ ] ...

**Comment by sormuras** [comment]
The URI https://github.com/jlrosa/testwithresources is wrong. Typo?

**Comment by hosuaby** [comment]
Hello @sormuras .

Here the repository that can be used to reproduce the bug following steps above:
https://github.com/hosuaby/junit-bug-2612
