### ISSUE TITLE
Add JBang catalog

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#2616]
JBang now has an [AppStore](https://www.jbang.dev/appstore/) that makes it nice and short to run Java executables. We should add a small wrapper and a JBang catalog to make the Console Launcher available through that.

## Deliverables

- [ ] Add a `junit-team/jbang-catalog` repo and make it possible to run the Console Launcher via `jbang cli@junit-team`

**Comment by vlsi** [comment]
It looks like JBang misses checksum/signature verification for the binaries it downloads :-(

**Comment by sormuras** [comment]
> jbang is a tool for building and running .java/.jsh scripts and jar packages.

It supports running JAR files published on Maven Central.

```
jbang group-id:artifact-id:version [args...]
        (to run a .jar file found with a GAV id)
```

Running

`jbang org.junit.platform:junit-platform-console-standalone:1.7.2 --scan-modules`

yields

```.
+-- JUnit Jupiter [OK]
'-- JUnit Vintage [OK]

Test run finished after 31 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

**Comment by sauravjaiswalsj** [comment]
Hey, @marcphilipp if the issue is unassigned, then can I take up this issue?

**Comment by sbrannen** [comment]
@sauravjaiswalsj, yes, feel free to take it, and please keep us posted on your progress.

Since it requires a new repository in the `junit-team` organization (which means you cannot submit a PR against this repository), it's probably best to create a new repository in your account, do the work there, and provide us a link to your repository for us to check out.

**Comment by marcphilipp** [comment]
@sauravjaiswalsj I created https://github.com/junit-team/jbang-catalog for you to fork and create a PR against.

**Comment by sauravjaiswalsj** [comment]
I am unable to fork the repo cause it's empty. Please put a readme so that Fork option is available @marcphilipp

**Comment by sormuras** [comment]
Created an almost empty `README.md` file.

**Comment by laurentperez** [comment]
Hello. Any ongoing updates ?

**Comment by marcphilipp** [comment]
@sauravjaiswalsj Are you still interested in working on this or should we try to find someone else to take over?

**Comment by sormuras** [comment]
I added an examplary `cli-1.8.1` alias to the catalog: try `jbang cli-1.8.1@junit-team` to start the console launcher.

**Comment by sormuras** [comment]
@maxandersen Is there a specified (documented, or perhaps a common/well-known) version name pattern for catalog aliases?

At the moment, we are going with `cli-VERSION@junit-team` and duplicating an alias configuration for pointing to the _latest_ version via `cli@junit-team`.

```yaml
{
  "aliases" : {
    "cli" : {
      "script-ref" : "org.junit.platform:junit-platform-console-standalone:1.8.1",
      "description" : "Launch the JUnit Platform from the console"
    },
    "cli-1.8.1" : {
      "script-ref" : "org.junit.platform:junit-platform-console-standalone:1.8.1",
      "description" : "Launch the JUnit Platform from the console"
    }
  }
}
```
Copied from: https://github.com/junit-team/jbang-catalog/blob/main/jbang-catalog.json

**Comment by maxandersen** [comment]
up to what you are after. 
Having some kind version in the name is the simplest for now. 

There are branch/tag support but it (currently) requires a full form string: cli@junit/jbang-catalog/1.8.1 ￼

If we can find a way to represent it better we can definitely do so. 

Might be able to make it cli@junit:1.8.1 come to think of it. But for now that isn't there.

**Comment by marcphilipp** [comment]
As far as I can tell there's nothing left to do for this issue.
