### ISSUE TITLE
KingShaggy listed as author of junit-jupiter BOM in GitHub Dependency graph

### ISSUE THREAD

**Issue by alexsikorski** [junit-team/junit5#2621]
Good afternoon,

I am working on a group project and noticed under the dependency graph that [KingShaggy](https://github.com/KingShaggy) is the author for **org.junit.jupiter:junit-jupiter**. My question is, is this normal? I am viewing other dependencies and noticed that they have their respective author teams. This seems misleading.

![2021-05-18 15_07_43-](https://user-images.githubusercontent.com/34862811/118666757-51a69000-b7eb-11eb-8f53-dad21b806fef.png)

**Comment by sbrannen** [comment]
How did you generate the dependency graph you took a screenshot of?

**Comment by sbrannen** [comment]
Never mind. I find the same in our GitHub repo: https://github.com/junit-team/junit5/network/dependencies

**Comment by sbrannen** [comment]
> is this normal? 

No, that sounds like a bug in GitHub's _Dependency Graph_ feature.

Thanks for letting us know.

We will get in touch with GitHub support.

**Comment by alexsikorski** [comment]
Switched over to **org.junit.jupiter:junit-jupiter-api** and this is displayed. Please have a look at the usages too, [https://github.com/ChitreshSirohi/MyCodingPractice](repo) - it states the repo has 120k~ usages.

No problem!
![2021-05-18 15_20_58-Window](https://user-images.githubusercontent.com/34862811/118668430-c5956800-b7ec-11eb-92af-f1e896be9990.png)

**Comment by sbrannen** [comment]
That's quite bizarre. Thanks for sharing.

**Comment by sbrannen** [comment]
I opened a ticket with GitHub support and tweeted this: https://twitter.com/sam_brannen/status/1394664675359526913

**Comment by sbrannen** [comment]
The GitHub support team replied that they have...

> updated the dependencies so they should be associated with the correct repositories now.

In light of that, I am closing this issue.
