### ISSUE TITLE
Add new AnnotationBasedArgumentsProvider 

### ISSUE THREAD

**Issue by Michael1993** [junit-team/junit5#2622]
Sometimes an arguments provider needs to be initialised with an annotation externally before you can call `provideArguments`. It has to implement something like `Consumer<A>` or [`AnnotationConsumer<A>`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/support/AnnotationConsumer.html). It'd be nice to have an extension point that merged `ArgumentsProvider` with `AnnotationConsumer<A>` (something like `AnnotationBasedArgumentsProvider<A>` so I could call `provideArguments(ExtensionContext extensionContext, A annotation)` instead of `accept(A annotation)` and then `provideArguments(ExtensionContext extensionContext)`.

An example extension that consumes an annotation is [CsvArgumentsProvider](https://github.com/junit-team/junit5/blob/main/junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvArgumentsProvider.java). It seems `AnnotationConsumer<A>` is only used by `ArgumentsProvider` implementations (?).

Maybe this is too simple and doesn't add much value, other than a bit of convenience.

EDIT: Another option is to not constrict the `ArgumentsProvider` in such a way (i.e.: `AnnotationConsumer` can only consume annotations) and have a more generic type parameter. This way the `ArgumentsProvider` can be initialised with anything - I recently used this approach with `Parameter`.

## Deliverables

- [ ] A new (very simple) extension point merging `AnnotationConsumer<A>` and `ArgumentsProvider`
- [ ] Alternatively: A new extension point merging `Consumer<T>` and `ArgumentsProvider`.

**Comment by juliette-derancourt** [comment]
Tentatively slated for 5.8-M2 solely for the purpose of _team discussion_

**Comment by Michael1993** [comment]
Sorry, I'm not really familiar with the process - I edited the original post to add another alternative I think you could consider. Hope that's OK.

**Comment by sbrannen** [comment]
> I edited the original post to add another alternative I think you could consider. Hope that's OK.

Yes, that's totally fine.

**Comment by marcphilipp** [comment]
**Team Decision:** We think it should roughly look like the following:

```java
public abstract class AnnotationBasedArgumentsProvider<A> implements ArgumentsProvider, AnnotationConsumer<A> {

	private A annotation;

	@Override
	public final void accept(A annotation) {
		this.annotation = annotation;
	}

	@Override
	public final Stream<? extends Arguments> provideArguments(ExtensionContext context) {
		return provideArguments(context, annotation);
	}

	protected abstract Stream<? extends Arguments> provideArguments(ExtensionContext context, A annotation);
}
```

@Michael1993 Are you still interested in this? If so, could you please submit a PR and change the internal implementations to use it?

**Comment by gilbertojrequena** [comment]
I could work on this if the OP is not interested in creating the PR.

**Comment by Michael1993** [comment]
Go for it - I'm interested but don't really have free capacity at the moment.

**Comment by gilbertojrequena** [comment]
Hey guys can you give it a look to the open [PR](https://github.com/junit-team/junit5/pull/2978) for solving this issue? It is being open for some time and it is not that big ;)

**Comment by marcphilipp** [comment]
**Team Decision:** We'll also create an `AnnotationBasedArgumentConverter` for symmetry.
