### ISSUE TITLE
Document best practices for test method and test class visibility

### ISSUE THREAD

**Issue by ttddyy** [junit-team/junit5#2626]
In JUnit Jupiter, the `public` modifier is optional in test classes and methods.

I see test classes in JUnit, Spring projects, etc apply this no `public` modifier pattern.
Once I get used to this style, it feels very redundant when I encounter tests that have `public` all over.

I believe this is a good practice to follow.

However, in JUnit documentation, I only find this line regarding the `public` modifier:

>  Test classes, test methods, and lifecycle methods are not required to be public, but they must not be private. 

It would be great if JUnit documentation mentions that leaving off the `public` modifier is preferred unless visibility is required. (e.g. base class shared by different packages)

I understand this is a bit of _opinionated_ aspect, but it would be nice to mention the principle of _["less is more"](https://stackoverflow.com/questions/55215949/why-junit-5-default-access-modifier-changed-to-package-private/55230350#55230350)_ in the documentation.
So that, a person like me can encourage this pattern to other devs with the backup of JUnit good practice.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.8 M2 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment]
**Team decision:** Add another sentence:

> It is recommended to omit `public` unless there's a technical reason for doing so, e.g. inheriting from a base test class in another package.

**Comment by A248** [comment]
I'm not sure if this was considered, but I thought I would mention it for anyone who comes here (I was myself linked here).

When testing on the module path, using non-public test methods requires *opening* the test packages to JUnit 5. I find it easier to export the packages (Maven Surefire does this automatically). That's my personal reason for using public test methods at the moment, but this could change if a later Surefire version opens packages.

For reference, here's a Maven surefire issue which describes the error one might encounter using non-public test methods: https://issues.apache.org/jira/projects/SUREFIRE/issues/SUREFIRE-1909

**Comment by sbrannen** [comment]
@A248, I think that's a good use case to mention in the User Guide, since it might assist some people who encounter that issue.

So I'm reopening this issue to add a hint about that as well.

**Comment by sbrannen** [comment]
Closely related to:

- #3553
