### ISSUE TITLE
EclipseRunner creates fresh root ExtensionContext per package

### ISSUE THREAD

**Issue by almondtools** [junit-team/junit5#2628]
According to https://stackoverflow.com/questions/49532885/with-junit-5-how-to-share-information-in-extensioncontext-store-between-test all subsequent tests of one test run should share the same extension context. The eclipse runner (and maybe also others) seems to create a new ExtensionContext every time a new package is entered.

This meens that instances cannot be shared via root context store, since even the context is not shared.

## Steps to reproduce

[bugs.zip](https://github.com/junit-team/junit5/files/6559233/bugs.zip)
Running attached tests with the eclipse junit 5 runner results in following output

```
------------------------------
org.junit.jupiter.engine.descriptor.JupiterEngineExtensionContext@1aafa419:Optional[class com.enbw.eop.constructors.bugs.package1.Test1]
------------------------------
------------------------------
org.junit.jupiter.engine.descriptor.JupiterEngineExtensionContext@55182842:Optional[class com.enbw.eop.constructors.bugs.package2.Test2]
------------------------------
```

Thus there are different root context in the same test run.

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit 5.7.2 (Jupiter + Platform)
 - Build Tool/IDE: Eclipse

## Deliverables
[bugs.zip](https://github.com/junit-team/junit5/files/6559236/bugs.zip)

**Comment by almondtools** [comment]
I tested later in IntelliJ and there the problem does not occur.

**Comment by marcphilipp** [comment]
Please open an issue with Eclipse. It looks like they're calling `Launcher.execute` multiple times.
