### ISSUE TITLE
Download JUnit's API Documentation

### ISSUE THREAD

**Issue by f8chicken** [junit-team/junit5#2633]
this is not feature request, but perhaps a silly and embarrasing question. 
how to get the junit api documentation offline, the download link.
what you do with junit user guide, i really thanks for that. it is a pdf format. 
- [ ] ...

**Comment by sormuras** [comment]
We don't provide a downloadable "all-in-one" API documentation in an aggregated format.

For the time being, you may grab an API documentation for each module (artifact) from Maven Central. For example, the Jupiter API file (`junit-jupiter-api-5.8.0-M1-javadoc.jar`) is located in this directory:

- https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-api/5.8.0-M1/

The idea of providing a downloadable JAR (or zip) file that contains all pages of a specific version is a good one, though.
For https://junit.org/junit5/docs/5.8.0-M1/api/ it would exist something like: https://junit.org/junit5/docs/junit-5.8.0-M1-api.zip (⬅ does not work, yet!)

**Comment by sormuras** [comment]
A way suggested by @marcphilipp that already works today: https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fjunit-team%2Fjunit5%2Ftree%2Fgh-pages%2Fdocs%2F5.8.0-M1%2Fapi

**Comment by f8chicken** [comment]
thank you for the link ,🤩
