### ISSUE TITLE
Improved DynamicTest testSourceUri support

### ISSUE THREAD

**Issue by therealryan** [junit-team/junit5#2635]
The current set of schemes for [URI Test Sources for Dynamic Tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests-uri-test-source) is missing support for test instances that work out their own location by walking the stack trace.

The answers to [this relevant stackoverflow question](https://stackoverflow.com/questions/58788085/how-can-i-create-a-junit-5-dynamictest-testsourceuri-from-a-stacktraceelement) fall short:
 * Top-rated answer, of using the `method:` scheme:
   * You cannot get method arguments from a `StackTraceElement`
   * Scheme does not support line number information, so you loose the distinction between multiple tests instances created in the same method
   * Does not support test instances created in constructors
 * Accepted answer, of constructing a `file:` URI from the `StackTraceElement`, leaves you making unsafe assumptions about how the project source and build directories are organised (e.g.: maven vs gradle conventions, multi-module projects, instances defined in dependency jars, etc)

## Deliverables

- [ ] Test source URI scheme that can be constructed from the data available in a StackTraceElement

**Comment by marcphilipp** [comment]
Related to #2431

**Comment by marcphilipp** [comment]
@therealryan Would the above PR suit your needs?

**Comment by therealryan** [comment]
@marcphilipp It would! My use-case wouldn't require the automatic population of the URI (Test cases are defined without reference to junit, so I'm already walking the stack well before calling `dynamicTest()`) but the addition of the `class:` URI scheme is exactly what I'm after.

**Comment by marcphilipp** [comment]
`ClassSource` already supports an optional `FilePosition` (line/column). Doesn't that solve your use case?

**Comment by therealryan** [comment]
@marcphilipp quite possibly it does, but we seem to be missing the ability to create a `ClassSource` from the URI supplied in the `dynamicTest()` call - that's the bits of #2431 that I'm wanting (i.e.: the changes in `ClassSource` and `TestFactoryTestDescriptor`).
Would it be feasible to split out those changes into a PR of their own if they are more palatable than the default-on-stack-walking stuff?

**Comment by marcphilipp** [comment]
> Would it be feasible to split out those changes into a PR of their own if they are more palatable than the default-on-stack-walking stuff?

Yes, I think that would make sense. Would you be interested in providing a PR for that?
