### ISSUE TITLE
Update junit-vintage-engine dependency to junit version to 4.13.2 due to vulnerability in the current 4.13

### ISSUE THREAD

**Issue by marioja** [junit-team/junit5#2641]
Currently junit-vintage-engine 5.7.2 requires version 4.13 of junit and should change the dependency to junit 4.13.2.  See this link for the vulnerability https://ossindex.sonatype.org/component/pkg:maven/junit/junit@4.13

**Comment by sbrannen** [comment]
Published Maven POM: https://repo1.maven.org/maven2/org/junit/vintage/junit-vintage-engine/5.7.2/junit-vintage-engine-5.7.2.pom

**Comment by marcphilipp** [comment]
The 5.8 snapshots already use 4.13.2. As of today, there are no plans for another 5.7.x release. Hence, I'm closing this issue.
