### ISSUE TITLE
Only search for annotations on enclosing class if current class is an inner class

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2647]
## Overview

While working on the fix for #2645, I realized that our annotation search algorithms that fall back to searching on _enclosing classes_ also find annotations on enclosing classes even if the current nested class is a static nested class.

For example, given the following test case, the test method in `InnerNestedTests` passes; whereas, the test method in `StaticNestedTests` fails.

```java
@DisplayNameGeneration(ReplaceUnderscores.class)
class DisplayNameGenerationInheritanceTests {

	@Nested
	class InnerNestedTests {
		@Test
		void this_is_a_test(TestInfo testInfo) {
			assertThat(testInfo.getDisplayName()).isEqualTo("this is a test (TestInfo)");
		}
	}

	// @DisplayNameGeneration(Standard.class)
	static class StaticNestedTests {
		@Test
		void this_is_a_test(TestInfo testInfo) {
			assertThat(testInfo.getDisplayName()).isEqualTo("this_is_a_test(TestInfo)");
		}
	}
}
```

One could of course argue that this is be design; however, I'm not convinced that `@DisplayNameGeneration` and `@IndicativeSentencesGeneration` should be _inherited_ from an enclosing static class or top-level class if the current class is not an inner class.

For example, in the Spring Framework's testing support, I only search for an annotation on the enclosing class if the current class is an _inner class_:

https://github.com/spring-projects/spring-framework/blob/df588e030f069dd31997ff747839f1d8d5d8d7c7/spring-test/src/main/java/org/springframework/test/context/TestContextAnnotationUtils.java#L398-L401

## Deliverables

- [x] Decide if want to retain the current semantics.
- <strike>[ ] If so, document those semantics for `@DisplayNameGeneration` and `@IndicativeSentencesGeneration` and anywhere else we employ such a search algorithm.</strike>
- [x] If not, change the algorithm to match the behavior in the Spring Framework and document the new semantics.

**Comment by marcphilipp** [comment]
**Team decision:** Change the algorithm to treat static nested classes like standalone test classes (as in all other places), i.e. don't look up annotations on the enclosing class.
