### ISSUE TITLE
`CloneNotSupportedException` when running a certain Unit Test using AdoptOpenJDK 16, `junit-vintage-engine` and PowerMock

### ISSUE THREAD

**Issue by TheBusyBiscuit** [junit-team/junit5#2648]
When running a certain Unit Test using `PowerMock` and `Junit-Vintage` on Java 16 (AdoptOpenJDK 16), the test fails to intialize due to Java 16's new reflection policies. I have linked the Unit Test and stacktrace below, let me know if you need any further information :)

## Steps to reproduce

1. Install AdoptOpenJDK 16
2. Clone the repository `https://github.com/mcMMO-Dev/mcMMO`
3. Run `mvn clean package` (or any other command which executes the `test` goal)
4. Witness how `ChunkStoreTest.java` fails to initialize

The issue was discovered on this repository: 
https://github.com/mcMMO-Dev/mcMMO

Here is the project's `pom.xml`:
https://github.com/mcMMO-Dev/mcMMO/blob/master/pom.xml

Here is the Unit Test which fails to initialize:
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/test/java/com/gmail/nossr50/util/blockmeta/ChunkStoreTest.java

And the full stacktrace:
https://pastebin.com/7DBVLmEZ

I updated the Unit Test from `Junit-Vintage` to `Junit5-Jupiter` (and from `PowerMock` to `Mockito`) and it seems to completely resolve the issue, but I decided to still raise an issue here in case this is somehow be able to be fixed nonetheless.

## Context

 - Used JDK: AdoptOpenJDK 16 - `16.0.1+9 64-bit 2021-04-20`
 - Used versions: `org.junit.vintage:junit-vintage-engine:5.6.2` (also tested on `5.8.0-M1`)
 - Build Tool: Maven (`mvn clean package`)

## Deliverables
Not quite sure what is needed here :/

**Comment by marcphilipp** [comment]
The stacktrace is misleading since it only points towards the location where the `MultipleFailuresError` is instantiated but the stacktraces of the contained exceptions are not printed. Please raise an issue with Surefire to improve reporting of such failures.

Root cause is almost certainly PowerMock. Adding a bunch of `--add-opens` parameters resolves the issue for me:

```
mvn clean test "-DargLine=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED"
```

**Comment by TheBusyBiscuit** [comment]
Thanks for the quick reply!
I found a coresponding issue on the PowerMock issues tracker, so I will continue my journey there.
Thank you :)

Link for any curious developer who comes across this post:
https://github.com/powermock/powermock/issues/1094
