### ISSUE TITLE
Introduce AnnotationSupport.findAnnotation() variant that searches on enclosing classes

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2649]
## Overview

This a follow up to #2647 that aims to make the new `org.junit.platform.commons.util.AnnotationUtils.findAnnotation(Class<?>, Class<A>, boolean)` feature available to `TestEngine` and extension authors.

See also [this thread](https://twitter.com/knutwannheden/status/1404685536527327233) on Twitter.

## Implementation Considerations

The new method in `AnnotationSupport` does not necessarily have to have the same name or signature as the internal method in `AnnotationUtils`. We may choose a different method name in order to avoid the simplistic `boolean` flag to enable the feature, since setting the flag to `false` makes the method behave the same as the existing `findAnnotation()` methods. Alternatively, we may wish to introduce an enum instead of a boolean flag in order to be able to support additional semantics in the future.

## Deliverables

- [x] Design the new API.
- [x] Implement the new API.
- [x] Document it in release notes.

**Comment by knutwannheden** [comment]
As an alternative to the new API I still think it could be interesting to introduce a new meta-annotation. Something like `@Nestable` or `@NestingAware` which could be applied to JUnit annotations. This may not work or make sense for reasons I am unaware of, but what I like about this is that it would be easily discoverable (for extension authors and users) as the presence of the annotation would already document how the annotation can be used in the context of nested tests.

**Comment by marcphilipp** [comment]
**Team decision:** Introduce new `findAnnotation(Class<?>, Class<A>, SearchOption)` method in `AnnotationSupport` with `enum SearchOption { DEFAULT, INCLUDE_ENCLOSING_CLASSES }`.

**Comment by sbrannen** [comment]
> As an alternative to the new API I still think it could be interesting to introduce a new meta-annotation. Something like `@Nestable` or `@NestingAware` which could be applied to JUnit annotations. This may not work or make sense for reasons I am unaware of, but what I like about this is that it would be easily discoverable (for extension authors and users) as the presence of the annotation would already document how the annotation can be used in the context of nested tests.

We decided not to introduce an annotation like `@InheritedFromEnclosingClasses` since users or extension authors might then need a way _not_ to search on enclosing classes for the meta-annotated annotation.

With the new `findAnnotation(Class<?>, Class<A>, SearchOption)` method introduced in commit 3f2d4e115a9d3f67083d5ebe6b07e091183ddad5, people can now choose the search strategy to use on a case-by-case basis.

Please give it a try in the upcoming 5.8 M2 snapshots and let us know what you think.
