### ISSUE TITLE
Support ordering between @ExtendWith and @RegisterExtension

### ISSUE THREAD

**Issue by oehme** [junit-team/junit5#2651]
I was trying to write a [Micronaut test](https://micronaut-projects.github.io/micronaut-test/latest/guide/#junit5) using the `@MicronautTest` annotation. This annotaiton is a meta-annotation that includes `@ExtendWith(MicronautJunit5Extension)`. However, I also needed to start up some other services with random port numbers and add those ports to Micronaut's configuration. I tried doing so with `@Order(1) @RegisterExtension MyOtherService service`, but that didn't work. The MicronautExtension is still called first and fails because calling `getPort` on my service can't be done until it has started.

It would be great if `@Order` worked together with `@ExtendWith`, so that I could push my service in front of Micronaut's startup.

Workaround:

Don't use `MicronautTest` with all its convenience and instead use `ApplicationContext.run(EmbeddedServer.class, properties)`.

## Deliverables

- [ ] ...

**Comment by oehme** [comment]
The same issue has been reported previously for [MicronautTest in Spock](https://github.com/micronaut-projects/micronaut-test/issues/80) and got closed as "not a Micronaut problem", which is why I'm looking for a solution in JUnit instead.

**Comment by marcphilipp** [comment]
Related to #506.

**Comment by sbrannen** [comment]
Related to #2680
