### ISSUE TITLE
assertEquals behavior with Int, Long looks inconsistency in Kotlin

### ISSUE THREAD

**Issue by hojongs** [junit-team/junit5#2652]
Bug report for JUnit 5 jupiter API

## Steps to reproduce

```kotlin
internal class ExampleTest {

    private fun exampleInt(): Int = 1

    private fun exampleLong(): Long = 1L

	
    @Test
    fun test1() {
        // success
        assertEquals(1, exampleLong())
    }

    @Test
    fun test2() {
        // fail: expected: java.lang.Long@30a3e2da<1> but was: java.lang.Integer@50fc3976<1>
        assertEquals(1L, exampleInt())
    }
}
```

## Context

 - Used versions (Jupiter/Vintage/Platform):
```
    // Gradle Kotlin DSL
    testImplementation(platform("org.junit:junit-bom:5.7.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")

tasks {
    withType<Test> {
        useJUnitPlatform()
    }
}

```
 - Build Tool/IDE:
   - JDK 16
   - Intellij

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
Here's a Java based variant. See comments for details.

```java
package example;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class ExampleTests {

	@Test
	void test1() {
		// Invokes assertEquals(long, Long)
		Assertions.assertEquals(1, exampleLong());
	}

	@Test
	void test2() {
		// Compiler error:
		// The method assertEquals(long, long) is ambiguous for the type Assertions
		// Assertions.assertEquals(1L, exampleInt());

		// fail: expected: java.lang.Long@30a3e2da<1> but was: java.lang.Integer@50fc3976<1>
		// Invokes assertEquals(Object, Object)
		Assertions.assertEquals(Long.valueOf(1L), exampleInt());
	}

	private Integer exampleInt() {
		return 1;
	}

	private Long exampleLong() {
		return 1L;
	}

}
```

Thus, with the Kotlin based variant provided in this issue's description, it would appear that `assertEquals(Object, Object)` is also being invoked.

Note that we don't have overloaded variants of `assertEquals(...)` where the actual and expected arguments have different primitive types or different wrapper types.

In Java, the solution is to ensure that a `Long` wrapper is used for both. For example, the following _fixes_ the failing assertion in Java: `Assertions.assertEquals(Long.valueOf(1L), exampleInt().longValue())`.

**Comment by marcphilipp** [comment]
Interestingly, IDEA shows a warning in Java for `Assertions.assertEquals(Long.valueOf(1L), exampleInt())` because `Long` and `Integer` are incompatible, i.e. `equals()` will always return `false`.

**Comment by marcphilipp** [comment]
**Team decision:** Since the compiler follows its own rules when to apply a widening conversion (in this case from Kotlin's `Int` to `Long`), the `assertEquals` overload it picks is determined based on that. We can't add overloads for `assertEquals(int, long)`/`assertNotEquals(int, long)` because an `int` can be widened to a `long` but a `long` cannot be narrowed to an `int`. Moreover, passing an `Integer` to `Long.equals()` always returns `false`. Hence, in this case, the only way to fix this is to make sure you compare compatible types, e.g. using `longValue()` in Java to `toLong()` in Kotlin.

**Comment by hojongs** [comment]
Thank you for very fast and detail explanation!! :) 

According to your comment, Kotlin users should watch out when using assertEquals with Int, Long but I agree with your team decision, Good!
