### ISSUE TITLE
DiscoverySelectors#selectPackage does not select packages from JAR

### ISSUE THREAD

**Issue by umapriyadarsi** [junit-team/junit5#2655]
Fundamentally I am facing the same issue : https://github.com/junit-team/junit5/issues/1493 
Thought I do not know if the underlying cause is same.
I checked that issue and also ensured that my jdk is above 141. But still Junit is unable to resolve the package selector.

With package, I get 'containsTests' as false.
![image](https://user-images.githubusercontent.com/3054787/123893652-6d6c8c80-d97a-11eb-8330-f08327811cb8.png)

Whereas when I give a class in the same package, it works just fine : 
![image](https://user-images.githubusercontent.com/3054787/123893831-c2a89e00-d97a-11eb-83ba-e8a951560784.png)

![image](https://user-images.githubusercontent.com/3054787/123894049-216e1780-d97b-11eb-8ff6-23d5f81b3145.png)
In the above screenshot you can see that the testing class is part of the same package mentioned.

## Context
I am using this Junit dependency jar : https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.0-M1/junit-platform-console-standalone-1.8.0-M1.jar

OS : 
centos-release-7-7.1908.0.el7.centos.x86_64
jdk : 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

## Deliverables

What is the recommended way to tackle this? Should we be providing all the list of testing class names?

**Comment by marcphilipp** [comment]
@umapriyadarsi Could you please share a reproducer project?

**Comment by sbrannen** [comment]
I don't know the structure of your project and its classpath, but you might need to use `org.junit.platform.engine.discovery.DiscoverySelectors.selectClasspathRoots(Set<Path>)` when building the `LauncherDiscoveryRequest` to make sure that classpath scanning looks in the right places.

**Comment by umapriyadarsi** [comment]
> I don't know the structure of your project and its classpath, but you might need to use `org.junit.platform.engine.discovery.DiscoverySelectors.selectClasspathRoots(Set<Path>)` when building the `LauncherDiscoveryRequest` to make sure that classpath scanning looks in the right places.

Your suggestion worked out 👍 .
![image](https://user-images.githubusercontent.com/3054787/124003632-ce38ab00-d9f4-11eb-8155-c88e512a2abb.png)

I do not have a reproducible project currently.
You guys at Junit are doing a fantastic job, but unless I am missing something, this kind of info would be helpful on the help docs/user guide.

One of the reasons why I want to try out selectors based on package was to avoid typing out all the Test classes.
While we are just getting started, one of my other concerns is that(though it appears silly to me), if the list of classes grows too large, maybe it might cause OutOfMemoryException.
I guess I should be looking into [ClassOrderer](https://junit.org/junit5/docs/snapshot/api/org.junit.jupiter.api/org/junit/jupiter/api/ClassOrderer.html)
