### ISSUE TITLE
@DataJpaTest in a multi module project 

### ISSUE THREAD

**Issue by ankisinha3005** [junit-team/junit5#2656]
https://stackoverflow.com/questions/67863862/datajpatest-in-a-multimodule-maven-project
<img width="1241" alt="Screenshot 2021-06-30 at 8 10 58 PM" src="https://user-images.githubusercontent.com/32894171/124066821-fb1daa00-da56-11eb-92f3-f67408286dc5.png">

Hi everyone ,

It's been one month , didn't get any replies . Please help !
I have a multi module project containing module A and module B . Module A has the server main class and hence has Module B as dependency . Now i'm trying to write a @DataJpaTest in my module B , but this annotation is looking for @ContextConfiguration which is in main class, for that i need to add Module A as dependency in module B and hence due to this a dependency cycle problem appears. Please suggest me how should i resolve it . Above screenshot shows the exception i'm getting .

**Comment by marcphilipp** [comment]
I added a comment to the StackOverflow question.
