### ISSUE TITLE
Get unique ID from TestInfo

### ISSUE THREAD

**Issue by xtaixe** [junit-team/junit5#2657]
I'm trying to create a unique folder per test (including parameterized tests) in a specific location, so I wanted to use the test unique ID (assuming it's unique also for each parameterized test) but it is not available in TestInfo. Should it be there or could it be added?

Thanks.

**Comment by jbduncan** [comment]
@xtaixe I might be missing something here, so please feel free to clarify if I have.

Have you considered using JUnit 5's [`@TempDir`](https://www.baeldung.com/junit-5-temporary-directory) annotation already, by any chance?

**Comment by marcphilipp** [comment]
@xtaixe I think it would be fine to add the unique ID to `TestInfo`. Please note it's already available via `ExtensionContext` so you could write an extension to create the folders.

**Comment by xtaixe** [comment]
@jbduncan I want to create the directory in a specific location, not in/as a temp dir.

@marcphilipp yes, but for now I wanted to avoid creating a whole extension just for this and just use the provided `TestInfo`

Thanks.

**Comment by xtaixe** [comment]
I didn't know that the unique id was such a long "path" string... I'll need to parse it somehow to make it usable for us, so let me explain some more details on my use case in case there's a better way to do this or it's a feature that might make sense for JUnit to support directly.

We are testing a series of commands that produce some files and logs and we want those available for manual review (usually only if the test fails) instead of in a temp dir which is automatically deleted. Since we are using Maven our idea is to use the following directory: `target/test-output/ClassName/MethodName/sequence` (sequence is there for parameterized tests), this way the directory is automatically git ignored and cleaned by Maven.

Let me know if you have any thoughts or suggestions around this. Thanks.

**Comment by sbrannen** [comment]
@xtaixe, have you considered getting the `ClassName` from the `TestInfo` and using the display name (also from `TestInfo`) instead of `MethodName/sequence`?

Note that you would want to _sanitize_ the display name to ensure that it doesn't contain any characters that are invalid for the file system.

**Comment by xtaixe** [comment]
If `@DisplayName`, contains a long-ish description (which we already have in some cases), it's not going to work well... I think the best solution for this would be to be able to obtain some kind of `UUID` for each test (which is what I expected unique id to contain when I started looking into this).

**Comment by xtaixe** [comment]
@sbrannen Actually just a sequence (which it's already there at the end of the unique id) would be better, cause then you know which folder maps to which test/parameterized value immediately, which you lose with something opaque like a `UUID`.

**Comment by sbrannen** [comment]
> if `@DisplayName`, contains a long-ish description (which we already have in some cases), it's not going to work well...

Yes, I agree with that.

> Actually being able to query a sequence for each class and method (which it's already there at the end of the unique id) would be better, cause then you know which folder maps to which test/parameterized value immediately, 

By "sequence", I guess you mean the invocation index. 

That would work in terms of uniqueness for a given run of the `TestPlan`, but seeing the index in the file system would not be very "user friendly" in terms of mapping back to the arguments with which the parameterized test was invoked.

Though, I don't currently have a better idea for "concise and precise" uniqueness.

> which you lose with something opaque like a `UUID`.

True.
