### ISSUE TITLE
JUnit silently fails to resolve tests if they aren't of type `void`. This can be confusing, particularly in other JVM languages like Scala.

### ISSUE THREAD

**Issue by GavinRay97** [junit-team/junit5#2659]
## Steps to reproduce

1. Make class with a JUnit `@Test` that doesn't return `void`
2. Try to run all tests
3. Have it be reported that no tests were found

## Context

Following a multi-day investigation and discussion with the Redhat/Quarkus team at:
- https://github.com/quarkusio/quarkus/issues/18373
- https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/.22No.20Tests.20Found.22.2C.20last.20issue.20for.20Scala.203.20support

# The confusion
![image](https://user-images.githubusercontent.com/26604994/124505556-c0d64480-dd97-11eb-9be4-288cfc7cf83f.png)

![image](https://user-images.githubusercontent.com/26604994/124505570-cc297000-dd97-11eb-986a-a41e9b71195f.png)

# The resolution

- (Add `: Unit` to function signature to have it generate `void` as return type in bytecode)

![image](https://user-images.githubusercontent.com/26604994/124505624-e95e3e80-dd97-11eb-9459-e2e0f847fb55.png)

![image](https://user-images.githubusercontent.com/26604994/124505647-f24f1000-dd97-11eb-9b72-c3b05726f0c3.png)

## Deliverables

Please would it be possible to either:
- Make JUnit tests accept `@Test` that return things beside `void`, potentially just disregarding the return type
- Issue a VERY LARGE, blatant error/warning message when `No tests were found` that JUnit only resolves `@Test` methods of type `void`. Something like `No tests returning type "void" were found. JUnit only resolves tests of type "void".`

**Comment by marcphilipp** [comment]
Thanks for raising the issue! This has come up before and is tracked in #242. Feel free to join the discussion there!

**Comment by GavinRay97** [comment]
> Thanks for raising the issue! This has come up before and is tracked in #242. Feel free to join the discussion there!

Sorry, wasn't aware of the existing issue -- my apologies!

**Comment by marcphilipp** [comment]
> Sorry, wasn't aware of the existing issue -- my apologies!

No worries at all!
