### ISSUE TITLE
Ensure JAR manifests are not regenerated unless there are code changes

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#266]
## Status Quo

Executing `gradle test` twice in a row results in all tests being executed by the `JUnit5Plugin` again, even though everything is up-to-date in the subsequent run.

## Analysis

After thorough analysis, it turns out that the `JUnit5Plugin` is not the culprit here. Rather, the underlying cause is that JAR manifests are now continuously created with a `buildDate` and `buildTime` (see ca83f28). The net result is that dependent project JARs are always rebuilt, and since these JARs serve as _inputs_ to the `junit5Test` task the tests are always executed.

## Deliverables

- [ ] Ensure that JAR manifests are only generated if code is compiled or recompiled.

**Comment by sbrannen** [comment]
@aalmiray, do you have any tips on how to achieve the desired behavior here?

**Comment by raniejade** [comment]
@sbrannen you could mark the `test` (`project.sourceSets.test`) sourceSet as an input. This will clearly not work on custom sourceSets.

**Comment by sbrannen** [comment]
After executing `gradle --info :junit-tests:junit5Test`, I consistently see the following:

```
:junit-tests:junit5Test
Executing task ':junit-tests:junit5Test' (up-to-date check took 0.002 secs) due to:
  Input file /Users/sbrannen/source/junit-lambda/junit4-runner/build/libs/junit4-runner-5.0.0-SNAPSHOT.jar has changed.
  Input file /Users/sbrannen/source/junit-lambda/junit-commons/build/libs/junit-commons-5.0.0-SNAPSHOT.jar has changed.
  Input file /Users/sbrannen/source/junit-lambda/junit5-engine/build/libs/junit5-engine-5.0.0-SNAPSHOT.jar has changed.
```

Can anyone enlighten me as to why `junit4-runner-5.0.0-SNAPSHOT.jar`, `junit-commons-5.0.0-SNAPSHOT.jar`, and `junit5-engine-5.0.0-SNAPSHOT.jar` would have been _changed_? 

From my understanding, those JARs should not be rebuilt if nothing has changed in those projects.

Note, however, that when I execute `gradle -a :junit-tests:junit5Test` things work as expected.

So I guess the real question is: _How can we modify the build so that the JARs from other projects are not modified unnecessarily?_

**Comment by sbrannen** [comment]
To partially answer my own question, these JARs are rebuilt because the MANIFEST has been modified, for example:

```
Executing task ':junit-commons:jar' (up-to-date check took 0.003 secs) due to:
  Input file /Users/sbrannen/source/junit-lambda/junit-commons/build/tmp/jar/MANIFEST.MF has changed.
```

The underlying cause is that JAR manifests are now continuously created with a timestamp (see ca83f28761eacf0db5f85b409af39b4e4e7730c7).

So how can we fix this?

**Comment by aalmiray** [comment]
I think the fix wold be to skip injecting `buildDate` and `buildTime` on the JAR's manifest given a conditional.

**Comment by sbrannen** [comment]
Thanks, @aalmiray.

I have actually come up with a solution along those lines on my own. (surprise)

I'll push it to `master` in a few minutes.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
I have revised the title and description for this issue accordingly.
