### ISSUE TITLE
LauncherDiscoveryRequest can't find spock unit tests in a jar

### ISSUE THREAD

**Issue by chansonzhang** [junit-team/junit5#2660]
I followed this [document](https://junit.org/junit5/docs/current/user-guide/#launcher-api-execution) to discovery and execute spock unit tests, and in IDEA everything is ok, but when I packaged the code to jar, and use `java -cp xx.jar <main_class>`, the number of found tests is **0**. No error is reported and test class exists in jar.

**Comment by sbrannen** [comment]
> `java -cp xx.jar <main_class>`

What is the `main_class`, and what is the full classpath you supply?

**Comment by ligun** [comment]
I have similar problem.
I could execute tests using spock framework yesterday on IntelliJ IDEA and Linux shell with Gradle.
But today I built same tests, and it was not found test.
I didn't change any build setting or soure code.

**Comment by chansonzhang** [comment]
> > `java -cp xx.jar <main_class>`
> 
> What is the `main_class`, and what is the full classpath you supply?

I use this [RunTests.java](https://github.com/chansonzhang/jvmlang/blob/main/src/test/java/com/chansonzhang/demo/RunTests.java) as main class to discover the groovy tests in [src/test/groovy/com/chansonzhang/demo](https://github.com/chansonzhang/jvmlang/tree/main/src/test/groovy/com/chansonzhang/demo).

When I run it directly in IDEA, it prints the following message:
```
found: 6
skipped: 0
failed: 0
```
As the log shows, it found 6 groovy tests. 
However, when I package this project use `mvn -e package -DskipTests -f pom.xml` and run it agagin with 
```
java -cp jvmlang-0.0.1-SNAPSHOT-tests.jar:jvmlang-0.0.1-SNAPSHOT-test-jar-with-dependencies.jar com.chansonzhang.demo.RunTests
```
it just found 0 groovy tests, as the logs show:
```
found: 0
skipped: 0
failed: 0
```

**Comment by marcphilipp** [comment]
The problem is that the maven-assembly-plugin does not merge files in META-INF/services:

```console
$ unzip -c jvmlang-0.0.1-SNAPSHOT-test-jar-with-dependencies.jar META-INF/services/org.junit.platform.engine.TestEngine
Archive:  jvmlang-0.0.1-SNAPSHOT-test-jar-with-dependencies.jar
  inflating: META-INF/services/org.junit.platform.engine.TestEngine
org.junit.jupiter.engine.JupiterTestEngine
```

Hence, the Spock engine is not registered and won't be called.
