### ISSUE TITLE
Allow to intercept DynamicContainer#getChildren via InvocationInterceptor

### ISSUE THREAD

**Issue by BerndFarkaDyna** [junit-team/junit5#2661]
I hereby agree to the terms of the JUnit Contributor License Agreement.

The Creation of DynamicNodes can be intercepted via InvocationInterceptor# interceptTestFactoryMethod, the execution of DynamicTests can be intercepted via InvocationInterceptor#interceptDynamicTest. IMHO there is a gap between where the DynamicContainers are (if existing) evaluated.

In order to have an API which is consistent an method 

InvocationInterceptor#interceptDynamicContainter should be added.

**Comment by marcphilipp** [comment]
I think that's a fair point and could be added. What's your use case?

**Comment by Cody-Banks7** [comment]
I think it's a quite interesting idea. I would like to try to implement it.

**Comment by marcphilipp** [comment]
@Cody-Banks7 Thanks for the PR but we'd first need to understand the use case so we can ensure the new APIs actually meet the requirements.

@Cody-Banks7 @BerndFarkaDyna Could you please elaborate?
