### ISSUE TITLE
ReflectionUtils.hasCompatibleSignature method return false incorrectly in some cases

### ISSUE THREAD

**Issue by eeverman** [junit-team/junit5#2663]
## Applies to JUnit 5.7.2 / Junit-platform-commons 1.7.2

`ReflectionUtils.hasCompatibleSignature()` should return true for methods that have wider parameters than the passed argument types, however, it will return false.

Since this method is used by all of the `findMethod()` methods, all of those methods are similarly broken in this class (`ReflectionUtils`) and `ReflectionSupport`.

## Steps to reproduce
Here is a sample test that demonstrates the issue via `ReflectionSupport.findMethod`, which uses `hasCompatibleSignature` in its implementation.

You would expect `findMethod` to find the `format(Object)` method if you pass any type of Object (except Date which has an overloaded method version), however, it only finds this method if `Object.class` is passed, not a `String.class`.

```java
@Test
public void junitTest() throws Exception {

    //There is a SimpleDateFormat.format(Object) method
    assertTrue(
	    ReflectionSupport.findMethod(
			    SimpleDateFormat.class, 
			    "format",
			    Object.class
	    ).isPresent()
    );
    
    //This should find the same method as above since
    //a string can be passed to the same method, but
    // - - THIS TEST FAILS - -
    assertTrue(
	    ReflectionSupport.findMethod(
			    SimpleDateFormat.class,
			    "format",
			    String.class
	    ).isPresent()
    );

}
```

## Notes

It seems clear that the intent is that the wider method signatures be accepted and it would make sense because the found method would be usable.  The [for loop on this line](https://github.com/junit-team/junit5/blob/main/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java#L1632) is where the code steps through each method argument to ensure that the method accepts a wide type then the passed type.  If that is not true for any argument, false is returned inside the loop.  However, if all arguments pass the test, only methods that pass the `isGeneric` test return true.

**Comment by marcphilipp** [comment]
@sbrannen IIRC `ReflectionUtils.hasCompatibleSignature()` is working as expected. Could you please double check?

**Comment by sbrannen** [comment]
> @sbrannen IIRC `ReflectionUtils.hasCompatibleSignature()` is working as expected. Could you please double check?

Yes, as far as I know `ReflectionUtils.hasCompatibleSignature()` is working expected.

In any case, `ReflectionUtils.hasCompatibleSignature()` is an internal implementation detail that is used to support compatible method sub-signatures when generics are involved.

That method is not intended to support widening conversions like the 2 `isAssignableTo(...)` variants in `ReflectionUtils`.

Phrased differently the supported use case for `findMethod(...)` is when the caller knows the actual signature of the method as defined in the source code.

Thus, widening does not make sense in such use cases. If you know that `SimpleDateFormat.format(Object)` is the declaration in the source code, you would never search for `SimpleDateFormat.format(String)`.

In light of that, I am closing this issue.
