### ISSUE TITLE
Make mismatch reporting less noisy

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#2664]
When running individual test methods via Gradle in IntelliJ IDEA, JUnit logs INFO statements like the following to stderr:

```
Jul 12, 2021 12:37:26 PM org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFO: 1 containers and 1 tests were Method or class mismatch
```

Since those appear in red, they are confusing and somewhat distracting.

## Deliverables

- [ ] Consider using a different log level to support this normal use case better

**Comment by sormuras** [comment]
This and also those keep nagging me way too often when no muting JUL configuration is applied.

```text
Juli 12, 2021 5:41:52 PM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
INFO: Loading JUnit Platform configuration parameters from classpath resource [jar:file:///D:/dev/github/sormuras/bach/.bach/workspace/modules-test/test.projects@17-ea-test.jar!/junit-platform.properties].
Juli 12, 2021 5:41:52 PM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
INFO: Loading JUnit Platform configuration parameters from classpath resource [jar:file:///D:/dev/github/sormuras/bach/.bach/workspace/modules-test/test.projects@17-ea-test.jar!/junit-platform.properties].
Juli 12, 2021 5:41:52 PM org.junit.jupiter.engine.config.EnumConfigurationParameterConverter get
INFO: Using parallel execution mode 'CONCURRENT' set via the 'junit.jupiter.execution.parallel.mode.default' configuration parameter.
```

**Comment by sormuras** [comment]
My quick-and-dirty workaround is: `System.setProperty("java.util.logging.config.file", "DOES-NOT-EXIST");`

But, perhaps, JUnit should only log at `FINE` (`DEBUG`) level. Users that want logging from JUnit (and other libraries) will turn it on via an explicit and customized configuration any way.

**Comment by juliette-derancourt** [comment]
There's also this one:
```
juil. 15, 2021 2:59:11 PM org.junit.jupiter.engine.config.DisplayNameGeneratorParameterConverter logGeneratorClassMessage
INFOS: Using default display name generator 'org.junit.jupiter.api.DisplayNameGenerator$ReplaceUnderscores' set via the 'junit.jupiter.displayname.generator.default' configuration parameter.
```

**Comment by marcphilipp** [comment]
We already use a custom logging façade. Hence, I propose the following change: `DelegatingLogger` would only log if JUL is configured, i.e. if one of the following system properties is set: `java.util.logging.manager`, `java.util.logging.config.class`, or `java.util.logging.config.file`. Otherwise, logs would be dropped.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment]
> `DelegatingLogger` would only log if JUL is configured, i.e. if one of the following system properties is set: `java.util.logging.manager`, `java.util.logging.config.class`, or `java.util.logging.config.file`.

Is that how other logging frameworks like Logback and Log4j integrate with JUL?

**Comment by sormuras** [comment]
Instead of guarding logging by another measure, let's tune down all message emitted at `INFO` level to `DEBUG`.

This change would effect the following six places:
![image](https://user-images.githubusercontent.com/2319838/129538384-a3e9c021-100b-4843-841d-fdb31ac9d4c6.png)
