### ISSUE TITLE
TestExecutionExceptionHandler does not handle/intercept After*Callbacks

### ISSUE THREAD

**Issue by staenker** [junit-team/junit5#2666]
I expect a TestExecutionExceptionHandler to handle exceptions originating from an afterEach/All extension.
2 Reasons:
1. The TestExecutionExceptionHandler is invoked for ParameterResolutionExceptions so it would be inconsistent, to not invoke it for exceptions originating from other extension callbacks
2. I am writing an extension myself. It is working fine, but in order to write a test case, testing my extension, I need to verify that my custom extension is actually throwing an exception. I am using the TestExecutionExceptionHandler to verify that behavior. If there is a better alternative to achieve my goal, I'm happily adjusting my path. Nevertheless, I think 1. still applies here.

## Steps to reproduce
Execute the following test and extension collection:
```kotlin
@ExtendWith(SwallowAllExceptions::class, ResolveParameters::class, FailAfterFailInAfterTestCase::class)
class BugOrFeatureTest {
    @Test
    fun failInTest() { throw TheExceptionToSwallow("TestCase") }

    @Test
    fun failInParameterResolver(theParameter: String) { fail("This should not be executed") }

    @Test
    fun failInAfterEachCallback() { println("Happy go lucky test case without happy ending") }
}

class TheExceptionToSwallow(source: String) : Exception("The exception to swallow from ${source}")

class SwallowAllExceptions : TestExecutionExceptionHandler {
    override fun handleTestExecutionException(ctx: ExtensionContext, t: Throwable) { println("Yum yum ${t.message}") }
}

class ResolveParameters : ParameterResolver {
    override fun supportsParameter(p: ParameterContext, c: ExtensionContext): Boolean { return true }
    override fun resolveParameter(pc: ParameterContext?, c: ExtensionContext?): Any { throw TheExceptionToSwallow("ParameterResolver") }
}

class FailAfterFailInAfterTestCase : AfterEachCallback {
    override fun afterEach(context: ExtensionContext) {
        if (context.testMethod.map { it.name == "failInAfterEachCallback" }.orElse(false)) {
            throw TheExceptionToSwallow("FailAfterFailInAfterEachCallback")
        }
    }
}
```
<img width="1645" alt="grafik" src="https://user-images.githubusercontent.com/1114168/126142713-383df83e-c654-40a1-a0d5-d915fb6ae476.png">

## Expected Behavior
I expect all test cases to pass since the SwallowAllExceptions TestExecutionExceptionHandler is written so that it swallows all exceptions.

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.7.2
 ```
 <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>5.7.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
 ```
 - Build Tool/IDE: Intellij IDEA

## Deliverables
- A pizza, but that one was good and has nothing to do with this bug

**Comment by pietrygamat** [comment]
Your extension can swallow exceptions thrown by a test class in @AfterAll/Each methods if it implements the `org.junit.jupiter.api.extension.LifecycleMethodExecutionExceptionHandler` as an addition to `org.junit.jupiter.api.extension.TestExecutionExceptionHandler` . 

Handling exceptions thrown by Before/After Callbacks though... - Where would it fit this diagram?
https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order-overview. Are we talking about introducing `LifcecycleMethodCallbackExecutionExceptionHandler` ?
:exploding_head:

**Comment by marcphilipp** [comment]
> If there is a better alternative to achieve my goal, I'm happily adjusting my path.

The best way of testing custom extensions is to use the [`EngineTestKit`](https://junit.org/junit5/docs/current/user-guide/#testkit-engine).

We would rather not introduce an extension to handle exception thrown by extensions.

**Comment by bastiat** [comment]
@marcphilipp _We would rather not introduce an extension to handle exception thrown by extensions._
it seems to be my problem:
`
        java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$6(ClassBasedTestDescriptor.java:350)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:355)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$7(ClassBasedTestDescriptor.java:350)`



So I cannot swallow this exception?

Exception is thrown by Spring because Spring cannot  start application context because rabbitmq cannot find a queue. But this is my expected behaviour. I would like to make sure spring rabbitmq doesn't start when it doesn't find a queue. So I wanted to write an extension that would fail if it didn't receive this exception. This exception is expected bahaviour. How can I handle it? Is it possible at all? It seems what I was trying to do was writing an extension that would handle exception thrown by extension. Wasn't I?

**Comment by marcphilipp** [comment]
Instead of using `SpringExtension`, could you instead created an application context in the test method and assert it throws an exception?

**Comment by bastiat** [comment]
Yes, sure. thx for reply. I will do so.

**Comment by sbrannen** [comment]
> Instead of using `SpringExtension`, could you instead created an application context in the test method and assert it throws an exception?

I was going to suggest the same. So, thanks for recommending that, @marcphilipp.

If you're using Spring Boot, see also [ApplicationContextAssert](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/context/assertj/ApplicationContextAssert.html) and related classes in the same package.
