### ISSUE TITLE
[feature request] : Custom Condition test code execute by method

### ISSUE THREAD

**Issue by pasudo123** [junit-team/junit5#2670]
I am studying how to write tests by looking at the [junit5 User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-custom).

For `@EnabledIf`, can you provide a function to dynamically determine true/false as a return value for a method rather than setting a property?

Below is my code (kotlin):

```kotlin
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class Exercise04 {

    private val elements = listOf("apple", "banana")
    private val logger = KotlinLogging.logger {}

    @Test
    @EnabledIf("conditionalElementOnList")
    fun doTestConditionalByAppleString() {
        logger.info { "apple test code exec" }
    }

    @Test
    @EnabledIf("conditionalElementOnList")
    fun doTestConditionalByBananaString() {
        logger.info { "banana test code exec" }
    }

    fun conditionalElementOnList(): Boolean {
        val element = elements.shuffled().first()
        logger.info { "shuffled element : [$element]" }
        return element.startsWith("a")
    }
}
```

Additional code (kotlin):

```kotlin
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class Exercise04 {

    private val logger = KotlinLogging.logger {}

    @Test
    @EnabledIf("conditionalElementOnList")
    fun doTestConditionalByAppleString() {
        logger.info { "apple test code exec" }
    }

    @Test
    @EnabledIf("conditionalElementOnList")
    fun doTestConditionalByBananaString() {
        logger.info { "banana test code exec" }
    }

    companion object {
        private val elements = listOf("apple", "banana")

        @JvmStatic
        fun conditionalElementOnList(): Boolean {
            val element = elements.shuffled().first()
            println ( "shuffled element : [$element]" )
            return element.startsWith("a")
        }
    }
}
```

When I read  issue #1911, it seems that the current function is being provided.

Can you please confirm if I am using it wrong?

**Comment by sbrannen** [comment]
Hi @pasudo123,

Thanks for raising your first issue for JUnit 5.

> Can you please confirm if I am using it wrong?

You are using it correctly.

As stated in the User Guide:

> The method is provided to the annotation via its name, or its fully qualified name if located outside the test class.

The name of the method is supplied as a `String` as you have done.

Java unfortunately does not support providing a method reference via annotation attributes.

In light of that, I am closing this issue.

**Comment by pasudo123** [comment]
> Java unfortunately does not support providing a method reference via annotation attributes.

So, do you know when the feature will be available?

**Comment by marcphilipp** [comment]
@pasudo123 I haven't heard about any plans for Java to add such a feature.

**Comment by pasudo123** [comment]
@marcphilipp 

Yes. Thank you for your confirmation.
