### ISSUE TITLE
@ParametersByName annotation

### ISSUE THREAD

**Issue by prdoyle** [junit-team/junit5#2671]
## Goals

A really low-friction way to provide a set of parameters for a parameterized test.

Also, sometimes it's desirable to get full coverage of all combinations of parameters. For example, try all `Evaluator` implementations with all possible `Expression` objects. The existing parameterization schemes require the user to list all the possible combinations; it would be nice if independent parameters could be injected independently.

## Usage example

I have the following example working in my project and I think it's pretty handy.

The effect is to call the `test` method with every combination of `name` and `number` returned by the static methods.

```
public class MyTest {
	@ParametersByName  // The new annotation
	void test(String name, Integer number) {
		// test goes here
	}

	static Stream<String> name() {
		return Stream.of("Hello", "world");
	}

	static Stream<Integer> number() {
		return Stream.of(123, 456, 789);
	}
}
```

`@ParametersByName` is a variant of `@TestTemplate`:

```
@Target({ ElementType.ANNOTATION_TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@ExtendWith(ParametersByNameContextProvider.class)
@TestTemplate
public @interface ParametersByName {
}
```

`ParametersByNameContextProvider` calls, for each parameter, a static method with the same name. It expects a `Stream` of values. It creates a `TestTemplateInvocationContext` for each combination of parameter values. It looks up the methods using `ReflectionUtils` so it plays nice with inheritance even though the methods are static.

If you agree that this is a good practice, perhaps it could be included in the base JUnit5 distribution.

For Java 8, it current requires the javac flag `-parameters` to include parameter name information in the classfile of the test class. But the annotation could also accept parameter names, like `@ParametersByName({"name","number"})`.

## Deliverables

- [ ] `@ParametersByName` annotation that calls a method for each parameter, and invokes the test template with every combination of parameter values returned by those methods.

**Comment by jbduncan** [comment]
As a JUnit 5 user, this sounds like junit-pioneer's [`@CartesianProductTest`](https://junit-pioneer.org/docs/cartesian-product/) to me, but with the relative simplicity of https://github.com/google/TestParameterInjector for JUnit 4.

I like it! But I think if TestParameterInjector were ported to JUnit 5, it would be a more flexible API overall with hardly any more ceremony.

Regardless, if the JUnit 5 team don't accept this, it sounds like a good candidate for junit-pioneer.

**Comment by prdoyle** [comment]
Thanks for the feedback! My context provider class does have a `cartesianProduct` method inside it. 😄 

I've used this thing for a couple of days now, and it seems to be a little too clever for IntelliJ. If one of the tests fails, it's really awkward to re-run just that test one. 🤔

**Comment by prdoyle** [comment]
@jbduncan - I think you're onto something. I've taken a look at `TestParameter` and there's a lot to like about it. The way they can easily stuff a strongly typed "tuple" of values into an enum is cool. (I might skip the YAML support though.  😄)

I like how easy `@ParametersByName` makes it to specify parameters with `Stream` expressions. I'd want to retain that if I could.

I'm wondering if it would make sense to build a Junit 5 version of `@TestParameter` that has support for something like `@TestParameter(method="methodName")`; then define `@ParametersByName` to be shorthand for configuring all of a method's parameters to be configured by a `@TestParameter(method="x")` for their respective names. 🤔

**Comment by Michael1993** [comment]
Hey, @prdoyle 👋 
Just wanted to let you know that JUnit Pioneer just released 1.6.1 with a revamped `@CartesianTest`. If you are interested, take a look!
We might also implement your idea - it sounds fun.

**Comment by prdoyle** [comment]
@rgseyvie - sorry! I didn't notice your message until now!

**Comment by marcphilipp** [comment]
**Team decision:** This could be implemented as a custom `ArgumentsProvider` or as an enhancement to [JUnit Pioneer's `@CartesianTest` feature](https://junit-pioneer.org/docs/cartesian-product/). Therefore, we don't think this needs to be implemented in JUnit core.
