### ISSUE TITLE
Typesafe mechanism for storing and retrieving extension state

### ISSUE THREAD

**Issue by hakanai** [junit-team/junit5#2673]
When writing extensions, typically I will be storing objects of a particular type.

To put the object in, I will be writing, let's say,

```java
    private final String KEY = "...";
    List<Integer> value = ImmutableList.of(1, 2, 3);
    store.put(KEY, value);
```

To get it back out, I will be writing,

```java
    List<Integer> value = (List<Integer>) store.get(KEY);
```

This issues an unsafe cast warning that I have to suppress.

While the warning is annoying, I don't think it's the thing I want to address. Rather, I wondered whether JUnit has considered that the key can automatically carry the type information wanted for the value.

Consider a design like this:

```java
    public class StoreKey<V> {
        private final String name;
        private final TypeToken<V> valueType;
        private Key(String name, TypeToken<V> valueType) {
            this.name = name;
            this.valueClass = valueClass;
        }
        public static <V> StoreKey<V> of(String name, TypeToken<V> valueType) {
            return StoreKey<>(name, valueType);
        }
        public TypeToken<V> getValueType() {
            return valueType;
        }
        @Override
        public String toString() {
            return name;
        }
    }

    public interface Store {
        // ...
        public <V> void put(Key<V> key, V value);
        public <V> V get(Key<V> key);
    }
```

The `TypeToken` I refer to is a common utility class found in a few other libraries but I'm guessing to reduce dependencies it would be neatest to clone something similar in JUnit. You could of course have overloads taking just Class for the simpler cases.

Putting the values in looks more or less the same, but I'm essentially declaring the type up-front:

```java
    private final String KEY = StoreKey.of("...", new TypeToken<List<Integer>>(){});
    List<Integer> value = ImmutableList.of(1, 2, 3);
    store.put(KEY, value);
```

But to get it back out, now I only have to write:

```java
    List<Integer> value = store.get(KEY);
```

## Deliverables

[ ] ?

**Comment by kcooney** [comment]
This sounds similar to #361 and #996

**Comment by hakanai** [comment]
Indeed. It looks like someone even went to the trouble of implementing it, and then at the last minute it was knocked back by someone who doesn't like type safety.

**Comment by jbduncan** [comment]
@hakanai Did you mean to come across as belligerent just now? :)

I ask because it looks to me that you were being... critical of the lead developer of JUnit 4 and 5, and regardless it came across as rather hurtful.

**Comment by hakanai** [comment]
No, I simply did not realise that the lead developer of JUnit 4 and 5 hated type safety so much.

**Comment by jbduncan** [comment]
I hear you.

That being said, I don't actually see any mention in the thread of why this feature was rejected in the first place. Have I missed it?

Maybe it was very well that the JUnit team didn't like the additional type safety at the time, but that seems unlikely to me. I think the real explanation was that not enough people said they wanted the feature at the time, so the team thought that the complexity the feature would add to the JUnit 5 codebase was not worth it.

JUnit team, what do you think of this feature now?
