### ISSUE TITLE
Support assertDoesNotThrow() with suspending functions in Kotlin

### ISSUE THREAD

**Issue by williamboman** [junit-team/junit5#2674]
Support for suspending functions was added for the `assertThrows()` counterpart (see #1851), but it seems like calling suspending functions in an `assertDoesNotThrow()` block is currently not supported.

## Deliverables

- [ ] Add support for calling suspending functions for all variants of `assertDoesNotThrow()`.

**Comment by sbrannen** [comment]
@williamboman, thanks for raising the issue.

Are you interested in submitting PR for this enhancement?

**Comment by govi20** [comment]
@sbrannen I would like to work on it. I already have a fork and setup, Any suggestions on how should I proceed?

**Comment by williamboman** [comment]
> Are you interested in submitting a PR for this enhancement?

Sure, I'll give it a look!

**Comment by williamboman** [comment]
I've opened a draft PR at #2684 for early review

**Comment by juliette-derancourt** [comment]
@williamboman Thank you for the PR! 👍

**Comment by williamboman** [comment]
Thanks for the reviews! Happy to contribute to this great project 😊
