### ISSUE TITLE
Junit5 testSuite with SelectClasses not working in android unit test

### ISSUE THREAD

**Issue by TheReprator** [junit-team/junit5#2686]
- JUnit5: 5.7.1
- JUnit Platform : 1.7.2
- IDE: Android Studio

I am trying to create a test suite for Unit test of android application, but it always fails with different kinds of configuration error, one among that is as follows,

```
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':appModules:factList:testDebugUnitTest'.
No tests found for given includes: [reprator.wipro.factlist.FactListTestSuite]
(filter.includeTestsMatching)
```
RepoDetails: https://github.com/TheReprator/Wipro/tree/junit5
Branch: junit5

TestSuite Class: https://github.com/TheReprator/Wipro/blob/junit5/appModules/factList/src/test/kotlin/reprator/wipro/factlist/FactListTestSuite.kt

My whole code works perfectly with junit4 in master branch.

**Comment by sormuras** [comment]
Duplicate of https://stackoverflow.com/questions/68750803/junit5-testsuite-with-selectclasses-not-working-in-android-unit-test

**Comment by TheReprator** [comment]
@sormuras Can we have the solution, for above

**Comment by juliette-derancourt** [comment]
@TheReprator Suites are not yet supported in 5.7.1, you still need JUnit 4 for that (see [this paragraph of the user guide](https://junit.org/junit5/docs/current/user-guide/#running-tests-junit-platform-runner-test-suite)).

If you try to add the `junit-vintage` dependency, does it work?

**Comment by TheReprator** [comment]
@juliette-derancourt  yes, i had tried those as well, but didn't worked

**Comment by juliette-derancourt** [comment]
Ah, my bad, I believe that you can only run JUnit 4 **tests** that way, so it won't work if you migrated those tests to use Jupiter (which seems to be the goal of your branch).

I think you will have to wait for the release of 5.8 to use the new suite support (see https://github.com/junit-team/junit5/issues/744), or run your tests in a different way in the meantime.

**Comment by sormuras** [comment]
Already gave https://github.com/mannodermaus/android-junit5 a try?

**Comment by TheReprator** [comment]
@sormuras Yes, i am doing the same

**Comment by TheReprator** [comment]
@juliette-derancourt now from the #744 , i also think, i had to wait for the releaseof 5.8-M1

**Comment by TheReprator** [comment]
finally suite is accomplished with, 

testImplementation("org.junit.platform:junit-platform-suite:1.8.0-RC1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.0-RC1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.0-RC1")

Repo:
https://github.com/TheReprator/Wipro/blob/master/appModules/factList/src/test/kotlin/reprator/wipro/factlist/FactListTestSuite.kt

**Comment by sbrannen** [comment]
Thanks for the feedback, @TheReprator!

Glad that the new `@Suite` engine works for you. 👍
