### ISSUE TITLE
`TestRun` in Vintage omits suppressed exceptions when creating `MultipleFailuresError`

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2693]
# Overview

Thanks to the tip from @DidierLoiseau (see https://github.com/junit-team/junit5/issues/1602#issuecomment-891077168), I have confirmed that the changes made in #1602 should also be applied in `org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestDescriptor)`.

The reason is that `org.junit.internal.runners.model.EachTestNotifier.addMultipleFailureException(MultipleFailureException)` invokes `org.junit.runner.notification.RunNotifier.fireTestFailure(Failure)` for each failure in the supplied `org.junit.runners.model.MultipleFailureException`.

This can happen if you are using the JUnit 4 `ErrorCollector` rule.

## Deliverables

- [ ] Add suppressed exceptions to the `MultipleFailuresError` created in the Vintage `TestRun`.

**Comment by DidierLoiseau** [comment]
Thanks for creating this, I had kept a note for it on the side but it happened to us in some Spring-related test (in MockMVC IIRC) which wasn’t that hard to fix, but providing a simple test case for reporting it seemed harder.

**Comment by DidierLoiseau** [comment]
IIRC it had to do with MockMvc's `ResultAction.andExpect()`, but I might be wrong.

Anyway, thanks for the fix 🙂
