### ISSUE TITLE
Allow `@Nested` test classes to be ordered

### ISSUE THREAD

**Issue by mcanalesmayo** [junit-team/junit5#2699]
When having a `@TestMethodOrder` annotated class, I'd like to not only be able to annotate `@Test` methods, but also be able to define an order on `@Nested` inner classes. This is to avoid having to define an `@Order` on all the tests individually, which makes it harder to maintain.

For example:

```java
@TestMethodOrder(OrderAnnotation.class)
class MyTests {

  @Nested
  @Order(1)
  class MyFirstGroupOfTests {

    @Test
    void testA() {
      ...
    }

    @Test
    void testB() {
      ...
    }

    @Test
    void testC() {
      ...
    }
  }

  @Nested
  @Order(2)
  class MySecondGroupOfTests {

    @Test
    void testD() {
      ...
    }

    @Test
    void testE() {
      ...
    }

    @Test
    void testF() {
      ...
    }
  }

  @Nested
  @Order(3)
  class MyThirdGroupOfTests {

    @Test
    void testH() {
      ...
    }

    @Test
    void testI() {
      ...
    }

    @Test
    void testJ() {
      ...
    }
  }
}
```

**Comment by ledoyen** [comment]
I do not remember if it was a choice or an oversight. It should be fairly simple to add though.
I am currently AFK, but I can take care of this in September if needed.

**Comment by sbrannen** [comment]
Thanks for the feedback, @ledoyen!

Indeed it does appear to be fairly simple.

It looks like we just have to recursively call `AbstractOrderingVisitor.orderChildrenTestDescriptors()`.

I have a spike locally that appears to work, so I'll add some tests and likely put together a PR.

**Comment by sbrannen** [comment]
I've opened PR #2701 to address this issue.

However, after implementing the feature, I realized that users may wish to configure the execution order of `@Nested` test classes locally and declaratively. For example, a new annotation analogous to `@TestMethodOrder` would serve that purpose well.

The annotation could be named `@TestClassOrder` or `@NestedTestClassOrder`.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment]
> The annotation could be named `@TestClassOrder` or `@NestedTestClassOrder`.

`@TestClassOrder` has been added to the PR. See https://github.com/junit-team/junit5/pull/2701#issuecomment-907790976 for details.

**Comment by overheadhunter** [comment]
As a bonus task for an additional 50 points, update this answer: https://stackoverflow.com/a/55482937/4014509 😉

**Comment by sbrannen** [comment]
I hate to disappoint you, but the answer to that SO question actually still remains the same, specifically this point:

> No, we (the JUnit Team) have no plans of mixing the execution order of tests between nested test classes and their enclosing classes, simply because that would violate the entire design principles of nested containers.

With this PR, `@Nested` test classes can be ordered relative to other `@Nested` test classes that have the same enclosing class. `@Nested` test classes will not be ordered relative to `@Test` methods.

**Comment by overheadhunter** [comment]
Fair enough, but at least it solves the problem to run tests in a specific order, of they depend on a certain state. I don't see any problem encapsulating tests in nested classes.

**Comment by sbrannen** [comment]
> Fair enough, but at least it solves the problem to run tests in a specific order, if they depend on a certain state. 

Indeed it does.

> I don't see any problem encapsulating tests in nested classes.

I actually meant to suggest that as a "workaround" for your SO question, so I'm happy you came to the same conclusion. 👍
