### ISSUE TITLE
ParameterizedTest cannot use Kotlin inline value classes as arguments

### ISSUE THREAD

**Issue by alyssum** [junit-team/junit5#2703]
## Steps to reproduce

Expect parameterized tests to be able to use Kotlin's inline classes as arguments.  Test below fails to run and instead get an error when initializing the test:
`Error converting parameter at index 0: No implicit conversion to convert object of type InlineValueClass to type java.lang.String`

```kotlin
@JvmInline
value class InlineValueClass(val value: String)

class InlineTest {
    @ParameterizedTest
    @MethodSource("values")
    fun shouldRun(arg: InlineValueClass) {
        assertEquals(arg, arg)
    }

    fun values() = listOf(
        arguments(InlineValueClass("test"))
    )
}
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Junit 5.0.0 / Kotlin 1.5.20
 - Build Tool/IDE: Gradle / IntelliJ

**Comment by marcphilipp** [comment]
I'm not sure how involved adding support for inline classes would be. @alyssum Would you be interested in spiking a solution?

**Comment by vidhithakrar** [comment]
Unfortunately this is still an issue, isn't it going to be priortized?

**Comment by mustafaberkaymutlu** [comment]
The simple solution I found was to use the value class type in the test function and use the primitive type in the argument provider.

JUnit finds the constructor of the inline class and creates a new version of it by passing the primitive value we specify.

For example:

```kotlin
@JvmInline
value class InlineValueClass(val value: String)

class InlineTest {
    @ParameterizedTest
    @ArgumentsSource(MyArgumentsSource::class)
    fun shouldRun(arg: InlineValueClass) {
        assertEquals(arg, arg)
    }

    class MyArgumentsSource : ArgumentsProvider {
        override fun provideArguments(context: ExtensionContext): Stream<out Arguments> = Stream.of(
            Arguments.of("my value 1"),
            Arguments.of("my value 2"),
        )
    }
}
```

It also works with nullable types:
```kotlin
@JvmInline
value class InlineValueClass(val value: String)

class InlineTest {
    @ParameterizedTest
    @ArgumentsSource(MyArgumentsSource::class)
    fun shouldRun(arg: InlineValueClass?) {
        assertNull(arg)
    }

    class MyArgumentsSource : ArgumentsProvider {
        override fun provideArguments(context: ExtensionContext): Stream<out Arguments> = Stream.of(
            Arguments.of(null),
            Arguments.of(null),
        )
    }
}
```
