### ISSUE TITLE
Change to scope of API Guardian dependency breaks builds with custom Gradle `Configuration`

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2705]
## Overview

The change in c5ee49d1347bdab01b7e72d6aa61a0e3c1a9065b breaks existing Gradle builds.

For example, the Spring Framework is using Gradle 6.8.3, and when the build is upgraded to JUnit 5.8 snapshots the build fails with numerous errors similar to the following.

```
> Task :spring-test:compileJava FAILED
/Users/sbrannen/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.8.0-SNAPSHOT/617bb4ea90ad07de26681dd57932575b534ec15e/junit-jupiter-api-5.8.0-SNAPSHOT.jar(org/junit/jupiter/api/extension/ExtendWith.class): warning: Cannot find annotation method 'status()' in type 'API': class file for org.apiguardian.api.API not found
warning: unknown enum constant Status.STABLE
  reason: class file for org.apiguardian.api.API$Status not found
```

## Workaround

Adding `compileOnly("org.apiguardian:apiguardian-api")` to `spring-test` allows the `spring-test` module to build.

## Deliverables

- [ ] Document as a potentially breaking change in the release notes.

**Comment by sbrannen** [comment]
The Maven POM for `junit-jupiter-api` for the [latest snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/junit/jupiter/junit-jupiter-api/5.8.0-SNAPSHOT/junit-jupiter-api-5.8.0-20210902.134413-315.pom) contains the following.

```xml
<dependency>
    <groupId>org.apiguardian</groupId>
    <artifactId>apiguardian-api</artifactId>
    <version>1.1.2</version>
    <scope>compile</scope>
</dependency>
```

So it looks like the change doesn't affect Maven builds.

**Comment by sbrannen** [comment]
By comparing the Gradle module files -- for example `junit-jupiter-api-5.8.0-M1.module` vs `junit-jupiter-api-5.8.0-20210902.134413-315.module` -- we see that the `apiguardian-api` dependency moved from `runtimeElements` to `apiElements`.

Note that the `spring-test` module declares its dependencies on JUnit Jupiter as follows.

```groovy
optional("org.junit.jupiter:junit-jupiter-api")
```

From the documentation of Spring Framework's [OptionalDependenciesPlugin](https://github.com/spring-projects/spring-framework/blob/main/buildSrc/src/main/java/org/springframework/build/optional/OptionalDependenciesPlugin.java):

> The `optional` configuration is part of the project's compile and runtime classpaths but does not affect the classpath of dependent projects.

/cc @bclozel, @wilkinsona

**Comment by wilkinsona** [comment]
We might need to configure some attributes on the `optional` configuration so that it consumes from `apiElements`.

**Comment by sbrannen** [comment]
FYI: Spring Framework's `optional` configuration has been updated to properly work with `apiElements` in https://github.com/spring-projects/spring-framework/pull/27365.

In light of that, we may consider this a necessary enhancement to Spring's build instead of a bug in JUnit.

However, other projects out there might run into similar issues with custom dependency configuration. So I'll leave this issue open for team discussion before releasing 5.8 GA.

**Comment by sormuras** [comment]
An interesting developement of the topic and I agree that other projects. if affected, should enhance/correct their dependency management. In order to support people fixing their broken builds, we should add a note to the changes list and point to this issue, or perhaps a dedicated (wiki) help page.

**Comment by sbrannen** [comment]
> In order to support people fixing their broken builds, we should add a note to the changes list and point to this issue, or perhaps a dedicated (wiki) help page.

At the very least, I think we should add a "Breaking Change" entry to "general" section of the release notes that briefly describes the issue and provides guidance on how to approach it. The use of custom `Configuration` in Gradle like `optional` in Spring Framework is a rather advanced feature, and most projects won't run into the issue.

As for whether or not we need a dedicated Wiki page, I'd rather hold off on that to see how many projects in the community run into any issues.

**Comment by marcphilipp** [comment]
**Team decision:** Document as a potentially breaking change in the release notes.

**Comment by timja** [comment]
I hit this as well, the linked commit wasn't useful for a gradle project rather than plugin, I got it working with this:
https://github.com/hmcts/spring-boot-template/pull/338

By adding a configuration and extending from the `testImplementation` in it. The gradle guides seemed to extend from `implementation` but that wasn't very useful.

This guide is what I used in the end to fix it: https://www.baeldung.com/gradle-source-sets
