### ISSUE TITLE
`autoCloseArguments` support in `@ParameterizedTest` breaks existing tests

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2706]
## Overview

Having `autoCloseArguments` default to `true` is a breaking change for arguments that are shared between parameterized test invocations.

In the Spring Framework test suite, we have three `@ParameterizedTest` methods (in `PathMatchingUrlHandlerMappingTests` and `ClientHttpConnectorTests`) that hang indefinitely while running against JUnit 5.8 snapshots.

Declaring `@ParameterizedTest(autoCloseArguments = false)` solves the problem, but this is technically a regression and, more importantly, the average user will not even know where to begin debugging such failures.

## Deliverables

Document that `autoCloseArguments` in `@ParameterizedTest` is a potentially breaking change in:

- [x] Javadoc
- [x] Release Notes
- [x] User Guide

**Comment by marcphilipp** [comment]
**Team decision:** Add a note to the release notes
