### ISSUE TITLE
Introduce a mechanism for associating multiple TestSources with a single test

### ISSUE THREAD

**Issue by signed** [junit-team/junit5#271]
With cucumber you have a feature file with the scenario definition and a Java class that implements the steps used in the scenario. If a scenario run fails and I have the test tree in my IDE I like to have the choice to navigate either to the feature file or the implementation of the failing step.

How would an implementation of TestSource look like to support this?

**Comment by marcphilipp** [comment]
Thanks for raising this issue!

I see two possibilities:

1. Provide a `TestSource` implementation that represents multiple sources, e.g. a class `MultiSource` that contains a list of test sources.
2. Replace `TestIdentifier#getSource` and `TestDescriptor#getSource` with `getSources() : List<TestSource>`.

@signed @junit-team/junit-lambda Which one would you prefer?

**Comment by sbrannen** [comment]
I would prefer the first option, and I would suggest introducing a `CompositeTestSource` that is a direct subinterface of `TestSource` with a `List<TestSource> getSources()` method.

**Comment by sbrannen** [comment]
FYI: I have renamed this issue.

**Comment by mmerdes** [comment]
I would prefer the classic composite pattern as well

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, please review PR #274.

**Comment by sbrannen** [comment]
No longer _in progress_: awaiting team feedback.

**Comment by signed** [comment]
I know too little about the consumers of the API to have a preference. As long as it is possible its fine with me.

**Comment by sbrannen** [comment]
Merged into `master` in 798beef089df5368a335d541140adbf79f665046.
