### ISSUE TITLE
Support for more specific and more general OS categories in DisabledOnOs/EnabledOnOs

### ISSUE THREAD

**Issue by hakanai** [junit-team/junit5#2713]
We have many tests where we're doing this:

```java
assumeThat(OperatingSystem.getCurrent().isUnix(), is(true));
```

Or,

```java
assumeThat(OperatingSystem.getCurrent().isLinux(), is(true));
```

Or,

```java
assumeThat(OperatingSystem.getCurrent().isCentos(), is(true));
```

Out of these three, one of the three can be replaced by `@EnabledOnOs`, but the other two cannot.

It would be nice if I could cover all UNIXy flavours with

```java
@EnabledOnOs(OS.UNIX)
```

and just one Linux distro with

```java
@EnabledOnOs(OS.CENTOS)
```

but obviously there are a ton of distros so that may not be the most suitable API. In the meantime I will probably leave these using `assumeThat` unless I make my own annotation.

I hit a similar thing with Mac classic vs. macOS or Windows vs. WindowsNT but I figured we won't be seeing classic or non-NT Windows anymore so I was happy to assume that all Windows is WindowsNT. ;)

## Deliverables

- [ ] ...

**Comment by marcphilipp** [comment]
The first one could probably be emulated by `@EnabledOnOs({OS.LINUX, OS.MAC})` (disregarding AIX, Solaris, and others) so only the third one is problematic. I don't see us adding support for individual distros but you could create your own `ExecutionCondition` extension with an accompanying annotation.
