### ISSUE TITLE
Streaming discovery of tests and containers

### ISSUE THREAD

**Issue by papegaaij** [junit-team/junit5#2714]
The current `LauncherDiscoveryRequest` only supports discovery using fixed selectors, like selecting on a class. The maven-surefire-plugin, when using a `forkCount > 1`, streams the classes to be tested to the forks one by one. Using the current API, this can only be implemented by creating a `LauncherDiscoveryRequest` for every class, executing that request and fetching the next class. This has the unwanted side effect that extensions like the Arquillian extension initialize and tear down the entire runtime for every class to be executed. This introduces a significant overhead in running these tests.

The Arquillian extension registers its integration in the `Store` of the root `ExecutionContext`. When selecting multiple classes at once, these classes will all share this root context. However, when a new `LauncherDiscoveryRequest` is executed separately for every class, the root will be a new one for every test class.

The problematic code in surefire can be found in [JUnitPlatformProvider.execute](https://github.com/apache/maven-surefire/blob/master/surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java#L177). The then branch of the if works fine, however in the else branch, when the test classes are streamed (and cannot be fetched eagerly), the recreation of the request creates the problem. A corresponding ticket is also filed at [SUREFIRE-1935](https://issues.apache.org/jira/browse/SUREFIRE-1935), but it seems this cannot be fixed without support in JUnit Platform.

**Comment by marcphilipp** [comment]
As [you've already discovered](https://lists.apache.org/thread.html/rbf1dff6f955c3976faf1e785a65d3278582892d8325bc2187df306dc%40%3Cdev.maven.apache.org%3E), 5.8 introduces `LauncherSessionListener` for this purpose.

**Comment by Tibor17** [comment]
Is `LauncherSessionListener` a hack in surefire?
I guess it is because we have to force the junit to launch the fixture methods without a control of the junit5 engine/launcher.
So it is a workaround.

`LauncherSession` helps but it is not a fix of the underlying problem.
On the other hand the stream would be juicy feature for scriptable languages and load balancers.

**Comment by papegaaij** [comment]
As far as I understand the LauncherSession, it's more of an additional lifecycle event. Maintainers of JUnit extensions and users of the framework will have to implement LauncherSessionListeners. When surefire opens and closes the session, these will get called. This does provide pre and post fixtures, but it still results in a different TestPlan when executing tests one by one. Also, I think it will take a very long time before all existing extensions are updated to the new listener.

Looking at the code, it seems JUnit can already handle a lazy stream of tests in the form of dynamic tests. It would be great if this could somehow be exposed to the launcher.

**Comment by marcphilipp** [comment]
@papegaaij Were you able to leverage `LauncherSessionListener` for the Arquillian use case?

**Comment by papegaaij** [comment]
@marcphilipp yes, you can find the result here: https://github.com/topicusonderwijs/arquillian-testrunner-spock/blob/spock-2.0-junit5/core/src/main/java/org/jboss/arquillian/spock/ArquillianSetupAndTeardownSessionListener.java . Surefire also supports these sessions now and for our usecase it's working great.

**Comment by marcphilipp** [comment]
Thanks for the feedback! Closing this issue in the light of that.
