### ISSUE TITLE
Overhaul exception handling in MethodFinder

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#272]
## Status Quo

`org.junit.gen5.engine.junit5.discovery.MethodFinder` currently explicitly throws a `RuntimeException` if a named class cannot be loaded and swallows an `IndexOutOfBoundsException` if the supplied method specification does not follow the required format.

## Deliverables

- [x] Ensure that `MethodFinder` only throws instances of `JUnitException` as required by our coding guidelines.

**Comment by sbrannen** [comment]
_in progress_

**Comment by mmerdes** [comment]
thanks for keeping an eye on this detail
