### ISSUE TITLE
Deprecate `@UseTechnicalNames`

### ISSUE THREAD

**Issue by mpkorstanje** [junit-team/junit5#2720]
With the deprecation of the JUnitPlatform runner in favor of `@Suite` support (https://github.com/junit-team/junit5/commit/8ac3dfbc5fbef433a98684a4ca958fad91c1f0f4) `UseTechnicalNames` should also be deprecated.

In brief using `@UseTechnicalNames` would instruct the JUnitPlatform runner to use class and/or method names in JUnit4 test descriptions [using the information contained in the Junit5 TestIndentifiers](https://github.com/junit-team/junit5/blob/43638eb6a870e0d6c49224053dfeb39dcf0ef33f/junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatformTestTree.java#L111-L130).

Reasons for deprecation:

1. I do not see a usecase where other implementations that use the `junit-platform-suite-api` would benefit from UseTechnicalNames.
2. UseTechnicalNames is specific to to the Junit Platform runner and should not have been included in the suite-api.
3. The JUnit Platform Suite Engine provides `TestIndentifiers` as part of the JUnit Platform. Users of the JUnit Platform can reconstruct the technical names in the same way the JUnitPlatform runner did.

**Comment by marcphilipp** [comment]
**Team decision:** Deprecate `UseTechnicalNames` since it no longer has any effect (when not using the `JUnitPlatform` runner).

**Comment by StepanTuchin98** [comment]
Hi!
I have found the case, where I need to have technical names instead DisplayName.

The team's Developers copy pasted DisplayName, so multiple tests have the same Name and ClassName.
From my point, I need to get all the info from the report like:
ClassName#TestName -> time of execution

As for now, the testcases have the same names, that's my metric is not clear.

Is there a way to say Junit5 to use Method Name instead DisplayName?

**Comment by mpkorstanje** [comment]
You may want to create a new issue to discuss your proposal. To deal with the large amount of issues and feature requests efficiently and notifications the JUnit team has a workflow.  

When you create a new issue the template will promt you to explain your problem. Bear in mind that in your proposal you'll have to explain why you can't fix your duplicate display names.
