### ISSUE TITLE
Separate the assertion utility API from the test framework API

### ISSUE THREAD

**Issue by hakanai** [junit-team/junit5#2725]
We use exclusively Hamcrest assertions but occasionally someone will discover that JUnit has its own assertion library and put a call to that into the code.

While it is entirely possible to use tools like [Forbidden APIs](https://github.com/policeman-tools/forbidden-apis) to prevent this malpractice, it would be much simpler if JUnit simply had its assertions in a different library to the rest of the API.

It's fine for projects to like the JUnit style of assertions, and those projects can import that assertion library. But having it around on the classpath is damaging for the rest of us who have different preferences.

**Comment by marcphilipp** [comment]
**Team decision:** Thanks for reaching out but we believe some core assertions are integral to using Jupiter and have therefore decided to not separate these two APIs.

**Comment by hakanai** [comment]
I wonder if that's true. We at least seem to be surviving 100% on Hamcrest at this point in time.

I guess we just have to use forbidden-apis or similar to stop people using the JUnit ones.
