### ISSUE TITLE
Fix seed property name documentation for ClassOrderer.Random

### ISSUE THREAD

**Issue by bnorb** [junit-team/junit5#2731]
Version: JUnit 5.8.1

In the class description, the `ClassOrderer.Random` documentation states that the "junit.jupiter.execution.<ins>class</ins>.order.random.seed" configuration parameter should be used to set the custom seed. 

The actual value of `RANDOM_SEED_PROPERTY_NAME` is equal to `MethodOrderer.Random.RANDOM_SEED_PROPERTY_NAME` however, which is `junit.jupiter.execution.order.random.seed`. This is documented correctly in the field description.

## Deliverables

- [ ] Change `junit.jupiter.execution.class.order.random.seed` in class description to `junit.jupiter.execution.order.random.seed`.

**Comment by sbrannen** [comment]
Good catch! 👍 

I'll fix that right away.

**Comment by sbrannen** [comment]
@bnorb, thanks for reporting your first issue for JUnit 5!

This has been addressed in commit fd93eeca94479b71ce0d06d61df874a167a3fbf7.
