### ISSUE TITLE
Missing symmetric extension for TestInstancePreDestroyCallback (TestInstancePreCreateCallback?)

### ISSUE THREAD

**Issue by dweiss** [junit-team/junit5#2733]
Ok, so this may sound weird but I actually do have a need for a hook that is invoked prior to test instances being created (before the test instance factory or the default machinery actually creates the test instance). This would be a symmetric counterpart to the TestInstancePreDestroyCallback extension, which seems to be missing now.

The reason for this is that I have a custom parameter resolver which takes into account the context of when it's injected. So, essentially, it'd change value when it's injected during:

- class initialization level (static initializer) and beforeall hooks
- before instance constructor (or factory),
- beforeeach hooks
- test methods
- aftereach hooks
- afterall hooks

I can intercept nearly all of the above using JUnit5 extensions except for the moment prior to when new instances are created (constructor call).

A longer explanation is that I'm looking at moving the randomizedtesting framework (https://github.com/randomizedtesting/randomizedtesting) to JUnit5. I desperately try to avoid writing a custom test engine (so that I don't have to reimplement all of jupiter's extensions, etc.) but some of the new infrastructure doesn't cover the required needs. The parameter resolver above injects the randomization seed and this should be hierarchical. 

I peeked at the code and it seems like this should be fairly easy to implement in ClassBasedTestDescriptor - much like the current  pre-destroy callback is implemented (or the instance post-processor). Would this be something you consider acceptable if I provided a patch?

**Comment by dweiss** [comment]
Apologies for asking but I'm a bit baffled - just added throw new RuntimeException() to one of the existing tests and I can't get the build to fail... it's as onlyIf is set to false somewhere but I can't find it:
{code}
> git log -1 --one-line
commit 7a79a3ef0ccd0ab2201674298e9e52ec570d377f (HEAD -> main, origin/main, origin/HEAD)
Author: Sam Brannen <sbrannen@vmware.com>
Date:   Wed Sep 29 10:43:18 2021 +0200

> ./gradlew cleanTest test --console=plain -p junit-jupiter-engine --info
...
> Task :junit-jupiter-engine:test SKIPPED
Skipping task ':junit-jupiter-engine:test' as task onlyIf is false.
:junit-jupiter-engine:test (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 0.0 secs.
...
{code}

There's obviously something I'm missing but I don't know what it is or where to look. Weird.

**Comment by sbrannen** [comment]
> Apologies for asking but I'm a bit baffled - just added throw new RuntimeException() to one of the existing tests and I can't get the build to fail... it's as onlyIf is set to false somewhere but I can't find it:

What exactly are you trying to achieve?

In which module did you modify a test to fail?

What is the result of the Gradle build scan?

Have you tried running with `./gradlew --rerun-tasks test`?

**Comment by dweiss** [comment]
> What exactly are you trying to achieve?

I wanted to implement that extension and added a test. But the test doesn't run. Then I modified another (existing) test - doesn't run either. 

> In which module did you modify a test to fail?

Plain git checkout at de699420216459dd:
gradlew -p junit-jupiter-engine test --rerun-tasks --console=plain

this shows:

```
> Task :junit-jupiter-engine:compileTestJava
> Task :junit-jupiter-engine:compileTestGroovy
> Task :junit-jupiter-engine:testClasses
> Task :junit-jupiter-engine:test SKIPPED

BUILD SUCCESSFUL in 44s
67 actionable tasks: 67 executed
```

Clearly something is wrong... But I've no idea what.

**Comment by dweiss** [comment]
This is the build scan:
https://gradle.com/s/giadc4v5jrxlw

**Comment by sbrannen** [comment]
`-p` sets a project property.

So, it looks like what you're trying to do is `./gradlew :junit-jupiter-engine:test`.

You can use `--rerun-tasks` if you really want to make sure that tasks are rerun and not loaded from the cache.

See also: https://github.com/junit-team/junit5#building-from-source

**Comment by dweiss** [comment]
On Fri, Oct 1, 2021, 21:21 Sam Brannen ***@***.***> wrote:

> -p sets a project property.
>
Large P does it. Small p is a subdirectory directive that narrows tasks. I
am not new to Gradle, it is not the source of the problem.

So, it looks like what you're trying to do is ./gradlew
> :junit-jupiter-engine:test.
>
> You can use --rerun-tasks if you really want to make sure that tasks are
> rerun and not loaded from the cache.
>
I know. But it still doesn't work - see the build scan I posted. This is
with rerun tasks and tests still show as skipped.

See also: https://github.com/junit-team/junit5#building-from-source
>
I will try on a different machine later. I saw the same behavior on some of
the ci jobs you guys have, which is even more confusing.

**Comment by jbduncan** [comment]
@dweiss In my relatively inexperienced view, it sounds like the build cache is preventing the task from being re-run? What happens if you disable it with the command-line flag `--no-build-cache`?

**Comment by jbduncan** [comment]
Ah, I've just seen the `SKIPPED` in your Gradle logs, which suggests the build cache isn't involved. You can try my suggestion, but I don't know if it'll have any impact.

**Comment by dweiss** [comment]
I had tried several options prior to the build cache - same result, the task always seems to have onlyIf set to false. I'll get to the bottom of this - I just thought I needed some kind of magic switch or environment setup... It is even more weird because I run tons of gradle projects and never saw anything like this. I tend to believe it's one of the plugins playing tricks and disabling tests for some reason but why - I've no idea.

**Comment by sbrannen** [comment]
When I execute `./gradlew -p junit-jupiter-engine test --rerun-tasks --console=plain`, I also see that the tests are skipped.

```
> Task :junit-jupiter-engine:compileTestKotlin
w: Language version 1.3 is deprecated and its support will be removed in a future version of Kotlin

> Task :junit-jupiter-engine:compileTestJava
> Task :junit-jupiter-engine:compileTestGroovy
> Task :junit-jupiter-engine:testClasses
> Task :junit-jupiter-engine:test SKIPPED

BUILD SUCCESSFUL in 1m 25s
67 actionable tasks: 67 executed
```

When I execute `./gradlew :junit-jupiter-engine:test --console=plain`, I also see that the tests are skipped.

So, you're right.

Something is wrong!

It appears that ALL tests are SKIPPED across the JUnit 5 repository.

@marcphilipp, could this be because of your recent build refactorings?

**Comment by sbrannen** [comment]
### Update

All tests are `SKIPPED` since commit 826088ec6a3b602e0717505233aad9f33205aecc.

I'll create an issue to track this and disable Jacoco support for the time being, so that tests are executed within the build.

**Comment by sbrannen** [comment]
@dweiss, please pull from `main` and see if tests execute properly for you.

Thanks!

**Comment by dweiss** [comment]
Ha! :) Thank you for looking at this. For a bit I thought I was going crazy. I'll take another look at that patch next week so I'm sure tests will be handy. :)

**Comment by sbrannen** [comment]
> Ha! :) Thank you for looking at this. 

You're welcome.

> For a bit I thought I was going crazy. 

For a bit I thought you might be crazy, too. 😉 

I couldn't imagine that a failing test wouldn't fail the build, because that's never happened.

But you were persistent, and we're grateful for that! 👍 

If you hadn't convinced me to investigate it, I would not have made the following change to my last commit... which would _eventually_ have broken the build.

https://github.com/junit-team/junit5/commit/f1cbfbe14a97ff2a3cfa77df48432b180fed83a5#diff-0e90d7805308542bd4864f165cb7fe13c101be5f7f95b5c19a7e4a0cb86e412eR118

Cheers

**Comment by dweiss** [comment]
> For a bit I thought you might be crazy, too. 😉

Yeah, well. It's still a subject of a heated debate among my children, especially when I ask them to go cycling with me.

Thanks for fixing this, tricky indeed. I'll can go back and try adding that callback later this week.

**Comment by marcphilipp** [comment]
@dweiss Any updates?

**Comment by dweiss** [comment]
I haven't had the time, I'm sorry. Preemptive scheduling. I do have this on the list of things to do and I will return to it - it's not a stale issue (if you have spare cycles and wish to take over - please do).

**Comment by dweiss** [comment]
Is there anybody working with the codebase using IntelliJ Idea? Module inter-dependencies don't really want to import properly.

![image](https://user-images.githubusercontent.com/199470/140044056-d2e20113-5746-4433-8e84-7d6994bf113f.png)

**Comment by marcphilipp** [comment]
I'm using IDEA as well. Have you configured the Gradle JVM to be JDK 17?

**Comment by dweiss** [comment]
Yes, I did. And I tried a few times from scratch too. Something is completely crazy with the way the module dependency configuration got resolved (it passes but the result is strange). I'll keep digging (and if not, good old Eclipse worked for me).

**Comment by sormuras** [comment]
Which version of IDEA do you use?

Works for me with:

```
IntelliJ IDEA 2021.3 Beta (Community Edition)
Build #IC-213.5605.12, built on November 3, 2021
Runtime version: 11.0.13+7-b1751.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
```

**Comment by dweiss** [comment]
I imported the project on another machine without problems. Go figure.

**Comment by dweiss** [comment]
Filed #2770 with the suggested code.

**Comment by dweiss** [comment]
Hi @marcphilipp. Is there anything else needed do be done here? Let me know, thanks.

**Comment by marcphilipp** [comment]
@dweiss No, everything was fine, it was just stuck in my review queue. Thanks for your contribution! 👍
