### ISSUE TITLE
All tests in Gradle build are SKIPPED

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2736]
## Overview

As mentioned in https://github.com/junit-team/junit5/issues/2733#issuecomment-932747744, all tests in the Gradle build are `SKIPPED` since commit 826088ec6a3b602e0717505233aad9f33205aecc.

I will disable Jacoco support for the time being, so that tests are executed within the build.

## Deliverables

- [ ] Determine why all `test` tasks are `SKIPPED` when the Jacoco support is enabled.
- [ ] Fix the issue and reinstate Jacoco support.

**Comment by sbrannen** [comment]
As a result of reverting that commit, the CI build now fails:

https://ge.junit.org/s/gsap7dr2zgivw/failure#1

```
Could not create task ':jacocoRootReport'.
> Task with name 'extractJar' not found in project ':junit-platform-commons'.
```

But at least the tests are executed in the interim.

**Comment by marcphilipp** [comment]
Mea culpa. I have a fix and will push it later.

**Comment by sbrannen** [comment]
Thanks for the quick turnaround, @marcphilipp. 👍
