### ISSUE TITLE
Introduce iterationSelector DiscoverySelector to JUnit Platform

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#2738]
## Motivation

With this [commit](https://github.com/spockframework/spock/commit/90427874f5ccde29be8cfb35c0f3450244bd8dd1) Spock got the capability to select individual iterations via their `UniqueId`. This works great for re-running a test from the IDE, but it doesn't work well if you don't have a prior run to obtain the `UniqueId` as we don't want external tools to create these IDs themselves.

![Spock_Run_Iteration](https://user-images.githubusercontent.com/1151511/135996162-01fbdb61-452a-4668-8766-93c0ae2ad140.png)

## Possible Solution

`DiscoverySelectors.iterationSelector(MethodSelector method, int... iterationIndices)`

This would re-use the existing `MethodSelector` to select the method and accept a varargs of indices to select which iterations to run.

## Deliverables

- [ ] Add a `DiscoverySelectors.iterationSelector(...)`

**Comment by marcphilipp** [comment]
Follow-up issue: #2920
