### ISSUE TITLE
Add documentation for dynamic tests

### ISSUE THREAD

**Issue by mmerdes** [junit-team/junit5#275]
- [x] Document _dynamic test_ support in the User Guide.
- [x] Review/augment Javadoc for _dynamic test_ support.
  - [x] `DynamicTest`
  - [x] `@TestFactory`

Completes #58

**Comment by mmerdes** [comment]
@junit-team/junit-lambda
We agreed that AsciiDoc documentation can be done in master without a PR, didn't we?

**Comment by marcphilipp** [comment]
Sure! :)

**Comment by marcphilipp** [comment]
@mmerdes Please also use static imports for `assertEquals` etc. in `DynamicTestGenerationTests`.

**Comment by mmerdes** [comment]
'in progress'

**Comment by sbrannen** [comment]
FYI: I've updated the deliverables for this issue to reflect the status quo.

**Comment by sbrannen** [comment]
I am closing this issue since all deliverables have been pushed to `master`.

If anyone discovers something that is missing, feel free to reopen this issue.
