### ISSUE TITLE
Allow EnumSource to provide arguments

### ISSUE THREAD

**Issue by hjohn** [junit-team/junit5#2760]
I think `EnumSource` is one of the best tools currently available for parameterized tests, being type safe and using the name of the enum to describe the test data, for example:

```java
    enum DataSet {
       SMALL(Set.of("a", "b", "c"), 3),
       LARGE( ... , 3000),
       EMPTY(Set.of(), 0);

       private Set<String> set;
       private int expectedCount;

       DataSet(Set<String> set, int expectedCount) {
           this.set = set;
           this.expectedCount= expectedCount;
       }

       public Set<String> getSet() {
           return set;
       }

       public int getExpectedCount() { 
           return expectedCount;
       }
    }
```

However, I think the `@ParameterizedTest` itself could be invoked a bit nicer.  Instead of having:

```java
     @ParameterizedTest
     @EnumSource(DataSet.class)
     void shouldHaveExpectedCount(DataSet dataSet) {
          assertEquals(dataSet.getExpectedCount(), dataSet.getSet().size());
     }
```

...it would be much nicer if one could write:

```java
     @ParameterizedTest
     @EnumSource(DataSet.class)
     void shouldHaveExpectedCount(Set<String> set, int expectedCount) {
          assertEquals(expectedCount, set.size());
     }
```

In other words, the parameter names should be examined (`set` and `expectedCount`), and be checked to see if they have matching getters in the given `EnumSource`.  If so, then provide those parameters directly.

**Comment by marcphilipp** [comment]
A similar case could be made for Java records.

**Comment by dogayalcin** [comment]
Hi, can I try this?

**Comment by sormuras** [comment]
Java records do always provide names (of their components) at runtime. However, method parameter names require a specific `javac` configuration in order to be persisted into their class files and only then they are available at runtime.

Thus "parameter names should be examined (`set` and `expectedCount`)" is not guaranteed to work.

Perhaps https://github.com/openjdk/amber-docs/blob/master/eg-drafts/deconstruction-patterns-records-and-classes.md might help this case. In the future...

**Comment by hjohn** [comment]
Even though this may not always work, a prerequisite can simply be that parameter name information must be available in order for this to work.  This can be documented.  In at least the projects I work on professionally, this is practically always on already to help Spring and Jackson do their things (the information can also be gleaned from debug info).

**Comment by marcphilipp** [comment]
**Team decision:** We want to avoid introducing unnecessary complexity that would only make tests more brittle and hence don't think this should be implemented.
