### ISSUE TITLE
Introduce MATCHES_NONE selection mode in @EnumSource

### ISSUE THREAD

**Issue by hjohn** [junit-team/junit5#2761]
I would like to exclude constants using a regex but found that although you can exclude by name, you can't exclude by regex.

Negating a regular expression is rather cumbersome and unreadable (something like this: `^((?!foo).)*$`).

I propose to extend the `EnumSource.Mode` with `MATCHES_NONE`:

```java
enum Mode {
	INCLUDE_NAMES((name, names) -> names.contains(name)),
	EXCLUDE_NAMES((name, names) -> !names.contains(name)),
	MATCHES_ALL((name, expressions) -> expressions.stream().allMatch(name::matches)),
	MATCHES_ANY((name, expressions) -> expressions.stream().anyMatch(name::matches)),
	MATCHES_NONE((name, expressions) -> expressions.stream().noneMatch(name::matches));
    }
```

**Comment by marcphilipp** [comment]
Makes sense to me. Would you be interested in submitting a PR that adds this?

**Comment by npathai** [comment]
@marcphilipp I can take a dig at it.

**Comment by npathai** [comment]
@marcphilipp Thanks. I have started the work on this.
