### ISSUE TITLE
Overview of shadowed dependencies in standalone JAR

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2772]
The `META-INF/MANIFEST.MF` file stored in `junit-platform-console-standalone` artifact includes following lines:

```text
Manifest-Version: 1.0
...
Engine-Version-junit-jupiter: 5.8.1
Engine-Version-junit-vintage: 5.8.1
Implementation-Title: junit-platform-console-standalone
Implementation-Version: 1.8.1
...
```

However, there's no information which other artifacts are shadowed "as-is" (without renaming their packages) into this standalone (uber) JAR.

Let's generate an overview of all those artifacts and include it as `META-INF/shadowed-artifacts`:
```
...
junit:junit:4.13.2
org.hamcrest:hamcrest-core:2.2
...
org.junit.jupiter:junit-jupiter:5.8.1
org.junit.jupiter:junit-jupiter-api:5.8.1
org.junit.jupiter:junit-jupiter-engine:5.8.1
org.junit.jupiter:junit-jupiter-params:5.8.1
org.junit.platform:junit-platfom-commons:1.8.1
org.junit.platform:junit-platfom-console:1.8.1
...
org.junit.vintage:junit-vintage-engine:5.8.1
...
```

Perhaps, that listing should also be included in the User Guide under https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

**Comment by marcphilipp** [comment]
**Team decision:** Document list of all included artifacts in user guide.

**Comment by sormuras** [comment]
Creating the standalone JAR was successful: https://oss.sonatype.org/content/repositories/snapshots/org/junit/platform/junit-platform-console-standalone/1.9.0-SNAPSHOT/ -- however it doesn't seem to contain the generated `META-INF/shadowed-artifacts` file.

Also generating and publishing the snapshot version of the User Guide failed:  https://ge.junit.org/s/xepk3smp7cuww/failure#1

**Comment by sormuras** [comment]
Here it _lists_! ✅

https://junit.org/junit5/docs/snapshot/user-guide/#running-tests-console-launcher
