### ISSUE TITLE
apiguardian-api version mismatch between source code and published POM

### ISSUE THREAD

**Issue by e-ts** [junit-team/junit5#2775]
Hello friends, I found something interesting that I couldn't find an explanation for. I wish someone more experienced with the code would take a look at it and try to figure out why.

The POM on Central for junit-jupiter-api:5.7.2 depends on apiguardian-api:1.1.0 while the source code on tag r5.7.2 declares version 1.1.1.

https://search.maven.org/artifact/org.junit.jupiter/junit-jupiter-api/5.7.2/jar
https://github.com/junit-team/junit5/blob/r5.7.2/gradle/libs.versions.toml

Maybe the version gets overridden by some other transitive dependency? If the version number declared in libs.version would be important, it might be a problem that the published POM doesn't follow it.

Thank you for your attention to this issue and for your other contributions to this extremely useful project.

**Comment by sbrannen** [comment]
Good catch.

I'm not sure why that's the case, but it seems to have been _fixed_ before 5.8.0 M1.

Perhaps @marcphilipp can provide further information.

**Comment by marcphilipp** [comment]
It appears the `r5.7.2` tag was pointing to the wrong commit. Fortunately, I still had the correct tag locally. I've tried to find out how that happened to no avail. I'll keep an eye out for the next few releases to ensure this doesn't happen again.

**Comment by marcphilipp** [comment]
@e-ts Thanks for bringing this to our attention!
