### ISSUE TITLE
Extend ParallelExecutionConfiguration to specify a predicate for determing if a pool is saturated

### ISSUE THREAD

**Issue by klease** [junit-team/junit5#2787]
I'm working on the Apache Camel project which uses parallel execution on a module with a large number of test cases (over 2400 classes and over 6000 tests.) After upgrading to 5.7.2 or later we were getting RejectedExecutionException which we solved by using a custom configuration with a large value for maxPoolSize.

The cause appears to be that the Tasks for the test classes all call `ForkJoinPool.managedBlock` and the tests themselves can take up to a few seconds to run. Fairly quickly all threads in the ForkJoinPool are busy and therefore each new call to managedBock causes a new thread to be allocated up to the maxPoolSize. Each of these new threads usually runs only 1 or 2 tests.

I found that by providing a predicate for _saturated_ when creating the ForkJoinPool, and having it return true, it was possible to run all the tests with a much smaller maxPoolSize.

Currently it's not possible to control this parameter using a custom implementation of `ParallelExecutionConfiguration`.

So I propose to add a method to the interface such as the following:

```java
/**
 * Get the predicate called when there the ForkJoinPool has reached MaxPoolSize
 * and there are no threads available, or null. The predicate should return true if the
 * blocking thread should try again. If the predicate is null or returns false a
 * RejectedExcecutionException is thrown.
 * @return a Predicate accepting a ForkJoinPool as the parameter or null.
 */
Predicate<? super ForkJoinPool> getSaturatePredicate();
```

The `DefaultParallelExecutionConfiguration` would return null.

The class `ForkJoinPoolHierarchicalTestExecutorService` would use `configuration.getSaturatePredicate()` when creating the `ForkJoinPool`.

**Comment by sbrannen** [comment]
How would one supply the `Predicate`?

**Comment by klease** [comment]
By implementing the new method in a custom implementation of ParallelExecutionConfiguration, for example:
```
        @Override
    	public Predicate<? super ForkJoinPool> getSaturatePredicate() {
        	return (ForkJoinPool p) -> {return true;};
        }
```

**Comment by sbrannen** [comment]
Thanks for the clarification.

Wouldn't `getSaturatedPredicate()` make more sense (_saturated_)?

**Comment by marcphilipp** [comment]
**Team decision:** Add `ParallelExecutionConfiguration.getSaturatedPredicate()`

@klease Would you be interested in submitting a PR for this?

**Comment by klease** [comment]
> @klease Would you be interested in submitting a PR for this?

Yes, of course. It will be my first for junit5 so I'll try to follow the guidelines.
