### ISSUE TITLE
Support JDK concrete types for `List`, `Set` and `Map` in `@EmptySource` / `EmptyArgumentsProvider`

### ISSUE THREAD

**Issue by scordio** [junit-team/junit5#2791]
I have tests targeting a legacy library, which unfortunately exposes parameters with concrete types of collections (e.g., `ArrayList`, `HashSet`, etc.) instead of the corresponding interfaces.

Currently, the `EmptyArgumentsProvider` implementation targets only interfaces:

https://github.com/junit-team/junit5/blob/4cd1fc064c6864d01ccacf08c4117c7c39d05e0a/junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EmptyArgumentsProvider.java#L47-L55

so a test like the following doesn't work:

```java
@ParameterizedTest
@EmptySource
void test(ArrayList<?> list) {
   ...
   legacyService.call(list);
   ...
}
```

The workaround is a `@MethodSource` taking care of the instantiation of the concrete type.

Would you accept enhancing the implementation of `EmptyArgumentsProvider` to also support the concrete types of the JDK? If yes, happy to raise a PR about it.

## Deliverables

- [ ] `@EmptySource` provides an empty instance of the JDK concrete types for `List`, `Set` and `Map`

**Comment by sbrannen** [comment]
> Would you accept enhancing the implementation of `EmptyArgumentsProvider` to also support the concrete types of the JDK?

The question is where to draw the line regarding which concrete types are supported.

As the Javadoc states:

> Subtypes of the supported types are not supported.

That was a conscious design decision to limit the maintenance scope of the feature.

In any case, the team will revisit this topic during an upcoming meeting.

**Comment by marcphilipp** [comment]
Couldn't we check whether the type implements `Collection` and has a public no-arg constructor?

**Comment by scordio** [comment]
@marcphilipp your proposal looks good to me. Can I prepare a PR with this approach or rather wait for the official decision of the team?

**Comment by scordio** [comment]
Right after submitting my last comment, I realized that there are already collections having a public no-arg constructor that shouldn't be used in standard flows.

For example, from Hibernate:
* [`PersistentList`](https://github.com/hibernate/hibernate-orm/blob/0b2a357670ae41aac326f99d9c8b38f825f23989/hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentList.java#L33-L37)
* [`PersistentSet`](https://github.com/hibernate/hibernate-orm/blob/0b2a357670ae41aac326f99d9c8b38f825f23989/hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSet.java#L36-L44)
* [`PersistentMap`](https://github.com/hibernate/hibernate-orm/blob/0b2a357670ae41aac326f99d9c8b38f825f23989/hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentMap.java#L38-L46)

Not sure if this would be a point in favor of supporting only a subset of implementations where the behavior is well-known.

**Comment by marcphilipp** [comment]
@scordio We discussed this in our team call today and were not sure about your use case.

Wouldn't the following be easy enough and not require any changes in JUnit?

```java
@ParameterizedTest
@EmptySource
void test(List<?> list) {
   ...
   legacyService.call(new ArrayList<>(list));
   ...
}
```

**Comment by scordio** [comment]
@marcphilipp Sorry, I forgot to provide the full background. My example goes together with the usage of `@NullSource`, something like:

```java
@ParameterizedTest
@NullSource
@MethodSource("emptyArrayList")
void test(ArrayList<?> list) {
   ...
   legacyService.call(list);
   ...
}
```

Your example would fail with an NPE at `new ArrayList<>(list)`.

`@NullAndEmptySource` would be the target if `@EmptySource` would support concrete types.

In the end, this is not a blocker and is mostly a cosmetic issue. We have a workaround but also the test can be rewritten in different ways to overcome the NPE and the unsupported concrete type, making it a bit more verbose.

Being a corner case, I totally understand if you'd rather not support it, but thought I'd ask for something that would improve the readability of the test.

**Comment by rgseyvie** [comment]
@scordio 
I would like to work on this issue, could you assign it to me?

**Comment by scordio** [comment]
@rgseyvie this is not really under my control and it's still in discussion with the team.

But I'd be happy to work on it by myself if it gets accepted 🙂

**Comment by scordio** [comment]
@marcphilipp I imagine this is still under team discussion and not something ready to be worked on, right?

**Comment by marcphilipp** [comment]
**Team decision:** Add support for concrete types as proposed in https://github.com/junit-team/junit5/issues/2791#issuecomment-991193585.

**Comment by marcphilipp** [comment]
@scordio Thanks for the ping! Would you like to take a stab at this?

**Comment by scordio** [comment]
Sure and thanks, @marcphilipp.

Just to reconfirm, with the proposal in https://github.com/junit-team/junit5/issues/2791#issuecomment-991193585, cases like https://github.com/junit-team/junit5/issues/2791#issuecomment-1002337965 won't work properly but this is understood and accepted, right?

**Comment by marcphilipp** [comment]
@scordio Yes, we think that's acceptable. We considered only doing this for `java.**` packages or an explicit list of well-known classes but decided it's not worth it because nobody has use declare a `PersistentList` or similar together with `@EmptySource`.

**Comment by scordio** [comment]
I created [IDEA-313866](https://youtrack.jetbrains.com/issue/IDEA-313866) to update the inspection rules of IDEA.
