### ISSUE TITLE
Why @MockBean Environment doesn't work in @WebMvcTest annotated controller class Junit 5

### ISSUE THREAD

**Issue by arvindersinghchhabra** [junit-team/junit5#2793]
Why @MockBean Environment(Interface) doesn't work in @WebMvcTest annotated controller class Junit 5 However same thing is working fine in Service layer here service layer doesn't have @WebMvcTest annotation.

Is this a bug or i am missing something?

Jupiter Version : 5.8.1
Spring boot 2.3.4.RELEASE
Java 8

**Comment by sbrannen** [comment]
Since your question is primarily related to Spring Boot testing features, please open an issue in the [Spring Boot issue tracker](https://github.com/spring-projects/spring-boot/issues).

In light of that, I am closing this issue.
