### ISSUE TITLE
Allow defining scope in the @TempDir annotation

### ISSUE THREAD

**Issue by OrangeDog** [junit-team/junit5#2798]
Currently you can choose the scope globally, but not on individual tests.

Some tests may require unique directories, and some may require shared ones.

**Comment by jbduncan** [comment]
The [new `TemporaryDirectory` feature](https://github.com/junit-pioneer/junit-pioneer/issues/348) in junit-pioneer, which I'm working on, will have this feature out-of-the-box. :)

**Comment by marcphilipp** [comment]
For the time being, I would recommend not to set the scope but use a `static` `@TempDir` field as [described in the user guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory).
