### ISSUE TITLE
Add support for dynamic test providers to TestDescriptor (and TestIdentifier?)

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#280]
While implementing support for #58 in #278 we discovered that it's currently not possible to have a `TestDescriptor` that returns `false` for `isTest()` and an empty set for `getChildren()` because it will get pruned by the launcher.

Thus, a `TestDescriptor` should have a way to signal to the launcher that it is going to produce children during the _execution phase_.

**Comment by sbrannen** [comment]
@marcphilipp, when you tidy up this issue, please make sure that the recent `Node` refactorings in the `HierarchicalTestEngine` still make sense -- especially the application and concrete implementations of the `isLeaf()` method.

**Comment by marcphilipp** [comment]
*in progress*
