### ISSUE TITLE
Global config

### ISSUE THREAD

**Issue by crizzis** [junit-team/junit5#2800]
Some config options (e.g. `@DisplayNameGeneration`) could offer a way to be configured globally. 

I'm thinking `.properties` file or package-level annotations

**Comment by sbrannen** [comment]
The `DisplayNameGenerator` can already be set via `junit-platform.properties`.

Have you read the [User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator-default)?

**Comment by crizzis** [comment]
Totally missed that, sorry. 

Closing issue.

**Comment by sbrannen** [comment]
> Totally missed that, sorry.

No problem.

The Javadoc for `DisplayNameGenerator` and `@DisplayNameGeneration` currently does not mention the global configuration option; however, that will be addressed in #2769. So, kudos to @marcphilipp for having already fixed that.
