### ISSUE TITLE
test arguments are not templated into @parameterizedtest name

### ISSUE THREAD

**Issue by nhomble** [junit-team/junit5#2804]
## Steps to reproduce

https://github.com/nhomble/junit5-display-name-repro

If I write 
```java
@ParameterizedTest(name = "{0} ' {1}")
```
then the second argument is **not templated** into the name.

## Context

 - Used versions (Jupiter/Vintage/Platform):
 ```groovy
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testImplementation('org.junit.jupiter:junit-jupiter:5.8.2')
}
```
 - Build Tool/IDE: Intellij 2021.3

## Deliverables

- [ ] ...

**Comment by juliette-derancourt** [comment]
I believe this is actually an expected behavior of the [MessageFormat](https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html) name.

As stated in [this section of the user guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-display-names):

> Please note that name is a MessageFormat pattern. Thus, a single quote (') needs to be represented as a doubled single quote ('') in order to be displayed.

**Comment by nhomble** [comment]
Apologies @juliette-derancourt, you're right. I reviewed the docs and was able to confirm your fix https://github.com/nhomble/junit5-display-name-repro/blob/master/src/test/java/SampleTest.java#L8

**Comment by juliette-derancourt** [comment]
Great! 👍
