### ISSUE TITLE
JUnit 4 migration tips should document switched assertion failure message argument position

### ISSUE THREAD

**Issue by Marcono1234** [junit-team/junit5#2809]
It would be good if the "Migration Tips" section of the user guide mentioned the switched assertion message position:
- JUnit 4 has the assertion message as first argument: `assertTrue(String message, boolean condition)`
- JUnit 5 has the assertion message as last argument: `assertTrue​(boolean condition, String message)`

I assume eventually users will figure out why some of their tests are failing with confusing messages after migration. But it might be good to warn them beforehand.

**Comment by sbrannen** [comment]
I agree: it would be beneficial to the community to add such advice in [Migration Tips](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-tips).

@Marcono1234, would you like to submit a PR for that?

**Comment by rob93c** [comment]
Hi @sbrannen and @Marcono1234, if you are ok with this I'd like to improve the documentation adding to [migration-from-junit4.adoc](https://github.com/junit-team/junit5/blob/main/documentation/src/docs/asciidoc/user-guide/migration-from-junit4.adoc) the entry:

- The following assertions now accept the assertion message as their last parameter: `assertTrue`, `assertFalse`, `assertNull`, `assertNotNull`, `assertEquals`, `assertNotEquals`, `assertArrayEquals`, `assertSame`, `assertNotSame` and `assertThrows`.

**Comment by sbrannen** [comment]
@rob93c, I think it's fine if you submit a PR, since @Marcono1234 has not volunteered to.

However, I think we should add more text than just that. We should state how it worked in JUnit 4 and how it works in JUnit Jupiter, and we should show an example from each framework for comparison -- for example, using `assertEquals(String, String, String)`.

**Comment by Marcono1234** [comment]
Sorry for not having responded yet. Thanks a lot @rob93c for taking on this task, your PR looks really good!
