### ISSUE TITLE
Feedback when Suite does not contain tests or IncludeEngines does not find engine

### ISSUE THREAD

**Issue by escay** [junit-team/junit5#2819]
As a user I want to use the Junit5 way to start a cucumber engine test by using a Suite and I want to get feedback from Junit when I made a configuration mistake.

Example code: 

```java
import static io.cucumber.core.options.Constants.GLUE_PROPERTY_NAME;
import static io.cucumber.core.options.Constants.PLUGIN_PROPERTY_NAME;

import org.junit.platform.suite.api.ConfigurationParameter;
import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("com/somepackage")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.somepackage")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "pretty")
public class RunCucumberTest {

}

// Old Junit4 style:
//
// import org.junit.runner.RunWith;
//
// import io.cucumber.junit.Cucumber;
// import io.cucumber.junit.CucumberOptions;
//
// @RunWith(Cucumber.class)
// @CucumberOptions(plugin = "pretty", features = "classpath:com/somepackage")
// public class RunCucumberTest {
// // Makes JUnit run all JUnit tests
// }
```

## Deliverables

It would be very useful to make a build fail when:
- Suite does not run any tests at all.
- IncludeEngines fails to find the correct engine, e.g. when I enter 'cucumper' for which there is no engine on the classpath.
- SelectClasspathResource fails to find the resource folder
- ConfigurationParameter defines a parameter which is not used (this is maybe too much to ask)

In my case:
- I failed to configure the cucumber engine correctly in my maven dependencies but I was not warned that less unit tests were running.
- I am afraid that if someone refactors a feature file resource folder the test might no longer be executed, the empty suite could warn me.

**Comment by mpkorstanje** [comment]
Some preliminary thoughts, I'm not part of the JUnit team, but I did write the suite engine and Cucumbers JUnit5 implementation.

> Suite does not run any tests at all.

Adding an annotation based equivalent of `--fail-if-no-tests` shouldn't be too difficult.

I'm undecided wether or not this should be the default.

> IncludeEngines fails to find the correct engine, e.g. when I enter 'cucumper' for which there is no engine on the classpath.

Checking if an explicitly included engine exists and failing if it does not would also make sense for the ConsoleLauncher and junit-platform-runner.

> SelectClasspathResource fails to find the resource folder

I think this one is pretty much impossible. There is no direct link between a discovery selector and the tests it discovered.

> ConfigurationParameter defines a parameter which is not used (this is maybe too much to ask)

With #2727 merged indivial test engines could warn about unused properties in their namespace. This wouldn't cover all properties but would catch a good number of mistakes.

You may want to consider contributing this to Cucumber.

@junit-team I guess it would it be too late to require that all test engines prefix their properties with their engine name?

**Comment by marcphilipp** [comment]
> > Suite does not run any tests at all.
> 
> Adding an annotation based equivalent of `--fail-if-no-tests` shouldn't be too difficult.
> 
> I'm undecided wether or not this should be the default.

**Team decision:** Add `failIfNoTests` attribute to `@Suite` with default of `true` since that would benefit more users in the future.

> > IncludeEngines fails to find the correct engine, e.g. when I enter 'cucumper' for which there is no engine on the classpath.
> 
> Checking if an explicitly included engine exists and failing if it does not would also make sense for the ConsoleLauncher and junit-platform-runner.

**Team decision:** Fail test discovery (regardless whether used via `@Suite` or not) if an include filter is configured that doesn't match any engine. Log a warning if all engines have been filtered out by an exclude filter. Log a warning (instead of `config`) in case no engine is on the classpath (in `ServiceLoaderTestEngineRegistry`).

> > SelectClasspathResource fails to find the resource folder
> 
> I think this one is pretty much impossible. There is no direct link between a discovery selector and the tests it discovered.
> 
> Additionally an engine may receive discovery selectors which will fail to discover any tests but will discover tests in another engine.

**Team decision:** Leave as-is. You could enable the `DEBUG` log level for `LoggingLauncherDiscoveryListener` to get more information about which selectors were unresolved during test discovery.

> > ConfigurationParameter defines a parameter which is not used (this is maybe too much to ask)
> 
> With #2727 merged indivial test engines could warn about unused properties in their namespace. This wouldn't cover all properties but would catch a good number of mistakes.
> 
> You may want to consider contributing this to Cucumber.
> 
> @junit-team I suppose it would it be too late to require that all test engines prefix their properties with their engine id?

**Team decision:** Yes, we think it's too late for that though we recommend using similar naming conventions as used by the Jupiter engine. We should document that recommendation in the test engine section of the user guide.

**Comment by sbrannen** [comment]
Slated for 5.9 M1 until the individual tasks have been split out into separate GitHub issue.

**Comment by juliette-derancourt** [comment]
I opened #2823, #2824 and #2825 to follow up on decisions taken in https://github.com/junit-team/junit5/issues/2819#issuecomment-1029910273.
