### ISSUE TITLE
Fail test discovery if an `IncludeEngines` filter is configured and doesn't match any engine

### ISSUE THREAD

**Issue by juliette-derancourt** [junit-team/junit5#2824]
As stated in #2819, it would be useful to make a build fail when engine filters are not well configured.

## Deliverables

- [x] Fail test discovery if an `IncludeEngines` filter is configured and doesn't match any engine.
- [x] Log a warning if all engines have been filtered out by an exclude filter.
- [x] ~Log a warning (instead of config) in case no engine is on the classpath (in `ServiceLoaderTestEngineRegistry`).~ `SuiteLauncher` and `DefaultLauncher` already throw an exception in that case

Issue opened following decision taken in https://github.com/junit-team/junit5/issues/2819#issuecomment-1029910273.

**Comment by marcphilipp** [comment]
_in progress_
