### ISSUE TITLE
Improve documentation about registering a `LauncherSessionListener`

### ISSUE THREAD

**Issue by jabby** [junit-team/junit5#2826]
Hello JUnit team.

Thanks for your work.

## Steps to reproduce

* Clone the following repository: https://github.com/jabby/junit5-launcher-session-listener-problem
* run `mvn test`
* check the following output

```
~/git/github/junit5-launcher-session-listener-problem   main  mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] -------< fr.jabbytechs:junit-launcher-session-listener-problem >--------
[INFO] Building junit-launcher-session-listener-problem 0.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-bytecode-version) @ junit-launcher-session-listener-problem ---
[INFO] Adding ignore: module-info
[INFO] Adding ignore: module-info
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ junit-launcher-session-listener-problem ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jabberwock/git/github/junit5-launcher-session-listener-problem/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ junit-launcher-session-listener-problem ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ junit-launcher-session-listener-problem ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ junit-launcher-session-listener-problem ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ junit-launcher-session-listener-problem ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
launcherSessionOpened
launcherSessionClosed
launcherSessionOpened
[INFO] Running fr.jabbytechs.ExampleTest
testName
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 s - in fr.jabbytechs.ExampleTest
launcherSessionClosed
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.088 s
[INFO] Finished at: 2022-02-07T16:48:00+01:00
[INFO] ------------------------------------------------------------------------
```

`SetupTeardownLauncherSessionListener` is execute twice.

As a non-native english speaker, I think the [documentation here](https://junit.org/junit5/docs/current/user-guide/#launcher-api-launcher-session-listeners-custom) is not clear.

In fact I thought this morning that there is a bug in JUnit. After reading more carefully the documentation and especially the sample code, I realize it's not a bug.

For me, the following sentence: 

> Registered implementations of [LauncherSessionListener](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSessionListener.html) are notified when a [LauncherSession](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSession.html) is opened (before a [Launcher](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/Launcher.html) first discovers and executes tests) and closed (when no more tests will be discovered or executed).

means the code will be executed as follow: 

- LauncherSessionListener#launcherSessionOpened
- start discovering test
- end discovering test
- start running tests
- stop running tests
- LauncherSessionListener#launcherSessionClosed

but it seams that the code is actually executed like this:

- LauncherSessionListener#launcherSessionOpened
- start discovering test
- end discovering test
- LauncherSessionListener#launcherSessionClosed
- LauncherSessionListener#launcherSessionOpened
- start running tests
- stop running tests
- LauncherSessionListener#launcherSessionClosed

Moreover, as I said the current behavior is clearer when you read correctly / understand the sample code.

My suggestion is to improve current documentation.

## Context

 - Used versions (Jupiter/Vintage/Platform): `5.8.2`
 - Build Tool/IDE: `Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)`

Thanks for your time.
Have a nice day.

**Comment by stoyanK7** [comment]
@jabby I believe this is a better explanation. What do you think?
> Registered implementations of[ LauncherSessionListener](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSessionListener.html) are notified when a[ LauncherSession](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSession.html) is opened (once before a[ Launcher](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/Launcher.html) first discovers and once before it executes the tests) and closed (once when no more tests will be discovered and once they are executed).

**Comment by jabby** [comment]
Looks good to me. I'm not fluent in english but I think it's a better explanation of how LauncherSessionListener works.

**Comment by stoyanK7** [comment]
Now that I am reading my explanation a second time, I think the order of the notifications is unclear. Explicitly stating what is happening might be the best way to understand it. Such as
>Registered implementations of[ LauncherSessionListener](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSessionListener.html) are notified when a[ LauncherSession](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSession.html) is opened and closed - 4 notifications in total:   
>1. Before a [Launcher](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/Launcher.html) first discovers the tests  
>2. When no more tests will be discovered  
>3. Before a [Launcher](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/Launcher.html) executes the tests  
>4. After the tests are executed

**Comment by marcphilipp** [comment]
@jabby I cloned your sample project, updated Surefire and Failsafe to 3.0.0-M6/M7, and added another test class. It now prints:

```
[INFO] --- maven-surefire-plugin:3.0.0-M6:test (default-test) @ junit-launcher-session-listener-problem ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
launcherSessionOpened
[INFO] Running fr.jabbytechs.Example1Test
testName
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in fr.jabbytechs.Example1Test
[INFO] Running fr.jabbytechs.Example2Test
testName
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in fr.jabbytechs.Example2Test
launcherSessionClosed
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

This was changed in https://issues.apache.org/jira/browse/SUREFIRE-1935 for 3.0.0-M6
