### ISSUE TITLE
Introduce `@EnabledInNativeImage` & `@DisabledInNativeImage` conditions for GraalVM

### ISSUE THREAD

**Issue by sdeleuze** [junit-team/junit5#2830]
With [Native Build Tools](https://github.com/graalvm/native-build-tools) supporting JUnit 5 testing of native images, there are more and more requests for being able to run or skip tests if running as native image or the other way around. Conceptually that seems close (but not equivalent) to existing [Java runtime environment conditions](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-jre).

In term of implementation, GraalVM `native-image` provides a simple and standardized way to check if the code is running or being compiled as a native image via the [`org.graalvm.nativeimage.imagecode` system property](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java). You can see [Spring Framework's `NativeDetector`](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/NativeDetector.java) for a concrete example and stable usage.

So I am wondering if such support could be provided by dedicated annotations like `@EnabledOnNative` and `@DisabledOnNative`. 

If not possible, the more verbose `@EnabledIfSystemProperty(named = "org.graalvm.nativeimage.imagecode")` and `@DisabledIfSystemProperty(named = "org.graalvm.nativeimage.imagecode")` annotations could potentially be an option. If this is the way to support that use case, that could perhaps be documented in https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution.

This is a common use case and the system property alternative seems too verbose and not discoverable enough to me, so my preference is for `@EnabledOnNative` and `@DisabledOnNative`.

**Comment by sbrannen** [comment]
The required syntax is:

```java
@DisabledIfSystemProperty(named = "org.graalvm.nativeimage.imagecode", matches = ".+")
```

Here's the original condition annotation I wrote 2 years ago:

https://github.com/sbrannen/spring-framework/blob/graalvm-testing/spring-core/src/testFixtures/java/org/springframework/core/testfixture/annotation/DisabledInGraalVmNativeImage.java

**Comment by sbrannen** [comment]
Hence other proposals for the naming convention for these two annotations.

- `@DisabledInGraalVmNativeImage`
- `@DisabledInNativeImage`

**Comment by marcphilipp** [comment]
**Team Decision:** Add `@EnabledInNativeImage` and `@DisabledInNativeImage`.

**Comment by sbrannen** [comment]
Reopening to make sure it's backported to the `5.9.x` branch.

**Comment by sbrannen** [comment]
Backported to 5.9.x for inclusion in 5.9.1
