### ISSUE TITLE
Support architecture in @EnabledOnOs and @DisabledOnOs

### ISSUE THREAD

**Issue by mhalbritter** [junit-team/junit5#2848]
Hi team,

In Spring Boot we [had the issue](https://github.com/spring-projects/spring-boot/issues/30082) that some of our tests don't run on Linux when using an AArch64 architecture. I then added a [custom annotation](https://github.com/spring-projects/spring-boot/blob/24a68fc5953f7de1c485b70692e65002782f4d70/spring-boot-project/spring-boot-tools/spring-boot-test-support/src/main/java/org/springframework/boot/testsupport/junit/DisabledOnOs.java) and the [condition](https://github.com/spring-projects/spring-boot/blob/24a68fc5953f7de1c485b70692e65002782f4d70/spring-boot-project/spring-boot-tools/spring-boot-test-support/src/main/java/org/springframework/boot/testsupport/junit/DisabledOnOsCondition.java) to disable the tests on Linux AArch64. This could be something that JUnit Jupiter provides out of the box. 

What do you think?

Another note: This could lead to making the annotations repeatable, as maybe a test doesn't work on Linux aarch64 and on MacOS x86, which you could not do without repeating the annotation.

## Deliverables

- [ ] Introduce `architecture` attribute in the `@EnabledOnOs` and `@DisabledOnOs` annotations.

**Comment by marcphilipp** [comment]
We brainstormed a few alternatives:

## Alternative 1

Enhance existing annotation:

```java
public @interface DisabledOnOs {
	OS[] value() default {};
	String[] architectures() default {};
}
@DisabledOnOs(architectures = "aarch64") // OS is not checked anymore
@DisabledOnOs(architectures = {"aarch64", "x86_64"}) // OS is not checked anymore
@DisabledOnOs(value = OS.LINUX, architectures = {"aarch64", "x86_64"})
```

## Alternative 2

Define new annotation:
```java
public @interface DisabledOnArchitecture {
	String[] value();
	OS[] os() default {};
}
@DisabledOnArchitecture("aarch64") // OS is not checked
@DisabledOnArchitecture({"aarch64", "x86_64"}) // OS is not checked
@DisabledOnArchitecture(value = {"aarch64", "x86_64"}, os = OS.LINUX)
```

## Alternative 3

Recommend using `@DisabledIf`

```java
@DisabledIf("linuxAarch64")
@Test
void test() {}

static boolean linuxAarch64() {
	return OS.current() == OS.LINUX && "aarch64".equals(System.getProperty("os.arch"))
}
```

**Comment by marcphilipp** [comment]
**Team decision:** Let's go with alternative 1.

@mhalbritter Would you be interested in submitting a PR?

**Comment by mhalbritter** [comment]
Yep, can do it. Is this urgent for you?

**Comment by sbrannen** [comment]
> Yep, can do it. 

Great

> Is this urgent for you?

No, it's not urgent.

Depending on when you get to it, it could make it into 5.9.

**Comment by mhalbritter** [comment]
Great, will put in on my todo list!

**Comment by michaelfmnk** [comment]
Hi! Is it still relevant? 
Had some spare time to implement this feature. 
Should I create a pull request?
