### ISSUE TITLE
stop .asc.${checksums} publication to Central repository

### ISSUE THREAD

**Issue by hboutemy** [junit-team/junit5#2852]
currently, for each artifact published to Central repository, there are many additional files published: checksums and signature
see for example: https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter/5.8.2/

most of the files that I see follow expected  Maven2 repository layout: https://maven.apache.org/repository/layout.html perfect

there is only one series of checksum files that I'm surprised of: each `.asc` file is currently complemented by checksum files `.asc.md5`+`.asc.sha1`+`.asc.sha256`+`.asc.sha512`

These files are not a Central requirement: see for example https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.4.1/

Is there a deliberate choice to add checksums for `.asc` files? Are these checksums found useful for something that I did not imagine?

I'd personally would think that these files should not be published.

**Comment by marcphilipp** [comment]
This is done by the [Maven Publish Plugin](https://docs.gradle.org/current/userguide/publishing_maven.html) from Gradle:
> checksum files will be generated for all artifacts and signature files.

I think the checksums for signature files (and all other artifacts for that matter) are useful to determine their integrity after having downloaded them. I don't see any harm in publishing them even if they're not required. Moreover, I don't think we should deviate from what Gradle does by default here.

@hboutemy Are these impacting you negatively apart from causing surprise?

**Comment by hboutemy** [comment]
IIUC, the issue is more to be reported against Gradle's Maven Publish Plugin: I'll need to find where is the issue tracker (I you know, pointers welcome)

it's just another level of confusion for many people, then I'm trying to remove confusion and remove noise files from Maven Central

thanks for your feedback

**Comment by marcphilipp** [comment]
It's just Gradle's usual issue tracker: https://github.com/gradle/gradle/issues

**Comment by hboutemy** [comment]
thanks, I'll go there, and explain more my context: I think this deserves a good positive discussion, experience sharing, design explanations from each sides

**Comment by hboutemy** [comment]
FYI https://github.com/gradle/gradle/issues/20232
