### ISSUE TITLE
Add an option to list all test found by Console Launcher

### ISSUE THREAD

**Issue by VasilyFomin** [junit-team/junit5#2854]
Hi,

I'm wondering if it'd be possible to add an option to list all tests found by the Console Launcher.

For example, Google Test [can](http://google.github.io/googletest/advanced.html#listing-test-names) print all tests using `--gtest_list_tests` option.

**Comment by marcphilipp** [comment]
**Team decision:** We agree that having an option (e.g. `--dry-run`) to list the result of test discovery to the Console Launcher would be useful.

**Comment by marcphilipp** [comment]
@VasilyFomin Would you be interested in submitting a PR?

**Comment by stoyanK7** [comment]
> @VasilyFomin Would you be interested in submitting a PR?

I am interested. May I try?

**Comment by stoyanK7** [comment]
@marcphilipp Should tests always be listed as a tree like Google Test does or should the user be able to specify it(flat, tree, verbose) just like when executing them?

**Comment by MatteoMolinari93** [comment]
What's the status here?

**Comment by stoyanK7** [comment]
@MatteoMolinari93  No idea, did not get much attention on my pull request so I gave up on it. Anybody feel free to take it and finish the issue if they would like to :)

**Comment by iofit** [comment]
Hello, I've taken over @stoyanK7 PR to try to get it merge, I updated the branch and applied the changes, no conflicts. Let me know if there are any further improvements we want to do or check out before merging https://github.com/junit-team/junit5/pull/3075

**Comment by marcphilipp** [comment]
@stoyanK7 @iofit Sorry for dropping the ball on this! I'll be revisiting your work shortly.
