### ISSUE TITLE
Feature request: Condition for headless environment

### ISSUE THREAD

**Issue by pbludov** [junit-team/junit5#2855]
Sometimes we need to write unit tests for UI. The problem is that they will fail in a headless environment.
We need a way to suppress them. One possibility is to use assumptions:
```java
    @BeforeAll
    static void beforeAll() {
        boolean isHeadless = GraphicsEnvironment.isHeadless();
        Assumptions.assumeFalse(isHeadless, "This test is incompatible with headless environment");
    }
```

The more elegant way is to use [conditions](https://junit.org/junit5/docs/current/user-guide/#extensions-conditions). Something like

```java
@DisabledIfSystemProperty(named = "java.awt.headless", matches = "true")
public class UITest {
}
```

Unfortunately, this approach will not work when such property isn't set. The default value of "headless" property is platform dependent. On Linux, there must be "DISPLAY" among the environment variables, on Mac it depends on presence of the process named "WindowServer", on Windows there is something similar.

## Deliverables
- [ ] Implement two new JUnit conditions, `@EnabledOnHeadlessEnvironment` and `@DisabledOnHeadlessEnvironment` to easily disable some tests in a headless CI environment.

**Comment by Akaame** [comment]
From what I have gathered from your post, you need conditions that act on results `GraphicsEnvironment.isHeadless`. Here is what I have come up with.

Listings:

`DisabledOnHeadlessEnvironment.java`

```java
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@ExtendWith(DisabledOnHeadlessEnvironmentCondition.class)
public @interface DisabledOnHeadlessEnvironment {

}
```

`DisabledOnHeadlessEnvironmentCondition.java`
```java
public class DisabledOnHeadlessEnvironmentCondition implements ExecutionCondition {
    @Override
    public ConditionEvaluationResult evaluateExecutionCondition(ExtensionContext context) {
        if (GraphicsEnvironment.isHeadless()) {
            return ConditionEvaluationResult.disabled("Environment is headless");
        }
        return ConditionEvaluationResult.enabled("Environment is not headless");
    }
}
```

`EnabledOnHeadlessEnvironment.java`
```java
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@ExtendWith(EnabledOnHeadlessEnvironmentCondition.class)
public @interface EnabledOnHeadlessEnvironment {

}
```

`EnabledOnHeadlessEnvironmentCondition.java`
```java
public class EnabledOnHeadlessEnvironmentCondition implements ExecutionCondition {
    @Override
    public ConditionEvaluationResult evaluateExecutionCondition(ExtensionContext context) {
        if (GraphicsEnvironment.isHeadless()) {
            return ConditionEvaluationResult.enabled("Environment is headless");
        }
        return ConditionEvaluationResult.disabled("Environment is not headless");
    }
}
```

Simple manual testing says that this holds up but I am not really sure if this should be a part of JUnit library though.

Cheers.

P.S: it is kind of interesting that BooleanExecutionCondition is not exposed. What is the reasoning behind keeping it package-private?

**Comment by sbrannen** [comment]
Please note that `GraphicsEnvironment` is part of the `java.desktop` module and is not guaranteed to always be present in the runtime environment for Java 9+.

In any case, if you know that `GraphicsEnvironment` is available have you tried using the following?

```java
@DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")
```

**Comment by sormuras** [comment]
The absence of module `java.desktop` could be mapped to the meaning of being headless, not?

**Comment by sbrannen** [comment]
> The absence of module `java.desktop` could be mapped to the meaning of being headless, not?

Probably, but then a simple `@DisabledIf` declaration pointing statically to `java.awt.GraphicsEnvironment` wouldn't always work post Java 9, in which case you'd need a dedicated extension to check whether the `GraphicsEnvironment` class can be loaded.

**Comment by pbludov** [comment]
> @DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")

Yes, this works fine, but only for methods (tested with JUnit 5.8.2, openjdk 17.0.3):

```java
class SomeTest {

    @Test
    @DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")
    void method1() { // Test skipped
        assertFalse(2 > 1);
    }

    @Test
    void method2() { // Test suceeded
        assertTrue(2 > 1);
    }
}

@DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")
class SomeOtherTest {

    @Test
    void method1() { // Test failed
        assertFalse(2 > 1);
    }

    @Test
    void method2() { // Test suceeded
        assertTrue(2 > 1);
    }
}
```

**Comment by sbrannen** [comment]
> but only for methods (tested with JUnit 5.8.2, openjdk 17.0.3):

I cannot reproduce that.

If I run both of those test classes with `-Djava.awt.headless=true`, then `method1` in `SomeTest` is skipped as well as the entire `SomeOtherTest` class.

**Comment by pbludov** [comment]
> I cannot reproduce that.

My bad. The actual class I tested was [this one](https://github.com/checkstyle/checkstyle/blob/399f1b48b79731d65e824eb927971ef6174c3463/src/test/java/com/puppycrawl/tools/checkstyle/AbstractGuiTestSupport.java#L33):
```java
public abstract class AbstractGuiTestSupport extends AbstractPathTestSupport {
    @BeforeAll
    public static void validateGraphicsEnvironment() {
        final boolean isHeadless = GraphicsEnvironment.isHeadless();
        assumeFalse(isHeadless, "This test is incompatible with headless environment");
    }
}

public class MainFrameTest extends AbstractGuiTestSupport {
    void test1() {
        // ...
    }

    @Test
    void testN() {
        // ...
    }
}
```

Changing this to 
```java
@DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")
public abstract class AbstractGuiTestSupport extends AbstractPathTestSupport {
}

public class MainFrameTest extends AbstractGuiTestSupport {
    void test1() {
        // ...
    }

    @Test
    void testN() {
        // ...
    }
}
```
does not work. But this one works fine

```java
public abstract class AbstractGuiTestSupport extends AbstractPathTestSupport {
}

@DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")
public class MainFrameTest extends AbstractGuiTestSupport {
    void test1() {
        // ...
    }

    @Test
    void testN() {
        // ...
    }
}
```

I must admit that proposed solution,
`@DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")`
works for me. It would be nice to have such example in the documentation.

**Comment by sbrannen** [comment]
> does not work. But this one works fine

That's because JUnit Jupiter enabled/disabled annotations are not `@Inherited`. Thus, the declaration on `AbstractGuiTestSupport` is ignored when conditions are evaluated for `MainFrameTest`.

In other words, annotations like `@DisableIf` must be declared locally on the test class to which they apply.

**Comment by sbrannen** [comment]
> I must admit that proposed solution,
> `@DisabledIf(value = "java.awt.GraphicsEnvironment#isHeadless", disabledReason = "headless environment")`
> works for me. 

Very glad to hear that.

> It would be nice to have such example in the documentation.

I agree. I light of that, this issue is superseded by #2933.
