### ISSUE TITLE
Improve error message when FQMN in `@MethodSource` is invalid

### ISSUE THREAD

**Issue by elonderin** [junit-team/junit5#2869]
With #1088 came support that `@MethodSource` to spec external Methods via FQMN.

It happened, that I did not carefully read the Javadoc:

> ... static factory methods in external classes referenced by fully qualified method name.

And so I put `@MethodSource("org.junit.Foo.bar")` on a `@Nested` test method  and consequently got this error:

```
Could not find method [org.junit.Foo.bar] in class [org.junit.FooTest$NestedTest]
```

This needlessly lead me in the wrong direction of chasing down the cause for this until I ended up at #1088 which after reading caused me to realize that I was missing the `#`.

Hence I propose these improvements for the value(s):

**Syntactically validate it**

ATM it's possible to enter any string, and this causes always the same message: 

> Could not find method [. asdjbh lkjahd jbh] in class [ <FQCN of `@MethodSource`>]

ideas:

- e.g. if it contains `.`, then it's an FQMN and the segment must be separated with `#`
- proper FQCN if one can be extracted from the given string (in the above case the `@Nested` test class is reported which is impossible for FQMN)
- report that finding in the error

**extend the jdoc to include an example**

```java
/**
 * ... static factory methods in external classes referenced by fully qualified 
 * method name, e.g. {@code @MethodSource("org.junit.Foo.#bar")}
 */
```

found in v5.7.2

**Comment by sbrannen** [comment]
Indeed, the diagnostics can certainly be improved for failure cases with `@MethoSource` factory method lookups.

I've added applicable labels and put this `up-for-grabs`.

**Comment by juliette-derancourt** [comment]
Hello @elonderin,

I've added [this commit](https://github.com/junit-team/junit5/commit/42c1add1478053921cf04bc5a082c136a8afbe50) which should improve the error message.
It will read like this: `[org.junit.Foo.bar] is not a valid fully qualified method name: it must start with a fully qualified class name followed by a '#' and then the method name, optionally followed by a parameter list enclosed in parentheses.`

> extend the jdoc to include an example

Do you remember where you wanted this example to be added? I've looked into `@MethodSource` JavaDoc, and there's already one:

https://github.com/junit-team/junit5/blob/42c1add1478053921cf04bc5a082c136a8afbe50/junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodSource.java#L106-L122

**Comment by elonderin** [comment]
AH, i missed that b/c `value` being the default property it's not written in code (most the times) and hence it's jdoc not shown. However, the jdoc of the annotation is shown and therefor i proposed in the OP to extend (the 1st paragraph).

```
/**
 * {@code @MethodSource} is an {@link ArgumentsSource} which provides access
 * to values returned from {@linkplain #value() factory methods} of the class in
 * which this annotation is declared or from static factory methods in external
 * classes referenced by <em>fully qualified method name</em>,  e.g. {@code @MethodSource("org.junit.Foo.#bar")}. 
 */
```
This being said, i acknowledge that `value` is the more proper place for it, alas it's much less visible. So maybe

**Comment by sbrannen** [comment]
@juliette-derancourt, if you've already fixed this, can you please assign this issue to yourself and remove the `up-for-grabs` label?

**Comment by juliette-derancourt** [comment]
@sbrannen thanks for the reminder! ;)

> Thx for fixing this so soon +1

@elonderin you're welcome, thanks for noticing the issue :)
