### ISSUE TITLE
Document ExtensionContext.Store in the User Guide

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#287]
Section 5.8 -- "Keeping State in Extensions" -- in the User Guide currently states:

>   Usually, an extension is instantiated only once. So the question becomes relevant: How do you keep the state from one invocation of an extension point to the next? …​

The ParameterResolvers for upREST involve parameters that are related to each other, and regardless of the test, an HttpRequest and the subsequent HttpResponse have to be generated.  For parameters like an HTTP StatusLine or HTTP EntityBody, you don't want to make additional HTTP requests for each parameter that's being resolved

My current method is for each parameter type to understand it's dependent parameters (whether they're passed to the test method or not), and to retrieve those parameters from the `ExtensionContext.Store`.  If the dependent parameter isn't found in the store, then its parameter resolver is called and the results of that call are both added to the store and returned to the dependent parameter's resolver.

I should note that I've only found this to be necessary for ParameterResolvers called to execute a single test.  Since I'm a relatively big fan of keeping tests as decoupled as possible (so they can run concurrently), I can't foresee needing this technique in other types of extensions.

If you'd like, I could expand this section but even with a simplified scenario, it's going to be more than a few paragraphs.

**Comment by sbrannen** [comment]
@smoyer64, thanks for raising the issue.

Feel free to draft a proposal and submit a PR.
