### ISSUE TITLE
Apparently, # is an illegal character in CSVSource text??

### ISSUE THREAD

**Issue by jayr-davis** [junit-team/junit5#2876]
- Java 17
- IntelliJ IDEA 2021.3.2
- JUnit Jupiter: 5.8.1
- JUnit Platform: 1.8.1

Here is one of my tests:

```java
    @DisplayName("HW Id Testing")
    @ParameterizedTest(name = "[{index}] {arguments}")
    @CsvSource(delimiter = '|', textBlock = """
            #Num: 1  Simple dec only                  | 123             | 123
            #Num: 2  Long test dec only               | 678987654321    | 987654321
            #Num: 3  dec and hex                      | 123AbC          | 1194684
            #Num: 4  dec and hex with extra chars     | 123XX^^^ABC     | 1194684
            #Num: 5  null                             | null            | null
            """)
    public void hwIdToIntTester(String descript,
                                String hwId,
                                String convertedValue){
```
  
This code FAILS with:

```
PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest
```

If I change the leading `#` to nearly any other character, it all works fine.

**Comment by sormuras** [comment]
A paragraph in the [@CsvSource](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-CsvSource) section of the User Guide reads:

> In contrast to CSV records supplied via the value attribute, a text block can contain comments. Any line beginning with a `#` symbol will be treated as a comment and ignored. Note, however, that the `#` symbol must be the first character on the line without any leading whitespace. It is therefore recommended that the closing text block delimiter (`"""`) be placed either at the end of the last line of input or on the following line, left aligned with the rest of the input (as can be seen in the example below which demonstrates formatting similar to a table).

One possible solution: moving the closing text block delimiter (`"""`) one step to the left, like in ...
```java
    @CsvSource(delimiter = '|', textBlock = """
            #Num: 1  Simple dec only                  | 123             | 123
            #Num: 2  Long test dec only               | 678987654321    | 987654321
            #Num: 3  dec and hex                      | 123AbC          | 1194684
            #Num: 4  dec and hex with extra chars     | 123XX^^^ABC     | 1194684
            #Num: 5  null                             | null            | null
           """)
```
... should make all `#` characters a part of the `descript` string.

**Comment by sbrannen** [comment]
Another option is to enclose the `descript` text in single or double quotes, though you have to be on JUnit Jupiter 5.8.2+ to use the `quoteCharacter` attribute to switch from single quotes (the default) to double quotes.

```java
    @CsvSource(delimiter = '|', textBlock = """
            '#Num: 1  Simple dec only'                  | 123             | 123
            '#Num: 2  Long test dec only'               | 678987654321    | 987654321
            '#Num: 3  dec and hex'                      | 123AbC          | 1194684
            '#Num: 4  dec and hex with extra chars'     | 123XX^^^ABC     | 1194684
            '#Num: 5  null'                             | null            | null
            """)
```

Similar to the option mentioned by @sormuras in https://github.com/junit-team/junit5/issues/2876#issuecomment-1086552014, you can prefix each line with with a text block "space character" (`\s`) if you prefer the content to vertically align with the closing `"""`.

```java
    @CsvSource(delimiter = '|', textBlock = """
            \s#Num: 1  Simple dec only                  | 123             | 123
            \s#Num: 2  Long test dec only               | 678987654321    | 987654321
            \s#Num: 3  dec and hex                      | 123AbC          | 1194684
            \s#Num: 4  dec and hex with extra chars     | 123XX^^^ABC     | 1194684
            \s#Num: 5  null                             | null            | null
            """)
```

In light of the above, I am closing this as "works as designed".
