### ISSUE TITLE
AllBooleanCombinationsSource arguments provider

### ISSUE THREAD

**Issue by tomerr90** [junit-team/junit5#2878]
A common use case we have is a test that take a bunch of boolean flags a check very slightly (mostly in expected value) based on this flag.
Classic for a ParameterizedTest, which is what we use today, but for the source we currently use CsvSource with the boolean options:
```
@ParameterizedTest
@CsvSource({
   "true, true",
   "true, false",
   "false, true",
   "false, false"
})
public void testMethod(boolean flag1, boolean flag2)
```
Which is annoying, verbose and error-prone.
So I wanted to implement an annotation like `@AllBooleanCombinationsSource(int)` that takes the number of boolean params and generate all possible combinations.
Though this might be a bit too specific, so wanted to get your opinion, is that something that you think belongs in Junit?

**Comment by sbrannen** [comment]
Take a look at the [Cartesian product support in JUnit Pioneer](https://junit-pioneer.org/docs/cartesian-product/).

I think that might suit your needs.

**Comment by XIANY1203** [comment]
May I try?

**Comment by marcphilipp** [comment]
**Team Decision:** We advise to use the feature from Pioneer and won't include this in Jupiter core for the time being.
