### ISSUE TITLE
TempDir fails to clean up for certain files

### ISSUE THREAD

**Issue by andrewparmet** [junit-team/junit5#2886]
Follow-up for #2883.

TempDir is failing to delete `Test.java` following a test (GenerateTest). This is a partial listing of the contents of the temporary directory including the problematic file:

```
./bufbuild/generated/java/com/parmet/buf/test/v1:
total 20
-rw-r--r-- 1 root root 17332 Apr 10 21:30 Test.java
```

In a separate test (PublishTest), `image.json` is also generated from a call to Docker but TempDir has no trouble deleting it:

```
./bufbuild:
total 4
-rw-r--r-- 1 root root 974 Apr 10 21:30 image.json
```

These logs are from build https://github.com/andrewparmet/buf-gradle-plugin/pull/59/checks?check_run_id=5963791559.

## Steps to reproduce

Run CI on https://github.com/andrewparmet/buf-gradle-plugin/pull/59.

## Context

 - Used versions (Jupiter/Vintage/Platform): c8fa9c371106ef5ab5d87d68abde4ead27a0ea5a
 - Build Tool/IDE: Gradle 7.4.1

cc @marcphilipp

**Comment by marcphilipp** [comment]
@andrewparmet Thanks for the analysis! If the files belong to `root` I don't see how `TempDir` can possibly delete them. How are you invoking Docker? Could you change the user you run it with or change the file mask?

**Comment by andrewparmet** [comment]
It doesn't look like there's a way to change the Docker user without modifying my plugin user's config (a nonstarter) or changing the Docker image build process (which I do not control).

The short term solution may be to try to change the permissions myself (maybe using Docker?), but the long term solution is to migrate off of Docker; the program I'm executing is also published as a binary for each supported platform. I'll just have to resolve the correct binary and download it myself.

I have no explanation for why TempDir was happy to delete `image.json` but not `Test.java`. As far as I can tell the only difference between them is that `Test.java` is located in a nested directory. In any case it looks like this is not a use case TempDir is meant to handle.
