### ISSUE TITLE
JUnit suite engine test selection

### ISSUE THREAD

**Issue by wzrumich** [junit-team/junit5#2888]
We are using the JUnit suite engine feature to group a bunch of tests into a suite, with the `@Suite` annotation.

Currently, we have a bunch of tests with names ending with `TestIT`, e.g. `AddGlobalNumTestIT`.

It seems that these tests could not be identified due to the filter defined here:

https://github.com/junit-team/junit5/blob/43638eb6a870e0d6c49224053dfeb39dcf0ef33f/junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassNameFilter.java#L41

We wonder if there is any way to do override this definition to avoid renaming our thousands of test files ending with "TestIT".

Thanks in advance!

**Comment by sbrannen** [comment]
> We wonder if there is any way to do override this definition to avoid renaming our thousands of test files ending with "TestIT".

Yes. Use `@IncludeClassNamePatterns` to supply your own custom class name pattern.

**Comment by marcphilipp** [comment]
Sam beat me to it.

It's documented in the [Javadoc of `@Suite`](https://junit.org/junit5/docs/current/api/org.junit.platform.suite.api/org/junit/platform/suite/api/Suite.html):

> When the [@IncludeClassNamePatterns](https://junit.org/junit5/docs/current/api/org.junit.platform.suite.api/org/junit/platform/suite/api/IncludeClassNamePatterns.html) annotation is not present, the default include pattern ["^(Test.*|.+[.$]Test.*|.*Tests?)$"](https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/discovery/ClassNameFilter.html#STANDARD_INCLUDE_PATTERN) will be used in order to avoid loading classes unnecessarily (see [ClassNameFilter#STANDARD_INCLUDE_PATTERN](https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/discovery/ClassNameFilter.html#STANDARD_INCLUDE_PATTERN)).
