### ISSUE TITLE
Set a custom extension for `@TempDir` via a configuration parameter

### ISSUE THREAD

**Issue by scordio** [junit-team/junit5#2889]
Test suites using `@TempDir` usually pay a performance penalty due to the file system interaction. While this might be ok for a few tests, the penalty becomes more visible when the number of tests increases, like with AssertJ's [`Path`](https://github.com/assertj/assertj-core/tree/main/src/test/java/org/assertj/core/internal/paths) and [`File`](https://github.com/assertj/assertj-core/tree/main/src/test/java/org/assertj/core/internal/files) assertions tests.

Hitting the file system is probably not always needed, especially when working locally. An in-memory file system implementation might provide sufficient confidence and would run much faster, while the CI could verify the actual integration with a real file system.

For this reason, it would be nice if a custom extension could be set globally for the `@TempDir` annotation via a configuration parameter, similarly to the [Default Display Name Generator](https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator-default). Also, I'm not sure if this might be a different way to address #2400.

Supporting a custom extension would allow the use of in-memory file systems like [memoryfilesystem](https://github.com/marschall/memoryfilesystem) or [jimfs](https://github.com/google/jimfs), and setting that with a configuration parameter would not require the rewriting of existing test classes and methods which already rely on `@TempDir`.

I tried alternative strategies based on inheritance or test interfaces but I couldn't come up with something really satisfying, hence this feature request. 

## Deliverables

- [ ] A custom extension for the `@TempDir` annotation can be set globally via a configuration parameter.

**Comment by marcphilipp** [comment]
> Should I add a few lines in #2400 about this point?

Please do! 👍
