### ISSUE TITLE
@AfterAll swallows exceptions

### ISSUE THREAD

**Issue by armandino** [junit-team/junit5#2896]
I expected to see a failure when running the following code, but the error is not propagated up. My use case: I want to aggregate some data generated from a `@ParameterizedTest` and have an assertion in the `@AfterAll` method (maybe there is a better way to achieve this... open to suggestions).

```java
class Example {
    @AfterAll
    static void afterAll() {
        throw new RuntimeException("does not fail the test");
    }
}
```
For comparison, the following does fail as expected.

```java
    @AfterEach
    void tearDown() {
        throw new RuntimeException("fails the test");
    }
```

Using:
```xml
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>
```

**Comment by Cody-Banks7** [comment]
I‘ve met this problem too. What's more, Try-catch can still capture the excption in the method but is unable to throw it. If it's not intentionally designed this way, I would like to try to fix it

**Comment by Cody-Banks7** [comment]
Hey man , I just find out that It was designed this way on purpose. Although I haven't understood the intention of this design, the handbook did mention this part, you can check it on https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/LifecycleMethodExecutionExceptionHandler.html#implementation-guidelines.

**Comment by mpkorstanje** [comment]
@armandino to make sure the exception is swallowed by JUnit please use the [platform launcher API](https://junit.org/junit5/docs/current/user-guide/#launcher-api).

I assume you are currently using Surefire to run your tests. If so make sure you have the latest `3.0.0-Mx` version otherwise you may see things such as #2178 .

**Comment by armandino** [comment]
Thanks @mpkorstanje. Your mention of Surefire made me realise that it's actually working as expected using `3.0.0-M5`. The issue appears to be with Intellij. I reported it as a [bug](https://youtrack.jetbrains.com/issue/IDEA-292853/Intellij-does-not-propagate-errors-thrown-in-JUnit-5's-@AfterAll).
