### ISSUE TITLE
Please add additional assertion tests for java Optionals.

### ISSUE THREAD

**Issue by catshow** [junit-team/junit5#2903]
It would be nice to have some tests for Optional values that would check to see if the value is present or is empty.  If it is present then it should return the value.  Additional tests would have messages too.

Here is a sample.
```java
    public static void assertIsEmpty(@Nonnull Optional<?> optionalValue) {
        Assertions.assertNotNull(optionalValue);
        Assertions.assertTrue(optionalValue.isEmpty());
    }

    public static <T> T assertIsPresent(@Nonnull Optional<T> optionalValue) {
        Assertions.assertNotNull(optionalValue);
        Assertions.assertTrue(optionalValue.isPresent());
        return optionalValue.get();
    }

```

**Comment by mpkorstanje** [comment]
The JUnit docs recommend using assertion libraries when more expressive assertions are needed.

And I suppose that building an assertion library beyond what was needed to maintain feature paririty with JUnit 4 would be considered out of scope.

So can you provide a compelling reason why assertions specifically for optionals should be added?

https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions-third-party
> Even though the assertion facilities provided by JUnit Jupiter are sufficient for many testing scenarios, there are times when more power and additional functionality such as matchers are desired or required. In such cases, the JUnit team recommends the use of third-party assertion libraries such as AssertJ, Hamcrest, Truth, etc. Developers are therefore free to use the assertion library of their choice.

**Comment by catshow** [comment]
No problem. I will just use another library.
