### ISSUE TITLE
Colon should not be used as classpath argument separator on Windows for junit-platform-console

### ISSUE THREAD

**Issue by alopukhov** [junit-team/junit5#2905]
## Steps to reproduce
Provide absolute path for jar with test located on drive distinct from working dir. E.g.:
Lets use `junit-platform-console-standalone-1.8.2.jar` and jar with test classes `simple-test-case.jar` located in directory on `C:` drive.
Running `java -jar C:\dir\junit-platform-console-standalone-1.8.2.jar --scan-classpath -cp C:\dir\simple-test-case.jar` from working directory on `C:` drive will work and running it from other drive will not.

```
PS D:\Downloads> java -jar C:\dir\junit-platform-console-standalone-1.8.2.jar --scan-classpath -cp C:\dir\simple-test-case.jar --disable-ansi-colors --disable-banner
.
+-- JUnit Jupiter [OK]
'-- JUnit Vintage [OK]

Test run finished after 33 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]

PS D:\Downloads> C:
PS C:\WINDOWS\system32> java -jar C:\dir\junit-platform-console-standalone-1.8.2.jar --scan-classpath -cp C:\dir\simple-test-case.jar --disable-ansi-colors --disable-banner
Hi, junit
.
+-- JUnit Jupiter [OK]
| '-- AwesomeTest [OK]
|   '-- sayHi() [OK]
'-- JUnit Vintage [OK]

Test run finished after 59 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         0 tests failed          ]
```

## Context
 - Used versions: junit-platform-console-standalone 1.8.2
 - Operation system: Windows

## Reason
Colons char should not be used as path separator at https://github.com/junit-team/junit5/blob/r5.8.2/junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java on Windows environment

**Comment by sormuras** [comment]
Does quoting the value help?
- `... -cp "C:\dir\simple-test-case.jar" ...`

**Comment by sbrannen** [comment]
I'm not sure that quoting would help, since it seems that we always let PicoCLI split the input based on `;` or `:`.

We might have to make the splitting platform dependent here:

https://github.com/junit-team/junit5/blob/f58cd419755846f1476e8d15783438de8d7aede4/junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java#L74-L80

**Comment by alopukhov** [comment]
> Does quoting the value help?
> 
> * `... -cp "C:\dir\simple-test-case.jar" ...`
> 
> Or how does quoting in PowerShell work?

Nope. This way of quotation doesn't help.
Neither in ordinary "cmd".
Neither in git bash.
