### ISSUE TITLE
Introduce support for required and excluded engines in EngineIdFilter

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#291]
## Status Quo

`EngineIdFilter` is currently only used to _require_ a single `TestEngine` within the _entire_ test plan, which is very lacking in terms of support for multiple engines going forward.

As the number of engines supported on the JUnit Platform increases, users will need the ability to require one or more engines and to exclude one or more engines simultaneously.

## Related Issues

- #285 

## Deliverables

- [x] Convert `requireEngineId(String)` in `EngineIdFilter` to `requireEngines(String...)`.
- [x] Introduce `excludeEngines(String...)` in `EngineIdFilter`.

**Comment by jlink** [comment]
Why should you want to exclude an engine in a filter? Just exclude it from your test-runtime classpath.

**Comment by marcphilipp** [comment]
In theory that's true, of course. However, you might just want to run tests for one engine without commenting out all the code that uses another and removing the latter from your classpath. Another benefit is that adding the possibility to exclude an engine will make it symmetric to what you can do for tags in `TagFilter`.

**Comment by sbrannen** [comment]
_in progress_
