### ISSUE TITLE
Support instance fields as source for `@ValueSource`

### ISSUE THREAD

**Issue by arturmkr** [junit-team/junit5#2911]
Having following code:

```java
@AllArgsConstructor
class Car {
  int year;
  String model;
}

class CarTest {
  Car carOne = new Car(2021, "X3");
  Car carTwo = new Car(2005, "M5");

  @ParameterizedTest
  @ValueSource
  void testCar(Car car) {
    System.out.println(car.model);
  }
}
```

I would like to pass into `testCar()` method objects `carOne` and `carTwo` using `@ValueSource`.

Currently, there is no such option.

I have to create separate method, which returns `Stream<Arguments>` with `carOne` and `carTwo`.

It would be great to have an option to specify objects using `@ValueSource`, without creating additional method, something like this: `@ValueSource(objects = {carOne,carTwo})`.

**Comment by sbrannen** [comment]
> It would be great to have an option to specify objects using `@ValueSource`, without creating additional method, something like this: `@ValueSource(objects = {carOne,carTwo})`.

That's unfortunately not possible in Java: annotation attributes cannot reference fields.

What about straightforward use of `@MethodSource` as in the following?

```java
class CarTest {

	@ParameterizedTest
	@MethodSource
	void cars(Car car) {
		System.out.println(car.model());
	}

	static Stream<Car> cars() {
		return Stream.of(new Car(2021, "X3"), new Car(2005, "M5"));
	}

}

record Car(int year, String model) {
}
```

**Comment by marcphilipp** [comment]
**Team decision:** We think the current built-in possibilities of providing sources are sufficient. You could create your own `@FieldSource` annotation and `ArgumentsProvider` implementation or use dynamic tests.
