### ISSUE TITLE
Open up ExecutionRequest creation for external usage

### ISSUE THREAD

**Issue by alopukhov** [junit-team/junit5#2912]
Currently I'm working on a test engine that delegates work to other test engines.

Everything works great, except I have to use `ExecutionRequest`'s constructor which is marked as internal.

https://github.com/junit-team/junit5/blob/80bf93fd3cb841e76fc017dc759d8ef0df158d49/junit-platform-engine/src/main/java/org/junit/platform/engine/ExecutionRequest.java#L39-L41

So please add a _public_ way to instantiate `ExecutionRequest` or replace it with an interface like `EngineDiscoveryRequest`.

This will make variations of suite engine possible.

The other possibility is to directly test the `TestEngine#execute` method without using an internal API.

**Comment by sbrannen** [comment]
> So please add a _public_ way to instantiate `ExecutionRequest` or replace it with an interface like `EngineDiscoveryRequest`.

We cannot replace the class with an interface since it is an existing public type, but we could consider creating a static factory method for creating an instance of `ExecutionRequest` (if we don't make the existing constructor a public API).

> The other possibility is to directly test the `TestEngine#execute` method without using an internal API.

Could you please expound on that?

**Comment by alopukhov** [comment]
Thanks for responce @sbrannen 

> Could you please expound on that?

I mean testing test engines like this:
```java
TestEngine engine = new AcmeEngine();
EngineExecutionListener acmeListener = new AcmeTestListener();
ExecutionRequest request = createExecutionRequestUsingConstructorOrFactory(acmeListener);
engine.execute(request);
//some checks on listener.
```
In a ways similar to:
https://github.com/junit-team/junit5/blob/80bf93fd3cb841e76fc017dc759d8ef0df158d49/junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineExecutionTests.java#L797-L803

**Comment by sbrannen** [comment]
Thanks for the feedback, @alopukhov.

We'll discuss this within the team.

**Comment by marcphilipp** [comment]
**Team decision:** Introduce `ExecutionRequest.create` factory method.
