### ISSUE TITLE
Add Assumptions.assumeInstanceOf

### ISSUE THREAD

**Issue by HeaDHeaD0820** [junit-team/junit5#2926]
Similar to the case descirbed in [issue #2482](https://github.com/junit-team/junit5/issues/2482), I also hope to skip large tests if the target object is even not of expected type, I suggest that ``assumeInstanceOf`` should be introduced.

Before conducting further tests, a validation for expected type with ``assumeInstanceOf`` can skip the tests that produce an unneccessary exception due to the wrong type. For a value potentially of several different types, using such assumptions can flexibly abort those tests not suitable for some type of the value. So it would be better if  ``Assumptions.assumeInstanceOf`` is available here similar to ``Assertions.assertInstanceOf``.

I'm quite willing to work on this feature myself and upload my pull request if accepted : )

**Comment by marcphilipp** [comment]
**Team decision:** Thanks for the proposal but we think `assumeTrue(o instanceof Foo)` is sufficiently short. If you need this a lot we recommend adding a custom assumption method to your project.

**Comment by HeaDHeaD0820** [comment]
Thanks! That makes sense : )
