### ISSUE TITLE
Decide the fate of ReportEntry.appendDescription()

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#293]
## Status Quo

`ReportEntry` currently has two `appendDescription()` methods.

- `appendDescription(Appendable, String)` appears to exist solely for the purpose of generating XML reports in `XmlReportWriter`.
- `appendDescription(Appendable)` is used in `ColoredPrintingTestListener` and `JUnit5RunnerListener`, but these invocations of `appendDescription(Appendable)` could likely be replaced with `ReportEntry#toString()` which includes the same information in a different format.

## Deliverables

- [x]  Decide the fate of both `ReportEntry.appendDescription()` methods (i.e., whether we need them in `ReportEntry` at all, whether the custom formatting logic could be moved to `XmlReportWriter`, etc.)
- [x] Either document the formatting logic in `appendDescription(Appendable, String)` or delete both variants

**Comment by sbrannen** [comment]
@mmerdes, I have assigned this issue to you for the time being.

**Comment by mmerdes** [comment]
in progress

**Comment by sbrannen** [comment]
Closing this issue since all points have been addressed in `master`.
