### ISSUE TITLE
Fix inefficient regular expression in ReflectionUtils

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#2950]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/214207/175013702-508a72b8-ad7a-416d-8263-4c20b4518230.png">

Tracking issue for:
- [ ] https://github.com/junit-team/junit5/security/code-scanning/1

**Comment by marcphilipp** [comment]
https://github.com/junit-team/junit5/blob/5451651b16e5714bad4b89326696012b215c1ccd/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java#L118

**Comment by sbrannen** [comment]
> From what I can tell, the RegEx does exactly what it's supposed to do, and I'm not sure that we can rewrite the RegEx to achieve the same goal (disclaimer: I am not a RegEx expert or a "Regexpert").

It turns out that we can use a [possessive quantifier](https://www.regular-expressions.info/possessive.html) to address the issue, and we should be expecting a PR from @michael-simons.
