### ISSUE TITLE
The JUnit 5 build must be executed with Java 17. Currently executing with Java 18.

### ISSUE THREAD

**Issue by prepstarr** [junit-team/junit5#2954]
## Steps to reproduce

follow the instructions, prompts and suggestions of java to upgrade to the latest version and then after try to install JUNIT. 

## Context

It's only natural that a programmer would want to be up to date , there may be a way that JUnit could be structured that it still functions with a latest version of Java even if it is not kept up to date.

**Comment by sbrannen** [comment]
> there may be a way that JUnit could be structured that it still functions with a latest version of Java even if it is not kept up to date.

That's not always possible. In fact it's probably impossible.

The build relies on tools being able to support new versions of Java.

For example, if the version of Gradle in use does not support Java 18, then Java 18 is not an option for running the build.

See the [Gradle compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html) for details.

Note, however, that we already test against Java 18, 19, and 20, as can be see in this recent commit (https://github.com/junit-team/junit5/commit/23910c857f1842a6b6172969b631450d7466738a).

In light of that, I am closing this issue.
