### ISSUE TITLE
Maintain list of third-party TestEngines and Extensions

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#297]
For maintainers and users of the framework, we want to have a list of third-party engines and extensions in the wiki ~or on the website~.

## Test Engines
- [Specsy](http://specsy.org/)
- [Spek](https://github.com/JetBrains/spek)
- [Cucumber](https://github.com/signed/junit-cucumber-engine)

## Extensions
- [SpringExtension](https://github.com/sbrannen/spring-test-junit5)
- [upREST](https://github.com/selesy/uprest)
- [JUnit 5 Docker](https://faustxvi.github.io/junit5-docker/)
- [JGiven](https://github.com/TNG/JGiven/tree/junit5/jgiven-junit5)

**Comment by sbrannen** [comment]
I think we should also maintain a list of third-party extensions.

Would you like to tack that onto this issue or create a separate one?

**Comment by marcphilipp** [comment]
I've rephrased the title of the issue to also include extensions.

**Comment by sbrannen** [comment]
Added Spek to the list of test engine.

**Comment by jbduncan** [comment]
[JUnit Io](https://github.com/CodeFX-org/junit-io) should probably be added to this list. :)

**Comment by FaustXVI** [comment]
I'd love to see the [docker extension](https://github.com/FaustXVI/junit5-docker) added to this list :)

**Comment by sbrannen** [comment]
I added JUnit 5 Docker to this issue's description.

**Comment by sbrannen** [comment]
Added link to JGiven

**Comment by sbrannen** [comment]
Added link to junit-cucumber-engine

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I've restructured the wiki a bit, added a custom sidebar, and made it editable by any GitHub user.

**Comment by marcphilipp** [comment]
The new page documenting third-party extensions is available at https://github.com/junit-team/junit5/wiki/Third-party-Extensions.

**Comment by jbduncan** [comment]
I'm not sure meeting if editable by any GitHub user is such a good idea.

When I went to try to edit the wiki just now, i found that I had permission to **delete** pages. That sounds rather dangerous to me.

Does GitHub have a mechanism to force wiki changes to be reviewed by someone on the JUnit team before they can be pushed through?

**Comment by marcphilipp** [comment]
> I'm not sure if making the wiki editable by any GitHub user is such a good idea.
> 
> When I went to try to edit the wiki just now, i found that I had permission to delete pages. That sounds rather dangerous to me.

It's all in a Git repo so even when someone deletes something it's not gone forever. We have been using this for JUnit 4 for quite a while and nothing bad has happened so far.

> Does GitHub have a mechanism to force wiki changes to be reviewed by someone on the JUnit team before they can be pushed through?

Unfortunately, no.

**Comment by jbduncan** [comment]
> It's all in a Git repo so even when someone deletes something it's not gone forever. We have been using this for JUnit 4 for quite a while and nothing bad has happened so far.

Oh good! In that case I have no problem with the wiki being made publicly editable. Even though there's no mechanism to enforce reviews of potential wiki changes, I'm satisfied knowing that changes can be reverted.
