### ISSUE TITLE
BUG: Post Discovery Filtering fails when an engine has no test descriptor to filter from

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#298]
This will, for example, lead to an exception when running JUnit5 only tests through Gradle and using `requireTag`, because due to #285 the junit4 engine is always present.

**Comment by marcphilipp** [comment]
By "no test descriptor to filter from" you mean the engine's descriptor has no children, right?

**Comment by jlink** [comment]
No childrean after discovery, yes.

**Comment by marcphilipp** [comment]
Ok, thanks for reporting! I'll look into it right away.

**Comment by marcphilipp** [comment]
@jlink The bug has been fixed. Please try using the latest SNAPSHOTs and see if it's fixed for you, too.

**Comment by jlink** [comment]
works. tx.

2016-06-09 9:43 GMT+02:00 Marc Philipp <notifications@github.com>:
