### ISSUE TITLE
passing parameterised test arguments into @BeforeEach fails when run in parallel

### ISSUE THREAD

**Issue by jflorez-planittesting** [junit-team/junit5#2983]
junit-version: 5.8.2
junit-launcher-version: 1.8.2

I'm using the solution from https://code-case.hashnode.dev/how-to-pass-parameterized-test-parameters-to-beforeeachaftereach-method-in-junit5 to pass @ParameterizedTest arguments into @BeforeEach

I'm doing this to be able to create a test where I can use an annotation to specify one or more browsers for a selenium test.
Full code can be found here:
https://github.com/jflorez-planittesting/junit5-parallel-multibrowser-bug

## Steps to reproduce
1. Clone https://github.com/jflorez-planittesting/junit5-parallel-multibrowser-bug 
2. set properties->parallel-test to false in the pom.xml 
3. run mvn test. This will show you the expected behaviour4. 
4. set properties->parallel-test to true in the pom.xml
5. run mvn test. This will demonstrate the problem when running in parallel

## Context

- junti-plaform version: 1.8.2
- IDE vscode but example of the bug can be run with maven
- JDK 17
- maven 3.8.6

## Deliverables

- https://github.com/jflorez-planittesting/junit5-parallel-multibrowser-bug

**Comment by sbrannen** [comment]
Reliance on `JupiterTestEngine` internals is not supported.

In any case, it appears that your `BrowserParameterResolver` implementation is not thread safe.

What happens if you change the `parameterisedTestParameterResolver` field to a `ThreadLocal`?

**Comment by jflorez-planittesting** [comment]
Thanks that pointed me in the right direction. Instead of a threadlocal I'm using **private Map<String, ParameterResolver> parameterisedTestParameterResolvers = new HashMap<>()** and use the test display name as the map key. This solved the issue and I now get all browsers in parallel as expected. Using the display name is not ideal and will replace it with a better test identifier but for now this fixes the reason for this but report
