### ISSUE TITLE
Polish discovery package in the junit5-engine

### ISSUE THREAD

**Issue by mmerdes** [junit-team/junit5#299]
- [x] reduce public visibility
- [x] introduce sub-package for predicates
- [x] introduce unit tests for predicates

**Comment by mmerdes** [comment]
in progress

**Comment by sbrannen** [comment]
Is the scope of this issue limited to the `discovery` package in the `junit5-engine`?

Or does this issue apply to the `discovery` package in the `junit-engine-api` as well?

**Comment by mmerdes** [comment]
no, the `discovery` package in the `api` is not included in this issue
