### ISSUE TITLE
gradlew clean assemble with Java 18

### ISSUE THREAD

**Issue by prepstarr** [junit-team/junit5#2996]
## Steps to reproduce

Install the latest recommended version of Java on Java.com

download the latest version of Junit 5 from github repository using git. 

type gradlew clean assemble and watch it fail

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.9.1 or latest of everything
 - Build Tool/IDE: git, powershell

## Deliverables

- [ ] ... nothing just a failed program that wants you to revert to the 1990s. Everyone complains that we need to be up to date , move forward but then when we finally do and get our game up to gear the people do everything in their power to drag us back down, tell us to revert, say we were only kidding and that you should stay where you were, the latest is not available yet, etc. and whatever other clever tactful hurtful excuse there is to just say well we were just looking to get under your skin, be like a hyena attacking a tiger and take a bit of a poke at you...

here is the error:

what's involved to fix this error (bug) and why can't it run on Java 18 ?

PS E:\can\junit5> ./gradlew clean assemble

FAILURE: Build failed with an exception.

* Where:
Settings file 'E:\can\junit5\settings.gradle.kts' line: 92

* What went wrong:
The JUnit 5 build must be executed with Java 17. Currently executing with Java 18.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

A build scan was not published as you have not authenticated with server 'ge.junit.org'.
For more information, please see https://gradle.com/help/gradle-authenticating-with-gradle-enterprise.

**Comment by prepstarr** [comment]
it's definitely holding me back, because I want to be able to work with this application . It's not a gradle issue also cause Gradle 7.5 works with Java 18.

**Comment by prepstarr** [comment]
vi E:\can\junit5\settings.gradle.kts I just edited this file and removed the check hopefully that's enough to make it work...

**Comment by prepstarr** [comment]
so I will suggest the change and hopefully you can commit I don't need a check on mine but I presume others do so I will make it Java 18 should this work...

**Comment by sormuras** [comment]
17 is 17, not 18: https://github.com/junit-team/junit5#building-from-source

![image](https://user-images.githubusercontent.com/2319838/183300009-6faad3a5-6fb7-47ee-81c5-39cc0f7843e1.png)

You may run Gradle on 17 and compile sources with 18, 19, and 20 as shown here: https://github.com/junit-team/junit5/blob/main/.github/workflows/cross-version.yml

**Comment by prepstarr** [comment]
I fixed the code so we should the documentation as well...

**Comment by prepstarr** [comment]
I need you to approve my pull request and secondly where do we edit this piece of documentation to reflect today's news?

**Comment by prepstarr** [comment]
https://github.com/junit-team/junit5/pull/2998 this fixes the documentation so please kindly approve

https://github.com/junit-team/junit5/pull/2997 this fixes the build error on Java 18.

**Comment by marcphilipp** [comment]
The build will stay on JDK 17 for the time being since it's an LTS release.
