### ISSUE TITLE
Achieve Cross Browser Testing at TestPlan level 

### ISSUE THREAD

**Issue by karanshah-browserstack** [junit-team/junit5#2999]
Hi, 
We want to achieve Cross Browser Testing with Junit5 and run it in parallel. 
We checked the documentation but the solution is only possible via adding @TestTemplate or @Parameterized tests which will modify the number of times it could be run. 
This can be achieved in TestNG by modifying testng.xml and also using their AlterSuiteListeners.

We want to know the recommended way/approach to achieve Cross Browser testing at the TestPlan level or using Service Loaders.

**Comment by sormuras** [comment]
Hi Karan Shah, did you find a solution that works for you in the meantime? If yes, do you care to share it with us?

If not, what are you referring to with "Cross Browser testing at the TestPlan level or using Service Loaders"?
Did you take a look at https://bonigarcia.dev/selenium-jupiter project or other existing extensions, possibly listed at https://github.com/junit-team/junit5/wiki/Third-party-Extensions ?

**Comment by karanshah-browserstack** [comment]
@sormuras Will check this out and update on this.
