### ISSUE TITLE
Improve documentation for extension registration via `@ExtendWith` on fields

### ISSUE THREAD

**Issue by abelsromero** [junit-team/junit5#3004]
## Steps to reproduce

I am trying to do the same as shown in documentation in https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic, where the following example appears:

```java


@Target({ ElementType.FIELD, ElementType.PARAMETER })
@Retention(RetentionPolicy.RUNTIME)
@ExtendWith(RandomNumberExtension.class)
public @interface Random {
}

class RandomNumberDemo {

    // use random number field in test methods and @BeforeEach
    // or @AfterEach lifecycle methods
    @Random
    private int randomNumber1;

/* . . . */

}
```

However, my extension (only implements `BeforeAllCallback`) only gets invoked when `private int randomNumber1;` is made static `private static int randomNumber1;`.
I don't know if this is an issue with the code or the documentation. Any clarifications would be appreciated.

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.9.0
 - Build Tool/IDE: Maven & IntelliJ

**Comment by abelsromero** [comment]
> However, we could revisit this behavior if you really think it's in need of change (and if it's feasible to change the behavior).

I'd be convenient, but now that I understand the issue, to me this is just a docs improvement.

For context, I could manage it with static but it didn't occur to me that the field needed to be static by design, the docs didn't help me much and I even checked the code in this repo, but without an implementation of the `RandomNumberExtension` I could not confirm if this was expected. The implementation added in the comment could be added for reference.
On another read through and knowing more of the internals I now understand this line in https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic-static-fields `Extensions registered via static fields may therefore implement class-level and instance-level extension APIs such as BeforeAllCallback`.

**Comment by marcphilipp** [comment]
**Team Decision:** Publish the code from https://github.com/junit-team/junit5/issues/3004#issuecomment-1215045050 as part of the documentation project and link to it from the User Guide with a disclaimer that it's an example rather than the definitive way of generating random numbers for tests.

**Comment by sbrannen** [comment]
@abelsromero, does this [new section of the User Guide](https://junit.org/junit5/docs/snapshot/user-guide/index.html#extensions-RandomNumberExtension) meet your needs?

**Comment by abelsromero** [comment]
Awesome, thanks!

**Comment by sbrannen** [comment]
> Awesome, thanks!

Glad to hear it. Thanks for providing feedback.
