### ISSUE TITLE
Document that class ordering is not honored for parallel execution for top-level classes

### ISSUE THREAD

**Issue by hikoma** [junit-team/junit5#3007]
## Steps to reproduce

Test classes

```
public class Test1 {
    @Test
    void test() throws Exception { Thread.sleep(1000); }
}

public class Test2 {
    @Test
    void test() throws Exception { Thread.sleep(1000); }
}

public class Test3 {
    @Test
    void test() throws Exception { Thread.sleep(1000); }
}
```

junit-platform.properties

```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.classes.default=concurrent
junit.jupiter.execution.parallel.config.strategy=fixed
junit.jupiter.execution.parallel.config.fixed.parallelism=2
junit.jupiter.testclass.order.default=org.junit.jupiter.api.ClassOrderer$ClassName
```

If you run all tests, Test1 and Test3 run first.
I expect that Test1 and Test2 run first.

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.9.0
 - Build Tool/IDE: Maven, Gradle

## Deliverables

- [ ] ...

**Comment by polyanskih** [comment]
seems that it's also actual for 
`junit.jupiter.testclass.order.default = org.junit.jupiter.api.ClassOrderer$OrderAnnotation`
class with 
@Order(DEFAULT)
may run earlier than class with
@Order(MAX_VALUE)

**Comment by polyanskih** [comment]
and even if class marked with `@Isolated`
**junit-platform.properties**
```
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.classes.default = concurrent
junit.jupiter.execution.parallel.mode.default = concurrent
junit.jupiter.execution.parallel.config.strategy = custom
junit.jupiter.execution.parallel.config.custom.class = com.example.tests.junit.CustomJunitStrategy
junit.jupiter.testclass.order.default = org.junit.jupiter.api.ClassOrderer$OrderAnnotation
```
**CustomJunitStrategy.java**
```
package com.example.tests.junit;

import org.junit.platform.engine.ConfigurationParameters;
import org.junit.platform.engine.support.hierarchical.ParallelExecutionConfiguration;
import org.junit.platform.engine.support.hierarchical.ParallelExecutionConfigurationStrategy;

public class CustomJunitStrategy implements ParallelExecutionConfiguration, ParallelExecutionConfigurationStrategy {
    private final int THREADS_COMMON_COUNT = 6;

    @Override
    public int getParallelism() {
        return THREADS_COMMON_COUNT;
    }

    @Override
    public int getMinimumRunnable() {
        return THREADS_COMMON_COUNT;
    }

    @Override
    public int getMaxPoolSize() {
        return THREADS_COMMON_COUNT;
    }

    @Override
    public int getCorePoolSize() {
        return THREADS_COMMON_COUNT;
    }

    @Override
    public int getKeepAliveSeconds() {
        return 30;
    }

    @Override
    public ParallelExecutionConfiguration createConfiguration(ConfigurationParameters configurationParameters) {
        return this;
    }
}

```

**Comment by nbrugger-tgm** [comment]
Hm for me (just user) my custom class ordering works for classes with `@Isolated` 
```properties
junit.jupiter.execution.parallel.enabled=false
junit.jupiter.execution.parallel.mode.classes.default=concurrent
#multiple concurrent methods in the same class break shared mocks
junit.jupiter.execution.parallel.mode.default=single_thread
junit.jupiter.testclass.order.default=com.niton.MyVeryCustomClassOrderer
```

**Comment by marcphilipp** [comment]
@hikoma While classes are ordered during discovery with the configured "orderer", at execution time all test classes are submitted in this order to the underlying `ForkJoinPool`. In which order that will schedule them is outside of our control.

**Team decision:** Document that class ordering is not honored for parallel execution for top-level classes (similar to what's documented for `MethodOrderer`).

**Comment by nbrugger-tgm** [comment]
@marcphilipp Is it intended to work with `@Isolated`? And in the case of `@ResourceLock()` where the classes are executed in a parallel context but a specific ResourceLock "group" is run sequentially, will/is the order ensured for the sequential running classes? (if not that would be awesome)

Does this mean the case explained above is just "luck to be in the right order"?

**Comment by hikoma** [comment]
@marcphilipp I see, so that's what was going on. Thank you for taking the time to consider this issue.

**Comment by marcphilipp** [comment]
@nbrugger-tgm It might work with `@Isolated`/`@ResourceLock` but that's also outside our control since the `ForkJoinPool` is in charge of scheduling tasks. It's unlikely that will change in a future version but I don't think we can guarantee that.
