### ISSUE TITLE
Introduce `@SelectMethod` for selecting methods in `@Suite` classes

### ISSUE THREAD

**Issue by dominikozi** [junit-team/junit5#3012]
Feature request to add support to filtering test methods by name in test suites. This could be done by annotation similar to @SelectClasses where user could specify list of method names. This could then be used when tests to run are determined during runtime and there is no possibility to add tags.

**Comment by dominikozi** [comment]
Example: 

There are two test classes

```
public class A(){
	@Test
	public void firstA(){...}
	@Test
	public void secondA(){...}
}

public class B(){
	@Test
	public void firstB(){...}
	@Test
	public void secondB(){...}
}
```

I need to generate a test suite during execution of my program that will only run some of avabile methods(which will be chosen during runtime), for example : firstA() and secondB() or secondA(), firstB(). In this scenario tagging will not work as I can not modify test classes code.

If this gets implemented it could for **example** look like this: 

@SelectMethods ({"com.example.junit5.examples.A.firstA", 
"com.example.junit5.examples.B.secondB"})

**Comment by Mohammed-2002** [comment]
Hey guys! I'm a college student an I really want to solve  issue 3012  "Allow filtering methods by name in test suites" to improve my skills in Java and Kotlin, I just don't know which class(es) is/are responsible for filtering classes during running suits test, in other terms which classes be called when looking for the selected classes @selectclasses()? and running the selected tests?, I want to see it as an example so I can start on that issue, any one who can give me some explanation? I would be very thankful!

**Comment by mpkorstanje** [comment]
@Mohammed-2002 if you do a usage search for the `SelectClasses` annotation you can find all the code that directly touches it. Then sprinkle a few breakpoints around and run the tests. That should get  you most if not all of the interactions.

So in this case you would have to look here:

https://github.com/junit-team/junit5/blob/3ba144efdb38181d13132a552988e69c35c619a2/junit-platform-suite-commons/src/main/java/org/junit/platform/suite/commons/SuiteLauncherDiscoveryRequestBuilder.java#L149-L151

**Comment by Mohammed-2002** [comment]
thank you for your answer! 
i found a solution for this problem but i don't know if it is the best. see the code below. 
import org.junit.platform.engine.TestExecutionResult;
import org.junit.platform.engine.TestExecutionResult.Status;
import org.junit.platform.engine.TestExecutionListener;
import org.junit.platform.engine.TestIdentifier;

import java.util.Arrays;
import java.util.List;

public class CustomTestExecutionListener implements TestExecutionListener {

    private List<String> selectedMethods;

    public CustomTestExecutionListener(String[] selectedMethods) {
        this.selectedMethods = Arrays.asList(selectedMethods);
    }

    @Override
    public void executionStarted(TestIdentifier testIdentifier) {
        if (shouldRun(testIdentifier)) {
            System.out.println("Running test: " + testIdentifier.getDisplayName());
        } else {
            System.out.println("Skipping test: " + testIdentifier.getDisplayName());
            throw new TestAbortedException("Test not selected");
        }
    }

    private boolean shouldRun(TestIdentifier testIdentifier) {
        if (testIdentifier.isTest()) {
            String methodName = testIdentifier.getDisplayName().split("\\(")[0];
            return selectedMethods.contains(methodName);
        }
        return true;
    }

    @Override
    public void executionFinished(TestIdentifier testIdentifier, TestExecutionResult testExecutionResult) {
        if (shouldRun(testIdentifier)) {
            System.out.println("Test result: " + testExecutionResult.getStatus());
        }
    }

}
as an example: 
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(CustomTestExecutionListener.class)
public class ExampleTest {

    @Test
    public void firstA() {
        System.out.println("firstA");
    }

    @Test
    public void secondA() {
        System.out.println("secondA");
    }

    @Test
    public void firstB() {
        System.out.println("firstB");
    }

    @Test
    public void secondB() {
        System.out.println("secondB");
    }
}
i would use 
@ExtendWith(CustomTestExecutionListener.class)
@SelectMethods({"firstA", "secondB"})
to run the selected methodes. is this a good solution?

**Comment by Mohammed-2002** [comment]
@mpkorstanje , Another solution is making a new implementation of the 'TestExecutionEngine' interface: here is the code:
import org.junit.platform.engine.*;
import org.junit.platform.engine.discovery.*;
import org.junit.platform.engine.execution.*;
import org.junit.platform.engine.support.descriptor.*;
import org.junit.platform.launcher.*;
import org.junit.platform.launcher.core.*;
import org.junit.platform.launcher.listeners.*;
import org.junit.platform.launcher.listeners.SummaryGeneratingListener;
import org.junit.platform.launcher.tagexpression.*;
import org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder;

import java.util.*;
import java.util.stream.*;

public class CustomTestExecutionMode implements TestExecutionEngine {

    private LauncherDiscoveryRequest request;
    private SummaryGeneratingListener listener;

    @Override
    public String getId() {
        return "custom";
    }

    @Override
    public TestDescriptor discover(EngineDiscoveryRequest request, UniqueId uniqueId) {
        TestDescriptor testDescriptor = new TestDescriptor(uniqueId, "custom");
        testDescriptor.setType(TestDescriptor.Type.CONTAINER);
        request.getSelectorsByType(MethodSelector.class).stream().map(selector -> {
            String className = selector.getClassName();
            String methodName = selector.getMethodName();
            return new TestIdentifier(uniqueId.append("method", className, methodName), className + "#" + methodName);
        }).forEach(testDescriptor::addChild);
        return testDescriptor;
    }

    @Override
    public void execute(LauncherDiscoveryRequest request, TestPlan testPlan, Launcher launcher) {
        this.request = request;
        this.listener = new SummaryGeneratingListener();
        launcher.registerTestExecutionListeners(listener);
        request.getSelectorsByType(MethodSelector.class).stream().map(selector -> {
            String className = selector.getClassName();
            String methodName = selector.getMethodName();
            return testPlan.getTestIdentifier(uniqueId -> {
                if (uniqueId.getSegmentCount() == 3 && uniqueId.getSegments().get(0).getType().equals(TestDescriptor.Type.CONTAINER) && uniqueId.getSegments().get(1).getType().equals(TestDescriptor.Type.CONTAINER) && uniqueId.getSegments().get(1).getUniqueId().toString().equals(className) && uniqueId.getSegments().get(2).getUniqueId().toString().equals(methodName)) {
                    return true;
                } else {
                    return false;
                }
            });
        }).filter(Optional::isPresent).map(Optional::get).forEach(identifier -> {
            launcher.execute(request, ExecutionFilter.forExactTestMethod(identifier.getUniqueId()));
        });
    }

    public static void main(String[] args) {
        LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
                .selectors(selectClass(ABTestSuite.class))
                .build();

        TestExecutionEngine engine = new CustomTestExecutionMode();

        Launcher launcher = LauncherFactory.create();
        launcher.registerTestExecutionListeners(new ConsoleTestExecutionListener());
        launcher.execute(request, engine);
    }
}
an example how to use it:
@Suite
@SelectMethods({"com.example.junit5.examples.A.firstA",
                "com.example.junit5.examples.B.secondB"})
public class ABTestSuite {
    // ...
}
is this a better solution?

**Comment by mpkorstanje** [comment]
Those are both pretty clever ideas but you are looking in the wrong location. 

JUnit 5 consists of four parts. There is the JUnit Platform and three test engine implementations on that platform. The Jupiter, Vintage and Suite Engines.

To discover tests JUnit 5 uses  `DiscoverySelector`s. These are bundled in a discovery request and passed onto the engines. The engines the report back with the tests they discovered.

The trick behind the Suite Engine is that it is a test engine that uses the JUnit Platform to discover tests. It doesn't run or execute any tests itself.

To do this the Suite Engine transforms annotations on a class into a discovery request for the JUnit Platform. This is what happens in the `SuiteLauncherDiscoveryRequestBuilder`.

To make a `@SelectMethod` annotation work you would have to transform that annotation into a `MethodSelector` (a discovery selector). You would have to do this mapping in the `SuiteLauncherDiscoveryRequestBuilder`. You can also look at the `SuiteLauncherDiscoveryRequestBuilderTests` for plenty of examples of this mapping.

**Comment by Mohammed-2002** [comment]
Thank u for your response!
Here is what I did: 
- I added this code to the constructor suite
"findAnnotationValues(suiteClass, SelectMethods.class, SelectMethods::value)
				.map(this::selectMethods)
				.ifPresent(this::selectors);
"
here is the implementation for the function 'selectMethods' 
"	private List<DiscoverySelector> selectMethods(String... methodPath) {
		List<DiscoverySelector> selectors = new ArrayList<>();

		for (String methodPathString: methodPath) {
			String[] methodData = getClassNameAndMethodName(methodPathString);
			selectors.add(DiscoverySelectors.selectMethod(methodData[0], methodData[1]));
		}

		return selectors;
	}

	private String[] getClassNameAndMethodName(String path) {
		String fileName = new File(path).getName();
		String className = fileName.substring(0, fileName.lastIndexOf("."));
		String methodName = className.substring(className.lastIndexOf("_") + 1);
		className = className.substring(0, className.lastIndexOf("_"));
		return new String[]{className, methodName};
	}" 
I juist don't know if this is optimal, when I use @selectMethod in combination with @selectClasses,would the tests I selected but don't exist in the arrayList of the selected class be run?

Here you can also find the interface selectMethods:
/**
 * {@code @SelectClasses} specifies the methods to <em>select</em> when running
 * a test suite on the JUnit Platform.
 *
 * @see org.junit.platform.runner.JUnitPlatform
 * @see org.junit.platform.engine.discovery.DiscoverySelectors#selectMethod(Class)
 */

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})

public @interface SelectMethods {

    /**
     * One or more methods to select.
     */

    String[] value();
}
@mpkorstanje Your advice please:)

**Comment by mpkorstanje** [comment]
This is going in the right direction. But I have quite a few comments on the execution.
So I think it would be more productive if you were to create a pull request. When creating it make sure to create it as a draft.

Please also have a look at https://github.com/junit-team/junit5/blob/main/CONTRIBUTING.md for the JUnits teams requirements for merging.

And do be sure to write tests and documentation. You can look at similar classes for an idea about the patterns to use.

**Comment by mpkorstanje** [comment]
You don't need the `getClassNameAndMethodName` method. If you look at the different `DiscoverySelectors.selectMethod` methods you'll find there is one that takes a fully qualified method name.

It's also worth thinking about the usability of the annotation. I don't think anyone would like to write out fully qualified class names. 

So `SelectMethod(javaClass = Example.class, methodName = "test", methodParameterTypes = "")` would be better. To select multiple methods, the annotation can be repeated.

This annotation could the be turned into a method selector using `MethodSelector.selectMethod(String className, String methodName, String methodParameterTypes)`.

**Comment by Mohammed-2002** [comment]
@mpkorstanje Thanks for your response! 
Here is how I updated it after your response!
I made two annotations, so the user can add more than one method.
`**@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
****
public @interface SelectMethods {

    /**
     * One or more methods to select.
     */
    SelectMethod[] value();
}
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})

public @interface SelectMethod {

    /**
     * The name of the method to select.
     */
    String name();

    /**
     * The parameter types of the method to select, in the form "int,String".
     */
    String parameterTypes() default "";

    /**
     * The return type of the method to select.
     */
    Class<?> returnType() default void.class;

}**
`
this is de code I added to the suite constructor:

`findAnnotationValues(suiteClass, SelectMethods.class, SelectMethods::value)
				.map(this::selectMethods)
				.ifPresent(this::selectors);`

this is the function 'selectMethods' : 

`private List<DiscoverySelector> selectMethods(SelectMethod... methods) {
		List<DiscoverySelector> selectors = new ArrayList<>();

		for (SelectMethod selectMethod: methods) {
			selectors.add(DiscoverySelectors.selectMethod(
					selectMethod.returnType().getName(),
					selectMethod.name(),
					selectMethod.parameterTypes()
			));
		}
		return selectors;
	}`
ps: I only fine the method `selectMethod` with `DiscoverySelectors`, not with `MethodSelector`.
This approach is much better than the previous one, if u also think so, I will write the documentation and some tests and create a pull request as u asked for.

**Comment by Mohammed-2002** [comment]
@mpkorstanje  a pull request is created ;)

**Comment by sbrannen** [comment]
I'm sorry that I didn't get a chance to review the PR before it got merged and closed this issue.

I've had a chance to look at the new feature now, and I am reopening this issue to discuss some things we should improve.

**Comment by sbrannen** [comment]
Aside from the name of the `clazz` attribute (which I think we should rename), having that attribute as the only way to specify the class is problematic because it is a `Class` reference. Consequently, the method you are trying to select must reside in a class that is either `public` or resides in the same package as the `@Suite` class, and those are restrictions we cannot impose on users.

That means we will at least have to introduce a way to define the class name as an alternative to the `Class` reference.

If you look at `DiscoverySelectors`, you will see that there are several overloaded variants of `selectMethod(...)`, and that's not by accident. The intent was to support multiple use cases -- both for Java-based testing frameworks and other types of testing frameworks that also have the concept of a method.

In light of that, I think we should focus on the use cases we need to support in the `@SelectMethod` annotation.

**Comment by sbrannen** [comment]
### Proposed Use Cases

1. `@SelectMethod("org.example.MyClass#myMethod")`
2. `@SelectMethod("org.example.MyClass#myMethod()")`
3. `@SelectMethod("org.example.MyClass#myOtherMethod(int, java.lang.String)")`
4. `@SelectMethod(javaClass = MyClass.class, name="myMethod")`
5. `@SelectMethod(javaClassName = "org.example.MyClass", name="myMethod")`
6. `@SelectMethod(javaClass = MyClass.class, name="myOtherMethod", parameterTypes = {int.class, String.class})`
7. `@SelectMethod(javaClassName = "org.example.MyClass", name="myOtherMethod", parameterTypes = {int.class, String.class})`
8. `@SelectMethod(javaClassName = "org.example.MyClass", name="myOtherMethod", parameterList = "int.class, java.lang.String")`
9. `@SelectMethod(javaClass = MyClass.class, name="myOtherMethod", parameterList = "int.class, java.lang.String")`

Use cases 1 through 3 are effectively the same use case: fully-qualified method names (FQMN).

Use case 4 is a type-safe alternative to using the FQMN as in use cases 1 and 2.

I included use case 5 for completeness, but it might not be very compelling in practice since it's more verbose than the equivalent `@SelectMethod("org.example.MyClass#myMethod")` (use case 1).

Use case 6 is the most user friendly when you know you are selecting Java methods **and** the class is `public` (or in the same package as the `@Suite` class). As a side note, it aligns directly with the signature of `ReflectionSupport.findMethod(Class<?>, String, Class<?>...)`, which is the best we can do in Java.

Use case 7 would address scenarios in which the class is not `public` (or in the same package as the `@Suite` class) **but** the parameter types happen to be visible to the `@Suite` class.

For use cases 8 and 9, I'm unsure how beneficial it would be to support supplying the parameter list as a single string, but I included it here for the sake of brainstorming.

**Comment by sbrannen** [comment]
To make the above proposal a bit more concrete, here's a sketch of what I think `@SelectMethod` should look like (with intentionally brief Javadoc solely for explanatory purposes).

_Please do not worry about validation of permissible attribute combinations, since that's an implementation detail._

```java
public @interface SelectMethod {

	/**
	 * Fully-qualified method name.
	 *
	 * <p>Cannot be combined with other attributes.
	 */
	String value() default "";

	/**
	 * Java {@link Class}.
	 *
	 * <p>Cannot be used in conjunction with {@link #className()}.
	 */
	Class<?> javaClass() default Class.class;

	/**
	 * Fully-qualified class name.
	 *
	 * <p>Cannot be used in conjunction with {@link #javaClass()}.
	 */
	String className() default "";

	/**
	 * Method name.
	 */
	String name();

	/**
	 * Parameter types.
	 */
	Class<?>[] parameterTypes() default {};

}
```

p.s. note that I opted for `className` instead of `javaClassName` here, but the names of the attributes are naturally up for debate.

**Comment by sbrannen** [comment]
As pointed out by @marcphilipp elsewhere, `@SelectClasses` also only allows a class to be selected via a `Class` reference.

Thus, if we decide to support class selection by name in `@SelectMethod`, we should do the same for `@SelectClasses` -- for example, via a new `String[] classNames() default {}` attribute.

**Comment by mpkorstanje** [comment]
@sbrannen I'm not following your line of reasoning in your last comment.

Is this an argument for using `javaClass/className` rather than `type/typeName` as annotation field names or for making `@SelectMethod` plural? I would not agree with the latter.

**Comment by marcphilipp** [comment]
**Team decision:**

* `@SelectMethod`: Change annotation as below
* `@SelectClasses`: Add `names: String[]` attribute that can be used in conjunction with or instead of `value`
* `DiscoverySelector.selectMethod`: Add overload that takes a vararg `Class<?>...` argument of parameter types

```java
public @interface SelectMethod {

	/**
	 * Fully-qualified method name.
	 *
	 * <p>Cannot be combined with other attributes.
	 */
	String value() default "";

	/**
	 * Java {@link Class}.
	 *
	 * <p>Cannot be used in conjunction with {@link #typeName()}.
	 */
	Class<?> type() default Class.class;

	/**
	 * Fully-qualified class name.
	 *
	 * <p>Cannot be used in conjunction with {@link #type()}.
	 */
	String typeName() default "";

	/**
	 * Method name.
	 */
	String name() default "";

	/**
	 * Parameter types.
	 *
	 * <p>Cannot be used in conjunction with {@link #parameterTypeNames()}.
	 */
	Class<?>[] parameterTypes() default {};

	/**
	 * Parameter type names.
	 *
	 * <p>Cannot be used in conjunction with {@link #parameterTypes()}.
	 */
	String parameterTypeNames() default "";

}
```

**Comment by sbrannen** [comment]
Action items from the above **Team Decision** will be addressed in the following dedicated issues.

- #3324
- #3325
- #3326

Since the initial implementation for `@SelectMethod` already exists on `main`, I am closing this issue.
