### ISSUE TITLE
Should ExecutableInvoker#invoke(Method, Object) run all extensions ?

### ISSUE THREAD

**Issue by ledoyen** [junit-team/junit5#3014]
Hello 👋 

Toying around with the new extension point `ExecutableInvoker`, I figured that `ExecutableInvoker#invoke(Method, Object)` does only run `ParameterResolver`s.

Should it not run all extensions applicable ?
My reasoning is the following:
* Any extension can have side effects (such as adding a closable resource into the extension context)
* If `ParameterResolver` extensions are executed, but the others are not, may the test not be in an inconsistent state ?

I can provide more utilization context if needed.

**Comment by sbrannen** [comment]
> Should it not run all extensions applicable ?

I'm not quite sure what you mean by "applicable".

So, yes, please expound with concrete use cases.

**Comment by marcphilipp** [comment]
**Team Decision:** `ExecutableInvoker` was introduced as a means to provide support for executing custom methods while reusing Jupiter's parameter resolution support. It's not meant to provide a way to run a test class or method with the full lifecycle.

We think the use case you outline in your extension is very interesting and think we should provide dedicated extension APIs to replace the classloader for a certain test classes or methods. The long-standing issue #201 is probably too abstract for that. Could you please raise a new dedicated feature request for your use case?

**Comment by sbrannen** [comment]
> We think the use case you outline in your extension is very interesting and think we should provide dedicated extension APIs to replace the classloader for a certain test classes or methods.

Providing dedicated `ClassLoader` APIs in Jupiter might also allow the Spring Framework to stop launching the entire JUnit Platform within an intercepted test method as can be see in the `@CompileWithTargetClassAccess` support in [this package](https://github.com/spring-projects/spring-framework/tree/main/spring-core-test/src/main/java/org/springframework/aot/test/generate/compile).

**Comment by ledoyen** [comment]
@marcphilipp , I tried to summarize the idea in #3028

Do not hesitate to modify the content if you feel that is necessary.
