### ISSUE TITLE
Test Smell: it is not a good practice to write a return statement in test case

### ISSUE THREAD

**Issue by TestSmell** [junit-team/junit5#3016]
Hi!

I notice that you write a test case with a return statement.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/110402847/187116950-cefb6fa4-3a84-42e7-ab6c-7466465f85db.png">

It is not a good idea to write the return statement in your test case.
Since, test cases should not return a value based on the corresponding definition.
So I would like to know if is it really a useful test case?
Maybe I think you should remove the @test annotation from this method or remove the return statement.

**Comment by sormuras** [comment]
Where did you find that test case?

Yes, I know where it is located - and I know why it is located there.

Are you a bot?

![image](https://user-images.githubusercontent.com/2319838/187128947-78555853-539d-44ef-8c7b-4b8459c4cf9c.png)
