### ISSUE TITLE
@sbrannen Sorry for replying only now, I just tried the case you wrote. If the DisableIfDemoTests class is executed, the expected effect can be achieved, but if the disabledIfTest method is executed, it will output: disabledIfTest.

### ISSUE THREAD

**Issue by darrenluo1993** [junit-team/junit5#3017]
https://user-images.githubusercontent.com/9458513/187624480-ad78e4c9-71a4-40ae-bfc1-3266a8074ad0.mp4

@sbrannen Sorry for replying only now, I just tried the case you wrote. If the DisableIfDemoTests class is executed, the expected effect can be achieved, but if the disabledIfTest method is executed, it will output: disabledIfTest.
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledIf;

public class DisableIfDemoTests {

	@Test
	@DisabledIf("customCondition")
	public void disabledIfTest() {
		System.err.println("disabledIfTest");
	}

	private boolean customCondition() {
		System.err.println("customCondition");
		return true;
	}

}
```

_Originally posted by @darrenluo1993 in https://github.com/junit-team/junit5/issues/3015#issuecomment-1232353208_

**Comment by sbrannen** [comment]
Please do not open a new issue simply to reply to an existing issue.

Thanks

**Comment by darrenluo1993** [comment]
Okay
> Please do not open a new issue simply to reply to an existing issue.
> 
> 
> 
> Thanks
