### ISSUE TITLE
Add a utility for iterating through combinations of arguments

### ISSUE THREAD

**Issue by bondolo** [junit-team/junit5#3018]
For parameterized tests that take multiple arguments `@MethodSource` is the currently the most commonly used approach for generating tests cases. If the arguments to the test are all the combinations of multiple enums or iterables then the resulting method is usually similar to the following:

```
Stream<Arguments> testCases() {
      List<Arguments> case = new ArrayList();
       for(State eachState : State.values()) {
           for (Model eachModel : Model.values()) {
               for (Colour eachColour : Colour.values()) {
                   for (boolean eachBoole : new boolean[] { false, true}) {
                       for (int eachInt = 1; eachInt < 5; eachInt++) {
                           cases.add(new Arguments(eachState, eachModel, eachColour, eachBoole, eachInt));
                       }
                   }
               }
          }
      }
      return cases.stream();
  ```

The intention is to provide a utility that allows this same logic to be expressed more concisely as:

```
 return fromSources(State.class, Model.class, Colour.class, Boolean.class, IntStream.range(1, 5));
```

**Comment by marcphilipp** [comment]
Have you asked the JUnit Pioneer maintainers if they would consider including this since their `@CartesionTest` extension does something very similar using annotations?

**Comment by sormuras** [comment]
➡️ https://junit-pioneer.org/docs/cartesian-product/

**Comment by bondolo** [comment]
I have to admit I was entirely unaware of JUnit Pioneer. In part my decision to structure the API as a single static method was to make it easier to justify inclusion in the baseline API. (Heck, some don't even consider "params" part of the core). I will take a closer look at what their Cartesian product annotation does but it seem likely it doesn't quite do everything this proposal does because of the limitations of annotations; only constant expression values can be included as arguments to annotations where as this features allows constant values as well as any iterable type.

**Comment by Bukama** [comment]
@bondolo When you have took time to review the Pioneer documentation (link see above) and think it's close then feel free to contact us over at: https://github.com/junit-pioneer/junit-pioneer/

**Comment by marcphilipp** [comment]
@bondolo Any updates?

**Comment by bondolo** [comment]
I took a look at the Pioneer cartesian product annotation and not surprisingly there is a lot of overlap. It would handle about 60-70% of the tests that I am currently using with method source. For the remainder, the argument dimension is usually something that is computed, such as powers of two. (My exemplar for this work is a set of unit test for a graphics library so powers of two often figures in to test case parameters). `IntStream.range(0, Integer.BITS).map( x -> 1 << x)` . Some of the smaller cases could easily use `CartesianTest.Values` but there is a loss of expressiveness in not being able to use any stream/iterable as a source.

I do like some elements of the `CartesianTest` approach, the annotations on test arguments are clearer mapping of the test values to the source for those values. I don't like that I can't use standard `@Test` annotation. My general reaction though is why not put both CartesianTest and my proposal in to the main `org.junit.jupiter.params` module?  They are both smallish in code size and reasonable in API surface-area. I was unaware, like most JUnit users I believe, of the Pioneer project and the intended role of the project relative to JUnit Jupiter is unclear. If `CartesianTest` were in the JUnit params module I would probably use it in some cases, but will also probably continue to use the feature I have proposed for more complicated or computed argument sets.

If there is no interest in the contribution here I will probably still try to suggest it for Pioneer so that it at least available to others. I don't want to publish it as a module myself.

**Comment by bondolo** [comment]
Any further thoughts on this proposal?

**Comment by vlsi** [comment]
For reference, here's a cartesian + filter from pgjdbc: https://github.com/pgjdbc/pgjdbc/blob/REL42.5.1/pgjdbc/src/test/java/org/postgresql/test/jdbc2/AutoRollbackTestSuite.java#L181

**Comment by marcphilipp** [comment]
**Team decision:** Revisit for 5.11

**Comment by marcphilipp** [comment]
**Team decision:** We are not convinced a simple utility method would be sufficient. As demonstrated in the code linked from https://github.com/junit-team/junit5/issues/3018#issuecomment-1360147058, there is sometimes a need to filter out invalid combinations, etc. While nested `for` loops are verbose, they offer type safety that would not be possible by filtering the `Stream<Arguments>` returned from the utility method. Moreover, JUnit Pioneer already [provides similar functionality](https://junit-pioneer.org/docs/cartesian-product/#defining-arguments-with-factories).

**Comment by vlsi** [comment]
By the way, the recent Java and Kotlin allow single-line record definitions like `record TestParams(State state, Model model, Color color, ...)`. Then one can replace `Stream<Arguments>` with `Stream<TestParams>`.

It allows better type safety, and avoids repeating the parameters.
The test method could receive "state + model + color" as a single `TestParams` object, so there will be no "positional argument" errors.

See sample at https://github.com/apache/jmeter/blob/09c3f810dda7efaf1510ac062454d978d90a0741/src/protocol/jdbc/src/test/kotlin/org/apache/jmeter/protocol/jdbc/sampler/JDBCSamplerTest.kt#L138-L157

However, these types have to be created on a case by case basis (I do not think JUnit can automate creating those records as user requests cartesian joins). However, I tend to prefer `Stream<Record>` approach better than `Stream<Arguments>` since records enable me to declare the parameter names and types only once (in the record definition).
