### ISSUE TITLE
Support saturating the Forkjoin pool via a property

### ISSUE THREAD

**Issue by mpkorstanje** [junit-team/junit5#3026]
Currently [JUnit Jupiter does not guarantee that the number of concurrently executing tests will not exceed the configured parallelism](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-config). The advice is to provide a custom [`ParallelExecutionConfigurationStrategy`](https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/support/hierarchical/ParallelExecutionConfigurationStrategy.html). And through https://github.com/junit-team/junit5/pull/2792 it is now possible to configure whether or not the pool should be saturated.

However implementing a custom strategy to replicate the behaviour of the existing `fixed` or `dynamic` strategy with saturation is non-trivial. On the other hand, ensuring a maximum number of concurrent tests is a common need e.g: https://github.com/junit-team/junit5/issues/2545, https://github.com/junit-team/junit5/issues/1675, https://github.com/junit-team/junit5/issues/1858, https://github.com/SeleniumHQ/selenium/issues/10113, https://github.com/cucumber/cucumber-jvm/issues/2512, https://github.com/cucumber/cucumber-jvm/issues/2602.

We can stream line the experience for end-users by providing `*.dynamic.saturate` and `*.fixed.saturate` properties. When set to `true` the `DefaultParallelExecutionConfiguration.getSaturatePredicate` would return `__ -> true` and `null` otherwise.

## Deliverables

- [x] Update `DefaultParallelExecutionConfigurationStrategy` to read `*.dynamic.saturate` and `*.fixed.saturate` properties.
- [x] Update the documentation to explain this.

**Comment by marcphilipp** [comment]
**Team Decision:** Follow the proposal.

**Comment by marcphilipp** [comment]
@mpkorstanje Thanks for bringing this up! Could you please add the missing documentation to the PR so we can include it in 5.9.1? 🙂

**Comment by mpkorstanje** [comment]
I reckon https://github.com/junit-team/junit5/pull/3044 is good go.
