### ISSUE TITLE
Drop Java 8 support ...

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#3029]
... and use Java 17 (current LTS) as a the new base Java version would prevent the following warnings, that started appearing with Java `20-ea+14`:
```text
> Task :junit-platform-commons:compileJava FAILED
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified
```
➡️ https://github.com/junit-team/junit5/runs/8283467469?check_suite_focus=true#step:6:285

Yes, suppressing those warnings via `-Xlint:-options` as suggested is also an option.

No, removing `-Werror` is not an option as all other warning types should fail the build.

What about a describing a transition plan for when JUnit "5" will drop support for Java 8?

🤔 Mhhh, are  only `-source 8` and `-target 8` options affected, and not `--release 8`?
_To me the warning reads more like the cross-version compilation support targetting Java SE version 8 is removed. Like it was done for the support of Java SE 7._

Related
- [JDK-8173605](https://bugs.openjdk.org/browse/JDK-8173605) Remove support for source and target 1.7 option in javac
- https://github.com/openjdk/jdk/commit/2d18dda3f2074a4f8b9a0c62ece9ac6d5284e93b

**Comment by marcphilipp** [comment]
**Team Decision:** Stay backwards compatible with Java 8 until we have a compelling, user-facing reason to adopt a later release.
