### ISSUE TITLE
Assumptions should support most/all features of Assertions

### ISSUE THREAD

**Issue by voomdoon** [junit-team/junit5#3030]
I am trying to use something like
```
Assumptions.assumeThrows(Exception.class, () -> program.run());
```
to ignore the test if no exception was thrown.
The test should e.g. check whether cleanup/rollback is done correctly on error.

But `assumeThrows` does not exist.

The idea behind is: There is a separate test with
```
Assertions.assertThrows(Exception.class, () -> program.run());
```
that will fail if the method does not throw an exception.

If the method does not throw an exception, there should be one failing test only pointing to the problem.

-----

The idea of this feature request is to add all features of Assertions also at Assumptions.
A think this could be easily doable if we would generate the code using Assertions as source and replace all assertions by assumptions?

**Comment by sbrannen** [comment]
@Ilpyo-Yang, the team has not yet decided to implement this proposal. 

A PR would therefore be premature at this stage.

**Comment by marcphilipp** [comment]
**Team decision:** `Assumptions` is intentionally simpler than `Assertions` and even only contains a subset of the assumptions that were available in JUnit 4. In light of that we don't have any plans to extend the `Assumptions` API.

**Comment by Ilpyo-Yang** [comment]
I will participate if there is another opportunity. Thank you for sharing the team decision with me.
