### ISSUE TITLE
TestReporter does not work with Kotlin

### ISSUE THREAD

**Issue by SaherAlSous** [junit-team/junit5#3033]
I'm using JUnit Jupiter 5.9.0 with Kotlin, using Gradle, and I used the `TestReporter` in both Java and Kotlin projects.

On Java it prints to the console normally, but in Kotlin nothing prints.

## Steps to reproduce

```kotlin
    @Test
    fun `Testing Reporting`(testReporter: TestReporter) {
        testReporter.publishEntry("Here we go...")
        testReporter.publishEntry("Here we go...", "Again")
    }
```

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.9.0
 - Build Tool/IDE: IntelliJ, Gradle

## Deliverables

- To have the `TestReporter` work normally with Kotlin.
- Generally speaking... I feel there is no Kotlin support in JUnit5.

**Comment by marcphilipp** [comment]
> On Java it prints to the console normally, but in Kotlin nothing prints.

Printing report entries is an IntelliJ feature and I just verified that it works for me for a Kotlin class. If you run the test via Gradle, report entries are not printed, neither for Kotlin nor Java classes.

Did you maybe run the Kotlin test via Gradle?

**Comment by SaherAlSous** [comment]
Yes Gradle...

**Comment by SaherAlSous** [comment]
hmmm... I run the test also with the "Play" button from IntelliJ and it is the same...

**Comment by marcphilipp** [comment]
You can configure how IntelliJ executes tests:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/214207/190624983-7d0de6b6-af47-416d-974d-8025d3c285d0.png">

**Comment by SaherAlSous** [comment]
yes that fixed it... reports and logs are showing up... thank you!
