### ISSUE TITLE
getRequiredTestMethod().getAnnotations() doesn't return meta-annotations

### ISSUE THREAD

**Issue by cbottomline** [junit-team/junit5#3038]
JUnit 5.8.2

I have a meta-annotation that contains a custom annotation is placed on a test method.  In my extension when I call `getRequiredTestMethod().getAnnotations()` I can't get the custom annotation.  `getAnnotations` only returns the meta annotation but not any of the annotations that make up the meta annotation.

## Steps to reproduce

1.  Create 2 custom annotations (CustomA, CustomB).
2. Add CustomA to CustomB
3. Place @CustomB on a test method.

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit Jupiter 5.8.2
 - Build Tool/IDE: IntelliJ IDEA 2022.2.2 (Ultimate Edition)

**Comment by marcphilipp** [comment]
`getRequiredTestMethod()` returns a `java.lang.reflect.Method` which we can't change the behavior for. In order to find meta-annotations, please use the APIs in `AnnotationSupport` instead of calling `Method.getAnnotations()`.
