### ISSUE TITLE
junit-jupiter-params 5.9.1 upgrade fails with NoSuchMethodError

### ISSUE THREAD

**Issue by mhlavac** [junit-team/junit5#3041]
Dependencies:
```
junit-jupiter-api:5.9.1
junit-jupiter-engine:5.9.1
junit-jupiter-params:5.9.1
junit-platform-commons:1.9.0
junit-platform-engine:1.9.0
```

After upgrading to `junit-jupiter-params:5.9.1` the tests started failing with following error `java.lang.NoSuchMethodError: 'boolean org.junit.platform.commons.util.CollectionUtils.isConvertibleToStream(java.lang.Class)'`. It looks like a new method is to be introduced in commons 1.9.1 and got used in the 5.9.1 release already.

From this diff it seems like the method was user prematurely https://github.com/junit-team/junit5/compare/r5.9.0...r5.9.1

I'm new to the project so I might be understanding it wrong.

[#diff-69531322f458eb134daa846fd4239d5d1a5874bea76c426b6ca0f2a6708c06f1R92](https://github.com/junit-team/junit5/commit/5508b8d506740e0e54535bb86b3e2951df96205e#diff-69531322f458eb134daa846fd4239d5d1a5874bea76c426b6ca0f2a6708c06f1R92) - usage of the new method

https://github.com/junit-team/junit5/commit/bb718750207ce6c7de78328b5f01341cad9057db#diff-b36782efd4b10b3e769e60f0987699d95878887b776fe0c2125f567b9c8466fcR129 - addition of the method for 1.9.1 that is not released yet.

## Steps to reproduce

I'll do my best to provide a repo this week for reproduction. In meanwhile, using the suggested dependencies with combination of `@ParameterizedTest` and `@MethodSource` that will return `Stream<Arguments>` causes the issue within our project.

## Context

 - Used versions (Jupiter/Vintage/Platform):
```
junit-jupiter-api:5.9.1
junit-jupiter-engine:5.9.1
junit-jupiter-params:5.9.1
junit-platform-commons:1.9.0
junit-platform-engine:1.9.0
```
 - Build Tool/IDE: IntelliJ

## Deliverables

- [ ] The `isConvertibleToStream` noSuchMethodError is no longer trigger

**Comment by marcphilipp** [comment]
`junit-jupiter-params:5.9.1` has a transitive dependency on `junit-platform-commons:1.9.1`. Using it with `1.9.0` is not supported. Please also update the junit-platform dependencies to 1.9.1.

**Comment by marcphilipp** [comment]
> addition of the method for 1.9.1 that is not released yet.

It was released at the same time as `junit-jupiter-params:5.9.1`:
https://search.maven.org/artifact/org.junit.platform/junit-platform-commons/1.9.1/jar

**Comment by mhlavac** [comment]
Confirming this indeed works. I won't trust mvnrepostiory.com again. Thank you @marcphilipp!
