### ISSUE TITLE
EngineDiscoveryOrchestrator does not exclude filtered TestDescriptors if they contain children

### ISSUE THREAD

**Issue by ddscharfe** [junit-team/junit5#3042]
Hi,

I'm running into an issue with the junit platform engine discovery mechanism and I wonder if this is intended behavior, a bug, or if I got something wrong.

During test discovery `EngineDiscoveryOrchestrator::discover` applies `PostDiscoveryFilters` and removes `TestDescriptors` according to these filters (`EngineDiscoveryOrchestrator::applyPostDiscoveryFilters`). Additionally `TestDescriptors` which can't be executed are removed by `EngineDiscoveryOrchestrator::prune`. 

If a `TestDescriptor` contains any children, it will never be filtered out, regardless of the filter result:
```java
        // EngineDiscoveryOrchestrator
	private boolean isExcluded(TestDescriptor descriptor, FilterResult filterResult) {
		return descriptor.getChildren().isEmpty() && filterResult.excluded();
	}
```
`EngineDiscoveryOrchestrator::prune` implicitly calls `TestDescriptor::prune` which removes the descriptor from the hierarchy unless it is a root or contains tests.

Hence a test descriptor which is also a container (type == `Type.CONTAINER_AND_TEST`) and has children will always be discovered, even if itself and its children are excluded by a post discovery filter.

I would expect `EngineDiscoveryOrchestrator::isExcluded` to exclude filtered test descriptors which have children if they are tests, e.g.:
```java
        // EngineDiscoveryOrchestrator
	private boolean isExcluded(TestDescriptor descriptor, FilterResult filterResult) {
		return (descriptor.isTest() || descriptor.getChildren().isEmpty()) && filterResult.excluded();
	}
```

BR,
Dominic

**Comment by marcphilipp** [comment]
Are you using a custom `PostDiscoveryFilter`? If so, could that case be handled there?

**Comment by ddscharfe** [comment]
I am using a `PostDiscoveryFilter` and it returns `FilterResult.excluded("REASON")`, but the descriptor has children and is therefore not excluded due to the implementation of `EngineDiscoveryOrchestrator::isExcluded`.

**Comment by marcphilipp** [comment]
Could you change your `PostDiscoveryFilter` to also return `FilterResult.excluded("REASON")` for all children of such descriptors?

**Comment by ddscharfe** [comment]
It does, but `EngineDiscoveryOrchestrator::isExcluded` ignores the filter result because the descriptor has children (see my first comment).

**Comment by marcphilipp** [comment]
I thought it would get pruned of all of its children are excluded but it seems I was wrong (since `isTest()` returns `true` for `CONTAINER_AND_TEST`:

https://github.com/junit-team/junit5/blob/e69243ae0f3c68f07d075ac3901c98c375d040f0/junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java#L226-L230
https://github.com/junit-team/junit5/blob/e69243ae0f3c68f07d075ac3901c98c375d040f0/junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java#L209-L213

@ddscharfe As a workaround, could you override `prune()` on the test descriptor of type `CONTAINER_AND_TEST` in question?

**Comment by ddscharfe** [comment]
Thanks for your suggestion @marcphilipp. I thought about that too, however this violates the "contract" (aka JavaDoc) of `PostDiscoveryFilter`, because I would have to set some kind of state on the `TestDescriptor` during filtering. However it's an okay solution for me as it should solve my problem.
So am I right assuming that this is indeed a bug?

**Comment by ddscharfe** [comment]
I worked around this issue by not using a `PostDiscoveryFilter`. Instead I do the filtering in my `SelectorResolver::resolve` implementation and don't add the respective `TestDescriptor`s in the first place.
Unless this issue is of concern for anyone else, I think it can be closed as not planned.

**Comment by sbrannen** [comment]
Thanks for the feedback, @ddscharfe.

We'll close this issue for now.
