### ISSUE TITLE
Provides variant of assertThrows which allow doing assertion on thrown throwable instance.

### ISSUE THREAD

**Issue by stonerichard** [junit-team/junit5#3043]
Current `assertThrow` does not give handle of thrown `Throwable` to do further assertions.

```java
static <T extends Throwable> assertThrows(Class<T> expectedType, Executable executable)
```

Expected a variant of `assertThrow` which give the thrown `Throwable` for further assertions.

```java
static <T extends Throwable> assertThrows(Class<T> expectedType, Executable executable, Consumer<T> throwableConsumer)
```

Sample usage:

```java
assertThrows(SomeDomainException.class, () -> doSomeDomainAction(), (SomeDomainException exception) -> {
            assertEquals(exception, new SomeDomainException("someDomainField", 2));
        });
```

**Comment by sbrannen** [comment]
> Current `assertThrow` does not give handle of thrown `Throwable` to do further assertions.
> 
> ```java
> static <T extends Throwable> assertThrows(Class<T> expectedType, Executable executable)
> ```

That's incorrect. The actual signature is:

```java
	public static <T extends Throwable> T assertThrowsExactly(Class<T> expectedType, Executable executable)
```

That returns the "thrown Throwable".

The [Assertions](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions) section of the user guide demonstrates this:

```java
    @Test
    void exceptionTesting() {
        Exception exception = assertThrows(ArithmeticException.class, () ->
            calculator.divide(1, 0));
        assertEquals("/ by zero", exception.getMessage());
    }
```

In light of that, I am closing this issue.
