### ISSUE TITLE
Hoist the `ExtensionValuesStore` implementation to the platform

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#3047]
The concept of such a store seems useful to test engines in general,
so having it in the platform would be helpful for other engines.

For example, I'd like to add something like it to Spock.

## Deliverables

- [ ] ExtensionValuesStore or a comparable implementation is available via the JUnit Platform.

**Comment by sbrannen** [comment]
## Related Issues

- #2411
- #2816
