### ISSUE TITLE
testMethod parameter provided to generateDisplayNameForMethod doesn't contains test method annotations except "Test"

### ISSUE THREAD

**Issue by Little-Elephant** [junit-team/junit5#3057]
junit 5.9.1

given test with Tag

`    @Tag("test.id")
    @Test
    void less_than_min_cluster_size() {`
    
and class implementing DisplayNameGenerator
in which I want to use Tag value to generate DisplayName
But in testMethod parameter provided to generateDisplayNameForMethod implementation i see only one declaredAnnotation:
`{Class@3839} "interface org.junit.jupiter.api.Test" -> {$Proxy15@4049} "@org.junit.jupiter.api.Test()"`

testClass parameter provided to generateDisplayNameForMethod implementation contains Tags of class in declaredAnnotations, as expected.

in same time I see Tags for testMethod in ExtensionContext provided to TestWatcher implementation.

**Comment by sbrannen** [comment]
If you are using the standard JDK reflection APIs to look up annotations on the `Method`, it should be able to find any annotations with the proper runtime retention.

If that's not the case, please provide a minimal example that demonstrates the undesired behavior.

Without an example, I'm afraid we likely won't be able to assist you very well.

**Comment by Little-Elephant** [comment]
I tried testMethod.getDeclaredAnnotations() then I dive into debug in IntelJ Idea (I guess it use standard JDK reflection API)

It does not find org.junit.jupiter.api.Tag annotation, That runtime retention and have method in targets

If it matter JVM correto-17.

I will try to make example based on  samples

**Comment by Little-Elephant** [comment]
Unable to reproduce on sample. Will debug more.

**Comment by Little-Elephant** [comment]
My bad.  There was no Tag because it was another testMethod, without Tag.

**Comment by sbrannen** [comment]
Glad you sorted it out, and thanks for providing feedback.
