### ISSUE TITLE
Guarantee that calls to TestExecutionListener are executed synchronously

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#3061]
`org.junit.platform.launcher.TestExecutionListener` seems to be the only hook to provide cross-engine plugins and extensions.
In order to make their behaviour predictable, asynchronously calling the methods would be unfortunate.
Synchronous calls would make sure that, e.g. a resource can really be initialized in `executionStarted` and torn down in `executionFinished`. Having guarantees for this and other callbacks would enable the creation of real cross-engine extension mechanisms.

## Deliverables

- [x] Check if they are currently always being called synchronously
- [x] Document the guarantees

**Comment by marcphilipp** [comment]
To clarify: by "being called synchronously" do you mean that `executionStarted` and `executionFinished` will be called on the same thread for any given `TestIdentifier`?

**Comment by jlink** [comment]
The same thread might not be necessary. But the execution of the test should not start before `executionStarted` has returned.

**Comment by marcphilipp** [comment]
> Stronger guarantee would be that no two calls to `executionStarted` for the same test identifier will happen concurrently.

In what scenario would `executionStarted` be called for the same test identifier multiple times?

**Comment by jlink** [comment]
> In what scenario would `executionStarted` be called for the same test identifier multiple times?

When more than one listener has been registered.

**Comment by marcphilipp** [comment]
So you basically want us to add the following sentence to the docs, right?

> Listeners are called sequentially in registration order.

Is there anything else you rely on that's undocumented and should be added?

**Comment by jlink** [comment]
Yes:

> Test case execution won't start before all executionStarted calles have returned.
