### ISSUE TITLE
ParameterizedTest using current instance

### ISSUE THREAD

**Issue by rogermiranda1000** [junit-team/junit5#3062]
I tried to use @ParameterizedTest with an @ArgumentsSource of the same class as the test. This class have a BeforeAllCallback that initializes a variable, and I want to use that variable (a list of objects) as argument.

I can't use @ArgumentsSource because it creates a new instance, thus the variable is null, and I can't use the variable either because @VariableSource needs an static variable.

## Deliverables

- @ParameterizedTest allows @ArgumentsSource(this)

**Comment by rogermiranda1000** [comment]
Some minimal "functional" example:

AbstractTest.java
```
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.ArrayList;
import java.util.Random;
import java.util.stream.Stream;

public class AbstractTest implements BeforeAllCallback, ArgumentsProvider {
    private ArrayList<Integer> parameters;

    @Override
    public void beforeAll(ExtensionContext extensionContext) {
        this.parameters = new ArrayList<>();

        Random rand = new Random();
        for (int n = 0; n < rand.nextInt(5); n++) this.parameters.add(rand.nextInt());
    }

    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) throws Exception {
        return this.parameters.stream().map(e -> Arguments.of(e));
    }
}
```

TestExample.java
```
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ArgumentsSource;

@ExtendWith(TestExample.class) // run the tests with the AbstractTest overridden methods
public class TestExample extends AbstractTest {
    @ParameterizedTest
    @ArgumentsSource(TestExample.class)
    public void opPlayer(Integer num) {
        System.out.println(num);
    }
}
```

**Comment by mpkorstanje** [comment]
I'm not sure what the underlying problem is that you're trying to solve. However extensions should not use private fields. Instead of using `private ArrayList<Integer> parameters;` to store the random numbers they should be stored in the `ExtensionContext`.

**Comment by rogermiranda1000** [comment]
> to store the random numbers they should be stored in the `ExtensionContext` that is provided as a method argument.

But they are different instances of the parameter didn't they? If I print `extensionContext.getUniqueId()` in `beforeAll` and `provideArguments` they provide the same class, but different IDs

**Comment by mpkorstanje** [comment]
They are indeed different instances.

JUnit is a hierarchical test engine, so every node has it's own unique extension context. However each context also has access the context of it's parents. This allows information from the class level extension to be provided to the method level arguments provider.

For your example you would do this by placing the value in the store of the extension context. 

```
iimport org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.ExtensionContext.Namespace;
import org.junit.jupiter.api.extension.ExtensionContext.Store;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

public class ExampleExtension implements BeforeAllCallback, ArgumentsProvider {

    @Override
    public void beforeAll(ExtensionContext extensionContext) {
        Random random = new Random();
        int argumentSize = 1 + random.nextInt(5);
        List<Arguments> parameters = random
                .ints()
                .limit(argumentSize)
                .mapToObj(Arguments::of)
                .collect(Collectors.toList());

        Store store = getStore(extensionContext);
        store.put("parameters", parameters);
    }

    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) {
        Store store = getStore(extensionContext);
        List<? extends Arguments> parameters = (List<? extends Arguments>) store.get("parameters");
        return parameters.stream();
    }

    private static Store getStore(ExtensionContext extensionContext) {
        return extensionContext.getStore(Namespace.create(ExampleExtension.class));
    }

}
```

Note: I've had to fix the algorithm to generate a list of random size. There must always be at least 1 parameter.

```
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ArgumentsSource;

@ExtendWith(ExampleExtension.class)
public class TestExample {

    @ParameterizedTest
    @ArgumentsSource(ExampleExtension.class)
    public void test1(Integer num) {
        System.out.println(num);
    }

}
```

Note: There is no reason to extend the `TestExample` with the `ExampleExtension`. The extension method in the parent class of `TestExample` will never be invoked.

**Comment by rogermiranda1000** [comment]
> Note: I've had to fix the algorithm to generate a list of random size. There must always be at least 1 parameter.
That was just an example. Still, thanks for the example.

> Note: There is no reason to extend the `TestExample` with the `ExampleExtension`. The extension method in the parent class of `TestExample` will never be invoked.

The problem is that I need to override a function. You can see the exact implementation of my [ExampleExtension](https://github.com/rogermiranda1000/WatchWolf-Tester/blob/dev/src/com/rogermiranda1000/watchwolf/tester/AbstractTest.java) and [TestExample](https://github.com/rogermiranda1000/WatchWolf-Tester/blob/dev/test/TesterTester.java). TestExample needs to override the `getConfigFile` function defined in ExampleExtension.

**Comment by mpkorstanje** [comment]
To setup resources in the beforall step, the config for those resources must be accessible from a static context. There is no instance of the test class yet to invoke a method on.

You can access this static method in your extension without extending from it. The `ExtensionContext` will provide you the test class. You can then use reflection to either look for a method with a well known name/signature or use an annotation to mark that method.

**Comment by marcphilipp** [comment]
There's another way to implement this, without using `BeforeAllCallback` but by storing the parameters in the extension context of the test class lazily.

```java
package com.example.project;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.ExtensionContext.Namespace;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;
import org.junit.platform.commons.support.ReflectionSupport;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.stream.Stream;

public class ExampleExtension implements ArgumentsProvider {

    private static final Namespace NAMESPACE = Namespace.create("example");
    private static final String KEY = "parameters";

    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) {
        List<?> parameters = extensionContext.getParent().orElseThrow()
                .getStore(NAMESPACE)
                .getOrComputeIfAbsent(KEY, __ -> computeParameters(extensionContext), List.class);
        return parameters.stream().map(Arguments::of);
    }

    private static List<Integer> computeParameters(ExtensionContext extensionContext) {
        int config = ReflectionSupport.findMethod(extensionContext.getRequiredTestClass(), "config")
                .map(method -> extensionContext.getExecutableInvoker().invoke(method))
                .map(Integer.class::cast)
                .orElse(42);
        System.out.println("extension: computing parameters");
        List<Integer> result = new ArrayList<>();
        Random rand = new Random();
        for (int n = 0; n < config; n++) result.add(rand.nextInt());
        return result;
    }
}
```

```java
package com.example.project;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ArgumentsSource;

public class TestExample {

    static int config() {
        return 5;
    }

    @ParameterizedTest
    @ArgumentsSource(ExampleExtension.class)
    public void test1(Integer num) {
        System.out.println("test1: " + num);
    }

    @ParameterizedTest
    @ArgumentsSource(ExampleExtension.class)
    public void test2(Integer num) {
        System.out.println("test2: " + num);
    }
}
```
