### ISSUE TITLE
Ability to combine a few argument sources in parameterized tests

### ISSUE THREAD

**Issue by rpuch** [junit-team/junit5#3063]
## The problem

Sometimes one needs to write a parameterized test over a combination (i.e. a cartesian product) of 2 or more parameter sets. For example, cable connectors might be male/female, have one of 3 colors, and be new or used, and we want to test all `2*3*2=12` combinations:

```
enum ConnectorType { MALE, FEMALE }
enum Color { RED, GREEN, BLUE }

@ParameterizedTest
???
void shouldWorkOk(ConnectorType connType, Color color, boolean isNew) {
...
}
```

Currently one way is to use `@MethodSource` and generate all the possible combinations there, but it's tedious and error-prone. Also, it might not be that easy to read.

## Idea

The idea is to add ability to combine various argument sources via a new annotation. Ideally, this would look like this:

```
@CompositeSource({
    @EnumSource(ConnectorType.class),
    @EnumSource(Color.class),
    @ValueSource(bools = { false, true })
})
```

But Java does not allow polymorphic annotations, so this won't work. I see 2 alternative approaches:

### Approach 1

Have N * M elements in `@CompositveSource` (N is the number of supported dimenstions, say 5, M is the number of supported standard source annotations):

```
@CompositeSource(
    enum1 = @EnumSource(ConnectorType.class),
    enum2 = @EnumSource(Color.class),
    value3 = @ValueSource(bools = { false, true })
)
```

### Approach 2

Add another wrapper annotation (`@Source`) that would have M elements (one per supported source annotation), then:

```
@CompositeSource({
    @Source(enumSource = @EnumSource(ConnectorType.class)),
    @Source(enumSource = @EnumSource(Color.class)),
    @Source(valueSource = @ValueSource(bools = { false, true }))
})
```

(Alternatively, the annotation could be named `@_`:
```
@CompositeSource({
    @_(enumSource = @EnumSource(ConnectorType.class)),
    @_(enumSource = @EnumSource(Color.class)),
    @_(valueSource = @ValueSource(bools = { false, true }))
})
```
which is ugly by itself, but, arguably, reduces amount of noise)

Both approaches are not too elegant (even ugly); also, they will only work for the limited set of source annotations known beforehand; but they allow to solve the task.

First approach causes a combinatorial explosion of annotation elements and cumbersome implementation, but allows to avoid a wrapper annotation. It is also more brittle, as user must be careful about numbers (those `enum1`, `value3`, etc).

Second approach avoids the combinatorial explosion, but leads to noisier test code.

Of course, there is also a third approach: drop this as irrelevant for Junit5 core.

I would appreciate opinions on the matter. WDYT?

If this does not get dropped, I would be pleased to try and implement it.

**Comment by sormuras** [comment]
At the moment, I am happy to use JUnit Pioneer's https://junit-pioneer.org/docs/cartesian-product/ in such cases.

For some history on that topic you might want to read:
- https://github.com/junit-team/junit5/issues/1427
- https://github.com/junit-team/junit5/issues/3018

**Comment by rpuch** [comment]
Thank you Christian, I've never heard about Junit Pioneer before. On the first glance, it looks like this is what I was looking for. I'll try to use it and see how it goes. Also, thanks for the context.

**Comment by fabricio-entringer** [comment]
Hello, it seems fantastic. What I was looking for.
Just to know, is it a plugin for JUnit right? But maintained by another group! Did I understand correctly?

**Comment by sormuras** [comment]
Yes.

Find more details at: https://github.com/junit-pioneer/junit-pioneer#readme

**Comment by agentgt** [comment]
To be honest I think this is a bug at least for all enum parameter tests because `@EnumSource` is repeatable.

Why is `@EnumSource` repeatable?

**Comment by mpkorstanje** [comment]
Have a look at the tests for enum source.

https://github.com/junit-team/junit5/blob/16c6f72c1c728c015e35cb739ea75884f19f990c/jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java#L2214-L2217

Here the enums implement a common interface, which makes a reusable annotation useful.
