### ISSUE TITLE
Make class in org.junit.jupiter.params package public

### ISSUE THREAD

**Issue by iNikem** [junit-team/junit5#3067]
Related to #1558. I wanted to modify @artsok's retry plugin to better suit our specific use-case and realised that it has to verbatim copy quite several classes from the `org.junit.jupiter.params` package from this repository because they are package-protected. For example `org.junit.jupiter.params.ParameterizedTestMethodContext` and `org.junit.jupiter.params.ParameterizedTestParameterResolver`.  This copy-paste, although necessary, is clearly bad and not sustainable. From #1558 it seems that flaky test retry mechanism will not come to JUnit core and we have to rely on external extensions. But any of those extensions will need access to classes in `org.junit.jupiter.params` to support retrying ParameterizedTest.

Is it possible to make them public to simplify flaky test extension development?

**Comment by marcphilipp** [comment]
**Team decision:** We have decided against making those classes public since that would mean an additional maintenance constraint.
