### ISSUE TITLE
Programatically set test display name from extension

### ISSUE THREAD

**Issue by luisalves00** [junit-team/junit5#3070]
I'm trying to set the display name of a test to be setted programmatically from one extension as explained on this [stackoverflow question ](https://stackoverflow.com/questions/74070724/junit5-set-displayname-programatically-from-extension). Seems is not possible. Can this feature be available on the future? The extension loads a file where the test data is described as well the test display name and long description.

**Comment by marcphilipp** [comment]
As @jlink [explained on StackOverflow](https://stackoverflow.com/questions/74070724/junit5-set-displayname-programatically-from-extension#comment130830317_74070724), it's not possible to change the display name at execution time, only at discovery time by implementing `DisplayNameGenerator`.

**Comment by jlink** [comment]
@luisalves00 What you probably want, is some kind of dynamic test (https://www.baeldung.com/junit5-dynamic-tests)

**Comment by luisalves00** [comment]
Sounds interesting, but doesn't support:

> The DynamicTests are executed differently than the standard @Tests and do not support lifecycle callbacks. Meaning, the @BeforeEach and the @AfterEach methods will not be called for the DynamicTests.

Anyway might be useful for the future.

thanks @jlink
