### ISSUE TITLE
Set of URLs may behave surprisingly on hashCode/equals

### ISSUE THREAD

**Issue by rillig** [junit-team/junit5#3079]
https://github.com/junit-team/junit5/blob/242f3b3ef84cfd96c9de26992588812a68cdef8b/junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java#L261

[IntelliJ 2022.3 warns](https://github.com/JetBrains/intellij-community/blob/223/plugins/InspectionGadgets/src/inspectionDescriptions/CollectionContainsUrl.html):
> URL's equals() and hashCode() methods can perform a DNS lookup to resolve the host name.
> This may cause significant delays, depending on the availability and speed of the network and the DNS server.
> Using java.net.URI instead of java.net.URL will avoid the DNS lookup.

I don't know whether the code in question actually has this problem, as class paths usually only use local URLs, it's just that the code looks suspicious.

**Comment by marcphilipp** [comment]
**Team decision:** While the warning makes sense in general, in this case the `URL`s typically reference files in classpath in the local file system. Converting them all to `URI`s might have unintended side effects. Therefore, we intend to keep the behavior as is unless an actual issue is reported.
