### ISSUE TITLE
5.9+ breaks compatibility with vintage runner+Enclosed+junitparams

### ISSUE THREAD

**Issue by mmorrisontx** [junit-team/junit5#3083]
When a junit 4 test class, running under the junit 5 vintage engine, is annotated with org.junit.experimental.runners.Enclosed, and contains multiple nested classes, each using JunitParams, then gradle fails with `Received a completed event for test with unknown id '1.12'. Registered test ids: '[1.1, 1.2, 1.11, :test, 1.10]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '1.12'. Registered test ids: '[1.1, 1.2, 1.11, :test, 1.10]'`

This is a regression in 5.9. It works properly on 5.8.2. I am aware that this is a contrived example, but I assure you, it did actually happen to our existing tests :)

## Steps to reproduce

* Check out https://github.com/mmorrisontx/junit5-3083-repro
* ./gradlew test
* Output fails due to `Received a completed event for test with unknown id`
* If you replace junit dependencies with 5.8.2, tests pass.

## Context

 - Used versions (Jupiter/Vintage/Platform): jupiter+vintage 5.9.1
 - Build Tool/IDE: gradle 7.5.1

## Deliverables

- [ ] ...

**Comment by marcphilipp** [comment]
@mmorrisontx Thanks for reporting this issue and providing a reproducer! It turned out I was simply calling the wrong method.
