### ISSUE TITLE
Inline jopt-simple into junit-platform-console

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#309]
## Status Quo

The `junit-console` module currently has a mandatory dependency on `jopt-simple`, which can have negative side effects if the consumer of `junit-console` wants to use a different version of JOpt Simple. In addition, having a mandatory, transitive dependency on a third-party library breaks the general rule for JUnit modules.

## See Also

- b1746e8b00aba42823d873941d4f26d5a111ffda

## Deliverables

- [ ] Inline `jopt-simple` into `junit-console`
  - for example, using the [Shadow Plugin](https://github.com/johnrengelman/shadow) (with a custom `Transformer`) or [jarjar](https://code.google.com/archive/p/jarjar/).

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, let's discuss the merits of this proposal.

**Comment by marcphilipp** [comment]
I think I tried that but it didn't work because of a few resource bundles inside the jopt-simple jar that contain class names. We would have to process those as well, but I couldn't find a suitable post-processor at the time.

**Comment by sbrannen** [comment]
In that case, the [Shadow Plugin](https://github.com/johnrengelman/shadow) may be a better choice than [jarjar](https://code.google.com/archive/p/jarjar/).

**Comment by jbduncan** [comment]
@sbrannen, if the Shadow Plugin and jarjar don't work, may I recommend trying [Capsule](https://github.com/puniverse/capsule)? I've personally used it in the past, and it seems to produce nice executable JARs even for large-ish projects. Although it doesn't have any official build tool plugins, the website does point to some third-party ones including Gradle (http://www.capsule.io/user-guide/#build-tool-plugins).

**Comment by jbduncan** [comment]
Hmm, then again, I don't know if Capsule can be used for renaming library classes and all references to those classes. I'd still recommend having a look at it, however, if all your other options fail.

**Comment by sbrannen** [comment]
@jbduncan, thanks for the tip. If all else fails, we'll look into Capsule.

**Comment by sbrannen** [comment]
As far as I can tell, the _Shadow Plugin_ does not have a built-in `Transformer` that will rename the class name based property keys in JOpt Simple's properties files.

However, it should be simple enough to create our own custom transformer for that purpose, and we can use the [PropertiesFileTransformer](https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.groovy) for inspiration.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I've opened pull request johnrengelman/shadow#247 that adds the required properties file transformation functionality to the Shadow Gralde plugin.

**Comment by sbrannen** [comment]
Awesome!

Thanks, man! 👍

**Comment by marcphilipp** [comment]
This issue is _blocked_ by johnrengelman/shadow#247. We could of course create our own transformer, but I would rather use the Shadow plugin as-is without a custom extension that we need to maintain.

**Comment by sbrannen** [comment]
It definitely makes sense to have this use officially supported by the Shadow plug-in!

But we always have the option to use a _forked_ version of the code in your PR as an interim solution in case the updated Shadow plugin doesn't get released soon enough for us.

**Comment by marcphilipp** [comment]
I will go ahead and add the modified version of the PropertiesFileTransformer to our build even though it was not officially released, yet.
