### ISSUE TITLE
Document JUnit Platform compatibility issues when using Maven Surefire

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#3093]
## Overview

Examples in the User Guide still use Maven Surefire version 2.22.2 which does not automatically support recent versions of JUnit 5.

This can cause problems for users that are not aware of this. See https://github.com/spring-projects/spring-kafka/issues/2481#issuecomment-1317178199 for details.

For the GraalVM Native Build Tools, I added a [dedicated section](https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#testing-support-version-compatibility) explaining this as well.

## Related Issues

- https://github.com/graalvm/native-build-tools/issues/151
- https://github.com/spring-projects/spring-kafka/issues/2481

## Deliverables

- [x] Improve Maven Surefire documentation in the User Guide to help users figure out when it's necessary to manually override the JUnit Platform version used.

**Comment by marcphilipp** [comment]
There's a working integration test for 2.22.2:
https://github.com/junit-team/junit5/blob/e98b714b0ffd5fbbaf7e9a65478c4911c2a3cbd0/platform-tooling-support-tests/projects/maven-starter/pom.xml#L40-L41

**Comment by sbrannen** [comment]
> There's a working integration test for 2.22.2:

I believe that's relying on the use of JUnit BOMs (and does not include dependencies on third-party libraries that have _optional_ dependencies on JUnit artifacts) and therefore not the same thing.
