### ISSUE TITLE
@CsvSource - Params Selection

### ISSUE THREAD

**Issue by J3yGy** [junit-team/junit5#3094]
Hi, I have multiple junit with lot of params, and each time a test fail with just one param or I have to test a new feature of an existing test, I must comment all the other params (otherwise a single test would take ages to compile).
I think would be nice to have a way to select just one Param for cases like these and I'm pretty sure that doesen't exist (I spent hours searching for a solution)
Thanks

**Comment by sbrannen** [comment]
> I think would be nice to have a way to select just one Param for cases like these and I'm pretty sure that doesen't exist (I spent hours searching for a solution)

You can re-run a single iteration of a parameterized test in IntelliJ and Eclipse by right-clicking on the iteration in the results view of the previous run.

Does that meet your needs?

**Comment by tubbynl** [comment]
I does meet my daily requirement, but i'm guessing he's using cli.


mvn -Dtest=TestCircle#mytest test

Perhaps here a ':5' postfix for selecting a Csv line makes sense for that use-case

**Comment by marcphilipp** [comment]
The ConsoleLauncher already supports this:

```
--select-iteration=method:com.example.TestCircle#mytest()[5]
```

For IDEs and build tools such as Surefire, please raise an issue in the corresponding issue tracker.
