### ISSUE TITLE
org.junit.jupiter.api.ClassOrderer$OrderAnnotation not ordering tests

### ISSUE THREAD

**Issue by StuAtGit** [junit-team/junit5#3095]
Hello,
 I have added:
 `junit.jupiter.testclass.order.default = org.junit.jupiter.api.ClassOrderer$OrderAnnotation`
to my 
`src/test/resources/junit-platform.properties`
file.

I also added it in gradle, and disabled parallelism:

```
    test {
        systemProperty 'junit.jupiter.execution.parallel.enabled', 'false'
        systemProperty 'junit.jupiter.testclass.order.default', 'org.junit.jupiter.api.ClassOrderer$OrderAnnotation'
        useJUnitPlatform {
            systemProperty 'junit.jupiter.execution.parallel.enabled', 'false'
            systemProperty 'junit.jupiter.testclass.order.default', 'org.junit.jupiter.api.ClassOrderer$OrderAnnotation'
        }
```

(You can tell I was getting desperate, as I put it in both places!)

And placed the `@Order` annotation on all the classes.

Yet the classes continue to run:

(1) In the same order they do without the annotation (can't quite make heads or tails of it, but it's deterministic)
(2) NOT the order given by the order annotation

I tried with both the Intellij test runner (set to use gradle), and by running:

`./gradlew test` 

on the command line, but the tests do NOT run in order.

I confirmed the order by creating a 

`    public static final AtomicInteger TEST_ORDER = new AtomicInteger(0);`

variable in one of the test classes, and then printing:

`        System.out.println("..... test class " + TEST_ORDER.incrementAndGet());`

in the constructor for each test class.

## Steps to reproduce

Create a gradle project with multiple test classes, follow the steps above, execute tests using `./gradlew test`

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.9
 - Build Tool/IDE: Intellij

**Comment by StuAtGit** [comment]
I also dumped out the system property in the test constructor like so:

```
        System.out.println("Test orderer: " + System.getProperty("junit.jupiter.testclass.order.default"));
```

The test class set with `@Order(0)`

```
@Order(0)
public class MyMostImportantTests {
    public static final AtomicInteger TEST_ORDER = new AtomicInteger(0);

    public MyMostImportantTests() {
        System.out.println("test class " + TEST_ORDER.incrementAndGet());
        System.out.println("Test orderer: " + System.getProperty("junit.jupiter.testclass.order.default"));
  ....
```

output:

```
test class 11
Test orderer: org.junit.jupiter.api.ClassOrderer$OrderAnnotation
```

Test class names changed to protect the innocent - apologies for any fat-finger errors in that change, but the results are valid.

**Comment by sbrannen** [comment]
Have you tried disabling parallel test execution at the Gradle `test` task level?

```groovy
tasks.withType(Test)  {
  maxParallelForks = 1
}
```

**Comment by StuAtGit** [comment]
@sbrannen - just gave it a try, didn't help. I also tried setting `forkEvery` to 1 .. but that just meant each test class got it's own process, if I understand the effect correctly.

**Comment by marcphilipp** [comment]
@StuAtGit Could you please provide a minimal reproducer?

**Comment by smarkwal** [comment]
@StuAtGit I learned yesterday that class ordering only works when running tests with the Jupiter engine, but not when running old JUnit 4 tests with the Vintage engine. You maybe want to check whether your tests are written using the JUnit 4 or JUnit 5 API.
