### ISSUE TITLE
Reach out to Maven Surefire maintainers regarding JUnit Platform provider

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#31]

**Comment by marcphilipp** [comment]
I've opened [an issue in the Maven Surefire JIRA](https://issues.apache.org/jira/browse/SUREFIRE-1206) regarding future support for JUnit 5 in Maven Surefire.

**Comment by Tibor17** [comment]
@marcphilipp 
Can you show me a prototype where the launcher executes JUnit4 tests on the top of JUnit5 engine?
Can we still interpret this cote in JUnit5?
```
Request req = Request.classes( computer, classesToRun );
```

**Comment by Tibor17** [comment]
>>For tagging we can use Surefire's groups and ignored tests will have to be reported in the same way as now, right?
Groups and tags seem to be compliant.

**Comment by marcphilipp** [comment]
@Tibor17 Please take a look at https://github.com/junit-team/junit5-samples/tree/c9027db477d54ca7a78069eaa9bc9edd819f1235/junit5-maven-consumer

It demonstrates that our [prototype of a `SurefireProvider` provider](https://github.com/junit-team/junit-lambda/blob/prototype-1/surefire-junit5/src/main/java/org/junit/gen5/surefire/JUnitGen5Provider.java) can run both JUnit 5 and JUnit 4 tests.

The code you've posted only works in JUnit 4. The rough equivalent using the new Launcher API would look like:

```java
Launcher launcher = new Launcher();
launcher.registerTestExecutionListeners(listener);
launcher.execute(TestPlanSpecification.build(TestPlanSpecification.forClasses(classesToRun)));
```

Currently there is no equivalent of `Computer` in JUnit 5. Do you need it for parallelization?

**Comment by kcooney** [comment]
To clarify, `Request` isn't going away. It just won't allow you to run JUnit5-style tests

**Comment by marcphilipp** [comment]
Well, `Request` isn't going away, but you won't need it to run JUnit 4 or JUnit 5 tests. Instead you have to build a `TestPlanSpecification` that the new *junit4-engine* will convert into one or multiple `Requests`.

**Comment by marcphilipp** [comment]
@Tibor17 I've updated the README in the sample project: https://github.com/junit-team/junit5-samples/tree/2caa4619577926a368353ca72771346053928aab/junit5-maven-consumer

**Comment by marcphilipp** [comment]
@Tibor17 Here's an overview of our intended overall architecture:

![junit](https://cloud.githubusercontent.com/assets/214207/11817699/68482a30-a356-11e5-8c38-c93d95988488.png)

**Comment by Tibor17** [comment]
IIUC Junit 4 should be wrapped in an engine and TestEngine interface should
be implemented. AFAIK the Launcher executes all tests over all engines. It
seems filtering of applicable classes is a subject to the implementation of
the particular engine, right?
Is the JUnit4TestEngine implementation complete?
The rule in Maven group is to wait for complete JUnit release and then
adapt Surefire to it in master. Meanwhile we can of course make a try and
create a branch with a new provider.

On Tue, Dec 15, 2015 at 6:07 PM, Marc Philipp <notifications@github.com>
wrote:

> @Tibor17 <https://github.com/Tibor17> Here's an overview of our intended
> overall architecture:
>
> [image: junit]
> <https://cloud.githubusercontent.com/assets/214207/11817699/68482a30-a356-11e5-8c38-c93d95988488.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit-lambda/issues/31#issuecomment-164828984>
> .
>



-- 
Cheers
Tibor

**Comment by marcphilipp** [comment]
Yes, exactly. We will provide engines for JUnit 4 and JUnit 5. However, their implementations are not complete, yet. Actually, we've deleted all the code from the prototype and started from scratch.

Our plan is to have a complete implementation of both engines and a stable API in an alpha release in February. I think it would be a good idea to then start a new provider in a branch. This way we'd stumble upon potential problems as early as possible.

@Tibor17 Does that make sense to you?

**Comment by Tibor17** [comment]
Enjoy it :)
We, actually I, have a big task in Surefire. We have an ambition in
Surefire project to open our API for public use. The problem is that JIRA
users report controversial issue however both are valid for relevant use
cases. That's the reason why I need to design such abstraction which
satisfies the users and they would write their own extensions. I should
combine idea of your engines but I am not sure about complete picture of
the extensions yet. So my situation is quite complicated. Some people say
that generic API would never exist , I agree, some people say to use
traditional Maven artifacts as extensions and some people like scripting;
and I want all.

On Tue, Dec 15, 2015 at 8:51 PM, Marc Philipp <notifications@github.com>
wrote:

> Yes, exactly. We will provide engines for JUnit 4 and JUnit 5. However,
> their implementations are not complete, yet. Actually, we've deleted all
> the code from the prototype and started from scratch.
>
> Our plan is to have a complete implementation of both engines and a stable
> API in an alpha release in February. I think it would be a good idea to
> then start a new provider in a branch. This way we'd stumble upon potential
> problems as early as possible.
>
> @Tibor17 <https://github.com/Tibor17> Does that make sense to you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit-lambda/issues/31#issuecomment-164875613>
> .
>



-- 
Cheers
Tibor

**Comment by Tibor17** [comment]
Question. Can you create such API where lazily loaded tests set would be
discovered on the fly?
Not sure if you have it already or not.
This means the length of the Set of classes is unknown ahead. This would
enable us to stream the tests from another machine and distribute the
classes via socket.
I think you can utilize Java 8 streams. WDYT?
In JUnit 4 it was not possible and therefore we complicated implementation
and always had to switch the logic.
I think you can always filter the particular class on the fly and you do
not need to have full test set ready to know if particular class has one
method to run.


On Tue, Dec 15, 2015 at 10:18 PM, Tibor Digana <tibor.digana@googlemail.com>
wrote:

> Enjoy it :)
> We, actually I, have a big task in Surefire. We have an ambition in
> Surefire project to open our API for public use. The problem is that JIRA
> users report controversial issue however both are valid for relevant use
> cases. That's the reason why I need to design such abstraction which
> satisfies the users and they would write their own extensions. I should
> combine idea of your engines but I am not sure about complete picture of
> the extensions yet. So my situation is quite complicated. Some people say
> that generic API would never exist , I agree, some people say to use
> traditional Maven artifacts as extensions and some people like scripting;
> and I want all.
>
> On Tue, Dec 15, 2015 at 8:51 PM, Marc Philipp <notifications@github.com>
> wrote:
>
>> Yes, exactly. We will provide engines for JUnit 4 and JUnit 5. However,
>> their implementations are not complete, yet. Actually, we've deleted all
>> the code from the prototype and started from scratch.
>>
>> Our plan is to have a complete implementation of both engines and a
>> stable API in an alpha release in February. I think it would be a good idea
>> to then start a new provider in a branch. This way we'd stumble upon
>> potential problems as early as possible.
>>
>> @Tibor17 <https://github.com/Tibor17> Does that make sense to you?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/junit-team/junit-lambda/issues/31#issuecomment-164875613>
>> .
>>
>
>
>
> --
> Cheers
> Tibor
>



-- 
Cheers
Tibor

**Comment by marcphilipp** [comment]
I'm not sure I understand you correctly.

Here's what I think you're up to:
- In the VM where the Maven process is running you have a stream of classes you would like to run.
- You want to dispatch the execution of those test classes one-by-one to a set of other VMs running on the same machine.

I assumed that was about what forking did in Surefire, already?

We have an API that allows TestEngines to discover "dynamic" tests at runtime: `TestExecutionListener#dynamicTestRegistered(TestIdentifier)`. We plan to provide support for lambda-based testing, parameterized tests, theories/quickcheck this way.

**Comment by Tibor17** [comment]
In the old JUnit4 we always created new JUnitCore and run only single class.
This is of course an overhead if you consider many fast running methods.
Of course we are streaming classes to the forked VM and we do NOT want
JUnit do that.
All we want to have is some kind of iterator used internally by JUnit5 and
we will provide it to JUnit5 from outside. We already have such one and the
methods like hasNext(), next() have a lock waiting for new stream data -
our goal.
The advantage against traditional JUnit is the fact that all the SPI etc.
was already started up and you do not need to filter all classes in the
begining. This will speed up the execution because you will filter only
particular class right now retrieved from Iterator#next().

On Thu, Dec 17, 2015 at 8:57 AM, Marc Philipp <notifications@github.com>
wrote:

> I'm not sure I understand you correctly.
>
> Here's what I think you're up to:
>
>    - In the VM where the Maven process is running you have a stream of
>    classes you would like to run.
>    - You want to dispatch the execution of those test classes one-by-one
>    to a set of other VMs running on the same machine.
>
> I assumed that was about what forking did in Surefire, already?
>
> We have an API that allows TestEngines to discover "dynamic" tests at
> runtime: TestExecutionListener#dynamicTestRegistered(TestIdentifier). We
> plan to provide support for lambda-based testing, parameterized tests,
> theories/quickcheck this way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit-lambda/issues/31#issuecomment-165377556>
> .
>



-- 
Cheers
Tibor

**Comment by Tibor17** [comment]
@marcphilipp 
Question. Is it possible to use individual `ClassLoaders` per test method in JUnit5?
Last time I did the same with JUnit4 and it was pain because I could not fully reuse `BlockJUnitClassRunner`. The rules handler was written with Reflection because the Runner class was loaded by System ClassLoader and the test class in another one.

**Comment by marcphilipp** [comment]
@Tibor17 Individual class loaders per test method are not on our agenda at the moment. Can you please provide a few details about the use case we're talking about here?

**Comment by Tibor17** [comment]
yes I know it is not in your agenda, but for you maybe a little change in
abstraction would mean a big change for the world :)
Simply there were two use cases.
First use case needed to run parallel tests with a singleton. The status of
the singleton should not be shared across multiple tests.
Second use case was with Java EE CDI container to isolate the beans context
across parallel tests.

On Tue, Dec 22, 2015 at 1:55 PM, Marc Philipp <notifications@github.com>
wrote:

> @Tibor17 <https://github.com/Tibor17> Individual class loaders per test
> method are not on our agenda at the moment. Can you please provide a few
> details about the use case we're talking about here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit-lambda/issues/31#issuecomment-166610358>
> .
>



-- 
Cheers
Tibor

**Comment by marcphilipp** [comment]
@britter is currently reaching out to the Maven Surefire developers.

**Comment by britter** [comment]
You can follow the discussion [here](http://markmail.org/message/nx6qzkarj7r6eyf5). Currently we're planning to meet on freenode to decide on how to move this issue forward.

**Comment by sbrannen** [comment]
Sounds good, @britter. Thanks for taking the initiative!

**Comment by britter** [comment]
Marc and I talked to Tibor via IRC yesterday. The Maven team wants to be sure the JUnit 5 surefire provider has all the features the old provider has. For this reason we're going to setup up their integration tests for JUnit 5. This also relates to my comment in #485 about maven `groups` vs. JUnit `tags`.

**Comment by marcphilipp** [comment]
The initial contribution is done. Thus, I'm closing this issue.
