### ISSUE TITLE
Separate snapshots from releases for published documentation

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#310]
## Status Quo

Snapshots for the _User Guide_ are currently published to: http://junit.org/junit5/docs/current/user-guide

Snapshots for Javadoc are currently published to: https://junit.ci.cloudbees.com/job/JUnit5/javadoc/

This behavior has been acceptable until now since there had not yet been a first milestone release; however, with M1 we will need to devise a better scheme for where documentation is published.

## Deliverables

- [x] Publish snapshots of the User Guide to:
  - http://junit.org/junit5/docs/snapshot/user-guide
- [x] Publish snapshots of the Javadoc to:
  - http://junit.org/junit5/docs/snapshot/api
- [x] Add Gradle task to replace docs/current.
- [x] ~~Publish version M1 of the User Guide to:~~ will be done when releasing M1
  - ~~http://junit.org/junit5/docs/5.0.0-M1/user-guide~~
  - ~~http://junit.org/junit5/docs/current/user-guide~~
    - ~~_current_ may simply redirect to _5.0.0-M1_ (e.g., via a symlink)~~
- [x] ~~Publish version M1 of the Javadoc to:~~ will be done when releasing M1
  - ~~http://junit.org/junit5/docs/5.0.0-M1/api~~
  - ~~http://junit.org/junit5/docs/current/api~~
    - ~~_current_ may simply redirect to _5.0.0-M1_ (e.g., via a symlink)~~

**Comment by marcphilipp** [comment]
*in progress*

**Comment by marcphilipp** [comment]
I've updated the deliverables of this issue. The remainder of the work will be done when releasing M1.

**Comment by marcphilipp** [comment]
The release checklist now contains the necessary steps: https://github.com/junit-team/junit5/wiki/Releasing

**Comment by sbrannen** [comment]
Awesome. Thanks for taking care of that: it's much more professional now! 👍 

I especially like that _Celebrate_ step in the _Releasing_ page. 😉

**Comment by sbrannen** [comment]
Reopening issue since the _redirect_ approach is unfortunately flawed.

Specifically, with the JavaScript/meta redirect approach, it is impossible to actually link to anything within the Javadoc tree.

For example, the User Guide links to the following which does not physically exist (resulting in a _404_): http://junit.org/junit5/docs/current/api/org/junit/platform/runner/package-summary.html

We will therefore have to physically publish the _current_ content to the `current` folder (even if it's just a copy).

**Comment by sbrannen** [comment]
Related resources which might prove useful:

- https://news.ycombinator.com/item?id=7570160
- https://github.com/Sidnicious/gh-pages-symlink-test/issues/4

**Comment by marcphilipp** [comment]
Symlinks won't work because we're using Jekyll. So copying seems to be the only option.

**Comment by sbrannen** [comment]
Alrighty... then copying it is! C'est la vie.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
The current folder is now replaced when using `-PreplaceCurrentDocs`. I've updated the deliverables of this issue and the Releasing wiki page.
