### ISSUE TITLE
Add a way to inherit ResourceLocks that allows for more parallel execution of tests

### ISSUE THREAD

**Issue by Squibbles** [junit-team/junit5#3102]
As seen in issue #2038 if a class level resource lock is specified, even if it is only a READ lock it will cause all tests that inherit it to run single threaded if any one of those tests uses a READ_WRITE lock.  It was suggested in a comment by @leonard84 that it might be possible to add an annotation that would apply to a descriptor's children but not to the descriptor itself.  This kind of functionality would be extremely useful in our project because we have 3000+ tests spread over hundreds of test classes.  I would like to apply a READ lock to our commonly used resources in the inheritance chain rather than having to add individual resource locks on each of several thousand tests. However, if I do specify a class level/inherited lock of any kind it makes any class that inherits it run in SAME_THREAD mode if there is any READ_WRITE locks anywhere in the class.

In this below example the first two tests run in parallel and tests 3/4 run individually as expected.  But if you uncomment the class level resource lock then all tests run individually.  I would like there to be a way to specify that all of these tests have a READ lock on resource2 without having to add the lock individually to each test:

```java
   // @ResourceLock(value = "resource2", mode = READ)
   public class SampleClassLevelLocksTest {

    @Test
    @ResourceLock(value = "resource1", mode = READ)
    void test1() throws InterruptedException {
        Thread.sleep(2000L);
        Assertions.assertTrue(true);
    }

    @Test
    @ResourceLock(value = "resource1", mode = READ)
    void test2() throws InterruptedException {
        Thread.sleep(2000L);
        Assertions.assertTrue(true);
    }

    @Test
    @ResourceLock(value = "resource1", mode = READ_WRITE)
    void test3() throws InterruptedException {
        Thread.sleep(2000L);
        Assertions.assertTrue(true);
    }

    @Test
    @ResourceLock(value = "resource1", mode = READ_WRITE)
    void test4() throws InterruptedException {
        Thread.sleep(2000L);
        Assertions.assertTrue(true);
    }
```

## Deliverables

- [ ] Implement a way to specify resource locks that should be inherited to tests without forcing the tests to run in SAME_THREAD mode if there is a READ_WRITE lock anywhere at the same level

**Comment by marcphilipp** [comment]
**Team decision:** Introduce `@ResourceLock(target = SELF | CHILDREN)` where `target` would default to `SELF` to preserve existing behavior. Using `CHILDREN` would have the same effect as declaring `@ResourceLock` on every `@Test` method of a test class.

**Comment by anatolyD** [comment]
Hey @Squibbles, can you build locally the branch from PR #3220 to see if that brings any improvement? I soon realized my unit tests work insignificantly better (not that many of those I have to show some real boost)

@marcphilipp I would appreciate your feedback too.

**Comment by VladimirDmitrienko** [comment]
@marcphilipp If the work is not currently in progress, I'd be happy to continue. Can I take it?

**Comment by marcphilipp** [comment]
@VladimirDmitrienko Yes, please go ahead! 👍

**Comment by VladimirDmitrienko** [comment]
@marcphilipp regarding [this comment](https://github.com/junit-team/junit5/pull/3220#pullrequestreview-1401371933): do I understand correctly that the proposal is to pass `CHILDREN` locks to "dynamic descriptors"?

For example in this case:

```java
@ResourceLock(value = "a", mode = READ, target = CHILDREN)
@ParameterizedTest
@ValueSource(strings = { "1", "2", "3" })
void test(String s) {
	// ...
}
```
`TestTemplateInvocationTestDescriptor` receives the lock, not `TestTemplateTestDescriptor`; 
but if we set `target = SELF`, then the lock assigned to `TestTemplateTestDescriptor`.

If so, I wonder if it would give us any advantage in terms of execution speed.

Also, seems like it would require several additional changes given we don't support `ExclusiveResource` for "dynamic" containers at the moment (see `DefaultDynamicTestExecutor#execute`).

WDYT?

**Comment by VladimirDmitrienko** [comment]
Agree with that 👍 
Will think about how to validate such cases

**Comment by VladimirDmitrienko** [comment]
@marcphilipp, should we support `target` for "dynamic" resources?
```java
new ResourceLocksProvider.Lock("key", READ, CHILDREN)
```
It seems to me that `target` should apply only to "static" resources. In fact, I’m struggling to think of any use cases for `target = CHILDREN` in "dynamic" resources.
Maybe you have such use cases in mind?

Also, in case `@ResourceLock` declares both: `target` and `providers` at the same time, then `target` should not affect locks declared by `providers` in any way I guess:
```java
@ResourceLock(value = "key", mode = READ, target = CHILDREN, providers = MyProvider.class)
```

**Comment by marcphilipp** [comment]
> It seems to me that `target` should apply only to "static" resources. In fact, I’m struggling to think of any use cases for `target = CHILDREN` in "dynamic" resources.
> Maybe you have such use cases in mind?

I don't have such a use case in mind and agree with not supporting it there. We can always add it later, if necessary.

> Also, in case `@ResourceLock` declares both: `target` and `providers` at the same time, then `target` should not affect locks declared by `providers` in any way I guess

Agreed. Please document that accordingly in the Javadoc for `target`.

**Comment by VladimirDmitrienko** [comment]
@marcphilipp The [PR](https://github.com/junit-team/junit5/pull/4151) is ready for review.
@Squibbles Would appreciate your feedback too.
