### ISSUE TITLE
Composed annotation based on `@EnumSource` with annotation attribute overrides

### ISSUE THREAD

**Issue by armandino** [junit-team/junit5#3103]
I'd like to define a meta-annotation with `@EnumSource`:

```java
@EnumSource(value = MyEnum.class)
@ParameterizedTest
@Target({ElementType.ANNOTATION_TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@interface MyEnumSource {

    String[] names() default {};
}
```

and use it as follows:

```java
@MyEnumSource(names = {"FOO", "BAR", "BAZ"})
void example(MyEnum e) {
   // ...
}
```

Would this be feasible?

**Comment by sbrannen** [comment]
What you are actually asking for is support for composed annotations with annotation attribute overrides.

JUnit 5 supports finding meta-annotations on custom composed annotations; however, JUnit does not provide support for annotation attribute overrides (i.e., the `names` attribute in your composed annotation).

Some frameworks support annotation attribute overrides (for example, Spring Framework's `@AliasFor` support), but JUnit has no plans to provide such support.

- see also: #1440

In light of the above, I am closing this issue.

**Comment by armandino** [comment]
Thanks for providing the background on this. Hopefully, it will be reconsidered by the team some day in the future :)
