### ISSUE TITLE
Introduce `exclude-method` filter to complement `select-method` selector

### ISSUE THREAD

**Issue by kishoretak** [junit-team/junit5#3107]
## Support for exclude-method similar to exclude-class filter or select-method selector

Surefire provides exclude-method support by adding "!" to _includes_ (config)  or _-Dtest_ (command line args), similarly, there should be support for the same in [console-launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher-options) as well.

https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html

**Comment by kishoretak** [comment]
Thanks @marcphilipp, any rough timeline for this feature?

**Comment by sbrannen** [comment]
@kishoretak, we have not scheduled this feature for any upcoming milestone.

As you can see from the assigned labels, we put this in the `status: waiting-for-interest` category.

However, I just added the `up-for-grabs` label to indicate that we would accept a contribution from the community.

**Comment by Sakieye** [comment]
May I give it a try? Do I need to deliver the following items like [issue 313](https://github.com/junit-team/junit5/issues/313)?

- [ ] Introduce include and exclude filter support for methods in a new MethodFilter class (similar to ClassFilter).
- [ ] Introduce include and exclude filter support for methods in the Gradle JUnit Platform plugin.
- [ ] Introduce include and exclude filter support for methods in the JUnitPlatform runner (e.g., @IncludeMethods and @ExcludeMethods).

**Comment by sbrannen** [comment]
@Sakieye,

Thanks for volunteering. Since it's up-for-grabs, anyone is welcome to submit a PR.

Please note, however, that issue #313 is very old. The Gradle JUnit Platform plugin no longer exists, and the `JUnitPlatform` runner for JUnit 4 is deprecated.

Rather (at a quick glance) the focus would be on a `MethodFilter` (as you mentioned) and the `ConsoleLauncher`.
