### ISSUE TITLE
Provide a mechanism to disable stdout and stderr output in XML reports

### ISSUE THREAD

**Issue by jame-s-github** [junit-team/junit5#3109]
Currently in the XML test results files generated by JUnit 5, for each test case, `stdout` and `stderr` are appended by default. This is not a good idea and will easily cause troubles.

For instance, when a test build involves running a large number of tests, which can generate huge amount of text outputs. e.g. in a Jenkins build, 1000 tests were executed, which produced std outputs with a total size of 100Mb. In order to generate JUnit HTML report in a Jenkins build, XML test result files must be saved to Jenkins as archived artifacts. So those large XML files will quickly eat up the disk space of Jenkins servers, when there are more and more builds triggered.

I request JUnit 5 team to provide a flag to enable users to turn off adding `stdout` and `stderr` into the XML result files.

Here is an example of the current format of a `build/test-results/test/xxxx.xml` file. Look at the `<system-out>...</system-out>` and `<system-err>...</system-err>`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SampleTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2022-12-19T01:12:51" hostname="" time="6.773">
  <properties/>
  <testcase name="test2()" classname="SampleTest" time="6.773">
    <failure message="java.lang.AssertionError" type="java.lang.AssertionError">java.lang.AssertionError
	at SampleTest.test2(SampleTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	...
</failure>
  </testcase>
  <system-out><![CDATA[12-18 17:12:51.8890 [?[36mINFO?[0;39m] v.tests.framework.TestBaseWeb - Running beforeAll of TestBaseWeb
12-18 17:12:51.9000 [?[36mINFO?[0;39m] v.tests.framework.TestBaseWeb - # Running a test method #: void SampleTest.test2()
12-18 17:12:56.1730 [?[36mINFO?[0;39m] v.t.s.f.t.managers.Manager - Store a manager instance into 
12-18 17:12:56.1750 [?[36mINFO?[0;39m] v.tests.web.SampleTest - log from test 2 in SampleTest
12-18 17:12:58.4040 [?[36mINFO?[0;39m] v.t.s.f.t.managers.Manager - There is a to be recycled.
12-18 17:12:58.4050 [?[36mINFO?[0;39m] v.t.s.f.t.managers.Manager - Recycling the code: 309585857
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
The report you have supplied is not generated by JUnit 5's `LegacyXmlReportGeneratingListener`. If it were, you would see entries for the `unique-id` and `display-name` similar to the following.

```xml
<system-out><![CDATA[
unique-id: [child:test]
display-name: test
]]></system-out>
```

Thus, I assume the XML report you have provided is generated by Maven, Gradle, Ant, or some other build tool. Consequently, you will need to investigate the configuration options for your build tool.

In light of that, I am tempted to close this issue; however, JUnit 5's `LegacyXmlReportGeneratingListener` and `ConsoleLauncher` also do not have mechanisms for disabling STDOUT and STDERR output in the XML reports generated by JUnit 5.

@junit-team/junit-committers, WDYT about introducing such a mechanism?

**Comment by jame-s-github** [comment]
It's a gradle project, but no matter if I run the test via gradle build or via intellij, it creates the .xml files in the same format. I don't understand why.

**Comment by marcphilipp** [comment]
As @sbrannen pointed out above, the XML report is written by Gradle in this case. I'm not aware of any way to disable test output capturing on Gradle test tasks. Please raise an issue with Gradle directly.
