### ISSUE TITLE
Populate release notes for 5.0.0-M1 in the User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#311]
## Deliverables

- [x] Populate the _Summary of Changes_ section in `release-notes-5.0.0-M1.adoc`

**Comment by marcphilipp** [comment]
Good catch! 👍

**Comment by sbrannen** [comment]
_in progress_ since this is an ongoing team effort

**Comment by sbrannen** [comment]
Update: I'm working on a rudimentary list based on the git log, generated using the following:

`git --no-pager log r5.0.0-ALPHA...TEST --pretty=format:'- %s' --reverse > changelog.txt`

(where `TEST` is a local tag I created)

**Comment by sbrannen** [comment]
Release notes have been completed and pushed to `master`.
