### ISSUE TITLE
Running single test (using mvn -Dtest) not working in JUnit5?

### ISSUE THREAD

**Issue by danuvian** [junit-team/junit5#3122]
The ability to run a single test on a class does not appear to be working for me using JUnit 5. However, it works with JUnit 4.

For JUnit 5, I am using org.junit.jupiter:org.junit.jupiter:5.9.1

When I try to run a single test method with mvn and "-Dtest=", it does not seem to work. 

For examle: "mvn -Dtest=my.package.MyClass#myMethod test"

When I do the above, it runs all my tests, or sometimes does not run any tests.

When I tried switching to using JUnit4 -- junit:junit:4.13.2 -- the above worked fine.

My maven version is: Apache Maven 3.8.4

My Java version is: OpenJDK Runtime Environment Temurin-17.0.1+12

Thanks.

**Comment by marcphilipp** [comment]
@danuvian Please report this issue to the Maven Surefire project as it is handling `-Dtest`.
