### ISSUE TITLE
LifecycleMethodExecutionExceptionHandler not handling exceptions in lifecycle methods

### ISSUE THREAD

**Issue by LeggoMahEggo** [junit-team/junit5#3124]
## Steps to reproduce
TestExtension.java

```
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.LifecycleMethodExecutionExceptionHandler;

public class TestExtension implements BeforeAllCallback, LifecycleMethodExecutionExceptionHandler {

    @Override
    public void beforeAll(ExtensionContext extensionContext) {
        if (true)
            throw new RuntimeException("Exception here");
    }

    @Override
    public void handleBeforeAllMethodExecutionException(ExtensionContext context, Throwable throwable) throws Throwable {
        System.out.println("== BeforeAll Handler ==");
        throw throwable;
    }
}
```

TestClass.java
```
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(TestExtension.class)
public class TestClass {

    @Test
    public void testSomething() {
        System.out.println("Testing a thing");
        Assertions.assertEquals(1+1, 2);
    }
}
```
## Expected result
To see the text `== BeforeAll Handler ==` printed on the console, along with the exception stack trace

## Actual result
Just the exception stack trace

## Note
I also found this behavior in the other lifecycle methods, but did not include them in the sample code.

## Context
Java 16
Jupiter version 5.9.1
IntelliJ IDEA 2021.3.3
Windows 10

**Comment by marcphilipp** [comment]
`LifecycleMethodExecutionExceptionHandler` is about handling exception thrown from lifecycle methods, not extensions:

https://github.com/junit-team/junit5/blob/7212e5a42dcd5db655d59c4900bb306a4f15a048/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/LifecycleMethodExecutionExceptionHandler.java#L18-L21

**Comment by marcphilipp** [comment]
@LeggoMahEggo Could you please elaborate on your use case?

**Comment by LeggoMahEggo** [comment]
@marcphilipp sure. One of my test suites exhaustively tests the content of one my company's web tools, which takes many hours to complete. I also have an extension that implements the callback interfaces of BeforeAll, BeforeEach, AfterEach, and AfterAll, which is registered on an interface that all my test classes implement. I need to be able to handle and log errors that may crop up in any of these methods while running this particular suite.

**Comment by marcphilipp** [comment]
Could you handle those exceptions directly in the extension that implements the callback interfaces for `BeforeAll`, `BeforeEach`, `AfterEach`, and `AfterAll`? Or in a decorator of said extension?

**Comment by LeggoMahEggo** [comment]
Yeah, did something to that effect and it works well. Thank you for your responses.

**Comment by marcphilipp** [comment]
**Team decision:** We don't want to add another exception handler extension point for extensions although it would raise the interesting question who would handle its exceptions...
