### ISSUE TITLE
ArchTest tests not orderable via ClassOrderer

### ISSUE THREAD

**Issue by wimdeblauwe** [junit-team/junit5#3129]
## Steps to reproduce

In a Spring Boot 2.7.7 project, add an ArchUnit test, for example:

```
package com.example.archunitclassorderer;

import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.library.GeneralCodingRules;

@AnalyzeClasses(packagesOf = ArchunitClassordererApplication.class)
public class ArchitectureTest {
    @ArchTest
    public static final ArchRule testsShouldBeInSamePackageAsCodeUnderTest = GeneralCodingRules.testClassesShouldResideInTheSamePackageAsImplementation();

}
```

Also have a ClassOrderer implementation like this:

```
package com.example.archunitclassorderer;

import org.junit.jupiter.api.ClassDescriptor;
import org.junit.jupiter.api.ClassOrderer;
import org.junit.jupiter.api.ClassOrdererContext;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Comparator;

public class SpringBootTestClassOrderer implements ClassOrderer {
    @Override
    public void orderClasses(ClassOrdererContext classOrdererContext) {
        classOrdererContext.getClassDescriptors()
                           .sort(Comparator.comparingInt(SpringBootTestClassOrderer::getOrder));
    }

    private static int getOrder(ClassDescriptor classDescriptor) {
        System.out.println("classDescriptor = " + classDescriptor);
        int result;
        if (classDescriptor.getTestClass().equals(ArchitectureTest.class)) {
            result = -1;
        } else if (classDescriptor.isAnnotated(SpringBootTest.class)) {
            result = 4;
        } else {
            result = 1;
        }

        return result;
    }
}
```

The goal is to have the `ArchitectureTest` run first, then run the normal unit tests and finally run the `SpringBootTest` annotated tests.
This works fine for all the "normal" tests, but the `ArchitectureTest` is always run last, no matter what I try.

The output statement I added in the orderer only prints this:

```
classDescriptor = DefaultClassDescriptor [class = 'public class com.example.archunitclassorderer.SimpleUnitTest']
classDescriptor = DefaultClassDescriptor [class = 'class com.example.archunitclassorderer.ArchunitClassordererApplicationTests']
```

It seems like the `ArchitectureTest` is never passed to the orderer.

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit 5.8.2 (via Spring Boot 2.7.7)
 - Build Tool/IDE: Maven

## Deliverables

I have attached a zip file with the Spring Boot project that shows the problem. If you run `mvn test`, then the `ArchitectureTest` is run last, while I want to have it run first (and ideally fail the complete maven build if it fails, but that is something else I need to figure out).
[archunit-classorderer.zip](https://github.com/junit-team/junit5/files/10443923/archunit-classorderer.zip)

**Comment by marcphilipp** [comment]
@wimdeblauwe Thanks for the report!

`ClassOrderer` is a Jupiter concept, not a Platform one. ArchUnit is a separate test engine and can decide to offer ordering functionality independently from Jupiter. It could for example decide to implement support for `ClassOrderer` from Jupiter or define its own mechanism. Please raise an issue (and link it here) with the ArchUnit project.
