### ISSUE TITLE
Introduce support for filtering packages

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#313]
## Status Quo

It is currently possible to _select_ a package -- for example, for classpath scanning. However, it is not possible to _filter_ packages.

See use case described in #534 for additional input.
## Related Issues
- #301
- #312 
- #314
- #437 
- #474
- #534 
## Deliverables
- [x] Introduce _include_ and _exclude_ filter support for packages in a new `PackageFilter` class (similar to `ClassFilter`).
- [x] Introduce _include_ and _exclude_ filter support for packages in the Gradle JUnit Platform plugin.
- [x] Introduce _include_ and _exclude_ filter support for packages in the `JUnitPlatform` runner (e.g., `@IncludePackages` and `@ExcludePackages`).

**Comment by bechte** [comment]
When specifying filters for packages we have different options how to evaluate the filter rules:

1. Use one filter that handles included and excluded packages (filter rules also apply for sub packages)
2. Use one filter that handles included and excluded packages (filter rules only apply for their specified package)
3. Use two different filters, one for included packages and one for excluded packages (filter rules also apply for sub packages)
4. Use two different filters, one for included packages and one for excluded packages (filter rules only apply for their specified package)

The advantage of having one filter over two different filters is, that it could evaluate all filter rules allowing to specify more granulate filter rules. The advantage of having two separate filters is, that the filters itself are simpler and better to maintain. Therefore, we prefer option 4 in favor to option 2 in case of simplicity.

We can discuss the other options using the following example and see have the filter rule are applied and what the outcome is.

## Example

Given the following filter rules:

No | Package | Filter Rule
----|---------|-----------
1 | org.junit.sample | included
2 | org.junit.sample.module1 | excluded
3 | org.junit.sample.module1.category1 | included
4 | org.junit.sample.module1.category2 | excluded
5 | org.junit.sample.module2 | excluded
6 | org.junit.sample.module3 | included

### Filtering with Option 1

Class | Matching Rules | Filter result | Included in test run?
------|----------------|--------|--------------------------
org.junit.outside.SampleTests | - | **undefined** | **undefined**
org.junit.sample.SampleTests | 1 | included | yes
org.junit.sample.module1.SampleTests | 1, 2 | excluded | no
org.junit.sample.module1.category1.SampleTests | 1, 2, 3 | included | yes
org.junit.sample.module1.category2.SampleTests | 1, 2, 4 | excluded | no
org.junit.sample.module1.category3.SampleTests | 1, 2 | excluded | no
org.junit.sample.module2.SampleTests | 1, 5 | excluded | no
org.junit.sample.module3.SampleTests | 1, 6 | included | yes

**Note:**
- If the Filter does not find any matching rule and has at least one rule, if is undefined if the class should be included or excluded!

### Filtering with Option 3

Class | Matching Rules | Filter result | Included in test run?
------|----------------|--------|--------------------------
org.junit.outside.SampleTests | - | excluded | no
org.junit.sample.SampleTests | 1 | included | yes
org.junit.sample.module1.SampleTests | 2 | excluded | no
org.junit.sample.module1.category1.SampleTests | 3 | included | yes
org.junit.sample.module1.category2.SampleTests | 4 | excluded | no
org.junit.sample.module1.category3.SampleTests | - | excluded | no
org.junit.sample.module2.SampleTests | 5 | excluded | no
org.junit.sample.module3.SampleTests | 6 | included | yes

**Note:**
- If the IncludeFilter does not find any matching rule and has at least one rule, it will decline the class
- The ExcludeFilter does not find any matching rule and has at least one rule, it will accept the class

### Filtering with Option 4

Class | Matching Rules | Filter result | Included in test run?
------|----------------|--------|--------------------------
org.junit.outside.SampleTests | - | excluded | no
org.junit.sample.SampleTests | 1 | included | yes
org.junit.sample.module1.SampleTests | 1, 2 | excluded | no
org.junit.sample.module1.category1.SampleTests | 1, 2, 3 | included | yes
org.junit.sample.module1.category2.SampleTests | 1, 2, 4 | excluded | no
org.junit.sample.module1.category3.SampleTests | 1, 2 | excluded | no
org.junit.sample.module2.SampleTests | 1, 5 | excluded | no
org.junit.sample.module3.SampleTests | 1, 6 | included | yes

**Note:**
- If the IncludeFilter does not find any matching rule and has at least one rule, it will decline the class
- The ExcludeFilter does not find any matching rule and has at least one rule, it will accept the class

## Conclusion

From the example above I suggest to take Option 4, as its filter result is the most obvious solution to me and it has a higher simplicity than Option 2.

**Comment by bechte** [comment]
Team decision: Follow the recommendation and start with option 3.

**Comment by bechte** [comment]
Merged into master with #570

**Comment by sbrannen** [comment]
Thanks, @bechte! :+1:
