### ISSUE TITLE
Introduce support for excluding classes via filters

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#314]
## Status Quo

It is currently possible to _filter_ a class for _inclusion_ but **not** for _exclusion_.

## Related Issues
- #301
- #312 
- #313 
- #474

## Deliverables
- [x] Introduce _exclude_ support in `ClassNameFilter` (e.g., `excludeClassNamePatterns()`)
- [x] Introduce _exclude_ filter support for classes in the `ConsoleLauncher` (e.g., `-N` and `--exclude-classname`).
- [x] Introduce _exclude_ filter support for classes in the Gradle JUnit Platform plugin (e.g., `excludeClassNamePattern()` and `excludeClassNamePatterns()`).
- [x] Introduce _exclude_ filter support for classes in the `JUnitPlatform` runner (e.g., `@ExcludeClassNamePatterns`).

**Comment by mmerdes** [comment]
in progress

**Comment by sbrannen** [comment]
FYI: I updated the deliverables with regard to plurality.

**Comment by marcphilipp** [comment]
Remainder of work is addressed in #644.
