### ISSUE TITLE
Provide a way to create extension via extension factory

### ISSUE THREAD

**Issue by dant3** [junit-team/junit5#3140]
Hello!

We're developing a complicated testing system for our internal needs. Quite often we need to implement custom extensions to provide a reusable building blocks. There are quite some context we need for those extensions. The problem we're facing is that JUnit rules should always have a no-args constructor to be registered via annotation or ServiceLoader mechanisms. There is a way to register extension programmatically via static fields which allows to construct extension instance the way we want, however to do this reusably we will have to use base class which will be extended by every test class -- this is something we would like to avoid because it's often leads to bad practices.

The proposal I have is to allow to register an extension factory. The mechanism can be similar to ParameterResolver or TestInstanceFactory. The extension factory expected to specify a way to deliver the context to the extension by correctly invoking it's constructor, or specifying how to deliver parameters into extension constructor.

**Comment by marcphilipp** [comment]
Where would the extension factory get the context for invoking the extension constructors from?

I think a more concrete example might help me understand this use case better.

**Comment by dant3** [comment]
Consider an example that we're creating an extension which should report test results to some reporting system.
JUnit provides disabled/failed/aborted/successful statuses, howerver our system has bigger amount of statuses to account for test being disabled or failed due to different conditions.
Depending on our design choice we might end up with one or two extensions. One of them is TestWatcher, another is ExecutionCondition. 
In the latter case, we need to share the list of disabled test identifiers between those extensions. This shared list can be a context source, which extension factory will manage, or will have a knowledge where to get from.
In the former case you could argue we can store this information inside of the extension instance itself. However we need guarantees about extension lifecycle then and currently JUnit docs does not provide such a guarantees.

**Comment by dant3** [comment]
Closing this since there is no feedback from JUnit team and I solved my problem, albeit not in the way I would prefer (by using post-construct injection).

**Comment by safeuq** [comment]
This would be a neat feature to have

Currently, in our unit tests, we use Armeria's `ServerExtension` to spin up a test server. The extension itself requires some configuration, so right now, we inject it into the test class (Guice + `TestInstanceFactory`) and mark the field as `@RegisterExtension`. Allowing the ability to configure a factory for Extension classes would simplify this to the plain old `@ExtendWith(ServerExtension.class)` pattern.

I glazed through the code and I noticed that we are instantiating the extensions in `MutableExtensionRegistry` using reflection. Our new factory interface can be a simple SPI that shall be plugged at the point of initialization. Although this might be a problem if multiple SPI providers are available in the classpath.

**Comment by mpkorstanje** [comment]
@safeuq at a glance it sounds like you have a specific server configuration you want to reuse in multiple tests. It also sounds like Armeria has not designed their extension to support that. So I think it would be more fruitful if you addressed a request to Armeria to improve their extension with your usecase in mind.

Though a quick glance at the [`ServerExtension`](https://github.com/line/armeria/blob/main/junit5/src/main/java/com/linecorp/armeria/testing/junit5/server/ServerExtension.java) source suggests that you can extend the class to `MyCustomServerExtension` which sets up the server and then use that extension instead with:

```java
@RegisterExtension
static final MyCustomServerExtension server = new MyCustomServerExtension() 
```

That all said, this issue has been closed for about 3 years now. If neither of the suggestions above provide you with a solution, it would be more productive to start a new issue. If you do, please also include a concrete example of the original problem you are trying to solve.
