### ISSUE TITLE
Move build logic from `buildSrc` to an included build

### ISSUE THREAD

**Issue by britter** [junit-team/junit5#3149]
Using buildSrc to manage build logic is semi-deprecated by the Gradle team because it has several issues, e.g. it's used as an input for all modules, so each change causes a full rebuild of the whole projects. The recommended way of organizing build logic nowadays is to use an included build instead. Here's the proposal for how to do it in the JUnit project:

- `buildSrc` directory is renamed to `gradle/plugins`.
- The new location is defined as an included build in `settings.gradle.kts` by adding an `includeBuild("gradle/plugins")` statement.
- All pre-compiled script plugins are renamed and prefixed with `junitbuild`. This will result in all plugins build from the build logic build having the group prefix `junitbuild`. For example, the `kotlin-library-conventions.gradle.kts` file will be renamed to `junitbuild.kotlin-library-conventions.gradle.kts`. When the plugin is applied the new plugin ID will be `junitbuild.kotlin-library-conventions`. This makes it easier to distinguish custom plugins from core plugins. I propose `junitbuild` instead of `org.junit.gradle` to also indicate that this code is not public facing or meant to be published to an external repository.
- If the team agrees with the above I would also change the root package for code in `gradle/plugins` from `org.junit.gradle` to `junitbuild`.

This is a prerequisite for delivering #3143.

## Deliverables

- [ ] `buildSrc` is migrated to an included build

**Comment by marcphilipp** [comment]
Sounds good to me! 👍
