### ISSUE TITLE
Gradle plugin should support ignoring test failures

### ISSUE THREAD

**Issue by raniejade** [junit-team/junit5#315]
## Proposal

This mirrors Gradle's `Test` task's  [ignoreFailures](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:ignoreFailures) option. 

It should allow the Gradle build to continue even if `junitPlatformTest` fails.
## Related Issues
- #475

**Comment by sbrannen** [comment]
Good point.

We will look into this during the M2 development phase.

**Comment by marcphilipp** [comment]
Since we're in the process of handing over the Gradle plugin to the Gradle team in gradle/gradle#1037, I'm closing this issue.
