### ISSUE TITLE
Introduce Maven BOM for JUnit Platform, Jupiter, and Vintage artifacts

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#316]
## Overview

To ease consumption of _JUnit 5_ artifacts, we should introduce a Maven _Bill Of Materials_ POM ([search for BOM here](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html)) for all published Platform, Jupiter, and Vintage artifacts.

## Proposed Maven Coordinates

- Group ID: `org.junit`
- Artifact ID: `junit-bom`
- Version: `5.2.0`

## Related Issues

- #146 

## Deliverables

- [X] Introduce `junit-bom` Gradle project.
  - See the [spring-framework-bom](https://github.com/spring-projects/spring-framework/blob/master/spring-framework-bom/spring-framework-bom.gradle) Gradle project from the Spring Framework for inspiration.
  - This is the actual [POM](http://search.maven.org/remotecontent?filepath=org/springframework/spring-framework-bom/5.0.3.RELEASE/spring-framework-bom-5.0.3.RELEASE.pom) generated by Spring's `spring-framework-bom` project.
- [ ] Add section to User Guide
- [ ] Publish `junit-bom` POM to Maven Central.
  - either along with the JUnit 5.2 GA release or afterwards

**Comment by sbrannen** [comment]
Tentatively slated for 5.1 GA.

Note, however, that it would be perfectly fine to _publish_ a BOM for 5.1 GA artifacts _after_ 5.1 GA has been released. Ideally we would release the BOM at the same time, but it is technically not an absolute must.

**Comment by sbrannen** [comment]
**Update**:

I overhauled this issue's description and added deliverables.

The name of the BOM is up for debate, but I believe `junit-bom` is a suitable name since:

1. JUnit never had a BOM before.
2. The BOM has to include version information for artifacts from the Platform, Jupiter, _and_ Vintage.

**Comment by sbrannen** [comment]
So, I guess the main question is: _what should be the Group ID of the BOM be_?

**Comment by sbrannen** [comment]
Spring's BOM is published as `compile 'org.springframework:spring-framework-bom:5.0.3.RELEASE'`.

So I'm thinking JUnit's should be published as `compile 'org.junit:junit-bom:5.1.0'`.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment]
FYI: I added a _Proposed Maven Coordinates_ section to this issue's description.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I've added a `junit-bom` subproject that generates a POM with a `<dependencyManagement/>` block. However, the `junit-platform-surefire-provider` needs to be declared in the `<dependencies/>` block of the `maven-surefire-plugin`. There, the `<dependencyManagement/>` block is not taken into account. We could add a `<pluginManagement/>` block and configure the `maven-surefire-plugin` with our provider and both engines as dependencies. However, I'm not sure if declaring the plugin and overriding its dependencies would then still be possible. Thus, I'm postponing this task for further discussion and experimentation until after 5.1 GA is released.

**Comment by sbrannen** [comment]
> I've added a `junit-bom` subproject that generates a POM with a `<dependencyManagement/>` block in b8b0753bfcaccb2231b43edead4b392cd25916e8. 

Thanks! 👍 

> Thus, I'm postponing this task for further discussion and experimentation until after 5.1 GA is released.

SGTM
