### ISSUE TITLE
Unexpected behavior with inheritance and -Dtest with Surefire

### ISSUE THREAD

**Issue by djaekim** [junit-team/junit5#3167]
Here is the test code:

```
public abstract class AbstractClassTest {
    @Test
    public void AbstractMethod1() {
        System.out.println("AbstractMethod1");
    }
    @Test
    public void AbstractMethod2() {
        System.out.println("AbstractMethod2");
    }
}

public class ChildTest extends AbstractClassTest {
    @Test
    public void ChildTestMethod1() {
        System.out.println("ChilTestMethod1");
    }
}
```

When executing tests with ```mvn test -Dtest=ChildTest#AbstractMethod1``` all inherited methods, i.e., AbstractMethod1() and AbstractMethod2(), are executed from the parent, while it omits ChildTestMethod1()

I also get an additional log message:
```
Feb 22, 2023 11:22:42 AM org.junit.vintage.engine.descriptor.RunnerTestDescriptor logIncompleteFiltering
WARNING: Runner org.junit.internal.runners.SuiteMethod (used on class ChildTest) was not able to satisfy all filter requests.
```

Is this an expected behavior? I was wondering how to only select the inherited method from parent that was executed in the child.
The Junit version is 5.8.2

Thank you

**Comment by marcphilipp** [comment]
That filter is implemented on the Surefire side. Please report an issue there.
