### ISSUE TITLE
Add optional `reason` attribute in `@Execution`

### ISSUE THREAD

**Issue by szpak** [junit-team/junit5#3187]
A reason of using a non-default execution mode in parallel test execution might be obvious (e.g. setting System Properties) or not (e.g. multiple cases in acceptance UI testing where some tests share the user which can only have one active session on the server). For those cases, a new optional `reason` attribute in `@Execution` could be used.

We added that field in [Spock recently](https://github.com/spockframework/spock/pull/1576/), so I though, it could be useful also in JUnit Jupiter. WDYT?

## Deliverables

- [x] new optional String `reason` attribute in the [`@Execution`](https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/Execution.java#L99) annotation

**Comment by BassemElMasry** [comment]
@sbrannen @marcphilipp I will pick this one 🙏

**Comment by BassemElMasry** [comment]
> Hi @BassemElMasry,
> 
> 
> 
> We'd like to include this in 5.10 M1, which we plan to release this week.
> 
> 
> 
> Have you had a chance to work on this?

Hey @sbrannen, yes I will try to finalize it this week

**Comment by BassemElMasry** [comment]
@marcphilipp I raised the [PR](https://github.com/junit-team/junit5/pull/3332)

Sorry for the late PR, I did not realize it is a small change and I was overloaded with work.

**Comment by marcphilipp** [comment]
@BassemElMasry No worries, thank you!
