### ISSUE TITLE
Generate User Guide referencing specific revision/tag of Javadoc and source code on GitHub

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#319]
The user guide of a release should point to GitHub sources and Javadoc of the corresponding release tag.

### Deliverables

- [x] Make path to Javadoc configurable.
- [x] Link to Javadoc instead of source code whenever appropriate.
- [x] Math path to the branch or tag for source code on GitHub configurable.
- [x] Document how to build User Guide for a release in [wiki](https://github.com/junit-team/junit5/wiki/Releasing).

**Comment by marcphilipp** [comment]
_in progress_

**Comment by sbrannen** [comment]
I've added a TODO regarding Javadoc, and I'm working on that now.

**Comment by sbrannen** [comment]
Changes introduced in 4bb19f04b319d25af5906a0381ddfc11eac27c26:

The path to Javadoc on the server is now configurable as follows.

- Introduced `docsVersion` project property which defaults to "snapshot"
- `docsVersion` is passed to AsciiDoctor as `docs-version`
- `javadoc-root` in user guide is now constructed using `docs-version`

To change the Javadoc path, simply supply a custom value to the Gradle build. For example, to set the path to 5.0.0-M1, run Gradle as follows.

`gradlew asciiDoc -PdocsVersion=5.0.0-M1`

**Comment by sbrannen** [comment]
Changes introduced in 20a30011775d5f7ae3dd5fbfb9121c665c88f9a5:

The path to the branch or tag for source code on GitHub is now configurable as follows.

- Introduced `releaseBranch` project property which defaults to `master`
- `releaseBranch` is passed to AsciiDoctor as `release-branch`
- Renamed `master-branch` in user guide to `current-branch`
- `current-branch` in user guide is now constructed using `release-branch`

To change the branch/tag path, simply supply a custom value to the Gradle
build. For example, to set the path to 5.0.0-M1, run Gradle as follows.

`$> gradlew asciiDoc -PreleaseBranch=5.0.0-M1`

**Comment by sbrannen** [comment]
FYI: I have updated the _Deliverables_ to reflect the status quo (i.e., the last few commits).

**Comment by sbrannen** [comment]
Note: as of e89ab31ef550e6e694452f4162939ebca20c636d, we are now using the existing calculated `docsVersion` _within_ the User Guide as well.

**Comment by sbrannen** [comment]
FYI: the current `branch` is definitely available via the [versioning plugin](https://github.com/nemerosa/versioning) plugin; however, getting the tag seems to be a bit more challenging in terms of our [Releasing](https://github.com/junit-team/junit5/wiki/Releasing) checklist.

**Comment by sbrannen** [comment]
@marcphilipp, I'm inclined to close this issue (since we have solutions in place) and move the last deliverable (i.e., dynamically determining the release tag, etc.) to a new issue for M2.

What do you think?

**Comment by sbrannen** [comment]
Closing this issue since all primary goals have been achieved for M1.

Additional work may be performed in conjunction with #370.
