### ISSUE TITLE
Improve error message for non-static `@MethodSource` factory methods

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#3215]
We should improve error message for non-static `@MethodSource` factory methods.

The following error message is a bit cryptic:

```
org.junit.platform.commons.PreconditionViolationException:
Cannot invoke non-static method [private java.util.stream.Stream<org.junit.jupiter.params.provider.Arguments> FooTest.params()] on a null target.
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:314)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:723)
	at org.junit.jupiter.engine.execution.DefaultExecutableInvoker.invoke(DefaultExecutableInvoker.java:55)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$provideArguments$1(MethodArgumentsProvider.java:55)
```

```java
    private Stream<Arguments> params() {
        System.out.println("In params()");
        return Stream.of(Arguments.of("bar"));
    }

    @ParameterizedTest
    @MethodSource("params")
    public void test(final String val) {
        System.out.println("In test method for param: " + val);
    }
```

It should read something similar to:

```
private java.util.stream.Stream<org.junit.jupiter.params.provider.Arguments> FooTest.params() must be static
```

**Comment by BassemElMasry** [comment]
@sbrannen is it possible to pick this up?

**Comment by sbrannen** [comment]
@BassemElMasry, yes, feel free to submit a PR.

**Comment by sbrannen** [comment]
> It should read something similar to:
> 
> ```
> private java.util.stream.Stream<org.junit.jupiter.params.provider.Arguments> FooTest.params() must be static
> ```

We need to introduce a custom "precondition" check in `MethodArgumentsProvider` that requires `static` only if the test instance lifecycle is `PER_METHOD`, and the failure message would need to be explicit about.

**Comment by BassemElMasry** [comment]
Hey @sbrannen, I have finalized the PR but this is my first time contributing to open source projects and I am not sure how to open the PR since I am denied any access to push or open a PR. is there any guide I should follow or what do I need to do in order to open the PR?

**Comment by sbrannen** [comment]
@BassemElMasry, the official [GitHub documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests) is pretty thorough.

In addition, there are multiple resources available on the Internet.

**Comment by BassemElMasry** [comment]
@sbrannen I understand of course, I thought I need some certain permissions to be able to push to this repository

**Comment by BassemElMasry** [comment]
@sbrannen I understand of course, I thought I need some certain permissions to be able to push to this repository since I keep getting this 
<img width="895" alt="Screen Shot 2023-04-04 at 14 11 14" src="https://user-images.githubusercontent.com/75857183/229791135-79c06902-4f3c-4545-ad46-6a7c9fee758e.png">

**Comment by sbrannen** [comment]
You need to

- create a fork of this repository
- best to also create a branch in that fork to do the work
- push to your fork on GitHub
- open a pull request based on the branch in your fork

**Comment by marcphilipp** [comment]
@BassemElMasry Any updates?

**Comment by BassemElMasry** [comment]
@marcphilipp I opened the PR

**Comment by sbrannen** [comment]
> We need to introduce a custom "precondition" check in `MethodArgumentsProvider` that requires `static` only if the test instance lifecycle is `PER_METHOD`, and the failure message would need to be explicit about.

Please allow me to correct myself.

What I said was only partially true.

All external factory methods must be `static`, and the improved error message now states that the factory method "must be static unless the test class is annotated with `@TestInstance(Lifecycle.PER_CLASS)`" which is not true if it's an external factory method.

The test instance lifecycle has no influence on external factory methods.

I will push a _fix_ for that.

**Comment by BassemElMasry** [comment]
@sbrannen @marcphilipp is there anything else that I could take a stab at? I can see some issues up for grabs but it is from
Very long time and I am not sure what are the statuses on those!

**Comment by marcphilipp** [comment]
@BassemElMasry One of these?

- https://github.com/junit-team/junit5/issues/3187
- https://github.com/junit-team/junit5/issues/1555

**Comment by BassemElMasry** [comment]
@marcphilipp thank you for the suggestions! I will pick up [3187](https://github.com/junit-team/junit5/issues/3187)
