### ISSUE TITLE
Please update link for engine of cucumber

### ISSUE THREAD

**Issue by S-Kerrigan** [junit-team/junit5#3218]
Current [wiki-page](https://github.com/junit-team/junit5/wiki/Third-party-Extensions) have list of different engines with links
In Cucumber-project was changed directory (and path)
Before: https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine
Now: https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-junit-platform-engine

**Comment by sbrannen** [comment]
I updated the link.

Please note, however, that there is no need to create an issue for this.

You can edit the page yourself, which would have been less work than creating this detailed issue. 😉
