### ISSUE TITLE
Revert disallowing private lifecycle methods

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#3242]
In #2914 validation was added to fail when encountering private lifecycle methods. Since we've received reports from multiple users that this broke tests for them, we should revert this change. Instead, we should document that using `private` for lifecycle methods is discouraged and support for them is likely to be removed in the next major release. 

## Deliverables

- [x] Revert validation for `private` lifecycle methods
- [x] Document `private` as being discouraged

**Comment by sbrannen** [comment]
Reopening to backport to `5.9.3`.

**Comment by marcphilipp** [comment]
Cherry-picked to the `releases/5.9.x` branch.

**Comment by sbrannen** [comment]
Closely related to:

- #3553
