### ISSUE TITLE
Promote `EXPERIMENTAL` APIs that have matured to `STABLE`

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#3248]
Several features that have existed for quite a while are still marked as `EXPERIMENTAL` APIs. This includes constants, methods, and annotation attributes not listed in the [Experimental APIs](https://junit.org/junit5/docs/current/user-guide/#api-evolution-experimental-apis) table.

Since we have not received negative feedback from the community regarding these features, we should promote them to "stable" APIs.

**Comment by sbrannen** [comment]
@junit-team/junit-5, and objections?

**Comment by sormuras** [comment]
None.

**Comment by marcphilipp** [comment]
SGTM. 👍

**Comment by sbrannen** [comment]
Reopening to ensure that attention is brought to this in the Release Notes.
