### ISSUE TITLE
`./gradlew build` fails due to checkstyle errors

### ISSUE THREAD

**Issue by mpkorstanje** [junit-team/junit5#3268]
## Steps to reproduce

Checkout `main` (currently at 07f2bf349e45f5a63228cb6002ae7bdbd3445ce1) and run:
```
 ./gradlew build
...
> Task :checkstyleNohttp
[ant:checkstyle] [ERROR] /home/mpkorstanje/Projects/junit-team/junit5/buildSrc/build/generated-sources/kotlin-dsl-accessors/kotlin/gradle/kotlin/dsl/accessors/_01a7fddcf81aa279b379d6fe3cb64505/Accessors8lcri9ibgd9oj8dt3t8z8nvfx.kt:9:10: http:// URLs are not allowed but got 'http://www.apache.org/licenses/LICENSE-2.0'. Use https:// instead. [NoHttp]

[many more of these]
...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleNohttp'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > Checkstyle rule violations were found. See the report at: file:///home/mpkorstanje/Projects/junit-team/junit5/build/reports/checkstyleNohttp/nohttp.html
     Checkstyle files with violations: 719
     Checkstyle violations by severity: [error:719]

...
```

Looks like the generated code is included in the check style. This code includes a http link to the Apache Licence,

**Comment by marcphilipp** [comment]
`buildSrc` was deleted in #3149. Please delete it manually which should only be necessary once.

**Comment by sbrannen** [comment]
> `buildSrc` was deleted in #3149. Please delete it manually which should only be necessary once.

Well, it will keep reappearing if you switch between `5.9.x` and `main`, like what just happened to me.

But... I guess that won't happen verify often. 😇

**Comment by sbrannen** [comment]
Side note: you may have to stop the Gradle daemon to delete that folder.

At least I had to.

**Comment by marcphilipp** [comment]
I pushed 918f0970bce9e010b8b085dd25471984854f1665 to avoid having to fight that for the time being.

**Comment by mpkorstanje** [comment]
Cheers!
