### ISSUE TITLE
Do you like to have native support of Allure Framework

### ISSUE THREAD

**Issue by baev** [junit-team/junit5#329]
Hi there! Do you like to have native support of Allure Framework? We would like to move Allure integration code to your repository, so you could maintain it at your will and e.g. add early support of your new features such `@DisplayName`. We on our turn would like to move a little bit away from solving test framework specific issues and concentrate on general reporting problems to make Allure rock. What do you guys think?

**Comment by sbrannen** [comment]
Although we of course appreciate the gesture, the answer is unfortunately no.

As a policy, JUnit projects do not depend on any third-party libraries or frameworks [*], and [for very good reasons](https://github.com/junit-team/junit5/wiki/Core-Principles#minimize-dependencies-especially-third-party).

Please see the following discussion for further insight: https://github.com/junit-team/junit5/issues/321#issuecomment-227106343

Of course, if you have questions about how to best integrate with JUnit 5, or if you find bugs or areas for improvement, we would be glad to assist you.

**Comment by baev** [comment]
@sbrannen thanks for the answer.
