### ISSUE TITLE
5.10.0-M1 & SimpleArgumentConverter

### ISSUE THREAD

**Issue by sysmat** [junit-team/junit5#3309]
- `SimpleArgumentConverter` has Override `Object convert(Object source, Class<?> type) throws ArgumentConversionException`, but convert wants `ParameterContext` which is an interface, so what is implementing `ParameterContext`

```java
@Override
protected Object convert(Object source, Class<?> type) throws ArgumentConversionException {
        if ("null".equals(source))
            return null;        
        return DefaultArgumentConverter.INSTANCE.convert(source, type);
}
```
- is there any way from Class<?> to create ParameterContext  implementation?

**Comment by marcphilipp** [comment]
Have you tried implementing `ArgumentConverter` directly without extending `SimpleArgumentConverter`?

**Comment by sysmat** [comment]
@marcphilipp with implementing ArgumentConverter it works, thx
