### ISSUE TITLE
Support `@TempDir` as a meta-annotation

### ISSUE THREAD

**Issue by marschall** [junit-team/junit5#3311]
With 5.10-M1 offering `TempDirFactory` it would be great to have `@TempDir` meta annotation capable.

To give you an example, I have [my own TempDirFactory](https://github.com/marschall/memoryfilesystem-junit-provider/blob/master/src/main/java/com/github/marschall/memoryfilesystem/junit/MemoryFileSystemTempDirFactory.java) (I know it's not thread safe yet) that creates directories on a in-memory file system.

If my users do not want to switch the global default provider they have to use this everywhere.

```java
@TempDir(factory = MemoryFileSystemTempDirFactory.class)
Path tempDirectory;
```
If `@TempDir` is meta annotation capable we can instead define the following meta annotation

```java
@Retention(RUNTIME)
@Target({FIELD, PARAMETER, ANNOTATION_TYPE})
@TempDir(factory = MemoryFileSystemTempDirFactory.class)
public @interface MemoryTempDir {
  
}
```

and our users can use:

```java
@MemoryTempDir
Path tempDirectory;
```

If we want to go further and allow the user some configuration options, eg. which file system semantics (Windows, Linux, ...) they want we would use an annotation for this.

With meta annotations instead of having

```java
@MemoryTempDirType(WINDOWS)
@TempDir(factory = MemoryFileSystemTempDirFactory.class)
Path tempDirectory;
```

we could have a meta annotation

```java
@Retention(RUNTIME)
@Target({FIELD, PARAMETER, ANNOTATION_TYPE})
@MemoryTempDir
@MemoryTempDirType(WINDOWS)
public @interface WindowsMemoryTempDir {

}
```

And the user could simply write

```java
@WindowsMemoryTempDir
Path windowsTempDirectory;
```

## Deliverables

- [x] Add `ElementType.ANNOTATION_TYPE` to `@Target` of `@TempDir`

I would be willing to work on a PR.

**Comment by marcphilipp** [comment]
I think that sounds like a good idea! 👍

**Comment by sbrannen** [comment]
> I would be willing to work on a PR.

@marschall, I've assigned this to you, so feel free to submit a PR.
