### ISSUE TITLE
Improve documentation for `TempDirFactory` API contract

### ISSUE THREAD

**Issue by marschall** [junit-team/junit5#3312]
The API Javadoc of `TempDirFactory` does not define what the threading model is. This forces the implementer to make assumptions. See Effective Java, 3rd Edition Item 82: Document thread safety.

I would assume something like this:
- An instance is created whenever a `@TempDir` value is requested for the first time.
- `#createTempDirectory` can be called concurrently by multiple threads
- `#close` will not be called before the last call to `#createTempDirectory` has returned
- `#close` will be called only once
- `#close` will be called when the engine is shut down

An alternative would be to define a general threading model to be supported by [extensions](https://junit.org/junit5/docs/snapshot/user-guide/#extensions) and link to this.

## Deliverables

- [ ] explicitly define the threading model to be supported by `TempDirFactory` implementations

**Comment by marcphilipp** [comment]
Actually, `createTempDirectory` will only be called once per `TempDirFactory` instance and from the same thread as `close` but I agree that it should be documented.

**Comment by scordio** [comment]
@marcphilipp happy to give this one a try, if that's fine with you.
