### ISSUE TITLE
Version 5.10.0-M1 failed with missing class: NamespacedHierarchicalStore$CloseAction

### ISSUE THREAD

**Issue by binkley** [junit-team/junit5#3314]
```
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.support.store.NamespacedHierarchicalStore$CloseAction
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

## Steps to reproduce

Using this repository and commit -- https://github.com/binkley/kotlin-dice/commit/72371bff2f6d031b1fb1465efe8d95b54acbde68
Update `pom.xml` with `junit.version` set to 5.10.0-M1
Run a build with `./mvnw clean verify`
Failure is during the `test` goal.

Previous release version 5.9.3 works.

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.10.0-M1
 - Build Tool/IDE: Maven

## Deliverables

- [ ] ...

**Comment by mpkorstanje** [comment]
At a glance I see that `kotlin-dice` doesn't use the `junit-bom`. So it's likely that dependencies don't converge. One potential cause of this could be `kotest-runner-junit5-jvm`.

You can verify this by using `mvn dependency:tree -Dverbose`.

**Comment by binkley** [comment]
@mpkorstanje Thank you! This was helpful _and_ insightful.
This issue affected several of my projects. My choice of example project ("kotlin-dice") may have clouded things.

A simpler repo failing pre/post application of BOM is Kunits. It passed with 5.9.3, failed with 5.10.0-M1, and passed against with 5.10.0-M1 using the BOM: https://github.com/binkley/kunits/tree/9df81fa545d674da9731803dedeae42cebb61718

My latest successful build with kotlin-dice includes 5.10.0-M1 after:
1. Cleaning `pom.xml` (removing duplication, etc)
2. Using the JUnit BOM

I wasn't aware of either the BOM or of the `-Dverbose` flag to `dependency:tree`. These are going into my bag of tricks for builds.

**Comment by marcphilipp** [comment]
If I interpret your comment correctly, you were able to resolve the issue using the BOM. Please let me know otherwise.

**Comment by binkley** [comment]
@marcphilipp Yes sir! Using the BOM fixed my problems, and I've added to my list of recommendations for developers on JVM:
https://github.com/binkley/modern-java-practices#tips-13

**Comment by binkley** [comment]
I would suggest updating this section of the documentation:
https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven
to show use of BOM.

**Comment by marcphilipp** [comment]
@binkley Good idea! Done in https://github.com/junit-team/junit5/commit/7ba55150060beec798ffb0e982e2ea69055b7a69.
