### ISSUE TITLE
Console launcher should support `NO_COLOR` environment variable

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#3328]
Support `NO_COLOR` environment variable as described by https://no-color.org in JUnit's console launcher.

**Comment by marcphilipp** [comment]
**Team decision:** Check if picocli supports this already and, if not, raise an issue.

**Comment by sormuras** [comment]
Seems to be the case: https://picocli.info/#_heuristics_for_enabling_ansi

**Comment by marcphilipp** [comment]
**Team decision:** Check if our Console Launcher already supports this or what would need to be done in order to do so.

**Comment by sormuras** [comment]
- `$ java -jar junit-platform-console-standalone-1.10.3.jar engines`

> 💚 `Thanks for using JUnit! Support its development at https://junit.org/sponsoring`
> 
> **`junit-jupiter`**` (org.junit.jupiter:junit-jupiter-engine:5.10.3)`
> **`junit-platform-suite`**` (org.junit.platform:junit-platform-suite-engine:1.10.3)`
> **`junit-vintage`**` (org.junit.vintage:junit-vintage-engine:5.10.3)`

- `$ export NO_COLOR=1`
- `$ java -jar junit-platform-console-standalone-1.10.3.jar engines`

> ```
> Thanks for using JUnit! Support its development at https://junit.org/sponsoring
> 
> junit-jupiter (org.junit.jupiter:junit-jupiter-engine:5.10.3)
> junit-platform-suite (org.junit.platform:junit-platform-suite-engine:1.10.3)
> junit-vintage (org.junit.vintage:junit-vintage-engine:5.10.3)
> ```

The console launcher already does support `NO_COLOR`.

**Comment by sbrannen** [comment]
> The console launcher already does support `NO_COLOR`.

Cool! 👏 

In light of that, I'm removing this from the 5.11 RC1 milestone.

**Comment by dhoard** [comment]
Based on my testing using 5.11, the `NO_COLOR` environment variable is not fully supported.

**Shell**

```bash
> export NO_COLOR=1
> export | grep NO_COLOR
declare -x NO_COLOR="1"
> java -cp "junit-platform-console-standalone-1.11.0.jar:tests/target/test-classes:tests/lib/*" org.junit.platform.console.ConsoleLauncher execute --scan-classpath -n "JUnit5"
```

**Output**

![image](https://github.com/user-attachments/assets/4d5dca9b-f36a-4a72-b04d-ccd8f206053e)

**Code**

Looking at the code, only the `--disable-ansi-colors` command line option is used to determine whether to use ANSI colors. If I use the command line option, ANSI colors are disabled.

https://github.com/junit-team/junit5/blob/40bc1c4146d91b595668bd06402dba0a83d05b9f/junit-platform-console/src/main/java/org/junit/platform/console/options/AnsiColorOptionMixin.java#L32-L37

**Comment by sormuras** [comment]
Thanks for reporting this, @dhoard - it's an initialization issue.

https://github.com/junit-team/junit5/blob/abf5ac3f2e17911bd932f020d2726b01d3c68a6b/junit-platform-console/src/main/java/org/junit/platform/console/options/AnsiColorOptionMixin.java#L26 should read like: `private boolean disableAnsiColors = System.getenv("NO_COLOR") != null;` instead of being set to `false`. It would be even better to tap into PicoCLI's [heuristic](https://picocli.info/#_heuristics_for_enabling_ansi) programmatically.

**Comment by sbrannen** [comment]
Reopening to backport to the `5.10.x` branch:

- [ ] backport code changes
- [ ] move release notes entry to appropriate file(s)
- [ ] backport release notes
