### ISSUE TITLE
Declare `ClassLoader` as first parameter in `DiscoverySelector` methods and constructors

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#3335]
## Overview

This is a prerequisite for #3326.

## Deliverables

- [x] Declare `ClassLoader` as first parameter in `DiscoverySelector` methods and constructors.
- [x] Document in Release Notes.

**Comment by sbrannen** [comment]
@kriegfrj, in order to make it easier to introduce var-args in various selectors, I've decided to go with your original proposal to introduce the `ClassLoader` parameter first. 😉

**Comment by kriegfrj** [comment]
> @kriegfrj, in order to make it easier to introduce var-args in various selectors, I've decided to go with your original proposal to introduce the `ClassLoader` parameter first. 😉

I'm not sure whether to laugh or cry... 🤣 The joys and pains of software development. 😄 Thank you for your hard work.
