### ISSUE TITLE
Introduce `assertInstanceOf()` for Kotlin

### ISSUE THREAD

**Issue by bjmi** [junit-team/junit5#3353]
This is a follow up of #2492 but for Kotlin.

After discovering the new `assertInstanceOf` assertion (since 5.8) I find it really expressive and useful.
Could you please also add a Kotlin variant to _Assertions.kt_? E.g.

Usage:

```
Now:      assertInstanceOf(String::class.java, actual)
Proposal: assertInstanceOf<String>(actual)
```

Definition:

```
inline fun <reified T : Any> assertInstanceOf(actualValue: Any?): T =
    Assertions.assertInstanceOf(T::class.java, actualValue)
...
```

**Comment by marcphilipp** [comment]
@bjmi Thanks for creating the issue! I think this would be a natural addition. Would you be interested in submitting a PR?

**Comment by bjmi** [comment]
I can give it a try.

**Comment by TWiStErRob** [comment]
@Mikhail2048/@bjmi there are two PRs for this now.

**Comment by TWiStErRob** [comment]
@Mikhail2048 / @bjmi there are two PRs for this now.

**Comment by andrewparmet** [comment]
It would be great for this implementation to use Kotlin's contracts feature so the instance can be used subsequently as an instance of the expected class.

See also: https://youtrack.jetbrains.com/issue/KT-28298 which has been implemented.

A slight modification of #3492:
```kotlin
inline fun <reified T : Any> assertInstanceOf(actualValue: Any?, message: String? = null): T {
    contract {
        returns() implies (value is T)
    }
    return Assertions.assertInstanceOf(T::class.java, actualValue, message)
}
```

will allow this pattern without cast:

```kotlin
val bar: Any = foo()
assertIsInstanceOf<String>(bar)
bar.lowercase() // bar is a String
```

**Comment by TWiStErRob** [comment]
@andrewparmet you can leave a suggestion as a review on a PR in context, more likely to get noticed when the PR is reviewed.
