### ISSUE TITLE
JUnit 5 to support min performance testing if not the advanced peformance specification

### ISSUE THREAD

**Issue by nagkumar** [junit-team/junit5#3375]
It is good if JUnit 5 support 

@RepeatedTest(10) at class and more so at suite level and make sure this annotation is supported with tests parallel execution.

With that simple repeat execution support, unit tests can definitely expose concurrency issues much faster at development time itself.

additionally it can also support

`rampup `and `number of threads `to use simpler to JMeter testplan.

Goal here is not the latency measurements but to make sure concurrency is exposing any object state issues.

**Comment by marcphilipp** [comment]
**Team decision:** Repeating tests and running them concurrently at the class/suite level does not necessarily surface concurrency issues. In our experience, it is best to write targeted tests that use multiple threads that exercise a particular use case that you suspect may have concurrency issues.
