### ISSUE TITLE
Provide Mock Support for Unirest Call

### ISSUE THREAD

**Issue by vamsi-6579** [junit-team/junit5#3404]
Provide Mocking support for Unirest call in junit5 by updating the existing dependency or by adding new dependencies

**Comment by marcphilipp** [comment]
We don't provide testing/mocking support for third-party libraries. Instead, libraries are encouraged to provide testing support as a separate artifact as, for example, Spring does.

@vamsi-6579 Could you please raise an issue with the Unirest folks instead?
