### ISSUE TITLE
GraalVM native tests failing with 5.10.0 version

### ISSUE THREAD

**Issue by jeanbisutti** [junit-team/junit5#3405]
Version: 5.10.0

The  [daily GraalVM native tests of the _OpenTelemetry Instrumentation for Java_ project are failing](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9044) from [the bump of org.junit:junit-bom from 5.9.3 to 5.10.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9031).

To reproduce:

`git clone https://github.com/open-telemetry/opentelemetry-java-instrumentation.git`

`cd opentelemetry-java-instrumentation`

`./gradlew nativeTest`

The addition of the following initializations at  the build time fixes the issue:

`--initialize-at-build-time=org.junit.platform.launcher.core.LauncherConfig`

`--initialize-at-build-time=org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter`

[It seems that JUnit 5 code is doing theses initializations for testing.](https://github.com/junit-team/junit5/blob/22a64e7aad5ae0e3c9cf2a692f77bd3de8d1bbed/platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts#L34)

One  way to make  JUnit 5.10.0 works with GraalVM native could be the addition of a _native-image.properties_ file with these initializations in a Junit 5 jar.

**Comment by marcphilipp** [comment]
Yes, that's correct 5.10.0 requires additional flags as stated in the [release notes](https://junit.org/junit5/docs/current/release-notes/index.html#deprecations-and-breaking-changes).

I've just checked and it seems these have already been added by @melix in https://github.com/graalvm/native-build-tools/pull/471.
