### ISSUE TITLE
How can I put all dependent jar packages into one directory and execute them together？

### ISSUE THREAD

**Issue by Danst-bjtu** [junit-team/junit5#3412]
When the test I want to execute requires the introduction of multiple dependent jar packages, the command line must write - cp multiple times, which is too long. How can I put all dependent jar packages into one directory and execute them together？

java -jar junit-platform-console-standalone-1.9.3.jar -cp test -cp .\commons-3.31.0.jar -cp .\abc-engine-0.1.0.jar -cp .\abc-formula-0.1.0.jar -cp .\antlr-runtime-3.2.jar --scan-classpath --reports-dir=.\

![image](https://github.com/junit-team/junit5/assets/77576766/18e356c6-5258-41c2-8f69-870cac117fe5)

When I put all jar packages in one directory, such as testlib, it will appear that the class cannot be found. 
java -jar junit-platform-console-standalone-1.9.3.jar -cp test -cp testlib --scan-classpath --reports-dir=.\
![image](https://github.com/junit-team/junit5/assets/77576766/84edcf85-82e6-45c6-9943-9126bb212b92)

**Comment by sbrannen** [comment]
Please read the User Guide before posting questions.

This is documented in the [Console Launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher) section:



> You can also run the standalone ConsoleLauncher as shown below (for example, to include all jars in a directory):
> 
> `$ java -cp classes:testlib/* org.junit.platform.console.ConsoleLauncher <OPTIONS>`
>
