### ISSUE TITLE
Improve Javadoc for `assertTimeoutPreemptively` regarding thread interrupt

### ISSUE THREAD

**Issue by karstenspang** [junit-team/junit5#3424]
The [description](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html#assertTimeoutPreemptively(java.time.Duration,org.junit.jupiter.api.function.Executable)) in the various `Assertions.assertTimeoutPreemptively` methods is vague. It states

> Furthermore, execution of the `executable` will be preemptively aborted if the timeout is exceeded.

It is not clear what is meant by "aborted". Looking at the source code of both JUnit and JDK, I can see what happens is that the thread is interrupted. I suggest that the description be changed to something like

> Furthermore, it will be attempted to preemptively abort execution of the `executable` by calling `interrupt()` on the thread if the timeout is exceeded. If the `executable` does not return when interrupted, the thread will be left running.

**Comment by sbrannen** [comment]
Hi @karstenspang,

Congratulations on creating your first issue for JUnit 5. 👍 

I've addressed this in 7fb4165c94fb8d9c0e9dfd30519371d3ca73e1fe

Thanks for the suggestion
