### ISSUE TITLE
Ensure dependency diagram is generated in User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#3430]
The dependency diagram is no longer generated in the [User Guide](https://junit.org/junit5/docs/current/user-guide/#dependency-diagram).

**Comment by marcphilipp** [comment]
I fixed the `5.10.0` and `current` docs retroactively in https://github.com/junit-team/junit5/commit/4257ad1a8592e639c93dcd4ee60642a496b8c41c

**Comment by sbrannen** [comment]
> I fixed the `5.10.0` and `current` docs retroactively in [4257ad1](https://github.com/junit-team/junit5/commit/4257ad1a8592e639c93dcd4ee60642a496b8c41c)

Thanks for the quick-fix!

Interestingly, the diagram is actually included in the [PDF](https://junit.org/junit5/docs/current/user-guide/junit-user-guide-5.10.0.pdf), but it's missing the text for the API Guardian note as well as the dashed arrow lines.

**Comment by marcphilipp** [comment]
I'm still trying to figure out what's going on. The diagram is also missing from the snapshot docs
