### ISSUE TITLE
`TestInstancePostProcessor` cannot be registered via `@ExtendWith` on a non-static field

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#3437]
## Overview

As discovered by @graydavid in #3433, there is an issue regarding extension registration via `@ExtendWith` on instance fields.

The following is a simplification of the `RandomNumberDemo` from the User Guide which demonstrates the problem.

```java
// @ExtendWith(RandomNumberExtension.class)
class RandomNumberDemoTest {

	@Random
	Integer randomNumber;

	@Test
	void test() {
		assertThat(this.randomNumber).isNotNull();
	}
}
```

The above test fails; however, if you annotate the test class with `@ExtendWith(RandomNumberExtension.class)` the test then passes.

The reason is that `ClassBasedTestDescriptor#instantiateAndPostProcessTestInstance()` invokes `ExtensionUtils.registerExtensionsFromFields()` too late.

I even added the following comment when I introduced that support.

```java
// In addition, we register extensions from instance fields here since the
// best time to do that is immediately following test class instantiation
// and post processing.
```

In retrospect, that is not the "best time to do that" when a field is annotated (or meta-annotated in the case of `@Random`) with an `@ExtendWith` annotation that registers an extension that implements `TestInstancePostProcessor`.

## Related Issues

- #3433
- #3463

## Deliverables

- [ ] Revise the usage of `ExtensionUtils.registerExtensionsFromFields()` so that a `TestInstancePostProcessor` can be registered via `@ExtendWith` on a non-static field.

**Comment by Michael1993** [comment]
Should I be able to inject a `@RegisterExtension` value with a field-level `TestInstancePostProcessor`?

Example:
```java
class BasicTests {

  @ExtendWith(ExtensionInjector.class)
  ExtensionInjector injector;

  @RegisterExtension
  ParameterResolver extension;

  // some tests...
}
```

Can I work on this issue? Other than this one question, I think I can handle it.

**Comment by sbrannen** [comment]
Hi @Michael1993,

> Should I be able to inject a `@RegisterExtension` value with a field-level `TestInstancePostProcessor`?

Ideally, yes, I believe so. At least, generally speaking a `TestInstancePostProcessor` should be capable of doing that.

I believe I demonstrated that once with Spring. Let me see if I can find it...

**Comment by sbrannen** [comment]
> I believe I demonstrated that once with Spring. Let me see if I can find it...

https://stackoverflow.com/a/50251190/388980

**Comment by sbrannen** [comment]
> Also: can I work on this issue? Other than this one question, I think I can handle it.

Thanks for volunteering!

However, this issue is assigned to me and not labeled as `up-for-grabs`.

In addition, it may turn out to be more challenging than you expect.

In light of that, I would like to keep this assigned to me.

FWIW, I took a glance at your [spike](https://github.com/Michael1993/junit5/commit/bb00173c2ca617eb4ff60a588bfc44b9b07115e5), and I'd like to point out that we have no plans to add specific handling for a particular extension API (such as `TestInstancePostProcessor`). Rather, I will implement a general solution that applies to any extension type registered via `@ExtendWith` on both static and non-static fields, and I've already begun work on this issue.

**Comment by Michael1993** [comment]
Sorry, I don't know how I missed that. I will take a look at the up-for-grabs issues instead, then. 🙂
