### ISSUE TITLE
Use runtime or run-time consistently in the user guide

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#344]
Currently both run-time and runtime are used in the user guide.  Compile-time is consistent.  Two of the three references to execution time (without a hyphen) refer to the wall clock time of a lambda's execution (versus the use of run-time as a reference to the execution lifecycle?).  One of the uses of execution time refers to the period during which the method being timed is running.

**Comment by sbrannen** [comment]
Wow. Thanks for reading the User Guide so closely!

We'll look into this for M2.

**Comment by smoyer64** [comment]
No hurry ... I'd be happy to go through the whole manual with a fine-tooth comb at some point (and perhaps force some of our developers to use JUnit 5 without looking at Javadocs or code).  I'm a little busy at the moment but how about I make a pass after M1?

**Comment by marcphilipp** [comment]
Sure, sounds good! 👍

**Comment by sbrannen** [comment]
Agreed: that sounds great! 👍 

However, I'm not sure why you would want to force anyone to use JUnit 5 without being able to read the Javadoc. IMHO, the Javadoc can be just as important or more important than the User Guide.

And... yes, I'd definitely recommend holding off on such a task until after M1 goes out.

**Comment by smoyer64** [comment]
"However, I'm not sure why you would want to force anyone to use JUnit 5 without being able to read the Javadoc."

I've actually used this technique quite a few times, and not just in Java or a programming environment.  It's an interactive process and you often need to pick someone with no prior exposure to the subject.  As they (try to) work, you keep track of the questions they ask - and give them the answers they need to continue.  For each of the questions, you determine whether (in this case) it should be in the User Guide or whether the Javadocs are the right place for the information.  Sometimes the answer will be both - and other times the answer might be a link to the appropriate junit5-samples.

It's not supposed to be torture ;)

**Comment by sbrannen** [comment]
good, good.... no torture.

Sounds like a good technique for achieving the desired results!

**Comment by sbrannen** [comment]
This has been addressed in e26c3c791f003358cef544e886eb9a7d6a05b7c4.

However, I only came across one reference to "execution time". Thus, if I have overlooked something, please let me know.

**Comment by sbrannen** [comment]
This has been addressed in e26c3c791f003358cef544e886eb9a7d6a05b7c4.

However, I only came across one reference to "execution time". Thus, if I have overlooked something, please let me know.

**Comment by smoyer64** [comment]
I should have added a commit id as a marker when I created this issue.  From memory, there were one or two places that used execution-time as a synonym for runtime but they do indeed seem to be gone now.  The users guide is looking very polished!

**Comment by sbrannen** [comment]
@smoyer64, thanks for the feedback and praise!
