### ISSUE TITLE
Idea to simplify asserting two doubles are "close enough".

### ISSUE THREAD

**Issue by nielsbasjes** [junit-team/junit5#3444]
Normally when you need to check if two doubles are close enough the `assertEquals(one, two, delta)` is the solution for that.
Key is that the developer needs to explicitly specify the allowed delta that matches the two provided values (which is fine for a large number of testcases).

In one of my projects I ran into a situation where I have a great many scenarios that need to be tested and the actual code to do the testing is reused over many scenarios where the values at hand were in completely different value ranges. So simply having a `fixed` delta would not work very well.

For that project I created this code fragment that does not compare the values but compares the log10 of the two provided values instead.

By doing this and selecting a value for the `CLOSE_ENOUGH_LOG10_DIFFERENCE` that was suitable for my usecase; I now have a testing compare that is much easier to use and makes the right assessment for all my (!!) usecases.

The oversimplified way you can look at this value is "how many digits must the two values be the same". In my usecase ~ 10 significant digits is good enough because the overall precision of a double is about 15 digits.

Key question: Do you think it is a good idea to include something like this as an additional `assertCloseEnough(double, double)` to Junit ?

```java
private static final double CLOSE_ENOUGH_LOG10_DIFFERENCE = 0.00000001d;

public static boolean closeEnough(double one, double two) {
    double oneLog10 = Math.log10(one);
    double twoLog10 = Math.log10(two);
    double diff = Math.abs(oneLog10 - twoLog10);
    return (diff < CLOSE_ENOUGH_LOG10_DIFFERENCE);
}
```

**Comment by marcphilipp** [comment]
**Team decision:** Thanks for the suggestion but we don't think it's a good idea to decide what's "close enough" for everyone.
