### ISSUE TITLE
ExtensionContext.Store.CloseableResource doesn't work with ThreadLocal in Concurrent Mode

### ISSUE THREAD

**Issue by uchagani** [junit-team/junit5#3446]
Version: 5.10.0

## Steps to reproduce

1.  Create an extension implementing `ExtensionContext.Store.CloseableResource` with a static `ThreadLocal` field
2. Create a test class with multiple test methods running in concurrent mode.

Expected Result:
`close()` is called in the same thread as the method so the proper ThreadLocal variable can be used.

Actual Result:
`close` is called from a different thread and the ThreadLocal variable is null.

## Context

Since ExtensionContext.Store.CloseableResource runs in a separate thread than the test, any static ThreadLocal variable remains null because it has not been initialized in this new thread.

**Comment by uchagani** [comment]
I think this can be mitigated if `close` accepted `ExtensionContext` as a parameter.

**Comment by mpkorstanje** [comment]
What is the purpose of the thread local? The resource can already be scoped to either the test or test class. What benefit do you derive from using a thread local?

**Comment by uchagani** [comment]
I need the resource scoped to the thread it was created on

**Comment by marcphilipp** [comment]
@uchagani Could you please post a more complete example?
