### ISSUE TITLE
ExtensionContext.getExecutionMode() in Before/AfterAllCallback returns incorrect value when running in same_thread mode

### ISSUE THREAD

**Issue by uchagani** [junit-team/junit5#3447]
version: 5.10.0

When you run tests via configuration parameter `junit.jupiter.execution.parallel.mode.default = same_thread`, the `ExtensionContext.getExecutionMode()` method inside of `BeforeAllCallback` and `AfterAllCallback` will return `CONCURRENT`.  However, if you add `@Execution(ExecutionMode.SAME_THREAD)` to the test class, they report `SAME_THREAD` as expected.

## Steps to reproduce

```
// junit-platform.properties

junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = same_thread
junit.jupiter.execution.parallel.mode.classes.default = concurrent
```

```java
//TestExtension.java

public class TestExtension implements BeforeAllCallback, AfterAllCallback, BeforeEachCallback, AfterEachCallback {
  @Override
  public void afterAll(ExtensionContext extensionContext) throws Exception {
    System.out.println("AfterAllCallback: " + extensionContext.getExecutionMode());
  }

  @Override
  public void afterEach(ExtensionContext extensionContext) throws Exception {
    System.out.println("AfterEachCallback " + extensionContext.getExecutionMode());
  }

  @Override
  public void beforeAll(ExtensionContext extensionContext) throws Exception {
    System.out.println("BeforeAllCallback " + extensionContext.getExecutionMode());
  }

  @Override
  public void beforeEach(ExtensionContext extensionContext) throws Exception {
    System.out.println("BeforeEachCallback " + extensionContext.getExecutionMode());
  }
}
```

```java
// ExtensionTest.java

@ExtendWith(TestExtension.class)
public class ExtensionTest {

  @Test
  void foo() {

  }

  @Test
  void foo1() {

  }
}
```

## Expected Result:

```
BeforeAllCallback SAME_THREAD
BeforeEachCallback SAME_THREAD
AfterEachCallback SAME_THREAD
BeforeEachCallback SAME_THREAD
AfterEachCallback SAME_THREAD
AfterAllCallback: SAME_THREAD
```

## Actual Result

```
BeforeAllCallback CONCURRENT
BeforeEachCallback SAME_THREAD
AfterEachCallback SAME_THREAD
BeforeEachCallback SAME_THREAD
AfterEachCallback SAME_THREAD
AfterAllCallback: CONCURRENT
```

## Context

If you add `@Execution(ExecutionMode.SAME_THREAD)` to the test class then the correct results are reported.  But adding this annotation should not be necessary because the default configuration is `same_thread`

**Comment by sbrannen** [comment]
Since you specify `junit.jupiter.execution.parallel.mode.classes.default = concurrent`, why would you expect class-level callbacks to report `SAME_THREAD`?

**Comment by marcphilipp** [comment]
You're correct: all methods of the test class and the callback extensions are run in the same thread. However, as configured, the test class itself may run concurrently with other test classes. That's what `getExecutionMode()` returns. If you print `Thread.currentThread()` in all places above, you will see the same thread is executing all of them.
