### ISSUE TITLE
Introduce `StringConversionSupport` in `junit-platform-commons`

### ISSUE THREAD

**Issue by Michael1993** [junit-team/junit5#3449]
[`DefaultArgumentConverter`](https://junit.org/junit5/docs/5.9.1/api/org.junit.jupiter.params/org/junit/jupiter/params/converter/DefaultArgumentConverter.html) used by JUnit is marked as internal. I'm not sure why that is but I think it'd be great if we got some support for argument conversion, so I'm proposing partially or entirely exposing or mirroring it in the `support` package (or somewhere else where it makes sense).

Or if the JUnit team doesn't want to support it, maybe Pioneer can host something?

## Deliverables

- [x] All or partial functionality of `DefaultArgumentConverter` exposed.

**Comment by marcphilipp** [comment]
Would it suffice to add `StringConversionSupport` class in `org.junit.platform.commons.support` with the following method `Object convert(String source, Class<?> targetType, ClassLoader classLoader)` (possibly supporting `Class<T>` and `T` as a return type)?

**Comment by Michael1993** [comment]
That sounds superb! I'm just not entirely sure why you need `ClassLoader` in there?

**Comment by sbrannen** [comment]
> I'm just not entirely sure why you need `ClassLoader` in there?

A custom `ClassLoader` is necessary to support use cases where classes are dynamically loaded.

A concrete example is converting from a fully-qualified class name (i.e., a `String`) to a `Class`.

We introduce `ClassLoader` arguments in numerous places in JUnit 5.10 to support custom `ClassLoader` arrangements. Consult the release notes for details.

----

By the way, we would likely accept `null` as the `ClassLoader` argument to imply that the default `ClassLoader` should be used.

**Comment by sbrannen** [comment]
Reopening to ensure `StringConversionSupport` is documented in the [Supported Utilities](https://junit.org/junit5/docs/current/user-guide/#extensions-supported-utilities) section of the User Guide.
