### ISSUE TITLE
Add a mechanism to display the `payload` of a `Named` argument instead of its `name`

### ISSUE THREAD

**Issue by onacit** [junit-team/junit5#3451]
```java
import org.junit.jupiter.api.Named;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

class JupiterNamedParametersTest {

    private static Stream<Arguments> arguments1() {
        return Stream.of(
                Arguments.of(0, 0)
        );
    }

    private static Stream<Arguments> arguments2() {
        return Stream.of(
                Arguments.of(Named.of("a", 1), Named.of("b", 1))
        );
    }

    private static Stream<Arguments> arguments3() {
        return arguments2().map(a -> {
            final Object[] got = a.get();
            return Arguments.of(
                    ((Named<?>) got[0]).getPayload(),
                    ((Named<?>) got[1]).getPayload()
            );
        });
    }

    @MethodSource({"arguments1", "arguments2", "arguments3"})
    @ParameterizedTest
    void test1(int a, int b) {
    }

    @MethodSource({"arguments1", "arguments2", "arguments3"})
    @ParameterizedTest(name = "[index] a: {0}, b: {1}")
    void test2(int a, int b) {
    }
}
```

<img width="268" alt="Screenshot 2023-09-06 at 14 11 51" src="https://github.com/junit-team/junit5/assets/247819/570bd195-9e1e-4570-a352-a0dde7ea3581">

## Deliverables

- [ ] Add a feature optionally unnames named arguments.

Say,

```java
    @MethodSource({"arguments1", "arguments2", "arguments3"})
    @ParameterizedTest(name = "[index] a: {unnamed({0})}, b: {unnamed({1})}")
    void test3(int a, int b) {
    }
```

**Comment by sbrannen** [comment]
Interesting idea.

Basically you're requesting to be able to use the `payload` of a `Named` argument instead of its `name`.

In light of that, I think `payload` would be a better name than `unnamed` for this function/macro.

In any case, I think this is rather an edge case that would not benefit many people.

**Comment by onacit** [comment]
@sbrannen Thank you for your comment, sir.

The original intention of the issue is not abount the case actually can happen but implies a developer's *confusion*.

Say, ss [Generating display names for @ParameterizedTest in JUnit 5](https://stackoverflow.com/questions/57892989/generating-display-names-for-parameterizedtest-in-junit-5).

A developer may read answers and may reach to the [JUnit 5 User Guide](https://stackoverflow.com/questions/57892989/generating-display-names-for-parameterizedtest-in-junit-5
).

And *an edge case* of following try may happen (again and again).

```java
    // this method may come from an alien class
    private static Stream<Arguments> arguments2() { // is this the way?
        return Stream.of(
                Arguments.of(Named.of("a", 1), Named.of("b", 1))
        );
    }

    @MethodSource({"arguments2"})
    @ParameterizedTest(name = "[index] a: {0}, b: {1}") // or is this the way?
    void test2(int a, int b) {
    }
```

And that's the case where the `payload` directive, named as you suggested, may be required.

```java
    @MethodSource({"arguments1", "arguments2", "arguments3"})
    @ParameterizedTest(name = "[index] a: {payload(0)}, b: {payload(1)}") // named of not, I want to display as I wan it to be
    void test2(int a, int b) {
    }
```

More precisely as intended,

```java
    @MethodSource({"arguments1", "arguments2", "arguments3"})
    @ParameterizedTest(name = "[index] a: {actual(0)}, b: {actual(1)}") // named of not, I want to display as I wan it to be
    void test2(int a, int b) {
    }
```

Thanks.

**Comment by marcphilipp** [comment]
**Team decision:** We don't think adding a feature for this would be widely useful and there exists a workaround. Therefore, we're closing the issue but would consider reopening it should there be considerable interest from the community.

**Comment by gusega** [comment]
this is an interesting idea,

I provide a description for each test case like this, 
```java
static Stream<Arguments> stringProvider() {
    return Stream.of(
            Arguments.of(named("when something happens, then expect fail",
                            "argument1"), "argument2", "argument3"));
}

@ParameterizedTest(name = "{index}: {0}: {argumentsWithNames}")
@MethodSource("stringProvider")
public void myTest(String param1, String param2, String param3) {

}
```
I expect the display name:
`1 - when something happens, then expect fail: argument1, argument2, argument3`

I get display name:
`1 - when something happens, then expect fail: when something happens, then expect fail, argument2, argument3`

could you please update `{argumentsWithNames}` so it returns payload of named argument?

Maybe a better feature, provide a display name per all arguments:
```java
static Stream<Arguments> stringProvider() {
    return Stream.of(
           named("when something happens, then expect fail", Arguments.of(
                            "argument1", "argument2", "argument3"));
}

@ParameterizedTest(name = "{displayName}: {argumentsWithNames}")
@MethodSource("stringProvider")
public void myTest(String param1, String param2, String param3) {

}
```
