### ISSUE TITLE
CloseablePath has thread-safety issue.

### ISSUE THREAD

**Issue by motlin** [junit-team/junit5#3452]
I ran into the same issue described in #2952 in my project. I looked at the fix in #2956 for ideas and tried to apply a similar fix. I found a problem around the reference counting and wound up taking a different approach. I'm not actually using JUnit 5 and haven't encountered an exception with JUnit 5, but I'm reporting this in case you believe it's a problem worth fixing. 

CloseablePath holds a static ConcurrentMap called `MANAGED_FILE_SYSTEMS`. The reference counting is implemented using `MANAGED_FILE_SYSTEMS.compute(...)`.

```java
	private static CloseablePath createForJarFileSystem(URI jarUri, Function<FileSystem, Path> pathProvider) {
		ManagedFileSystem managedFileSystem = MANAGED_FILE_SYSTEMS.compute(jarUri,
			(__, oldValue) -> oldValue == null ? new ManagedFileSystem(jarUri) : oldValue.retain());
		Path path = pathProvider.apply(managedFileSystem.fileSystem);
		return new CloseablePath(path,
			() -> MANAGED_FILE_SYSTEMS.compute(jarUri, (__, ___) -> managedFileSystem.release()));
	}
```

The compute() method expects the lambda passed in to be idempotent. From [the javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ConcurrentMap.html#compute(K,java.util.function.BiFunction)):

> When multiple threads attempt updates, map operations and the remapping function may be called multiple times.

It looks possible for two threads to call `createForJarFileSystem()`, both invoke `new ManagedFileSystem(jarUri)`, both invoke `FileSystems.newFileSystem(jarUri, emptyMap());` and one gets an exception.

Besides that, it's difficult for me to reason through the implications. I'm not sure if there's a reference counting issue or a resource leak.

I went with a [different approach in my project](https://github.com/motlin/liftwizard/pull/1532/files#diff-8a1a42a52fb79940fa257130bd2f3f9151b255cd5ec35d8c9167caf759cfae62) which has different pros and cons. I consistently avoid `FileSystemAlreadyExistsException` with this approach, but it requires callers to *not* close the returned `FileSystem`s.

**Comment by marcphilipp** [comment]
Thanks for raising this potential issue! I added another test in 4d8e306535f80e30a06e3862a5c2fef2f95deb54 that demonstrates that there's no thread-safety issue here. The implementation is thread-safe, because `ConcurrentHashMap.compute` offers stricter guarantees ([Javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html#compute(K,java.util.function.BiFunction))):

> The supplied function is invoked exactly once per invocation of this method
