### ISSUE TITLE
Document that `@Disabled` and conditional annotations are not inherited

### ISSUE THREAD

**Issue by DevDengChao** [junit-team/junit5#3462]
## Steps to reproduce

1. Define a AbstractDisabledTest:
```java
import org.junit.jupiter.api.Disabled;

@Disabled
public abstract class AbstractDisabledTest {
}
```
2. Define a MainTest:
```java
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.fail;

public class MainTest extends AbstractDisabledTest {

    @Test
    void thisShouldBeDisabled() {
        fail();
    }
}
```
3. Run `gradlew :test`
4. It fails

`@Disabled` didn't mentioned it cannot be used on parent class, so I opened this issue.

**Comment by sbrannen** [comment]
That's the expected behavior.

`@Disabled` is not annotated with `@Inherited` and therefore only applies to the current class.

The Javadoc for `@Disabled` actually states that:

> `@Disabled` is used to signal that the annotated test class or test method is currently disabled and should not be executed.

I suppose we could add a sentence to point out that it is not `@Inherited`, but then we'd probably want to add similar notes to **every** conditional execution annotation -- such as `@EnabledOnJre`, `@DisabledOnOs`, etc.

**Comment by sbrannen** [comment]
We'll improve the documentation for 5.10.1.

**Comment by sbrannen** [comment]
> is there any way/workaround if I do want it works inherite-able ?

No, there is no workaround to make `@Disabled` inherited. The JUnit 5 annotation search algorithms simply do not support that.

However, you should be able to implement a programmatic solution by registering a custom `ExecutionCondition` that always returns `disabled()`.

I'll see if I can spike a solution for you.

**Comment by sbrannen** [comment]
Voilà.....

Here's the solution:

```java
import org.junit.jupiter.api.extension.ConditionEvaluationResult;
import org.junit.jupiter.api.extension.ExecutionCondition;
import org.junit.jupiter.api.extension.RegisterExtension;

public abstract class AbstractDisabledTest {

	@RegisterExtension
	static ExecutionCondition disabledCondition = context ->
		ConditionEvaluationResult.disabled("Programmatically @Disabled");

}
```

**Comment by DevDengChao** [comment]
@sbrannen Thanks, it works.

**Comment by sbrannen** [comment]
> `@Disabled` didn't mentioned it cannot be used on parent class, so I opened this issue.

After further investigation, I noticed that this is actually already documented in the [User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-annotations).

> Used to [disable](https://junit.org/junit5/docs/current/user-guide/#writing-tests-disabling) a test class or test method; analogous to JUnit 4’s `@Ignore`. Such annotations are not _inherited_.

In any case, I am adding a note to the Javadoc of each _conditional_ annotation and a note in the `Conditional Test Execution` section of the User Guide as well.

**Comment by DevDengChao** [comment]
@sbrannen Maybe we should let others known there is a workaround ... instead of the term `must be redeclared on the subclass.` 😂

**Comment by sbrannen** [comment]
> @sbrannen Maybe we should let others known there is a workaround ... instead of the term `must be redeclared on the subclass.` 😂

I suppose we could mention a workaround for `@Disabled`, but that would not apply to any of the other conditional annotations since their extension implementations are sometimes rather complex and are not `public`.

The only reason is _works_ for `@Disabled` is that there is zero logic in the "workaround".

**Comment by sbrannen** [comment]
Reopening for team discussion about inclusion of the workaround for `@Disabled`.

**Comment by marcphilipp** [comment]
Another workaround:
```java
import org.junit.jupiter.api.Disabled;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@InheritedDisabled
public abstract class AbstractDisabledTest {
}

@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@Disabled
@interface InheritedDisabled {
}
```

**Comment by marcphilipp** [comment]
**Team decision:** Wait for additional community interest on a way to "inherit" conditional annotations.

**Comment by scordio** [comment]
> **Team decision:** Wait for additional community interest on a way to "inherit" conditional annotations.

Hi @marcphilipp and team, today I faced a use case where inheritance for `@EnabledIfSystemProperty` would have helped for less boilerplate.

Specifically, it's a project with many test classes for integration tests that should be executed only on the CI infrastructure and on specific runners. Such fine-grained control is currently achieved combining the `maven-failsafe-plugin` to exclude the local environment and `@EnabledIfSystemProperty(named = "it.test", matches = ".+")` on each test class to ensure that they are executed only under the appropriate CI jobs (the `it.test` property is set to different values by each job to tune the failsafe plugin execution further). The test classes already share common parts in a parent class, so pulling `@EnabledIfSystemProperty` one level up would help reduce the boilerplate.

Please let me know if I should open a new issue, as this one has been closed for over a year.

**Comment by sbrannen** [comment]
@scordio, yes, please open a new issue, since this one was closed in conjunction with an update to the documentation.
