### ISSUE TITLE
`DefaultArgumentConverter` no longer converts `"null"` to `false`

### ISSUE THREAD

**Issue by JKomoroski** [junit-team/junit5#3472]
Error message: `Failed to convert String "null" to type java.lang.Boolean`

Working Version: `5.9.2`
Broken Version: `5.10.0`

## Steps to reproduce

Use the `DefaultArgumentConverter` to convert a string to a Boolean. Strings `"true"` and `"false"` convert correctly, but the string `"null"` no longer converts to a `null` `Boolean` (wrapper type) after upgrading.

Since this converter is used for `@CsvSource` data in `@ParameterizedTest` methods , it is quite common to include nulls in those sources for many types, not just `Boolean.class`.

A naive fix and test for this issue is included in my fork of junit5. I suspect a more robust fix for nullable types more broadly should be considered.

https://github.com/junit-team/junit5/compare/main...JKomoroski:junit5:main

## Deliverables

- [ ] Fix behavior of nullable wrapper types to support `"null"` -> `null` conversions once again.

**Comment by sbrannen** [comment]
This is now the expected behavior due to #3177.

However, we may consider a way to switch back to _lenient_ parsing of boolean values or make the true/false values somehow configurable.

**Comment by JKomoroski** [comment]
@sbrannen I'm not sure this title change accurately reflects the behavior change.

In the past `"null"`  was being converted to `null` for nullable primate wrapper types (`Boolean.class`  in this case). The new issue title indicates that the issue was expecting `"null"` -> `false` for a `boolean` primitive which is not the issue I'm having.

**Comment by sbrannen** [comment]
> In the past `"null"` was being converted to `null` for nullable primate wrapper types (`Boolean.class` in this case). 

My initial tests do not reveal that, but perhaps I am missing something.

Previously, we used `Boolean::valueOf` to convert a `String` to a `Boolean`, and that method returns `false` for `"null"`. It also returns `false` for `null`.

> The new issue title indicates that the issue was expecting `"null"` -> `false` for a `boolean` primitive which is not the issue I'm having.

If I'm not mistaken, we previously converted `"null"` to `Boolean.FALSE` or `false` for `Boolean` and `boolean` target types, respectively.

Based on that, I believe we can consider this a _regression_.

In any case, I'll introduce more extensive testing around this.

**Comment by sbrannen** [comment]
> but the string `"null"` no longer converts to a `null` `Boolean` (wrapper type) after upgrading.

Were you perhaps using the `nullValues = "null"` feature of `@CsvSource` as in the following example?

```java
@ParameterizedTest
@CsvSource(nullValues = "null", value = ...)
void myTest(...) {
}
```

If not, I don't see how `"null"` would have been converted to a `Boolean` `null`.

**Comment by sbrannen** [comment]
In summary, the following test passes against `5.9.x`.

```java
	@ParameterizedTest
	@CsvSource(nullValues = "null", textBlock = """
			apple,   True
			banana,  true
			lemon,   false
			kumquat, null
			""")
	void yummyFruit(String fruit, Boolean yummy) {
		switch (fruit) {
			case "apple" -> assertThat(yummy).isTrue();
			case "banana" -> assertThat(yummy).isTrue();
			case "lemon" -> assertThat(yummy).isFalse();
			case "kumquat" -> assertThat(yummy).isNull();
			default -> fail("Unexpected fruit : " + fruit);
		}
	}
```

Whereas, the following test fails against `5.9.x`, since `nullValues = "null"` has been removed and `yummy` for kumquat is now `false`.

```java
	@ParameterizedTest
	@CsvSource(textBlock = """
			apple,   True
			banana,  true
			lemon,   false
			kumquat, null
			""")
	void yummyFruit(String fruit, Boolean yummy) {
		switch (fruit) {
			case "apple" -> assertThat(yummy).isTrue();
			case "banana" -> assertThat(yummy).isTrue();
			case "lemon" -> assertThat(yummy).isFalse();
			case "kumquat" -> assertThat(yummy).isNull();
			default -> fail("Unexpected fruit : " + fruit);
		}
	}
```

**Comment by sbrannen** [comment]
To observe the actual behavioral changes, consult the following commits.

- Status quo for `5.9.x`: https://github.com/junit-team/junit5/commit/738b13cd8ba67d3498311164ced070e3a146074d
  - ported to `5.10.x` and `main` unchanged: 849ce5ed327548a62ffd3cf813c19d28be1d3d0d
- Status quo for `5.10.x` and `main`: ab160b09d44efbb72ce28d50c15442dbfdf3dddd

The latter commit makes it clear that the only thing that has changed is that we now only convert `"false"` (ignoring case) to a boolean `false`.

**Comment by JKomoroski** [comment]
This is very helpful. Thank you. I'll update my csv source tests with this in mind. I'll further investigate my other failing tests to see what else could be the problem.

**Comment by sbrannen** [comment]
> This is very helpful. Thank you.

You're welcome.

> I'll update my csv source tests with this in mind. I'll further investigate my other failing tests to see what else could be the problem.

OK. Let us know if you run into any other issues.

**Comment by JKomoroski** [comment]
All of my failures were related to `@CsvSource` changes. The other failures from the upgrade to 5.10 in my work do not have an underlying problem with Junit5.  This issue can be closed.
