### ISSUE TITLE
Tests failure on abstract class only shows the abstract class name

### ISSUE THREAD

**Issue by tisonkun** [junit-team/junit5#3475]
I inherit test class to share common test cases:

```java
public class RedisTest extends BehaviorTest {
    public RedisTest() {
        super("redis");
    }
}
```

But on failure, the test failure report only shows `org.apache.opendal.behavior.BehaviorTest$AsyncWriteTest`, but nothing related to `RedisTest`:

```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.535 s <<< FAILURE! - in org.apache.opendal.behavior.BehaviorTest$AsyncWriteTest
[ERROR] org.apache.opendal.behavior.BehaviorTest$AsyncWriteTest.testReadFull  Time elapsed: 0.491 s  <<< FAILURE!
java.lang.AssertionError: 
```

This can make debugging quite difficult to locate what exact case is related.

**Comment by sbrannen** [comment]
Hi @tisonkun,

I'm afraid that is not enough information to go on.

Are you using JUnit Jupiter? JUnit 4? ...?

Can you please provide a complete example that we can run and evaluate?

Is the issue only with the output in Maven? Or does your IDE also cause issues for you?

**Comment by tisonkun** [comment]
* JUnit Jupiter.
* Only on Maven.

I'm encountering this while writing some code for a OSS project, I can share with you the branch URI a few later.

**Comment by tisonkun** [comment]
This is the related code - https://github.com/apache/incubator-opendal/pull/3161.

You can clone the code and:

```
cd bindings/java
./mvnw test
```

Try to make some failure assertion in BehaviorTest and observe.

**Comment by marcphilipp** [comment]
@tisonkun Thanks for the reproducer! This looks like an issue in the Maven Surefire/Failsafe plugin. It seems to print the information based only on the `MethodSource` of the test rather than taking into account the sources or display names of parent `TestIdentifiers`. Please raise an issue with them!

**Comment by tisonkun** [comment]
@marcphilipp Thank you! Can you share the related code lines so that I can file a ticket there with helpful info?

**Comment by marcphilipp** [comment]
@tisonkun I'm not familiar enough with the Surefire codebase to point to specific lines.
