### ISSUE TITLE
Add feature about blocks or labels for test reports how Spock Framework offers

### ISSUE THREAD

**Issue by manueljordan** [junit-team/junit5#348]
Hello Developers

I use `Spock Framework` which is based on `Groovy`, there is a special feature very useful. It contains some special blocks or labels such as `given`, `where` etc where appears in some special kind of reports. It is very useful by itself

Such feature would be added in JUnit 5?

Thanks

**Comment by marcphilipp** [comment]
If Spock implemented a custom TestEngine it could easily add those to the test tree. We currently do not plan to add such a feature to the Jupiter API.

**Comment by manueljordan** [comment]
Thanks by the reply, I hope it would be added later... I know exists other priorities
