### ISSUE TITLE
Broken image link - User guide - Dependency Diagram

### ISSUE THREAD

**Issue by sh3hz** [junit-team/junit5#3486]
Image link is broken in below location: 

https://junit.org/junit5/docs/current/user-guide/#dependency-diagram

**Comment by sbrannen** [comment]
Hi @sh3hz,

Congratulations on raising your first issue for JUnit 5! 👍 

Please note, however, that this is a duplicate of #3430.

In light of that, I'm closing this issue.

In the future, please make sure you search for existing issues before creating a new issue.

Thanks
