### ISSUE TITLE
Update CONTRIBUTING.MD

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#35]
- [ ] I hereby agree…
- [X] Section about coding standards, usage of spotless
- [x] Section about Javadoc:
  - No author tag
  - etc.

**Comment by marcphilipp** [comment]
@sbrannen Do you still have this on your radar or shall I take over?

**Comment by sbrannen** [comment]
I'll see if I can do some work on that tomorrow, but if you're eager to start on it now, feel free.
