### ISSUE TITLE
`@ParameterizedTest` fails but is reported as successful

### ISSUE THREAD

**Issue by KyleAure** [junit-team/junit5#3501]
## Steps to reproduce

I have a test client abstract class that has a ParameterizedTest:
```java
public abstract class TestClient {
	public abstract URL getBaseURL();

    @ParameterizedTest
    @ArgumentsSource(TestClientArgumentsProvider.class)
    public void runServletTests(String path, String testMethod) {        
        URL requestURL = URLBuilder.fromURL(getBaseURL())
                .withPath(path)
                .withQuery(TestServlet.TEST_METHOD_PARAM, testMethod)
                .build();
        
        System.out.println("CHECK - built URL");
        try {
            runTest(requestURL); //Gets connection to service, and verifies response  
        } catch (Throwable t) {
            System.out.println("CHECK - caught throwable: " + t.getLocalizedMessage());
            fail("Exception: " + t.getLocalizedMessage());
        } finally {
            System.out.println("CHECK - ran TEST");    
        }
    }
}
```

The implementation provides a baseURL:
```java
public class ComplexServletTests extends TestClient {
    @Override
    public URL getBaseURL() {
        return baseURL;
    }
}
```

The argument provider returns the arguments: 
```java
public class TestClientArgumentsProvider implements ArgumentsProvider {
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext context) throws Exception {
       /**
         * Only execute test methods on servlet that are public, non-static, and annotated with @Assertion
         */
        return Arrays.asList(testServlet.getMethods()).stream()
            .filter(method -> Modifier.isPublic(method.getModifiers()) && !Modifier.isStatic(method.getModifiers()))
            .filter(method -> method.isAnnotationPresent(Assertion.class))
            .map(method -> Arguments.of(servletPath, method.getName()));
	}
}
```

Using logging I can see the test starting, catching the error, and exiting through the finally block: 
```txt
16:28:02,852 [INFO] Running web.example.ComplexServletTests
CHECK - built URL
CHECK - caught throwable: Output did not contain successful message: SUCCESS ==> expected: <true> but was: <false>
CHECK - ran TEST
```
Therefore, this test should have failed given the `fail("...")` statement, however we see both of the iterations of the test failed: 
![Screenshot 2023-10-10 at 16 30 23](https://github.com/junit-team/junit5/assets/33664635/de18a5e3-c93b-4519-b980-c04e1e641115)

I am unsure how to debug this further as I have no idea why it would be reported as passed when there is a clear `fail("")` statement.

## Context

 - Used versions (Jupiter/Vintage/Platform):
 ```xml
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter</artifactId>
	<version>5.10.0</version>
</dependency>
```
 - Build Tool/IDE:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>3.1.2</version>
</plugin>
```
## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
> I am unsure how to debug this further as I have no idea why it would be reported as passed when there is a clear `fail("")` statement.

What is reporting the success? A report generator from Maven Surefire? Your own custom report generator?

In any case, it appears to be an issue with the report instead of with JUnit.

If you would like us to confirm that or assist you further, please provide a minimal example project that demonstrates the behavior you are claiming (preferably something that we can download and run ourselves -- a ZIP file or online Git repository).

Thanks

**Comment by KyleAure** [comment]
I made an example project and it worked.  I think the problem is actually Arquillian which is intercepting the lifecycle of tests.  I'm going to open an issue over there to see if they can investigate this.
