### ISSUE TITLE
Introduce assertions for `java.util.Optional`

### ISSUE THREAD

**Issue by delanym** [junit-team/junit5#3506]
I would be neat to have assertions specifically for working with java.util.Optional

- assertIsEmpty
- assertIsPresent

This would help unpack the cause of a test failure faster. So for instance instead of
```java
assertTrue(validate("gateway name", "BLAH").isEmpty(), "Failed string test");
```

I'd write
```java
assertIsEmpty(validate("gateway name", "BLAH"), "Failed string test");
```

And a fail could use the Optional in the output, so instead of
```
Failed max length string test ==> expected: <false> but was: <true>
```
it could be
```
Failed max length string test ==> expected: <Optional>::<empty> but was: <Optional>::<"Property must have a specific length of 5">
```

**Comment by sbrannen** [comment]
Hi @delanym,

Please search the issue tracker before opening new issues.

Thanks!

----

Closing as a...

- duplicate of #1920
