### ISSUE TITLE
Standalone Console not reporting @SuiteDisplayName in XML file

### ISSUE THREAD

**Issue by EnlitHamster** [junit-team/junit5#3509]
I am currently running JUnit Platform Console Standalone version 1.10.0. I have JUnit 5 System Exit plugin 1.1.2 installed too. I run JUnit 5 with the following command: `java -jar "junit5.jar" execute -cp "junit5.jar:system-exit.jar:." --reports-dir reports --select-class TestSuite`. The output of `java -version` is reported below.

```
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Debian-1deb11u1, mixed mode, sharing)
```

The command line output reports the `@SuiteDisplayName` of my test suite. However, the display name is not reported in any of the XML files in the `reports` directory. I checked both the `<testsuite>` name property and the CDATA in the files. The command line output is reported below.

```
╷
├─ JUnit Jupiter ✔
├─ JUnit Vintage ✔
└─ JUnit Platform Suite ✔
   └─ This is a suite ✔
      └─ JUnit Jupiter ✔
         ├─ Test the isValid() and makeInvalid() functionality. ✔
         │  ├─ Is a Passport invalid after running makeInvalid() method? ✔
         │  └─ Is a Passport valid by default? ✔
         └─ Test whether Passports can be instantiated correctly. ✔
            ├─ Can a Passport be instantiated for James Gosling, age 67 from Canada? ✘ Test
            └─ Can a Passport be instantiated for CodeGrade, age 5 from The Netherlands? ✘ Test
```

## Steps to reproduce

The full reproduction is available in [this repo](https://github.com/EnlitHamster/junit5-suite-display-name-bug). Just run `./run.sh`. It will run JUnit 5 on the test suite and generate the reports in `reports`.

## Context

 - Used versions (Jupiter/Vintage/Platform): https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.0/junit-platform-console-standalone-1.10.0.jar
 - Build Tool/IDE: Bash console
 - Java version: 11.0.20

## Deliverables

- [ ] ...

**Comment by sormuras** [comment]
This is a known limition of the legacy XML reporting format.

Using the Open Testing reporting format by adding following run-time configuration arguments:

`--config=junit.platform.reporting.open.xml.enabled=true --config=junit.platform.reporting.output.dir=open-testing-reports`

shows lines like

```xml
...
<e:started id="4" name="This is a suite" parentId="3" time="2023-10-18T14:40:30.181236Z"><metadata><junit:uniqueId>[engine:junit-platform-suite]/[suite:TestSuite]</junit:uniqueId><junit:legacyReportingName>This is a suite</junit:legacyReportingName><junit:type>CONTAINER</junit:type></metadata><sources><java:classSource className="TestSuite"></java:classSource></sources></e:started>
...
<e:finished id="4" time="2023-10-18T14:40:30.279885Z"><result status="SUCCESSFUL"></result></e:finished>
...
```

Find more details at https://junit.org/junit5/docs/current/user-guide/#junit-platform-reporting
