### ISSUE TITLE
TravisCI can't execute even assemble when org.junit.platform.gradle.plugin is attached

### ISSUE THREAD

**Issue by sta-szek** [junit-team/junit5#351]
Result:
![image](https://cloud.githubusercontent.com/assets/6240704/16313771/0c881532-397b-11e6-906f-0b8031f74a40.png)

build.gradle:

```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath "info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.1.9"
        classpath "org.junit.platform:junit-platform-gradle-plugin:1.0.0-SNAPSHOT"
    }
}
.
.
.
ext.junit4Version = "4.12"
ext.junitVintageVersion = "4.12.0-SNAPSHOT"
ext.junitPlatformVersion = "1.0.0-SNAPSHOT"
ext.junitJupiterVersion = "5.0.0-SNAPSHOT"
ext.log4JVersion = "2.5"
.
.
.
apply plugin: "org.junit.platform.gradle.plugin"
.
.
.
repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
junitPlatform {
    enableStandardTestTask true
    engines {
        include "junit-jupiter"
    }

    includeClassNamePattern ".*Test"
}
```

**Comment by marcphilipp** [comment]
Does this only happen on Travis? Is this a private job or can we take a look?

**Comment by sbrannen** [comment]
Sounds like an incompatible Gradle version. 

What version of Gradle are you using?

**Comment by sbrannen** [comment]
@sta-szek, Ping!

Any update?

**Comment by sbrannen** [comment]
The JUnit Platform Gradle plugin requires Gradle 2.5 or higher.

I am therefore closing this issue; however, if you encounter the same problem with Gradle 2.5 or higher, please let us know.

**Comment by sbrannen** [comment]
FYI: beginning with the next snapshot build, the JUnit Gradle Plugin will now throw a `GradleException` with the message `"junit-platform-gradle-plugin requires Gradle version 2.5 or higher"`. 

To see the actual error message you may need to run `gradle` with `--stacktrace`.

**Comment by sta-szek** [comment]
Sorry for my absence. You were right. Travis is using gradle 2.2.1 by default.
I used script:
```
before_install:
  # Download desired version of Gradle
  - wget http://services.gradle.org/distributions/gradle-2.14-bin.zip
  - unzip -qq gradle-2.14-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14
  - export PATH=$GRADLE_HOME/bin:$PATH
  # just to test gradle version, against our provided one
  - gradle -v
```
and it's working now.

But have same issue as here #350

**Comment by sbrannen** [comment]
Great to hear that upgrading Gradle on Travis at least allows the plugin to be properly applied! 

Thanks for letting us know. 👍 

Regarding #350, that seems to be completely unrelated to this issue.

**Comment by sbrannen** [comment]
By the way, instead of using `wget` you could alternatively use the Gradle `Wrapper` like we do in our own builds. Then when you execute `gradlew check` on the Travis CI server, you can be assured that the correct version of Gradle is being used to run your build.

**Comment by sta-szek** [comment]
Thanks for your advice, I'll try `gradlew` ASAP.
