### ISSUE TITLE
Introduce `ConsoleLauncher` option to fail if no tests are run

### ISSUE THREAD

**Issue by delanym** [junit-team/junit5#3515]
As discussed https://github.com/sormuras/junit-platform-maven-plugin/issues/111

The `ConsoleLauncher` has an option to `--fail-if-no-tests`. But if there ARE tests and they're just `@Disabled` then I would expect this option to have no effect.

For cases where one wants a failure when no tests are run, I propose to include another switch `--fail-if-no-tests-run`

**Comment by marcphilipp** [comment]
@delanym This already seems to work in the way you want for `@Disabled` test classes with at least one `@Test` method. Could you please post an example test class where it doesn't?

**Comment by delanym** [comment]
My mistake. I probably got confused with parallel build output
