### ISSUE TITLE
Make reflection, annotation, and scanning utilities available to TestEngine authors

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#352]
Most 3rd party engines will have to handle reflection and annotations and do classpath scanning. If you want engines to be consisten in how they do it and how they handle corner cases, make the important stuff of junit-platform-commons, where everything is API(Internal), available, e.g. in `org.junit.platform.engine.support`

**Comment by raniejade** [comment]
I found myself depending on those internal APIs as well. I'm just being lazy and don't want to reinvent the wheel. :)

**Comment by sbrannen** [comment]
This is closely related to #246.

These issues should therefore be addressed together in order to come up with a consistent, maintainable means to provide such support to third-party developers.

**Comment by sormuras** [comment]
PR #651 adds an interface named `Util` to `ExtensionContext` supplying **extension** authors access to utility methods. That can easily be widend to a general first-class citizen utility API that can be used by both, extension and engine authors.

**Comment by sormuras** [comment]
Two possible solutions:
1. Mark parts of `org.junit.platform.commons.util.*Utils` with`@API(Maintained)` and compile an overview of stable and maintained assets: https://github.com/junit-team/junit5/issues/144
2. Implement an indirection layer exposing maintained parts of utilities, like https://github.com/junit-team/junit5/compare/issue-246-352-utilities

**Comment by sormuras** [comment]
Skimming http://openjdk.java.net/projects/jigsaw/spec/sotms/ - especially:
> _Strong encapsulation_, to allow a component to declare which of its **public types** are accessible to other components, and which are not.
makes me wonder, if i could solve this issue ... in the future.

**Comment by nicolaiparlog** [comment]
> makes me wonder, if it could solve this issue ... in the future.

This does not really change anything. It just means that you have to pick the packages whose public types are to be accessible but it still requires you to put the feature into a specific class in a specific package.

One thing Jigsaw can do, though, is make `@API(Maintained)` superfluous as, ideally, exactly those types should be accessible to code outside of the Jigsaw modules.

**Comment by jlink** [comment]
As far as I know Jigsaw can only provide/deny visibility. The `API` annotation is more explicit about the level of support.

**Comment by jbduncan** [comment]
> Two possible solutions:
>
> 1. Mark parts of org.junit.platform.commons.util.*Utils with@API(Maintained) and compile an overview of stable and maintained assets: #144
> 2. Implement a maintained indirection layer exposing internal parts of utilities, like https://github.com/junit-team/junit5/compare/issue-246-352-utilities

3. Expose internal parts of the utilities, similarly to (2), but as a new, separate utilit(y|ies) class, to

- allow those methods to be made visible separately from the internal utils if/when Jigsaw is adopted (which is a big problem with option (1)), and
- not tie those utilities to particular classes, as currently done in option (2).

**Comment by sormuras** [comment]
### junit-platform-commons

The `package-info.java` of `package org.junit.platform.commons;` states:
```
/**
 * Internal common library of JUnit.
 *
 * <h3>DISCLAIMER</h3>
 *
 * <p>These utilities are intended solely for usage within the JUnit framework
 * itself. <strong>Any usage by external parties is not supported.</strong>
 * Use at your own risk!
 */
```

### Usages of `@API(...)` in junit-platform-commons

![usagesofapiannoinplatformcommons](https://cloud.githubusercontent.com/assets/2319838/23058348/d4e5ef60-f4f4-11e6-929d-bae03dc218a8.PNG)

Two are already not `Internal`: the `API` annotation itself and the `Testable` annotation already used by 3rd parties, like IJ (and Eclipse?)

Sooo, without further ado I tend to solution 1 -- supported by quoting @jlink 
> Alternatively: Just start marking parts of org.junit.platform.commons with the appropriate @API annotations. It's just a matter of what the team wants to commit to. No indirection through additional classes will get rid of the fundamental problem.
- What is declared `public`, stays `public` and will be used by s/o anyway. A textual tag won't prevent that.
- We use the utilities as they are. A lot of internal code depends on the status-quo: it is our own interest not to break things.
- Keep things simple and maybe, we can even sell those features to standard JUnit 5 users: _"You need reflection support in your test code? Try org.junit.platform.commons.util.ReflectionUtils!"_ Or at least encourage extension and engine authors to do so.

**Comment by nicolaiparlog** [comment]
@jlink 

> As far as I know Jigsaw can only provide/deny visibility. The API annotation is more explicit about the level of support.

True. My point was that if something was not `Stable` it should not be accessible. Looking over [the API annotation](http://junit.org/junit5/docs/current/user-guide/#api-evolution-annotations), that doesn't make sense, though, because most other values also allows uses of the class.

But the other way around might work, making exactly `@API(Internal)` classes inaccessible (public in non-exported packages or non-public in exported packages). Anyways, this is not the best thread for that so I'll shut up about it now. :wink:

**Comment by sbrannen** [comment]
> 1. Mark parts of `org.junit.platform.commons.util.*Utils` with`@API(Maintained)` and compile an overview of stable and maintained assets: https://github.com/junit-team/junit5/issues/144

I vote for this course of action.

**Comment by jlink** [comment]
Does Jigsaw visibility have finer granularity like allowing / denying
access to a single method?

2017-02-17 11:00 GMT+01:00 Nicolai Parlog <notifications@github.com>:

**Comment by nicolaiparlog** [comment]
> Does Jigsaw visibility have finer granularity like allowing / denying access to a single method?

No. Incidentally I'm not convinced that slicing an API so thinly is a good idea anyway. In light of that I came to the opinion that 1. is a bad choice. 2. has limitations as well, so I vote for @jbduncan's 3.:

> 3. Expose internal parts of the utilities, similarly to (2), but as a new, separate utilit(y|ies) class

A "utility gateway" plays well with Jigsaw and does not parade internal methods by users while they are not supposed to call them.

**Comment by sormuras** [comment]
> Does Jigsaw visibility have finer granularity like allowing / denying access to a single method?

No, as far as I understand: http://openjdk.java.net/projects/jigsaw/spec/sotms/#accessibility

**Comment by nicolaiparlog** [comment]
I understand 3. in such a way that internally, JUnit continues to use the Utils as is - nothing changes here. Additionally, everything that external users are allowed to call (effectively everything besides `@API(Internal)`) would be found in that gateway, by which I mean copy-pasting the signature and `@API` annotation and forwarding the method call. The gateway gets exported, the internal utilities don't. Changing public API is as simple as creating/deleting forwarding calls.

**Comment by sormuras** [comment]
> 1. is a bad choice. 2. has limitations as well, so I vote for @jbduncan's 3

*(1.)* is only a bad solution (now and in Jigsaw-times), if you want to hide some internals. If you want the opposite, you want to publish and encourage the use of an API, then 1. is good now and in the future.

> I understand 3. in such a way that internally, JUnit continues to use the Utils as is - nothing changes here. 

*(2. and 3.)* only makes sense, if all access modifiers are tuned down to _JUnit 5-private level_ ... which leads to either bridging the tools other packages internally. How do you use `package-private AnnotationsUtil` in `jupiter-engine`?

**Comment by jlink** [comment]
Might work in this case since Util methods are by nature just static
functions. Does not as easily work in a  general way since experimental API
methods might refer to an instance already visible in through the API.

2017-02-17 11:27 GMT+01:00 Nicolai Parlog <notifications@github.com>:

**Comment by sormuras** [comment]
Giving 2 (and 3) another thought, after scanning [Package javax.lang.model.util](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/util/package-summary.html) with focus on [Elements](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/util/Elements.html) and [Types](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/util/Types.html). Here, the implementation is completely hidden and you can even provide your own.

**Comment by nicolaiparlog** [comment]
@sormuras 

> (1.) is only a bad solution (now and in Jigsaw-times), if you want to hide some internals.

I am sure this will always be true of utilities for a big project like JUnit - hence the invention of `@API(Internal)`. Everything that will be easily available _will_ be used by someone, `@API(Internal)` notwithstanding. Exposing users to such seductive utilities without any intentions to actually maintain them or heeding the user's opinions when taking them away is just mean. 😈 

>  If you want the opposite, you want to publish and encourage the use of an API, then

... you make it public, not put it into a corner marking it as internal. (At least that's how my father did it and his before him. :wink: )

> (2. and 3.) only makes sense, if all access modifiers are tuned down to _JUnit 5-private level_

Exactly, mark the entire internal utility class with `@API(Internal)` and once Jigsaw rolls around use [qualified exports](http://openjdk.java.net/projects/jigsaw/spec/sotms/#qualified-exports) to make them _JUnit 5-private_ while happily exporting the public gateway. 

@jlink 

> Might work in this case since Util methods are by nature just static functions.

Yes, my proposal only addressed this scenario.

> Does not as easily work in a general way since experimental API methods might refer to an instance already visible in through the API.

True. I still find it weird to make the internal-or-external-API cut through the middle of a class but there are surely situations where this is the best option. If so, take it. Here, I think we can find a better one.

**Comment by sormuras** [comment]
> ... you make it public, not put it into a corner marking it as internal.

That's the point of solution 1. -- *Utils *are* public, just about to change the API marker from _Internal_ to ... bold move, *Stable*.

**Comment by nicolaiparlog** [comment]
> *Utils _are_ public, just about to change the API marker from _Internal_ to ... bold move, _Stable_.

They are not really _public_, they are just `public`. :wink: Because Java does not really give you any option here (at least not until July), you have to use `public` but that does not mean that they are supported API. **If** they are (and I doubt that but that's just my opinion without having looked at them), then sure, go ahead. But as soon as you want to use `Internal` for the first time you will (or should?) again wonder where to put that method.

**Comment by marcphilipp** [comment]
As the Javadoc on `@API` indicates: We can still add `@API(Internal)` to methods in `AnnotationUtils` that we don't want to be used.

**Comment by nicolaiparlog** [comment]
I know you _can_ the question is whether you _should_ if it can be avoided. If one out of ten methods is internal, then publishing all of them is fine. If nine out of ten methods are internal, then publishing all is just cruel.

**Comment by sormuras** [comment]
Going the `public` is _public_ way till the end, within the entire `junit-platform-commons` module (read: all declared packages in it) should not contain a single use of `@API(Internal)`. It's first-class member like `java.util` is to the JDK. You are encouraged to use it. You don't have to. As long the platform and Jupiter and Vintage are using those tools -- I consider them maintained.

If some type (e.g. `CloseablePath`) or method or ... is not not ment to be published, it is declared `private`, `protected` or package private.

**Comment by jbduncan** [comment]
> I understand 3. in such a way that internally, JUnit continues to use the Utils as is - nothing changes here. Additionally, everything that external users are allowed to call (effectively everything besides @API(Internal)) would be found in that gateway, by which I mean copy-pasting the signature and @API annotation and forwarding the method call. The gateway gets exported, the internal utilities don't. Changing public API is as simple as creating/deleting forwarding calls.

Yep, that's exactly the idea I had when I suggested 3. as an option.

I admit I'm struggling to see what's so bad with this idea, especially in light of Jigsaw where, AFAICT, something like this would be needed if JUnit 5 ever decides to adopt Java 9+ or modules.

@sormuras @jlink, can you kindly explain to me again why you think it isn't such a good idea?

**Comment by jbduncan** [comment]
> Going the public is public way till the end...

I ain't convinced by this. :wink:

With the introduction of Jigsaw, `public` no longer means "truly public", it just means "public (accessible) **if it's exported from a module**".

Unfortunately or not, the smallest "things" that can me made "truly public" in Jigsaw are classes. Hence I suggested 3. as a way of exporting a "gateway" of methods in `AnnotationUtils` and other static utils classes that we really don't want normal users to use as-is, but which we want to support a small portion of for extension-writers.

I understand that perhaps I'm not explaining myself very well, so if my explanation _is_ unclear, please do let me know what you're confused about, and I'll do my best to better explain myself.

**Comment by nicolaiparlog** [comment]
> It's first-class member like `java.util` is to the JDK.

You are aware that `java.util` uses a lot of internal types, right? Package-private classes, public classes from `sun.*`, from `com.sun.*`, from `jdk.internal` - none of them are supported APIs. In fact, that it seems that `java.util` is all public is making my point for me: It presents a shiny gateway to the interconnected web of supported and internal APIs.

> As long the platform and Jupiter and Vintage are using those tools -- I consider them maintained.

But _maintained_ means they can be changed, particularly as the requirements for JUnit change. What the users need is _stable_, though.

Final summary of my argument before I have to do something else:

* use `@API(Internal)` aggressively to reduce API surface because that needs to be maintained and kept (somewhat) stable
* if many utilities are internal, don't tease users by showing them to them, instead make sure it is hard for them to depend on them (using "them" to mean two different subjects - awesome Englishing)
* consider creating a gateway (proposal 3.) to present users with a uniform surface and use Jigsaw to lock everything else away

**Comment by sormuras** [comment]
@nicolaiparlog You're argument regarding `java.util` can also be re-turned into one supporting the _public_ approach: public members of `ReflectionUtils` is the shiny gateway to the internal types of `ClasspathScanner` and `CloseablePath`.

I do like both solutions. I will favor the simpler one, which achives the goal of having a set of common platform utilities usable by any (internal and external) engine, extension or what-ever author.

@jbduncan Can you modify/comment the draft https://github.com/junit-team/junit5/compare/issue-246-352-utilities what needs to be changed to accomplish proposol 3? Just replace the `default` modifier with `static`?

**Comment by jlink** [comment]
If I'm going to write a test engine today I can use all of junit-common fully aware that it might and probably will change in future releases. If you lock it away and don't publish everything I need I'll have to duplicate logic with a chance of creating inconsistent behaviour. The hiding is just not worth it IMO and brings potential problems. Focus on the tools that evaluate the correct usage of API methods instead. 

Von meinem iPad gesendet

**Comment by jbduncan** [comment]
> @jbduncan Can you modify/comment the draft https://github.com/junit-team/junit5/compare/issue-246-352-utilities what needs to be changed to accomplish proposol 3?

Certainly!

I've provided links below to my comments on the draft:
- https://github.com/junit-team/junit5/commit/76e799795102ce8991b76b1f1d00af81da727590#commitcomment-20930421
- https://github.com/junit-team/junit5/commit/76e799795102ce8991b76b1f1d00af81da727590#commitcomment-20930423
- https://github.com/junit-team/junit5/commit/76e799795102ce8991b76b1f1d00af81da727590#commitcomment-20930429
- https://github.com/junit-team/junit5/commit/76e799795102ce8991b76b1f1d00af81da727590#commitcomment-20930425
- https://github.com/junit-team/junit5/commit/76e799795102ce8991b76b1f1d00af81da727590#commitcomment-20930427

**Comment by jbduncan** [comment]
Hi @jlink,

> Focus on the tools that evaluate the correct usage of API methods instead.

That's a good point I think. Perhaps we should wait until good tools for validating `@API` usage appear?

> If I'm going to write a test engine today I can use all of junit-common fully aware that it might and probably will change in future releases. If you lock it away and don't publish everything I need I'll have to duplicate logic with a chance of creating inconsistent behaviour. The hiding is just not worth it IMO and brings potential problems.

I think we'll have to agree to disagree, because IMO clear separation of concerns via API hiding is more important than code duplication in this case. :)

**Comment by jlink** [comment]
Sure. YMMV. The JUnit 5 team will decide.

2017-02-17 15:17 GMT+01:00 Jonathan Bluett-Duncan <notifications@github.com>
:

**Comment by marcphilipp** [comment]
I can see two advantages of introducing a gateway (as detailed out in https://github.com/junit-team/junit5/issues/352#issuecomment-280646629). First, we could eventually use Jigsaw to hide the utils package that contains the implementations. Second, it would be very clear which utility methods are available to be used in third-party code. We would still have to be very careful when modifying the implementations, though.

Maybe `JUnitUtils` would be a slightly better name for such a gateway class than `Utilities`. But then again, you can always argue about naming...

**Comment by marcphilipp** [comment]
Team decision:

Introduce `org.junit.platform.commons.support.AnnotationSupport` and `org.junit.platform.commons.support.ReflectionSupport` annotated with `@API(Maintained)`.

**Comment by jlink** [comment]
Any support for classpath scanning?

**Comment by sormuras** [comment]
> Any support for classpath scanning?

@jlink Which methods exactly do you have in mind?

**Comment by jlink** [comment]
```
ClasspathScanner.scanForClassesInPackage
ClasspathScanner.scanForClassesInClasspathRoot
```

I wasn't aware that they have corresponding methods in ReflectionUtils, though. So it's probably covered by the team decision.

**Comment by sormuras** [comment]
Closed by https://github.com/junit-team/junit5/commit/086c13b8ab8138611111cd77039b7937e0a20a96

**Comment by jlink** [comment]
Looks like some of the needed stuff from ReflectionUtils is missing in ReflectionSupport, e.g. `findMethod|s`, `isStatic/Private/Abstract`. Especially the hierarchical method finding is hard to implement if one wants to mimick Jupiter's behaviour. Anyone doing that would probably come out with "just a little difference".

All of that I just used yesterday when implementing a very simple test engine for educational purposes.

**Comment by sormuras** [comment]
Candidates, which depend on Jupiters' way of implemetation:

- Optional< Method > **findMethod**(Class<?> clazz, String methodName, Class<?>... parameterTypes)
- List< Method > **findMethods**(Class<?> clazz, Predicate<Method> predicate, MethodSortOrder sortOrder)

The one-liners coping with element modifiers are ... are to fly-weight and straight-forward to be "supported" by the Platform.

**Comment by sormuras** [comment]
*findMethods* is in https://github.com/junit-team/junit5/pull/688 ... do you need the other two as well, @jlink ?

**Comment by jlink** [comment]
Sure. Go ahead.

2017-02-24 21:31 GMT+01:00 Christian Stein <notifications@github.com>:
