### ISSUE TITLE
Opt-in: Use `equals()` method from `actual` in object assertions

### ISSUE THREAD

**Issue by bjmi** [junit-team/junit5#3527]
Other unit testing frameworks and assertion libraries use following assertion pattern
`actual.equals(expected)` - Ref: https://github.com/junit-team/junit5/issues/3120#issuecomment-1596090617

and the rationale behind JUnit 5 does it `expected.equals(actual)` is

> When we first introduced assertEquals in JUnit Jupiter, I copied and modified the existing logic from JUnit 4.
> There was no rationale other than keeping it similar to JUnit 4.
Ref: https://github.com/junit-team/junit5/issues/3120#issuecomment-1596161330

Therefore please provide a global switch like a system property or configuration parameter that allows to use the `equals()` implementation of `actual` as an opt-in feature. Otherwise it would probably break existing test codebases. And it allows to migrate tests to the requested behavior smoothly.

The idea is that `obj1` and `obj2` could be swapped via a switch:
https://github.com/junit-team/junit5/blob/3f6c32b76540ce9c7816c8b77cdcf10df5427eff/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java#L106-L111

(Then even `assertNotEquals(null, actual)` would reveal when the equals method doesn't work with a null parameter, although this assertion example is not recommended.)
### Refs
* https://github.com/junit-team/junit5/issues/3120
* https://github.com/junit-team/junit5/issues/623

**Comment by Madjosz** [comment]
I just want to note that
* C#'s NUnit also calles `expected.Equals(actual)` ([Source code](https://github.com/nunit/nunit/blob/d22be76f6d7180142f197b7eeb8c8a36b97d8056/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L141) is called with `x` as expected, `y` as actual)
* JS assertion library chai.js does `expected ==(=) actual` ([Source code](https://github.com/chaijs/chai/blob/744a16e1cc4e8a9c6d4499e1e520a0bc4c80ec18/lib/chai/interface/assert.js#L136) although [comparision in JS is a different beast](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-islooselyequal))

**Comment by marcphilipp** [comment]
> Therefore please provide a global switch like a system property or configuration parameter that allows to use the `equals()` implementation of `actual` as an opt-in feature. Otherwise it would probably break existing test codebases. And it allows to migrate tests to the requested behavior smoothly.

Could you please provide a more concrete use case? In my opinion, this argument does not justify making this configurable strongly enough.

**Comment by bjmi** [comment]
I ran existing tests with the modified `objectsAreEqual(obj2, obj1)` in projects in our company and to my surprise not one of them failed after this change. Maybe @rschmitt could try this in a bigger code base and can present his results.
Thus it might break existing tests in very rare cases only. (or our tests are just in good shape ;) )

Basically `assertEquals(Object expected, Object actual)` doesn't enforce that both arguments are of the same type.
An improper chosen _expected_ could lead to a false positive when the `equals()` implementation is too permissive and / or isn't symmetric and it leads to _expected_ being actually tested.
In that case I'd like to rely on the `equals()` of _actual_.

I cannot judge whether the introduction is justified. From my side I'd enable that feature at our company by default.

Side-effect: `assertNotEquals(null, actual)` would actually call `actual.equals()` method and would reveal null pointer issues in the implementation.

**Comment by marcphilipp** [comment]
**Team decision:** As different comparison strategies could cause confusion (e.g. when only doing so locally but not on CI, different behavior in different projects, new people joining the team etc.), we think it's not justified to make it configurable. In general, users always have the option to choose a different assertion library or create their own assertion methods.
