### ISSUE TITLE
Patching a module with Java 21 fails with Maven Surefire

### ISSUE THREAD

**Issue by future2r** [junit-team/junit5#3528]
When you run the attached minimal example with "mvnw test" with java 21 it will fail. Somehow the module is not known during patching. It works fine with Java 20.

[example_java21.zip](https://github.com/junit-team/junit5/files/13225675/example_java21.zip)

**Comment by sormuras** [comment]
Seems due to an outdated ASM version being used by Surefire:

```
...
[DEBUG]       org.codehaus.plexus:plexus-java:jar:1.1.2:compile (version managed from default)
[DEBUG]          org.ow2.asm:asm:jar:9.4:compile
...
```

Updating to ASM 9.5 (supports Java 21) or ASM 9.6 (supports Java 22-ea) should help. https://asm.ow2.io/versions.html

**Comment by future2r** [comment]
I can confirm that. With the changes above it works.

**Comment by sormuras** [comment]
Please update https://issues.apache.org/jira/projects/SUREFIRE/issues/SUREFIRE-2207 as well. Thank you.

**Comment by future2r** [comment]
Done that. Thank you for your quick response. It was a pleasure. :-)

**Comment by sormuras** [comment]
> Done that. Thank you for your quick response. It was a pleasure. :-)

Thank you for providing an example for reproduction - that almost always helps a lot to pin-point the underlying cause more quickly.

**Comment by slawekjaranowski** [comment]
Surefire with fix will be published in a three days
If you wish you can check staged release.

https://lists.apache.org/thread/fbfp5jy0x5gxvvjr9zp3o95jcclgbo3r

**Comment by sormuras** [comment]
Thanks for the information, @slawekjaranowski

**Comment by sormuras** [comment]
With [Surefire 3.2.2](https://central.sonatype.com/artifact/org.apache.maven.surefire/surefire/versions) being released you should be able to remove the extra configuration for ASM.

**Comment by future2r** [comment]
I can confirm that. Thanks for the hint @sormuras
