### ISSUE TITLE
Platform Launcher discovers and runs Vintage nested tests twice

### ISSUE THREAD

**Issue by danilopiazza** [junit-team/junit5#3537]
The [JUnit Platform Launcher API](https://junit.org/junit5/docs/current/user-guide/#launcher-api) ([`LauncherDiscoveryRequest`](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherDiscoveryRequest.html)) discovers and executes nested tests inside JUnit 4 classes annotated with [`@Enclosed`](https://junit.org/junit4/javadoc/latest/org/junit/experimental/runners/Enclosed.html) twice.

I was able to reproduce this issue on JUnit 5.10.0 down to 5.8.0 and, after removing references to [`LauncherSession`](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSession.html), as far back as 5.5.0.

### Reproducer Git repository

https://github.com/danilopiazza/junit5-3537-reproducer

Run with:

    mvn verify

### Main class which uses the JUnit Platform Launcher API

```java
var request = LauncherDiscoveryRequestBuilder.request()
        .selectors(selectPackage("nestedtests.tests"))
        .build();
try (LauncherSession session = LauncherFactory.openSession()) {
    session.getLauncher().execute(request);
}
```

### Discovered JUnit 4 test class

```java
@RunWith(Enclosed.class)
public class DiscoveredVintageEnclosedTests {
    public static class DiscoveredEnclosedTests {
        @Test
        public void vintageEnclosedTest() {
            System.out.println("RUNNING discovered enclosed vintage tests TWICE");
            assertTrue(true);
        }
    }
}
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Vintage 5.10.0, Platform 1.10.10
 - Build Tool/IDE: Maven

## Deliverables

- [ ] Ensure that nested test classes are only discovered/executed once with `@RunWith(Enclosed.class)`.

**Comment by sbrannen** [comment]
Hi @danilopiazza,

Congratulations on reporting your first issue for JUnit 5! 👍 

I have confirmed that this is a bug that occurs with or without the `LauncherSession`.

The result can also be visually observed in the Eclipse UI.

<img width="565" alt="Screenshot 2023-11-05 at 15 09 11" src="https://github.com/junit-team/junit5/assets/104798/5be7239e-ec31-4a10-921c-04298cc97c3b">

Thus, it appears that `DiscoveredEnclosedTests` is discovered/executed once by itself and a second time as a child of `DiscoveredVintageEnclosedTests`.

We'll look into it.

**Comment by marcphilipp** [comment]
The reason Surefire only runs it once, is that there's a default [exclude filter](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludes) in place for `**/*$*`.

You could do the equivalent in your custom main class:
```java
var request = LauncherDiscoveryRequestBuilder.request()
        .selectors(selectPackage("nestedtests.tests"))
        .filters(ClassNameFilter.excludeClassNamePatterns(".+\\$.+"))
        .build();
```
