### ISSUE TITLE
Temporary directories retained by cleanup mode should be traceable

### ISSUE THREAD

**Issue by delanym** [junit-team/junit5#3558]
I configured `junit.jupiter.tempdir.cleanup.mode.default = ON_SUCCESS`
Then I ran a test that was made to fail.
I saw that a directory was created and retained: /tmp/junit16392329683018641954
But there is no mention of this directory in surefire output or surefire-reports
So if a test fails (or passes) and I want to examine the results I have to guess which directory to look in.

Perhaps for failing tests the path can be evident in surefire output so I can quickly examine the files.
And for failing AND successful tests the path can be written to surefire reports.

**Comment by marcphilipp** [comment]
As a workaround, does printing the dir in your test code work?

**Comment by sbrannen** [comment]
> So if a test fails (or passes) and I want to examine the results I have to guess which directory to look in.

You should actually be able to see the directory if you set log level for the `org.junit.jupiter.engine.extension` category to `INFO`.

https://github.com/junit-team/junit5/blob/89303135ba1621ac2d184e24ccdf378c6055bb75/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L302-L305

**Comment by sbrannen** [comment]
> So if a test fails (or passes) and I want to examine the results I have to guess which directory to look in.

If a test fails, you should be able to see the directory if you set log level for the `org.junit.jupiter.engine.extension` category to `INFO`.

https://github.com/junit-team/junit5/blob/89303135ba1621ac2d184e24ccdf378c6055bb75/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L302-L305

**Comment by marcphilipp** [comment]
**Team decision:** Closing since already possible by enabling logging.

**Comment by delanym** [comment]
The cleanup message comes at the start of the logs. Not very intuitive.
I don't want to change the log level to INFO for this. If there are failures and there's something to do—that's when I need to see it.

**Comment by sbrannen** [comment]
> But there is no mention of this directory in surefire output or surefire-reports

I suppose JUnit Jupiter _could_ register a report entry for the temp directory in addition to logging it.

Does the version of Surefire you're using support JUnit 5 "report entries"?

If not, how would you expect to be able to access this information (if not via the log)?

**Comment by delanym** [comment]
I'm using the latest. I mentioned the surefire report but I don't think I would want to go there to find this out.

If its too much to move the log line to after the tests and have the log level dependent on the outcome (info for success, warn for fail) then lets just leave it. I see the log in Intellij and that's 99% of our usage. Thanks for considering.
