### ISSUE TITLE
Question about android support

### ISSUE THREAD

**Issue by raniejade** [junit-team/junit5#356]
Hi! I'm working on a JUnit Platform `TestEngine` for https://github.com/JetBrains/spek. One thing we want to keep is the ability to write tests for android projects. The platform relies heavily on Java 8 features, how would this affect android users? Or is it supported at all?

**Comment by marcphilipp** [comment]
AFAIK you still cannot run JDK >= 8 on Android devices. Thus, you cannot run the new JUnit Platform on an Android device. You could use JUnit 5 to write _unit_ tests, though.

I'm closing this issue. Feel free to reopen it or comment if you have any questions.
