### ISSUE TITLE
java.util.Set org.junit.platform.engine.TestDescriptor.getAncestors()

### ISSUE THREAD

**Issue by hantsy** [junit-team/junit5#3560]
I encountered the issue in my project: https://github.com/hantsy/arquillian-container-glassfish-jakarta

I am using JUnit 5.10.1, managed by a BOM import.

```xml
<dependency>
  <groupId>org.junit</groupId>
  <artifactId>junit-bom</artifactId>
  <version>${junit-jupiter.version}</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```

In the `jboss-parent` upgrade PR, it tries to update the surefire to the newest version, and throws the following exceptions.

https://github.com/hantsy/arquillian-container-glassfish-jakarta/actions/runs/6918305067/job/18820424749?pr=21

I tried to show the dependencies tree, and got the following.

```bash 
[INFO] \- org.junit.jupiter:junit-jupiter:jar:5.10.1:test
[INFO]    +- org.junit.jupiter:junit-jupiter-api:jar:5.9.3:test
[INFO]    |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO]    |  +- org.junit.platform:junit-platform-commons:jar:1.10.1:test
[INFO]    |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO]    +- org.junit.jupiter:junit-jupiter-params:jar:5.9.3:test
[INFO]    \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.3:test
[INFO]       \- org.junit.platform:junit-platform-engine:jar:1.9.3:test
```

I do not know why the JUnit 5 versions are different in the transitive deps.

_Originally posted by @hantsy in https://github.com/junit-team/junit5/issues/3548#issuecomment-1817742654_

**Comment by marcphilipp** [comment]
Your versions are not aligned (5.10.1/1.10.1 vs. 5.9.3). Please make sure they all use the same version, preferably 5/1.10.1. I'm not sure what's the proper way of doing this with the JBoss parent POM. You might have to set a certain property in your POM or similar.
