### ISSUE TITLE
`LauncherInterceptor` is missing from the `org.junit.platform.launcher` module's `uses` declaration

### ISSUE THREAD

**Issue by shartte** [junit-team/junit5#3561]
## Steps to reproduce

- Set junit.platform.launcher.interceptors.enabled to true
- Try running JUnit tests as modules
- Exception: `Caused by: java.util.ServiceConfigurationError: org.junit.platform.launcher.LauncherInterceptor: module org.junit.platform.launcher does not declare uses`

## Context

 - Used versions (Jupiter/Vintage/Platform): Platform 1.10.1
 - Build Tool/IDE: Gradle

Probably an oversight since JUnit platform consumed as a module is an uncommon configuration.
The new Interceptor probably just needs to be added here:
https://github.com/junit-team/junit5/blob/main/junit-platform-launcher/src/module/org.junit.platform.launcher/module-info.java#L37

**Comment by sormuras** [comment]
Good catch!

I wonder why our modular compilation tests didn't catch that missing `uses` directive. 🤔

**Comment by sormuras** [comment]
I guess `javac` doesn't perform the "static" check due to that we no longer use `ServiceLoader.load(...)` method directly:

https://github.com/junit-team/junit5/blob/f892e8153736a20d7bfd9c8687d79ab775968544/junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ServiceLoaderRegistry.java#L28

**Comment by sormuras** [comment]
> You can compile without it.

Sure. Yet, a warning should be emitted when running `javac` in modular mode and there's a `ServiceLoader.load(LauncherInterceptor.class[, ...])` statement and no `uses [...]LauncherInterceptor` in the associated module declaration. And as we usually compile with "treat all warnings as errors" flag, it should not compile (in modular mode).

**Comment by sormuras** [comment]
At least, it is an IntelliJ IDEA code inspection: https://www.jetbrains.com/help/idea/list-of-java-inspections.html#visibility "Usage of service not declared in `module-info`"

**Comment by sormuras** [comment]
Seems like I there's **no** such lint warning from `javac` - neither `javac -Xlint:module ...` nor `javac -Xlint:all ...` emits the warning that IDEA generates. Perhaps, we can teach `javac` to perform a similar check. But that all can be done in parallel with your PR here.

**Comment by marcphilipp** [comment]
Reopening to backport it to 5.10.2

**Comment by sormuras** [comment]
Backported via https://github.com/junit-team/junit5/commit/ec8d4282c60f480d3de264330b37e75b1b8d05d9
