### ISSUE TITLE
Javadoc should refer to arguments providers rather than argument providers

### ISSUE THREAD

**Issue by markslater** [junit-team/junit5#3579]
There's a minor typo in the Javadoc for [`ParameterizedTest`](https://github.com/junit-team/junit5/blob/r5.10.1/junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java#L31) and [`ArgumentsSource`](https://github.com/junit-team/junit5/blob/r5.10.1/junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/ArgumentsSource.java#L26) in JUnit 5.10.1.

Both these annotations refer to the [`ArgumentsProvider`](https://github.com/junit-team/junit5/blob/r5.10.1/junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/ArgumentsProvider.java) interface, which is appropriately named because it provides a `Stream` of instances of `Arguments`.  However, in the text of the Javadoc, they refer to "argument providers" (singular argument).

The Javadoc should read "argument**s** providers" to match the terminology used in the code.

## Context

 - JUnit Jupiter Params 5.10.1

**Comment by sbrannen** [comment]
Hi @markslater,

Congratulations on opening your first issue for JUnit 5! 👍 

I've already made the suggested changes.

Cheers
