### ISSUE TITLE
@Tag should be processed by Vintage Engine

### ISSUE THREAD

**Issue by adrian-tarau** [junit-team/junit5#3602]
Vintage Engine (which runs JUnit4 tests) converts @ Category into a tag (class name -> tag). However, for consistency, one would want to tag old tests the same as new tests (**fast** for unit tests, **slow** for integration tests) and reference them as one set with a single tag.  Right now, If you want to run unit tests only, you would have to provide two tags, **fast** and **com.company.UnitTestCategory**.

We just need a bit of code in _VintageTestDescriptor_ to handle the @ Tag annotation (probably make _JupiterTestDescriptor.getTags_ public and call it from _VintageTestDescriptor_ ?).

**Comment by marcphilipp** [comment]
I can understand where you're coming from, but I don't think mixing JUnit 4 and Jupiter annotations in a test class is a good idea as it's confusing. Each engine has its own way of letting users define tags. In JUnit 4 it's the `@Category` annotation, in Jupiter it's `@Tag`, in jqwik it's `@Label`.
