### ISSUE TITLE
Update Store to use type-safe keys.

### ISSUE THREAD

**Issue by kcooney** [junit-team/junit5#361]
Currently the APIs for updating and removing values from `Store` was not type-safe. In 55175604801ada @sbrannen added methods so that you can avoid casts when getting the values, but the programmer still has to ensure that all of the places were a key is accessed uses the same type.

Instead, we can make the keys generic. In other words, we would create a key class that encapsulates two things: a key for getting the value and the type for the values.

One proposal would be to have a `Key` interface that just looks like this:

```
public interface Key<V> {}
```

Keys could be constructed like this:

```
private static final Key<Long> KEY = Key.create();
```

Then used like this:

```
Long value = store.remove(KEY);
```

This works if you need a key that could be represented as a compile time constant. If you wanted the key to depend on a value type (for example, `Method`) we could provide a different API to create Keys:

```
private static final KeySpace<Method, Long> METHOD_START_TIMES = new KeySpace<>() {
  @Override protected Long initialValue(Method key) {
    return System.currentTimeMillis;
  }
};   
```

(named "KeySpace" because it is a namespace for keys)

A `KeySpace` would be used like this:

```
Key<Long> key = METHOD_START_TIMES.keyFor(method);
Long startTime = store.remove(key);
```

We could add methods to `Store` to make using a `KeySpace` even easier:

```
Long startTime = store.remove(METHOD_START_TIMES, method);
```

**Comment by sbrannen** [comment]
Thanks for the proposal!

We'll look into later, perhaps in the M2 time frame.

**Comment by marcphilipp** [comment]
i'm closing this issue (see discussion in #996 for details).
