### ISSUE TITLE
`NamespacedHierarchicalStore` should fail on modifications after close

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#3614]
## Status Quo

The `NamespacedHierarchicalStore` doesn't track its state. Currently it is possible to call `put()` or any other modifying action after the store has already been closed via `close()`, allowing for potential misuse and bugs to creep in unknowingly.

## Proposal

Any modification or query after `close()` should result in an `IllegalStateException` or similar. The method `close()` should be idempotent: any subsequent call to `close()` should effectively be a no-op.

## Deliverables

- [x] `NamespacedHierarchicalStore` tracks its active/closed state
- [x] `NamespacedHierarchicalStore` throws an exception for modification or query calls after it has been closed
- [x] `NamespacedHierarchicalStore.close()` is idempotent

**Comment by sbrannen** [comment]
Thanks for raising the issue, @leonard84.

I've slated this for 5.11 M1.

Would you be interested in submitting a PR?

**Comment by Code-breaker1998** [comment]
Hi @sbrannen 

Can you assigned this issue to me?

**Comment by mobounya** [comment]
Oops did not notice that this does not have an `up-for-grabs` label, can i still submit a PR for this ?

**Comment by marcphilipp** [comment]
@mobounya Yes, feel free to do so! I've added the label now.

**Comment by sbrannen** [comment]
The current implementation for tracking `closed` state does not mark the store as closed if an exception is thrown while invoking close actions.

See:

https://github.com/junit-team/junit5/blob/0ce27d212f115427938caca3703724c6c055aa3f/platform-tests/src/test/java/org/junit/platform/engine/support/store/NamespacedHierarchicalStoreTests.java#L448-L449

I am therefore reopening this issue to address that bug.
