### ISSUE TITLE
Incorrect module-info.class in junit-jupiter-api jar version 5.6.3 ot 5.10.0

### ISSUE THREAD

**Issue by marioja** [junit-team/junit5#3619]
When using either versions of junit5 Eclipse will report the jar to require a java runtime version 9 because of this file.  There might be other validation (in maven builds) in the future that will also fail because of this.

## Steps to reproduce

Open a java project in Eclipse 2023-12 that has a dependency on junit-jupiter-api version 5.10.0 and turn on the java/compiler/building/incompatible required binaries: error.  You must have a java 8 JRE for your java project.  You will see the error 

> Incompatible .class files version in required binaries. Project 'tjp' is targeting a 1.8 runtime, but is compiled against 'C:Users/usera/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.6.3/junit-jupiter-api-5.6.3.jar' which requires a 9 runtime

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.6.3, 5.10.0
 - Build Tool/IDE: Eclipse 2023-12

I have not tested other version of jupiter or eclipse but I suspect that any version of junit 5 and any recent version of Eclipse will display the problem.

## Deliverables

- [ ] ...

**Comment by sormuras** [comment]
Java versions below 9 (8 or lower) should never read the `module-info.class` file; Java versions 9 and higher will do just fine.

Seems to be an issue (regression?) with Eclipse and its "java/compiler/building/incompatible required binaries: error" validation. Can you try to ignore binary module descriptor files?

**Comment by khmarbaise** [comment]
The incompatible class file is the `module-info.class` in the root of the jar file which is required... and is ignored by JVM (less than 9).. The JUnit Jupiter will work perfectly in JDK8 only ... also in JDK9+ 
A Maven build will not do a validation like that neither today nor in the future...

**Comment by sbrannen** [comment]
> Can you try to ignore binary module descriptor files?

One option might be to use a Resource Exclude Filter for the project in Eclipse: `Properties for <project>` &rarr; `Resource` &rarr; `Resource Filters` &rarr; `Add Filter...`.
