### ISSUE TITLE
Support scanning for classpath resources

### ISSUE THREAD

**Issue by mpkorstanje** [junit-team/junit5#3630]
Currently `ReflectionUtils` supports resolving class based selectors such as `PackageSelector` and  `ClasspathRootSelector`.  These can be resolved using `findAllClassesInPackage` and `findAllClassesInClasspathRoot` respectively. 

Unfortunately there are no resource based equivalents to help resolve resources contained in a class path directory targeted by a `ClasspathResourceSelector` or `ClasspathRootSelector` e.g:

```java
List<Resource> findAllResourcesInPackage(String basePackageName, ResourceFilter resourceFilter)

List<Resource> findAllResourcesInClasspathRoot(URI root, ResourceFilter resourceFilter) 
```

As this functionality is backed by the `ClasspathScanner` I believe it would be prudent to add this functionality prior to making the `ClasspathScanner` part of the public API as proposed in https://github.com/junit-team/junit5/issues/3628. This would avoid breaking changes by adding more methods to an interface, or potential bug reports caused by a default implementation that always returns an empty collection of resources. 

And I would be happy to provide a PR that facilitates this.

## Deliverables

- [ ] Support for scanning class path resources through `ReflectionUtils` and `ClasspathScanner`.

**Comment by sbrannen** [comment]
We never implemented that, because we never needed to scan for resources (other than `.class` files).

What's the concrete use case you're thinking of -- scanning for Cucumber files or similar?

**Comment by mpkorstanje** [comment]
Yup. Cucumber uses `.feature` files which are typically located on the classpath. 

The benefits would be two fold
 * Eventually replace Cucumbers classpath scanning with the JUnit Platform
 * Benefit from implementations that support classpath scanning on Android.

**Comment by marcphilipp** [comment]
**Team decision:** Let's add the two extra methods to `ClasspathScanner` and make them available via `ReflectionSupport` and `ReflectionUtils`.

As a follow-up task, we should add a `addResourceContainerSelectorResolver()` method to `EngineDiscoveryRequestResolver.Builder` analogous to `addClassContainerSelectorResolver()`.

**Comment by marcphilipp** [comment]
@mpkorstanje A PR would be most welcome! 🙂

**Comment by mpkorstanje** [comment]
I am still working on this, unfortunately due to circumstances it is going a bit slower than usual.

**Comment by sbrannen** [comment]
Thanks for letting us know, @mpkorstanje.

This is currently assigned to the 5.11 M2 milestone, so you've got a bit more time.
