### ISSUE TITLE
Getting Ambiguous method overloading for method org.testng.Assert#assertEquals. in groovy version 3.0.19

### ISSUE THREAD

**Issue by PrakratiAgarwal123** [junit-team/junit5#3634]
Ambiguous method overloading for method org.testng.Assert#assertEquals. Cannot resolve which method to invoke for [class java.lang.Integer, class java.lang.Integer] due to overlapping prototypes between:  [int, class java.lang.Integer]  [class java.lang.Integer, int]

Code is  -
     List<MyClass> listOfClassFields = MyClass.classMethod("CO").read()
 Assert.assertEquals(7,listOfClassFields.size())

**Comment by sbrannen** [comment]
Hi @PrakratiAgarwal123,

This is the issue tracker for JUnit 5.

The `Assert` class you're using is from TestNG.

Thus, please raise an issue with the [TestNG team](https://github.com/testng-team/testng).

In light of the above, I'm closing this issue.
