### ISSUE TITLE
Introduce support for excluding packages and classes

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#364]
## Status Quo

The Maven Surefire Plugin's API provides wildcarded "includes" and "excludes" for test selection.  Having the ability to exclude a subset of packages and/or classes from those included via the `@SelectedPackages` and `@SelectedClasses` annotations would provide the equivalent ability for declarative tests.  I would also recommend that if includes and excludes configuration is not provided through the plugin's API, the `JUnitPlatformProvider` should use the underlying declarative configuration.

## Proposal

Introduce `@ExcludePackages` and `@ExcludeClasses` for use with the `JUnitPlatform` runner.

An example of use cases is provided in the code block below:

```java
@SelectPackages("a.b.c")
@ExcludePackages("a.b.c.d.e")
@SelectClasses(a.b.c.d.e.SomeTest.class)
class TestCase { /* ... */ }
```

Recommended rules for prioritizing includes and excludes are:

-   Explicitly selected packages and classes are always run.
-   Excluded packages and classes must be subsets of selected packages.
-   Explicitly selecting and excluding the same package or class is an error.

**Comment by sbrannen** [comment]
Thanks for raising the issue. We had in fact already foreseen the need -- thus the recent renaming of `@Packages` and `@Classes`, etc. -- but we had not yet raised a public issue.

Note that I have slightly modified the title and description and have assigned this to M2 for the time being.

**Comment by sbrannen** [comment]
Disregard my last comment. 😉 

I am closing this issue since it duplicates #313 and #314.

Feel free to comment directly on those issues if you have further input.

**Comment by smoyer64** [comment]
You're right ... it's a duplicate as I missed the tasks to add useful filtering annotations.

Sorry!
