### ISSUE TITLE
Improve documentation for contents of `junit-platform-console-standalone` artifact

### ISSUE THREAD

**Issue by siddhsql** [junit-team/junit5#3648]
[this](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher) link states:

>An executable junit-platform-console-standalone-1.10.1.jar with all dependencies included is published in the [Maven Central](https://search.maven.org/) repository under the [junit-platform-console-standalone](https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone) directory. It includes the following dependencies:

junit:junit:4.13.2

org.apiguardian:apiguardian-api:1.1.2

org.hamcrest:hamcrest-core:1.3

org.junit.jupiter:junit-jupiter-api:5.10.1

org.junit.jupiter:junit-jupiter-engine:5.10.1

org.junit.jupiter:junit-jupiter-params:5.10.1

org.junit.platform:junit-platform-commons:1.10.1

org.junit.platform:junit-platform-console:1.10.1

org.junit.platform:junit-platform-engine:1.10.1

org.junit.platform:junit-platform-launcher:1.10.1

org.junit.platform:junit-platform-reporting:1.10.1

org.junit.platform:junit-platform-suite-api:1.10.1

org.junit.platform:junit-platform-suite-commons:1.10.1

org.junit.platform:junit-platform-suite-engine:1.10.1

org.junit.platform:junit-platform-suite:1.10.1

org.junit.vintage:junit-vintage-engine:5.10.1

org.opentest4j:opentest4j:1.3.0

However, when I try to include `junit-platform-console-standalone-1.10.1` in my `pom.xml` file like so:

```xml
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-console-standalone</artifactId>
    <version>1.10.1</version>
    <scope>test</scope>
</dependency>
```

I get none of the abovementioned dependencies. running `mvn dependency:tree` confirms the same.

**Comment by sbrannen** [comment]
Hi @siddhsql,

Congratulations on raising your first issue for JUnit 5! 👍 

I wouldn't say the documentation is necessarily incorrect; however, I can see how it can be misleading.

The `junit-platform-console-standalone` artifact is what is known as a _Fat JAR_: it _contains_ the contents of all of those dependencies.

As such, there is no need for it's POM to declare transitive dependencies on the JARs for those contained artifacts.

As a side note, you should practically never include a dependency on the `junit-platform-console-standalone` artifact in your Maven POM or Gradle build script. Rather, you should include dependencies only on the JUnit artifacts that you actually need in your project. Note that you can use the `junit-jupiter` aggregator artifact or `junit-bom` to simplify dependency management of JUnit artifacts in your build.

Hopefully that clarifies matters for you.

I've labeled this as a `documentation` issue to improve the wording the User Guide regarding the `junit-platform-console-standalone` artifact.

**Comment by sbrannen** [comment]
The updated documentation can be viewed here:

https://junit.org/junit5/docs/snapshot/user-guide/#running-tests-console-launcher

**Comment by siddhsql** [comment]
thanks.
