### ISSUE TITLE
Reporting tree incorrect for dynamically added containers.

### ISSUE THREAD

**Issue by mfulton26** [junit-team/junit5#368]
This is a follow-up to #366.

I tried adding a dynamic container as a sub-container to my dynamic container. It runs fine but the report doesn't have the hierarchy I expected:

**Expected**
* :white_check_mark: DemoTestEngine
  * :white_check_mark: demo
    * :white_check_mark: root *#*0
      * :white_check_mark: container *#*1 
        * :white_check_mark: dynamic test *#*1
        * :white_check_mark: dynamic test *#*2
        * :white_check_mark: container *#*2
          * :white_check_mark: dynamic test *#*3

**Actual**
* :red_circle: DemoTestEngine
  * :red_circle: demo
    * :red_circle: root *#*0
  * :white_check_mark: container *#*1 
    * :white_check_mark: dynamic test *#*1
    * :white_check_mark: dynamic test *#*2
  * :white_check_mark: container *#*2
    * :white_check_mark: dynamic test *#*3

**Code**
```java
import org.junit.platform.engine.*;
import org.junit.platform.engine.support.descriptor.AbstractTestDescriptor;
import org.junit.platform.engine.support.descriptor.EngineDescriptor;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.runner.RunWith;

@RunWith(JUnitPlatform.class)
public class DemoTestEngine implements TestEngine {

    private UniqueId rootUniqueId;

    @Override
    public String getId() {
        return "demo";
    }

    @Override
    public TestDescriptor discover(EngineDiscoveryRequest discoveryRequest, UniqueId uniqueId) {
        EngineDescriptor engineDescriptor = new EngineDescriptor(uniqueId, "demo");
        RootTestDescriptor root = new RootTestDescriptor(uniqueId.append("root", "0"), "root #0");
        engineDescriptor.addChild(root);
        rootUniqueId = root.getUniqueId();
        return engineDescriptor;
    }

    @Override
    public void execute(ExecutionRequest request) {
        EngineExecutionListener engineExecutionListener = request.getEngineExecutionListener();
        TestDescriptor engineDescriptor = request.getRootTestDescriptor();
        TestDescriptor root = engineDescriptor.findByUniqueId(rootUniqueId).get();

        TestDescriptor container = new ContainerTestDescriptor(rootUniqueId.append("container", "1"), "container #1");
        root.addChild(container);

        engineExecutionListener.dynamicTestRegistered(container);
        engineExecutionListener.executionStarted(container);
        engineExecutionListener.executionFinished(container, TestExecutionResult.successful());

        UniqueId containerUid = container.getUniqueId();

        TestDescriptor dynamicTest1 = new TestTestDescriptor(containerUid.append("test", "1"), "dynamic test #1");
        container.addChild(dynamicTest1);
        engineExecutionListener.dynamicTestRegistered(dynamicTest1);
        engineExecutionListener.executionStarted(dynamicTest1);
        engineExecutionListener.executionFinished(dynamicTest1, TestExecutionResult.successful());

        TestDescriptor dynamicTest2 = new TestTestDescriptor(containerUid.append("test", "2"), "dynamic test #2");
        container.addChild(dynamicTest2);
        engineExecutionListener.dynamicTestRegistered(dynamicTest2);
        engineExecutionListener.executionStarted(dynamicTest2);
        engineExecutionListener.executionFinished(dynamicTest2, TestExecutionResult.successful());

        TestDescriptor subcontainer = new ContainerTestDescriptor(containerUid.append("container", "2"), "container #2");
        container.addChild(subcontainer);
        engineExecutionListener.dynamicTestRegistered(subcontainer);
        engineExecutionListener.executionStarted(subcontainer);
        engineExecutionListener.executionFinished(subcontainer, TestExecutionResult.successful());

        UniqueId subcontainerUid = subcontainer.getUniqueId();

        TestDescriptor dynamicTest3 = new TestTestDescriptor(subcontainerUid.append("test", "3"), "dynamic test #3");
        subcontainer.addChild(dynamicTest3);
        engineExecutionListener.dynamicTestRegistered(dynamicTest3);
        engineExecutionListener.executionStarted(dynamicTest3);
        engineExecutionListener.executionFinished(dynamicTest3, TestExecutionResult.successful());
    }

    static class RootTestDescriptor extends AbstractTestDescriptor {
        RootTestDescriptor(UniqueId uniqueId, String displayName) {
            super(uniqueId, displayName);
        }

        @Override
        public boolean isContainer() {
            return true;
        }

        @Override
        public boolean isTest() {
            return false;
        }

        @Override
        public boolean hasTests() {
            return true;
        }
    }

    static class ContainerTestDescriptor extends AbstractTestDescriptor {
        ContainerTestDescriptor(UniqueId uniqueId, String displayName) {
            super(uniqueId, displayName);
        }

        @Override
        public boolean isContainer() {
            return true;
        }

        @Override
        public boolean isTest() {
            return false;
        }
    }

    static class TestTestDescriptor extends AbstractTestDescriptor {
        TestTestDescriptor(UniqueId uniqueId, String displayName) {
            super(uniqueId, displayName);
        }

        @Override
        public boolean isContainer() {
            return false;
        }

        @Override
        public boolean isTest() {
            return true;
        }
    }
}
```

I'm using IntelliJ IDEA 2016.1.3. Might this be an IDE/JUnit4 integration issue? Am I doing something wrong or is there something I can do to work around this?

Thanks!

**Comment by sbrannen** [comment]
You definitely cannot rely on an IDE to understand dynamic tests registered by the JUnit Platform when running via JUnit 4.

So the best thing to do is debug it and manually verify the tree structure.

Please give that a try.

If you find that the physical tree structure in the `TestPlan` is not as you would expect, then please post your findings back here.

Thanks!

**Comment by sbrannen** [comment]
FYI: Eclipse also does not properly display dynamic tests where they belong in the test tree, and that is to be expected.

**Comment by sbrannen** [comment]
I am closing this issue for now, but if you detect an actual bug in the structure of the `TestPlan`, we'll be happy to reopen this issue.

**Comment by mfulton26** [comment]
I've placed a breakpoint on [`JUnitPlatformTestTree.java:63`](https://github.com/junit-team/junit5/blob/47d20a7448d441f3239b9b2ace53fe45396d9859/junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatformTestTree.java#L63).

Below are the variables for `this.plan`.

I'm not sure but I suspect that "[engine:demo]/[root:0]/[container:1]" and "[engine:demo]/[root:0]/[container:1]/[container:2]" should not be direct `children` of `this.plan`. Thoughts?

- this.plan = {TestPlan@1177}
  - roots = {LinkedHashSet@1222}  size = 1
    - 0 = {TestIdentifier@1235} "TestIdentifier [uniqueId = '[engine:demo]', parentId = null, displayName = 'demo', source = null, tags = [], test = false, container = true]"
  - children = {LinkedHashMap@1223}  size = 4
    - 0 = {LinkedHashMap$Entry@1252} "[engine:demo]" -> " size = 1"
    - 1 = {LinkedHashMap$Entry@1253} "[engine:demo]/[root:0]" -> " size = 1"
    - 2 = {LinkedHashMap$Entry@1254} "[engine:demo]/[root:0]/[container:1]" -> " size = 3"
    - 3 = {LinkedHashMap$Entry@1255} "[engine:demo]/[root:0]/[container:1]/[container:2]" -> " size = 1"
  - allIdentifiers = {LinkedHashMap@1224}  size = 7
    - 0 = {LinkedHashMap$Entry@1227} "[engine:demo]" -> "TestIdentifier [uniqueId = '[engine:demo]', parentId = null, displayName = 'demo', source = null, tags = [], test = false, container = true]"
    - 1 = {LinkedHashMap$Entry@1228} "[engine:demo]/[root:0]" -> "TestIdentifier [uniqueId = '[engine:demo]/[root:0]', parentId = '[engine:demo]', displayName = 'root *#*0', source = null, tags = [], test = false, container = true]"
    - 2 = {LinkedHashMap$Entry@1229} "[engine:demo]/[root:0]/[container:1]" -> "TestIdentifier [uniqueId = '[engine:demo]/[root:0]/[container:1]', parentId = '[engine:demo]/[root:0]', displayName = 'container *#*1', source = null, tags = [], test = false, container = true]"
    - 3 = {LinkedHashMap$Entry@1230} "[engine:demo]/[root:0]/[container:1]/[test:1]" -> "TestIdentifier [uniqueId = '[engine:demo]/[root:0]/[container:1]/[test:1]', parentId = '[engine:demo]/[root:0]/[container:1]', displayName = 'dynamic test *#*1', source = null, tags = [], test = true, container = false]"
    - 4 = {LinkedHashMap$Entry@1231} "[engine:demo]/[root:0]/[container:1]/[test:2]" -> "TestIdentifier [uniqueId = '[engine:demo]/[root:0]/[container:1]/[test:2]', parentId = '[engine:demo]/[root:0]/[container:1]', displayName = 'dynamic test *#*2', source = null, tags = [], test = true, container = false]"
    - 5 = {LinkedHashMap$Entry@1232} "[engine:demo]/[root:0]/[container:1]/[container:2]" -> "TestIdentifier [uniqueId = '[engine:demo]/[root:0]/[container:1]/[container:2]', parentId = '[engine:demo]/[root:0]/[container:1]', displayName = 'container *#*2', source = null, tags = [], test = false, container = true]"
    - 6 = {LinkedHashMap$Entry@1233} "[engine:demo]/[root:0]/[container:1]/[container:2]/[test:3]" -> "TestIdentifier [uniqueId = '[engine:demo]/[root:0]/[container:1]/[container:2]/[test:3]', parentId = '[engine:demo]/[root:0]/[container:1]/[container:2]', displayName = 'dynamic test *#*3', source = null, tags = [], test = true, container = false]"

**Comment by sbrannen** [comment]
I apologize for having instructed you to look at the `TestPlan`. That was a logic error on my part.

The actual tree structure is only visible within the `TestDescriptor` hierarchy.

So, for example, if you invoke `printPath(dynamicTest2)` (see code below) within your engine's `execute()` method, I think you'll see what you're expecting, namely: `demo ==> root #0 ==> container #1 ==> dynamic test #2`

```java
	static void printPath(TestDescriptor descriptor) {
		System.err.println(concat(descriptor));
	}

	static String concat(TestDescriptor descriptor) {
		if (descriptor.isRoot()) {
			return descriptor.getDisplayName();
		}
		else {
			return concat(descriptor.getParent().get()) + " ==> " + descriptor.getDisplayName();
		}
	}
```

Can you please verify you see the expected tree structure using these utility methods?

**Comment by sbrannen** [comment]
FYI: it will be up to build tools and IDE vendors to display a proper tree based on `TestIdentifier`s.

**Comment by sbrannen** [comment]
To simplify matters, you can also easily print the entire tree with `printTree(request.getRootTestDescriptor())`, given the following. 😉 

```java
	static void printTree(TestDescriptor descriptor) {
		printTree(descriptor, 0);
	}

	static void printTree(TestDescriptor descriptor, int depth) {
		System.err.println(String.join("", Collections.nCopies(depth, "\t")) + descriptor.getDisplayName());
		descriptor.getChildren().forEach(child -> printTree(child, depth + 1));
	}
```

Of course, you have to invoke `printTree()` _after_ having built up the entire tree.

**Comment by mfulton26** [comment]
Not a problem. Thank you for the further clarification.

```java
printPath(engineDescriptor);
printPath(root);
printPath(container);
printPath(dynamicTest1);
printPath(dynamicTest2);
printPath(subcontainer);
printPath(dynamicTest3);
```

does indeed produce the desired paths:

```
demo
demo ==> root #0
demo ==> root #0 ==> container #1
demo ==> root #0 ==> container #1 ==> dynamic test #1
demo ==> root #0 ==> container #1 ==> dynamic test #2
demo ==> root #0 ==> container #1 ==> container #2
demo ==> root #0 ==> container #1 ==> container #2 ==> dynamic test #3
```

I'm not too familiar with how IDE test runners integrate/inspect JUnit runners to build such reporting. Any insight as to why static tests (e.g. `Nested` classes with tests) would be able to be reported on fine through the IDE but dynamic tests wouldn't?

**Comment by sbrannen** [comment]
The above `printTree()` output for your test engine is as follows:

```demo
	root #0
		container #1
			dynamic test #1
			dynamic test #2
			container #2
				dynamic test #3
```

So, that's exactly what you were expecting! 👍

**Comment by sbrannen** [comment]
@mmerdes, what ever happened to that cool _ASCII tree printing_ `TestExecutionListener` you wrote?

**Comment by mmerdes** [comment]
@sbrannen this tree printer was rather static in nature - could be interesting to see how it could be extended to truly dynamic  `DynamicTest`s

**Comment by sbrannen** [comment]
@mmerdes, I only intend to use it in a static way, to print out a human readable tree after the entire test plan finishes. Anyway, I'll open a separate issue to address that.

**Comment by sbrannen** [comment]
FYI: I created #369 regarding the tree printing `TestExecutionListener`.
