### ISSUE TITLE
Document `SuiteLauncherDiscoveryRequestBuilder`

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#3695]
`LauncherDiscoveryRequestBuilder` is very well documented; however, `SuiteLauncherDiscoveryRequestBuilder` has zero documentation.

We should therefore introduce Javadoc for `SuiteLauncherDiscoveryRequestBuilder` and all of its `public` methods, analogous to the documentation for `LauncherDiscoveryRequestBuilder`. In fact, most of the work will be copy-and-paste.

**Comment by airtyon** [comment]
May I start working on this one?

**Comment by sbrannen** [comment]
Hi @airtyon,

Thank you very much for volunteering!

However, let's hold off until we know if @mpkorstanje wishes to address it.

See https://github.com/junit-team/junit5/pull/3694#discussion_r1493745271 for details.

**Comment by sbrannen** [comment]
Good news, @airtyon, @mpkorstanje has said he's happy to let you take this one.

I've assigned it to you.

So, go for it!

**Comment by sbrannen** [comment]
This has been addressed in `main` in c9e66fc8d70b95295411d24b2de8aabe2d01efe3 and revised in e9f1bcc4979759c74a1f29194327062318298d73.
