### ISSUE TITLE
Define a new XML report schema that supports the JUnit Platform

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#373]
## Overview

The `XmlReportWriter` in the `junit-platform-console` currently generates XML that is compliant with the de facto standard for JUnit 4; however, this XSD is very limiting and does not support many of the features of the JUnit Platform.

## Goals

Define a new XML report schema that supports the features of the JUnit Platform.

The following is only a partial list of features needed beyond the JUnit 4 de facto standard.

- unique IDs
- display names
- tags
- test sources
- custom reporting entries
- nested test classes
- skipped vs. aborted execution

## Additional Considerations

- Provide a mechanism for converting between the JUnit 4 XSD and JUnit Platform XSD (e.g., via XSLT).
- Provide a JSON based format compatible with the XML format.

## Related Discussions

- https://github.com/ota4j-team/opentest4j/issues/9
- #86 
- #350 
- #372

**Comment by jensim** [comment]
The surefire-reports are not valid in junit5.
We had a problem running JUnit plugins in jenkins because the XML validation would fail.
The difference between junit4 and junit5 is the XML tag "xsi:noNamespaceSchemaLocation" has changed to "xsi:schemaLocation".
I've manually validated both junit4 and junit5 reports, and junit4 succeeds where junit5 reports fail.

**Comment by marcphilipp** [comment]
How did you generate the XML reports? Using Maven or using Gradle/ConsoleLauncher?

**Comment by marcphilipp** [comment]
Using Gradle/ConsoleLauncher seems to work fine for us: 
https://junit.ci.cloudbees.com/job/JUnit5/job/master/91/testReport/

**Comment by jensim** [comment]
Maven
I made a focused project to showcase this
https://github.com/jensim/junit5-bad-report

**Comment by marcphilipp** [comment]
@jensim The XML report is generated by the maven-surefire-plugin, not by JUnit. Did you also switch to a later version of the maven-surefire-plugin?

**Comment by jensim** [comment]
I was starting out from scratch
Now I've tested all released versions of the surefire plugin against junit-5.0.1.
I've discovered that the ONLY version this will both not crach and build a valid report is 2.20. 
Version 2.20.1 craches. 
Version 2.19.x are invalid. (surefires 'fault')
Versions prior to 2.19.x craches.

The good thing is, there is one version that is compatible with junit5, yay!

**Comment by jensim** [comment]
I noticed that junit 5.0.2 was released a few days ago, but this version changed none of my results.

**Comment by jensim** [comment]
I'll just post the print i get when running 2.20.1 version of surefire
````
/usr/lib/jvm/java-8-oracle/bin/java -Dmaven.multiModuleProjectDirectory=/home/jens/vcs/junit5-bad-report -Dmaven.home=/home/jens/opt/idea-IU-172.4343.14/plugins/maven/lib/maven3 -Dclassworlds.conf=/home/jens/opt/idea-IU-172.4343.14/plugins/maven/lib/maven3/bin/m2.conf -javaagent:/home/jens/opt/idea-IU-172.4343.14/lib/idea_rt.jar=35379:/home/jens/opt/idea-IU-172.4343.14/bin -Dfile.encoding=UTF-8 -classpath /home/jens/opt/idea-IU-172.4343.14/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2017.2.6 clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building junit-test-xsd 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ junit-test-xsd ---
[INFO] Deleting /home/jens/vcs/junit5-bad-report/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ junit-test-xsd ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/jens/vcs/junit5-bad-report/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ junit-test-xsd ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /home/jens/vcs/junit5-bad-report/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ junit-test-xsd ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/jens/vcs/junit5-bad-report/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ junit-test-xsd ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /home/jens/vcs/junit5-bad-report/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ junit-test-xsd ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.560 s
[INFO] Finished at: 2017-11-18T08:33:10+01:00
[INFO] Final Memory: 16M/248M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project junit-test-xsd: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jens/vcs/junit5-bad-report/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] org.apache.maven.surefire.report.RunListener.testSetStarting(Lorg/apache/maven/surefire/report/ReportEntry;)V
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org.apache.maven.surefire.report.RunListener.testSetStarting(Lorg/apache/maven/surefire/report/ReportEntry;)V
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1
````

**Comment by jensim** [comment]
Anyway, this is nolonger a matter of XML formatting, which was the reason i brought it up in this thread from the first place.
Thank you @marcphilipp

**Comment by marcphilipp** [comment]
As stated in the [User Guide](http://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven), Surefire 2.20 has a memory leak. But as long as it works for you, I guess it's okay. 😉

**Comment by mkobit** [comment]
As of right now, is the only way to consume the `ExtensionContext.publishReportEntry` from extensions/what not is to implement [a `TestExecutionListener`](https://junit.org/junit5/docs/5.2.0/api/org/junit/platform/launcher/TestExecutionListener.html#reportingEntryPublished-org.junit.platform.launcher.TestIdentifier-org.junit.platform.engine.reporting.ReportEntry-)? Can that be used from Gradle?

**Comment by sbrannen** [comment]
> As of right now, the only way to consume the `ExtensionContext.publishReportEntry` from extensions/what not is to implement a [`TestExecutionListener`](https://junit.org/junit5/docs/5.2.0/api/org/junit/platform/launcher/TestExecutionListener.html#reportingEntryPublished-org.junit.platform.launcher.TestIdentifier-org.junit.platform.engine.reporting.ReportEntry-)?

Yes, AFAIK, that's correct.

> Can that be used from Gradle?

AFAIK, you cannot register a custom `TestExecutionListener` within a Gradle build script, but @marcphilipp can perhaps correct me if I'm wrong.

In any case, you can have your custom `TestExecutionListener` registered automatically. Details here: https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom

**Comment by marcphilipp** [comment]
Gradle has its own `TestListener` that you can register on a `Test` task: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:addTestListener(org.gradle.api.tasks.testing.TestListener)

It does not currently report events for intermediate nodes in the test tree, though.

**Comment by marcphilipp** [comment]
@bitcoder Yes, we still want to define a new schema that supports all Platform features. It's probably not going to make 5.5 but will be our top priority for 5.6.

**Comment by bitcoder** [comment]
thanks @marcphilipp for the feedback; that means that you will be able to make whatever changes will be necessary on the surefire plugin, if necessary, in order to generate that report?

**Comment by marcphilipp** [comment]
We'll work with the Surefire team to make it happen.

**Comment by bitcoder** [comment]
Then, from "Xray Test Management for Jira" team side will make the integration happen ASAP right afterwards :)

**Comment by tobymurray** [comment]
Reading this today, ironically while trying to integrate with XRay, is it accurate to say there's no out-of-the-box way to have `@DisplayName` contents appear in the XML produced by a JUnit 5 execution? I can use reflection and log it to system out, which is captured in `<system-out>`, but so is a lot of other stuff.

**Comment by bitcoder** [comment]
There are so many people waiting for a new, more complete format; I hope it comes soon so we can adopt it and bring it to everyone.
Eventually @tobymurray you may need to have a custom report to have it that would duplicate the existing Junit XML generation code (?) but probably a better solution is to wait for the format. Maybe @marcphilipp and the team can provide more insights at this point

**Comment by baev** [comment]
@tobymurray for now you can try use Allure as middleware.

**Comment by tobymurray** [comment]
I've never looked at Allure before (assuming it's [this](https://docs.qameta.io/allure/)). I'll see what it offers for what I'm looking at - thanks for the tip. I'll update if it comes together with something usable that might be workable for others.

**Comment by baev** [comment]
> I've never looked at Allure before (assuming it's this).

yep

We even have a plugin for XRay https://github.com/allure-framework/allure2/tree/master/plugins/xray-plugin

As a bonus you'll not only get support for JUnit5 tests, but we also provide integrations for majority of test frameworks (not only for Java, but also for Python, JavaScript, C# and others). 

<details>
  <summary>Advertising</summary>
  Allure has paid version https://qameta.io/ that extends open source report and integrations, and it also provides XRay integration. 
</details>

**Comment by bitcoder** [comment]
Unfortunately, this keeps getting postponed :( we have many customers asking for this kind of capability

**Comment by marcphilipp** [comment]
Any arguments against using JSON instead of XML for the new format?

**Comment by bitcoder** [comment]
Hi @marcphilipp , we don't see any problems with adopting JSON instead of XML. For us, it will be a new format we have to support and if it's more flexible/easier in the future to make changes in it, ok.
As long as JUnit team provides a kinda of schema for it, it's ok 👍  We've seen some JSON formats out there that don't have a clear definition which in the end leads to some confusion around implementations.

**Comment by signed** [comment]
Would be nice to have support for #271 in the report as well.

> Any arguments against using JSON instead of XML for the new format?

If you think about changing the format did you consider [yaml](https://yaml.org/)?

**Comment by bitcoder** [comment]
@signed , yaml is not suited for reporting IMO.

**Comment by aslakhellesoy** [comment]
I'd like to chime in with our experience defining a new report format in Cucumber a couple of years ago. Cucumber has been able to produce a JSON report for several years, but we're phasing this out and replacing it with a stream of *messages*, encoded as [NDJSON](http://ndjson.org/).

Here is a minimal example: https://github.com/cucumber/cucumber/blob/master/compatibility-kit/javascript/features/minimal/minimal.ndjson

Due to the cross-platform nature of Cucumber, we implemented this using protobuf, but in hindsight that was a mistake, and we're in the process of [replacing it with JSON Schema](https://github.com/cucumber/cucumber/pull/1414).

The main reason we went for multiple messages instead of one large JSON document is to reduce potentially huge memory consumption. If the report contains several image attachments (common when used in conjunction with browser testing tools), the report can get very big. The lack of streaming support in JSON means all those attachments must be kept in memory until the final document is written. So we went with individual messages instead.

I'm not suggesting JUnit adopt the Cucumber message format as-is. But I do think an NDJSON based message stream format could work well.

You can read more about [Cucumber Messages here](https://github.com/cucumber/cucumber/blob/master/messages/README.md).

**Comment by sbrannen** [comment]
@aslakhellesoy, thanks for sharing your insight regarding individual JSON messages. We'll take that into consideration.

**Comment by brabenetz** [comment]
Any update on this ticket.
Would be nice to have readable test-names for Parameterized Tests in the surfire-reports.
Or does someone know a workaround?

**Comment by marcphilipp** [comment]
I'm working on it but in the meantime, have you tried [configuring Surefire](https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName)?

**Comment by benhumphrey-okta** [comment]
If a test report XML output testcase entry looks like this for my JUnitParamsRunner JUnit4 test,  Is there any workaround ? I assume configuring _statelessTestsetReporter_ is for Junit5 tests (I attempted to add it to my pom but it seemed to have no effect on a Junit4 test. Our organization has a large number of JUnitParamsRunner tests. Conversion isn't straigtforward (that I'm aware) given thousands of legacy tests.  

` <testcase name="" classname="com.`

Also wanted to confirm this is in the scope of this isse.

**Comment by marcphilipp** [comment]
> If a test report XML output testcase entry looks like this for my JUnitParamsRunner JUnit4 test, Is there any workaround ?

I'm not a Surefire expert. I'm afraid, you'll have to ask on StackOverflow or the Maven users list.

> Also wanted to confirm this is in the scope of this isse.

Yes, that should be addressed by the new format as well.

**Comment by marcphilipp** [comment]
Please see https://github.com/ota4j-team/opentest4j/issues/9#issuecomment-1078990334
