### ISSUE TITLE
junit-jupiter:5.9.1- Not able to build with UAT.- (GPG signing failure)

### ISSUE THREAD

**Issue by shivsrivastava** [junit-team/junit5#3741]
I am building code of junit-jupiter:5.9.1 with UAT enabled and trying ./gradlew test command. Here are my tried versions.

Java version - 8, 11, 17
Gradle command - ./gradlew test
Gradle build command - ./gradlew build -x test

## Steps to reproduce

I am facing this error/issue . Also attached log.
[build-junit-jupiter-5.9.1-2024-02-28-09-32-43-014-6275255597.txt](https://github.com/junit-team/junit5/files/14716108/build-junit-jupiter-5.9.1-2024-02-28-09-32-43-014-6275255597.txt)

"[28 09:38:49.578] | > Task :junit-bom:signMavenPublication FAILED
[28 09:38:49.578] | gpg: directory '/root/.gnupg' created
[28 09:38:49.578] | gpg: keybox '/root/.gnupg/pubring.kbx' created
[28 09:38:49.578] | gpg: no default secret key: No secret key
[28 09:38:49.578] | gpg: signing failed: No secret key"

**Comment by marcphilipp** [comment]
Why are you building 5.9.1 yourself? I'm afraid the Gradle build logic in that version always requires signing when building non-snapshot versions. The error message indicates that you have no secret keys in your GPG keyring. If you generate one by running `gpg --gen-key` ([more detailed instructions](https://central.sonatype.org/publish/requirements/gpg/#generating-a-key-pair)), it should work.

**Comment by shivsrivastava** [comment]
With 

> 5.9.1

We are having requirement of building code with UT pass. Please let me know how to complete it. 
As per my understanding, UT cases( Test cases) should pass without providing any  secret keys.

**Comment by shivsrivastava** [comment]
Please update.

**Comment by marcphilipp** [comment]
You should be able to skip signing but run all tests using this command:

```
$ ./gradlew test -x signMavenPublication
```

**Comment by shivsrivastava** [comment]
> You should be able to skip signing but run all tests using this command:
> 
> ```
> $ ./gradlew test -x signMavenPublication
> ```
I do not want to skip any module/submodule. Requirement is to have all test cases passed.

**Comment by shivsrivastava** [comment]
Please update on this ticket.

**Comment by devidandupati** [comment]
I tried mention jdk and mvn version's but still facing issue

**Comment by meetankit24** [comment]
Multiple times i tried but getting same issue for Maven 3.9.6

**Comment by marcphilipp** [comment]
> I do not want to skip any module/submodule. Requirement is to have all test cases passed.

This does not skip any module, only the signing of artifacts

**Comment by sormuras** [comment]
From your log: `./gradlew build -x test -q --stacktrace`
Replace (as suggested) with: `./gradlew build -x signMavenPublication`

_Happiness follows suit._

**Comment by shivsrivastava** [comment]
> From your log: `./gradlew build -x test -q --stacktrace` Replace (as suggested) with: `./gradlew build -x signMavenPublication`
> 
> _Happiness follows suit._

Sure, will check and update.
