### ISSUE TITLE
Disable creation of Log4J JMX beans in Gradle test conventions

### ISSUE THREAD

**Issue by sdavids** [junit-team/junit5#3751]
Would it make sense to disable the creation of Log4J JMX beans?

## Steps to reproduce

https://github.com/junit-team/junit5/blob/ccd24b390d5b571f047c1c205f11407acfca90c9/gradle/plugins/common/src/main/kotlin/junitbuild.testing-conventions.gradle.kts#L43

⇓

```kotlin
systemProperty("java.util.logging.manager", "org.apache.logging.log4j.jul.LogManager")
systemProperty("log4j2.disableJmx", "true")
```

## Context

> To disable JMX completely, and prevent these MBeans from being created, specify system property `log4j2.disableJmx` to true when you start the Java VM.

https://logging.apache.org/log4j/2.x/manual/jmx.html#enabling-jmx

**Comment by sbrannen** [comment]
As long as we are not relying on their presence, it sounds reasonable to disable the JMX beans.

@marcphilipp and @sormuras, do you foresee any issue with disabling them?

**Comment by sormuras** [comment]
No. Our tests don't rely on JMX to configure Log4J at runtime.

PR also looks good to me.
