### ISSUE TITLE
Request to add copyright information to pom.xml

### ISSUE THREAD

**Issue by zeeneir** [junit-team/junit5#3756]
Our organization requires us to record copyright information for all OpenSource library dependencies. The copyright scanner we use can extract all information from pom.xml. Therefore it would be great if you could add the copyright in the pom.xml or even have it as a separate file in your repository.

**Comment by sormuras** [comment]
Can you please configure the copyright scanner to extrat the information from a source file of your choice?

```
/*
 * Copyright 2015-2024 the original author or authors.
 *
 * All rights reserved. This program and the accompanying materials are
 * made available under the terms of the Eclipse Public License v2.0 which
 * accompanies this distribution and is available at
 *
 * https://www.eclipse.org/legal/epl-v20.html
 */
```

![image](https://github.com/junit-team/junit5/assets/2319838/7a6a0780-aaba-4083-a69a-0de42c7b4561)

Counted 1300+ duplications already.

**Comment by mpkorstanje** [comment]
> The copyright scanner we use can extract all information from pom.xml.

Looking at the pom files as published on Maven Central, they do contain the license information.

https://central.sonatype.com/artifact/org.junit.jupiter/junit-jupiter-engine
```xml
....
  <licenses>
    <license>
      <name>Eclipse Public License v2.0</name>
      <url>https://www.eclipse.org/legal/epl-v20.html</url>
    </license>
  </licenses>
....
```

**Comment by zeeneir** [comment]
Thanks for the prompt reply. I was looking for this header exactly. We use a 3rd party tool and unfortunately it doesn't have that flexibility. It only looks at the pom file of a given maven dependency. I'm trying to see anything can be done.

**Comment by marcphilipp** [comment]
The published POMs already contain the license information:

```xml
  <licenses>
    <license>
      <name>Eclipse Public License v2.0</name>
      <url>https://www.eclipse.org/legal/epl-v20.html</url>
    </license>
  </licenses>
```

What other information are you looking for?

**Comment by zeeneir** [comment]
I was looking for this line:
`Copyright 2015-2024 the original author or authors.`

It would be amazing if you could add it. But if it's not feasible, feel free to close the ticket.

**Comment by marcphilipp** [comment]
AFAIK the POM schema does not have a "copyright" element. We could customize the generated POM to add a comment but that would be non-standard and provide a questionable benefit. Therefore, I'm closing this issue.
