### ISSUE TITLE
ClassOrderer$Random with seed does not work

### ISSUE THREAD

**Issue by patrick-dedication** [junit-team/junit5#3779]
## Steps to reproduce
JUnit 5.10.2
Have three test files and use `junit.jupiter.execution.order.random.seed` in combination with `junit.jupiter.testclass.order.default=org.junit.jupiter.api.ClassOrderer$Random` in `junit-platform.properties`.
Run the tests multiple times, they have a different order each time.
As far as I see this is because `ClassOrderer::orderClasses` gets a differently ordered list from `context.getClassDescriptors()` with almost every test-run. 

## Context

 - Used versions (Jupiter/Vintage/Platform):
 - Build Tool/IDE:

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
Please provide a sample project which reproduces the issue so that we can run it ourselves -- for example, a public Git repository or a ZIP file attached to this issue.

Thanks

**Comment by patrick-dedication** [comment]
Tried to reproduce, but found out it's an edge case, sorry for wasting you time.

What happens:
I have a gradle Task to run the test suite 10 times, when I pick the seed from the first failing run and run the tests with the default test task then the order is different, but consistent.
So I guess my way of reproducing/fixing problems is not optimal.

**Comment by sbrannen** [comment]
> Tried to reproduce, but found out it's an edge case, sorry for wasting you time.

No problem.

Thanks for letting us know.
