### ISSUE TITLE
Provide opt-in support for technical names instead of display names for JUnitPlatform runner

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#379]
When `JUnitPlatform` is used through build tools such as Gradle or Bamboo, using display names for test and container descriptors causes them to be shown in the default package. To provide a good interim solution, f7b93a3f2818494048b741dbbf4b10ff2e02557a changed the names in `Description` objects for test descriptors to use class and method names.

## Deliverables

- [x] Introduce new annotation `@UseTechnicalNames` to enable this behavior. When the annotation is not present, display names will be used (as before).
- [x] Use class name for suite descriptions, too, if `@UseTechnicalNames` is present.

**Comment by sbrannen** [comment]
_in progress_
