### ISSUE TITLE
Console launcher should support `--version`

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#3795]
The `junit` console launcher should support a `--version` option and print its version.

Perhaps it should also print the version of each discoverable test engine?

**Comment by marcphilipp** [comment]
There's support for version options in Picocli: https://picocli.info/#_version_help

**Comment by sormuras** [comment]
Related option already in place: `--list-engines`
- https://github.com/junit-team/junit5/issues/2789

**Comment by sbrannen** [comment]
@sormuras, can you please create a new issue to address that in 5.11 M3?
