### ISSUE TITLE
`InvocationInterceptor` is not invoked for a parameterized test

### ISSUE THREAD

**Issue by ArvindJoshi-okta** [junit-team/junit5#3808]
JUnit 5 - 5.10.2

## Steps to reproduce

Hello,
I am trying to add a JUnit5 extension to my test class, but for some reason, the parameterized test isn't executing it. A non-parameterized test within the same class seems to be executing the extension fine. Am I missing something?

Here's my test class

```
@ExtendWith(MyExtension.class)
class MyTest {

    @ParameterizedTest
    @NullAndEmptySource
    void testNotSkipping(String test) {
    }

    @Test
    void testGettingSkipped() {
    }
}
```

Here's my extension, simplified to just skip the test

```
class MyExtension implements InvocationInterceptor {

    @Override
    public void interceptTestMethod(Invocation<Void> invocation, ReflectiveInvocationContext<Method> invocationContext,
                                    ExtensionContext extensionContext) {
        System.out.println("Skipping test ... ");
        invocation.skip();
    }
}
```

Looks like the annotation already extends an extension, maybe due to that, its not able to extend additional ones?

```
@Target({ElementType.ANNOTATION_TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@API(
    status = Status.STABLE,
    since = "5.7"
)
@TestTemplate
@ExtendWith({ParameterizedTestExtension.class})
public @interface ParameterizedTest {
```

## Context

 - Used versions (Jupiter/Vintage/Platform): 
 
 ```
         <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>5.10.2</version>
            </dependency>
```

 - Build Tool/IDE: Maven/IntelliJ

**Comment by BlueIce** [comment]
According to the [JavaDoc](https://junit.org/junit5/docs/5.10.2/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/InvocationInterceptor.html#interceptTestMethod(org.junit.jupiter.api.extension.InvocationInterceptor.Invocation,org.junit.jupiter.api.extension.ReflectiveInvocationContext,org.junit.jupiter.api.extension.ExtensionContext)) the `interceptTestMethod` method will only be called for Test-Methods:

> Intercept the invocation of a [@Test](https://junit.org/junit5/docs/5.10.2/api/org.junit.jupiter.api/org/junit/jupiter/api/Test.html) method.


For parameterized tests you need to use [`interceptTestTemplateMethod`](https://junit.org/junit5/docs/5.10.2/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/InvocationInterceptor.html#interceptTestTemplateMethod(org.junit.jupiter.api.extension.InvocationInterceptor.Invocation,org.junit.jupiter.api.extension.ReflectiveInvocationContext,org.junit.jupiter.api.extension.ExtensionContext)).

**Comment by ArvindJoshi-okta** [comment]
Thank, @BlueIce, that worked!
