### ISSUE TITLE
JUnit Platform Surefire provider ignores purely dynamic test classes

### ISSUE THREAD

**Issue by littleclay** [junit-team/junit5#384]
I have a test project I am running some JUnit 5 experiments with using the maven surefire plugin. I am seeing an issue with dynamic tests. It apparently isn't discovering TestFactories as tests unless regular test methods also appear in the class. Take the following test class:

```java
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;
import java.util.stream.Stream;

public class FooTest {
	@Test
	public void foo() {
		System.out.println( "Hello" );
	}

	@TestFactory
	public Stream< DynamicTest > testFactoryFoo() {
		return Stream.of( "A", "B" )
					 .map( str -> DynamicTest.dynamicTest( "testFactoryFoo" + str + "()",
														   () -> System.out.println( str ) ) );
	}
}
```

If I run the command `mvn clean test` then I see the expected output:

```
Running redfin.automation.junit.jupiter.FooTest
A
B
Hello
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.059 sec - in redfin.automation.junit.jupiter.FooTest
testFactoryFooA()  Time elapsed: 0.005 sec
testFactoryFooB()  Time elapsed: 0 sec
foo()  Time elapsed: 0.002 sec

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

However, if I take out the regular test `foo` leaving only the TestFactory, and try running `mvn clean test` again, I get the following output:

```
Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by sbrannen** [comment]
Are you using M1?

**Comment by sbrannen** [comment]
I have confirmed that this is a bug.

Thanks for raising the issue!

We'll look into it.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
This has been fixed in 5c391f998a98e5152a329a72c164fabd78e151b5.

Please try out the next available snapshot and let us know if this solves your problem.

**Comment by littleclay** [comment]
I tried it with the snapshot and it now works as expected. Thanks!

**Comment by sbrannen** [comment]
Glad to hear it worked, and thanks for letting us know!
