### ISSUE TITLE
Consider implementing assertEqualsAnyOrder(Collection, Collection)

### ISSUE THREAD

**Issue by exabrial** [junit-team/junit5#3869]
Please consider implementing assertEqualsAnyOrder(Collection, Collection)

As far as I'm aware, there is no way in JUnit5 to deeply compare the contents of two collections, without respecting order. This would be useful when comparing sets to lists and this feature would provide a parity to assertIterableEquals(iterable, iterable). 

Thank you for considering!

**Comment by mpkorstanje** [comment]
It might be worth using a different library for assertions instead. As the User Guide notes:

https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions-third-party

> Even though the assertion facilities provided by JUnit Jupiter are sufficient for many testing scenarios, there are times when more power and additional functionality such as matchers are desired or required. In such cases, the JUnit team recommends the use of third-party assertion libraries such as [AssertJ](https://assertj.github.io/doc/), [Hamcrest](https://hamcrest.org/JavaHamcrest/), [Truth](https://truth.dev/), etc. Developers are therefore free to use the assertion library of their choice.

**Comment by marcphilipp** [comment]
Indeed, I was about to post that. In light of the above, I am closing this issue.
