### ISSUE TITLE
TempDir on default file system

### ISSUE THREAD

**Issue by oliviercailloux** [junit-team/junit5#3891]
Please provide a way to request (for example, in the `@TempDir` annotation) that the created path live on the default file system. This is sometimes necessary for a unit test to pass. 

Currently this is possible by specifying one’s own TempDir factory. But having to write one (in each project where this will occur) for such a common feature seems overkill.

The doc does not guarantee that Jupiter’s default implementation uses the default file system. I do not know whether this is intended. It [states](https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory): “The default implementation available in Jupiter delegates the directory creation to java.nio.file.Files::createTempDirectory, passing junit as the prefix string to be used in generating the directory’s name” (as also confirmed by the header of the [Javadoc](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/io/TempDirFactory.Standard.html) of `TempDirFactory.Standard`). And considering in turn the Javadoc of [`Files::createTempDirectory(…)`](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/nio/file/Files.html#createTempDirectory(java.nio.file.Path,java.lang.String,java.nio.file.attribute.FileAttribute...)), this gives no explicit guarantee, as also confirmed by the Javadoc of [`TempDirFactory.Standard::createTempDirectory(…)`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/io/TempDirFactory.Standard.html#createTempDirectory(org.junit.jupiter.api.extension.AnnotatedElementContext,org.junit.jupiter.api.extension.ExtensionContext)). (Incidentally, I do not know why the JUnit doc specifies that its default implementation delegates to `Files::createTempDirectory`: this only seems to constrain the implementation without giving anything useful to the user.)

**Comment by marcphilipp** [comment]
AFAICS since `TempDirFactory.Standard` does not pass a parent directory to `Files.createTempDirectory`, it always uses the default Java temp dir which is always on the default file system. Or am I missing something?

Are you asking us to _document_ that the created path is always on the default file system?

**Comment by oliviercailloux** [comment]
> Are you asking us to _document_ that the created path is always on the default file system?

Yes, if the intent is to provide this guarantee to your users (which was unclear to me so far), not as an implementation detail but as a part of the contract, then I am asking if you can make this guarantee more explicit in the doc.

**Comment by marcphilipp** [comment]
I've clarified that in the User Guide and Javadoc in the linked commit. Feedback welcome! :slightly_smiling_face:
