### ISSUE TITLE
Document that a test class can be implemented as a `record` in the User Guide

### ISSUE THREAD

**Issue by djkeh** [junit-team/junit5#3892]
## Overview

JUnit 5 user guide currently have tons of example test codes, and all the test classes are written in `class`.

It seems that we can write a test class with `record`, and there's no trouble with it.

Well indeed there would be no reason for it not to work, it is simply a final class with private final members and the constructor and etc.
Actually I'd prefer to use `record` because of its neat look and convenience for doing constructor injection.

If it is officially possible without any side effects, i'd like to see the official section or any explanations mentioning `record` and the sample test codes in the user guide.

Thank you.

## Related Issues

Below is just a reference that deals with record-written test: it has nothing to do with this feature request.

- #2575

**Comment by marcphilipp** [comment]
Yes, records are supported (we have tests verifying they work as expected). I wouldn't go as far as recommending them for all tests in general but the User Guide should mention they are supported and include an example.

**Comment by djkeh** [comment]
Thx, so do you have a specific plan to update the user guide for `record`?
