### ISSUE TITLE
Failsafe xml for a test class has results from another class

### ISSUE THREAD

**Issue by ArvindJoshi-okta** [junit-team/junit5#3897]
JUnit version 5.10.2
Using Maven to execute JUnit5 tests (concurrently)

**Issue**

When I execute tests concurrently (at class level), I see the failsafe xmls being generated, but the test methods themselves seem to be mixed up with other classes. 

**Expectation**

Each failsafe xml is unique to a class, which was the case with the JUnit4 provider.

**Sample Code**

pom.xml

`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>JUnit5Sample</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.2.5</version>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>parallel-tests</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.2.5</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>3.2.5</version>
                        <dependencies>
                            <dependency>
                                <groupId>org.junit.jupiter</groupId>
                                <artifactId>junit-jupiter-engine</artifactId>
                                <version>5.10.2</version>
                            </dependency>
                        </dependencies>
                        <configuration>
                            <properties>
                                <configurationParameters>
                                    junit.jupiter.execution.parallel.enabled = true
                                    junit.jupiter.execution.parallel.mode.default = same_thread
                                    junit.jupiter.execution.parallel.mode.classes.default = concurrent
                                </configurationParameters>
                            </properties>
                            <threadCount>4</threadCount>
                            <includes>
                                <include>*IT.java</include>
                            </includes>
                            <reportFormat>xml</reportFormat>
                            <skipITs>false</skipITs>
                            <failIfNoTests>true</failIfNoTests>
                        </configuration>
                        <executions>
                            <execution>
                                <id>parallel-tests</id>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
`

Tests

`
package org.example;

import org.junit.jupiter.api.Test;

class ClassAIT {
    @Test
    void test() {
    }
}
`

`
package org.example;

import org.junit.jupiter.api.Test;

class ClassBIT {
    @Test
    void test() {
    }
}
`

**XML**

Note, this is from Class A's failsafe xml. Class B's xml has no tests in it.

`
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-failsafe-plugin/xsd/failsafe-test-report-3.0.xsd" version="3.0" name="org.example.ClassAIT" time="0.018" tests="2" errors="0" skipped="0" failures="0">
`
`
  <testcase name="test" classname="org.example.ClassBIT" time="0.007"/>
  <testcase name="test" classname="org.example.ClassAIT" time="0.007"/>
`

**Comment by marcphilipp** [comment]
This file is written by the Maven Failsafe plugin, not JUnit. Please raise an issue with them instead.
