### ISSUE TITLE
Duplicate `junit-platform.properties` warning should also print the duplicate URLs

### ISSUE THREAD

**Issue by huxi** [junit-team/junit5#3898]
Due to [a bug in Kafka](https://issues.apache.org/jira/browse/KAFKA-17121), we currently see several warnings in our build that look like this:
`Discovered 2 'junit-platform.properties' configuration files in the classpath; only the first will be used.`

While this is certainly true, I had to write code to find out what's actually going on and pinpoint the issue to Kafka.

This could have been prevented if the warning message would have also included the multiple URLs.

This is not a big thing but a low-hanging fruit to slightly enhance the user experience in such a situation.

**Comment by sbrannen** [comment]
> This could have been prevented if the warning message would have also included the multiple URLs.

Sounds reasonable to me. 

We should be able to adapt `org.junit.platform.launcher.core.LauncherConfigurationParameters.loadClasspathResource(String)` easily to support this.

**Comment by marcphilipp** [comment]
I'll take a look
