### ISSUE TITLE
Regression: Extension must not be registered if already registered for parent context

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#390]
An extension that is applied to the test class as well to a test method therein gets called twice. As far as I can tell, this behavior was different in the alpha version.

In my scenario this had undesired consequences and came as a surprise (I expected it to be called once), so I was initially sure it was a bug. After thinking about it for a while I'm not so sure any more. Maybe there is a use case for this?

More abstract this begs the question of the extension semantics. Does it mean "call this extension at the implemented extension points" (then repeated calls make sense) or does it mean "activate this extension for the implemented extension points" (in which case it should be idempotent).

## Example

```java
public class DoubleCallback implements BeforeTestExecutionCallback {

	@Override
	public void beforeTestExecution(TestExtensionContext context) throws Exception {
		System.out.println("Before " + context.getDisplayName());
	}

}

@ExtendWith(DoubleCallback.class)
class DoubleCallbackTest {

	@Test
	@ExtendWith(DoubleCallback.class)
	void test() { }

}
```

Output:

```
Before test()
Before test()
```

## Deliverables

- [x] Add tests for the previous behavior.
- [x] Fix the regression.
- [x] Document semantics regarding parent and child extension contexts in the User Guide.

**Comment by sbrannen** [comment]
This is a regression that I introduced in 6c146c5a76da048a935c0615a1033fcca7846736, so thanks for bringing this to our attention.

We unfortunately never had any tests in place for the scenario you depicted. So we will add appropriate tests when we fix this.

**Comment by sbrannen** [comment]
FYI: I added _Deliverables_.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
This has been fixed in `master`.
