### ISSUE TITLE
`@TempDir` should fail if `TempDirFactory::createTempDirectory` does not return a directory

### ISSUE THREAD

**Issue by scordio** [junit-team/junit5#3902]
The following test passes:

```java
@Test
void test(@TempDir(factory = Factory.class) Path tempDir) {
}

static class Factory implements TempDirFactory {
    @Override
    public Path createTempDirectory(AnnotatedElementContext elementContext, ExtensionContext extensionContext) throws Exception {
        return Files.createFile(Files.createTempDirectory("junit-").resolve("file"));
    }
}
```

while this one fails:

```java
@Test
void test(@TempDir(factory = Factory.class) Path tempDir) {
    assertThat(tempDir).isDirectory(); // fails
}
```

I propose to let `@TempDir` fail fast if `createTempDirectory` doesn't return a directory, similar to #3900. I could squeeze the corresponding changes in #3901.

**Comment by sbrannen** [comment]
Let's address this one in conjunction with #3900.

In general, we should fail fast if the factory does not return a directory (i.e., returns null or a file).

In light of that, I'm closing this issue as a duplicate.
