### ISSUE TITLE
`@TempDir` with `File` annotated elements should fail fast if temp directory file system is not default

### ISSUE THREAD

**Issue by scordio** [junit-team/junit5#3910]
`TempDirFactory` implementations based on non-default file systems like [jimfs](https://github.com/google/jimfs) and [memoryfilesystem](https://github.com/marschall/memoryfilesystem) cannot work with `@TempDir` annotated elements of type `File`.

See also the `Path::toFile` [Javadoc](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/Path.html#toFile()):

> **Throws:**
>    `UnsupportedOperationException` - if this `Path` is not associated with the default provider

Right now, a test like [the example in the user guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory), but with `tempDir` of type `File`:

```java
@Test
void test(@TempDir(factory = JimfsTempDirFactory.class) File tempDir) {
    // perform test
}

static class JimfsTempDirFactory implements TempDirFactory {

    private final FileSystem fileSystem = Jimfs.newFileSystem(Configuration.unix());

    @Override
    public Path createTempDirectory(AnnotatedElementContext elementContext, ExtensionContext extensionContext) throws IOException {
        return Files.createTempDirectory(fileSystem.getPath("/"), "junit-");
    }

    @Override
    public void close() throws IOException {
        fileSystem.close();
    }

}
```

fails with:

```
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [java.io.File arg0] in method [void io.github.scordio.jimfs.junit.jupiter.Tests.test(java.io.File)]

	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.jimfs.JimfsPath.toFile(JimfsPath.java:386)
	... 2 more
```

I would like to improve the user experience, clearly stating that `File` annotated elements are not supported.

As of today, the factory doesn't have easy access to the type of the annotated element.

In my extension for Jimfs, I've implemented a workaround:

https://github.com/scordio/jimfs-junit-jupiter/blob/ac6f085a89368823e7f515f335eb44f21d981447/src/main/java/io/github/scordio/jimfs/junit/jupiter/JimfsTempDirFactory.java#L86-L107

## Deliverables

I see two possible directions:

1. JUnit owns the error handling and asks the factory if `File` annotated elements are supported
    * This could be done with a new default method in `TempDirFactory`, e.g., `boolean supportsFile()`.
3. The error handling happens in the factory
    * `AnnotatedElementContext` should expose the element type somehow so that the factory can build up the error handling around it without having to cast the result of `getAnnotatedElement()`. For example, a new `Class<?> getAnnotatedElementType()` method could be added to `AnnotatedElementContext`.

My preference goes to option 1 to reduce duplication in each `TempDirFactory` implementation.

I'm happy to contribute once a solution is agreed.

---

Relates to:
* scordio/jimfs-junit-jupiter@99d946e3ca99c807fb70e28e48b6c588027f3e0a
* marschall/memoryfilesystem-junit-provider#2

CC @marschall

**Comment by marcphilipp** [comment]
Thanks for reporting! I'm wondering if we should instead introduce a `List<Class<?>> getSupportedTypes()` method in case we want to support some hypothetical other type in the future. Thoughts?

**Comment by marcphilipp** [comment]
I'm wondering if we could check the file system of the returned `Path` and throw an exception when it's not the default file system and trying to inject a `File`. Can you imaginea case where that wouldn't be sufficient?

**Comment by scordio** [comment]
> Can you imagine a case where that wouldn't be sufficient?

No, not really – this approach seems sensible to me!

I can start with the implementation, unless you see something else to define.

**Comment by marcphilipp** [comment]
No, I think we're good to go! 👍

**Comment by scordio** [comment]
@marcphilipp I'm struggling with deciding where the responsibility of checking the file system should be implemented:

* In the `getPathOrFile` method:

  https://github.com/junit-team/junit5/blob/b105747923df9d9a85b4426b4cc5e11c4692ff8d/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L250-L261

  **Pros**
  * No new parameter needs to be propagated to the `CloseablePath` constructor

  **Cons**
  * The `CloseablePath` instance should be closed in case the file system validation fails
  * Testing to be covered in both `TempDirectoryPerDeclarationTests` and `TempDirectoryPerContextTests`

* In the `CloseablePath` constructor validation:

  https://github.com/junit-team/junit5/blob/b105747923df9d9a85b4426b4cc5e11c4692ff8d/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L287-L298

  **Pros**
  * No `CloseablePath` instance is created when a non-default file system is used
  * Testing can be added to `CloseablePathTests`, although with a bit of complexity (e.g., test case matrix via dynamic tests)

  **Cons**
  * A `Class<?> type` parameter needs to be propagated down to the `CloseablePath` constructor

At the moment, I tend to favor the new constructor parameter, but I wanted to have another opinion before going forward.

**Comment by marcphilipp** [comment]
I think the validation should occur _before_ creating the temporary directory, if possible. Additionally, we need to ensure whenever `TempDirFactory.createTempDirectory` was called,  the corresponding `CloseablePath` is closed so the cleanup is executed. Therefore, I think we should not throw an exception from the `CloseablePath` constructor but validate in the `getPathOrFile` method.

**Comment by scordio** [comment]
> I think the validation should occur before creating the temporary directory, if possible.

Theoretically, the directory is created as soon as `TempDirFactory.createTempDirectory` returns. To perform the validation before the directory is created, we'd have to introduce some new API for `TempDirFactory` (related to https://github.com/junit-team/junit5/issues/3910#issuecomment-2260559403). Or do you have something else in mind?

> Additionally, we need to ensure whenever `TempDirFactory.createTempDirectory` was called, the corresponding `CloseablePath` is closed so the cleanup is executed.

Indeed, that's already a gap caused by #3901, which I addressed separately in #3911.

> Therefore, I think we should not throw an exception from the `CloseablePath` constructor but validate in the `getPathOrFile` method.

If the `CloseablePath` constructor throws an exception, it would be handled similarly to #3911, i.e., with a try/catch that ensures the underlying factory is also closed in case a `PreconditionViolationException` is thrown by the temp directory validation. This way, no `CloseablePath` instance would be created, and no close handling would need to be in the `getPathOrFile` caller.

Of course, we can push this logic up to `getPathOrFile` and that will require explicit closure of the `CloseablePath`, as you mentioned.

I think both directions can work so happy to follow your preference. I just wanted to bring both options to the table 🙂

**Comment by marcphilipp** [comment]
> > I think the validation should occur before creating the temporary directory, if possible.
> 
> Theoretically, the directory is created as soon as `TempDirFactory.createTempDirectory` returns. To perform the validation before the directory is created, we'd have to introduce some new API for `TempDirFactory` (related to [#3910 (comment)](https://github.com/junit-team/junit5/issues/3910#issuecomment-2260559403)). Or do you have something else in mind?

You're right. Let's not introduce a new API at this time.

> Indeed, that's already a gap caused by #3901, which I addressed separately in #3911.
> 
> > Therefore, I think we should not throw an exception from the `CloseablePath` constructor but validate in the `getPathOrFile` method.
> 
> If the `CloseablePath` constructor throws an exception, it would be handled similarly to #3911, i.e., with a try/catch that ensures the underlying factory is also closed in case a `PreconditionViolationException` is thrown by the temp directory validation. This way, no `CloseablePath` instance would be created, and no close handling would need to be in the `getPathOrFile` caller.

Shouldn't we also delete the `Path` returned from `TempDirFactory.createTempDirectory` if it did not throw an exception before closing the factory? In most cases, the latter should take care of the former but that's not necessarily the case.

> Of course, we can push this logic up to `getPathOrFile` and that will require explicit closure of the `CloseablePath`, as you mentioned.
> 
> I think both directions can work so happy to follow your preference. I just wanted to bring both options to the table 🙂

I'll leave the decision where to put the check up to you.

**Comment by scordio** [comment]
> Shouldn't we also delete the `Path` returned from `TempDirFactory.createTempDirectory` if it did not throw an exception before closing the factory? In most cases, the latter should take care of the former but that's not necessarily the case.

You're absolutely right 🤦 let me revise that in #3911.

**Comment by scordio** [comment]
Yes, I have time, I was waiting for #3920 🙂 I should be able to submit something by the end or tomorrow
