### ISSUE TITLE
Backport `JAVA_23` and `JAVA_24` `JRE` constants to `5.10.x`

### ISSUE THREAD

**Issue by snicoll** [junit-team/junit5#3918]
Please backport for testing Java 23 to `5.10.x` as Java 23 is around the corner and the only option AFAICS is to use `OTHER`.

**Comment by marcphilipp** [comment]
The plan is to release 5.11 next week. Therefore, no additional 5.10.x release is scheduled.

**Comment by sbrannen** [comment]
See also:

- #3930
- #3931

**Comment by marcphilipp** [comment]
@snicoll I think the escape hatch would be to document how to use a later version of JUnit with the Spring Boot version that's in maintenance mode, should users want to upgrade. We already have a [section for that in our User Guide](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-spring-boot) that Spring Boot's docs could link to. WDYT?

**Comment by snicoll** [comment]
I've raised this issue for our own needs. And for everyone who has a maintenance policy like ours.

Once could argue the current arrangement is quite artificial as all that's needed is a new enum value and everything would work from a JUnit perspective.

**Comment by sbrannen** [comment]
> One could argue the current arrangement is quite artificial as all that's needed is a new enum value and everything would work from a JUnit perspective.

We hope to address that in #3931.

**Comment by marcphilipp** [comment]
> I've raised this issue for our own needs.

@snicoll You mean for your own tests, right? Could you not use a different version of JUnit for the test sources than for the main sources?

**Comment by marcphilipp** [comment]
**Team decision:** Backport the enum constants to 5.10.x and 5.11.x.
