### ISSUE TITLE
Introduce DiscoverySelector for "fully qualified method name" with method parameters

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#392]
`org.junit.platform.commons.util.ReflectionUtils#loadMethod` assumes that methods don't declare arguments (see #331), but in the injected case it could declare `TestInfo`, like:

```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;

class FirstTest {
    @Test
    void myFirstTest(TestInfo testInfo) {}
}
```

If I start `myFirstTest` and then invoke `DiscoverySelectors.selectNames(Arrays.asList("FirstTest#myFirstTest"))`, it finds nothing.

## Related Issues

- #331  
- #332

**Comment by littleclay** [comment]
Yeah, it looks like it's due to the fact that in `ReflectionUtils#loadMethod` it parses out the package and class information by looking for `#` and then considers everything after that as part of the method name:

```
return Optional.of(classOptional.get().getDeclaredMethod(methodName));
```

It doesn't look for any parentheses `(` and then treat the information between them as types so that it can call:

```
return Optional.of(classOptional.get().getDeclaredMethod(methodName,parameterTypes...);
```

If it did support that in the select names (or via a different method like `DiscoverySelectors.selectName(name, argumentTypes)`) then you would be able to do something like this:
```
DiscoverySelectors.selectName("com.foo.bar.FooTest#foo(org.junit.jupiter.api.TestInfo)");
```

**Comment by sbrannen** [comment]
This is closely related to #331.

We will therefore address these issues together.

**Comment by sbrannen** [comment]
@akozlova, thanks for raising the issue.

I have updated the title and description accordingly.

**Comment by sbrannen** [comment]
@akozlova,

As an alternative to "name based" selection, you can always use a `Method` reference like this:

```java
Method method = FirstTest.class.getDeclaredMethod("myFirstTest", TestInfo.class);

MethodSelector selector = selectMethod(FirstTest.class, method);
```

Does that work for you?

**Comment by sbrannen** [comment]
FYI: `DiscoverySelectors.selectNames()

**Comment by sbrannen** [comment]
FYI: `DiscoverySelectors.selectNames()` has been deprecated in #409.

**Comment by sbrannen** [comment]
See also: #409, #410, #411

**Comment by sbrannen** [comment]
Since there is an alternative solution for this use case, I am removing the "bug" label and assigning this issue to M3.

**Comment by akozlova** [comment]
We don't have any means to populate method signatures to the tests vm yet. Would you provide any string based signature or should we serialize method signature with own means and search it in the Class ourselves? (we don't have Method, we have the text of a method only).

**Comment by sbrannen** [comment]
When we address _this_ issue in 5.0 M3, you will then have the support you're looking for.

For the time being, however, there is unfortunately no `DiscoverySelector` that allows you to select a method using String-based argument types.

Having said that, you could of course create your own `DiscoverySelector` which does exactly that using reflection (which is how we will eventually implement it anyway), and you could make that `DiscoverySelector` available in the test's VM.

**Comment by sbrannen** [comment]
@akozlova,

I'm not sure what your exact use case is. However, as an IDE I would assume that you executed a test plan and got back a `TestIdentifier` for `FirstTest#myFirstTest`. In that case, the **best practice** for IDEs and build tools is to obtain the UID via `testIdentifier.getUniqueId()` and then pass that to `DiscoverySelectors.selectUniqueId(String)`.

Can you please give that a try and let us know how it works out for you?

Cheers,

Sam

**Comment by sbrannen** [comment]
This issue is _blocked_ until #331 is resolved.

See `@Disabled` test in `OverloadedTestMethodTests`.

**Comment by sbrannen** [comment]
This issue is _blocked_ until #332 is resolved.

**Comment by sbrannen** [comment]
Thanks to the work performed in #332, #331, #411, the following use case is now supported.

```java

// Fully Qualified Method Name:
String fqmn = "org.example.FirstTest#myFirstTest(org.junit.jupiter.api.TestInfo)";

MethodSelector selector = DiscoverySelectors.selectMethod(fqmn);
```

I am therefore closing this issue.
