### ISSUE TITLE
Third-party usage of `JupiterTestEngine` in Jupiter Engine integration tests

### ISSUE THREAD

**Issue by scordio** [junit-team/junit5#3934]
I want to add integration tests to [`jimfs-junit-jupiter`](https://github.com/scordio/jimfs-junit-jupiter) with a testing strategy similar to [`TempDirectoryPerDeclarationTests`](https://github.com/junit-team/junit5/blob/main/jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java).

The motivation for needing such a testing strategy is to add a configuration property that tunes the configured Jimfs file system globally (see scordio/jimfs-junit-jupiter#1).

So far, I'm using `junit-platform-testkit` and I've taken inspiration from [`AbstractJupiterTestEngineTests`](https://github.com/junit-team/junit5/blob/main/jupiter-tests/src/test/java/org/junit/jupiter/engine/AbstractJupiterTestEngineTests.java), but I noticed that [`JupiterTestEngine`](https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/JupiterTestEngine.java) is declared for internal usage only.

What would you suggest for my use case? Would you consider declaring `JupiterTestEngine` for external usage, or should I create my custom `HierarchicalTestEngine`?

**Comment by sbrannen** [comment]
In the `spring-test` module of the Spring Framework, we use `org.junit.platform.testkit.engine.EngineTestKit.engine(String)` and supply `"junit-jupiter"` as the test engine ID.

By doing that, you don't need to reference the `JupiterTestEngine` directly, and that's the actual reason we introduced `EngineTestKit.engine(String)`.

Does that suit your needs?

**Comment by scordio** [comment]
Yes, that's perfect. Thanks!

**Comment by scordio** [comment]
@sbrannen one more question: not even [`JupiterEngineDescriptor.ENGINE_ID`](https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineDescriptor.java#L33) is meant to be used externally, right?

I imagine it's unlikely that the ID will ever change, and I see that `spring-test` [uses a string value everywhere](https://github.com/search?q=repo%3Aspring-projects%2Fspring-framework+%22junit-jupiter%22+language%3AJava&type=code&l=Java).

It's obviously not a cardinal problem 🙂 I'm just curious.

**Comment by sbrannen** [comment]
> @sbrannen one more question: not even [`JupiterEngineDescriptor.ENGINE_ID`](https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineDescriptor.java?rgh-link-date=2024-08-24T14%3A44%3A53Z#L33) is meant to be used externally, right?

That's correct.

The JUnit Team has no plans to ever change the IDs of the Jupiter and Vintage test engines, and I assume most other published test engines would not change their IDs randomly (like Spock, etc.).

FWIW, I _believe_ the IDs for JUnit's test engines are documented somewhere officially. If not, that would be something we could improve. 😉

**Comment by sbrannen** [comment]
> FWIW, I _believe_ the IDs for JUnit's test engines are documented somewhere officially.

Well... there's at least this sentence in the User Guide:

> For the sake of brevity, the following sections demonstrate how to test JUnit’s own `JupiterTestEngine` whose unique engine ID is "junit-jupiter".

**Comment by scordio** [comment]
Indeed, just found the same. Thanks again!
