### ISSUE TITLE
Add an option to `ExecutionMode` to run concurrently but wait for all test runs in the class to complete

### ISSUE THREAD

**Issue by k163377** [junit-team/junit5#3947]
It seems that `ExecutionMode.CONCURRENT` does not wait for everything in the class to complete before executing tests in other classes.
I was trying to parallelize a test for a query to retrieve from a database, but this behavior corrupted the test data and did not produce the expected results.
Is it possible to add a mode where execution within a class is parallelized, but execution of all tests within the class waits for completion?

---

As far as I have tried, it seems to be possible to achieve this behavior by giving `@Execution(ExecutionMode.CONCURRENT)` to the inner class and preparing an empty `AfterAll` in the outer class.
The following is the structure when reproduced (it was actually `Kotlin`).

```java
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class Foo {
  @Nested
  @Execution(ExecutionMode.CONCURRENT)
  class Bar {
    
  }
  
  @AfterAll
  public static void afterAll() {}
}
```

However, when this was done, it seemed that execution via `gradle` would result in a normal exit even though there were tests that had not yet been processed.
I am sorry that I have not been able to reproduce the problem at a minimum, but I am reporting this once in consideration of the possibility of a bug.
I have reproduced it at least with `5.10.2` and `5.10.3`.

**Comment by marcphilipp** [comment]
> Is it possible to add a mode where execution within a class is parallelized, but execution of all tests within the class waits for completion?

If you want to run all classes sequentially, but tests within a class concurrently, you can use the following configuration parameter settings:

```properties
junit.jupiter.execution.parallel.mode.default = CONCURRENT
junit.jupiter.execution.parallel.mode.classes.default = SAME_THREAD # default
```

> However, when this was done, it seemed that execution via `gradle` would result in a normal exit even though there were tests that had not yet been processed.

Are you using an include/exclude pattern in your Gradle config that caused the outer class to be excluded?

**Comment by marcphilipp** [comment]
@k163377 I'm afraid it's close to impossible to discuss this without a concrete example. If you could post a reproducer that illustrates the problem, I'd be happy to take a look.
