### ISSUE TITLE
Gradle version used by Travis CI does not match configured Gradle version

### ISSUE THREAD

**Issue by PeterWippermann** [junit-team/junit5#397]
The Gradle version [configured in the wrapper](https://github.com/junit-team/junit5/blob/6055beebc9de136a6a863de51ebac03c304e4ffb/gradle/wrapper/gradle-wrapper.properties#L6) is 2.14.
The version used by TravisCI is nightly-build of release 3 as you can see in [Travis' build log](https://travis-ci.org/junit-team/junit5/jobs/144558735).

I think it's a good practice to use the same version of the build tool in CI and locally.

**Comment by PeterWippermann** [comment]
If you decide to switch to the nightly builds: I took [these steps](https://gradle.org/gradle-nightly-build/) to update my local wrapper.

**Comment by sbrannen** [comment]
The Travis CI build is specifically set up to test against Gradle 3.0 snapshots, JDK 8, and JDK 9.

The [Jenkins build](https://junit.ci.cloudbees.com/job/JUnit5/), however, uses the Gradle wrapper configured in `build.gradle` and executes against JDK 8.

We currently have no plans to switch to Gradle nightly builds for Jenkins (i.e., the official CI builds) or local builds. I am therefore closing this issue as _invalid_.

**Comment by PeterWippermann** [comment]
Oh ok, I thought that Travis would be your only CI server.
Maybe you could link to your Jenkins in the [readme's CI section ](https://github.com/junit-team/junit5#continuous-integration-builds) as well?

**Comment by sbrannen** [comment]
Jenkins was already mentioned in the following section on code coverage, but you're right: we didn't have a status badge for Jenkins.

so... I just added it: https://github.com/junit-team/junit5#continuous-integration-builds

Cheers!
