### ISSUE TITLE
Support classpath scanning within JAR files

### ISSUE THREAD

**Issue by nilsga** [junit-team/junit5#399]
`DiscoverySelector.selectPackage` does not work when the package resides within a jar file. This is due to https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java#L122, since `listFiles` does not work for a "folder" within a jar file.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
@nilsga I've decided to only use the test you've provided in #400 (I cherry-picked your commit, see 2205313c19223ae05aa98928f270ae005b639378) and implement it using the `Path` API (as proposed in #466) so there's only one implementation for both cases.

Please take a look at the current [implementation](https://github.com/junit-team/junit5/blob/cbfdd3039a91578a09290d895621defc263bbbba/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java). Basically, it collects all base `URI` for a package, converts them into a `Path` based on their scheme and uses `Files.walkFileTree` for traversal.

Please confirm that this fix solves your problem, so we can close this issue.

**Comment by nilsga** [comment]
Looks good. The problem seems to be resolved with this fix.

**Comment by sbrannen** [comment]
Awesome! Thanks for letting us know it works for you.
