### ISSUE TITLE
Set up JUnit 5 build on Microsoft Windows

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#403]
## Status Quo

A bug reported in #398 made it apparent that the JUnit 5 build is currently not compatible with Microsoft Windows.

## Deliverables

- [x] Introduce a CI build that runs on Microsoft Windows.
  - [AppVeyor](https://www.appveyor.com/) may be a viable option, especially since it's free for open source projects.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
Build has been setup on AppVeyor and documented in README.md (cf. 898e2eeaf4be7f46b409532bf1b14d50226ac2b5): https://ci.appveyor.com/project/marcphilipp/junit5

**Comment by sbrannen** [comment]
Thanks! 👍
