### ISSUE TITLE
Machro

### ISSUE THREAD

**Issue by Plotomea82** [junit-team/junit5#4035]
SEGMENT/ed
END/joch

**Comment by sbrannen** [comment]
@Plotomea82, please experiment with GitHub features in your own repository.

**Comment by sbrannen** [comment]
> The work wasn't done right

@Plotomea82, I'm not sure what you mean by that, but unless you are contributing something or reporting something related to JUnit 5, please refrain from creating issues and posting comments in this repository.

Thanks
