### ISSUE TITLE
Upgrade to Spotless 2.0

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#404]
## Status Quo

Spotless 2.0 should fix issues regarding EOL characters on Windows (see https://github.com/diffplug/spotless/issues/23).

## Related Issues

- #398 

## Deliverables

- [x] Upgrade to Spotless 2.0 once it is released.

**Comment by nedtwigg** [comment]
Just FYI, Spotless 2.0 is now available.

I think right now you've got something like this:

```
spotless {
    ...
    lineEndings 'UNIX'
}
```

You shouldn't need to specify lineEndings any longer - it will automatically use the same line endings policy as git.

**Comment by sbrannen** [comment]
Hi @nedtwigg,

Thanks for the heads up and congratulations on releasing Spotless 2.0!

I just tried it locally, and it works fine.

As for removing the explicit `lineEndings` declaration, we do not currently have a custom `.gitattributes` file in place. So, please correct me if I'm wrong, but... my understanding is that the default settings (and search algorithm for custom line ending settings) in Spotless 2.0 won't help us unless we create such a custom `.gitattributes` file.

Can you please confirm the above assumption?

Cheers,

Sam

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
@nedtwigg, 

The latest build on Windows just passed.... _with_ the Spotless `lineEndings` configuration removed:

https://ci.appveyor.com/project/marcphilipp/junit5/build/101

So, maybe we can just assume it's working properly, ... but a confirmation would still be nice. 😉

**Comment by nedtwigg** [comment]
You do have a .gitattributes file:

https://github.com/junit-team/junit5/blob/master/.gitattributes, added in dc5e8753963928850b3092a456090b5e1560e981

and so everything is working properly.

If you didn't have a .gitattributes file, then git would check them out as `\r\n`, and if you have tests which rely on line ending (which I believe you do), then you'd have problems.  And you could tell spotless `lineEndings 'UNIX'`, but the problem then would be that the build would fail until you called `spotlessApply`.  And once you called `spotlessApply`, everything in the working tree would be marked dirty, so you had to tell spotless AND `.gitattributes`.

Before spotless 2.0, it was really important to synchronize git and spotless on the line ending.  Now they're always synchronized unless you go out of your way to manually specify a line ending.

**Comment by sbrannen** [comment]
@nedtwigg, well... you're totally correct!

I must be getting senile, since I'm the one who created that `.gitattributes` file. 😉 

Thanks for _reminding_ me,

Sam
