### ISSUE TITLE
Both `@BeforeAll`s with the same static method names in a parent class and its inherited class are called in JUnit 5.11, but not in JUnit 5.10

### ISSUE THREAD

**Issue by tomtongue** [junit-team/junit5#4052]
After upgrading to JUnit 5.11, if a testbase class has a **static**  method with the `@BeforeAll` annotation and its inherited testbase class also has the static method (with the same method name as its parent class) with the `@BeforeAll` annotation, both of the static methods with the `@BeforeAll` annotation are called. However, in Junit 5.10, only the 2nd static method with `@BeforeAll` is called. 

I would like to ask if it's intended, and if it's intended, is there any way to suppress calling the first static method with the `@BeforeAll` annotation?

## Steps to reproduce

Assuming the following class structure, the actual tests are in the `TestA` class.

```
abstract class TestBase (including @BeforeAll)
    <- abstract class Feature1TestBase (including @BeforeAll)
        <-  class TestA
```

When you run the tests in `TestA`, 
* In JUnit 5.11.1, a static method with `@BeforeAll` in the `TestBase` class is called, then the same name static method with `@BeforeAll` in the `Feature1TestBase` class is called.
* In JUnit 5.10, only a static method with `@BeforeAll` in the `Feature1TestBase` class is called, the static method in the `TestBase` class is NOT called.

The below shows more details:

### Code

`TestBase`:

```java
// TestBase
import org.junit.jupiter.api.BeforeAll;

public abstract class TestBase {
    @BeforeAll
    public static void beforeAll() {
        System.out.println("Run beforeAll in TestBase.");
    }

    public void testMethod() {
        System.out.println("Run testMethod in TestBase.");
    }
}
```

`Feature1TestBase`:

```java
import org.junit.jupiter.api.BeforeAll;

public abstract class Feature1TestBase extends TestBase {
    @BeforeAll
    public static void beforeAll() {
        System.out.println("Run beforeAll in Feature1TestBase.");
    }
}
```

`TestA`:

```java
import org.junit.jupiter.api.Test;

public class TestA extends ConcreteTestBase {
    @Test
    public void runTestA1() {
        testMethod();
    }
}
```

### Output

JUnit 5.11.1:

```java
Run beforeAll in TestBase.
Run beforeAll in Feature1TestBase.
Run testMethod in TestBase.
```

JUnit 5.10.5:

```
Run beforeAll in Feature1TestBase.
Run testMethod in TestBase.
```

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit 5.11.1 and JUnit 5.10.5 (`org.junit.jupiter:junit-jupiter:5.11.1` and `org.junit.jupiter:junit-jupiter:5.10.5`)
 - Build Tool/IDE: IntelliJ IDEA 2024.1.4 (Ultimate Edition)

## Deliverables
n/a

**Comment by sbrannen** [comment]
Hi @tomtongue,

Sorry to ask the obvious, but did you read the release notes for JUnit 5.11 before posting this question?

> I would like to ask if it's intended

This is intentional, and it's very well documented.

- https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.11.0-junit-jupiter-bug-fixes
- https://junit.org/junit5/docs/snapshot/user-guide/index.html#extensions-supported-utilities-search-semantics
- https://github.com/junit-team/junit5/wiki/Upgrading-to-JUnit-5.11

> and if it's intended, is there any way to suppress calling the first static method with the `@BeforeAll` annotation?

Yes, you can revert to "legacy" mode, which is also documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/index.html#extensions-supported-utilities-search-semantics).

In light of the above, I am closing this issue.

Regards,

Sam

**Comment by tomtongue** [comment]
@sbrannen Thanks so much for pointing these documents. Just one thing, I set the legacy semantics to true, but it seems not to work for those static methods. https://github.com/junit-team/junit5/blob/main/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java this code only has the legacy mode only for fields. Please correct me if I'm wrong.

**Comment by sbrannen** [comment]
> @sbrannen Thanks so much for pointing these documents. 

You're welcome

> Just one thing, I set the legacy semantics to true, but it seems not to work for those static methods. [`main`/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java](https://github.com/junit-team/junit5/blob/main/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java?rgh-link-date=2024-10-06T14%3A31%3A48Z) this code only has the legacy mode only for fields. Please correct me if I'm wrong.

The `useLegacySearchSemantics` flag is honored in two places, for fields and methods. Please search for use of that flag for details.

**Comment by tomtongue** [comment]
Thank you for sharing the flag (sorry, the flag also works for method as you're mentioning). Yes I was checking the flag, but if the method is "static", I believe it doesn't hide the static method in a parent class like the JUnit 5.10. So I'm wondering setting the legacy mode is not fully compatible with JUnit 5.10.
