### ISSUE TITLE
Give @Spy the same usability of @Mock

### ISSUE THREAD

**Issue by mirkoscotti** [junit-team/junit5#4069]
My request is to adapt the Spy annotation's target to {FIELD, PARAMETER} like its cousin Mock, instead of only FIELD.
Thanks.

**Comment by sbrannen** [comment]
I assume you are referring to Mockito annotations.

If so, please open an issue in the [Mockito issue tracker](https://github.com/mockito/mockito).

In light of that, I am closing this issue.
