### ISSUE TITLE
Does it make sense for a TestDescriptor to be both a test and a container?

### ISSUE THREAD

**Issue by orfjackal** [junit-team/junit5#407]
## Overview

In [Specsy](http://specsy.org/), it's not known before executing a test whether its TestDescriptor has children or not. The nested tests are discovered dynamically while the test is executed. This holds true also for the top-level test, which is the test class itself. Thus conceptually all TestDescriptors are both tests and containers. This caused a problem with IntelliJ IDEA test results (see [this comment](https://youtrack.jetbrains.com/issue/IDEA-148288#comment=27-1518123) and [its reply](https://youtrack.jetbrains.com/issue/IDEA-148288#comment=27-1518474)) and I had to do [a workaround](https://youtrack.jetbrains.com/issue/IDEA-148288#comment=27-1518757).

## Deliverables

This issue should be not closed until the following issues have been resolved.

- [ ] What does JUnit mean by the concepts of "test" and "container"?
- [ ] How should IDEs and other tools change their behavior based on those variables?
   - If they shouldn't change behavior, then why do the variables exist?
- [ ] What about the case of isTest()=false and isContainer()=false?
- [ ] What about defining them dynamically based on whether there are children? (I tried it. IntelliJ IDEA doesn't notice that the values change during test execution.)
- [ ] Would it be possible to remove both concepts, and just check whether a TestDescriptor has children?

**Comment by marcphilipp** [comment]
Thanks for reaching out! These are all valid questions that we've to discuss in the team. 

`isTest()` is intended to be used for reporting, e.g. the number of tests executed. A descriptor should either be a test or a container for tests.

Since you can't decide a priori: Have you tried adding the descriptors dynamically?

**Comment by orfjackal** [comment]
The descriptors are already added dynamically. That's the only way for Specsy to work, because all tests are discovered during the execution of their enclosing test. The "Syntax" and "Isolated Execution Model" chapters in http://specsy.org/documentation demonstrate nested tests (the Java version shows best how test registration is implemented as method calls).

**Comment by orfjackal** [comment]
If isTest and isContainer should be mutually exclusive, then how about making it an enum? Or just remove one of them. In that case all descriptors in Specsy would be tests and at the same time they would have 0 to many children. The test class would also be a test and not a container, because the root spec (the `run` method or constructor) is conceptually no different from the child specs (calls to `spec` method).

**Comment by bechte** [comment]
This issue is related with #508 and we might find a common solution. Therefore, I set it to blocked, until #508 is solved or closed.

**Comment by sbrannen** [comment]
Slated for M4 as a follow-up to #508.

**Comment by sbrannen** [comment]
PR #720 addressed the issue regarding "four possible boolean states for `isTest()` and `isContainer()`" for `TestDescriptor`; however, the issue still remains for `TestIdentifier`.

@sormuras, would you be willing to submit a similar PR to address the "4 boolean states" issue for `TestIdentifier` as well?

**Comment by sormuras** [comment]
Sure. Is `TestIdentifier` allowed to use the same enumeration type?

**Comment by sbrannen** [comment]
> Sure. Is TestIdentifier allowed to use the same enumeration type?'

Well, that all depends on the dependency graph between the Maven artifacts. 😛 

All kidding aside, yes, I think the semantics should be identical with the same (or an equivalent) enum.

**Comment by sbrannen** [comment]
FYI: I have revised the description of this issue to include a _Deliverables_ section.

**Comment by sbrannen** [comment]
> Sure. Is `TestIdentifier` allowed to use the same enumeration type?'

But then it would likely make more sense to make the `Type` enum a top-level class.

**Comment by marcphilipp** [comment]
There's now the `Type` enum that gets rid of invalid cases, such as container == false and test == false. In addition, a test descriptor may now state that it will eventually register dynamic tests (see #508).
