### ISSUE TITLE
When only the RepeatedTest method is included in the unit test, BeforeAll is executed after all the methods have been executed in a different order than expected

### ISSUE THREAD

**Issue by GaulleGL** [junit-team/junit5#4071]
JUnit5 version:5.11.1
code:
```java
class HelloWorldTest {

    @BeforeAll
    public static void beforeAll() {
        System.out.println("BeforeAll...");
    }

    @RepeatedTest(2)
    void test() {
        System.out.println("test execute");
    }

    @RepeatedTest(2)
    void test1() {
        System.out.println("test1 execute");
    }

    @AfterAll
    public static void afterAll() {
        System.out.println("AfterAll...");    }
}
```
Console output:
test execute
test execute
test1 execute
test1 execute
BeforeAll...
AfterAll...

**Comment by marcphilipp** [comment]
I can confirm that the console output looks like that when executing in IntelliJ IDEA. However, changing the code to include timestamps and sleeps, the shown output is the following:
```
15:35:59.260741054 - test execute
15:35:59.368766545 - test execute
15:35:59.472213945 - test1 execute
15:35:59.574471085 - test1 execute
15:35:59.141689507 - BeforeAll...
15:35:59.677100729 - AfterAll...
```

As you can see, `@BeforeAll` method is clearly executed prior to running any (repeated) test.

Thus, this seems to be a bug in IntelliJ IDEA. In fact, a similar issue was reported last week by @wind57 in #4047.

@GaulleGL @wind57 Could one of you please raise an issue directly in the [IntelliJ IDEA issue tracker](https://youtrack.jetbrains.com/issues?q=project:%20%7BIntelliJ%20IDEA%7D)?
