### ISSUE TITLE
Release Bug-Fixes for Milestone 1

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#408]
M1 has a couple of bugs that might have a detrimental effect on early adopters' opinion of JUnit 5 (#384, #390, #396, #402). It is not unlikely that more will be found.

A bug-fix release for M1 could prevent this.

With an M1 release branch it should be easy to cherry pick the fixes (as long as they apply well) into that branch and occasionally release new versions, e.g. as M1.1. This branch would of course also have to be covered by CI.

**Comment by sbrannen** [comment]
Thanks for the suggestions.

We have in fact already decided to release M2 ahead of schedule due to the number of bugs found/fixed since M1. M2 will then be reduced in scope with most of the issues currently assigned to M2 moved to M3.

So there won't be a need for M1.1. 😉 

In light of that I am closing this issue.

> It is not unlikely that more will be found.

Yes.... we _hope_ so!

**Comment by nicolaiparlog** [comment]
My personal assumption was that a milestone is something rare and noteworthy that brings new features and possibly breaking changes to the table. At the same time a regular uncovering of small bugs creates a constant demand for new releases.

I recommend not to conflate these two scenarios because then API breaking changes can not be bottled up until a new coherent state is reached. Instead they have to be released early and often, undermining the API stability M1 was supposed to guarantee. Tool developers might come into the situation to chose between updating their code or living with bugs in JUnit 5.

Release branches on the other hand would guarantee that bug fixes can be released very often (basically after each fixed bug) without much ado and that all M1.x releases are perfectly compatible. It also makes it easier to spot the more revolutionary releases, in this case M2, M3, ...
