### ISSUE TITLE
Create/Migrate Tests for project 'junit-launcher'

### ISSUE THREAD

**Issue by bechte** [junit-team/junit5#41]

**Comment by jlink** [comment]
`junit-launcher` has an almost 100% line coverage. The one thing I found missing are microtests for the diverse filter types in `TestDiscoveryRequestBuilderTests`.

**Comment by jlink** [comment]
Except LoggingListener (which is not used anywhere) junit-launcher seems reasonably tested.
`TagFilter` has an issued of its own (#131).
