### ISSUE TITLE
Document bug fixes and changes in 5.0 M2 change log in User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#412]
## Deliverables

- [x] Document all issues and pull requests associated with M2 in the User Guide.
- [x] Link to all issues and pull requests closed in conjunction with M2 in the User Guide
  - https://github.com/junit-team/junit5/milestone/4?closed=1

**Comment by sbrannen** [comment]
_in progress_, using:

```
git --no-pager log r5.0.0-M1..HEAD --pretty=format:'- %s' --reverse > changelog.txt
```

**Comment by sbrannen** [comment]
All bug fixes and changes thus far have been documented in the change log; however, I'm leaving this issue _Open_ in case further work such as #401 is completed before 5.0 M2 is released.

**Comment by mmerdes** [comment]
I am closing this issue as there are no other issues left which could be resolved and documented.

**Comment by sbrannen** [comment]
Reopening to document latest changes and bug fixes in M2.

**Comment by sbrannen** [comment]
Add _Deliverables_ section.

**Comment by sbrannen** [comment]
_in progress_
