### ISSUE TITLE
Rename new ParameterizedTest attributes to avoid confusion

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#4137]
> With #3708 (PR #4045) adding `argumentCountValidation` to `@ParameterizedTest`, I feel like there is a bit lack of clarity for users about what `requireArguments` does compared to `argumentCountValidation`. Specifically, I think it's not very clear which of these applies to arguments within an argument set and which applies to argument sets, if that is even the right wording.
> 
> @marcphilipp since you worked on both PRs, what's your opinion on this?
> Maybe, it'd make sense to rename `requireArguments` to `requireArgumentSets` and improve the docs? Or it's not that big of a deal. I'm not sure.
> 
> For context these are the two fields in  `@ParameterizedTest`: https://github.com/junit-team/junit5/blob/490e663244d506223d9e7b2aa1864576e44446cd/junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java#L295-L325

 _Originally posted by @JonasJebing in [#1477](https://github.com/junit-team/junit5/issues/1477#issuecomment-2482949332)_

## Deliverables

- [ ] Rename one or both attributes to make their effect clearer

**Comment by Anmavel** [comment]
Hi, can i work on this issue? :)

**Comment by juliette-derancourt** [comment]
Hey @Anmavel, I just assigned the issue to you! :)

**Comment by sormuras** [comment]
Have fun hacking @Anmavel !

**Comment by JonasJebing** [comment]
> **Team decision:** Rename `ParameterizedTest.requireArguments` to `allowZeroInvocations` (and change default to `true`)

@marcphilipp I think there's a typo. Shouldn't it be "change default to `false`"?
https://github.com/junit-team/junit5/blob/c96feb2cfa26e7377cc2e3b9de2b57d1d1a2356c/junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java#L307
