### ISSUE TITLE
Support @ExtendWith on fields

### ISSUE THREAD

**Issue by slu-it** [junit-team/junit5#416]
## Overview

**Is it planned for JUnit 5 to discover composed `@ExtendWith` annotations on fields?**

As far as I can see (from Milestone 1) they are only discovered in case they are used on types or methods.

For projects like Mockito it would be useful to also discover extension by analyzing field annotations.

**Example:**

``` java
// The following explicit declaration would become unnecessary.
// @ExtendWith(MockitoExtension.class)
public class MyServiceTest {

    @Mock
    FooService fooService;

    @InjectMocks
    MyService cut;

    @Test
    void testSomething() {
        ....
    }

}
```

In case `@Mock` and `@InjectMocks` were to be changed to composed annotations declaring `@ExtendWith(MockitoExtension.class)`, they could simply be used without having to declare the extension for each test class.

## Related Issues

- #497
- #506 
- #864 

## Deliverables

- [ ] Support registration of extensions on fields with the desired extension classes supplied via `@ExtendWith(...)`.
  - This is analogous to the current support for declaring `@ExtendWith` on classes and methods.

**Comment by sbrannen** [comment]
Discovery of extensions on fields is something we have in fact considered, but the feature is not currently planned. So I'll put it in the backlog now.

Thanks for raising the issue.

**Comment by sbrannen** [comment]
Overhauled this issue's description by introducing _Status Quo_, _Proposal_, and _Deliverables_ sections with a new focus on _programmatic_ extension registration via fields.

**Comment by sbrannen** [comment]
Currently slated for M3.

**Comment by sbrannen** [comment]
**Update**

The description of this issue has been returned to its original focus.

Support for registering extensions programmatically will be addressed in #497.

**Comment by sbrannen** [comment]
@slu-it, in light of #497, is this issue still relevant?

**Comment by slu-it** [comment]
Hi @sbrannen,

I think it is still relevant (as in not resolved) because #497 does not address the described usecase (`@Mock` without having to declare the corresponding `MockitoExtension`). In cases like that, the annotated field is not itself an extension implementation but rather something the extension should act upon.

But since I did not feel much pain regarding this in the past years, I can't speak to how important it really is. I just would find it useful.

**Comment by sbrannen** [comment]
> In cases like that, the annotated field is not itself an extension implementation but rather something the extension should act upon.

Indeed, that is something different. Sorry for overlooking that.

In any case, I am closing this as superseded by #1836.

If you feel that is inappropriate, please provide further feedback.

Thanks!

**Comment by sbrannen** [comment]
Please note that this feature will be delivered in JUnit 5.8.

See:

- #864 
- #2680
