### ISSUE TITLE
M1: Maven Central

### ISSUE THREAD

**Issue by mfulton26** [junit-team/junit5#418]
I can only find the alpha in maven central. Will M1 be added anytime soon? Thanks!

**Comment by smoyer64** [comment]
Check under the following groups:

-   org.junit.jupiter
-   org.junit.platform
-   org.junit.vintage

More information can be found in the M1 release notes:

http://junit.org/junit5/docs/current/user-guide/#release-notes-5.0.0-m1

**Comment by mfulton26** [comment]
Silly me. Thank you!

**Comment by smoyer64** [comment]
No problem ... M2 should be available any day!
