### ISSUE TITLE
A restricted method in java.lang.System has been called

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#4182]
https://github.com/junit-team/junit5/actions/runs/12211323266/job/34068453967?pr=4181#step:7:506
```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/runner/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/native-platform-0.22-milestone-26.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```

## Steps to reproduce

Run build on JDK 25

## Deliverables

- [ ] Update to versions not loading native code or use `--enable-native-access=ALL-UNNAMED`

**Comment by marcphilipp** [comment]
This is a coming from Gradle so there's nothing we can do about it. I'm sure they're already aware because it is also printed on JDK 24. I think we can close this issue since we're keeping the version of Gradle we're using up-to-date already.

**Comment by marcphilipp** [comment]
I've verified it originates in Gradle and opened an issue:
https://github.com/gradle/gradle/issues/31625

**Comment by sormuras** [comment]
For the record: https://youtrack.jetbrains.com/issue/IDEA-363985
