### ISSUE TITLE
Lifecycle Documentation?

### ISSUE THREAD

**Issue by littleclay** [junit-team/junit5#426]
Is there anywhere that explains the "lifecycle" so to speak of a JUnit Jupiter test run? I know the JavaDocs exist for each class, etc, and the user guide gives usage on how to write extensions and tests but I haven't seen anything that discusses the detailed breakdown of the component parts (e.g. test, test container, extensions, engines, etc) and their lifecycle (e.g. how long does each portion "live", when is it instantiated and by what, etc). I am sure some of this is in flux as the milestones are completed and JUnit Jupiter is finalized, but wasn't sure if there was any existing documentation that went over all of that yet.

I also am not sure if this is the right place to ask this? I thought about asking on the stack exchange site with the JUnit5 tag, but again wasn't sure if *that* was the right place :-) ... if it is, please let me know and I'll ask there instead. Thanks!

**Comment by marcphilipp** [comment]
Sure, this is one of the right places to ask this. Thanks for doing so! :-)

There's definitely room for improvement wrt. documenting the lifecycles. Do you have specific questions we can help you with?

**Comment by sbrannen** [comment]
These are all very valid questions, and we in fact already have an issue to address this topic: #149.

I am therefore closing this issue as a _duplicate_.

Cheers!

**Comment by sbrannen** [comment]
If you have additional questions or input, please share them in #149.

**Comment by littleclay** [comment]
Thanks! Sorry that I didn't see #149 ... that'll teach me to search the existing issues more fully next time ;-P

**Comment by sbrannen** [comment]
No worries.

The previous title for #149 was "Document exception handling extension invocation relative to other extensions". So that's likely why it didn't jump out at you as the same topic. I've since updated the title for #149 to reflect the intended scope of the issue.

**Comment by littleclay** [comment]
Cool. I also put one of my specific questions in the comments of that issue ( #149 ). Thanks again!
