### ISSUE TITLE
Enhance DefaultLauncherTests for null conditions in the DummyTestEngine.

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#430]
Pull request #429 eliminates an NPE thrown when the TestEngine's discover() method returns null.  Looking at the DefaultLauncherTests, it appears that the DummyTestEngine should be enhanced so that the engineDescriptor can be forced to null.  Tests for the correct exception can then be added to the DefaultLauncherTests.

If this seems like the correct course of action, feel free to assign it to me (I was going to include it with the pull request but I'm just starting to learn the platform test code).

**Comment by sbrannen** [comment]
Oops.

I totally missed this issue.

Consequently, I've actually already addressed both of these topics in c88bd40fc19d16022abd5ee9bd4cc287b67afff9 and d360441e81c7b0d91f08456e8b83ae4f50f1fc3b.
