### ISSUE TITLE
Support simple variable expansion in display names

### ISSUE THREAD

**Issue by mmerdes** [junit-team/junit5#432]
The integration of a full-blown expression language for generating the strings of display names might not really be necessary. A simple alternative would be to allow for the expansion of those variables that are injected by the current method argument `ParameterResolver`. The scope of this proposal is intentionally limited to calling the `toString()` method on said arguments and replacing the variable reference in the `DisplayName` value with this output.

**Comment by marcphilipp** [comment]
Team decision: Since parameters are not available during discovery and there's currently no way to signal a different display name for an existing test descriptor, we will close this ticket for now.

**Comment by sbrannen** [comment]
Effectively superseded by #1154
