### ISSUE TITLE
Add integration tests for Maven Surefire provider

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#435]
In order to ensure that the Maven Surefire provider is working correctly we need a basic set of integration tests that use an actual POM, execute tests via Maven, and verify their results.

**Comment by lutovich** [comment]
Hello @marcphilipp,

I've made some initial progress on such tests and it would be nice to get some feedback.
Commit https://github.com/lutovich/junit5/commit/6ea1ebc690e840464381abfb93311ccfc2b122a3 adds a simple IT with real `pom.xml` that checks maven exit code and test execution results.

The main complication is that ITs like this need `junit-platform-surefire-provider` jar to include into the pom. Same applies to transitive dependencies. Prototype scans classpath and creates `pom.xml` with needed jars using `system` scope and `systemPath`. This can probably be made prettier by using some template engine for `pom.xml` generation. Also IT lives in `platform-tests` module to be able to access surefire provider jar.

Please let me know what you think about this approach. Thanks!

**Comment by marcphilipp** [comment]
Thanks, that looks like it has been a lot of work! Maybe we should really think about a plan to submit a pull request to Surefire soon so we can leverage their integration test infrastructure. But for now I think you're heading into the right direction. 👍

**Comment by lutovich** [comment]
@marcphilipp thanks for the feedback. I'll try to shape up a PR this week.

**Comment by britter** [comment]
See #31 : We'll be using the infrastructure already provided by the Surefire Project.

**Comment by lutovich** [comment]
@britter @marcphilipp ok, this sounds like a good plan. I'll stop working on this task than.
Here is my latest version of ITs: https://github.com/lutovich/junit5/commit/6e94d9d6d5df985b5cb1218788ac04dbab093eca and it is not really pretty. Plus I was not able to figure out how to retrieve surefire events to assert on them.

**Comment by britter** [comment]
Please see apache/maven-surefire#18

**Comment by britter** [comment]
apache/maven-surefire#118 has been fixed. The Apache Maven team has set up a branch in the surefire repository for working on the surefire integration. I'm going to add more integration tests. I'm currently not sure when/how we're going to handle the contribution of the provider implementation. I'll comment again, when I have a better overview of surefire.

**Comment by marcphilipp** [comment]
@britter Awesome, thanks for your perseverence!

**Comment by marcphilipp** [comment]
Will be addressed within Surefire.
