### ISSUE TITLE
Relocate @API to a stand-alone module

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#436]
## Overview

The `@API` annotation may better serve the community at large if it is moved from `junit-platform-commons` to a stand-alone module.

## Related Issues
- #144 
- #317 
- #375 

## Deliverables

- [x] Refactor the `@API` annotation so that it has the following attributes:
   - [x] `status: Status` (used to be `value`)
   - [x] `since: String` (version the status was last changed, e.g. `"5.0.0"`, defaults to `""`)
   - [x] `consumers: String[]` (list of package patterns for intended consumers, defaults to `{"*"}`)
- [x] Rename `Status` constants to align with industry standards for enum constants.
- [x] Set `since` attribute across the JUnit 5 code base.
- ❌  Set `consumers` attribute across the JUnit 5 code base.
   - to be addressed in #1054 
- [x] Move `@API` to a stand-alone project on GitHub.
- [x] Use `@API` from the `@API Guardian` project and delete `@API` from `junit-platform-commons`.

**Comment by sbrannen** [comment]
Currently slated for 5.0 M5 in order to be discussed amongst the team.

**Comment by marcphilipp** [comment]
The new `@API` annotation will have the following attributes:
- `status: Status` (used to be `value`)
- `since: String` (version the status was last changed, e.g. `"5.0.0"`, defaults to `""`)
- `consumers: String[]` (list of package patterns for intended consumers, defaults to `{"*"}`)

**Comment by sbrannen** [comment]
**Update:** `@API` has been moved to the following new repository.

https://github.com/apiguardian-team/apiguardian

Note, however, that artifacts are currently not published.

**Comment by sbrannen** [comment]
All `@API` related tasks have now been completed in preparation for 5.0 GA.
