### ISSUE TITLE
Introduce support for selecting packages, classes, and methods in ConsoleLauncher and Gradle plugin

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#437]
## Overview

#410 removed the generic name based selectors previously used by the `DiscoveryRequestCreator`.

Consequently, that deleted code has been relocated to `DiscoveryRequestCreator` as a private, internal implementation detail; however, this is only a temporary solution.

This issue therefore aims to provide a robust solution that will accommodate support for additional test artifact types other than Java based packages, classes, and methods.
## Related Issues
- #313 
- #452 
- #453 
- #468
## Deliverables
- [x] Introduce explicit support for selecting packages in `ConsoleLauncher` via `-p` |  `--select-package`
- [x] Introduce explicit support for selecting packages in the JUnit Platform Gradle plugin
- [x] Introduce explicit support for selecting classes in `ConsoleLauncher` via `-c` |  `--select-class`
- [x] Introduce explicit support for selecting classes in the JUnit Platform Gradle plugin
- [x] Introduce explicit support for selecting methods in `ConsoleLauncher` via `-m` |  `--select-method`
- [x] Introduce explicit support for selecting methods in the JUnit Platform Gradle plugin

**Comment by marcphilipp** [comment]
I've updated the issue's description and removed the `java` part of the long options to be in sync with our decision wrt. DiscoverySelectors for packages, classes, and methods.

**Comment by marcphilipp** [comment]
Done.
