### ISSUE TITLE
Document and test project 'junit-engine-api'

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#44]
- [ ] Document the intended usage of AbstractTestDescriptor 
- [ ] Document TestPlan, Request classes and Source classes
- [x] Write tests for HierarchicalTestExecutor

**Comment by bechte** [comment]
I will take care of adding documentation.

**Comment by marcphilipp** [comment]
Not *in progress* right now.

**Comment by sbrannen** [comment]
I am closing this issue since the documentation sub-tasks have been moved to #234.

**Comment by marcphilipp** [comment]
👍
