### ISSUE TITLE
Populate release notes for 5.0 M3

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#442]
## Deliverables
- [ ] Document all issues and pull requests associated with M3 in the User Guide.

The following can be used as a starting point:

```
git --no-pager log r5.0.0-M2..HEAD --pretty=format:'* %s' --reverse | grep -vi 'Polish' > changelog.adoc
```

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I went through all issues assigned to M3 and made sure they are documented in the release notes, if relevant.

**Comment by sormuras** [comment]
**5.0 M3** _done_ by November 30, 2016 **100% complete**

Great way to start December. 🎁

**Comment by marcphilipp** [comment]
Indeed, finally! 🎉 😊
