### ISSUE TITLE
Can the JUnit 5 logo be used in presentations?

### ISSUE THREAD

**Issue by goerge** [junit-team/junit5#443]
I can't find the JUnit 5 logo (http://junit.org/junit5/assets/img/junit5-logo.png) in any github repo of the junit-team.
The footer on the JUnit 5 homepage (http://junit.org/junit5) says:
> Copyright © 2016 The JUnit Team

The questions is: Am I allowed to use the JUnit 5 logo in (possible commercial) presentations?

**Comment by marcphilipp** [comment]
We should think about a CC license for it. However, I believe including it in a presentation would be fair-use anyway. So, feel free to include it in your presentation!

**Comment by goerge** [comment]
Thanks a lot.

**Comment by dmgorbunov** [comment]
@marcphilipp Hello! What would you say about company website mention?
We developed a tool that can parse JUnit annotations (so it's, like, "JUnit-compatible"). Is that also an example of fair use?

**Comment by marcphilipp** [comment]
@dmgorbunov Sorry for the late reply. I think that should be ok. Is the website available in the meantime by any chance?
