### ISSUE TITLE
Introduce mechanism for asynchronous tests to signal test completion

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#444]
For example, a test method that spawns asynchronous tasks in the background may not have completed when the execution the test method completes. It would therefore be beneficial if such a test method had a mechanism for signaling that it was complete in order for _verify_ methods to be invoked at the appropriate time.

**Comment by sbrannen** [comment]
@nebhale, you might be somehow interested in this issue, says a little birdie.

**Comment by sbrannen** [comment]
[Awaitility](https://github.com/awaitility/awaitility) can also be of interest to users wishing to test asynchronous code.

**Comment by ttddyy** [comment]
That's interesting.
One idea is to create a flag variable accessible from test (maybe inject variable to the test method, some static method, etc.)
When test is finishing, check the flag, and if the flag says not yet, then wait until the flag says ok to finish.

**Comment by ttddyy** [comment]
inject something like this:
```java
public class WaitContext {
  private Duration timeout;
  private boolean done;

  ...
}
```

**Comment by ttddyy** [comment]
I created a junit5 extension, `WaitExtension`.
Since there is no centralized location to host junit5 extensions, I put it to my repo for now.
https://github.com/ttddyy/junit5-extension-wait

**Comment by sbrannen** [comment]
@ttddyy, that looks interesting. Thanks for investigating the possibilities!
