### ISSUE TITLE
Change visibility of junit-vintage to get other test engines running

### ISSUE THREAD

**Issue by aaschmid** [junit-team/junit5#445]
Hi junit-team,

I am the maintainer of https://github.com/TNG/junit-dataprovider and in order to be able to migrate to the new JUnit5 engine for new test cases in the future I would like to provide a test engine for it. This would make it possible to migrate step by step.

To achieve that I created the following:

* The branch "issue75-junit5-support-by-only-extend-code" in my forked repo "aaschmid/junit5" with one commit which extends the visibility of various junit-vintage classes and methods, see https://github.com/junit-team/junit5/compare/master...aaschmid:issue75-junit5-support-by-only-extend-code?expand=1

* The junit-dataprovider test engine and the corresponding code, see https://github.com/TNG/junit-dataprovider/compare/issue75-junit5-support-by-only-extend-code?expand=1

Now here are my questions:

1. Are you OK with extending your (internal) APIs like that or is there an easier way which I completely overlooked? (Even if could think about better solutions to achieve what I need but this can be discussed after you do not see another solution and would be OK with extending visibility ...)

2. As I used ```@Test``` and ```@UseDataProvider``` for annotating my test cases, obviously the junit-vintage engine also tries to execute the test cases and fails with the error "java.lang.Exception: Method testAdd should have no parameters ..." due to "BlockJUnit4ClassRunner" and its validations. Can you think of a solution or do I have to create a custom runner too? (Please note that this would require even more classes and methods to be visible but it would work as I have already tested it :-) If you want to see the code to compare or so, just let me now).

I appreciate every help and your great work so far. 

Thanks,
Andreas

**Comment by aaschmid** [comment]
Of course one could always start a new class for "junit-jupiter" test cases but I like the idea to even mix it up and therefore migrate smoothly :-)

And also depending on your ```@DynamicTest``` feature set, I want to provide the "junit-dataprovider" as "junit-jupiter" extension or not ... (I could also think about migrating my features to the core ;-) )

**Comment by marcphilipp** [comment]
Hmm, we're certainly not comfortable with you extending our internal APIs because we might need to change them in the future...

We still have parameterized tests on our agenda (see #17). When we get to implementing it, we will certainly provide an Jupiter extension point for it so you don't have to write a new engine to provide a new way to supply data. However, we're not there, yet.

**Comment by aaschmid** [comment]
Hi @marcphilipp,

hm ... I am ok with code changes in the future if I use an internal API. Also I understand that you want to define the API. Does that mean I just have to wait for the above mentioned Jupiter extension point?

If yes, can you tell me more about your plans / concepts / integrations for parameterized tests such that I can implement / help implementing it and getting it sooner?

Cheers,
Andreas

**Comment by aaschmid** [comment]
I now created my own test engine. It's currently in a beta state, see https://github.com/TNG/junit-dataprovider/tree/issue75-second-try. Filtering is not implemented and it is build from scratch. A lot of code is quite similar to junit-vintage.

**Comment by sbrannen** [comment]
Thanks for the feedback.

Closing this issue.
