### ISSUE TITLE
Cannot migrate Rule to junit 5

### ISSUE THREAD

**Issue by tsachev** [junit-team/junit5#449]
I am using following junit 4 rule

https://github.com/google/compile-testing/blob/master/src/main/java/com/google/testing/compile/CompilationRule.java

What it basically does is it spins up a java compiler against dummy source file and provides to it a simple annotation processor. This way it gets references to `Types` and `Elements` from the processing environment that can be used by the test, and also executes the test statement within its `process` method.
The new extension model currently does not provide a way to execute the test method within another execution context (as a callback).
There should be a way to achieve something like this. The hard thing here is that elements and types, I believe are only available in the context of the annotation processor (i.e. the test method should be executed within the `process` of the annotation processor.

**Comment by marcphilipp** [comment]
Thanks for reporting this issue! 👍 

This has been discussed but not decided in #157. Closing this issue as duplicate.
