### ISSUE TITLE
Improve interface of TestPlanSpecification

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#45]
- [x] Change Launcher API to just use `TestSpecificationElement` (or better name) as marker interface, and make the collection of elements accessible to engines, as a group or by specific type
- [x] Build DSL on top of launcher API in separate module `junit-testplan-dsl`
- ~~Change `filterWith()` from `Predicate<TestDescriptor>` to `Predicate<TestIdentfier>`~~
- ~~`TestPlanSpecification` must implement `Serializable`~~
- ~~`TestPlanSpecification` must be immutable~~

**Comment by bechte** [comment]
I will investigate this during #29 .

**Comment by marcphilipp** [comment]
We should also change `filterWith()` from `Predicate<TestDescriptor>` to `Predicate<TestIdentfier>`.

**Comment by jlink** [comment]
Team decision:
- Change launcher API to just use `TestSpecificationElement` (or better name) as marker interface, make collection of elements accessible to engines, as a group or by specific type.
- Build DSL on top of launcher API in separate module 'junit-testplan-dsl'

**Comment by marcphilipp** [comment]
I've updated the task description with our decisions from this afternoon and added two items regarding serializability and immutability.

**Comment by bechte** [comment]
Implemented and merged into master, see pull request #108.

The following tasks are covered within issue: #116 
- Change filterWith() from Predicate<TestDescriptor> to Predicate<TestIdentfier>
- TestPlanSpecification must implement Serializable
- TestPlanSpecification must be immutable

Therefore, I close this issue.
