### ISSUE TITLE
Introduce support for selecting classpath resources in ConsoleLauncher and Gradle plugin

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#452]
## Overview

This issue builds on the work performed in #301.
## Related Issues
- #437
- #453 
- #468
## Deliverables
- [x] Introduce support for selecting classpath resources in `ConsoleLauncher` via `-r` |  `--select-resource`
- [x] Introduce support for selecting classpath resources in the JUnit Platform Gradle plugin

**Comment by marcphilipp** [comment]
_in progress_
