### ISSUE TITLE
Introduce support for selecting files and directories in ConsoleLauncher and Gradle plugin

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#453]
## Overview

This issue builds on the work performed in #123.
## Related Issues
- #437
- #452 
- #468
## Deliverables
- [x] Introduce support for selecting files in `ConsoleLauncher` via `-f` |  `--select-file`
- [x] Introduce support for selecting directories in `ConsoleLauncher` via `-d` |  `--select-directory`
- [x] Introduce support for selecting files in the JUnit Platform Gradle plugin
- [x] Introduce support for selecting directories in the JUnit Platform Gradle plugin

**Comment by marcphilipp** [comment]
_in progress_
