### ISSUE TITLE
Introduce query language for selecting tags

### ISSUE THREAD

**Issue by ondrejlerch** [junit-team/junit5#454]
Let's imagine that our tests are annotated with multiple tags such as fast / slow, priority1 / priority2, stable / unstable, integration / unit, subproject1 / subproject2.

If I am not mistaken:

``` java
tags {
        include 'fast', 'priority1', 'stable', 'integration', 'subproject1'
}
```

will run 'fast' OR 'priority1' OR 'stable' OR 'integration' OR 'subproject1'

I would like to be able to specify:

``` java
tags {
        include 'fast AND priority1 AND stable AND integration AND subproject1'
}
```

or even:

``` java
tags {
        include 'fast AND (priority1 OR priority2) AND NOT unstable AND integration AND (subproject1 OR subproject2)'
}
```

Syntax can be different but you get the idea.

Alternatively, it would be great if there is simple Java API which would help us create such queries. Benefit of Java API would be that queries could be typesafe, autocompleted by IDE and dynamic.

PS: let's make JUnit 5 great!

**Comment by marcphilipp** [comment]
Regarding the Java API: It's already possible to add custom `PostDiscoveryFilters` to `LauncherDiscoveryRequests`. However, there's no way to specify such a filter through Gradle, Maven or the ConsoleLauncher, yet.

While I can see that such a query language might be useful in some cases, I honestly don't want to implement and maintain it.

@junit-team/junit-lambda What do you think?

**Comment by smoyer64** [comment]
I was just sitting down to allow the junit-platform-surefire-provider to specify JUnit 5 tags through the <properties> configuration tag.  Expect a PR in the next couple days.  Should I consider other types of filters at the same time?

**Comment by ondrejlerch** [comment]
Hi Steve,

Filters types that I described (AND, OR, NOT, brackets) are enough for our purposes. I don't know about any other types that you should consider.

More members of my team find "tag queries" feature very useful. We currently miss it in JUnit / TestNG & Maven Surefire Plugin.

To avoid misunderstanding (since I am not expert on junit-platform-surefire-provider) could you show me example how Maven "tag query" would look like if your PR is approved?

Would it be something like:
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<configuration>
		<groups>fast AND (priority1 OR priority2) AND NOT stable</groups>
	</configuration>
</plugin>
or something else?

Thanks for your effort!

Ondrej

**Comment by sbrannen** [comment]
I agree with @marcphilipp:

> While I can see that such a query language might be useful in some cases, I honestly don't want to implement and maintain it.

In my opinion, a query language for tags is beyond the current scope of the project; however, if somebody wishes to give it a try and submit a PR, we could then consider including it (depending on the complexity, etc.).

**Comment by sbrannen** [comment]
@smoyer64,

> Should I consider other types of filters at the same time?

Yes.

The JUnit Platform Maven Surefire Provider should actually align with the support for filters provided by the JUnit Platform Gradle Plugin, which currently includes support for _includes_ and _excludes_ for tags and engines.

**Comment by ondrejlerch** [comment]
@marcphilipp @sbrannen 
Could you give me example how to specify something like `fast AND (priority1 OR priority2) AND NOT stable` using `PostDiscoveryFilters` and `LauncherDiscoveryRequests`?
And then how to run such suite?

**Comment by sbrannen** [comment]
> Could you give me example how to specify something like `fast AND (priority1 OR priority2) AND NOT stable` using `PostDiscoveryFilters` and `LauncherDiscoveryRequests`?

`LauncherDiscoveryRequestBuilder` has a `filters(...)` method which you can pass an instance of `PostDiscoveryFilter`.

So you would need to implement your own `PostDiscoveryFilter` that supports your tag query language.

See the source code for `TagFilter` for examples.

> And then how to run such suite?

As @marcphilipp mentioned:

> there's no way to specify such a filter through Gradle, Maven or the ConsoleLauncher, yet.

So you'll have to run the `Launcher` manually.

**Comment by sbrannen** [comment]
Added labels and milestone

**Comment by marcphilipp** [comment]
@signed We have reserved `&`, `|`, and `!` instead of `and`, `or`, and `not`.

**Comment by sbrannen** [comment]
_in progress_ in #1219
