### ISSUE TITLE
Rerun failed tests via command line

### ISSUE THREAD

**Issue by ondrejlerch** [junit-team/junit5#457]
Let's imagine that:
1. We run large number of tests via command line
2. Some tests fail
3. We investigate why they failed
4. We fix the problem, for example in the code
5. Now we want to rerun failed tests only

**It would be great to have something like --rerun-failed-tests command option**.

IntelliJ IDEA IDE has "Rerun Failed Tests" feature, so why not to have it directly in Junit 5 Console Launcher?

**Comment by marcphilipp** [comment]
How would the ConsoleLauncher know which tests failed last time? I guess you could pass it the XML result file and it could parse it. However, at the moment the XML schema does not support unique IDs which we would need to specify which tests to run.
