### ISSUE TITLE
Integrate with Gradle Build Scans

### ISSUE THREAD

**Issue by mmerdes** [junit-team/junit5#458]
Add the new Gradle Build Scan to the JUnit 5 build.
The results can then be linked from gradle.com.

See: https://scans.gradle.com/setup/step-1

## Deliverables

- [x] Add the new Gradle Build Scan to the JUnit 5 build.
- [x] Link to a build scan results page from the JUnit 5 README.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, do we want to link to the build scan results from the README?

**Comment by etiennestuder** [comment]
Note that once we have accounts for build scans, you will be able to associate the build scans with an identity, and will also be able to always point to the lastest scan for a given identity.

**Comment by sbrannen** [comment]
Related discussion on [Gradle Forum](https://discuss.gradle.org/t/how-to-change-name-on-build-scan-page/19218).

**Comment by sbrannen** [comment]
That sounds good, @etiennestuder.

Looking forward to that!

**Comment by sbrannen** [comment]
@etiennestuder,

> will also be able to always point to the lastest scan for a given identity.

Are you saying we should not yet point to links such as https://scans.gradle.com/s/.... ?

**Comment by etiennestuder** [comment]
Oh yes, feel free to point to anything. That's all good. You can also point to some created build scans very well (I hope you do!). What is currently not possible is to have a link that automatically always points to the latest scan for a given project (sort of a symbolic link). That will come.

**Comment by sbrannen** [comment]
OK. Makes sense.

Cheers!

**Comment by sbrannen** [comment]
Updated _Deliverables_.

**Comment by sbrannen** [comment]
The README now covers build scans:

https://github.com/junit-team/junit5#gradle-build-scans

**Comment by etiennestuder** [comment]
Thank you for the integration!

Btw, in agreement with you guys, you can now see a sample scan of a JUnit 5 build on our Gradle.com homepage.
