### ISSUE TITLE
Align classpath command-line options for ConsoleLauncher with Java

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#461]
## Status Quo

`ConsoleLauncher` currently supports a `-p` command-line option for configuring additional classpath entries; however, this short form deviates from the `-cp` command-line option for the standard `java` executable.

## Rationale

It would beneficial to users of the `ConsoleLauncher` to align the classpath command-line options for `ConsoleLauncher` with Java.

Furthermore, doing so also frees up the `-p` option for later use in selecting packages for test discovery (see #437).

## Deliverables

- Rename `-p` command-line option to `-cp` in the `ConsoleLauncher`

**Comment by nicolaiparlog** [comment]
FYI: Java is [moving away](http://openjdk.java.net/jeps/293) from options like `-cp`, which are "un-GNU". Particularly `-cp` is an exception, though, and [it looks like](http://mail.openjdk.java.net/pipermail/jigsaw-dev/2016-August/009025.html) it's not going to get a proper one-letter alias. Maybe something to keep in mind for other command line arguments, though.

**Comment by sbrannen** [comment]
@nicolaiparlog, thanks for the tips.

The `cp` option is currently the only one we support that is "un-GNU" like, and I only added it in order to align with what people are accustomed with Java. So hopefully this one exception to the rule is deemed acceptable. 😉 

FWIW, the `cp` option can be declared as `-cp` or `--cp` thanks to JOpt Simple's leniency in that regard.

And... with my latest commit, we now support the following for additional classpath entries.

- `-cp` or `--cp`
- `-classpath` or `--classpath`
- `--class-path`

**Comment by sbrannen** [comment]
@nicolaiparlog, you may also be interested in #468.
