### ISSUE TITLE
Allow extensions to register TestExecutionListeners

### ISSUE THREAD

**Issue by lewisb42** [junit-team/junit5#462]
As best I can tell, if I want to register a custom TestExecutionListener I have to go through the motions of creating a new test engine, launcher, etc., when I'd rather just have an ExtendsWith extension that can listen to test execution from one of the stock engines.  Specifically, I'd like to intercept ReportEntry's as they are published so I can process them further.

**Comment by marcphilipp** [comment]
Makes sense IMHO. Related to #19.

**Comment by marcphilipp** [comment]
Since #583, you can add TestExecutionListener using the ServiceLoader API.

@lewisb42 Does that address your use case?

**Comment by lewisb42** [comment]
That particular project has been back-burnered for a couple of months so I can't say off the top of my head, but I'll try to context-switch in the next few weeks and get you a proper answer.  On it's face it sounds like a nice clean approach, though.

**Comment by lewisb42** [comment]
@marcphilipp I got a chance to play with this and I believe it works.  Here is the overview of what I did (to make sure you and I are thinking the same thing):

1. My `@ExtendsWith` extension is packaged inside a JAR library with a file `META-INF/services/org.junit.platform.launcher.TestExecutionListener` with my `SampleTestExecutionListener` implementation referenced inside. 
2. I referenced that jar in a test project, where I annotated a Junit5 test class with `@ExtendsWith(MyExtension.class)`.
3. When the tests are run my `SampleTestExecutionListener` is catching the execution events for all `@Test` methods in the class.

I'll mark this as closed from my end. If your intention was different feel free to reopen.  Thanks so much for addressing this.

**Comment by marcphilipp** [comment]
Just wondering: What interface besides `TestExecutionListener ` does your `SampleTestExecutionListener` need to implement? In other words, is it necessary to register it using `@ExtendsWith(SampleTestExecutionListener.class)` at all? Or is `MyExtension` ≠ `SampleTestExecutionListener`.

**Comment by lewisb42** [comment]
They aren't the same class, though there's no particular reason they couldn't be.  And your question makes me wonder if, at the least, the two objects need to share state. As I re-visit things, the answer, I think, is yes.

So let me give you the specifics of my project and maybe that'll avoid the awkwardness of talking in abstract terms. I'm a CS prof and I'd like to annotate my junit tests with some grading-related information to save me some time when I'm grading student work. One use case is assigning point values to `@Test` methods via a `@Gradable` annotation and then being able to automatically sum up those points at the end.  My `@ExtendWith` extension (I'm calling it `Gradeunt`) handles the reflection to identify those annotated tests but until now there wasn't a really good way find out which tests passed or failed and do the calculations accordingly.

So the current state is that I can find out pass/fails via `TestExecutionListener` injected via Service Loader, but it's unclear to me if I can aggregate that information with the annotation information that `Gradeunt` reported on the front end. Looking right now I don't see a clear path from a `TestExecutionListener` object back to the actual `Method` objects that were run as tests.

Assuming I'm not missing something, here are some possible fixes (from my point of view)
1. Have `TestIdentifier` include a getter for the `Method` that was executed. This way a `TestExecutionListener` could walk back and see any custom annotations applied to that `Method`.
2. Give `TestExecutionListeners` access to the `Store` for extensions
3. Re-visit the original suggestion and allow extensions to dynamically register `TestExecutionListener`s -- which would also allow the extension to register itself as a listener.

In case I haven't said it yet, thank you so much for taking the time to listen through this issue. I hope it's something that is more generally useful than just my one little side-project.

**Comment by sormuras** [comment]
...or, if you just want to know the **result** of an executed test:
4. Extend Jupiters [TestExtensionContext](http://junit.org/junit5/docs/snapshot/api/org/junit/jupiter/api/extension/TestExtensionContext.html) with an `Optional<org.junit.platform.engineTestExecutionResult>`?

**Comment by marcphilipp** [comment]
@lewisb42 Can you report the annotation information via `publishReportEntry` and do the calculations in your `TestExecutionListener`?

> ...or, if you just want to know the **result** of an executed test:
> 4. Extend Jupiters [TestExtensionContext](http://junit.org/junit5/docs/snapshot/api/org/junit/jupiter/api/extension/TestExtensionContext.html) with an `Optional<org.junit.platform.engineTestExecutionResult>`?

I think that looks like the most simple solution. However, we cannot use `TestExecutionResult` because it's in the platform-engine module and needs to stay there. There's already `Optional<Throwable> getTestException()` in `TestExtensionContext`, though. If we added an additional `Status` enum to jupiter-api and `Optional<Status> getTestStatus()` we'd be all set.

**Comment by sormuras** [comment]
Is that enum `Status` a member candidate for https://github.com/ota4j-team/opentest4j ?

**Comment by marcphilipp** [comment]
Hmm, good thinking! That might work, too.

**Comment by chasecaleb** [comment]
Related to this issue, I need to report test passes/fails within an `Extension` and think I finally figured out how, but wanted confirmation that I'm doing it.

Use case: I'm using `SpringExtension` for dependency injection, and at the end of each test I need access to the test outcome and a Spring-managed bean at the same time. _(Specifically for anyone who cares, I'm running Selenium browser automation tests and need to report the test outcome tied to the WebDriver bean's session id)._

Problem: I know as of #583 that I can easily register a `TestExecutionListener` and get the test result there, but I don't have access to the `ExtensionContext`. Within an `Extension `I would obviously have the `ExtensionContext`, but as pointed out in this issue there isn't a way to explicitly get the test result within an `Extension`.

Solution?: Within an `Extension `implementing `AfterEachCallback`, it looks like I can implicitly determine whether or not a test succeeded by checking whether or not `TestExtensionContext.getTestException()` is present. **Is that reliable/correct, or am I missing circumstances where that doesn't hold true?** That is, could test either fail without having an exception or succeed with an exception?

Here's a short demo gist: https://gist.github.com/chasecaleb/407d3c5605b46838b81bed190cba8eee

**Comment by marcphilipp** [comment]
> Is that reliable/correct, or am I missing circumstances where that doesn't hold true?

The test could still fail, e.g. in an `@After` method.

Proposal: Have your extension publish the WebDriver bean's session id, e.g.

```java
String sessionId = ...;
extensionContext.publishReportEntry("webDriverSessionId", sessionId)
```

In your `TestExecutionListener`, implement `reportingEntryPublished` and store it in a `Map` with the `TestIdentifier` as a key. In `executionFinished` report the test outcome along with the value from this `Map`.

Would that work for you?

**Comment by chasecaleb** [comment]
> The test could still fail, e.g. in an @After method.
In which case you're saying the `TestExecutionListener` would incorrectly think the test passed, since the failing `@After` method would be invoked after it, correct? That makes sense.

Your solution using reporting entries sounds workable. One minor disadvantage: if a test suite is killed halfway through, then the already-finished test results won't be published. I don't really care about that for my use case though, so it's fine.

Thanks for the help!

**Comment by marcphilipp** [comment]
`executionFinished` is called for each `TestIdentifier` as soon as it's finished. So there shouldn't be any lost data. 🤔

**Comment by chasecaleb** [comment]
Oops, I don't know where I got that assumption from. Even better :+1:
