### ISSUE TITLE
Introduce support for selecting URIs in ConsoleLauncher and Gradle plugin

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#470]
## Overview

This issue builds on the work performed in #469.
## Related Issues
- #437
- #452 
- #468
## Deliverables
- [x] Introduce support for selecting URIs in `ConsoleLauncher` via `-u` and `--select-uri` options
- [x] Introduce support for selecting URIs in the JUnit Platform Gradle plugin

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
This issue is blocked until we've defined the syntax to be used by the Gradle plugin.

**Comment by marcphilipp** [comment]
Team decision wrt. the Gradle syntax:

```groovy
junitPlatform {
    selectors {
        uris 'file:///foo.txt', 'http://example.com'
        packages 'com.acme.app', 'foo.bar'
        classes 'com.acme.AllTests'
        methods 'test1()'
        directories 'foo/bar', 'foo/baz'
        files 'a.csv'
        classpathResources 'some.jar'
    }
}

**Comment by marcphilipp** [comment]
I'll continue to work on this issue.
