### ISSUE TITLE
Classpath scanning eagerly loads classes unnecessarily

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#474]
## Status Quo

`ClasspathScanner.processClassFileSafely()` _eagerly_ loads candidate classes without applying any filtering (other than the recently adding filtering for `package-info`). Consequently, every single class in the classpath is loaded even if it will never be needed for the current test plan.

Although `ClassFilter.includeClassNamePattern(String)` can be used to filter out scanned classes, this unfortunately occurs after classpath scanning has occurred, meaning that even unused test classes are unnecessarily eagerly loaded.

This leads to unnecessary loading of classes, and since classes may have `static` initialization blocks, this also potentially leads to unnecessary execution of code.

## Worst Case Scenario

Due to the recently added support for scanning JARs in the classpath (see #399), the `ClasspathScanner` can now potentially *load every single class in the entire JVM* if all classpath roots are scanned _and_ the user selects the default package as the base package from which to begin scanning.

## Related Issues

- #313 
- #314 

## Deliverables

- [x] Apply filtering to classpath scanning candidates before loading the class (i.e., based solely on the file name of the `.class` file).
  - [x] Supply class name patterns registered via `ClassFilter.includeClassNamePattern(String)` to the classpath scanning algorithms
- [x] Change includeClassNamePattern(String pattern) to includeClassNamePatterns(String... patterns) and combine the patterns within a single filter using OR semantics
- [x] Do the same for the `@IncludeClassNamePattern` annotation.
- [x] Create follow-up ticket for M4 to delete deprecated `ClassFilter.includeClassNamePattern(String)` and `@IncludeClassNamePattern`

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, let's discuss this topic.

**Comment by sbrannen** [comment]
Added _Worst Case Scenario_ section to issue description.

**Comment by sbrannen** [comment]
**Team Decisions**:

- Apply filtering based on the configured test class name regular expression _before_ loading a class during classpath scanning.
- Continue to apply filtering as a `PostDiscoveryFilter` in order to exclude classes selected by means other than classpath scanning (e.g., selection by class, method, UID, etc.).

**Comment by marcphilipp** [comment]
_in progress_

**Comment by sbrannen** [comment]
Thanks, @marcphilipp! Good work.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, I am reopening this issue in order to discuss the following.

I wonder if we really want to compose the filters with AND semantics in `ClasspathScanningSupport`.

For example, if a user specifies `^.+TestCase$` and `^.+Tests$` as class name patterns, no tests would be executed since a class cannot end with "TestCase" _and_ "Tests" simultaneously.

One alternative would be to compose them with OR semantics.

Another possibility would be to throw an exception if there is more than one `ClassNameFilter` registered in the discovery request.

If we opt for the latter, we would then need to document that only a single pattern is supported and that multiple patterns must be combined into a single regular expression.

Actually, we'll have to document the semantics (AND vs OR) in either case. I'll add a note to #490 to address that.

**Comment by marcphilipp** [comment]
Well, from a `LauncherDiscoveryRequestBuilder` point-of-view, adding multiple filters means only discovering tests that pass _all_ of the filters. But you're right, I don't think it explicitly states that we use AND semantics, just that we apply all of the filters.

We could add a generic OR filter or change `includeClassNamePattern()` to multiple patterns via varargs.

**Comment by sbrannen** [comment]
The varargs route might be the best solution.

Basically, I'm thinking ahead to how the Gradle plugin may eventually look.

If you look at the standard Gradle `test` task, you can supply multiple include and exclude patterns. The same is true for Maven Surefire as well.

For example, in the build for `spring-test`, I use the following:

```java
include(['**/*Tests.class', '**/*Test.class', '**/SpringJUnitJupiterTestSuite.class'])
exclude(['**/testng/**/*.*'])
```

So, if we hope to provide an easy migration to the JUnit Platform for Gradle users, I think we should provide OR semantics for include patterns. Otherwise, it can become a daunting task for the average developer to work out the exact syntax for a single, all-encompassing regular expression. 😉 

Similarly, we should consider allowing multiple patterns via `@IncludeClassNamePattern`.

Thoughts?

**Comment by marcphilipp** [comment]
SGTM! 👍

**Comment by marcphilipp** [comment]
FYI I'm continuing to work on this issue and have added one additional deliverable.

**Comment by marcphilipp** [comment]
All deliverables are done, follow-up task for M4 is created (#547) -> I'm closing this issue.
