### ISSUE TITLE
Align Gradle plugin options with standard Gradle Test task

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#475]
## Status Quo

The JUnit Platform Gradle Plugin currently does not support most features of the standard Gradle `Test` task. For example, without the `afterEvaluate` work-around listed in the comments section, it is impossible to contribute system properties or configure the underlying `JavaExec` task used by the plugin behind the scenes.
## Related Issues
- #315
- #484 
## Deliverables
- [ ] Where feasible, support all features of the standard Gradle `Test` task in the JUnit Platform Gradle plugin.
  - Since the JUnit plugin should eventually implement `Test` instead of `JavaExec` anyway, this might be an opportune time to make that switch.
## Original Issue Description

The JUnit Platform Gradle Plugin should expose Gradle's `JavaExec` task properties... or at least let me pass JVM arguments to the `ConsoleLauncher` process.

I need to set `-ea` or `-Djava.util.logging.config.file=...` when running tests. 

Or am I missing a built-in(?) Gradle feature?

**Comment by sbrannen** [comment]
Technically speaking, this is already possible.

For example, to manually set the `LogManager` instead of using the `logManager` configuration option for `junitPlatform`, you can do the following in a project that applies the JUnit Platform Gradle Plugin.

```java
afterEvaluate {
	def junitPlatformTestTask = tasks.getByName('junitPlatformTest')

	junitPlatformTestTask.systemProperty 'java.util.logging.manager', 'org.apache.logging.log4j.jul.LogManager'
}
```

You can also set the `-ea` option for `java` as follows:

```java
afterEvaluate {
	def junitPlatformTestTask = tasks.getByName('junitPlatformTest')

	junitPlatformTestTask.enableAssertions true
}
```

The same technique should be applicable to any properties supported by the `JavaExec` task.

**Comment by sbrannen** [comment]
FYI: I have overhauled this issue's title and description.

**Comment by sbrannen** [comment]
This is directly related to #315.

**Comment by sormuras** [comment]
Thanks for the quick Gradle help and looking forward to the real `Test` implementation.

**Comment by sormuras** [comment]
Is it #583 related?

**Comment by sbrannen** [comment]
@sormuras, #538 is related in the sense that both are related to improving the Gradle plugin; however, _this_ issue has a much broader scope than #538.

**Comment by nskvortsov** [comment]
Also, support for Gradle common [test listeners](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:addTestListener(org.gradle.api.tasks.testing.TestListener)) would be very useful

**Comment by estekhin** [comment]
JUnit should use the logging system provided by Gradle by default when running as a part of Gradle-based build.

`junitPlatform.logManager` should be used to override this default behavior, but the default should be that all logging done by JUnit inside Gradle should go to the logger provided by Gradle and be affected by Gradle log-related command-line options (https://docs.gradle.org/current/userguide/logging.html).

**Comment by marcphilipp** [comment]
The current plugin uses the Java task to start a new JVM. How can it use Gradle's logging system?

**Comment by sbrannen** [comment]
@estekhin, you are confusing two different things.

1. JUnit uses Java's built-in logging framework (regardless of how JUnit is executed: Gradle, IntelliJ IDEA, command-line, etc.).
1. Gradle tasks can participate in Gradle's logging support.

The `junitPlatform.logManager` you refer to can therefore only apply to category 1 above.

Thus your proposal can only be applied to what the JUnit Platform Gradle Plugin does.

**Comment by marcphilipp** [comment]
Since we're in the process of handing over the Gradle plugin to the Gradle team in gradle/gradle#1037, I'm closing this issue.

**Comment by arteme** [comment]
What is the advantage of setting properties in the "afterEvaluate" block as opposed to during the task configuration? Given that `xyz { ... }` syntax is essentially a shortcut to `tasks.getByName('xyz') { ... }`, then in my tests, the following works with gradle 4.2 at least and skips the unpleasantness of having to do manual `getByName()` lookup :
```
junitPlatformTest {
    setProperty "my.custom.property.name", "value"
} 
```
