### ISSUE TITLE
Non-standard method names are not supported for discovery selection

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#477]
## Status Quo

All `selectMethod()` variants in `DiscoverySelectors` attempt to eagerly load the selected method with the assumption that the supplied method name follows Java's standard convention for methods.

This is totally fine for standard Java methods; however, for testing frameworks such as Spock the method name might contain special characters.

For example, `"applying the plugin"` is a valid method name in a Spock specification (at least within the Groovy source code). In the decompiled byte code, however, we see that the actual Java method name is something completely different, such as `$spock_feature_0_0` in the following example.

```java
// Method descriptor #26 ()V
// Stack: 18, Locals: 3
@org.spockframework.runtime.model.FeatureMetadata(line=(int) 32,
  name="applying the plugin",
  ordinal=(int) 0,
  blocks={@org.spockframework.runtime.model.BlockMetadata(kind=org.spockframework.runtime.model.BlockKind.WHEN,
          texts={}),@org.spockframework.runtime.model.BlockMetadata(kind=org.spockframework.runtime.model.BlockKind.THEN,
          texts={})},
  parameterNames={})
public void $spock_feature_0_0();
```

For this reason, attempting to _select_ the `"applying the plugin"` method by name (e.g., via `selectMethod("org.junit.platform.gradle.plugin.JUnitPlatformPluginSpec#applying the plugin")`) results in an exception similar to the following.

```
org.junit.platform.commons.util.PreconditionViolationException: 
    'org.junit.platform.gradle.plugin.JUnitPlatformPluginSpec#applying the plugin'
    could not be resolved to a unique method
```

## Related Resources

- [IntelliJ IDEA](https://youtrack.jetbrains.com/issue/IDEA-159975) issue on the same topic.

## Deliverables

- [x] Introduce a `selectMethod()` variant that does not attempt to eagerly load the selected method.
  - The `MethodSelector` could then provide the input method name as a `String` and let the `TestEngine` decide how to load or reference the method.
- [x] Consider if all existing method selectors should be revised to avoid eager loading of methods using reflection.
- [x] Consider if all existing class selectors should be revised to avoid eager loading of classes using reflection.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, we will need to discuss the ramifications of such use cases and come to a decision on how to proceed _across the board_ for all such selectors.

**Comment by bechte** [comment]
Good catch. I would like to take care about the discovery mechanism. Let's talk about this issue together with #489 within the team. If all agree, I could work on this for M3.

**Comment by sbrannen** [comment]
Since #489 essentially supersedes this issue, I have marked this issue as _blocked_ until #489 is completed.

But let's leave this issue here since it was the original bug report that inspired #489. Furthermore, I'd like to leave it in M3 so that we can list it as a bug fix in the release notes.

**Comment by sbrannen** [comment]
In addition, we have to ensure that changes made in conjunction with #489 actually _fix_ this bug. 😉

**Comment by bechte** [comment]
Merged into master.
