### ISSUE TITLE
Versioning plugin slowing down your build

### ISSUE THREAD

**Issue by oehme** [junit-team/junit5#480]
Hey folks,

I just noticed this line in your build:

```
'Build-Revision': versioning.info.commit,
```

This effectively calls `git status` once for *every* subproject on *every* Gradle invocation. At the very least you'll want to call it only once. This will speed up all your builds.

Ideally you could change it so that attribute is only computed on CI builds. On local builds you probably don't care so much about the "Build-Revision" in the manifest.

Cheers,
Stefan

**Comment by sbrannen** [comment]
_in progress_

**Comment by oehme** [comment]
Note that my PR only fixed the first half of this. You might still want to consider whether you really need this manifest attribute on local dev builds.

**Comment by sbrannen** [comment]
Understood, but I don't think the once-per-build status quo is really an issue.
