### ISSUE TITLE
DeGraph should not be run as part of test task

### ISSUE THREAD

**Issue by oehme** [junit-team/junit5#481]
The Junit 5 build is currently running DeGraph as a Junit test in `DependencyTests`. This means that someone just running `./gradlew test` will also run this very expensive check, even though they probably just were interested in running "real" unit tests.

Ignoring this single test cuts test execution time from 25s to 10s on my machine.

I'd suggest writing a dedicated task for DeGraph.

**Comment by oehme** [comment]
I'm working on a [fix](https://github.com/oehme/junit5/commit/8e64e9916e5dddbf6c641a8519bd606957ba1cde), which is blocked on a DeGraph [issue](https://github.com/schauder/degraph/issues/67). Feel free to up-vote it :)

**Comment by sbrannen** [comment]
Thanks for raising the issue and working on a fix!

I've slated this for M3 with the hope that we can get it in by then. Otherwise, we'll just push it back to M4.

**Comment by sbrannen** [comment]
By the way, we are very aware of how long that "test" takes.

That's why we moved it to a dedicated project in the first place.

And that's why I practically always execute `gradlew clean test -x :test`. 😉

**Comment by oehme** [comment]
> And that's why I practically always execute gradlew clean test -x :test

Yes, but such "secret knowledge" should not be necessary to get a good dev experience :) 

In this case a dedicated task is the right solution. More generally though, if you have expensive tests (let's say integration tests), you should create a custom sourceSet for those. The default `test` task is really only meant for unit tests and users generally expect it to be fast.

**Comment by marcphilipp** [comment]
I really would like to have a Gradle plugin for degraph. I've talked to @schauder (the author of degraph) about it and he would welcome it but does not have time to do it.

**Comment by oehme** [comment]
I'll make sure that the fix I'm currently working on will be simple to wrap in a published plugin. So anyone can then pick it up.

**Comment by sbrannen** [comment]
Via some Gradle wizardry, I have already addressed the major concerns of this issue in d268d9f5df916e16651c91cb51deb95b5508243d. 😉 

Of course, a _real_ plugin for DeGraph would be great.

**Comment by sbrannen** [comment]
Closing this issue due to the work performed in d268d9f5df916e16651c91cb51deb95b5508243d.

An actual migration to a dedicated plugin will be addressed in #483.
