### ISSUE TITLE
Migrate to dedicated Degraph Gradle plugin

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#483]
## Overview

As mentioned by @oehme in #481:

> [He's] working on a [fix](https://github.com/oehme/junit5/commit/1228fd1fefec6623ef57e48364cde340f5b47e51), which is blocked on a DeGraph [issue](https://github.com/schauder/degraph/issues/67). Feel free to up-vote it :)
## Deliverables
- [ ] Migrate to a dedicated Gradle plugin for Degraph once such a plugin exists.

**Comment by marcphilipp** [comment]
@oehme Now that degraph 0.1.4 has been released, do you have time to continue working on the fix?

**Comment by oehme** [comment]
I will, when I come back from vacation in 2 weeks :)

Am 12.09.2016 04:49 schrieb "Marc Philipp" <notifications@github.com>:

**Comment by schauder** [comment]
Minor thing: It's Degraph, not DeGraph

**Comment by schauder** [comment]
If the plugin in agnostic of JUnit (except for it's own test) It would be cool to have it with the the other Degraph modules.  If interested, we can handle it via

1. PR to the Degraph repository
2. I'm willing to grant commit privileges to those doing most of the work
3. Migrate everything to a Degraph organisation and have second repo there

I'm open for alternatives, but would like to avoid the effect of Degraph artifacts coming from two places without an obvious connection.

**Comment by marcphilipp** [comment]
> Minor thing: It's Degraph, not DeGraph

Fixed.

> If the plugin in agnostic of JUnit (except for it's own test) It would be cool to have it with the the other Degraph modules.

Agreed! Let's get a first version for use with JUnit and then figure out how to contribute it to Degraph, ok?

**Comment by schauder** [comment]
> Let's get a first version for use with JUnit and then figure out how to contribute it to Degraph, ok?

Sure.

**Comment by oehme** [comment]
I was initially planning to just write a script for the JUnit team, but
since there is broader interest, I'd be willing to start a real plugin.

You'll need to get an account on plugins.gradle.org so you can publish it.

Am 12.09.2016 12:23 schrieb "Jens Schauder" <notifications@github.com>:

**Comment by schauder** [comment]
No pressure. There is no point in having a half done plugin (that's why I never started one so far)

If out of this comes a code snippet that I can post somewhere as an example how to have Degraph run separately it would help a lot.

**Comment by oehme** [comment]
@schauder Why don't we schedule a hangout when I'm back? We could go through possible use cases and design a plugin together.

**Comment by marcphilipp** [comment]
@schauder @oehme Any news on the dedicated degraph Gradle plugin?

**Comment by oehme** [comment]
I have added my ideas to the Degraph issue tracker: https://github.com/schauder/degraph/issues/69

**Comment by schauder** [comment]
I'm sorry, no news yet. I just started my xmas vacation, so maybe I find some time.

**Comment by sormuras** [comment]
https://github.com/obecker/gradle-degraph ?

**Comment by sbrannen** [comment]
worth a try...
