### ISSUE TITLE
DynamicTest.stream does not support checked exceptions

### ISSUE THREAD

**Issue by hovinen** [junit-team/junit5#486]
Currently `DynamicTest.stream` uses `java.util.function.Consumer` for the parameter to execute tests. This interface does not allow throwing checked exceptions. Thus, e.g., the following code will not compile:

```java
    @TestFactory
    Stream<DynamicTest> myCodeShouldDoSomethingUseful() {
        return DynamicTest.stream(
                ImmutableList.of(
                    new IndividualTestCase("some data"),
                    new IndividualTestCase("some other data")).iterator(),
                IndividualTestCase::toString,
                this::myCodeShouldDoSomethingUseful);
    }

    private void myCodeShouldDoSomethingUseful(IndividualTestCase testCase)
            throws Exception {
        throw new Exception("This will fail");
    }

    private static final class IndividualTestCase {
        public IndividualTestCase(String data) {}
    }
```

In analogy with `Executable`, it would be helpful to use a different functional interface for the test executor whose method throws `Throwable`. Thanks!

**Comment by sbrannen** [comment]
Good catch! 👍 

I believe this was merely an oversight on our part.

Slating this for M3.

Cheers,

Sam

**Comment by marcphilipp** [comment]
This should be relatively easy to do, I'm putting it up-for-grabs.

@hovinen Do you have time to work on a fix?

**Comment by hovinen** [comment]
Hi Marc,

I can certainly do it, but not before next week.

Best regards,

Bradford Hovinen

Am 30.08.2016 1:11 nachm. schrieb "Marc Philipp" <notifications@github.com>:

**Comment by sbrannen** [comment]
@hovinen, please note that we might resolve the issue on our own in the interim.

So, with that in mind, please do not start work on this issue without having checked the status of this issue. 😉

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Fixed in `master` in b926c0bc58008f8bde13087b151a373c7ed25528.

**Comment by hovinen** [comment]
Looks great. Thanks!

Best regards,

Bradford Hovinen

Sam Brannen <notifications@github.com> schrieb am Di., 30. Aug. 2016 um
15:28 Uhr:

**Comment by sbrannen** [comment]
Cool. Thanks for letting us know!
