### ISSUE TITLE
Store raw values in DiscoverySelectors & TestSources

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#489]
## Overview

In light of issues such as #477 and the discussion in #466,  the JUnit 5 Team has decided to store _raw_ values in all `DiscoverySelector` and `TestSource` implementations for the _entire Platform_.

In other words, the JUnit Platform should not _store_ anything in either selectors or sources using a _biased_ format (e.g., `File` vs. `Path` vs. `URI` vs. `String` _and_ `Method` vs. method name), since it is up to a specific `TestEngine` or IDE to interpret the _raw_ format.

## Proposal for file system sources

Input from @marcphilipp:

> We could change `FileSource` and `DirectorySource` to store a `URI` instead of a `File` and provide methods that return a `File`/`Path` from the `URI`.

## Deliverables

- [x] Ensure that each `DiscoverySelector` implementation stores the selected element in a _raw_ format.
  - Add _getter_ methods for retrieving the raw format as well as technology specific representations.
- [x] Ensure that each `TestSource` implementation stores the source in a _raw_ format.
  - Add _getter_ methods for retrieving the raw format as well as technology specific representations.

**Comment by jbduncan** [comment]
Sounds pretty reasonable to me!

**Comment by bechte** [comment]
First step: Ensure that each DiscoverySelector implementation stores the selected element in a raw format

- [ ] ClasspathResourceSelector
- [ ] ClasspathRootSelector
- [ ] DirectorySelector
- [ ] FileSelector
- [ ] JavaClassSelector
- [ ] JavaMethodSelector
- [ ] JavaPackageSelector
- [ ] UniqueIdSelector
- [ ] UriSelector

**Comment by sbrannen** [comment]
@bechte, could you please take a look at #516 and keep that bug in mind as you address #489?

Cheers!

**Comment by bechte** [comment]
Sure, thanks for pointing that. 👍

**Comment by bechte** [comment]
Second Step: Ensure that each `TestSource` implementation stores the source in a raw format.
Add getter methods for retrieving the raw format as well as technology specific representations.

- [ ] JavaClassSource
- [ ] JavaMethodSource
- [ ] JavaPackageSource

**Comment by bechte** [comment]
I did some rework on the classes to provide a good base for further discussion, see feature branch *sb_userawvaluesfordiscovery*. There are still some questions open that we will discuss in the team. Afterwards, I will prepare a pull request for the changes.

**Comment by bechte** [comment]
Merged into master.
