### ISSUE TITLE
[SUREFIRE] Questionable asserts in TestPlanScannerFilterTests

### ISSUE THREAD

**Issue by britter** [junit-team/junit5#492]
The following assert in `TestPlanScannerFilterTests ` does not seem to make sense.

```java
	@Test
	void emptyClassAccepted() {
		assertTrue(newFilter().accept(EmptyClass.class), "accepts empty class because it is a container");
	}
```

In this case, when you debug into `TestPlan.countTestIdentifiers`, it will return true because the test plan contains the two root identifiers for the Jupiter and the Vintage Engine. Since `EmptyClass` is empty, it should not be accepted by the filter.

**Comment by smoyer64** [comment]
See the PR for the includeTags and excludeTags filter #485.  I changed that code because after filtering what you really care about is whether there are any tests to run (and you shouldn't count the containers themselves).

**Comment by britter** [comment]
Actually the `TestPlanScannerFilter` will accept any class as long as the platform discovers any engines.

**Comment by marcphilipp** [comment]
> Actually the `TestPlanScannerFilter` will accept any class as long as the platform discovers any engines.

That doesn't make any sense IMHO. We used to prune empty engine descriptors from the `TestPlan`, so that might be a leftover that wasn't discovered due to a missing unit test.

**Comment by britter** [comment]
@sbrannen I'm not saying it is undesirable. I currently don't understand what `TestPlanScannerFilter` is testing. I don't think it is possible to write a test so that `accept(Class)` will return false. And that is, because the TestPlan will always contain the discovered engines.

So maybe this is really a Bug in `TestPlanScannerFilter` ? Should it really return true for `EmptyClass`? Maybe the `hasTests` Predicate needs to be adjusted.

**Comment by sbrannen** [comment]
I can fully understand your confusion, especially since there is zero documentation in `TestPlanScannerFilter`.

> Maybe the `hasTests` Predicate needs to be adjusted.

That's what I was hinting at when I said:

> we will then have to introduce explicit support for allowing a `TestDescriptor` to state that it will _eventually register dynamic tests_.

So, to clear up the confusion, `TestPlanScannerFilter` is supposed to determine if a class actually contains tests or _will_ eventually produce tests (in the form of dynamically registered tests).

**Comment by sbrannen** [comment]
> So maybe this is really a Bug in `TestPlanScannerFilter`?

Yes and no.

`TestPlanScannerFilter` does the best it currently can, because the `TestIdentifier` API doesn't provide a mechanism for saying that a container will eventually register tests dynamically.

Does that make sense now?

**Comment by britter** [comment]
@sbrannen yes, I think I understand now. So this issue could be resolved and a new issue for adding the API you mentioned in your other comment.

**Comment by sbrannen** [comment]
Superseded by #508.
