### ISSUE TITLE
Provide consistent API in LauncherDiscoveryRequestBuilder regarding nullability

### ISSUE THREAD

**Issue by britter** [junit-team/junit5#493]
The API for building a `LauncherDiscoveryRequest` seems strange to me:

`LauncherDiscoveryRequestBuilder.filters(Filter<?>...)` accepts a `null` array but does not accept `null` values in that array.

`TagFilter.includeTags(String...)` and `TagFilter.excludeTags(String...)` only accept non null, non empty arrays.

I think it would be better if methods accepting arrays/collections behave the same way.

**Comment by marcphilipp** [comment]
Good catch, thanks!

I think we should not accept `null` arrays/collections in `LauncherDiscoveryRequestBuilder`.

@junit-team/junit-lambda Any objections?

**Comment by sbrannen** [comment]
No objections to that.

We should in fact verify that the elements of such arrays and collections are also non-null, something analogous to `Preconditions.notNull(Object[], String)`.

**Comment by smoyer64** [comment]
Relates to #358 - that issue should probably be broadened to also clarify when passed parameters might be null.

**Comment by britter** [comment]
@sbrannen @marcphilipp I was working on a PR for this, when I discovered #496. I think that has to be resolved first.

**Comment by sbrannen** [comment]
_Blocked_ until #496 is resolved.

**Comment by sbrannen** [comment]
This issue is no longer _blocked_ since #496 has been resolved.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Resolved in `master`.
