### ISSUE TITLE
Unix-style command-line options for ConsoleLauncher should follow Unix conventions

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#494]
The aliases added to the CLI console launch in PR #468 are wonderful but the Unix-style options that take arguments should use an "=" (equals sign) to pass in their parameters.  Currently this option will not work:

```
--class-path=~/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar
```

But replacing the "=" with a " " (space) results in the engine being found:

```
--class-path ~/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar
```

**Comment by sbrannen** [comment]
Hmmmm... that seems odd.

We actually have unit tests in place that show `--class-path=...` working:

https://github.com/junit-team/junit5/blob/ae175d3c667e4e96b9d66dac713241a5a229defb/platform-tests/src/test/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParserTests.java#L163-L179

Can you provide a failing test?

Or are you just experiencing this when actually trying it in the console?

**Comment by sbrannen** [comment]
Out of curiosity, what happens if you put a space _after_ the equals sign like the following?

```
--class-path= ~/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar
```

**Comment by sbrannen** [comment]
And what happens if you put double quotes around individual path elements like this?

```
--class-path="~/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar"
```

**Comment by smoyer64** [comment]
I was actually trying to run the DynamicTests class I gave the command line for in this [comment](https://github.com/junit-team/junit5/issues/491#issuecomment-244429382) on #491.  My entire command line is:

```
smoyer1@smoyer1-x1-carbon:~/git/psu/junit5-presentation/target/test-classes$ ./junit-platform-console-1.0.0-SNAPSHOT/bin/junit-platform-console --class-path="~/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar" ./DynamicTests
```

Putting a space after the equals sign works - putting double quotes around the path element doesn't work.  (And by "works" I mean the console launcher finds the engine I'm trying to add to the classpath - I still haven't got it to find the test class yet).

**Comment by smoyer64** [comment]
On a whim (or maybe intuition from past problems?) I manually expanded the tilde into a full path and that also fixes the problem.  Here's the working command for comparison with those above:

```
smoyer1@smoyer1-x1-carbon:~/git/psu/junit5-presentation/target/test-classes$ ./junit-platform-console-1.0.0-SNAPSHOT/bin/junit-platform-console --class-path=/home/smoyer1/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar ./DynamicTests
```

**Comment by sbrannen** [comment]
Yep, that's kinda what I expected and actually the reason I asked you to try it with a leading space and wrapped in double quotes... with the hope that your shell would then properly handle the tilde expansion.

And your results confirm my suspicion. Namely, this doesn't have anything to do with the `ConsoleLauncher` or JOpt Simple. Rather, it's just that your shell refuses to expand the `~` in the middle of a string of non-whitespace characters.

I am therefore closing this issue as _invalid_.

**Comment by smoyer64** [comment]
JOpt Simple references the POSIX conventions for arguments (http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html).  Since the shell is expanding the tilde before the argument parser is called, I think this is a case where the JUnit 5 console can choose to do nothing (it's the shell's fault) or could expand tildes if it wanted to.  In any case, I'm renaming this issue to help others who might run into problems with tildes.

**Comment by sbrannen** [comment]
FYI: the official definition of [tilde expansion](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01) also explains that the tilde must become at the beginning of a _word_. 😉

**Comment by sbrannen** [comment]
Thanks for renaming the issue.

**Comment by smoyer64** [comment]
Thanks for the link ... I didn't realize tilde expansion was actually specified somewhere!  I guess I'd find that the shells I don't use (or use frequently) should work the same way as the one I use all the time.

**Comment by sbrannen** [comment]
> Since the shell is expanding the tilde before the argument parser is called, I think this is a case where the JUnit 5 console can choose to do nothing (it's the shell's fault) or could expand tildes if it wanted to.

JUnit is not in the business of guessing how the user intended for the shell to expand variables, etc. Plus, it's impossible for JUnit to know if the user has customized the shell with aliases, functions, etc.

So we should just leave it "as is".

**Comment by smoyer64** [comment]
I wasn't suggesting that you change your mind ... I really just meant that Java CLI programs could choose whether or not to perform the expansion needed.  And as an argument for your decision, the Java compiler and JVM don't expand tildes in the classpath either.

**Comment by sbrannen** [comment]
FYI: when building a path in a UNIX like shell, you'd typically use _variable expansion_ instead of _tilde expansion_ anyway.

For example, does the following work for you?

```
--class-path=${HOME}/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.0.0-SNAPSHOT/junit-jupiter-engine-5.0.0-SNAPSHOT.jar

```

**Comment by smoyer64** [comment]
Yes ... that works.  And if I was scripting something I'd probably create a variable that pointed way deeper into my Maven repository (JUNIT_REPO=${HOME}/.m2/repository/org/junit).

**Comment by NicolasMassart** [comment]
I found our that `--class-path ~/.m2/` without the equal sign between option name and value works.
