### ISSUE TITLE
Move JUnitPlatform, SelectPackages and SelectClasses to a public API

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#498]
Separating the JUnit 5 API from it's implementation provides a concise way for a test writer to know what classes can safely be used when writing tests.  Pull request https://github.com/junit-team/junit5-samples/pull/16 changes the Maven POM to only expose the JUnit 5 public APIs to test writers when using the Maven build system as the test runner.

As soon as you you also want to run these tests using a JUnit 4 runner (whether using the console or via Eclipse), you have to add the junit-platform-runner and the junit-jupiter-engine to the test-compile classpath.  This results in the minimal dependencies shown in the referenced PR to expand to a large number of non-public classes as shown below:

![junit5-maven-consumer-minimal-with-junit-4](https://cloud.githubusercontent.com/assets/328333/18361264/2e706a06-75cf-11e6-84ed-18eb2435404f.png)

**Comment by marcphilipp** [comment]
@smoyer64 I'm not sure I understand what you're asking for in this issue. You want to somehow minimize the dependencies... but how exactly?

**Comment by sbrannen** [comment]
I'm also confused: `JUnitPlatform`, `@SelectPackages`, and `@SelectClasses` are already _public_ APIs that make the up the programming model for anyone who needs to use JUnit 4 infrastructure to launch the JUnit Platform.

So what exactly are you proposing we change?

**Comment by sbrannen** [comment]
@smoyer64 in light of #681, are you OK if I close this issue?

Or is there still something you would like to address beyond #681?

**Comment by sbrannen** [comment]
Superseded by #681.

**Comment by smoyer64** [comment]
Yes ... this should be closed as it was "clarified" by #681.  I should have be more concise the first time but then again, I'd completely forgotten this issue by the time I wrote the other one!

**Comment by sbrannen** [comment]
OK. Thanks for the feedback.

BTW,  does the implementation of #681 meet your needs/expectations?

**Comment by smoyer64** [comment]
Yes ... moving these annotations into another package eliminates the import of Vintage and JUnit 4.  I think there are more uses for these annotations than just suites (we're really talking about limiting/hinting the discovery process) but I think people will find commonality between selecting tests for suites and selecting tests for various engines/runs.

Thanks for taking care of this!
