### ISSUE TITLE
Introduce component diagram in User Guide

### ISSUE THREAD

**Issue by schauder** [junit-team/junit5#500]
I'm currently updating my JUnit talk and created a component diagram of all the different modules and there dependencies using plant uml.

Do want this in the user manual? At least I keep returning to that diagram all the time to understand what dependencies I need.

The current version looks like this
![image](https://cloud.githubusercontent.com/assets/136683/18376934/a4575952-7663-11e6-9544-3a3e2b4cbc61.png)

If interested I'd prepare a PR

**Comment by marcphilipp** [comment]
Good point!

I've been using this one in my presentations:
![architektur](https://cloud.githubusercontent.com/assets/214207/18381879/bf6c2bee-767e-11e6-8238-aae2a5e721ba.png)

It omits OpenTest4J, though.

**Comment by schauder** [comment]
Looks much nicer, but needs fiddling with an image editor for updating, I guess?

Let me know if you want the plant uml version.

**Comment by sbrannen** [comment]
Having some sort of diagram in the user guide would certainly be beneficial.

I'm just not sure about the best _format_ for that yet.

**Comment by marcphilipp** [comment]
@schauder Did you generate the above diagram using platuml from the source code?

**Comment by schauder** [comment]
Nein, ich bin manuell die build files durchgegangen.

Dies ist der Sourcecode des Diagrams:


[plantuml]
....
package Jupiter {
[jupiter-api] as jupiterapi
[jupiter-engine] as jupiterengine
}

package Platform {
[platform-commons] as commons
[platform-console] as console
[platform-engine] as engine
[platform-gradle-plugin] as gradle
[platform-launcher] as launcher
[platform-runner] as runner
[platform-surefire-provider] as surefire
}

package Vintage {
[vintage-engine] as vintage
}

package Opentest4j {
[opentest4j]
}

package JUnit4 {
[junit4]
}

jupiterapi ..> opentest4j
jupiterapi ..> commons

jupiterengine ..> engine
jupiterengine ..> jupiterapi

console ..> launcher

gradle ..> console

launcher ..> engine

runner ..> launcher
runner ..> junit4

surefire ..> launcher

vintage ..> engine
vintage ..> junit4
....

**Comment by marcphilipp** [comment]
I've added a component diagram to the user guide based on @schauder's input in 6a7760559462e39b3b033f8ce9d5fe26883e23bd. You can see it here: http://junit.org/junit5/docs/snapshot/user-guide/#dependency-metadata

@junit-team/junit-lambda @schauder Do you think I put it in the right place in the documentation or would you rather move it elsewhere?

**Comment by schauder** [comment]
The Diagram and its position is fine, But it looks a little like the section title "Dependency Metadata" would refer just to the diagram (at least that's what I first thought). Therefore I'd move the diagram down in the following subsection, or add a new subsection (e.g. "Overview")

**Comment by sbrannen** [comment]
I would create a new section called _Dependency Diagram_ below the _Dependency Metadata_ section, since I don't think it makes sense to display a diagram showing artifacts that haven't been mentioned yet.

And, now that I think about it, we should likely introduce an _Artifacts_ section that briefly describes each artifact _before_ we talk about metadata and diagrams.

**Comment by sbrannen** [comment]
The _Artifacts_ section could basically quote content from existing`package-info.java
