### ISSUE TITLE
Document IntelliJ IDEA support in the User Guide

### ISSUE THREAD

**Issue by schauder** [junit-team/junit5#502]
## Status Quo

The [IDE Support](http://junit.org/junit5/docs/current/user-guide/#running-tests-ide) section in the User Guide says there is currently no IDE support, but the IDE support of IntelliJ is actually rather nice and should be mentioned there.

## Deliverables

- [ ] Document IntelliJ IDEA's support for the JUnit Platform in the User Guide

**Comment by sormuras** [comment]
Nice and almost up-to-date: https://youtrack.jetbrains.com/issue/IDEA-160756

**Comment by sbrannen** [comment]
Good catch!

I've overhauled the description and slated this for M3.

**Comment by marcphilipp** [comment]
_in progress_
