### ISSUE TITLE
Tests for gradle plugin

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#51]
Write at least one test to apply the gradle-plugin so that the most stupid mistakes don't break the build.

**Comment by marcphilipp** [comment]
Idea: Try to build it locally for testing.

**Comment by jlink** [comment]
Link to description how to test gradle plugin without pushing: https://github.com/junit-team/junit5/wiki/How-To:-Testing-JUnit5Plugin-Before-Pushing-to-GitHub

Since the plugin will hopefully superseded by native JUnit5 support in Gradle, writing of automatic tests is currently not considered to be time well spent. Closing issue.

**Comment by jlink** [comment]
Started with addind tests for gradle plugin

**Comment by jlink** [comment]
Added Spock tests to module 'junit-gradle'.
