### ISSUE TITLE
Introduce @TestsFor annotation to define the test subject

### ISSUE THREAD

**Issue by rolandkrueger** [junit-team/junit5#510]
The idea is to be able to define the concrete class which is subject of a given test class. An example could look like the following:

``` java
@TestsFor(Foo.class)
class FooTests {
    // ...
}
```

`@TestsFor` should be a class level annotation. Usage should be optional.

Having such an annotation makes it explicit which class is tested by a test class without having to rely on the test class's name to obtain this information. IDE vendors can use this information to make it possible to unambiguously navigate from a production class to all related test classes. IntelliJ IDEA already provides this feature, but (as far as I know) has to use the class name of a test class to determine all test classes for a test subject.

While in the most cases it is sufficient to use the name of a class to find all related tests, there are some situations where this approach fails or is inaccurate.
- A test class that only tests a subset of some class may conjugate parts of the tested class's name (especially for non-English class names). Contrived example: class under test is named `BuchVersand`, test class is named `BücherWerdenSonntagsNichtVersandtTests`
- The test subject has a name which is part of other unrelated class names. Example: Classes `Condition` and `VisibilityCondition`. In IntelliJ, also the `VisibilityConditionTests` will falsely be shown as test for `Condition` in addition to `ConditionTests`. 

Using a `@TestsFor` annotation could make it clear what the real class under test is for these cases. It could also be used by  reporting tools.

What do you think about this proposal? And especially, what do IDE vendors think about that?

**Comment by sbrannen** [comment]
@akozlova, what do you think about this proposal from the perspective of the IDE?

**Comment by sbrannen** [comment]
Let's keep in mind that something as generic as this may be better positioned as part of the Open Test Alliance instead of limited to the JUnit Platform.

**Comment by sbrannen** [comment]
> The idea is to be able to define the concrete class which is subject of a given test class.

IMO, the annotation would actually need to support `Class[]` instead of a single `Class` reference.

**Comment by akozlova** [comment]
As stated in the issue: IDEA searches for *MyKlass*Test pattern to detect tests (and create tests accordingly). So if people prefer to have Test e.g. as prefix, this won't work. With such annotation this ad hoc approach won't be needed and that's good. I agree that this could be more general than junit. 

What about an opposite annotation '@TestOf' so the navigation from test to class could be easier as well? Or additional parameter to @Test annotation. Not sure though if it's a good idea.

**Comment by sbrannen** [comment]
@akozlova, the proposed `@TestFor` annotation would reside on a test class. So that already takes care of navigation from the test class to the production class being tested. And, in theory, an IDE could preprocess classes in the test source tree for the presence of `@TestFor` and thereby infer a bidirectional relationship from that annotation alone.

The flip side would therefore logically be `@TestedBy`. However, I don't consider this reasonable since production code should not rely on test libraries. By that I mean that a production class (the one being tested) cannot feasibly be annotated with anything like `@TestedBy` since `@TestedBy` would come from a test library.

Even if `@TestedBy` only had source code retention, I would still feel uncomfortable requiring development teams to include such a test dependency in the classpath for production code.

**Comment by smoyer64** [comment]
I like this proposal for unit tests and if @TestFor supports Class[] perhaps some integration tests but it may not work so well for system and acceptance tests.  I think it would be useful to be able to pass a String as an alternative to a Class[].  Test classes could be annotated with the name of a user story, use case or requirement (section?) for traceability.

**Comment by sbrannen** [comment]
>  I think it would be useful to be able to pass a String as an alternative to a Class[]. Test classes could be annotated with the name of a user story, use case or requirement (section?) for traceability.

That's also worth considering. Thanks for bringing it up.

**Comment by akozlova** [comment]
> the proposed @TestFor annotation would reside on a test class. So that already takes care of navigation from the test class to the production class being tested. And, in theory, an IDE could preprocess classes in the test source tree for the presence of @TestFor and thereby infer a bidirectional relationship from that annotation alone.

Sorry, was not reading the issue :/ The suggestion indeed covers both searches and would work for both directions perfectly well.

**Comment by rolandkrueger** [comment]
Thanks for the positive feedback to my proposal.

@sbrannen, I agree that this feature belongs to the more general OTA project.

Regarding the idea for an opposite annotation `@TestedBy`, I also see that such an annotation couldn't be used since every well-configured project includes testing libraries only with test scope. So, I wouldn't propose to introduce such a feature.

When thinking about the number of classes which could be specified with this annotation, I only had unit tests in mind where one test class should only test one production class. But, of course, when taking integration tests into consideration one might want to be able to specify all affected classes. So, supporting `Class[]` would make more sense in this case. On the other hand, it is debatable whether the complete set of affected classes could (or should) be specified for an integration test. If the developer goes to far with such a list, the set of test classes displayed by an IDE as belonging to a particular production class could grow too large with a lot of irrelevant test classes. Thinking further, this could call for the introduction of more specific annotations, such as `@UnitTestFor(Class)`, `@IntegrationTestFor(Class[])`, etc., enabling IDEs to differentiate between the different test types. Just a thought :-)

@smoyer64, adding an optional String-typed `scenario` field for the annotation sounds like a good idea. So another usage of `@TestFor` could look like the following:

```
@TestFor(scenario="Discover all the foos in a bar (use case #23)")
public class SomeScenarioTest { ...
```

**Comment by jbduncan** [comment]
Regarding unit tests, there's a proposal going on to split `AssertionsTests` into multiple logical units, e.g. `AssertionsEqualsTests` (https://github.com/junit-team/junit5/issues/509), so I think it's worth having a potential `@TestFor` or `@UnitTestFor` annotation which accepts `Class[]` (not just `Class`).

**Comment by jbduncan** [comment]
Oh wait, spoke too soon!

For that proposal, it wouldn't matter whether `@(Unit)TestFor` accepted `Class` or `Class[]`, since all the subtests would test the same public class anyway.

You may ignore my previous comment. :sweat_smile:

**Comment by smoyer64** [comment]
@rolandkrueger  Your code snippet looks great but remember that it also requires that whatever attribute is assigned for the Class[] is also nullable (or defaults to empty.)  Are there cases where you might want more than one String?  (And yes, you could always put more than one use case number in a single String instead.)

**Comment by sbrannen** [comment]
If such an annotation supports a `String` or `String[]`, I would suggest calling it `usecase` or `usecases` (or perhaps `useCase` or `useCases`).

**Comment by sbrannen** [comment]
> Your code snippet looks great but remember that it also requires that whatever attribute is assigned for the Class[] is also nullable (or defaults to empty.)

While that is technically true, in practice it doesn't have to be so. In other words, it can be documented as part of the contract that either `classes` or `usecases` must be supplied and that an exception should be thrown otherwise. Of course... it's then up to the consumer to enforce the contract and out of our hands as API designers.

Just playing devil's advocate...

**Comment by rolandkrueger** [comment]
@smoyer64 I'm not sure if I correctly understand your point. I assume you mean that when the annotation has a second optional attribute `scenario`, the `Class[]`-typed `value` parameter needs to be optional, to which I agree. This would mean that `@TestFor` could be used standalone without any specified values which wouldn't hurt since a solitary `@TestFor()` would simply be a truism without any effect.

As for the question whether it would make sense to define more than one scenario, I'm not so sure if this is desirable. I think developers should be encouraged to adhere to the Single Responsibility Principle, i. e. only one scenario (or reference) per test class.

Regarding the naming of the scenario attribute, I'd say that a different name than `scenario` should be chosen if this concept is in use in a different context of the framework. So @sbrannen's proposal of `useCase` would be a better fit (or `userStory`, `reference`, or anything like that).

Eventually, the annotation could be outlined as follows:

```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Documented
public @interface TestFor {

  Class<?>[] value() default {};

  String useCase() default "";
}
```

**Comment by smoyer64** [comment]
@sbrannen @rolandkrueger 

Yes ... that's what I meant but it was obviously unclear!

**Comment by signed** [comment]
As this is a class level annotation and most of the time a test class contains multiple tests how about Test**s**For(...) instead of TestFor(...)

I do not like the additional useCase/scenario attribute. Seems to me like mixing different concerns into a single annotation (IDE navigation vs. Test documentation / grouping).

**Comment by sbrannen** [comment]
@signed agreed: `@TestsFor` is a better name. Updating the title accordingly.

**Comment by marcphilipp** [comment]
@rolandkrueger Is this issue still relevant for you? If so, we could tag it _up-for-grabs_ for a contributor to pick up.

**Comment by rolandkrueger** [comment]
@marcphilipp yes, I still think this is useful for IDEs, so it would make sense to tag it with *up-for-grabs*.
