### ISSUE TITLE
Container successful, even if tests failed.

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#519]
`TestExecutionListener`s receive a successful container finish status, even if it contained a failing test. Should a container report also as `FAILED` if it has more than zero failed tests?

See https://travis-ci.org/sormuras/beethoven/builds/161083042
Line 766 points to a failing test, line 872 is the end of the enclosing container, which reports a successful execution.

**Comment by marcphilipp** [comment]
That's by design, see Javadoc of TestExecutionListener.
