### ISSUE TITLE
TestIdentifier methods: isTest() and isContainer()

### ISSUE THREAD

**Issue by noopur2507** [junit-team/junit5#520]
TestIdentifier has these two methods: `isTest()` and `isContainer()`. As per my understanding, `isTest()` is used to identify a test case that is executed and `isContainer()` is used to identify a container of these test cases. Hence, a `@TestFactory` method is a container and not a test.

Is there anything else to the meaning of `isContainer()`? If not, these two are exactly opposite of each other and one of them can be removed.

Also, it would be useful to have another method called as `isTestFactory()`, which can be used to identify a container method. Or, is there any other way to identify a test factory method?

**Comment by orfjackal** [comment]
Related: #407

**Comment by bechte** [comment]
This issue is related with #508 and we might find a common solution. Therefore, I set it to blocked, until #508 is solved or closed.

**Comment by marcphilipp** [comment]
Resolved in #720.
