### ISSUE TITLE
DiscoverySelectors#selectJavaPackage not restricted to the provided package name

### ISSUE THREAD

**Issue by noopur2507** [junit-team/junit5#534]
I have two packages in my Java project: 
- package `samples` containing a test class `FirstTest.java`
- package `samples.one` containing a test class `SecondTest.java`

I am using the API `DiscoverySelectors.selectJavaPackage(String)` to create the request and discover the test plan while passing the package name as `samples`. The returned test plan contains both the test classes `FirstTest.java` and `SecondTest.java` whereas I expect only `FirstTest.java` to be present in the result. 

This causes the execution of the tests from the package `samples.one` also even though I selected to run the tests only from the package `samples`.

The problem is in the method `org.junit.platform.commons.util.ClasspathScanner#findClassesForPath` which uses `Files#walkFileTree` to walk the entire file tree.

**Comment by sbrannen** [comment]
Hi @noopur2507,

Thanks for raising the issue!

You're correct: package selection results in recursive classpath scanning beginning with the supplied package.

We are aware of this shortcoming and have already opened #313 to address this issue.

I am therefore closing this issue as a _duplicate_. So feel free to _subscribe_ to #313 and participate in the discussion there.

Cheers!

Sam

**Comment by sbrannen** [comment]
@noopur2507, in the interim you should be able to achieve filtering by providing a pattern to `org.junit.platform.engine.discovery.ClassFilter.includeClassNamePattern(String)` that matches against the specific package name you want to include; all other packages would then be excluded.

**Comment by noopur2507** [comment]
Thanks, I will subscribe to  #313.

In my case, if I use the pattern `samples.*` with `ClassFilter.includeClassNamePattern(String)`, it will also include the tests present in its sub-packages e.g. from `samples.one` package. So, it doesn't solve the problem.

**Comment by sbrannen** [comment]
@noopur2507, 

> In my case, if I use the pattern `samples.*` with `ClassFilter.includeClassNamePattern(String)`, it will also include the tests present in its sub-packages e.g. from `samples.one` package. So, it doesn't solve the problem.

That's because `.*` is a _greedy_ regular expression which results in the exact same behavior as the default (i.e., eager inclusion of sub-packages).

What happens if you use `"^samples\\.[^.]+Tests?$"` as the pattern?

**Comment by noopur2507** [comment]
Ah, didn't look into it properly. 
The given pattern works fine. Thanks!

**Comment by sbrannen** [comment]
Great. Glad that works for you!

**Comment by noopur2507** [comment]
Using `DiscoverySelectors.selectJavaPackage(..)` is filtering out all the test suite classes, so if the selected package contains only a test suite class, no tests are run.

Example:

I have a test suite in a separate package in that project as follows:
`package suite;`
`import org.junit.platform.runner.SelectPackages;`
`@SelectPackages("samples")`
`public class AllTests {}`

I created the request as:
`LauncherDiscoveryRequestBuilder.request()`
`.selectors(DiscoverySelectors.selectJavaPackage("suite"))`
`.filters(ClassNameFilter.includeClassNamePattern("^suite\.[^.]+$"))`
`.build();`

In `org.junit.platform.commons.util.ClasspathScanner.processClassFileSafely(..)`, the `classFilter` i.e. `IsScannableTestClass` is applied which filters out a test suite class. As a result, no tests are run.

PS: I am looking into the initial JUnit 5 support in Eclipse - [bug 488566](https://bugs.eclipse.org/bugs/show_bug.cgi?id=488566).

**Comment by sbrannen** [comment]
@noopur2507,

First and foremost, please do not start discussions on a new topic in a closed issue. Instead, please open a new issue to address the separate problem.

Secondly, as stated in the documentation, `@SelectPackages` can only be used on a class annotated with `@RunWith(JUnitPlatform.class)`. So that's why your `AllTests` class gets ignored (i.e., because it is not a test class).

Thirdly, to include multiple lines of Java source code in a comment, please use the [multi-line code formatting syntax](https://guides.github.com/features/mastering-markdown/). FYI: I updated your comment with proper syntax highlighting. So you can click on the "edit" pencil to see how it's done. 😉

**Comment by noopur2507** [comment]
Sure, thanks!
