### ISSUE TITLE
Introduce @Testable to facilitate test discovery in IDEs

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#537]
## Overview

This issue is a direct result of discussions in #504.

## Deliverables

- [ ] Introduce and use `@Testable` annotation

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Resolved in `master` in a1168ec7f4cecd3f9d9aa3a19e16ff58e1ad85bf.

**Comment by akozlova** [comment]
I think it would be useful to add link in javadoc from TestEngine to Testable so people who implement custom engine would see it.

**Comment by sbrannen** [comment]
Good idea, @akozlova.

Done: 073100f4739c99ff705471b803e91c79d8aaa7ae
