### ISSUE TITLE
Re-license Surefire Provider under ASL

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#541]
## Deliverables
- [x] Get agreement from all contributors of code under `junit-platform-surefire-provider` to change license to ASL 2.0
  - [x] @lutovich 
  - [x] @hotchemi 
  - [x] @sbrannen 
  - [x] @bechte 
  - [x] @marcphilipp
  - [x] @mmerdes
  - [x] @jlink  
- [x] Change license header to ASL for `junit-platform-surefire-provider`
- [x] Package correct LICENSE file in JAR
- [x] Update Contributor Agreement

**Comment by mmerdes** [comment]
in progress

**Comment by mmerdes** [comment]
@lutovich 
@hotchemi 
@sbrannen 
@bechte 
@marcphilipp 

Dear contributors to the junit-platform-surefire-provider module,
we would like to ask for your consent to re-license said module under the Apache License (ASL).
Please state your agreement by commenting on this issue.

Thanks a lot,
The JUnit 5 Team

**Comment by lutovich** [comment]
I agree on re-licensing junit-platform-surefire-provider under the Apache License (ASL).
Thank you!

**Comment by hotchemi** [comment]
Agreed. Haven't contributed recently but I'll try something again, thx!

**Comment by smoyer64** [comment]
If the plan is to eventually donate this code to the Surefire team, you might also need iCLAs from each contributor (https://www.apache.org/licenses/icla.pdf).  Are you working with someone from the ASF?

**Comment by marcphilipp** [comment]
> Are you working with someone from the ASF?

Yes, we're working with @britter.

**Comment by britter** [comment]
@marcphilipp thank you for taking care of this! I'll start working on the provider lookup code in surefire. For start, we will implement a lookup that pulls in the junit5 snapshot provider. After we have finished that, we're planning to integrate the provider code from Junit.

**Comment by marcphilipp** [comment]
> Dear contributors to the junit-platform-surefire-provider module,
> we would like to ask for your consent to re-license said module under the Apache License (ASL).
> Please state your agreement by commenting on this issue.

Agreed, too! :-)

**Comment by marcphilipp** [comment]
@britter Do we need signed ICLAs?

**Comment by bechte** [comment]
> Dear contributors to the junit-platform-surefire-provider module,
we would like to ask for your consent to re-license said module under the Apache License (ASL).
Please state your agreement by commenting on this issue.

I agree.

**Comment by sbrannen** [comment]
I hereby agree to the re-licensing of all work that I have contributed to the `junit-platform-surefire-provider` module under the Apache Software License (ASL 2.0).

**Comment by mmerdes** [comment]
I hereby agree to re-licensing the junit-platform-surefire-provider module under the Apache License (ASL 2.0).

**Comment by mmerdes** [comment]
@britter 
Would the version of the ASL license used, e.g., here be fine?
https://github.com/apache/maven-surefire/blob/master/maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/VerifyMojo.java

Or do we need the version quoted at the bottom of this file:
https://www.apache.org/licenses/LICENSE-2.0
?

**Comment by britter** [comment]
@marcphilipp 

> Do we need signed ICLAs?

I don't think so but I can check with our legal team.

@mmerdes 

> Would the version of the ASL license used, e.g., here be fine?

Yes, that one can be used.

**Comment by jlink** [comment]
Everything good.

2016-10-18 12:47 GMT+02:00 Matthias Merdes <notifications@github.com>:

**Comment by marcphilipp** [comment]
All source files in junit-platform-surefire-provider now use the appropriate header and the correct license is packaged in the JAR files.

**Comment by britter** [comment]
Great work everybody, thank you!
