### ISSUE TITLE
Introduce support for disabling --hide-details with JUnit Platform Gradle Plugin

### ISSUE THREAD

**Issue by leejoon** [junit-team/junit5#546]
The gradle plugin always passes --hide-details to the console launcher. I find the details to be informative without causing too much extra output.

I think it would be nice if the platform gradle plugin had a property to enable details. The default should still be to pass --hide-details.

**Comment by sbrannen** [comment]
Good idea. 👍 

I'll add this to the backlog.

**Comment by sormuras** [comment]
PR #524 already has this _solved_.

**Comment by sormuras** [comment]
Just for quick access: https://github.com/junit-team/junit5/pull/524/files#diff-e76d1c3389aef8c3546d60bb6ed45cabR100

**Comment by marcphilipp** [comment]
_in progress_ due to #524

**Comment by sbrannen** [comment]
This has been addressed in `master` in a64e354fa285ecd9297521ca327d9fbed34c21c9.
