### ISSUE TITLE
Delete deprecated ClassFilter.includeClassNamePattern(String) and @IncludeClassNamePattern

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#547]
Both `ClassFilter.includeClassNamePattern(String)` and `@IncludeClassNamePattern` were deprecated for M3 in #474.
## Deliverables
- [x] Delete `ClassFilter.includeClassNamePattern(String)`
- [x] Delete `@IncludeClassNamePattern`
- [x] Update release notes

**Comment by bechte** [comment]
see feature branch "sb_547_remove_includeClassNamePattern".

**Comment by sbrannen** [comment]
@bechte, it looks like https://github.com/junit-team/junit5/commits/sb_547_remove_includeClassNamePattern is ready to be merged into `master` -- right?

**Comment by bechte** [comment]
yes it is. I will do it right away. sorry for the delay.

**Comment by bechte** [comment]
Merged into master with #627.

**Comment by sbrannen** [comment]
@bechte, thanks for the quick turnaround!
