### ISSUE TITLE
Configure Eclipse plugin to include JOpt Simple in generated .classpath file

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#556]
## Status Quo

Due to the changes introduced in #309, executing `gradle cleanEclipse eclipse` no longer results in a generated `.classpath` file that includes the JOpt Simple dependency. Consequently, it is impossible to build the `junit-platform-console` module within Eclipse when using this mechanism.

## Deliverables

- [ ] Modify `junit-platform-console.gradle` so that the JOpt Simple dependency is once again included in the generated `.classpath` file for Eclipse.

**Comment by marcphilipp** [comment]
_in progress_
