### ISSUE TITLE
Document nullability in TestExecutionSummary.Failure

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#557]
## Status Quo

This issue picks up where #552 left off. Specifically, since `Failure` is now a public API, the nullability of values returned by its accessor methods must be properly documented.

## Deliverables

- [ ] Document nullability in `TestExecutionSummary.Failure`

**Comment by sbrannen** [comment]
Food for thought: if `null` is permissible as a return value in the affected methods, we should then perhaps consider returning a non-null `Optional` instead.

**Comment by marcphilipp** [comment]
But `null` isn't permissible, is it?

**Comment by sbrannen** [comment]
No, likely not.

I'm just saying one needs to analyze it, add precondition checks, and document it. 😉

**Comment by marcphilipp** [comment]
_in progress_
