### ISSUE TITLE
Align selectors and filters in Surefire provider with request builder API and Gradle plugin

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#558]
Follow-up on #485:

> We [...] want to align the use of filters and selectors in the Surefire provider with the style used in the Launcher's request builder API and the Gradle plugin.

### Related Issues

- #485 
- #554 

### Goal

```xml
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.19.1</version>
    <configuration>
        <properties>
            <filters>
                <tags>
                    <include>foo, bar</include>
                    <exclude>acceptance, integration</exclude>
                </tags>
            </filters>
        </properties>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-surefire-provider</artifactId>
            <version>${junit.platform.version}</version>
        </dependency>
    </dependencies>
</plugin>
```

### Deliverables

- [ ] Change `includeTags` and `excludeTags` to `include`/`exclude` and wrap them in a `tags` element that is wrapped in a `filters` element

**Comment by marcphilipp** [comment]
@Tibor17 Does Surefire support nested `properties`?

**Comment by marcphilipp** [comment]
@junit-team/junit-lambda I've changed the issue description and deliverable. Please take a look.

**Comment by sbrannen** [comment]
@marcphilipp, LGTM

**Comment by smoyer64** [comment]
I didn't want to say anything that would have biased your discussion in the other thread but I don't think you will end up with unmarshaled Java objects if you try to nest tags within <properties>.  It looks like you've found an expert to ask (above).

One important reminder is that the <groups> and <excludedGroups> tags (the aliases we created during the course of designing #485) have to remain compatible with the existing parameters for the maven-surefire-plugin's test goal.

**Comment by marcphilipp** [comment]
I will discuss with @britter when this issue can be moved to Surefire's issue tracker.

**Comment by marcphilipp** [comment]
@britter Shall we move this issue to Surefire's issue tracker now?

**Comment by marcphilipp** [comment]
I've opened an issue on Surefire's JIRA project:
https://issues.apache.org/jira/browse/SUREFIRE-1337

**Comment by britter** [comment]
@marcphilipp sorry for the late reply. Yes I think it would be good to move all issues related to the provider code to the Apache JIRA. Thank you!

**Comment by britter** [comment]
And you just created issue number 1337 😎

**Comment by marcphilipp** [comment]
> sorry for the late reply.

No worries. 🙂

> And you just created issue number 1337.

Indeed. 😎
