### ISSUE TITLE
Migrate documentation from wiki to AsciiDoc

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#56]
- [X] Migrate documentation from wiki to AsciiDoc
- [x] Extract existing Java examples from AsciiDoc into Java source files.
- [x] Move tests from sample-project to Java test source folder in documentation module and include them in the AsciiDoc documentation.

**Comment by mmerdes** [comment]
started migrating the embedded classes/tests one by one

**Comment by jlink** [comment]
fixed in mster
