### ISSUE TITLE
Introduce extensible reporting API

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#57]
- [x] Move `TestReporter` junit5-api module
- [x] Replace `Map<String, String>` with a custom class, e.g. `ReportingEntry`
- [x] Display entries in `ConsoleRunner`
- [x] Add tests for `JUnit5EngineExecutionContext#getExecutionListener()`
- [x] Add tests for `TestReporterParameterResolver`
- [x] Add tests for `ExecutionListenerAdapter`
- [x] Move `reportingEntryPublished` method to the end of `TestExecutionListener`, `EngineExecutionListener`, and their implementations.
- [x] Move ReportEntry to `junit-engine-api`. TestReporter uses Map (instead of ReportEntry) 
- [x] Added TestReporter example to documentation
- [x] Output incoming ReportEntries in junit4-runner and document that in documentation.
  - All formatted outputs of report entries should look alike (see XmlReportWriter, ColoredPrintingTestListener)

**Comment by sbrannen** [comment]
I suggest we rename `TestReporter` to `ReportEntryPublisher`.

Any objections?

**Comment by mmerdes** [comment]
Wouldn't renaming TestReporter to ReportEntryPublisher be somewhat redundant with the method named publishEntry()? 
Any opinions by anyone else?

**Comment by jlink** [comment]
I share your feeling *Publisher might be more precise but it doesn't tell us anything about the purpose.

Von meinem iPad gesendet

**Comment by jlink** [comment]
all done in master
