### ISSUE TITLE
Discover @BeforeAll/@AfterAll on static interface methods

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#571]
Currently static interface methods are not considered and thus the `@BeforeAll` / `@AfterAll` lifecycle annotations can not be used in interfaces. It would be possible to use reflection to find these methods, though.

**Comment by sbrannen** [comment]
### Analysis

`ReflectionUtils.getInterfaceMethods()` currently only detects _default methods_ in interfaces.

**Comment by sbrannen** [comment]
This has been addressed in `master` in d1657ae69d7c8c885aba8a6aad2152a5aa3e3ebb.

**Comment by nicolaiparlog** [comment]
Damn, Sam, I planned on doing this this weekend. You're too fast for your own good! :wink:

**Comment by sbrannen** [comment]
Well, the actual change was literally less than a single line of code. 

The testing and documentation took considerably longer. 😉
