### ISSUE TITLE
Access To Test Artifacts

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#572]
I started working on a [collection of JUnit extensions](https://github.com/CodeFX-org/junit-io) and would like to stay as close to JUnit as possible, e.g. regarding build tools, code style, etc. The same goes for testing so it would be great to have access to the `ExecutionEventRecorder` but, as far as I see it, the test jar [is not published](https://oss.sonatype.org/content/repositories/snapshots/org/junit/platform/junit-platform-engine/1.0.0-SNAPSHOT/).

Is there a chance to change that? If not, what git/Gradle magic could I use to build it locally?

**Comment by sbrannen** [comment]
We have considered this in the past but simply did not want to focus on maintaining the test utilities at this time. However, it is obviously worth considering. So it's basically a question of resources in terms of who has time to make it happen.

As for git/Gradle magic to access those classes outside of the JUnit 5 build, I can't think of anything off the top of my head.

**Comment by sbrannen** [comment]
Assigned to the 5.0 Backlog for the time being.

**Comment by nicolaiparlog** [comment]
Regarding maintenance, wouldn't it be a cheap way out to mark the whole thing `@API(Internal)`?

**Comment by sbrannen** [comment]
Sure. We could do that. Though it's a bit of a hack if the whole published artifact is "internal".

**Comment by Bukama** [comment]
Any updates on this topic? There's still a corresponend issue at junit-pioneer.

**Comment by marcphilipp** [comment]
Please upgrade to 5.4.2 or later and use junit-platform-testkit.
