### ISSUE TITLE
assertThrows() should use getCanonicalName() for printing exception type

### ISSUE THREAD

**Issue by kcooney** [junit-team/junit5#575]
In JUnit 4, we changed `assertThrows()` to use `Class.getCanonicalName()` so the exception messages are more readable. See https://github.com/junit-team/junit4/pull/1394 for details.

Note in that same pull, I ensured that the message would remain readable even if the string representation of the exception classes are identical (which could happen if there are multiple classloaders). Previously, the error message would be `'expected: java.lang.String<my.package.MyException>"`, which is confusing. JUnit 5 appears to have the same bug.

We should do the same thing for JUnit 5. I propose that we do this by passing the actual and expected class values to `org.opentest4j.AssertionFailedError` and have OpenTest4J print out a more human-readable message when the expected and/or actual values are classes.

**Comment by sbrannen** [comment]
Thanks, @kcooney.

I've slated this for M4.

**Comment by marcphilipp** [comment]
As in JUnit 4, when canonical name is undefined (returns null) we should fallback to using the FQCN.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
This has been addressed in commit 3a1bc3e7aec1a382328c04dd43be557732a790dc.

**Comment by sbrannen** [comment]
> I propose that we do this by passing the actual and expected class values to `org.opentest4j.AssertionFailedError` and have OpenTest4J print out a more human-readable message when the expected and/or actual values are classes.

Since `AssertionFailedError` does not currently build an error message from expected and actual values, JUnit Jupiter's assertion facilities manually take `Class` expected and actual values into account when generating error messages.

If we want to push this custom formatting off to the OTA, we will need to address that there first.
