### ISSUE TITLE
Gradle plugin JUnitPlatformExtension.platformVersion should default to plugin version

### ISSUE THREAD

**Issue by estekhin** [junit-team/junit5#576]
`JUnitPlatformExtension.platformVersion` is defined as "1.+" (dynamic version style, the most relevant documentation seems to be https://docs.gradle.org/current/userguide/dependency_management.html#sub:dynamic_versions_and_changing_modules and https://docs.gradle.org/current/userguide/dependency_management.html#sec:controlling_caching).

When building the project which uses JUnit5 Gradle plugin, Gradle will check whether `org.junit.platform:junit-platform-launcher` and `org.junit.platform:junit-platform-console` dependencies for `junitPlatform` configuration have updates. There is a small performance impact to do that, which is negligible when using default resolution strategy (recheck every 24 hours), but it can become quite noticeable if the project uses custom dependency resolution strategy with smaller cache period, in the worst case causing dependency update check on every build.

Another issue with dynamic version is that it introduces some variability into the build process when future updates to `junit-platform-launcher` and `junit-platform-console` can cause the build to fail even if the project itself has not been changed.

One can solve both of these issues by explicitly setting `junitPlatform.platformVersion` in their gradle.build to the version of `junit-platform-gradle-plugin` used (or to some other fixed value).

Please consider changing the default value of `JUnitPlatformExtension.platformVersion` to the version of the plugin so that the default behavior is more predictable, and explicit configuration with dynamic version range or some other specific version not matching the plugin's is needed only if really required by the user, not the other way around.

## Related Issues

- #609

**Comment by marcphilipp** [comment]
Sounds like a sensible thing to do.

@junit-team/junit-lambda What do you think?

**Comment by sbrannen** [comment]
Yep, sounds reasonable to me. 

We just have to make sure that our own internal use of the Gradle plugin picks the correct version, which -- as we know -- is a bit of a Texas Two-Step. 😝

**Comment by estekhin** [comment]
This is how it looks when the build depends on `junit-platform-gradle-plugin:1.0.0-M2`, plugin depends on `junit-platform-launcher:1.+` and `junit-platform-console :1.+`, and 1.0.0-M3 was released:

> [12:01:08][Step 1/1] Download .../org/junit/platform/junit-platform-launcher/1.0.0-M3/junit-platform-launcher-1.0.0-M3.pom
> [12:02:27][Step 1/1] Download .../org/junit/platform/junit-platform-console/1.0.0-M3/junit-platform-console-1.0.0-M3.pom
> [12:02:28][Step 1/1] Download .../org/junit/platform/junit-platform-engine/1.0.0-M3/junit-platform-engine-1.0.0-M3.pom
> [12:02:30][Step 1/1] Download .../org/junit/platform/junit-platform-commons/1.0.0-M3/junit-platform-commons-1.0.0-M3.pom
> [12:02:30][Step 1/1] Download .../org/junit/platform/junit-platform-launcher/1.0.0-M3/junit-platform-launcher-1.0.0-M3.jar
> [12:02:30][Step 1/1] Download .../org/junit/platform/junit-platform-console/1.0.0-M3/junit-platform-console-1.0.0-M3.jar
> [12:02:30][Step 1/1] Download .../org/junit/platform/junit-platform-engine/1.0.0-M3/junit-platform-engine-1.0.0-M3.jar
> [12:02:30][Step 1/1] Download .../org/junit/platform/junit-platform-commons/1.0.0-M3/junit-platform-commons-1.0.0-M3.jar
> [12:02:30][Step 1/1] :junitPlatformTest
> [12:02:31][:junitPlatformTest] Exception in thread "main" org.junit.platform.commons.JUnitException: Error parsing command-line arguments
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:44)
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:52)
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
> [12:02:31][:junitPlatformTest] Caused by: org.junit.platform.joptsimple.UnrecognizedOptionException: all is not a recognized option
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.joptsimple.OptionParser.parse(OptionParser.java:396)
> [12:02:31][:junitPlatformTest] 	at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:40)
> [12:02:31][:junitPlatformTest] 	... 2 more

The build which was running fine yesterday has failed today without any changes to the project itself.
It happened because plugin:1.0.0-M2 is not compatible with launcher:1.0.0-M3 due to
•The -a and --all command-line options for the ConsoleLauncher have been renamed to --scan-class-path.

The fix on the client side is trivial (just update to 1.0.0-M3) but this clearly demonstrates why the plugin should depend on the specific version of launcher and console.

And thanks for releasing 1.0.0-M3 :-)

**Comment by sormuras** [comment]
Happend at https://github.com/junit-team/junit5/issues/578 too.

**Comment by bmuschko** [comment]
+1 for declaring a concrete version for additional dependencies that need to be resolved at build time. I'd consider using a dynamic versioning scheme a bad practice as it makes the build unreproducible. It's also puts an additional burden on the end user as she/he has to declare a version through the extension in any of their builds that uses the Gradle plugin.

**Comment by marcphilipp** [comment]
Instead of hard-coding the version in the code we should try to determine the version at runtime.

Possible solutions from team brainstorming:
- Find out plugin version from JAR manifest
- Generate properties file at build time

**Comment by sbrannen** [comment]
Relates to #609

**Comment by sbrannen** [comment]
> Find out plugin version from JAR manifest

We have to keep in mind that this may be (more) challenging when running on Java 9 since the `Implementation-Version` is not available via the `Package` API when running as a _module_.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by childnode** [comment]
still, `junitPlatform.platformVersion` can't be used as reference for further compile dependencies as it is only set if you set it manually, any way to get out of this issue?

**Comment by marcphilipp** [comment]
Would #316 help?
