### ISSUE TITLE
Improve version display/selection in User Guide and Release Notes

### ISSUE THREAD

**Issue by nipafx** [junit-team/junit5#580]
As it stands the JUnit 5 project publishes a user guide (which is awesome, btw) with every milestone and also has a current one tracking master (so to speak). This is pretty cool but suffers from the problem that a lot of very similar texts exist that Google, SO, blogs and other sites index and link to in a pretty random fashion. User can easily get lost in a guide that does not apply to their version (which is hopefully current or the most recent milestone).

I have two ideas that could help users find their way around:

* Add a one-line banner that sticks to the top of the screen and announces which version this is for and whether it is the current one. Alternatively the current version could not have a banner (making the common case not annoying) and the dev version a differently styled (maybe colored) one.
* Add a list to the guide (e.g. above "1. Overview") that links to all available versions, similarly to the drop-down box in [the Hibernate docs](http://hibernate.org/orm/documentation) (on the right).

**Comment by marcphilipp** [comment]
That's very good feedback and very good ideas, thanks! 👍

**Comment by fankee** [comment]
Hey,
I would like to work on this issue if it is still available.

**Comment by marcphilipp** [comment]
Sure, go ahead! Do you have any ideas how to implement this, yet?

**Comment by sormuras** [comment]
"Out-dated" user guides (and Javadoc) can be annotated with a canonical URL that tells search engines to prefer the latest result. See https://publicobject.com/2017/02/14/canonical-urls-for-javadocs/ for details.

**Comment by kondapally1989** [comment]
Is this still up for grabs ? 
if it is, give me starting point where i can start with.

**Comment by sbrannen** [comment]
@kondapally1989, yes this is still "up for grabs" since @snigdhaAgarwal does not appear to have worked on it.

@snigdhaAgarwal, please correct me if I'm wrong about that.

**Comment by sbrannen** [comment]
>  if it is, give me starting point where i can start with.

I honestly don't know it will be achieved exactly. I can only assume it will be a combination of HTML, CSS, and JavaScript, and that will need to be incorporated into the documentation generated in the `documentation` project in this repository, which is generated using Asciidoctor.

To see how the User Guide and Release Notes are currently generated, check out the following Gradle build script: https://github.com/junit-team/junit5/blob/master/documentation/documentation.gradle

**Comment by sormuras** [comment]
https://javadoc.io already lists all JavaDoc API versions we published. From `5.0.0-M4` up to `5.3.0-RC1` as of today.

See for example:

- https://javadoc.io/doc/org.junit.jupiter/junit-jupiter-api
- https://javadoc.io/doc/org.junit.jupiter/junit-jupiter-params

All we need is a link from our User-Guide and/or README.md to this archive.

Same goes for a link to an API/ABI history page: https://abi-laboratory.pro

- https://abi-laboratory.pro/index.php?view=timeline&lang=java&l=junit-jupiter-api

**Comment by NivedhaSunderraj** [comment]
@sormuras Is this still up for grabs? If so, any specific place in the user guide where the link to https://javadoc.io  is supposed to be placed in the user guide ? And any description kind of text to accompany the link ?

**Comment by sbrannen** [comment]
I personally am not very fond of https://javadoc.io (at least for our purposes). The documentation there is based solely on artifacts published to Maven Central; whereas, "our" published Javadoc is aggregated and uses the JUnit 5 styling.

Thus, although it's probably not a bad idea to link to https://javadoc.io from somewhere (e.g., the project's top-level README), I would prefer that we link to "our" Javadoc from the User Guide.

**Comment by sbrannen** [comment]
> @sormuras Is this still up for grabs? If so, any specific place in the user guide where the link to https://javadoc.io is supposed to be placed ? And any description kind of text to accompany the link ?

Hi @NivedhaSunderraj,

Yes, this is still up for grabs.

However, the team has not actually decided on what we want. 😉 

I'll therefore add the "team discussion" label so that we (@junit-team/junit-lambda) can make up our minds.

**Comment by sbrannen** [comment]
Added _team discussion_ label and tentatively slated for 5.4 M1 so that we can nail down the deliverables for this issue.

**Comment by sormuras** [comment]
> I personally am not very fond of https://javadoc.io (at least for our purposes). The documentation there is based solely on artifacts published to Maven Central; whereas, "our" published Javadoc is aggregated and uses the JUnit 5 styling.

Sure. We will keep it the way it is today, for the current and snapshot versions. Older versions don't need to be hosted by us, imho, they can be viewed on https://javadoc.io

**Comment by marcphilipp** [comment]
Not sure how it works, but Antora has a version selector built-in:
https://docs.antora.org/antora/1.1/

**Comment by sbrannen** [comment]
> Not sure how it works, but Antora has a version selector built-in:
> https://docs.antora.org/antora/1.1/

Sounds quite nice!

https://docs.antora.org/antora/1.0/navigation/#page-dropdown

**Comment by frasercrossman** [comment]
I've tried looking into how this can be implemented and here is what I've found.

The hibernate documentation site referenced above makes no additional calls to determine the available versions of the documentation which means that either the list is generated serverside or it was statically generated. They then link to Asciidocs which, besides the URL, make no reference to the version selected. So no similar solution available there.

I've built the junit5 project and have run the asciidoc gradle task but given that there is only one version of the documentation generated I see ~~no way for us to statically generate the list of available versions~~ only two ways of generating this list statically, scraping asciidoc/release-notes/index.adoc or the filenames in that same directory. This feels like a bit of a hack. Perhaps I'm missing something. If we can agree on an approach I'm happy to implement it.

**Comment by marcphilipp** [comment]
9 years later and this has finally been done as part of #5244. 😅

**Comment by nipafx** [comment]
"Only" for 6+, though, or am I missing something?

**Comment by scordio** [comment]
I see [5.14.1](https://docs.junit.org/5.14.1/overview.html) in the dropdown.

**Comment by nipafx** [comment]
Good point, I missed that. I looked at pages for the old versions and hoped that they would be included in this. I specifically checked https://docs.junit.org/5.5.0/user-guide/index.html and https://docs.junit.org/5.10.2/user-guide/ because those are the top hits when I search Google for "JUnit 5 user guide".

**Comment by marcphilipp** [comment]
I added a banner to all old versions of user guide and release notes now:

<img width="2411" height="2061" alt="Image" src="https://github.com/user-attachments/assets/480b9aa8-3946-4e4b-91de-7634334d660b" />

Thanks for the feedback!
