### ISSUE TITLE
Add method name to report

### ISSUE THREAD

**Issue by Jessevanbekkum** [junit-team/junit5#582]
I used to work on a tool that parsed test results generated by different junit like tools (junit, karma, etc). One of the advantages of junit was that you could construct a unique name for each test result, because the combination of package + class + method is guaranteed to be unique in java.

This advantage has been lost, because of the `@DisplayName`. It is possible to generate output like this:

    <testcase name="My 1st JUnit 5 test!" classname="com.example.project.FirstTest" time="0.011"/>
    <testcase name="My 1st JUnit 5 test!" classname="com.example.project.FirstTest" time="0"/>

Although the programmer was stupid to copy the displayname without looking and these cases will not be present in good code, tools will always have to assume that multiple test results with the same xml text can exist.

Suggestion: Add the method name to the report (in the tag `method` for example) to guarantee a unique id for each test result. I think it can never hurt, and is possibly an improvement.

**Comment by marcphilipp** [comment]
Actually, we have a unique ID for each test case. However, the legacy XML format doesn't support it. We currently output it as a XML comment.

```xml
<testcase name="findAnnotationDirectlyPresentOnMethod()" classname="org.junit.platform.commons.util.AnnotationUtilsTests" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class:org.junit.platform.commons.util.AnnotationUtilsTests]/[method:findAnnotationDirectlyPresentOnMethod()]
display-name: findAnnotationDirectlyPresentOnMethod()
]]></system-out>
</testcase>
```

Having said that, we've already switched to using the method name in the `name` attribute of the `testcase` element as you suggested in #372.

**Comment by marcphilipp** [comment]
Better example:

```xml
<testcase name="testWithDisplayNameContainingSpaces()" classname="example.DisplayNameDemo" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class:example.DisplayNameDemo]/[method:testWithDisplayNameContainingSpaces()]
display-name: Custom test name containing spaces
]]></system-out>
</testcase>
```
