### ISSUE TITLE
Load and register custom TestExecutionListener implementations automatically

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#583]
What about adding support for loading custom `TestExecutionListener` implementations via the Service API to the console launcher?

Enhance (and document) [ExecuteTestsTask#registerListeners](https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/tasks/ExecuteTestsTask.java#L90) with:
```java
ServiceLoader.load(TestExecutionListener.class)
  .forEach(launcher::registerTestExecutionListeners);
```

Or add the load and register functionality to the platform `DefaultLauncher` itself?

**Comment by marcphilipp** [comment]
I think we should add them to the DefaultLauncher not just when using ConsoleLauncher. I also proposed we do this in https://github.com/junit-team/junit5/issues/542#issuecomment-257308591.

**Comment by marcphilipp** [comment]
@junit-team/junit-lambda Any objections?

**Comment by sbrannen** [comment]
No objections. Go for it!

**Comment by sbrannen** [comment]
Resolved in 3c52d958f1e3de36726724c62012d75f55db6d8b.

**Comment by marcphilipp** [comment]
This still needs to be documented in the User Guide and Release Notes. We haven't really used a consistent strategy to address that need in the past. We could reopen this issue, create a new one, or procrastinate until some poor guy wants to do a release and has to go through all the issues.

I'm in favor of the first option.

@junit-team/junit-lambda What do you think?

**Comment by sbrannen** [comment]
> This still needs to be documented in the User Guide and Release Notes. 

Oooooops. Yes... you are totally correct!

I'm in favor of reopening the original issue in such cases: no need to multiple issues for the _same issue_.

Since I prematurely closed it, I'll reopen it. 😉

**Comment by sbrannen** [comment]
In retrospect, we need to (re)define our _Definition of Done_ for issues. Though perhaps we should discuss that amongst the team and then document it in the wiki (and of course actually adhere to the rules).

**Comment by sbrannen** [comment]
Actually, I'll create an issue to address the DoD.

**Comment by sbrannen** [comment]
See #593 regarding the _Definition of Done_.
