### ISSUE TITLE
Unable to discover 2 methods in the same class

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#589]
IDEA allows users to run 2 test methods of the same test class. This is done now through `LauncherDiscoveryRequest`, like:

```java
        List<DiscoverySelector> selectors = new ArrayList<>();
          while ((line = reader.readLine()) != null) {
            selectors.add(createMethodSelector(line));
          }
          builder = builder.selectors(selectors);
          if (tagName != null && !tagName.isEmpty()) {
            builder = builder.filters(TagFilter.includeTags(tagName));
          }
          return builder.build();
```

Works well in most cases, but if both methods belong to the same class, then only the first one would be executed. After debugging it turns out that `org.junit.jupiter.engine.discovery.JavaElementsResolver#tryToResolveWithResolver` detects that there is already a corresponding class but instead of replacing newly created `ClassTestDescriptor` with old one, newly created descriptors are returned, and second method is added there and this subtree is lost.

**Comment by marcphilipp** [comment]
Thanks for reporting, @akozlova! I'll look into it right away.

**Comment by marcphilipp** [comment]
@akozlova Please take a look at #591. That's what you meant, right?

**Comment by akozlova** [comment]
Looks like your commit should fix my issue. Thanks!
