### ISSUE TITLE
Define and document Definition of Done for issues

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#593]
## Overview

In order to avoid forgetting to document issues in the User Guide and Release Notes, to avoid having appropriate tests and Javadoc in place, etc., we need to formulate an explicit _Definition of Done_ for accepting pull requests and closing issues.

## Related Material

See the discussion spawned by https://github.com/junit-team/junit5/issues/583#issuecomment-265417246.

# Deliverables

- [x] Agree upon a _Definition of Done_ including a requirements checklist.
- [x] Document the _Definition of Done_ in the wiki.
- [X] Update pull request template to include the checklist.
- [x] Update new issue template.

**Comment by nicolaiparlog** [comment]
Good idea! I think documenting it in the Wiki is a little too far away for everyday coding, though. What about extending the pull request template (e.g. with a checkbox list)? Similarly an issue template could be created.

**Comment by sbrannen** [comment]
Great ideas, @nicolaiparlog! 👍 

I think we'll document it in the wiki for thoroughness and update our templates as well.

Cheers

**Comment by marcphilipp** [comment]
First draft of DoD: https://github.com/junit-team/junit5/wiki/Definition-of-Done

@junit-team/junit-lambda Please take a look and let me know what you think. What did I miss?

**Comment by sbrannen** [comment]
I think that's a great draft. Thanks for putting it together!

The only additional things I can think of at the moment are along the line of...

- ensure preconditions are documented and checked
- follow the defined logging guidelines

**Comment by marcphilipp** [comment]
I've added both to the wiki page. Please take another look!
