### ISSUE TITLE
ConsoleLauncher does not work on M3

### ISSUE THREAD

**Issue by danilofaria** [junit-team/junit5#608]
I just migrated from M2 to M3 and found that the console launcher does not work.
In the past I had something like the following:
```java -cp "lib/*" org.junit.platform.console.ConsoleLauncher -p src -a -D```
Then after migrating to M3, I updated it to:
```java org.junit.platform.console.ConsoleLauncher -cp src --scan-class-path --hide-details```
Then I found out that it was not picking up any of my tests anymore. Is this a bug?

**Comment by marcphilipp** [comment]
`-cp src` looks strange to me. You should add directories that contain class files there. 

In addition, we've added a default class name filter that only picks up classes that end with Test or Tests. 

Does that help?

**Comment by sormuras** [comment]
`java -cp "lib/*" org.junit.platform.console.ConsoleLauncher -d src --scan-class-path --hide-details`

I guess. If you're compiling from and to `src`.

**Comment by danilofaria** [comment]
Adding ` --include-classname "^.*IT?$"` fixed it for me. My test files end with IT (for integration test), so they were not being picked up. Thanks for the hint, @marcphilipp

**Comment by sbrannen** [comment]
@danilofaria thank you for confirming that you got it working.

Closing this issue since it is not a _bug_.
