### ISSUE TITLE
Assert that parent and child have different ids in AbstractTestDescriptor#addChild?

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#615]
If child and parent have same uniqueId, things go wrong. An assertion could help engine writers to find that more quickly.

**Comment by marcphilipp** [comment]
Did that happen for you or some engine?

**Comment by akozlova** [comment]
It was a custom engine, which results in SOE in the IDE (fixed). 
To me it looked like a bug in the engine and the assertion could help to see the bug. If it's ok to have same ids, then just close the ticket. Thanks

**Comment by marcphilipp** [comment]
No, it's definitely not ok to have the same ID twice. I'm just thinking about a more general approach in the Launcher, because there must not be any duplicate ID within the complete test plan.

@junit-team/junit-lambda What do you guys think?

**Comment by sbrannen** [comment]
`AbstractTestDescriptor` already implements `equals()` and `hashCode()` based on the immutable `UniqueId` and stores children in a `Set`.

Thus, within any given level in the hierarchy, duplicates are not allowed, except that `addChild()` silently replaces an existing child if a duplicate unique ID is provided. So there is likely room for improvement there.

As for uniqueness at the level of the test plan, it's definitely a requirement that there are no duplicate unique IDs. So we should probably actually enforce that as well.
