### ISSUE TITLE
Running Cucumber with JUnit5 and Surefire exposes base64 ids.

### ISSUE THREAD

**Issue by avandeursen** [junit-team/junit5#616]
The classname set for Cucumber tests when run with Surefire in JUnit5 exposes the base64 encoding used internally in the generated XML test reports.

Original outcome when running junit4:

    grep classname target/surefire-reports/TEST-nl.tudelft.cucumber64.CucumberTest.xml

Output: 

```xml
    <testcase name="Given I have chosen to sign up" classname="Scenario: Successful sign up." time="0.001"/>
    <testcase name="When I sign up with valid details" classname="Scenario: Successful sign up." time="0"/>
    <testcase name="Then I should receive a confirmation email" classname="Scenario: Successful sign up." time="0"/> 
    <testcase name="And I should see a personalized greeting message" classname="Scenario: Successful sign up." time="0.001"/>
    <testcase name="Scenario: Successful sign up." classname="Scenario: Successful sign up." time="0.001"/>    
```

Note that the classname is not a real class, but the name of the scenario executed extracted from a `.feature` file. The underlying magic is done by the Cucumber Junit4 test runner.

Doing the same when using the JUnit 5 Surefire yields as output:

```xml
    <testcase 
      name="Given I have chosen to sign up" 
      classname=
        "[engine:junit-vintage]
        /[runner:nl.tudelft.cucumber64.CucumberTest]
        /[test:rO0ABXNyAB9naGVya2luLmZvcm1hdHRlci5tb2RlbC5GZWF0dXJlAAAAAAAAAAECAAB4cgAkZ2hlcmtpbi5mb3JtYXR0ZXIubW9kZWwuVGFnU3RhdGVtZW50AAAAAAAAAAECAAJMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wABHRhZ3N0ABBMamF2YS91dGlsL0xpc3Q7eHIAKmdoZXJraW4uZm9ybWF0dGVyLm1vZGVsLkRlc2NyaWJlZFN0YXRlbWVudInoQ7yJkLCFAgABTAALZGVzY3JpcHRpb25xAH4AAnhyACZnaGVya2luLmZvcm1hdHRlci5tb2RlbC5CYXNpY1N0YXRlbWVudPM3wIsDVBUvAgAETAAIY29tbWVudHNxAH4AA0wAB2tleXdvcmRxAH4AAkwABGxpbmV0ABNMamF2YS9sYW5nL0ludGVnZXI7TAAEbmFtZXEAfgACeHIAGmdoZXJraW4uZm9ybWF0dGVyLk1hcHBhYmxl42CLFPnowjUCAAB4cHNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAAAdwQAAAAAeHQAB0ZlYXR1cmVzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGphdmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAAAXQACFNpZ24gdXAudAAlU2lnbiB1cCBzaG91bGQgYmUgcXVpY2sgYW5kIGZyaWVuZGx5LnQACHNpZ24tdXAuc3EAfgAJAAAAAHcEAAAAAHg=]
        /[test:rO0ABXNyACBnaGVya2luLmZvcm1hdHRlci5tb2RlbC5TY2VuYXJpbwAAAAAAAAABAgABTAAEdHlwZXQAEkxqYXZhL2xhbmcvU3RyaW5nO3hyACRnaGVya2luLmZvcm1hdHRlci5tb2RlbC5UYWdTdGF0ZW1lbnQAAAAAAAAAAQIAAkwAAmlkcQB+AAFMAAR0YWdzdAAQTGphdmEvdXRpbC9MaXN0O3hyACpnaGVya2luLmZvcm1hdHRlci5tb2RlbC5EZXNjcmliZWRTdGF0ZW1lbnSJ6EO8iZCwhQIAAUwAC2Rlc2NyaXB0aW9ucQB+AAF4cgAmZ2hlcmtpbi5mb3JtYXR0ZXIubW9kZWwuQmFzaWNTdGF0ZW1lbnTzN8CLA1QVLwIABEwACGNvbW1lbnRzcQB+AANMAAdrZXl3b3JkcQB+AAFMAARsaW5ldAATTGphdmEvbGFuZy9JbnRlZ2VyO0wABG5hbWVxAH4AAXhyABpnaGVya2luLmZvcm1hdHRlci5NYXBwYWJsZeNgixT56MI1AgAAeHBzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAHcEAAAAAHh0AAhTY2VuYXJpb3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAAAEdAATU3VjY2Vzc2Z1bCBzaWduIHVwLnQAXE5ldyB1c2VycyBzaG91bGQgZ2V0IGEgY29uZmlybWF0aW9uIGVtYWlsIGFuZCBncmVldGVkIHBlcnNvbmFsbHkgYnkgdGhlIHNpdGUgb25jZSBzaWduZWQgaW4udAAcc2lnbi11cC47c3VjY2Vzc2Z1bC1zaWduLXVwLnNxAH4ACQAAAAB3BAAAAAB4dAAIc2NlbmFyaW8=]
        /[test:rO0ABXNyABxnaGVya2luLmZvcm1hdHRlci5tb2RlbC5TdGVwAAAAAAAAAAECAAJMAApkb2Nfc3RyaW5ndAAjTGdoZXJraW4vZm9ybWF0dGVyL21vZGVsL0RvY1N0cmluZztMAARyb3dzdAAQTGphdmEvdXRpbC9MaXN0O3hyACZnaGVya2luLmZvcm1hdHRlci5tb2RlbC5CYXNpY1N0YXRlbWVudPM3wIsDVBUvAgAETAAIY29tbWVudHNxAH4AAkwAB2tleXdvcmR0ABJMamF2YS9sYW5nL1N0cmluZztMAARsaW5ldAATTGphdmEvbGFuZy9JbnRlZ2VyO0wABG5hbWVxAH4ABHhyABpnaGVya2luLmZvcm1hdHRlci5NYXBwYWJsZeNgixT56MI1AgAAeHBzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAHcEAAAAAHh0AAZHaXZlbiBzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGphdmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAAB3QAGEkgaGF2ZSBjaG9zZW4gdG8gc2lnbiB1cHBw]"
      time="0.005"/>    
```

This behavior is incompatible with JUnit4. The base64 names also appear in the Surefire reports generated by the `mvn site` plugin.

In the long run, the Cucumber team will probably need to create a JUnit5 extension to run their features. But it would be nice if running Cucumber with JUnit5 would yield the same reports as when running with JUnit4.

I created a simple maven project to reproduce this issue at https://github.com/avandeursen/cucumber64

**Comment by marcphilipp** [comment]
@avandeursen BTW I think @signed already had some ideas about a custom Cucumber engine.

The unique IDs of the `TestIdentifier` are used by our `RunListenerAdapter` implementation when the Java class name cannot be determined. We could instead fallback to the parent's display name.

**Comment by avandeursen** [comment]
Thanks!

The `RunListenerAdapter` code you are talking about is here I think:

https://github.com/junit-team/junit5/blob/r5.0.0-M3/junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/RunListenerAdapter.java#L89

At that program point, the `testIdentifier` can indeed be used to get the `parentId()`, which is quite similar to the uniqueId of the testIdentifier itself (i.e., both are of the form `[engine:junit-vintage]/[runner:nl.tudelft.cucumber64.CucumberTest]/[test:rO0ABXNyAB9naGV....`)

And how can the parentId be turned into a displayName at that program point?

**Comment by marcphilipp** [comment]
`RunListenerAdapter` needs to implement `testPlanExecutionStarted()` and store a reference to the current `TestPlan`. It can then use `TestPlan.getParent()` to get the parent `TestIdentifier` of the test.

**Comment by avandeursen** [comment]
Ok, thanks. I will look into this.

**Comment by signed** [comment]
I have not spend much thought about the report format yet.
Currently my [implementation][junit-cucumber-engine] produces the following report when running your example (no vintage or jupiter engine present on the surefire classpath):
````
<testcase name="Given I have chosen to sign up" classname="nl.tudelft.cucumber64.FeatureSteps" time="0.125"/>
<testcase name="When I sign up with valid details" classname="nl.tudelft.cucumber64.FeatureSteps" time="0"/>
<testcase name="Then I should receive a confirmation email" classname="nl.tudelft.cucumber64.FeatureSteps" time="0"/>
<testcase name="And I should see a personalized greeting message" classname="nl.tudelft.cucumber64.FeatureSteps" time="0"/>
````

I guess the classname is derived from the *MethodSource* I attached to the TestDescriptor.
But no clue where this happens within junit. For navigation in the IDE I'd like to keep the method source in the TestDescriptor.

Is there some way for the engine to influence how the report is generated?

[junit-cucumber-engine]: https://github.com/signed/junit-cucumber-engine

**Comment by avandeursen** [comment]
Thanks @signed. I'll have a look at your implementation and your question.

Almost done with the change suggested by @marcphilipp in https://github.com/junit-team/junit5/issues/616#issuecomment-269645324 -- pull request will follow shortly.

**Comment by marcphilipp** [comment]
> I guess the classname is derived from the `MethodSource` I attached to the TestDescriptor.

Indeed! That made me realize that it's actually wrong to derive it that way, e.g. in the following case.

### AbstractTestClass.java
```java
package com.example.project;

import org.junit.jupiter.api.Test;

class AbstractTestClass {
    @Test
    void test() {
    }
}
```

### Sub1Tests.java
```java
package com.example.project;

class Sub1Tests extends AbstractTestClass {
}
```

### Sub2Tests.java
```java
package com.example.project;

class Sub2Tests extends AbstractTestClass {
}
```

In this case the Surefire reports will look like this:

### TEST-com.example.project.Sub1Tests.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="com.example.project.Sub1Tests" time="0.03" tests="1" errors="0" skipped="0" failures="0">
  <properties>
    ...
  </properties>
  <testcase name="test" classname="com.example.project.AbstractTestClass" time="0.005"/>
</testsuite>
```

### TEST-com.example.project.Sub2Tests.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="com.example.project.Sub2Tests" time="0.03" tests="1" errors="0" skipped="0" failures="0">
  <properties>
    ...
  </properties>
  <testcase name="test" classname="com.example.project.AbstractTestClass" time="0.005"/>
</testsuite>
```

In both cases, the `classname` is derived from the `MethodSource` which _correctly_ points to the source location of the test case. However, `classname` should be `com.example.project.Sub1Tests` and `com.example.project.Sub2Tests`, respectively.

> Is there some way for the engine to influence how the report is generated?

I think that would be a good way out of this dilemma for this "legacy" XML report. Ultimately, we need a new reporting format (see #373).

@junit-team/junit-lambda What do you think about adding a way for a `TestIdentifier` to specify `classname` and `methodname`? We could make it optional and fallback to using display names.

**Comment by sbrannen** [comment]
> @junit-team/junit-lambda What do you think about adding a way for a `TestIdentifier` to specify `classname` and `methodname`? We could make it optional and fallback to using display names.

As long as its optional (i.e., has a _default_ implementation) and well documented, I think it would be OK to introduce those.

**Comment by avandeursen** [comment]
The `RunListenerAdapter.java` class presently has a `getMethodName` and `getClassName` method for a `TestIdentifier`. That is a feature envy smell indeed, so these could be moved as default implementations to the `TestIdentifier` class.

All `TestIdentifiers` appear to be created from `TestDescriptions`. Does every `TestDescription` subclass have a natural response for getMethod/Class-Name?

The `instanceof` on `TestSource` needed for the implementation of getMethod/Class is fishy too. This suggests a need to move these methods to `TestSource` and its appropriate subclasses.

To solve the subclass1/2 problem raised by @marcphilipp clients should also be able to _set_ the method/class name (for reporting purposes).

**Comment by marcphilipp** [comment]
> The `RunListenerAdapter.java` class presently has a `getMethodName` and `getClassName` method for a `TestIdentifier`. That is a feature envy smell indeed, so these could be moved as default implementations to the `TestIdentifier` class.
> 
> All `TestIdentifiers` appear to be created from `TestDescriptions`. Does every `TestDescription` subclass have a natural response for getMethod/Class-Name?

A `TestIdentifier` is the final and serializable DTO used in the Launcher API to report the test plan to IDEs and build tools. It's just a data container without any behavior that may even be transferred across VMs/processes. `TestDescriptors` are used by test engines to represent the test tree they have discovered and potentially also to attach execution behavior to it. It is designed to be subclassed and doesn't have to be serializable.

I propose that we add a `default` method to `TestDescriptor`, e.g. `getLegacyReportingInfos() : LegacyReportingInfos` where `LegacyReportingInfos` is an interface with two methods: `getName() : String` and `getClassName() : Optional<String>`. We should provide a `DefaultLegacyReportingInfo` that extends Serializable and stores two strings in final fields in the `support` package. The default implementation simply returns `getDisplayName()` in `getName()` and `getParent().map(TestDescriptor::getDisplayName)` in `getClassName()`. In `TestIdentifier.from(TestDescriptor)` we should store an `DefaultLegacyReportingInfo` to make sure `TestIdentifier` is serializable.

Does that make sense?

> The `instanceof` on `TestSource` needed for the implementation of getMethod/Class is fishy too. This suggests a need to move these methods to `TestSource` and its appropriate subclasses.

That may look fishy but we also want to support engines that work on files etc. (see `FileSource`) so moving `getMethod/Class()` to `TestSource` does not seem natural either.

**Comment by sbrannen** [comment]
@marcphilipp, your proposal sounds reasonable to me.

But please make sure to call the thing `LegacyReportingInfo` without the "s". Pluralizing "info" is _typisch deutsch_ (and I'm hoping you don't take offense at that). 😉

**Comment by marcphilipp** [comment]
@sbrannen Ah, makes sense, thanks for the info(s). 😉

**Comment by sbrannen** [comment]
@marcphilipp, I'm always glad to provide _Infos_ [sic]!

**Comment by marcphilipp** [comment]
@avandeursen Do you have time to work on this issue? Or is it something your students could work on?

**Comment by LiamClark** [comment]
@marcphilipp

One of @avandeursen 's students here, i'm going to give this a shot.
I think i implemented your proposal correctly, now working to get it into the RunListenerAdapter.
