### ISSUE TITLE
Support for discovering and launching tests on Java 7

### ISSUE THREAD

**Issue by bmuschko** [junit-team/junit5#619]
Tool providers that want to discover and launch JUnit 5-based tests with the help of the [JUnit Platform Launcher API](http://junit.org/junit5/docs/current/user-guide/#launcher-api) are currently limited to the use of Java 8. Some of the methods exposed by the Launcher API only work with Java 8 language level and do not provide an alternative e.g. the use of static interface methods like [`ClassNameFilter.includeClassNamePatterns `](https://github.com/junit-team/junit5/blob/master/junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassNameFilter.java#L59).

Do you have plans to support an API fully usable with Java 7? I am asking specifically as a follow up for a [discussion on the Gradle forum](https://discuss.gradle.org/t/core-support-for-junit-platform-a-k-a-junit-5/19487/3):

> It seems that JUnit Platform only supports Java 8 and higher. We will need to keep in mind that Gradle 3.x still supports Java 7. That's ok, we fork a new JVM for tests and can enforce Java8+ semantics at runtime. That just means that we cannot introduce compile-time dependencies to Gradle that don't compile on Java 7.

**Comment by marcphilipp** [comment]
I am not sure I understand you completely. Even if we wouldn't use Java 8 language features in our public APIs we would still require a Java 8 runtime. How would that help?

Since you fork a new JVM for test execution, the code that is being executed on that JVM could make use of Java 8 language features, couldn't it?

**Comment by bmuschko** [comment]
> I am not sure I understand you completely. 

Maybe there's something that I am still missing. Let me try to explain in more detail.

> Even if we wouldn't use Java 8 language features in our public APIs we would still require a Java 8 runtime. How would that help?

The [Gradle source code](https://github.com/gradle/gradle) in its current form is built as a multi-module project and distributed as a single ZIP file. The [source compatibility version for the most part is 1.7](https://github.com/gradle/gradle/blob/master/gradle/groovyProject.gradle#L10). When compiling the code, we cannot use Java 8 language features or an API that exposes methods based on Java 8 language features. That's the case for `ClassNameFilter.includeClassNamePatterns` for example when trying to create a `Filter` instance. Currently, `IncludeClassNameFilter` is package private so I can't work around it but just instantiating it. At the moment the existing Gradle code that deals with test detection and execution is fully based on 1.7. So if we'd try to use the JUnit Launcher API we couldn't. The Java 8 runtime comes into play when we discover and execute the tests in a forked JVM. I guess we could work our way around it by using `org.junit.platform.console.ConsoleLauncher` for the forked test JVM but it would give us less control than the programmatic approach of the JUnit Launcher API.

> Since you fork a new JVM for test execution, the code that is being executed on that JVM could make use of Java 8 language features, couldn't it?

That's correct.

**Comment by marcphilipp** [comment]
I'm assuming that you need to have some code in addition to the Launcher and its dependencies running on the forked JVM, e.g. to handle inter-process communication of discovery/execution request and events. Can you move that code into a separate module that has a different source compatibility?

**Comment by bmuschko** [comment]
Yes, we do but I'd have to check how much of the code has to be detangled. We'll have to rethink the Gradle support for our testing infrastructure anyway. Moving the code to a different module and using 1.8 as source compatibility might work. Something we'd have to evaluate and discuss internally first. I'd be a bit concerned about bundling the Java 8-based JARs for `junit-platform-engine` and `junit-platform-launcher` with the Gradle distribution. I don't think it would have any side-effects but it would have to be proven.

In the long run, we are also planning to look into the following options though I don't have a concrete time horizon: 

- Break up Gradle into smaller components with different repositories and release cycles.
- Support Java 8.

To come back to my original question it sounds like the JUnit team does not have plans to support and release a Java 7-compatible version of JUnit 5. Is that correct? To be honest I'd totally understand your point of view if you wouldn't want to support Java 7. :-)

**Comment by sbrannen** [comment]
> Do you have plans to support an API fully usable with Java 7?

To answer your original question: No, we do not currently have any plans to support any version of Java prior to Java 8 for the JUnit Platform or JUnit Jupiter.

**Comment by marcphilipp** [comment]
> I'd be a bit concerned about bundling the Java 8-based JARs for `junit-platform-engine` and `junit-platform-launcher` with the Gradle distribution. I don't think it would have any side-effects but it would have to be proven.

I know for other "core" plugins, e.g. Checkstyle, there's a `toolVersion` property. How is dependency resolution done in those cases? I'm assuming it uses the regular dependency resolution mechanism. Is the default version of the tool bundled with the Gradle distribution in these cases?

**Comment by bmuschko** [comment]
> To answer your original question: No, we do not currently have any plans to support any version of Java prior to Java 8 for the JUnit Platform or JUnit Jupiter.

Thanks for clarifying.

> I know for other "core" plugins, e.g. Checkstyle, there's a toolVersion property. How is dependency resolution done in those cases? I'm assuming it uses the regular dependency resolution mechanism. Is the default version of the tool bundled with the Gradle distribution in these cases?

For the static code analysis plugins that come with Gradle we use the Ant libraries provided by the corresponding tool. Gradle does not use a programmatic API when for those tools - meaning we don't need to have a compile-time dependency on their API. Instead we build the Ant syntax at runtime, resolve the declared dependency for the `toolVersion` and execute the command using [AntBuilder](http://docs.groovy-lang.org/latest/html/documentation/ant-builder.html). The static code analysis libraries are not bundled with the Gradle runtime. In a way the mechanism is comparable to using [JUnit Platform Console](https://github.com/junit-team/junit5/tree/master/junit-platform-console) in your Gradle plugin.
