### ISSUE TITLE
Add support for scanning JAR files as classpath roots

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#620]
## Overview

We currently scan JAR files but only when resolving package selectors. We should add support for explicitly selecting a JAR as a classpath root to be scanned, i.e. using the `ConsoleLauncher` with  `--scan-classpath some.jar` should scan that JAR.

## Deliverables

- [ ] Change `DiscoverySelectors.selectClasspathRoots(Set<Path>)` to accept JAR files in addition to directories.
- [ ] Change `ClasspathScanner.scanForClassesInClasspathRoot(...)` to process JAR files in addition to directories.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by smoyer64** [comment]
>   We currently scan JAR files but only when resolving package selectors.

I ran into this when I was working on the beginnings of the API tools but didn't have time to determine what was happening.  It appears that the code I already have might just work when I get back to it!
