### ISSUE TITLE
Console Launcher has no flag to run all discovered tests

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#621]
It looks like in M3 `-a` is gone which allowed to simply run all discovered tests. I can see no alternative - do I have to use `-p org` or is there something shorter?

**Comment by marcphilipp** [comment]
`-a` has been superseded by `--scan-classpath`.

**Comment by nicolaiparlog** [comment]
True, damn. I tried that option before but couldn't make it work so I filed it under "don't know what it does". 😄
