### ISSUE TITLE
Remove 'hide-details' from console options

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#629]
## Background

Option `--hide-details` is deprecated by #524 and replaced by `--details none`.

## Deliverables

- [ ] Remove the following lines in class `org.junit.platform.console.options.AvailableOptions`:
```
// TODO Remove "hide-details" before final release. Only here to make "legacy" Gradle plugin happy.
// If removed, an old Gradle:junitPlatformTest will report:
//   Exception in thread "main" joptsimple.UnrecognizedOptionException: hide-details is not a recognized option
parser.accepts("hide-details", "@Deprecated. Use '--details none' instead.");
```

- [ ] Update `documentation/src/docs/asciidoc/running-tests.adoc` by removing line:
```
--hide-details                                @Deprecated. Use '--details none' instead.
```

- [ ] Update `documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc` by adding line:
```
* `--hide-details` option of the `ConsoleLauncher` is removed, use `--details none` instead.
```

- [x] Update User-Guide with latest example tree http://junit.org/junit5/docs/snapshot/user-guide/#running-tests-console-launcher

**Comment by sbrannen** [comment]
Thanks for creating this follow-up ticket.
