### ISSUE TITLE
Gradle Plugin: Does not publish events to IntelliJ when using IntelliJ's "delegate Gradle run actions" feature

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#641]
(Not sure the best path to file this issue since it is related to both IntelliJ and the Gradle plugin)

## Overview

When using the [delegate Gradle run actions to Gradle](https://www.jetbrains.com/help/idea/2016.3/working-with-gradle-tasks-in-gradle-tool-window.html) option in IntelliJ test events are not received (so IDE indications).

## Version Info

* IntelliJ version: 2017.1 EAP
* Gradle Version: 3.3
* `'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M3'`
* `'org.junit.jupiter:junit-jupiter-api:5.0.0-M3'`
* `'org.junit.jupiter:junit-jupiter-engine:5.0.0-M3'`

## Details

I originally posted this on the [Gradle forum](https://discuss.gradle.org/t/junit-5-gradle-and-intellij-publishing-test-events-for-tooling-api-consumers/21349)

> JUnit 5 development is in progress, and there is [gradle/gradle#1037](https://github.com/gradle/gradle/issues/1037) for integrating it natively into Gradle. Right now, the JUnit 5 team has built a [simple plugin](https://github.com/junit-team/junit5/tree/master/junit-platform-gradle-plugin) that can be used until the support is built directly in.
>
> IntelliJ can [delegate Gradle run actions to Gradle](https://www.jetbrains.com/help/idea/2016.3/working-with-gradle-tasks-in-gradle-tool-window.html). I believe that IntelliJ uses the [tooling API](https://docs.gradle.org/current/userguide/embedding.html) to launch these tests as well as receive events for them.
>
> When using the current JUnit 5 plugin and the delegating run actions, IntelliJ displays "No events found", which makes sense.
>
> What I'm trying to figure out is, how can the current JUnit 5 plugin be adapted to publish test events so that IntelliJ can receive them?

It would be nice if running Gradle in this manner from IntelliJ would produce the same results as using IntelliJ's Platform runner.

**Comment by marcphilipp** [comment]
> It would be nice if running Gradle in this manner from IntelliJ would produce the same results as using IntelliJ's Platform runner.

Agreed. However, this can only be achieved through a native Gradle integration which is being worked on in gradle/gradle#1037. Therefore, I'm closing this issue as "won't fix" for now.
