### ISSUE TITLE
Add integration test to ensure Jupiter engine correctly runs tests

### ISSUE THREAD

**Issue by kcooney** [junit-team/junit5#648]
Most of the tests are written in JUnit5-style. This is good in the sense that we want to try out our APIs, but bad because regressions in the framework can cause failing tests to pass or can filter tests entirely. One example was in the initial version of #647 where an incorrect usage of a Stream's `filter()` method removed all tests from being run.

We should have some kind of integration test that runs some sample tests (which includes failing and passing tests), reads the output, and ensures that we get the expected result. This integration test should not be written as a JUnit5-style test (for obvious reasons).

Some initial discussion for this is in the comments for #647

**Comment by sormuras** [comment]
in progress
