### ISSUE TITLE
Not possible to run multiple methods in one test class

### ISSUE THREAD

**Issue by gdiegel** [junit-team/junit5#653]
## Overview

If two or more test methods are selected to be run in a org.junit.platform.launcher.Launcher with the method org.junit.platform.engine.discovery.DiscoverySelectors#selectMethod(java.lang.String, java.lang.String), only the first of them is actually run. It seems that the other methods are removed from the TestDescriptor in org.junit.jupiter.engine.discovery.DiscoverySelectorResolver#pruneTree.

Expected behavior: All selected test methods in a test class are run.
Actual behavior: Only the first test method is run. 

## Deliverables

Minimal working example in https://github.com/gdiegel/select-method.

**Comment by sormuras** [comment]
Works for me.

If I change the `selectMethod` statements to:
```
selectMethod(TestClassWithTwoMethods.class, "one"),
selectMethod(TestClassWithTwoMethods.class, "two")
```
both are executed as well. Can you try that at your site, please?

**Comment by gdiegel** [comment]
Hi @sormuras,

I can confirm that either way works with the SNAPSHOT version.

Thanks!

**Comment by sormuras** [comment]
Just found the entry in the [M4](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes-5.0.0-m4) release notes:
> JUnit Jupiter
> Bug Fixes
> Fix bug that prevented discovery of two or more methods of the same class.
