### ISSUE TITLE
Test tree prints ReportEntry(ies) outside the hierarchy

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#663]
## Overview

When printing the test tree results via Gradle or the console runner, ```ReportEntry``` rows are printed before their corresponding tests.  In the following example, I've hacked multiple ```ReportEntry``` rows into the ```TimingExtension``` to better illustrate the issue:

```
│  ├─ TimingExtensionTests
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.559, Method execution time1 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.559, Method execution time2 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.559, Method execution time3 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.560, Method execution time4 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.560, Method execution time5 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.560, Method execution time6 (in mS) = '21']
│  │  ├─ sleep20ms() ✔
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.612, Method execution time1 (in mS) = '51']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.613, Method execution time2 (in mS) = '51']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.614, Method execution time3 (in mS) = '51']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.614, Method execution time4 (in mS) = '51']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.616, Method execution time5 (in mS) = '51']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.622, Method execution time6 (in mS) = '51']
│  │  ├─ sleep50ms() ✔
```

- (X) **Bug report.** The test method name is still rooted to the test class name via the tree's connection lines, so leaving the ```ReportEntry``` lines unconnected.  

## Deliverables

- [ ] Move the ```ReportEntry``` lines so that they're printed below their corresponding test's name as follows:

```
│  ├─ TimingExtensionTests
│  │  ├─ sleep20ms() ✔
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.559, Method execution time1 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.559, Method execution time2 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.559, Method execution time3 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.560, Method execution time4 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.560, Method execution time5 (in mS) = '21']
│  │  │   ReportEntry [timestamp = 2017-02-18T19:57:24.560, Method execution time6 (in mS) = '21']
│  │  └─ sleep50ms() ✔
│  │       ReportEntry [timestamp = 2017-02-18T19:57:24.612, Method execution time1 (in mS) = '51']
│  │       ReportEntry [timestamp = 2017-02-18T19:57:24.613, Method execution time2 (in mS) = '51']
│  │       ReportEntry [timestamp = 2017-02-18T19:57:24.614, Method execution time3 (in mS) = '51']
│  │       ReportEntry [timestamp = 2017-02-18T19:57:24.614, Method execution time4 (in mS) = '51']
│  │       ReportEntry [timestamp = 2017-02-18T19:57:24.616, Method execution time5 (in mS) = '51']
│  │       ReportEntry [timestamp = 2017-02-18T19:57:24.622, Method execution time6 (in mS) = '51']
```

Also note that I've adjusted the tree hierarchy to properly terminate the connection line at the last node of the hierarchy as described in issue #664.

**Comment by sormuras** [comment]
@smoyer64 Thanks for the thorough analysis. I'll look into the issues next week, but the current **tree** implementation focusses on being simple:

- print events immediatly (don't buffer at all)
- don't look ahead of execution (no chance to know if you're the last test in a container)
- don't use ANSI controls to move the cursor around

The **verbose** tree is doing a better job in displaying things at the expected places.

**Comment by smoyer64** [comment]
@sormuras I certainly don't mean to minimize all the work that's gone into the current tree printer ... it's a tough problem - this article was recently posted to HackerNews: https://pcmonk.wordpress.com/2014/04/01/why-dont-we-have-a-general-purpose-tree-editor/.  I won't argue with your third bullet as it adds a whole layer of complexity (and test output should be more like output to a line printer).  For the first and second bullets, what happens if the tests are run concurrently?

Thanks for all the work you've put into this ... I certainly appreciate it!

**Comment by sormuras** [comment]
> For the first and second bullets, what happens if the tests are run concurrently?

It all goes down the same road that every console output does, when it doesn't care about synchronization: http://stackoverflow.com/a/9459886/1431016 -- see #666 "the threaded number of the beast" (-:

**Comment by smoyer64** [comment]
Haha ... I chuckled to myself when that issue was assigned #666 as it seemed really appropriate.  I wonder if we'd say that regardless of what issue won that lottery though.
