### ISSUE TITLE
Test tree printer should not continue connection lines past terminal nodes

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#664]
## Overview

The tree printer continues hierarchy connection lines past terminal nodes as shown below:

```
│  ├─ A stack
│  │  ├─ is instantiated with new Stack() ✔
│  │  ├─ when new
│  │  │  ├─ throws EmptyStackException when popped ✔
│  │  │  ├─ throws EmptyStackException when peeked ✔
│  │  │  ├─ is empty ✔
│  │  │  ├─ after pushing an element
│  │  │  │  ├─ it is no longer empty ✔
│  │  │  │  ├─ returns the element when peeked but remains not empty ✔
│  │  │  │  ├─ returns the element when popped and is empty ✔
```

- (X) **Bug report.** It's conventional to use the lower-left corner character to indicate that a node is the last node in a particular level of the hierarchy.

## Deliverables

- [ ] Detect the last node in a given level of the hierarchy and use the lower-left corner character (extended ASCII 192 or the unicode equivalent) to discontinue the hierarchy's connection line as shown below:

```
│  ├─ A stack
│  │  ├─ is instantiated with new Stack() ✔
│  │  └─ when new
│  │      ├─ throws EmptyStackException when popped ✔
│  │      ├─ throws EmptyStackException when peeked ✔
│  │      ├─ is empty ✔
│  │      └─ after pushing an element
│  │          ├─ it is no longer empty ✔
│  │          ├─ returns the element when peeked but remains not empty ✔
│  │          └─ returns the element when popped and is empty ✔
```

**Comment by sormuras** [comment]
Will be implemented with the caveat that the tree is no longer printed immediately. The two other details modes, namely `FLAT` and `VEROSE`, will remain as-is.

**Comment by sormuras** [comment]
Getting closer: https://travis-ci.org/junit-team/junit5/jobs/207683435#L519

**Comment by gaganis** [comment]
@sormuras Looks nice!

**Comment by sormuras** [comment]
Thanks for the thumbs.

What do you think of the aligned/grouped test report entry rendering: https://travis-ci.org/junit-team/junit5/jobs/207891095#L612 ?

**Comment by smoyer64** [comment]
@sormuras I like the way the test report's date is inset from the test name which implies another level of nesting in the hierarchy.  In fact I think it's better without lines.  There's one other possibility to include in your demo ... a test that has multiple single-line report entries (which could potentially have different timestamps).

I personally like aligning the separators when showing key/value data because it makes it more like a table but I wouldn't hold this issue up for that.  I think you've gone above and beyond the call of duty on the test tree printer!

**Comment by smoyer64** [comment]
@sormuras I like the way the test report's date is inset from the test name which implies another level of nesting in the hierarchy.  In fact I think it's better without lines.  There's one other possibility to include in your demo ... a test that has multiple single-line report entries (which could potentially have different timestamps).

I personally like aligning the separators when showing key/value data because it makes it more like a table but I wouldn't hold this issue up for that.  I think you've gone above and beyond the call of duty on the test tree printer!

**Comment by sormuras** [comment]
> [...] a test that has multiple single-line report entries (which could potentially have different timestamps).

Current iteration already covers that in a test. https://github.com/junit-team/junit5/compare/refactor_tree_printing_listener#diff-bcdd220ee20a4cdae2c4835d9e21e65bR163 May enhance the documentation demo as well.

**Comment by marcphilipp** [comment]
Looks good!

**Comment by sormuras** [comment]
Do you think an optional caption for a test report set is worth the effort? See https://github.com/junit-team/junit5/pull/711/files#r104756183

**Comment by marcphilipp** [comment]
Probably not right now. Shall we create a separate issue?

**Comment by sormuras** [comment]
M5 or 5.1. Fine with me.
