### ISSUE TITLE
Add alternate runners for the documentation examples

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#665]
## Overview

It should be easy for new JUnit 5 users to execute the examples provided in the documentation project.  Current it's easy to run these demos and tests using the Gradle runner by executing the following command in the parent project:

```
./gradlew documentation:junitPlatformTest
```

- (X) **Feature request.** We should make it just as easy for Maven and Console users to execute these tests and to view the output provided by that runner.

## Deliverables

The following files should be added to the documentation project:

- [x] A Maven POM
- [ ] A Windows batch file (.bat) to launch the console runner on Windows
- [x] A Bash shell file (.sh) to launch the console runner on Linux
- [ ] A Bash shell file (.sh) to launch the console runner via Mac OSX (or confirm the Linux script works for this OS)

**Comment by marcphilipp** [comment]
Is this really necessary as we already have example projects for Gradle and Maven? I'm not sure I want to maintain this... If we do, we need some integration test that ensures that we don't accidentally break it.

**Comment by smoyer64** [comment]
No ... it's not necessary and there are certain aspects of the work I'm doing that would probably be better suited to the junit-samples project.  Now I'm also wondering if I'm adding more code than you'd like to illustrate the patterns for JUnit 4 rule replacement in #660.  Since we've agreed that we're going to ignore the ```DisableOnDebug``` rule, I've only got the ```ExternalResource/TemporaryFolder``` test class to write.  This weekend I should actually start adding text to the users guide.

**Comment by marcphilipp** [comment]
Thanks for your understanding!

> Now I'm also wondering if I'm adding more code than you'd like to illustrate the patterns for JUnit 4 rule replacement in #660.

Please go ahead with that! I think we have enough room in the User Guide and it's an important topic.
