### ISSUE TITLE
Add boolean disableOnDebug to @ExtendWith

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#668]
## Overview

When analyzing the existing JUnit 4 ```TestRules``` in #343, I completely missed the point of the ```DisableOnDebug``` rule.  It's purpose is to disable the encapsulated rule when the JVM is in debug mode and it has nothing to do with which tests are selected for execution.

- (X) **Feature request.** I'd like to propose that there's an additional member added to the ```@ExtendWith``` annotation in the following form:

```
boolean disableOnDebug() default false;
```

This flag would conditionally allow one or more ```Extension```s to be disabled when the JVM is in debug mode.  Code using this feature might look something like:

```
@ExtendWith(WeldExtension.class)
@ExtendWith(StopwatchExtension.class, disableOnDebug = true)
public void testSomething() { ... }
```

## Deliverables

- [ ] Change the ```@ExtendWith``` annotation.
- [ ] Alter the Jupiter engine to ignore extensions during debug.

**Comment by marcphilipp** [comment]
We're currently reluctant to add the `disableOnDebug` parameter to `@ExtendWith` because the only use case we could think of is disabling a timeout extension -- which does not exist (yet?). I think we should postpone this feature until we add such an extension, if at all.

We currently only support timeouts via `assertTimeout*` in `Assertions`. Adding the possibility to disable the timeout there might make sense. Would you agree?

**Comment by smoyer64** [comment]
I agree completely ... when trying to document this ```@Rule``` I was a bit surprised at what it was actually doing.  I've never used this feature nor have I ever seen tests where it was used.  I'd suggest we move this issue to the backlog and pull my PR (#669) into a "parking" branch.  I feel like I found the right spot in the code for this implementation but it also felt a little dirty.

For disabling tests during debug, I think the ```@EnableIf/@DisableIf" annotations are better and we can just supply a predicate that determines whether or not the JVM is in debug.

**Comment by nicolaiparlog** [comment]
@smoyer64 I also wondered about a more general `@DisabledIf` extension. If you have a concrete idea, feel free to open a PR on [JUnit Io](https://github.com/CodeFX-org/junit-io).

**Comment by marcphilipp** [comment]
Well, `@EnabledIf`/`@DisableIf` would enable/disable the test completely. The point of `DisableOnDebug` seems to be that the test is executed as normal but only certain rules are turned off.

**Comment by emick** [comment]
I've used `DisableOnDebug` around `Timeout` and custom `RetryOnFailure` rule to tackle flaky selenium tests, while still allowing easy debugging and manual runs. Using `assertTimeout` won't help in this case since those rules need to be global for all tests.
