### ISSUE TITLE
Introduce a top-level ExtensionContext for the JupiterTestEngine

### ISSUE THREAD

**Issue by LymanEfunktion** [junit-team/junit5#671]
## Feature Request

When using the available extension contexts in test runs with extensions like `BeforeAllCallback` and `BeforeTestExecutionCallback`, it only seems possible to use these contexts during one test and lose all context information in following test runs.

Trying to use the parent context of an instance of `ContainerExtensionContext` in a `beforeAllCallback` leads to an empty `Optional` object, thus no information can be used or set.

```java
import java.util.logging.Logger;

import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeTestExecutionCallback;
import org.junit.jupiter.api.extension.ContainerExtensionContext;
import org.junit.jupiter.api.extension.TestExtensionContext;

/**
 * @author Simon Ebner
 */
public class ParentAwareExtension implements BeforeAllCallback, BeforeTestExecutionCallback {

	@Override
	public void beforeAll(ContainerExtensionContext context) throws Exception {
		/**
		 * Issue - no parent context during test execution available to act on
		 * or use any global context information
		 */
		context.getParent().ifPresent(parent -> {
			Logger.getLogger("JUnit5-Issue").info("'before all' has parent context " + parent.getDisplayName());
		});
	}

	@Override
	public void beforeTestExecution(TestExtensionContext context) throws Exception {
		context.getParent().ifPresent(parent -> {
			Logger.getLogger("JUnit5-Issue").info("'before test' has parent context " + parent.getDisplayName());
		});
	}
}
```

It would be great to be able to set and use context information for an entire test run, especially when needing to execute time and resource expensive operations, that could be reduced to one call per entire test run.

## Suite Considerations

I am not sure as to how it would be necessary to look also at `@SelectClasses` and `@SelectPackages` in this case, because they also may create a distinct series of tests and thus a logical unit, that might need its own context to be able to separate tests that run in a suite and others. I would like to know your opinion in this respect.

**Comment by smoyer64** [comment]
Having a top-level context available for the duration of the engine would help with creating @BeforeSuite and @AfterSuite (#456).

**Comment by marcphilipp** [comment]
**Team decision:** Provide an `ExtensionContext` for the engine level.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by sbrannen** [comment]
FYI: changed title and formatted description
