### ISSUE TITLE
Create two versions of the javadocs - link to the API from the users guide

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#676]
## Overview

```@Test``` writers as well as ```Extension``` developers shouldn't be using classes outside of ```org.junit.jupiter.api.*```.  While introducing developers of both ilks to JUnit 5, I've found that it would be far easier to have the javadocs they're using for reference to the users guide.  Since the users guide provides content that almost exclusively deals with the API, it should probably link to a more limited set of javadocs.  (as should the link from http://junit.org/junit5).

On the other hand, core developers and those of us who are trying to understand how it works under the hood definitely find the full set of javadocs useful.  The link to these javadocs can be a little more hidden - I'd suggest the link to the full javadocs be published in the README.md file at the top of the JUnit 5 repository.

- (X) **Feature request.** Provide a more limited set (and less intimidating) set of javadocs to ```@Test``` writers and ```Extension``` developers to facilitate platform adoption.  JUnit 5 may be much bigger (and better abstracted) than JUnit 4, but the surface area that a new user needs to learn is nicely limited to the API.

## Deliverables

- [ ] Publish the API javadocs for most JUnit 5 users.
- [ ] Create the merged version of the javadocs for JUnit 5 developers

**Comment by jbduncan** [comment]
Sounds like a very good idea to me!

**Comment by marcphilipp** [comment]
Makes sense!

**Comment by marcphilipp** [comment]
I'm putting this "up-for-grabs". However, it would be a good idea in this case to discuss how exactly the URLs should look like etc. here before starting.

**Comment by joergsesterhenn** [comment]
I'd like to do this.

You are using a kotlin/gradle script through github actions to generate and publish your docs? I'm not an expert on any of that, but I'd like to try it, if that's okay with you. 

I suggest to put the API under the current URL https://junit.org/junit5/docs/current/api/ and the complete docs under the currently unused URL https://junit.org/junit5/docs/current/ .
What do you think of that @marcphilipp ?

Should there be links from the api to the complete docs and/or vice versa?

**Comment by marcphilipp** [comment]
I don't think we should use `https://junit.org/junit5/docs/current/` for that because the `user-guide` and the `release-notes` are also subdirectories of that folder. How about `https://junit.org/junit5/docs/current/jupiter-api`?

**Comment by marcphilipp** [comment]
> Should there be links from the api to the complete docs and/or vice versa?

I'm not sure. I think it would be ok to keep them completely separate.

> You are using a kotlin/gradle script through github actions to generate and publish your docs? I'm not an expert on any of that, but I'd like to try it, if that's okay with you.

Yes, it's all in the `documentation` subproject. Basically, you'll have to define a new `Javadoc` task and include it in the `prepareDocsForUploadToGhPages` task.

**Comment by joergsesterhenn** [comment]
> I don't think we should use `https://junit.org/junit5/docs/current/` for that because the `user-guide` and the `release-notes` are also subdirectories of that folder. How about `https://junit.org/junit5/docs/current/jupiter-api`?

Just to make sure I understood that correctly:
I'll leave the current api where it is and add the new jupiter public only api under:
`https://junit.org/junit5/docs/current/jupiter-api`

**Comment by marcphilipp** [comment]
@kazhuru is taking over (see https://github.com/junit-team/junit5/pull/2056#issuecomment-565155170).

**Comment by marcphilipp** [comment]
Since #2155, Javadoc is grouped by module. E.g. the Jupiter API has its own overview page: https://junit.org/junit5/docs/snapshot/api/org.junit.jupiter.api/module-summary.html

Thus, I'm closing this issue as _superseded_ by #2155.
