### ISSUE TITLE
Remove deprecated members

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#678]
## Overview

Changes like #620 created `@Deprecated` members. They should be removed in M5 or in GA.

Scope: entire source tree or public API?

## Deliverables

- [x] Scan for deprecated members and remove them.

**Comment by marcphilipp** [comment]
Also helpful: http://junit.org/junit5/docs/snapshot/api/deprecated-list.html

**Comment by sbrannen** [comment]
Resolved in f7a957b2202aa749cc0d660da58bb29ecf2c55f1
