### ISSUE TITLE
@selectpackages and @selectclasses are not working in maven test

### ISSUE THREAD

**Issue by sankarpadhy** [junit-team/junit5#680]
## Overview

`@SelectPackages` and `@SelectClasses` tags are not getting parsed with maven test command.Though it is working fine in IDE.

- ( ) **Question.** http://stackoverflow.com/questions/42392512/running-test-suite-is-not-working-in-junit5-through-maven
-
## Deliverables

- [ ] ...

**Comment by marcphilipp** [comment]
I've posted a response on StackOverflow:
http://stackoverflow.com/a/42415749/6327046

Does that help?

**Comment by sankarpadhy** [comment]
no, it is not working. 

here is my pom.xml

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<junit.jupiter.version>5.0.0-M2</junit.jupiter.version>
		<junit.vintage.version>4.12.0-M2</junit.vintage.version>
		<junit.platform.version>1.0.0-M2</junit.platform.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<includes>
						<include>**/AllSuiteTests.java</include>
					</includes>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.junit.jupiter</groupId>
						<artifactId>junit-jupiter-engine</artifactId>
						<version>${junit.jupiter.version}</version>
					</dependency>
					<dependency>
						<groupId>org.junit.vintage</groupId>
						<artifactId>junit-vintage-engine</artifactId>
						<version>${junit.vintage.version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

	<dependencies>

	

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-runner</artifactId>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
		</dependency>
	</dependencies>
</project>
```

Please note that I have removed the surefire. It did not run my tests:-

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.authentic.suite.AllSuiteTests
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in com.authentic.suite.AllSuiteTests

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

I have to run the suite because I need to run the test packages in that order

**Comment by marcphilipp** [comment]
Can you please check the Surefire report files for any (logging) output? They should be in `target/surefire-reports`.

**Comment by sankarpadhy** [comment]
![file----c--source-authentic-tests-target-site-surefire-report h](https://cloud.githubusercontent.com/assets/2771130/23267742/a6b07102-fa11-11e6-862e-7156410eb952.jpg)

**Comment by sankarpadhy** [comment]
Hey, it is working now.. This is the final POM
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.howtoprogram</groupId>
	<artifactId>junit5-test-suite-example</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>


	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<junit.jupiter.version>5.0.0-M2</junit.jupiter.version>
		<junit.vintage.version>4.12.0-M2</junit.vintage.version>
		<junit.platform.version>1.0.0-M2</junit.platform.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<configuration>
					<includes>
						<include>**/*SuiteTest.java</include>
					</includes>
				</configuration>

			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-runner</artifactId>
			<version>${junit.platform.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>
`

The output is 

 T E S T S
-------------------------------------------------------
```
Feb 23, 2017 10:21:06 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [junit-jupiter]
Running xyz.howtoprogram.junit5.suite.UserFeatureSuiteTest
Feb 23, 2017 10:21:06 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [junit-jupiter]
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.053 sec - in xyz.howtoprogram.junit5.suite.UserFeatureSuiteTest
```

Also the report as :+1: 

![file----c--practice1-junit5-examples-master-junit5-test-suite-e](https://cloud.githubusercontent.com/assets/2771130/23269529/defe9e8a-fa16-11e6-801b-a398daad4874.jpg)

Thanks for your help!

**Comment by marcphilipp** [comment]
Glad it's working now! 🙂
