### ISSUE TITLE
Close the stream in org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor#invokeTestMethod()

### ISSUE THREAD

**Issue by honza-zidek** [junit-team/junit5#683]
## Overview

The stream received by a @TestFactory method should be closed after all the tests have been run.

## Motivation

Currently, if you wish to create dynamic tests based on the data from file, you cannot call the following:

```
@TestFactory
Stream<DynamicText> pointTests() {
    return
        Files.lines(fileName).map(Point::parse).map(
            point -> dynamicTest("Testing " + p, () -> pointTest(p))
        );
}

```
because the stream represented by `Files.lines()` is a file-system-based resource and must be closed.

Unfortunately we cannot just use
```
@TestFactory
Stream<DynamicText> pointTests() {
{
    try (final Stream<String> lines = Files.lines(fileName)) {
    return
        lines.map(Point::parse).map(
            point -> dynamicTest("Testing " + p, () -> pointTest(p)))
    );
}
```
as the source stream is closed **before** JUnit5 even starts reading from it (the termination operation is lazy).

The only solution currently is probably only using an interim collection and collect the lines to it, which is awkward:

```
@TestFactory
Stream<DynamicText> pointTests() {
    final List<Point> data;
    try (final Stream<String> lines = Files.lines(fileName)) {
        data = lines.map(Point::parse).collect(Collectors.toList());
    );
    return data.map(point -> dynamicTest("Testing " + p, () -> pointTest(p));
}
```

**It would be most convenient if the contract of @TestFactory guaranteed calling Stream#close().**

## Documentation

It is crucial that all the related documentation states that the stream is closed, so it becomes part of the contract and the clients may rely on it.

**Comment by marcphilipp** [comment]
Good catch!

> It would be most convenient if the contract of @TestFactory guaranteed calling Stream#close().

Agreed. Do you have time to do it?

**Comment by LiamClark** [comment]
@honza-zidek @marcphilipp if not I wouldn't mind having a look at it :)

**Comment by nicolaiparlog** [comment]
If I didn't miss anything the call to `close` should go into [`TestFactoryTestDescriptor::invokeTestMethod`](https://github.com/junit-team/junit5/blob/73f3eeb436e78226f19554f2c2b5dab63e103670/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java#L91-L92).

**Comment by marcphilipp** [comment]
Yep.

**Comment by honza-zidek** [comment]
@LiamClark I'd appreciate if you do it! I am just an observer here and I have not changed any code here yet.
