### ISSUE TITLE
Upgrade to Gradle 3.4

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#690]
## Overview

The build fails after upgrading to Gradle 3.4 with following stacktrace:
```
...
:junit-platform-gradle-plugin:spotlessCheck
:junit-platform-gradle-plugin:compileTestJava NO-SOURCE
:junit-platform-gradle-plugin:compileTestGroovy
:junit-platform-gradle-plugin:processTestResources NO-SOURCE
:junit-platform-gradle-plugin:testClasses
:junit-platform-gradle-plugin:test

org.junit.platform.gradle.plugin.JUnitPlatformPluginSpec > adds dependencies to configuration FAILED
    java.lang.UnsupportedOperationException
        at org.gradle.api.internal.CompositeDomainObjectSet$DomainObjectCompositeCollection.containsAll(CompositeDomainObjectSet.java:228)
        at org.gradle.api.internal.DefaultDomainObjectCollection.containsAll(DefaultDomainObjectCollection.java:241)
        at org.gradle.api.internal.DelegatingDomainObjectSet.containsAll(DelegatingDomainObjectSet.java:98)
        at org.gradle.api.internal.DelegatingDomainObjectSet.containsAll(DelegatingDomainObjectSet.java:98)
        at org.junit.platform.gradle.plugin.JUnitPlatformPluginSpec.adds dependencies to configuration(JUnitPlatformPluginSpec.groovy:251)

10 tests completed, 1 failed
:junit-platform-gradle-plugin:test FAILED
```

## Deliverables

- [ ] Solve `UnsupportedOperationException`
- ~Make use of https://docs.gradle.org/current/userguide/java_library_plugin.html~ Moved to #691

**Comment by marcphilipp** [comment]
I'm putting this up-for-grabs.

**Comment by sormuras** [comment]
> I'm putting this up-for-grabs.

Great!

Btw. the failing test spec mentioned in the description is the only build-breaking issue after upgrading Gradle 3.4. The adoption of the new **Java Library Plugin** is another story.

**Comment by gaganis** [comment]
I have looked into this and getting to a fix solving the UnsupportedOperationException proved to be more easy than I expected.

For the second deliverable though I must confess that I gave a look at the java library plugin doc that @sormuras posted but this was one of the cases when after reading the doc you come out more confused than before :(

**Comment by gaganis** [comment]
FYI The following blog post on the gradle site helps a lot in the understanding the why of the java library plugin. 
https://blog.gradle.org/incremental-compiler-avoidance

Looks like a very interesting mechanism.

**Comment by marcphilipp** [comment]
Thanks for sharing the link! I've changed this issue to only address the `UnsupportedOperationException` and created #691 to migrate to the java-library plugin.

@gaganis Please submit a pull request with your fix. 🙂
