### ISSUE TITLE
Migrate to java-library Gradle plugin

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#691]
## Overview

The java-library plugin allows for more fine-grained dependency management. In particular, it distinguishes between `api` and `implementation` dependencies.

## Prerequisites

- Gradle 3.4 (#690)

## Deliverables

- [ ] Change all modules to use java-library plugin and appropriate dependency configurations

**Comment by marcphilipp** [comment]
This issue is _blocked_ until #690 has been resolved.

**Comment by marcphilipp** [comment]
This issue is no longer _blocked_ since #690 was resolved earlier today.

**Comment by gaganis** [comment]
I would like to work on this, but I seems that it might need good big-picture knowledge of the project so I would need a lot of help and time from those of you with more experience.

If that is not a problem and no-one else wants it I can give it a go. :)

**Comment by marcphilipp** [comment]
Time could be an issue, especially since we maintainers are very opinionated... 😉

If you want to give it a go that's fine. However, we might need to play around with the new possibilities a bit ourselves.

**Comment by marcphilipp** [comment]
This issue is _in progress_ (see #699).

**Comment by sormuras** [comment]
Closed by https://github.com/junit-team/junit5/commit/04d10a6a2f468e6ae42eb75334c288e17c004e31
