### ISSUE TITLE
Tracking:  Pitest/JUnit 5 integration

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#696]
There's a discussion related to creating a new plugin to support JUnit 5 in Pitest at:

https://github.com/hcoles/pitest/issues/284

Potential issues:

- [ ] Removal of the ```forUniqueId``` static method from ```org.junit.platform.engine.discovery.UniqueIdSelector```.

No action should be taken until analysis is complete.

## Deliverables

**Comment by marcphilipp** [comment]
@smoyer64 `forUniqueId` has been moved to `DiscoverySelectors` prior to M1. So, it still exists, but in a different location. Reading through hcoles/pitest#284, it sounds like we can close this issue?

**Comment by smoyer64** [comment]
There is a prototype that currently treats each JUnit 5 test class as a Pitest ```TestUnit```.  Pitest runs can be made more efficient if the ```TestUnit``` is an individual test, but I'd anticipate that there would be problems with ```@TestFactory```, ```@TestTemplate``` and maybe with ```@Nested``` if that's done.

If you want to close this issue that's fine ... if it's left open then I'll keep it up-to-date as a one-to-many reference to getting Pitest/JUnit 5 integration working.

**Comment by marcphilipp** [comment]
I'm fine with leaving it open. But please update the issue description if the `forUniqueId` item is no longer relevant.

**Comment by smoyer64** [comment]
I've realized that this is an impractical way to track external issues.  I'm certainly interested in knowing what issues are imposed in related (but technically downstream) projects but none of us really stands a chance of finding them all (and advanced search doesn't provide a way to find projects that refer to JUnit 5 issues).
