### ISSUE TITLE
Gradle-Plugin make test-task not working

### ISSUE THREAD

**Issue by michaelsiepmann** [junit-team/junit5#700]
Hi,

we have the following code in our build.gradle:

```groovy
test {
    systemProperty 'serviceUrl', "http://$masterServerAddress"
    systemProperty 'java.io.tmpdir', file("$buildDir/tmp").absolutePath

    doFirst {
        // do something
    }

    finalizedBy "stopMasterServer"
}
```

This worked unless i've added the junit5Plugin. After that, systemProperty and doFirst won't be called.
Maybe this happens, because "configureTaskDependencies" changes this task. 

Is there a way to stop this? Or can I do this above on the junitPlatformTest?

**Comment by marcphilipp** [comment]
The junitPlatform plugin disables the standard test task to prevent test from being executed twice. However, you can re-enable it:

```groovy
junitPlatform {
    enableStandardTestTask = true
}
```

The `junitPlatform` extension/task does not support `systemProperty` at this time. This will change when the Gradle team adds support for JUnit 5 to core Gradle.

You should be able to get `doFirst` and `finalizedBy` working using standard Gradle:

```groovy
junitPlatform.doFirst {
    // do something
}
junitPlatform.finalizedBy "stopMasterServer"
```

If you really need custom system properties, you can define your own task that uses `ConsoleLauncher` directly:

```gradle
dependencies {
    testRuntime 'org.junit.platform:junit-platform-console:1.0.0-M3'
    testRuntime 'org.junit.jupiter:junit-jupiter-engine:5.0.0-M3'
}

task runJUnitPlatform(type: JavaExec) {
    doFirst {
        // do something
    }

    systemProperty 'serviceUrl', "http://$masterServerAddress"
    systemProperty 'java.io.tmpdir', file("$buildDir/tmp").absolutePath

    classpath = project.sourceSets.test.runtimeClasspath
    main 'org.junit.platform.console.ConsoleLauncher'
    args '--scan-class-path'
    args "--reports-dir=$buildDir/jupiter-results"

    finalizedBy "stopMasterServer"
}

test.dependsOn runJUnitPlatform
test.enabled = false
```

**Comment by marcphilipp** [comment]
@michaelsiepmann Have you tried the things I've proposed?

**Comment by sta-szek** [comment]
I have similar problem - cannot run JaCoCo (any version) with junit5 gradle plugin on board.

JaCoCo is telling me:

```
Skipping task ':jacocoTestReport' as task onlyIf is false.
19:00:22.616 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':jacocoTestReport'
19:00:22.616 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :jacocoTestReport SKIPPED
```
which means I do not run `test` task,

despite of :

```
junitPlatform {
    enableStandardTestTask true
}
```

I cannot make jacoco generate its reports on my project https://github.com/sta-szek/pojo-tester

have you ever had this issue?

**Comment by michaelsiepmann** [comment]
@marcphilipp 
Yes, i've tried it. It works, when I start "runJUnitPlatform", but not when running "test". This should be possible, because our project is very large and has some modules. We need for the project a one way to run the tests, so the test-task is mandantory.

@sta-szek 
JaCoCo works in our environment. These are the changes

junitPlatform {
    reportsDir file('build/test-results/test')
}

afterEvaluate {

    jacoco {
        toolVersion = toolVersions.jacoco
        applyTo junitPlatformTest
    }

    task junit5CodeCoverageReport(type:JacocoReport){
        executionData junitPlatformTest
        sourceSets sourceSets.main
        sourceDirectories = files(project.sourceSets.main.allSource.srcDirs)
        classDirectories = files(project.sourceSets.main.output)
        reports {
            xml.enabled = true
            html.enabled = true
        }
    }
}

**Comment by sta-szek** [comment]
@michaelsiepmann thanks, it worked. 
but I think running jacoco with junit4 is much easier because of lack of dynamically created junitPlatformTest task.

And gradle test set plugin (for e.g. integrationTest) does not work - junit5 does not run those tests.

**Comment by sbrannen** [comment]
Actually, it _is_ possible to set system properties when using the `junitPlatform` task, as discussed here: http://stackoverflow.com/questions/41331199/setting-system-properties-when-using-junitplatform/41334739#41334739

**Comment by sbrannen** [comment]
And I originally posted the work-around here: https://github.com/junit-team/junit5/issues/475#issuecomment-242038043

**Comment by edeandrea** [comment]
Looks like the Gradle team is still spinning on this issue - gradle/gradle#1037

**Comment by marcphilipp** [comment]
Gradle now provides [native support](https://docs.gradle.org/4.6/release-notes.html#junit-5-support) for running tests on the JUnit Platform using the standard `test` task. We've decided to deprecate our custom plugin (see #1317 for details) and not add any new features to it. Thus, I'm closing this issue.
