### ISSUE TITLE
Console standalone jar does not come alone

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#701]
## Overview

The current console standalone jar is uploaded with the "full" pom file, which leads to too many dependent jars to be downloaded when you only want and need the standalone "classified" jar.

-  (standalone) -> **junit-platform-console-1.0.0-SNAPSHOT-standalone.jar** // only file needed
-  (standalone) -> junit-platform-launcher-1.0.0-SNAPSHOT.jar
-  (standalone) -> junit-platform-engine-1.0.0-SNAPSHOT.jar
-  (standalone) -> junit-platform-commons-1.0.0-SNAPSHOT.jar
-  (standalone) -> opentest4j-1.0.0-SNAPSHOT.jar

Potential caused by by-passing http://imperceptiblethoughts.com/shadow/#default_java_groovy_tasks : 

_Configures the uploadShadow task (as part of the maven plugin) with the following behavior:_
- _Removes the compile and runtime configurations from the pom.xml file mapping._
- _Adds the shadow configuration to the pom.xml file as RUNTIME scope._

This is a test case in another project:

https://github.com/sormuras/beethoven/commit/669a6cb8361a97f850b8c6145aa68523870c7b20

## Deliverables

- [ ] Only file `junit-platform-console-1.0.0-SNAPSHOT-standalone.jar` has to be resolved when depending on "standalone" classifier.

**Comment by sormuras** [comment]
Possible solution? https://discuss.gradle.org/t/plugin-publishing-how-to-remove-pom-dependencies/12466

**Comment by marcphilipp** [comment]
Is this really an issue? The use case for the standalone JAR is to use it without any dependency management, isn't it? Right now there's only one POM: https://oss.sonatype.org/content/repositories/snapshots/org/junit/platform/junit-platform-console/1.0.0-SNAPSHOT/

> Potential caused by by-passing
> http://imperceptiblethoughts.com/shadow/#default_java_groovy_tasks

Are we by-passing something?

**Comment by sormuras** [comment]
True. But it should behave correctly, when resolved via Maven/Gradle/etc. I.e. it should not report any extra dependency.

Gradle docs hint at [maven_pom_generation](https://docs.gradle.org/current/userguide/maven_plugin.html#sec:maven_pom_generation) especially [:multiple_artifacts_per_project](https://docs.gradle.org/current/userguide/maven_plugin.html#sub:multiple_artifacts_per_project) ... combined with http://stackoverflow.com/questions/29392236/how-to-alter-dependencies-for-a-generated-artifact should do the trick: having two poms and have the standalone report no other dependency.

**Comment by sormuras** [comment]
> Are we by-passing something?

Could be. See "_Configures the uploadShadow_" from description ... which, I think, does not cover our new task at https://github.com/junit-team/junit5/blob/master/junit-platform-console/junit-platform-console.gradle#L80 

Introducing a new module for "junit-platform-console-standalone" back then, might have been a cleaner solution.

**Comment by marcphilipp** [comment]
Does Maven support different POMs for the same artifact ID?

**Comment by sormuras** [comment]
Mh. Yes? Not sure. :)

I think, with the filters you can also modify  (read: clear) the dependency list of a specific artifacts' generated pom file. Maybe. Like here: http://stackoverflow.com/a/42248185/1431016
