### ISSUE TITLE
Parameter resolvers should be able to access the invocation context for test templates

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#704]
## Overview

When a ```TestTemplateInvocationContextProvider``` is created, its ```provide()``` method must return a `Stream` of ```TestTemplateInvocationContext```s.

I've extended/implemented  ```TestTemplateInvocationContext``` to include context that is specific to the tests that will be executed.  As the ```TestEngine``` iterates over these invocation contexts, parameter resolution (via one or more ```ParameterResolver```s) is performed.  It appears that there's no way for the invocation's parameter resolvers to obtain the context provided by the ```TestTemplateInvocationContextProvider```.

- **Feature request.** Make the invocation context available to the extensions that it adds to the invocation.

## Related Issues

- #14 

## Deliverables

- ?

**Comment by sbrannen** [comment]
Tentatively slated for M4.

**Comment by sbrannen** [comment]
FYI: this is related to the proposal (in #14) for an `@InvocationIndex` annotation for injecting the current _invocation index_ into `@Test`, `@BeforeEach`, and `@AfterEach` methods.

See https://github.com/junit-team/junit5/commit/d2e3a4dfdc8cc4b4b8609e4297f8e00b753cb5b3.

**Comment by smoyer64** [comment]
As a concrete example, I have a branch in upREST that creates the combinations of tests needed based on the annotations that are present, so one test method might yield many invocations.  Since the invocation context is an interface, I've created an implementation that holds the specific HttpRequest object that must be sent to the server before the method's parameter resolution.

When it's time to execute the test, the parameter resolver will send the HttpRequest and, based on what parameters are to be injected, will process the response and build provide the parameters needed (it's a bit more complicated than that since a request can fail and there are types of responses that can and can't be converted properly depending on whether there's an entity body present).  I've also overridden the ```getDisplayName()``` method since I'm not so interested in the index or order the tests are run in but do care about the characteristics of the request.

I guess in some cases ```@InvocationIndex``` is useful but I need a way for the parameter resolvers to get a reference to the invocation context itself.  Since you've brought up the idea of injecting an ```InvocationIndex``` into the test method, I guess it would also be nice to have a built-in parameter resolver for the ```TestTemplateInvocationContext``` in the same manner as the ```TestInfo``` parameter resolution.

**Comment by sbrannen** [comment]
> I guess in some cases `@InvocationIndex` is useful 

Actually, the more I think about it, the more I come to realize that `@InvocationIndex` is probably completely useless.

It's _useless_ simply because it provides _zero_ context. It's just a number, and without further information one simply cannot know how to interpret it. If you don't know what other providers are registered, and in what order, and exactly what they do... then the index becomes meaningless.

That's why I ended up _inventing_ `RepetitionInfo` for repeated tests. 😉

**Comment by sbrannen** [comment]
> but I need a way for the parameter resolvers to get a reference to the invocation context itself.

I agree that that could be useful, and it provides more _context_ (no pun intended) than merely the index.

> Since you've brought up the idea of injecting an ```InvocationIndex``` into the test method, I guess it would also be nice to have a built-in parameter resolver for the ```TestTemplateInvocationContext``` in the same manner as the ```TestInfo``` parameter resolution.

I don't think that would be prudent, at least not in that form. 

Thus far we strive to decouple extension APIs from _normal_ test code, meaning that we wouldn't want to inject a type from the `extension` package into a test method.

Perhaps something like `TestTemplateInfo` would work, but I'm also not sure that there is a real need for that.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment]
FYI: I changed the title of this issue to reflect its more generic nature.

**Comment by sormuras** [comment]
Which other properties would a `TestTemplateInfo` carry around, other than `int getInvocationIndex()`?

**Comment by sbrannen** [comment]
> Which other properties would a `TestTemplateInfo` carry around, other than `int getInvocationIndex()`?

Good question.

In order to provide _contextual information_, it would need to somehow provide the _source_; otherwise, we again have the problem with the invocation index being meaningless on its own.

So, I guess the question is: what is the _source_?

It could be a _name_.

It could be a `Class` reference.

Or perhaps @smoyer64 had it right: perhaps the only meaningful source is the actual provider of the invocation context (the `TestTemplateInvocationContextProvider`) or the `TestTemplateInvocationContext` itself. However, this would be new territory for us: we have intentionally never referenced types from the `extension` package within the `api` package. So we would need to be cautious and make sure we avoid any package cycles if we do something along those lines.

**Comment by smoyer64** [comment]
Should this be split into two issues?  It seems like being able to access a ```TestTemplateInvocationContext``` from within a ```ParameterResolver``` is different than providing a built-in ```ParameterResolver``` that allows a test to gain access to it's context.

To be honest, I was expecting that this would require the addition of an (```Optional```) accessor in ```ExtensionContext```.

**Comment by sbrannen** [comment]
> Should this be split into two issues?  

It basically already is; we just happen to be discussing the topics in two places since they are related. 😉 

> It seems like being able to access a ```TestTemplateInvocationContext``` from within a ```ParameterResolver``` is different than providing a built-in ```ParameterResolver``` that allows a test to gain access to it's context.

I agree.

This issue is focused on the extension model.

The related _Deliverable_ in #14 is focused on the programming model.

> To be honest, I was expecting that this would require the addition of an (```Optional```) accessor in ```ExtensionContext```.  

That's definitely an option.

So are you proposing `Optional<TestTemplateInvocationContext> getTestTemplateInvocationContext()`?

**Comment by sbrannen** [comment]
> If it turns out that all the invocation context does is (potentially) set a test's display name, then I'll make sure that name can be used as a key and stash the HttpRequest into the context's Store.

Are you saying that you don't care about the physical _type_ of the invocation context?

In other words, are you not going to downcast it to a type you know (or own) and interact with other methods it may provide?

Do you have some code we can look at in order to better understand your use case?

**Comment by marcphilipp** [comment]
This works for me:

```java
class ParamResolverWithAccessToContext {

	static class MyTestTemplateInvocationContextProvider implements TestTemplateInvocationContextProvider {
		@Override
		public boolean supports(ContainerExtensionContext context) {
			return true;
		}

		@Override
		public Stream<TestTemplateInvocationContext> provide(ContainerExtensionContext context) {
			return Stream.of(new MyTestTemplateInvocationContext());
		}
	}

	static class MyTestTemplateInvocationContext implements TestTemplateInvocationContext {
		@Override
		public List<Extension> getAdditionalExtensions() {
			return singletonList(new MyParameterResolver(this));
		}
	}

	static class MyParameterResolver implements ParameterResolver {

		private final MyTestTemplateInvocationContext invocationContext;

		MyParameterResolver(MyTestTemplateInvocationContext invocationContext) {
			this.invocationContext = invocationContext;
		}

		@Override
		public boolean supports(ParameterContext parameterContext, ExtensionContext extensionContext)
				throws ParameterResolutionException {
			return parameterContext.getParameter().getType().equals(TestTemplateInvocationContext.class);
		}

		@Override
		public Object resolve(ParameterContext parameterContext, ExtensionContext extensionContext)
				throws ParameterResolutionException {
			return invocationContext;
		}
	}

	@TestTemplate
	@ExtendWith(MyTestTemplateInvocationContextProvider.class)
	void template(TestTemplateInvocationContext invocationContext) {
		assertNotNull(invocationContext);
	}

}
```

@smoyer64 Would that work for you, too?

**Comment by smoyer64** [comment]
@marcphilipp  That might just work - hopefully I can try it out later today.  As you previously suggested, I've created a new ```@TestTemplate``` annotation for the REST tests performed by upREST and was declaratively adding the appropriate ```ParameterResolver```s to that annotation.  That annotation looks something like this:

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
@TestTemplate
@ExtendWith(RestTestContextProvider.class)
@ExtendWith(EntityBodyResolver.class)
@ExtendWith(HttpRequestResolver.class)
@ExtendWith(HttpResponseResolver.class)
@ExtendWith(StatusLineResolver.class)
public @interface RestTest {

}
```

There are actually quite a few more ```ParameterResolver```s and I was letting the engine instantiate them prior to ```@TestTemplate```.  One issue is that I don't necessarily know the complete list of ```ParameterResolver```s to statically/programmatically create that list as upREST is modular.  The core module provides the REST functionality but if you want to convert a JSON or XML entity body to a Java object for further assertions, you can add other modules as needed.

My gut is telling me that I can discover which resolvers are on the classpath via service discovery and then use a factory to create the list programmatically as you've shown above.

**Comment by marcphilipp** [comment]
Did you have a chance to try it out?

**Comment by marcphilipp** [comment]
@smoyer64 Can we close this issue?

**Comment by smoyer64** [comment]
@smoyer64 ... sorry for disappearing (my day job has been consuming my personal time lately).  I'm about half-way through upREST's conversion to ``@TestTemplate``.  I'm pretty sure this is going to work and has the advantage that executing the request can be lazy - if there isn't a parameter that needs data from the response, then why execute the request.

Can I have a couple more days to catch up?

**Comment by marcphilipp** [comment]
Sure!

**Comment by marcphilipp** [comment]
@smoyer64 Any news?

**Comment by smoyer64** [comment]
I'm not finished yet but it's going to work ... let's close this since it's way better to apply a specific set of extensions to the execution contexts than what I was doing before.

**Comment by sbrannen** [comment]
OK. Closing this issue now.

**Comment by sbrannen** [comment]
Added label _works-as-designed_, due to the workaround proposed by @marcphilipp.
