### ISSUE TITLE
Publish pruneTree() in junit-platform-engine support package

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#706]
`DiscoverySelectorResolver.pruneTree()` is something that all test engines should do in order to not have empty packages. I see two options:
1. Publish pruneTree() in junit-platform-engine support package for all engines to use
2. Do it for all engines automatically after collecting their discovery result

Since I cannot think of a reason to not prune a branch without executable tests I'd vote for the latter.

**Comment by bechte** [comment]
In case of dynamic or parameterized tests, we have discussed the topic of "may potentially have tests". We came to the conclusion that one cannot easily decide, whether or not a node in the test tree has tests or (maybe) will have tests in the future (runtime).

Therefore, I think it is dangerous to prune the tree from the "outside". It would require that the mechanism knows about the "concepts" (e.g. parameterization or dynamic tests) of the TestEngine itself. I would say that the TestEngine is responsible to preduce a tree that is consistent and efficient (not containing meaningless nodes) itself.

I, therefore, recommend not to force the test engines to prune the tree nor to require "hacks" to keep nodes alive by saying "may potentially have tests". This raises the overall complexity and does not add any value IMHO.

**Comment by jlink** [comment]
Just checked the current implementation of `DefaultLauncher`. Looks like `dicoverRoot(..)` already does a final pruning of all non-test nodes after applying the post-discovery filters.

So unless you're not planning to change that behaviour - and unless I'm missing something - this issue can be closed. However, there seems to be redundant logic since `DiscoverySelectorResolver` also prunes its descriptor tree, which should not be necessary.  That also mean that dynamic tests already signal that they "may potentially have tests".

I guess the expected engine contract should be clarified if the @junit-team wants to  encourage development of 3rd party test engines.

**Comment by marcphilipp** [comment]
Johannes is correct! Finally closing this issue... 👍
