### ISSUE TITLE
'junitPlatformTest' task can not be retrieved at configuration time by Gradle plugin

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#708]
## Overview

Currently, the `JUnitPlatformPlugin` has logic to be applied `afterEvaluate` which makes it so users must also do some lazy evaluation logic to be able to also configure it.

For example, is a user wants to apply configuraiton to the `'junitPlatformTest'` task, they might try this by:

```groovy
tasks.getByName('junitPlatformTest').dependsOn(myTask)
```

This will fail at configuration time with an NPE.

A user will have to work around this by making the configuration more lazy. One workaround for a user would be something like:

```groovy
tasks.whenTaskAdded {
  if (it.name == "junitPlatformTest") {
    it.dependsOn(myTask)
  }
}
```

## Deliverables

- [x] Make the `JUnitPlatformPlugin` applied at configuration time rather than `afterEvaluate`
- [x] Change is documented in the User Guide and Release Notes

**Comment by sormuras** [comment]
Seems like an easy fix. Want to send a PR?

Mid-term, an official plugin will be provided by Gradle itself: https://github.com/gradle/gradle/issues/1037

**Comment by mkobit** [comment]
@sormuras Sure! I just opened https://github.com/junit-team/junit5/pull/709 which _I think_ should be merged in first.

**Comment by sbrannen** [comment]
Reopening since this has not been documented in the release notes for M5.

**Comment by sbrannen** [comment]
In other words, #751 was merged without adhering to the Definition of Done.

**Comment by mkobit** [comment]
Sorry @sbrannen , I'll follow up with a PR today or tomorrow with the change.

**Comment by sbrannen** [comment]
Thanks, @mkobit!

We are all in the process of adjusting to our _Definition of Done_. 😉

**Comment by sbrannen** [comment]
Closing this issue since the release notes were updated in #800.
