### ISSUE TITLE
Add notice and include third-party licenses

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#714]
## Overview

To be safe, we need to include not only our license but also those of subcomponents, such as jopt-simple and univocity-csv to the corresponding JARs.

Here's how Spring does it:
https://github.com/spring-projects/spring-framework/blob/master/src/docs/dist/notice.txt
https://github.com/spring-projects/spring-framework/blob/master/src/docs/dist/license.txt

## Deliverables

- [x] Add `notice.md` files to all JARs
- [x] Include `LICENSE-jopt-simple.md` in junit-platform-console[-standalone] JAR
- [x] Include `LICENSE-univocity-parsers.md` in junit-jupiter-params

**Comment by sormuras** [comment]
###JOpt Simple -- in junit-platform-console and junit-platform-console-standalone
http://pholser.github.io/jopt-simple/license.html

The `jopt-simple-5.0.3.jar` does not contain a license file. The documenation and maven central point to https://opensource.org/licenses/mit-license.php

Copy MIT license text to a file called `junit-platform-console/LICENSE-jopt-simple.md` and include it the `junit-platform-console/build/libs/junit-platform-console-XYZ.jar`?

**Comment by marcphilipp** [comment]
Sounds good! Here's a Markdown version of the MIT license:
https://github.com/IQAndreas/markdown-licenses/blob/master/mit.md

**Comment by sormuras** [comment]
## uniVocity-parsers

https://github.com/uniVocity/univocity-parsers/blob/master/LICENSE-2.0.html

Used by

- junit-jupiter-params
- junit-platform-console-standalone (soon?)

uniVocity/univocity-parsers is licensed under the Apache License 2.0

Copy Apache License 2.0 to a file called junit-jupiter-params/LICENSE-univocity-parsers.md and include it the  junit-jupiter-params-XYZ.jar

**Comment by sormuras** [comment]
Updated deliverables.

**Comment by marcphilipp** [comment]
We should also do this for junit-platform-commons-standalone, right?

**Comment by sormuras** [comment]
The `LICENSE-xyz.md`s are auto-merged into the standalone JAR.

**Comment by sormuras** [comment]
Solved on master via https://github.com/junit-team/junit5/commit/9c1742a04ac8b26b53f644a5dbc998e02565a305 https://github.com/junit-team/junit5/commit/311b4efb8967c166e93b765863064cb5c593bc09 and https://github.com/junit-team/junit5/commit/f175c175a35eb9a1b7770ae63f02b138606944bf

Follow-up issue: #761
