### ISSUE TITLE
@Nested test classes are not inherited from superclasses

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#717]
## Overview

I created an abstract test class and organized the tests in nested classes. Unfortunately it looks like the implementing test class does not inherit those nested tests. Shouldn't it? (I think it should.) Or am I just doing something wrong?

(I discovered this with M3.)

## Deliverables

- [x] Decide whether nested test classes should be inherited.
- [x] Update `ReflectionUtils` so that searches for nested classes also return inherited nested classes (regardless of whether they are static or not).

**Comment by sormuras** [comment]
Maybe already fixed in SNAPSHOT version. When executing:

```
class ConsoleDetailsTests {

	static abstract class A {

		@Test void mA() {}

		static class B extends A {
			@Test void mB() {}
		}

		static class C extends B {
			@Test void mC() {}
		}
	}

	@Test
	void issue771() {
		ConsoleLauncherWrapper wrapper = new ConsoleLauncherWrapper();
		ConsoleLauncherWrapperResult result = wrapper.execute(//
				"--include-engine", "junit-jupiter", //
				"--select-class", A.B.class.getName(), //
				"--select-class", A.C.class.getName(), //
				"--include-classname", ".*" // allow all class names, other than "^.*Tests?$"
		);
		System.out.println(result.out);
	}
}
```
...the console reads like:
```
╷
└─ JUnit Jupiter ✔
   ├─ ConsoleDetailsTests$A$B ✔
   │  ├─ mA() ✔
   │  └─ mB() ✔
   └─ ConsoleDetailsTests$A$C ✔
      ├─ mA() ✔
      ├─ mB() ✔
      └─ mC() ✔
```

Didn't check M3.

**Comment by sormuras** [comment]
You're hiding, shadowing, bridging some methods, do you? Might want to check https://github.com/junit-team/junit5/issues/333#issuecomment-285399782 -- which was re-opend only hours ago.

**Comment by nicolaiparlog** [comment]
You do not seem to show my use case - have a look at #718, which creates a test demonstrating my problem.

**Comment by sormuras** [comment]
I see. Thanks for the [failing](https://ci.appveyor.com/project/marcphilipp/junit5/build/732) test case.

**Comment by nicolaiparlog** [comment]
I think my use case is a typical example of testing interface implementations:

1. create an interface `Awesome` 
2. create an abstract test class `AwesomeTest`, which tests the correct behavior as defined by `Awesome`'s Javadoc
3. for each implementation of `Awesome`, create a matching implementation of `AwesomeTest`

Up to here all is fine and everything works as planned. Implementations of `AwesomeTest` inherited all tests methods so all of them get executed. Now, the maintainer of `AwesomeTest` does some refactoring and decides to reorganize tests in nested classes. ~> Doesn't work because these do not get inherited.

**Comment by nicolaiparlog** [comment]
Oh, too slow, you already added the _bug_ label, so I assume you agree. :wink:

**Comment by sormuras** [comment]
I do. Let's wait what @junit-team/junit-lambda thinks about that.

**Comment by sormuras** [comment]
The current implementation of [ReflectionUtils.findNestedClasses(...)](https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java#L523) only considers **declared** class in the passed class. We could look up the class and interface hierarchy.

**Comment by gaganis** [comment]
I would also expect it and would be surprised to see nested class tests not being run (being 'inherited').

What I would like to point out though is that we need to be careful using the term '**inherited**'. Inheritance implies a semantic model that nested classes are not part of.

**Comment by sormuras** [comment]
@nicolaiparlog I didn't manage to pull/fetch/cherry/fetch/pick your #718 into mine branch. So, I copied your tests over by copy and paste. Hope, you don't mind.

Does #722 work as you expected it work? @sbrannen et al will take a look at this issue and PR later.

**Comment by sbrannen** [comment]
@jlink and @bechte, as "nested test class" aficionados, what are your thoughts on this topic?

Does the proposed change _violate_ the principles of nested test classes in terms of scoping, semantics, etc.?

**Comment by sbrannen** [comment]
FYI: updated _Deliverables_.
