### ISSUE TITLE
Update javadocs for ExtensionContextException

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#721]
## Overview

The javadocs for ExtensionContextException currently read:

>   Thrown if an error is encountered regarding the use of an ExtensionContext or ExtensionContext.Store.

It seems like this exception would also be appropriate for situations where the user has caused a problem with the extension's context (lower-case "c").  One example might be:

```
@EnabledIf( ... );
@DisabledIf( ... );
void someTest() {
...
}
```

I'd like to propose that the javadocs be changed to read as follows:

>   Thrown if an error is encountered when evaluating an extension's context.

- (X) **Feature request.** Broaden the allowed use of the ExtensionContextException.

## Deliverables

- [ ] Change the javadocs.

**Comment by marcphilipp** [comment]
@smoyer64 Is this issue still relevant?

**Comment by sbrannen** [comment]
@smoyer64, ping
