### ISSUE TITLE
TestTemplate methods detection is missing

### ISSUE THREAD

**Issue by ledoyen** [junit-team/junit5#730]
## Overview

- ( ) **Bug report.** `@TestTemplate` methods are not detected by the Jupiter engine.
To be specific, the `IsTestClassWithTests` predicate is missing the use of the `IsTestTemplateMethod` predicate to detect this new kind of tests introduce after the third milestone.

This problem is present using the last commit on master(ca24ac4218b87391de71daf77a3b9a82d94a2536).

Here is a pull request with the fix : #729

**Comment by sbrannen** [comment]
Good catch!

Please see comments in PR.

**Comment by sbrannen** [comment]
Resolved in f889ef881045a20192924341309e596c3768695a.
