### ISSUE TITLE
ReflectionUtils.findMethod() should search using bottom-up semantics

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#731]
## Status Quo

The `findMethod()` variants in `ReflectionUtils` currently use "top down" search semantics.

While "top down" may make sense when searching for multiple methods -- for example, when searching for all `@BeforeEach` methods within a type hierarchy -- "top down" semantics don't make sense when searching for a single method since you typically are interested in the first such method that is not overridden.

## Further Analysis

Further analysis shows that the `HierarchyTraversalMode` in use when searching for a single method is a moot point since our `!isMethodShadowedByLocalMethods(...)` checks take care of that logic. However, it still makes sense to use bottom-up search semantics by default, especially if we later implement a short-circuit algorithm for "finding the first" such method without traversing the type hierarchy needlessly.

## Deliverables

- [ ] Use bottom-up search semantics in `findMethod()` variants in `ReflectionUtils`

**Comment by sbrannen** [comment]
Updated with a _Further Analysis_ section.

**Comment by sbrannen** [comment]
Resolved in cf4a63be5e6fa69baf5d9eedaf662b6ca0665981

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, I resolved this issue in cf4a63be5e6fa69baf5d9eedaf662b6ca0665981, but please read the comments above in the _Further Analysis_ section as well as in the commit message. Namely, we could consider adding a true "find first method" algorithm to the platform in order to avoid needlessly searching an entire type hierarchy after having already found the method we are looking for (e.g., an annotated method in a leaf class).

Thoughts?

**Comment by marcphilipp** [comment]
Absolutely agree! Maybe we can delegate both to a stream-based private method?

**Comment by gaganis** [comment]
I have seen @sbrannen comments in the https://github.com/junit-team/junit5/commit/cf4a63be5e6fa69baf5d9eedaf662b6ca0665981 and I have looked at the code and I pondered how this might be solved. 
 
I have seen this problem before where the code was copy pasted and different for each traversal type and it proved difficult to maintain-keep in sync.

So I came up with this idea to model a solution with a Visitor pattern similar to JDK's Files.walk and Visitor.

--- 
- A MethodWalker would be introduced that could be configured to traverse TOP_DOWN or BOTTOM_UP 
- MethodVisitor's eg a FindFirstVisitor that would stop on the first method visited/found.  Also eg a  FindAllMethodsVisitor would accrue all methods visited/found.

It would introduce the creation of a couple of more objects but it would help with keeping the common code together.

This is something that I am interested working on.

Please let me know what you think!

**Comment by sbrannen** [comment]
@gaganis, I don't think we actually need to go the _visitor_ route here. The algorithm for finding such a _first method_ would likely be considerably simpler. For example, it wouldn't need to take into account method shadowing, since such an algorithm would only ever use _bottom-up_ search semantics and stop once it finds the first method matching the predicate. Also, the predicate would have to be applied eagerly, not lazily like in the current search algorithm.

**Comment by sbrannen** [comment]
@gaganis and @junit-team/junit-lambda, I have opened #734 to address the _find-first_ algorithm.
