### ISSUE TITLE
Jupiter DiscoverySelectorResolver: to prune or not to prune

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#732]
## Overview

This issue is a follow up from #720 where [question](https://github.com/junit-team/junit5/pull/720#discussion_r105541997)  arose: _Do we really need to prune here (since DefaultLauncher will do it later anyway)?_

When the line `engineDescriptor.pruneTree();` is deleted, three `DiscoverySelectorResolverTests` fail:

- `resolvingSelectorOfNonTestMethodResolvesNothing()`
- `resolvingUniqueIdWithWrongParamsResolvesNothing()`
- `resolvingUniqueIdOfNonTestMethodResolvesNothing()`

## Deliverables

- [x] Investigate and decide if the pruning call can be omitted

**Comment by marcphilipp** [comment]
If we implement the ideas in https://github.com/junit-team/junit5/issues/508#issuecomment-293544977 we will have to keep pruning in Jupiter because Launcher will no longer do so.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
Rather than removing the pruning call in Jupiter, we have decided to remove the pruning call in `DefaultLauncher`.

**Comment by marcphilipp** [comment]
It seems sometimes you have to spell things out to realize that something is off...

Pruning in `DefaultLauncher` is actually necessary, because it applies `PostDiscoveryFilters` (e.g. tags) and then needs to remove empty containers that will not register dynamic tests from the `TestPlan`. Thus, I've

**Comment by marcphilipp** [comment]
In d438a97, I've reintroduced pruning in `DefaultLauncher`. So, the question remains: Do we need to prune in Jupiter's `DiscoverySelectorResolver`. It doesn't hurt, but could have an impact on runtime.
