### ISSUE TITLE
Remove deprecated Launcher.execute() method

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#740]
## Overview

Addressing issue #628 with PR #739 marked the old single-parameter `Launcher.execute(LauncherDiscoveryRequest launcherDiscoveryRequest)` as deprecated.

Remove this method and revert all explicit `Launcher.execute(request, new TestExecutionListener[0])` invocations that were introduced by #739.

## Deliverables

- [ ] Revert https://github.com/junit-team/junit5/commit/cb6ca6823ac854165246caebd6dcafe2e085d981 before RC1

**Comment by sormuras** [comment]
in progress...

**Comment by sormuras** [comment]
Partly reverting this commit to make current IDE(A)s running local tests again.

This new code will be removed before GA!

**Comment by sbrannen** [comment]
> This new code will be removed before GA!

Then we should remove the "in progress" label for now and assign this issue to RC1.

Or... are you doing work on it right now?

**Comment by sormuras** [comment]
I am. ;-)

**Comment by sormuras** [comment]
Revert https://github.com/junit-team/junit5/commit/cb6ca6823ac854165246caebd6dcafe2e085d981 before RC1

**Comment by sormuras** [comment]
Updated deliverables.
