### ISSUE TITLE
Add nullability annotations to code base for better tooling assistance

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#741]
## Overview

**Context:** When implementing extensions in Kotlin I noticed that when generating the members in IntelliJ the method signatures had nullable types like `ContainerExtensionContext?`:

```kotlin
class MyExtension : BeforeAllCallback {
  override fun beforeAll(context: ContainerExtensionContext?) {
    TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
  }
}
```

The desired behavior when implementing something like this is to have the generated type represent what the documentation says. I would like the generated parameter to be `ContainerExtensionContext` instead of `ContainerExtensionContext?`.

It is also useful to have when looking at Javadoc or implementation as well as when using some static code analysis tools.

An overview of the support Kotlin compiler annotations can be found [here](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations), but these can benefit authors in other languages as well.

## Deliverables

- [ ] nullable library chosen
- [ ] `@NonNull` and `@Nullable` (or other annotations) are applied to method parameters

**Comment by smoyer64** [comment]
This is the fourth task in #358 - I'm completely in favor of annotations to help static code analysis tools and we'll be using one in junit-pioneer (https://github.com/junit-pioneer/junit-pioneer/issues/33).  It would be really convenient to use the same libraries in both JUnit 5 and in Pioneer.

**Comment by mkobit** [comment]
@smoyer64 good catch, I didn't see that issue.

I think this one can be closed as a duplicate.

**Comment by smoyer64** [comment]
Your issue has additional information (Kotlin related) ... would it be better to merge the two issues or just let them reference each other?

**Comment by mkobit** [comment]
@smoyer64 that makes sense to me as well. I believe the issue you referenced is more of a superset of this one, and hopefully solving that one solves this one.

**Comment by marcphilipp** [comment]
Thanks for the Kotlin example! I've added a corresponding comment to #358. Closing this issue as a _duplicate_.

**Comment by sbrannen** [comment]
- Superseded by #4550
