### ISSUE TITLE
Introduce lifecycle support for objects stored in ExtensionContext.Store

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#742]
## Overview

As mentioned in https://github.com/junit-team/junit5/issues/710#issuecomment-287634552, JUnit Jupiter should ideally have lifecycle support for objects stored in the `ExtensionContext.Store`.

For example, when the execution of a given level in the test execution hierarchy has completed, we should properly _close_ the execution context and any objects within it.

## Deliverables

- [ ] Introduce lifecycle support for objects stored in `ExtensionContext.Store`.
  - Specifically, for objects that implement `Closeable` or `AutoCloseable`.

**Comment by sormuras** [comment]
#1174 will introduce the "closeable resource" part.

Do we need/want a "general purpose _on close_ callback" as well? Meaning an interface like `ExtensionContextOnCloseCallback` which can implemented by `Extension`s to get notified when their context is teared down?

**Comment by sbrannen** [comment]
No, I think we can forego the introduction of an additional extension API for the time being.
