### ISSUE TITLE
Unmappable character for encoding Cp1250

### ISSUE THREAD

**Issue by Januson** [junit-team/junit5#745]
## Overview

After a fresh **git clone** running **gradlew clean assemble** fails with following error.

> E:\Projects\Git\java\junit5\junit-jupiter-api\src\main\java\org\junit\jupiter\api\Assertions.java:907: error: unmappable character for encoding Cp1250
>          * Ôöé  Ôöé  Ôöé     status: Ôť? FAILED
>
> E:\Projects\Git\java\junit5\junit-jupiter-api\src\main\java\org\junit\jupiter\api\AssertLinesMatch.java:111: error: unmappable character for encoding Cp1250
>                                                 fail(expectedLines, actualLines, "fast-forward(Ô?×) didn't find: `%s`", snippet(expectedLine));

This happened with Intellij IDEA 2017.1 and gradle wrapper 3.4.1. I tried to set the encoding for whole project in IDEA but without any effect.
Adding **options.encoding "UTF-8"** to **javadoc** resolved the issue.
```
javadoc {
    options.memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
    options.author = true
    options.header = project.name
    options.addStringOption('Xdoclint:html,syntax', '-quiet')
    options.encoding "UTF-8"
}

**Comment by sormuras** [comment]
I can't reproduce the errors on Windows 10 and default IJ 2017.1 installation. But having the encoding set to `UTF-8` makes sense. Or switch example snippets to use only default 7-bit ASCII characters.

**Comment by sormuras** [comment]
@Januson Can you please try again and drop a note whether the javadoc now compiles on your box?

**Comment by Januson** [comment]
@sormuras Yes. It works now.

**Comment by sormuras** [comment]
Thanks for reporting and retesting @Januson
