### ISSUE TITLE
Consideration of create a new annotation to be executed before of @Parameters

### ISSUE THREAD

**Issue by manueljordan** [junit-team/junit5#752]
## Overview

I have assumed that `@BeforeClass` is executed before of `@Parameters`. 
I did realize it is not true. 

## Situation

The situation is that `@Parameters` needs mandatorily data initializated from `@BeforeClass`. 

Now, because my original assumption was wrong, my unique way to around this is through a `static` block to accomplish my goal.

## Original Proposal

Assuming this behaviour is the expected. Create a new annotation to accomplish the following order:

* `@NewAnnotation` such as "@BeforeParameter"
* `@Parameter`
* `@BeforeClass`
* `@Before`
* `@Test`

**Comment by sbrannen** [comment]
This issue tracker is for JUnit 5; whereas, your inquiry only applies to JUnit 4.

Please raise your issue against https://github.com/junit-team/junit4/issues.

**Comment by manueljordan** [comment]
>  your inquiry only applies to JUnit 4

Should I assume this situation is already fixed in version 5?

**Comment by marcphilipp** [comment]
M4 includes support for parameterized tests (see http://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests). They work a bit different than in JUnit 4.

There, `@BeforeAll` is called before any parameter-providing method.

**Comment by manueljordan** [comment]
Thanks by the link. I appreciate your support. Thanks again
