### ISSUE TITLE
Support for new annotation equivalent to TestInstancePostProcessor

### ISSUE THREAD

**Issue by ttddyy** [junit-team/junit5#753]
## Overview

Currently, there is a `TestInstancePostProcessor` extension point, but there is no equivalent annotation.

Similar functionality can be achieved by instance initializer block, but it cannot have access to the context info that JUnit Jupiter DI provides. 

New annotation should be annotated on instance method, so that logic that once-per-test-class but don't-want-to-be-in-static-method can be performed.

## Deliverables

- [ ] Introduce an annotation analogous to the `TestInstancePostProcessor` extension point  
  for example, `@[Post|After]Instantiation`, `@AfterConstruct`, `@ProcessTestInstance`, etc.

**Comment by sbrannen** [comment]
If we introduce such support, my recommendation would be to simply support the standard `@PostConstruct` annotation.

**Comment by marcphilipp** [comment]
Would a constructor with a `TestInfo` argument work for you?

**Comment by ttddyy** [comment]
yeah, constructor works. Thanks @marcphilipp 

Also, I'm wondering how about having annotation for a method that is called after all tests in a class have executed. Similar to `@AfterAll` but on instance method.

**Comment by marcphilipp** [comment]
That method would only be called once? On which instance?

**Comment by sbrannen** [comment]
I'm not sure it warrants an additional annotation.

I'd rather just consider it a choice between lifecycle modes for test instances... which is coming soon (likely in M5). Then `@AfterAll` will meet your needs (in "test instance per test class" mode).

**Comment by ttddyy** [comment]
ah, my bad. I forgot junit creates test instance per method.
And if lifecycle mode is added(instance per test class), then `@AfterAll` on instance method is sufficient.

Thanks,
