### ISSUE TITLE
Improve documentation of DynamicTest lifecycle (round 2)

### ISSUE THREAD

**Issue by avandeursen** [junit-team/junit5#754]
The [documentation](http://junit.org/junit5/docs/5.0.0-M3/user-guide/#writing-tests-dynamic-tests) for JUnit5's dynamic tests states:

> @`BeforeEach` and @`AfterEach` methods and their corresponding extension callbacks are not executed for dynamic tests. 

Reading this I thought BeforeEach methods are not executed at all if a class has dynamic tests.

What happens, however, is that such methods are executed, but just once. For example, I have a class with one `BeforeEach` method (`setUp`, which sets some fields), and 8 dynamic tests (which use these fields without modifying them). Executing these tests results in:

1. The `setUp` method is called exactly once and initializes the field
2. After that the 8 dynamic tests are executed.

So the tests work, but:

- The BeforeEach intuitively behaves more like a (non-static) BeforeAll
- The behavior seems inconsistent with what is written in the documentation

Is this the correct intended behavior?

If it is, should the documentation be updated?

Bumped into this while migrating an existing @`Parameterized` test -- which relied on an @`Before` annotation.

**Comment by ledoyen** [comment]
In my understanding, `@BeforeEach` and `@AfterEach` (and equivalent extensions) mean **@BeforeEachTestMethodInvocation** and **@AfterEachTestMethodInvocation**.

In your case, only one method defines DynamicTests, so, only one invocation of this test method is done, along with one invocation of `@BeforeEach` method.

**Comment by marcphilipp** [comment]
The behavior is intended but needs better documentation: The methods/callbacks are only executed for test factory methods, not for the dynamic tests they produce.

**Comment by sbrannen** [comment]
See related discussions in #374 and #386 for further inspiration.

**Comment by hglasgow** [comment]
Hi, I've created a pull request that I hope clarifies the callback lifecycle for dynamic tests.

**Comment by sormuras** [comment]
Thanks @hglasgow

With #813 on the horizon we need to update and clarify the "dynamic tests" documentation, again. :)

**Comment by hglasgow** [comment]
Hmmm. The CI checks are failing. _"Run 'gradlew spotlessApply' to fix these violations."_ But this task has no effect on the file when I run it locally. Eclipse Neon; Windows 10.

**Comment by sbrannen** [comment]
> _"Run 'gradlew spotlessApply' to fix these violations."_ But this task has no effect on the file when I run it locally. Eclipse Neon; Windows 10.

That sounds a bit odd.

What happens if you run `gradlew spotlessApply` from the command line?

Also, it appears that you simply have trailing spaces at the end of several of those lines. So manually deleting all trailing spaces might resolve the problem for you.

**Comment by hglasgow** [comment]
Thanks, removing the trailing spaces has fixed the CI builds.

**Comment by sbrannen** [comment]
@hglasgow, glad that sorted it out for you!

Let's see what @avandeursen has to say about your proposal.
