### ISSUE TITLE
Remove final from EngineDescriptor.getType()

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#755]
While implementing a minimal engine with @mmerdes we got bitten by the fact that we cannot override `EngineDescriptor.getType()` with `return Type.Test`. 

This would be very useful for an engine that does nothing but delegate to an external tool for running tests. In case there is no strong rationale for not allowing an engine to be an executable test itself. 

A possible workaroung might be to override `TestDescriptor.isTest()` and `isContainer()` but then `getType()` and `isTest()` would no longer be consistent.

**Comment by sormuras** [comment]
The `final` was only introduced because of the `Type.ENGINE` constant, which I thought was a fundamental building block that never will neither be a container nor a test. What about an explicite `Type.ENGINE_AND_TEST` constant? Feels a bit like an overkill.

**Comment by jlink** [comment]
`Type.ENGINE_AND_TEST` feels clumsy but it looks like the easiest way to go.

Maybe `Type` could evolve from enum to class with `isTest` and `isContainer` methods.

**Comment by sormuras** [comment]
Thinking about your initial comment, stating: "[...]override TestDescriptor.isTest() and isContainer() [...]" is more and more appealing to me.

You _are_ creating an engine. So, the default/final `Type.ENGINE` is correct. An engine is by default a container -- but your special one is a test. So, return `true` when your descriptor is asked `.isTest()`. There's no need to be consistent with the default implementation. If it was important, we could have removed the `isContainer()` and `isTest()` accessors.

**Comment by jlink** [comment]
Ok. We'll try that.

**Comment by sormuras** [comment]
What are your results on this topic, @jlink ?

**Comment by jlink** [comment]
Not yet tried. 
My guess is that the whole topic might hide a few more quirks, e.g. https://github.com/junit-team/junit5/issues/756

**Comment by sormuras** [comment]
**Team decision**: Remove the `Type.ENGINE` enum constant, change `EngineDescriptor` to return `Type.CONTAINER` and remove the `final` modifier from `EngineDescriptor.getType()`
