### ISSUE TITLE
Upgrade from github-pages to git-publish

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#757]
## Overview

The following note is printed while building JUnit 5:
```
org.ajoberstar.github-pages is deprecated will be removed in gradle-git 2.0.0.
Users should migrate to org.ajoberstar.git-publish.
```

## Deliverables

- [X] Migrate to org.ajoberstar.git-publish https://github.com/ajoberstar/gradle-git-publish
- [x] Adapt Jenkins build

**Comment by marcphilipp** [comment]
Merged and works in Jenkins: 3ec7c96a5df5dbc2a15283f6ce495719eefa4c3d
