### ISSUE TITLE
Allow possibility to change display name during execution

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#758]
## Use Case

A test engine (or Jupiter extension) might want to enhance the display name with additional information, e.g. a reason for failure or random seed in case of property testing.
This could make dealing with concrete failures simpler.

## Alternatives

Additional information can already be logged via `EngineExecutionListener.reportingEntryPublished()` but this info is usually hidden in stdout or some log.

## Possible solution

Add an additional event method, eg
```
EngineExecutionListener.changeDisplayName(descriptor, newName)
```
or 
```
EngineExecutionListener.appendDisplayName(descriptor, appendix)
```

**Comment by marcphilipp** [comment]
I think that's a good idea. I have been toying with the idea myself, too. We could even make it more "generic" and allow engines to report arbitrary (e.g. display name, legacy reporting name, source, tags etc.) changes to a `TestDescriptor`, e.g. `EngineExecutionListener.propertyChanged(TestDescriptor, PropertyChangeEvent)`.

However, I'm not sure how we would report those changes to tools that use `TestIdentifier`. Those are immutable, so we cannot update them. We can create a new, updated instance and replace the one in the `TestPlan`. But we'd also need to add a method to `TestExecutionListener`, e.g. `propertyChanged(TestIdentifier old, TestIdentifier new, PropertyType type)`.

@junit-team/junit-lambda What do you think?

**Comment by sormuras** [comment]
I never felt the need to change a test name at runtime before. Having `@DisplayName` now is good, as the name of a test was always my human-readable (almost unique) ID for the test. I use those names when searching test logs...

If I want to report some extra information, I'd use the reporting-facility you mentioned.

**Comment by sbrannen** [comment]
I'm also not convinced that changes to such properties at runtime is a good idea.

I would rather report _special things_ via reporting entries. If the tooling and report generators don't yet support reporting entries, that's a different topic.

We shouldn't introduce new features just to circumvent the (current) lack of tooling support.

If we want tools (e.g., IDEs) to support a feature we already have (i.e., reporting entries), we should ask for support in the respective tools.

**Comment by sbrannen** [comment]
@marcphilipp, do you have any concrete use cases for when it would make sense for _legacy reporting name, source, and tags_ to change dynamically?

**Comment by sormuras** [comment]
Team decision: display names stay immutable at execution time.

#162 will provide means to change ("beautify") display name at discover time.
