### ISSUE TITLE
3rd-party friendly entry point in ConsoleLauncher

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#763]
## Overview

Make [ConsoleLauncher](https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/ConsoleLauncher.java#L38) more re-usable by external applications by providing an `execute(String...)` method that returns an exit code and does **not** call `System.exit(code)`.

Use-case https://github.com/forax/pro plugin:
https://github.com/sormuras/pro/blob/plugin_junitconsole/src/main/java/com.github.forax.pro.plugin.junitconsole/com/github/forax/pro/plugin/junitconsole/JunitConsolePlugin.java#L36

## Deliverables

- [ ] Split `static` main method into two, the normal main delegating to the new one, that is more 3rd-party friendly.

**Comment by sormuras** [comment]
Team decision: use [Launcher API](http://junit.org/junit5/docs/current/user-guide/#launcher-api) instead.

**Comment by sbrannen** [comment]
@sormuras, since you addressed this is bedf19ae8d0f7230de813de3e75758ff6dadac6e, shouldn't we remove the "won't fix" label and assign this to 5.0 M5?

**Comment by sormuras** [comment]
Good idea.
