### ISSUE TITLE
Allow LauncherFactory to be configured regarding engines and listeners

### ISSUE THREAD

**Issue by baev** [junit-team/junit5#767]
## Overview

Currently the only way to create DefaultLauncher is use `LauncherFactory.create()` method, that loads engines and listeners via SPI. In some cases it would be nice to have an ability to directly specify the engines and listeners for launcher. 

In my case I want to load engines with SPI, but disable SPI for listeners

**Comment by sbrannen** [comment]
Thanks for raising the issue. We'll look into it.

**Comment by sbrannen** [comment]
Closing this issue since the brunt of the work has been completed in #1269.

**Comment by sbrannen** [comment]
Reopening to address the remaining TODOs from the PR:

- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

**Comment by sbrannen** [comment]
All TODOs are now completed in `master`.
