### ISSUE TITLE
Publish JUnit Platform Gradle Plugin to Gradle plugin repository

### ISSUE THREAD

**Issue by jackmiras** [junit-team/junit5#768]
The current gradle plugin implementation where Junit 5 is available doesn't support the new syntax of plugins inclusion from gradle.

Currently in order to include Junit 5 in a gradle project I have to implement the following script:
```groovy
buildscript {
    repositories { mavenCentral() }
    dependencies { classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M4' }
}

apply plugin: 'org.junit.platform.gradle.plugin'

```

But recently gradle include a new feature that allows us to load plugins by implement a shorter script, just like down below:
```groovy
plugins {
    id 'org.junit.platform.gradle.plugin' version '1.0.0-M4'
}
```

Unfortunately is not possible to load Junit 5 plugin in the second way because to load plugins in that way the plugins must be "uploaded" in the [plugins gradle repositorty](https://plugins.gradle.org)... The steps to inclue a plugin in the repository is available in the following [link](https://plugins.gradle.org/docs/submit).

**Comment by sbrannen** [comment]
We are aware of this and will look into it.

Cheers!

**Comment by jochenchrist** [comment]
The plugin id should simply be 
```
org.junit.platform
```

as the suffix in `.gradle.plugin` is quite obvious in the Gradle plugin repo.

**Comment by sormuras** [comment]
I really hope, after the [4.0](https://docs.gradle.org/4.0-rc-2/release-notes.html) dust settles, the native/core plugin will be designed and implemented: https://github.com/gradle/gradle/issues/1037

**Comment by Minecrell** [comment]
If anyone stumbles on this issue trying to use the JUnit Platform Gradle Plugin together with [kotlin-dsl] and its automatically generated extension accessors, it's also possible to use the `pluginManagement` DSL as a workaround to make the plugin available within the `plugins` block. By default, [kotlin-dsl] only generates extension accessors for plugins applied in the `plugins` block so the solution below is necessary if you want to access `junitPlatform` directly in your build script.

If you add this to `settings.gradle`:

```gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = ArtifactRepositoryContainer.MAVEN_CENTRAL_URL }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'org.junit.platform.gradle.plugin') {
                useModule("org.junit.platform:junit-platform-gradle-plugin:${requested.version}")
            }
        }
    }
}
```

You can then reference it normally with the plugins DSL:

```kotlin
plugins {
    id("org.junit.platform.gradle.plugin") version "1.0.0"
}

junitPlatform {
    platformVersion = "1.0"
    logManager = "org.apache.logging.log4j.jul.LogManager"
    setReportsDir(file("build/test-results/junit-platform"))
}
```

[kotlin-dsl]: https://github.com/gradle/kotlin-dsl

**Comment by sdeleuze** [comment]
+1 for publishing the plugin, this is especially needed for Kotlin developers.

**Comment by sbrannen** [comment]
Switched to 5.1 Backlog

**Comment by sdeleuze** [comment]
@Minecrell As reported [here](https://github.com/sdeleuze/spring-kotlin-fullstack/issues/1), this workaround seems to work only when the plugin is in Gradle cache. I have raised the point to gradle team and am waiting their feedback.

**Comment by Minecrell** [comment]
@sdeleuze Weird, it's still working for me after deleting the `~/.gradle` cache. It downloads the JUnit Gradle plugin automatically. 

I think this is something that is broken specifically only for your project. I can't tell for sure, but it looks like the issue in your case is somehow connected to the custom Maven repository and the specific setup of the POM of `org.springframework.boot:spring-boot-gradle-plugin:2.0.0.M5`.

The workaround I've posted above is working correctly for the JUnit Gradle plugin.

**Comment by sdeleuze** [comment]
@Minecrell It works in your case probably because all your artifacts are in Maven Central, when you are using multiple repos, it is broken, see https://github.com/gradle/gradle/issues/3210#issuecomment-337156450.

**Comment by dmvk** [comment]
Is there any blocker for this issue? This could make move to junit 5 much less painful for gradle users.

**Comment by marcphilipp** [comment]
We're working with Gradle towards official support so it might be better not to publish it to the Gradle plugin repository in order to avoid confusing future users.

@junit-team/junit-lambda Thoughts?

**Comment by guenhter** [comment]
I guess with gradle 4.6, this is no longer an issue because support is now integrated.

https://docs.gradle.org/4.6/release-notes.html?_ga=2.23402686.529326761.1520834024-229490448.1507271429#junit-5-support

**Comment by sbrannen** [comment]
Good point.

Thanks for mentioning it!

I'll close this issue now...
