### ISSUE TITLE
VintageTestEngine attempts to execute abstract test classes

### ISSUE THREAD

**Issue by LiamClark** [junit-team/junit5#769]
## Overview
I believe I stumbled on a bug, my use case is the following:

I have an abstract class containing tests and a constructor:

```java
import org.junit.Test;

public abstract class BugTest {

    public BugTest(int x) {

    }

    @Test
    public void test() {}

}
```

Please note that currently it's using the JUnit 4 `@Test` and a sub class extending this class providing the constructor argument: 

```java
public class SubBugTest extends BugTest {
    public SubBugTest() {
        super(2);
    }
}
```

There are various interactions with this construct between gradle and maven.  The outputs are shown below. The build.gradle and pom.xml are copies of the sample projects.

## Running the tests through maven ##
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Apr 05, 2017 10:30:45 AM org.junit.jupiter.engine.discovery.JavaElementsResolver resolveClass
WARNING: Class 'com.BugTest' could not be resolved
Running com.BugTest
Apr 05, 2017 10:30:45 AM org.junit.jupiter.engine.discovery.JavaElementsResolver resolveClass
WARNING: Class 'com.BugTest' could not be resolved
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec <<< FAILURE! - in com.BugTest
initializationError  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.Exception: Test class should have exactly one public zero-argument constructor

Running com.SubBugTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.SubBugTest

Results :

Failed tests: 
  BugTest »  Test class should have exactly one public zero-argument constructor

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
```

# Changing the annotation in the super class to org.junit.jupiter.api.Test the error goes away:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Apr 05, 2017 10:33:33 AM org.junit.jupiter.engine.discovery.JavaElementsResolver resolveClass
WARNING: Class 'com.BugTest' could not be resolved
Running com.BugTest
Apr 05, 2017 10:33:33 AM org.junit.jupiter.engine.discovery.JavaElementsResolver resolveClass
WARNING: Class 'com.BugTest' could not be resolved
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.BugTest
Running com.SubBugTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.SubBugTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

## Running with gradle ##

```
Running with the JUnit 4 `@Test` the results are:

Test run finished after 20 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

Running it through gradle gives slightly different results, using the jupiter api `@Test` everything works beautifully, 

```
Test run finished after 30 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         0 tests failed          ]
```

## Deliverables

- [x] Update `VintageTestEngine` so that it no longer attempts to execute abstract test classes but rather simply logs a warning when an abstract test class is _discovered_.

**Comment by sbrannen** [comment]
This is indeed a _bug_. 

Thanks for raising the issue!

**Comment by marcphilipp** [comment]
Thanks for raising the issue, @LiamClark!

I think this actually demonstrates multiple problems:

1. While the Jupiter engine logs a warning when it gets a `ClassSelector` for an abstract class, the Vintage engine blindly tries to run it and, unsurprisingly, fails.
1. The Surefire provider currently is unable to determine whether a class is executable as a test from the `TestPlan` it gets from the `Launcher`.

While we're discussing how to solve (2), I think the proper behavior for (1) is pretty clear: The Vintage engine should apply the same predicate it uses for classpath scanning (`IsPotentialJUnit4TestClass`) to the result of discovery. From a brief look on the code, I think filtering the classes inside `TestClassCollector` in `JUnit4DiscoveryRequestResolver` and logging warnings for those that were excluded should work.

---

There may be an additional issue. When I copy the two classes into the sample Gradle consumer and delete all other test classes, the test is discovered and executed:

```
Test run finished after 10068 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         0 tests failed          ]
```

From `build/test-results/junit-platform/TEST-junit-vintage.xml`:

```xml
<testcase name="test" classname="com.example.project.SubBugTest" time="0.001">
<system-out><![CDATA[
unique-id: [engine:junit-vintage]/[runner:com.example.project.SubBugTest]/[test:test(com.example.project.SubBugTest)]
display-name: test
]]></system-out>
</testcase>
```

Did you also use M4? Something must be different in your setup. Can you provide more details or, if possible, share the project?

**Comment by LiamClark** [comment]
@marcphilipp I forked the sample project and added the classes there, it still shows the same behaviour for me. It's located here https://github.com/LiamClark/junit5-samples

**Comment by marcphilipp** [comment]
Ah, `SubBugTest` isn't `public` in your project and thus not excluded when scanning the classpath. So, I think we can forget about that issue.

Do you want to give fixing (1) a shot?

**Comment by LiamClark** [comment]
@marcphilipp I must have removed the public when I tried maven with jupiter, my bad!

I just opened #776 as my attempt for fixing (1)

**Comment by sbrannen** [comment]
FYI: updated _Deliverables_ and formatted example output.

**Comment by sbrannen** [comment]
> I just opened #776 as my attempt for fixing (1)

If you had referred to this issue in the commit message for your PR, you wouldn't have to explicitly state that since GitHub would do it for you. 😉

**Comment by marcphilipp** [comment]
Reopening to address Surefire issue.

**Comment by sbrannen** [comment]
> Reopening to address Surefire issue.

Out of curiosity, which issue are you referring to?

**Comment by marcphilipp** [comment]
> The Surefire provider currently is unable to determine whether a class is executable as a test from the `TestPlan` it gets from the `Launcher`.

**Comment by sbrannen** [comment]
Don't you think we should address the Surefire issue in a different, dedicated ticket?

**Comment by marcphilipp** [comment]
You're right. I just wanted to keep this ticket open as a reminder to create the dedicated ticket. 😉

**Comment by jankotek** [comment]
Also please note that it tries to execute JUnit 3 classes which extends TestCase

**Comment by marcphilipp** [comment]
That's actually on purpose. Why shouldn't it?

**Comment by jankotek** [comment]
@marcphilipp I forgot to add **abstract** classes which extends TestCase

**Comment by marcphilipp** [comment]
@jankotek Thanks for reporting. In 811ab782c6651f89a964c23db164f71ec109b173 I've now added another test to ensure that this has been fixed (in M5), too.

**Comment by marcphilipp** [comment]
I've created #879 as follow-up to improve the Surefire provider.
