### ISSUE TITLE
Publish PDF version of User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#770]
## Overview

The User Guide is currently published in HTML; however, it would be beneficial to provide a PDF download as well.

## Related Issues

- #777 
- #1099 

## Deliverables

- [x] Configure Gradle build to generate PDF version of the User Guide.
- Use the `rouge` syntax highlighting support for PDFs.
  - Since `rouge` is not yet supported for the `html5` _backend_, we would need to have separate configurations for HTML and PDF; see https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/28#issuecomment-25956045
  - Will be addressed in #777.
- Use the `rouge` syntax highlighting support for HTML.
  - Will be addressed in #777.
- [x] Determine why `component-diagram.svg` is not embedded in the generated PDF.
  - See https://github.com/asciidoctor/asciidoctor-pdf/issues/271.
- [x] Ensure that `component-diagram.svg` gets embedded in the generated PDF.
  - See https://github.com/asciidoctor/asciidoctor-pdf/issues/271#issuecomment-291992364 for details.
- [x] Construct links to JavaDoc API as absolute URLs instead of the relative links used in the HTML version of the User Guide.
- Determine if special characters (e.g., emoji from custom display names and glyphs used with `unicode` mode for the `ConsoleLauncher`) can be displayed in the generated PDF.
  - See discussion in https://github.com/asciidoctor/asciidoctor-pdf/issues/323.
  - Will be addressed in #2315.
- [x] Publish PDF version of the User Guide alongside the HTML version.
  - Currently published as http://junit.org/junit5/docs/snapshot/user-guide/index.pdf
  - [x] ~Rename the generated `index.pdf` file to something like `junit-user-guide-5.0.0-M5.pdf`.~ Done in #2314.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
No longer _in progress_: resolved issue with generated diagrams and PDF output.

**Comment by sbrannen** [comment]
FYI: this issue is currently assigned to me.

But if anyone else wants to tackle any of the open deliverables... feel free to do so!

Just add a comment here first, please.

**Comment by sbrannen** [comment]
FYI: I noticed that links to JavaDoc are broken in the PDF and have therefore updated the _Deliverables_ accordingly.

**Comment by sbrannen** [comment]
FYI: the PDF version of the User Guide is actually already published during SNAPSHOT builds and can be downloaded via the following URL.

http://junit.org/junit5/docs/snapshot/user-guide/index.pdf

**Comment by mojavelinux** [comment]
> Construct links to JavaDoc API as absolute URLs instead of the relative links used in the HTML version of the User Guide.

You may want to consider the javadoc inline macro that Aslak Knutsen created. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/implicit-apidoc-inline-macro.rb.

The benefit of that macro is that it's implicit, so it will display just fine when the extension is absent (as plain text). It essentially decorates class names with links to JavaDoc, much like how JavaDoc itself works.

**Comment by mojavelinux** [comment]
> Determine if special characters (e.g., emoji from custom display names and glyphs used with unicode mode for the ConsoleLauncher) can be displayed in the generated PDF.

Yes, this is just a matter of create a custom font. I could help you with that. It's almost impossible to find a single font that has all the characters you need, and creating fonts is actually quite simple.

**Comment by mojavelinux** [comment]
> Rename the generated index.pdf file to something like junit-user-guide-5.0.0-M5.pdf.

I would like to see the Gradle plugin support an output filename pattern that uses AsciiDoc attributes. I've also considered this for core, but since Gradle doesn't use that part of core, it would have to go in both places.

You might still be able to accomplish it using a doLast block.

**Comment by sbrannen** [comment]
@mojavelinux,

> You may want to consider the javadoc inline macro that Aslak Knutsen created. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/implicit-apidoc-inline-macro.rb.

Maybe I'm missing something (since I have zero experience with inline macros and how they are applied/configured), but...

It appears to me that such a macro would be hard-coded; whereas, if we switch from relative paths to absolute paths we would then be required to create the base URL dynamically.

For example, the base URL could be any of the following:

- http://junit.org/junit5/docs/current/api/
- http://junit.org/junit5/docs/snapshot/api/
- http://junit.org/junit5/docs/5.0.0-M2/api/
- http://junit.org/junit5/docs/5.0.0-M3/api/
- http://junit.org/junit5/docs/5.0.0-M4/api/
- http://junit.org/junit5/docs/5.0.0/api/
- etc.

So, would we be able to parameterize such an inline macro?

**Comment by sbrannen** [comment]
@mojavelinux,

> Yes, this is just a matter of create a custom font. I could help you with that. It's almost impossible to find a single font that has all the characters you need, and creating fonts is actually quite simple.

That would be awesome if you'd submit a PR for that!

Seriously.... such a PR would be very well received. 😉

**Comment by sbrannen** [comment]
> I would like to see the Gradle plugin support an output filename pattern that uses AsciiDoc attributes. I've also considered this for core, but since Gradle doesn't use that part of core, it would have to go in both places.

Yep, I'd like to see support for that as well.

Having a web page named `index.html` makes sense (though, only if it's deployed on a web server), but having a PDF named `index.pdf` is next to useless.

> You might still be able to accomplish it using a doLast block.

Sure. Though we'll likely just _rename_ it in our `prepareDocsForUploadToGhPages` task.

**Comment by mojavelinux** [comment]
> It appears to me that such a macro would be hard-coded

Actually, not at all. I'm proposing taking the link completely out of the AsciiDoc. Then, the macro injects the link into the final result. In other words, what you'd type in the AsciiDoc is:

```
@Test
```

or

```
`@Test`
```

or even

```
[.type]`@Test`
```

then, the converter, with help from the inline macro, would write it as:

```
<a href="http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Test.html"><code>@Test</code></a>
```

The whole point is to completely abstract the reference. No absolute base URL. No relative base URL. Just completely automatic.

**Comment by mojavelinux** [comment]
And inline macro can rewrite any inline pattern in the source. While it's recommend to use the `<name>:<target>[<text>]` format, an inline macro can match anything with up to two placeholders.

**Comment by mojavelinux** [comment]
>  if we switch from relative paths to absolute paths we would then be required to create the base URL dynamically.

But sure, you could also just replace:

```
http://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertThat[`assertThat()`]
```

With

```
{uri-junit4-api}/org/junit/Assert.html#assertThat[`assertThat()`]
```

But I'd encourage more laziness than that.

**Comment by mojavelinux** [comment]
What you can to do is capture the semantics and nothing more. So something like:

```
method:Assert#assertThat[api-version=4]
```

**Comment by mojavelinux** [comment]
Any time you are typing long APIs to very specific paths, you are probably typing output. You want to be thinking input.

**Comment by sbrannen** [comment]
@marcphilipp, what happened to the PDF in your latest commits to `master`?

http://junit.org/junit5/docs/snapshot/user-guide/index.pdf is no longer a valid link. 🤔

**Comment by sbrannen** [comment]
@marcphilipp, this is the commit I'm referring to: 6b945ebf9a7d2f75b1fd843e0e9ffa2125412066

**Comment by sbrannen** [comment]
Regarding the missing PDF, never mind: I found the related issue (#1099).

**Comment by davidmichaelkarr** [comment]
So, starting to read about JUnit 5, found https://junit.org/junit5/docs/current/user-guide/ , found the "PDF Download" link.  It displays fine in Firefox.  However, when I download that file and then open it in Windows 7, I get "Cannot extract the embedded font 'be8840+NotoSerif'. Some ...".  This is not just an ignorable warning.  All the text is unreadable. It all shows up as dots.

**Comment by sbrannen** [comment]
@davidmichaelkarr, I experience the exact same issue on a Mac.

Can you please open a new issue?

**Comment by sbrannen** [comment]
Actually, this only appears to be an issue with Adobe Acrobat Reader on my Mac. If I open the same PDF in the _Preview_ app on my Mac, it works fine.

**Comment by sbrannen** [comment]
Oddly, if I download the PDF from `5.3.2` (https://junit.org/junit5/docs/5.3.2/user-guide/) instead of `current` (https://junit.org/junit5/docs/current/user-guide/), the PDF seems fine.

Maybe the PDF got corrupted in the `current` folder.

**Comment by sbrannen** [comment]
GitHub displays both versions of the PDF, but they in fact have different sizes.

https://github.com/junit-team/junit5/blob/gh-pages/docs/5.3.2/user-guide/index.pdf

https://github.com/junit-team/junit5/blob/gh-pages/docs/current/user-guide/index.pdf

I'll see if I can manually copy the one from `5.3.2` to `current`.

@davidmichaelkarr, no need to create a new issue.

**Comment by marcphilipp** [comment]
All but one item have been completed. I opened #2315 for the remaining one.
