### ISSUE TITLE
Compile and test on Java 9

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#775]
## Moved "Lessons learned..." to Wiki

[Lessons learned "JUnit 5 compile and test on Java 9 b162"](https://github.com/junit-team/junit5/wiki/Lessons-learned-%22JUnit-5---compile-and-test-on-Java-9-b162%22)

Here, only the remaining technical steps resulting from the lessons learned are retained.

## Related Issues

- #425

## Deliverables

- [x] Upgrade to Gradle 3.5 - done in master with https://github.com/junit-team/junit5/commit/5ef538f7b7e953f89053de6986e254ee737cf918
- [x] Add information tag stating location from where an engine was loaded from - see #788 
- [x] Merge main Java 8 and this Java 9 build into a single `.travis.yml` script -- via https://github.com/junit-team/junit5/commit/a313a075353a573d97b443ba57dd83db0f00f8fd
- [x] Include [AssertJ 3.7.0](https://github.com/joel-costigliola/assertj-core/milestone/28) - remove jitpack from repositories
- [x] Include [Gradle Shadow 2.0.0](https://github.com/johnrengelman/shadow/milestone/18) - remove jfrog.org/artifactory from repositories
- [ ] ~~Report and~~ remove workaround for ServiceLoader "bug" when "everybody" has access to build 163

**Comment by sbrannen** [comment]
@sormuras, thanks for compiling all of this information! 👍

**Comment by sbrannen** [comment]
FYI: the Shadow plugin has already been upgraded to ASM 5.2: https://github.com/johnrengelman/shadow/issues/285

**Comment by sbrannen** [comment]
Why not just suppress deprecation warnings on the call for now?

Or... would that mess up the JDK 8 build? 😜

**Comment by sbrannen** [comment]
It'll also be nice to be able to switch to [trySetAccessible()](http://download.java.net/java/jdk9/docs/api/java/lang/reflect/AccessibleObject.html#trySetAccessible--), but we'll have to wait until JUnit 6 for that probably.

**Comment by jbduncan** [comment]
Alternatively to waiting for JUnit 6, we might be able to use MR-JAR support coming with Java 9, once we have a clear picture of how MR-JARs fit into Gradle. :)

**Comment by sbrannen** [comment]
> Alternatively to waiting for JUnit 6, we might be able to use MR-JAR support coming with Java 9, once we have a clear picture of how MR-JARs fit into Gradle. :)

Ummmm... yeah... once we can actually (reliably) develop against Java 9 with the whole tool chain (Gradle, all CI servers, IDEs, etc.). So, I'm not going hold my breath for that at the moment.

**Comment by jbduncan** [comment]
Of course.

**Comment by reinhapa** [comment]
I would be happy to help on that as soon you wanted to  start on this issue...

**Comment by sormuras** [comment]
https://twitter.com/qos_ch/status/850301391608438785

Ceki just released **SLF4J version 1.8.0-alpha0**, modularized for Java9/Jigsaw/JPMS/JSR 376, on Maven Central. Let's have look how he did.

**Comment by sormuras** [comment]
W/ daemon (default): http://stackoverflow.com/questions/43318585/how-to-implement-a-custom-runner-in-junit5 works
W/o daemon (--no-daemon): https://travis-ci.org/junit-team/junit5/builds/220480116 fails

Why?

**Comment by sormuras** [comment]
All three open ends are still not resolvable:

- Travis CI (debian trusty) is still on JDK9-B162, see https://launchpad.net/~webupd8team/+archive/ubuntu/java?field.series_filter=trusty
- John did not release Gradle Shadow 2.0.0 yet, see https://github.com/johnrengelman/shadow/releases
- Joel did not release AssertJ 3.7.9 yet, set https://github.com/joel-costigliola/assertj-core/releases

**Comment by joel-costigliola** [comment]
@sormuras AssertJ 3.7.0 should be released in a week or so.

**Comment by sormuras** [comment]
Thanks for the information, Joel! 👍

**Comment by sormuras** [comment]
AssertJ 3.7.0 now used in master via https://github.com/junit-team/junit5/commit/30581c788501729090f3490fe933013420d943fa

**Comment by marcphilipp** [comment]
@johnrengelman Are there any updates regarding Shadow 2.0.0?

**Comment by johnrengelman** [comment]
@marcphilipp I'm going to publish it tonight when I get home.
