### ISSUE TITLE
Use Rouge syntax highlighting in User Guide

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#777]
## Overview

#770 introduced support for generating a PDF version of the User Guide and initially attempted to use _Rouge_ syntax highlighting but stopped short of doing so for the HTML version since _Rouge_ is not yet supported for the `html5` backend in Asciidoctor.

The reason we say "initially" is that we have now stopped using Rouge due to a bug that prevents it from being used on MS Windows. See https://github.com/jneen/rouge/issues/661 for details.

## Related Issues

- #770 
- #1099 

## Deliverables

- [ ] Upgrade to Asciidoctor 1.5.7 once https://github.com/asciidoctor/asciidoctor/issues/1040 has been resolved.
- [ ] Change from `coderay` to `rouge` for syntax highlighting in the HTML and PDF versions of the User Guide once https://github.com/jneen/rouge/issues/661 has been resolved.

**Comment by sbrannen** [comment]
Changed the scope of this issue to both versions of the User Guide due to https://github.com/jneen/rouge/issues/661.

**Comment by mojavelinux** [comment]
I think you should plan to use Rouge 2.0.8 (the next release at the time of this comment). Until then, just stick with CodeRay (which gets the job done).

**Comment by JLLeitschuh** [comment]
This will be really nice because rouge also supports kotlin syntax highlighting. This would be useful for #1001. For now I think I'll just use the java language highlighter.

**Comment by mojavelinux** [comment]
> Rouge is not yet supported for the html5 backend in Asciidoctor.

You'll be happy to know that support for rouge will be included in the upcoming Asciidoctor 2.0.0. Here's the pull request that's introducing it (using the new pluggable syntax highlighter API): https://github.com/asciidoctor/asciidoctor/pull/3033

**Comment by sormuras** [comment]
Good to know ... maybe it's just in time for our 5.4 GA documenation?

**Comment by sbrannen** [comment]
Thanks for the heads up, @mojavelinux!

Looking forward to it.....  But is 2.0 really going to be released _January 31, 2019_ with [48 open issues](https://github.com/asciidoctor/asciidoctor/milestone/10)? 😉

**Comment by mojavelinux** [comment]
Yep. Some issue gardening is still in order (as we overhaul our whole process). It's also merge week. It will probably be a few extra days since releases always take longer than expected, but the train is definitely departing!

**Comment by sbrannen** [comment]
OK. Have fun gardening!

**Comment by JLLeitschuh** [comment]
@marcphilipp Did you convert the Kotlin code blocks to using the kotlin language highlighting?
https://github.com/junit-team/junit5/issues/777#issuecomment-326155338

**Comment by marcphilipp** [comment]
Thanks for the reminder, I totally forgot about that. Done in be2aa2497a75dedceb37bc3297276e230fb4f293.
