### ISSUE TITLE
Introduce deactivation mechanism for conditional test execution

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#78]
## Status Quo

There is currently no way to deactivate or turn off support for conditional test execution.

For example, if a test class or test method is annotated with `@Disabled`, it is always disabled, and there is currently no way to override this behavior. However, there are times when a developer would like to run all _disabled_ tests to see if they are still _broken_ without having to manually delete or comment out all declarations of `@Disabled`.

Similarly, a developer may wish to disable _all_ or _specific_ conditions for a given test run.

## Prerequisites

- #233

## Deliverables

- [x] Introduce a mechanism for turning off conditions -- for example, via a Java system property and/or a _configuration property_ which is supplied to a `Launcher` and propagated to engines via the `ExecutionRequest`.

**Comment by jlink** [comment]
I assumed overriding @Disabled would happen through a launcher parameter.

2015-12-21 17:05 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by sbrannen** [comment]
@jlink, yes, that's likely the most common mechanism for this feature.

When I wrote "an attribute supplied to ... the `ExtensionContext`", I was envisioning that the attribute would be provided to the `Launcher` as a launch parameter and passed from the `Launcher` to the engine and on down to the `ExtensionContext`.

And as an alternative, I'm proposing that we also provide the same support via a system property for command-line usage and in builds where it might not (yet) be possible to supply custom launch parameters.

Does that make sense?

**Comment by marcphilipp** [comment]
Makes sense to me.

**Comment by jlink** [comment]
> Am 21.12.2015 um 17:28 schrieb Sam Brannen <notifications@github.com>:
> 
> @jlink, yes, that's likely the most common mechanism for this feature.
> 
> When I wrote "an attribute supplied to ... the ExtensionContext", I was envisioning that the attribute would be provided to the Launcher as a launch parameter and passed from the Launcher to the engine and on down to the ExtensionContext.
> 
Would the evaluator itself decide to ignore the decision or would the condition extension point not be executed? In other words: Only override @Disabled or all conditional execution?

**Comment by bechte** [comment]
Nice feature. I totally agree with the parameter solution.

I could also think of running tests by their unique id should reactivate them, too. At least it would be a nice-to-have. This only applies for the components that were given by an unique id directly and not for any of their children.

But it would raise complexity (we need to track how a test was discovered) and I am not sure if we want to go that far...

**Comment by schauder** [comment]
How about using tagging for this?

I think/hope some kind of tagging mechanism is planned, which would enable the user to run tests including or excluding certain tests. "disabled" could be just one of those tags, being disable if not explicitly enabled.

**Comment by sbrannen** [comment]
Hi @schauder,

> How about using tagging for this?
> 
> I think/hope some kind of tagging mechanism is planned, which would enable the user to run tests including or excluding certain tests.

We have actually had first-class support for tagging since the JUnit Lambda prototype. This is supported via the `@Tag` annotation. See [Tagging and Filtering](http://junit-team.github.io/junit5/#tagging-and-filtering) in the user guide for details.

> "disabled" could be just one of those tags, being disabled if not explicitly enabled.

`@Disabled` is currently implemented via the _conditional test execution_ feature (i.e., via the `ContainerExecutionCondition` and `TestExecutionCondition` extension APIs). In that regard, the decision as to whether or not a test is _disabled_ is dynamic in nature. However, you make an interesting point: `@Disabled` could in fact be implemented as a static _tag_ instead of a dynamic _condition_. So we will keep that in mind.

In any case, the original title of this issue was misleading. My goal was not to provide support for overriding only the `DisabledCondition` but rather to provide a general mechanism for overriding any implementation of `ContainerExecutionCondition` or `TestExecutionCondition`. The title has therefore been changed to reflect this intent, and I will change the description/deliverables in time as well.

**Comment by sbrannen** [comment]
On second thought, implementing `@Disabled` as a _tag_ has a significant drawback.

I just experimented with this approach:

```java
@Tag("disabled")
public @interface Disabled {}
```

This does in fact achieve the goal of not executing a `@Disabled` test; however, the user is never informed that the tests are disabled/ignored/skipped. In other words, tests that are filtered out due to missing tags are never reported since there is never an attempt to execute them in the first place.

With this in mind, I think we have only two options:

1. Keep `@Disabled` support as it is now (i.e., based on _conditions_).
1. Provide events for "filtered out" tests in the listener API for the `Launcher`.

Thoughts?

**Comment by sbrannen** [comment]
I've actually been proposing for quite some time that _tags_ could be implemented as _conditions_, analogous to `@Disabled`.

Making this switch would come with a freebie: tests filtered out by tags would automatically show up in reports as _skipped_.

So IMO, this is a win-win situation.

Thoughts?

**Comment by jlink** [comment]
Tags is a generic feature for all runners. How could that be done with
conditions?

2016-01-21 16:38 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by marcphilipp** [comment]
I'm with @jlink on this one: Conditional test execution is a feature of the JUnit 5 Engine while tags are a more general feature supported by other engines (e.g. JUnit 4 Engine).

**Comment by jlink** [comment]
Team decision: Implement with simple global launch parameter that will switch off evaluation of conditionals. Hierarchical test engine can then ignore `shouldBeSkipped`.

Investigate if JUnit4 engine can do the same.

**Comment by marcphilipp** [comment]
#233 needs to be resolved first.

**Comment by sbrannen** [comment]
This issue is no longer _blocked_ since #233 has been resolved.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, please review PR #265.

**Comment by sbrannen** [comment]
Merged into `master` in ff6c3f635a444ccc92039420616402e32d3506a9

**Comment by sbrannen** [comment]
@akozlova, 

You may be interested in knowing that is now possible to deactivate JUnit 5's `@Disabled` condition via a JVM system property like this:

`-Djunit.conditions.deactivate=org.junit.*DisabledCondition`

The same property (`junit.conditions.deactivate`) can alternatively be supplied as a configuration parameter to the `Launcher`.
