### ISSUE TITLE
Static inner classes should be considered as a potential JUnit4 test classes

### ISSUE THREAD

**Issue by LiamClark** [junit-team/junit5#781]
## Overview

The current implementation of  [isPotentialJUnit4TestClass](https://github.com/junit-team/junit5/blob/master/junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/IsPotentialJUnit4TestClass.java#L30) excludes any member class. This can be seen in #778. To reiterate, a member class is: 

> A member class is a class whose declaration is directly enclosed in the body of
another class or interface declaration (§8.1.6, §9.1.4).

from the java 8 specification section 8.5 page 256

This also includes static inner classes. But JUnit 4 does consider static inner classes as valid. An example for this would be the [enclosed runner](https://github.com/junit-team/junit4/wiki/'Enclosed'-test-runner-example). 

If a static member class is indeed the only valid one for JUnit4, we can simply add a check:
```java
ReflectionUtils.isStatic(testClass)
```
## Deliverables

- [ ] A corrected implementaiton of `isPotentialJUnit4TestClass`
- [ ] Unit tests for `isPotentialJUnit4TestClass`
- [ ] Bug fix entry in the release notes

**Comment by sbrannen** [comment]
👍
