### ISSUE TITLE
Ensure extension composability in JUnit Jupiter

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#793]
## Status Quo

As can be seen in #766, it is currently too easy to introduce new extensions in JUnit Jupiter that cannot be composed.

We therefore need to introduce a policy and corresponding tests to ensure the composability of all extension APIs in JUnit Jupiter.

## Requirements

A concrete extension must be able to implement all extension APIs supported by JUnit Jupiter without any naming conflicts or ambiguities with regard to method names or method signatures.

## Proposals

The following table displays the proposed renamings for ambiguous extension API methods.

API                                     | Old Name             | New Name
--------------------------------------- | --------             | --------
`ParameterResolver`                     | `supports()`         | `supportsParameter()`
`ParameterResolver`                     | `resolve()`          | `resolveParameter()`
`ContainerExecutionCondition`           | `evaluate()`         | `evaluateContainerExecutionCondition()`
`TestExecutionCondition`                | `evaluate()`         | `evaluateTestExecutionCondition()`
`TestTemplateInvocationContextProvider` | `supports()`         | `supportsTestTemplate()`
`TestTemplateInvocationContextProvider` | `provide()`          | `provideTestTemplateInvocationContexts()`

## Deliverables

- [x] Introduce a policy to ensure extension composability in JUnit Jupiter.
  - for example, in the Wiki and as a step in the release process.
- [x] Introduce `KitchenSinkExtension` for visual inspection of all extension APIs implemented in a single concrete extension.
- [x] Introduce tests to ensure extension composability in JUnit Jupiter.
- [x] Rename existing extension API methods to ensure extension composability.

**Comment by sbrannen** [comment]
Based on the current state of affairs (see [KitchenSinkExtension](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/java/org/junit/jupiter/extensions/KitchenSinkExtension.java)), the following methods should be renamed.

- `org.junit.jupiter.api.extension.ParameterResolver.supports(ParameterContext, ExtensionContext)`
- `org.junit.jupiter.api.extension.ParameterResolver.resolve(ParameterContext, ExtensionContext)`
- `org.junit.jupiter.api.extension.ContainerExecutionCondition.evaluate(ContainerExtensionContext)`
- `org.junit.jupiter.api.extension.TestExecutionCondition.evaluate(TestExtensionContext)`
- `org.junit.jupiter.params.converter.ArgumentConverter.convert(Object, ParameterContext)`
- `org.junit.jupiter.params.provider.ArgumentsProvider.provideArguments(ContainerExtensionContext)`
- `org.junit.jupiter.api.extension.TestTemplateInvocationContextProvider.supports(ContainerExtensionContext)`
- `org.junit.jupiter.api.extension.TestTemplateInvocationContextProvider.provide(ContainerExtensionContext)`

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, the following is my first draft for how to rename ambiguous extension methods.

API                                     | Old Name             | New Name
--------------------------------------- | --------             | --------
`ParameterResolver`                     | `supports()`         | `supportsParameter()`
`ParameterResolver`                     | `resolve()`          | `resolveParameter()`
`ContainerExecutionCondition`           | `evaluate()`         | `evaluateCondition()`
`TestExecutionCondition`                | `evaluate()`         | `evaluateCondition()`
`TestTemplateInvocationContextProvider` | `supports()`         | `supportsTestTemplate()`
`TestTemplateInvocationContextProvider` | `provide()`          | `provideForTestTemplate()`
`ArgumentConverter`                     | `convert()`          | `convertArgumentForParameterizedTest()`
`ArgumentsProvider`                     | `provideArguments()` | `provideArgumentsForParameterizedTest()`

Thoughts?

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, one additional area where we are inconsistent with regard to naming is the topic of _parameters vs. arguments_.

We have `ParameterResolver.resolve()` and `ArgumentsProvider.provideArguments()`... which essentially do the exact same thing: they provide one or more arguments to be passed to a method.

So if at all possible, I would like to see us standardize on the naming of such parameters/arguments and the _actions_ performed by such extensions. In other words, why do we say "resolve" for one use case and "provide" for the other?

Thoughts?

**Comment by marcphilipp** [comment]
Thanks for bringing that up, @sbrannen! I absolutely agree with your concerns regarding `Extension` subinterfaces.

However, I don't think an extension should implement `ArgumentConverter` and `ArgumentsProvider`, i.e. I wouldn't throw them into same kitchen sink. 😉

IMHO `ParameterResolver.resolve()` and `ArgumentsProvider.provideArguments()` are not doing exactly the same thing. While the former _resolves_ a single, distinct parameter (into a unique argument), the latter _provides_ multiple argument lists for an invocation each. Thus, I think the distinction between _parameter_ and _arguments_ is valid (cf. http://stackoverflow.com/a/156778/6327046) and using two different names is actually _less_ confusing, since both serve a different purpose.

**Comment by sbrannen** [comment]
> However, I don't think an extension should implement `ArgumentConverter` and `ArgumentsProvider`, i.e. I wouldn't throw them into same kitchen sink. 😉

Mmmmm.... You're right: while they are in fact _extensions_, technically speaking they are not extensions of `Extension` and therefore should not be implemented by any class that is registered via `@ExtendWith`.

I'll remove them from the kitchen sink.

**Comment by sbrannen** [comment]
FYI: the kitchen sink can now be found [here](https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/KitchenSinkExtension.java).

**Comment by sbrannen** [comment]
Regarding `ParameterResolver.resolve()` and `ArgumentsProvider.provideArguments()`, my primary concern is the wording we currently have in place (e.g., in the JavaDoc).

A `ParameterResolver` clearly _supports_ the resolution of an argument for a given `Parameter`. Thus `supportsParameter()` seems to make sense.

However, a `ParameterResolver` _resolves_ the run-time _argument_ for a given `Parameter`. So I'm a bit hesitant to call the method `resolveParameter()`, since it doesn't actually return a parameter. It rather returns an argument. Thus, I'm starting to think that `resolveArgument()` (or `resolveArgumentForParameter()`) might be a better name. In the very least, I feel we should update the wording in the JavaDoc for `ParameterResolver` to refer to "argument" instead of "parameter" when appropriate.

Thoughts?

**Comment by sbrannen** [comment]
FYI: I have updated the _Deliverables_ and introduced a _Proposals_ section in order to track proposed renamings in a single location.

**Comment by sbrannen** [comment]
FWIW, I'm not completely happy with the current proposals for `TestTemplateInvocationContextProvider`. 

Anyone have any better suggestions for the methods (that aren't 80+ characters long)?

**Comment by sbrannen** [comment]
How about `provideTestTemplateInvocationContext()` as a replacement for `provide()`?

Or... if we follow the _Factory_ design pattern, we could rename `TestTemplateInvocationContextProvider` to `TestTemplateInvocationContextFactory` and rename the method to `createTestTemplateInvocationContext()`.

Thoughts?

**Comment by marcphilipp** [comment]
Since it usually returns multiple `TestTemplateInvocationContext` instances, I think `provide` is a better fit than `create`. So, I would vote for `supportsTestTemplate()` and `provideTestTemplateInvocationContexts()`.

**Comment by sbrannen** [comment]
> Since it usually returns multiple `TestTemplateInvocationContext` instances, I think `provide` is a better fit than `create`. So, I would vote for `supportsTestTemplate()` and `provideTestTemplateInvocationContexts()`.

OK. Thanks for the feedback. I'll update the proposal accordingly.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, are there any objections to the current _Proposal_ (see this issue's description)?

**Comment by sbrannen** [comment]
@junit-team/junit-lambda,

How about the names for the conditions?

Should we stick with the shorter `evaluateContainerCondition()` and `evaluateTestCondition()` variants?

Or should we opt for longer (and more precise) `evaluateContainerExecutionCondition()` and `evaluateTestExecutionCondition()` variants?

**Comment by marcphilipp** [comment]
@sbrannen From our team call: The rest of the team prefers the longer names. 😉

**Comment by sbrannen** [comment]
OK. I've updated the _Proposal_ accordingly. 

Cheers

**Comment by marcphilipp** [comment]
Shouldn't `provideTestTemplateInvocationContext` have an `s` at the end?

**Comment by sbrannen** [comment]
Yep. I'll add the "s".

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, please review the current extension method names in the [KitchenSinkExtension](https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/KitchenSinkExtension.java) and provide comments here if you foresee any issues with the new names.

**Comment by sbrannen** [comment]
I implemented a _dynamic_ kitchen sink extension in db83822190ca9c037fdc2b563ef01ee58b4066e7. 😉

**Comment by sbrannen** [comment]
The policy has been documented in the Wiki on the [Releasing](https://github.com/junit-team/junit5/wiki/Releasing) page.

Since that was the last open task, I am now closing this issue.
