### ISSUE TITLE
Introduce utility for invoking private, protected, and package private methods

### ISSUE THREAD

**Issue by Andrei94** [junit-team/junit5#794]
## Feature request

It would be nice to allow tests to invoke `private`, `protected`, and _package private_ methods. Often times these methods change and the lack for such mechanism makes testing harder, especially when changing the visibility of the method is not a feasible option.

**Comment by sbrannen** [comment]
Do you by any chance use Spring in your projects?

If so, I wrote just such a utility in the `spring-test` module called `ReflectionTestUtils`.

**Comment by Andrei94** [comment]
I use Spring for some of them.

For others, where Spring was not a priority, it would help to have such functionality.

**Comment by sbrannen** [comment]
Well, I can't promise that we will introduce a utility like that in JUnit itself, but I've added the "team discussion" label so that we can discuss it.

**Comment by mkobit** [comment]
This can be accomplished with [`ReflectionSupport` now](https://github.com/junit-team/junit5/blob/8635ea0ad90dfbed84448a00eed3f900813a42b2/junit-platform-commons/src/main/java/org/junit/platform/commons/support/ReflectionSupport.java#L33), right?

**Comment by sbrannen** [comment]
@mkobit, yep... you're totally right!

`invokeMethod(...)` was introduced in `ReflectionSupport` in conjunction with #790.

Although `ReflectionSupport` is actually intended for extension and test engine authors, test authors can of course use it as well.

I am therefore closing this issue.
