### ISSUE TITLE
"Test events were not received" and other issues under IntelliJ

### ISSUE THREAD

**Issue by iirekm** [junit-team/junit5#804]
It seems that `junit-platform-gradle-plugin` behaves completely differently than standard `test` task, and this makes problems:
- `gradle cleanTest test` doesn't cause to rerun tests as normally IntelliJ expects
- `Test events were not received` error in IntelliJ test results view
- The plugin seems to ignore `--tests ...` option
- Now I'm unable to reproduce it, but sometimes I got Gradle exit code 255 when I clicked test method and chose `Run` from context menu

Plugin version: 1.0.0-M4, IntelliJ version: 2017.1.1

It's more issue with this plugin, not with IntelliJ. Without backwards compatibility with `test` task, other IDEs will probably suffer same issues.

IMHO, a good cooperation with IDEs  is a must for any tool to become popular.

**Comment by sbrannen** [comment]
> It seems that `junit-platform-gradle-plugin` behaves completely differently than standard `test` task, and this makes problems:

Yes, this is a well-known issue. For example, see #475, #484, #315, etc.

> IMHO, a good cooperation with IDEs  is a must for any tool to become popular.

We could not agree more!

However, the @junit-team/junit-lambda unfortunately has neither the skill set nor the time to address these issues properly. More importantly, the current architecture of Gradle's standard `test` task infrastructure causes multiple hurdles for proper integration of the JUnit Platform in Gradle.

Consequently, we are in the process of handing over the `junit-platform-gradle-plugin` to the Gradle team. See https://github.com/gradle/gradle/issues/1037 for details.

I am therefore closing this issue.

**Comment by sbrannen** [comment]
@iirekm, thanks for raising the issue!

If you would like to see the issues you raised addressed we strongly encourage you to voice your opinion with the Gradle Team (e.g., via https://github.com/gradle/gradle/issues/1037).
