### ISSUE TITLE
Clean up integrated engine tests 

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#81]
All subclasses of `AbstractJUnit5TestEngineTests` in org.junit.gen5.engine.junit5:
- [x] Detect and remove duplication
- [x] Migrate to JUnit5

**Comment by marcphilipp** [comment]
Another point to consider: I've created `ExecutionEventRecordingEngineExecutionListener` which could replace `TrackingEngineExecutionListener`.

**Comment by sbrannen** [comment]
`ExecutionEventRecordingEngineExecutionListener` looks quite promising. However, since I've yet to look at it in detail... would there be an easy to way to simply assert the number of tests started/skipped/etc. with the _event_ approach, or do you intend that we always explicitly list every single event in the assertions?

**Comment by marcphilipp** [comment]
I think for simple cases asserting the number of tests in a certain category is sufficient.

It would be easy to add getters like `getTestStartedCount()` that simply filter the events by type (`STARTED`) and test descriptor (`TestDescriptor::isTest`) and call `count()` using the Stream API.

**Comment by sbrannen** [comment]
> It would be easy to add getters like `getTestStartedCount()` that simply filter the events by type (`STARTED`) and test descriptor (`TestDescriptor::isTest`) and call `count()` using the Stream API.

Sounds good/elegant.

**Comment by marcphilipp** [comment]
I've pushed  ccf3530 to showcase how using events would look for the JUnit 5 Engine.

**Comment by jlink** [comment]
Nice!

What's left to invent is a better mechanism to check order and nesting of
before and after calls...

2016-01-07 9:32 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by sbrannen** [comment]
Looks good, @marcphilipp. Feel free to convert the other tests to the event-based approach. :wink:

**Comment by jlink** [comment]
I'd also like a somewhat looser way to check for events than `assertRecordedExecutionEventsContainsExactly(...)`, e.g. `assertEventsInOrder` (checking events but ignoring unspecified ones) but I failed to provide it - damned Generics.

**Comment by marcphilipp** [comment]
I was thinking about that as well. We can sort out the generics together next week if need be. ;-)
