### ISSUE TITLE
Remove Node.isLeaf()

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#812]
## Overview

The semantics of `Node.isLeaf()` are unclear. It was introduced to handle dynamic tests. Right now it's not possible to mix dynamic and static children in a container. If `HierarchicalTestExecutor` kept track of already executed `TestDescriptors`, we should be able to get rid of `Node.isLeaf()`.

## Deliverables

- [x] Investigate if we can get rid of `Node.isLeaf()`
- [ ] If so, refactor `HierarchicalTestExecutor` and remove `Node.isLeaf()`

**Comment by marcphilipp** [comment]
_in progress_

**Comment by sbrannen** [comment]
👍

**Comment by sbrannen** [comment]
BTW, I added a small comment to the commit.
