### ISSUE TITLE
Display name for array parameter type can be improved

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#814]
## Overview

JUnit 5 M4 introduces parameterized tests.

When a parameter is of type `String[]`, then the default display name contains `[Ljava.lang.String` instead of array presentation, e.g. `["foo", "bar"]`.

The IDE shows this ugly now:
![image](https://cloud.githubusercontent.com/assets/4306070/25534806/4c4e29a6-2c35-11e7-87b1-83e81abceeee.png)

## Analysis

Caused by substitution `org.junit.jupiter.params.ParameterizedTestNameFormatter#format`. 

## Proposal

`Arrays.deepToString` looks to be able to fix the issue.

**Comment by sbrannen** [comment]
Hi @akozlova,

Thanks for reporting this.

We'll get to it!

Cheers,

Sam

p.s. this is vaguely related to #810.

**Comment by sormuras** [comment]
More related to #764

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
@akozlova, with the commit I'm about to push to `master`, the following will be the new display name for your use case: `[1] [foo, bar]`

How's that?

**Comment by akozlova** [comment]
Perfect, thanks!

**Comment by sbrannen** [comment]
When I said, "I'm about to push...", I spoke too soon.

The core of the solution was done, but... there was a ripple effect that forced me to do a bit of refactoring across the code base. C'est la vie. 😉 

It's in `master` now via commit 4116a6be2822df730a113dce611f0f88b6900b07.
