### ISSUE TITLE
MethodSelector should accept parameter type names supplied in source code syntax

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#815]
## Status Quo

`void test(int i) {}` has signature `test(int)`, though `void test(int[] ints)` has signature `test([I)`.

Source: `org.junit.platform.commons.util.ReflectionUtils#primitiveNameToTypeMap`

## Proposal

I'd rather expect the signature to be JVM method signature or presentable method signature.

Could you please consider to change this?

**Comment by akozlova** [comment]
Also relates to #810

**Comment by sbrannen** [comment]
Hi @akozlova,

> I'd rather expect the signature to be JVM method signature or presentable method signature.

`[I` is in fact the _JVM method signature_ for an argument of type `int[]` in Java source code.

Or... did you mean something different by "JVM method signature"?

In any case, we can consider supporting "source code array type declarations" in addition to the JVM internal format -- for example, we could support both `int[]` and `[I` as a primitive integer array.

Is that what you want?

**Comment by akozlova** [comment]
Yep, Int is from source code and [I is from VM signature. For me source code signatures are easier than [Lava.lang.String;

**Comment by sbrannen** [comment]
@akozlova, 

Before I implement the requested change, I'd like to be totally clear about what you mean...

> MethodSelector expects method signature which is inconsistent

What is the signature "inconsistent" with, the default display name of the method?

> For me source code signatures are easier than [Lava.lang.String;

Easier in what regard? Easier for you to select a method via `DiscoverySelectors.selectMethod(String, String, String)`?

**Comment by sbrannen** [comment]
In my local branch, I've laid the groundwork for this change with the following passing tests.

```java
	@Test
	void loadClassForPrimitiveArrayUsingSourceCodeArraySyntax() throws Exception {
		Optional<Class<?>> optional = ReflectionUtils.loadClass("int[]");
		assertThat(optional).contains(int[].class);
	}

	@Test
	void loadClassForObjectArrayUsingSourceCodeArraySyntax() throws Exception {
		Optional<Class<?>> optional = ReflectionUtils.loadClass("java.lang.String[]");
		assertThat(optional).contains(String[].class);
	}
```

This should then translate to the ability to pass `"int[]"` and `"java.lang.String[]"` as the `methodParameterTypes` argument to `DiscoverySelectors.selectMethod(String, String, String)`.

@akozlova, is that you end goal?

**Comment by akozlova** [comment]
Sorry if I was not clear. The change in your branch should work for selection of test from sources very well. On the other side I can translate the parameter types to the VM names, like [I or [Ljava.lang.String; if you think that junit should support VM names, like $ instead of . in the qualified names. But the idea that some names are source names and some are VM names looks strange to me - that's why this request.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Thanks for the clarification, @akozlova.

I'll put some more thought into the topic and see what can be done.

**Comment by sbrannen** [comment]
> On the other side I can translate the parameter types to the VM names, like `[I` or `[Ljava.lang.String;` if you think that junit should support VM names like `$` instead of `.` in the qualified names.

I think we literally _have_ to support technical VM names, as we do now.

And I think we will continue to use/store the technical names internally.

The only reasonable set of changes I foresee are those that result in the user either _seeing_ the technical name (e.g., in a test display name) or _providing_ the technical name (e.g., via a method selector). For those cases, I agree with you that the user should be able to _see_ and _provide_ the "source code names" of such types.

At the same time, we will continue to _accept_ technical names provided by a user or tool (e.g., IDE or build tool).

How does that sound to you?

**Comment by sbrannen** [comment]
In summary, we should follow [**Postel's Law**](https://en.wikipedia.org/wiki/Robustness_principle) in this context:

> Be conservative in what you do, be liberal in what you accept from others.

**Comment by sbrannen** [comment]
Closing this issue due to the work performed in 6eaeab2de153f334ea09d3328be6e001e617a085 and d2cb326ef1ff71267e99ed2817abff5b9a390747.

**Comment by sbrannen** [comment]
@akozlova, can you please confirm that I have addressed your needs in the aforementioned commits?

Thanks,

Sam

**Comment by sbrannen** [comment]
@akozlova, you might also be interested in #819 which I created as a result of this issue.

**Comment by akozlova** [comment]
Before your latrst commits. What I don't understand is that you support test (int) and not test(I). Given that other names are VM names, why int?
The commit fixes this as well as far as I can tell now. 
Actually I don't insist on 'source signatures', I only want to know what signatures are expected.

**Comment by sbrannen** [comment]
> What I don't understand is that you support test (int) and not test(I). Given that other names are VM names, why int?

Executing the following...

```java
public static void main(String[] args) {
	System.err.println("int   --> " + int.class.getName());
	System.err.println("int[] --> " + int[].class.getName());
}
```

... results in:

```
int   --> int
int[] --> [I
```

Thus `I` is not supported for `int` in Java in terms of performing a "reverse lookup" as we do in `ReflectionUtils`.

So, perhaps it's not the answer you were expecting, but that it is the reason why we don't support `I` as a type when loading classes by name.

**Comment by sbrannen** [comment]
>  Actually I don't insist on 'source signatures', I only want to know what signatures are expected.

The signatures that are _expected_ are those supported automatically by Java's reflection APIs.

The signatures that are _tolerated_ are those correlating to Java source code syntax.

Make sense?

**Comment by sbrannen** [comment]
In addition to what I've already stated in https://github.com/junit-team/junit5/issues/815#issuecomment-298249666, Java also does not support loading a class named `I`.

In other words, there is no such class named `I` in Java, but there is a class named `[I`.

One could also argue that there is no such class named `int[]` in Java, and that would be correct; however, we are now explicitly supporting _source code array syntax_ simply as a means of enhancing usability -- since most developers don't know what `[I` means but immediately recognize `int[]`.

**Comment by sormuras** [comment]
Re-opened because of https://github.com/jlink/jqwik/issues/12

**Comment by sormuras** [comment]
For a method like:

```
@ParameterizedTest
@MethodSource
void testPrimitiveByteArray(byte[] bytes) {
	fail("bytes: " + Arrays.toString(bytes));
}
```

IDEA 2018.1 sends `[byte` as the parameter type name. Which is a mix of VM-internal syntax (it starts with a `[` bracket) and Java source representation (`byte` indicates the type here, not `B`).

JUnit's `ReflectionSupport` understands the followin notations:
- `[I`
- `byte[]`

JUnit doesn't support
- `[byte`

@junit-team/junit-lambda  Shall we add support for this mixed notation?

**Comment by sbrannen** [comment]
No, I don't see any reason to invent any new syntax.

The JUnit Platform already supports binary and source code syntax for array types.

If a client (e.g., build tool, IDE, etc.) wants to _select_ a method that accepts a `byte[]`, JUnit only supports `byte[]` (source code syntax) or `[B` (binary syntax).

**Comment by sbrannen** [comment]
The supported syntax is clearly documented [here](https://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectMethod-java.lang.String-).

I am therefore re-closing this issue.

**Comment by jlink** [comment]
I agree that it looks like a clear IntelliJ bug. What could be improved is the platform's error handling. 

As it is now the error occurs when an engine tries to access `MethodSelector.getJavaMethod()`.
IMO it shouldn't be possible in the first place to create a selector that cannot be resolved.

**Comment by sbrannen** [comment]
That's a tough one, @jlink.

`MethodSelector` is currently generic in that it can be used to select methods that do not correlate to _Java_ methods.

That was one of the design decisions for all of the selectors and sources. Another goal was to avoid eager loading of classes and methods when selectors are created solely from strings.

Perhaps it is a bit too generic for engines that expect Java classes and methods even when selected by strings, but I don't think we can easily change the contract for `MethodSelector` without introducing breaking changes.

I suppose an alternative would be to introduce a `JavaMethodSelector` with corresponding `selectJavaMethod(*)` variants in `DiscoverySelectors`, where those variants eagerly load the corresponding Java class and method.

@junit-team/junit-lambda & @jlink, thoughts?

**Comment by jlink** [comment]
Maybe my imagination isn't sufficiently broad: What kind of method on the JVM wouldn't have to refer to correct JVM type in the field `methodParameterTypes`? I understand that the concrete type might not be resolvable during creation time - due to classloader or module visibility issues - but the syntax should stick to what's possible on the JVM, shouldn't it?

**Comment by sbrannen** [comment]
A test engine does not have to support JVM languages, per se.

One could conceivably create a test engine that executes tests in some scripting language (perhaps homegrown) that is not compiled to JVM byte code.

That was the rationale behind making it generic.
