### ISSUE TITLE
Document DynamicContainer feature

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#831]
## Overview

Followup from #813

## Deliverables

- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] Update user-guide, i.e. include a paragraph about `dynamicTestsWithContainers`

**Comment by sbrannen** [comment]
@sormuras, have the _Deliverables_ all been addressed now?

**Comment by sormuras** [comment]
Aye. Updated bullet list in the description.
