### ISSUE TITLE
Forbid return values from test and lifecycle methods

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#835]
## Status Quo

In the JUnit Jupiter programming model it is currently not forbidden for `@Test` and lifecycle methods (i.e., `@BeforeEach`, `@BeforeAll`, etc.) to have a return value, even if it's _assumed_ that no one declares anything other than `void` as a return type for such methods.

For example, the following currently execute.

```java
@Test
int test() {
	fail("Boom!");
	return 42;
}
```

```java
@BeforeEach
int before() {
	fail("Boom!");
	return 42;
}
```

## Related Issues

- #242 

## Deliverables

- [ ] Forbid return values from test and lifecycle methods via test predicates that exclude such methods.

**Comment by marcphilipp** [comment]
**Team decision:** Forbid via test predicates that exclude such methods.

**Comment by mmerdes** [comment]
in progress
