### ISSUE TITLE
Rename `names` attribute in @MethodSource to `value`

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#836]
## Deliverables

- [ ]  Rename `names` attribute in `@MethodSource` to `value`.

**Comment by marcphilipp** [comment]
I chose `names` to have the possibility of later introducing sth. like `keys`, e.g.:

```java
@ParameterizedTest
@MethodSource(keys="my strings")
void test(String arg) {...}

@ArgumentsProvider(key="my strings")
Stream<String> methodNameIsNotImportant() {...}
```

**Comment by sbrannen** [comment]
OK.

But... what are "keys"? 😕

**Comment by sormuras** [comment]
![keys](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcScEkfquCxV7Oza20aBisQ1r18Am-OQlGFULVehtl5wefSbH0K5)

**Comment by marcphilipp** [comment]
Call it `id` if you like that better.

**Comment by marcphilipp** [comment]
**Team decision:** Rename `names` to `value`.

**Comment by marcphilipp** [comment]
_in progress_
