### ISSUE TITLE
Document JUnit 5 integration with JaCoCo and SonarQube in Maven builds

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#837]
## Feature Request

Add documentation to the User Guide that describes how to enable Jacoco test coverage in Maven builds and how to make it report with SonarQube.  I currently have this running with the following configuration sections in my Maven POM:

```xml
  <properties>
    ...

    <sonar.core.codeCoveragePlugin>jacoco</sonar.core.codeCoveragePlugin>
    <sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
    <sonar.jacoco.reportPath>${project.basedir}/../target/jacoco.exec</sonar.jacoco.reportPath>

    ...
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.7.9</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <destFile>${sonar.jacoco.reportPath}</destFile>
        </configuration>
      </plugin>
      ...
```

Note that while Jenkins builds have the correct test count, SonarQube does not.  SonarQube's percent-covered is however correct.  There may be additional work interacting with the JaCoCo and/or SonarQube teams as JUnit 5 hits the mainstream.

You can assign this task to me if the team decides it's worth documenting.

## Deliverables

- [ ] Add a sub-section in the Maven instructions detailing the above.

**Comment by sbrannen** [comment]
Currently slated for 5.0 M5 for _team discussion_.

**Comment by smoyer64** [comment]
The discussion on #240 is related (although targeted at the JUnit 5 build system as opposed to general use).

**Comment by marcphilipp** [comment]
I think this documentation should rather be done in JaCoCo/SonarQube. 🤔

**Comment by sbrannen** [comment]
I agree with @marcphilipp: I don't see how this information is specific to the JUnit Platform.

Or, @smoyer64, am I missing something?

**Comment by marcphilipp** [comment]
On second thought, we could provide a sample project in junit5-samples. Thoughts?

**Comment by sbrannen** [comment]
Given the request:

> Add documentation to the User Guide that describes how to enable Jacoco test coverage in Maven builds and how to make it report with SonarQube.

... I don't even see how this pertains to JUnit. Unless I'm missing something, this could just as well pertain to JUnit 4, TestNG, etc.

In other words, it's not our job to explain to people how to use features of a build tool or IDE that do not pertain to the JUnit Platform.

So, unless the proposal is updated to address specific needs related to the JUnit Platform, I think we should decline the proposal.

**Comment by smoyer64** [comment]
>   I don't even see how this pertains to JUnit

There are lots of things that don't necessarily pertain to JUnit but will impede adoption ... this suggestion was aimed at the latter.  Can someone with the appropriate privileges add a "won't fix" label?

**Comment by nicolaiparlog** [comment]
@smoyer64 I think a well-written blog post would do the trick. If you want to collaborate on one, you know how to reach me. :wink:

**Comment by davidkarlsen** [comment]
Info for others finding the thread - there is a listener for jacoco+sonar: https://deors.wordpress.com/2014/07/04/individual-test-coverage-sonarqube-jacoco/ - it has not been updated for junit5
