### ISSUE TITLE
Decide if/what/where/how to log

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#84]

**Comment by jlink** [comment]
I'd also get rid of the information level logs during a standard build. But nothing I do in `log4j2-test.xml or creating a corresponding `log4j2.xml` in `src/main/resources` seems to have any effect on log levels during the junit5Test task. Any tips?

**Comment by sbrannen** [comment]
> But nothing I do in log4j2-test.xml or creating a corresponding log4j2.xml in src/main/resources seems to have any effect on log levels during the junit5Test task. Any tips?

Yes, I've already fixed that problem.

I'll push the changes today.

**Comment by jlink** [comment]
cheers.

2016-01-04 14:37 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by sbrannen** [comment]
> I'd also get rid of the information level console output during a standard build.

Addressed in e061fa45d89529edff690f329298c6a061482834. The logging output in the build now looks like this:

```
14:55:21.103 [main] INFO  org.junit.gen5.launcher.ServiceLoaderTestEngineRegistry - Discovered TestEngines with IDs [junit4, junit5]

Test run finished after 12463 ms
[       215 tests found     ]
[         0 tests skipped   ]
[       215 tests started   ]
[         0 tests aborted   ]
[       215 tests successful]
[         0 tests failed    ]
```

**Comment by sbrannen** [comment]
Furthermore, logging configuration within an IDE is now documented in `AllFastJUnit5Tests` (see commit d25441446ec9acf73d75a8fabfcfa3a3a5774c8a):

>
> In order for our log4j2 configuration to be used in an IDE, you must set the following system property before running any tests — for example, in Run Configurations in Eclipse.
>
> `-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager`
>

**Comment by jlink** [comment]
`[main] INFO ... Discovered TestEngines with IDs...` is still being output. On purpose?

**Comment by sbrannen** [comment]
yes

**Comment by marcphilipp** [comment]
Put in CONTRIBUTING.MD:

### Logging Guidelines

- Use sparingly
- Do not log in utility classes (junit-commons)
- Levels
  - `SEVERE` (Log4J: `ERROR`): extra information (in addition to an Exception) about errors that will halt execution
  - `WARNING` (Log4J: `WARN`): potential usage errors that should not halt execution
  - `INFO`: stuff the users might want to know but not by default (Example: `ServiceLoaderTestEngineRegistry` logs IDs of discovered engines)
  - `FINE` (Log4J: `DEBUG`)
  - `FINER` (Log4J: `TRACE`)
