### ISSUE TITLE
Switch to Spotless Groovy formatter

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#843]
## Overview

We currently use a custom formatting config for Groovy source files. Now that diffplug/spotless#13 is fixed, we should switch to use GrEclipse formatting for Groovy files.

## Deliverables

- [ ] Change Spotless config to use Groovy extension with GrEclipse formatter settings

**Comment by fvgh** [comment]
If you like can provide you with a proposal (PR) next week. We would need to switch to spotless 3.3.2, since I will need the fix for diffplug/spotless#106.

**Comment by marcphilipp** [comment]
That would be great! 👍

**Comment by fvgh** [comment]
Happy that you are interested in my work.
But I just used is on a very small code base till now.
Thanks for volunteering to be my guinea pig :wink:.
Just kidding. I will have a careful look, but it might be possible that I find some issues, so that we need to postpone this issue if I still need to fix some minor things in my diffplug/spotless#13 implementation.

**Comment by marcphilipp** [comment]
Sure, no worries.

**Comment by fvgh** [comment]
@marcphilipp Sorry Marc, I am not familiar with the JUnit PR cycle. Is there anything your are waiting for regarding #860? I currently waiting for a feed back whether the proposal is as such acceptable before applying the changes agreed upon (like [this finding](https://github.com/junit-team/junit5/pull/860#pullrequestreview-39802658)).

**Comment by marcphilipp** [comment]
@fvgh Sorry for the delay! We were just busy with other things. I've reviewed #860 now.

**Comment by fvgh** [comment]
@marcphilipp I did not want to rush the things, was just not sure whether you guys waited for something I should do. Thanks for the review. There is something I want to check on the [auto paddedCell feature](https://github.com/diffplug/spotless/blob/master/PADDEDCELL.md) applied by Spotless, before I answer your review comments.

**Comment by marcphilipp** [comment]
Sure, no worries.

**Comment by fvgh** [comment]
Last question: Are you (in a separated PR) interested to apply the formatter on the Gradle files as well?

**Comment by marcphilipp** [comment]
Apply the formatter? I thought that was what #860 is doing, isn't it? I'm sure I'm missing something. Please try to clarify. 🙂

**Comment by fvgh** [comment]
Currently it only [selects the groovy files](https://github.com/junit-team/junit5/pull/860/files#diff-c197962302397baf3a4cc36463dce5eaR418).
Question is, whether you want to have a (slightly different) configuration for *.gradle as well.

**Comment by marcphilipp** [comment]
Sorry, I mixed up Gradle and Groovy... 🙈

A formatting check for Gradle files sounds like a good idea! Please open a new issue/PR for that if you have time!

**Comment by fvgh** [comment]
Ok. Will come back to you on #860 next week (no time this weekend). When this issue is solved to everybody's convenience, I'll provide you with another PR. The difference between groovy and gradle is just that the import sorter and license header check needs to be removed.

**Comment by fvgh** [comment]
@marcphilipp I am not so firm with the review process. Do you expect my changes as another commit so that you can see differences, or do you prefer a squashed PR to keep the history clean?

**Comment by marcphilipp** [comment]
Feel free to push additional commits to the existing branch. We can squash it when we merge it if we see fit.
