### ISSUE TITLE
Add Assertions.assertTrue/False() taking an user-defined Predicate instance

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#846]
## Overview

Instead of `assertTrue(StableList.of().isEmpty())` an `assertTrue/assertFalse` that takes a predicate will make things more clear, like:

```
assertTrue(List::isEmpty, StableList.of());
```

The original request can be found [here](https://github.com/forax/pro/commit/eb5f1b7b6df63c75ffa7a14a61d8d4c596b627bc#commitcomment-22058065).

The signature of `assertTrue` is
```
<T> void assertTrue(Predicate<? super T> predicate, T input) {
  assertTrue(predicate.test(input));
}
```

## Deliverables

- [ ] Implement and test `Assertions.assertTrue` and `Assertions.assertFalse` an user-defined Predicate instance

**Comment by nicolaiparlog** [comment]
Just my 2 ct but I don't think this is a particularly good idea. While adding complexity to the assertion it does not even make it easier to read. I know it's an easy addition but that does not mean it should be implemented.

Maybe another example would be better?

**Comment by marcphilipp** [comment]
This is already supported in AssertJ and more readable, too:

```java
assertThat(Collections.emptyList()).matches(Collection::isEmpty);
```

**Comment by marcphilipp** [comment]
**Team Decision:** We don't want to introduce additional complexity to Jupiter's Assertions. Please use AssertJ. 🙂
