### ISSUE TITLE
Update JUnit 5 dependency recommendations in Maven section of the Users Guide

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#848]
- (X) **Bug report.** 

When I submitted https://github.com/junit-team/junit5-samples/pull/16 (Alters POM to minimize test-compile dependencies), I purposely included only the ```junit-jupiter-api``` artifact as a test-scoped dependency and included the other packages that were needed at test-execution time as a dependency of the ```maven-surefire-plugin```.  My intention was to only expose the classes in ```junit-jupiter-api``` to the test writer's test compiler.

In this [comment](https://github.com/junit-team/junit5/issues/801#issuecomment-299856881), @Tibor17 has instructed that this is not the correct configuration and that only the ```junit-platform-surefire-provider``` should be a plugin dependency.  I'll let @Tibor17 comment on why this is important if he chooses.  The incorrect configuration has also been adopted in the Users Guide.

Related to https://github.com/junit-team/junit5-samples/issues/25#issuecomment-300209012

## Deliverables

- [ ] Align Maven examples in the Users Guide to the ```junit5-maven-consumer``` sample project.

**Comment by Tibor17** [comment]
We can check `AbstractSurefireMojo` if really needed. This is to my memory that we pickup such artifact which has Surefire SPI. This artifact is provided in classpath when you run your test. Surefire documented adding provider in plugin's dependency section.

is there any reason to not to use project dependencies?

**Comment by Tibor17** [comment]
Pls follow https://github.com/junit-team/junit5-samples/pull/26.

**Comment by marcphilipp** [comment]
Closing because the current recommendations work fine (see https://github.com/junit-team/junit5-samples/issues/25#issuecomment-307568647 for details).
