### ISSUE TITLE
EnumSource filtering

### ISSUE THREAD

**Issue by danielolszewski** [junit-team/junit5#850]
## Overview

Many times I run into a situation where some test should be repeated only for a subset of enum values. Currently we can filter which values should be used for a test using the `names` attribute, but this solution has one big drawback. Every time someone adds a new value to the enum, the same value must be added to the test in the `names` attribute. If the developer forgets to do so, the test may raise a false positive result and potentially lead to a bug.

If the `@EnumSource` annotation allowed to specify which enum values should be excluded from a test, the newly added values would be covered automatically. It would be nice if the API allowed us to specify whether values in the `names` attribute is the list of values that should be included or excluded from a test. For instance, it might be an additional boolean attribute.

**Comment by sormuras** [comment]
I like to extend the filter options as well. Locally, I'm playing with an `EnumSource.ConstantSelectionMode` that can easily enhanced in the future:
```
enum ConstantSelectionMode {
  INCLUDE_NAMES((constant, names) -> names.contains(constant.name())),
  EXCLUDE_NAMES((constant, names) -> !names.contains(constant.name())),
  MATCHES_ALL((constant, names) -> names.stream().allMatch(regex -> constant.name().matches(regex))),
  MATCHES_ANY((constant, names) -> names.stream().anyMatch(regex -> constant.name().matches(regex)))
  ;
}
```

**Comment by sormuras** [comment]
Usage [demo](https://github.com/junit-team/junit5/pull/852/files#diff-0fa4104a4390c34de08dfe177d56f88c):
```
@ParameterizedTest
@EnumSource(TimeUnit.class)
void testWithEnumSource(TimeUnit timeUnit) {
	// "all of" TimeUnit constants
}

@ParameterizedTest
@EnumSource(value = TimeUnit.class, names = { "DAYS", "HOURS" })
void testWithEnumSourceInclude(TimeUnit timeUnit) {
	// default mode = INCLUDE_NAMES
	// TimeUnit.DAYS
	// TimeUnit.HOURS
}

@ParameterizedTest
@EnumSource(value = TimeUnit.class, mode = EXCLUDE_NAMES, names = { "DAYS", "HOURS" })
void testWithEnumSourceExclude(TimeUnit timeUnit) {
	// TimeUnit.SECONDS
	// TimeUnit.MINUTES
	// TimeUnit.NANOSECONDS
	// TimeUnit.MICROSECONDS
	// TimeUnit.MILLISECONDS
}

@ParameterizedTest
@EnumSource(value = TimeUnit.class, mode = MATCHES_ALL, names = "[M|N].+SECONDS")
void testWithEnumSourceRegex(TimeUnit timeUnit) {
	// TimeUnit.NANOSECONDS
	// TimeUnit.MICROSECONDS
	// TimeUnit.MILLISECONDS
}
```

**Comment by danielolszewski** [comment]
I really like this proposal. Very clean and readable.

**Comment by sormuras** [comment]
Addressed via PR #852 -- just merged into master with https://github.com/junit-team/junit5/commit/dea8473ffa912510c51cd2efc24f753206670b80

**Comment by sbrannen** [comment]
Reopening due to discovered issues.

**Comment by sbrannen** [comment]
The "no duplicate constant names" precondition does not actually test for duplicates.

For example, changing the existing test for this precondition to the following still causes the test to _pass_.

```java
	@Test
	void duplicateConstantNameIsDetected() {
		Exception exception = assertThrows(PreconditionViolationException.class,
			() -> provideArguments(EnumWithTwoConstants.class, "x", "x", "x"));
		assertThat(exception).hasMessageContaining("Duplicate enum constant name(s) found");
	}
```

**Comment by sbrannen** [comment]
Never mind: I thought it was supposed to detect duplicate _valid_ enum constants names, but it apparently was only ever intended to check that the user didn't supply duplicates.

Since the _validation_ of the supplied constant names is applied later, I think we have all bases covered here.

Closing this issue again.
