### ISSUE TITLE
Set JPMS module names in all published artifacts

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#866]
## Overview

The artifacts listed here https://github.com/junit-team/junit5#dependency-metadata should define their JPMS module names.

> [...] the name of a module to be specified in the MANIFEST.MF file of a JAR file. If a JAR file with such a manifest entry is not a modular JAR (i.e., it has no module-info.class file), but is used as an automatic module, then the name of the automatic module is that specified in the manifest rather than that derived from the name of the JAR file itself. This would allow the maintainer of an existing library to specify a preferred module name simply by updating the library’s manifest. [...]
http://openjdk.java.net/projects/jigsaw/spec/issues/#ModuleNameInManifest

See http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-May/000687.html for details.

## Naming proposal

Follow reverse DNS naming convention described here http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html

- `junit-platform-commons` ➡️ `org.junit.platform.`~~console~~ `commons`
- `junit-jupiter-api` ➡️ `org.junit.jupiter.api`
- `junit-vintage-engine` ➡️ `org.junit.vintage.engine`

**Comment by sbrannen** [comment]
When you say...
> - `junit-platform-commons` ➡️ `org.junit.platform.console`

I'm assuming you mean:

- `junit-platform-commons` ➡️ `org.junit.platform.commons`

😉

**Comment by sormuras** [comment]
Too much copy'n paste...

**Comment by sormuras** [comment]
3 module names do not match their super [package names](https://twitter.com/jodastephen/status/870888939091103744).

## junit-jupiter-migration-support

Automatic-Module-Name: `org.junit.jupiter.migration.support`
Contains classes in packages that start with: `org/junit/jupiter/migrationsupport/**/*`

- [ ] rename Automatic-Module-Name to `org.junit.jupiter.migrationsupport` without the dot before `support` 

## junit-platform-console

Automatic-Module-Name: `org.junit.platform.console`
Contains classes in packages that start with:  `org/junit/platform/joptsimple/**/*`

- [ ] move shaded `joptsimple` to `org.junit.platform.console.joptsimple` 

## junit-platform-console-standalone

Automatic-Module-Name: `org.junit.platform.console.standalone`
Contains classes in various packages - **none** in a packaged named `org.junit.platform.console.standalone`. This artifact is just an "all-in-one" or "uber" JAR that is not meant to be on the module-path.

- [ ] leave as-is
- [ ] remove Automatic-Module-Name from JAR's manifest

**Comment by marcphilipp** [comment]
Looks good to me! 👍

**Comment by jodastephen** [comment]
"all-in-one" or "uber" jar files should not have the MANIFEST.MF entry, as they are unsuitable for the module path.

Shaded jars do need to be under the main super-package. It may be worth using `org.junit.platform.console.shaded.joptsimple` to emphasise what has happened.

**Comment by sormuras** [comment]
Thanks for the review!

- Rename sub-project directory from `junit-jupiter-migration-support` to `junit-jupiter-migrationsupport` or treat it as a special case in the integration test?
- Move shaded joptsimpel to `org.junit.platform.console.shaded.joptsimple`
- Remove `AutomaticModuleName` from standalone JAR an skip it when testing the module names.

**Comment by sormuras** [comment]
All three items went into https://github.com/junit-team/junit5/compare/issues/866_package_names?expand=1

**Comment by sormuras** [comment]
Addressed via #875
