### ISSUE TITLE
Transaction roll back is not working in test case in @Nested class of JUnit5

### ISSUE THREAD

**Issue by wicksome** [junit-team/junit5#868]
when use spring-boot, JUnit5 and Mybatis, Rollback of test case in nested class is not working.

```java
@SpringJUnitJupiterConfig(classes = {RepositoryTestConfig.class})
@MapperScan
@Rollback
@Transactional
public class TestClass {
	@Autowired
	private TestMapper testMapper;
	
	@BeforeEach
	void init() {
		User user = new User();
		testMapper.insert(user);	
	}
	
	@Test
	public void test1() {
		// (1) success rollback
	}
	
	@Nested
	class WhenExistData {
		@Test
		public void test2() {
			// (2) rollback not working
		}	
	}
}
```

(1) is working rollback. And following log is output.

	2017-05-26 22:21:29 [INFO ](TransactionContext.java:136) Rolled back transaction for test context ...
	
But, (2) is not working. I want to be able to roll back into `@Nested`.
I have solved it in the following way, is this normal?

```java
@SpringJUnitJupiterConfig(classes = {RepositoryTestConfig.class})
@MapperScan
@Rollback
@Transactional
public class TestClass {
    @Autowired
    private TestMapper testMapper;

    @BeforeEach
    void init() {
        User user = new User();
        testMapper.insert(user);    
    }

    @Nested
    @SpringJUnitJupiterConfig(classes = {RepositoryTestConfig.class})
    @MapperScan
    @Rollback
    @Transactional
    class WhenExistData {
        @Test
        public void test2() {
        }   
    }
}
```

**Comment by sbrannen** [comment]
For future reference, please do not report issues about Spring in the JUnit repository.

The best place to report issues about Spring is Spring's own JIRA issue tracker. ;-)

**Comment by sbrannen** [comment]
Closing this issue since it is already addressed in Spring's issue tracker as 
[SPR-15366](https://jira.spring.io/browse/SPR-15366).

**Comment by nicolaiparlog** [comment]
> For future reference, please do not report issues about Spring in the JUnit repository.

That was my fault. I [commented](https://stackoverflow.com/questions/44203244/transaction-roll-back-is-not-working-in-test-case-in-nested-class-of-junit5#comment75427304_44204171) on the StackOverflow question and recommended to open an issue here. Sorry for that.
