### ISSUE TITLE
Custom gradle task for run jUnit 5 tests

### ISSUE THREAD

**Issue by ksuzu** [junit-team/junit5#874]
Hello!
I need to have a custom task in a gradle script for running integration tests of a project. 
Can you suggest how to create another gradle task (with different name, not "junitPlatform") with another filtration settings? I mean that I want to have two tasks: 1) one for fast tests and 2) for integration_test.
I think it will be like a:
task IntegrationTest {
    filters {
        engines {
            include 'junit-jupiter'
        }
        tags {
            include 'integration_test'
        }
    }
}

**Comment by marcphilipp** [comment]
Unfortunately, that's currently not very easy to do. The medium-term plan is to get Gradle core support so it will be able to configure an additional test task.

Right now, you can define your own task for the integration tests and use `ConsoleLauncher` directly as described in https://github.com/junit-team/junit5/issues/700#issuecomment-283374073.

I'm closing this issue for now but feel free to comment on it if you have additional questions.
