### ISSUE TITLE
Document that @BeforeAll & @AfterAll are unsupported in @Nested test classes

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#88]
## Status Quo

Since support for configuring the test instance lifecycle was dropped after the prototype, `@BeforeAll` and `@AfterAll` methods are now required to be `static`. Consequently such methods can no longer be used in `@Nested` test classes. Any attempt to do so will result in a compilation error similar to the following.

> The method myBeforeAllMethod cannot be declared static; static methods can only be declared in a static or top level type.

See the nested test classes in `com.example.HierarchyTestCase` for concrete examples.

## Deliverables

- [x] Decide how to handle `@BeforeAll` and `@AfterAll` methods in nested test classes.
  - The team decided that this is simply not supported since the Java language doesn't support it.
- [x] Document that `@BeforeAll` and `@AfterAll` are unsupported in nested test classes.
- [x] Delete `com.example.HierarchyTestCase`.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda, this is a _gotcha_ that we will need to discuss amongst the group.

**Comment by jlink** [comment]
I see several options. No need for desperation ;)

The simplest thing might just be to disallow @Before/AfterAll in nested tests since nested tests IMO are a means to group tests by their domain context not by their technical context. If someone really really needs a before/afterAll for technical reasons, they can easily use an extension.

Von meinem iPad gesendet

**Comment by sbrannen** [comment]
Resolve in `master`. See associated commits for details.

**Comment by jlink** [comment]
Missing Tests for:
- [ ] fail(Supplier<String> messageSupplier)
- [ ] assertTrue(BooleanSupplier booleanSupplier, String message)
- [ ] assertFalse() in all variants
- [ ] assertNull(Object actual, String message)
- [ ] assertEquals(Object expected, Object actual, Supplier<String> messageSupplier) failing
- [ ] assertNotEquals(Object unexpected, Object actual, String message)
- [ ] assertSame(Object expected, Object actual, Supplier<String> messageSupplier) failing
- [ ] assertNotSame(Object unexpected, Object actual, String message)

**Comment by marcphilipp** [comment]
@jlink I believe this list belongs to #76, doesn't it?

**Comment by mkobit** [comment]
After reading through this and trying to look at the other issues, does it still make sense that `@BeforeAll` and `@AfterAll` _have_ to be `static`?

**Comment by sbrannen** [comment]
Without "test instance per test class" semantics it is required that `@BeforeAll` and `@AfterAll` methods be `static`. See the description of #48 for details.

However, once #48 is resolved, the `static` restriction will possibly be removed for scenarios in which that makes sense.

**Comment by silkentrance** [comment]
@sbrannen a valid position against ``@BeforeAll`` and ``@AfterAll`` being static would be the Spring Framework or any such framework that provides for dependency injection of either configuration or components or services used during the tests.

And, considering that during ``@BeforeAll`` one would establish a required set of data (aka fixtures) in for example a database, one cannot accomplish that when using static methods unless one would set up a spring ioc before hand and use that only for the purpose of the ``@BeforeAll`` and ``@AfterAll``, aka the test set up and tear down methods.

I know there exists the SpringExtension, however, this only works on the test instance, and both ``@BeforeAll`` and ``@AfterAll`` are not supported here.

**Comment by silkentrance** [comment]
@sbrannen and i do not see why we would need the Scenario abstraction as proposed by #48. perhaps we might be able to accomplish this right now using for example a suitable extension class? Of course, and basically that might be the reason for ``@Before/AfterAll`` are still static is the fact that on instance level one will override existing behaviour inherited from a base test class, e.g.

```
class BaseTest {
  @BeforeAll
  public void setUp() { ... }
}

public ConcreteTest extends BaseTest {
   @BeforeAll
   public void setUp() { ... }
}
```

So here, the concrete test's setUp method will override the base test class' method.
Why not use standard java idioms here? Allow the derived class to either call upon super or simply override its behaviour.

**Comment by sbrannen** [comment]
Hi @silkentrance,

For starters, *this issue* was only pertinent to the **Alpha** release of JUnit 5 and was closed on Jan 20, 2016 (over two years ago).

More importantly, this issue was superseded by #419 which was closed on Jun 30, 2017.

Thus, it has been possible to have non-static `@BeforeAll` and `@AfterAll` methods for quite some time now.

Please inform yourself of the status quo in JUnit Jupiter 5.0.x, and if you have further concerns please open a *new* issue to address them.

I will now lock this conversation since it pertains to an outdated version of the framework.
