### ISSUE TITLE
Global activation for chosen extensions

### ISSUE THREAD

**Issue by ctapobep** [junit-team/junit5#885]
While JUnit5 provides an ability to look use SPI for extension activation, right now it activates all of the extensions. 

In reality extensions could be very different - you wouldn't want to activate SpringExtension for all your tests, but others (like Reporting) would be convenient to turn on globally instead of marking literally each test class with `@ExtendWith`.

So would be great to pass some variables (like extension class names) to surefire to be able to activate that extension for all tests at once.

**Comment by nicolaiparlog** [comment]
> you wouldn't want to activate SpringExtension for all your tests

I would say that's an argument against the Spring extensions using the SPI mechanism. Only truly cross-cutting concerns that (ideally) do not change the test outcome should be addressed via SPI (like reporting or benchmarking).

This was meant as an argument against such an explicit activation mechanism but it might actually end up supporting it. Imagine a useful or even required test dependency registers some stupid services... as it stands there is no way to keep it from registering those, right?
