### ISSUE TITLE
Request for a warning in release notes: Unable to start tests in IntelliJ with current SNAPSHOT version using launcher bundled in the IDE

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#889]
my build.gradle looks like:
```
ext.junitJupiterVersion  = 'latest.integration'

dependencies {
    testRuntime("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
}
```
This way launcher is added by IDE and the exception appears:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.junit.platform.commons.util.ReflectionUtils.getDefaultClassLoader()Ljava/lang/ClassLoader;
	at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.loadTestEngines(ServiceLoaderTestEngineRegistry.java:30)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.createListeners(JUnit5IdeaTestRunner.java:39)
```

I guess, after releasing M5, many users would face this issue as well. Though they may already know how to trick the IDE and use the launcher delivered by the same version as their api, please add corresponding warnings to the user guide and in release notes. We would have to repeat this anyway, but at least we would have a good place where to point.

Thanks in advance!

**Comment by marcphilipp** [comment]
Will do, thanks @akozlova!

**Comment by akozlova** [comment]
Thanks!

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I've added a [warning](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes-5.0.0-m5) to the Release Notes and a [section](http://junit.org/junit5/docs/snapshot/user-guide/#running-tests-ide-intellij-idea) to the User Guide.

@akozlova Would be great if you could review those. 🙂

**Comment by akozlova** [comment]
Yep, I've read that yesterday. Looks good to me. I am happy that I have a place where to point users. Many thanks!
