### ISSUE TITLE
How to separate integration tests from unit tests using testSets plugin

### ISSUE THREAD

**Issue by sta-szek** [junit-team/junit5#892]
I have problem with test separation.
We use test sets plugin to separate integration tests from unit (we keep them in different directories):

```
buildscript {
    ext {
        springBootVersion = '1.5.4.RELEASE'
    }
    repositories {
        maven {
            url 'https://mvn.cin.pl/artifactory/plugins-release'
        }
    }
    dependencies {
        classpath "org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:1.0.2"
    }
}
apply plugin: 'org.unbroken-dome.test-sets'
testSets {
    integrationTest { dirName = 'it' }
}
```

As far as we were using Junit4, there was a simple step to set up new `test module`:
```
integrationTest {
    filter {
        includeTestsMatching "*E2E"
        includeTestsMatching "*IT"
    }
    jacoco {
        destinationFile = file("build/jacoco/integrationTest.exec")
        classDumpFile = file("build/jacoco/integrationTestDumps")
    }
}
```

Is there any way to acheive the same with Junit5 and testSets plugin?

**Comment by marcphilipp** [comment]
Since the `test` task currently does not support the new JUnit platform the testsets plugin will not work. For the test task to work, we need core Gradle support. Feel free to follow gradle/gradle#1037 for details.

**Comment by sta-szek** [comment]
@marcphilipp thanks.

**Comment by marcphilipp** [comment]
Gradle now provides [native support](https://docs.gradle.org/4.6/release-notes.html#junit-5-support) for running tests on the JUnit Platform and the testsets plugin should work as usual. We've decided to deprecate our custom plugin (see #1317 for details) and not add any new features to it. Thus, I'm closing this issue.
