### ISSUE TITLE
Question about gradle integration

### ISSUE THREAD

**Issue by born2snipe** [junit-team/junit5#895]
Why was it decided to make a separate gradle plugin instead of integrating with gradle's [`TestFramework`](https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java#L1103)?

**Comment by sormuras** [comment]
1. Historical reasons, I guess.
2.  `org.gradle.api.internal.tasks.testing.TestFramework` looks like **internal** API
3.  Results emerging from [Design Specification for JUnit 5 Support](https://github.com/gradle/gradle/issues/1037) will use it, I guess.
