### ISSUE TITLE
Ignore disabled annotations when they appear on element from DiscoverySelector

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#898]
Given the code

```java
import org.junit.jupiter.api.*;

@Disabled
class DisabledTest {
    @Disabled
    @Test
    void testIgnorance() throws Exception {
        Assertions.assertEquals("1", "1", "strings doesn't match");
        System.out.println("Assertion performed");
    }
    @Test
    void shouldBeExecuted() throws Exception {
        Assertions.assertTrue(true, "True is always true");
    }
}
```

When user runs `testIgnorance`, IDEA disables the `DisabledCondition` and allows to run the test. Works as it was in JUnit 4. But when user runs the whole class, the same idea not really works: the disabled method also runs. I don't see how to influence the discovery mechanism to ignore `@Disabled` annotations differently. Please correct me if I am wrong.

On the other hand, from the point of JUnit 5 itself: storing information of the entry point (discovery selector root, when exactly one) and then using this information to ignore top level annotations looks not that strange (though it's strange of cause). What do you think?

**Comment by marcphilipp** [comment]
Do I understand you correctly that you expect that `@Disabled` in merely ignored for the executed selector, not everywhere?

**Comment by sbrannen** [comment]
> But when user runs the whole class, the same idea not really works: the disabled method also runs. I don't see how to influence the discovery mechanism to ignore @Disabled annotations differently. Please correct me if I am wrong.

That's correct. If you deactivate a condition (such as `org.junit.jupiter.engine.extension.DisabledCondition`), then that condition will be deactivated completely (i.e., for all occurrences).

In other words, there is currently no way to deactivate a condition for a single location within the code.

**Comment by sbrannen** [comment]
> On the other hand, from the point of JUnit 5 itself: storing information of the entry point (discovery selector root, when exactly one) and then using this information to ignore top level annotations looks not that strange (though it's strange of cause). What do you think?

I'm not sure what I think... because I didn't totally follow you. 😉 

Would you mind expounding on your idea a bit more?

**Comment by akozlova** [comment]
In IDEA with junit 4 (disabled -> ignore): when you run a class, only 'shouldBeExecuted' method would be executed and the second method would be ignored. We would like to have the same behaviour with junit 5. I don't think that it's possible now.
My idea to implement it inside junit itself was to mark 'root' somehow and don't apply DisabledCondition to it

**Comment by marcphilipp** [comment]
We could add a second system property, e.g. `junit.conditions.deactivate.location`, that let's you specify the location as a unique ID where the conditions specified in `junit.conditions.deactivate` should be deactivated.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment]
I had the exact same idea, @marcphilipp. 😉 

Though I was thinking about calling it `unique-id` instead of `location`.

**Comment by sbrannen** [comment]
This proposal obviously requires that the Unique ID be known up front.

**Comment by akozlova** [comment]
I'd prefer to specify source only as I won't have uniqueId before I start the discovery process and at that time it would be probably too late to specify any properties, or?

**Comment by marcphilipp** [comment]
Well, you could call `discover` first, find the identifier with the correct `TestSource` and get its unique ID. Then you can set the system property and launch the tests.

Or, we could think about a different format to specify the location, e.g. `class:com.acme.Foo` or `method:com.acme.Foo#test(String)`.

**Comment by akozlova** [comment]
I can provide TestSource directly or do it under the hood, I don't think that different format is required.
