### ISSUE TITLE
Random Java Object Generator

### ISSUE THREAD

**Issue by sajjusajuu** [junit-team/junit5#900]
## Random java Object Generator

- ( ) **Feature request.** In most cases while writing Junits we supply sample input to the methods to test. And this sample input is mostly some domain object or a list of domain objects. I feel it would be helpful, if there is a feature/class which generates the domain objects from its classes, after taking into consideration, the data types of the fields in it.

Need your inputs on this on. Thanks!

**Comment by sormuras** [comment]
Perhaps https://github.com/pholser/junit-quickcheck already does what want?

**Comment by marcphilipp** [comment]
Populating objects with random values is outside the scope of JUnit and should be done in an extension.

**Comment by jlink** [comment]
you might also consider using http://jqwik.net which provided a Junit5 test engine for the exact purpose.
