### ISSUE TITLE
Merge [Container|Test]ExtensionContext into ExtensionContext

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#901]
## Overview

`ConatinerExtensionContext` is already just a _marker interface_, and with the changes being introduced in #419 the `TestExtensionContext` will soon contain a single `Optional<Throwable> getTestException()` method.

With these points in mind, now may be an opportune time to take the plunge and completely remove both the `ConatinerExtensionContext` and `TestExtensionContext` APIs and allow extension authors to rely solely on the `ExtensionContext` API.

## Related Issues

- #419 
- #625 
- #899 

## Deliverables

- [ ] Move `getTestException()` from `TestExtensionContext` to `ExtensionContext`.
  - [ ] Potentially rename `getTestException()` to `getExecutionException()` in preparation for #899.
- [ ] Remove the `ContainerExtensionContext` API.
- [ ] Remove the `TestExtensionContext` API.
- [ ] Merge `ContainerExecutionCondition` and `TestExecutionCondition` into a single, general purpose `ExecutionCondition` whose method accepts a sole `ExtensionContext` argument.

**Comment by sbrannen** [comment]
@junit-team/junit-lambda This issue is _open for team discussion_ within the 5.0 M5 time frame.

**Comment by sbrannen** [comment]
Thinking out loud...

One thing I find controversial about the proposal is the merging of `ContainerExecutionCondition` and `TestExecutionCondition`.

I know that the same contextual information will available to extension authors; however, extension authors may wish to implement entirely different logic for the container level and the test level.

Perhaps it's a non-issue, but it's definitely something to keep in mind.

This of course ties into any decision made in conjunction with #625.

**Comment by sbrannen** [comment]
Added a sub-deliverable regarding `getExecutionException()` and #899.

**Comment by marcphilipp** [comment]
_in progress_
