### ISSUE TITLE
Gradle JunitPlatform sub extensions are not Gradle Kotlin DSL friendly

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-team/junit5#902]
## Feature request

The Junit5 Gradle plugin configuration does not lend itself well to being configured with the new [Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl).

I would like to be able to use the following syntax in my Gradle Kotlin DSL build file:

```kotlin
junitPlatform {
    filters {
        includeClassNamePatterns(".*Test", ".*Tests", ".*Spec")
    }
}
```

The problem is rooted in the fundamental design decision to dynamically add properties to the `JunitPlatformExtention` at runtime with groovy. That means statically typed languages have to jump through hoops to access them.

[Lines that cause this problem](https://github.com/junit-team/junit5/blob/6ded3d033b33d313767550dbd7fc0611f6a485b4/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy#L30-L35)

There is a workaround for this problem in kotlin but it isn't the prettiest.

```kotlin
fun org.junit.platform.gradle.plugin.JUnitPlatformExtension.filters(configure: org.junit.platform.gradle.plugin.FiltersExtension.() -> Unit = {}) =
    with(getProperty("filters") as org.junit.platform.gradle.plugin.FiltersExtension) { configure() }
```

Placing the above code snippet somewhere in my build file allows me to use the syntax I want but it would be better practice if `JUnitPlatformExtension` had member functions that are explicitly declared.

For example:
```groovy
void selectors(org.gradle.api.Action<SelectorsExtension> closure)

void filters(org.gradle.api.Action<FiltersExtension> closure)

// ect...
```

## Deliverables

- [ ] Add `selectors` method to `JUnitPlatformExtension`
- [ ] Add `filters` method to `JUnitPlatformExtension`
- [ ] Add `packages` method to `FiltersExtension `
- [ ] Add `tags` method to `FiltersExtension `
- [ ] Add `engines` method to `FiltersExtension `

**Comment by sormuras** [comment]
Thanks for creating the issue including a work-around, @JLLeitschuh -- do you want to provide a PR with the member functions you mentioned?

Hoping that all those shortcomings of the current implementation will be gone for good, when https://github.com/gradle/gradle/issues/1037 is finally addressed.

**Comment by marcphilipp** [comment]
`packages`, `tags`, and `engines` should be part of `FiltersExtension`, though, right?

**Comment by JLLeitschuh** [comment]
@marcphilipp You are correct.
