### ISSUE TITLE
ParameterResolutionException with TestInfo and Parameterized Tests

### ISSUE THREAD

**Issue by littleclay** [junit-team/junit5#935]
When trying to get the TestInfo as an argument to a parameterized test method an error is thrown. I'm attaching the pom and test java file in the simple testing project I'm seeing this with.

[Archive.zip](https://github.com/junit-team/junit5/files/1136396/Archive.zip)

The error being thrown when I run `mvn clean test` is:
```
org.junit.jupiter.api.extension.ParameterResolutionException: Discovered multiple competing
ParameterResolvers for parameter [org.junit.jupiter.api.TestInfo arg0] in executable [void
com.foo.FooTest.testParameterizedFoo(org.junit.jupiter.api.TestInfo,java.lang.String)]:
org.junit.jupiter.engine.extension.TestInfoParameterResolver,
org.junit.jupiter.params.ParameterizedTestParameterResolver
```

**Comment by marcphilipp** [comment]
As stated in the [User Guide](http://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-lifecycle-interop):

> You may use `ParameterResolver` extensions with `@ParameterizedTest` methods. However, method parameters that are resolved by argument sources need to come first in the argument list. Since a test class may contain regular tests as well as parameterized tests with different parameter lists, values from argument sources are not resolved for lifecycle methods (e.g. `@BeforeEach`) and test class constructors.

Thus, if you swap your parameters, it works:

```java
@ParameterizedTest
@ValueSource(strings = {"hello", "world"})
void testParameterizedFoo(String argument, TestInfo info) {
    System.out.println(info.getDisplayName());
    System.out.println(argument);
}
```

**Comment by littleclay** [comment]
Doh, somehow missed that. Sorry and thanks!

**Comment by marcphilipp** [comment]
No worries!
