### ISSUE TITLE
Ensure that tags are trimmed

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#942]
## Overview

As purported in #927, it would appear that we do not consistently trim user-supplied tags.

## Deliverables

- [x] Investigate the validity above the above claim.
  - See _Analysis_ and _Correction_ comments below.
- [x] Ensure that individual tags supplied to a `TagFilter` are trimmed.
- [x] Ensure that individual tags supplied via `@Tag` are trimmed.

**Comment by jbduncan** [comment]
Here's food for thought: _which_ whitespaces do we want to trim? Just spaces, tabs and all sorts of newlines? Or do we look into other sorts of separator characters supported by Unicode?

**Comment by jbduncan** [comment]
There used to be a good-looking document from the Guava guys linked from their [`CharMatcher.whitespace()` javadoc](http://google.github.io/guava/releases/22.0/api/docs/com/google/common/base/CharMatcher.html#whitespace--) that covered different definitions of "whitespace", [but it appears to be dead now](https://spreadsheets.google.com/pub?key=pd8dAQyHbdewRsnE5x5GzKQ).

**Comment by sbrannen** [comment]
We just mean the `trim()` method provided in `java.lang.String`: nothing more, nothing less.

**Comment by jbduncan** [comment]
Okey dokey!

**Comment by jbduncan** [comment]
Is there any particular reason that we use `String.trim()` over any other string-trimming strategy?

**Comment by sbrannen** [comment]
It's built-in, simple, and meets our needs.

**Comment by jbduncan** [comment]
Cool, that's completely fair. Thank you very much for answering my questions!

**Comment by sbrannen** [comment]
**Analysis**:


Any tags supplied to `org.junit.platform.launcher.TagFilter.includeTags(List<String>)` or `org.junit.platform.launcher.TagFilter.excludeTags(List<String>)` are already trimmed via `org.junit.platform.launcher.TagFilter.trimmedTagsOf(TestDescriptor)`. This includes user-supplied tags passed in the console launcher, Maven Surefire provider, and the Gradle plugin.


Neither `org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.getTags(AnnotatedElement)` nor `org.junit.platform.engine.TestTag.create(String)` currently performs any trimming.

**Comment by sbrannen** [comment]
**Correction:**

`TagFilter.includeTags()` and `TagFilter.excludeTags()` currently trim tags stored in a `TestDescriptor` but do **not** trim the user-supplied tags.

**Comment by sbrannen** [comment]
Addressed in `master` in commit 172cef7dfde19546e6a8be6e2785f6ddfa68db0f.
