### ISSUE TITLE
Consider using static analysis and formal verification tools

### ISSUE THREAD

**Issue by jbduncan** [junit-team/junit5#955]
## Overview

Currently, AFAICT, no static analysis or formal verification tools are being used to catch bugs in the JUnit 5 code base. IMO it would be a sensible thing to do to start using a combination of various tools now, so that when we reach GA and proceed beyond GA, we are less likely to be inundated by preventable bug reports and/or suffer from potential security issues.

I'd personally suggest a combination of the following tools, but I'm more than happy to discuss the merits of the tools listed and to discuss other tools which aren't listed or that I may have not thought of:
- [error-prone](http://errorprone.info/)
- [SpotBugs](https://spotbugs.github.io/) or FindBugs
- SpotBugs/FindBugs plugins:
    - [fb-contrib](http://fb-contrib.sourceforge.net/)
    - [find-sec-bugs](http://find-sec-bugs.github.io/)
- PMD
- [Checker Framework](https://checkerframework.org/) (specifically for [nullness formal verification](https://checkerframework.org/manual/#nullness-checker))

## Deliverables

- [ ] A number of agreed-upon static analysis and/or formal verification tools are adopted.

**Comment by sormuras** [comment]
Would you mind filing a PR with the tool(s) of your choice?

**Comment by alixwar** [comment]
SonarQube exists in a cloud version, free for use by Open Source projects: https://about.sonarcloud.io/

SonarQube includes support for PMD, FindBugs and more

**Comment by jbduncan** [comment]
@alixwar We could indeed use SonarQube in the future, but I'd feel leery about us primarily depending on it considering that Gradle already comes with first- and third-party support for SpotBugs (FindBugs' current successor), PMD, and other great tools like error-prone.

**Comment by jbduncan** [comment]
...and also considering that SonarQube's cloud version is yet another thing which we don't have a lot of control over.

**Comment by alixwar** [comment]
@jbduncan Maybe one solution does not exclude the other? My thinking is that bootstrapping SonarQube is probably very quick and easy (based on my experience setting it up locally)

**Comment by jbduncan** [comment]
You make a good point. I'm most likely dismissing SonarQube out of fear too quickly. :)

I personally have no experience with SonarQube, so it's not something I could setup unless I get a lot of free time and develop the inclination to work on it in the future, so I wouldn't mind at all if you wanted to have a stab at it yourself at some point. :)

**Comment by alixwar** [comment]
> I personally have no experience with SonarQube, so it's not something I could setup unless I get a lot of free time and develop the inclination to work on it in the future, so I wouldn't mind at all if you wanted to have a stab at it yourself at some point. :)

Definitely. I can wire it up to a local installation and post some screenshots :)

**Comment by alixwar** [comment]
I have set it up locally. A few comments:
- I configured it the "Gradle way" which actually means changing the build.gradle and adding the Gradle SonarQube plugin. This is not necessary, although it is the recommended way. The alternative is to use a separate properties file and analyze the project using a command line tool (SonarQube Scanner). That way there is no "pollution" to the code base
- I don't have a Clover license locally so I could not report any coverage data. I have configured SonarQube to report from Clover but I cannot test it.
- I enabled all available rules which might not be what is configured in the cloud version

![dashboard](https://user-images.githubusercontent.com/5415786/29016065-193f9d7c-7b51-11e7-874b-b61bfe031d58.jpg)
![example-issue](https://user-images.githubusercontent.com/5415786/29016068-1bedfbb8-7b51-11e7-9420-f8f31f0642fe.jpg)
![issues](https://user-images.githubusercontent.com/5415786/29016072-1ffd3462-7b51-11e7-90c5-4eb4408a1a47.jpg)

**Comment by alixwar** [comment]
New screenshots with all rules applied:

![dashboard-2](https://user-images.githubusercontent.com/5415786/29016578-3d40474c-7b53-11e7-8b4a-41cec872c26f.jpg)
![issues-2](https://user-images.githubusercontent.com/5415786/29016582-415bd864-7b53-11e7-921d-6209fb632490.jpg)
![example-issue-2](https://user-images.githubusercontent.com/5415786/29016585-4369d44e-7b53-11e7-8304-f4c1fd938890.jpg)

**Comment by alixwar** [comment]
Some screenshots from IntelliJ:

![intellij-config](https://user-images.githubusercontent.com/5415786/29016824-5afa6b90-7b54-11e7-9421-685c634874cf.jpg)
![intellij-issue-in-code](https://user-images.githubusercontent.com/5415786/29016835-5fdc1f28-7b54-11e7-93c0-9348ea17e1c8.jpg)

**Comment by alixwar** [comment]
Here are the changes: https://github.com/junit-team/junit5/pull/1008

**Comment by alixwar** [comment]
@jbduncan  @sormuras  Anything else you want to know about SonarQube and its capabilities?

**Comment by sormuras** [comment]
Thanks for all your work @alixwar and @jbduncan in this section!

Given the amount of time left for RC3 (and higher) and especially for GA, static code analysis might not find it's way into this project's automated build process in the near future. As far as I can see from your manually executed runs and screenshots, there's no show-stopper found in the JUnit 5 code base that would prevent a release. Do you agree?

**Comment by alixwar** [comment]
There are some (9) violations concerning optionals being retrieved without a "Optional#isPresent()" check. 
Example:

{code}RepeatedTest repeatedTest = AnnotationUtils.findAnnotation(testMethod, RepeatedTest.class).get();{code}

I'm not familiar with the code so I don't know whether this is a show stopper.

**Comment by sormuras** [comment]
IIRC, those un-guarded `Optional.get()` calls are all located in our test cases. Here, a failing `.get()` would result in a failing test. Which is okay for me.

**Comment by alixwar** [comment]
Then I'm not aware, at least, of a show stopping issue. But it is a good thing to have static code analysis set up ASAP to avoid building up debt

**Comment by jbduncan** [comment]
@alixwar I actually do have a question regarding SonarQube, thanks for asking.

In one of your IntelliJ screenshots above, it shows "violations" like "move left curly brace one line ahead" and "convert tabs to whitespaces". Although I personally agree with whitespaces, the JUnit team decided on tabs a long time ago, and they also decided on placing left curly braces as they currently are, so is there a way of telling SonarQube to not report cases like this?

**Comment by jbduncan** [comment]
@sormuras It's a pleasure! :)

**Comment by alixwar** [comment]
@jbduncan 

For your first question, someone has already answered it in StackOverflow: https://stackoverflow.com/questions/23908058/can-i-edit-some-rules-in-sonarqube

The first step is to identify the rule keys of the rules that you want to change. In this case (see screenshot below):
- squid:LeftCurlyBraceEndLineCheck
- squid:S00105

It appears that none of the two rules are configurable so you need to disable them if you don't like them. There are a some rules in SonarQube that conflict with each other (in the case of code conventions). As part of the normal setup procedure you first define a Quality Profile (rule container) and fine tune it according to your needs, which means enabling/disabling rules.

Screenshots (where to find the rule id) + check details of a rule (some are configurable, this one isn't):

![identify-rule](https://user-images.githubusercontent.com/5415786/29169156-dbaf63aa-7dd2-11e7-8012-b63a1a3ef0d6.jpg)
![check-if-rule-configurable](https://user-images.githubusercontent.com/5415786/29169163-e218d622-7dd2-11e7-9f3d-2ac51cb9d8de.jpg)

**Comment by jbduncan** [comment]
@alixwar Great, thanks for your comprehensive response.

Am I right to think that thus SonarQube comes with checks or rules that aren't in FindBugs, PMD and the other tools that SonarQube bundles? If yes, then I'd be even more convinced that it's a tool worth using.

**Comment by alixwar** [comment]
@jbduncan You're welcome. 

Yes. The rules with the rule key prefix "squid" are rules that come from SonarQubes own Java rule set. Some of them will be very similar to rules coming from PMD, FindBugs etc. In this case their strategy is to deprecate the ones coming from the external plugin (https://blog.sonarsource.com/already-158-checkstyle-and-pmd-rules-deprecated-by-sonarqube-java-rules/). 

Although posted by the creators themselves (so biased) there is some evidence that their own rule set can help detect issues where other static tools fail: https://blog.sonarsource.com/sonarqube-enters-the-security-realm-and-makes-a-good-first-showing/

**Comment by jbduncan** [comment]
@alixwar Very cool, thanks for showing me those blogs!

Their mention of custom rules for security issues looks rather promising to me, so I'm indeed more convinced of SonarQube's usefulness.

Perhaps it could be enhanced combined with find-sec-bugs (mentioned as Find Security Bugs on the blog itself), which is a tool I was already considering adding to JUnit 5. :)

**Comment by alixwar** [comment]
Find-sec-bugs is actually part of the "FindBugs/SpotBugs"-plugin in SonarQube: https://github.com/SonarQubeCommunity/sonar-findbugs

> ...uses SpotBugs, fb-contrib and Find Security Bugs to provide coding rules.

It seems as though this plugin is gradually becoming obsolete though (here they have tracked their conversion process): http://dist.sonarsource.com/reports/coverage/findbugs.html

**Comment by alixwar** [comment]
@jbduncan  @sormuras  This add-on might save some time for reviewing pull requests: https://docs.sonarqube.org/display/PLUG/GitHub+Plugin

**Comment by sormuras** [comment]
Indeed. Looks nice and clean.

**Comment by smoyer64** [comment]
Related to #358.

**Comment by pauldingemans** [comment]
In [https://github.com/junit-team/junit5/pull/1008](pull request 1008) an implementation of SonarQube was set up. Finally the team decided not to merge it to master. Does it also mean that this issue should be closed or should it be kept open waiting for an alternative?

**Comment by sbrannen** [comment]
> Does it also mean that this issue should be closed or should it be kept open waiting for an alternative?

This issue will remain open for the time being. The JUnit 5 team is open to alternative solutions but primarily for simple solutions that provide real value to the team. The terms "simple" and "real" are of course left to interpretation by the team itself.

**Comment by jbduncan** [comment]
I'm happy to close this issue, actually. I've learned since opening it that a judicious use of static analysis tools is the best kind of use.

I still quite like error-prone though. ;)

And if SonarQube is ever deemed useful in the future, a new issue could easily be opened there and then.
