### ISSUE TITLE
Restrict allowed characters in tags

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#956]
## Overview

Although tags are currently _trimmed_ (see #942), they are otherwise allowed to contain any type of character. However, this makes it more difficult to reason about a tag expression language as proposed in #927 and can lead to subtle configuration errors.

## Related Issues

- #927 
- #942 

## Deliverables

- [x] Disallow [whitespace](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isWhitespace-int-) and [control characters](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isISOControl-int-) within tags, after trimming.

**Comment by sormuras** [comment]
For quick look up:
- [Character.isWhitespace(int)](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isWhitespace-int-)
- [Character.isISOControl(int)](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isISOControl-int-)

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Resolved in commit 430f2f647d4cc2f4cbe37bd2d68be51c2c370614.
