### ISSUE TITLE
Detect annotations on overridden super type methods

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#960]
## Overview

In JUnit 4, if `@Test` is declared on an `abstract` method in a superclass, then any concrete implementation of the method is not required to redeclare the `@Test` annotation. However, JUnit Jupiter currently does not support _implicitly inherited_ annotations on overridden methods.

This is an unintentional difference between JUnit 4 and JUnit Jupiter.

## Related Discussions

- https://stackoverflow.com/questions/45162254/why-do-junit-5-tests-not-inherit-test-annotation-from-abstract-classes 
- https://github.com/junit-team/junit4/issues/695
- https://github.com/junit-team/junit4/issues/468
- https://github.com/stefanbirkner/junit/commit/26077526b792168ce80cf16d52b5fbcaf17e8c42

## Deliverables

- [ ] Tweak internal annotation utilities to find _implicitly inherited_ annotations on overridden methods.
- [ ] Tweak internal annotation utilities to find _implicitly inherited_ repeated annotations on overridden methods.

**Comment by sbrannen** [comment]
FYI: I have updated the title and description.

**Comment by sbrannen** [comment]
## Works in JUnit 4

```java
public abstract class AbstractTests {

	@org.junit.Test
	public abstract void test();
}
```

```java
public class FooTests extends AbstractTests {

	@Override
	// @Test
	public void test() {
	}
}
```

**Comment by sbrannen** [comment]
## Does not work in JUnit Jupiter 5.0 M5

```java
public abstract class AbstractTests {

	@org.junit.jupiter.api.Test
	public abstract void test();
}
```

```java
public class FooTests extends AbstractTests {

	@Override
	// @Test
	public void test() {
	}
}
```

**Comment by sormuras** [comment]
## Does not work in JUnit Jupiter 5.0 M5

```java
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

interface InterfaceTests {

	@BeforeEach
	void before();

	@Test
	void test();

}
```

```java
public class BarTests implements InterfaceTests {

	@Override
	// @BeforeEach
	public void before() {
		System.err.println("before");
	}

	@Override
	// @Test
	public void test() {
		System.err.println("test");
	}

}
```

**Comment by sbrannen** [comment]
My preliminary analysis of this _functionality_ in JUnit 4 leads me to believe that the behavior is perhaps accidental, especially in light of explicit documentation within JUnit 4's `BlockJUnit4ClassRunner` such as the following.

```java
    /**
     * Returns the methods that run tests. Default implementation returns all
     * methods annotated with {@code @Test} on this class and superclasses that
     * are not overridden.
     */
    protected List<FrameworkMethod> computeTestMethods() {
        return getTestClass().getAnnotatedMethods(Test.class);
    }
```

A round of debugging led me to the fact that the following is actually what JUnit 4 tracks as the "test method" in such cases.

```[public void org.junit.platform.AbstractTests.test()]```

In summary: it appears that JUnit 4 in fact does not have any special reflective code in place to support "implicit inheritance" of annotations of methods. Rather, it only works coincidentally since JUnit 4 erroneously (?) tracks annotated abstract methods. If a concrete method (that overrides an annotated abstract method) is not annotated, it simply gets ignored since it is in fact "not a test method". Then the _execution_ of the abstract method just happens to work by chance (?) since the methods have the same name.

In light of these findings, I am removing the "bug" label, adding the "team discussion" label, and moving this issue to 5.0 RC1.

**Comment by sbrannen** [comment]
Added _Platform_ label since such a change will (adversely?) affect any lookups for annotations on methods across all use cases.

**Comment by marcphilipp** [comment]
We also need to consider cases where the subclass adds an annotation, e.g.

```java
public class BaseTests {
	@Test
	public void test() {/*...*/}
}
```

```java
public class SubTests extends BaseTests {
	@Override
	@Disabled
	public void test() {/*...*/}
}
```

This would be equivalent to:

```java
public class SubTests {
	@Test
	@Disabled
	public void test() {/*...*/}
}
```

This becomes even more interesting, if the subclass declares annotations that the base class declares as well.

```java
public class BaseTests {
	@Test
	@DisplayName("base")
	@Tag("base")
	public void test() {/*...*/}
}
```

```java
public class SubTests extends BaseTests {
	@Override
	@DisplayName("sub")
	@Tag("sub")
	public void test() {/*...*/}
}
```

In this case the display name should be "sub" but it should/could have both tags, so it would be equivalent to:

This would be equivalent to:

```java
public class SubTests {
	@Test
	@DisplayName("sub")
	@Tag("base")
	@Tag("sub")
	public void test() {/*...*/}
}
```

To override a repeatable annotation completely, you could use its container annotation:

```java
public class SubTests extends BaseTests {
	@Override
	@DisplayName("sub")
	@Tags({@Tag("sub")})
	public void test() {/*...*/}
}
```

which would then yield only the tag "sub".

**Comment by sbrannen** [comment]
> We also need to consider cases where the subclass adds an annotation, e.g.

Yep, that opens up a whole new can of worms.

Not so sure that I'm a fan of this approach unless we keep it _super simple_.

**Comment by sbrannen** [comment]
Added additional links to the _Related Discussions_ section thanks to a few tips from @marcphilipp.

**Comment by elonderin** [comment]
what is the recommended migration for these kind of tests from junit4 when testing the behavior of different implementations?

Parameterization is out of the question b/c the implementation needs to be instantiated based on the common setup/member vars in `@BeforeAll` as well as custom setup in each test (passed as an argument to `runImpl()`  where the instantiation happens as well as the execution of the method under test).

I tried using _Test Interfaces_ but for simple cases this is quite bothersome b/c all my custom asserts must move there as well and i still need an abstract class for the member vars which need a getter in the interface.

**Comment by remal** [comment]
@marcphilipp are there any plans to implement it?

**Comment by marcphilipp** [comment]
@remal No, it's currently not planned to be implemented. What's your concrete use case?

**Comment by remal** [comment]
@marcphilipp the use case is quite simple: I have several implementations of an interface and I'd like to use a base abstract test class (with abstract methods annotated with `@Test`) as a contract (concrete tests should test at least listed scenarios).

**Comment by rpost** [comment]
> > We also need to consider cases where the subclass adds an annotation, e.g.
> 
> Yep, that opens up a whole new can of worms.
> 
> Not so sure that I'm a fan of this approach unless we keep it _super simple_.

Imo silently skipping overridden annotated method is the worst solution. It should be either checked for such case and rejected with clear error message or supported as in junit4 (the latter is my personal preference: `@BeforeEach methods are inherited from superclasses as long as they are not overridden.` - this behaviour is very surprising).

**Comment by marcphilipp** [comment]
**Team decision:** Keep the current behavior to avoid a breaking change and considerable added complexity.

**Comment by mjustin** [comment]
Is this behavior documented somewhere (and should it be)?

**Comment by marcphilipp** [comment]
Yes, it's documented on all method-level annotations, e.g.

> `@BeforeEach` methods are inherited from superclasses as long as they are not overridden.
