### ISSUE TITLE
Default display name for test class is generated differently for Vintage and Jupiter

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#970]
Jupiter's `ClassTestDescriptor` provides short class name as display names; whereas, Vintage's `RunnerTestDescriptor` provides fully qualified class names.

Is there any rationale behind this?

Looks suspicious in the UI,  and I hesitate if I should explicitly change the display names so they look pretty. 

Screenshot of current IDEA version with mixed Vintage/Jupiter tests:
![image](https://user-images.githubusercontent.com/4306070/28464282-c06702be-6e24-11e7-933a-2d20b0f1a47b.png)

**Comment by marcphilipp** [comment]
The only rationale is backwards compatibility, i.e. use the display name provided in `Description` for Vintage. We could add a special-case for Vintage `Description` instances where display name equals the FQCN of the test class.

@junit-team/junit-lambda Thoughts?

**Comment by marcphilipp** [comment]
@akozlova Is this issue still relevant for you?

**Comment by akozlova** [comment]
Yes, I have corresponding issue. I separated tests by different engines now, so it is not that bad as on the screenshot.

**Comment by sbrannen** [comment]
> We could add a special-case for Vintage `Description` instances where display name equals the FQCN of the test class (and use the simple name of the test class as display name).

I think that would be reasonable as long as we don't mess with the actual technical name.

**Comment by jaredholdcroft** [comment]
Hi. Is it ok if I take a look at this? I'm keen to make a contribution to the project and this looks like a good place to start.

**Comment by marcphilipp** [comment]
@jaredholdcroft Sure, go ahead!

**Comment by Andrei94** [comment]
Is this issue still open?

**Comment by marcphilipp** [comment]
Please do!

**Comment by sbrannen** [comment]
Assigned to @Andrei94 due to ongoing work in #1475.

**Comment by sbrannen** [comment]
... except that... well... I apparently cannot actually assign it to @Andrei94.

Weird.

**Comment by Andrei94** [comment]
Perhaps because assignment only works for members? 🤔

**Comment by sbrannen** [comment]
No... the menu suggests @akozlova and @geo-m as options for an assignee, and they are not members of this repository. Of course, @akozlova created this issue, but @geo-m is not even involved in this issue AFAICT.

And I can't manually add anyone.

That's why I find it odd.

**Comment by sbrannen** [comment]
This has been addressed in c6ce0138668d1ef4d67df5073962b4f1d708809f.
