### ISSUE TITLE
Consider breaking down Gradle build into sub-scripts for maintainability

### ISSUE THREAD

**Issue by jbduncan** [junit-team/junit5#972]
## Overview

As I'm working on https://github.com/junit-team/junit5/pull/961, I've come to realise that the `build.gradle` file could be organised better, as I'm currently having to jump about and edit disparate lines in the file just to import error-prone and get it working properly on both JDK 8 and JDK 9.

Consider organising the Gradle build in a similar fashion to [Caffeine](https://github.com/ben-manes/caffeine)'s, where dependencies, code quality tools, publishing functions etc. are extracted into their own `gradle/*.gradle` sub-scripts, which are then imported into the project's other `.gradle` files as needed.

## Deliverables

- [ ] ` build.gradle` is broken down into sub-scripts as appropriate.

**Comment by jbduncan** [comment]
I'm glad to see that commit https://github.com/junit-team/junit5/commit/ef526644a5d1d27536096c2f0b8c5d2df247fc92 partially resolves this issue by splitting out the dependency versions into their own source file. :)

**Comment by marcphilipp** [comment]
Yeah, that's true. The root buildscript is still too big. My current plan is to extract parts (JAR manifest entries, publishing to GH Pages) into plugins in `buildSrc` and eventually standalone plugins so we can reuse them in the opentest4j and apiguardian projects. I think we should revisit the buildscript afterwards and decide which parts would benefit from being extracted.

**Comment by marcphilipp** [comment]
The root build script still isn't perfect but has a reasonable size now. Thus, I'm closing this issue as resolved.
