### ISSUE TITLE
Document behavior of "hidden" static methods

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#982]
## JUnit 4 Behavior

```java
public class A {

	@org.junit.BeforeClass
	public static void beforeClass() {
		System.out.println("A");
	}

	@org.junit.Test
	public void a() {
		System.out.println("a()");
	}
}
```

```java
public class B extends A {

	@org.junit.BeforeClass
	public static void beforeClass() {
		System.out.println("B");
	}

	@org.junit.Test
	public void b() {
		System.out.println("b()");
	}
}
```

Executing test class `B` with JUnit 4 results in the following:

```
B
b()
a()
```

## JUnit Jupiter Behavior

```java
class A {

	@BeforeAll
	static void beforeAll() {
		System.out.println("A");
	}

	@Test
	void a() {
		System.out.println("a()");
	}
}
```

```java
class B extends A {

	@BeforeAll
	static void beforeAll() {
		System.out.println("B");
	}

	@Test
	void b() {
		System.out.println("b()");
	}
}
```

Executing test class `B` with JUnit Jupiter results in the following:

```
B
a()
b()
```

## Deliverables

- [x] Write unit tests in `ReflectionUtilsTests` that verifies the current behavior within the Platform.
- [x] Write an integration test in `junit-jupiter-engine` that verifies the current behavior within Jupiter.
- [ ] Document the current behavior in the User Guide.
- [ ] Document the current behavior in `ReflectionSupport`.

**Comment by sbrannen** [comment]
I revised the example scenario with a real JUnit Jupiter test and the observed output.

**Comment by sbrannen** [comment]
Added example with JUnit 4.

**Comment by sbrannen** [comment]
Surprisingly, JUnit 4 executes test methods in subclasses **before** test methods in superclasses.

@junit-team/junit-lambda Were you all aware of this difference?

**Comment by sbrannen** [comment]
On a positive note, there is no difference with regard to _hidden_ static methods between JUnit 4 and JUnit Jupiter.

**Comment by sbrannen** [comment]
Added additional _Deliverables_.

**Comment by sbrannen** [comment]
_in progress_

**Comment by smoyer64** [comment]
If the static ```@BeforeClass``` methods are named ```beforeClassA()``` and ```beforeClassB()``` do JUnit 4 and JUnit Jupiter both execute the static methods in the same order?  Right now the method ```beforeClass()``` overrides the method with the same name in class A so these tests don't completely expose the static ordering.  The javadocs for both the ```getDeclaredMethods()``` and ```getMethods()``` calls state:

>   The elements in the returned array are not sorted and are not in any particular order.

The ordering in JUnit 4 is due to the framework's code recursively discovering super-classes (see https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/TestClass.java), so the ordering of the individual methods within a class won't be consistent but the groups of methods will always start with the child class and proceed to super-classes.

I'm a bit surprised that ```a()``` didn't run twice in your JUnit 4 test - I vaguely remember that you have to add the ```abstract``` modifier to the parent class if it contains tests that should only be inherited by children.

**Comment by sbrannen** [comment]
> I'm a bit surprised that a() didn't run twice in your JUnit 4 test - I vaguely remember that you have to add the abstract modifier to the parent class if it contains tests that should only be inherited by children.

Not sure I follow you there: I only executed class `B`, so why would there ever be two executions of `a()`?

**Comment by sbrannen** [comment]
> The ordering in JUnit 4 is due to the framework's code recursively discovering super-classes (see https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/TestClass.java), so the ordering of the individual methods within a class won't be consistent but the groups of methods will always start with the child class and proceed to super-classes.

The JUnit Platform also has extensive reflection utilities in `ReflectionUtils` that traverse the type hierarchy using top-down or bottom-up semantics depending on the use case.

**Comment by smoyer64** [comment]
@sbrannen - Somehow I missed that only B was executed ... sorry!

**Comment by sbrannen** [comment]
Regarding "The ordering in JUnit 4", I am aware of JUnit 4's reflective support in that regard... except that I always thought JUnit 4 executed tests using top-down semantics.

**Comment by sbrannen** [comment]
> Right now the method beforeClass() overrides the method with the same name in class A so these tests don't completely expose the static ordering.

Let's make sure we are using the correct terminology here (related to the JLS): a static method _hides_ another static method; whereas, an instance method _overrides_ another instance method (or default method).

**Comment by sbrannen** [comment]
Regarding the "static ordering", it was not my intention to address that in this issue.

JUnit Jupiter clearly supports top-down ordering for _before_ callbacks and bottom-up ordering for _after_ callbacks.

**Comment by sbrannen** [comment]
FYI: `BeforeAndAfterAllTests` verifies the expected ordering of static callback methods.

**Comment by sbrannen** [comment]
> so the ordering of the individual methods within a class won't be consistent

BTW, that's actually not true.

Since JUnit 4.7 the ordering of methods is always "stable" across launches of the JVM. In other words, it's deterministic even if you don't know the algorithm used. 😉 

And the JUnit Platform just adopted the same approach in #934.

**Comment by sbrannen** [comment]
> If the static @BeforeClass methods are named beforeClassA() and beforeClassB() do JUnit 4 and JUnit Jupiter both execute the static methods in the same order?

Dunno... but it wouldn't be too difficult to check. 😉

**Comment by smoyer64** [comment]
Wow ... I saw #934 but somehow missed that JUnit 4 had already adopted that same consistency (even digging through the code looking for that functionality).  We had also tested that the outside-in (pre) and inside-out (post) set-up was performed in the expected order when preparing our presentation for J1 last year - I think you've got it all covered!

**Comment by sbrannen** [comment]
OK... I checked.

> If the static ```@BeforeClass``` methods are named ```beforeClassA()``` and ```beforeClassB()``` do JUnit 4 and JUnit Jupiter both execute the static methods in the same order?

Yes, they do.

### JUnit 4

```
A
B
b()
a()
```

### JUnit Jupiter

```
A
B
a()
b()
```

**Comment by smoyer64** [comment]
And you're correct - I should use hidden instead of overridden in this context (changed for posterity).

**Comment by sbrannen** [comment]
So, JUnit 4 is inconsistent here.

JUnit 4 executes _before class_ methods with top-down semantics, but it executes actual test methods with bottom-up semantics, which IMHO is completely senseless.

**Comment by smoyer64** [comment]
>   which IMHO is completely senseless

I agree - I like the top-down semantics and it will be easier to document them if it's top-down in all cases.

Thinking over my general use-case for test super-classes - If they contain tests, those tests will usually be the earliest indication that something is broken and there is implicit information provided by whether the method fails in just one sub-class versus failing in all the sub-classes.

**Comment by sbrannen** [comment]
Update: tests for the status quo are in place (82b91d7dc04f90f6dbe33e5da025912c54d0d445).

**Comment by sbrannen** [comment]
Update: improved documentation in commit 86e21702dc1e742b7ca2c2de21c27f9badb3aa1e.

Closing this issue.
