### ISSUE TITLE
Allow @MethodSource methods to be non-static

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#984]
## Overview

`@MethodSource` methods are currently required to always be `static`; however, if a test class is annotated with `@TestInstance(Lifecycle.PER_CLASS)` it is conceivable that a test author would like for his or her `@MethodSource` methods to be non-static.

## Deliverables

- [x] Allow `@MethodSource` methods to be non-static -- by executing the method against the `testInstance` (or `null`) from the current `ExtensionContext` in `MethodArgumentsProvider.provideArguments()`

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Addressed in commit a52e33101af6c1ef8b55345891f2e96995348fe3.

**Comment by mih-kopylov** [comment]
@sbrannen sorry, is there any chance to have this feature implemented in JUnit5?

**Comment by sbrannen** [comment]
@mih-kopylov, this feature has existed in JUnit Jupiter (JUnit 5) since the original GA release.

> Addressed in commit a52e331.
