### ISSUE TITLE
Accessibility: Customizing colours for people with disabilities

### ISSUE THREAD

**Issue by AJNeufeld** [junit-team/junit5#985]
## Overview

**Feature request.** 

Console tasks are flagged with various statuses, such as `SUCCESSFUL` and `FAILED`.  These are mapped (as of #930, as `final` constants) to `GREEN` and `RED`.
These may seem like reasonable choices, until you encounter people who are red-green colour blind, or completely colour blind, who may be unable to distinguish between success and failure cases at a glance, unlike the fully sighted.
Worse, they may find it hard to read the text as high-contract text (green-on-black) is for them low-contrast dark-grey-on-black.

## Deliverables

JUnit5 should allow the user to customize the `Color.ansiString` that is associated with the various status values.  At a minimum, this should allow customize the status colour, but could include:
- [ ] a ANSI text attribute, such as `underline`, `bold` or `italic`.
- [ ] reverse video
- [ ] (forgive me) blink

This applies only to console output.
An IDE will apply its own colour/style to the various test statuses.

**Comment by jbduncan** [comment]
@AJNeufeld The JUnit team may be more knowledgeable than I am on the topic of colour-blindness, but my own knowledge is rather limited, so I'm ashamed to say that I don't know what you mean by "reverse video" and "blink" in this context.

Could you elaborate further for me?

**Comment by sormuras** [comment]
@jbduncan See http://ascii-table.com/ansi-escape-sequences.php at

**`Esc[Value;...;Valuem`** | **Set Graphics Mode**

Calls the graphics functions specified by the following values. These specified functions remain active until the next occurrence of this escape sequence. Graphics mode changes the colors and attributes of text (such as bold and underline) displayed on the screen.

```
...
5 | Blink on
7 | Reverse video on
...
```

![](https://lh3.googleusercontent.com/-tHYQfbLsV6k/VjAfC-HEGkI/AAAAAAAAIHk/0hI9BlGkq68/s800-Ic42/ansi.colortable.gif)

**Comment by smoyer64** [comment]
Hmm ... there are a couple of accessibility problems beyond color-blindness for a lot of those combinations.  For people like me (older eyes that have been staring at a monitor for 35+ years), the lack of contrast is a serious problem.  I'll link to a tool that provides ratings for contrast if I can remember where I saved it.

(Also **ouch** - some of those color combinations are borderline offensive.  I lived through the DOS days with ANSI colors on a VGA monitor and don't really miss them!)

**Comment by jbduncan** [comment]
Thank you @sormuras!

Do you have an example for "reverse video" as well? I admit it's not clear to me yet what that ANSI escape sequence does to text that it's applied to.

**Comment by sormuras** [comment]
> Do you have an example for "reverse video" as well?

Look at the top right of the gif.

**Comment by b0n541** [comment]
I would try to take on this issue.

I'm currently not sure about the requirements and the implementation approach:

1. Should each test status be configurable independently or shall there be one option for formatting all test statuses in bold, underline or italic?
2. Should the new option be added to the command line options listed here: https://github.com/junit-team/junit5/blob/main/junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java

**Comment by marcphilipp** [comment]
I think we should make this user configurable, e.g via a properties file that can be specified via a new `--color-theme` cli arg.

`junit-console-color-theme.properties`
```
successful=1;32
failed=1;5;9;30;41
```

@AJNeufeld Would that work for you or would it be more convenient if we read the theme from an environment variable?

**Comment by AJNeufeld** [comment]
Thank you, very much!
