### ISSUE TITLE
maven-surefire-plugins's setting "redirectTestOutputToFile" is being ignored

### ISSUE THREAD

**Issue by piotrkrokowski** [junit-team/junit5#986]
Given the following plugin definition:

```xml
<plugin>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>2.19.1</version>
   <configuration>
      <redirectTestOutputToFile>true</redirectTestOutputToFile>
   </configuration>
   <dependencies>
      <dependency>
         <groupId>org.junit.platform</groupId>
         <artifactId>junit-platform-surefire-provider</artifactId>
         <version>1.0.0-M6</version>
      </dependency>
      <dependency>
         <groupId>org.junit.vintage</groupId>
         <artifactId>junit-vintage-engine</artifactId>
         <version>4.12.0-M6</version>
      </dependency>
      <dependency>
         <groupId>org.junit.jupiter</groupId>
         <artifactId>junit-jupiter-engine</artifactId>
         <version>5.0.0-M6</version>
      </dependency>
   </dependencies>
</plugin>
```

and tests, that produce console output with `System.out.println()`, Test's console output is being written out on the actual console, while it is expected to be redirected to surefire's files, as it happened before adding `junit-vintage-engine` and `junit-platform-surefire-provider` to dependencies.

This issue is severe, because the project I'm working on heavily depends on the fact that tests output is suppressed (without it, it produces hundreds of megabytes of logs, ruining the performance and blocking storage capacity).

**Comment by smoyer64** [comment]
I've worked on the Surefire provider a little bit and I'm not surprised that the executor doesn't redirect the output.  I've been working on a JUnit 5 extension that allows you to control the console but I think what's needed here is for the provider itself to redirect System.out.  Fortunately the test results themselves are recorded via the ```RunListener``` (see https://github.com/junit-team/junit5/blob/master/junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java#L107).

I'm not sure that the JUnit 5 team is interested in making this code a full-fledged ```Provider``` but I'd be happy to add this feature to the plugin if it's deemed worthwhile.  I'm also a bit surprised that the ```AbstractProvider``` that is extended by that code doesn't take care of the output redirection.

**Comment by piotrkrokowski** [comment]
I'd appreciate such contribution ;)

**Comment by sbrannen** [comment]
I've assigned this to the general backlog and put it "up for grabs".

**Comment by blairnangle** [comment]
Is this issue still free to be worked on?

**Comment by marcphilipp** [comment]
@smoyer64 Is it?

**Comment by smoyer64** [comment]
@marcphilipp - I haven't started working on it yet so I'd say "yes".

**Comment by kaustubhmallik** [comment]
Hey guys, has somebody picked it up yet?

**Comment by sbrannen** [comment]
@kaustubhmallik, not to my knowledge.

Feel free to give it a shot and report back here.

**Comment by BogdanStirbat** [comment]
Hi!

For this issue, I added a new [pull request](https://github.com/junit-team/junit5/pull/1073).
