### ISSUE TITLE
Failure during test discovery doesn't cause Maven run failure

### ISSUE THREAD

**Issue by piotrkrokowski** [junit-team/junit5#987]
Given the following plugin definition:

```xml
<plugin>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>2.19.1</version>
   <dependencies>
      <dependency>
         <groupId>org.junit.platform</groupId>
         <artifactId>junit-platform-surefire-provider</artifactId>
         <version>1.0.0-M6</version>
      </dependency>
     <dependency>
         <groupId>org.junit.jupiter</groupId>
         <artifactId>junit-jupiter-engine</artifactId>
         <version>5.0.0-M6</version>
      </dependency>
   </dependencies>
</plugin>
```

and the following (incorrect) test:

```java
public class JUnit5Test {

   @BeforeAll
   void setUp() {
   }

   @Test
   void name() {
      assertTrue(true);
   }
}
```

Running tests with maven `mvn clean test` will cause a Jupiter failure (which is expected, because `@BeforeAll` should be static), but will end up with a successful Maven run (see attached Maven console output).

This behavior is quite dangerous, and might cause someone to oversee tests failure.

[run-success.txt](https://github.com/junit-team/junit5/files/1174674/run-success.txt)

**Comment by smoyer64** [comment]
Great catch!

**Comment by smoyer64** [comment]
A ```MojoFailureException``` should be thrown in this case - see https://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException.

**Comment by sbrannen** [comment]
This should have been fixed in #971.

@piotrkrokowski, can you please try your example against a recent snapshot for RC1?

**Comment by smoyer64** [comment]
To work correctly with the Maven lifecycle, the exceptions thrown on line 86 (https://github.com/junit-team/junit5/blob/master/junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java#L86) may need to be wrapped in the above mentioned ```MojoFailureException```.

**Comment by sbrannen** [comment]
> To work correctly with the Maven lifecycle, the exceptions thrown on line 86 ... may need to be wrapped in the above mentioned MojoFailureException.

Ahhhh. OK. 

Well, I'm not an expert with regard to Surefire plugin development, so I'll have to let somebody else assess that.

On the other hand, if you're certain that's the case, we could repurpose this ticket to address that issue.

**Comment by sbrannen** [comment]
However... the method signature for `org.apache.maven.surefire.providerapi.SurefireProvider.invoke(Object)` explicitly declares those three types as thrown exceptions.

So I would find it rather odd that an implementation is required to _wrap_ them.

**Comment by smoyer64** [comment]
Good point - I'm not an expert on the Surefire provider either but that makes it look like they might be wrapped up by the caller.  There's plenty of code between the Maven plugin executor and that provider.  In any case, I wasn't advocating making any changes until we get the confirmation you asked for.

**Comment by piotrkrokowski** [comment]
@sbrannen RC1? Is it deployed in any public Maven Repository?

**Comment by sbrannen** [comment]
> RC1? Is it deployed in any public Maven Repository?

Nope. It's the current work in `master`, but you can build against snapshots by adding the following repository to your build configuration and changing your versions to `1.0.0-SNAPSHOT` and `5.0.0-SNAPSHOT`.

https://oss.sonatype.org/content/repositories/snapshots/org/junit/

Let us know how it goes!

**Comment by piotrkrokowski** [comment]
I'm not sure what's wrong, but I can't fetch it. It won't resolve junit-jupiter-api for some reason.
Cant you guys just test it, using the snippet I provided?

**Comment by sbrannen** [comment]
Sure. I'll check it.

**Comment by sbrannen** [comment]
Running the sample app against the latest RC1 snapshot, the test run now looks the following:

```-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.example.project.FirstTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.079 sec <<< FAILURE! - in com.example.project.FirstTest
com.example.project.FirstTest  Time elapsed: 0.075 sec  <<< FAILURE!
org.junit.platform.commons.JUnitException: @BeforeAll method 'void com.example.project.FirstTest.setUp()' must be static unless the test class is annotated with @TestInstance(Lifecycle.PER_CLASS).

Running com.example.project.JUnit4Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec - in com.example.project.JUnit4Test
Running com.example.project.OtherTests
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec - in com.example.project.OtherTests
Running com.example.project.SecondTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.026 sec - in com.example.project.SecondTest

Results :

Failed tests:
  FirstTest » JUnit @BeforeAll method 'void com.example.project.FirstTest.setUp(...

Tests run: 5, Failures: 1, Errors: 0, Skipped: 1
```

Thus, the exception is now thrown during the execution phase instead of during the discovery phase, meaning that #971 in fact fixed this.

**Comment by sbrannen** [comment]
I am therefore closing this issue since it effectively duplicates #971.

**Comment by piotrkrokowski** [comment]
Great! Thanks.

**Comment by sbrannen** [comment]
@smoyer64, if you would still like to make any changes to the Surefire provider, please open a new issue.

**Comment by sbrannen** [comment]
@piotrkrokowski, you're welcome.

BTW, if you want to configure your POM to use the snapshots, the following should help:

https://raw.githubusercontent.com/junit-team/junit5-samples/17cf80d17c5126397fc768cf7a31d17beaa7e526/junit5-maven-consumer/pom.xml

**Comment by sbrannen** [comment]
You have to set up `repositories` & `pluginRepositories` and change the versions to `1.0.0-SNAPSHOT` & `5.0.0-SNAPSHOT`.

**Comment by smoyer64** [comment]
@sbrannen - I think I'm going to take on #986 and I'm hoping to get that and #343 done for RC1 but I'm going to work on the documentation I've been promising first.  I should have more personal time now.

**Comment by sbrannen** [comment]
>  I think I'm going to take on #986 and I'm hoping to get that and #343 done for RC1 but I'm going to work on the documentation I've been promising first. I should have more personal time now.

@smoyer64, that sounds good! 👍

**Comment by Dil-a** [comment]
[WARNING] Tests run: 4, Failures: 0, Errors: 0, Skipped: 4
[INFO] 
I am getting this type warning and it is skipping my tests?

**Comment by marcphilipp** [comment]
@Dil-a You'll have to give us a little more than that. Please open a new issue if you suspect this is a bug but I'd suggest asking on StackOverflow first.
