### ISSUE TITLE
Fix Gradle consumption of junit-jupiter-engine

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#997]
## Overview

Consuming the RC1 artifact of junit-jupiter-engine with Gradle fails due to an invalid POM:

```
▶ ./gradlew --refresh-dependencies clean build

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':testRuntimeClasspath'.
> Could not resolve org.junit.jupiter:junit-jupiter-engine:5.0.0-RC1.
  Required by:
      project :
   > Could not resolve org.junit.jupiter:junit-jupiter-engine:5.0.0-RC1.
      > Could not parse POM https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.0.0-RC1/junit-jupiter-engine-5.0.0-RC1.pom
         > Unable to resolve version for dependency 'org.jetbrains.kotlin:kotlin-stdlib-jre8:jar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2s
6 actionable tasks: 6 executed
```

## Deliverables

- [ ] Exclude 'test' scope dependencies from generated POM

**Comment by Ukrainis** [comment]
Hello, 
Having the same issue:

> Resource missing. [HTTP GET: https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.01/junit-jupiter-api-5.01.pom]
> Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.01/junit-jupiter-api-5.01.jar]
> :compileTestJava FAILED

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':testCompileClasspath'.
> > Could not find org.junit.jupiter:junit-jupiter-api:5.01.
>   Searched in the following locations:
>       https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.01/junit-jupiter-api-5.01.pom
>       https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.01/junit-jupiter-api-5.01.jar
>   Required by:
>       project :

Having this problem, when trying to execute build task.
Used components: Junit 5.01, Java 8, Gradle 4.2.1.

**Comment by mkobit** [comment]
I think your version is incorrect - `5.0.1` instead of `5.01`

**Comment by Ukrainis** [comment]
My gradle.build file:
group 'com.selenium.tests'
version '1.0-SNAPSHOT'

ext.junitJupiterVersion     **= '5.01'**
ext.seleniumVersion         = '3.6.0'
ext.log4jVersion            = '2.9.0'
ext.junitPlatformVersion    = '1.0.1'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.1'
    }
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.junit.platform.gradle.plugin'

compileTestJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    options.compilerArgs += '-parameters'
}

repositories {
    mavenCentral()
}

junitPlatform {
    // platformVersion '1.0.1'
    filters {
        engines {
            // include 'junit-jupiter', 'junit-vintage'
            // exclude 'custom-engine'
        }
        tags {
            // include 'fast'
            exclude 'slow'
        }
        // includeClassNamePattern '.*Test'
    }
    // configurationParameter 'junit.jupiter.conditions.deactivate', '*'
     enableStandardTestTask true
    // reportsDir file('build/test-results/junit-platform') // this is the default
    logManager 'org.apache.logging.log4j.jul.LogManager'
}

dependencies {
    compile ("org.seleniumhq.selenium:selenium-java:${seleniumVersion}")
    testCompile("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
    testRuntime("org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}")

    // To avoid compiler warnings about @API annotations in JUnit code
    testCompileOnly('org.apiguardian:apiguardian-api:1.0.0')

    // To use Log4J's LogManager
    testRuntime("org.apache.logging.log4j:log4j-core:${log4jVersion}")
    testRuntime("org.apache.logging.log4j:log4j-jul:${log4jVersion}")

    // Only needed to run tests in an (IntelliJ) IDE(A) that bundles an older version
    testRuntime("org.junit.platform:junit-platform-launcher:${junitPlatformVersion}")
}
