### ISSUE TITLE
Extension request

### ISSUE THREAD

**Issue by seventh7me** [junit-team/junit5#999]
Hi,
  Is it possible to add a new extension with which I can determine 'how' a test is executed. 'how' here means that, for example, I can determine which thread my tests should be executed. I just don't want to wrap each test with some skeleton codes (almost the same) to archive that. thanks

**Comment by smoyer64** [comment]
You should be able to write your own extension for that ... and if it's broadly applicable please consider submitting it for inclusion in https://github.com/junit-pioneer/junit-pioneer.

**Comment by marcphilipp** [comment]
Thanks for the request, there's already #157 and #20. Feel free to chime in there. I'm closing this issue as a duplicate.
